### ISSUE TITLE
Errors while saving sale order/quotation lines with taxes assigned

### ISSUE THREAD

**Issue by Waniliowy** [odoo/odoo#10055]
There seems to be a problem with a change made in commit 7e2628aeb2d525d00f457fe979c34860f13db727 - tested on fresh install with only sales module installed. While trying to save quotation/sale order with lines that have modified taxes field (or new lines with automatically assigned taxes), there are multiple odoo server errors - TypeError: unhashable type: 'list'. The issue probably exists everywhere where m2m tags fields are used in list views. Rolling back to previous commit fixes the issue.

Steps to reproduce:
- fresh install with sale module only
- create test product
- create new quotation with that product with some taxes assigned (create new one or use some existing accounting module, tested with i10n_pl)
- while trying to save there are multiple error popups, but the changes seems to be saved

All errors looks the same:
```
Traceback (most recent call last):
  File "/path/to/odoo/openerp/http.py", line 605, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/path/to/odoo/openerp/http.py", line 642, in dispatch
    result = self._call_function(**self.params)
  File "/path/to/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/path/to/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/path/to/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/path/to/odoo/openerp/http.py", line 893, in __call__
    return self.method(*args, **kw)
  File "/path/to/odoo/openerp/http.py", line 471, in response_wrap
    response = f(*args, **kw)
  File "/path/to/odoo/addons/web/controllers/main.py", line 994, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/path/to/odoo/addons/web/controllers/main.py", line 986, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/path/to/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/path/to/odoo/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/path/to/odoo/openerp/models.py", line 5985, in onchange
    record = self.new(values)
  File "/path/to/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/path/to/odoo/openerp/models.py", line 5555, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/path/to/odoo/openerp/models.py", line 5450, in _convert_to_cache
    for name, value in values.iteritems()
  File "/path/to/odoo/openerp/models.py", line 5451, in <dictcomp>
    if name in fields
  File "/path/to/odoo/openerp/fields.py", line 1743, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/path/to/odoo/openerp/tools/misc.py", line 1106, in __init__
    super(OrderedSet, self).__init__([(x, None) for x in seq])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/path/to/python/virtual/env/bin/../lib/python2.7/_abcoll.py", line 567, in update
    self[key] = value
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 58, in __setitem__
    if key not in self:
TypeError: unhashable type: 'list'
```

Tested on OSX 10.10.5 with Safari 9.0.1 and Firefox 42.0

**Comment by gurneyalex** [comment]
same as #10083 #10069

**Comment by odony** [comment]
Thanks for reporting and identifying the root cause: commit 7e2628aeb2d525d00f457fe979c34860f13db727!
We have reverted this commit at rev. b4949f757cfdf4efd89ec645cb31664e085657dc because it produces invalid `x2many` serialized commands, such as:
   `[[6, false, [[5, false, false], [6, false, [8]]]]]`

This is what causes the error and tracebacks.

@Gorash will look into fixing this properly to address the original issue 7e2628aeb2d525d00f457fe979c34860f13db727 was trying to address.

**Comment by gurneyalex** [comment]
@odony thanks for the quick handling of this issue.
