### ISSUE TITLE
cannot marshal <class 'odoo.api.account.partial.reconcile'> objects (xmlrpc)

### ISSUE THREAD

**Issue by EduardoVa** [odoo/odoo#100930]
i'm trying to create a credit note through the xmlrpc API, the credit note is created successfully, but when i try to attach to the account move, it fails.

Impacted versions: 15.0

Steps to reproduce:

using xmlrpc-client (java) and trying to call the 'js_assign_outstanding_line' method:

```java
var finalResp = modelService.executeAction(
    "account.move",
    "js_assign_outstanding_line",
    List.of(moveId, (Integer) lineId[0])
);
```

equivalent to:
```python
models.execute_kw(db, uid, password, 'account.move', 'js_assign_outstanding_line', [move_id, line_id])
```

Current behavior:  throws the next error:

```python
2022-09-22 16:46:58.396 ERROR m.c.p.o.services.impl.RpcOdooClient 82 - ERROR: Traceback (most recent call last):
  File "/usr/lib/python3.8/xmlrpc/client.py", line 509, in __dump
    f = self.dispatch[type(value)]
KeyError: <class 'odoo.api.account.partial.reconcile'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 93, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 74, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 968, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 594, in dump_struct
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 513, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.api.account.partial.reconcile'> objects
```

The https://stackoverflow.com/a/73176567 answer explains that the "reconcile" function is the cause of the problem (https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_move.py#L5351).

Expected behavior:
Same as the web interface (or return True)

**Comment by gdgellatly** [comment]
Just use JSONRpc, save yourself headaches and it is faster. Odoo isn't going to update every function that returns None.

**Comment by EduardoVa** [comment]
> 

@gdgellatly , 

with your answer and exploring on https://www.odoo.com/documentation/15.0/es/developer/howtos/web_services.html?highlight=jsonrpc#json-rpc-library
effectively i can resolve with a simple request:

Url request: `https://odoo-domain/jsonrpc`
Body:
```js
{
    "jsonrpc": "2.0",
    "id": randomNumber(),
    "method": "call",
    "params": {
        "service": "object",
        "method": "execute",
        "args": [
            DB,
            UID,
            SECRET_KEY,
            "account.move",
            "js_assign_outstanding_line",
            [ moveId ],
            [ lineId ]
        ]
    }
}
```

Thank you
