### ISSUE TITLE
[9.0] Accounting module not accessible when switched to german translation

### ISSUE THREAD

**Issue by darenkster** [odoo/odoo#10163]
Impacted Version:

  -9.0 CE & EE

Steps to reproduce:
1. Load the german translation of odoo from Settings/Translations/Load a Translation
2. Switch to german in the user settings
3. Click on 'Finanzen' in the Header-menu

Current behaviour:
Exception is thrown:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/models.py", line 1536, in fields_view_get
    root_view = View.read_combined(cr, uid, view_id, fields=['id', 'name', 'field_parent', 'type', 'model', 'arch'], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/121068-9-0-8595bc/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
    view_arch = etree.fromstring(view['arch'].encode('utf-8'))
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
XMLSyntaxError: xmlParseEntityRef: no name, line 111, column 64

Expected behaviour:
Open Accounting Module

**Comment by joenazz** [comment]
have exactly the same issue. maybe any translation file has got a syntax error like in https://github.com/odoo/odoo/issues/9276 ?
do not really know to debug this.

odoo version 9.0c.20151225 on ubuntu 14.01

**Comment by eneldoserrata** [comment]
you have to look into your 
odoo/addons/account/i18n/de.po

Lines 481, 488, 595, 698
change </ strong> to </strong>

but you have to fix on transifex yo fix the issue

**Comment by darenkster** [comment]
@eneldoserrata i have fixed the term you mentioned in transifex. unfortunately, i am unable to test if your suggestion works right now because i am away from home

**Comment by waveeagle** [comment]
I have the same issue here with the german language. Could you please give advice how to fix this in transifex. I have no experience with transifex yet.

Thanks in advance

**Comment by darenkster** [comment]
The problem seems to be fixed, i have checked this on runbot and locally (In Settings the Translation needs to be reloaded with the option 'Overwrite Existing Terms' checked). 
Issue can be closed.
