### ISSUE TITLE
Exception: Type de rapport inconnu : "webkit"

### ISSUE THREAD

**Issue by rihene** [odoo/odoo#10161]
Hello everybody!!!!!
Please, i have implemented the report_webkit on odoo9.
But, when i clicked on "PRINT" i have got this error:
2015-12-21 11:31:24,342 9320 ERROR ODOO openerp.service.report: Exception: Type de rapport inconnu : "webkit"
Traceback (most recent call last):
  File "/opt/odoo/openerp/service/report.py", line 95, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/odoo/openerp/report/__init__.py", line 22, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_actions.py", line 197, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/odoo/openerp/report/report_sxw.py", line 370, in create
    raise NotImplementedError(_('Unknown report type: %s') % report_type)
NotImplementedError: Type de rapport inconnu : "webkit"

Can anyone help me please.
Thanks a lot in advance.
Best Regards.

**Comment by rihene** [comment]
Can anyone help please :/
