### ISSUE TITLE
Validating Incoming Shipment with 10,000+ lines gets error

### ISSUE THREAD

**Issue by burhanghee** [odoo/odoo#101838]
Impacted versions:16

Steps to reproduce: Created a PO having 10,000+ lines, confirmed and then validated the incoming shipment.

Current behavior: getting below error
2022-10-01 20:34:59,777 10656 ERROR odoo16in odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "E:\Development\odoo16\odoo\http.py", line 1936, in __call__
    response = request._serve_db()
  File "E:\Development\odoo16\odoo\http.py", line 1519, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "E:\Development\odoo16\odoo\service\model.py", line 134, in retrying
    result = func()
  File "E:\Development\odoo16\odoo\http.py", line 1548, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "E:\Development\odoo16\odoo\http.py", line 1745, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "e:\development\odoo16\addons\website\models\ir_http.py", line 221, in _dispatch
    response = super()._dispatch(endpoint)
  File "E:\Development\odoo16\odoo\addons\base\models\ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "E:\Development\odoo16\odoo\http.py", line 673, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "e:\development\odoo16\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "e:\development\odoo16\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\Development\odoo16\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "E:\Development\odoo16\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "e:\development\odoo16\addons\stock\models\stock_picking.py", line 1039, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "e:\development\odoo16\addons\sale_stock\models\stock.py", line 84, in _action_done
    res = super()._action_done()
  File "e:\development\odoo16\addons\stock\models\stock_picking.py", line 883, in _action_done
    done_incoming_moves._trigger_assign()
  File "e:\development\odoo16\addons\stock\models\stock_move.py", line 2007, in _trigger_assign
    moves_to_reserve = self.env['stock.move'].search(expression.AND([static_domain, expression.OR(domains)]),
  File "E:\Development\odoo16\odoo\models.py", line 2016, in search
    return res if count else self.browse(res)
  File "E:\Development\odoo16\odoo\models.py", line 5554, in browse
    if not ids:
  File "E:\Development\odoo16\odoo\tools\query.py", line 217, in __bool__
    return bool(self._result)
  File "E:\Development\odoo16\odoo\tools\func.py", line 28, in __get__
    value = self.fget(obj)
  File "E:\Development\odoo16\odoo\tools\query.py", line 210, in _result
    self._cr.execute(query_str, params)
  File "E:\Development\odoo16\odoo\sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: memory exhausted at or near "("
LINE 1: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((...

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
That is a deployment issue, not enough memory (kind of, the query would be interesting to see, looks like an abomination).

**Comment by burhanghee** [comment]
Thank you for the reply @gdgellatly.
The problem is with the below method:

```
    def _trigger_assign(self):
        """ Check for and trigger action_assign for confirmed/partially_available moves related to done moves.
            Disable auto reservation if user configured to do so.
        """
        if not self or self.env['ir.config_parameter'].sudo().get_param('stock.picking_no_auto_reserve'):
            return

        domains = []
        for move in self:
            domains.append([('product_id', '=', move.product_id.id), ('location_id', '=', move.location_dest_id.id)])
        static_domain = [('state', 'in', ['confirmed', 'partially_available']),
                         ('procure_method', '=', 'make_to_stock'),
                         ('reservation_date', '<=', fields.Date.today())]
        moves_to_reserve = self.env['stock.move'].search(expression.AND([static_domain, expression.OR(domains)]),
                                                         order='reservation_date, priority desc, date asc, id asc')
        moves_to_reserve._action_assign()
```

The ideal code is to either do *moves_to_reserve._action_assign()* one by one (inside for loop) or apply the paging concept so that if there's bulk Picking then it doesn't break.

**Comment by gdgellatly** [comment]
Well it seems a very inefficient domain anyway. Could be reduced to

group by dest location
[(product_id in product_ids),(location_id = dest_location)]

Still not great. Also annoying, it should fields.Date.context_today in that domain.
