### ISSUE TITLE
[9.0] website 500 Internal Error if not logged in

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#10184]
If the website module and you are not logged in you will get the following error in the server log and a 500 Internal Error in the front end.

From what i gathered this is usually a configuration problem. Any pointers are welcome.

```
Traceback (most recent call last):
  File "/opt/odoo/90/odoo/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/90/odoo/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/90/odoo/openerp/http.py", line 743, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/90/odoo/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/90/odoo/openerp/http.py", line 774, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/90/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/90/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/90/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/90/odoo/openerp/http.py", line 893, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/90/odoo/openerp/http.py", line 471, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/90/odoo/addons/website/controllers/main.py", line 44, in index
    return request.registry['ir.http'].reroute(first_menu.url)
  File "/opt/odoo/90/odoo/addons/website/models/ir_http.py", line 209, in reroute
    return self._dispatch()
  File "/opt/odoo/90/odoo/addons/website/models/ir_http.py", line 175, in _dispatch
    key = self.get_page_key()
  File "/opt/odoo/90/odoo/addons/website/models/ir_http.py", line 94, in get_page_key
    return (self._name, "cache", request.uid, request.lang, request.httprequest.full_path)
AttributeError: 'Request' object has no attribute 'full_path'
```

Someone else seems to have the same problem.
http://stackoverflow.com/questions/34202584/error-openerp-addons-website-models-ir-http-500-internal-server-error-after-lo

**Comment by InfernalLV** [comment]
It was as dependency problem.

import pkg_resources
pkg_resources.get_distribution("werkzeug").version
'0.8.3'

solved by 
pip instal werkzeug==0.9.4

**Comment by turkeshmedma** [comment]
This version of werkzeug gives error on opening some website

  ERROR db werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1422, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1396, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1586, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/openerp/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/opt/odoo/openerp/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/openerp/addons/website/models/ir_http.py", line 193, in _dispatch
    resp.set_cookie('website_lang', request.lang)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 1016, in set_cookie
    self.charset))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/http.py", line 943, in dump_cookie
    value = to_bytes(value, charset)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_compat.py", line 112, in to_bytes
    raise TypeError('Expected bytes')
TypeError: Expected bytes

on werkzeug 0.11 also gives same error

**Comment by jl2035** [comment]
@turkeshmedma so true. And again let me guess: nobody has any clue how to fix this error, right? @InfernalLV did you really just install werkzeug 0.9.4 and that was it?

**Comment by christophlsa** [comment]
To avoid such issues you should install the python packages as defined in the requirements.txt file of your odoo version. Odoo 9 requires to install version 0.9.6.

**Comment by InfernalLV** [comment]
@jl2035 I'm currently running 0.9.6 as as said by christophlsa and everything works just fine.

**Comment by jl2035** [comment]
I was still a huge noob at that time. In situations like this you have to run odoo with output (disable log file), to see the errors and fix them. I was really frustrated back then :)

**Comment by satyakishores** [comment]
My odoo is running good but after logged out and again logged in i am getting 500 Internal server error. Other users who are not logged out are using the odoo perfectly. If the user logged out and logged in again then 500 error starts for that user only. please help.

**Comment by aspcsharp9** [comment]
I also have problem...after click on logout on frontend get below error:

```
"Traceback (most recent call last):
  File "/opt/odoo96/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo96/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo96/openerp/http.py", line 738, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo96/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/odoo96/openerp/http.py", line 769, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo96/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo96/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo96/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo96/openerp/http.py", line 888, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo96/openerp/http.py", line 466, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo96/addons/website/controllers/main.py", line 44, in index
    return request.registry['ir.http'].reroute(first_menu.url)
  File "/opt/odoo96/addons/website/models/ir_http.py", line 209, in reroute
    return self._dispatch()
  File "/opt/odoo96/addons/website/models/ir_http.py", line 175, in _dispatch
    key = self.get_page_key()
  File "/opt/odoo96/addons/website/models/ir_http.py", line 94, in get_page_key
    return (self._name, "cache", request.uid, request.lang, request.httprequest.full_path)
AttributeError: 'Request' object has no attribute 'full_path'"
```

**Comment by aspcsharp9** [comment]
On debian vps, 

1. download werkzeug-0.9.4 zip from git
2. Unzip
3. Open terminal and navigate to  cd Downloads
4. Navigate to cd  werkzeug-0.9.4 
5. run this line -->  python setup.py install
6. Restart odoo server
7. Done

Work on my debian....
