### ISSUE TITLE
[9.0] XMLSyntaxError: Opening and ending tag mismatch

### ISSUE THREAD

**Issue by esciara** [odoo/odoo#10190]
On the latest Odoo 9.0 code (ed6a52a5177349d41f2a589596d9ddfc312b8dff), with modules ['website_sale', 'stock', 'account_accountant', 'l10n_fr', 'purchase', 'website_sale_delivery'] installed , the following error shows when clicking on the "Inventory" or "Accounting" tabs when language is set to french/France :
```
Odoo Server Error
Traceback (most recent call last):
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 643, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 680, in dispatch
result = self._call_function(**self.params)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 316, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 309, in checked_call
result = self.endpoint(*a, **kw)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 959, in __call__
return self.method(*args, **kw)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/http.py", line 509, in response_wrap
response = f(*args, **kw)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/addons/web/controllers/main.py", line 892, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/addons/web/controllers/main.py", line 884, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 342, in old_api
result = method(recs, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/addons/web_planner/models/web_planner.py", line 45, in render
return self.env['ir.ui.view'].browse(template_id).render(values=values)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 236, in wrapper
return new_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 562, in new_api
result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/addons/website/models/ir_ui_view.py", line 141, in render
return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in render
return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 252, in render
element = self.get_template(id_or_xml_id, qwebcontext)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 172, in get_template
document = qwebcontext.loader(name)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
return self.read_template(cr, uid, name, context=context)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template
return self._read_template(cr, uid, view_id, context=context)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "<string>", line 2, in _read_template
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/tools/cache.py", line 85, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template
arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/api.py", line 238, in wrapper
return old_api(self, *args, **kwargs)
File "/Users/myname/Documents/Development/git-repos/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
view_arch = etree.fromstring(view['arch'].encode('utf-8'))
File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307)
File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105098)
File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99780)
File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94757)
XMLSyntaxError: Opening and ending tag mismatch: h4 line 645 and br, line 645, column 169
```

**Comment by renatonlima** [comment]
This also happens when change the language to Portuguese.

**Comment by esciara** [comment]
Actually, the problem is not present anymore in f3ef7001cf35da72a6c35d958b3360fc9b2dd26d (last commit of Dec 22, 2015) but is present again in 5e51dc9924c38335570d4a0209e5f2a15f63aca1 ((last commit of Dec 23, 2015). The bug must have been reintroduced somewhere between the two.

ping to the commiters @mart-e @Gorash @dbo-odoo @beledouxdenis @simongoffin  :)

**Comment by beledouxdenis** [comment]
This has probably nothing to do with a recent commit, but this is a problem in one of the translation of a view.

If you send me your database dump, along with the method to reproduce the issue, I will gladly have a look.

**Comment by mart-e** [comment]
Hello,

This was indeed a translation issue, the planners were incorrectly translated. Before edfa2c4732b8351e6c711e487b3e7f14f5bfa691 the translation was not fetch so you didn't had the bug.

@renatonlima I fixed it for French but if you have the same issue in other language, please specify on which menu exactly

**Comment by beledouxdenis** [comment]
@esciara To solve this in your existing databases in French, you will probably have to update your server sources, with the revision mentioned by Martin above, and then load the French language again, while making sure to check the "Overwrite existing terms" box.

You could as well update the given translations manually if you changed manually some translations in your database, and do not want to loose your custom translations.

**Comment by mart-e** [comment]
If you want to search the incorrect terms, in stock you need to change the translation of `Odoo has preconfigured <strong>one Warehouse</strong> for you.` with `Odoo a préconfiguré <strong>un entrepôt</strong> pour vous.` and in account, the `"to describe<br/> your experience or to suggest improvements !"` should be translated `pour décrire <br/> votre expérience ou pour suggérer des améliorations!`

**Comment by esciara** [comment]
Thanks @beledouxdenis , @mart-e !

**Comment by esciara** [comment]
Actually, looking that the origin of the problem : tags were wrong. </br> instead of <br/> in the first case and <strong>un entrepôt</strong> instead of <strong>un entrepôt<strong> in the second.

Would it be a good suggestion that there is a processor automatically validating tags and tag combinations? That translations with invalid tags are not used for translation? Or some preprocessing that rejects erronous modifications made outside the server?

**Comment by mart-e** [comment]
In a dev branch, at 88d1188ee160b79d07e21d48613502571185e90b, I created a test module that tries to built every planner in every language (not going to be merged as slow down quite a bit the runbot).
I fixed something like 27 errors at ef762f43353ff37de911eb2f1c406766e1023b79 but there is still at least [18 remaining](http://runbot.odoo.com/runbot/build/121962).

PR welcome to improve the processing but I am afraid it won't be possible (or highly overkill) to determine if the rendering is failing because of a wrong translation or other reason.
Maybe we can make above test run weekly and report to translators but it still quite manual and requires a good technical understanding.

**Comment by flotho** [comment]
Hi Mart-e, 
I've installed the latest rpm and impossible for me to go to sale menu with french language.
I've search a little bit in translation part but don't find what's going on.
Any tips would be appreciated,
regards

**Comment by mart-e** [comment]
What is the date of your rpm? I just tried on the latest 9.0 [runbot](http://runbot.odoo.com/runbot) and I got no issue in French. The translations are synced every Sunday so if your translation is from this week it should work.
Moreover the rendering of the planner is **not** blocking so even if there is an error, you can discard it and keep working.

Your error is probably different (check the traceback with the one reported) so I would advise you to open a new bug report. Anyway, if the issue is a wrong translation, you should check the translations on Transifex ([translation wiki](https://github.com/odoo/odoo/wiki/Translations)) as we do not manage it from GitHub.

**Comment by flotho** [comment]
Hi @mart-e 

Thanks for your answer.
I'm working with 9.0c_20151229-1 and just made a recent update from an older release odoo_9.0.20151125.noarch.rpm
Do you recommend me to update all modules to be sure of the issue?

regards

**Comment by mart-e** [comment]
Depends what is your issue but if you get a translation error in the planner, reload the translations checking the option "Overwrite Existing Terms"

**Comment by flotho** [comment]
(y) great!

**Comment by flotho** [comment]
BTW, hos is it possible to change in the github a french translation on the french dashboard.
The translation of "un pipe" is not really appropriate for business ;-)

**Comment by mart-e** [comment]
The translation is not done on github, issues should be reported on [Transifex](https://www.transifex.com/odoo/odoo-9) (but I [fixed that one](https://www.transifex.com/odoo/odoo-9/translate/#fr/sales_team/60114853)).

**Comment by renatonlima** [comment]
@mart-e,

There is a problem in brazilian portuguese translation https://github.com/odoo/odoo/blob/9.0/addons/stock/i18n/pt_BR.po#L248 I did fix in Transifex How translations are synchronized?

**Comment by mart-e** [comment]
@renatonlima [When will my translations appear in the software (or in GitHub)?](https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github)

**Comment by Adbrim** [comment]
You haven't closed one of the fields
https://www.odoo.com/forum/help-1/xmlsyntaxerror-opening-and-ending-tag-mismatch-132806
