### ISSUE TITLE
odoo 9 crm phone calls??

### ISSUE THREAD

**Issue by tanerhasret** [odoo/odoo#10248]
Hello everyone,
I have a problem migrating from Odoo 8 CRM to Odoo 9.
Everything is going well except the last step which is list of phone calls(crm.phonecall).
Seems like this feature isn't included in the new version anymore.
It is very important for us.

**Comment by raycarnes** [comment]
There are now 'Activities' for CRM.  These are managed via the crm.activity model.  For each record in crm.lead, you can set and record the activity.  This information is added to the chatter below the Opportunity, so there is no longer a record for each phone call.

**Comment by tanerhasret** [comment]
Thank You raycarners .

**Comment by tanerhasret** [comment]
odoo 8 to 9 Internal server error after making the migration gives error please help

2016-01-07 23:23:44,934 4256 INFO kuresel_migrated werkzeug: 127.0.0.1 - - [07/Jan/2016 23:23:44] "GET /web?db=kuresel_migrated HTTP/1.1" 303 -
2016-01-07 23:23:44,953 4256 INFO kuresel_migrated werkzeug: 127.0.0.1 - - [07/Jan/2016 23:23:44] "GET /web/login HTTP/1.1" 500 -
2016-01-07 23:23:44,969 4256 ERROR kuresel_migrated werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/odoo/odoo-server/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 312, in checked_call
    result.flatten()
  File "/odoo/odoo-server/openerp/http.py", line 1439, in flatten
    self.response.append(self.render())
  File "/odoo/odoo-server/openerp/http.py", line 1432, in render
    context=request.context)
  File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 1070, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 459, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 459, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 282, in render_node
    self, element, attribute_name, attribute_value, qwebcontext)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 361, in render_att_att
    return [(attribute_name[6:], self.eval(attribute_value, qwebcontext))]
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 195, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 192, in eval
    return qwebcontext.safe_eval(expr)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/odoo/odoo-server/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
    
QWebException: "'NoneType' object has no attribute 'name'" while evaluating
'res_company.name'

**Comment by adekock11** [comment]
You can also note that Odoo S.A. has a module on the app store called crm_voip. There is a crm.phonecall object in that module.

**Comment by Yenthe666** [comment]
Hi @tanerhasret,

Migration problems don't fall under the Github issues, they are reserved to bugs only, not migration and implementation issues.
That being said @adekock11 is correct that the module `crm_voip` has the ability to hold this data.

Regards,
Yenthe

**Comment by sehrishnaz** [comment]
Hope this will helps: https://learnopenerp.blogspot.com/2020/08/t-call-web-website-login-layout-qwebexception-odoo.html
