### ISSUE TITLE
[16.0] Searching in apps

### ISSUE THREAD

**Issue by Elblassy** [odoo/odoo#102515]
When to try to search for specific module in odoo 16 it get me this error : 

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/http.py", line 1528, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/http.py", line 1557, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/http.py", line 1754, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/addons/website/models/ir_http.py", line 222, in _dispatch
    response = super()._dispatch(endpoint)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/addons/base/models/ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/http.py", line 673, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/addons/base/models/ir_module.py", line 1021, in search_panel_select_range
    record['__count'] = self.env['ir.module.module'].search_count(model_domain)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/models.py", line 1514, in search_count
    res = self.search(domain, limit=limit, count=True)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/models.py", line 1536, in search
    res = self._search(domain, offset=offset, limit=limit, order=order, count=count)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/models.py", line 4633, in _search
    self._cr.execute(query_str, params)
  File "/Users/elblasy/PycharmProjects/odoo16/odoo/odoo/sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedFunction: function jsonb_path_query_array(jsonb, unknown) does not exist
LINE 1: ...dule_module"."name"::text like 'theme_%'))) AND ((jsonb_path...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by Elblassy** [comment]
It solved when update postgresql to v13
