### ISSUE TITLE
Traceback when creating a privacy lookup.

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#102618]
Impacted versions: 16.0

Steps to reproduce:
1. Open the Contact module.
2. Open any contact -> Click on Action -> Privacy lookup.
3. Enter "Test" in Email address field. 
4. Click on Lookup.

Current behavior: I am getting a Traceback.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1532, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1561, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1758, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 222, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 673, in route_wrapper
    result = endpoint(self, args, *params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, args, *kwargs)
  File "/data/build/odoo/addons/privacy_lookup/wizard/privacy_lookup_wizard.py", line 174, in action_lookup
    self.env.cr.execute(query, tuple(values))
  File "/data/build/odoo/odoo/sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = boolean
LINE 5:                 WHERE email_normalized = false
                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

Expected behavior: It should raise a warning instead of giving a traceback.

Video/Screenshot link (optional): 

https://user-images.githubusercontent.com/32053757/194547800-1e1c511e-6040-4ea1-b6c0-3b118214ff49.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by PatelAtul891** [comment]
@odooaktiv PR  #102774 has been generated
