### ISSUE TITLE
Error while initializing DB on odoo 9.0

### ISSUE THREAD

**Issue by gadLinux** [odoo/odoo#10264]
The odoo initialization fails because wrong biew. 

I just created a database and let odoo create everything. It fails 100% of times. Leaving the system unusable. So this is critical.

1.- Create database, grant permissions.
2.- Init odoo with DB init option 
    ./odoo.py -c /etc/odoo/odoo-server.conf --without-demo=ALL -d odoo_level2
3.- It fails after a while with the error below. 

2016-01-01 14:26:46,931 20576 INFO odoo_level2 openerp.modules.loading: loading report/views/layouts.xml
2016-01-01 14:26:47,706 20576 INFO odoo_level2 openerp.modules.loading: loading report/views/views.xml
2016-01-01 14:26:48,465 20576 INFO odoo_level2 openerp.addons.base.ir.ir_ui_view: View inheritance may not use attribute 'string' as a selector.

Error context:
View `view_company_form_inherited`
[view_id: 183, xml_id: n/a, model: res.company, parent_id: 110]
2016-01-01 14:26:48,471 20576 ERROR odoo_level2 openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/srv/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/srv/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/srv/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/srv/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/srv/odoo/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/srv/odoo/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/srv/odoo/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/srv/odoo/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/srv/odoo/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/addons/base/ir/ir_model.py", line 1101, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/srv/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 478, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/srv/odoo/openerp/models.py", line 4323, in _create
    recs._validate_fields(vals)
  File "/srv/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `view_company_form_inherited`
[view_id: 183, xml_id: n/a, model: res.company, parent_id: 110]
None" while parsing /srv/openerp/addons/report/views/views.xml:96, near
<record id="reporting_settings_form_inherited" model="ir.ui.view">
            <field name="name">view_company_form_inherited</field>
            <field name="inherit_id" ref="base.view_company_form"/>
            <field name="model">res.company</field>
            <field name="arch" type="xml">
                <data>
                    <xpath expr="//page[@string='Report Configuration']/group[@string='Configuration']" position="inside">
                        <field name="paperformat_id"/>
                    </xpath>
                </data>
            </field>
        </record>
2016-01-01 14:26:48,488 20576 CRITICAL odoo_level2 openerp.service.server: Failed to initialize database `odoo_level2`.
Traceback (most recent call last):
  File "/srv/odoo/openerp/service/server.py", line 885, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/srv/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/srv/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/srv/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/srv/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/srv/odoo/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/srv/odoo/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/srv/odoo/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/srv/odoo/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/srv/odoo/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/addons/base/ir/ir_model.py", line 1101, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/srv/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/srv/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/api.py", line 478, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/srv/odoo/openerp/models.py", line 4323, in _create
    recs._validate_fields(vals)
  File "/srv/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `view_company_form_inherited`
[view_id: 183, xml_id: n/a, model: res.company, parent_id: 110]
None" while parsing /srv/openerp/addons/report/views/views.xml:96, near
<record id="reporting_settings_form_inherited" model="ir.ui.view">
            <field name="name">view_company_form_inherited</field>
            <field name="inherit_id" ref="base.view_company_form"/>
            <field name="model">res.company</field>
            <field name="arch" type="xml">
                <data>
                    <xpath expr="//page[@string='Report Configuration']/group[@string='Configuration']" position="inside">
                        <field name="paperformat_id"/>
                    </xpath>
                </data>
            </field>
        </record>

**Comment by gadLinux** [comment]
Forget about this. I was mixing odoo 8 plugins with version 9
