### ISSUE TITLE
[9.0] Accounting Issue when loading dashboard

### ISSUE THREAD

**Issue by sebastian-code** [odoo/odoo#10272]
**Error on accounting app on launch**

In clean installation on a VirtualBox VM running Ubuntu 14.04.03, during the setup When opening the accounting app it throws the following error message, which also happens when you try to launch the setup wizard from the configuration menu:

```xml
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web_planner/models/web_planner.py", line 45, in render
    return self.env['ir.ui.view'].browse(template_id).render(values=values)
  File "/opt/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 562, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 252, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 172, in get_template
    document = qwebcontext.loader(name)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(cr, uid, view_id, context=context)
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _read_template
  File "/opt/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
    view_arch = etree.fromstring(view['arch'].encode('utf-8'))
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68106)
  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)
  File "parser.pxi", line 1673, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101284)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:96466)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
XMLSyntaxError: Entity 'uacute' not defined, line 531, column 28

```

Impacted version:
  - 9.0

Steps to reproduce:
  - Somehow it appears that the issue is related to the setup wizard.

Current behaviour:
  - Every time the panel is called, the error message is shown to the user with configuration rights.

Expected behaviour:
  - The accounting application setup wizard to be launch.

**Comment by eneldoserrata** [comment]
The problem is in you translation #.po files

XMLSyntaxError: Entity 'uacute' not defined, line 531, column 28

search on yours po files the word "uacute" and fix there.

and you can contribute by fixing on translation repos here is the wiki https://github.com/odoo/odoo/wiki/Translations

**Comment by jprodriguez12** [comment]
I have the same problem in a new installation with just sales and invoices modules. I created the database in spanish language.
I reproduce the error in configuration menu by clicking in invoices ("Facturación") link to configure the app.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web_planner/models/web_planner.py", line 45, in render
    return self.env['ir.ui.view'].browse(template_id).render(values=values)
  File "/opt/odoo/odoo-server/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 562, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 252, in render
    element = self.get_template(id_or_xml_id, qwebcontext)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 172, in get_template
    document = qwebcontext.loader(name)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 1063, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(cr, uid, view_id, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _read_template
  File "/opt/odoo/odoo-server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 923, in _read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/odoo/odoo-server/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 635, in read_combined
    view_arch = etree.fromstring(view['arch'].encode('utf-8'))
  File "lxml.etree.pyx", line 3094, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70505)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106339)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105130)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99812)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94286)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95722)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94789)
XMLSyntaxError: Entity 'uacute' not defined, line 533, column 28

I use branch 9 and is up to date.
I have searched my po files and I cannot see any error:

./odoo/odoo-server/addons/account/i18n/es.po:msgstr "<strong>Anotar el extracto bancario (o importar archivo)</strong><br/>\nDependiendo del vol&uacute;men de transacciones, deber&iacute; guardar su extracto bancario cada semana o varias veces al d&iacute;a."
./odoo/odoo-server/addons/account/i18n/es_EC.po:msgstr "<strong>Anotar el extracto bancario (o importar archivo)</strong><br/>\nDependiendo del vol&uacute;men de transacciones, deber&iacute; guardar su extracto bancario cada semana o varias veces al d&iacute;a."
./odoo/odoo-server/addons/account/i18n/es_CL.po:msgstr "<strong>Anotar el extracto bancario (o importar archivo)</strong><br/>\nDependiendo del vol&uacute;men de transacciones, deber&iacute; guardar su extracto bancario cada semana o varias veces al d&iacute;a."

**Comment by sebastian-code** [comment]
Thanks for the comment @eneldoserrata can you tell me where are those specificly? My localization setup is on es_CO.

I have been looking for it but I haven't been able to find them.

**Comment by eneldoserrata** [comment]
es_CO.po no have this expression translated odoo take from es.po

the issue are in:
odoo/addons/account/i18n/es.po line 615

i already fix on transfix

**Comment by sebastian-code** [comment]
Thanks. I'll look into it to try to fix it.

**Comment by dansanti** [comment]
Hi! well some other terms need be fixed too on all es language https://github.com/odoo/odoo/issues/10299

**Comment by dansanti** [comment]
HI! update to latest Version, it fixed(and close this issue)

**Comment by sebastian-code** [comment]
It's great, thanks to all of you guys
