### ISSUE TITLE
Error when opening invoice's form view on mobile device

### ISSUE THREAD

**Issue by inst-sol4u** [odoo/odoo#102735]
Impacted versions: 16.0

Steps to reproduce:
- Install the Invoicing app
- Open the invoices list view (on a mobile device)
- Click on any invoice

Current behavior:
An error is displayed:
UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1211:101)
    at owl.App.handleError (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:2028:29)
    at Fiber._render (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1434:19)
    at Fiber.render (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1432:6)
    at ComponentNode.initiateRender (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1511:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'value')
    at KanbanRecord.template (eval at compile (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1990:370), <anonymous>:20:47)
    at owl.App.callTemplate (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1659:129)
    at KanbanRecord.template (eval at compile (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1990:370), <anonymous>:17:16)
    at Fiber._render (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1433:96)
    at Fiber.render (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1432:6)
    at ComponentNode.initiateRender (http://localhost:9016/web/assets/466-551fb63/web.assets_common.min.js:1511:47)

Expected behavior:
The selected invoice's form view should be displayed

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/60315721/194650042-07d7757a-6e5e-4fa7-9bf6-0610c350b1ad.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by inst-sol4u** [comment]
Should be fixed by now.

**Comment by inst-sol4u** [comment]
Now, it is fixed.
