### ISSUE TITLE
[16.0] Odoo.sh Issue: Start Odoo.sh With Empty Repo & Only Core Modules - Install point_of_sale:  function jsonb_path_query_array(jsonb, unknown) does not exist

### ISSUE THREAD

**Issue by luke-stdev001** [odoo/odoo#103175]
## Impacted versions:

`16.0`

## Steps to reproduce:

1) Use an empty repo to start an Odoo.sh build
2) Try to install any modules related in some way to products (eg. eCommerce, Point of Sale, etc.)
3) The installation of any of these modules will fail with a traceback.

**Not reproduce-able on runbot.**

## Current behavior:
Currently when installing any of the modules described above i'll get the following traceback:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1534, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1563, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1760, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 673, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 610, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 207, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 467, in init_models
    self.check_indexes(cr, model_names)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 528, in check_indexes
    sql.create_index(cr, indexname, tablename, [expression], method, where)
  File "/home/odoo/src/odoo/odoo/tools/sql.py", line 287, in create_index
    cr.execute(f'CREATE INDEX "{indexname}" ON "{tablename}" USING {method} ({args}){where}')
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedFunction: function jsonb_path_query_array(jsonb, unknown) does not exist
LINE 1: ...index" ON "product_template" USING gin (unaccent((jsonb_path...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

## Expected behavior:
The clean builds of Odoo.sh, should not have issues installing the modules described above. It appears to be some issue with the compatibility of JSONB in Postgres, however after checking the Postgres version running on Odoo.sh it appears to be up to date (postgresql 14.5.x) and shouldn't have any JSONB compatibility issues, as it's well supported.

Screenshots attached, show a clean Odoo.sh build of Odoo 16.0, then demonstrating an attempted installation of the point_of_sale module, resulting in the traceback outlined above.

## Video/Screenshot link (optional):

![odoo_sh](https://user-images.githubusercontent.com/111725650/195517203-772a13c0-91a7-4268-81cf-c6591f06e7a5.jpg)
![Screen Shot 2022-10-13 at 5 09 19 pm](https://user-images.githubusercontent.com/111725650/195516483-a0874a2f-09e6-4040-9124-0d16422d8b8c.png)
![Screen Shot 2022-10-13 at 5 09 35 pm](https://user-images.githubusercontent.com/111725650/195516491-539efc67-11d1-4e28-9a1d-5176c6d985c2.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by ma-syentys** [comment]
I hade the same error in my local machine, when i'm traying to install sale_management/account/stock .. in **Odoo16**
Ubuntu 18.04.6 LTS With Postgres 10.22

**Comment by amigrave** [comment]
Hi @luke-stdev001 ,

One of our asian server running 18.04 was still opened for development builds. This is now corrected so you can rebuild your development branch and it will be routed to a new server.

**Comment by luke-stdev001** [comment]
> Hi @luke-stdev001 ,
> 
> 
> 
> One of our asian server running 18.04 was still opened for development builds. This is now corrected so you can rebuild your development branch and it will be routed to a new server.
> 
> 
> 
> 
Thanks @amigrave !
