### ISSUE TITLE
[Bug] Open invoice form view via mobile mode

### ISSUE THREAD

**Issue by darbi-a** [odoo/odoo#103240]
Impacted versions:  CE 16.0

Steps to reproduce: 
1/ Install l10n_be module
2/ Create new Invoice
3/ Go back to tree view (Invoices)
4/ Switch the browser to responsive mode (Use Toggle Device Mode)
5/ Reload the page
6/ Try to open that invoice (form view for editing)

Current behavior:
**>>An error message appears:**

UncaughtPromiseError > OwlError
Promesse non interceptée > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1211:101)
        at owl.App.handleError (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:2028:29)
        at Fiber._render (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1434:19)
        at Fiber.render (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1432:6)
        at ComponentNode.initiateRender (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1511:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'value')
    TypeError: Cannot read properties of undefined (reading 'value')
        at KanbanRecord.template (eval at compile (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1990:370), <anonymous>:20:47)
        at owl.App.callTemplate (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1659:129)
        at KanbanRecord.template (eval at compile (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1990:370), <anonymous>:17:16)
        at Fiber._render (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1433:96)
        at Fiber.render (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1432:6)
        at ComponentNode.initiateRender (http://localhost:8016/web/assets/189-e9b4e95/web.assets_common.min.js:1511:47)

Expected behavior:
Open invoice via responsive mode (Use Toggle Device Mode) without any issue

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ffpaniago** [comment]
When install the e-mail marketing module, same problem:

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://vagas.dentrodahistoria.com.br/web/assets/766-045e6b2/web.assets_common.min.js:1211:101)
    at owl.App.handleError (https://vagas.dentrodahistoria.com.br/web/assets/766-045e6b2/web.assets_common.min.js:2028:29)
    at ComponentNode.initiateRender (https://vagas.dentrodahistoria.com.br/web/assets/766-045e6b2/web.assets_common.min.js:1510:19)

Caused by: Unable to render the required templates for the assets to load: XmlHttpRequestError
