### ISSUE TITLE
Error Con idioma español en contabilidad

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#10337]
Al instalar el modulo de contabilidad en odoo 9.0 da este error:

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 959, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\web\controllers\main.py", line 892, in call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 342, in old_api
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\web_planner\models\web_planner.py", line 45, in render
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 236, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 562, in new_api
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\web_editor\models\ir_ui_view.py", line 29, in render
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_ui_view.py", line 1065, in render
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_qweb.py", line 252, in render
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_qweb.py", line 172, in get_template
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_ui_view.py", line 1063, in loader
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_ui_view.py", line 938, in read_template
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "<string>", line 2, in _read_template
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\tools\cache.py", line 85, in lookup
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_ui_view.py", line 923, in _read_template
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server.\openerp\api.py", line 238, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20151228\server\openerp\addons\base\ir\ir_ui_view.py", line 635, in read_combined
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68106)
  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102455)
  File "parser.pxi", line 1673, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101284)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96466)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91757)
XMLSyntaxError: Entity 'oacute' not defined, line 15, column 55

Revisando en el foro es un problema sobre las traducciones 

Alguna idea para solucionar gracias

**Comment by dansanti** [comment]
Estimado, puedes pasar por transifex https://www.transifex.com/odoo/odoo-9 y ayudar a quitar los acute, por acento o en decimal, provicionalmente, puedes ir abriendo el archivo es.po de la carpeta i18n del módulo afectado y cambiarlo manualmente, luego ir a las configuraciones de odoo y recargar las traducciones (ojalás de que el archivo que edite lo suba a transifex, para así ir reparando ) https://github.com/odoo/odoo/issues/10299

**Comment by eneldoserrata** [comment]
Que idioma estas usando?

**Comment by Yenthe666** [comment]
Hey guys,

Closing as this bug report is in spanish & contains little information.
If somebody can still reproduce it and explain this in English I'm happy to reopen it.

Regards,
Yenthe
