### ISSUE TITLE
role "root" does not exist

### ISSUE THREAD

**Issue by 2016LQ** [odoo/odoo#10331]
what's wrong with it?  SOS!
i follow this for install ：
https://www.linode.com/docs/websites/cms/install-odoo-9-erp-on-ubuntu-14-04

Running as user 'root' is a security risk.
2016-01-06 14:45:39,275 34049 INFO ? openerp: OpenERP version 9.0c
2016-01-06 14:45:39,277 34049 INFO ? openerp: addons paths: ['/home/weblin/.local/share/Odoo/addons/9.0', u'/opt/odoo/openerp/addons', u'/opt/odoo/addons']
2016-01-06 14:45:39,278 34049 INFO ? openerp: database: default@default:default
2016-01-06 14:45:40,360 34049 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2016-01-06 14:46:40,034 34049 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-01-06 14:46:40,045 34049 INFO ? openerp.sql_db: Connection to the database failed
2016-01-06 14:46:40,045 34049 ERROR ? openerp.addons.bus.models.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/addons/bus/models/bus.py", line 168, in run
    self.loop()
  File "/opt/odoo/addons/bus/models/bus.py", line 146, in loop
    with openerp.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/openerp/sql_db.py", line 556, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/openerp/sql_db.py", line 162, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/openerp/sql_db.py", line 445, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 507, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  role "root" does not exist

2016-01-06 14:46:42,443 34049 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2016-01-06 14:46:43,520 34049 INFO ? openerp.http: HTTP Configuring static files
2016-01-06 14:46:43,536 34049 INFO ? openerp.sql_db: Connection to the database failed
2016-01-06 14:46:43,541 34049 INFO ? werkzeug: 192.168.175.1 - - [06/Jan/2016 14:46:43] "GET / HTTP/1.1" 500 -
2016-01-06 14:46:43,559 34049 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1617, in dispatch
    self.setup_db(httprequest)
  File "/opt/odoo/openerp/http.py", line 1548, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/odoo/openerp/http.py", line 1695, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/odoo/openerp/http.py", line 1669, in db_list
    dbs = openerp.service.db.list_dbs(force)
  File "/opt/odoo/openerp/service/db.py", line 307, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/odoo/openerp/sql_db.py", line 556, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/openerp/sql_db.py", line 162, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/openerp/sql_db.py", line 445, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 507, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  role "root" does not exist

**Comment by colinnewell** [comment]
Those instructions correctly show to create an odoo user on the system and how to setup an init script that runs odoo as the odoo user.

If you're trying to run that manually on the command line then switch to the odoo user first (running as root is a bad idea, as suggested by the very first line of the log output).

**Comment by Yenthe666** [comment]
Hi @2016LQ,

You're trying to run the Odoo process under an incorrect system user, this should be done with the user that is dedicated to the Odoo service.
In any case, this is not an issue for Github, since you've configured something wrong regarding users (or running the service)

Regards,
Yenthe
