### ISSUE TITLE
[9.0] Crash when creating a new voucher entry from a Journal

### ISSUE THREAD

**Issue by vro-odoo** [odoo/odoo#10348]
Navigate to Accounting > Configuration > Accounting > Journals and open the form view of any accounting journal record. Under "Action" click "Voucher Entries" and then click Create.
It results in the following error:

```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/models.py", line 1327, in default_get
    defaults[name] = field.default(self)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/addons/account_voucher/account_voucher.py", line 81, in <lambda>
    currency_id = fields.Many2one('res.currency', compute='_get_journal_currency', string='Currency', readonly=True, required=True, default=lambda self: self._get_currency())
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/addons/account_voucher/account_voucher.py", line 20, in _get_currency
    if journal.currency_id:
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/fields.py", line 905, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/models.py", line 3281, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/models.py", line 3211, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/models.py", line 3349, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/123903-9-0-8e1057/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "Exchange Difference (USD)"
LINE 2: ...                   WHERE "account_journal".id IN ('Exchange ...
                                                             ^
```

**Comment by Yenthe666** [comment]
Hi @vro-odoo,

Thanks a lot for your report.
This issue has been solved in the meanwhile so please update your local Odoo instance in order to fix this.

Regards,
Yenthe
