### ISSUE TITLE
[9.0] PoS numpad on payment page launches Uncaught ReferenceError

### ISSUE THREAD

**Issue by fawyna** [odoo/odoo#10355]
I tried installing on a fresh database just Point of Sale, with the nightly build from 20160106. Started a Point of Sale session and navigated to payment. Clicking on the numpad will launch this error. 

```
Uncaught ReferenceError: instance is not defined
https://fleurstory.gronex.com.sg/web/content/1612-6e24ea5/point_of_sale.assets.js:285
Traceback:
ReferenceError: instance is not defined
    at OdooClass.core.Class.extend.numpad_input (https://fleurstory.gronex.com.sg/web/content/1612-6e24ea5/point_of_sale.assets.js:285:492)
    at OdooClass.ScreenWidget.extend.payment_input (https://fleurstory.gronex.com.sg/web/content/1612-6e24ea5/point_of_sale.assets.js:336:383)
    at OdooClass.ScreenWidget.extend.click_numpad (https://fleurstory.gronex.com.sg/web/content/1612-6e24ea5/point_of_sale.assets.js:340:6)
    at HTMLButtonElement.<anonymous> (https://fleurstory.gronex.com.sg/web/content/1612-6e24ea5/point_of_sale.assets.js:340:191)
    at HTMLDivElement.jQuery.event.dispatch (https://fleurstory.gronex.com.sg/web/content/1408-0fe5f4a/web.assets_common.js:740:451)
    at HTMLDivElement.elemData.handle (https://fleurstory.gronex.com.sg/web/content/1408-0fe5f4a/web.assets_common.js:713:173)
```

Should I update to today's build?

**Comment by fawyna** [comment]
Just tested the latest build, works fine.
