### ISSUE TITLE
odoo 8 to 9 Internal server error after making the migration gives error please help

### ISSUE THREAD

**Issue by tanerhasret** [odoo/odoo#10371]
2016-01-07 23:23:44,934 4256 INFO kuresel_migrated werkzeug: 127.0.0.1 - - [07/Jan/2016 23:23:44] "GET /web?db=kuresel_migrated HTTP/1.1" 303 -
2016-01-07 23:23:44,953 4256 INFO kuresel_migrated werkzeug: 127.0.0.1 - - [07/Jan/2016 23:23:44] "GET /web/login HTTP/1.1" 500 -
2016-01-07 23:23:44,969 4256 ERROR kuresel_migrated werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
execute(self.server.app)
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
application_iter = app(environ, start_response)
File "/odoo/odoo-server/openerp/service/server.py", line 245, in app
return self.app(e, s)
File "/odoo/odoo-server/openerp/service/wsgi_server.py", line 184, in application
return application_unproxied(environ, start_response)
File "/odoo/odoo-server/openerp/service/wsgi_server.py", line 170, in application_unproxied
result = handler(environ, start_response)
File "/odoo/odoo-server/openerp/http.py", line 1488, in call
return self.dispatch(environ, start_response)
File "/odoo/odoo-server/openerp/http.py", line 1462, in call
return self.app(environ, start_wrapped)
File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in call
return self.app(environ, start_response)
File "/odoo/odoo-server/openerp/http.py", line 1652, in dispatch
result = ir_http._dispatch()
File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
return self._handle_exception(e)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
return request._handle_exception(exception)
File "/odoo/odoo-server/openerp/http.py", line 781, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
result = request.dispatch()
File "/odoo/odoo-server/openerp/http.py", line 840, in dispatch
r = self._call_function(*self.params)
File "/odoo/odoo-server/openerp/http.py", line 316, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
return f(dbname, args, *kwargs)
File "/odoo/odoo-server/openerp/http.py", line 312, in checked_call
result.flatten()
File "/odoo/odoo-server/openerp/http.py", line 1439, in flatten
self.response.append(self.render())
File "/odoo/odoo-server/openerp/http.py", line 1432, in render
context=request.context)
File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
return old_api(self, args, *kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 1070, in render
return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
return old_api(self, args, *kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
generated_attributes= name == "t" and generated_attributes or ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
result = self._render_tagt_render
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 459, in render_tag_call
res = self.render(cr, uid, template, d)
File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
return old_api(self, args, *kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
generated_attributes= name == "t" and generated_attributes or ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
result = self._render_tagt_render
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 459, in render_tag_call
res = self.render(cr, uid, template, d)
File "/odoo/odoo-server/openerp/api.py", line 238, in wrapper
return old_api(self, args, *kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 254, in render
return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
generated_attributes= name == "t" and generated_attributes or ''))
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 282, in render_node
self, element, attribute_name, attribute_value, qwebcontext)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 361, in render_att_att
return [(attribute_name[6:], self.eval(attribute_value, qwebcontext))]
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 195, in eval
raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 192, in eval
return qwebcontext.safe_eval(expr)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
File "/odoo/odoo-server/openerp/tools/safe_eval.py", line 298, in safe_eval
return eval(c, globals_dict, locals_dict)
File "", line 1, in

QWebException: "'NoneType' object has no attribute 'name'" while evaluating
'res_company.name'

**Comment by Yenthe666** [comment]
Hi @tanerhasre,

There are three options here: 
1) You tried to export an Odoo 8 database and import it in Odoo 9, which will not work.
2) You've used OpenUpgrade to migrate your database (https://github.com/OCA/OpenUpgrade)
3) You've bought an upgrade from Odoo and used their services. 

If you've used case 1 it is simply not possible.
If you've used case 2 then there is an issue with OpenUpgrade, which is not maintained by Odoo SA.
If you've used case 3 then you should contact sales@odoo.com to ask for help.

I will close this issue for now since all three cases are not handled by Odoo issues on Github.
If you face another problem you can reply on this.

Regards,
Yenthe

**Comment by 0967697922** [comment]
hi .. 
i have this issue 

this is my handler 
@http.route(['/demo/check/<string:db_name>'], type='http', auth='user')
	def check_url(self , db_name , **post):
		print 'db_name : ',db_name
		user_db = request.env['user.databases'].sudo().search([('db_name','=',db_name),('state','=','onprogress'),('user_id','=',request.uid)])
		if user_db : 
			return http.request.render('shamil_demo_application.db_creation', {
					'user_db':user_db.id,
			})
		else:
			return http.request.render('shamil_demo_application.db_creation', {
					'user_db':1,
			})
i call it with URL like 
http://192.168.44.21:8079/demo/check/RcSMzi4tf73qGvxR2017-01-02%2006%3A27%3A17.528626
on render cause this issue : 

2017-01-02 06:27:33,964 31855 ERROR shamilDemoApplication werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/home/demo/coreerp/branches/shamil/server_9/addons/website/models/ir_http.py", line 191, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/home/demo/coreerp/branches/shamil/server_9/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/home/demo/coreerp/branches/shamil/server_9/addons/website/models/ir_http.py", line 240, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 312, in checked_call
    result.flatten()
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 1439, in flatten
    self.response.append(self.render())
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/http.py", line 1432, in render
    context=request.context)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/addons/website/models/ir_ui_view.py", line 142, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_ui_view.py", line 1070, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 459, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 282, in render_node
    self, element, attribute_name, attribute_value, qwebcontext)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 361, in render_att_att
    return [(attribute_name[6:], self.eval(attribute_value, qwebcontext))]
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 195, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 192, in eval
    return qwebcontext.safe_eval(expr)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/home/demo/coreerp/branches/shamil/server_9/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
    
QWebException: "'NoneType' object has no attribute 'name'" while evaluating
'res_company.name'

**Comment by sehrishnaz** [comment]
try this: https://learnopenerp.blogspot.com/2020/08/t-call-web-website-login-layout-qwebexception-odoo.html
