### ISSUE TITLE
[16.0] website_forum : Exception In Forum Post Using Action Unpublished. 

### ISSUE THREAD

**Issue by sutharhardik** [odoo/odoo#103874]
Impacted versions:16.0 CE

Steps to reproduce:

1. Elearning -> Forum -> Posts
2. From Tree view select any Post.
3. From Action click on Unpublish.

Current behavior: Getting Tracebeck.

![elarning_publish](https://user-images.githubusercontent.com/41465217/197361728-b3ef42ec-b022-440e-9095-8a0de6509abf.png)

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/hsuthar/workspace/16.0/odoo/http.py", line 1534, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/hsuthar/workspace/16.0/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/hsuthar/workspace/16.0/odoo/http.py", line 1563, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/hsuthar/workspace/16.0/odoo/http.py", line 1760, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/hsuthar/workspace/16.0/addons/website/models/ir_http.py", line 222, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/hsuthar/workspace/16.0/odoo/addons/base/models/ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "/home/hsuthar/workspace/16.0/odoo/http.py", line 673, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/hsuthar/workspace/16.0/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/hsuthar/workspace/16.0/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/hsuthar/workspace/16.0/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/hsuthar/workspace/16.0/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/hsuthar/workspace/16.0/addons/website_forum/models/forum.py", line 603, in write
    res = super(Post, self).write(vals)
  File "/home/hsuthar/workspace/16.0/addons/mail/models/mail_thread.py", line 315, in write
    result = super(MailThread, self).write(values)
  File "/home/hsuthar/workspace/16.0/odoo/models.py", line 3658, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'is_published' on model 'forum.post'

Expected behavior:

should post unpulish without any exceptions.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @sutharhardik ,
seems this has been resolved as it is not reproducible now.
can you confirm
thanks
