### ISSUE TITLE
[14 Enterprise] consolidation.account can't adapt type 'lazy' for field consolidation_account_ids

### ISSUE THREAD

**Issue by albertopoljak** [odoo/odoo#103896]
### Impacted versions:

Odoo 14 Enterprise

### Steps to reproduce:

For tree/list view of model "consolidation.account" try to change field "consolidation_account_ids". 

### Current behavior:

When clicking the field "consolidation_account_ids" drop-down should be presented with record names.
But we get this error:
```
File "/home/alberto/Desktop/odoo_14/modules/enterprise_addons/account_consolidation/models/consolidation_coa.py", line 248, in name_get
    record.read()
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/models.py", line 3020, in read
    self._read(stored_fields)
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/models.py", line 3138, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
  File "/home/alberto/Desktop/odoo_14/venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 126, in getquoted
    qobjs = [o.getquoted() for o in pobjs]
  File "/home/alberto/Desktop/odoo_14/venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 126, in <listcomp>
    qobjs = [o.getquoted() for o in pobjs]
  File "/home/alberto/Desktop/odoo_14/venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 121, in getquoted
    pobjs = [adapt(o) for o in self._seq]
  File "/home/alberto/Desktop/odoo_14/venv/lib/python3.8/site-packages/psycopg2/extensions.py", line 121, in <listcomp>
    pobjs = [adapt(o) for o in self._seq]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alberto/Desktop/odoo_14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: can't adapt type 'lazy'
```

### Expected behavior:

There should be no error.

### Cause of error and possible fix

This commit that was added in enterprise: https://github.com/odoo/enterprise/commit/d9deefefb531b6f0d25f1282b9e7ecbb33caaf28

The added `_name_search` function breaks `name_get`.

One way to fix is not to return lazy load and instead return the search expression? Just do it like:

```py
    @api.model
    def _name_search(self, name='', args=None, operator='ilike', limit=100, name_get_uid=None):
        """Overwrite so it is the same as their new commit but WITHOUT the lazy load that breaks things."""
        args = args or []
        domain = []
        if name:
            domain = ['|', ('code', '=ilike', name.split(' ')[0] + '%'), ('name', operator, name)]
            if operator in expression.NEGATIVE_TERM_OPERATORS:
                domain = ['&', '!'] + domain[1:]
        return self._search(expression.AND([domain, args]), limit=limit, access_rights_uid=name_get_uid)
```

**Comment by malb-odoo** [comment]
i will look at this this afternoon ! thx for the reporting

**Comment by malb-odoo** [comment]
The lazy seems to not work since V14.0, since it's a FW of a correction in V13.0 we didn't catch this, i will make a PR to correct this, so it will be corrected soon ! 

Thx again for reporting this bug

**Comment by malb-odoo** [comment]
This issues has been corrected in this commit https://github.com/odoo dev/enterprise/commit/90b4f0fd74c101c1b9d9bd702d3874d9be7f5497
