### ISSUE TITLE
[16.0] Error when trying to open Website > Content > Pages

### ISSUE THREAD

**Issue by inst-sol4u** [odoo/odoo#104006]
Impacted versions:
16.0

Steps to reproduce:
Install Website app, then from the website menu, go to Site > Content > Pages

Current behavior:
The following error message is displayed:
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: [object Object]
OwlError: Got duplicate key in t-foreach: [object Object]
    at PageListController.template (eval at compile (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:2001:370), <anonymous>:21:46)
    at PageListController.slot3 (eval at compile (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:2001:370), <anonymous>:43:27)
    at callSlot (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:1617:34)
    at ControlPanel.defaultContent3 (eval at compile (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:2001:370), <anonymous>:49:17)
    at callSlot (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:1618:28)
    at ControlPanel.template (eval at compile (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:2001:370), <anonymous>:76:15)
    at ControlPanel.template (eval at compile (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:2001:370), <anonymous>:17:27)
    at Fiber._render (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:1443:96)
    at Fiber.render (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:1442:6)
    at ComponentNode.initiateRender (http://localhost:9016/web/assets/363-4d9f7c4/web.assets_common.min.js:1521:47)

Expected behavior:
The Pages page should be displayed

Video/Screenshot link (optional):
![Webiste Pages displays an error](https://user-images.githubusercontent.com/60315721/197643715-a48d6a29-e720-4a32-ac01-bc76fedabc80.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by inst-sol4u** [comment]
Note: It is working as expected on a mobile device.

**Comment by inst-sol4u** [comment]
Now, it is fixed.
