### ISSUE TITLE
for modifier "column_invisible": Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by jinjieSpring** [odoo/odoo#104309]
<field name="assetsinput_table_ids">
                            <tree editable="bottom">
                                <field name="parent_asset_second" invisible="1"/>
                                <field name="parent_state" invisible="1"/>
                                <field name="name" domain="[('asset_second', '=', parent_asset_second)]" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="type"/>
                                <field name="no"/>
                                <field name="spec"/>
                                <field name="factory_code"/>
                                <field name="buy_date"/>
                                <field name="price"/>
                                <field name="keep_dept" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="l_hr" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="storage_location"/>
                                <field name="new_storage_location" />
                                <field name="note" attrs="{'column_invisible': [('parent_state', '=', 1)]}"/>
                            </tree>
                        </field>

assetsinput_table_ids is one2many;I get an error when I click on the tree

Error: for modifier "column_invisible": Cannot read properties of undefined (reading 'split')
    at Class._evalModifiers (http://localhost:8069/web/assets/1049-a91ff0e/web.assets_backend.min.js:4624:138)
    at http://localhost:8069/web/assets/1049-a91ff0e/web.assets_backend.min.js:4305:224
    at _.mapObject (http://localhost:8069/web/assets/907-23f256f/web.assets_common.min.js:189:233)
    at Class._evalColumnInvisibleFields (http://localhost:8069/web/assets/1049-a91ff0e/web.assets_backend.min.js:4305:150)
    at Class._render (http://localhost:8069/web/assets/1049-a91ff0e/web.assets_backend.min.js:4308:144)
    at prototype.<computed> [as _render] (http://localhost:8069/web/assets/907-23f256f/web.assets_common.min.js:4719:488)
    at http://localhost:8069/web/assets/1049-a91ff0e/web.assets_backend.min.js:3966:13

**Comment by jinjieSpring** [comment]
<field name="assetsinput_table_ids">
                            <tree editable="bottom">
                                <field name="parent_asset_second" invisible="1"/>
                                <field name="parent_state" invisible="1"/>
                                <field name="name" domain="[('asset_second', '=', parent_asset_second)]" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="type"/>
                                <field name="no"/>
                                <field name="spec"/>
                                <field name="factory_code"/>
                                <field name="buy_date"/>
                                <field name="price"/>
                                <field name="keep_dept" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="l_hr" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="storage_location"/>
                                <field name="new_storage_location" />
                                <field name="note" attrs="{'column_invisible': [('parent_state', '=', 1)]}"/>
                            </tree>
                        </field>

**Comment by jinjieSpring** [comment]
<field name="assetsinput_table_ids">
                            <tree editable="bottom">
                                <field name="parent_asset_second" invisible="1"/>
                                <field name="parent_state" invisible="1"/>
                                <field name="name" domain="[('asset_second', '=', parent_asset_second)]" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="type"/>
                                <field name="no"/>
                                <field name="spec"/>
                                <field name="factory_code"/>
                                <field name="buy_date"/>
                                <field name="price"/>
                                <field name="keep_dept" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="l_hr" options="{'no_open':True,'no_create':True,'no_create_edit':True}"/>
                                <field name="storage_location"/>
                                <field name="new_storage_location" />
                                <field name="note" attrs="{'column_invisible': [('parent_state', '=', 1)]}"/>
                            </tree>
</field>

**Comment by jinjieSpring** [comment]
15.0
