### ISSUE TITLE
wget -O- https://raw.githubusercontent.com/odoo/odoo/9.0/odoo.py | python

### ISSUE THREAD

**Issue by PW0131** [odoo/odoo#10432]
odoo:running git init odoo
Traceback (most recent call last):
  File "<stdin>", line 160, in <module>
  File "<stdin>", line 152, in main
  File "<stdin>", line 142, in cmd_setup
  File "<stdin>", line 64, in cmd_setup_git
  File "<stdin>", line 37, in run
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

---

HELP ME!

**Comment by Yenthe666** [comment]
Hi @PW0131,

In the meanwhile this command will work fine out of the box.

Regards,
Yenthe
