### ISSUE TITLE
[8.0] google calendar sync error

### ISSUE THREAD

**Issue by noamix** [odoo/odoo#10467]
When I did google calendar synchronization, half of the data was loaded, then this error occurred. Any help is appreciated

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/google_calendar/google_calendar.py", line 605, in synchronize_events
    res = self.update_events(cr, user_to_sync, lastSync, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/google_calendar/google_calendar.py", line 865, in update_events
    event_to_synchronize[base_event][0][1].OE.event_id = main_ev[0].get('event_id')[0]
IndexError: list index out of range

**Comment by kghunt** [comment]
me too same issue

**Comment by robertallanroker** [comment]
I get the exact same error.

**Comment by gvickrage** [comment]
me too same issue, I am on version 8

**Comment by JKE-be** [comment]
Hello
Can your reproduce with a clean database ?

**Comment by Yenthe666** [comment]
Hi @noamix ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some. There have been some improvements and bug fixes on the calendar in upper versions though.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
