### ISSUE TITLE
[9.0] Field 'user_id' is missing on model account.analytic.account

### ISSUE THREAD

**Issue by funbaker** [odoo/odoo#10499]
In /addons/project/project.py around line 459 there is a related field (old api style) named project_id.analytic_account_id.user_id

The corresponding field in the model account.analytic.account doesn't exist though.

**Quantity field is ignored in a sale order**

Impacted versions:
- 9.0

Steps to reproduce:
1. read the field 'manager_id' from model project.task over xmlrpc

Current behavior:
- Exception
  Traceback (most recent call last):
  File "/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/openerp/service/model.py", line 173, in execute_kw
    return execute(db, uid, obj, method, *args, *_kw or {})
  File "/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/openerp/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/openerp/api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/models.py", line 5249, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/openerp/api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "/openerp/api.py", line 236, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/models.py", line 3210, in read
    self._read_from_database(stored, inherited)
  File "/openerp/api.py", line 236, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/models.py", line 3401, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/openerp/osv/fields.py", line 1561, in _related_read
    res[record.id] = value[self.arg[-1]]
  File "/openerp/models.py", line 5710, in __getitem__
    return self._fields[key].__get__(self, type(self))
  KeyError: 'user_id'

Expected behavior:
- get the result

This has a low priority for myself, as i can workaround by defining the needed fields instead of fetching all.
Probably this wasn't noticed, because manager_id isn't defined in the project view.

**Comment by funbaker** [comment]
Probably its a good idea to do preview first:
```
Traceback (most recent call last):
  File "/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/openerp/service/model.py", line 173, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/openerp/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/models.py", line 5249, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/openerp/models.py", line 3210, in read
    self._read_from_database(stored, inherited)
  File "/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/openerp/models.py", line 3401, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/openerp/osv/fields.py", line 1561, in _related_read
    res[record.id] = value[self.arg[-1]]
  File "/openerp/models.py", line 5710, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'user_id'
```

**Comment by pedrobaeza** [comment]
That field has been removed in latest 9.0 code, so the problem should be gone now.
