### ISSUE TITLE
QWebException: "'product.template' object has no attribute 'optional_product_ids'" while evaluating 'len(product.product_variant_ids) == 1 and not len(product.optional_product_ids) >= 1'

### ISSUE THREAD

**Issue by arakattack** [odoo/odoo#10492]
Website locked out after customizing "add chart" on /shop page.

2016-01-16 02:47:00,863 602 ERROR openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 768, in dispatch
    r = self._call_function(*_self.params)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 311, in checked_call
    result.flatten()
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 1367, in flatten
    self.response.append(self.render())
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 1360, in render
    context=request.context)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_ui_view.py", line 141, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 425, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 425, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 434, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 434, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 433, in render_tag_if
    if self.eval_bool(template_attributes["if"], qwebcontext):
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 225, in eval_bool
    return int(bool(self.eval(expr, qwebcontext)))
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 191, in eval
    return qwebcontext.safe_eval(expr)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/Applications/odoo-9.0-1/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "'product.template' object has no attribute 'optional_product_ids'" while evaluating
'len(product.product_variant_ids) == 1 and not len(product.optional_product_ids) >= 1'

**Comment by pedrobaeza** [comment]
This is not a problem in Odoo itself, but something derived of a bad manipulation or deployment, so I close the issue. If this is reproducible in an standard environment, please open a new issue with the detailed steps for reproducing the problem.
