### ISSUE TITLE
[16.0] Error when opening Apps > Updates page

### ISSUE THREAD

**Issue by ossama-nvis** [odoo/odoo#105102]
Impacted versions:
16.0

Steps to reproduce:
Click on Apps > Updates

Current behavior:
The following error is displayed:
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of null (reading 'node')
TypeError: Cannot read properties of null (reading 'node')
    at handleError (http://localhost:9016/web/assets/1940-ecfa729/web.assets_common.min.js:1213:140)
    at owl.App.handleError (http://localhost:9016/web/assets/1940-ecfa729/web.assets_common.min.js:2039:29)
    at ComponentNode.initiateRender (http://localhost:9016/web/assets/1940-ecfa729/web.assets_common.min.js:1520:19)

Expected behavior:
Open the Updates page

Video/Screenshot link (optional):
![Error when opening Apps - Updates](https://user-images.githubusercontent.com/91417154/200159396-795f6c76-9b86-4b40-b23c-b2c2143bb2bf.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
duplicated: https://github.com/odoo/odoo/issues/104598
