### ISSUE TITLE
Issues starting the software 

### ISSUE THREAD

**Issue by joanna350** [odoo/odoo#105326]
I loaded with
`python odoo-bin --addons-path=addons -c /etc/odoo.conf` for v13.0, and it works just fine

As my database is empty, added the param at the end like this for master
`python odoo-bin --addons-path=addons -c /etc/odoo.conf -i base`

```
2022-11-08 13:23:25,480 338303 ERROR hansunlee odoo.modules.registry: Failed to load registry 
2022-11-08 13:23:25,481 338303 ERROR hansunlee odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-3>", line 2, in __getitem__
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'hansunlee'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/tools/convert.py", line 547, in _tag_root
    f(rec)
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/tools/convert.py", line 448, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/models.py", line 4364, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/models.py", line 4286, in _load_records_create
    return self.create(values)
  File "<decorator-gen-64>", line 2, in create
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/addons/base/models/ir_config_parameter.py", line 106, in create
    return super(IrConfigParameter, self).create(vals_list)
  File "<decorator-gen-10>", line 2, in create
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/models.py", line 3921, in create
    records = self._create(data_list)
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/models.py", line 4124, in _create
    cr.execute(
  File "/home/hansunlee/PycharmProjects/odoo_root/odoo_local/odoo/odoo/sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(mail.catchall.alias) already exists.
```

@mart-e may I ask you how to remedy this matter if you don't mind, sorry to bother

**Comment by mart-e** [comment]
Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for deployment questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).
You can also check [the documentation](https://www.odoo.com/documentation/16.0/) for deployment advises.

Regards

**Comment by joanna350** [comment]
@mart-e Thank you, please feel free to delete this
