### ISSUE TITLE
[9.0e] Sales button throws exception from product.template form view

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#10549]
Impacted versions:
- 9.0e

Steps to reproduce:
1. create a product.template record (with at least two variants)
2. click 'Sales' button

Current behavior:
- throw exception

``` javascript
Uncaught Error: Expected ":", got ","
https://king.odoo.com/web/static/lib/py.js/lib/py.js:361
Traceback:
Error: Expected ":", got ","
    at advance (https://king.odoo.com/web/static/lib/py.js/lib/py.js:361:19)
    at Object.symbol.nud (https://king.odoo.com/web/static/lib/py.js/lib/py.js:244:17)
    at expression (https://king.odoo.com/web/static/lib/py.js/lib/py.js:351:22)
    at Object.py.parse (https://king.odoo.com/web/static/lib/py.js/lib/py.js:1315:16)
    at Object.py.eval (https://king.odoo.com/web/static/lib/py.js/lib/py.js:1454:16)
    at https://king.odoo.com/web/static/src/js/framework/pyeval.js:823:28
    at iterator (https://king.odoo.com/web/static/lib/underscore/underscore.js:176:16)
    at Function.<anonymous> (https://king.odoo.com/web/static/lib/underscore/underscore.js:191:14)
    at _.(anonymous function) [as reduce] (https://king.odoo.com/web/static/lib/underscore/underscore.js:1484:34)
    at eval_contexts (https://king.odoo.com/web/static/src/js/framework/pyeval.js:811:24)
```

**Comment by ramonski** [comment]
Got the same issue on the current `saas-9` branch (78d20b552b4374b94aec7097c0e6a48a3dd2d961)

**Comment by Yenthe666** [comment]
Hi @leopard7777777,

Thanks a lot for the bug report.
This issue has been fixed in the meanwhile though! Please update your Odoo source code and it'll be fixed.

Regards,
Yenthe
