### ISSUE TITLE
MemoryError when send more than 2K mails using mass_mailing

### ISSUE THREAD

**Issue by lcgonzalez-rgbconsulting** [odoo/odoo#105571]
Impacted versions: 15.0

Steps to reproduce:

1. Create some lists for sending mass mailing (total recipients > 30K)
2. Create mail template and set the destination recipients lists
3. Send mails

Current behavior:
The sending operation starts as expected but, when an amount of around to 2K mails has been sent, the process stops and the trace like below shows in the logs. I wonder if could be some error that happens during the sending operation and makes all process consume a lot of memory by accumulating records in memory but I can't prove it.

`File "/opt/odoo/src/15.0/odoo-15.0/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 167268
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'mailing.contact.subscription(167268,).opt_out'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/tools/safe_eval.py", line 332, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/models/mailing.py", line 930, in _process_mass_mailing_queue
    mass_mailing.action_send_mail()
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/models/mailing.py", line 895, in action_send_mail
    composer._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/sale/wizard/mail_compose_message.py", line 15, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/purchase/models/mail_compose_message.py", line 15, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mail/wizard/mail_compose_message.py", line 299, in _action_send_mail
    all_mail_values = wizard.get_mail_values(res_ids)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/wizard/mail_compose_message.py", line 21, in get_mail_values
    res = super(MailComposeMessage, self).get_mail_values(res_ids)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mail/wizard/mail_compose_message.py", line 427, in get_mail_values
    results = self._process_state(results)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mail/wizard/mail_compose_message.py", line 473, in _process_state
    optout_emails = self._get_optout_emails(mail_values_dict)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/wizard/mail_compose_message.py", line 83, in _get_optout_emails
    opt_out_list += self.mass_mailing_id._get_opt_out_list()
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/models/mailing.py", line 716, in _get_opt_out_list
    opt_out = self.env[self.mailing_model_name]._mailing_get_opt_out_list(self)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/models/mailing_list.py", line 243, in _mailing_get_opt_out_list
    opt_out_contacts = subscriptions.filtered(lambda rel: rel.opt_out).mapped('contact_id.email_normalized')
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/models.py", line 5489, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/models.py", line 5489, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/opt/odoo/src/15.0/odoo-15.0/addons/mass_mailing/models/mailing_list.py", line 243, in <lambda>
    opt_out_contacts = subscriptions.filtered(lambda rel: rel.opt_out).mapped('contact_id.email_normalized')
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/fields.py", line 1081, in __get__
    recs = record._in_cache_without(self)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/models.py", line 5914, in _in_cache_without
    ids = self.env.cache.get_missing_ids(self.browse(ids), field)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/models.py", line 5170, in browse
    ids = tuple(ids)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/models.py", line 271, in expand_ids
    seen.add(id_)
MemoryError

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/web/controllers/main.py", line 1351, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/addons/base/models/ir_cron.py", line 85, in method_direct_trigger
    cron.with_user(cron.user_id).with_context(lastcall=cron.lastcall).ir_actions_server_id.run()
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/addons/base/models/ir_actions.py", line 643, in run
    res = runner(run_self, eval_context=eval_context)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/addons/base/models/ir_actions.py", line 512, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/tools/safe_eval.py", line 348, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/15.0/odoo-15.0/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'MemoryError'>: "" while evaluating
'model._process_mass_mailing_queue()'`

Expected behavior:
The sending of all mails

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mguertin-jump** [comment]
I'm seeing the exact same behaviour here with the 15.0 branch.

`ERROR odoo.jumpplus.com odoo.addons.base.models.ir_cron: Call from cron Mail Marketing: Process queue for server action #1018 failed in Job #61
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 26302

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 1061, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'mailing.contact(26302,).email_normalized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 332, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odoo/addons/mass_mailing/models/mailing.py", line 932, in _process_mass_mailing_queue
    mass_mailing.action_send_mail()
  File "/opt/odoo/odoo/addons/mass_mailing_sms/models/mailing_mailing.py", line 245, in action_send_mail
    return super(Mailing, self - mass_sms).action_send_mail(res_ids=res_ids)
  File "/opt/odoo/odoo/addons/mass_mailing/models/mailing.py", line 897, in action_send_mail
    composer._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/odoo/addons/website_sale/models/mail_compose_message.py", line 19, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/odoo/addons/sale/wizard/mail_compose_message.py", line 15, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/odoo/addons/purchase/models/mail_compose_message.py", line 15, in _action_send_mail
    return super(MailComposeMessage, self)._action_send_mail(auto_commit=auto_commit)
  File "/opt/odoo/odoo/addons/coupon/models/mail_compose_message.py", line 15, in _action_send_mail
    return super()._action_send_mail(**kwargs)
  File "/opt/odoo/odoo/addons/mail/wizard/mail_compose_message.py", line 306, in _action_send_mail
    all_mail_values = wizard.get_mail_values(res_ids)
  File "/opt/odoo/enterprise/marketing_automation/wizard/mail_compose_message.py", line 14, in get_mail_values
    res = super(MailComposeMessage, self).get_mail_values(res_ids)
  File "/opt/odoo/odoo/addons/mass_mailing/wizard/mail_compose_message.py", line 21, in get_mail_values
    res = super(MailComposeMessage, self).get_mail_values(res_ids)
  File "/opt/odoo/odoo/addons/mail/wizard/mail_compose_message.py", line 439, in get_mail_values
    results = self._process_state(results)
  File "/opt/odoo/odoo/addons/mail/wizard/mail_compose_message.py", line 485, in _process_state
    optout_emails = self._get_optout_emails(mail_values_dict)
  File "/opt/odoo/odoo/addons/mass_mailing/wizard/mail_compose_message.py", line 83, in _get_optout_emails
    opt_out_list += self.mass_mailing_id._get_opt_out_list()
  File "/opt/odoo/odoo/addons/mass_mailing/models/mailing.py", line 716, in _get_opt_out_list
    opt_out = self.env[self.mailing_model_name]._mailing_get_opt_out_list(self)
  File "/opt/odoo/odoo/addons/mass_mailing/models/mailing_list.py", line 244, in _mailing_get_opt_out_list
    opt_in_contacts = subscriptions.filtered(lambda rel: not rel.opt_out).mapped('contact_id.email_normalized')
  File "/opt/odoo/odoo/odoo/models.py", line 5464, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1180, in mapped
    self.__get__(first(remaining), type(remaining))
  File "/opt/odoo/odoo/odoo/fields.py", line 1085, in __get__
    recs = record._in_cache_without(self)
  File "/opt/odoo/odoo/odoo/models.py", line 5928, in _in_cache_without
    ids = self.env.cache.get_missing_ids(self.browse(ids), field)
  File "/opt/odoo/odoo/odoo/models.py", line 5184, in browse
    ids = tuple(ids)
  File "/opt/odoo/odoo/odoo/models.py", line 271, in expand_ids
    seen.add(id_)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_cron.py", line 367, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_actions.py", line 643, in run
    res = runner(run_self, eval_context=eval_context)
  File "/opt/odoo/odoo/addons/website/models/ir_actions.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_actions.py", line 512, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'MemoryError'>: "" while evaluating
'model._process_mass_mailing_queue()'`

**Comment by mguertin-jump** [comment]
In our case it was a misconfiguration between soft and hard memory limits if I recall correctly (soft was greater than hard).
