### ISSUE TITLE
[BUG] pos_coupon: bad query error raised if use coupons in 2 orders of the same table  

### ISSUE THREAD

**Issue by fernandahf** [odoo/odoo#105604]
Impacted versions:

15.0

Steps to reproduce:

1. Configure POS automatic coupon for all orders
2. Open a new session in the POS
3. Create a new order, set the customer and add some products
4. Click on Orders
5. Click on New Order, set the customer and add some products
6. Go to the `Floors` button
7. Click on the table you created the orders
8. Click on Orders
9. Click on any of two orders
10. Click on the `Floors` button

Current behavior:

You should see an error like this in the Odoo logs:

<details>
  <summary>Traceback</summary>

```
INSERT INTO "pos_order_line" ("id", "coupon_id", "create_date", "create_uid", "discount", "full_product_name", "is_program_reward", "mp_dirty", "mp_skip", "name", "note", "order_id", "price_subtotal", "price_subtotal_incl", "price_unit", "product_id", "program_id", "qty", "write_date", "write_uid") VALUES (nextval('pos_order_line_id_seq'), NULL, '2022-11-10 19:56:49.031959', 2, 0.0, '10.0% discount on total amount', true, false, false, 'Bar/0014', '', 2,  -0.22,  -0.22,  -0.22, 205, ARRAY[5,'Code for 10% on orders (Automatic)'], '1.00', '2022-11-10 19:56:49.031959', 2) RETURNING id
ERROR: invalid input syntax for type integer: "Code for 10% on orders (Automatic)"
LINE 1: ...014', '', 2,  -0.22,  -0.22,  -0.22, 205, ARRAY[5,'Code for ...
                                                             ^
 
2022-11-10 19:56:49,090 21 ERROR 20959006-15-0-all odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/pos_sale/models/pos_order.py", line 43, in create_from_ui
    order_ids = super(PosOrder, self).create_from_ui(orders, draft)
  File "/data/build/enterprise/pos_l10n_se/models/pos_blackbox_sweden.py", line 180, in create_from_ui
    return super(PosOrder, self).create_from_ui(regular_orders, draft)
  File "/data/build/enterprise/pos_loyalty/models/pos_order.py", line 20, in create_from_ui
    order_ids = super(PosOrder, self).create_from_ui(orders, draft)
  File "/data/build/odoo/addons/pos_gift_card/models/pos_order.py", line 20, in create_from_ui
    order_ids = super(PosOrder, self).create_from_ui(orders, draft)
  File "/data/build/odoo/addons/point_of_sale/models/pos_order.py", line 693, in create_from_ui
    order_ids.append(self._process_order(order, draft, existing_order))
  File "/data/build/odoo/addons/point_of_sale/models/pos_order.py", line 134, in _process_order
    pos_order.write(self._order_fields(order))
  File "/data/build/odoo/addons/point_of_sale/models/pos_order.py", line 434, in write
    return super(PosOrder, self).write(vals)
  File "/data/build/odoo/odoo/models.py", line 3858, in write
    field.write(self, value)
  File "/data/build/odoo/odoo/fields.py", line 3292, in write
    return self.write_batch([(records, value)])
  File "/data/build/odoo/odoo/fields.py", line 3313, in write_batch
    return self.write_real(records_commands_list, create)
  File "/data/build/odoo/odoo/fields.py", line 3489, in write_real
    flush()
  File "/data/build/odoo/odoo/fields.py", line 3451, in flush
    comodel.create(to_create)
  File "<decorator-gen-377>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/data/build/odoo/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/data/build/odoo/addons/point_of_sale/models/pos_order.py", line 971, in create
    return super(PosOrderLine, self).create(values)
  File "<decorator-gen-67>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/models.py", line 4070, in create
    records = self._create(data_list)
  File "/data/build/odoo/odoo/models.py", line 4168, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/data/build/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/data/build/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "Code for 10% on orders (Automatic)"
LINE 1: ...014', '', 2,  -0.22,  -0.22,  -0.22, 205, ARRAY[5,'Code for ...
                                                                             ^
```

</details>

Expected behavior:

Query to update the pos order line working fine and no traceback.

Video/Screenshot link (optional):

https://youtu.be/95D6ROuBZUU

Support ticket number submitted via odoo.com/help (optional):

**# 3064038**

**Comment by hugho-ad** [comment]
Hello @trj-odoo @caburj 

could you take a look at this please?

regards!
