### ISSUE TITLE
Odoo JSON ERROR

### ISSUE THREAD

**Issue by pav19892** [odoo/odoo#10566]
ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/serpentcs/workspace/Odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/workspace/Odoo/openerp/http.py", line 1399, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1421, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by dfang** [comment]
+1

**Comment by robertallanroker** [comment]
I have this same problem.

**Comment by ntttue** [comment]
2017-12-06 14:32:29,496 14588 ERROR Quiz odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\Odoo10\quizmanagement\odoo\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Odoo10\quizmanagement\odoo\odoo\addons\base\ir\ir_http.py", line 177, in _dispatch
    rule, arguments = cls._find_handler(return_rule=True)
  File "D:\Odoo10\quizmanagement\odoo\odoo\addons\base\ir\ir_http.py", line 79, in _find_handler
    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "C:\Python27\lib\site-packages\werkzeug\routing.py", line 1573, in match
    raise NotFound()
NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
-----------------------------
Odoo 10, the same error.

**Comment by Yenthe666** [comment]
Hi all,

As nobody filled in the template and there is no clear example on how to trigger or reproduce it I'm closing this report.
Feel free to respond if you have reproducable steps!
