### ISSUE TITLE
IM Livechat breaking because of exposed global variable _

### ISSUE THREAD

**Issue by javl** [odoo/odoo#105617]
**edit: ** 
updated this issue to reflect the actual cause (originally included some guesses)

**Impacted versions:**
15

**Steps to reproduce:**
Add the following lines to webpage to add live chat to an external website (copied from the chat settings page)
```
<link rel="stylesheet" href="https://companyname.odoo.com/im_livechat/external_lib.css"/>
<script type="text/javascript" src="https://companyname.odoo.com/im_livechat/external_lib.js"></script>
<script type="text/javascript" src="https://companyname.odoo.com/im_livechat/loader/1"></script>

```
In the same page, use a script that modifies a global variable called `_`. Then try to start a chat by clicking the button in the bottom right corner.

**Current behavior:**
The chat button appears and when clicked expands to show the employee name you can chat with, and I can receive messages, but I'm unable to send a message (hitting return doesn't do anything). 

As soon as the button expanded to show the chat an error appears in the console, coming from `external_lib.js`:
```Uncaught (in promise) TypeError: _.contains is not a function```
After that, every time your press return it throws another error: ```TypeError: _.str is undefined```

This is caused by the variable `_` being a non-scoped, global variable which can (and in my case does) get overwritten by other scripts.

**Expected behavior:**
To be able to send chat messages.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/734644/201370371-8369a903-613e-474b-aa3d-63be67b9f2bb.png)
![image](https://user-images.githubusercontent.com/734644/201371430-86b0c83e-5132-4d03-8f9d-87dbdd513077.png)

**Comment by javl** [comment]
It seems `_` isn't properly scoped which means it can be overwritten by other scripts. In my case I'm using a script from another vendor to show Google reviews on the frontpage and the `_` variable is pointing to something in their script. This explains why it was sometimes working: it does work on other pages where I'm not loading these reviews.

The `_.contains` error can be found in the `registerTyping` method:

```
        registerTyping: function(params) {
           (...)
            if (_.contains(this._typingPartnerIDs, partnerID)) {
                return;
            }
            (...)
        },

```
This function (or its parent block) doesn't specify the `_` variable, using a global variable instead.

**Comment by javl** [comment]
Also, not related to this problem, but still a problem in itself: this `external_lib.js` file is >900kb! That seems a bit excessive for just a chat function?

**Comment by javl** [comment]
Wondering if anyone has seen this post and if it is something that's being considered to fix (basically by changing _ to _odoo?)

**Comment by jase-k** [comment]
I'm getting the same error when trying to implement livechat on my website. Any solution? 

external_lib.js:5420 Uncaught (in promise) TypeError: _.contains is not a function
    at model._created (external_lib.js:5420:7)
    at ModelManager._executeCreatedRecordsCreated (external_lib.js:5167:148)
    at ModelManager._flushUpdateCycle (external_lib.js:5173:144)
    at ModelManager._notifyListenersInUpdateCycle (external_lib.js:5187:21)
    at ModelManager._flushUpdateCycle (external_lib.js:5173:64)
    at ModelManager._executeCreatedRecordsComputes (external_lib.js:5165:21)
    at ModelManager._flushUpdateCycle (external_lib.js:5173:26)
    at ModelManager.insert (external_lib.js:5087:135)
    at Messaging.insert (external_lib.js:5243:482)
    at ModelManager.start (external_lib.js:5075:97)

**Comment by seb-odoo** [comment]
We finally removed the _ (underscore) lib in recent versions, this should no longer conflict.
