### ISSUE TITLE
16.0.20221114 - OwlError

### ISSUE THREAD

**Issue by smokeyrd** [odoo/odoo#105719]
Impacted versions: 16.0.20221114

Steps to reproduce: attempt to view any CRM record or browse to settings page

Current behavior: error produced- 

UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: "a rpc promise should always have a reject function"

OwlError: The following error occurred in onWillStart: "a rpc promise should always have a reject function"
    at wrapError (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:18373:23) (/web/static/lib/owl/owl.js:2537)
    at onWillStart (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:18416:29) (/web/static/lib/owl/owl.js:2580)
    at useModel (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:47347:5) (/web/static/src/views/model.js:141)
    at FormController.setup (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:39014:22) (/web/static/src/views/form/form_controller.js:121)
    at FormController.setup (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:163213:14) (/mail/static/src/views/form/form_controller.js:22)
    at setup (patch mail) (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:17023:44) (patch mail https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:17023)
    at new ComponentNode (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:18153:28) (/web/static/lib/owl/owl.js:2317)
    at https://crm.itcreations.com/web/assets/debug/web.assets_common.js:21503:28 (/web/static/lib/owl/owl.js:5667)
    at View.slot1 (eval at compile (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:21278:16), <anonymous>:15:36) (/web/static/lib/owl/owl.js:5442)
    at callSlot (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:18723:46) (/web/static/lib/owl/owl.js:2887)

Caused by: Error: a rpc promise should always have a reject function
    at Class._rpc (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:73716:19) (/web/static/src/legacy/js/core/service_mixins.js:145)
    at Class._rpc (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:89121:21) (/web/static/src/legacy/js/views/abstract_model.js:279)
    at prototype.<computed> [as _rpc] (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:70370:38) (/web/static/src/legacy/js/core/class.js:91)
    at Class._rpc (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:96229:35) (/web/static/src/legacy/js/views/basic/basic_model.js:5109)
    at prototype.<computed> [as _rpc] (https://crm.itcreations.com/web/assets/debug/web.assets_common.js:70370:38) (/web/static/src/legacy/js/core/class.js:91)
    at Class._fetchRecord (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:93710:21) (/web/static/src/legacy/js/views/basic/basic_model.js:2590)
    at Class._load (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:95254:25) (/web/static/src/legacy/js/views/basic/basic_model.js:4134)
    at Class.__load (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:91946:21) (/web/static/src/legacy/js/views/basic/basic_model.js:826)
    at async Class.load (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:88961:24) (/web/static/src/legacy/js/views/abstract_model.js:119)
    at async CrmFormRecord.load (https://crm.itcreations.com/web/assets/debug/web.assets_backend.js:23974:34) (/web/static/src/views/basic_relational_model.js:364)

Expected behavior: CRM record should be displayed without error

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

**Comment by Beander** [comment]
I have the same - 16.0-20221114 (Community Edition) . 
Can not even go to settings -> getting 

UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: "a rpc promise should always have a reject function".

Installing Website application solves the issue. Unfortunately deinstalling it brings issue back again to life.

**Comment by smokeyrd** [comment]
@Beander Great catch. Can confirm installing website app resolves the error. Need fix for RC but this gives a decent work-around until it can get patched.

**Comment by Beander** [comment]
I wonder, when the patch will come. Similar problem I can see in [https://github.com/odoo/odoo/issues/105629](#105629).

**Comment by Beander** [comment]
I still have the same error (16.0-20221121 Community Edition). 
Has anyone the same problem on Enterprise edition and is able to make official ticket? 
Is there any other workaround than installing website app?

**Comment by DevDorrejo** [comment]
Hello, have this issue, from the container one.

can't use odoo, tried to recreate the container and restore backup, but not look

**Comment by Beander** [comment]
> Hello, have this issue, from the container one.
> 
> can't use odoo, tried to recreate the container and restore backup, but not look
> 
> can't go to settings or preferences.

Pls try to install website app and let know if it solves the problem. In my case it solves - but as soon as website app is uninstalled - problem comes back.  Or even if website app is installed and I try to open database without website - same issue (OWL, when going to settings - or going to inventory and pressing button inventory at the date)

**Comment by DevDorrejo** [comment]
> > Hello, have this issue, from the container one.
> > can't use odoo, tried to recreate the container and restore backup, but not look
> > can't go to settings or preferences.
> 
> Pls try to install website app and let know if it solves the problem. In my case it solves - but as soon as website app is uninstalled - problem comes back. Or even if website app is installed and I try to open database without website - same issue (OWL, when going to settings - or going to inventory and pressing button inventory at the date)

Hello, this fix the issue, but how can i hide or omit the website view?

**Comment by Beander** [comment]
> > > Hello, have this issue, from the container one.
> > > can't use odoo, tried to recreate the container and restore backup, but not look
> > > can't go to settings or preferences.
> > 
> > 
> > Pls try to install website app and let know if it solves the problem. In my case it solves - but as soon as website app is uninstalled - problem comes back. Or even if website app is installed and I try to open database without website - same issue (OWL, when going to settings - or going to inventory and pressing button inventory at the date)
> 
> Hello, this fix the issue, but how can i hide or omit the website view?

No idea... I do not have time to check - but I wanted to - maybe some actions like Regenerate Assets Bundlers could help... I wander if someone is really working on the OWL case - and if this case is common by every user.

**Comment by Beander** [comment]
@smokeyrd @DevDorrejo I think I got rid of the problem. 
With old database (without website activated) I entered developer mode. As I could not enter settings (also OWL) I just put in addres after "/web" string debug=1 -> means: 
/web?debug=1#action=36&model=ir.module.module&view_type=kanban&cids=1&menu_id=5. 
Then click on bug icon (top-right) and select "regenerate assets bundles" and then "activate assets debugging". After that few clicks, log off/on and works ok. 
Pls let me know if it works by you as well.

**Comment by DevDorrejo** [comment]
> ?debug=1

this breake my system, now i only get white screen
