### ISSUE TITLE
[14.0] Odoo 14 in Fedora 37 (python 3.11, werkzeug 2.2)

### ISSUE THREAD

**Issue by rajeeshknambiar** [odoo/odoo#105731]
Impacted versions: 14.0

Steps to reproduce: Use Odoo 14 in Feodra 37, create a new db

Current behavior: DB creation fails with `ST node line range (2, 1) is not valid` error.

I understand Odoo 14 doesn't support Python 3.11 or Werkzeug 2.2; but that requires only minimal changes (patch attached below). Even with those, logging into an existing DB or creating a new one fails with following error, appreciate if any pointers can be given how to fix it:
```
2022-11-15 06:54:06,175 55638 INFO odoo14 odoo.modules.loading: Loading module web (2/7) 
2022-11-15 06:54:06,292 55638 INFO odoo14 odoo.modules.registry: module web: creating or updating database tables 
2022-11-15 06:54:06,868 55638 INFO odoo14 odoo.modules.loading: loading web/security/ir.model.access.csv 
2022-11-15 06:54:06,882 55638 INFO odoo14 odoo.modules.loading: loading web/views/webclient_templates.xml 
2022-11-15 06:54:07,234 55638 INFO odoo14 odoo.modules.loading: loading web/views/report_templates.xml 
2022-11-15 06:54:07,436 55638 INFO odoo14 odoo.modules.loading: loading web/views/base_document_layout_views.xml 
2022-11-15 06:54:07,459 55638 INFO odoo14 odoo.modules.loading: loading web/data/report_layout.xml 
2022-11-15 06:54:07,509 55638 ERROR odoo14 odoo.tools.convert.init: Could not eval(obj()._get_asset_style_b64()) for datas in {} 
2022-11-15 06:54:07,511 55638 WARNING odoo14 odoo.modules.loading: Transient module states were reset 
2022-11-15 06:54:07,513 55638 ERROR odoo14 odoo.modules.registry: Failed to load registry 
2022-11-15 06:54:07,513 55638 ERROR odoo14 odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
        ~^^^^^
  File "/opt/odoo/odoo14/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f6064716ac0>, 226, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/addons/base/models/qweb.py", line 313, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: AST node line range (2, 1) is not valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1, in <module>
  File "/opt/odoo/odoo14/addons/web/models/models.py", line 806, in _get_asset_style_b64
    company_styles = template_style._render({
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_ui_view.py", line 1726, in _render
    return self.env[engine]._render(self.id, qcontext)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_qweb.py", line 110, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/addons/base/models/qweb.py", line 321, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: AST node line range (2, 1) is not valid
Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
        ~^^^^^
  File "/opt/odoo/odoo14/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f6064716ac0>, 226, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/addons/base/models/qweb.py", line 313, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: AST node line range (2, 1) is not valid

Error when compiling AST
ValueError: AST node line range (2, 1) is not valid
Template: web.styles_company_report
Path: /t/t/t[10]
Node: <t t-elif="layout == 'web.external_layout_standard'">
                &amp;.o_report_layout_standard {
                    h2 {
                        color: <t t-esc="primary"/>;
                    }
                    #informations strong {
                        color: <t t-esc="secondary"/>;
                    }
                    #total strong{
                        color: <t t-esc="primary"/>;
                    }
                    table {
                        thead {
                            color: <t t-esc="secondary"/>;
                        }
                    }
                }
            </t>
            }
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 566, in _tag_record
    f_val = _eval_xml(self, field, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 114, in _eval_xml
    return safe_eval(a_eval, idref2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 37, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/tools/safe_eval.py", line 366, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating
'obj()._get_asset_style_b64()'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/service/db.py", line 63, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo14/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo/odoo14/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /opt/odoo/odoo14/addons/web/data/report_layout.xml:36, near
<record id="asset_styles_company_report" model="ir.attachment">
            <field name="datas" model="res.company" eval="obj()._get_asset_style_b64()"/>
            <field name="mimetype">text/scss</field>
            <field name="name">res.company.scss</field>
            <field name="type">binary</field>
            <field name="url">/web/static/src/scss/asset_styles_company_report.scss</field>
        </record>
2022-11-15 06:54:07,524 55638 INFO odoo14 odoo.modules.loading: loading 1 modules... 
2022-11-15 06:54:07,544 55638 INFO odoo14 odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries (+0 extra) 
2022-11-15 06:54:07,636 55638 INFO odoo14 odoo.modules.loading: Modules loaded. 
```

Expected behavior: DB creation succeeds

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Patch to make Odoo 14 work with Python 3.11, Werkzeug 2.2:
```
diff --git a/odoo/addons/base/models/ir_http.py b/odoo/addons/base/models/ir_http.py
index e08b6e3d..f267f98a 100644
--- a/odoo/addons/base/models/ir_http.py
+++ b/odoo/addons/base/models/ir_http.py
@@ -69,7 +69,7 @@ class ModelsConverter(werkzeug.routing.BaseConverter):
         return ",".join(value.ids)
 
 
-class SignedIntConverter(werkzeug.routing.NumberConverter):
+class SignedIntConverter(werkzeug.routing.IntegerConverter):
     regex = r'-?\d+'
     num_convert = int
 
diff --git a/odoo/http.py b/odoo/http.py
index 551a16fe..69bb86bb 100644
--- a/odoo/http.py
+++ b/odoo/http.py
@@ -537,7 +537,7 @@ def route(route=None, **kw):
 
             if isinstance(response, werkzeug.exceptions.HTTPException):
                 response = response.get_response(request.httprequest.environ)
-            if isinstance(response, werkzeug.wrappers.BaseResponse):
+            if isinstance(response, werkzeug.wrappers.Response):
                 response = Response.force_type(response)
                 response.set_default()
                 return response
@@ -1451,7 +1451,7 @@ class Root(object):
 
     def set_csp(self, response):
         # ignore HTTP errors
-        if not isinstance(response, werkzeug.wrappers.BaseResponse):
+        if not isinstance(response, werkzeug.wrappers.Response):
             return
 
         headers = response.headers
diff --git a/odoo/tools/_vendor/sessions.py b/odoo/tools/_vendor/sessions.py
index c2c3a643..4002d213 100644
--- a/odoo/tools/_vendor/sessions.py
+++ b/odoo/tools/_vendor/sessions.py
@@ -26,7 +26,6 @@ from pickle import load
 from time import time
 
 from werkzeug.datastructures import CallbackDict
-from werkzeug.posixemulation import rename
 
 _sha1_re = re.compile(r"^[a-f0-9]{40}$")
 
@@ -198,7 +197,7 @@ class FilesystemSessionStore(SessionStore):
         finally:
             f.close()
         try:
-            rename(tmp, fn)
+            os.rename(tmp, fn)
             os.chmod(fn, self.mode)
         except (IOError, OSError):
             pass
diff --git a/odoo/tools/safe_eval.py b/odoo/tools/safe_eval.py
index ce47edb9..4b7e9cc2 100644
--- a/odoo/tools/safe_eval.py
+++ b/odoo/tools/safe_eval.py
@@ -66,6 +66,8 @@ _CONST_OPCODES = set(to_opcodes([
     # 3.6: literal map with constant keys https://bugs.python.org/issue27140
     'BUILD_CONST_KEY_MAP',
     'LIST_EXTEND', 'SET_UPDATE',
+    # 3.11 replace DUP_TOP, DUP_TOP_TWO, ROT_TWO, ROT_THREE, ROT_FOUR
+    'COPY',
 ])) - _BLACKLIST
  # operations which are both binary and inplace, same order as in doc'
@@ -86,6 +88,8 @@ _EXPR_OPCODES = _CONST_OPCODES.union(to_opcodes([
     # specialised comparisons
     'IS_OP', 'CONTAINS_OP',
     'DICT_MERGE', 'DICT_UPDATE',
+    # Added in 3.11, replacing all BINARY_* and INPLACE_*
+    'BINARY_OP',
 ])) - _BLACKLIST
 
 _SAFE_OPCODES = _EXPR_OPCODES.union(to_opcodes([
@@ -112,6 +116,22 @@ _SAFE_OPCODES = _EXPR_OPCODES.union(to_opcodes([
     'LOAD_GLOBAL',
 
     'RERAISE', 'JUMP_IF_NOT_EXC_MATCH',
+    # Added in 3.11 https://docs.python.org/3.11/whatsnew/3.11.html
+    'RESUME',
+    # replacement of opcodes CALL_FUNCTION, CALL_FUNCTION_KW, CALL_METHOD
+    'PUSH_NULL', 'PRECALL', 'CALL', 'KW_NAMES',
+    # replacement of POP_JUMP_IF_TRUE and POP_JUMP_IF_FALSE
+    'POP_JUMP_FORWARD_IF_FALSE', 'POP_JUMP_FORWARD_IF_TRUE',
+    'POP_JUMP_BACKWARD_IF_FALSE', 'POP_JUMP_BACKWARD_IF_TRUE',
+    #replacement of JUMP_ABSOLUTE
+    'JUMP_BACKWARD',
+    #replacement of JUMP_IF_NOT_EXC_MATCH
+    'CHECK_EXC_MATCH',
+    # new opcodes
+    'RETURN_GENERATOR',
+    'PUSH_EXC_INFO',
+    'NOP',
+
 ])) - _BLACKLIST
 
 _logger = logging.getLogger(__name__)

```

**Comment by nilshamerlinck** [comment]
fyi https://github.com/odoo/odoo/pull/101136

**Comment by rajeeshknambiar** [comment]
> fyi #101136

This is same as the code that I have shared at the end of the report. After incorporating it,  error is appearing (probably) from a different location and I’m not sure where exactly how to correct it.

**Comment by rajeeshknambiar** [comment]
Some progress on the investigation — the failing code is
```
unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
```
where `unsave_eval` is `eval` itself. Changes in [Python 3.11](https://docs.python.org/3/whatsnew/3.11.html) says
>[ast.AST](https://docs.python.org/3/library/ast.html#ast.AST) node positions are now validated when provided to [compile()](https://docs.python.org/3/library/functions.html#compile) and other related functions. If invalid positions are detected, a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) will be raised.

And that looks quite related.

**Comment by aricaldeira** [comment]
@rajeeshknambiar this worked here for me;
Change
`
unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
`
to
`
unsafe_eval(compile(ast.unparse(astmod), '<template>', 'exec'), ns)
`

**Comment by rajeeshknambiar** [comment]
> @rajeeshknambiar this worked here for me; Change `unsafe_eval(compile(astmod, '<template>', 'exec'), ns)` to `unsafe_eval(compile(ast.unparse(astmod), '<template>', 'exec'), ns)`

Thanks a lot; that made it work.
