### ISSUE TITLE
UncaughtPromiseError > OwlError about everywhere (Odoo 16)

### ISSUE THREAD

**Issue by kalanen** [odoo/odoo#105814]
Error when trying to access about anything:

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:1105:101)
    at owl.App.handleError (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:1932:29)
    at ComponentNode.initiateRender (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:1413:19)

Caused by: Error: a rpc promise should always have a reject function
    at Class._rpc (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:5784:62)
    at Class._rpc (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:7695:13)
    at prototype.<computed> [as _rpc] (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:5588:488)
    at Class._rpc (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:8010:183)
    at prototype.<computed> [as _rpc] (https://mydomain.com/web/assets/524-d69dd4c/web.assets_common.min.js:5588:488)
    at Class._performOnChange (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:7970:159)
    at Class._makeDefaultRecord (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:7965:258)
    at async Class.load (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:7690:244)
    at async Record.load (https://mydomain.com/web/assets/528-ceee82b/web.assets_backend.min.js:2282:66)

This error applies on settings of any area. Web editor and such work as usual.

**Comment by kalanen** [comment]
Activating debug from address line and selecting "regenerate asset bundles" seems to fix it.

**Comment by alesisjoan** [comment]
I'm facing a very related issue and regenerating assets bundles didn't help. Not happening to all users, so far I know happens on Chrome (Windows and Mac).

The error is the following

![image](https://user-images.githubusercontent.com/4945724/205352984-49a520c8-03b2-4e02-9052-878b887078cd.png)

**Comment by arif1403** [comment]
UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1241:101)
    at owl.App.handleError (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1868:29)
    at Fiber._render (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1266:19)
    at Fiber.render (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1264:6)
    at ComponentNode.initiateRender (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1332:47)

Caused by: TypeError: buttonBox.insertAdjacentElement is not a function
    at FormEditorCompiler.compile (https://shintadaya.odoo.com/web/assets/79-b6156ea/web_studio.studio_assets.min.js:555:271)
    at useViewCompiler (https://shintadaya.odoo.com/web/assets/111-d018eb8/web.assets_backend.min.js:6290:172)
    at FormEditorRenderer.setup (https://shintadaya.odoo.com/web/assets/111-d018eb8/web.assets_backend.min.js:4555:1885)
    at FormEditorRenderer.setup (https://shintadaya.odoo.com/web/assets/111-d018eb8/web.assets_backend.min.js:10062:881)
    at setup (patch mail/views/web) (https://shintadaya.odoo.com/web/assets/111-d018eb8/web.assets_backend.min.js:2137:22)
    at FormEditorRenderer.setup (https://shintadaya.odoo.com/web/assets/79-b6156ea/web_studio.studio_assets.min.js:611:1871)
    at ComponentNode (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1327:202)
    at https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1866:6
    at FormEditorController.slot6 (eval at compile (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1826:374), <anonymous>:66:27)
    at callSlot (https://shintadaya.odoo.com/web/assets/110-bb92a1d/web.assets_common.min.js:1434:25)

how can I fix it?

**Comment by ArunKumar280897** [comment]
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:916:101)
    at App.handleError (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:1006:19)

Caused by: Error: "res.config.settings"."unsplash_access_key" field is undefined.
    at Field.parseFieldNode (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:7661:231)
    at http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:8538:865
    at visit (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4223:51)
    at visitChildren (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4222:171)
    at visit (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4223:129)
    at visitChildren (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4222:171)
    at visit (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4223:129)
    at visitChildren (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4222:171)
    at visit (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4223:129)
    at visitChildren (http://desktop-cqtb515:8017/web/assets/1/e0d5057/web.assets_web.min.js:4222:171)

how can i fix it

**Comment by ArunKumar280897** [comment]
thanks issue has been solved

**Comment by namezhyp** [comment]
I encountered the same issue: in Odoo 17 Community Edition, the website editor is not functioning properly, and the error message is similar. I have tried regenerating the asset bundles and reinstalling the web and web_unsplash modules, but none of them worked. Can anyone help me? I really need help.
