### ISSUE TITLE
when i open setting page or Contacts page this errors occurs

### ISSUE THREAD

**Issue by hnjm** [odoo/odoo#105902]
Impacted versions:
odoo.16.0
Steps to reproduce:
localhost
Current behavior:
when on open setting page
```
UncaughtPromiseError > TypeError

وعد لم يتم رصده > Cannot read properties of undefined (reading 'string'

TypeError: Cannot read properties of undefined (reading 'string')
    at http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6521:211
    at traverse (http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:200)
    at http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:242
    at Function.each (http://localhost:8056/web/assets/1759-a4a3557/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:211)
    at http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:242
    at Function.each (http://localhost:8056/web/assets/1759-a4a3557/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:211)
    at http://localhost:8056/web/assets/1771-d8153f9/web.assets_backend.min.js:6516:242
    at Function.each (http://localhost:8056/web/assets/1759-a4a3557/web.assets_common.min.js:171:149)
```
when on open contacts page

```
UncaughtPromiseError \> TypeError
وعد لم يتم رصده \> Cannot read properties of undefined (reading 'string')
UncaughtPromiseError > TypeError
وعد لم يتم رصده  > Cannot read properties of undefined (reading 'string')
TypeError: Cannot read properties of undefined (reading 'string')
    at http://localhost:8056/web/assets/debug/web.assets_backend.js:67295:84 (/web/static/src/legacy/legacy_load_views.js:67)
    at traverse (http://localhost:8056/web/assets/debug/web.assets_backend.js:67235:9) (/web/static/src/legacy/legacy_load_views.js:7)
    at http://localhost:8056/web/assets/debug/web.assets_backend.js:67237:13 (/web/static/src/legacy/legacy_load_views.js:9)	
    at Function.each (http://localhost:8056/web/assets/debug/web.assets_common.js:1900:9) (/web/static/lib/underscore/underscore.js:1330)	
    at traverse (http://localhost:8056/web/assets/debug/web.assets_backend.js:67236:11) (/web/static/src/legacy/legacy_load_views.js:8)	
    at http://localhost:8056/web/assets/debug/web.assets_backend.js:67237:13 (/web/static/src/legacy/legacy_load_views.js:9)	
    at Function.each (http://localhost:8056/web/assets/debug/web.assets_common.js:1900:9) (/web/static/lib/underscore/underscore.js:1330)	
    at traverse (http://localhost:8056/web/assets/debug/web.assets_backend.js:67236:11) (/web/static/src/legacy/legacy_load_views.js:8)
    at http://localhost:8056/web/assets/debug/web.assets_backend.js:67237:13 (/web/static/src/legacy/legacy_load_views.js:9)	
    at Function.each (http://localhost:8056/web/assets/debug/web.assets_common.js:1900:9) (/web/static/lib/underscore/underscore.js:1330)
```
Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by nouraellm** [comment]
did you try upgrading the base module?
