### ISSUE TITLE
[9.0][win10]dose 9.0 not support win10?

### ISSUE THREAD

**Issue by wojunnihou** [odoo/odoo#10609]
2016-01-25 10:12:45,900 3000 INFO hrms werkzeug: 127.0.0.1 - - [25/Jan/2016 10:12:45] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-25 10:12:45,900 3000 ERROR hrms openerp.service.server: Exception happened during processing of request from ('127.0.0.1', 51991)
Traceback (most recent call last):
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "c:\python27\Lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "c:\python27\Lib\socket.py", line 283, in close
    self.flush()
  File "c:\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

**Comment by sle-odoo** [comment]
Odoo should be working fine on Windows 10. If you want help, please provide a little more context that just a traceback. I can't help you with that.

Regards

**Comment by wojunnihou** [comment]
general
Request URL:http://127.0.0.1:15715/longpolling/poll
Request Method:POST
Status Code:200 OK
Remote Address:127.0.0.1:15715


request headers
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Content-Length:116
Content-Type:application/json
Cookie:planner_account_last_page=æ¬¢è¿0; planner_website_last_page=Welcome0; website_lang=en_US; session_id=4003e843aef5e962b734eac46d75a45cb7099617
Host:127.0.0.1:15715
Origin:http://127.0.0.1:15715
Referer:http://127.0.0.1:15715/web?debug=
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
X-Debug-Mode:true
X-Requested-With:XMLHttpRequest


request payload

{"jsonrpc":"2.0","method":"call","params":{"channels":[],"last":0,"options":{"bus_inactivity":4428}},"id":933399296}
