### ISSUE TITLE
[9.0] WH/OUT "Tracking" Smart Button - Clicking Results in a Traceback

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#10615]
<H1>Tested On Runbot:</H1>
127167-9-0-6872aa on runbot9.odoo.com

<H1>Steps to reproduce:</H1>

1) Find a WH/OUT in Inventory
2) add a carrier to allow the tracking smart button to show up
3) add an example tracking code, (eg. RC123456789HK)
4) save the WH/OUT
5) click the tracking smart button

<H1>Result:</H1>
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/127167-9-0-6872aa/openerp/addons/delivery/models/stock_picking.py", line 107, in open_website_url
    'url': self.carrier_id.get_tracking_link(self)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

<H1>Screencap GIF showing Steps to Reproduce:</H1>
<img src="https://cloud.githubusercontent.com/assets/2337666/12549568/19e5abca-c399-11e5-90a8-2a2e4ad490fb.gif"/>

**Comment by lukebranch** [comment]
closed with commit:

https://github.com/odoo/odoo/commit/fbf6f2cd9b696ca2fbad9882d6015fa15f223658
