### ISSUE TITLE
Odoo pos issue

### ISSUE THREAD

**Issue by allan225** [odoo/odoo#106406]
When i click on pos refund buton it generate error like this:

TypeError: Cannot read properties of undefined (reading 'get_orderlines')
    at TicketScreen._doesOrderHaveSoleItem (http://allan-linux:8016/web/assets/143-7d62636/point_of_sale.assets.min.js:1571:54)
    at TicketScreen._onDoRefund (http://allan-linux:8016/web/assets/143-7d62636/point_of_sale.assets.min.js:1540:71)
    at ActionpadWidget.__trigger (http://allan-linux:8016/web/assets/121-a65fd85/web.assets_common.min.js:2080:104)
    at ActionpadWidget.trigger (http://allan-linux:8016/web/assets/121-a65fd85/web.assets_common.min.js:2078:33)
    at ActionpadWidget.hdlr2 (eval at compile (http://allan-linux:8016/web/assets/121-a65fd85/web.assets_common.min.js:2001:370), <anonymous>:23:27)
    at Object.mainEventHandler (http://allan-linux:8016/web/assets/121-a65fd85/web.assets_common.min.js:2008:77)
    at HTMLButtonElement.listener (http://allan-linux:8016/web/assets/121-a65fd85/web.assets_common.min.js:1241:15)

**Comment by em230418** [comment]
To reproduce this:
Point of Sale -> any POS without any orders -> Refund (ProductScreen) -> Refund (TicketScreen).

Culprint is here: https://github.com/odoo/odoo/commit/fa06e3225650ed9d1a96709b0398e7f33313acf5#diff-a656f74e5ff6c8c6f2aee69ca86440c173a0f2a3e40c4246c02eb9a9bcdb0a84
`if (!order)` check was moved for some reason after _doesOrderHaveSoleItem.

Ping @caburj as author of commit above.
