### ISSUE TITLE
[9.0] Create Quotation and click on Confirm Sale button

### ISSUE THREAD

**Issue by ppa-odoo** [odoo/odoo#10686]
Step:
1. Create vendor with fiscalposition
2. Create product having (type: stockable, Routing : Buy and MTO, vendor)
3. Create Qutation with created product and Click on  Confirm Sale button.

Traceback

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/web/controllers/main.py", line 911, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/delivery/models/sale_order.py", line 34, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/portal_sale/portal_sale.py", line 32, in action_confirm
    return super(sale_order, self).action_confirm(cr, uid, ids, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/sale/sale.py", line 398, in action_confirm
    order.order_line._action_procurement_create()
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/procurement_jit/sale.py", line 11, in _action_procurement_create
    res = super(SaleOrderLine, self)._action_procurement_create()
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/sale/sale.py", line 567, in _action_procurement_create
    new_proc = self.env["procurement.order"].create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/procurement/procurement.py", line 145, in create
    self.run(cr, uid, [procurement_id], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/stock/procurement.py", line 334, in run
    self.pool.get('stock.move').action_confirm(cr, uid, move_to_confirm_ids, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/delivery/models/stock_move.py", line 34, in action_confirm
    res = super(StockMove, self).action_confirm()
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/stock/stock.py", line 2328, in action_confirm
    self._create_procurements(cr, uid, moves, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/stock/stock.py", line 2101, in _create_procurements
    res.append(self._create_procurement(cr, uid, move, context=context))
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/stock/stock.py", line 2096, in _create_procurement
    return self.pool.get("procurement.order").create(cr, uid, self._prepare_procurement_from_move(cr, uid, move, context=context), context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/procurement/procurement.py", line 145, in create
    self.run(cr, uid, [procurement_id], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/stock/procurement.py", line 325, in run
    res = super(procurement_order, self).run(cr, uid, new_ids, autocommit=autocommit, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/procurement/procurement.py", line 199, in run
    res = self._run(cr, uid, procurement, context=context or {})
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/purchase/purchase.py", line 709, in _run
    return procurement.make_po()
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/purchase/purchase.py", line 898, in make_po
    vals = procurement._prepare_purchase_order_line(po, supplier)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/128057-9-0-49fec8/openerp/addons/purchase/purchase.py", line 775, in _prepare_purchase_order_line
    taxes_id = taxes_id.filtered(lambda x: x.company_id.id in companies).ids
AttributeError: 'list' object has no attribute 'filtered'

**Comment by Yenthe666** [comment]
Hi @ppa-odoo,

Thanks a lot for the bug report.
I've just tried this on the latest Odoo V9 and this issue has been fixed in the meanwhile. As you can see the code also changed:
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/purchase/purchase.py#L858-L860
Please update your Odoo source code in order to fix this issue.

Regards,
Yenthe
