### ISSUE TITLE
can you help me with this 

### ISSUE THREAD

**Issue by michellemartinezrojas** [odoo/odoo#106801]
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1149, in lo
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 385, in loa
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/__init__.py", line 4, in
    from . import controllers
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/__init__.py",
    from . import main, pivot
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", lin
    from odoo import http, tools
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 59, in <module>
    from . tools.vendor import sessions
ModuleNotFoundError: No module named 'odoo.tools.vendor'

**Comment by nouraellm** [comment]
Hello, you have to correct the import statement on the addon `import odoo.tools._vendor` it is missing an undersscore.

**Comment by michellemartinezrojas** [comment]
muchas gracias
________________________________
De: ノウラ ***@***.***>
Enviado: miércoles, 30 de noviembre de 2022 10:08
Para: odoo/odoo ***@***.***>
Cc: michelle martinez ***@***.***>; Author ***@***.***>
Asunto: Re: [odoo/odoo] can you help me with this (Issue #106801)


Hello, you have to correct the import statement on the addon import odoo.tools._vendor it is missing an undersscore.

―

**Comment by michellemartinezrojas** [comment]
File "/usr/lib/python3/dist-packages/odoo/http.py", line 59, in <module>
    from .tools.vendor import tools_vendor_sessions
ModuleNotFoundError: No module named 'odoo.tools.vendor'

________________________________
De: ノウラ ***@***.***>
Enviado: miércoles, 30 de noviembre de 2022 10:08
Para: odoo/odoo ***@***.***>
Cc: michelle martinez ***@***.***>; Author ***@***.***>
Asunto: Re: [odoo/odoo] can you help me with this (Issue #106801)


Hello, you have to correct the import statement on the addon import odoo.tools._vendor it is missing an undersscore.

―

**Comment by michellemartinezrojas** [comment]
de vez de . va _

**Comment by nouraellm** [comment]
Has probado a actualizar el complemento?

**Comment by michellemartinezrojas** [comment]
no lo eh actualizado
me puedes ayudarme

**Comment by nouraellm** [comment]
Tienes una base de datos en línea? o está tratando de ejecutar odoo localmente?

**Comment by michellemartinezrojas** [comment]
desde un servidor ubuntu 22.04

**Comment by michellemartinezrojas** [comment]
try:
  42     from werkzeug.middleware.shared_data import SharedDataMiddleware
  43 except ImportError:
  44     from werkzeug.wsgi import SharedDataMiddleware
  45
  46 try:
  47     import psutil
  48 except ImportError:
  49     psutil = None
  50
  51 import odoo
  52 from .service.server import memory_info
  53 from .service import security, model as service_model
  54 from .sql_db import flush_env
  55 from .tools.func import lazy_property
  56 from .tools import ustr, consteq, frozendict, pycompat, unique, date_utils
  57 from .tools.mimetypes import guess_mimetype
  58 from .tools.misc import str2bool
  59 from .tools._vendor import sessions
  60 from .modules.module import module_manifest

**Comment by michellemartinezrojas** [comment]
local

**Comment by nouraellm** [comment]
Puede proporcionarme el comando que usa para ejecutar Odoo?

**Comment by michellemartinezrojas** [comment]
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
sudo echo "deb http://nightly.odoo.com/15.0/nightly/deb/ ./" >> 
/etc/apt/sources.list.d/odoo.list
systemctl status odoo

**Comment by michellemartinezrojas** [comment]
2022-11-30 17:13:10,850 450165 ERROR ? odoo.service.server: Failed to load server-wide module `base`.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1149, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 386, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/__init__.py", line 4, in <module>
    from.import controllers
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/__init__.py", line 1, in <module>
    from.import rpc
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 8, in <module>
    from odoo.http import tools_vendo, Controller, dispatch_rpc, request, route
ImportError: cannot import name 'tools_vendo' from 'odoo.http' (/usr/lib/python3/dist-packages/odoo/http.py)

esto son mis errores por favor me pueden ayudarme

**Comment by nouraellm** [comment]
Para poder ayudarte necesito más detalles; Qué desencadena el problema? Aparece durante la instalación? o cuando intenta ejecutar el servidor? O estás tratando de agregar un nuevo complemento?

**Comment by michellemartinezrojas** [comment]
el servidor esta te puedo eviarte un correo especificando los error

**Comment by michellemartinezrojas** [comment]
[cid:4d261101-f01e-4921-badf-acaebbc73b72]
________________________________
De: ノウラ ***@***.***>
Enviado: miércoles, 30 de noviembre de 2022 12:24
Para: odoo/odoo ***@***.***>
Cc: michelle martinez ***@***.***>; Mention ***@***.***>
Asunto: Re: [odoo/odoo] can you help me with this (Issue #106801)


Para poder ayudarte necesito más detalles; Qué desencadena el problema? Aparece durante la instalación? o cuando intenta ejecutar el servidor? O estás tratando de agregar un nuevo complemento?

―

**Comment by nouraellm** [comment]
Puedes crear un [ticket](https://odoo.com/help) y lo revisaré.
