### ISSUE TITLE
[9.0]Error while adding element in Invoice with other user than admin

### ISSUE THREAD

**Issue by katsele** [odoo/odoo#10690]
I'm running an Odoo 9 Community Edition on a AmazonAWS with NGINX. Everything works fin with the admin. But when I create a new user and try to create a new Invoice, I encounter this error while adding a new element in my invoice: 

```
Odoo Server Error
Traceback (most recent call last):

  File "/odoo/odoo-server/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)

  File "/odoo/odoo-server/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)

  File "/odoo/odoo-server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)

  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)

  File "/odoo/odoo-server/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)

  File "/odoo/odoo-server/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)

  File "/odoo/odoo-server/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)

  File "/odoo/odoo-server/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)

  File "/odoo/odoo-server/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)

  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)

  File "/odoo/odoo-server/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)

  File "/odoo/odoo-server/openerp/models.py", line 6015, in onchange
    value = record[name]

  File "/odoo/odoo-server/openerp/models.py", line 5721, in __getitem__
    return self._fields[key].__get__(self, type(self))

  File "/odoo/odoo-server/openerp/fields.py", line 816, in __get__
    return record._cache[self]

  File "/odoo/odoo-server/openerp/models.py", line 6100, in __getitem__
    value = self._recs.env.cache[field][self._recs.id]

KeyError: <openerp.models.NewId object at 0x7f1678d97450>
```

The funny part is, I tried first to install Odoo on a VMWare local to see if it was working. And everything works perfectly fine with multiple users...

Do you have any idea of what it could be? 

Thanks, 
Katsele

**Comment by rco-odoo** [comment]
@katsele I introduced this bug on January 21st, but it has been fixed since.
Please synchronize your instance with branch 9.0 as of today.
Sorry for the inconvenience.
