### ISSUE TITLE
[16.0] account : Raise Singleton Error on Invoice Preview

### ISSUE THREAD

**Issue by malaycmkhamar** [odoo/odoo#107195]
**Impacted versions:**
- 16.0

**Steps to reproduce:**
1) Create a database without demo data checked
2) install invoicing module and create a sale journal
3) Go to the invoicing --> customers --> Invoices
4) click on create button and press Preview button from the header
5) It will open Error Message box, Now click on the Discard Changes
6) It raise an Odoo Server Singleton Error

**Current behaviour:**
Odoo Server Singleton Error

> Traceback (most recent call last):
  File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/models.py", line 5104, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/http.py", line 1578, in _serve_db
>     return service_model.retrying(self._serve_ir_http, self.env)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/service/model.py", line 134, in retrying
>     result = func()
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/http.py", line 1607, in _serve_ir_http
>     response = self.dispatcher.dispatch(rule.endpoint, args)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/http.py", line 1804, in dispatch
>     result = self.request.registry['ir.http']._dispatch(endpoint)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/addons/base/models/ir_http.py", line 140, in _dispatch
>     result = endpoint(**request.params)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/http.py", line 698, in route_wrapper
>     result = endpoint(self, *args, **params_ok)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/addons/web/controllers/dataset.py", line 46, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/addons/web/controllers/dataset.py", line 33, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/api.py", line 461, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/api.py", line 448, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/addons/account/models/account_move.py", line 3522, in preview_invoice
>     self.ensure_one()
>   File "/home/ubuntu/workspace/odoo_all/MK_Odoo/16.0/odoo/models.py", line 5107, in ensure_one
>     raise ValueError("Expected singleton: %s" % self)
> ValueError: Expected singleton: account.move()
> 
> The above server error caused the following client error:
> RPC_ERROR: Odoo Server Error
>     at makeErrorFromResponse (http://0.0.0.0:1616/web/assets/110-be608fb/web.assets_backend.min.js:957:163)
>     at XMLHttpRequest.<anonymous> (http://0.0.0.0:1616/web/assets/110-be608fb/web.assets_backend.min.js:964:13)
> 

**Expected behavior:**
It should not raise any errors

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by manishkumarbohra** [comment]
Hello @malaycmkhamar , 

Unable to reproduce the same issue. 

Have you check this issue with latest code?

PFA

[invoice.webm](https://user-images.githubusercontent.com/72200254/205919086-d680151a-0d0f-4a9a-a646-222d4e243ddb.webm)

**Comment by malaycmkhamar** [comment]
Hi @manishkumarbohra ,
Yes i have checked with latest code and faced issue in it.

This will raise when you have not any active currency. 

PFA

![Finance_currency_issue](https://user-images.githubusercontent.com/114251616/205987212-e7f90efe-cae9-4d5a-9312-919eba1929e9.gif)
