### ISSUE TITLE
[V8] Bug error in res_company onchange when try write into another model 

### ISSUE THREAD

**Issue by jonathanf** [odoo/odoo#10718]
Hi, i found a problem when declare a onchange in res_company, 

The code is:

```
class res_company(models.Model):
    _inherit = 'res.company'

    @api.onchange('name')
    def _onchange_basic_wage(self):
        contracts = self.env['res.partner'].search([('id', '=', '3')])
        if contracts:
            contracts.write({'name': 'test'})
```

The error output:

2016-02-01 15:25:26,808 10338 ERROR XXX openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/XXX/Src/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/XXX/Src/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/XXX/Src/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/XXX/Src/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/XXX/Src/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/XXX/Src/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/XXX/Src/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/XXX/Src/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/XXX/Src/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/XXX/Src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/XXX/Src/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/XXX/Src/odoo/openerp/models.py", line 5957, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/XXX/Src/odoo/openerp/models.py", line 5857, in _onchange_eval
    params = eval("[%s]" % params, global_vars, field_vars)
  File "/home/XXX/Src/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
**ValueError: "name 'fax' is not defined" while evaluating
'[custom_footer, phone, fax, email, website, vat, company_registry, bank_ids]**

I try this writing hr.contract and it's the same

**Comment by mocak** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @jonathanf,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
