### ISSUE TITLE
CSS and JS files are not loading

### ISSUE THREAD

**Issue by anshad** [odoo/odoo#10722]
Getting the login and dashboard web pages without CSS and JS. Also getting the following error in console. Shows 404 for the CSS and JS files.

```
2016-02-01 19:37:49,378 2741 ERROR abc werkzeug: Error on request:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/Users/anshad/Desktop/Python/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/Users/anshad/Desktop/Python/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/Users/anshad/Desktop/Python/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/Users/anshad/Desktop/Python/odoo/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/Users/anshad/Desktop/Python/odoo/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/Users/anshad/Desktop/Python/odoo/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/anshad/Desktop/Python/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/Users/anshad/Desktop/Python/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/Users/anshad/Desktop/Python/odoo/addons/web/controllers/main.py", line 505, in load_locale
    addons_path = http.addons_manifest['web']['addons_path']
KeyError: 'web'
```

Same issue reported http://stackoverflow.com/questions/35122765/unable-to-run-odoo-properly-in-mac-os-x

**Comment by flotho** [comment]
it looks like the addon path is not well defined
the module web is not available.
Didi you change your repo or something else.

**Comment by anshad** [comment]
No, I didn't do anything. Just cloned, installed dependencies and run.

**Comment by Kici3jsc** [comment]
I same this error, i'm try edit permission file config"odoo-server.conf", folder addons but this error not fix :(.

**Comment by Yenthe666** [comment]
This is either a misconfiguration of the path or of the rights of the addons folders or your community apps are before your enterprise web folder.

**Comment by ishitarpanet** [comment]
![screenshot 475](https://user-images.githubusercontent.com/37014237/37163087-e20a9b58-231c-11e8-8008-7731f86507eb.png)
Just installed odoo10 and not able to load css & js (installed odoo on windows)

**Comment by tiennguyen2009** [comment]
Do you other solution? 
I tried install less and nodejs but it still 404 for all css and js. 
Thank you

**Comment by jcgdjob** [comment]
> Do you other solution?
> I tried install less and nodejs but it still 404 for all css and js.
> Thank you

Have you restart Odoo service?
