### ISSUE TITLE
[V9]Debug mode causes QWebException: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10743]
Hi,

Running on latest git pull.
One worker, 
Pass in debug mode :
```
2016-02-02 20:50:02,823 29880 ERROR manu9_prod werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 312, in checked_call
    result.flatten()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1439, in flatten
    self.response.append(self.render())
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1432, in render
    context=request.context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1070, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 254, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 297, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 448, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 489, in render_tag_set
    qwebcontext[template_attributes["set"]] = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 325, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 320, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 295, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 481, in render_tag_call_assets
    return bundle.to_html(css=css, js=js, debug=bool(qwebcontext.get('debug')), async=async, qwebcontext=qwebcontext)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 1175, in to_html
    if not self.is_css_preprocessed():
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_qweb.py", line 1351, in is_css_preprocessed
    stylesheet._content = ira_record.datas.decode('base64').decode('utf8')
QWebException: 'NoneType' object has no attribute 'decode'
```

**Comment by flotho** [comment]
filestore has disappeared. Once restored it's Ok
