### ISSUE TITLE
Method read for invoice don't work in External API

### ISSUE THREAD

**Issue by ikril** [odoo/odoo#107478]
Impacted versions: 16

Steps to reproduce: When using the External API, I try to read the invoice using the read method. But this method does not work and returns an error

Curl request: 
```
curl --request POST \
  --url http://hdm-accounting.odoo.com/xmlrpc/2/object \
  --header 'Content-Type: application/xml' \
  --data '<?xml version="1.0" encoding="utf-8"?>
<methodCall>
	<methodName>execute_kw</methodName>
	<params>
		<param>
			<value>
				<string>hdm-accounting</string>
			</value>
		</param>
		<param>
			<value>
				<int>2</int>
			</value>
		</param>
		<param>
			<value>
				<string>PASSWORD</string>
			</value>
		</param>
		<param>
			<value>
				<string>account.move</string>
			</value>
		</param>
		<param>
			<value>
				<string>read</string>
			</value>
		</param>
		<param>
			<value>
				<array>
					<data>
						<value>
							<int>55</int>
						</value>
					</data>
				</array>
			</value>
		</param>
	</params>
</methodCall>
```

```
Reponse:
<?xml version='1.0'?>
<methodResponse>
	<fault>
		<value>
			<struct>
				<member>
					<name>faultCode</name>
					<value>
						<int>1</int>
					</value>
				</member>
				<member>
					<name>faultString</name>
					<value>
						<string>Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 55

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1138, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.move(55,).asset_remaining_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 55

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1191, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.move(55,).asset_remaining_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/controllers/rpc.py", line 149, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/custom/trial/saas_trial/controllers/main.py", line 270, in _xmlrpc
    res = super(OdooRPC, self)._xmlrpc(service)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/controllers/rpc.py", line 129, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 368, in dispatch_rpc
    return dispatch(method, params)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 37, in dispatch
    res = execute_kw(db, uid, *params[3:])
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 59, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 65, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 50, in execute_cr
    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 2994, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 3133, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 5843, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1194, in __get__
    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
ValueError: Compute method failed to assign account.move(55,).asset_remaining_value
</string>
					</value>
				</member>
			</struct>
		</value>
	</fault>
</methodResponse>
```

Current behavior:

Expected behavior:

**Comment by niyasraphy** [comment]
hi @ikril ,
issue has been resolved, feel free to close the ticket
