### ISSUE TITLE
[8.0] raise Exception('Postgres subprocess %s error %s' % (args2, rc))

### ISSUE THREAD

**Issue by azeemism** [odoo/odoo#10763]
Fix for #5241
https://github.com/odoo/odoo/commit/4bd2ee1aaace8e7f6fa5621688e00dc2115fa8a7

Does not solve the problem for me. Still receiving the following error when backing up database using web/database/manager with a zip format (incl. filestore).

Popup Error:
```
Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--username=oca80', '--host=localhost', '--port=5432', '--file=/tmp/tmpKFgYwf/dump.sql', u'erp-oca80-com') error 1
```

Log Output:
```
...
2016-02-03 21:01:44,631 7879 INFO erp-oca80-com openerp.service.db: DUMP DB: erp-oca80-com format zip
2016-02-03 21:01:45,594 7879 ERROR erp-oca80-com openerp.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 745, in backup
    dump_stream = openerp.service.db.dump_db(backup_db, None, backup_format)
  File "/opt/odoo/oca80/openerp/service/db.py", line 196, in dump_db
    openerp.tools.exec_pg_command(*cmd)
  File "/opt/odoo/oca80/openerp/tools/misc.py", line 131, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--username=oca80', '--host=localhost', '--port=5432', '--file=/tmp/tmpKFgYwf/dump.sql', u'erp-oca80-com') error 1
2016-02-03 21:01:45,623 7879 INFO erp-oca80-com werkzeug: 192.168.1.105 - - [03/Feb/2016 21:01:45] "GET /web/database/backup?token=1454533304630&backup_db=erp-oca80-com&backup_format=zip&b$
2016-02-03 21:02:04,746 7884 INFO erp-oca80-com openerp.modules.loading: loading 1 modules...
...
```
Also tired @lukebranch suggestion since I am using PosgreSQL 9.4, 

```
lrwxrwxrwx 1 root   root          35 Feb  3 15:24 pg_dump -> /usr/lib/postgresql/9.4/bin/pg_dump
lrwxrwxrwx 1 root   root          38 Feb  3 15:29 pg_dumpall -> /usr/lib/postgresql/9.4/bin/pg_dumpall
```

but the issue persisted until I used @maclarensg in #5241

Modified the ` openerp/tools/misc.py ` as follows:

```
def exec_pg_command(name, *args):
    prog = find_pg_tool(name)
    env = exec_pg_environ()
    with open(os.devnull) as dn:
# default commit 4bd2ee1
# https://github.com/odoo/odoo/commit/4bd2ee1aaace8e7f6fa5621688e00dc2115fa8a7
#        args2 = (prog,) + args
#        rc = subprocess.call(args2, env=env, stdout=dn, stderr=subprocess.STDOUT)
#        if rc:
#            raise Exception('Postgres subprocess %s error %s' % (args2, rc))
#
#
# new modification maclarensg
# https://github.com/odoo/odoo/issues/5241#issuecomment-76509036
         rc = subprocess.call((prog,) + args, env=env, stdout=dn, stderr=subprocess.STDOUT)
# new modification end
```

Log Output:

```
2016-02-04 03:16:49,118 6094 INFO erp-oca80-com openerp.modules.loading: Modules loaded.
2016-02-04 03:16:56,396 6088 INFO erp-oca80-com openerp.service.db: DUMP DB: erp-oca80-com format zip
2016-02-04 03:16:56,824 6088 INFO erp-oca80-com werkzeug: 127.0.0.1 - - [04/Feb/2016 03:16:56] "GET /web/database/backup?token=1454555816583&backup_db=erp-oca80-com&backup_format=zip&backup_pwd=open3rP%40%40dm%21n HTTP/1.0" 200 -
2016-02-04 03:17:51,627 6093 INFO erp-oca80-com openerp.modules.loading: loading 1 modules...
```

Backup zip file is created:
![2016-02-03 19_54_33-database](https://cloud.githubusercontent.com/assets/10731034/12805434/342a8636-cab0-11e5-9900-38f40af8c7ca.png)

But not sure why dump file gets saved at zero bytes if I choose `pg_dump custom format (without filestore)?

Debain Jessie latest
OCA/OCB Branch 8.0 latest as of this morning

Thanks

**Comment by azeemism** [comment]
Look like the database created cannot be restored. I received the following log output when I attempted to "Backup Restore" the database erp-oca80-com to a "New database name" test-oca80-com.

```
2016-02-04 20:20:07,210 2241 INFO erp-oca80-com openerp.modules.loading: Modules loaded.
2016-02-04 20:20:16,164 2220 ERROR None openerp.http: There is no item named 'dump.sql' in the archive
Traceback (most recent call last):
  File "/opt/odoo/oca80/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/oca80/openerp/service/db.py", line 73, in dispatch
    return fn(*params)
  File "/opt/odoo/oca80/openerp/service/db.py", line 217, in exp_restore
    restore_db(db_name, data_file.name, copy=copy)
  File "/opt/odoo/oca80/openerp/service/db.py", line 237, in restore_db
    z.extractall(dump_dir, ['dump.sql'] + filestore)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1023, in extract
    member = self.getinfo(member)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'dump.sql' in the archive"
2016-02-04 20:20:16,238 2220 INFO None werkzeug: 127.0.0.1 - - [04/Feb/2016 20:20:16] "POST /web/database/restore HTTP/1.0" 500 -
2016-02-04 20:20:16,289 2220 ERROR None werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/oca80/venv_oca80/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/oca80/venv_oca80/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/oca80/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/oca80/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/oca80/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/oca80/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/oca80/venv_oca80/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/oca80/openerp/http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/oca80/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/oca80/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo/oca80/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/oca80/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/oca80/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/oca80/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 758, in restore
    request.session.proxy("db").restore(restore_pwd, new_db, data, copy)
  File "/opt/odoo/oca80/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/oca80/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/oca80/openerp/service/db.py", line 73, in dispatch
    return fn(*params)
  File "/opt/odoo/oca80/openerp/service/db.py", line 217, in exp_restore
    restore_db(db_name, data_file.name, copy=copy)
  File "/opt/odoo/oca80/openerp/service/db.py", line 237, in restore_db
    z.extractall(dump_dir, ['dump.sql'] + filestore)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1023, in extract
    member = self.getinfo(member)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'dump.sql' in the archive"
2016-02-04 20:21:08,534 2241 ERROR test-oca80-com openerp.sql_db: Programming error: relation "ir_module_module" does not exist
LINE 1: SELECT 1 FROM ir_module_module WHERE name='base' AND latest_...
                      ^
, in query SELECT 1 FROM ir_module_module WHERE name=%s AND latest_version=%s
2016-02-04 20:21:08,535 2241 WARNING test-oca80-com openerp.addons.base.ir.ir_cron: Tried to poll an undefined table on database test-oca80-com.
2016-02-04 20:21:08,536 2241 INFO ? openerp.sql_db: ConnectionPool(used=0/count=3/max=64): Closed 1 connections to 'host=localhost port=5432 user=oca80 password=xxxxxxxxxxxxxxxxx dbname=test-oca80-com'
2016-02-04 20:21:08,566 2241 INFO erp-oca80-com openerp.modules.loading: loading 1 modules...
2016-02-04 20:21:08,581 2241 INFO erp-oca80-com openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2016-02-04 20:21:09,130 2241 INFO erp-oca80-com openerp.modules.loading: loading 267 modules...
2016-02-04 20:21:09,392 2241 INFO erp-oca80-com openerp.modules.loading: 267 modules loaded in 0.26s, 0 queries
2016-02-04 20:21:09,719 2242 ERROR test-oca80-com openerp.sql_db: Programming error: relation "ir_module_module" does not exist
LINE 1: SELECT 1 FROM ir_module_module WHERE name='base' AND latest_...
```
Any ideas? Would appreciate them.

Thanks

**Comment by azeemism** [comment]
[UPDATE]
Figured out how to solve this issue. I had geospatial modules installed
https://github.com/oca/geospatial
that require the postgresql ROLE to have a SUPERUSER attribute set. I know it is not recommend for security reasons, but I don't see a way of how to workaround requiring this attribute to be set, limiting the security risk.
If you have any suggestions please let me know. Thanks

**Comment by azeemism** [comment]
Suggestions mentioned by  @J1b4y work!
https://github.com/OCA/geospatial/issues/68
```
GRANT ALL PRIVILEGES ON SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology TO role_name;
```
So there is no need to assign the database ROLE  the attribute of SUPERUSER.
