### ISSUE TITLE
[8.0] Unit test for rendering report works, but actual use fails

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#10776]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 394, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 398, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/wizard/stock_transfer_details.py", line 105, in do_detailed_transfer
    self.picking_id.do_transfer()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/stock.py", line 1462, in do_transfer
    self.pool.get('stock.move').action_done(cr, uid, todo_move_ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock_account/stock_account.py", line 272, in action_done
    res = super(stock_move, self).action_done(cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/stock.py", line 2469, in action_done
    self.write(cr, uid, ids, {'state': 'done', 'date': time.strftime(DEFAULT_SERVER_DATETIME_FORMAT)}, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo_addons/sale_picking_notification/models/models.py", line 61, in write
    picking.sale_id.notify_picking_done(picking)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo_addons/sale_picking_notification/models/models.py", line 31, in notify_picking_done
    self.message_post(**self._decide_picking_done_message_args(picking))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo_addons/sale_picking_notification/models/models.py", line 39, in _decide_picking_done_message_args
    attachment_ids=self._create_attachments(picking).ids
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo_addons/sale_picking_notification/models/models.py", line 45, in _create_attachments
    report = self.env['ir.actions.report.xml'].render_report(picking.id, 'stock.report_picking', data=None)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_actions.py", line 153, in render_report
    return self.pool['report'].get_pdf(cr, uid, res_ids, new_report, data=data, context=context), 'pdf'
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/report/models/report.py", line 242, in get_pdf
    if ids and len(ids) == 1:
TypeError: object of type 'int' has no len()
```

The problem isn't the traceback itself: it seems that `get_pdf()` in model `report` expects a list of ids, even if that list only contains one id.

The problem is that I get the error from this call:

```
report = self.env['ir.actions.report.xml'].render_report(picking.id, 'stock.report_picking', data=None)
```

This call does _not_ throw an error when running this same code through unit tests. I can't say for sure, but it seems that during unit tests, Odoo uses `get_html()` instead of `get_pdf()`:

```
    def render_report(self, cr, uid, res_ids, name, data, context=None):
        """
        Look up a report definition and render the report for the provided IDs.
        """
        new_report = self._lookup_report(cr, name)

        if isinstance(new_report, (str, unicode)):  # Qweb report
            # The only case where a QWeb report is rendered with this method occurs when running
            # yml tests originally written for RML reports.
            if openerp.tools.config['test_enable'] and not tools.config['test_report_directory']:
                # Only generate the pdf when a destination folder has been provided.
                return self.pool['report'].get_html(cr, uid, res_ids, new_report, data=data, context=context), 'html'
            else:
                return self.pool['report'].get_pdf(cr, uid, res_ids, new_report, data=data, context=context), 'pdf'
        else:
            return new_report.create(cr, uid, res_ids, data, context)
```

I run unit tests via the following command line call:

```
/opt/odoo/odoo-server/openerp-server --addons-path=/path/to/custom/addons,/opt/odoo/odoo-server/addons/ --log-level=debug --db_user=***** --db_password=************ --db_host=127.0.0.1 --db_port=54321 --test-enable -i sale_picking_notification --stop-after-init -d testing --workers=0
```

Expected behaviour:

The result of calling `ir.actions.report.xml.render_report` should be identical given identical arguments in actual use and in unit tests.

**Comment by Yenthe666** [comment]
Hi @aisopuro,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
