### ISSUE TITLE
[9.0][Fleet] Server error when opening contract for vehicle when vehicle list is groupedby

### ISSUE THREAD

**Issue by AppliedMedicalEurope** [odoo/odoo#10791]
Steps to reproduce
- Group vehicle list by any variable (e.g. location)
- Open a vehicle from the list
- In vehicle page click on 'Contract'

This produces the following error 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 959, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server\openerp\addons\web\controllers\main.py", line 892, in call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server\openerp\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\models.py", line 2059, in read_group
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\api.py", line 354, in old_api
  File "C:\Program Files (x86)\Odoo 9.0-20160122\server.\openerp\models.py", line 1921, in _read_group_process_groupby
KeyError: u'location'

**Comment by cysnake4713** [comment]
Yes, I have the same problem here, I have target the problem code in fleet.py

**Comment by Yenthe666** [comment]
Hi @AppliedMedicalEurope,

Thanks a lot for your report.
This issue has been fixed in the meanwhile so please update your Odoo source code if you still face this issue.

Regards,
Yenthe
