### ISSUE TITLE
[9.0] regression: Not possible -i twice on sales.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#10806]
Hello All.

- In odoo 9.0 try to install sales with -i command. (./odoo.py -i sale)
- Then navigate and do a sale order for example (irrelevant just to show it is ok until this moment).
- Try again tu restart with -i sale.
- You will see the error below error 1.
- Then try to start with -u sale all look ok.
- Then try to navigate again all ok again.

**Note:** I do not know if it is relevant but I only tested with enterprise.

What I expect:
---

Server with -i starts normally following the -i procedure.

What do I get:
---

Sever cannot be even used.

[1]
```
Traceback (most recent call last):
  File "/home/oem/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/oem/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/oem/Vauxoo/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/oem/Vauxoo/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/oem/Vauxoo/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/oem/Vauxoo/odoo/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/oem/Vauxoo/odoo/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/home/oem/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/oem/Vauxoo/odoo/openerp/http.py", line 1637, in dispatch
    ir_http = request.registry['ir.http']
  File "/home/oem/Vauxoo/odoo/openerp/http.py", line 360, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/home/oem/Vauxoo/odoo/openerp/modules/registry.py", line 354, in get
    update_module)
  File "/home/oem/Vauxoo/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/oem/Vauxoo/odoo/openerp/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/oem/Vauxoo/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/oem/Vauxoo/odoo/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/oem/Vauxoo/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/oem/Vauxoo/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/oem/Vauxoo/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/oem/Vauxoo/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/oem/Vauxoo/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/oem/Vauxoo/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/oem/Vauxoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oem/Vauxoo/odoo/openerp/addons/base/ir/ir_model.py", line 1074, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/home/oem/Vauxoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oem/Vauxoo/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/oem/Vauxoo/odoo/addons/sale/sale.py", line 598, in write
    lambda r: r.state == 'sale' and float_compare(r.product_uom_qty, values['product_uom_qty'], precision_digits=precision) == -1)
  File "/home/oem/Vauxoo/odoo/openerp/models.py", line 5527, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/oem/Vauxoo/odoo/addons/sale/sale.py", line 598, in <lambda>
    lambda r: r.state == 'sale' and float_compare(r.product_uom_qty, values['product_uom_qty'], precision_digits=precision) == -1)
  File "/home/oem/Vauxoo/odoo/openerp/tools/float_utils.py", line 131, in float_compare
    value2 = float_round(value2, precision_rounding=rounding_factor)
  File "/home/oem/Vauxoo/odoo/openerp/tools/float_utils.py", line 52, in float_round
    normalized_value = value / rounding_factor # normalize
ParseError: "unsupported operand type(s) for /: 'str' and 'float'" while parsing /home/oem/Vauxoo/odoo/addons/sale/sale_demo.xml:197, near
<record id="sale_order_line_15" model="sale.order.line">
            <field name="order_id" ref="sale_order_6"/>
            <field name="name">PC Assamble + 2GB RAM</field>
            <field name="product_id" ref="product.product_product_4"/>
            <field name="product_uom_qty">1</field>
            <field name="product_uom" ref="product.product_uom_unit"/>
            <field name="price_unit">750.00</field>
        </record>
```

**Comment by beledouxdenis** [comment]
Hello Nhomar,

This isn't expected to use the -i (installation) argument on a module already installed. You can only use the -u (update) parameter.

Regards,

**Comment by nhomar** [comment]
Hello Denis.

I can not disagree with you because you are the designer, not me.

But IMHO such buggy behavior bring confusion and can brake a database if the behavior is not consistent, shouln't be the -i replaced by a -u behavior when installed more ellegant.?

What about unit tests, they run correctly and consistently when -u instead -i?

What I mean is that if that is the design decision (which is good for me) what I expect is NO errors or at least a clear warning "Module already installed -i command ignored" or something like that.

Thanks.
