### ISSUE TITLE
Access rights error on mail module and multicompany

### ISSUE THREAD

**Issue by nicomacr** [odoo/odoo#1080]
Short description of the issue
On a multi-company environment there is an access right error while reading inbox.

**_Impacted versions:**_
8.0
tested in last runbot http://05847-8-0-a3f911.runbot.odoo.com/

**_Steps to reproduce:**_
You can reproduce on runbot just changing company to demo user and trying to login with demo user. 

To try it locally:
1. Create new database with demo data
2. Give admin user multicompany gruop
3. Create a new company (without parent)
4. Change demo user to this new company
5. Log in with demo user, you will get the error

**_Current behavior:**_
This is the error we got
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: res.users, Operation: read)

and the log error:
2014-07-10 13:48:23,299 5337 ERROR test_80_2 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 495, in dispatch
    result = self._call_function(*_self.params)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 308, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 685, in __call__
    return self.method(_args, *_kw)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 360, in response_wrap
    response = f(_args, *_kw)
  File "/home/nico/odoo/80/server/addons/web/controllers/main.py", line 903, in load_needaction
    return request.session.model('ir.ui.menu').get_needaction_data(menu_ids, request.context)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 787, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/nico/odoo/80/server/openerp/addons/base/ir/ir_ui_menu.py", line 343, in get_needaction_data
    res[menu.id]['needaction_counter'] = obj._needaction_count(cr, uid, dom, context=context)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/nico/odoo/80/server/openerp/addons/base/ir/ir_needaction.py", line 64, in _needaction_count
    res = self.search(cr, uid, (domain or []) + dom, limit=100, order='id DESC', context=context)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/models.py", line 1633, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/nico/odoo/80/server/addons/portal/mail_message.py", line 39, in _search
    group_ids = self.pool.get('res.users').browse(cr, uid, uid, context=context).groups_id
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/fields.py", line 671, in __get__
    return record._cache[self]
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/models.py", line 5634, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/nico/odoo/80/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/fields.py", line 56, in get
    raise self.exception
AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.users, Operation: read)')

**_Expected behavior:**_

**Comment by Yenthe666** [comment]
Hi @antillia,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by pedroporras** [comment]
![image](https://user-images.githubusercontent.com/11019468/39604144-971afa52-4ef0-11e8-89f1-ab77fa332a9f.png)
Hello
i got the same problem in odoo v10.0
