### ISSUE TITLE
I am using odoo v9 community in Ubuntu 14.04 installation is perfectly done after all works.but when i install website module of odoo and after i log out from odoo it show following error: "500: Internal Server Error" and my log:

### ISSUE THREAD

**Issue by perezarrieu** [odoo/odoo#10808]
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/controllers/main.py", line 44, in index
    return request.registry['ir.http'].reroute(first_menu.url)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_http.py", line 209, in reroute
    return self._dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_http.py", line 175, in _dispatch
    key = self.get_page_key()
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0.post20151109-py2.7.egg/openerp/addons/website/models/ir_http.py", line 94, in get_page_key
    return (self._name, "cache", request.uid, request.lang, request.httprequest.full_path)
AttributeError: 'Request' object has no attribute 'full_path'

**Comment by JKE-be** [comment]
Can you provide more info about your werkzeug version ... ?

**Comment by perezarrieu** [comment]
can you please say where i can see the folder and version number

**Comment by perezarrieu** [comment]
Opt/bitnami/python/lib/Python2.7/site-packages/werkzeug-0.8.3-py2.7.egg/werkzeug

**Comment by JKE-be** [comment]
```(9.0) odoo@jke:~/src/odoo/odoo$ python -c "import werkzeug; print werkzeug.__version__"```
0.9.6

can you update and retry ?

**Comment by perezarrieu** [comment]
can you please say me how i can update the version i am new in odoo.
i have access to console linuk but i dont know the form of update and where i take the new version .
thank for your help

**Comment by JKE-be** [comment]
you can try something like ```pip install werkzeug --upgrade```

**Comment by perezarrieu** [comment]
from console of linux when put  pip install werkzeug --upgrade show me sh: 1: pip: not found.
i have  down zip Werkzeug 0.9.6 of page of python , but i dont know how apply the change 
i can move the unzip to path in mi vps and then reboot odoo postgres this is the form

**Comment by JKE-be** [comment]
http://werkzeug.pocoo.org/docs/0.11/installation/

If You have any question, please use forum.odoo.com

It's not really an issue but a problem with your install!

Take a look in the documentation... All is describe...
