### ISSUE TITLE
[16] PoS Stripe card payment throws error when doing a refund

### ISSUE THREAD

**Issue by simmyspike** [odoo/odoo#108339]
**Impacted versions:** 
16.0-20221023 (Community Edition)

**Steps to reproduce:**
1. Setup a Stripe payment terminal to process payments.
2. Select a previous paid order and click refund.
3. From the main PoS screen (now that it has a - figure for the total) click payment
4. On the payment screen, select the Stripe card payment method
5. Click send.

**Current behavior:**
The following error is thrown:
TypeError: Cannot read properties of undefined (reading 'client_secret')
    at http://xxx/web/assets/683-e682643/point_of_sale.assets.min.js:5629:4081
    at async Proxy.collectPayment (http://xxx/web/assets/683-e682643/point_of_sale.assets.min.js:5629:2517)
    at async Proxy.send_payment_request (http://xxx/web/assets/683-e682643/point_of_sale.assets.min.js:5629:4303)
    at async PaymentScreen._sendPaymentRequest (http://xxx/web/assets/683-e682643/point_of_sale.assets.min.js:1229:234)

**Expected behavior:**
The previous transaction should be refunded.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/35277692/208549352-e975e9ec-8a5c-4907-87bb-25cbfe86aee9.png)

**Support ticket number submitted via odoo.com/help (optional):**

**Comment by simmyspike** [comment]
More info:
The Stripe API log shows that Odoo requested a payment with a negative amount (which doesn't pass validation because it should be positive) instead of requesting a refund.

**Comment by bluesprocket** [comment]
Has there been any movement on resolving this issue?  I contacted Odoo support about it a month ago, and they pointed me here.  This really needs to be addressed.  Manually refunding CC transactions for customers isn't a viable long-term solution for my business.

I was pointed towards https://github.com/odoo/odoo/commit/930b6860d7faaebe30053b9a00808aa9a1d64c13 , but that is code that was closed in May of 2022.  So clearly the issue persists.

**Comment by leimantas** [comment]
Just look how old is stripe api ODOO uses: https://github.com/odoo/odoo/blob/16.0/addons/payment_stripe/const.py#L6

**Comment by bluesprocket** [comment]
I wanted to follow up again and see if there has been any movement on this.  I do believe that there is a mechanism in the Sales app to handle refunds through Stripe, but for our workflow, it needs to also be integrated into POS directly.
