### ISSUE TITLE
[16.0] s_blog_posts not showing for not logged in users.

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#108375]
Impacted versions:
Odoo 16.0-20221216 (Community Edition)

Current behavior:

After an update to the latest docker image release, my 

standard 'Blog Posts' dynamic block on homepage works as expected for logged in users. But for not logged in users it does not show ...
There is no special configuration that would prevent from showing the blog posts
But dynamic_snippet_template div is empty.

Surfing to /blog shows the blog posts ... also as not logged in user. So they are published and available ...

```
<section data-snippet="s_dynamic_snippet" class="s_blog_posts s_dynamic_snippet_blog_posts s_blog_posts_effect_marley s_dynamic pt32 pb32 o_colored_level s_blog_post_big_picture o_dynamic_empty" data-name="Blog Posts" style="background-image: none;" data-filter-by-blog-id="-1" data-number-of-records="6" data-filter-id="2" data-template-key="website_blog.dynamic_filter_template_blog_post_big_picture" data-number-of-elements="3">
        <div class="o_not_editable container">
          <div class="css_non_editable_mode_hidden">
            <div class="missing_option_warning alert alert-info rounded-0 fade show d-none d-print-none o_default_snippet_text">
                        Your Dynamic Snippet will be displayed here... This message is displayed because you did not provided both a filter and a template to use.<br>
                    </div>
          </div>
          <div class="dynamic_snippet_template"></div>
        </div>
      </section>
```
![image](https://user-images.githubusercontent.com/50528773/208664896-1902caed-bace-4ce3-b278-1cf7704ba60e.png)

**Comment by jwaes** [comment]
Further investigation show that all dynamic blocks are not working for not logged in users ... 

so i did a /web?debug=assets

And that gives me: 

```
UncaughtPromiseError > TypeError
Uncaught Promise > this.env.services.bus_service.start is not a function
TypeError: this.env.services.bus_service.start is not a function
    at model.start (https://xxx.yyy/web/assets/debug/web.assets_backend.js:150882:46) (/mail/static/src/models/messaging_notification_handler.js:28)
    at model.start (https://xxx.yyy/web/assets/debug/web.assets_backend.js:150141:42) (/mail/static/src/models/messaging.js:215)
    at async ModelManager.start (https://xxx.yyy/web/assets/debug/web.assets_backend.js:130569:9) (/mail/static/src/model/model_manager.js:115)
```
