### ISSUE TITLE
Odoo server Start Error in v15

### ISSUE THREAD

**Issue by abdorizak** [odoo/odoo#108835]
Impacted versions: v15

Steps to reproduce:
starting error
```terminal
Traceback (most recent call last):
  File "odoo-bin", line 5, in <module>
    import odoo
  File "/Users/xman/odoo/odoo15/odoo/__init__.py", line 113, in <module>
    from . import modules
  File "/Users/xman/odoo/odoo15/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/Users/xman/odoo/odoo15/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/Users/xman/odoo/odoo15/odoo/tools/__init__.py", line 4, in <module>
    from . import _monkeypatches
  File "/Users/xman/odoo/odoo15/odoo/tools/_monkeypatches.py", line 6, in <module>
    from lxml import etree
ImportError: dlopen(/Users/xman/odooenv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): tried: '/Users/xman/odooenv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/xman/odooenv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so' (no such file), '/Users/xman/odooenv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by abdorizak** [comment]
i have Fixed this issue installing libqp ```brew install libpq``` also reinstalling crypto
