### ISSUE TITLE
odoo.py not working ? 

### ISSUE THREAD

**Issue by diwa130** [odoo/odoo#10891]
I have downloaded v9 from sources. When I run odoo.py I am getting strange errors. 
(v9dev has been already created):

thunder:/home/walter/odoo # ./odoo.py -d v9dev
Traceback (most recent call last):
  File "./odoo.py", line 160, in <module>
    main()
  File "./odoo.py", line 156, in main
    import openerp
  File "/home/walter/odoo/openerp/__init__.py", line 58, in <module>
    import modules
  File "/home/walter/odoo/openerp/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/walter/odoo/openerp/modules/graph.py", line 13, in <module>
    import openerp.osv as osv
  File "/home/walter/odoo/openerp/osv/__init__.py", line 4, in <module>
    import osv
  File "/home/walter/odoo/openerp/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/home/walter/odoo/openerp/exceptions.py", line 16, in <module>
    from tools.func import frame_codeinfo
  File "/home/walter/odoo/openerp/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/home/walter/odoo/openerp/tools/misc.py", line 16, in <module>
    import passlib.utils
ImportError: No module named passlib.utils

Any clues ? Thanks

**Comment by flotho** [comment]
running it via odoo is not enough. You need to adapt your conf file :
https://www.odoo.com/documentation/9.0/reference/cmdline.html#configuration-file

**Comment by xmo-odoo** [comment]
The configuration is not the issue here, the issue is — exactly as the traceback notes — you're missing at least one dependency, [passlib](https://pythonhosted.org/passlib/).

**Comment by flotho** [comment]
damned @xmo-odoo , I read too fast, you're right.

**Comment by diwa130** [comment]
Thanks
Walter

**Comment by stellaf** [comment]
you missing the definition of PYTHONPATH
in your /etc/profile
given
PYTHONPATH="/usr/lib/python2.7/site-packages:/opt/virtualenv/odoo10/lib/python2.7/site-packages"
export PYTHONPATH

**Comment by YnievesDotNet** [comment]
I have same problem, I try add pythonpath, but not working.

Thanks

**Comment by YnievesDotNet** [comment]
I´m getting that
The directory '/Users/ynieves/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

what i do?
