### ISSUE TITLE
[V9]Impossible to set parent_id for product category

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10916]
Hi,

Running the latest RPM.
While trying to set a parent_id to a product category I have this message :

```
Traceback (most recent call last):
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/models.py", line 3818, in write
    self._write(old_vals)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/models.py", line 4040, in _write
    position = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

It happens when trying to set parent_id to the default one already existing.
Starting with a brand new categories as parent works perfectly

**Comment by Yenthe666** [comment]
Hi @flotho,

Thanks a lot for your report.
I've just tested this for both product categories and website product categories and it works fine.
Product categories:
![image](https://user-images.githubusercontent.com/6352350/34984109-07733c3c-fab0-11e7-80a0-3c3163fb0adc.png)

Website product categories:
![image](https://user-images.githubusercontent.com/6352350/34984124-13ab0f7a-fab0-11e7-9e69-54c596e896a4.png)

Please update your source code to the latest version if you're still facing this.

Regards,
Yenthe
