### ISSUE TITLE
UncaughtPromiseError > TypeError

### ISSUE THREAD

**Issue by hbajares** [odoo/odoo#109391]
Impacted versions: odoo 16

Steps to reproduce: error appears when ever try to go setting menue 

Current behavior:

Expected behavior:

Support ticket number submitted via odoo.com/help (optional):
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'string')
TypeError: Cannot read properties of undefined (reading 'string')
    at http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6542:211
    at traverse (http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:200)
    at http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:242
    at Function.each (http://localhost:8069/web/assets/1276-0c9c794/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:211)
    at http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:242
    at Function.each (http://localhost:8069/web/assets/1276-0c9c794/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:211)
    at http://localhost:8069/web/assets/1331-989187b/web.assets_backend.min.js:6537:242
    at Function.each (http://localhost:8069/web/assets/1276-0c9c794/web.assets_common.min.js:171:149)

**Comment by qaq2010** [comment]
Facing the Same error  and got it maybe after an saily update this week.

**Comment by alssafeer** [comment]
Hi
I have same error when i go to setting 
I’m using Odoo16 last build on Ubuntu 22

regards,

**Comment by sufyanel** [comment]
Encountering the same when clicking accounting app
