### ISSUE TITLE
[9.0] In customer invoice, I cannot unreconcile payments, or cancel payments.

### ISSUE THREAD

**Issue by munawar050** [odoo/odoo#10979]
I cannot unreconcile payments, or cancel payments in odoo, it gives me following error:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_move.py", line 876, in remove_move_reconcile
    return rec_move_ids.unlink()
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_move.py", line 1264, in unlink
    for rev_move in self.env['account.move'].browse(reversed_moves):
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 5353, in browse
    ids = _normalize_ids(arg)
  File "/opt/odoo/openerp/models.py", line 6259, in _normalize_ids
    return tuple(arg)
TypeError: 'bool' object is not iterable

**Comment by nafex** [comment]
same here... tested on latest runbot v9 build. same error.

**Comment by nafex** [comment]
fixed with https://github.com/odoo/odoo/commit/a04fce47e99723cb82f023b783ae2dfab0e817f3
