### ISSUE TITLE
[8.0] ImportError: No module named osv

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#10980]
```
2016-02-18 11:00:46,137 612 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1289, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1310, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm_partner_map/__init__.py", line 23, in <module>
    import res_partner
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm_partner_map/res_partner.py", line 22, in <module>
    from osv import fields,osv
ImportError: No module named osv
```

**Comment by tvibliani** [comment]
I figured out that error is originated from a community module: [crm_partner_map](https://apps.odoo.com/apps/modules/browse?search=crm_partner_map), so I close the issue.
