### ISSUE TITLE
[16.0] _get_accounting_amounts_and_currencies does not account for multirecords

### ISSUE THREAD

**Issue by evanomnisoft** [odoo/odoo#110225]
Impacted versions:
16.0
Steps to reproduce:

Bug in latest commit to odoo 
`https://github.com/odoo/odoo/commit/3edd1b65eb67bd856ed80622d2d92056ecac2cac`

Production server on Odoo.sh is fine if we revert to a previous revision (16.0.20230101)

Current behavior:
Tracelog:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/models.py", line 5112, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 913, in onchange
    return super(BankRecWidget, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/home/odoo/src/odoo/odoo/models.py", line 6516, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/odoo/models.py", line 6227, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 665, in _onchange_todo_command
    self._ensure_loaded_lines()
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 1434, in _ensure_loaded_lines
    self.line_ids
  File "/home/odoo/src/odoo/odoo/fields.py", line 4326, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 2786, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1135, in __get__
    self.recompute(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1324, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1346, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 4196, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 229, in _compute_line_ids
    wizard._lines_widget_add_auto_balance_line()
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 1009, in _lines_widget_add_auto_balance_line
    auto_balance_line_vals = self._lines_widget_prepare_auto_balance_line()
  File "/home/odoo/src/enterprise/account_accountant/models/bank_rec_widget.py", line 962, in _lines_widget_prepare_auto_balance_line
    = self.st_line_id._get_accounting_amounts_and_currencies()
  File "/home/odoo/src/odoo/addons/account/models/account_bank_statement_line.py", line 535, in _get_accounting_amounts_and_currencies
    transaction_amount = -suspense_line.amount_currency
  File "/home/odoo/src/odoo/odoo/fields.py", line 1131, in __get__
    record.ensure_one()
  File "/home/odoo/src/odoo/odoo/models.py", line 5115, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move.line(57863, 57864, 57865, 57866, 57867, 57868, 57869, 57870, 57871, 57872, 57873, 57874, 57875, 57876, 57877, 57878, 57879, 57880, 57881, 57882, 57883, 57884, 57885, 57886, 57887, 57888, 57889, 57890, 57891, 57892, 57893, 57894, 57895, 57896, 57897, 57898, 57899, 57900, 57901, 57902, 57903, 57904, 57905, 57906, 57907, 57908, 57909, 57910, 57911, 57912, 57913, 57914, 57915, 57916, 57917, 57918, 57919, 57920, 57921, 57922, 57923, 57924, 57925, 57926, 57927, 57928, 57929, 57930, 57931, 57932, 57933, 57934, 57935, 57936, 57937, 57938, 57939, 57940, 57941, 57942, 57943, 57944, 57945, 57946, 57947, 57948, 57949, 57950, 57951, 57952, 57953, 57954, 57955, 57956, 57957, 57958, 57959, 57960, 57961, 57962, 57963, 57964)

The above server error caused the following client error:
null
```

Expected behavior:
No Error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
#3140603

**Comment by evanomnisoft** [comment]
Hi @cfarnleitner, there was not much correspondence except for a request for video which we were unable to provide due to unwillingness to disclose our client's production data. 

Anyways, we closed the because we couldn't do any further and the feedback from client was that the issue was no longer happening. Tracing the commits it seems like it may have been fixed @ https://github.com/odoo/odoo/commit/564f91be019a1f5fe737a01218972dfd9d74d7c8. Could you check if your deployment uses a version later than that and see if the issue is fixed?
