### ISSUE TITLE
While install my custom module I got "SyntaxError: Non-ASCII character" error

### ISSUE THREAD

**Issue by cundi** [odoo/odoo#11078]
Impacted versions:  

9.0 

Steps to reproduce:  

add `# -*- coding: utf-8 -*-` to model's file then run at terminal, during installing my custom module I got an error as shown in below.  

Current behavior:  

```
Odoo Server Error
Traceback (most recent call last):
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/Users/m-l/web-dev/odoo-9.0/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/m-l/web-dev/odoo-9.0/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/Users/m-l/web-dev/odoo-9.0/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/Users/m-l/web-dev/odoo-9.0/addons/ask_for_leaving/__init__.py", line 2, in <module>
    from .models import main_model
  File "/Users/m-l/web-dev/odoo-9.0/addons/ask_for_leaving/models/main_model.py", line 8
SyntaxError: Non-ASCII character '\xe7' in file /Users/m-l/web-dev/odoo-9.0/addons/ask_for_leaving/models/main_model.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Expected behavior:  

I want to show chinese character correctly.  

Video/Screenshot link (optional):  

![2016-02-24 4 20 07](https://cloud.githubusercontent.com/assets/10941075/13279406/92b917ea-db12-11e5-807c-6b4709d68d69.png)

![2016-02-24 4 20 23](https://cloud.githubusercontent.com/assets/10941075/13279415/99df3a36-db12-11e5-8788-db212603056d.png)

**Comment by lem8r** [comment]
You have to write you text like this ```u"Some text"```

**Comment by christopherdurr** [comment]
I think this issue should be closed. lem8r has answered the issue

**Comment by Yenthe666** [comment]
Hi @cundi,

The answer from @lem8r is indeed correct.
Besides, the Github tracker is only for bugs in the official code. This is not the place to ask questions about custom development, plenty of people can help you with that on the official forums (http://odoo.com/help).
Closing as the answer will solve it and it is not really a bug but more of a question.

Regards,
Yenthe
