### ISSUE TITLE
  ERISP Server Error  Traceback (most recent call last):   File "/usr/lib/python3/dist-packages/flectra/addons/web/controllers/main.py", line 2143, in report_download     report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})   File "/usr/lib/python3/dist-packages/flectra/tools/safe_eval.py", line 328, in safe_eval     c = test_expr(expr, _SAFE_OPCODES, mode=mode)   File "/usr/lib/python3/dist-packages/flectra/tools/safe_eval.py", line 184, in test_expr     code_obj = compile(expr, "", mode)   File "<string>", line 1     data(%s)' % (object.name)          ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hasnain1212** [odoo/odoo#110798]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @hasnain1212 ,
it will be nice, if you reduce the title length and add it inside the description with the steps to reproduce,
thanks

**Comment by zeroheure** [comment]
This come from Flectra, not Odoo.
