### ISSUE TITLE
local variable 'valuation_stock_moves' referenced before assignment

### ISSUE THREAD

**Issue by mohamedlaminelalmi** [odoo/odoo#110951]
https://github.com/odoo/odoo/blob/3d490a264b2fe837f9dc5138f8605f5466b7c312/addons/purchase_stock/models/account_invoice.py#L88

The variable 'valuation_stock_moves' is used before assignment and this cause the following traceback when posting an invoice:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/sale/models/account_move.py", line 63, in action_post
    res = super(AccountMove, self).action_post()
  File "/home/odoo/src/enterprise/account_accountant/models/account_move.py", line 24, in action_post
    res = super().action_post()
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 3558, in action_post
    other_moves._post(soft=False)
  File "/home/odoo/src/enterprise/sale_subscription/models/account_move.py", line 22, in _post
    posted_moves = super()._post(soft=soft)
  File "/home/odoo/src/enterprise/account_asset/models/account_move.py", line 109, in _post
    posted = super()._post(soft)
  File "/home/odoo/src/odoo/addons/sale/models/account_move.py", line 106, in _post
    posted = super()._post(soft)
  File "/home/odoo/src/odoo/addons/purchase_stock/models/account_invoice.py", line 147, in _post
    self.env['account.move.line'].create(self._stock_account_prepare_anglo_saxon_in_lines_vals())
  File "/home/odoo/src/odoo/addons/purchase_stock/models/account_invoice.py", line 86, in _stock_account_prepare_anglo_saxon_in_lines_vals
    relevant_qty = line._get_out_and_not_invoiced_qty(valuation_stock_moves)
UnboundLocalError: local variable 'valuation_stock_moves' referenced before assignment

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://abtech-0000-permanente-6963306.dev.odoo.com/web/assets/1890-c3fcdde/web.assets_backend.min.js:975:163)
    at XMLHttpRequest.<anonymous> (https://abtech-0000-permanente-6963306.dev.odoo.com/web/assets/1890-c3fcdde/web.assets_backend.min.js:982:13)

**Comment by mehjabinfarsana** [comment]
fixed by : https://github.com/odoo/odoo/commit/bbc0b003f6ff08a50196e07b66083ee7e8896150#diff-7009731267a4251a381016efa47a39ac261b2d1e4c3c8bad177bddd9a8b15182

**Comment by mohamedlaminelalmi** [comment]
@mehjabinfarsana Issue closed. Thank you :)
