### ISSUE TITLE
TypeError: BaseURL.replace() takes 1 positional argument but 3 were given - - -

### ISSUE THREAD

**Issue by ErpMstar** [odoo/odoo#111490]
Impacted versions: 14

Steps to reproduce: Wen there are multiple databases, unable to select the DB.

Current behavior: It gives the error TypeError: BaseURL.replace() takes 1 positional argument but 3 were given - - -

If I apply DB filter then it works fine.

`2023-01-31 13:50:58,397 49380 INFO ? odoo.http: HTTP Configuring static files 
2023-01-31 13:50:58,420 49380 INFO ? odoo.http: Generating nondb routing 
2023-01-31 13:50:58,440 49380 INFO ? werkzeug: 127.0.0.1 - - [31/Jan/2023 13:50:58] "GET /web?db=odoo_14_new HTTP/1.1" 500 - 1 0.001 0.037
2023-01-31 13:50:58,446 49380 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 1498, in _dispatch_nodb
    result = request.dispatch()
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 808, in dispatch
    r = self._call_function(**self.params)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 362, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/addons/web/controllers/main.py", line 892, in web_client
    ensure_db()
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/addons/web/controllers/main.py", line 163, in ensure_db
    abort_and_redirect(url_redirect)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/addons/web/controllers/main.py", line 131, in abort_and_redirect
    response = werkzeug.utils.redirect(url, 302)
  File "/home/dev/odoo_py_envs/venv_14/lib/python3.10/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/lib/python3.10/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/odoo_py_envs/venv_14/lib/python3.10/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/dev/odoo_py_envs/venv_14/lib/python3.10/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 1334, in __call__
    return self.dispatch(environ, start_response)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "/home/dev/odoo_py_envs/venv_14/lib/python3.10/site-packages/werkzeug/middleware/shared_data.py", line 287, in __call__
    return self.app(environ, start_response)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 1527, in dispatch
    result = _dispatch_nodb()
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 1500, in _dispatch_nodb
    return request._handle_exception(e)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 746, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/mnt/4dfe0a24-ea07-496a-b531-d9f9d3e880cc/home/dev/Odoo14_home/odoo-14.0/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: BaseURL.replace() takes 1 positional argument but 3 were given - - -`

**Comment by idamonli** [comment]
odoo 14~python~3.10~
me too

**Comment by ErpMstar** [comment]
I found the solution for this issue:

in the web module > controllers > main.py

find this function 
def ensure_db(redirect='/web/database/selector'):

in this function        "abort_and_redirect(url_redirect)" is called

here this "url_redirect" is causing this issue. it must be string type
so just edit the base code and use 
        abort_and_redirect(url_redirect.to_url())

this will fix the issue.

**Comment by gdgellatly** [comment]
OPW 3222058
