### ISSUE TITLE
[9.0][master][Purchase] KeyError: u'date_planned'

### ISSUE THREAD

**Issue by hip-odoo** [odoo/odoo#11195]
Steps to reproduce:
Go-to Purchase -> Requests for Quotation / Purchase Orders
Group by 'Expected Date' gives following error:

Current behavior:
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/addons/web/controllers/main.py", line 882, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/addons/web/controllers/main.py", line 874, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/models.py", line 2104, in read_group
    for gb in groupby_list
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/api.py", line 358, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/models.py", line 1970, in _read_group_process_groupby
    qualified_field = self._inherits_join_calc(self._table, split[0], query)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/134752-master-bfe7aa/openerp/models.py", line 2231, in _inherits_join_calc
    translate = model._columns[field].translate
KeyError: u'date_planned'
```

**Comment by Yenthe666** [comment]
Hi @hip-odoo,

The filter 'Expected Date' is not present in V9:
![image](https://cloud.githubusercontent.com/assets/6352350/16000001/bd52da76-3149-11e6-8c62-8f4abfa2df8f.png)

In the master version the filter is there but it works fine by now:
![image](https://cloud.githubusercontent.com/assets/6352350/16000027/e1a5684e-3149-11e6-86fd-651a646bb474.png)
Closing this issue since it has been fixed in the meanwhile.

Regards,
Yenthe
