### ISSUE TITLE
[16.0][bug] Ctrl+X in the web editor casue Uncaught Promise Cannot read properties of null (reading 'nodeName')

### ISSUE THREAD

**Issue by skygunner** [odoo/odoo#112225]
Impacted versions:
16.0 CE docker version
Odoo 16.0-20230109 (Community Edition)

Steps to reproduce:
Any multiline input, 
without selecting any content, 
press Ctrl+X

Current behavior:
In multiline in box, triggers error:
`
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of null (reading 'nodeName')
TypeError: Cannot read properties of null (reading 'nodeName')
    at OdooEditor._onClipboardCopy (https://erp.palmit.com.au/web/assets/debug/web_editor.assets_wysiwyg.js:9649:41) (/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js:3261)
    at OdooEditor._onClipboardCut (https://erp.palmit.com.au/web/assets/debug/web_editor.assets_wysiwyg.js:9638:14) (/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js:3250)
`
In some place like fast sending message input, press Ctrl+X would make the input control dead until refresh page. But here it does not
pop up error. 

Expected behavior:
Should ignore the Ctrl+X if no content is selected. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/84759/217572372-6f0abc8c-65ef-4c43-9179-a8ccf1340966.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by skygunner** [comment]
Tested the recent version https://github.com/odoo/odoo/commit/43f6ea6cc891dce8336aab221039ba75ed24e601
which seems to work fine now. So maybe this issue has been fixed already in the git. 

Hope the docker image can be updated to a newer version with this fixed
