### ISSUE TITLE
[16.0][bug] assets_backend Click show/hide call settings button in discuss gives: Uncaught Promise > Cannot read properties of undefined (reading 'enumerateDevices')

### ISSUE THREAD

**Issue by skygunner** [odoo/odoo#112255]
Impacted versions:
git branch 16.0
doesn't happen in Odoo 16.0-20230109 (Community Edition), so it could be a recent change affected it. 

Steps to reproduce:
git branch 16.0
go to discussion, select a channel, click show/hide call settings 

Current behavior:

```Python
Uncaught Promise > Cannot read properties of undefined (reading 'enumerateDevices')
TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at model._created (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10778:586)
    at ModelManager._executeCreatedRecordsCreated (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10396:148)
    at ModelManager._flushUpdateCycle (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10402:144)
    at ModelManager._executeCreatedRecordsComputes (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10394:21)
    at ModelManager._flushUpdateCycle (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10402:26)
    at ModelManager._notifyListenersInUpdateCycle (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10416:21)
    at ModelManager._flushUpdateCycle (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10402:64)
    at ModelManager.update (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10326:62)
    at model.update (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:10473:137)
    at model.onClickShowCallSettingsMenu (http://c2.com:8069/web/assets/81-cb4b529/web.assets_backend.min.js:12340:82)
```

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Armitxes** [comment]
zxing-js issue requiring SSL/HTTPS. See https://github.com/odoo/odoo/pull/112813
https://github.com/zxing-js/library/issues/225

This also blocks clipboard access (i.e. copy meeting link to clipboard)
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
