### ISSUE TITLE
Odoo Server Error.   File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 186, in __getitem__     return self.models[model_name] KeyError: None

### ISSUE THREAD

**Issue by ChayaGavali** [odoo/odoo#112606]
Why this error Occured
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "D:\pycwrk\odoo-16.0\odoo\service\model.py", line 134, in retrying
    result = func()
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "d:\pycwrk\odoo-16.0\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "D:\pycwrk\odoo-16.0\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 484, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 373, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 206, in load_module_graph
    registry.setup_models(cr)
  File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 289, in setup_models
    model._setup_fields()
  File "D:\pycwrk\odoo-16.0\odoo\models.py", line 2818, in _setup_fields
    field.setup(self)
  File "D:\pycwrk\odoo-16.0\odoo\fields.py", line 516, in setup
    self.setup_related(model)
  File "D:\pycwrk\odoo-16.0\odoo\fields.py", line 579, in setup_related
    field = model.pool[model_name]._fields.get(name)
  File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 186, in __getitem__
    return self.models[model_name]
KeyError: None

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8082/web/assets/391-ff00880/web.assets_backend.min.js:967:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8082/web/assets/391-ff00880/web.assets_backend.min.js:974:13)

py file:
from odoo import fields, models, api

class SaleOrderFields(models.Model):
    _name = 'sale.order'
    _inherit = 'sale.order'
    _description = "Sales Order"

    series           = fields.Selection([("1","EXP"),("2","LAB"),("3","MFG"),("4","WRK")],
                                        string="Order Series",
                                        required=True, copy=False, readonly=True,
                                        states={'draft': [('readonly', False)]})
    display_series   = fields.Char(related='series. display_series')

    amend_no         = fields.Integer(string="SO Amend No",
                                      _auto = "increment",
                                      _status ="inactive")

    po_no            = fields.Integer(string="PO No")

    po_date          = fields.Date(string="PO Date")

    eff_date         = fields.Date(string="Eff Date")#Action on date

    partner_code     = fields.Selection(["",""],string="Customer Code")#Customer Code

    donee_code       = fields.Selection(["",""],string="Donee Code")#Consignee Code & Name
    donee_name       = fields.Selection(related='donee_code.donee_name')

    activity         = fields.Selection([("1","Yes"),("2","No")],string="Activity")
    mode_of_dispatch = fields.Selection([("1","Sea"),("2","Air"),("3","Road")],string="Mode of Dispatch")

xml file
<odoo>
    <record id="sale_order_form_inherited" model="ir.ui.view">
        <field name="name">sale.order.form.inherit</field>
        <field name="model">sale.order</field>
        <field name="inherit_id" ref="sale.view_order_form"/>
        <field name="arch" type="xml">

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="series"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="display_series"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="amend_no"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="po_no"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="po_date"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="eff_date"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="partner_code"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="donee_code"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="donee_name"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="activity"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="mode_of_dispatch"/>
            </xpath>
        </field>
    </record>
</odoo>

**Comment by niyasraphy** [comment]
i think this is the place to report issue in the Odoo core, if you are facing issue with custom developments, you can post it in the odoo forum:  https://www.odoo.com/forum/help-1  .

for now, you can remove the _name attribute from this:

class SaleOrderFields(models.Model):
_name = 'sale.order'
_inherit = 'sale.order'


to

class SaleOrderFields(models.Model):
_inherit = 'sale.order'

**Comment by ChayaGavali** [comment]
Thank You Sir.............this is worked .
@niyasraphy

**Comment by niyasraphy** [comment]
thanks for letting me know (y)
as it is done, please close the issue ticket and try using odoo forum to get support on such issues.

this channel is to report the issues inside the odoo core :)
