### ISSUE TITLE
Invalid field account.bank.statement.move_id in leaf ('move_id.state', '=', 'posted')

### ISSUE THREAD

**Issue by filwu8** [odoo/odoo#113081]
Impacted versions:  ODOO_RELEASE=20230219
http://nightly.odoo.com/14.0/nightly/deb/odoo_14.0.20230219_all.deb

Steps to reproduce:

when i update odoo_14.0.20230219_all.deb 

it‘s error when i point and click   Outstanding Payments/Receipts  

When I downgrade using odoo_14.0.20221008_all.deb， everything is normal

How to fix？

Current behavior:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1372, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1364, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/account_reports/models/account_report.py", line 1091, in get_report_informations
    'main_html': self.get_html(options),
  File "/mnt/extra-addons/account_reports/models/account_report.py", line 1129, in get_html
    headers, lines = self._get_table(options)
  File "/mnt/extra-addons/account_reports/models/account_report.py", line 690, in _get_table
    return self.get_header(options), self._get_lines(options)
  File "/mnt/extra-addons/account_reports/models/account_bank_reconciliation_report.py", line 550, in _get_lines
    last_statement = journal._get_last_bank_statement(domain=last_statement_domain)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal.py", line 819, in _get_last_bank_statement
    last_statement = self.env['account.bank.statement'].search(last_statement_domain, order='date desc, id desc', limit=1)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4528, in _search
    query = self._where_calc(args)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4284, in _where_calc
    return expression.expression(domain, self).query
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 654, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field account.bank.statement.move_id in leaf ('move_id.state', '=', 'posted')

Expected behavior:

**Comment by guva-odoo** [comment]
Hello, please see https://github.com/odoo/enterprise/pull/33317

**Comment by filwu8** [comment]
> 

thanks,i can't open it

![image](https://user-images.githubusercontent.com/54697960/220307715-4059aa78-06bd-4327-b6f2-ee00c9d25b60.png)

**Comment by niyasraphy** [comment]
@filwu8 you need access to odoo enterprise repository to see it.
the reported issue has been already fixed in the source code, so you have to use latest odoo source code, in order to not to get this exception

**Comment by AbdelAzizMohamedMousa** [comment]
It looks like the error is being caused by an invalid field in a leaf of the query expression. Specifically, the account.bank.statement.move_id field is being used in a leaf of the query expression with the condition ('move_id.state', '=', 'posted'), which is causing the server to throw an exception.

The error seems to be originating from the account_bank_reconciliation_report module, which is attempting to retrieve the last bank statement associated with a journal. To resolve this issue, you may need to modify the module's code to use a valid field in the query expression or to modify the query expression to use a valid condition.

One thing to check is whether the move_id field is a valid field for the account.bank.statement model. If it is not, you may need to use a different field in the query expression, such as journal_id or company_id.

Another thing to check is whether the state field is a valid field for the move_id field of the account.bank.statement model. If it is not, you may need to use a different field or condition in the query expression.

Once you have identified the issue, you can modify the module's code to use a valid field or condition in the query expression. Be sure to test the modified code thoroughly before deploying it to a production environment.

**Comment by filwu8** [comment]
> It looks like the error is being caused by an invalid field in a leaf of the query expression. Specifically, the account.bank.statement.move_id field is being used in a leaf of the query expression with the condition ('move_id.state', '=', 'posted'), which is causing the server to throw an exception.
> 
> The error seems to be originating from the account_bank_reconciliation_report module, which is attempting to retrieve the last bank statement associated with a journal. To resolve this issue, you may need to modify the module's code to use a valid field in the query expression or to modify the query expression to use a valid condition.
> 
> One thing to check is whether the move_id field is a valid field for the account.bank.statement model. If it is not, you may need to use a different field in the query expression, such as journal_id or company_id.
> 
> Another thing to check is whether the state field is a valid field for the move_id field of the account.bank.statement model. If it is not, you may need to use a different field or condition in the query expression.
> 
> Once you have identified the issue, you can modify the module's code to use a valid field or condition in the query expression. Be sure to test the modified code thoroughly before deploying it to a production environment.

Thank you Very much！
