### ISSUE TITLE
permission denied in addons_path from /home/$USER folder

### ISSUE THREAD

**Issue by jherna** [odoo/odoo#113080]
Impacted versions: 16

Steps to reproduce: 
create dirs: /home/usuari/odoo/src/custom
add a new module folder: /home/usuari/odoo/src/custom/myModuleTest
with required files.

Current behavior: Odoo is running in lxc container from Ubuntu 22.04 host and guest
when I put in odoo.conf: 
addons_path = /home/usuari/odoo/src/custom

**log server:**
2023-02-18 15:16:45,193 1313 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1989, in __call__
    if self.get_static_file(httprequest.path):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1895, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1864, in statics
    for module in os.listdir(addons_path):
PermissionError: [Errno 13] Permission denied: '/home/usuari/odoo/src/custom'

**But, If I put my addons folder on /opt/odoo/custom then odoo works fine!**

**Comment by AbdelAzizMohamedMousa** [comment]
The issue is caused by the lack of permissions to access the /home/usuari/odoo/src/custom folder. The user running the Odoo server does not have the necessary permissions to access this folder.

To fix the issue, you can try changing the permissions of the folder using the following command:
`sudo chown -R odoo:odoo /home/usuari/odoo/src/custom
`
This command will change the ownership of the folder and its contents to the user and group odoo, which should have the necessary permissions to access the folder.

Alternatively, you can add the user running the Odoo server to the group that owns the custom folder using the following command:
`sudo usermod -a -G <group_name> <user_name>
`
Replace <group_name> with the name of the group that owns the custom folder, and <user_name> with the name of the user running the Odoo server.

After making the necessary changes, restart the Odoo server and try accessing the module again.

**Comment by jherna** [comment]
Thanks Abdel but I've already tried it and the error was the same. I've tried one more time and the same.
With chown or with usermod, the ownership, group and user, of my folder addons is odoo

Another idea?
Thanks a lot!
