### ISSUE TITLE
  File "src\lxml\etree.pyx", line 3633, in lxml.etree._Validator.assert_ AssertionError: Element odoo has extra content: record, line 3

### ISSUE THREAD

**Issue by ChayaGavali** [odoo/odoo#113089]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "D:\pycwrk\odoo-16.0\odoo\service\model.py", line 134, in retrying
    result = func()
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "d:\pycwrk\odoo-16.0\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_upgrade
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 678, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "D:\pycwrk\odoo-16.0\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 373, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "D:\pycwrk\odoo-16.0\odoo\tools\convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "D:\pycwrk\odoo-16.0\odoo\tools\convert.py", line 812, in convert_xml_import
    relaxng.assert_(doc)
  File "src\lxml\etree.pyx", line 3633, in lxml.etree._Validator.assert_
AssertionError: Element odoo has extra content: record, line 3

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:967:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:974:13)

<?xml version="1.0" encoding="UTF-8"?>
<odoo>
 <record id="purchase_order_form_inherited" model="ir.ui.view">
        <fields name="name">purchase.order.form.inherit</fields>
        <fields name="model">purchase.order</fields>
        <fields name="inherit_id" ref="purchase.purchase_order_form"/>
        <fields name="arch" type="xml">

            <xpath expr="//field[@name='partner_id']" position="before">
            <field name="series_code"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="customer_code"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="customer_desc"/>
            </xpath>

            <xpath expr="//field[@name='partner_id']" position="after">
            <field name="activity"/>
            </xpath>

        </fields>
 </record>

 <record id="purchase_order_gst_form_view">
     <field name="name">purchase.order.gsr.form.view</field>
        <field name="model">purchase.order</field>
        <field name="inherit_id" ref="purchase.purchase_order_form"/>
        <field name="arch" type="xml">
             <xpath expr="//field[@name='job_id']" position="after">
             <field name="packing_amt"/>
             </xpath>
        </field>
 </record>
</odoo>

**Comment by AbdelAzizMohamedMousa** [comment]
The error message you are seeing indicates that there is an issue with the XML file that you are trying to load into Odoo. Specifically, it appears that there is an extra record element in the XML file that is causing the validation to fail.

To fix the issue, you will need to remove the extra record element from the XML file. The exact location of the element may vary depending on the structure of your file, but based on the error message, it seems that the issue is on line 3 of the XML file.

Here's an example of what your corrected XML file may look like after removing the extra record element: 
`<purchase.order form inherit="purchase.order">
    <xpath expr="//button[@name='action_confirm']" position="before">
        <button name="action_approve" string="Approve" type="object" class="btn-primary"/>
    </xpath>
</purchase.order>
` 
Make sure to save the corrected XML file and try loading it into Odoo again. If you continue to experience issues, you may want to double-check the overall structure of your XML file to ensure that it conforms to the Odoo schema.

**Comment by ChayaGavali** [comment]
thank you.............
