### ISSUE TITLE
[16.0][Bug] Odoo 16 docker + Enterprise cannot activate Accounting module

### ISSUE THREAD

**Issue by skasidej** [odoo/odoo#113095]
I've just recently install a brand new Odoo Enterprise 16, a fresh start.
Then trying to activate Accounting module, but instead got this below error.

Odoo version is 16 (docker)
Odoo Enterprise is 16 (freshly cloned)
Nothing wrong with any `addons_path`, or database.

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/account_accountant/views/bank_rec_widget_views.xml:538
Invalid view account.move.line.list.bank_rec_widget definition in account_accountant/views/bank_rec_widget_views.xml

View error context:
'-no context-'


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/150-f113849/web.assets_backend.min.js:974:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/150-f113849/web.assets_backend.min.js:981:13)
```

I have tried to trace back to `bank_rec_widget_views.xml` then commented out the whole record tag with id `view_account_move_line_list_bank_rec_widget`. Miraculously everything went smoothly. Has anyone
every had this kind of problem before ?

**Comment by skasidej** [comment]
I really need some help with this, since it's happening when initiating a clean project.

**Comment by niyasraphy** [comment]
hi,
with latest odoo source code, i couldnt reproduce the same in my side,
can you confirm that whether you are using the latest source code of 16

**Comment by skasidej** [comment]
@niyasraphy I'm currently running it on docker with fully access on enterprise modules, and also `web_enterprise` module is already installed.

<img width="444" alt="Screen Shot 2566-02-22 at 13 31 07" src="https://user-images.githubusercontent.com/22665150/220541198-05b12f47-e4fb-4a5b-a144-debb3fe200fd.png">

**Comment by skasidej** [comment]
It seems like there was really a bug somewhere inside the code in older version. The problem disappeared after I've pulled an updated version of Odoo official image, and re-build it again 😑.
