### ISSUE TITLE
[8.0] Error 500 after website Sign up with no Portal

### ISSUE THREAD

**Issue by paolovalier** [odoo/odoo#11314]
**Impacted versions**: 8.0 latest

**Steps to reproduce**: clean installation, install website and let public users Sign up in the website. When a public user sign up, he gets redirected to [mydomain.com/web?](url) but this returns a blank page with Error 500: Internal Server Error. If I go to mydomain.com the user is logged in correctly.
If I activate Portal the user can access to [mydomain.com/web?](url) with no problem
This happens on runbot.odoo.com too

**Current behavior**: 
- It redirect to [mydomain.com/web?](url)
- the page [mydomain.com/web?](url) responds with an Internal Server Error.
 
**Expected behavior**: 
- It should redirect to [mydomain.com/](url)
- In [mydomain.com/web?](url) should tell something "You don't have to right to access this page"

**Error in the Log file**:

2016-03-12 16:40:50,403 11164 ERROR odoo8-demo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/odoo8/OCB/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo8/OCB/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1292, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1266, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo8/OCB/openerp/http.py", line 1439, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo8/OCB/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo8/OCB/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo8/OCB/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo8/OCB/openerp/http.py", line 668, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo8/OCB/openerp/http.py", line 686, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo8/OCB/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo8/OCB/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo8/OCB/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo8/OCB/addons/web/controllers/main.py", line 477, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, context=request.context)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in load_menus
    
  File "/opt/odoo8/OCB/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_ui_menu.py", line 389, in load_menus
    menu_root_ids = self.get_user_roots(cr, uid, context=context)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_ui_menu.py", line 363, in get_user_roots
    return self.search(cr, uid, menu_domain, context=context)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/addons/mail/mail_group_menu.py", line 42, in search
    context=context, count=False)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_ui_menu.py", line 117, in search
    limit=None, order=order, context=context, count=False)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/models.py", line 1646, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/models.py", line 4667, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo8/OCB/openerp/models.py", line 3505, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/odoo8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
    
  File "/opt/odoo8/OCB/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo8/OCB/openerp/addons/base/ir/ir_model.py", line 769, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Human Resources/Employee\n\t- Administration/Settings\n\n(Document model: ir.ui.menu)')

**Comment by tafaRU** [comment]
@paolovalier, you need to thick **Activate the customer portal** on Settings >> General Settings menu.
This will imply the installation of the portal module. In this way the error shouldn't be raised again.
Please have a look at it.

**Comment by paolovalier** [comment]
@tafaRU you all right
but we wouldn't like to use the portal, I mean we don't need it and don't want the customer to be redirected there when he signup. 
when the customer register a new user during the checkout process he gets redirected to the checkout page (as a logged user) and that's fine, but when he registers from domain.com/web/signup he gets redirected to the portal and that's our problem, we would like instead he would be redirected to some kind of confirmation page or something like the homapage

**Comment by paolovalier** [comment]
we are gonna install the oca module website_portal_sale
this way we have the informations we usually get in portal (like orders, payments and so on, except the discussion feature) presented in the website at the page domain.com/my/home
