### ISSUE TITLE
[16.0][bug] web assets js: login via mobile browser welcomed by 2 js exceptions, 'registerToImStatus is not a function', followed by 'Cannot read properties of undefined (reading 'apply')', discussion won't load

### ISSUE THREAD

**Issue by skygunner** [odoo/odoo#113142]
Impacted versions:
24152884-16-0-all.runbot160 and 
github 16.0 branch on commit 5e505d909784f98a5097443968e3f4c29c9ef9e1

Steps to reproduce:
login in using mobile browser like chrome/brace

Current behavior:
first exception:
`UncaughtPromiseError > TypeError
Uncaught Promise > this.env.services.im_status.registerToImStatus is not a function
TypeError: this.env.services.im_status.registerToImStatus is not a function
    at model.updateImStatusRegistration (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:11774:32)
    at model.start (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:11781:47)
    at async model.start (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:11770:366)
    at async ModelManager.start (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:10312:151)`

After close this error, 
it is followed by:
`UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of undefined (reading 'apply')
TypeError: Cannot read properties of undefined (reading 'apply')
    at Class._trigger_up (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:5696:87)
    at Class.trigger_up (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:5879:280)
    at Class.call (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:5932:372)
    at Class.<anonymous> (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:15165:325)
    at Class.trigger (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:5873:180)
    at Class.trigger (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:5879:148)
    at owl.EventBus.<anonymous> (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:6690:254)
    at owl.EventBus.trigger (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:1534:63)
    at WebClient.<anonymous> (https://localhost/web/assets/878-0b9303d/web.assets_backend.min.js:6169:349)
    at MountFiber.complete (https://localhost/web/assets/817-b7813af/web.assets_common.min.js:1489:183)`

Happens every time. 

Expected behavior:
Seems the web assets js have a lot of bugs. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/84759/220124612-dbbff504-9e0c-4012-b9ff-1f3b4fedb3ec.png)

![image](https://user-images.githubusercontent.com/84759/220124674-726be8e9-1194-46ad-80a3-184a13d536eb.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by skygunner** [comment]
Does not happen when login using desktop browser, nor for 15.0 branch.

**Comment by mardisiaw** [comment]
Its also happen using desktop safari, chrome browser for 16.0 branch.
Exception:
```
TypeError: this.env.services['im_status'].registerToImStatus is not a function. (In 'this.env.services['im_status'].registerToImStatus('res.partner',partnerIds)', 'this.env.services['im_status'].registerToImStatus' is undefined)
    updateImStatusRegistration@https://myodoo.org/web/assets/19821-2374aaa/web.assets_backend.min.js:11775:50
    updateImStatusRegistration@[native code]
    @https://myodoo.org/web/assets/19821-2374aaa/web.assets_backend.min.js:11782:73
    asyncFunctionResume@[native code]
    @[native code]
    promiseReactionJobWithoutPromise@[native code]
    promiseReactionJob@[native code]
```

**Comment by certiz** [comment]
Guy I did have the same problem with a Honeywell PDA. I updated all the apps in the PDA and ir started to work.

**Comment by pkleineberg** [comment]
Same Problem here... :-/ 
Even an update didn't solve the problem. Other suggestions? :-)

**Comment by matijamandic-sc** [comment]
Having the same issue for a CLient, Discuss not working - infinite loading. While on iOS works flawlessy, no issues.

**Comment by yediel** [comment]
Same issue for my customer - on all android phones.
Fixed by downgrading to 16.0.20230213

**Comment by matijamand** [comment]
> Same issue for my customer - on all android phones. Fixed by downgrading to 16.0.20230213

Any specific commit you went for or just the latest on 13.02.2023?

**Comment by yediel** [comment]
@matijamand latest - downgraded on Odoo.sh settings page

**Comment by pkleineberg** [comment]
Has this bug now been fixed? Would like to enable automatic update again...

**Comment by skygunner** [comment]
> Has this bug now been fixed? Would like to enable automatic update again...

I think it's a bad idea to auto update in 16 without prior testing for your production instance, as v16 is basically a development branch, things change a lot and things break time to time, sometimes very bad.

Might be ok  to auto update in branch 14, 15 though.
