### ISSUE TITLE
email reception fails

### ISSUE THREAD

**Issue by TheTesla** [odoo/odoo#1134]
on ubuntu 14.04 (64 bit) server, odoo v8.0rc1:

I chosed my own dovecot as incoming imap-server, test works, after "fetch mail" I got the following output on the terminal and no mail appears in Messaging->Inbox:

Debug log:

2014-07-13 14:47:30,505 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:47:30] "POST /longpolling/poll HTTP/1.1" 200 -
2014-07-13 14:47:33,942 9002 INFO entroserv openerp.addons.fetchmail.fetchmail: start checking for new emails on imap server owndovecot
2014-07-13 14:47:34,004 9002 ERROR entroserv openerp.addons.fetchmail.fetchmail: Failed to process mail from imap server owndovecot.
Traceback (most recent call last):
  File "/home/stefan/odoo/addons/fetchmail/fetchmail.py", line 207, in fetch_mail
    context=context)
  File "/home/stefan/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/stefan/odoo/addons/mail/mail_thread.py", line 1157, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/home/stefan/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/stefan/odoo/addons/mail/mail_thread.py", line 1042, in message_route
    update_author=True, assert_model=True, context=context)
  File "/home/stefan/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/stefan/odoo/addons/mail/mail_thread.py", line 821, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2014-07-13 14:47:34,007 9002 INFO entroserv openerp.addons.fetchmail.fetchmail: Fetched 1 email(s) on imap server owndovecot; 0 succeeded, 1 failed.
2014-07-13 14:47:34,036 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:47:34] "POST /web/dataset/call_button HTTP/1.1" 200 -
2014-07-13 14:47:34,446 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:47:34] "POST /web/dataset/call_kw/fetchmail.server/search_read HTTP/1.1" 200 -
2014-07-13 14:47:34,832 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:47:34] "POST /web/menu/load_needaction HTTP/1.1" 200 -
2014-07-13 14:47:35,272 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:47:35] "POST /web/dataset/search_read HTTP/1.1" 200 -
2014-07-13 14:47:53,200 9002 DEBUG ? openerp.service.server: cron1 polling for jobs
2014-07-13 14:47:53,200 9002 DEBUG ? openerp.service.server: cron1 polling for jobs

**Comment by Atheryl** [comment]
I have the exact same problem, how did you managed to fix it ?

**Comment by sraps** [comment]
Actually I did not.

**Comment by Atheryl** [comment]
You use a manual installation ?

I'm wondering if it's coming from the bitnami stack.

**Comment by sraps** [comment]
mm, manual installation? what do you mean?

**Comment by Atheryl** [comment]
I just meant, you install it by yourself directly from the source, following the step by step installation or you use any one-click stack ?

Thank you for your quick replies.

**Comment by sraps** [comment]
From sources.

**Comment by mcojocaru** [comment]
Fixed with the patch below, pull request coming soon

```
diff --git a/addons/mail/mail_message.py b/addons/mail/mail_message.py
index 455dae7..cc9f521 100644
--- a/addons/mail/mail_message.py
+++ b/addons/mail/mail_message.py
@@ -758,7 +758,7 @@ class mail_message(osv.Model):
 
         # Calculate remaining ids: if not void, raise an error
         other_ids = other_ids.difference(set(document_related_ids))
-        if not other_ids:
+        if not document_related_ids or not other_ids:
             return
         raise orm.except_orm(_('Access Denied'),
                              _('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: %s, Operation: %s)') %
diff.patch (END)
```

**Comment by mcojocaru** [comment]
created PR #6196

**Comment by Yajo** [comment]
Duplicates #3735 #9795

**Comment by Yenthe666** [comment]
Hi @TheTesla ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
