### ISSUE TITLE
JSON 404

### ISSUE THREAD

**Issue by TheTesla** [odoo/odoo#1135]
ubuntu 14.04 (64 bit) server, odoo v8.0rc1:

Repeating error message on terminal, no noticable malfunction:
```
2014-07-13 14:49:15,197 9002 INFO entroserv werkzeug: 10.8.0.6 - - [13/Jul/2014 14:49:15] "POST /web/dataset/search_read HTTP/1.1" 200 -
2014-07-13 14:49:31,011 9002 ERROR entroserv openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/stefan/odoo/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/stefan/odoo/openerp/addons/base/ir/ir_http.py", line 109, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/home/stefan/odoo/openerp/addons/base/ir/ir_http.py", line 60, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
```

**Comment by yostashiro** [comment]
I also get the same error and haven't been able to identify what is causing this.  I'm using the code from 17 Feb 2015.

**Comment by codenpk** [comment]
2015-07-10 12:45:41,549 30085 ERROR evaluate openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by flotho** [comment]
Hi,
Same thing here, more precisely it's reproductible in multi-workers env and longpolling conf.
regards

**Comment by codenpk** [comment]
Hi Guys, 

I was able to come out of this error. 

After getting this error, I ran odoo.py multiple times.
It showed me few errors every time I ran. After I fixed them all, Website resumed normally.

**Comment by Danisan** [comment]
codenpk, what you mean multiple times?

**Comment by ElTorterol** [comment]
Hi codenpk,
I'm new on Odoo and Python, ( sorry if this question is so obvious )... 
... please can you give me more details about how to 'RAN' odoo.py, in order to try to apply your solution proposal for this bug?

**Comment by codenpk** [comment]
I meant running cmdline odoo.py without any options and observing the errors in the log file.
https://www.odoo.com/documentation/8.0/reference/cmdline.html.

**Comment by reggievaldez** [comment]
Hi! I am also experiencing this error:

Steps to replicate:
1.) Install Odoo via the V8 repo (May 27, 2016)
2.) Run Odoo via:
/opt/odoo/server/openerp-server --addons-path=/opt/odoo/server/openerp/addons,/opt/odoo/server/addons,/opt/odoo/custom -u all -d dbname_test
3.) Import warehouses
4.) Sample file content for import:
![snip20160527_4](https://cloud.githubusercontent.com/assets/6396381/15612299/c4ae8392-2460-11e6-9d4e-0dabab3dbdc7.png)
The file is in CSV format.
5.) Click the validate button

Though the excel file has only 159 rows, the importing is just showing the loading screen and issues the aforementioned error.

**Comment by Yenthe666** [comment]
Hi @TheTesla,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
