### ISSUE TITLE
Datetime:hour filter causes JS traceback

### ISSUE THREAD

**Issue by TFqoc** [odoo/odoo#113792]
Impacted versions:
v15, haven't tested v16 yet

Steps to reproduce:
Use any list view filter grouped by datetime_field:hour. My example was the following filter:
<filter string="Creation Date" name="create_date" domain="[]" context="{'group_by': 'create_date:hour'}"/>
Works perfectly fine if using :day

Current behavior:
Traceback with debug=assets
TypeError: Cannot read properties of undefined (reading 'description')
    at ControlPanelModelExtension._getFacetDescriptions (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:45634:87)
    at https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:45662:37 (/web/static/src/legacy/js/control_panel/control_panel_model_extension.js:1164)
    at Array.map (<anonymous>) (/web/static/src/legacy/js/control_panel/control_panel_model_extension.js:1192)
    at ControlPanelModelExtension._getFacets (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:45661:46) (/web/static/src/legacy/js/control_panel/control_panel_model_extension.js:1191)
    at ControlPanelModelExtension.get (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:44663:44) (/web/static/src/legacy/js/control_panel/control_panel_model_extension.js:193)
    at ActionModel._getFacets (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:63555:47) (/web/static/src/legacy/js/views/action_model.js:124)
    at ActionModel.get (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_backend.js:63502:44) (/web/static/src/legacy/js/views/action_model.js:71)
    at QWeb.eval (eval at _compile (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_common.js:10272:28), <anonymous>:13:31) (/web/static/lib/owl/owl.js:1786)
    at QWeb.fn (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_common.js:10152:45) (/web/static/lib/owl/owl.js:1666)
    at QWeb.render (https://qoc-innovations-node-test1-staging-7178392.dev.odoo.com/web/assets/debug/web.assets_common.js:10202:32) (/web/static/lib/owl/owl.js:1716)

Expected behavior:
No traceback

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Additional notes:

Although :hour is not documented in the docstring of read_group, [this issue](https://github.com/odoo/odoo/issues/11936) added the :hour grouping back in 2018. It is also used in the helpdesk module [here](https://github.com/odoo/enterprise/blob/15.0/helpdesk/models/helpdesk.py#L311) and I imagine I would get the same error for that view, though I'm not familiar enough with the helpdesk app to figure out the test case.

**Comment by AbdelAzizMohamedMousa** [comment]
Based on the error message you provided, it seems that there is an issue with the ControlPanelModelExtension in the web/static/src/legacy/js/control_panel/control_panel_model_extension.js file. It looks like the _getFacetDescriptions method is trying to read the description property of an undefined object, which is causing the error.

One potential solution is to modify the _getFacetDescriptions method to check whether the object is defined before trying to access its properties. Here's an example of how you could modify the method:
`_getFacetDescriptions: function (facets) {
    var self = this;
    return _.map(facets, function (facet) {
        var desc = {
            id: facet.id,
            name: facet.string,
            type: facet.type,
            icon: self._facetIcons[facet.type],
        };
        if (facet.description) {
            desc.description = facet.description;
        }
        return desc;
    });
},
`

In this modified version of the method, the if (facet.description) statement checks whether the description property is defined before trying to assign it to the desc object.

I hope this helps! If you have any further questions or if this solution doesn't work for you, please let me know.

**Comment by vava-odoo** [comment]
Hello @TFqoc,

You're right: the documentation (docstring) says:

> Right now, the only supported granularities are 'day', 'week', 'month', 'quarter' or 'year', and they only make sense for date/datetime fields.

The commit/PR you mentioned is not the right repository.
So I'm afraid this is not supported.

Regards
