### ISSUE TITLE
[9.0] project, web_planner dependency issue

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#11408]
Impacted versions: 9.0

Steps to reproduce: Install web_planner, write some data, next day update odoo with git pull, try to update db with -u all

Current behavior:
Traceback (most recent call last):
  File "/opt/workspace/Odoo9env/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/opt/workspace/Odoo9env/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/workspace/odoo9/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/opt/workspace/odoo9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/workspace/odoo9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/workspace/odoo9/openerp/http.py", line 1488, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/workspace/odoo9/openerp/http.py", line 1462, in **call**
    return self.app(environ, start_wrapped)
  File "/opt/workspace/Odoo9env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "/opt/workspace/odoo9/openerp/http.py", line 1637, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/workspace/odoo9/openerp/http.py", line 360, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/workspace/odoo9/openerp/modules/registry.py", line 355, in get
    update_module)
  File "/opt/workspace/odoo9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/workspace/odoo9/openerp/modules/loading.py", line 365, in load_modules
    registry['ir.model.data']._process_end(cr, SUPERUSER_ID, processed_modules)
  File "/opt/workspace/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo9/openerp/addons/base/ir/ir_model.py", line 1280, in _process_end
    self.pool[model].unlink(cr, uid, [res_id], context=context)
  File "/opt/workspace/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo9/openerp/addons/base/ir/ir_ui_menu.py", line 146, in unlink
    result = super(ir_ui_menu, self).unlink(cr, uid, ids, context=context)
  File "/opt/workspace/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo9/openerp/models.py", line 3658, in unlink
    'where id IN %s', (sub_ids,))
  File "/opt/workspace/odoo9/openerp/sql_db.py", line 141, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/workspace/odoo9/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: FEHLER:  NULL-Wert in Spalte „menu_id“ verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (2, null, 1, 2016-03-11 17:02:30.456223, Project Management planner, planner_project, 546, 1, 2016-03-18 09:56:57.173091, t, 7, null, <p>Learn how to better organize your company using Projects, Tas...).
KONTEXT:  SQL-Anweisung „UPDATE ONLY "public"."web_planner" SET "menu_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "menu_id"“

Expected behavior:
update all without errors

Same with that records in odoo9/addons/project/project_data.xml
https://github.com/odoo/odoo/blob/9.0/addons/project/project_data.xml#L112-L333

When you have delete this projects or set them to done, I get following errors:

openerp.tools.convert.ParseError
ParseError: "Datensatz existiert nicht oder kann nicht gefunden werden.
None" while parsing /opt/odoo9/addons/project/project_data.xml:145, near
<record id="project_task_data_0" model="project.task">
            <field name="sequence">1</field>
            <field name="user_id" ref="base.user_root"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_data"/>
            <field name="name">Welcome to Odoo</field>
            <field name="description">Welcome! This project has the objective to show you all the main feature in the project app. Each card will help you to manage your projects easily in a few minutes.</field>
            <field name="color">2</field>
            <field name="stage_id" ref="project_stage_data_0"/>
        </record>

Traceback (most recent call last)
File "/opt/odoo9/openerp/service/wsgi_server.py", line 184, in application
return application_unproxied(environ, start_response)
File "/opt/odoo9/openerp/service/wsgi_server.py", line 170, in application_unproxied
        del threading.current_thread().dbname

```
with openerp.api.Environment.manage():
    # Try all handlers until one returns some result (i.e. not None).
    for handler in [wsgi_xmlrpc, openerp.http.root]:
        result = handler(environ, start_response)
        if result is None:
            continue
        return result

# We never returned from the loop.
```

File "/opt/odoo9/openerp/http.py", line 1488, in **call**
return self.dispatch(environ, start_response)
File "/opt/odoo9/openerp/http.py", line 1462, in **call**
return self.app(environ, start_wrapped)
File "/opt/odooEnv/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in **call**
return self.app(environ, start_response)
File "/opt/odoo9/openerp/http.py", line 1637, in dispatch
ir_http = request.registry['ir.http']
File "/opt/odoo9/openerp/http.py", line 360, in registry
return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
File "/opt/odoo9/openerp/modules/registry.py", line 355, in get
update_module)
File "/opt/odoo9/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo9/openerp/modules/loading.py", line 334, in load_modules
force, status, report, loaded_modules, update_module)
File "/opt/odoo9/openerp/modules/loading.py", line 237, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/opt/odoo9/openerp/modules/loading.py", line 156, in load_module_graph
_load_data(cr, module_name, idref, mode, kind='data')
File "/opt/odoo9/openerp/modules/loading.py", line 98, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/opt/odoo9/openerp/tools/convert.py", line 851, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/opt/odoo9/openerp/tools/convert.py", line 938, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/opt/odoo9/openerp/tools/convert.py", line 801, in parse
self.parse(rec, mode)
File "/opt/odoo9/openerp/tools/convert.py", line 804, in parse
self._tags[rec.tag](self.cr, rec, de, mode=mode)
File "/opt/odoo9/openerp/tools/convert.py", line 708, in _tag_record
id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
File "/opt/odoo9/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo9/openerp/addons/base/ir/ir_model.py", line 1142, in _update
res_id = model_obj.create(cr, uid, values, context=context)
File "/opt/odoo9/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo9/addons/project/project.py", line 656, in create
task_id = super(task, self).create(cr, uid, vals, context=create_context)
File "/opt/odoo9/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo9/openerp/api.py", line 354, in old_api
result = method(recs, _args, *_kwargs)
File "/opt/odoo9/addons/mail/models/mail_thread.py", line 232, in create
thread = super(MailThread, self).create(values)
File "/opt/odoo9/openerp/api.py", line 248, in wrapper
return new_api(self, _args, *_kwargs)
File "/opt/odoo9/openerp/models.py", line 4115, in create
vals = self._add_missing_default_values(vals)
File "/opt/odoo9/openerp/api.py", line 248, in wrapper
return new_api(self, _args, *_kwargs)
File "/opt/odoo9/openerp/api.py", line 490, in new_api
result = method(self._model, cr, uid, _args, *_old_kwargs)
File "/opt/odoo9/openerp/models.py", line 1775, in _add_missing_default_values
defaults = self.default_get(cr, uid, list(missing_defaults), context)
File "/opt/odoo9/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo9/openerp/api.py", line 354, in old_api
result = method(recs, _args, *_kwargs)
File "/opt/odoo9/openerp/models.py", line 1326, in default_get
defaults[name] = field.default(self)
File "/opt/odoo9/openerp/fields.py", line 90, in <lambda>
value(model._model, model._cr, model._uid, model._context),
File "/opt/odoo9/addons/project/project.py", line 481, in <lambda>
'partner_id': lambda self, cr, uid, ctx=None: self._get_default_partner(cr, uid, context=ctx),
File "/opt/odoo9/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo9/addons/project/project.py", line 351, in _get_default_partner
if project and project.partner_id:
File "/opt/odoo9/openerp/fields.py", line 834, in __get__
return record._cache[self]
File "/opt/odoo9/openerp/models.py", line 6104, in __getitem__
return value.get() if isinstance(value, SpecialValue) else value
File "/opt/odoo9/openerp/fields.py", line 39, in get
raise self.exception
ParseError: "Datensatz existiert nicht oder kann nicht gefunden werden. None" while parsing /opt/odoo9/addons/project/project_data.xml:145, near <record id="project_task_data_0" model="project.task"> <field name="sequence">1</field> <field name="user_id" ref="base.user_root"/> <field name="priority">0</field> <field name="project_id" ref="project.project_project_data"/> <field name="name">Welcome to Odoo</field> <field name="description">Welcome! This project has the objective to show you all the main feature in the project app. Each card will help you to manage your projects easily in a few minutes.</field> <field name="color">2</field> <field name="stage_id" ref="project_stage_data_0"/> </record>
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by dynapps** [comment]
Anybody found a workaround or bugfix for this?

I have the same error (but in english)
client_660 openerp.modules.registry: Failed to load registryTraceback (most recent call last):
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/modules/loading.py", line 372, in load_modules
registry['ir.model.data']._process_end(cr, SUPERUSER_ID, processed_modules)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/addons/base/ir/ir_model.py", line 1318, in _process_end
self.pool[model].unlink(cr, uid, [res_id], context=context)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 146, in unlink
result = super(ir_ui_menu, self).unlink(cr, uid, ids, context=context)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/models.py", line 3694, in unlink
'where id IN %s', (sub_ids,))
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/sql_db.py", line 141, in wrapper
return f(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/sql_db.py", line 220, in execute
res = self._obj.execute(query, params)
IntegrityError: null value in column "menu_id" violates not-null constraint
DETAIL: Failing row contains (4, null, 1, 2017-04-25 07:19:17.668005, Project Management planner, planner_project, 879, 1, 2017-04-25 07:19:17.668005, t, 7, null, <p>Learn how to better organize your company using Projects, Tas...).
CONTEXT: SQL statement "UPDATE ONLY "public"."web_planner" SET "menu_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "menu_id""

**Comment by PieterAdriaensen** [comment]
Anybody found a workaround or bugfix for this?

I have the same error (but in english):

client_660 openerp.modules.registry: Failed to load registryTraceback (most recent call last):
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/modules/loading.py", line 372, in load_modules
registry['ir.model.data']._process_end(cr, SUPERUSER_ID, processed_modules)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/addons/base/ir/ir_model.py", line 1318, in _process_end
self.pool[model].unlink(cr, uid, [res_id], context=context)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 146, in unlink
result = super(ir_ui_menu, self).unlink(cr, uid, ids, context=context)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/models.py", line 3694, in unlink
'where id IN %s', (sub_ids,))
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/sql_db.py", line 141, in wrapper
return f(self, *args, **kwargs)
File "/opt/odoo/buildouts/client/revert-ef58f72c/revert-ef58f72c/parts/odoo/openerp/sql_db.py", line 220, in execute
res = self._obj.execute(query, params)
IntegrityError: null value in column "menu_id" violates not-null constraint
DETAIL: Failing row contains (4, null, 1, 2017-04-25 07:19:17.668005, Project Management planner, planner_project, 879, 1, 2017-04-25 07:19:17.668005, t, 7, null,

Learn how to better organize your company using Projects, Tas...).
CONTEXT: SQL statement "UPDATE ONLY "public"."web_planner" SET "menu_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "menu_id""

**Comment by PieterAdriaensen** [comment]
Updating odoo to the latest 9.0 works
