### ISSUE TITLE
UncaughtPromiseError > TypeError Uncaught Promise > Cannot read properties of undefined (reading 'string')

### ISSUE THREAD

**Issue by ChayaGavali** [odoo/odoo#114384]
Impacted versions: odoo 16
When i start the odoo service. i got an  web assets error
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'string')
TypeError: Cannot read properties of undefined (reading 'string')
    at http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6558:211
    at traverse (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:200)
    at http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:242
    at Function.each (http://localhost:8082/web/assets/377-23e6530/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:211)
    at http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:242
    at Function.each (http://localhost:8082/web/assets/377-23e6530/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:211)
    at http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:6553:242
    at Function.each (http://localhost:8082/web/assets/377-23e6530/web.assets_common.min.js:171:149)
 Is there any Solution...............................?
Thanks
![Screenshot (60)](https://user-images.githubusercontent.com/113785260/223042902-492868f0-e12b-4f83-9f01-778f1de43f90.png)

**Comment by vava-odoo** [comment]
Is this issue still present? What are the steps to reproduce?

**Comment by Grief6915** [comment]
> Is this issue still present? What are the steps to reproduce?

Hello vava-odoo, I am days back from a mistake that is preventing my company from working. I've tried everything but I don't know what else to do.

I have the following error:

I cannot access to contacts due to an error " Cannot read properties of undefined (reading 'string')"

I just simply want to open contacts and it gives me this error

Cannot read properties of undefined (reading 'string')

I have no idea how to fix it

TypeError: Cannot read properties of undefined (reading 'string')
at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6575:211
at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:200)
at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)
at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:211)
at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)
at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:211)
at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)

This happened after installing the following module: Vendor Purchase Discount
by Cybrosys Techno Solutions - this module was for version 15 of Odoo and I got the 16.

I've tried to upgrade the module but to no avail.

The error you gave me was in the following file error_service.js

console.error(uncaughtError.traceback); //-> Error in this line

handleError(uncaughtError); // -> Error in this line

I've tried everything but I don't know what else to do.

Help for resolve this error

**Comment by Grief6915** [comment]
I've already uninstalled the app. Before duplicating the db. I don't know what else to do. Can you help me remotely?
