### ISSUE TITLE
Google Integration 

### ISSUE THREAD

**Issue by richardtrujillo** [odoo/odoo#11447]
Odoo Version: 9
How do I fix this error?
Setting -> General Setting -> Google Integration -> Insert Code -> Apply

Generate Google Authorization Code

`Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/addons/base/res/res_config.py", line 573, in execute
    getattr(self, method)(cr, uid, ids, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/addons/google_drive/google_drive.py", line 240, in set_google_authorization_code
    refresh_token = self.pool['google.service'].generate_refresh_token(cr, uid, 'drive', config.google_drive_authorization_code, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160209-py2.7.egg/openerp/addons/google_account/google_account.py", line 35, in generate_refresh_token
    content = urllib2.urlopen(req, timeout=TIMEOUT).read()
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/opt/bitnami/python/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/opt/bitnami/python/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/opt/bitnami/python/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'`

**Comment by andrew-caines** [comment]
We also get this error:  
We had a dev box on old 2.7.? (I think it was 2.7.2) of python, and our google OAuth Worked.
We moved to a new box, which has 2.7.11 python on it, we now get this same error.
My research pointed me to a few issues, which i found online:

https://github.com/gevent/gevent/issues/477

It appears in 2.7.9 they changed the function signature , which broke a lot of different applications.
This is currently making it impossible to use Facebook, or Google Signin with OAuth.

Our Enviroment is: 
Odoo: Version 9.0c-20160209 
Python: 2.7.11
OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"

Thank you,

**Comment by Yenthe666** [comment]
Hey guys,

In Odoo itself this should be fixed by now. An example for an invalid token to try and trigger this:
![image](https://user-images.githubusercontent.com/6352350/34950654-12741896-fa14-11e7-8b8c-d0be67e0f01e.png)
Please update your Odoo source code to fix this.

Regards,
Yenthe
