### ISSUE TITLE
[9.0]Impossible to create sale.order.line in multi company mode

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11454]
Impacted versions:
9.0

Steps to reproduce:

Create a product without company in multi company environment
Create a sale order for a specfic list price as an admin

Current behavior:

```
   File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/product_visible_discount/product_visible_discount.py", line 68, in product_id_change
    new_list_price, currency_id = line.with_context(context_partner)._get_real_price_currency(line.product_id.id, list_price, line.product_uom_qty, line.product_uom.id, line.order_id.pricelist_id.id)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/product_visible_discount/product_visible_discount.py", line 48, in _get_real_price_currency
    cur_factor = self.pool['res.currency']._get_conversion_rate(cr, uid, product.company_id.currency_id, currency_id, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/res/res_currency.py", line 205, in _get_conversion_rate
    return to_currency.rate/from_currency.rate
```

Expected behavior:

No problem as for a limited user

**Comment by pna-odoo** [comment]
Check your currency rate. May be you have currency rate 0.0 .

**Comment by flotho** [comment]
Hi @pna-odoo ,

All my currencies have 1.0 as rates and only EUR is active. Additionnally as you can read, it happens only with the admin user, not with a limited user.

**Comment by flotho** [comment]
Hi,

The problem appears when working with product_discount_visible. This is probably not a problem of rate. I've tested it on the latest git /rpm
Here are the additionnal logs :
```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 6038, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5895, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/site-packages/openerp/addons/product_visible_discount/product_visible_discount.py", line 93, in product_uom_change
    new_list_price, currency_id = self.with_context(context_partner)._get_real_price_currency(self.product_id.id, list_price, self.product_uom_qty, self.product_uom.id, self.order_id.pricelist_id.id)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/product_visible_discount/product_visible_discount.py", line 43, in _get_real_price_currency
    cur_factor = self.pool['res.currency']._get_conversion_rate(cr, uid, product.company_id.currency_id, currency_id, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_currency.py", line 203, in _get_conversion_rate
    return to_currency.rate/from_currency.rate
ZeroDivisionError: float division by zero
```

@pna-odoo any chance to be reviewed on this

**Comment by Yenthe666** [comment]
@flotho are you still facing this one?

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
