### ISSUE TITLE
Error installing auth_ldap

### ISSUE THREAD

**Issue by pacolotero** [odoo/odoo#11451]
When try to install auth_ldap module i get this error:

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/odoo/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/odoo/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1122, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/home/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/openerp/models.py", line 4131, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/odoo/openerp/models.py", line 4322, in _create
    recs._validate_fields(vals)
  File "/home/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Sorting field login not found on model res.users
None" while parsing /home/odoo/odoo/addons/auth_ldap/users_ldap_view.xml:4, near
<record model="ir.ui.view" id="company_form_view">
            <field name="name">res.company.form.inherit.users_ldap</field>
            <field name="model">res.company</field>
            <field name="inherit_id" ref="base.view_company_form"/>
            <field name="arch" type="xml">
                <xpath expr="//group[@name='account_grp']" position="after">
                    <group string="LDAP Parameters">
                        <field name="ldaps" nolabel="1" colspan="4">
                            <form string="LDAP Configuration">
                                <group col="4">
                                    <field name="ldap_server"/>
                                    <field name="ldap_server_port"/>
                                    <field name="ldap_binddn"/>
                                    <field name="ldap_password" password="True"/>
                                    <field name="ldap_base"/>
                                    <field name="ldap_filter"/>
                                    <field name="create_user"/>
                                    <field name="user"/>
                                    <newline/>
                                    <field name="sequence"/>
                                    <field name="ldap_tls"/>
                                </group>
                            </form>
                            <tree string="LDAP Configuration">
                                <field name="sequence"/>
                                <field name="ldap_server"/>
                                <field name="ldap_server_port"/>
                                <field name="ldap_base"/>
                            </tree>
                        </field>
                    </group>
                </xpath>
            </field>
        </record>
```

Impacted versions:
- **Odoo branch 9.0 commit 8158827d2e800a961d98bf8334a9ed3a3813ba18**

Steps to reproduce:
- **install auth_ldap module**

Current behavior:
- **fail installing auth_ldap**

Expected behavior:
- **successful installation of auth_ldap**

**Comment by tesserB** [comment]
Can you confirm that python-ldap (2.4.19) and openldap-devel have installed correctly?

**Comment by Yenthe666** [comment]
@pacolotero can you verify that you have the packages installed and that you can still reproduce this on the latest Odoo 9.0? I could install it succesfully on the latest Odoo 9.0 without any problems:
![image](https://user-images.githubusercontent.com/6352350/36093500-27acbb5e-0feb-11e8-9604-7397dd495d7b.png)

Regards,
Yenthe
