### ISSUE TITLE
Cannot access odoo 15ee settings dashboard

### ISSUE THREAD

**Issue by mureithi111** [odoo/odoo#114897]
Impacted versions: 15.00ee

**Steps to reproduce:**
1. Login to odoo
2. go to the app dashboard
3.  click on the setting icon to access the settings dashboard
4. Cannot access the dashboard

**Current behavior:**
Gets an error below
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 863, in apply_inheritance_specs
    source = apply_inheritance_specs(
  File "/home/odoo/src/odoo/15.0/odoo/tools/template_inheritance.py", line 254, in apply_inheritance_specs
    raise ValueError(
ValueError: Element '<xpath expr="//button[@name=73]//ancestor::div[hasclass(&#39;o_setting_box&#39;)]">' cannot be located in parent view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/15.0/addons/web/controllers/main.py", line 1326, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/15.0/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1629, in load_views
    result['fields_views'] = {
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1630, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/res_config.py", line 393, in fields_view_get
    ret_val = super(ResConfigSettings, self).fields_view_get(
  File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 249, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1713, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1675, in _fields_view_get
    result['arch'] = view.get_combined_arch()
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 961, in get_combined_arch
    return etree.tostring(self._get_combined_arch(), encoding='unicode')
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 991, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 932, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/home/odoo/src/enterprise/15.0/web_studio/models/ir_ui_view.py", line 498, in apply_inheritance_specs
    return super(View, self).apply_inheritance_specs(source, specs_tree,
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 869, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_ui_view.py", line 746, in _raise_view_error
    raise err from from_exception
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/15.0/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Element '<xpath expr="//button[@name=73]//ancestor::div[hasclass(&#39;o_setting_box&#39;)]">' cannot be located in parent view

**Expected behavior:**
I should be able to access the dashboard

**Comment by niyasraphy** [comment]
hi @mureithi111 ,
this seems to be an issue related to your odoo instance/database. Settings can be accessed without any issues in the runbot.
do you have custom module installed in the db ? If yes, take a copy of your db and try uninstalling the third party apps and check.

thanks

**Comment by AbdelAzizMohamedMousa** [comment]
The error message you provided indicates that there is a problem with the inheritance specifications of a view in your Odoo installation. Specifically, the error message says that an element cannot be located in the parent view, and this is causing an exception to be raised.

To resolve this issue, you could try the following steps:

Check your Odoo logs to see if there are any additional error messages or information that could help diagnose the issue.

Try disabling any custom modules or add-ons that you have installed and see if the error still occurs. If the error disappears, you can then try enabling each module one by one until you find the one that is causing the issue.

If the error still occurs after disabling custom modules, try reverting any recent changes that you made to the system (such as adding a new view or modifying an existing one) and see if the error disappears.

If none of the above steps work, you could try restoring a backup of your Odoo installation from a time when you know that the system was working correctly. This will help you determine if the issue is caused by a recent change or if it is a more fundamental issue with the installation.

If you are still unable to resolve the issue, you could consider reaching out to the Odoo community for assistance. There are many knowledgeable developers and users who may be able to provide you with additional guidance and support.

**Comment by vava-odoo** [comment]
@mureithi111 Please re-open if you have more information to provide
