### ISSUE TITLE
Helpdesk - can't generate refund

### ISSUE THREAD

**Issue by mj8765** [odoo/odoo#115011]
Impacted versions: 16 enterprise

Steps to reproduce: create ticket - assign item - click refund

Current behavior: throws error (sales order line not linked?  no where to link sales order line

Expected behavior: Generate a credit

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-16.1/odoo/http.py", line 1677, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/saas-16.1/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-16.1/odoo/http.py", line 1706, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-16.1/odoo/http.py", line 1903, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-16.1/addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-16.1/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-16.1/odoo/http.py", line 708, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-16.1/addons/web/controllers/dataset.py", line 28, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.1/addons/web/controllers/dataset.py", line 24, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.1/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/saas-16.1/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-16.1/odoo/models.py", line 6411, in onchange
    defaults = self.default_get(missing_names)
  File "/home/odoo/src/enterprise/saas-16.1/helpdesk_account/wizard/account_move_reversal.py", line 24, in default_get
    domain = self._get_default_so_domain(ticket)
  File "/home/odoo/src/enterprise/saas-16.1/helpdesk_stock_account/wizard/account_move_reversal.py", line 18, in _get_default_so_domain
    if ticket.sale_line_id:
AttributeError: 'helpdesk.ticket' object has no attribute 'sale_line_id'

The above server error caused the following client error:
null

**Comment by ppr-odoo** [comment]
@mj8765 We have fixed this issue. We will merge soon  [PR]( https://github.com/odoo/enterprise/pull/36439/files).Thanks
cc @xavierbol
