### ISSUE TITLE
Error actualizar tasas automáticas servicio xe.com

### ISSUE THREAD

**Issue by bjustizorbiware** [odoo/odoo#115017]
Impacted versions: 15

Steps to reproduce: Contabilidad/Configuración/Tasas automáticas/Actualizar con servicio xe.com

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1330, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/currency_rate_live/models/res_config_settings.py", line 758, in update_currency_rates_manually
    if not (self.company_id.update_currency_rates()):
  File "/home/odoo/src/enterprise/currency_rate_live/models/res_config_settings.py", line 185, in update_currency_rates
    parse_results = parse_function(active_currencies)
  File "/home/odoo/src/enterprise/currency_rate_live/models/res_config_settings.py", line 485, in _parse_xe_com_data
    time_element = htmlelem.xpath(".//div[@id='table-section']/section/p")[0]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
IndexError: list index out of range

Support ticket number submitted via odoo.com/help (optional):

**Comment by AbdelAzizMohamedMousa** [comment]
It seems like the issue is related to the xe.com currency service failing to parse a webpage while updating currency rates in Odoo 15.

To troubleshoot this issue, you can try the following steps:

Make sure that the connection to the internet is working fine and there is no network issue.

Check if the xe.com website is working fine or not. You can try to access the website in a web browser and see if it is accessible or not.

Check the Odoo server logs for any errors related to the currency service or the xe.com website. You can try to reproduce the issue and see if there are any specific error messages related to this.

Try updating the currency rates manually by selecting another currency service from the list of available services in Odoo. You can also try to update the rates using a different currency service like the European Central Bank or Yahoo Finance.

If the above steps do not resolve the issue, you can contact the Odoo support team or the xe.com support team for further assistance. They may be able to provide more insights into the issue and help you resolve it.
