### ISSUE TITLE
Uncaught Promise > isVoidElement is not a function when trying to edit contact page

### ISSUE THREAD

**Issue by ikus060** [odoo/odoo#115536]
Impacted versions: 15.0
Steps to reproduce:
- Got to Website
- Browse to contact page
- Click "Edit" button

Current behavior:
- The editor never get loaded
- An exception is raised

```
UncaughtPromiseError > TypeError
Uncaught Promise > isVoidElement is not a function
TypeError: isVoidElement is not a function
    at Sanitize._parse (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:707:4)
    at Sanitize.parse (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:700:6)
    at new Sanitize (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:698:6)
    at sanitize (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:711:53)
    at new OdooEditor (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:372:120)
    at Class.start (https://rdiffweb.org/web/assets/6609-492ef78/2/web_editor.assets_wysiwyg.min.js:1945:226)
    at async Class.start (https://rdiffweb.org/web/assets/5157-b962c75/2/website.assets_wysiwyg.min.js:412:372)
    at async Class._createWysiwyg (https://rdiffweb.org/web/assets/5153-1167d9c/2/website.assets_editor.min.js:58:242)
    at async Class._startEditMode (https://rdiffweb.org/web/assets/5153-1167d9c/2/website.assets_editor.min.js:57:26)
    at async Promise.all (index 0)
```

Expected behavior:
- The editor get loaded and can be used to edit the page

Video/Screenshot link (optional):
[Screencast from 2023-03-16 09:39:51 AM.webm](https://user-images.githubusercontent.com/921251/225634979-e14a2706-7e6d-4643-a89d-687effea1154.webm)

Support ticket number submitted via odoo.com/help (optional):

**Comment by ikus060** [comment]
Closing this bug. I manage to resolve the issue by "regenerating asset bundle".

![image](https://user-images.githubusercontent.com/921251/226220068-4e2a22eb-42b3-45bd-8440-eeca5cc05570.png)

Then I restart Odoo. And error are gone !
