### ISSUE TITLE
Odoo 9.0 + Odoo Server Error + Point Of Sales + BUG2016

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11598]
Impacted versions: 9.0 CE

Steps to reproduce:
1. Create database, no demo data or with demo data
2. Setup accounting and sales
3. Install Point of sale module.

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/sbukerp/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/sbukerp/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/sbukerp/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/sbukerp/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/sbukerp/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/sbukerp/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/sbukerp/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/sbukerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/sbukerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/sbukerp/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/sbukerp/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/sbukerp/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/sbukerp/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/sbukerp/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/sbukerp/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/sbukerp/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/sbukerp/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/opt/sbukerp/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/sbukerp/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/addons/base/ir/ir_model.py", line 1101, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/addons/sb_cscart/product.py", line 70, in create
    res = super(product_product, self).create(cr, uid, vals, context=context)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/addons/product/product.py", line 1189, in create
    product_id = super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/sbukerp/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/opt/sbukerp/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/opt/sbukerp/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/api.py", line 478, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/sbukerp/openerp/models.py", line 4338, in _create
    cr, user, ids, fields2, context)
  File "/opt/sbukerp/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/sbukerp/openerp/models.py", line 4476, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/opt/sbukerp/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/sbukerp/openerp/osv/fields.py", line 1559, in _related_read
    value = value[field][:1]
  File "/opt/sbukerp/openerp/models.py", line 5715, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/sbukerp/openerp/fields.py", line 813, in __get__
    return record._cache[self]
  File "/opt/sbukerp/openerp/models.py", line 6095, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/sbukerp/openerp/fields.py", line 38, in get
    raise self.exception
ParseError: "Record does not exist or has been deleted.
None" while parsing /opt/sbukerp/addons/point_of_sale/point_of_sale_data.xml:48, near
<record id="product_product_consumable" model="product.product">
            <field name="name">Miscellaneous</field>
            <field name="standard_price">13.0</field>
            <field name="list_price">18.0</field>
            <field name="type">consu</field>
            <field name="uom_id" ref="product.product_uom_unit"/>
            <field name="uom_po_id" ref="product.product_uom_unit"/>
            <field name="default_code">MISC</field>
            <field name="image" type="base64" file="point_of_sale/static/img/product_product_49-image.jpg"/>
        </record>

Expected behavior:
Least work normal things of odoo tool.

Note: I had check if I remove all product from demo or data files from this module then all works fine.

**Comment by Yenthe666** [comment]
I can no longer reproduce this issue on the latest Odoo 9.0.
If you still face this issue please update your Odoo codebase. If the issue still persist please post back with more details.
