### ISSUE TITLE
[16.0] Wizard export data -> TypeError: TypeError: Cannot read properties of undefined (reading 'children') 

### ISSUE THREAD

**Issue by kikopeiro** [odoo/odoo#115995]
Impacted versions: Only v16 is affected

Steps to reproduce:

1. Go to Sales > Orders > Customers
2. Open tree view
3. Select some records
4. Action > Export
5. Expand field "Banks"
6. Check "I want to update data (import-compatible export)"
7. Expand field "Banks" (no reponse)
8. Expand field "Banks" (throws error)

Current behavior: Odoo Runbot

Expected behavior: When expand field "Banks" after "steps to reproduce" we should add new fields in export wizard

Video/Screenshot link (optional):
![Peek 2023-03-21 11-16](https://user-images.githubusercontent.com/4610000/226577913-32891336-e84d-4f51-bc3d-1cf4121d2b0d.gif)

Support ticket number submitted via odoo.com/help (optional):

**Comment by kikopeiro** [comment]
```
UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1247:101)
    at owl.App.handleError (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:2077:29)
    at Fiber._render (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1478:19)
    at Fiber.render (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1476:6)
    at ComponentNode.initiateRender (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1555:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'children')
    at ExportDataDialog.isFieldExpandable (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1857-44c4ed6/web.assets_backend.min.js:5570:53)
    at ExportDataItem.template (eval at compile (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:2040:370), <anonymous>:22:22)
    at Fiber._render (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1477:96)
    at Fiber.render (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1476:6)
    at ComponentNode.initiateRender (https://25345705-16-0-all.runbot106.odoo.com/web/assets/1860-c2bb698/web.assets_common.min.js:1555:47)
```
