### ISSUE TITLE
Odoo 9 bug, #odoo #InternalError: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11594]
Impacted versions: 9.0 CE

Steps to reproduce: 
Fresh install odoo over server,
then install accounting and working with customer invoice operation.
Sudden server stop and in terminal below error we face.
then on reload again, it works fine, but in server log we traced issue.

Current behavior:
Getting this message in terminal log of server, not know what to do more.

2016-04-05 06:25:36,136 5325 INFO theica werkzeug: 127.0.0.1 - - [05/Apr/2016 06:25:36] "GET /event HTTP/1.1" 500 -
2016-04-05 06:25:36,310 5325 ERROR theica werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/sbadmin/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/sbadmin/odoo/openerp/service/wsgi_server.py", line 182, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 144, in __call__
    return self.app(environ, start_response)
  File "/home/sbadmin/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/sbadmin/odoo/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/sbadmin/odoo/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/home/sbadmin/odoo/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/home/sbadmin/odoo/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/home/sbadmin/odoo/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/home/sbadmin/odoo/addons/website/models/ir_http.py", line 191, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/home/sbadmin/odoo/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/sbadmin/odoo/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/home/sbadmin/odoo/addons/website/models/ir_http.py", line 297, in _handle_exception
    html = request.website._render('website.http_error', values)
  File "/home/sbadmin/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/sbadmin/odoo/addons/website/models/website.py", line 417, in _render
    return self.pool['ir.ui.view'].render(cr, uid, template, values=values, context=context)
  File "/home/sbadmin/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/addons/website/models/ir_ui_view.py", line 147, in render
    qcontext = self._prepare_qcontext(cr, uid, context=context)
  File "/home/sbadmin/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/addons/website/models/ir_ui_view.py", line 172, in _prepare_qcontext
    company = self.pool['res.company'].browse(cr, SUPERUSER_ID, request.website.company_id.id, context=context)
  File "/home/sbadmin/odoo/openerp/fields.py", line 828, in __get__
    self.determine_value(record)
  File "/home/sbadmin/odoo/openerp/fields.py", line 926, in determine_value
    record._prefetch_field(self)
  File "/home/sbadmin/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/openerp/models.py", line 3283, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/sbadmin/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/openerp/models.py", line 3213, in read
    self._read_from_database(stored, inherited)
  File "/home/sbadmin/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sbadmin/odoo/openerp/models.py", line 3351, in _read_from_database
    cr.execute(query_str, params)
  File "/home/sbadmin/odoo/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sbadmin/odoo/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

Expected behavior:
fix this: InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by Yenthe666** [comment]
I cannot reproduce this issue anymore. If you can reproduce this on the latest runbot please post back and I'll re-open this.
