### ISSUE TITLE
[8.0] Changing the payslip date_from produces error.

### ISSUE THREAD

**Issue by MartinAavastik** [odoo/odoo#11601]
Steps to reproduce:
Create a new database. Create a employee with a contract and working schedule. Create payslip. Save. Edit and change date_from.

```
Traceback (most recent call last):
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/home/martin/Dokumendid/git/odoo-8.0/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/models.py", line 5956, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/models.py", line 5856, in _onchange_eval
    params = eval("[%s]" % params, global_vars, field_vars)
  File "/home/martin/Dokumendid/git/odoo-8.0 05.04.2016/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: "name 'date_from' is not defined" while evaluating
'[date_from, date_to, employee_id, contract_id]'
```

**Comment by Yenthe666** [comment]
Hi @MartinAavastik,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
