### ISSUE TITLE
[16.0] pos_mercury payment screen crashed.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#116564]
Impacted versions:
16.0

Steps to reproduce:

1. set a payment method as mercury
2. in payment screen, select mercury
3. 
4. 

Current behavior:

select payment as mercury, Pos screen report  error
<img width="535" alt="image" src="https://user-images.githubusercontent.com/1404460/227556439-e68a8632-3aba-4808-82c2-16b147e94703.png">

```
TypeError: order.trigger is not a function
    at PaymentScreen.addNewPaymentLine (http://test.geninit.cn:9001/web/assets/debug/point_of_sale.assets.js:46282:27) (/pos_mercury/static/src/js/PaymentScreen.js:593)
    at PaymentScreen.__trigger (http://test.geninit.cn:9001/web/assets/debug/web.assets_common.js:22213:21) (/web/static/src/legacy/legacy_component.js:89)
    at PaymentScreen.trigger (http://test.geninit.cn:9001/web/assets/debug/web.assets_common.js:22197:14) (/web/static/src/legacy/legacy_component.js:73)
    at PaymentScreen.hdlr2 (eval at compile (http://test.geninit.cn:9001/web/assets/debug/web.assets_common.js:21540:16), <anonymous>:48:27) (/web/static/lib/owl/owl.js:5480)
    at Object.mainEventHandler (http://test.geninit.cn:9001/web/assets/debug/web.assets_common.js:21807:25) (/web/static/lib/owl/owl.js:5747)
    at HTMLDivElement.listener (http://test.geninit.cn:9001/web/assets/debug/web.assets_common.js:16368:20) (/web/static/lib/owl/owl.js:308)

```

have reviewed the code, maybe `  order. Trigger('change', order); ` should change to `  this. Trigger('change', order);`

@caburj 

```
addNewPaymentLine({ detail: paymentMethod }) {
                const order = this.env.pos.get_order();
                const res = super.addNewPaymentLine(...arguments);
                if (res && paymentMethod.pos_mercury_config_id) {
                    order.selected_paymentline.mercury_swipe_pending = true;
                    order. Trigger('change', order);
                    this.render();
                }
            }
```

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by caburj** [comment]
Thank you for reporting @jeffery9. If I can ask, can you verify from you end whether the following PR solves this issue?
 https://github.com/odoo/odoo/pull/116642
