### ISSUE TITLE
[16.0][Odoo.sh] Uncaught Promise > Cannot read properties of undefined (reading 'match') for >v16.0.20230313

### ISSUE THREAD

**Issue by evanomnisoft** [odoo/odoo#117554]
Impacted versions:
Any version after 16.0.20230313

Steps to reproduce:
On Odoo.sh, set to latest revision(or any revision after 16.0.20230313)
Reload page on incognitio so as to use reload all assets

Current behavior:
Error is shown on page load
`
Uncaught Promise > Cannot read properties of undefined (reading 'match')
`

Trace

```
TypeError: Cannot read properties of undefined (reading 'match')
    at Class._onMainObjectRequest (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:7977:402)

    at Class.<anonymous> (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5836:11)

    at Class.trigger (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5834:180)

    at Class._trigger_up (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5840:378)

    at Class._trigger_up (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5840:462)

    at Class.trigger_up (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5840:280)

    at Class._getCategorySearchDomain (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:11637:29)

    at Class._getSearchDomain (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:11641:130)

    at prototype.<computed> [as _getSearchDomain] (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:5695:488)

    at Class._fetchData (https://XXX-staging.odoo.com/web/assets/231076-02bc543/1/web.assets_frontend_lazy.min.js:11550:2064)
```

Expected behavior:
No error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
#3262029

**Comment by evanomnisoft** [comment]
Additional error stack trace from browser console (Chrome Version 111.0.5563.110):

```
Error while loading root.widget: Cannot read properties of undefined (reading 'match') TypeError: Cannot read properties of undefined (reading 'match')
    at Class._onMainObjectRequest (web.assets_frontend_lazy.min.js:7977:402)
    at Class.<anonymous> (web.assets_frontend_lazy.min.js:5836:11)
    at Class.trigger (web.assets_frontend_lazy.min.js:5834:180)
    at Class._trigger_up (web.assets_frontend_lazy.min.js:5840:378)
    at Class._trigger_up (web.assets_frontend_lazy.min.js:5840:462)
    at Class.trigger_up (web.assets_frontend_lazy.min.js:5840:280)
    at Class._getCategorySearchDomain (web.assets_frontend_lazy.min.js:11637:29)
    at Class._getSearchDomain (web.assets_frontend_lazy.min.js:11641:130)
    at prototype.<computed> [as _getSearchDomain] (web.assets_frontend_lazy.min.js:5695:488)
    at Class._fetchData (web.assets_frontend_lazy.min.js:11550:2064)
onError @ web.assets_frontend_minimal.min.js:8
web.assets_frontend_lazy.min.js:6740 TypeError: Cannot read properties of undefined (reading 'match')
    at Class._onMainObjectRequest (web.assets_frontend_lazy.min.js:7977:402)
    at Class.<anonymous> (web.assets_frontend_lazy.min.js:5836:11)
    at Class.trigger (web.assets_frontend_lazy.min.js:5834:180)
    at Class._trigger_up (web.assets_frontend_lazy.min.js:5840:378)
    at Class._trigger_up (web.assets_frontend_lazy.min.js:5840:462)
    at Class.trigger_up (web.assets_frontend_lazy.min.js:5840:280)
    at Class._getCategorySearchDomain (web.assets_frontend_lazy.min.js:11637:29)
    at Class._getSearchDomain (web.assets_frontend_lazy.min.js:11641:130)
    at prototype.<computed> [as _getSearchDomain] (web.assets_frontend_lazy.min.js:5695:488)
    at Class._fetchData (web.assets_frontend_lazy.min.js:11550:2064)
```

**Comment by AbdelAzizMohamedMousa** [comment]
Based on the error message, it seems that the code is trying to access a property called "match" on an undefined object. This could happen if the code is expecting a regular expression object but instead receives undefined.

One possible solution could be to add a check for undefined values before accessing the "match" property. For example, you could modify the code to look like this: 
`if (myVariable !== undefined && myVariable.match(/myRegex/g)) {
  // do something
}
`

This will ensure that the code only tries to access the "match" property if "myVariable" is defined.

Alternatively, you could check where the regular expression object is being created and make sure that it is always initialized properly.

It's also worth checking if any recent changes have been made to the codebase that could have caused this issue. If so, you may need to revert those changes or modify them to fix the error.

**Comment by vava-odoo** [comment]
Hi @evanomnisoft 

In order to get help about Odoo.sh, please use https://www.odoo.com/help instead of the Odoo github issue tracker.

Thanks.

**Comment by evanomnisoft** [comment]
Hi @vava-odoo 

Thanks for the followup, I did indeed issue a support ticket (#3262029) and it is being investigated on that front.

The reason why it is also posted here is because its evidently an issue with the code and not the deployed environment. (Issue does not exist on older odoo versions)
