### ISSUE TITLE
Via XMLRPC Access Tasks, Read Method use

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11809]
Impacted versions: 9.0 Community

Steps to reproduce:
via xmlrpc trying to read some tasks, projects
Current behavior:
projects read successful, when trying to read tasks odoo gives errors.

Expected behavior:
xmlrpcresp Object
(
    [val] => 0
    [valtyp] => 
    [errno] => -1
    [errstr] => Traceback (most recent call last):
  File "/opt/odoo9c/openerp/service/wsgi_server.py", line 56, in xmlrpc_return
    result = openerp.http.dispatch_rpc(service, method, params)
  File "/opt/odoo9c/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo9c/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo9c/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo9c/openerp/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/odoo9c/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/odoo9c/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9c/openerp/models.py", line 3175, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo9c/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9c/openerp/models.py", line 3210, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo9c/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9c/openerp/models.py", line 3401, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo9c/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo9c/openerp/osv/fields.py", line 1561, in _related_read
    res[record.id] = value[self.arg[-1]]
  File "/opt/odoo9c/openerp/models.py", line 5715, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'user_id'

    [payload] => 
    [hdrs] => Array
        (
            [date] => Mon, 25 Apr 2016 06:26:39 GMT
            [server] => Werkzeug/0.9.6 Python/2.7.9
            [content-type] => text/xml
            [vary] => Accept-Encoding
            [content-encoding] => gzip
            [content-length] => 682
            [connection] => close
        )

    [_cookies] => Array
        (
        )

    [content_type] => text/xml
    [raw_data] => HTTP/1.1 200 OK
Date: Mon, 25 Apr 2016 06:26:39 GMT
Server: Werkzeug/0.9.6 Python/2.7.9
Content-Type: text/xml
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 682
Connection: close

**Comment by xmo-odoo** [comment]
Instructions unclear, no issue observed:
```python
>>> p = ServerProxy('http://143971-9-0-9c5683.runbot9.odoo.com/xmlrpc/2/object')
>>> ids = p.execute_kw('143971-9-0-9c5683-all', 1, 'admin', 'project.task', 'search', [[]], {})
>>> len(p.execute_kw('143971-9-0-9c5683-all', 1, 'admin', 'project.task', 'read', [ids], {}))
39
```
