### ISSUE TITLE
invalid field  'customer' on model 'product.template'

### ISSUE THREAD

**Issue by ramdas409** [odoo/odoo#118137]
Traceback (most recent call last):
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 5368, in _update_cache
    field_values = [(fields[name], value) for name, value in values.items()]
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 5368, in <listcomp>
    field_values = [(fields[name], value) for name, value in values.items()]
KeyError: 'customer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dasari/Downloads/odoo-15.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dasari/Downloads/odoo-15.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/dasari/Downloads/odoo-15.0/addons/web/controllers/main.py", line 1326, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dasari/Downloads/odoo-15.0/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dasari/Downloads/odoo-15.0/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/dasari/Downloads/odoo-15.0/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 6455, in onchange
    record._update_cache(changed_values, validate=False)
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 5374, in _update_cache
    cache.set(self, field, field.convert_to_cache(value, self, validate))
  File "/home/dasari/Downloads/odoo-15.0/odoo/fields.py", line 2787, in convert_to_cache
    id_ = comodel.new(value, origin=origin).id
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 5728, in new
    record._update_cache(values, validate=False)
  File "/home/dasari/Downloads/odoo-15.0/odoo/models.py", line 5370, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dasari/Downloads/odoo-15.0/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'customer' on model 'product.template'

**Comment by niyasraphy** [comment]
@ramdas409 could you provide more info about how to reproduce this issue in odoo runbot ?
i think this is most likely due to any custom developments in your odoo instance

**Comment by jp-22** [comment]
@ramdas409 You can try delete the view for product.template model after applying filter arch_blob contains "customer". And then restart the server.

Thanks!

**Comment by vava-odoo** [comment]
@ramdas409 Please re-open the issue if you can provide more information
