### ISSUE TITLE
[9.0e] Odoo Server Error when trying to scrap consumed product

### ISSUE THREAD

**Issue by bluestingray** [odoo/odoo#11837]
**Impacted versions:**
Version 9.0e (Enterprise Edition)

**Steps to reproduce:**
On demo2.odoo.com:
1. Create a MO for a '3" Valve' (which is setup as a manufacture and make to order with a BOM that has a lower level that is a manufacture and make to order) then confirm production
2. Click 'Reserve'
3. There should have been a new MO created for the '3" Act. Valve Bonnet' (the lower level mentioned above,) confirm, reserve and then produce it.
4. Consume the '3" Act. Valve Bonnet'
5. Go back to the MO for the '3" Act. Valve Bonnet' and click on the 'FINISHED PRODUCTS' tab
6. Under 'Produced Products' there should be the icon/link to scrap what has been produced; click it
7. Change the quantity to >= 1
8. Click 'Scrap'
9. An 'Odoo Server Error' shows as per the screen shot below.

**Current behavior:**
As above.  Error text:
```
Traceback (most recent call last):
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo9-enterprise/enterprise/web/controllers/main.py", line 911, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo9-enterprise/enterprise/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/addons/stock/wizard/stock_move.py", line 70, in move_scrap
    context=context)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/addons/mrp/stock.py", line 184, in action_scrap
    restrict_partner_id=restrict_partner_id, context=context)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/addons/stock/stock.py", line 2800, in action_scrap
    restrict_lot_id=scrap_move.restrict_lot_id.id, restrict_partner_id=scrap_move.restrict_partner_id.id, context=context)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: quants_get_preferred_domain() got an unexpected keyword argument 'restrict_partner_id'
```

**Expected behavior:**
Not sure.  This is why I was doing this exercise.  To see what would happen when trying to scrap goods that have already been consumed by another MO.

Video/Screenshot link (optional):
![mo00005 - odoo - google chrome_003](https://cloud.githubusercontent.com/assets/17476652/14825473/ba97c230-0b9f-11e6-9a70-89aa6bcd97a5.png)

**Comment by blaggacao** [comment]
cc/
@nim-odoo (as committer of incompatible parts in stock)
@qdp-odoo (as committer of incompatible parts in mrp)

**Comment by nim-odoo** [comment]
Hello,

demo2.odoo.com is not up-to-date. If you want to do some testing, you should use a local installation or the [runbot](http://runbot.odoo.com/runbot). By the way, this issue was solved more than a month ago with commit https://github.com/odoo/odoo/commit/c26fa293c8ef309213ed5e096e80ad4307e2682f

**Comment by blaggacao** [comment]
Thanks! I'll think of a practical way to include that kind of validations into my personal workflow before speaking up.
