### ISSUE TITLE
Ecuador withholdings do not work

### ISSUE THREAD

**Issue by kevturpromit** [odoo/odoo#118547]
Versions impacted: 16
update 2023-04-13 19:24:54.944321

Steps to reproduce:
In the Ecuadorian location, go to an issued sales invoice and enter a withholding

Current behavior:
throw the following message

UncaughtPromiseError > OwlError
Uncaught Promise > An error occurred in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occurred in the owl lifecycle (see this Error's "cause" property)
     at handleError (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1250:101)
     at owl.App.handleError (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:2080:29)
     at Fiber._render (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1481:19)
     at Fiber.render (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1479:6)
     at ComponentNode.initiateRender (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1558:47)

Caused by: TypeError: totals.subtotals_order is not iterable
     at TaxTotalsComponentForWithhold.formatData (https://29815235-master-base.runbot158.odoo.com/web/assets/528-6e2b6ec/web.assets_backend.min.js:10950:272)
     at TaxTotalsComponentForWithhold.setup (https://29815235-master-base.runbot158.odoo.com/web/assets/528-6e2b6ec/web.assets_backend.min.js:10944:330)
     at TaxTotalsComponentForWithhold.setup (https://29815235-master-base.runbot158.odoo.com/web/assets/528-6e2b6ec/web.assets_backend.min.js:12873:590)
     at new ComponentNode (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1553:202)
     at https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:2078:6
     at Field.template (eval at compile (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:2043:370), <anonymous>: 18:31)
     at Fiber._render (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1480:96)
     at Fiber.render (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1479:6)
     at ComponentNode.initiateRender (https://29815235-master-base.runbot158.odoo.com/web/assets/527-50d4bef/web.assets_common.min.js:1558:47)

Expected behavior:

You must go to a wizard to enter the amount of the withholding

Video link/screenshot (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by kevturpromit** [comment]
Does anyone have any information about it?
