### ISSUE TITLE
[Unstable odoo 9.0 ]Event Same user register twice a event, issue happening

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11967]
Impacted versions:
9.0

Steps to reproduce:
Event Same user register twice a event, issue happening

Current behavior:
2016-05-09 11:35:20,618 3923 WARNING newtestdbdbd openerp.models: event.registration.create() includes unknown fields: company_type, ufile
2016-05-09 11:35:20,628 3923 INFO newtestdbdbd openerp.sql_db: bad query: INSERT INTO "mail_followers" ("id", "res_model", "res_id", "partner_id") VALUES(nextval('mail_followers_id_seq'), 'res.partner', 73, 3) RETURNING id
2016-05-09 11:35:20,630 3923 ERROR newtestdbdbd openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/od9ce/addons/website/models/ir_http.py", line 243, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/od9ce/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/od9ce/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/od9ce/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/opt/od9ce/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/opt/od9ce/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/od9ce/openerp/service/model.py", line 140, in wrapper
    raise ValidationError(tr(registry._sql_error[key], 'sql_constraint') or inst[0])
ValidationError: ('Error, a partner cannot follow twice the same object.', None)

2016-05-09 11:35:20,631 3923 INFO newtestdbdbd openerp.sql_db: bad query:  SELECT "website"."social_linkedin" as "social_linkedin","website"."domain" as "domain","website"."create_uid" as "create_uid","website"."social_twitter" as "social_twitter","website"."create_date" as "create_date","website"."google_analytics_key" as "google_analytics_key","website"."company_id" as "company_id","website"."social_youtube" as "social_youtube","website"."write_date" as "write_date","website"."name" as "name","website"."salesperson_id" as "salesperson_id","website"."cdn_activated" as "cdn_activated","website"."write_uid" as "write_uid","website"."id" as "id","website"."social_facebook" as "social_facebook","website"."salesteam_id" as "salesteam_id","website"."compress_html" as "compress_html","website"."default_lang_id" as "default_lang_id","website"."cdn_filters" as "cdn_filters","website"."cdn_url" as "cdn_url","website"."social_github" as "social_github","website"."website_form_enable_metadata" as "website_form_enable_metadata","website"."user_id" as "user_id","website"."default_lang_code" as "default_lang_code","website"."social_googleplus" as "social_googleplus" FROM "website"
                        WHERE "website".id IN (1)  ORDER BY "website"."id"  
                    
2016-05-09 11:35:20,631 3923 INFO newtestdbdbd openerp.sql_db: bad query:  SELECT "website"."social_linkedin" as "social_linkedin","website"."domain" as "domain","website"."create_uid" as "create_uid","website"."social_twitter" as "social_twitter","website"."create_date" as "create_date","website"."google_analytics_key" as "google_analytics_key","website"."company_id" as "company_id","website"."social_youtube" as "social_youtube","website"."write_date" as "write_date","website"."name" as "name","website"."salesperson_id" as "salesperson_id","website"."cdn_activated" as "cdn_activated","website"."write_uid" as "write_uid","website"."id" as "id","website"."social_facebook" as "social_facebook","website"."salesteam_id" as "salesteam_id","website"."compress_html" as "compress_html","website"."default_lang_id" as "default_lang_id","website"."cdn_filters" as "cdn_filters","website"."cdn_url" as "cdn_url","website"."social_github" as "social_github","website"."website_form_enable_metadata" as "website_form_enable_metadata","website"."user_id" as "user_id","website"."default_lang_code" as "default_lang_code","website"."social_googleplus" as "social_googleplus" FROM "website"
                        WHERE "website".id IN (1)  ORDER BY "website"."id"  
                    
2016-05-09 11:35:20,634 3923 INFO newtestdbdbd werkzeug: 183.90.36.123 - - [09/May/2016 11:35:20] "POST /event/new-test-event-2016-05-09-2016-05-10-9/registration/confirm HTTP/1.1" 500 -
2016-05-09 11:35:20,667 3923 ERROR newtestdbdbd werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/od9ce/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/opt/od9ce/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/od9ce/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/od9ce/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/od9ce/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/od9ce/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/opt/od9ce/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/opt/od9ce/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/od9ce/addons/website/models/ir_http.py", line 191, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/od9ce/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/opt/od9ce/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/opt/od9ce/addons/website/models/ir_http.py", line 297, in _handle_exception
    html = request.website._render('website.http_error', values)
  File "/opt/od9ce/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/od9ce/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/od9ce/addons/website/models/website.py", line 417, in _render
    return self.pool['ir.ui.view'].render(cr, uid, template, values=values, context=context)
  File "/opt/od9ce/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/od9ce/addons/website/models/ir_ui_view.py", line 147, in render
    qcontext = self._prepare_qcontext(cr, uid, context=context)
  File "/opt/od9ce/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/od9ce/addons/website/models/ir_ui_view.py", line 172, in _prepare_qcontext
    company = self.pool['res.company'].browse(cr, SUPERUSER_ID, request.website.company_id.id, context=context)
  File "/opt/od9ce/openerp/fields.py", line 828, in __get__
    self.determine_value(record)
  File "/opt/od9ce/openerp/fields.py", line 926, in determine_value
    record._prefetch_field(self)
  File "/opt/od9ce/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/od9ce/openerp/models.py", line 3283, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/od9ce/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/od9ce/openerp/models.py", line 3213, in read
    self._read_from_database(stored, inherited)
  File "/opt/od9ce/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/od9ce/openerp/models.py", line 3351, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/od9ce/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/od9ce/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

Expected behavior:
Your mail module architecture is very unimpressive, it causes lot of issue across entire odoo framework.

Video/Screenshot link (optional):

**Comment by tejastank** [comment]
Issue occures in live and local both,

**Comment by tejastank** [comment]
I had check codes, odoo bit wired at this features, instead of skip, it rejecting all things. 

current transaction is aborted issue till exist since version 6.0 !!!

**Comment by Yenthe666** [comment]
I can no longer reproduce this error on the latest Odoo 9 code.
Please update your Odoo codebase and it should be fixed. If you still face this issue please give me more details on how to reproduce it.
