### ISSUE TITLE
Unformatted output

### ISSUE THREAD

**Issue by DGEAPerez** [odoo/odoo#11976]
After a big effort to run Odoo in a clean Ubuntu 16.04 (see here: https://github.com/odoo/odoo/issues/9113#issuecomment-217887807 ) I only see an unformatted output when try to create the database... I purged and reinstall odoo without get the expected output

This is from /var/log/odoo/odoo-server.log

2016-05-09 20:35:11,376 18289 INFO ? openerp: OpenERP version 9.0c-20160509
2016-05-09 20:35:11,377 18289 INFO ? openerp: addons paths ['/var/lib/odoo/.local/share/Odoo/addons/9.0', u'/usr/lib/python2.7/dist-packages/openerp/addons']
2016-05-09 20:35:11,378 18289 INFO ? openerp: database: odoo@default:default
2016-05-09 20:35:12,674 18289 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2016-05-09 20:38:42,321 18289 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-05-09 20:38:42,398 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:38:42] "GET /web/login HTTP/1.1" 500 -
2016-05-09 20:38:42,407 18289 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1487, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1508, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/calendar/__init__.py", line 4, in <module>
    from . import calendar
  File "/usr/lib/python2.7/dist-packages/openerp/addons/calendar/calendar.py", line 14, in <module>
    from dateutil import rrule
  File "/usr/local/lib/python2.7/dist-packages/dateutil/rrule.py", line 16, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
2016-05-09 20:40:42,472 18289 INFO ? openerp.http: Generating nondb routing
2016-05-09 20:40:42,522 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:42] "GET /web/login HTTP/1.1" 303 -
2016-05-09 20:40:42,961 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:42] "GET /web/database/selector HTTP/1.1" 200 -
2016-05-09 20:40:43,772 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:43] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 -
2016-05-09 20:40:43,777 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:43] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 404 -
2016-05-09 20:40:43,784 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:43] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 404 -
2016-05-09 20:40:43,798 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:43] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2016-05-09 20:40:43,807 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:43] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 -
2016-05-09 20:40:44,012 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:44] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2016-05-09 20:40:44,212 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:44] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 -
2016-05-09 20:40:44,379 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:44] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
2016-05-09 20:40:44,587 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:44] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2016-05-09 20:40:44,984 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:44] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2016-05-09 20:40:45,367 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:45] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
2016-05-09 20:40:45,431 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:45] "GET /web/database/selector HTTP/1.1" 200 -
2016-05-09 20:40:45,910 18289 INFO ? werkzeug: 186.138.17.188 - - [09/May/2016 20:40:45] "GET /web/static/src/img/favicon.ico HTTP/1.1" 404 -
![odoo 2016-05-09 18-01-17]

This is the output...

(https://cloud.githubusercontent.com/assets/1903754/15128065/156388b4-1610-11e6-8fbc-46a7db33973b.png)

Thanks in advance

**Comment by DGEAPerez** [comment]
I don't know why, but a few hours latter, in other computer, I can create the database, but after I logged I just get an empty output (just the black header and the left colun with odoo logo)

This says the log:
2016-05-09 23:30:01,498 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:01] "GET /web HTTP/1.1" 200 -
2016-05-09 23:30:02,023 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/static/src/css/full.css HTTP/1.1" 404 -
2016-05-09 23:30:02,062 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/content/245-1add395/web.assets_common.0.css HTTP/1.1" 304 -
2016-05-09 23:30:02,170 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/content/246-1add395/web.assets_common.js HTTP/1.1" 200 -
2016-05-09 23:30:02,196 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/content/248-320e2ae/web.assets_backend.1.css HTTP/1.1" 304 -
2016-05-09 23:30:02,222 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/content/247-320e2ae/web.assets_backend.0.css HTTP/1.1" 304 -
2016-05-09 23:30:02,781 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:02] "GET /web/content/249-320e2ae/web.assets_backend.js HTTP/1.1" 200 -
2016-05-09 23:30:03,026 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:03] "GET /web/binary/company_logo HTTP/1.1" 200 -
2016-05-09 23:30:34,662 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:34] "GET /web_editor/static/src/xml/editor.xml HTTP/1.1" 404 -
2016-05-09 23:30:34,673 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:34] "POST /web/dataset/call HTTP/1.1" 200 -
2016-05-09 23:30:35,366 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:35] "GET /web/static/src/img/favicon.ico HTTP/1.1" 404 -
2016-05-09 23:30:35,370 18289 INFO perezsanzOD openerp.service.common: successful login from 'admin' using database 'perezsanzod'
2016-05-09 23:30:35,384 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:35] "POST /web/webclient/translations HTTP/1.1" 200 -
2016-05-09 23:30:35,387 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:35] "POST /web/session/get_session_info HTTP/1.1" 200 -
2016-05-09 23:30:35,676 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:35] "POST /web/proxy/load HTTP/1.1" 200 -
2016-05-09 23:30:36,523 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:36] "POST /web/session/modules HTTP/1.1" 200 -
2016-05-09 23:30:37,018 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:37] "POST /web/dataset/search_read HTTP/1.1" 200 -
2016-05-09 23:30:37,032 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:37] "POST /web/webclient/translations HTTP/1.1" 200 -
2016-05-09 23:30:37,498 18289 INFO perezsanzOD werkzeug: 201.177.64.213 - - [09/May/2016 23:30:37] "GET /web/webclient/locale/en_US HTTP/1.1" 500 -
2016-05-09 23:30:37,512 18289 ERROR perezsanzOD werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 505, in load_locale
    addons_path = http.addons_manifest['web']['addons_path']
KeyError: 'web'

**Comment by JKE-be** [comment]
Seems to be a problem during installation and not an issue in Odoo.
Meanwhile I suppose that you have fixed your problem. Else use the forum for this type of question.

**Comment by alaherma** [comment]
Hi, im gertting similar problems

2017-09-12 18:32:53,197 1131 INFO ? werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:53] "GET /web?db=odoo HTTP/1.1" 302 -
2017-09-12 18:32:53,290 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:53] "GET /web?db=odoo HTTP/1.1" 303 -
2017-09-12 18:32:53,727 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:53] "GET /web/login HTTP/1.1" 200 -
2017-09-12 18:32:53,998 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:53] "GET /web/webclient/qweb?mods= HTTP/1.1" 304 -
2017-09-12 18:32:54,071 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:54] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
2017-09-12 18:32:54,100 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:54] "POST /website/translations HTTP/1.1" 200 -
2017-09-12 18:32:56,233 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 -
2017-09-12 18:32:56,233 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 404 -
2017-09-12 18:32:56,236 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 404 -
2017-09-12 18:32:56,257 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 -
2017-09-12 18:32:56,266 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2017-09-12 18:32:56,289 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2017-09-12 18:32:56,374 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:32:56] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
2017-09-12 18:33:15,264 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:15] "GET /web?db=odoo HTTP/1.1" 303 -
2017-09-12 18:33:15,386 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:15] "GET /web/login HTTP/1.1" 200 -
2017-09-12 18:33:15,646 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:15] "GET /web/webclient/qweb?mods= HTTP/1.1" 304 -
2017-09-12 18:33:15,721 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:15] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
2017-09-12 18:33:15,740 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:15] "POST /website/translations HTTP/1.1" 200 -
2017-09-12 18:33:20,305 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 -
2017-09-12 18:33:20,306 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 404 -
2017-09-12 18:33:20,394 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 404 -
2017-09-12 18:33:20,402 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 -
2017-09-12 18:33:20,403 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 -
2017-09-12 18:33:20,505 1131 INFO odoo werkzeug: 127.0.0.1 - - [12/Sep/2017 18:33:20] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 -
![image](https://user-images.githubusercontent.com/16642593/30342901-22b216f0-97c1-11e7-9dfe-003f300ad227.png)

**Comment by mohamedsaad306** [comment]
@alaherma  i have the same issue , did you manage to fix it  ?

**Comment by JKE-be** [comment]
It is an error in your deployment!

There are no fix to do in Odoo ...

Check the access in file... files static are not found

@alaherma

**Comment by Ark74** [comment]
I've been hit with this exact behavior, I do believe it's related to a postgres update or something similar, since I've been running the server for a month right after this behavior.

Which module is responsible for:
* /web/static/lib/bootstrap/css/bootstrap.css
* /web/static/lib/jquery/jquery.js
* /web/static/lib/bootstrap/js/modal.js
* /web/static/lib/bootstrap/js/tooltip.js
* /web/static/lib/bootstrap/js/dropdown.js
?

**Comment by gdgellatly** [comment]
You need to load web module globally in your config. That is all.

**Comment by mohamedsaad306** [comment]
@gdgellatly  How to do this load globally in config ?

**Comment by gdgellatly** [comment]
server_wide_modules = web
