### ISSUE TITLE
opening an invoice cause error on Android app

### ISSUE THREAD

**Issue by WikiM0tty** [odoo/odoo#119923]
Impacted versions: 4.0.4

Steps to reproduce: go to the invoice module, try to open an invoice.

Current behavior: after a few seconds, the page send back this error message : 
UncaughtPromiseError > NotAllowedError

Expected behavior: should open the invoice page.

Video/Screenshot link (optional):
![Screenshot_20230427_112248_Odoo](https://user-images.githubusercontent.com/16276048/234819316-eb23fa49-2f10-4d9a-9e24-27d28d48cb84.jpg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @WikiM0tty 
Could you provide more information about the steps to reproduce and the impacted version?
Regards,

**Comment by WikiM0tty** [comment]
Hi, there is no more steps to reproduce. It just said error when I try to open an invoice.
This is happening with version 4.0.5 under Android 13.

sometimes I can have this error message:

`UncaughtPromiseError > OwlError
Promesse non interceptée > An error occured in the owl lifecycle (see this Error's "cause" property)

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1247:101)
    at owl.App.handleError (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:2082:29)
    at Fiber._render (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1492:19)
    at Fiber.render (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1490:6)
    at ComponentNode.initiateRender (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1558:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'value')
    at KanbanRecord.template (eval at compile (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:2045:370), <anonymous>:20:47)
    at owl.App.callTemplate (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1707:129)
    at KanbanRecord.template (eval at compile (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:2045:370), <anonymous>:16:16)
    at Fiber._render (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1491:96)
    at Fiber.render (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1490:6)
    at ComponentNode.initiateRender (https://masquedURL.odoo.com/web/assets/772-047df39/web.assets_common.min.js:1558:47)`
