### ISSUE TITLE
[16.0] I get error when i click settings

### ISSUE THREAD

**Issue by hasankayra04** [odoo/odoo#120016]
After todays updates going to settings menu gives error
Impacted versions:
16.0 42723 or 27423
Steps to reproduce:
Click settings
Current behavior:
I get error below:
OwlError: Invalid prop suffix
    at CodeGenerator.formatProp (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1789:12)
    at http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1791:68
    at Array.map ()
    at CodeGenerator.formatPropObject (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1791:50)
    at CodeGenerator.compileComponent (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1794:113)
    at CodeGenerator.compileAST (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1686:558)
    at CodeGenerator.compileTDomNode (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1722:368)
    at CodeGenerator.compileAST (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1686:140)
    at CodeGenerator.compileInNewTarget (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1670:188)
    at CodeGenerator.compileComponent (http://mys.com/web/assets/582-2b0ae07/web.assets_common.min.js:1795:133)

code in 1789th line:

formatProp(name,value){value=this.captureExpression(value);if(name.includes(".")){let[_name,suffix]=name.split(".");if(suffix==="bind"){this.helpers.add("bind");name=_name;value=`bind(this, ${value || undefined})`;}
else{throw new OwlError("Invalid prop suffix");}}

desc:

Based on the provided code, the error occurs when a prop name contains a period (".") character and the suffix after the period is not "bind". In that case, the function throws an OwlError with the message "Invalid prop suffix".

To resolve the error, you need to make sure that all prop names in your code that contain a period character have a valid suffix of "bind". If a prop name with an invalid suffix is necessary, you may need to modify the code to handle it appropriately.

I haven't modified anything at all.
Expected behavior:
Opens settings menu
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by hasankayra04** [comment]
Any updates?

**Comment by vava-odoo** [comment]
Hello @hasankayra04 
Can you provide more information/context about the flow?
Can you reproduce your error on the [runbot](http://runbot.odoo.com/runbot)? (blue door icon of the version row (16) with login/pwd as admin/admin)
Thanks,

**Comment by hasankayra04** [comment]
Fixed by https://www.odoo.com/forum/help-1/uncaughtpromiseerror-owlerror-invalid-prop-suffix-223301
