### ISSUE TITLE
[9.0] openerp.http: Exception during JSON request handling

### ISSUE THREAD

**Issue by dfang** [odoo/odoo#12045]
Impacted versions: 9.0

Steps to reproduce: install from odoo source code 9.0 branch

```
2016-05-15 04:35:32,269 1 INFO ? openerp: OpenERP version 9.0c
2016-05-15 04:35:32,269 1 INFO ? openerp: addons paths: ['/var/lib/odoo/addons/9.0', u'/mnt/extra-addons', u'/opt/odoo/addons', '/opt/odoo/openerp/addons']
2016-05-15 04:35:32,270 1 INFO ? openerp: database: odoo@db:
2016-05-15 04:35:32,844 1 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2016-05-15 04:35:57,180 1 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-05-15 04:35:57,988 1 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2016-05-15 04:35:58,415 1 INFO ? openerp.http: HTTP Configuring static files
2016-05-15 04:35:58,424 1 INFO ? openerp.http: Generating nondb routing
2016-05-15 04:35:58,436 1 ERROR ? openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 1624, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
```

**Comment by sle-odoo** [comment]
This report does not tell much about what you're trying to do and what issue you're facing. Please complete this with more information about your setup and a scenario of what you're trying to do so we can try to reproduce it.

**Comment by dfang** [comment]
steps to reproduce this bug:

1. install from odoo source code 9.0 branch
2. open /web/database/manager, do nothing, just watch odoo logs

**Comment by cbjesse** [comment]
I'm receiving the same error in my logs. I am running a fresh install of Debian Jessie with Odoo 9.0 just pulled from repository this afternoon.  There have not been any custom modules installed at this point either.

**Comment by haidaraM** [comment]
I have the same errors in my logs. Just open the database manager and watch the logs

**Comment by Arsalan88** [comment]
I am experiencing the same issue....
Downloaded the source of odoo9
OS: Ubuntu
set the configuration file
started odoo server
Even without opening the browser, the logs giving this error

**Comment by Arsalan88** [comment]
Solution: 
1. Close all client session (browsers)
2. restart the server

**Comment by ehsanquranwala** [comment]
Thanks for the solution Arsalan88, your solution worked for me
I was trying to set debugging for odoo in pycharm
after solving this error it got done
