### ISSUE TITLE
[16.0] Website demo debug is not working for snippets.  - runbot themes

### ISSUE THREAD

**Issue by 3piece** [odoo/odoo#121115]
Impacted versions: 16.0, 16.x, master 

Steps to reproduce:
Load a fresh 16.0 database or open runbot.odoo.com themes. 

Login and navigate to the following urls:

website/demo/snippets
website/demo/bootstrap
website/demo/color-combinations

Current behavior:

Bootstrap and color-combinations load fine.

Snippets throws the following error:

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1601, in _serve_ir_http
    response = ir_http._serve_fallback()
  File "/data/build/odoo/addons/website/models/ir_http.py", line 329, in _serve_fallback
    website_page.flatten()
  File "/data/build/odoo/odoo/http.py", line 1098, in flatten
    self.response.append(self.render())
  File "/data/build/odoo/odoo/http.py", line 1090, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/data/build/odoo/addons/website/models/ir_ui_view.py", line 418, in _render_template
    return super()._render_template(template, values=values)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 2128, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/data/build/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/data/build/odoo/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<2735>", line 50, in template_2735
  File "<2735>", line 32, in template_2735_content
  File "<2735>", line 21, in template_2735_t_call_0
  File "<2568>", line 1286, in template_2568
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: Element '<div data-oe-id="2052" data-oe-xpath="/data/div" data-oe-model="ir.ui.view" data-oe-field="arch">' cannot be located in parent view
Template: website.snippets
Path: /t/div[5]/t
Node: <t t-call="website.snippet_options"/>
```

Expected behavior:

The snippets debug demo pages should load showing all available snippets in the system.

This same url works on Odoo 15.0

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
#3323122

**Comment by 3piece** [comment]
This is now fixed in the Odoo 16 codebase an working on runbot.

Am I okay to close this issue ?

**Comment by niyasraphy** [comment]
hi @3piece ,
if you think the issue is fixed and no more reproducible, feel free to close the ticket.
thanks
