### ISSUE TITLE
'_TTGlyphSetGlyf' object has no attribute '_hmtx'

### ISSUE THREAD

**Issue by mjrk** [odoo/odoo#121180]
Impacted versions: 16

Steps to reproduce: 

On ubuntu 22.04, install fonttools, print invoice

Current behavior:

-> Exception (Note: it's not always happening, but in a webshop with 

`'_TTGlyphSetGlyf' object has no attribute '_hmtx'
Traceback (most recent call last):
  File "path/odoo/addons/account_edi_ubl_cii/models/account_edi_format.py", line 170, in _prepare_invoice_report
    pdf_writer.convert_to_pdfa()
  File "path/odoo/odoo/tools/pdf.py", line 372, in convert_to_pdfa
    glyphs = ttfont.getGlyphSet()._hmtx.metrics
AttributeError: '_TTGlyphSetGlyf' object has no attribute '_hmtx'`

Expected behavior:

There shouldn't be an AttributeError

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by risto42** [comment]
yeah, we patch OCB as such:
diff --git a/odoo/tools/pdf.py b/odoo/tools/pdf.py
index bd1b05d1b5d..1e3cf8668a4 100644
--- a/odoo/tools/pdf.py
+++ b/odoo/tools/pdf.py
@@ -370,7 +370,15 @@ class OdooPdfFileWriter(PdfFileWriter):
                 stream = io.BytesIO(decompress(font_file._data))
                 ttfont = TTFont(stream)
                 font_upm = ttfont['head'].unitsPerEm
-                glyphs = ttfont.getGlyphSet()._hmtx.metrics
+                # Compatibility fix for different fonttools versions
+                glyph_set = ttfont.getGlyphSet()
+                if hasattr(glyph_set, 'hMetrics'):
+                    glyphs = glyph_set.hMetrics
+                elif hasattr(glyph_set, '_hmtx'):
+                    glyphs = glyph_set._hmtx.metrics
+                else:
+                    # Fallback for unsupported fonttools versions
+                    glyphs = {}
