### ISSUE TITLE
Canceling a Stripe payment after ecommerce product checkout shows 500 Internal server error

### ISSUE THREAD

**Issue by tyuen** [odoo/odoo#121544]
Impacted versions: 16.2+e

Steps to reproduce:
1) Set up Ecommerce App
2) Add Stripe module
3) Turn on developer mode
4) Manually input Stripe api key and secret (has to be production key, not test key)
5) Click get "webhook" to prefill Stripe webhook automatically 
6) Go through steps to buy a product
7) When it's time to enter your credit card, you are on the Stripe.com page
8) Click the Stripe in-page "back" link to cancel the transaction and return to cart

Current behavior:
9. You will be brought back to the /shop/cart page, which now shows a 500 Internal server error (see additional error msg below)
10. Manually going to page root (/) and directly navigating to the shopping cart link shows the same error too. The shopping cart page is inaccessible for this account forever.

If I complete the same steps (starting from 6) with a new user account, I get a blank page with "500: Internal Server Error".
If I complete the same steps (starting from 6) with the admin user account, I get a popup on the page saying:

```
Odoo Client Error
An error occurred
----
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'model')
----
TypeError: Cannot read properties of undefined (reading 'model')
    at Object.getUserModelName (https://www.[redacted]/web/assets/1567-fc63737/web.assets_backend.min.js:12694:464)
    at EditInBackendSystray._updateMainObjectName (https://www.[redacted]/web/assets/1567-fc63737/web.assets_backend.min.js:12390:83)
    at Registry.trigger (https://www.[redacted]/web/assets/1553-8ba3772/web.assets_common.min.js:1282:63)
    at set pageDocument [as pageDocument] (https://www.[redacted]/web/assets/1567-fc63737/web.assets_backend.min.js:12691:59)
    at WebsitePreview._onPageLoaded (https://www.[redacted]/web/assets/1567-fc63737/web.assets_backend.min.js:12601:348)
    at Object.mainEventHandler (https://www.[redacted]/web/assets/1553-8ba3772/web.assets_common.min.js:2097:77)
    at HTMLIFrameElement.listener (https://www.[redacted]/web/assets/1553-8ba3772/web.assets_common.min.js:1294:15)
```

Closing that popup reveals the below error already present behind the popup:

```
QWeb:
Error while render the template
KeyError: 'provider_sudo'
Template: payment_stripe.express_checkout_form
Path: /t/div
Node: <div name="o_express_checkout_container" t-attf-id="o_stripe_express_checkout_container_{{provider_sudo.id}}" t-att-data-provider-id="provider_sudo.id" t-att-data-provider-code="provider_sudo.code" t-att-data-stripe-publishable-key="provider_sudo._stripe_get_publishable_key()" t-att-data-country-code="provider_sudo.company_id.country_id.code" class="w-100 mt-2" t-att-data-stripe_account="provider_sudo.stripe_account_id" data-oe-model="ir.ui.view" data-oe-id="1513" data-oe-field="arch" data-oe-xpath="/t[1]/div[1]"/>
----
The error occurred while rendering the template payment_stripe.express_checkout_form [redacted] <div name="o_express_checkout_container" t-attf-id="o_stripe_express_checkout_container_{{provider_sudo.id}}" t-att-data-provider-id="provider_sudo.id" t-att-data-provider-code="provider_sudo.code" t-att-data-stripe-publishable-key="provider_sudo._stripe_get_publishable_key()" t-att-data-country-code="provider_sudo.company_id.country_id.code" class="w-100 mt-2" t-att-data-stripe_account="provider_sudo.stripe_account_id" data-oe-model="ir.ui.view" data-oe-id="1513" data-oe-field="arch" data-oe-xpath="/t[1]/div[1]"/>
```

Expanding the bottom box further shows:

```
Traceback (most recent call last):
  File "<1513>", line 41, in template_1513
  File "<1513>", line 17, in template_1513_content
KeyError: 'provider_sudo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1698, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/saas-16.2/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1725, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1838, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-16.2/addons/website/models/ir_http.py", line 234, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_http.py", line 156, in _dispatch
    result.flatten()
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1240, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo/saas-16.2/odoo/http.py", line 1232, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/home/odoo/src/odoo/saas-16.2/addons/website/models/ir_ui_view.py", line 440, in _render_template
    return super()._render_template(template, values=values)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_ui_view.py", line 2164, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/home/odoo/src/odoo/saas-16.2/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<1326>", line 230, in template_1326
  File "<1326>", line 212, in template_1326_content
  File "<1326>", line 187, in template_1326_t_call_0
  File "<599>", line 116, in template_599
  File "<599>", line 90, in template_599_content
  File "<1513>", line 47, in template_1513
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'provider_sudo'
Template: payment_stripe.express_checkout_form
Path: /t/div
Node: <div name="o_express_checkout_container" t-attf-id="o_stripe_express_checkout_container_{{provider_sudo.id}}" t-att-data-provider-id="provider_sudo.id" t-att-data-provider-code="provider_sudo.code" t-att-data-stripe-publishable-key="provider_sudo._stripe_get_publishable_key()" t-att-data-country-code="provider_sudo.company_id.country_id.code" class="w-100 mt-2" t-att-data-stripe_account="provider_sudo.stripe_account_id" data-oe-model="ir.ui.view" data-oe-id="1513" data-oe-field="arch" data-oe-xpath="/t[1]/div[1]"/>
```

**Comment by niyasraphy** [comment]
Fixed in:  https://github.com/odoo/odoo/commit/30ee75cbff010c349819eff58c14daf92f0aca58
