### ISSUE TITLE
[9.0][9.0e] Crash When Grouping Purchase Orders By 'Expected Date'

### ISSUE THREAD

**Issue by manney** [odoo/odoo#12161]
**Impacted versions:**
9.0 and 9.0e

**Steps to reproduce:**
1. Go in to Purchases App
2. Go to the Purchase Orders view
3. Then group by 'Expected Date'

**Current behavior:**
Crashes with this error:
```
Traceback (most recent call last):
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo9-enterprise/core/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo9-enterprise/enterprise/web/controllers/main.py", line 907, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo9-enterprise/enterprise/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/models.py", line 2058, in read_group
    for gb in groupby_list
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/models.py", line 1924, in _read_group_process_groupby
    qualified_field = self._inherits_join_calc(self._table, split[0], query)
  File "/odoo/odoo9-enterprise/core/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo9-enterprise/core/openerp/models.py", line 2185, in _inherits_join_calc
    translate = model._columns[field].translate
KeyError: u'date_planned'
```
I also have this from my local install of Odoo 9 Community:
```
2016-05-24 22:13:56,177 21668 ERROR odoo-test openerp.http: Exception during JSON request handling.
```

**Expected behavior:**
Groups purchase orders by expected date.

**Comment by Yenthe666** [comment]
Hi @manney,

Thank you for your report! I've tested this and can confirm this is a bug.

Regards,
Yenthe

**Comment by nim-odoo** [comment]
This is fixed in 41759e8e4080d9003a41b8ecab229c7b67dedcfd. Unfortunately we can't easily fix it in a stable version, so the only solution would be to remove the filter.

**Comment by Yenthe666** [comment]
Oh man, looks like a broken filter until V10. Too bad..

**Comment by manney** [comment]
Thanks for your help guys.  I was going to show this to a customer, but I guess we'll have to figure out a way around this.
