### ISSUE TITLE
[9.0][BUG] Constraints conflict with COA import

### ISSUE THREAD

**Issue by kenneth-vkd** [odoo/odoo#12178]
While trying to create a module that iincludes csv-files with COA, tax and account tags, we discovered an issue when having references to account tags and tax records in the COA.
Since account tags have to be imported first so that they can be used with the taxes this has to go first, but we are importing the COA with references to taxes, taxes can however not be imported without having the COA.

There seems to be a conflict in the model constraints in the relations

Impacted versions: 9.0

Steps to reproduce:
Import account tags, tax and COA using a module, where the COA contains references to the imported taxes and account tags

Current behavior:

Import order:
1. account tags (account.account.tags.csv)
2. account taxes (account.tax.template.csv)
3. COA (account.account.template.csv)

Fails to install the module with the following error:
Exception: Module loading mymodule_name failed: file mymodule_name\data/account.tax.template.csv could not be processed:
 Line 1 : No matching record found for external id '6902' in field 'Tax Account on Refunds'

Import order:
1. account tags (account.account.tags.csv)
2. COA (account.account.template.csv)
3. account taxes (account.tax.template.csv)

Fails to install the module with the following error:
Exception: Module loading mymodule_name failed: file mymodule_name\data/account.account.template.csv could not be processed:
 Line 1 : No matching record found for external id 'tax_sale' in field 'Default Taxes'

Expected behavior:
Import tags, tax and COA when a default tax is set on the COA

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look at this one? My experience doesn't go far enough for this one. :sweat_smile:

**Comment by qdp-odoo** [comment]
hello,

you need to define the objects you reference first, but without the full definition of it. Just the required fields. Then you load the csv files normally, by making sure that your referenced objects are now fully defined with the same XML ID (will be overwritten).

so, in your example, you can do:
1. account tags (account.account.tags.csv)
2. COA (account.account.template.csv) but without any default taxes set
3. account taxes (account.tax.template.csv)
4. completion of COA accounts with missing columns (default taxes)

best regards

**Comment by qdp-odoo** [comment]
ho and yes: that's not a bug at all... It was more a question actually.

**Comment by kenneth-vkd** [comment]
Ok. That is then the issue.
But what should I name this file that updates the COA with the taxes.
If I just put in a file with some name like account.account.template.tax_ids then it fails with this error:

`Traceback (most recent call last):
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 643, in _handle_exception
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 680, in dispatch
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 316, in _call_function
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\service\model.py", line 118, in wrapper
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 309, in checked_call
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 959, in __call__
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\http.py", line 509, in response_wrap
  File "I:\Program Files (x86)\Odoo 9.0e\server\openerp\addons\web\controllers\main.py", line 911, in call_button
  File "I:\Program Files (x86)\Odoo 9.0e\server\openerp\addons\web\controllers\main.py", line 899, in _call_kw
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\api.py", line 250, in wrapper
  File "I:\Program Files (x86)\Odoo 9.0e\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\api.py", line 250, in wrapper
  File "I:\Program Files (x86)\Odoo 9.0e\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\registry.py", line 386, in new
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\loading.py", line 338, in load_modules
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\loading.py", line 156, in load_module_graph
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\loading.py", line 98, in _load_data
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\tools\convert.py", line 845, in convert_file
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\tools\convert.py", line 910, in convert_csv_import
  File "I:\Program Files (x86)\Odoo 9.0e\server\.\openerp\modules\registry.py", line 84, in __getitem__
KeyError: u'account.account.template.tax_ids'`

There must be a specific way this should be named, but where can I find information about this?
