### ISSUE TITLE
I cannot access to contacts due to an error " Cannot read properties of undefined (reading 'string')"

### ISSUE THREAD

**Issue by Grief6915** [odoo/odoo#122134]
Hello everyone, I am days back from a mistake that is preventing my company from working. I've tried everything but I don't know what else to do.

I have the following error:

I cannot access to contacts due to an error " Cannot read properties of undefined (reading 'string')"

I just simply want to open contacts and it gives me this error

Cannot read properties of undefined (reading 'string')

I have no idea how to fix it

TypeError: Cannot read properties of undefined (reading 'string')
    at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6575:211
    at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:200)
    at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
    at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:211)
    at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
    at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)
    at traverse (http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:211)
    at http://localhost:8069/web/assets/5955-6249fb3/web.assets_backend.min.js:6570:242
    at Function.each (http://localhost:8069/web/assets/4367-3b809bf/web.assets_common.min.js:171:149)
	
This happened after installing the following module: Vendor Purchase Discount
by Cybrosys Techno Solutions - this module was for version 15 of Odoo and I got the 16.

I've tried to upgrade the module but to no avail.

The error you gave me was in the following file error_service.js 

console.error(uncaughtError.traceback); //-> Error in this line

handleError(uncaughtError); // -> Error in this line

I've tried everything but I don't know what else to do.

Help for resolve this error

**Comment by niyasraphy** [comment]
hi @Grief6915 ,
did you update the source code to the latest and upgraded all the modules in the db ? if not have a try and ensure custom codes are not causing any issue.

as the same is not reproducible in odoo runbot, i beleave this is something specific to your instance.
thanks

**Comment by Grief6915** [comment]
Hello I do not know how to upgrade to all modules in db. My installation is on windows, and is not linked to github, so I can not do / do not know how to update the code to the latest version.
