### ISSUE TITLE
[9.0][regression] account: Reconciled invoice can't be opened

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#12269]
Impacted versions: 9.0

Steps to reproduce: Reconcile invoice before this commit https://github.com/odoo/odoo/commit/5f9ca1b89becb6867d0755cf7cb3d7f9c533e7af and try to open form view after applying this commit

Current behavior: Stack trace when trying to open form view of invoice which was created and paid before commint:

```
Odoo Server Error
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in handle_exception
return super(JsonRequest, self).handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in dispatch
result = self._call_function(*self.params)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
return f(dbname, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
result = self.endpoint(a, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call
return self.method(args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
response = f(args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 896, in call_kw
return self.call_kw(model, method, args, kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 888, in call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
return old_api(self, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3193, in read
result = BaseModel.read(records, fields, load=load)
File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
return new_api(self, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3239, in read
values[name] = field.convert_to_read(record[name], use_name_get)
File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5740, in __getitem
return self.fields[key].__get_(self, type(self))
File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 829, in get
self.determine_value(record)
File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 936, in determine_value
self.compute_value(recs)
File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 891, in compute_value
self.compute_value(records)
File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 881, in compute_value
getattr(records, self.compute)()
File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
return new_api(self, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 425, in new_api
result = [method(rec, args, *kwargs) for rec in self]
File "/usr/lib/python2.7/dist-packages/openerp/addons/account/models/account_invoice.py", line 158, in _get_payment_info_JSON
payment_currency_id = all([p.currency_id == payment.matched_credit_ids[0].currency_id for p in payment.matched_credit_ids]) and payment.matched_credit_ids[0].currency_id or False
File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5744, in __getitem
return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range
``` 

Expected behavior: Invoice should be opened without errors

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo you've made this commit, perhaps you can shed some light on this one? @mart-e pinging you for this one too.

**Comment by qdp-odoo** [comment]
cannot reproduce... and I don't see any point where it could theoretically fail with the given error message  !

**Comment by qdp-odoo** [comment]
geez, guys... >_<

https://github.com/odoo/odoo/commit/272c7b26f

**Comment by lem8r** [comment]
I don't know how to reproduce it too. I just have list of paid invoices, some of them can't be opened after this update. Database is not broken

**Comment by Yenthe666** [comment]
@lem8r the commit that @qdp-odoo linked should fix your issue. It was added four days after the commit that broke things. Do another Odoo update and it should be fixed!

**Comment by lem8r** [comment]
Yeah, I'll try it. Thanks)

**Comment by lem8r** [comment]
Just updated Odoo and problem is gone
Thanks again!

**Comment by Yenthe666** [comment]
Great to hear! Best of luck with Odoo.
