### ISSUE TITLE
RPC_ERROR: Odoo Server Error for Module Inventory Activity

### ISSUE THREAD

**Issue by syhrlfdllh** [odoo/odoo#122806]
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoo/odoo-server/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/odoo-server/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/odoo-server/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/odoo-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/stock/models/stock_picking.py", line 1086, in button_validate
    pickings_not_to_backorder.with_context(cancel_backorder=True)._action_done()
  File "/odoo/odoo-server/addons/sale_stock/models/stock.py", line 84, in _action_done
    res = super()._action_done()
  File "/odoo/odoo-server/addons/stock/models/stock_picking.py", line 892, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/odoo/odoo-server/addons/stock_account/models/stock_move.py", line 259, in _action_done
    for move in res - self:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'stock.move'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://erp.sbp.net.id/web/assets/2171-5c63445/web.assets_backend.min.js:970:163)
    at XMLHttpRequest. (http://erp.sbp.net.id/web/assets/2171-5c63445/web.assets_backend.min.js:978:13)

Error happen when i use inventory module, like for add stock, add product, receipt, sending.
Can help to solved this issue ?

Thanks

**Comment by niyasraphy** [comment]
hi @syhrlfdllh ,
please add more info like, version umber, how to reproduce the bug, also check in runbot and see if you can reproduce it there: https://runbot.odoo.com/

thanks

**Comment by syhrlfdllh** [comment]
> hi @syhrlfdllh , please add more info like, version umber, how to reproduce the bug, also check in runbot and see if you can reproduce it there: https://runbot.odoo.com/
> 
> thanks

hi @niyasraphy 

we are using Odoo 16.0 (Community Edition)

thanks

**Comment by niyasraphy** [comment]
@syhrlfdllh please provide the steps to reproduce the issue

**Comment by syhrlfdllh** [comment]
> please provide the steps to reproduce the issue

@niyasraphy 

1. When i want to "validate" the receipt process
2. When i want to "update quantity" on product
3. When i want to "validate" the delivery process

thats all i test and the same log error comes
