### ISSUE TITLE
odoo16 website error web.assets_common.min.js:1247:101

### ISSUE THREAD

**Issue by lauraruggerilinea** [odoo/odoo#123956]
Impacted versions: 16

Steps to reproduce:
When install website in odoo16 error in common asset load:
`OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://ppp.com/web/assets/204-6073476/web.assets_common.min.js:1247:101)
    at owl.App.handleError (https://ppp.com/web/assets/204-6073476/web.assets_common.min.js:2082:29)
    at ComponentNode.initiateRender (https://ppp.com/web/assets/204-6073476/web.assets_common.min.js:1557:19)

Caused by: AssetsLoadingError: The loading of /web/assets/209-7a13a9b/website.assets_wysiwyg.min.css failed
    at HTMLLinkElement.<anonymous> (https://ppp.com/web/assets/205-e6759fd/web.assets_backend.min.js:20:470)`

**Comment by lauraruggerilinea** [comment]
ho trovato il problema e riguarda una configurazione di nginx di sicurezza. Abbiamo aggiunto questa riga e in fase di generazione degli assets genera l'errore riportato:
`add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self'; frame-src 'self'; object-src 'none'; media-src 'self';" always;`
