### ISSUE TITLE
[9.0] Cannot validate invoice with purchased assets if it was cancelled before

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#12446]
Impacted versions:
9.0c (latest version JUNE 16)

Steps to reproduce:
1) Create a product or two and make sure you set `Asset Type`
2) Create a PO with the products your created earlier
3) `Validate` PO then `Receive Products`
4) After receving products and they are in stock, click on `Invoices` then `Create` to create a new invoice
5) Click on `Validate` to validate invoice 

6) Let's say you made a mistake after validation and you want to fix your invoice, you can't edit it so the only way to do it is to cancel it,click on `Cancel Invoice` , then `Reset to draft`
>Note: after clicking on `Reset to draft`, if you go to `Assets` page in `Accounting` you will notice these two products are still there and they are not removed, maybe this is related to my issue? not sure

7) Click on `Edit` to edit your invoice, update any inputs i.e. set `Analytic account` for your products , then `Save`
8) Click on `Validate` to validate invoice
9) An error message appears

````
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 907, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/odoo/odoo-server/openerp/http.py", line 1270, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/odoo/odoo-server/openerp/http.py", line 1038, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/odoo/odoo-server/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/odoo/odoo-server/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 194, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/odoo/odoo-server/openerp/service/model.py", line 188, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/odoo/odoo-server/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3617, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/odoo/odoo-server/openerp/workflow/__init__.py", line 67, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/odoo/odoo-server/openerp/workflow/service.py", line 73, in validate
    res2 = wi.validate(signal)
  File "/odoo/odoo-server/openerp/workflow/instance.py", line 62, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 102, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 230, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 239, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 77, in create
    workflow_item.process(stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 98, in process
    if not self._execute(activity, stack):
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 144, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 295, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 273, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/odoo/odoo-server/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account_asset/account_asset_invoice.py", line 22, in action_move_create
    asset_ids.write({'active': False})
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account_asset/account_asset.py", line 363, in write
    self.compute_depreciation_board()
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account_asset/account_asset.py", line 155, in compute_depreciation_board
    self.ensure_one()
  File "/odoo/odoo-server/openerp/models.py", line 5403, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: "Expected singleton: account.asset.asset(4, 5)" while evaluating
u'action_move_create()'
````

Current behavior:
You cannot validate invoice with purchased assets if it was cancelled before,and for sure you can't delete it, it's stuck!

Expected behavior:
I should be able to validate invoice with no problems
 
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look at this?

**Comment by qdp-odoo** [comment]
I cannot reproduce it, and that error is very strange since it is supposed to be solved since https://github.com/odoo/odoo/commit/9d14230d (Apr 25).


Are you <i>very</i> sure your code is up-to-date?

**Comment by alaa9jo** [comment]
Of course I'm very suremy code is up to date with branch 9.0 ,I even pulled latest update and the issue still occurs

**Comment by Yenthe666** [comment]
@alaa9jo could you perhaps make a video? Then we can see the exact way to reproduce this and try again.

**Comment by qdp-odoo** [comment]
ok, the problem is that you had already several assets related to the same invoice. So when it tries to set the supposed only one to inactive it raises the error because you've already 2, which is not supposed to happen.

  File "/odoo/odoo-server/addons/account_asset/account_asset_invoice.py", line 22, in action_move_create
    asset_ids.write({'active': False})

So, you won't have that problem anymore, but in order to fix that you need to manually cancel first the assets with ID 4 and 5 (at least one).

**Comment by alaa9jo** [comment]
> ok, the problem is that you had already several assets related to the same invoice

@qdp-odoo that's it, this is exactly the cause of the problem, when invoice is validated,odoo add assets related to the invoice automatically,but when invoice is cancelled and returned to draft,I expected odoo to remove related assets automatically, and add them after invoice is validated, or maybe I expected odoo to detect what exactly has changed; did I change info related to my invoice or related to assets as well,then acts accordingly.

Nonetheless, I followed your suggestion and removed all assets related to my invoice, and I was able to validate my invoice
