### ISSUE TITLE
in dev mod , database  structure>modle>create>in add field item panel>advance setting tag>first input occur an error

### ISSUE THREAD

**Issue by 474416133** [odoo/odoo#12455]
Impacted versions:odoo 9.0c

Steps to reproduce:

error msg:
Uncaught Error: NameError: name 'model_id' is not defined
http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:370
追溯
Error: NameError: name 'model_id' is not defined
    at PY_ensurepy (http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:370:19)
    at Object.py.evaluate (http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:1340:20)
    at Object.py.evaluate (http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:1397:38)
    at Object.py.evaluate (http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:1409:37)
    at Object.py.eval (http://127.0.0.1:8069/web/static/lib/py.js/lib/py.js:1453:19)
    at http://127.0.0.1:8069/web/static/src/js/framework/pyeval.js:862:35
    at Function._.each._.forEach (http://127.0.0.1:8069/web/static/lib/underscore/underscore.js:145:9)
    at _.(anonymous function) [as each] (http://127.0.0.1:8069/web/static/lib/underscore/underscore.js:1484:34)
    at eval_domains (http://127.0.0.1:8069/web/static/src/js/framework/pyeval.js:853:16)
    at http://127.0.0.1:8069/web/static/src/js/framework/pyeval.js:867:32

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![1-1](https://cloud.githubusercontent.com/assets/17959465/16116631/a068a01c-3400-11e6-90b2-c79af0e7cfec.png)
![1-3](https://cloud.githubusercontent.com/assets/17959465/16116650/b91da918-3400-11e6-939f-e1ba7f109c35.png)
![1-4](https://cloud.githubusercontent.com/assets/17959465/16116649/b8c16cf2-3400-11e6-858d-1e3e1564d399.png)
![Uploading 1-5.png…]()

**Comment by 474416133** [comment]
![1-5](https://cloud.githubusercontent.com/assets/17959465/16143145/693f76c2-349d-11e6-8c8e-fb2d2c9b7218.png)
