### ISSUE TITLE
[8.0] Installing new chart of accounts results in error

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12471]
Impacted versions: 8.0

Steps to reproduce:
 1. Go to settings > Accounting
 2. Choose a chart of account and try to install it.

Current behavior:
A major error happens and you're unable to install a chart of account. Full stacktrace:
`Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/tools/convert.py", line 528, in _tag_workflow
    uid, model, id, rec.get('action').encode('ascii'), cr)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/account/account_invoice.py", line 931, in action_move_create
    move.post()
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/account_sequence/account_sequence.py", line 36, in post
    res = super(account_move, self).post(cr, uid, ids, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/account/account.py", line 1336, in post
    self.write(cr, uid, [move.id], {'name':new_name})
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/account/account.py", line 1377, in write
    result = super(account_move, self).write(cr, uid, ids, vals, c)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/models.py", line 3788, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/models.py", line 4041, in _write
    recs.recompute()
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/models.py", line 5761, in recompute
    rec._write(values)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/models.py", line 3899, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: ""duplicate key value violates unique constraint "account_invoice_number_uniq"
DETAIL:  Key (number, company_id, journal_id, type)=(SAJ/2016/001, 1, 1, out_invoice) already exists.
" while evaluating
u'action_move_create()'" while parsing /home/odoo/runbot/extra/runbot/static/build/154378-8-0-bdf939/openerp/addons/l10n_be_coda/l10n_be_coda_demo.xml:57, near
<workflow action="invoice_open" model="account.invoice" ref="coda_demo_invoice_1"/>`
![issue](https://cloud.githubusercontent.com/assets/6352350/16145645/0a68c37e-347a-11e6-8856-4b698c88acc6.PNG)

Expected behavior:
The chart of account installs perfectly.

**Comment by Yenthe666** [comment]
@qdp-odoo another one for you I'm afraid :smile:

**Comment by qdp-odoo** [comment]
It was a weird one, but should be fixed since revision https://github.com/odoo/odoo/commit/ba49172929559aeff0be5e59fd95b5562fab3224

Glad we don't have that next-numbering-thing in v9....

**Comment by Yenthe666** [comment]
Great job, thanks!
