### ISSUE TITLE
Client Error:UncaughtPromiseError OwlError

### ISSUE THREAD

**Issue by zizle** [odoo/odoo#125512]
An error occurred

Please use the copy button to report the error to your support service.

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8069/web/assets/205-8947824/web.assets_common.min.js:1247:101)
    at owl.App.handleError (http://localhost:8069/web/assets/205-8947824/web.assets_common.min.js:2082:29)
    at Fiber._render (http://localhost:8069/web/assets/205-8947824/web.assets_common.min.js:1492:19)
    at Fiber.render (http://localhost:8069/web/assets/205-8947824/web.assets_common.min.js:1490:6)
    at ComponentNode.initiateRender (http://localhost:8069/web/assets/205-8947824/web.assets_common.min.js:1558:47)

Caused by: TypeError: str.replaceAll is not a function
    at toStringExpression (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5481:97)
    at KanbanCompiler.renderDropdown (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:4203:174)
    at KanbanCompiler.compileDropdown (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:4217:67)
    at KanbanCompiler.compileNode (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5583:124)
    at KanbanCompiler.compileGenericNode (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5595:56)
    at KanbanCompiler.compileNode (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5583:254)
    at KanbanCompiler.compileGenericNode (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5595:56)
    at KanbanCompiler.compileNode (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5583:254)
    at KanbanCompiler.compile (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5579:41)
    at useViewCompiler (http://localhost:8069/web/assets/206-a53e851/web.assets_backend.min.js:5605:172)

when i build the develop environment and login.(the source code version is odoo 16)
I'm a newcomer at odoo，help! it can not running...

**Comment by niyasraphy** [comment]
hi @zizle ,
i think this is not a bug inside odoo, but something specific to your odoo instance. you can do the following
* make sure you have the latest source code of odoo 16
* custom codes are not causing any issues

if you feel this is a bug in odoo, see if you can reproduce it in odoo runbot and if yes, please provide more details to reproduce it. in case if it is not reproducible in runbot, you can post the same in help forums to get support:  https://www.odoo.com/forum/help-1

thanks

**Comment by zizle** [comment]
Oops！That's a problem with my browser！The Chromium Version was too old...
after I update it. odoo is working now.I was negligent，Sorry.
