### ISSUE TITLE
[BUG] [15.0] [fetchmail]

### ISSUE THREAD

**Issue by jabelchi** [odoo/odoo#126185]
Impacted versions: 
15.0 Enterprise On premise

Steps to reproduce: 
Automaticaly receive and email

Current behavior:
Just once, as far as we know, one incoming email raised an exception. The mail wasn't processed and no notification was received. We marked the message as unread, to force a new download, and this second time everything went well.

Expected behavior:
When an exception appears in the mail download, it is notified in some way.

Log of the exception:
2023-06-14 13:00:12,792 2199294 INFO midgard.com-on.cat odoo.addons.fetchmail.models.fetchmail: General failure when trying to fetch mail from imap server asistencia@midgard.com-on.cat IMAP SSL (DinaHosting).
Traceback (most recent call last):
File "/usr/lib/python3.9/imaplib.py", line 1047, in _command_complete
typ, data = self._get_tagged_response(tag, expect_bye=logout)
File "/usr/lib/python3.9/imaplib.py", line 1173, in _get_tagged_response
self._get_response()
File "/usr/lib/python3.9/imaplib.py", line 1130, in _get_response
dat = self._get_line()
File "/usr/lib/python3.9/imaplib.py", line 1185, in _get_line
raise self.abort('socket error: EOF')
imaplib.IMAP4.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/fetchmail/models/fetchmail.py", line 189, in fetch_mail
result, data = imap_server.fetch(num, '(RFC822)')
File "/usr/lib/python3.9/imaplib.py", line 548, in fetch
typ, dat = self._simple_command(name, message_set, message_parts)
File "/usr/lib/python3.9/imaplib.py", line 1230, in _simple_command
return self._command_complete(name, self._command(name, *args))
File "/usr/lib/python3.9/imaplib.py", line 1049, in _command_complete
raise self.abort('command: %s => %s' % (name, val))
imaplib.IMAP4.abort: command: FETCH => socket error: EOF
2023-06-14 13:00:12,807 2199294 ERROR midgard.com-on.cat odoo.addons.base.models.ir_cron: Call from cron Mail: Fetchmail Service for server action #139 failed in Job #8
Traceback (most recent call last):
File "/usr/lib/python3.9/imaplib.py", line 1047, in _command_complete
typ, data = self._get_tagged_response(tag, expect_bye=logout)
File "/usr/lib/python3.9/imaplib.py", line 1173, in _get_tagged_response
self._get_response()
File "/usr/lib/python3.9/imaplib.py", line 1075, in _get_response
resp = self._get_line()
File "/usr/lib/python3.9/imaplib.py", line 1185, in _get_line
raise self.abort('socket error: EOF')
imaplib.IMAP4.abort: socket error: EOF

**Comment by jabelchi** [comment]
It happened again, exactly the same as the first time.
I know that this may be a problem for our hosting, but I believe that possible exceptions should be monitored.
