### ISSUE TITLE
Error opening the inbox client action 

### ISSUE THREAD

**Issue by aek** [odoo/odoo#12681]
Impacted versions: 
v8, v9, online(enterprise free test)

Steps to reproduce: 
In v8, v9 find the menuitem for messaging inbox in the technical settings menu and open the action
In Odoo online open the discuss app, activate the developer mode, on the Developer tools footer clic on the action link and next clic on the edit action

Current behavior:
#Error v8, v9
```` Python
Traceback (most recent call last):
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/opt/soltein/odoo-8.0/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/soltein/odoo-8.0/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/soltein/odoo-8.0/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/soltein/odoo-8.0/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/opt/soltein/odoo-8.0/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/soltein/odoo-8.0/openerp/models.py", line 3366, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/soltein/odoo-8.0/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/soltein/odoo-8.0/openerp/addons/base/ir/ir_actions.py", line 1199, in _get_params
    result[record.id] = record.params_store and eval(record.params_store, {'uid': uid}) or False
  File "/opt/soltein/odoo-8.0/openerp/tools/safe_eval.py", line 312, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/soltein/odoo-8.0/openerp/tools/safe_eval.py", line 167, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    305 bytes
            ^
SyntaxError: unexpected EOF while parsing
```
#Error online
```` Python
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/saas-10/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/enterprise/saas-10/web/controllers/main.py", line 900, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/enterprise/saas-10/web/controllers/main.py", line 892, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/api.py", line 254, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/models.py", line 3291, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/src/odoo/saas-10/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/models.py", line 3326, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/src/odoo/saas-10/openerp/api.py", line 252, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-10/openerp/models.py", line 3517, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/odoo/src/odoo/saas-10/openerp/osv/fields.py", line 1507, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/odoo/src/odoo/saas-10/openerp/addons/base/ir/ir_actions.py", line 1276, in _get_params
    result[record.id] = record.params_store and eval(record.params_store, {'uid': uid}) or False
  File "/home/odoo/src/odoo/saas-10/openerp/tools/safe_eval.py", line 297, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/home/odoo/src/odoo/saas-10/openerp/tools/safe_eval.py", line 154, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    68 bytes
           ^
SyntaxError: unexpected EOF while parsing
```

Expected behavior:
Work without error

Video/Screenshot link (optional):
![screenshot from 2016-07-05 01 32 03](https://cloud.githubusercontent.com/assets/404966/16578622/5cf44fc6-4250-11e6-8d7e-ece0f97f9e5d.png)
![screenshot from 2016-07-05 01 32 15](https://cloud.githubusercontent.com/assets/404966/16578621/5cf360ac-4250-11e6-93e4-16787bf2ad8c.png)

**Comment by Yenthe666** [comment]
Hi @aek,

Thanks a lot for your report, I just managed to reproduce this on the latest runbot:
![image](https://cloud.githubusercontent.com/assets/6352350/16620351/6c2e3b9e-4392-11e6-8d95-6eb84a1b4baf.png)
@mart-e can you assign somebody on this please?

**Comment by mart-e** [comment]
Fixed at 0df7a1ca2f86b63911a5822ccccf4ab00bcd341c
Thanks for the report

**Comment by aek** [comment]
nice work, congrats for the quick response for both!!!

**Comment by aek** [comment]
Just a quote that I managed to see it on v8 and v9 and assume that in master with the @Yenthe666 test. I saw the PR against the v8 only. Is this something the just get merged latter?

**Comment by mart-e** [comment]
@aek don't worry every commit is ported to upper versions. So a commit made in 8.0 will ends up in 9.0 and master, just need a bit of time to be forward ported.
