### ISSUE TITLE
Error installing Project Management on Odoo - 8.0.1.1

### ISSUE THREAD

**Issue by tsartas** [odoo/odoo#12692]
Impacted versions:  Project Management 8.0.1.1

Steps to reproduce: Press the Installation of Module

Current behavior: Cannot Install the Module

Expected behavior:Module Installation

Video/Screenshot link (optional):

```
Error: OpenERP Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/var/packages/Odoo8/target/addons/web/controllers/main.py", line 1252, in run
    [action_id], request.context)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 834, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_actions.py", line 1011, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/packages/Odoo8/target/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_actions.py", line 848, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/safe_eval.py", line 315, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 185, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 756, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 841, in model_id_get
    return model_data_obj.get_object_reference(cr, self.uid, mod, id_str)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 946, in get_object_reference
    return self.xmlid_lookup(cr, uid, "%s.%s" % (module, xml_id))[1:3]
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 904, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: "" while evaluating
u"self.button_immediate_install(cr, uid, context.get('active_ids', []), context=context)"
```

**Comment by tsartas** [comment]
Any ideas of how to install the Module?

**Comment by mart-e** [comment]
Hello,

You server code looks quite outdated (at least 2015), could you try to update it first?
Also which button do you click exactly? Could you provide a screenshot?

**Comment by Yenthe666** [comment]
Hi @tsartas,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
