### ISSUE TITLE
Odoo 16: Fail to install Studio

### ISSUE THREAD

**Issue by jasoniem9246** [odoo/odoo#126928]
Impacted versions: 16.0

Steps to reproduce: Install Studio

Current behavior: show 500 error

Expected behavior: No Error

I have tried Python 3.9.6 and 3.10.11. Both show the same error as below: 

```
2023-06-30 08:27:43,448 26800 INFO odoo16 odoo.addons.base.models.ir_http: Generating routing map for key 1 
2023-06-30 08:27:48,976 26800 ERROR odoo16 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/lru.py", line 35, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._generate_asset_nodes_cache at 0x108a750d0>, 'web.assets_backend', False, True, '', False, False, False, False, ('en_US', None, None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<191>", line 323, in template_191
  File "<191>", line 305, in template_191_content
  File "<191>", line 274, in template_191_t_call_0
  File "<191>", line 191, in template_191_t_set_2
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_qweb.py", line 2415, in _get_asset_nodes
    return self._generate_asset_nodes_cache(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "<decorator-gen-68>", line 2, in _generate_asset_nodes_cache
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_qweb.py", line 2470, in _generate_asset_nodes_cache
    return self._generate_asset_nodes(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_qweb.py", line 2544, in _generate_asset_nodes
    return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load, defer_load=defer_load, lazy_load=lazy_load)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/assetsbundle.py", line 181, in to_node
    js_attachment = self.js(is_minified=not is_debug_assets)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/assetsbundle.py", line 394, in js
    content.append(self.xml(show_inherit_info=not is_minified))
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/assetsbundle.py", line 556, in xml
    inherited_template = apply_inheritance_specs(parent_tree, xpaths)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/template_inheritance.py", line 265, in apply_inheritance_specs
    raise ValueError(
ValueError: Element '<xpath expr="./div[1]">' cannot be located in parent view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1998, in __call__
    response = request._serve_db()
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1725, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_http.py", line 156, in _dispatch
    result.flatten()
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1099, in flatten
    self.response.append(self.render())
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/http.py", line 1091, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/addons/website/models/ir_ui_view.py", line 418, in _render_template
    return super()._render_template(template, values=values)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_ui_view.py", line 2128, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/Users/tsung-hsienlin/Workspace/odoo-16/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<191>", line 329, in template_191
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: Element '<xpath expr="./div[1]">' cannot be located in parent view
Template: web.webclient_bootstrap
Path: /t/t/t[1]/t[4]
Node: <t t-call-assets="web.assets_backend" t-css="false"/>
```

**Comment by niyasraphy** [comment]
hi @jasoniem9246 .
i have tried to reproduce the same in my local in a fresh db with latest source code of ce/ee and seems there is no such issue and module is getting installed.

Can you confirm that you are having latest source code and custom codes are not causing the issues, also see if you can reproduce the same runbot.


Thanks

**Comment by jasoniem9246** [comment]
> 

Just get the latest code and working fine.
