### ISSUE TITLE
Need to drop view before recreation

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#12754]
Impacted versions: certainly 8.0

Steps to reproduce: Update module hr_timesheet_sheet

Current behavior: Error (see below). Server crash.

Expected behavior: no error

Video/Screenshot link (optional):
```
2016-07-11 11:54:22,946 22667 INFO odomsadem80 openerp.modules.module: module hr_timesheet_sheet: creating or updating database tables
2016-07-11 11:54:23,056 22667 ERROR odomsadem80 openerp.sql_db: Programming error: cannot drop columns from view
, in query create or replace view hr_timesheet_sheet_sheet_day as
            SELECT
                id,
                name,
                sheet_id,
                total_timesheet,
                total_attendance,
                cast(round(cast(total_attendance - total_timesheet as Numeric),2) as Double Precision) AS total_difference
            FROM
                ((
                    SELECT
                        MAX(id) as id,
                        name,
                        sheet_id,
                        timezone,
                        SUM(total_timesheet) as total_timesheet,
                        CASE WHEN SUM(orphan_attendances) != 0
                            THEN (SUM(total_attendance) +
                                CASE WHEN current_date <> name
                                    THEN 1440
                                    ELSE (EXTRACT(hour FROM current_time AT TIME ZONE 'UTC' AT TIME ZONE coalesce(timezone, 'UTC')) * 60) + EXTRACT(minute FROM current_time AT TIME ZONE 'UTC' AT TIME ZONE coalesce(timezone, 'UTC'))
                                END
                                )
                            ELSE SUM(total_attendance)
                        END /60  as total_attendance
                    FROM
                        ((
                            select
                                min(hrt.id) as id,
                                p.tz as timezone,
                                l.date::date as name,
                                s.id as sheet_id,
                                sum(l.unit_amount) as total_timesheet,
                                0 as orphan_attendances,
                                0.0 as total_attendance
                            from
                                hr_analytic_timesheet hrt
                                JOIN account_analytic_line l ON l.id = hrt.line_id
                                LEFT JOIN hr_timesheet_sheet_sheet s ON s.id = hrt.sheet_id
                                JOIN hr_employee e ON s.employee_id = e.id
                                JOIN resource_resource r ON e.resource_id = r.id
                                LEFT JOIN res_users u ON r.user_id = u.id
                                LEFT JOIN res_partner p ON u.partner_id = p.id
                            group by l.date::date, s.id, timezone
                        ) union (
                            select
                                -min(a.id) as id,
                                p.tz as timezone,
                                (a.name AT TIME ZONE 'UTC' AT TIME ZONE coalesce(p.tz, 'UTC'))::date as name,
                                s.id as sheet_id,
                                0.0 as total_timesheet,
                                SUM(CASE WHEN a.action = 'sign_in' THEN -1 ELSE 1 END) as orphan_attendances,
                                SUM(((EXTRACT(hour FROM (a.name AT TIME ZONE 'UTC' AT TIME ZONE coalesce(p.tz, 'UTC'))) * 60) + EXTRACT(minute FROM (a.name AT TIME ZONE 'UTC' AT TIME ZONE coalesce(p.tz, 'UTC')))) * (CASE WHEN a.action = 'sign_in' THEN -1 ELSE 1 END)) as total_attendance
                            from
                                hr_attendance a
                                LEFT JOIN hr_timesheet_sheet_sheet s
                                ON s.id = a.sheet_id
                                JOIN hr_employee e
                                ON a.employee_id = e.id
                                JOIN resource_resource r
                                ON e.resource_id = r.id
                                LEFT JOIN res_users u
                                ON r.user_id = u.id
                                LEFT JOIN res_partner p
                                ON u.partner_id = p.id
                            WHERE action in ('sign_in', 'sign_out')
                            group by (a.name AT TIME ZONE 'UTC' AT TIME ZONE coalesce(p.tz, 'UTC'))::date, s.id, timezone
                        )) AS foo
                        GROUP BY name, sheet_id, timezone
                )) AS bar
2016-07-11 11:54:23,056 22667 CRITICAL odomsadem80 openerp.service.server: Failed to initialize database `odomsadem80`.
Traceback (most recent call last):
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/service/server.py", line 936, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/modules/loading.py", line 350, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/modules/module.py", line 294, in init_module_models
    obj.init(cr)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/addons/hr_timesheet_sheet/hr_timesheet_sheet.py", line 627, in init
    )) AS bar""")
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_magneto_80/buildout/parts/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: cannot drop columns from view
```

**Comment by mart-e** [comment]
This bug will only happend when you update the module after a change of view structure but I agree on the fix.
Merged at 17a130428516d9dd8105f90e8c9a65a0b4e8901b, thanks
