### ISSUE TITLE
[14.0][BUG] Crash on l10n_de_reports

### ISSUE THREAD

**Issue by lorenzoallegrucci** [odoo/odoo#127605]
Impacted versions: 14.0

Steps to reproduce:
Update module `l10n_de_reports` with latest commit https://github.com/odoo/enterprise/commit/5b5c126572edb151f5eb8eac17741de3afa44d9d

Current behavior:
```
2023-07-06 12:27:57,509 1 INFO xxxxxxx odoo.modules.loading: loading l10n_de_reports/data/balance_sheet.xml 
2023-07-06 12:27:57,657 1 ERROR xxxxxxx odoo.tools.convert.init: Could not eval([('account_id.tag_ids', 'in', [ref('l10n_de.tag_de_liabilities_bs_D')])]) for domain in {} 
2023-07-06 12:27:57,660 1 WARNING xxxxxxx odoo.modules.loading: Transient module states were reset 
2023-07-06 12:27:57,662 1 ERROR xxxxxxx odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fec3aed6940>, 'l10n_de.tag_de_liabilities_bs_D')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 331, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1945, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1938, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_de.tag_de_liabilities_bs_D
```

Expected behavior:
no error

Please fix urgently this issue because it's impacting on production environments.

**Comment by niyasraphy** [comment]
hi @lorenzoallegrucci ,
can you confirm that the you have pulled the latest of community:  https://github.com/odoo/odoo/commit/8b4c4a2cbedeb9831810ed0440c19821945e98cd and updated the l10n_de module

thanks

**Comment by lorenzoallegrucci** [comment]
Solved by pulling from the latest community, thanks
