### ISSUE TITLE
[9.0] stock_account: wizard stock valuation history divison by zero

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12777]
We are currently working on a migration from v6.1 to v9.0e, we have found that this exact commit https://github.com/odoo/odoo/commit/d951a7d5eecadfa15758a103e2ba1971468b24c1 broke the 'Inventory > Reports > Inventory at date' wizard, and now we get **Division by Zero** error:

```
Traceback (most recent call last):
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, args, *kwargs)
  File "/opt/local/odoo/odoo/community/openerp/service/model.py", line 118, in wrapper
    return f(dbname, args, *kwargs)
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 962, in call
    return self.method(*args, **kw)
  File "/opt/local/odoo/odoo/community/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/local/odoo/odoo/enterprise/web/controllers/main.py", line 912, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/local/odoo/odoo/enterprise/web/controllers/main.py", line 904, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
  File "/opt/local/odoo/odoo/community/openerp/api.py", line 250, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/local/odoo/odoo/community/addons/stock_account/wizard/stock_valuation_history.py", line 46, in read_group
    res = super(stock_history, self).read_group(cr, uid, domain, fields, groupby, offset=offset, limit=limit, context=context, orderby=orderby, lazy=lazy)
  File "/opt/local/odoo/odoo/community/openerp/api.py", line 250, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/local/odoo/odoo/community/openerp/models.py", line 2123, in read_group
    cr.execute(query, where_clause_params)
  File "/opt/local/odoo/odoo/community/openerp/sql_db.py", line 141, in wrapper
    return f(self, args, *kwargs)
  File "/opt/local/odoo/odoo/community/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
DataError: division by zero
```

opw-ticket: 683502

**Comment by aristobulo-eezee** [comment]
@nim-odoo please could you take a look on this issue.

**Comment by aristobulo-eezee** [comment]
This is related to:
https://github.com/odoo/odoo/commit/5e466d3507d81db5fd698d18fe623e5b802bd011

and could have been resolved.
