### ISSUE TITLE
[10.0/master] access denied to web_tour.tour - user can't login

### ISSUE THREAD

**Issue by atrueba** [odoo/odoo#12815]
Impacted versions:

10.0/master - .deb package 20160715

Steps to reproduce:

- Create a new database
- Create a new user with default access rights and set its password
- Logout as admin
- Login as the new user

Current behavior:

Server responds with an "Internal server error" and the user can't login. As the session is created and stored neither refreshing the page or closing the browser redirects to a new login, so the only way to relogin as admin would be to ssh to the server and remove the session file.

The last line of the following server log shows a message that looks as if it should be shown to the user, but it's not.

```
2016-07-16 09:00:52,050 6392 INFO test-ACL werkzeug: 192.168.101.2 - - [16/Jul/2016 09:00:52] "POST /web/login HTTP/1.1" 200 -
2016-07-16 09:00:53,750 6392 INFO test-ACL openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: web_tour.tour
2016-07-16 09:00:53,801 6392 INFO test-ACL werkzeug: 192.168.101.2 - - [16/Jul/2016 09:00:53] "GET /web HTTP/1.1" 500 -
2016-07-16 09:00:53,913 6392 ERROR test-ACL werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1494, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1468, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1659, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(IrHttp, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 189, in _dispatch
    return self._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 160, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 786, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 185, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 845, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 450, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/models/ir_http.py", line 14, in webclient_rendering_context
    'session_info': json.dumps(self.session_info()),
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web_tour/models/ir_http.py", line 10, in session_info
    result['web_tours'] = request.env['web_tour.tour'].get_consumed_tours()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web_tour/models/tour.py", line 25, in get_consumed_tours
    return [t.name for t in self.search([('user_id', '=', self.env.uid)])]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 1660, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4762, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3631, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "<string>", line 2, in check
    
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 782, in check
    raise AccessError(msg % msg_params)
AccessError: (u'Sorry, you are not allowed to access this document. Por favor, contacte con su administrador de sistemas si sospecha que esto es un error.\n\n(Document model: web_tour.tour)', None)
```

Expected behavior:

Server should respond with the normal home screen or whatever that web_tour.tour is.

alternative behaviour should be to show the AccessError message to the user and provide a way to cancel the session and get back to the login page.

**Comment by mart-e** [comment]
Hello,

Thank you for the report but the master branch is *not* the 10.0, it is still a development and highly unstable version. Things get broken and are not working properly but don't worry, a lot will still happen before releasing v10.
We are aware of this particular bug and are working on it.
Regards

**Comment by shingonoide** [comment]
@mart-e Hello,

I'm using version 10 and this or similar problem continues to happen.
Shall we reopen this issue and solve this problem?

If I can get any new information about this problem I'll add it here.

**Comment by mart-e** [comment]
@shingonoide this issue is very old and a lot has changed since, so yes, please open an issue.
Please, be careful to specify how to reproduce your issue on a standard Odoo
