### ISSUE TITLE
[BUG][16.0] im_livechat: error 404 after start a chat and login

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#128206]
Impacted versions: 16.0

Steps to reproduce:
- In public session on website, start a chat
- Login
- If you try to continue to chat an 404 error appear

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/im_livechat/controllers/main.py", line 199, in notify_typing
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The above server error caused the following client error:
null
```

Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/16716992/2784676a-e030-4fd7-b3fe-72c7261b2d7a

Support ticket number submitted via odoo.com/help (optional):

**Comment by fmdl** [comment]
OPW #3421386

**Comment by tde-banana-odoo** [comment]
@seb-odoo

**Comment by tsm-odoo** [comment]
Fixed by https://github.com/odoo/odoo/pull/128301
