### ISSUE TITLE
Module Install/Uninstall Issue

### ISSUE THREAD

**Issue by SeanHardyOdoo** [odoo/odoo#12822]
Impacted versions: 9.0

Steps to reproduce:
try to install or uninstall a module
Current behavior:
Seee below
Expected behavior:
To be able to install modules
Video/Screenshot link (optional):

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 911, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/wizard/base_module_upgrade.py", line 87, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 702, in _tag_record
    f_val = _eval_xml(self,field, self.pool, cr, self.uid, self.idref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 121, in _eval_xml
    return unsafe_eval(a_eval, idref2)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 53, in <lambda>
    return lambda x: self.id_get(cr, x)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 782, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 793, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 962, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 952, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base.user_demo" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/test_new_api/demo_data.xml:11, near
<record id="discussion_0" model="test_new_api.discussion">
            <field name="name">Stuff</field>
            <field name="participants" eval="[(4, ref('base.user_root')), (4, ref('base.user_demo'))]"/>
        </record>
```

**Comment by dreispt** [comment]
Try upgrading the `base` module.

**Comment by mart-e** [comment]
My guess is that you have created a database without demo data and are using the command line to install the module without the `--without-demo` option.
Is that correct?

**Comment by SeanHardyOdoo** [comment]
Not using the command line to install the module

 

Installed it normally

**Comment by SeanHardyOdoo** [comment]
I upgraded the base module, that helped a little

**Comment by mart-e** [comment]
Closing as you seem to have found a solution but if there is really a bug, please give exact details as it is more complex than "install any module".
We need to be able to reproduce it on a standard Odoo instance, you can also check [on runbot](http://runbot.odoo.com/runbot) for a standard instance.

**Comment by fanha99** [comment]
I got the same problem on my v8 database.
I tried upgrade the base with still not work.
I'm trying to install the Employee Directory (hr) module

ParseError: "External ID not found in the system: base.user_demo" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/hr/hr_demo.xml:224, near
<record id="employee_qdp" model="hr.employee">
          <field name="name">Gilles Gravie</field>
          <field name="user_id" ref="base.user_demo"/>
          <field name="department_id" ref="dep_rd"/>
          <field name="parent_id" ref="employee_al"/>
          <field name="job_id" ref="hr.job_developer"/>
          <field name="category_ids" eval="[(6, 0, [ref('employee_category_4')])]"/>
          <field name="work_location">Grand-Rosi&#232;re</field>
          <field name="work_phone">+3281813700</field>
          <field name="work_email">gilles@openerp.com</field>
          <field name="image" type="base64" file="hr/static/img/employee_qdp-image.png"/>
      </record>
