### ISSUE TITLE
not able to save any settings

### ISSUE THREAD

**Issue by Kamalzahid** [odoo/odoo#128394]
Impacted versions:16Enterprise

Steps to reproduce:I think its soft memory limit and hard memory limit increase in odoo.sh

Current behavior:not able to save any settings getting time out error cashe error after loading for 1 minute 20s I created backup and restored in  local server after back i increased soft limit and hard limit  and time system allow m to save changes but what should i do in  odoo.sh

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
@Yenthe666 @odony

**Comment by Yenthe666** [comment]
Actually you should make a ticket on odoo.com/help as you're on odoo.sh :) Normally the soft/hard limit shouldn't go off though. Are you sure it is nothing else? Either way, open a ticket at Odoo

**Comment by Kamalzahid** [comment]
i opened ticket in odoo 7 days now but they are not able to identify the issue  error
2023-07-14 09:46:43,256 8693 ERROR italian_mall_16_3 odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 984, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 353442

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 991, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.move(353442,).company_currency_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 984, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 353442

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 991, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.move(353442,).company_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aps/odoo/odoo16/odoo16/odoo/http.py", line 1998, in __call__
    response = request._serve_db()
  File "/home/aps/odoo/odoo16/odoo16/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/aps/odoo/odoo16/odoo16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/aps/odoo/odoo16/odoo16/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/aps/odoo/odoo16/odoo16/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/aps/odoo/odoo16/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/aps/odoo/odoo16/odoo16/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/aps/odoo/odoo16/odoo16/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/aps/odoo/odoo16/odoo16/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 459, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 439, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-283>", line 2, in create
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/home/aps/odoo/odoo16/odoo16/addons/point_of_sale/models/res_config_settings.py", line 146, in create
    result = super().create(vals_list)
  File "<decorator-gen-246>", line 2, in create
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/aps/odoo/odoo16/enterprise/account_accountant/models/res_config_settings.py", line 55, in create
    return super().create(vals_list)
  File "<decorator-gen-97>", line 2, in create
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/aps/odoo/odoo16/odoo16/odoo/addons/base/models/res_config.py", line 757, in create
    return super().create(vals_list)
  File "<decorator-gen-63>", line 2, in create
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/aps/odoo/odoo16/odoo16/odoo/addons/base/models/ir_fields.py", line 669, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 3982, in create
    next(iter(fields)).determine_inverse(batch_recs)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1396, in determine_inverse
    determine(self.inverse, records)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/home/aps/odoo/odoo16/odoo16/addons/account/models/res_config_settings.py", line 198, in _inverse_account_default_credit_limit
    self.env['ir.property']._set_default(
  File "/home/aps/odoo/odoo16/odoo16/odoo/addons/base/models/ir_property.py", line 196, in _set_default
    prop.write({'value': value})
  File "/home/aps/odoo/odoo16/odoo16/odoo/addons/base/models/ir_property.py", line 126, in write
    self.env.flush_all()
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 732, in flush_all
    self._recompute_all()
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 728, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 6175, in _recompute_field
    field.recompute(records)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1338, in apply_except_missing
    func(records)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 4208, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 100, in determine
    return needle(records, *args)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 701, in _compute_related
    record[[self.name](http://self.name/)] = self._process_related(value[[self.related_field.name](http://self.related_field.name/)])
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 5873, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 2799, in __get__
    return super().__get__(records, owner)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/home/aps/odoo/odoo16/odoo16/addons/mail/models/mail_thread.py", line 403, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 4208, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 100, in determine
    return needle(records, *args)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 689, in _compute_related
    values = [first(value[name]) for value in values]
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 689, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 5873, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 2799, in __get__
    return super().__get__(records, owner)
  File "/home/aps/odoo/odoo16/odoo16/odoo/fields.py", line 1186, in __get__
    recs._fetch_field(self)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 3177, in _fetch_field
    self._read(fnames)
  File "/home/aps/odoo/odoo16/odoo16/odoo/models.py", line 3283, in _read
    self.env.cache.insert_missing(fetched, field, values)
  File "/home/aps/odoo/odoo16/odoo16/odoo/api.py", line 1094, in insert_missing
    field_cache.setdefault(id_, val)
MemoryError

**Comment by Kamalzahid** [comment]
@Yenthe666 can you please sgare your email i have paid task for you

**Comment by Yenthe666** [comment]
Thanks but we have a customer stop currently as we're fully booked for the next months :)
