### ISSUE TITLE
Merge contacts bug with AbstractModel and Reference field

### ISSUE THREAD

**Issue by siddharth-kanojiya** [odoo/odoo#128761]
Impacted versions: 16.0

Steps to reproduce: Create Abstract model with Reference field in it.

![image](https://github.com/odoo/odoo/assets/12948934/6ed976ed-b2ad-4fd1-8402-8b9c207fd2d5)

After that go to contacts list view, select any two contacts. Try to merge. It will raise error.

**Error**
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/sid/workspace/16/odoo16/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/sid/workspace/16/odoo16/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/sid/workspace/16/odoo16/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/sid/workspace/16/odoo16/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/sid/workspace/16/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/sid/workspace/16/odoo16/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/sid/workspace/16/odoo16/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/sid/workspace/16/odoo16/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/sid/workspace/16/odoo16/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/sid/workspace/16/odoo16/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sid/workspace/16/odoo16/odoo/addons/base/wizard/base_partner_merge.py", line 653, in action_merge
    self._merge(self.partner_ids.ids, self.dst_partner_id)
  File "/home/sid/workspace/16/odoo16/odoo/addons/base/wizard/base_partner_merge.py", line 338, in _merge
    self._update_reference_fields(src_partners, dst_partner)
  File "/home/sid/workspace/16/odoo16/odoo/addons/base/wizard/base_partner_merge.py", line 224, in _update_reference_fields
    records_ref = Model.sudo().search([(record.name, '=', 'res.partner,%d' % partner.id)])
  File "/home/sid/workspace/16/odoo16/odoo/models.py", line 1508, in search
    res = self._search(domain, offset=offset, limit=limit, order=order, count=count)
  File "/home/sid/workspace/16/odoo16/odoo/models.py", line 4657, in _search
    query.order = self._generate_order_by(order, query).replace('ORDER BY ', '')
  File "/home/sid/workspace/16/odoo16/odoo/models.py", line 4532, in _generate_order_by
    order_by_elements = self._generate_order_by_inner(self._table, order_spec, query)
  File "/home/sid/workspace/16/odoo16/odoo/models.py", line 4498, in _generate_order_by_inner
    raise ValueError("Invalid field %r on model %r" % (order_field, self._name))
ValueError: Invalid field 'id' on model 'test.abstract.model'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/211-beb3100/web.assets_backend.min.js:970:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/211-beb3100/web.assets_backend.min.js:978:13)

Current behavior:
Currently raise error when try to merge contacts

Expected behavior:
It should not raise any error and it should work with abstract model with Reference field 
(Maybe we can filter Reference fields of abstract modules)

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/12948934/280cc1d8-8210-47c2-9824-5d2f432dc7d5)

![image](https://github.com/odoo/odoo/assets/12948934/5a4152ee-ab8f-40f2-9df1-e24c91356c11)

![image](https://github.com/odoo/odoo/assets/12948934/2e8cd6c1-0bbe-46d3-9792-e7b263cab900)

Support ticket number submitted via odoo.com/help (optional):

Sorry if any information is not posted properly. As its first time I posted any bug :smile:

**Comment by siddharth-kanojiya** [comment]
> I guess you've missed one step in your description: `res.partner` will inherit the actract model?

Its not necessary that res.partner will inherit that abstract model.

Because currently it's directly searching for all "Reference" fields from ir.model.fields

And from all that fields model, it's try to search for Reference value with res.partner model.

![image](https://github.com/odoo/odoo/assets/12948934/65c35275-1fac-4da1-a854-db8677b8c9b1)

So when search method called and try to group by with id field. And it's giving error.
