### ISSUE TITLE
Error while installing requirements.txt 

### ISSUE THREAD

**Issue by jdmloki** [odoo/odoo#12888]
Tried the easysetup file still running into this issue. 
```
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run

    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_
files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 587, in _prepare
_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 653, in unpack_http
_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 605, in unpac
k_file
    untar_file(filename, location)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 581, in untar
_file
    tar.utime(member, path)
  File "c:\python27\lib\tarfile.py", line 2332, in utime
    raise ExtractError("could not change modification time")
ExtractError: could not change modification time
```

**Comment by antonylesuisse** [comment]
Probably a permission issue on you side. Does the pip install command works ?

**Comment by mart-e** [comment]
Hello,

It looks like a problem on your machine, probably an access rights error as the errors happens when an external library (not odoo) tries to modify a file.
Could you give more details on how you install? Which version? Which Windows?

**Comment by jdmloki** [comment]
I switched to Windows 10 from 8.1 and it worked fine.

**Comment by mart-e** [comment]
Thanks for the update, closing as the problem seems in the deployment, not in Odoo.
