### ISSUE TITLE
PosBoxless setup - AttributeError: 'NoneType' object has no attribute 'bmAttributes'

### ISSUE THREAD

**Issue by gwasky** [odoo/odoo#12890]
**Impacted versions:**
Odoo 8/ ubuntu 16 -- posboxless setup with hw_proxy,hw_scanner,hw_escpos
Thermal Printer - HU HAI SUNCSW Receipt Printer Co.,Ltd. Gprinter USB Printer

**Steps to reproduce:**
ranning a posboxless setup, 
load the w_proxy,hw_scanner,hw_escpos modules
http://localhost:8069/hw_proxy/status page shows 
Both devices(scanner and printer) seem to connect, except for the printer, which connects and disconnects
escpos : connected
Connected to ZHU HAI SUNCSW Receipt Printer Co.,Ltd. Gprinter USB Printer
scanner : connected
Connected to ['Honeywell Honeywell Scanning and Mobility Scanner', 'OKE Electron Com

**Current behavior:**
Printer keeps connecting/coming online and going offline, 
Printer doesnt print anything on validation of  sale on the POS
Logs are below:
```
2016-07-24 12:55:44,211 890 INFO ? openerp.addons.hw_escpos.controllers.main: connected : Connected to ZHU        HAI SUNCSW Receipt Printer Co.,Ltd. Gprinter USB Printer
 2016-07-24 12:55:44,344 890 INFO ? openerp.addons.hw_escpos.controllers.main: connected : Connected to ZHU HAI SUNCSW Receipt Printer Co.,Ltd. Gprinter USB Printer
2016-07-24 12:55:44,442 890 INFO ? openerp.addons.hw_escpos.controllers.main: error : 'NoneType' object has no attribute 'bmAttributes'
2016-07-24 12:55:44,443 890 ERROR ? openerp.addons.hw_escpos.controllers.main: ESC/POS Error: 'NoneType' object has no attribute 'bmAttributes'
2016-07-24 12:55:44,443 890 ERROR ? openerp.addons.hw_escpos.controllers.main: 'NoneType' object has no attribute 'bmAttributes'
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/addons/hw_escpos/controllers/main.py", line 167, in run
self.print_status(printer)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hw_escpos/controllers/main.py", line 201, in print_status
eprint.text('\n\n')
File "/usr/lib/python2.7/dist-packages/openerp/addons/hw_escpos/escpos/escpos.py", line 826, in text
self._raw(txt)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hw_escpos/escpos/printer.py", line 68, in _raw
if len(msg) != self.device.write(self.out_ep, msg, self.interface):
File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 625, in write
fn = fn_map[self._ctx.get_endpoint_type(self, endpoint, intf)]
File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 180, in get_endpoint_type
etype = util.endpoint_type(e.bmAttributes)
```
**Expected behavior:**
Print a receipt after entering amount paid by customer, and open the cashdrawer

Video/Screenshot link (optional):
Posted this on stackoverflow
http://stackoverflow.com/questions/38552581/posboxless-setup-attributeerror-nonetype-object-has-no-attribute-bmattribu

Note : lsusb command, doesnt return neither the scanner nor the thermal printer

Desparately need assistance on this.

**Comment by antonylesuisse** [comment]
I dont think this printer is supported.

**Comment by mart-e** [comment]
You follow the [PosBoxless guide](https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html#posboxless-guide-advanced), right?
Indeed, it looks like the `PyUSB` library does not succeed to access the device, probably using a different endpoint.
We [support](https://www.odoo.com/page/point-of-sale-hardware#part_6) the popular EPSON printers so sorry but we can't help you. The Chinese printers tends to imitate popular printers (like EPSON TM-T20) but often with some incompatibilities...

You may want to check #12485 as somebody else succeeded to work with a printer working on a different endpoint.

**Comment by odony** [comment]
@gwasky I've encountered the same error with a "STMicroelectronics POS58 Printer USB" thermal printer recently. The POSBox is hardcoded to use interface `0x82` for esc/pos INPUT and `0x01` for OUTPUT, and it turns out that this printer was using USB interface `0x03` for OUTPUT instead.
We ought to make this configurable or auto-detect it, but in the meantime you can find out what endpoints are exposed by your printer using the `lsusb -v` command, and change the [hardcoded interfaces](https://github.com/odoo/odoo/blob/4809b572835a94543cd1f37e621a98fabec053fd/addons/hw_escpos/escpos/printer.py#L16) accordingly.
What you're looking for in the result of `lsusb -v` is something like `bEndpointAddress     0x82  EP 1 IN`  and  `bEndpointAddress     0x01  EP 2 OUT` in the section related to your printer, where the `0x??` value are the interface addresses for the corresponding endpoints (INput/OUTput).

**Comment by odony** [comment]
@gwasky if your issue was simply the detection of the right IN/OUT endpoint address for your printer (as in the case of "STMicroelectronics POS58 Printer"), you can download [version 15 of the POSBox image](https://download.odoocdn.com/master/posbox) and the problem should now be fixed.
If it's not solved yet, the output of `lsusb -v` will now be displayed in the hardware status page, and the printer status will indicate the auto-detected IN/OUT endpoints, so you can more easily identify issues.
