### ISSUE TITLE
accounting

### ISSUE THREAD

**Issue by wassmtg** [odoo/odoo#129172]
Impacted versions:16

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Filesodoo16\server\odoo\http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Filesodoo16\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Program Filesodoo16\server\odoo\http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Filesodoo16\server\odoo\http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Filesodoo16\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\Program Filesodoo16\server\odoo\http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Program Filesodoo16\server\odoo\addons\web\controllers\dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Filesodoo16\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Filesodoo16\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Filesodoo16\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Filesodoo16\server\odoo\addons\account\models\account_move.py", line 2398, in onchange
    return super().onchange(values, field_name, field_onchange)
  File "C:\Program Filesodoo16\server\odoo\models.py", line 6507, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Program Filesodoo16\server\odoo\models.py", line 6218, in _onchange_eval
    method_res = method(self)
  File "C:\Program Filesodoo16\server\odoo\addons\account\models\account_move.py", line 1617, in _onchange_name_warning
    if self.name and self.name != '/' and self.name <= (self.highest_name or '') and not self.quick_edit_mode:
  File "C:\Program Filesodoo16\server\odoo\fields.py", line 1157, in __get__
    self.recompute(record)
  File "C:\Program Filesodoo16\server\odoo\fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "C:\Program Filesodoo16\server\odoo\fields.py", line 1338, in apply_except_missing
    func(records)
  File "C:\Program Filesodoo16\server\odoo\fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "C:\Program Filesodoo16\server\odoo\addons\mail\models\mail_thread.py", line 403, in _compute_field_value
    return super()._compute_field_value(field)
  File "C:\Program Filesodoo16\server\odoo\models.py", line 4208, in _compute_field_value
    fields.determine(field.compute, self)
  File "C:\Program Filesodoo16\server\odoo\fields.py", line 97, in determine
    return needle(*args)
  File "C:\Program Filesodoo16\server\odoo\addons\account\models\account_move.py", line 690, in _compute_name
    if move_has_name and move.posted_before or not move_has_name and move._get_last_sequence(lock=False):
  File "C:\Program Filesodoo16\server\odoo\addons\account_sequence\models\sequence_mixin.py", line 11, in _get_last_sequence
    return super()._get_last_sequence(relaxed, with_prefix, False)
  File "C:\Program Filesodoo16\server\odoo\addons\account\models\sequence_mixin.py", line 207, in _get_last_sequence
    self.env.cr.execute(query, param)
  File "C:\Program Filesodoo16\server\odoo\sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidRegularExpression: invalid regular expression: quantifier operand invalid

The above server error caused the following client error:
null

where is the problem?

**Comment by niyasraphy** [comment]
hi @wassmtg ,
can you see if it is reproducible in odoo runbot and if yes, please provide steps to reproduce the same.
thanks

**Comment by islamSera** [comment]
The error message "RPC_ERROR Odoo Server Error" is caused by an invalid regular expression with an invalid quantifier operand. The error occurred in the file "sequence_mixin.py" in the "account_sequence" module. The error message suggests that the problem should be reported to the author or maintainer of the Python interpreter
