### ISSUE TITLE
Payment Engine 

### ISSUE THREAD

**Issue by elpreto** [odoo/odoo#129305]
**Impacted versions:** Odoo 16.0 (Versión Community)

**Steps to reproduce:** Go to Applications, select Uninstall in Payment Engine

**Current behavior:** Fails to Uninstall with error 
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://odoo-137101-0.cloudclusters.net/web/assets/115-03dc707/web.assets_backend.min.js:969:163)
    at XMLHttpRequest.<anonymous> (https://odoo-137101-0.cloudclusters.net/web/assets/115-03dc707/web.assets_backend.min.js:977:13)

**Expected behavior:** Uninstall and remove the app and it's dependencies

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**### Complete error the application shows**

RPC_ERROR
Odoo Server Error

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/cloudclusters/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/cloudclusters/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/cloudclusters/odoo/odoo/http.py", line 1808, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/cloudclusters/odoo/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/wizard/base_module_uninstall.py", line 59, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-77>", line 2, in button_immediate_uninstall
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 640, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/cloudclusters/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 567, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "<decorator-gen-76>", line 2, in module_uninstall
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 507, in module_uninstall
    self.with_context(prefetch_fields=False).write({'state': 'uninstalled', 'latest_version': False})
  File "/cloudclusters/odoo/odoo/models.py", line 3752, in write
    self.modified(vals)
  File "/cloudclusters/odoo/odoo/models.py", line 6029, in modified
    for field, records, create in tocompute:
  File "/cloudclusters/odoo/odoo/models.py", line 6096, in _modified_triggers
    records = model.search([(field.name, 'in', real_records.ids)], order='id')
  File "/cloudclusters/odoo/odoo/models.py", line 1509, in search
    return res if count else self.browse(res)
  File "/cloudclusters/odoo/odoo/models.py", line 5085, in browse
    if not ids:
  File "/cloudclusters/odoo/odoo/tools/query.py", line 217, in __bool__
    return bool(self._result)
  File "/cloudclusters/odoo/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/cloudclusters/odoo/odoo/tools/query.py", line 210, in _result
    self._cr.execute(query_str, params)
  File "/cloudclusters/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "payment_provider" does not exist
LINE 1: SELECT "payment_provider".id FROM "payment_provider" WHERE (...
                                          ^

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://odoo-137101-0.cloudclusters.net/web/assets/115-03dc707/web.assets_backend.min.js:969:163)
    at XMLHttpRequest.<anonymous> (https://odoo-137101-0.cloudclusters.net/web/assets/115-03dc707/web.assets_backend.min.js:977:13)

**Comment by niyasraphy** [comment]
hi @elpreto ,
i tried the same locally and in runbot and it seems without any issues the module is getting uninstalled.

![Screenshot from 2023-07-24 10-31-14](https://github.com/odoo/odoo/assets/27989791/6abc4300-54bc-429b-bdb3-6aee0e11e6e8)

thanks

**Comment by elpreto** [comment]
Ok, I tried in a clean instance in CloudClusters.

Just in case, I deleted the instance, started a fresh one and tried again and still fails.
Not sure what could make the difference.

**Comment by AntoineVDV** [comment]
Hello @elpreto, I was able to uninstall the `payment` module without any issue, too, on [a community runbot](https://48914239-16-0-all.runbot150.odoo.com/web#action=36&model=ir.module.module&view_type=kanban&cids=1&menu_id=5).

It is likely that the problem comes from the platform on which you're conducting your test. If you manage to reproduce the problem on Odoo's runbot, I'll be glad to investigate, but I cannot help here, sorry.
