### ISSUE TITLE
[XmlRpc] fields_get "payment.link.wizard" {'attributes': ['selection']}

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#129490]
# Impacted versions: **16 only** (tested from 13 to 15 and it's ok)

# Steps to reproduce:

Use Odoo Docker official image and run it with this options :

```shell
docker run -p 8069:8069 --env HOST=host.docker.internal --name odoo_16 --pull missing -t odoo:16 -- --database odoo-master-v16 --init "l10n_fr,account_accountant,sale_management"
```

# Current behavior:

Trying to introspect data using the XML-RPC api for each models available in the database, an error occurs while requesting info about the `payment.link.wizard`

Here is an example of the python code to reproduce the error :

```python
models.execute_kw(db, uid, password, 'payment.link.wizard', 'fields_get', [], {'attributes': ['string', 'help', 'type', 'selection']})
```

I want to get info about the `selection` of any fields for this model. If I don't request it no error occurs.

Here is the error :

```log
Traceback (most recent call last):                                                                                                             
    File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 148, in xmlrpc_2                                             
      response = self._xmlrpc(service)                                                                                                           
    File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 128, in _xmlrpc                                              
      result = dispatch_rpc(service, method, params)                                                                                             
    File "/usr/lib/python3/dist-packages/odoo/http.py", line 366, in dispatch_rpc                                                                
      return dispatch(method, params)                                                                                                            
    File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 37, in dispatch                                                            
      res = execute_kw(db, uid, *params[3:])                                                                                                     
    File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 59, in execute_kw                                                          
      return execute(db, uid, obj, method, *args, **kw or {})                                                                                    
    File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 65, in execute                                                             
      res = execute_cr(cr, uid, obj, method, *args, **kw)                                                                                        
    File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 50, in execute_cr                                                          
      result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)                                                                  
    File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying                                                           
      result = func()                                                                                                                            
    File "/usr/lib/python3/dist-packages/odoo/api.py", line 457, in call_kw                                                                      
      result = _call_kw_model(method, model, args, kwargs)                                                                                       
    File "/usr/lib/python3/dist-packages/odoo/api.py", line 430, in _call_kw_model                                                               
      result = method(recs, *args, **kwargs)                                                                                                     
    File "/usr/lib/python3/dist-packages/odoo/models.py", line 2850, in fields_get                                                               
      description = field.get_description(self.env, attributes=attributes)                                                                       
    File "/usr/lib/python3/dist-packages/odoo/fields.py", line 846, in get_description                                                           
      value = value(env)                                                                                                                         
    File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2697, in _description_selection                                                   
      return determine(selection, env[self.model_name])                                                                                          
    File "/usr/lib/python3/dist-packages/odoo/fields.py", line 97, in determine                                                                  
      return needle(*args)                                                                                                                       
    File "/usr/lib/python3/dist-packages/odoo/addons/payment/wizards/payment_link_wizard.py", line 90, in _selection_payment_provider_selection  
      res_model, res_id = defaults['res_model'], defaults['res_id']                                                                              
  KeyError: 'res_model'
```

The issue seems to be coming from here : https://github.com/odoo/odoo/blob/16.0/addons/payment/wizards/payment_link_wizard.py#L90

# Expected behavior:

Be able to request info about this model that fail getting a `selection` on the field `payment_provider_selection`.

**Comment by Prometee** [comment]
Update : Same error happen with the JSON RPC API.

**Comment by niyasraphy** [comment]
fixed in: https://github.com/odoo/odoo/commit/290210d1da38b7ee19f441117aa1448a43bcc8f5
