### ISSUE TITLE
[16.0][hr] `write` method on `hr.employee` can cause singleton ValueError

### ISSUE THREAD

**Issue by carmenbianca** [odoo/odoo#129620]
Impacted versions: 16.0

Steps to reproduce:

1. Create a database with `hr` installed.
2. Run the following Python code:

```python
# Any value for user_id will trigger the bug
env["hr.employee"].search([]).write({"user_id": False})
```

Current behavior:

```python
Traceback (most recent call last):
  File "/home/carmenbianca/cie/odoo16/src/odoo/odoo/models.py", line 5137, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/carmenbianca/cie/odoo16/src/odoo/addons/hr/models/hr_employee.py", line 369, in write
    (bool(self.image_1920))))
  File "/home/carmenbianca/cie/odoo16/src/odoo/odoo/fields.py", line 1153, in __get__
    record.ensure_one()
  File "/home/carmenbianca/cie/odoo16/src/odoo/odoo/models.py", line 5140, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: hr.employee(20, 3, 9, 17, 15, 19, 18, 11, 6, 8, 7, 1, 14, 16, 5, 2, 4, 12, 10, 13)
```

Expected behavior:

No singleton error.

Video/Screenshot link (optional):

None

Support ticket number submitted via odoo.com/help (optional):

None

---

The relevant code in `addons/hr/models/hr_employee.py` is as follows:

```python
    def write(self, vals):
        if 'address_home_id' in vals:
            account_id = vals.get('bank_account_id') or self.bank_account_id.id
            if account_id:
                self.env['res.partner.bank'].browse(account_id).partner_id = vals['address_home_id']
            self.message_unsubscribe(self.address_home_id.ids)
            if vals['address_home_id']:
                self._message_subscribe([vals['address_home_id']])
        if 'user_id' in vals:
            # Update the profile pictures with user, except if provided 
            vals.update(self._sync_user(self.env['res.users'].browse(vals['user_id']),
                                        (bool(self.image_1920))))
        [...]
```

The bug is on the last line. `self.image_1920` does not work when `self` is a recordset containing multiple records. The method either needs to be rewritten to loop over all elements in `self`, or the method call to `_sync_user` needs to be adjusted to not get `image_1920`.

**Comment by pedrobaeza** [comment]
`self.bank_account_id.id` seems also problematic.

**Comment by niyasraphy** [comment]
fixed in: https://github.com/odoo/odoo/commit/9a21bdf37e1ae3bec33a572f3bf2374b6fa0e183
