### ISSUE TITLE
[9.0] ERROR TEST openerp.http: Exception during JSON request handling.

### ISSUE THREAD

**Issue by rohailnasir** [odoo/odoo#13014]
Odoo 9 is having trouble loading menu bar for my in-use database. While parsing it raises the below exception. 
![odoo error](https://cloud.githubusercontent.com/assets/7452386/17391393/c511a4bc-5a26-11e6-8419-15b387026f23.png)

_2016-08-04 11:18:43,190 16140 INFO ? openerp.service.server: HTTP service (werkzeug) running on localhost:8069
2016-08-04 11:18:47,832 16140 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-08-04 11:18:48,055 16140 INFO TEST openerp.modules.loading: loading 1 modules...
2016-08-04 11:18:48,085 16140 INFO TEST openerp.modules.loading: 1 modules loaded in 0.02s, 0 queries
2016-08-04 11:18:55,448 16140 INFO TEST openerp.modules.loading: loading 53 modules...
2016-08-04 11:18:57,546 16140 INFO TEST openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2016-08-04 11:19:06,150 16140 INFO TEST openerp.modules.loading: 53 modules loaded in 10.70s, 0 queries
2016-08-04 11:19:18,144 16140 INFO ? openerp.http: HTTP Configuring static files
2016-08-04 11:19:18,890 16140 INFO TEST openerp.modules.loading: Modules loaded.
2016-08-04 11:19:18,892 16140 INFO TEST openerp.addons.base.ir.ir_http: Generating routing map
2016-08-04 11:19:18,892 16140 INFO TEST openerp.addons.base.ir.ir_http: Generating routing map
2016-08-04 11:19:22,881 16140 INFO TEST openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: None, model: bus.presence
2016-08-04 11:19:22,891 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:22] "POST /longpolling/poll HTTP/1.1" 200 -
2016-08-04 11:19:25,062 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web? HTTP/1.1" 200 -
2016-08-04 11:19:25,471 16140 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/static/src/css/full.css HTTP/1.1" 304 -
2016-08-04 11:19:25,782 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/content/402-490ce44/web.assets_common.0.css HTTP/1.1" 304 -
2016-08-04 11:19:25,798 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/content/766-eec7c6f/web.assets_backend.0.css HTTP/1.1" 200 -
2016-08-04 11:19:25,832 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/content/767-eec7c6f/web.assets_backend.1.css HTTP/1.1" 200 -
2016-08-04 11:19:25,858 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/content/403-490ce44/web.assets_common.js HTTP/1.1" 200 -
2016-08-04 11:19:25,980 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:25] "GET /web/content/768-eec7c6f/web.assets_backend.js HTTP/1.1" 200 -
2016-08-04 11:19:26,703 16140 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:26] "GET /web_editor/static/src/xml/editor.xml HTTP/1.1" 200 -
2016-08-04 11:19:26,815 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:26] "POST /web/dataset/call HTTP/1.1" 200 -
2016-08-04 11:19:26,835 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:26] "GET /web/binary/company_logo HTTP/1.1" 304 -
2016-08-04 11:19:27,058 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:27] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
2016-08-04 11:19:27,147 16140 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:27] "GET /web_editor/static/src/xml/snippets.xml HTTP/1.1" 200 -
2016-08-04 11:19:27,168 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:27] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
2016-08-04 11:19:27,548 16140 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:27] "GET /web_editor/static/src/xml/translator.xml HTTP/1.1" 200 -
2016-08-04 11:19:27,630 16140 INFO ? werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:27] "GET /mail/static/src/audio/ting.ogg HTTP/1.1" 200 -
2016-08-04 11:19:28,127 16140 INFO TEST openerp.service.common: successful login from 'admin' using database 'test'
2016-08-04 11:19:28,562 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:28] "POST /mail/client_action HTTP/1.1" 200 -
2016-08-04 11:19:29,575 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:29] "POST /mail/chat_init HTTP/1.1" 200 -
2016-08-04 11:19:30,263 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:30] "POST /web/webclient/translations HTTP/1.1" 200 -
2016-08-04 11:19:30,783 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:30] "POST /web/session/get_session_info HTTP/1.1" 200 -
2016-08-04 11:19:35,756 16140 INFO TEST openerp.http: Generating nondb routing
2016-08-04 11:19:45,030 16140 ERROR TEST openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\service\model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\addons\web\controllers\main.py", line 616, in load
    return Client(request.httprequest.app, BaseResponse).get(path, base_url=base_url).data
  File "D:\Python27\lib\site-packages\werkzeug-0.9.6-py2.7.egg\werkzeug\test.py", line 762, in get
    return self.open(_args, *_kw)
  File "D:\Python27\lib\site-packages\werkzeug-0.9.6-py2.7.egg\werkzeug\test.py", line 736, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "D:\Python27\lib\site-packages\werkzeug-0.9.6-py2.7.egg\werkzeug\test.py", line 659, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "D:\Python27\lib\site-packages\werkzeug-0.9.6-py2.7.egg\werkzeug\test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 1490, in **call**
    return self.dispatch(environ, start_response)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 1464, in **call**
    return self.app(environ, start_wrapped)
  File "D:\Python27\lib\site-packages\werkzeug-0.9.6-py2.7.egg\werkzeug\wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 1658, in dispatch
    result = _dispatch_nodb()
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 1631, in _dispatch_nodb
    result = request.dispatch()
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 840, in dispatch
    r = self._call_function(*_self.params)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 317, in _call_function
    return self.endpoint(_args, **kwargs)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\addons\web\controllers\main.py", line 530, in qweb
    content, checksum = concat_xml(files)
  File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\addons\web\controllers\main.py", line 205, in concat_xml
    xml = ElementTree.parse(fp).getroot()
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
2016-08-04 11:19:45,036 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:45] "POST /web/proxy/load HTTP/1.1" 200 -
2016-08-04 11:19:45,509 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:45] "POST /web/session/modules HTTP/1.1" 200 -
2016-08-04 11:19:45,617 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:45] "POST /web/dataset/search_read HTTP/1.1" 200 -
2016-08-04 11:19:45,838 16140 INFO TEST werkzeug: 127.0.0.1 - - [04/Aug/2016 11:19:45] "POST /web/webclient/translations HTTP/1.1" 200 -_

**Comment by Yenthe666** [comment]
Hi @rohailnasir,

Could you provide us with the rest of the stacktrace please? This is not the full error / crash and we need the bottom part to know what is wrong or what happend.

**Comment by rohailnasir** [comment]
Hi @Yenthe666, I have updated the stacktrace above, kindly check if thats wt you are expecting?

**Comment by JKE-be** [comment]
You should print 'files' from File "D:\eclipse\Workspace\odoo-9.0c-latest-20160613\openerp\addons\web\controllers\main.py", line 530, in qweb
content, checksum = concat_xml(files) ...
Seems like you have a badly formatted file. (`ParseError: no element found: line 1, column 0
`)
Do you have some customizations ?

**Comment by rohailnasir** [comment]
@JKE-be  nope, no changes at all. It runs perfectly fine on a new database.

**Comment by JKE-be** [comment]
You can always try to delete all your asset attachments to force the generation again... But if it is a static file, it should not fix the problem.
But if you had the filename which fail, it will be easier... Maybe you db is online ?
Did you try in debug mode (which one don't use assets) if you have the error ? (?debug= in url)

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on the questions from @JKE-be.
