### ISSUE TITLE
after odoo 15 to 16 migrate database giving error psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""

### ISSUE THREAD

**Issue by MAYURNAGAR-7069** [odoo/odoo#130152]
Traceback (most recent call last):
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/loading.py", line 208, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/modules/registry.py", line 526, in init_models
    model._auto_init()
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/models.py", line 2574, in _auto_init
    new = field.update_db(self, columns)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/fields.py", line 1006, in update_db
    self.update_db_column(model, column)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/fields.py", line 1042, in update_db_column
    self._convert_db_column(model, column)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/fields.py", line 1046, in _convert_db_column
    sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/tools/sql.py", line 128, in convert_column
    _convert_column(cr, tablename, columnname, columntype, using)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/tools/sql.py", line 147, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/home/mayurnagar/source/odoo/branches/16-odoo/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""

**Comment by vava-odoo** [comment]
Hi @MAYURNAGAR-7069 
Thanks for reporting. This is fixed now.
Cheers
