### ISSUE TITLE
[BUG] [crm] psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "٢٠٢٣-٠٧-٠١"

### ISSUE THREAD

**Issue by wm-cortex** [odoo/odoo#130295]
Impacted versions:
15.0, 16.0

Steps to reproduce:

 - Open runbot
 - Run Odoo 15.0 or 16.0 
 - Activate Arabic / العربية Language and switch to Arabic.
 - Go to CRM -> Reporting -> Forecast 
 
![image](https://github.com/odoo/odoo/assets/91066610/9ca8b45f-e429-46d0-bed5-be75518f6b7b)

The below error shown:
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/web/models/models.py", line 172, in read_progress_bar
    for group in self._read_progress_bar(domain, group_by, progress_bar):
  File "/data/build/odoo/addons/mail/models/mail_activity_mixin.py", line 313, in _read_progress_bar
    self.env.cr.execute(select_query, where_params)
  File "/data/build/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "٢٠٢٣-٠٧-٠١"
LINE 18: ...dline" IS NULL  OR ("crm_lead"."date_deadline" >= '٢٠٢٣-٠٧-٠...
                                                              ^

The above server error caused the following client error:
OwlError: The following error occurred in onWillStart: "Odoo Server Error"
    at wrapError (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:1601:77)
    at onWillStart (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:1607:117)
    at useModel (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1855-016957c/web.assets_backend.min.js:4813:1)
    at KanbanController.setup (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1855-016957c/web.assets_backend.min.js:4250:851)
    at new ComponentNode (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:1559:202)
    at https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:2095:6
    at View.slot1 (eval at compile (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:2056:370), <anonymous>:15:36)
    at callSlot (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:1666:25)
    at WithSearch.template (eval at compile (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:2056:370), <anonymous>:8:12)
    at Fiber._render (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1858-a18257a/web.assets_common.min.js:1497:96)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1855-016957c/web.assets_backend.min.js:985:163)
    at XMLHttpRequest.<anonymous> (https://48671346-16-0-all.runbot145.odoo.com/web/assets/1855-016957c/web.assets_backend.min.js:993:13)

Current behavior:
Forecast report raise an error in Arabic Language

Expected behavior:

Video/Screenshot link (optional):
[Untitled video - Screen Recording - 7_31_2023, 7_55_40 PM.webm](https://github.com/odoo/odoo/assets/91066610/025b2567-16b6-4296-b9e5-082d541b17f7)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @wm-cortex 
Thanks for reporting. It's now fixed.
Cheers

**Comment by mfhm95** [comment]
i still have the same issue how it can be fixed ?
