### ISSUE TITLE
[BUG] [16.0] l10n_de/de_reports/de_skr03/de_skr04: update DE balance sheet

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#130970]
After latest pull this error is coming : 

https://github.com/odoo/odoo/commit/cc4825ba6ccd543a9262fb4fff428ba05f420f53

Module "Base" not possible anymore now. Please kindly address this on highest priority.

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 546, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2368, in _process_end
    self._process_end_unlink_record(record)
  File "/odoo/odoo-server/addons/website/models/ir_model_data.py", line 36, in _process_end_unlink_record
    return super()._process_end_unlink_record(record)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2297, in _process_end_unlink_record
    record.unlink()
  File "/odoo/odoo-server/odoo/models.py", line 3576, in unlink
    cr.execute(query, (sub_ids,))
  File "/odoo/odoo-server/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: update or delete on table "account_account_tag" violates foreign key constraint "account_account_account_tag_account_account_tag_id_fkey" on table "account_account_account_tag"
DETAIL:  Key (id)=(173) is still referenced from table "account_account_account_tag".

**Comment by bhaveshselarka** [comment]
@alialfie  kindly look into this asap, thanks in advance.

**Comment by bhaveshselarka** [comment]
https://github.com/odoo/odoo/pull/130359
