### ISSUE TITLE
mail_message.py", line 43, in decode

### ISSUE THREAD

**Issue by martinauger03** [odoo/odoo#1311]
My email fetch process was blocked...  It was working perfectly but since yesterday I have this msg in my log:

```
2014-07-22 14:10:41,460 991 ERROR MYBD openerp.addons.fetchmail.fetchmail: Failed to fetch mail from pop server myemail@cie.com.
Traceback (most recent call last):
  File "/usr/local/openerp/server/openerp/addons/fetchmail/fetchmail.py", line 230, in fetch_mail
    context=context)
  File "/usr/local/openerp/server/openerp/addons/mail/mail_thread.py", line 643, in message_process
    msg = self.message_parse(cr, uid, msg_txt, save_original=save_original, context=context)
  File "/usr/local/openerp/server/openerp/addons/mail/mail_thread.py", line 876, in message_parse
    msg_dict['body'], msg_dict['attachments'] = self._message_extract_payload(message, save_original=save_original)
  File "/usr/local/openerp/server/openerp/addons/mail/mail_thread.py", line 770, in _message_extract_payload
    attachments.append((decode(filename) or 'attachment', part.get_payload(decode=True)))
  File "/usr/local/openerp/server/openerp/addons/mail/mail_message.py", line 43, in decode
    text = decode_header(text.replace('\r', ''))
  File "/usr/lib/python2.7/email/header.py", line 73, in decode_header
    header = str(header)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 20: ordinal not in range(128)
```

 Can some one can help?

Thx,

Martin Auger

**Comment by Yenthe666** [comment]
Hi @martinauger03,

Thank you for your report.
This bug has been fixed quite a while ago and is no longer present in Odoo V8 and up.
If you can still reproduce it on V8, V9 or V10 then please don't hesitate to create a new bug report!

Regards,
Yenthe
