### ISSUE TITLE
Failed installing odoo8.0 on mac OS X 10.11

### ISSUE THREAD

**Issue by chary1n** [odoo/odoo#13125]
Impacted versions:
OSX 10.11
Postgresql 9.3
Odoo 8.0

Steps to reproduce:
Everything goes well until 
`python ./odoo.py`
Current behavior:
shows
`Traceback (most recent call last):
  File "./odoo.py", line 160, in <module>
    main()
  File "./odoo.py", line 156, in main
    import openerp
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/__init__.py", line 76, in <module>
    import modules
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/modules/__init__.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/osv/__init__.py", line 22, in <module>
    import osv
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/osv/osv.py", line 23, in <module>
    from .orm import Model, TransientModel, AbstractModel
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/osv/orm.py", line 5, in <module>
    from ..models import (
  File "/Users/Charlie/Desktop/Python_Workspace/odoo-8.0/openerp/models.py", line 56, in <module>
    import psycopg2
  File "/Library/Python/2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.11-intel.egg/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Library/Python/2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.11-intel.egg/psycopg2/_psycopg.so, 2): Library not loaded: libpq.5.dylib
  Referenced from: /Library/Python/2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.11-intel.egg/psycopg2/_psycopg.so
  Reason: unsafe use of relative rpath libpq.5.dylib in /Library/Python/2.7/site-packages/psycopg2-2.6.2-py2.7-macosx-10.11-intel.egg/psycopg2/_psycopg.so with restricted binary`
Expected behavior:

Success

Video/Screenshot link (optional):
![230405ee-2de8-4950-b6e0-efaba5246a33](https://cloud.githubusercontent.com/assets/10299993/17612255/76231ec8-6082-11e6-9ac1-19425a004d3b.png)

**Comment by kuznetsovin** [comment]
This is problem with psycopg2 package: his not load libpq.5.dylib. The solution this problem is described [here](http://stackoverflow.com/questions/28515972/problems-using-psycopg2-on-mac-os-yosemite)

**Comment by Yenthe666** [comment]
Hi @chary1n,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
