### ISSUE TITLE
Custom_id error in odoo 16.0

### ISSUE THREAD

**Issue by SheltonMuianga** [odoo/odoo#131749]
Impacted versions:
Odoo 16.0

Steps to reproduce:
Create a dashboard, the Change Layout button appears automatically, every time you hit the Change Layout button the custom_id error appears

Current behavior:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/shelton_muianga/projects/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/shelton_muianga/projects/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/shelton_muianga/projects/odoo/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/shelton_muianga/projects/odoo/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/shelton_muianga/projects/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/shelton_muianga/projects/odoo/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
TypeError: View.edit_custom() missing 1 required positional argument: 'custom_id'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost.:8069/web/assets/205-c395ff1/web.assets_backend.min.js:970:163)
    at XMLHttpRequest.<anonymous> (http://localhost.:8069/web/assets/205-c395ff1/web.assets_backend.min.js:978:13)

Expected behavior:
To change layout without rising custom_id error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @SheltonMuianga 
Thanks for reporting.
I could not reproduce. Isn't it related to a custom module? Are you able to reproduce the problem on the [runbot](http://runbot.odoo.com/runbot)?
Please provide more information if it is reproducible.
Cheers

**Comment by BustamiAG10** [comment]
this case, the same in my case :

RPC_ERROR://localhost:8069/web/assets/debug/web.assets_backend.js:10453:19) (/web/static/src/core/network/rpc_service.js:34)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/debug/web.assets_backend.js:10506:27) (/web/static/src/core/network/rpc_service.js:87)
