### ISSUE TITLE
Cannot dispatch sale.order. KeyError: <class 'odoo.api.res.partner'>

### ISSUE THREAD

**Issue by Donderda** [odoo/odoo#131848]
Impacted versions:
15 on Odoo.sh
Steps to reproduce:
Try to fetch a `sale.order` with a partner
Current behavior:
getting this error:
```org.apache.xmlrpc.XmlRpcException: Traceback (most recent call last):
  File "/usr/lib/python3.8/xmlrpc/client.py", line 509, in __dump
    f = self.dispatch[type(value)]
KeyError: <class 'odoo.api.res.partner'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 93, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 74, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 968, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 576, in dump_array
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 594, in dump_struct
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 576, in dump_array
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 576, in dump_array
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 513, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.api.res.partner'> objects```


Expected behavior:
No Error :)

Support ticket number submitted via odoo.com/help (optional):
#3465041

**Comment by Donderda** [comment]
Currently I've fixed it by creating copying the original rpc controller and altering to a custom controller. 

It works, but I'm pretty sure it isn't the most beautiful or reliable way. Improvements and / or hints are more than welcome:

```
import re
import xmlrpc.client
from datetime import date, datetime
from collections import defaultdict

from xmlrpc.client import dumps, loads

from markupsafe import Markup
from werkzeug.wrappers import Response

from odoo.http import Controller, dispatch_rpc, request, route
from odoo.service import wsgi_server
from odoo.fields import Date, Datetime, Command
from odoo.tools import lazy, ustr
from odoo.tools.misc import frozendict

from odoo import models, api, SUPERUSER_ID

# ustr decodes as utf-8 or latin1 so we can search for the ASCII bytes
# 	Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF]
XML_INVALID = re.compile(b'[\x00-\x08\x0B\x0C\x0F-\x1F]')


class MyOdooMarshaller(xmlrpc.client.Marshaller):
    dispatch = dict(xmlrpc.client.Marshaller.dispatch)

    def dump_frozen_dict(self, value, write):
        value = dict(value)
        self.dump_struct(value, write)

    dispatch[frozendict] = dump_frozen_dict

    # By default, in xmlrpc, bytes are converted to xmlrpclib.Binary object.
    # Historically, odoo is sending binary as base64 string.
    # In python 3, base64.b64{de,en}code() methods now works on bytes.
    # Convert them to str to have a consistent behavior between python 2 and python 3.
    def dump_bytes(self, value, write):
        # XML 1.0 disallows control characters, check for them immediately to
        # see if this is a "real" binary (rather than base64 or somesuch) and
        # blank it out, otherwise they get embedded in the output and break
        # client-side parsers
        if XML_INVALID.search(value):
            self.dump_unicode('', write)
        else:
            self.dump_unicode(ustr(value), write)

    dispatch[bytes] = dump_bytes

    def dump_datetime(self, value, write):
        # override to marshall as a string for backwards compatibility
        value = Datetime.to_string(value)
        self.dump_unicode(value, write)

    dispatch[datetime] = dump_datetime

    def dump_date(self, value, write):
        value = Date.to_string(value)
        self.dump_unicode(value, write)

    dispatch[date] = dump_date

    def dump_lazy(self, value, write):
        v = value._value
        return self.dispatch[type(v)](self, v, write)

    dispatch[lazy] = dump_lazy
##########################
# CUSTOM PART START.     #
##########################
    def custom_dump_res_partner(self, value, write):
        v = value
        return self.dump_int(v.id, write)

    try:
        registries = api.Registry.registries.d
        keys = list(registries.keys())

        dbname = keys[0]

        partner_model = api.Registry.registries.d[dbname].models["res.partner"]
        dispatch[partner_model] = custom_dump_res_partner
    except:
        1 + 1
##########################
# CUSTOM PART END.       #
##########################    dispatch[Command] = dispatch[int]
    dispatch[defaultdict] = dispatch[dict]
    dispatch[Markup] = lambda self, value, write: self.dispatch[str](self, str(value), write)

# monkey-patch xmlrpc.client's marshaller
xmlrpc.client.Marshaller = MyOdooMarshaller
```

**Comment by niyasraphy** [comment]
hi @Donderda ,
could you update the issue with relevant part of the script .

triggering below line of code with a local db seems to be working in my end:

models.execute_kw(db, uid, password, 'sale.order', 'search_read', [[]], {'limit': 5})

thanks

**Comment by vava-odoo** [comment]
Closing as it looks solved, don't hesitate to open again if it is not the case
