### ISSUE TITLE
Bug with API request

### ISSUE THREAD

**Issue by scwall** [odoo/odoo#131905]
Impacted versions: 16

Steps to reproduce:

Send ask get in api/.....

GET https://localhost:8069/api/admission/NSEJ/2335442
Accept: application/json

Current behavior:

```
2023-08-14 11:17:39,264 246619 ERROR ? werkzeug: 127.0.0.1 - - [14/Aug/2023 11:17:39] code 400, message Bad request version ("\x8a½(âj4`»Ftk88\x10ª\xad¤}p¶ü¨\x15\x1bu\x11\x10\x03¸]\x9e2\x00b\x13\x02\x13\x01\x13\x03À,À+Ì©À0Ì¨À/\x
00\x9fÌª\x00£\x00\x9e\x00¢À$À(À#À'\x00k\x00j\x00g\x00@À.À2À-À1À&À*À%À)À") - - -
2023-08-14 11:17:39,264 246619 INFO ? werkzeug: 127.0.0.1 - - [14/Aug/2023 11:17:39] "ÑÍ]æm#e
2023-08-14 11:17:39,264 246619 ERROR ? odoo.service.server: Exception happened during processing of request from ('127.0.0.1', 45562)
Traceback (most recent call last):
  File "/usr/lib/python3.11/http/server.py", line 292, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/pascdese/Projects_WSL/Python/Odoo/Eupen/odoo16/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 342, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/home/pascdese/Projects_WSL/Python/Odoo/Eupen/odoo16/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 373, in handle_one_request
    elif self.parse_request():
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/server.py", line 309, in parse_request
    self.send_error(
  File "/usr/lib/python3.11/http/server.py", line 468, in send_error
    self.send_header('Connection', 'close')
  File "/home/pascdese/Projects_WSL/Python/Odoo/community/odoo16/odoo/service/server.py", line 145, in send_header
    if self.headers.get('Upgrade') == 'websocket' and keyword == 'Connection' and value == 'close':
       ^^^^^^^^^^^^
AttributeError: 'RequestHandler' object has no attribute 'headers'
```

Expected behavior:

return json response

**Comment by develop-elitumgroup-gchan** [comment]
someone has been able to fix this?

**Comment by wm-cortex** [comment]
I'm getting the same error in Odoo 16.

Python Version: 3.8
werkzeug Version: 0.16.1 

The issue raised dur to this dirty fix 
https://github.com/odoo/odoo/commit/e3f3e025cc3646f89e0d05993d9a4c8b5a473b0a

**Comment by leomartinez2020** [comment]
I had the same problem and I supposed it was a dependency problem. In the end I solved it in development using the script suggested in the documentation (https://www.odoo.com/documentation/16.0/administration/install/source.html#dependencies):
`sed -n -e '/^Depends:/,/^Pre/ s/ python3-\(.*\),/python3-\1/p' debian/control | sudo xargs apt-get install -y`

**Comment by odoochain** [comment]
me too

**Comment by odoochain** [comment]
> I'm getting the same error in Odoo 16.
> 
> Python Version: 3.8 werkzeug Version: 0.16.1
> 
> The issue raised due to this dirty fix [e3f3e02](https://github.com/odoo/odoo/commit/e3f3e025cc3646f89e0d05993d9a4c8b5a473b0a)

Maybe can do this:
`pip install Werkzeug==2.2.3`
I am in python 3.11

**Comment by Dg0210** [comment]
someone has been able to fix this?

**Comment by devfletscher** [comment]
> > I'm getting the same error in Odoo 16.
> > Python Version: 3.8 werkzeug Version: 0.16.1
> > The issue raised due to this dirty fix [e3f3e02](https://github.com/odoo/odoo/commit/e3f3e025cc3646f89e0d05993d9a4c8b5a473b0a)
> 
> Maybe can do this: `pip install Werkzeug==2.2.3` I am in python 3.11

not working

**Comment by leomartinez2020** [comment]
I solved the problem using http instead of https:
This doesn't work: `https://localhost:8069`
But this works: `http://localhost:8069`

**Comment by odoochain** [comment]
> > > I'm getting the same error in Odoo 16.
> > > Python Version: 3.8 werkzeug Version: 0.16.1
> > > The issue raised due to this dirty fix [e3f3e02](https://github.com/odoo/odoo/commit/e3f3e025cc3646f89e0d05993d9a4c8b5a473b0a)
> > 
> > 
> > Maybe can do this: `pip install Werkzeug==2.2.3` I am in python 3.11
> 
> not working

get fixed file here.
https://github.com/odoochain/OCB/compare/16.0...odoochain-patch-1

My env is:
Python Version: 3.11.6
werkzeug Version: 3.0.1 and 2.2.3

**Comment by SebasAbril91** [comment]
It is possible that you have this problem because you are trying to consume the service using HTTPS and you have not yet configured your server for it.
Try with HTTP, as follows: http://localhost:8069, remember to change <localhost> for the url or IP of your server and the port <8069> for the one you are using in case you are not using the default configuration.
