### ISSUE TITLE
[master][account_reports]  QWebException: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#13230]
Impacted versions:

master, 10e, saas-12

Steps to reproduce:

installed Chinese language support, and switch to Chinese

open report `Trial Balance`  like screen snapshot.

Current behavior:

raise encoding error.

```
QWebException: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/odoo/odoo10e/openerp/addons/base/ir/ir_qweb/qweb.py", line 312, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_account_reports_report_financial_body_124
  File "/opt/odoo/odoo10e/addons/account_reports/models/account_report_coa.py", line 126, in get_columns_names
    columns = [_('Debit') + '<br/>' + temp.decode("utf-8"), _('Credit')]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

Error to render compiling AST
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Template: account_reports.report_financial_body
Path: /templates/t/div/div[5]/table/thead/tr/t[2]
Node: <t t-foreach="context.get_columns_names()" t-as="column_name">
                            <t t-set="column" t-value="column + 1"/>
                            <th t-att-class="context.get_columns_types()[column - 1] == 'number' and 'text-right' or context.get_columns_types()[column - 1] == 'text' and  'text-left' or 'text-center'" t-raw="column_name" t-att-width="context.get_columns_types()[column - 1] == 'number' and '1%' or ''" style="padding-left: 15px;"/>
                        </t>

```

Expected behavior:

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/1404460/17816385/76cae8b2-666b-11e6-9239-e54313c72365.png)

**Comment by vsnetvn** [comment]
It is also similar to the report Profit and Loss

**Comment by xmo-odoo** [comment]
Tried to reproduce both in 9.0 and 10.0 (generic COA) as well as saas-18 (zh_CN + l10n_cn and vi_VN + l10n_vn), no dice.
