### ISSUE TITLE
[16.0] Get error "Uncaught Javascript Error > invalid parameter format" when using. export data

### ISSUE THREAD

**Issue by andriusdj** [odoo/odoo#132490]
Impacted versions: v16

Steps to reproduce:
1) export data (any model, list view)

Current behavior: 
Data is successfully exported

Expected behavior: 
Export fails and an error is shown :

```
UncaughtClientError > TypeError
Uncaught Javascript Error > invalid parameter format
TypeError: invalid parameter format
    parse@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:956:45
    download._download/</xhr.onload@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:978:177
    EventHandlerNonNull*download._download/<@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:978:25
    download._download@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:976:39
    download._download@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:15608:86
    download@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:975:105
    downloadExport@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:4558:7
    async*onDirectExportData@https://winecode.ge/web/assets/713-fdfa5b5/web.assets_backend.min.js:4561:39
    mainEventHandler@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:2106:77
    listener@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1282:15
    EventListener.handleEvent*setup@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1283:47
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1387:90
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1297:164
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1388:269
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1228:57
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1388:269
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1373:261
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1297:164
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1388:269
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1297:164
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1388:269
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1373:261
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1228:57
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1297:164
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1388:269
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1373:261
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1228:57
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1447:57
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1228:57
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1590:69
    mount@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1228:57
    patch@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1233:13
    patch@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1392:178
    _patch@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1595:66
    complete@https://winecode.ge/web/assets/712-ed166f2/web.assets_common.min.js:1501:24
```

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): unable to submit ticket - subscription code is not accepted!

Additional information / links: 
- https://www.odoo.com/forum/help-1/odoo16-export-data-error-in-all-modules-how-to-resolve-it-224621
- https://github.com/odoo/odoo/issues/103232

**Comment by andriusdj** [comment]
downgrade of the python3-werkzeug pacakge to version 2.0.2 of bullseye backports does not work too:

```
UncaughtClientError > TypeError
Uncaught Javascript Error > invalid parameter format
TypeError: invalid parameter format
    at parse (https://winecode.ge/web/assets/764-b9affb1/web.assets_backend.min.js:956:45)
    at xhr.onload (https://winecode.ge/web/assets/764-b9affb1/web.assets_backend.min.js:978:177)
```

**Comment by andriusdj** [comment]
temporary and ugly hack is to downgrade the package:
add repository `deb http://deb.debian.org/debian bullseye-backports main`
do `apt get update` and `apt purge python3-werkzeug && apt install python3-werkzeug=2.0.2+dfsg1-3~bpo11+1`
