### ISSUE TITLE
[16.0][BUG] Website: UncaughtPromiseError > TypeError when editing header in WYSIWYG editor

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#132860]
Impacted versions:
16.0

Steps to reproduce:
- Go to website
- Click on "Edit"
- Click on the top menu (header) to highlight it

Current behavior:
Crash blocks ability to edit menu on homepage.
Error below:

```
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
    at WysiwygAdapterComponent._handleAction (http://localhost:8069/web/assets/debug/web.assets_backend.js:181187:74) (/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js:435)
    at WysiwygAdapterComponent._trigger_up (http://localhost:8069/web/assets/debug/web.assets_backend.js:181171:32) (/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js:419)
    at Class._trigger_up (http://localhost:8069/web/assets/debug/web.assets_common.js:73895:20) (/web/static/src/legacy/js/core/mixins.js:341)
    at Class._trigger_up (http://localhost:8069/web/assets/debug/web.assets_common.js:73895:20) (/web/static/src/legacy/js/core/mixins.js:341)
    at Class._trigger_up (http://localhost:8069/web/assets/debug/web.assets_common.js:73895:20) (/web/static/src/legacy/js/core/mixins.js:341)
    at Class._trigger_up (http://localhost:8069/web/assets/debug/web.assets_common.js:73895:20) (/web/static/src/legacy/js/core/mixins.js:341)
    at Class.trigger_up (http://localhost:8069/web/assets/debug/web.assets_common.js:73888:14) (/web/static/src/legacy/js/core/mixins.js:334)
    at http://localhost:8069/web/assets/debug/website.assets_wysiwyg.js:3058:18 (/website/static/src/js/editor/snippets.options.js:2446)
    at new Promise (<anonymous>)
    at Class._isShown (http://localhost:8069/web/assets/debug/website.assets_wysiwyg.js:3057:16) (/website/static/src/js/editor/snippets.options.js:2445)
```

Expected behavior:
Should be able to edit menu.

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/53917021/be2947c7-bd01-4b02-9c19-ef4bfb983363)

Support ticket number submitted via odoo.com/help (optional):

**Comment by chrisandrewmann** [comment]
A further update that might help with this issue is that it arrived after an upgrade from Odoo 15 using OpenUpgrade. All other functionality seems to be working fine.

**Comment by vava-odoo** [comment]
Hi @chrisandrewmann 
Looks related to the upgrade, but we do not provide any support for OpenUpgrade.
Cheers
