### ISSUE TITLE
AttributeError: Field `subject_ids` does not exist

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#13304]
When i click on Employee Name,  it gives error message as

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 313, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 963, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 513, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 897, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/mail/models/mail_thread.py", line 367, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 1557, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 920, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 463, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `subject_ids` does not exist

Error context:
View `hr.employee.form`
[view_id: 786, xml_id: hr.view_employee_form, model: hr.employee, parent_id: n/a]

**Comment by Yenthe666** [comment]
Hi @odoouser2,

Thank you for your report but I cannot get this simulated. Can you please give me steps and more details about how to reproduce this?
Please try to follow the default template and rules for creating issues.

Regards,
Yenthe

**Comment by JKE-be** [comment]
Hello,

It is probably due to a custom module.
Because 'subject_ids' doesn't exists in Odoo standard code IMHO !

Please provide the version (9 i suppose) and the step to reproduce it on runbot.

If it is not an issue in base code from Odoo, please use https://help.odoo.com to get help. This tracker is for issue in Odoo only.

**Comment by odoouser2** [comment]
Thanks @Yenthe666 and @JKE-be for your comment. It was due to custom module installation. it worked fine now after reinstalling the module.
