### ISSUE TITLE
404 Error when starting v16 Enterprise

### ISSUE THREAD

**Issue by noblesocius** [odoo/odoo#133121]
Impacted versions:
15 Enterprise, 16 Enterprise

Steps to reproduce: 
    - Install enterprise version of Odoo v16 using the InstallScript (or installing the packages from the requirements)
    - Start the Odoo server

Current behavior:
    - On the first start, it raises a 404 error with the log lines
```
2023-05-20 20:04:45,782 40333 INFO ? odoo: Odoo version 16.0
2023-05-20 20:04:45,782 40333 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2023-05-20 20:04:45,782 40333 INFO ? odoo: addons paths: ['/odoo/odoo-server/odoo/addons', 
'/odoo/.local/share/Odoo/addons/16.0', '/odoo/enterprise/addons', '/odoo/odoo-server/addons']
2023-05-20 20:04:45,782 40333 INFO ? odoo: database: default@default:default
2023-05-20 20:04:46,050 40333 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf 
version of the reports.
2023-05-20 20:04:46,174 40333 CRITICAL ? odoo.modules.module: Couldn't load module base
2023-05-20 20:04:46,174 40333 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Traceback (most recent call last):
File "/odoo/odoo-server/odoo/service/server.py", line 1248, in load_server_wide_modules
odoo.modules.module.load_openerp_module(m)
File "/odoo/odoo-server/odoo/modules/module.py", line 432, in load_openerp_module
import('odoo.addons.' + module_name)
File "/odoo/odoo-server/odoo/addons/base/init.py", line 5, in
from . import models
File "/odoo/odoo-server/odoo/addons/base/models/init.py", line 21, in
from . import ir_mail_server
File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in
from OpenSSL import crypto as SSLCrypto
File "/usr/local/lib/python3.10/dist-packages/OpenSSL/init.py", line 8, in
from OpenSSL import crypto, SSL
File "/usr/local/lib/python3.10/dist-packages/OpenSSL/crypto.py", line 1556, in
class X509StoreFlags(object):
File "/usr/local/lib/python3.10/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute
```

The current requirements.txt file installs older versions of the following packages

>cryptography==3.4.8
>pyopenssl==20.0.1

and we suspect this is what causes the error.

Expected behavior:
    Normal loading of Odoo web page on first startup
I'm guessing there's a reason behind using older versions of these packages as the current versions are as follows:

> cryptography 41.0.3
> pyOpenSSL 23.2.0

@d-fence I was told by Yenthe that you were the one that knows how to take care and handle this packaging issue. If there are no other obstacles, kindly change these lines in the requirements.txt file so that it downloads the latest versions of these packages. 

A similar issue that we found in this repo #110634

**Comment by Ranamiu** [comment]
Can confirm, same issue on latest Odoo 16 CE 260823 Community Edition.

Solved upgrading packages to:

> cryptography   41.0.3
> pyOpenSSL   23.2.0

Latest Odoo 16 CE requirements should be probably updated.

Please, anyone in charge of, kindly report.

Appreciate

**Comment by d-fence** [comment]
Hello. I cannot reproduce the bug. Which install script did you use ?

**Comment by Yenthe666** [comment]
@d-fence it seems to happen depending on the cloud provider and/or latest updates :) I've been bitten by it once in a while too. In some cases you can reproduce it with my installation script too https://github.com/Yenthe666/InstallScript

**Comment by d-fence** [comment]
I that case, I would recommend to use a virtualenv as it seems to be related with some cloud provider packages. Our requirements should match the Ubuntu/Debian packages versions at the time of the release. So in the case of 16.0 it's Jammy and Buster. I tested right now in a virtualenv and in a Docker Jammy and I could not reproduce. We probably won't change the requirements to fix the cloud  providers issues.

**Comment by Yenthe666** [comment]
@d-fence just a note. Remember that a big majority does **not** use virtualenvs and generally do an install on a bare Linux (and thus no Docker). Don't underestimate how many people run it on a native Ubuntu without virtualenv.

**Comment by noblesocius** [comment]
Not sure if this is related, but I just ran into this error on a fresh server with just Python 3.8 installed. I was trying to install some certs using certbot and that triggered this exact error. So now I feel this has more to do with Python itself rather than Odoo. If possible, we should address this issue to the Python devs. Maybe this issue already exists there, but if not, can someone point me in the right direction. Thanks for your inputs @d-fence @Yenthe666 @mehjabinfarsana.

**Comment by colinstu12** [comment]
I had to upgrade urllib3 to at least 2.0.5 to resolve this issue (up to 2.0.7 currently supported).
