### ISSUE TITLE
OwlError on export dialog trying to load an export template with developer mode enabled

### ISSUE THREAD

**Issue by adnoh** [odoo/odoo#133281]
Impacted versions: 16

Steps to reproduce: go for example to products, list view, select a few, export, save the field selection as a template. reopen that dialog and try to load your created export template

Current behavior: error message:
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: undefined
OwlError: Got duplicate key in t-foreach: undefined
    at ExportDataDialog.slot2 (eval at compile (http://localhost:8069/web/assets/debug/web.assets_common.js:21540:16), <anonymous>:132:45) (/web/static/lib/owl/owl.js:5480)
    at callSlot (http://localhost:8069/web/assets/debug/web.assets_common.js:18969:37) (/web/static/lib/owl/owl.js:2909)
    at Dialog.template (eval at compile (http://localhost:8069/web/assets/debug/web.assets_common.js:21540:16), <anonymous>:47:10) (/web/static/lib/owl/owl.js:5480)
    at Fiber._render (http://localhost:8069/web/assets/debug/web.assets_common.js:17676:38) (/web/static/lib/owl/owl.js:1616)
    at Fiber.render (http://localhost:8069/web/assets/debug/web.assets_common.js:17668:18) (/web/static/lib/owl/owl.js:1608)
    at ComponentNode.updateAndRender (http://localhost:8069/web/assets/debug/web.assets_common.js:18509:19) (/web/static/lib/owl/owl.js:2449)

Expected behavior: load the saved export template

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by adnoh** [comment]
@vava-odoo don't get it in the runbot. Can be closed
Quite strange, I tested with a few fresh docker containers and the all blew up in that constellation 🤷🏼‍♂️

**Comment by vava-odoo** [comment]
That's the magic of Odoo :shrug:
