### ISSUE TITLE
PosBox RuntimeError: cannot set daemon status of active thread

### ISSUE THREAD

**Issue by linuxipho** [odoo/odoo#13395]
Impacted versions:
PosBox v14

Current behavior:

There is no way to print a receipt nor open cash drawer, the http://my_posbox_ip:8069/hw_proxy/status page report a bug (error 500) and I have this entry in /var/log/odoo/odoo-server.log (PosBox hardware) :

```
2016-09-05 09:23:40,867 789 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/pi/odoo/openerp/http.py", line 540, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/pi/odoo/openerp/http.py", line 577, in dispatch
    result = self._call_function(**self.params)
  File "/home/pi/odoo/openerp/http.py", line 314, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/pi/odoo/openerp/http.py", line 806, in __call__
    return self.method(*args, **kw)
  File "/home/pi/odoo/openerp/http.py", line 406, in response_wrap
    response = f(*args, **kw)
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 122, in status_json
    return self.get_status()
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 38, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 114, in get_status
    self.push_task('status')
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 191, in push_task
    self.lockedstart()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 100, in lockedstart
    self.daemon = True
  File "/usr/lib/python2.7/threading.py", line 1029, in daemon
    raise RuntimeError("cannot set daemon status of active thread");
RuntimeError: cannot set daemon status of active thread
```

Expected behavior:
Printer recognized as connected

**Comment by safecoms** [comment]
Not sure if this is fixed, but it could be because the printer modele is not fully recognized.

I just got the same error.
We have an old Epson model M188B.

At first, it takes some time but I get an ip printed from the POSBOX. but as soon as I am in the POS application and want to print, the connection becomes red with the followin error message.
`Traceback (most recent call last):
  File "/home/pi/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/pi/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/pi/odoo/openerp/http.py", line 318, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/pi/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/pi/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 377, in print_xml_receipt
    driver.push_task('xml_receipt',receipt)
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 195, in push_task
    self.lockedstart()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 100, in lockedstart
    self.daemon = True
  File "/usr/lib/python2.7/threading.py", line 1029, in daemon
    raise RuntimeError("cannot set daemon status of active thread");
RuntimeError: cannot set daemon status of active thread
`

**Comment by pedrobaeza** [comment]
This seems a deployment problem, so I'm closing this in expectation is already fixed at that level.
