### ISSUE TITLE
 why odoo 16  can't update files  used  webportal？

### ISSUE THREAD

**Issue by filwu8** [odoo/odoo#134018]
Impacted versions:  16 .0

Steps to reproduce:

open Purchasing   or   Sales order in   webportal
update  files

Current behavior:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_slides/controllers/mail.py", line 25, in portal_chatter_post
    result = super(SlidesPortalChatter, self).portal_chatter_post(res_model, res_id, message, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/project/controllers/project_sharing_chatter.py", line 92, in portal_chatter_post
    return super().portal_chatter_post(res_model, res_id, message, attachment_ids=attachment_ids, attachment_tokens=attachment_tokens, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/portal_rating/controllers/portal_chatter.py", line 29, in portal_chatter_post
    return super(PortalChatter, self).portal_chatter_post(res_model, res_id, message, attachment_ids=attachment_ids, attachment_tokens=attachment_tokens, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/portal/controllers/mail.py", line 130, in portal_chatter_post
    self._portal_post_check_attachments(attachment_ids or [], attachment_tokens or [])
  File "/usr/lib/python3/dist-packages/odoo/addons/portal/controllers/mail.py", line 109, in _portal_post_check_attachments
    request.env['ir.attachment'].browse(attachment_ids)._check_attachments_access(attachment_tokens)
AttributeError: 'ir.attachment' object has no attribute '_check_attachments_access'

The above server error caused the following client error:
null

**Comment by filwu8** [comment]
> hi @filwu8 , are you able to reproduce the same in runbot ? i tried with specified steps and seems working fine with me. thanks

thanks，may be i updated promble codes , i try Downgrade codes

https://github.com/odoo/odoo/commit/914870f2d4b9dbdf39cdde98fed3bb21ca0074cf#diff-d43c34911f97d4d6b8963b41c1419a4c55b36f645bafaf627d2890f0faf44d35

**Comment by vava-odoo** [comment]
Closing as seems to be solved. Don't hesitate to open again if not the case.
