### ISSUE TITLE
Error When Post Journal Entries with two or more taxes

### ISSUE THREAD

**Issue by afwanwh** [odoo/odoo#13446]
Impacted versions: 9.0

Steps to reproduce:
1. Create expense with two taxes filled
2. submit and approve
3. Post journal entries

Current behavior: I get error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/addons/web/controllers/main.py", line 911, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/addons/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/addons/hr_expense/models/hr_expense.py", line 230, in action_move_create
    move_lines = expense._move_line_get()
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/addons/hr_expense/models/hr_expense.py", line 291, in _move_line_get
    account_move[-1]['tax_ids'] = expense.tax_ids.id
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/fields.py", line 2020, in __get__
    return record.ensure_one()._ids[0]
  File "/home/odoo/runbot/extra/runbot/static/build/171100-9-0-3c82d5/openerp/models.py", line 5415, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.tax(8, 9)

Expected behavior: No Error

Video/Screenshot link (optional):

**Comment by afwanwh** [comment]
Thanks, it works now.
