### ISSUE TITLE
Error when installed a module: Product and Pricelist within demo

### ISSUE THREAD

**Issue by RickHunterEc** [odoo/odoo#13451]
@odony, please, can you review this problem:

Impacted versions: Master (10.0 community)
Steps to reproduce: 
1) Install a new Odoo.
2) Create a database with demo and install Module: Product and Pricelist: Ok.
3) Create a new database within demo and install Module: Product and Pricelist: Error.
File ../odoo/addons/product/data/product_data.xml have a dependency with base_demo.xml for create record base.partner_demo, in line 200:
` <record forcecreate="True" id="property_product_pricelist_demo" model="ir.property">
            <field name="name">property_product_pricelist</field>
            <field name="fields_id" search="[('model','=','res.partner'),('name','=','property_product_pricelist')]"/>
            <field eval="'product.pricelist,'+str(ref('list0'))" name="value"/>
            <field eval="'res.partner,'+str(ref('base.partner_demo'))" name="res_id"/>
        </record>`
but this file install only with check demo when create database.

Current behavior:
```
2016-09-11 11:16:42,584 16150 ERROR test_odoo3 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-10.0/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-10.0/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-10.0/odoo/addons/web/controllers/main.py", line 856, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo-10.0/odoo/addons/web/controllers/main.py", line 844, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo-10.0/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo-10.0/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-10.0/odoo/odoo/addons/base/module/module.py", line 526, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo-10.0/odoo/odoo/addons/base/module/module.py", line 483, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo-10.0/odoo/odoo/modules/registry.py", line 77, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo-10.0/odoo/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo-10.0/odoo/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo-10.0/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo-10.0/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 850, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 920, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 804, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 703, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 118, in _eval_xml
    return unsafe_eval(a_eval, idref2)
  File "<string>", line 1, in <module>
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 787, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo-10.0/odoo/odoo/tools/convert.py", line 793, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo-10.0/odoo/odoo/addons/base/ir/ir_model.py", line 920, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo-10.0/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo-10.0/odoo/odoo/addons/base/ir/ir_model.py", line 909, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: base.partner_demo" while parsing /opt/odoo-10.0/odoo/addons/product/data/product_data.xml:200, near
<record forcecreate="True" id="property_product_pricelist_demo" model="ir.property">
            <field name="name">property_product_pricelist</field>
            <field name="fields_id" search="[('model','=','res.partner'),('name','=','property_product_pricelist')]"/>
            <field eval="'product.pricelist,'+str(ref('list0'))" name="value"/>
            <field eval="'res.partner,'+str(ref('base.partner_demo'))" name="res_id"/>
        </record>
```
Expected behavior:
Change file with base.main_partner as res_id:
`` <record forcecreate="True" id="property_product_pricelist_demo" model="ir.property">
            <field name="name">property_product_pricelist</field>
            <field name="fields_id" search="[('model','=','res.partner'),('name','=','property_product_pricelist')]"/>
            <field eval="'product.pricelist,'+str(ref('list0'))" name="value"/>
            <field eval="'res.partner,'+str(ref('base.main_partner'))" name="res_id"/>
        </record>``

**Comment by JKE-be** [comment]
@RickHunterEc  Thanks for reporting

It has been fixed one week ago, but not already forward-ported https://github.com/odoo/odoo/commit/a5e03c1bf47e43dea826ec8ad9583af9863f48f7

**Comment by RickHunterEc** [comment]
Hi. When can you port this change to master branch?

El 14 sept. 2016 03:41, "JKE-be" <notifications@github.com> escribió:

>

> Closed #13451 <https://github.com/odoo/odoo/issues/13451>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/13451#event-788793782>, or mute the
thread

**Comment by JKE-be** [comment]
ASAP, @KangOl is working on it now... (but starting from the older version to the newest...)

**Comment by RickHunterEc** [comment]
Ready. Thanks @JKE-be.
