### ISSUE TITLE
Cant use Discuss chat on Android

### ISSUE THREAD

**Issue by dev-dynaeng** [odoo/odoo#135097]
Impacted versions:16

Steps to reproduce:open odoo online on Android. Go to Discuss app and try to open a chat.

Current behavior:get the following error:

UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot set properties of undefined (setting 'hidden')
TypeError: Cannot set properties of undefined (setting 'hidden')
    at Proxy.hide (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:8625:35)
    at Proxy.hide (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:10167:449)
    at hide (patch discuss/core/web) (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:2135:22)
    at Proxy.makeVisible (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:8622:79)
    at Proxy.insert (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:8619:28)
    at Proxy._openChatWindow (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:9754:121)
    at Proxy.open (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:9750:60)
    at open (patch mail/core/web) (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:2135:22)
    at MessagingMenu.openDiscussion (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:9660:43)
    at MessagingMenu.onClickThread (https://dynaengineering.odoo.com/web/assets/42-33e494c/web.assets_backend.min.js:9640:59)

Expected behavior:
Be able to see the chat
Video/Screenshot link (optional):
![Screenshot_20230911_101812_Chrome](https://github.com/odoo/odoo/assets/103538618/9edeba61-69ee-438f-8f73-c74c395c66e9)

Support ticket number submitted via odoo.com/help (optional):

**Comment by seb-odoo** [comment]
Assuming resolved, dynaengineering no longer available to test issue.
