### ISSUE TITLE
[9.0][MRP] Error when press Start on Work Orders or Edit Work Orders with scheduled date

### ISSUE THREAD

**Issue by pfunkowski** [odoo/odoo#13559]
Impacted versions:
9.0

Steps to reproduce:
-Manufacturing
-Work orders - select order with sheduled date OR start order

Current behavior:
Message with odoo error

Video/Screenshot link (optional):
`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 899, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1272, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1040, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 194, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 188, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3617, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/__init__.py", line 67, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/service.py", line 73, in validate
    res2 = wi.validate(signal)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/instance.py", line 62, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 102, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 230, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 239, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 77, in create
    workflow_item.process(stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 98, in process
    if not self._execute(activity, stack):
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 144, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 295, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 273, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_operations/mrp_operations.py", line 171, in action_start_working
    self.modify_production_order_state(cr, uid, ids, 'start')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_operations/mrp_operations.py", line 126, in modify_production_order_state
    prod_obj_pool.signal_workflow(cr, uid, [prod_obj.id], 'button_produce')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3617, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/__init__.py", line 67, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/service.py", line 73, in validate
    res2 = wi.validate(signal)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/instance.py", line 62, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 102, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 230, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 239, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 77, in create
    workflow_item.process(stack=stack)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 98, in process
    if not self._execute(activity, stack):
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 144, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 295, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/usr/lib/python2.7/dist-packages/openerp/workflow/workitem.py", line 273, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_operations/mrp_operations.py", line 248, in action_in_production
    return super(mrp_production,self).action_in_production(cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp/mrp.py", line 1110, in action_in_production
    return self.write(cr, uid, ids, {'state': 'in_production', 'date_start': time.strftime('%Y-%m-%d %H:%M:%S')})
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_operations/mrp_operations.py", line 359, in write
    self._compute_planned_workcenter(cr, uid, ids, context=context, mini=mini)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mrp_operations/mrp_operations.py", line 289, in _compute_planned_workcenter
    wc.hour or 0.0
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/resource/resource.py", line 615, in interval_get
    cr, uid, [(dt_from.strftime('%Y-%m-%d %H:%M:%S'), hours, id)], resource, byday)[(dt_from.strftime('%Y-%m-%d %H:%M:%S'), hours, id)]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/resource/resource.py", line 604, in interval_get_multi
    default_interval=(8, 16)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/resource/resource.py", line 487, in schedule_hours
    return self._schedule_hours(cr, uid, id, hours, day_dt, compute_leaves, resource_id, default_interval, context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/resource/resource.py", line 468, in _schedule_hours
    current_datetime = datetime.datetime.combine(self.get_next_day(cr, uid, id, current_datetime, context), datetime.time())
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/resource/resource.py", line 200, in get_next_day
    new_index = (base_index + 1) % len(weekdays)
ValueError: ""integer division or modulo by zero" while evaluating
u'action_in_production()'" while evaluating
u'action_start_working()'
`

**Comment by Yenthe666** [comment]
Hi @pfunkowski,

Thanks a lot for your bug report and sorry for the late reply.
This issue has been fixed in the meanwhile. If you still face is then please update your local Odoo instance.

Regards,
Yenthe
