### ISSUE TITLE
V15 Upgrade Error Due To sale_renting SQL View

### ISSUE THREAD

**Issue by mariadforgeflow** [odoo/odoo#136171]
Impacted versions: Database upgrade  15.0 --> 16.0

Steps to reproduce: Upgrade v15 database to v16 with module `sale_renting` installed

Current behavior:

The following error blocks the database upgrade:

```
2023-09-21 13:39:28,893 6464 INFO db_1147242 odoo.modules.registry: module product: creating or updating database tables 
2023-09-21 13:39:28,960 6464 ERROR db_1147242 odoo.sql_db: bad query: 
        ALTER TABLE "product_template"
        ALTER COLUMN "name" DROP DEFAULT,
        ALTER COLUMN "name" TYPE jsonb USING CASE WHEN "name" IS NOT NULL THEN jsonb_build_object('en_US', "name"::varchar) END
    
ERROR: operator class "gin_trgm_ops" does not accept data type jsonb
 
2023-09-21 13:39:28,990 6464 WARNING db_1147242 odoo.modules.loading: Transient module states were reset 
2023-09-21 13:39:28,990 6464 ERROR db_1147242 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/tools/sql.py", line 147, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.FeatureNotSupported: cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view sale_rental_schedule depends on column "name"
```
`sale_renting` module adds `sale_rental_schedule` SQL view that is causing the issue.

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
It isn't the sale rental module, it is every trigram index on every translatable field. While some are covered in enterprise migration so they don't error, we just tend to drop them before submitting database, figuring the right ones will be recreated anyway.
