### ISSUE TITLE
[10.0] JSON-RPC database drop raises exception

### ISSUE THREAD

**Issue by katyukha** [odoo/odoo#13694]
Impacted versions:
- 10.0

Steps to reproduce:
- make json-rpc call like 

``` json
{
    "params": {
        "args": [
            "adminpass",
            "odoo-10-test-x1"
        ],
        "method": "drop",
        "service": "db"
    },
    "jsonrpc": "2.0",
    "method": "call",
    "id": 986950257
}
```

Current behavior:
- Database _dropt_
- But following exception raised on Odoo server:

``` traceback
2016-10-06 11:30:17,164 6676 INFO None werkzeug: 127.0.0.1 - - [06/Oct/2016 11:30:17] "POST /jsonrpc HTTP/1.1" 500 -
2016-10-06 11:30:17,193 6676 ERROR None werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/http.py", line 1476, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/http.py", line 276, in __exit__
    self._cr.commit()
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/katyukha/projects/OpenERP/odoo-10.0/odoo/odoo/sql_db.py", line 363, in commit
    result = self._cnx.commit()
InterfaceError: connection already closed
```

Expected behavior:
- No exceptions raised

**Comment by Yenthe666** [comment]
Hi @katyukha,

Thanks a lot for your report.
Could you please propose this fix as a PR on Odoo 10? Then the Odoo developers can have a look at it, test it and in case everything is fine merge it.

Regards,
Yenthe

**Comment by katyukha** [comment]
Hello @Yenthe666 

This is not a fix, i just found this bug, when tried to add tests for compatability with Odoo 10 to my [rpc-client project](https://github.com/katyukha/openerp-proxy), so i have no fix for this bug(

Regards,
Dmytro

**Comment by Yenthe666** [comment]
@mart-e and @xmo-odoo could you guys have a look at this one please?

**Comment by katyukha** [comment]
Seems to be already fixed.
