### ISSUE TITLE
[10.0] Lead Automation >> Campaigns >> Campaigns Form  >> Diagram - ValueError

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#13724]
Impacted versions: 10

Steps to reproduce: Lead Automation >> Campaigns >> Campaigns Form  >> Diagram

Current behavior:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_diagram/controllers/main.py", line 103, in get_diagram_info
    if safe_eval(expr, act):
  File "/usr/lib/python2.7/dist-packages/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: <type 'exceptions.NameError'>: "name 'type' is not defined" while evaluating
u"type=='subcampaign'"

Expected behavior: View Diagram

Video/Screenshot link (optional): https://youtu.be/-9u_hbXcV8U

**Comment by Yenthe666** [comment]
Hi @collex100,

Thanks a lot for your report and for the video!
I've just tested this and I can confirm this is a bug.
@mart-e can you assign somebody on this one please?

Regards,
yenthe

**Comment by JKE-be** [comment]
Hello, 

Thanks for the reporting, It has been fixed by commit odoo/doo@8033467

Best regards

JKE
