### ISSUE TITLE
odoo install requirements error

### ISSUE THREAD

**Issue by Ramil001** [odoo/odoo#137201]
Navigate to the path of the Odoo Community installation (CommunityPath) and run pip on the requirements file to install the requirements for the current user.

 cd /CommunityPath
 pip install -r requirements.txt

```
root@ubuntu-2gb-nbg1-1:/odoo# pip install -r requirements.txt
Ignoring freezegun: markers 'python_version < "3.8"' don't match your environment
Ignoring gevent: markers 'python_version == "3.7"' don't match your environment
Ignoring gevent: markers 'python_version > "3.7" and python_version <= "3.9"' don't match your environment
Ignoring gevent: markers 'python_version > "3.10"' don't match your environment
Ignoring greenlet: markers 'python_version == "3.7"' don't match your environment
Ignoring greenlet: markers 'python_version > "3.7" and python_version <= "3.9"' don't match your environment
Ignoring greenlet: markers 'python_version > "3.10"' don't match your environment
Ignoring Jinja2: markers 'python_version > "3.10"' don't match your environment
Ignoring lxml: markers 'python_version > "3.10"' don't match your environment
Ignoring MarkupSafe: markers 'python_version > "3.10"' don't match your environment
Ignoring ofxparse: markers 'python_version <= "3.9"' don't match your environment
Ignoring Pillow: markers 'python_version > "3.10"' don't match your environment
Ignoring psutil: markers 'python_version > "3.10"' don't match your environment
Ignoring psycopg2: markers 'sys_platform != "win32" and python_version < "3.8"' don't match your environment
Ignoring psycopg2: markers 'sys_platform == "win32" and python_version < "3.10"' don't match your environment
Ignoring psycopg2: markers 'python_version > "3.10" or (sys_platform == "win32" and python_version == "3.10")' don't match your environment
Ignoring PyPDF2: markers 'python_version > "3.10"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring pyusb: markers 'python_version > "3.10"' don't match your environment
Ignoring reportlab: markers 'python_version > "3.10"' don't match your environment
Ignoring Werkzeug: markers 'python_version <= "3.9"' don't match your environment
Ignoring xlrd: markers 'python_version < "3.8"' don't match your environment
Collecting Babel==2.9.1
  Downloading Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 35.2 MB/s eta 0:00:00
Requirement already satisfied: chardet==4.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (4.0.0)
Requirement already satisfied: cryptography==3.4.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (3.4.8)
Collecting decorator==4.4.2
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting docutils==0.16
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.2/548.2 KB 58.8 MB/s eta 0:00:00
Collecting ebaysdk==2.1.5
  Downloading ebaysdk-2.1.5.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 KB 11.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting freezegun==0.3.15
  Downloading freezegun-0.3.15-py2.py3-none-any.whl (14 kB)
Collecting gevent==21.8.0
  Downloading gevent-21.8.0.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 123.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 481, in <module>
          run_setup(EXT_MODULES)
        File "setup.py", line 348, in run_setup
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-awkpvn9m/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-awkpvn9m/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-awkpvn9m/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
          ffi = FFI()
        File "/tmp/pip-build-env-awkpvn9m/overlay/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.16.0, located in '/tmp/pip-build-env-awkpvn9m/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
root@ubuntu-2gb-nbg1-1:/odoo# 
```

**Comment by getlazo** [comment]
Had the same issue, but it works with python 3.9
