### ISSUE TITLE
[10.0] variant product can't be added to cart

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#13757]
Impacted versions: odoo 10 nightly

Steps to reproduce:

![image](https://cloud.githubusercontent.com/assets/3096827/19298499/b7345110-9080-11e6-80dd-55168e6f543a.png)

The product has variants has an issue,it's that when the attributes have single value,then when this product was added to cart,it will cause 500 Internal Server Error.

Here is the log:

```
2016-10-12 05:49:23,117 15789 INFO demo76 odoo.sql_db: bad query: INSERT INTO "sale_order_line" ("id", "qty_delivered", "product_id", "product_uom", "sequence", "customer_lead", "price_unit", "product_uom_qty", "order_id", "state", "invoice_status", "discount", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('sale_order_line_id_seq'), '0.000', NULL, NULL, 10, 0.0, '0.00', '1.000', 17, 'draft', 'no', '0.00', NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2016-10-12 05:49:23,117 15789 ERROR demo76 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 265, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 161, in wrapper
    raise ValidationError(msg)
ValidationError: ('The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: Product Unit of Measure - product.uom]', None)

2016-10-12 05:49:23,118 15789 INFO demo76 odoo.sql_db: bad query: SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = 'website.500'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1
2016-10-12 05:49:23,119 15789 INFO demo76 odoo.sql_db: bad query: SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = 'website.http_error'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1
2016-10-12 05:49:23,126 15789 INFO demo76 werkzeug: 127.0.0.1 - - [12/Oct/2016 05:49:23] "POST /shop/cart/update HTTP/1.0" 500 -
2016-10-12 05:49:23,138 15789 ERROR demo76 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 210, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 318, in _handle_exception
    html = request.env['ir.ui.view'].render_template('website.http_error', values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1020, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "<string>", line 2, in get_view_id
    
  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 77, in get_view_id
    view = self.search(domain, order='website_id', limit=1)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1497, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4203, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

How to make it work?

**Comment by Yenthe666** [comment]
Hi @ed29,

Thank you for your report.
I've just tested this on the latest Odoo 10.0 and it works without any issues. The product:
![image](https://cloud.githubusercontent.com/assets/6352350/19299713/5071c5ea-9056-11e6-81e0-5f60323afd4d.png)

The website:
![image](https://cloud.githubusercontent.com/assets/6352350/19299721/5ff922a6-9056-11e6-8708-1c2986d26149.png)

Could you test it again on the latest runbot (runbot.odoo.com) please? If you cannot reproduce it there it means you'll have to update your local Odoo installation.

Regards,
Yenthe

**Comment by ed29** [comment]
@Yenthe666 Can it be added to cart? I already upgrade the odoo 10 nightly to today's version.I tested this on demonstration database,only install the ecommece APP.

![image](https://cloud.githubusercontent.com/assets/3096827/19301618/f01ea70c-9092-11e6-8d7c-d8c8ccf3849a.png)

**Comment by Yenthe666** [comment]
Ahh yes I didn't add it to the cart.
This is indeed a bug and has been confirmed!

**Comment by JKE-be** [comment]
Hello @ed29 

It seems that the bug is because product variant are duplicated. Once at the product creation, once a the variant creation. Temporary, you can delete one of both... (there are both identical)
We try to find a patch, but for previous variants created, you will probably need to delete the duplicate manually.

**Comment by ed29** [comment]
@Yenthe666  @JKE-be  OK,and thank you.
