### ISSUE TITLE
[10.0] Lead Automation > Campaigns > Campaigns Form > Diagram > New Link > Odoo Client Error

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#13775]
Impacted versions:10

Steps to reproduce: Lead Automation > Campaigns > Campaigns Form > Diagram > New Link > Odoo Client Error
```
Current behavior: Odoo Client Error
Uncaught TypeError: Cannot read property 'on' of undefined
http://mysite.bz/web/content/376-c85406d/web.assets_backend.js:3722
Traceback:
TypeError: Cannot read property 'on' of undefined
    at OdooClass.add_connector (http://mysite.bz/web/content/376-c85406d/web.assets_backend.js:3722:1064)
    at Function.CuteEdge.new_edge_callback (http://mysite.bz/web/content/376-c85406d/web.assets_backend.js:3719:277)
    at Element.drag_up (http://mysite.bz/web/content/376-c85406d/web.assets_backend.js:3644:235)
    at eve (http://mysite.bz/web_diagram/static/lib/js/raphael.js:79:32)
    at Function.dragUp (http://mysite.bz/web_diagram/static/lib/js/raphael.js:2030:13)
    at HTMLDocument.f (http://mysite.bz/web_diagram/static/lib/js/raphael.js:1953:31)
```
Expected behavior: New Link

Video/Screenshot link (optional): https://youtu.be/qiq0RMvLglU

**Comment by Yenthe666** [comment]
Hi @collex100,

Thanks a lot for your report.
I've just tested this and I can confirm this is a bug. Example:
![image](https://cloud.githubusercontent.com/assets/6352350/19316557/3947b248-90a2-11e6-92bd-94d38be05559.png)

P.S: It is new node in place of new link in your description.
@mart-e for who is this one?

Regards,
Yenthe

**Comment by mart-e** [comment]
@aab-odoo @ged-odoo any idea? The non-minimized traceback is:
```
Uncaught TypeError: Cannot read property 'on' of undefined
http://175189-10-0-0acd63.runbot9.odoo.com/web_diagram/static/src/js/diagram.js:280
Traceback:
TypeError: Cannot read property 'on' of undefined
    at OdooClass.add_node (http://175189-10-0-0acd63.runbot9.odoo.com/web_diagram/static/src/js/diagram.js:280:24)
    at HTMLButtonElement.<anonymous> (http://175189-10-0-0acd63.runbot9.odoo.com/web_diagram/static/src/js/diagram.js:349:18)
    at HTMLDivElement.dispatch (http://175189-10-0-0acd63.runbot9.odoo.com/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLDivElement.elemData.handle (http://175189-10-0-0acd63.runbot9.odoo.com/web/static/lib/jquery/jquery.js:4309:63)
```
I wonder if it's not a deferred missing as the form view is not loaded yet before this call.

**Comment by aab-odoo** [comment]
@mart-e @ged-odoo i take it
