### ISSUE TITLE
XMLSyntaxError: Document is empty, line 1, column 1

### ISSUE THREAD

**Issue by bala2341** [odoo/odoo#13815]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @bala2341,

Thanks for your report but we really need more information in order to handle an issue.
Please create a new issue which tells us for which Odoo version this is and what the exact problem is.

Regards,
Yenthe

**Comment by bala2341** [comment]
i have Odoo 9  integrated with jasper report. while i click the print button i got the following error for " 

odoo09 openerp.pooler: openerp.pooler.get_db_and_pool() is deprecated.
2016-10-14 12:32:11,442 19765 INFO odoo09 openerp.addons.jasperreports.jasper_report: Requested report: '/opt/AIMSERP/addons'
2016-10-14 12:32:11,442 19765 ERROR odoo09 openerp.service.report: Exception: Document is empty, line 1, column 1
Traceback (most recent call last):
  File "/opt/AIMSERP/openerp/service/report.py", line 94, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/AIMSERP/openerp/report/__init__.py", line 22, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/AIMSERP/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/AIMSERP/openerp/addons/base/ir/ir_actions.py", line 197, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/AIMSERP/addons/jasperreports/jasper_report.py", line 306, in create
    return r.execute()
  File "/opt/AIMSERP/addons/jasperreports/jasper_report.py", line 107, in execute
    self.report = JasperReport(self.reportPath)
  File "/opt/AIMSERP/addons/jasperreports/JasperReports/JasperReport.py", line 65, in __init__
    self.extractProperties()
  File "/opt/AIMSERP/addons/jasperreports/JasperReports/JasperReport.py", line 137, in extractProperties
    doc = etree.parse(self._reportPath)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
XMLSyntaxError: Document is empty, line 1, column 1
2016-10-14 12:32:11,688 19765 ERROR odoo09 openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/AIMSERP/addons/web/controllers/main.py", line 67, in wrap
    return f(*args, **kwargs)
  File "/opt/AIMSERP/addons/web/controllers/main.py", line 1481, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/AIMSERP/openerp/http.py", line 1040, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/AIMSERP/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/AIMSERP/openerp/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/opt/AIMSERP/openerp/service/report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "/opt/AIMSERP/openerp/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"Document is empty, line 1, column 1: (<class 'lxml.etree.XMLSyntaxError'>, XMLSyntaxError(u'Document is empty, line 1, column 1',), <traceback object at 0x7f8c50f00950>)", None)

plz help me?

**Comment by Yenthe666** [comment]
Hi @bala2341,

The Github tracker is only for bugs in the official Odoo code. Jasper Reports is not from Odoo so this can't be handled here.
I'd advice you to create a new topic on the official help forums, where a lot of people can probably help you. See http://help.odoo.com/

Regards,
Yenthe

**Comment by bala2341** [comment]
actually problem is not for jasper report. problem occur on  File "/opt/odoo/openerp/addons/base/ir/ir_actions.py", line 197, in render_report issue

**Comment by alexcuellar** [comment]
I got a similar error in Ubuntu 18.04 with Odoo11 and the solutions like this:
`diff --git a/odoo/tools/convert.py b/odoo/tools/convert.py
index 59e87d6ee32..4a53169e17b 100644
--- a/odoo/tools/convert.py
+++ b/odoo/tools/convert.py
@@ -831,7 +831,7 @@ def convert_csv_import(cr, module, fname, csvcontent, idref=None, mode='init',
 def convert_xml_import(cr, module, xmlfile, idref=None, mode='init', noupdate=False, report=None):
     doc = etree.parse(xmlfile)
     relaxng = etree.RelaxNG(
-        etree.parse(os.path.join(config['root_path'],'import_xml.rng' )))
+        etree.parse(os.path.join(config['root_path'],'import_xml.rng' ),etree.ETCompatXMLParser()))
     try:
         relaxng.assert_(doc)
     except Exception:
`
