### ISSUE TITLE
Operations > Replenishment: OverflowError: date value out of range after  Commit 62153ba5c

### ISSUE THREAD

**Issue by btxluke** [odoo/odoo#138113]
Impacted versions:

Odoo 16e, using UK date formats

Steps to reproduce:

open Inventory > Replenishment

Current behavior:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/tools/safe_eval.py", line 362, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(649,)", line 6, in <module>
  File "/opt/odoo/odoo-server/addons/stock/models/stock_orderpoint.py", line 203, in action_open_orderpoints
    return self._get_orderpoint_action()
  File "/opt/odoo/odoo-server/addons/stock/models/stock_orderpoint.py", line 362, in _get_orderpoint_action
    to_date=today + relativedelta.relativedelta(days=days)
  File "/opt/odoo/odoo-server/venv/lib/python3.10/site-packages/dateutil/relativedelta.py", line 405, in __radd__
    return self.__add__(other)
  File "/opt/odoo/odoo-server/venv/lib/python3.10/site-packages/dateutil/relativedelta.py", line 387, in __add__
    ret = (other.replace(**repl)
OverflowError: date value out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/action.py", line 42, in run
    result = action.run()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 668, in run
    res = runner(run_self, eval_context=eval_context)
  File "/opt/odoo/odoo-server/addons/website/models/ir_actions_server.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 538, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "/opt/odoo/odoo-server/odoo/tools/safe_eval.py", line 376, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'OverflowError'>: "date value out of range" while evaluating
"action = model.with_context(\n                search_default_filter_to_reorder=True,\n                search_default_filter_not_snoozed=True,\n                default_trigger='manual',\n                searchpanel_default_trigger='manual'\n            ).action_open_orderpoints()"

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://biketrax.co.uk/web/assets/1015943-c9d970b/web.assets_backend.min.js:994:163)
    at XMLHttpRequest.<anonymous> (https://biketrax.co.uk/web/assets/1015943-c9d970b/web.assets_backend.min.js:1002:13)

Expected behavior:

Replenishments report run

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by btxluke** [comment]
Further investigation of the “Reordering Rules” stock_warehouse_orderpoint Model, turned up the same error when trying to view:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/api.py", line 989, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 1383

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo-server/odoo/api.py", line 996, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'stock.warehouse.orderpoint(1383,).qty_on_hand'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/api.py", line 989, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 1383

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo-server/odoo/api.py", line 996, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'stock.warehouse.orderpoint(1383,).lead_days_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 462, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/opt/odoo/odoo-server/odoo/models.py", line 5014, in search_read
    result = records.read(fields, **read_kwargs)
  File "/opt/odoo/odoo-server/odoo/models.py", line 2985, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3164, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo-server/odoo/models.py", line 5897, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo-server/odoo/models.py", line 4221, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/opt/odoo/odoo-server/addons/purchase_stock/models/stock.py", line 95, in _compute_qty
    return super()._compute_qty()
  File "/opt/odoo/odoo-server/addons/stock/models/stock_orderpoint.py", line 251, in _compute_qty
    orderpoint_context = orderpoint._get_product_context()
  File "/opt/odoo/odoo-server/addons/stock/models/stock_orderpoint.py", line 315, in _get_product_context
    'to_date': datetime.combine(self.lead_days_date + relativedelta.relativedelta(days=visibility_days), time.max)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo-server/odoo/models.py", line 4221, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/opt/odoo/odoo-server/addons/purchase_stock/models/stock.py", line 99, in _compute_lead_days
    return super()._compute_lead_days()
  File "/opt/odoo/odoo-server/addons/stock/models/stock_orderpoint.py", line 123, in _compute_lead_days
    lead_days_date = fields.Date.today() + relativedelta.relativedelta(days=lead_days)
  File "/opt/odoo/odoo-server/venv/lib/python3.10/site-packages/dateutil/relativedelta.py", line 405, in __radd__
    return self.__add__(other)
  File "/opt/odoo/odoo-server/venv/lib/python3.10/site-packages/dateutil/relativedelta.py", line 387, in __add__
    ret = (other.replace(**repl)
OverflowError: date value out of range

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://www.biketrax.co.uk/web/assets/1017158-0e3ae57/web.assets_backend.min.js:994:163)
    at XMLHttpRequest.<anonymous> (https://www.biketrax.co.uk/web/assets/1017158-0e3ae57/web.assets_backend.min.js:1002:13)

Using PGAdmin, I have determined that these rules are causing the errors:

"id"	"warehouse_id"	"location_id"	"product_id"	"product_category_id"	"group_id"	"company_id"	"route_id"	"create_uid"	"write_uid"	"name"	"trigger"	"snoozed_until"	"product_min_qty"	"product_max_qty"	"qty_multiple"	"qty_to_order"	"active"	"create_date"	"write_date"	"bom_id"	"manufacturing_visibility_days"	"supplier_id"	"vendor_id"	"purchase_visibility_days"
1383	1	8	24811	33		1		1	7	"Replenishment Report"	"manual"	"2023-10-11"	0.00	0.00	0.00	1.00	false	"2023-09-08 11:00:09.662523"	"2023-10-12 09:10:55.414048"		0			0
1384	1	8	24812	33		1		1	7	"Replenishment Report"	"manual"	"2023-10-11"	0.00	0.00	0.00	1.00	false	"2023-09-08 11:00:09.662523"	"2023-10-12 09:12:19.758538"		0			0
1388	1	8	77493	31		1	7	1	7	"Replenishment Report"	"manual"	"2023-10-19"	0.00	0.00	0.00	1.00	false	"2023-09-11 09:56:23.294776"	"2023-10-12 09:13:37.988595"		0			0
1397	1	8	162633	47		1	7	1	7	"Replenishment Report"	"manual"	"2023-10-11"	0.00	0.00	0.00	1.00	false	"2023-09-11 14:06:59.839664"	"2023-10-12 09:15:13.05761"		0			0
1399	1	8	121687	34		1	7	1	7	"Replenishment Report"	"manual"	"2023-10-11"	0.00	0.00	0.00	2.00	false	"2023-09-11 14:41:41.438862"	"2023-10-12 09:19:52.655686"		0			0
1405	1	8	77875	17		1		1	9	"Replenishment Report"	"manual"	"2023-10-14"	0.00	0.00	0.00	1.00	true	"2023-09-14 08:30:00.384919"	"2023-09-14 08:30:25.202558"		0			0
1406	1	8	71647	82		1		1	9	"Replenishment Report"	"manual"	"2023-10-14"	0.00	0.00	0.00	1.00	true	"2023-09-14 08:30:00.384919"	"2023-09-14 08:30:29.45481"		0			0
1407	1	8	71904	38		1		1	9	"Replenishment Report"	"manual"	"2023-10-14"	0.00	0.00	0.00	1.00	true	"2023-09-14 08:30:00.384919"	"2023-09-14 08:30:33.212441"		0			0
1414	1	8	52806	44		1	7	1	9	"Replenishment Report"	"manual"	"2023-10-18"	0.00	0.00	0.00	1.00	true	"2023-09-18 12:58:38.896346"	"2023-09-18 13:10:12.561771"		0			0
1427	1	8	25833	33		1	7	1	7	"Replenishment Report"	"manual"		0.00	0.00	0.00	1.00	false	"2023-09-19 09:56:22.00944"	"2023-09-25 08:41:49.35244"		0			0
1457	1	8	538668	86		1	5	7	1	"OP/00181"	"auto"		5.00	12.00	12.00	0.00	true	"2023-09-26 12:53:34.069036"	"2023-10-11 11:31:39.062709"		0			0
1459	1	8	10542	50		1	7	7	7	"OP/00182"	"manual"		0.00	0.00	0.00	0.00	true	"2023-09-26 14:05:05.37057"	"2023-09-27 13:47:12.390553"		0	192195	47	0
1466	1	8	159620	83		1	5	7	1	"OP/00183"	"auto"		1.00	4.00	4.00	0.00	true	"2023-09-27 15:28:25.026356"	"2023-10-11 11:31:39.062709"		0			0
1471	1	8	479340	44		1	7	1	7	"Replenishment Report"	"manual"		0.00	0.00	0.00	1.00	true	"2023-09-29 06:19:20.41962"	"2023-09-29 06:20:00.903142"		0			0
1472	1	8	420349	1		1	7	1	1	"Replenishment Report"	"auto"		0.00	0.00	0.00	0.00	true	"2023-09-29 06:19:20.41962"	"2023-10-11 11:31:39.062709"		0	231072	47	0
1492	1	8	38625	33		1		1	9	"Replenishment Report"	"manual"		0.00	0.00	0.00	0.00	true	"2023-10-04 13:44:58.478868"	"2023-10-05 11:33:01.317031"		0			0
1494	1	8	71452	51		1	7	1	9	"Replenishment Report"	"manual"		0.00	0.00	0.00	0.00	true	"2023-10-04 13:44:58.478868"	"2023-10-05 11:31:47.980215"		0			0

And this (an example product) seems to be the reason – I can’t immediately see what the error in the product_product model is, but I cannot save edits made to that record either:

"id"	"message_main_attachment_id"	"product_tmpl_id"	"create_uid"	"write_uid"	"default_code"	"barcode"	"combination_indices"	"volume"	"weight"	"active"	"can_image_variant_1024_be_zoomed"	"create_date"	"write_date"	"base_unit_id"	"base_unit_count"	"ebay_quantity_sold"	"ebay_quantity"	"ebay_variant_url"	"ebay_use"	"ebay_fixed_price"
77875		23517		9	"RX100AL"	"8592842176774"	"91334,91336,91338"		0.50	true	false	"2023-01-05 13:13:26.084912"	"2023-07-07 17:11:00.584678"		0		1		false

**Comment by btxluke** [comment]
Field causing the error was `delay` in `product.supplierinfo` which somehow an employee had managed to enter a negative value into.

Can we add protection / rejection for non-positive values here?
