### ISSUE TITLE
Traceback on creating blogpost

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#13829]
Impacted versions:
10.0
Steps to reproduce:
Go to website admin and crate a blogpost
Current behavior:
Traceback on save

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/models.py", line 4663, in search_read
    result = records.read(fields)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/models.py", line 3002, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/models.py", line 5178, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/fields.py", line 860, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/fields.py", line 969, in determine_value
    self.compute_value(recs)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/fields.py", line 924, in compute_value
    self._compute_value(records)
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/fields.py", line 916, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/runbot/extra/runbot/static/build/175617-10-0-eb9c9e/odoo/addons/website_blog/models/website_blog.py", line 93, in _compute_ranking
    age = datetime.now() - fields.Datetime.from_string(blog_post.post_date)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ploegvde,

Thanks a lot for your report! I've just tested this and this is indeed a bug:
![image](https://cloud.githubusercontent.com/assets/6352350/19426711/2b185024-943f-11e6-8861-6f444f90c9cf.png)
Either post_date has to be required or there should be an if statement around the calculation of the dates.
@JKE-be looks like something for you.

Regards,
Yenthe

**Comment by JKE-be** [comment]
Hello @ploegvde , thanks for the reporting.
I will take a look asap...

@Yenthe666  "Either post_date has to be required" => no ! it is a computed field based on create_date ;)

**Comment by Yenthe666** [comment]
Woop I didn't notice that it was a computed.  Ignore that one then 😉

**Comment by JakubSs** [comment]
Hey,
I have the same issue - I checked and edits from that commit are there.

**Comment by JKE-be** [comment]
Hello @JakubSs 

Maybe you already have old blogs before this commit ?

**Comment by JakubSs** [comment]
Nope, it was fresh install and new database few days ago...

**Comment by JKE-be** [comment]
@JakubSs 

no... it seems to be another bug that is not linked to the original issue here.
Please open a new issue... and ping me on it

**Comment by JakubSs** [comment]
all right

**Comment by collex100** [comment]
How did you decide this?
I have the same problem on a clean installation:
[#14753 ](https://github.com/odoo/odoo/issues/14753)

**Comment by JakubSs** [comment]
@collex100 hi, 
problem is with babel... use this commands, reboot server and it should work. I was working on solution for two days and with help od guys here I came up with:

` yum install python-pip -y
pip install --upgrade pip pytz babel`

it solved the problem for myself on centos 7.2... I think it worth to publish it more closely on odoo 10 install guide for redhat/centos guys...

Hope it helps you, too.

**Comment by collex100** [comment]
Thank you very much!!!

**Comment by JakubSs** [comment]
@collex100 so it works now?

**Comment by collex100** [comment]
Yes it's!

**Comment by JakubSs** [comment]
glad to hear 👍
