### ISSUE TITLE
"Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'" removing Calendar from Dashboard

### ISSUE THREAD

**Issue by astrazzari72** [odoo/odoo#13858]
Impacted versions: 9.0c-20160617 (Edizione Community)

Steps to reproduce:
Add Calendar to Dashboard. Go to Dashboard. Remove the Calendar widget from Dashboard with the x button. Than you have the error.

Current behavior:
The  error described.

Expected behavior:
No error.

Video/Screenshot link (optional):
![odoo dash calendarremoveerror](https://cloud.githubusercontent.com/assets/5904427/19469755/e9add530-951c-11e6-9c7a-ab22c66e3731.jpg)

**Comment by JKE-be** [comment]
@ged-odoo @aab-odoo 

```
Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'
http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery/jquery.js:247
Traceback:
Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'
    at Function.error (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery/jquery.js:247:23)
    at HTMLInputElement.<anonymous> (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery.ui/jquery-ui.js:507:15)
    at Function.each (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery/jquery.js:383:58)
    at jQuery.each (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery/jquery.js:136:31)
    at jQuery.$.fn.(anonymous function) [as autocomplete] (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery.ui/jquery-ui.js:499:9)
    at OdooClass.<anonymous> (http://175993-9-0-327f88.runbot10.odoo.com/web/static/src/js/views/form_relational_widgets.js:88:79)
    at OdooClass.trigger (http://175993-9-0-327f88.runbot10.odoo.com/web/static/src/js/framework/mixins.js:222:31)
    at OdooClass.trigger (http://175993-9-0-327f88.runbot10.odoo.com/web/static/src/js/framework/mixins.js:272:42)
    at HTMLHtmlElement.<anonymous> (http://175993-9-0-327f88.runbot10.odoo.com/web/static/src/js/framework/core.js:31:18)
    at HTMLHtmlElement.dispatch (http://175993-9-0-327f88.runbot10.odoo.com/web/static/lib/jquery/jquery.js:4641:58)
```
