### ISSUE TITLE
Loading of demo data and running tests is broken

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#13933]
https://github.com/odoo/odoo/commit/ecb6055b0f208001894ae5b05aef01ee367a9099 breaks loading demo data and running tests. When initializing a database with demo data, as of this change the demo data of the dependent modules is no longer loading.

Impacted versions:
8.0 and later.

Steps to reproduce:
createdb freshdb; openerp-server -i account -d freshdb

Current behavior:

```
2016-10-21 08:59:41,798 19512 INFO freshdb openerp.modules.loading: loading account/demo/account_demo.xml
2016-10-21 08:59:42,266 19512 CRITICAL freshdb openerp.service.server: Failed to initialize database `freshdb`.
Traceback (most recent call last):
  File "/home/buildout/freshdb/parts/odoo/openerp/service/server.py", line 937, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/buildout/freshdb/parts/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/buildout/freshdb/parts/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/buildout/freshdb/parts/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/buildout/freshdb/parts/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/buildout/freshdb/parts/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/buildout/freshdb/parts/odoo/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/buildout/freshdb/parts/odoo/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/buildout/freshdb/parts/odoo/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/buildout/freshdb/parts/odoo/openerp/tools/convert.py", line 759, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/buildout/freshdb/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/buildout/freshdb/parts/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/buildout/freshdb/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/buildout/freshdb/parts/odoo/addons/auth_signup/res_users.py", line 301, in create
    user_id = super(res_users, self).create(cr, uid, values, context=context)
  File "/home/buildout/freshdb/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/buildout/freshdb/parts/odoo/addons/mail/res_users.py", line 75, in create
    raise openerp.exceptions.RedirectWarning(msg, action_id, _('Go to the configuration panel'))
```

The crash is caused by missing demo data from the base module that the demo data of the account module depends on.

Expected behavior:
All demo data is loaded for all the modules that are installed in this step.

**Comment by Yenthe666** [comment]
@KangOl the commit is made by you, can you give feedback?

**Comment by StefanRijnhart** [comment]
The problematic behaviour was caused in combination with the option without_demo = True which I have had in my config forever. This to me was the most mysterious Odoo option, and it still is ;-). Setting it to False I get the desired behaviour.
