### ISSUE TITLE
[9.0] acccount: A commit is causing errors while creating invoices 

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#13943]
**Impacted versions:**
9.0

**Steps to reproduce:**
Creating an invoice with taxes after commit https://github.com/odoo/odoo/commit/327f88dfcee9a9b9855c0e1300e6db5797334f67 crashes.

**Current behavior:**
```
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/models.py", line 6071, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/src/odoo/openerp/models.py", line 5928, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_invoice.py", line 447, in _onchange_invoice_line_ids
    taxes_grouped = self.get_taxes_values()
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_invoice.py", line 572, in get_taxes_values
    val = self._prepare_tax_line_vals(line, tax)
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_invoice.py", line 557, in _prepare_tax_line_vals
    'base': tax['base'],
KeyError: 'base'
```

**Expected behavior:**
Create the invoice

**Comment by wtaferner** [comment]
@gustavovalverde 
Can you reproduce it on Runbot? Unfortunately I can't. It seems that you use a module where the ```_compute_all``` has been overwritten or not properly inherited as the base has been defined in the same commit [here](https://github.com/odoo/odoo/blob/327f88dfcee9a9b9855c0e1300e6db5797334f67/addons/account/models/account.py#L730).

**Comment by gustavovalverde** [comment]
@wtaferner I'll check in a clean install and then test while installing the plugins that affect the accounting module. I'll let you know.

**Comment by gustavovalverde** [comment]
Closing this issue for #FalseAlarm. Another plugin was actually overwritting `compute_all`.
