### ISSUE TITLE
[8.0] hw_ecspos: throw an error "cannot set daemon status of active thread"

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#13942]
Impacted versions:
[8.0] PosBox v14

Steps to reproduce:
Nothing especial, after 4 days working with POSBOX, service ECS/POS stop working

Current behavior:
- POS printer connection is Red
- Tickets are not printed
- Posbox odoo-log show the following error:

```
2016-10-22 13:27:16,264 757 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/pi/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/pi/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/home/pi/odoo/openerp/http.py", line 317, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/pi/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/home/pi/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 122, in status_json
    return self.get_status()
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 38, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 114, in get_status
    self.push_task('status')
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 191, in push_task
    self.lockedstart()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 100, in lockedstart
    self.daemon = True
  File "/usr/lib/python2.7/threading.py", line 1029, in daemon
    raise RuntimeError("cannot set daemon status of active thread");
RuntimeError: cannot set daemon status of active thread
```

Expected behavior:
- POS printer connection should be Green
- Tickets should be printed
- No erron on Odoo log

Video/Screenshot link (optional):
- Currently printer connection is in red, but connected via ssh to the posbox and i do a ping to server all packets are transmitted
  ![4865643483832602472-account_id 1](https://cloud.githubusercontent.com/assets/5335402/19619941/ad25d360-9837-11e6-899b-a4133c15f6ee.jpg)

![pantallazo-2016-10-22 09-18-03](https://cloud.githubusercontent.com/assets/5335402/19619972/94524278-9838-11e6-875a-7c30f4f3c191.png)
- Trying to print a ticket

![3988906456624526075-account_id 1](https://cloud.githubusercontent.com/assets/5335402/19619988/febe8bf8-9838-11e6-88dd-854d4805ac96.jpg)

**Comment by Yenthe666** [comment]
Hi @suniagajose ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
