### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by karimsoft** [odoo/odoo#139481]
hi, how i can fix the erorr
Impacted versions:
Ver Odoo 15
Steps to reproduce:

        common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(url))
        
        uid = 0
        has_error=False
        try:
            uid = common.authenticate(db,username,password, {})
            logger.info(f"step={'03'}")
        except Exception as ex: 
            has_error=True
            logger.info(f"step={'03 Error'}")
            # logger.info(f"ex={ex}")
        finally: 
            common.rollback
            del common

        if has_error:
            return "Has Error"

        models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))
        
        # order headers
        domain = [("session_id.config_id", "=", "Madenity")]
        
        fields = ["name", "date_order"]
        
        try:   **### # next line get error**
            order_headers = models.execute_kw(db, uid, password,'pos.order', 'search_read', [domain, fields])
            logger.info(f"step={'07'}")
        except Exception as ex: 
            del models
            has_error=True
            logger.info(f"step={'07 Error'}")
            logger.info(f"ex={ex}")
            
        if has_error:
            return "Has Error 1"

error:
<Fault 1: 'Traceback (most recent call last):\n  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 93, in xmlrpc_2\n    response = self._xmlrpc(service)\n  File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 73, in _xmlrpc\n    result = dispatch_rpc(service, method, params)\n  File "/home/odoo/src/odoo/odoo/http.py", line 141, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/home/odoo/src/odoo/odoo/service/model.py", line 41, in dispatch\n    res = fn(db, uid, *params)\nTypeError: execute_kw() missing 1 required positional argument: \'args\'\n'>
2023-10-23 15:27:23,513 4240 INFO main werkzeug: 127.0.0.1 - - [23/Oct/2023 15:27:23] "GET /api_test/pos_read HTTP/1.1" 200 - 1 0.001 9.792
2023-10-23 15:29:25,420 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `Mail: Email Queue Manager`.
2023-10-23 15:29:38,114 4240 INFO main odoo.addons.base.models.ir_cron: Job `Mail: Email Queue Manager` done.
2023-10-23 15:30:26,390 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `payment: post-process transactions`.
2023-10-23 15:30:26,452 4240 INFO main odoo.addons.base.models.ir_cron: Job `payment: post-process transactions` done.
2023-10-23 15:30:26,613 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `SMS:
SMS Queue Manager`.
2023-10-23 15:30:26,662 4240 INFO main odoo.addons.base.models.ir_cron: Job `SMS: SMS Queue Manager` done.
2023-10-23 15:30:26,801 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `Partner Autocomplete : Sync with remote DB`.
2023-10-23 15:30:26,857 4240 INFO main odoo.addons.base.models.ir_cron: Job `Partner Autocomplete : Sync with remote DB` done.
2023-10-23 15:30:26,985 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `Snailmail: process letters queue`.
2023-10-23 15:30:27,060 4240 INFO main odoo.addons.base.models.ir_cron: Job `Snailmail: process letters queue` done.
2023-10-23 15:40:37,335 4240 INFO main odoo.addons.base.models.ir_cron: Starting job `payment: post-process transactions`.
2023-10-23 15:40:37,382 4240 INFO main odoo.addons.base.models.ir_cron: Job `payment: post-process transactions` done.
2023-10-23 15:46:49,500 4240 INFO ? odoo.service.server: Initiating shutdown
2023-10-23 15:46:49,500 4240 INFO ? odoo.service.server: Hit CTRL-C again or send a second
signal to force the shutdown.
2023-10-23 15:46:49,915 4240 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 6 connections

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @karimsoft 
Could you provide the steps to reproduce the issue?
Thanks

**Comment by karimsoft** [comment]
thank you i am update the code
