### ISSUE TITLE
The synchronize term doesn't work

### ISSUE THREAD

**Issue by Chugarbert** [odoo/odoo#13957]
Impacted versions: 8.0

Steps to reproduce: go to configuration/translation/application terms/Synchronize terms

Current behavior:

the system try to synchronize the terms, but after 5 min send my this windows
```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/wizard/base_update_translations.py", line 47, in act_update
    tools.trans_export(this.lang, ['all'], buf, 'csv', cr)
  File "/opt/odoo/openerp/tools/translate.py", line 524, in trans_export
    translations = trans_generate(lang, modules, cr)
  File "/opt/odoo/openerp/tools/translate.py", line 811, in trans_generate
    push_translation(module, 'model', name, xml_name, encode(term))
  File "/opt/odoo/openerp/tools/translate.py", line 687, in push_translation
    if not source or len(source.strip()) <= 1:
AttributeError: 'bool' object has no attribute 'strip'
```
Expected behavior: synchronize the terms

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Chugarbert,

Thank you for your report but this is no longer present in Odoo.
Odoo 8 is no longer supported either, so I'm closing this report.

Regards,
Yenthe
