### ISSUE TITLE
Can not input Journal Voucher, comes out with :

### ISSUE THREAD

**Issue by ispottahiti** [odoo/odoo#13982]
Impacted versions:

Steps to reproduce:Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo/odoo/models.py", line 1108, in default_get
    defaults[name] = field.default(self)
  File "/opt/odoo/odoo/addons/account_voucher/models/account_voucher.py", line 48, in <lambda>
    string='Currency', readonly=True, required=True, default=lambda self: self._get_currency())
  File "/opt/odoo/odoo/addons/account_voucher/models/account_voucher.py", line 86, in _get_currency
    if journal.currency_id:
  File "/opt/odoo/odoo/odoo/fields.py", line 860, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 962, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odoo/odoo/models.py", line 3051, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo/odoo/odoo/models.py", line 2991, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo/odoo/models.py", line 3119, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "Caisse (XPF)"
LINE 2: ...                   WHERE "account_journal".id IN ('Caisse (X...

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ispottahiti,

Sorry but this bug report contains too little information.
I'm closing it as there are no steps on how to reproduce it or what you did. Even the Odoo version is missing in your description.
Feel free to create a new bug report, or edit this one, if you can still reproduce it.

Regards,
Yenthe
