### ISSUE TITLE
keyerror:none

### ISSUE THREAD

**Issue by kiralorelei** [odoo/odoo#140241]
Impacted versions:odoo-16

Steps to reproduce:install/upgrade my model

Current behavior:RPC_ERROR   Odoo Server Error

Expected behavior:install successfully

I don't know what happened,each model seems to be alright like i check the issue list, and i found an issue error looked just like mine,which is his model named like "_name='sale.order', _inherit='sale.order'".
However,the solution didn't work in the same way ,i inherit sale.order as well,but i don't _name it .

log:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\base\models\ir_module.py", line 456, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\addons\base\models\ir_module.py", line 580, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\loading.py", line 207, in load_module_graph
    registry.setup_models(cr)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\registry.py", line 297, in setup_models
    model._setup_fields()
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\models.py", line 2810, in _setup_fields
    field.setup(self)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\fields.py", line 536, in setup
    self.setup_related(model)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\fields.py", line 599, in setup_related
    field = model.pool[model_name]._fields.get(name)
  File "C:\Users\wqy\Desktop\odoo16\server\odoo\modules\registry.py", line 190, in __getitem__
    return self.models[model_name]
KeyError: None

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/124-19d759d/web.assets_backend.min.js:985:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/124-19d759d/web.assets_backend.min.js:993:13)

**Comment by gdgellatly** [comment]
If I had to guess your module doesn't depend on sale so it isn't loaded at the time you inherit.

**Comment by vava-odoo** [comment]
Hi @kiralorelei 
Was the inheritance the issue?
Closing this as not related to standard modules.
Cheers
