### ISSUE TITLE
Error after installing modules

### ISSUE THREAD

**Issue by mohamedlaminelalmi** [odoo/odoo#140235]
**Impacted versions:**
V17

**Steps to reproduce:**
After installing modules

**Current behavior:**
Traceback:
UncaughtPromiseError > TypeError
Promesse non interceptée > Cannot read properties of undefined (reading 'apply')
TypeError: Cannot read properties of undefined (reading 'apply')
    at PurchaseAdditionalTourSteps._get_purchase_stock_steps (http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:18049:484)
    at Object.steps (http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:16881:3543)
    at get steps [as steps] (http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:10973:1543)
    at convertToMacro (http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:10978:236)
    at startTour (http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:10988:442)
    at http://localhost:8069/web/assets/3952abf/web.assets_web.min.js:10994:344
    
![image](https://github.com/odoo/odoo/assets/28647595/7ae5509a-af97-4145-93d2-dd7eca587b01)

**Comment by kalungia** [comment]
Sometimes this happens if some dependencies are missing, make sure to run requirements.txt

**Comment by mohamedlaminelalmi** [comment]
@kalungia @vava-odoo 
I think the issue is solved.
I'll close this one.
Thank you.
