### ISSUE TITLE
Getting Error during clicking on Technical / Show Full Accounting Features Group

### ISSUE THREAD

**Issue by rohit-webkul** [odoo/odoo#140242]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web/models/models.py", line 144, in web_read
    values[field_name] = sorted(values[field_name], key=order_key.__getitem__)
KeyError: 135

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8051/web/assets/470-f9a18c2/web.assets_web.min.js:916:101)
    at App.handleError (http://localhost:8051/web/assets/470-f9a18c2/web.assets_web.min.js:1543:29)
    at ComponentNode.initiateRender (http://localhost:8051/web/assets/470-f9a18c2/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8051/web/assets/470-f9a18c2/web.assets_web.min.js:2992:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8051/web/assets/470-f9a18c2/web.assets_web.min.js:2996:13)

**Comment by vava-odoo** [comment]
Hi @rohit-webkul 
Could you provide steps to reproduce?
Thanks
