### ISSUE TITLE
Traceback: Translation Error

### ISSUE THREAD

**Issue by mohamedlaminelalmi** [odoo/odoo#140236]
**Impacted versions:**
17.0

**Steps to reproduce:**
Accessing login page or Website

**Current behavior:**
Traceback
UncaughtPromiseError
Promesse non interceptée > translation error
Error: translation error
    at LazyTranslatedString.valueOf (http://localhost:8069/web/assets/1/c940910/web.assets_frontend_lazy.min.js:4642:56)
    at LazyTranslatedString.toString (http://localhost:8069/web/assets/1/c940910/web.assets_frontend_lazy.min.js:4643:24)
    at new Error (<anonymous>)
    at new UncaughtError (http://localhost:8069/web/assets/1/c940910/web.assets_frontend_lazy.min.js:4321:655)
    at new UncaughtPromiseError (http://localhost:8069/web/assets/1/c940910/web.assets_frontend_lazy.min.js:4323:152)
    at http://localhost:8069/web/assets/1/c940910/web.assets_frontend_lazy.min.js:4331:157
    
    
![image](https://github.com/odoo/odoo/assets/28647595/c8fa07df-08f9-475c-a740-6cb20847c2c7)

**Comment by stagenie** [comment]
Hello Mohammed, 
I had the same problem, in my case i restart the sevice of odoo then restart also the Server ( Ubuntu 22 in my case) and the problem is solved.
Hope this be helpful for you also

**Comment by stagenie** [comment]
Hello Mohammed, 
Try to restart the service odoo 17and then the system (Ubuntu 22.04 in my case) .
Hope this helping you

**Comment by sakesun** [comment]
I think this is the same issue that I opened #140518
The solution is in the detail of that issue.

**Comment by sakesun** [comment]
PR #141211 should fix this issue.

**Comment by mohamedlaminelalmi** [comment]
@sakesun 
Thank you. I'll close this one and wait for the PR #141211 to be merged.
Thank you!
