### ISSUE TITLE
500: Internal Server Error unsubscribe link

### ISSUE THREAD

**Issue by ngarner-at-goxaas-dot-com** [odoo/odoo#140602]
Impacted versions: 16

Steps to reproduce:
Create a marketing email, add the footer box with unsubscribe or use a default template with the unsubscribe already inside it
Current behavior:
500: Internal Server Error 

Expected behavior:
a unsubscribe webpage

Video/Screenshot link (optional):
2023-10-31 18:24:50,283 18 ERROR xxxxxxxxx-odoosh-internaldeployment-main-7114722 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 2003, in __call__
    response = request._serve_db()
  File "/home/odoo/src/odoo/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1730, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/mass_mailing/controllers/main.py", line 42, in mailing
    subscription_list_ids = contacts.mapped('subscription_list_ids').filtered('active')
  File "/home/odoo/src/odoo/odoo/models.py", line 5425, in filtered
    self.mapped(name)
  File "/home/odoo/src/odoo/odoo/models.py", line 5401, in mapped
    recs = recs._fields[name].mapped(recs)
KeyError: 'active'

Support ticket number submitted via odoo.com/help (optional):
Ticket opened, and support said this was a known issue but there is no public posting about it. I am making a post about it so that if you have the same issue you can find it when searching online.

**Comment by LocallyCloud** [comment]
Same issue here, exact same error output too.

I've tried manually reinstalling, and installing via install scripts, etc. Exact same error and output.
