### ISSUE TITLE
Erro 404 Not Found after updating.

### ISSUE THREAD

**Issue by tiniba** [odoo/odoo#14159]
I'm new using linux and odoo, did all based installation "nightly.odoo.com" worked perfectly, but when updating the system (apt update apt and upgrade), the system does not work anymore!

This is the second system coming down, after an update, where am I going wrong?

Since now, I appreciate the help.

following the log below:

2016-11-04 23:52:47,455 45306 INFO ? openerp: OpenERP version 9.0c-20161028
2016-11-04 23:52:47,457 45306 INFO ? openerp: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/9.0', u'/usr/lib/python2.7/dist-packages/openerp/addons']
2016-11-04 23:52:47,458 45306 INFO ? openerp: database: odoo@default:default
2016-11-04 23:52:47,482 45306 WARNING ? openerp.modules.module: module None: module not found
2016-11-04 23:52:47,483 45306 CRITICAL ? openerp.modules.module: Couldn't load module None
2016-11-04 23:52:47,498 45306 CRITICAL ? openerp.modules.module: No module named None
2016-11-04 23:52:47,499 45306 ERROR ? openerp.service.server: Failed to load server-wide module `None`.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 833, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 331, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 60, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named None

**Comment by JKE-be** [comment]
Hello

Pull the last version ... it has been fixed last week... so, It should works...
Or replace None by web,web_kanban for server_wide_module from your config

**Comment by tiniba** [comment]
It's Working! Ty

If not abuse, could tell me how to improve the system speed? I am 32 threades to use.
Another question, how can I restore a backup on another computer always get the error "Database restore error: Postgres subprocess ('/usr/bin/pg_restore', u'--dbname=PIS_BK', '--no-owner', '/tmp/tmpzrIlG3') error 1".

thank you

**Comment by JKE-be** [comment]
hi @tiniba 

The error is too generic to help you... 
Maybe you have other module that require to change role. eg: https://github.com/odoo/odoo/issues/10763
You will find more help on help.odoo.com if you give more details about your error (take a look in your log)

About the setup, the best approach is to take a look in the documentation (and make fine tuning after according to your usage if required...):  https://www.odoo.com/documentation/9.0/setup/deploy.html#id5
