### ISSUE TITLE
Error in Res_Partner

### ISSUE THREAD

**Issue by jwcaceres78** [odoo/odoo#141612]
Impacted versions: 17 (language=ES_pe, localization = PE)

Steps to reproduce: In fresh Instalation try to create new res_partner

Current behavior: Cannot create new res_partner

Expected behavior: create new partner

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

'''
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:916:101)
    at App.handleError (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1543:29)
    at Fiber._render (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:941:19)
    at Fiber.render (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1007:47)

Caused by: EvalError: Can not evaluate python expression: (bool(no is_company))
Error: Name 'no' is not defined
    at evaluateExpr (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:3023:54)
    at FormRenderer.evaluateBooleanExpr (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:3026:8)
    at FormRenderer.slot8 (eval at compile (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1501:374), <anonymous>:177:26)
    at callSlot (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1109:25)
    at InnerGroup.template (eval at compile (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1501:374), <anonymous>:62:42)
    at Fiber._render (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:940:96)
    at Fiber.render (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (http://54.234.178.137/web/assets/0188510/web.assets_web.min.js:1007:47)
'''

**Comment by andru1236** [comment]
I have the same error, probably our build is no updated

**Comment by vava-odoo** [comment]
Hi @jwcaceres78  
Thanks for reporting. It will be fixed by https://github.com/odoo/odoo/pull/141704 very soon.
Cheers
