### ISSUE TITLE
Error When Trying to Open / Click Employee Card While The Employee Is Already Checked In 

### ISSUE THREAD

**Issue by GesangPJ** [odoo/odoo#141677]
Impacted versions: v17.0 CE and Enterprise

Steps to reproduce: 
1. Sign In
2. Check In
3. Go To Employees
4. Click Employee Card of the current user that sign in
5. Odoo Server Error

The Only step to solve the error is to : 
1.  _**Check Out**_  
2.  _**Click the employee card again**_
3. Now it's working / not error 

If this bug is intentional or to prevent data mismatch, there's should be an error handling like a message box "Pelase Check Out to Modify / see Employee Data".

Error also happening when trying to open other Employee Data that the employee is already Checked In, and to solve it is same like before, check out -> then click the employee card to show the data, seems like this kind of error is caused by attendance module.

I'm not using any additional third party module or apps, you can even try to reproduce it in Odoo Runbot.

Current behavior:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/web/models/models.py", line 86, in web_read
    values_list: List[Dict] = self.read(fields_to_read, load=None)
  File "/data/build/odoo/odoo/models.py", line 3521, in read
    return self._read_format(fnames=fields, load=load)
  File "/data/build/odoo/odoo/models.py", line 3732, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/data/build/odoo/odoo/models.py", line 6570, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1205, in __get__
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1383, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/data/build/odoo/odoo/models.py", line 4848, in _compute_field_value
    fields.determine(field.compute, self)
  File "/data/build/odoo/odoo/fields.py", line 101, in determine
    return needle(*args)
  File "/data/build/odoo/addons/hr_attendance/models/hr_employee.py", line 103, in _compute_hours_last_month
    for att in employee.attendance_ids.filtered(
  File "/data/build/odoo/odoo/models.py", line 6082, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/odoo/models.py", line 6082, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/addons/hr_attendance/models/hr_employee.py", line 104, in <lambda>
    lambda att: att.check_in >= start_naive and att.check_out <= end_naive
TypeError: '<=' not supported between instances of 'bool' and 'datetime.datetime'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://53546335-17-0-all.runbot168.odoo.com/web/assets/b6ad5a5/web.assets_web_dark.min.js:916:101)
    at App.handleError (https://53546335-17-0-all.runbot168.odoo.com/web/assets/b6ad5a5/web.assets_web_dark.min.js:1543:29)
    at ComponentNode.initiateRender (https://53546335-17-0-all.runbot168.odoo.com/web/assets/b6ad5a5/web.assets_web_dark.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://53546335-17-0-all.runbot168.odoo.com/web/assets/b6ad5a5/web.assets_web_dark.min.js:2866:163)
    at XMLHttpRequest.<anonymous> (https://53546335-17-0-all.runbot168.odoo.com/web/assets/b6ad5a5/web.assets_web_dark.min.js:2870:13)
```

Expected behavior:

`Not Error`

Video/Screenshot link (optional):

Enterprise Edition :
![odoo enterprise-employee error](https://github.com/odoo/odoo/assets/26625652/884c3071-066b-419a-96b9-9282605d1c18)

Community Edition : 
![odoo communite edition-error employee data](https://github.com/odoo/odoo/assets/26625652/4f647177-38ca-4738-970e-6d44a0dd6f3d)

**Comment by schreeedi** [comment]
I can confirm. This should be fixed asap.

**Comment by sofiagvaladze** [comment]
Has been fixed in https://github.com/odoo/odoo/pull/141673 and will be forwardported to later versions, including 17. Thanks!
