### ISSUE TITLE
Error in Res_Partner

### ISSUE THREAD

**Issue by juanmanuelnunez** [odoo/odoo#141739]
Impacted versions: 17 (language=ES_mx, localization = MX)

Steps to reproduce: In fresh Instalation try to create new res_partner

Current behavior: Cannot create new res_partner

Expected behavior: create new partner

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

'''
UncaughtPromiseError > OwlError
Promesa no controlada > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:916:101)
    at App.handleError (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1543:29)
    at Fiber._render (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:941:19)
    at Fiber.render (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1007:47)

Caused by: EvalError: Can not evaluate python expression: (bool(no is_company))
Error: Name 'no' is not defined
    at evaluateExpr (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:3023:54)
    at FormRenderer.evaluateBooleanExpr (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:3026:8)
    at FormRenderer.slot22 (eval at compile (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1501:374), <anonymous>:313:26)
    at callSlot (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1109:25)
    at InnerGroup.template (eval at compile (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1501:374), <anonymous>:62:42)
    at Fiber._render (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:940:96)
    at Fiber.render (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (https://brescahort-odoo.odoo.com/web/assets/d154101/web.assets_web.min.js:1007:47)
'''

**Comment by vava-odoo** [comment]
Hello @juanmanuelnunez 
Thanks for reporting. This has been already fixed with https://github.com/odoo/odoo/pull/141704.
Your PR doesn't solve the problem. The es_MX.po file hasn't changed in 6 months, so it is clearly outdated. The first line is always coming from the pot file (if it is up to date) and is never changed in a po file.
Cheers.
