### ISSUE TITLE
when add button in article odoo 17

### ISSUE THREAD

**Issue by mohasem2020** [odoo/odoo#141748]
Impacted versions:17

Steps to reproduce: in Knowledge app when add /button

this error raise up ( Error: node.oid can not be falsy.
    at serializeNode (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:1103:292)
    at serializeNode (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:1105:165)
    at serializeNode (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:1105:165)
    at OdooEditor.serializeNode (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:648:62)
    at https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:731:234
    at Array.map (<anonymous>)
    at OdooEditor._historyGetSnapshotStep (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:731:180)
    at OdooEditor._historyMakeSnapshot (https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:732:194)
    at https://53610918-17-0-base.runbot185.odoo.com/web/assets/c9f4d7c/web_editor.backend_assets_wysiwyg.min.js:619:5929 )

**Comment by Goaman** [comment]
@mohasem2020 Do you still have the problem ?
I can't reproduce it on my ends.
If you can reproduce it, can you provide more detailed steps to try reproducing it?

**Comment by michaelhofer-slg** [comment]
We see the same issue with Odoo 17 when we leave a `project.task` form view open for a while:

```
Error: node.oid can not be falsy.
    serializeNode@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:1111:292
    serializeNode@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:1113:165
    serializeNode@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:1113:165
    serializeNode@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:656:62
    _historyGetSnapshotStep/<.mutations<@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:739:234
    _historyGetSnapshotStep@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:739:180
    _historyMakeSnapshot@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:740:194
    OdooEditor/this._snapshotInterval<@https://www.domain.com/web/assets/243130a/web_editor.backend_assets_wysiwyg.min.js:627:5929
```

I will need to investigate further, but so far I can only reproduce it, when the task description contains a link.

**Comment by Goaman** [comment]
@michaelhofer-slg A PR is on its way https://github.com/odoo/odoo/pull/142049
