### ISSUE TITLE
Odoo 17 translate error

### ISSUE THREAD

**Issue by trincm** [odoo/odoo#141742]
Impacted versions: odoo 17

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): UncaughtPromiseError
Không thể bắt lỗi dự kiến > translation error
Error: translation error
    at LazyTranslatedString.valueOf (https://beta.alittlelove.vn/web/assets/1/92eb4e3/web.assets_frontend_lazy.min.js:4481:56)
    at LazyTranslatedString.toString (https://beta.alittlelove.vn/web/assets/1/92eb4e3/web.assets_frontend_lazy.min.js:4482:24)
    at new Error (<anonymous>)
    at new UncaughtError (https://beta.alittlelove.vn/web/assets/1/92eb4e3/web.assets_frontend_lazy.min.js:4160:655)
    at new UncaughtPromiseError (https://beta.alittlelove.vn/web/assets/1/92eb4e3/web.assets_frontend_lazy.min.js:4162:152)
    at https://beta.alittlelove.vn/web/assets/1/92eb4e3/web.assets_frontend_lazy.min.js:4170:157

UncaughtPromiseError > translation error
Error: translation error

**Comment by frankofno** [comment]
Had the same error message. Looks like a website theme issue. Since I was still in testing phase, I just uninstalled the website / app within odoo. Error is no longer showing up. 
I used the Design Theme on the website. Guess not all and everything is updated in that theme.

**Comment by alexis-vannot** [comment]
Same issue with Docker : image: odoo:17.0
