### ISSUE TITLE
Create customer from POS

### ISSUE THREAD

**Issue by jwcaceres78** [odoo/odoo#141804]
Impacted versions: 17.00 (localization PE, language = ES_pe)

Steps to reproduce: Install Point of Sale module in fresh odoo 17.00

Current behavior: error creating customer

Expected behavior: customer created succesfully

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

this is the message when I try to create a new customer from point_of_sale module in fresh instalation of odoo 17.00
'''
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6579:163)
    at XMLHttpRequest.<anonymous> (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6583:13)
'''

**Comment by jwcaceres78** [comment]
Is there any update for this?

**Comment by vava-odoo** [comment]
Hi @jwcaceres78 
Looks very similar to https://github.com/odoo/odoo/issues/141697
You should try updating the es_419 translations. It is the standard base for the LATAM locales.
It should fix the problem.
Could you confirm?
Cheers

**Comment by jwcaceres78** [comment]
No, this is another issue, in this case the error is in **Point Of Sale** module

**Comment by vava-odoo** [comment]
Yes, but creating a customer/partner is a standard action, so it inherits from the problematic base view.
If it does not solve, could you provide the full error?
Cheers

**Comment by jwcaceres78** [comment]
I posted the error in issue:

```
RPC_ERROR: Odoo Server Error
at makeErrorFromResponse (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6579:163)
at XMLHttpRequest. (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6583:13)
```

**Comment by vava-odoo** [comment]
I just tried on [runbot.odoo.com](url), and couldn't reproduce... Please try there and if you are able to reproduce, add all the steps.

**Comment by jwcaceres78** [comment]
The issue is when I create a new customer with *VAT ID* look at this

https://youtu.be/AD7Fel8o8bs

**Comment by jwcaceres78** [comment]
Have you any update about this issue?
