### ISSUE TITLE
[10.0] note: cannot share multiple followers with Send Mail field checked

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#14199]
Impacted versions: 10.0

Steps to reproduce:

1. Create a note. Scroll down to OpenChatter to Add followers
2. Add at least 2 followers while keeping Send Mail field being checked
3. Press Add Followers button to see an error message

Current behavior:
No one is added as a follower while an error message appears as below:
`Traceback (most recent call last):
  File "/path/to/odoo10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/path/to/odoo10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/path/to/odoo10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/path/to/odoo10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/path/to/odoo10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/path/to/odoo10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/path/to/odoo10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/path/to/odoo10/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/path/to/odoo10/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/path/to/odoo10/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/path/to/odoo10/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/path/to/odoo10/addons/mail/wizard/invite.py", line 63, in add_followers
    new_partners.with_context(auto_delete=True)._notify(message, force_send=True, send_after_commit=False, user_signature=True)
  File "/path/to/odoo10/addons/mail/models/res_partner.py", line 156, in _notify
    ('notify_email', '!=', 'none')])._notify_by_email(message, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/path/to/odoo10/addons/mail/models/res_partner.py", line 186, in _notify_by_email
    recipients = self.env[message.model].browse(message.res_id)._message_notification_recipients(message, self)
  File "/path/to/odoo10/addons/mail/models/mail_thread.py", line 690, in _message_notification_recipients
    groups = self._notification_recipients(message, default_groups)
  File "/path/to/odoo10/addons/note/models/note.py", line 129, in _notification_recipients
    groups['user']['actions'] = [{'url': new_action, 'title': _('New Note')}]
TypeError: list indices must be integers, not str`

Expected behavior:
There should be no error message. And followers must be added.

**Comment by W360S** [comment]
i have the same error plz help
after i create note & i want to share the note to my staff follow but cannot share, it show up error message
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/wizard/invite.py", line 63, in add_followers
    new_partners.with_context(auto_delete=True)._notify(message, force_send=True, send_after_commit=False, user_signature=True)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/res_partner.py", line 156, in _notify
    ('notify_email', '!=', 'none')])._notify_by_email(message, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/res_partner.py", line 186, in _notify_by_email
    recipients = self.env[message.model].browse(message.res_id)._message_notification_recipients(message, self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 690, in _message_notification_recipients
    groups = self._notification_recipients(message, default_groups)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/note/models/note.py", line 129, in _notification_recipients
    groups['user']['actions'] = [{'url': new_action, 'title': _('New Note')}]
TypeError: list indices must be integers, not str

**Comment by kurtghekiere** [comment]
I have the same issue when only selecting 1 addressee : 

 File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/wizard/invite.py", line 63, in add_followers
    new_partners.with_context(auto_delete=True)._notify(message, force_send=True, send_after_commit=False, user_signature=True)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/res_partner.py", line 156, in _notify
    ('notify_email', '!=', 'none')])._notify_by_email(message, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/res_partner.py", line 186, in _notify_by_email
    recipients = self.env[message.model].browse(message.res_id)._message_notification_recipients(message, self)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 690, in _message_notification_recipients
    groups = self._notification_recipients(message, default_groups)
  File "/usr/lib/python2.7/site-packages/odoo/addons/note/models/note.py", line 129, in _notification_recipients
    groups['user']['actions'] = [{'url': new_action, 'title': _('New Note')}]
TypeError: list indices must be integers, not str

**Comment by LeartS** [comment]
Same issue, seems to be triggered in general when logging a message that sends an email

**Comment by davidtranhp** [comment]
I acknowledge that the issue was removed in recent commit 458aaca
Please update your source code and revert if the issue still persists.

**Comment by W360S** [comment]
Yeap update to the lasted version and it fixed thanks :)

**Comment by W360S** [comment]
im using ubuntu so run this :) 
`sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get autoremove`
and it fixed :)

**Comment by davidtranhp** [comment]
Great! I'm closing this issue now.
