### ISSUE TITLE
[17.0] Error when installing demo data: KeyError: planning.slot.allocated_hours

### ISSUE THREAD

**Issue by chrisb-c01** [odoo/odoo#141966]
Impacted versions: 
17.0

Steps to reproduce:
Install demo data for industry_fsm_sale_report

Current behavior:
Error is shown, see stack trace below.

Expected behavior:
Demo data install without issues.

Video/Screenshot link (optional):
NA

Support ticket number submitted via odoo.com/help (optional):
NA

Stack trace:
```
2023-11-14 10:03:22,122 72265 INFO odoo-17 odoo.modules.loading: Module industry_fsm_sale_report: loading demo 
2023-11-14 10:03:22,122 72265 INFO odoo-17 odoo.modules.loading: loading industry_fsm_sale_report/data/industry_fsm_sale_report_demo.xml 
2023-11-14 10:03:22,158 72265 DEBUG odoo-17 odoo.modules.registry: Invalidating default model caches from create /../odoo-17/odoo/addons/base/models/ir_model.py:963 
2023-11-14 10:03:22,820 72265 WARNING odoo-17 odoo.modules.loading: Module industry_fsm_sale_report demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/../odoo-17/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/../odoo-17/odoo/tools/convert.py", line 456, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/../odoo-17/odoo/models.py", line 5042, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/../odoo-17/odoo/models.py", line 4953, in _load_records_create
    return self.create(values)
  File "<decorator-gen-329>", line 2, in create
  File "/../odoo-17/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/../odoo-enterprise-17/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-34>", line 2, in create
  File "/../odoo-17/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/../odoo-17/odoo/addons/base/models/ir_model.py", line 983, in create
    self.pool.setup_models(self._cr)
  File "/../odoo-17/odoo/modules/registry.py", line 340, in setup_models
    env.flush_all()
  File "/../odoo-17/odoo/api.py", line 712, in flush_all
    self._recompute_all()
  File "/../odoo-17/odoo/api.py", line 708, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/../odoo-17/odoo/models.py", line 6825, in _recompute_field
    field.recompute(records)
  File "/../odoo-17/odoo/fields.py", line 1361, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/../odoo-17/odoo/fields.py", line 1334, in apply_except_missing
    func(records)
  File "/../odoo-17/odoo/fields.py", line 1370, in compute_value
    fields = records.pool.field_computed[self]
KeyError: planning.slot.allocated_hours

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/../odoo-17/odoo/modules/loading.py", line 89, in load_demo
    load_data(env(su=True), idref, mode, kind='demo', package=package)
  File "/../odoo-17/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/../odoo-17/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/../odoo-17/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/../odoo-17/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/../odoo-17/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/../odoo-17/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /../odoo-enterprise-17/industry_fsm_sale_report/data/industry_fsm_sale_report_demo.xml:9, somewhere inside
<record id="fsm_template_field4" model="ir.model.fields">
            <field name="name">x_model</field>
            <field name="ttype">many2one</field>
            <field name="relation">product.product</field>
            <field name="field_description">Model</field>
            <field name="model_id" model="ir.model" eval="obj().env.ref('industry_fsm_report.fsm_worksheet_template2').model_id.id"/>
        </record>
2023-11-14 10:03:23,103 72265 DEBUG odoo-17 odoo.modules.registry: Invalidating templates model caches from write /../odoo-17/odoo/addons/base/models/ir_ui_view.py:520 
2023-11-14 10:03:23,107 72265 DEBUG odoo-17 odoo.modules.registry: Invalidating templates model caches from write /../odoo-17/odoo/addons/base/models/ir_ui_view.py:520 
2023-11-14 10:03:23,670 72265 ERROR odoo-17 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/../odoo-17/odoo/http.py", line 2157, in __call__
    response = request._serve_db()
  File "/../odoo-17/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/../odoo-17/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/../odoo-17/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/../odoo-17/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/../odoo-17/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/../odoo-17/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/../odoo-17/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/../odoo-17/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/../odoo-17/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/../odoo-17/odoo/api.py", line 467, in call_kw
    model.env.flush_all()
  File "/../odoo-17/odoo/api.py", line 712, in flush_all
    self._recompute_all()
  File "/../odoo-17/odoo/api.py", line 708, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/../odoo-17/odoo/models.py", line 6825, in _recompute_field
    field.recompute(records)
  File "/../odoo-17/odoo/fields.py", line 1361, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/../odoo-17/odoo/fields.py", line 1334, in apply_except_missing
    func(records)
  File "/../odoo-17/odoo/fields.py", line 1370, in compute_value
    fields = records.pool.field_computed[self]
KeyError: planning.slot.allocated_hours
```

**Comment by chrisb-c01** [comment]
@kbapt can you possible help?
