### ISSUE TITLE
error create form in website use odoo studio in odoo 17 enterprise

### ISSUE THREAD

**Issue by haitac261189** [odoo/odoo#142047]
Impacted versions: 17

![image](https://github.com/odoo/odoo/assets/15794711/4e34ec20-8b57-42d1-b7df-de23a09efaa0)

`UncaughtPromiseError > KeyNotFoundError
Uncaught Promise > Cannot find false in this registry!
KeyNotFoundError: Cannot find false in this registry!
    at Registry.get (https://53673670-17-0-all.runbot159.odoo.com/web/assets/3/144654e/web.assets_web.min.js:3350:76)
    at Class._renderCustomXML (https://53673670-17-0-all.runbot159.odoo.com/web/assets/3/1ed3751/website.backend_assets_all_wysiwyg.min.js:3418:198)
    at Class._renderOriginalXML (https://53673670-17-0-all.runbot159.odoo.com/web/assets/3/1ed3751/website.backend_assets_all_wysiwyg.min.js:2748:734)
    at Class.willStart (https://53673670-17-0-all.runbot159.odoo.com/web/assets/3/1ed3751/website.backend_assets_all_wysiwyg.min.js:2694:1643)`

**Comment by arielprado** [comment]
were you able to resolve the error
I am having the same problem in odoo docker

**Comment by mugua** [comment]
Me too, Still haven't fix this bug
![odoo17-bug](https://github.com/odoo/odoo/assets/15046097/be8abdaf-a264-4c1b-9b89-62d2d0c16adb)

**Comment by jtham1511** [comment]
I still have this issue. I recreate my Odoo.sh instance and do the same using Studio, it still give me the same error. It seem that the latest pull is not available in Odoo.sh ??

**Comment by jruedaflores** [comment]
I had the same error. Can anyone provide me with any updates or solutions?
