### ISSUE TITLE
[17.0] Server Internal Error when sharing projects with portal users

### ISSUE THREAD

**Issue by michaelhofer-slg** [odoo/odoo#142372]
Impacted versions:
17.0

Steps to reproduce:
* Create a project
* Share the project with a portal user
* Sign up / log in as portal user
* Open the project
* Server Internal Error shows: `Unallowed to fetch files from addon partner_autocomplete for file partner_autocomplete/static/src/js/partner_autocomplete_core.js`

Current behavior:
```
2023-11-16 16:12:28,312 117642 ERROR slgbroadcast odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._generate_asset_links_cache at 0x7f3ece9cd240>, 'project.webclient', True, True, (('website_id', False),), False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.asset', <function IrAsset._get_asset_paths at 0x7f3ecf9d64d0>, 'project.webclient', (('website_id', False),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<1591>", line 123, in template_1591
  File "<1591>", line 105, in template_1591_content
  File "<1591>", line 51, in template_1591_t_call_0
  File "<1591>", line 15, in template_1591_t_set_1
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2461, in _get_asset_nodes
    links = self._get_asset_links(bundle, css=css, js=js, debug=debug)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2476, in _get_asset_links
    return self._generate_asset_links_cache(bundle, css=css, js=js, assets_params=assets_params, rtl=rtl)
  File "<decorator-gen-70>", line 2, in _generate_asset_links_cache
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2530, in _generate_asset_links_cache
    return self._generate_asset_links(bundle, css, js, False, assets_params, rtl)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2606, in _generate_asset_links
    asset_bundle = self._get_asset_bundle(bundle, css=css, js=js, debug_assets=debug_assets, rtl=rtl, assets_params=assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2553, in _get_asset_bundle
    files, external_assets = self._get_asset_content(bundle_name, assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2535, in _get_asset_content
    asset_paths = self.env['ir.asset']._get_asset_paths(bundle=bundle, assets_params=assets_params)
  File "<decorator-gen-52>", line 2, in _get_asset_paths
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 154, in _get_asset_paths
    self._fill_asset_paths(bundle, asset_paths, [], addons, installed, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 187, in _fill_asset_paths
    self._process_path(bundle, directive, target, path_def, asset_paths, seen, addons, installed, bundle_start_index, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 211, in _process_path
    paths = self._get_paths(path_def, installed)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 345, in _get_paths
    raise Exception(f"Unallowed to fetch files from addon {addon} for file {path_def}")
Exception: Unallowed to fetch files from addon partner_autocomplete for file partner_autocomplete/static/src/js/partner_autocomplete_core.js

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2157, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1873, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _dispatch
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1240, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 443, in _render_template
    return super()._render_template(template, values=values)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_studio/models/ir_ui_view.py", line 1310, in _render_template
    return super(View, self)._render_template(template, values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2044, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 593, in _render
    result = ''.join(rendering)
  File "<1591>", line 129, in template_1591
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
Exception: Unallowed to fetch files from addon partner_autocomplete for file partner_autocomplete/static/src/js/partner_autocomplete_core.js
Template: project.project_sharing_embed
Path: /t/t/t[1]/t
Node: <t t-call-assets="project.webclient"/>
2023-11-16 16:12:28,314 117642 INFO slgbroadcast werkzeug: 172.16.1.11 - - [16/Nov/2023 16:12:28] "GET /my/projects/10/project_sharing HTTP/1.0" 500 - 55 0.014 0.089

```
Expected behavior:
Project view shown

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by michaelhofer-slg** [comment]
As an additional hint: We have disabled the partner auto complete in the general settings.

**Comment by gdgellatly** [comment]
Well obviously the asset is still there in the database, just disable it, but probably a bug in uninstall. We get this error a lot with migrations.

**Comment by gdgellatly** [comment]
It will be in the table ir.asset, just delete the entry.

**Comment by vava-odoo** [comment]
Thanks @michaelhofer-slg for reporting. This was fixed in https://github.com/odoo/odoo/commit/ba649fbc9c12eaa247979f8dcb4147e3c5257dea

**Comment by mss-hadih** [comment]
Thanks @gdgellatly, ur solution worked for me
