### ISSUE TITLE
Error creating customer from point_of_sale

### ISSUE THREAD

**Issue by jwcaceres78** [odoo/odoo#142430]
Impacted versions: 17.0

Steps to reproduce: install point_of_sale in fresh installation

Current behavior: Error creating user (view complete error ahead)

Expected behavior: user created

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

'''
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6579:163)
    at XMLHttpRequest.<anonymous> (http://54.225.12.57/web/assets/c4001a2/point_of_sale.assets_prod.min.js:6583:13)
'''

**Comment by jwcaceres78** [comment]
Duplicated
