### ISSUE TITLE
[10.0] website_versioning

### ISSUE THREAD

**Issue by ygol** [odoo/odoo#14241]
Impacted versions:   **10.0**
Steps to reproduce:
- go to odoo runbot and log into a running v10 instance
- click on 'webste_admin / settings' and select "Allow multiple versions of the same page (advanced)" under Advanced,A/B testing
- click on 'webste_admin / website Domain' and select either "Website localhost" or "Website 0.0.0.0"

Current behavior: **Getting error message**
`Uncaught Error: QWeb2: Template 'website_version.GoogleAccess' not found
http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'website_version.GoogleAccess' not found
    at Object.exception (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:2908:7)
    at Engine._render (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:2952:103)
    at Engine.render (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:2948:151)
    at Class.renderElement (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:3112:1073)
    at Class.renderElement (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1897-8b34031/web.assets_backend.js:2213:2962)
    at Class.prototype.(anonymous function) [as renderElement] (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:3009:559)
    at Class.renderElement (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1897-8b34031/web.assets_backend.js:2219:1462)
    at Class.prototype.(anonymous function) [as renderElement] (http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:3009:559)
    at http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:3112:917
    at http://179353-10-0-ca11d3.runbot5.odoo.com/web/content/1857-7835d74/web.assets_common.js:547:681`

Expected behavior: **Access to the website settings**

Video/Screenshot link (optional):

**Comment by ygol** [comment]
It also generate an error when accessing 'Settings / General Settings'

**Comment by Yenthe666** [comment]
Hi @ygol,

Thanks a lot for your report.
I've just tested this and can confirm that this is a bug. Example:
![image](https://cloud.githubusercontent.com/assets/6352350/20142747/6777815c-a696-11e6-9fae-635afb1c758e.png)
@Gorash and @JKE-be this might be something for you guys. 😉 

Regards,
Yenthe

**Comment by JKE-be** [comment]
@ygol @Yenthe666 
Probably somebody who play with runbot.
website_version don' t exists in community ;)

So the bug is probably only on the current runbot... Can you reproduce in local ?

**Comment by ygol** [comment]
@JKE-be  yes I got the bug locally and confirmed it by reproducing on runbot

**Comment by JKE-be** [comment]
Are you using community version or Enterprise ?

**Comment by ygol** [comment]
community.

**Comment by JKE-be** [comment]
How can you have website_version in the community ? do you have a custom module ?

**Comment by JKE-be** [comment]
no, the traceback that you report is related to website_version.

The version in your link is simply the current odoo version. (base module)

Could you provide your own traceback ...

**Comment by ygol** [comment]
get the same error as the one I reported from the runbot.

**Comment by JKE-be** [comment]
Stop to try to uses enterprise module on community and you will not have the error...

If you get this error on runbot, it is because you have installed yourself this module. It is not a standard module in the community version.

So yes you have the same error in local that on runbot, because you are doing the same crap.
But if you take a fresh install of Odoo without install it, it will works like a charm !

**Comment by JKE-be** [comment]
Ok, after some research... It is not an updploaded module, but a dwonloaded module.
I can now reproduce it  ! 
The real bug is 'that it should be not installable'.

Thanks for the reporting
