### ISSUE TITLE
error in importing Odoo standard "base import module" 

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14266]
Impacted versions:
10
Steps to reproduce:
I've tried to install the "base import module"
a short dump has occurred (please have a look at the first system log)
and the whole system has been corrupted because it is not possible to navigate (consider the second log when clicking any menu item)
thanks in advance
Claudio Candito

Uncaught TypeError: Cannot read property 'widgets' of undefined
http://XXXX.com/web_studio/static/src/js/web_client.js:239
Traceback:
TypeError: Cannot read property 'widgets' of undefined
    at Class._update_studio_systray (http://XXXX.com/web_studio/static/src/js/web_client.js:239:57)
    at Class.current_action_updated (http://XXXX.com/web_studio/static/src/js/web_client.js:226:22)
    at Class.current_action_updated (http://XXXX.com/web/static/src/js/framework/class.js:122:38)
    at Class.current_action_updated (http://XXXX.com/web/static/src/js/abstract_web_client.js:34:18)
    at http://XXXX.com/web/static/src/js/framework/widget.js:398:23
    at Class.<anonymous> (http://XXXX.com/web/static/src/js/framework/widget.js:331:17)
    at Class.trigger (http://XXXX.com/web/static/src/js/framework/mixins.js:222:31)
    at Class._trigger_up (http://XXXX.com/web/static/src/js/framework/mixins.js:292:34)
    at Class._trigger_up (http://XXXX.com/web/static/src/js/framework/mixins.js:294:20)
    at Class.trigger_up (http://XXXX.com/web/static/src/js/framework/mixins.js:288:14)

Uncaught TypeError: Cannot read property 'children' of undefined
http://XXXX.com/web_studio/static/src/js/web_client.js:54
Traceback:
TypeError: Cannot read property 'children' of undefined
    at Class.<anonymous> (http://XXXX.com/web_studio/static/src/js/web_client.js:54:55)
    at Class.trigger (http://XXXX.com/web/static/src/js/framework/mixins.js:222:31)
    at Class.trigger (http://XXXX.com/web/static/src/js/framework/mixins.js:283:42)
    at HTMLAnchorElement.<anonymous> (http://XXXX.com/web/static/src/js/menu.js:43:22)
    at HTMLUListElement.dispatch (http://XXXX.com/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLUListElement.elemData.handle (http://XXXX.com/web/static/lib/jquery/jquery.js:4309:63)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by mge-odoo** [comment]
Hi @ccandito 

Sorry for the unusual delay to address your issue.
It got lost somehow, without the process of being tagged by the community so I didn't see it.

Next time you get traceback on a database, do not hesitate to open a ticket on www.odoo.com/help to directly contact our support.

We haven't touch this part of the code in 10.0 since its creation and I think that have never experienced this error. Do you have custom JS code that would modify the systray menu?

This error is quite unusual ; is is still occuring? As you reported it some time ago, I assume that you find a way to fix it ; I therefore close this ticket but do not hesitate to reopen it if it's still occuring.

Regards,

Martin
