### ISSUE TITLE
[10.0-hr_gamification] Application not installed - bug

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#14300]
Impacted versions:10
Linux Ubuntu 14.04

Steps to reproduce: Apps > HR Gamification > Install

Current behavior: Application not installed
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 842, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 894, in convert_csv_import
    result = env[model].load(fields, datas)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 862, in load
    for id, xid, record, info in converted:
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1026, in _convert_records
    converted = convert(record, functools.partial(_log, extras, stream.index))
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_fields.py", line 85, in fn
    log(field, w)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1001, in _log
    message=unicode(exception.args[0]) % exc_vals)
KeyError: u'\u043f\u043e\u043b\u0435'
``
Expected behavior:
The application must be installed

Video/Screenshot link (optional): 
http://prntscr.com/d742iq

**Comment by JKE-be** [comment]
Hi,
I cannot reproduce in English on the runbot...
What is your current language installed... ?

**Comment by collex100** [comment]
Russian

**Comment by mart-e** [comment]
Hello,

Indeed it was a translation issue. I have fixed it on Transifex and it should be included in the next translation update (on Sunday).
Please note that we are not responsible of bad translations, it is done by the community on [Transifex](https://www.transifex.com/odoo/)

**Comment by collex100** [comment]
Thank you!
