### ISSUE TITLE
Cant create contact V17.0 Odoo sh

### ISSUE THREAD

**Issue by ocandoe** [odoo/odoo#143230]
Impacted versions: 17.0 

Steps to reproduce:
using language Spansih (GT) go Contact -> New 

Im using odoo.sh Lastest version ( i tested on runbot and the behavior not show)
i try with english, italian, spanish(mx) and the behavior not show

Current behavior:

UncaughtPromiseError > OwlError
Promesa no controlada > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:916:101)
    at App.handleError (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1543:29)
    at Fiber._render (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:941:19)
    at Fiber.render (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1007:47)

Caused by: EvalError: Can not evaluate python expression: (bool(no is_company))
Error: Name 'no' is not defined
    at evaluateExpr (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:3024:54)
    at FormRenderer.evaluateBooleanExpr (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:3027:8)
    at FormRenderer.slot31 (eval at compile (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1501:374), <anonymous>:320:26)
    at callSlot (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1109:25)
    at InnerGroup.template (eval at compile (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1501:374), <anonymous>:56:42)
    at Fiber._render (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:940:96)
    at Fiber.render (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (https://ocandoe-corsisa-17.odoo.com/web/assets/dcd9efc/web.assets_web.min.js:1007:47)

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ocandoe** [comment]
> @ocandoe Okay, there is your problem. Odoo **needs** a localization package to be installed before you can do anything sensible with it.
> 
> Odoo's contacts need to know a default account payable & receivable. Same applies for creation of products. They also need profit and loss accounts.
> 
> Yep, it is a defect that one gets a Python crash. But for the real-world use you always need to have one localization installed.

Thanks, I already installed the l10n_gt module but the problem persists
