### ISSUE TITLE
[10.0] TransientModel compute binary download error

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#14380]
Impacted versions:
download binary field

Steps to reproduce:

- create a TransientModel
- create a compute binary field, use for demo file to download
```python
tmpl_data = fields.Binary("Template", readonly=True, attachment=True)
tmpl_name = fields.Char("Template FileName", readonly=True)

@api.model
def default_get(self, fields):
    res = super(CrawlerUploadWizard, self).default_get(fields)
    active_model = self._context.get("active_model")
    res['tmpl_name'], res['tmpl_data'] = self.env[active_model].get_template()
    return res
```
```python
@api.model
def get_template(self):
    demo = self.env.ref('business_master.business_master_demo_item_xlsx')
    return demo.datas_fname, demo.datas
```
- click download icon
- raise AttributeError: 'NotFound' object has no attribute 'set_cookie' 

Current behavior:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/king/yubao-task/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/king/yubao-task/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/king/yubao-task/openerp/http.py", line 1488, in __call__
    return self.dispatch(environ, start_response)
  File "/home/king/yubao-task/openerp/http.py", line 1462, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/king/yubao-task/openerp/http.py", line 1652, in dispatch
    result = ir_http._dispatch()
  File "/home/king/yubao-task/openerp/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/king/yubao-task/openerp/addons/base/ir/ir_http.py", line 186, in _dispatch
    return self._handle_exception(e)
  File "/home/king/yubao-task/openerp/addons/base/ir/ir_http.py", line 157, in _handle_exception
    return request._handle_exception(exception)
  File "/home/king/yubao-task/openerp/http.py", line 781, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/king/yubao-task/openerp/addons/base/ir/ir_http.py", line 182, in _dispatch
    result = request.dispatch()
  File "/home/king/yubao-task/openerp/http.py", line 840, in dispatch
    r = self._call_function(**self.params)
  File "/home/king/yubao-task/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/king/yubao-task/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/king/yubao-task/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/king/yubao-task/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/king/yubao-task/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/king/yubao-task/openerp/addons/web/controllers/main.py", line 978, in content_common
    response.set_cookie('fileToken', token)
AttributeError: 'NotFound' object has no attribute 'set_cookie'
```
Expected behavior:

web/controller/main.py 
class Binary(http.Controller)
def content_common

status = 404, because id of TransientModel is null now. but data is computed.
i want to download this demo file

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
