### ISSUE TITLE
[10.0] Customer Portal gives 500 Server Error for Invoice or Delivery Order

### ISSUE THREAD

**Issue by joe1981alAPR** [odoo/odoo#14395]
Impacted versions: 10.0

Steps to reproduce: Create a new customer, under Actions->Portal Access Management, enable portal for this customer.  Create an Invoice for that customer, then log into the portal as the customer and try and view the invoice.

Current behavior:  Fails with a 500 Internal Server Error

Expected behavior:  Invoice will display

The rule "res_partner: portal/public: read access on my commercial partner" defined in https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/security/base_security.xml is causing the issue.  If that rule is disabled then the report generates for the customer.

The rule is limiting records from res.partner to the customers own partner records and not allowing the associated company_id or company_ids (in multi company) records to be accessed even though those fields are in the report template by default.

@tde-banana-odoo think you could add to this rule to also allow access to company_id or company_ids assigned to the user?

Error from Server Log:
```python
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 264, in _handle_exception
   response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
   return request._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 766, in _handle_exception
   return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
   result = request.dispatch()
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 825, in dispatch
   r = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
   return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
   return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
   result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
   return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
   response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
   pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 165, in get_pdf
   html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 139, in get_html
   return self.render(report.report_name, docargs)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 115, in render
   return view_obj.render_template(template, values)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
   return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_ui_view.py", line 110, in render
   return super(View, self).render(values, engine=engine)
  File "/opt/odoo/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
   return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
   return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
   return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
     File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
   self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
   raise e
QWebException: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)', None)
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
   return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_report_external_layout_footer_500
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 872, in __get__
   value = record._cache[self]
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5526, in __getitem__
   return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 48, in get
   raise self.exception
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)', None)
Error to render compiling AST
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)', None)
Template: report.external_layout_footer
Path: /templates/t/div/div/ul[1]/li[2]
Node: <li t-if="company.fax and company.phone" data-oe-id="352" data-oe-model="ir.ui.view" data-oe-field="arch" data-oe-xpath="/t[1]/div[1]/div[1]/ul[1]/li[2]">&amp;bull;</li>```

**Comment by joe1981alAPR** [comment]
This PR #14420 should fix the issue.  Took the rule from another rule and added to the portal rule to allow portal users to access company partner records for companies that are assigned to them.

**Comment by JKE-be** [comment]
.

**Comment by mart-e** [comment]
Hello,

When I am checking your PR and this issue (in the future, please only create one, it is easier not to split the discussion), I believe there is some company configuration you are not explaining.

Please specify exactly how you create the partners and how you are accessing the record to.
We do not wish to modify base security rule, maybe we can prevent the error somewhere else.

**Comment by mart-e** [comment]
As said on the pull request, I understand as multicompany for portal users which is out of scope of the classic security rules suggestions.
