### ISSUE TITLE
[9.0] account: traceback when changing company on vendor invoices

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#14410]
**Impacted versions:**
[9.0]

**Steps to reproduce:**

1. Create a new database with demonstration data
1. Install `account`
1. Activate multi-company
1. Go to vendor bill, pick a draft invoice.
1. Edit the invoice and go to tab `Other info`
1. On company field, erase whatever the value is and hit `tab`

**Current behavior:**
A wild traceback appears!

**Expected behavior:**
Nothing should happen, field is required so it cannot be saved if empty. Nevertheless, a traceback shouldn't happen.`

```
Traceback (most recent call last):
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/build/2c991c3d-1851/parts/enterprise/web/controllers/main.py", line 903, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/enterprise/web/controllers/main.py", line 895, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/models.py", line 6041, in onchange
    record.mapped(field_seq)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/models.py", line 5539, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/models.py", line 5519, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/models.py", line 5757, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/fields.py", line 830, in __get__
    self.determine_value(record)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/fields.py", line 939, in determine_value
    self.compute_value(recs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/fields.py", line 894, in compute_value
    self._compute_value(records)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/fields.py", line 884, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/api.py", line 425, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/addons/account/models/account_invoice.py", line 1107, in _compute_price
    price_subtotal_signed = self.invoice_id.currency_id.compute(price_subtotal_signed, self.invoice_id.company_id.currency_id)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/build/2c991c3d-1851/parts/odoo/openerp/addons/base/res/res_currency.py", line 225, in compute
    assert to_currency, "compute to unknown currency"
AssertionError: compute to unknown currency
```

opw: 694476

**Comment by nim-odoo** [comment]
Solved in https://github.com/odoo/odoo/commit/aa7d1ab9d1b14a68e421ee254d31d3eb6ef04207
