### ISSUE TITLE
Erro ao inserir avatar em usuário cadastrado. / Error inserting avatar into registered user.

### ISSUE THREAD

**Issue by thiago95macedo** [odoo/odoo#14467]
Impacted versions: v10

Steps to reproduce: Erro ao inserir avatar em usuário cadastrado. / Error inserting avatar into registered user.

Current behavior: 

Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/hr/models/res_users.py", line 17, in write
    result = super(User, self).write(vals)
  File "/odoo/odoo-server/addons/mail/models/res_users.py", line 56, in write
    write_res = super(Users, self).write(vals)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 802, in write
    res = super(UsersView, self).write(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 640, in write
    res = super(UsersImplied, self).write(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 355, in write
    res = super(Users, self).write(values)
  File "/odoo/odoo-server/odoo/models.py", line 3545, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3683, in _write
    self.env[parent_model].browse(parent_ids).write(parent_vals)
  File "/odoo/odoo-server/odoo/addons/base/res/res_partner.py", line 491, in write
    tools.image_resize_images(vals)
  File "/odoo/odoo-server/odoo/tools/image.py", line 265, in image_resize_images
    avoid_resize_big=True, avoid_resize_medium=False, avoid_resize_small=False))
  File "/odoo/odoo-server/odoo/tools/image.py", line 254, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/odoo/odoo-server/odoo/tools/image.py", line 143, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/odoo/odoo-server/odoo/tools/image.py", line 73, in image_resize_image
    image = image_resize_and_sharpen(image, size)
  File "/odoo/odoo-server/odoo/tools/image.py", line 92, in image_resize_and_sharpen
    image = image.convert('RGBA')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 832, in convert
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 200, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 417, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder jpeg not available

**Comment by thiago95macedo** [comment]
Solução! / Solution!

sudo apt-get install libjpeg-dev

sudo ln -s /usr/lib/i386-linux-gnu/libjpeg.so /usr/lib/
sudo ln -s /usr/lib/i386-linux-gnu/libfreetype.so.6 /usr/lib/
sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib/

pip install --no-cache-dir -I pillow

reboot
