### ISSUE TITLE
[JSON-RPC] `product.product` selecting `product_properties` field -> tuple indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#145138]
Impacted versions:
v17 only

Steps to reproduce:
Make a json rpc request to get one of the `product.product` with this selected field `product_properties` :

```javascript
var xhr = new XMLHttpRequest();
xhr.open("POST", "http://localhost:8069/jsonrpc", true);
xhr.send(JSON.stringify({
   "jsonrpc":"2.0",
   "method":"call",
   "params":{
      "service":"object",
      "method":"execute_kw",
      "args":[
         "odoo-master-v17",
         2,
         "admin",
         "product.product",
         "search_read",
         [[]],
         {
            "offset":0,
            "order":null,
            "limit":1,
            "fields":[
               "product_properties",
               "id",
               "display_name"
            ]
         }
      ]
   }
}));
```

Current behavior:

```
Odoo Server Error - builtins.TypeError
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 158, in jsonrpc
    return dispatch_rpc(service, method, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 388, in dispatch_rpc
    return dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 37, in dispatch
    res = execute_kw(db, uid, *params[3:])
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 59, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 65, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 50, in execute_cr
    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5716, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3721, in _read_format
    results = field.convert_to_read_multi(values_list, self.browse(records))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3402, in convert_to_read_multi
    definition = self._get_properties_definition(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3592, in _get_properties_definition
    container = record[self.definition_record]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6574, in __getitem__
    return self.browse((self._ids[key],))
TypeError: tuple indices must be integers or slices, not NoneType

tuple indices must be integers or slices, not NoneType
```

**Comment by diegovicente5** [comment]
facing the same issue.

**Comment by vadimscafari** [comment]
Hi,
Look at issue: #146835
