### ISSUE TITLE
Google Calendar Sync Issue Error

### ISSUE THREAD

**Issue by innovo3d** [odoo/odoo#14575]
Impacted versions: 
Version 9.0c (Community Edition)

Steps to reproduce: 
Install Google Calendar App, configure according to instructions in General Settings, go to Calendar tab, Sync with Google

Current behavior:  
produces this error:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/parts/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/parts/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/parts/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/parts/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/parts/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/parts/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/parts/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/google_calendar/google_calendar.py", line 603, in synchronize_events
    res = self.update_events(cr, user_to_sync, lastSync, context)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/google_calendar/google_calendar.py", line 834, in update_events
    self.create_from_google(cr, uid, event, myPartnerID, context=context)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/google_calendar/google_calendar.py", line 411, in create_from_google
    res = self.update_from_google(cr, uid, False, event.GG.event, "create", context=context_tmp)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/google_calendar/google_calendar.py", line 531, in update_from_google
    res = calendar_event.create(cr, uid, result, context=context)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/crm/calendar_event.py", line 17, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/calendar/calendar.py", line 1647, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/parts/odoo/addons/mail/models/mail_thread.py", line 233, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/parts/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/parts/odoo/openerp/models.py", line 4348, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/parts/odoo/openerp/osv/fields.py", line 1518, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/parts/odoo/addons/calendar/calendar.py", line 839, in _set_rulestring
    update_data = self._parse_rrule(field_value, dict(data), rdate)
  File "/opt/odoo/parts/odoo/addons/calendar/calendar.py", line 1321, in _parse_rrule
    data['day'] = r._bymonthday[0]
TypeError: 'set' object does not support indexing

Expected behavior:

Video/Screenshot link (optional):
<img width="1271" alt="screen shot 2016-12-02 at 1 06 44 pm" src="https://cloud.githubusercontent.com/assets/7477099/20844904/3597a94e-b890-11e6-9820-8903f89d901f.png">

**Comment by JKE-be** [comment]
Hello
Check That you have the last odoo code ...
Else you can also update the package Python datetime ! That will fix this error...

**Comment by innovo3d** [comment]
Do you mean dateutil?

This is what I have:
root@odoo-v9:~# dpkg -s python-dateutil
Package: python-dateutil
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 216
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 1.5+dfsg-1ubuntu1
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2),
tzdata
Description: powerful extensions to the standard datetime module
 It features:
 .
  * computing of relative deltas (next month, next year, next monday, last
week
    of month, etc);
  * computing of relative deltas between two given date and/or datetime
objects
  * computing of dates based on very flexible recurrence rules, using a
superset
    of the iCalendar specification. Parsing of RFC strings is supported as
well.
  * generic parsing of dates in almost any string format
  * timezone (tzinfo) implementations for tzfile(5) format files
    (/etc/localtime, /usr/share/zoneinfo, etc), TZ environment string (in
all
    known formats), iCalendar format files, given ranges (with help from
    relative deltas), local machine timezone, fixed offset timezone, UTC
    timezone
  * computing of Easter Sunday dates for any given year, using Western,
Orthodox
    or Julian algorithms
Original-Maintainer: Guido Günther <agx@sigxcpu.org>

*Adam Rumjahn*

* <http://www.innovo3d.co>*

*adam@innovo3d.co <adam@innovo3d.co>Cel: +57 304 643 1248*
*Fijo: +57 2 374 2473*

**Comment by JKE-be** [comment]
Yes dateutil sorry

**Comment by JKE-be** [comment]
Take a look here: https://github.com/odoo/odoo/commit/9f09c625f5163ef98ee308ea1bd7cb2004ef1f03
