### ISSUE TITLE
[16.0][Lunch] Error in converting hours to time object

### ISSUE THREAD

**Issue by elmeriniemela** [odoo/odoo#145863]
Impacted versions: at least V16

Steps to reproduce:
1. Install all Community apps
2. Run odoo-bin populate --size large

Current behavior:
```
2023-12-11 18:44:43,780 49 INFO db odoo.models: Batch: 1000/1500
2023-12-11 18:44:49,864 49 ERROR db odoo.cli.populate: Something went wrong populating database
Traceback (most recent call last):
  File "/mnt/odoo/odoo/cli/populate.py", line 76, in populate
    registry.populated_models[model._name] = model._populate(size).ids
  File "/mnt/odoo/odoo/models.py", line 6680, in _populate
    records_batches.append(self.create(create_values))
  File "<decorator-gen-173>", line 2, in create
  File "/mnt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/mnt/odoo/addons/lunch/models/lunch_supplier.py", line 188, in create
    suppliers._sync_cron()
  File "/mnt/odoo/addons/lunch/models/lunch_supplier.py", line 135, in _sync_cron
    float_to_time(supplier.automatic_email_time, supplier.moment)))
  File "/mnt/odoo/addons/lunch/models/lunch_supplier.py", line 27, in float_to_time
    return time(int(integral), int(float_round(60 * fractional, precision_digits=0)), 0)
ValueError: minute must be in 0..59
```

Expected behavior:
No exception.

**Comment by JoernGoepel** [comment]
Hi,

PUSH.

seems like the bug is already open.
Got the same problem.

float_to_time(0.991) should work
float_to_time(0.992) gives error, that minute must be in 0..59

The view widget="float_time" converts this correctly if you give him the 0.992 and doesn´t throw a error.

![Image](https://github.com/user-attachments/assets/77995c7d-b3a7-441c-b421-aa0a0cadafa9)
