### ISSUE TITLE
Create New Branch  

### ISSUE THREAD

**Issue by viewsaloon** [odoo/odoo#146607]
Impacted versions:
Create New Branch 
Steps to reproduce:

Current behavior:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fd82f918550>, 'account.1_pos_receivable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 135, in retrying
    env.cr.flush()  # submit the changes to the database
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 138, in flush
    self.precommit.run()
  File "/home/odoo/src/odoo/odoo/tools/misc.py", line 1219, in run
    func()
  File "/home/odoo/src/odoo/addons/account/models/company.py", line 272, in try_loading
    self.env['account.chart.template']._load(
  File "/home/odoo/src/odoo/addons/account/models/chart_template.py", line 191, in _load
    self._load_data(data)
  File "/home/odoo/src/odoo/addons/account/models/chart_template.py", line 508, in _load_data
    'values': deref(record, self.env[model]),
  File "/home/odoo/src/odoo/addons/account/models/chart_template.py", line 431, in deref
    raise e
  File "/home/odoo/src/odoo/addons/account/models/chart_template.py", line 428, in deref
    values[fname] = self.ref(value).id if value not in ('', 'False', 'None') else False
  File "/home/odoo/src/odoo/addons/account/models/chart_template.py", line 938, in ref
    or self.env.ref(f"account.{self.env.company.parent_ids[0].id}_{xmlid}", raise_if_not_found)
  File "/home/odoo/src/odoo/odoo/api.py", line 572, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 2182, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-42>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 2175, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account.1_pos_receivable

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://viewsaloon-view-saloon.odoo.com/web/assets/41bd685/web.assets_web.min.js:2872:163)
    at XMLHttpRequest.<anonymous> (https://viewsaloon-view-saloon.odoo.com/web/assets/41bd685/web.assets_web.min.js:2876:13)
Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
#3644278

**Comment by vava-odoo** [comment]
Ticket closed as it was linked to deleted account data
