### ISSUE TITLE
Backend loading blank (404), Undefined FieldMany2ManyTag

### ISSUE THREAD

**Issue by alexanderahlsen** [odoo/odoo#14676]
Impacted versions: 10.0-20161211

Steps to reproduce: Run apt-get update, apt-get upgrade

Current behavior: Backend displaying logo, menubar, sidebar and main without content

Expected behavior: Content loaded in the backend.

Video/Screenshot link (optional): https://cl.ly/40423E0w3P1P

**Comment by alexanderahlsen** [comment]
Log file:
`2016-12-11 14:22:56,376 2531 INFO thegeek odoo.addons.base.ir.ir_http: Generating routing map
2016-12-11 14:23:00,250 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:00] "GET /web/ HTTP/1.0" 200 -
2016-12-11 14:23:00,628 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:00] "GET /web/content/252-54a49f8/web.assets_backend.js HTTP/1.0" 200 -
2016-12-11 14:23:00,756 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:00] "GET /web/content/247-54a49f8/web.assets_backend.0.css HTTP/1.0" 200 -
2016-12-11 14:23:00,767 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:00] "GET /web/content/248-54a49f8/web.assets_backend.1.css HTTP/1.0" 200 -
2016-12-11 14:23:06,284 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:06] "GET /web/webclient/qweb?mods=base_import,base HTTP/1.0" 304 -
2016-12-11 14:23:06,610 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:06] "GET /web_editor/static/src/xml/ace.xml HTTP/1.0" 404 -
2016-12-11 14:23:06,630 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:06] "POST /web/dataset/call HTTP/1.0" 200 -
2016-12-11 14:23:06,995 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:06] "GET /web_editor/static/src/xml/editor.xml HTTP/1.0" 404 -
2016-12-11 14:23:07,143 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:07] "GET /web_editor/static/src/xml/snippets.xml HTTP/1.0" 404 -
2016-12-11 14:23:07,328 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:07] "POST /web/webclient/translations HTTP/1.0" 200 -
2016-12-11 14:23:07,359 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:07] "POST /web/webclient/translations HTTP/1.0" 200 -
2016-12-11 14:23:07,459 2531 INFO thegeek werkzeug: 127.0.0.1 - - [11/Dec/2016 14:23:07] "GET /web/webclient/locale/en_US HTTP/1.0" 500 -
2016-12-11 14:23:07,473 2531 ERROR thegeek werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 491, in load_locale
    addons_path = http.addons_manifest['web']['addons_path']
KeyError: 'web'
`

**Comment by Yenthe666** [comment]
Hi @alexanderahlsen,

Thanks a lot for your bug report and sorry for the quite late response.
Can you still reproduce it? On what OS & version of the OS are you doing this exactly?

Regards,
Yenthe
