### ISSUE TITLE
XMLRPC search_read error "TypeError: tuple indices must be integers or slices, not NoneType" on product.product

### ISSUE THREAD

**Issue by vadimscafari** [odoo/odoo#146835]
Impacted versions:
17

Steps to reproduce:
execute_kw(target_dbname, target_uid, target_password, 'product.product', 'search_read, *args, **kwargs)

Current behavior:
Traceback (most recent call last):
  File "/odoo/odoo/addons/base/controllers/rpc.py", line 150, in xmlrpc_2
    response = self._xmlrpc(service)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/addons/base/controllers/rpc.py", line 130, in _xmlrpc
    result = dispatch_rpc(service, method, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/http.py", line 388, in dispatch_rpc
    return dispatch(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/service/model.py", line 37, in dispatch
    res = execute_kw(db, uid, *params[3:])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/service/model.py", line 59, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/service/model.py", line 65, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/service/model.py", line 50, in execute_cr
    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/odoo/odoo/api.py", line 462, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/models.py", line 5730, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/models.py", line 3731, in _read_format
    results = field.convert_to_read_multi(values_list, self.browse(records))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/fields.py", line 3403, in convert_to_read_multi
    definition = self._get_properties_definition(record)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/fields.py", line 3593, in _get_properties_definition
    container = record[self.definition_record]
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/odoo/odoo/models.py", line 6588, in __getitem__
    return self.browse((self._ids[key],))
                        ~~~~~~~~~^^^^^
TypeError: tuple indices must be integers or slices, not NoneType

Expected behavior:
return a product or nothing

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by SamekaTV** [comment]
The *args or **kwargs you're passing could contain invalid values or have a bad structure. Make sure to debug and/or inspect the values.

**Comment by vadimscafari** [comment]
> The *args or **kwargs you're passing could contain invalid values or have a bad structure. Make sure to debug and/or inspect the values.

I checked it and still getting the error. 
Also, if I change it to product.product to product.template, it works perfectly

**Comment by vadimscafari** [comment]
I seem to have found the solution:
in "/odoo/odoo/fields.py", the function
```
def _get_properties_definition(self, record):
    """Return the properties definition of the given record."""
    container = record[self.definition_record]
    if container:
        return container.sudo()[self.definition_record_field]
```
seems to call self.definition_record even when this one is 'None'.

My solution to it:
```
def _get_properties_definition(self, record):
    """Return the properties definition of the given record."""
    if self.definition_record:
        container = record[self.definition_record]
        if container:
            return container.sudo()[self.definition_record_field]
```

**Comment by sikemullivan** [comment]
@vadimscafari I tried your solution and it still throws the same error. Did I missing something?

_get_properties_definition
    **if self.definition_record:**
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6588, in __getitem__
    return self.browse((self._ids[key],))
TypeError: tuple indices must be integers or slices, not NoneType

**Comment by sikemullivan** [comment]
nevermind.... I had to restart the docker container for the odoo service to pick up the updated fields.py file.

**Comment by cuonghuynh** [comment]
I'm facing the same issue.
It works for me. Thank you @vadimscafari
