### ISSUE TITLE
Traceback on creating blogpost

### ISSUE THREAD

**Issue by JakubSs** [odoo/odoo#14725]
Its as it was downloaded, no changes made. Trying to update source files...

Impacted versions:
Odoo 10.0-20161207 (Community Edition)

Steps to reproduce:
Go to website and crate a blogpost

Current behavior:
Traceback on save

Video/Screenshot link (optional):
```python

Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/odoo/addons/website/models/ir_http.py", line 264, in _handle_exception
response = super(Http, cls)._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
return request._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 766, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
result = request.dispatch()
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 825, in dispatch
r = self._call_function(**self.params)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in call
return self.method(*args, **kw)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python2.7/site-packages/odoo/addons/website_blog/controllers/main.py", line 249, in blog_post
'nav_list': self.nav_list(blog),
File "/usr/lib/python2.7/site-packages/odoo/addons/website_blog/controllers/main.py", line 43, in nav_list
group['year'] = babel.dates.format_datetime(start, format='YYYY', tzinfo=tzinfo, locale=locale)
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 508, in format_datetime
return parse_pattern(format).apply(datetime, locale)
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 702, in apply
return self % DateTimeFormat(datetime, locale)
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 699, in mod
return self.format % other
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 720, in getitem
return self.format_year(char, num)
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 772, in format_year
week = self.get_week_number(self.get_day_of_year())
File "/usr/lib/python2.7/site-packages/babel/dates.py", line 863, in get_day_of_year
return (date - date(date.year, 1, 1)).days + 1
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

```
@JKE-be ping

**Comment by JKE-be** [comment]
Re,

I cannot reproduce it on runbot 10

So:
  I connect as admin on website, 
  click on '+new'
  click  on 'new blog'
  drop snippet and set title
  save
...

not traceback ...


Can you try to reproduce it on runbot and give me the process ? 

If you cannot reproduce, it could be interesting to print the start value in 
`"/usr/lib/python2.7/site-packages/odoo/addons/website_blog/controllers/main.py", line 43"`

**Comment by JakubSs** [comment]
I am not able to reproduce it either on runbot 10... 
On mine serve I uninstalled website_blog, removed tables from postgres blog_blog and eveyrhing starting with blog, updated sources and installed again after restart of odoo server - no success. 

I am sorry, I am not as good. How can I print star value in "/usr/lib/python2.7/site-packages/odoo/addons/website_blog/controllers/main.py", line 43" ?

**Comment by JakubSs** [comment]
I am going to try new db after source update...

**Comment by JakubSs** [comment]
I installed odoo on new full updated Centos and there is same error.
I used this guide
https://www.rosehosting.com/blog/how-to-install-odoo-9-on-a-centos-7-vps/

`[odoo-nightly]
name=Odoo Nightly repository
baseurl=http://nightly.odoo.com/10.0/nightly/rpm/
enabled=1
gpgcheck=1
gpgkey=https://nightly.odoo.com/odoo.key`

I am going to replace files from source

**Comment by JKE-be** [comment]
what is your babel version ?

**Comment by JakubSs** [comment]
seems babel-0.9.6

**Comment by JKE-be** [comment]
Your version is outdated...

This bug has been fixed 30/07/2012 ;) in babel
https://github.com/python-babel/babel/commit/920bb01c6bd84e2693aadb39effa24d3f4722e6f

This fix is already included in v1 :) 

As you can see in the requirement file from Odoo, we depends of Babel==2.3.4 ...
https://github.com/odoo/odoo/blob/10.0/requirements.txt#L1

**Comment by JakubSs** [comment]
@JKE-be  issue - there is only this version of babel for centos 7.2
https://www.rpmfind.net/linux/rpm2html/search.php?query=python-babel

**Comment by JakubSs** [comment]
I think its a big problem. CentOS 7.2 is used by lots of sysadmins.

**Comment by JKE-be** [comment]
Let me try to check tomorrow for a patch in Odoo...

**Comment by JakubSs** [comment]
all right. I will try install it within pip tomorrow. It could work there.

**Comment by sle-odoo** [comment]
@JakubSs indeed, there's only the 0.9.6 version in the centos repository and sadly there's no updated verions in the EPEL repositories. I guess we should not install this package with the official repos and use the [post-install script](https://github.com/odoo/odoo/blob/10.0/setup/redhat/postinstall.sh#L61) for that, as we do for packages that aren't bundled in the official repos or the EPEL.

**Comment by JakubSs** [comment]
@sle-odoo Hi,
well, I had some errors using https://github.com/odoo/odoo/blob/10.0/setup/redhat/postinstall.sh#L61 but I successfully solved the issue -  by installing pip, removing babel from site-packages  and `pip install pytz babel`.
All is working now :) I think it deserve some note, mentioning or something on odoo install process for CentOS/RedHat 7.2.

Thanks for you help @sle-odoo and @JKE-be, I appreciate it. You may close the issue :)
