### ISSUE TITLE
Numeric field overflow

### ISSUE THREAD

**Issue by gelodev** [odoo/odoo#14773]
Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/common/http.py", line 593, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 360, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 586, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 167, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 121, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/server/openerp/addons/audittrail/audittrail.py", line 501, in execute_cr
    return fct_src(cr, uid, model, method, *args)
  File "/opt/openerp/server/openerp/osv/osv.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/server/openerp/osv/orm.py", line 2245, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4599, in _search
    cr.execute('SELECT "%s".id FROM ' % self._table + from_clause + where_str + order_by + limit_str + offset_str, where_clause_params)
  File "/opt/openerp/server/openerp/sql_db.py", line 152, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/sql_db.py", line 212, in execute
    res = self._obj.execute(query, params)
DataError: numeric field overflow
DETAIL:  A field with precision 16, scale 2 must round to an absolute value less than 10^14.

I have this error whenever I click on Purchases, Can someone help me?

**Comment by Yenthe666** [comment]
Hi @gelodev,

This is 'logical' behaviour because the number is bigger than a numeric field can hold without crashing.
To fix this you could for example store it as text or a float instead of double.

Regards,
Yenthe
