### ISSUE TITLE
EDI : Perform web services operations cron issue

### ISSUE THREAD

**Issue by smt-sa-dev** [odoo/odoo#147819]
Impacted versions:
15.0
Steps to reproduce:
running  cron job : EDI : Perform web services operations

Current behavior:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 332, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/odoo/addons/account_edi/models/account_edi_document.py", line 262, in _cron_process_documents_web_services
    nb_remaining_jobs = edi_documents._process_documents_web_services(job_count=job_count)
  File "/home/odoo/src/odoo/addons/account_edi/models/account_edi_document.py", line 249, in _process_documents_web_services
    self._process_job(documents, doc_type)
  File "/home/odoo/src/odoo/addons/account_edi/models/account_edi_document.py", line 198, in _process_job
    edi_result = edi_format._post_invoice_edi(invoices)
  File "/home/odoo/src/odoo/addons/l10n_sa_edi/models/account_edi_format.py", line 449, in _post_invoice_edi
    return {invoice: self._l10n_sa_post_zatca_edi(invoice)}
  File "/home/odoo/src/odoo/addons/l10n_sa_edi/models/account_edi_format.py", line 328, in _l10n_sa_post_zatca_edi
    response_data, submitted_xml = self._l10n_sa_export_zatca_invoice(invoice, xml_content)
UnboundLocalError: local variable 'xml_content' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1328, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 469, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 90, in method_direct_trigger
    cron.with_user(cron.user_id).with_context(lastcall=cron.lastcall).ir_actions_server_id.run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 643, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 512, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'UnboundLocalError'>: "local variable 'xml_content' referenced before assignment" while evaluating
'model._cron_process_documents_web_services(job_count=20)'

Expected behavior:
send invoices to zacat
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Atteqany** [comment]
**Still they **modul**e** of ZATCA not fixed 
**Impacted versions:** V16

**Current behavior:** 
If I invoiced via Point of sale, it causes the following error: 

Traceback (most recent call last):
  File "/odoo3/odoo3-server/odoo/api.py", line 996, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 41

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo3/odoo3-server/odoo/fields.py", line 1161, in _get_
    value = env.cache.get(record, self)
  File "/odoo3/odoo3-server/odoo/api.py", line 1003, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.move(41,).l10n_sa_qr_code_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "&lt;756&gt;", line 2297, in template_756
  File "&lt;756&gt;", line 2279, in template_756_content
  File "&lt;756&gt;", line 236, in template_756_t_call_0
  File "&lt;756&gt;", line 191, in template_756_t_set_2
  File "/odoo3/odoo3-server/odoo/fields.py", line 1210, in _get_
    self.compute_value(recs)
  File "/odoo3/odoo3-server/odoo/fields.py", line 1392, in compute_value
    records._compute_field_value(self)
  File "/odoo3/odoo3-server/addons/mail/models/mail_thread.py", line 403, in _compute_field_value
    return super()._compute_field_value(field)
  File "/odoo3/odoo3-server/odoo/models.py", line 4232, in _compute_field_value
    fields.determine(field.compute, self)
  File "/odoo3/odoo3-server/odoo/fields.py", line 98, in determine
    return needle(*args)
  File "/odoo3/odoo3-server/addons/l10n_sa_edi/models/account_move.py", line 47, in _compute_qr_code_str
    qr_code_str = move._l10n_sa_get_qr_code(move.journal_id, xml_content, b64decode(x509_cert),
  File "/odoo3/odoo3-server/addons/l10n_sa_edi/models/account_move.py", line 115, in _l10n_sa_get_qr_code
    signature_enc = self._l10n_sa_get_qr_code_encoding(7, signature.encode())
AttributeError: 'bool' object has no attribute 'encode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo3/odoo3-server/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/odoo3/odoo3-server/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo3/odoo3-server/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/odoo3/odoo3-server/addons/account/models/ir_actions_report.py", line 61, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_actions_report.py", line 820, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/odoo3/odoo3-server/addons/account_edi_ubl_cii/models/ir_actions_report.py", line 58, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/odoo3/odoo3-server/addons/account_edi/models/ir_actions_report.py", line 14, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/odoo3/odoo3-server/addons/account/models/ir_actions_report.py", line 20, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_actions_report.py", line 709, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, res_ids_wo_stream, data=data)[0]
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_actions_report.py", line 897, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_actions_report.py", line 624, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_ui_view.py", line 2127, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/odoo3/odoo3-server/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/odoo3/odoo3-server/odoo/addons/base/models/ir_qweb.py", line 581, in _render
    result = ''.join(rendering)
  File "&lt;662&gt;", line 110, in template_662
  File "&lt;662&gt;", line 92, in template_662_content
  File "&lt;662&gt;", line 80, in template_662_t_call_0
  File "&lt;756&gt;", line 2303, in template_756
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'bool' object has no attribute 'encode'
Template: l10n_gcc_invoice.arabic_english_invoice
Path: /t/t/t[4]/p/img
Node: &lt;img t-if="o.l10n_sa_qr_code_str" style="display:block;" t-att-src="\'/report/barcode/?barcode_type=%s&amp;amp;value=%s&amp;amp;width=%s&amp;amp;height=%s\'%(\'QR\', quote_plus(o.l10n_sa_qr_code_str), 200, 200)"/&gt;
pos-zatca-error.txt
Displaying pos-zatca-error.txt.

**Expected behavior :** 
To send the invoice to ZATCA 
------------------------- 
I tested also in V17 but the same problem with more simple error 
This video explain https://drive.google.com/file/d/1y3icsqj63av8v6PVaIvyGaxyxQ7my6s8/view

**Background demo:** 
Firstly, ZATCA module was not able to send invoices to ZATCA correctly because of the problem of time
https://zatca1.discourse.group/t/warning-time-on-qr-code-does-not-match-with-invoice-issue-time-ksa-25/823

After some fixed by Odoo, in the last update (until date of this post) the time problem fixed but the above problem (invoicing via POS) came.
