### ISSUE TITLE
Error when use wkhtmltopdf 0.12.4 with odoo 9

### ISSUE THREAD

**Issue by juniorkid** [odoo/odoo#14908]
I have error in below:
```
odoo Server Error
Traceback (most recent call last):
  File "/Users/tanapol/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/Users/tanapol/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/Users/tanapol/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=data, context=context)
  File "/Users/tanapol/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/tanapol/odoo/addons/report/models/report.py", line 269, in get_pdf
    context
  File "/Users/tanapol/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/tanapol/odoo/addons/report/models/report.py", line 443, in _run_wkhtmltopdf
    head_file.write(headers[index])
IndexError: list index out of range
```
it happen when i install wkhtmltopdf 0.12.4.
My os is OSX. Please help me.

**Comment by jlong01** [comment]
You might need to change to wkhtmltopdf 0.12.1 instead but also see this: http://stackoverflow.com/questions/37569444/qweb-indexerror-list-index-out-of-range

**Comment by Yenthe666** [comment]
Hi @juniorkid,

Thanks for your report.
it is indeed the case that 0.12.4 is not supported for Odoo, please downgrade to 0.12.1.

Regards,
Yenthe

**Comment by Muhammad105** [comment]
I have 0.21.1, but still same issue.
