### ISSUE TITLE
[8.0] Odoo error Division By Zero

### ISSUE THREAD

**Issue by rayer91** [odoo/odoo#14904]
Impacted versions: **8.0**

Steps to reproduce:
- Open edit product template view 
- Product on hand count > 0
- Sale count > 0

Current behavior:
Odoo server Error
Division by Zero

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3370, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/odoo-server/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/odoo-server/addons/sale/sale.py", line 1383, in _sales_count
    res[template.id] = sum([p.sales_count for p in template.product_variant_ids])
  File "/opt/odoo/odoo-server/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 928, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3246, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3370, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/odoo-server/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/odoo-server/addons/sale/sale.py", line 1363, in _sales_count
    for group in self.pool['sale.report'].read_group(cr, uid, domain, ['product_id', 'product_uom_qty'], ['product_id'], context=context):
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 2158, in read_group
    data_dict = {d['id']: d for d in self.read(cr, uid, data_ids, many2onefields, context=context)}
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3315, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: division by zero
```

**Comment by rayer91** [comment]
I can turn off the sale count with the code above and the error disappear.

``` 
class product_product(models.Model):
    _inherit = 'product.product'

    def _sales_count_override(self, cr, uid, ids, field_name, arg, context=None):
        #r = dict.fromkeys(ids, 0)
        #domain = [
        #    ('state', 'in', ['confirmed', 'done']),
        #    ('product_id', 'in', ids),
        #]
        # I think there are the issue
        #for group in self.pool['sale.report'].read_group(cr, uid, domain, ['product_id', 'product_uom_qty'], ['product_id'], context=context):
            #r[group['product_id'][0]] = group['product_uom_qty']
        r = 0
        return r

    _columns = {
        'sales_count': fields.function(_sales_count_override, string='# Sales', type='integer'),

    }
```

**Comment by gerisg** [comment]
Could you fix it?

**Comment by rayer91** [comment]
I couldn't fixed it. I was just turned off sale count on product template view.

**Comment by gerisg** [comment]
Hi rayer91, good news. I fixed this error.

**Problem**

"sale_report" is a postgresql [VIEW](https://www.postgresql.org/docs/9.2/static/sql-createview.html). 
You can see definition of sale_report view in:
> /usr/lib/python2.7/dist-packages/openerp/addons/sale/report/sale_report.py

Follow lines have possible division by zero errors:
_sum(l.product_uom_qty / **u.factor * u2.factor**) AS product_uom_qty,
sum(l.product_uom_qty * l.price_unit / **cr.rate** * (100.0 - l.discount) / 100.0) AS price_total,_

**Solution**

Add conditionals expressions to avoid zero values [NULLIF](https://www.postgresql.org/docs/9.4/static/functions-conditional.html#FUNCTIONS-NULLIF).

My Odoo installation got zero values in **cr.rate**. I updated **sale_report** view as follow:
```
CREATE or REPLACE VIEW sale_report as (
WITH currency_rate (currency_id, rate, date_start, date_end) AS (
SELECT r.currency_id, r.rate, r.name AS date_start,
(SELECT name FROM res_currency_rate r2
WHERE r2.name > r.name AND
r2.currency_id = r.currency_id
ORDER BY r2.name ASC
LIMIT 1) AS date_end
FROM res_currency_rate r
)
SELECT min(l.id) as id,
l.product_id as product_id,
t.uom_id as product_uom,
sum(l.product_uom_qty / u.factor * u2.factor) as product_uom_qty,
sum(l.product_uom_qty * l.price_unit / NULLIF(cr.rate, 0) * (100.0-l.discount) / 100.0) as price_total,
count(*) as nbr,
s.date_order as date,
s.date_confirm as date_confirm,
s.partner_id as partner_id,
s.user_id as user_id,
s.company_id as company_id,
extract(epoch from avg(date_trunc('day',s.date_confirm)-date_trunc('day',s.create_date)))/(24*60*60)::decimal(16,2) as delay,
l.state,
t.categ_id as categ_id,
s.pricelist_id as pricelist_id,
s.project_id as analytic_account_id,
s.section_id as section_id
FROM (sale_order_line l
join sale_order s on (l.order_id=s.id)
left join product_product p on (l.product_id=p.id)
left join product_template t on (p.product_tmpl_id=t.id)
left join product_uom u on (u.id=l.product_uom)
left join product_uom u2 on (u2.id=t.uom_id)
left join product_pricelist pp on (s.pricelist_id = pp.id)
join currency_rate cr on (cr.currency_id = pp.currency_id and
cr.date_start <= coalesce(s.date_order, now()) and
(cr.date_end is null or cr.date_end > coalesce(s.date_order, now()))))
GROUP BY l.product_id,
l.order_id,
t.uom_id,
t.categ_id,
s.date_order,
s.date_confirm,
s.partner_id,
s.user_id,
s.company_id,
l.state,
s.pricelist_id,
s.project_id,
s.section_id
)
``` 
I dropped the view before create it again.

Feel free to ask me, if I can to help you.

**Comment by nick2474** [comment]
In my case the issues was solved because the local currency CRC, was set in 0. I changed to 1.0000 and the issue was solved.

**Comment by Yenthe666** [comment]
Hi @rayer91 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
