### ISSUE TITLE
[10.0] Error for xmlrpc search_read method for product.template model

### ISSUE THREAD

**Issue by techspawn** [odoo/odoo#14939]
Impacted versions: Odoo version 10

Steps to reproduce: Install eCommerce (Technical Name = website_sale). 
When xmlrpc search_read method for product.template model is called error occurred.

Current behavior: 
2017-01-05 06:28:35,260 11208 ERROR connector_v10 odoo.http: object unbound
Traceback (most recent call last):
  File "odoo-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "odoo-server/odoo/service/model.py", line 38, in dispatch
    res = fn(db, uid, *params)
  File "odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo-server/odoo/service/model.py", line 182, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "odoo-server/odoo/service/model.py", line 171, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "odoo-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "odoo-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "odoo-server/odoo/models.py", line 3002, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "odoo-server/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo-server/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "odoo-server/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "odoo-server/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "odoo-server/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "odoo-server/addons/website_sale/models/product.py", line 147, in _website_price
    p.website_price = p.product_variant_id.website_price
  File "odoo-server/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "odoo-server/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "odoo-server/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "odoo-server/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "odoo-server/addons/website_sale/models/product.py", line 193, in _website_price
    pricelist = self.env['website'].get_current_website().get_current_pricelist()
  File "odoo-server/addons/website/models/website.py", line 395, in get_current_website
    domain_name = request.httprequest.environ.get('HTTP_HOST', '').split(':')[0]
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 135, in _lookup
    raise RuntimeError('object unbound')
RuntimeError: object unbound

Expected behavior: Should fetch Expected product information. 

Video/Screenshot link (optional):
![screenshot from 2017-01-05 12 02 56](https://cloud.githubusercontent.com/assets/4945969/21671163/8b047e1a-d33f-11e6-86a7-8ade61cd2d4e.png)

**Comment by jadavraviodoo217** [comment]
fixed by read mehods
