### ISSUE TITLE
Internal Server Error after update discuss, view workflow? 

### ISSUE THREAD

**Issue by pstisoluciones** [odoo/odoo#14931]
Impacted versions: 9.0 Enterprise

Steps to reproduce: update module Discuss, after that crash my server. 
Current behavior: Cant enter to the server, only check log in console. After using ./odoo.py -u all -d psti_soluciones, I can see my server but I cant enter to the database.
Idk If I can put here. (If not please say me for delete or ignore or something like that). 
Do you have any Ideas? Thanks in advance.

Track.

odoo@pstisoluciones:~/odoo-server$ ./odoo.py -u all -d psti_soluciones
2017-01-03 14:46:40,264 9998 INFO ? openerp: OpenERP version 9.0c
2017-01-03 14:46:40,264 9998 INFO ? openerp: addons paths:
['/odoo/.local/share/Odoo/addons/9.0', u'/odoo/odoo-server/openerp/addons', u'/odoo/odoo-server/addons']
2017-01-03 14:46:40,264 9998 INFO ? openerp: database:default@default:default
2017-01-03 14:46:40,322 9998 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069 Exception in thread openerp.service.httpd:
Traceback (most recent call last):

File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()  
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)  
  File "/odoo/odoo-server/openerp/service/server.py", line 247, in http_thread  
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)  
  File "/odoo/odoo-server/openerp/service/server.py", line 106, in __init__
    handler=RequestHandler)    
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 410, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)   
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()  
  File "/odoo/odoo-server/openerp/service/server.py", line 116, in server_bind  
    super(ThreadedWSGIServerReloadable, self).server_bind()  
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)  
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind  
    self.socket.bind(self.server_address)  
  **File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)  
error: [Errno 98] Address already in use  
2017-01-03 14:46:40,333 9998 INFO psti_soluciones openerp.modules.loading: loading 1 modules...
2017-01-03 14:46:40,437 9998 INFO psti_soluciones openerp.modules.module: module base: creating or updating database tables
2017-01-03 14:46:41,916 9998 INFO psti_soluciones openerp.modules.loading: loading base/base_data.xml
2017-01-03 14:46:41,930 9998 INFO psti_soluciones openerp.modules.loading: loading base/res/res_currency_data.xml
2017-01-03 14:46:42,061 9998 INFO psti_soluciones openerp.modules.loading: loading base/res/res_country_data.xml
2017-01-03 14:46:42,257 9998 INFO psti_soluciones openerp.modules.loading: loading base/security/base_security.xml
2017-01-03 14:46:43,568 9998 INFO psti_soluciones openerp.modules.loading: loading base/base_menu.xml
2017-01-03 14:46:43,668 9998 INFO psti_soluciones openerp.modules.loading: loading base/res/res_config.xml
2017-01-03 14:46:43,693 9998 INFO psti_soluciones openerp.modules.loading: loading base/res/res.country.state.csv
2017-01-03 14:46:43,792 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_actions.xml
2017-01-03 14:46:43,936 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [137843, 137844]
2017-01-03 14:46:44,160 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_config_parameter_view.xml
2017-01-03 14:46:44,198 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_cron_view.xml
2017-01-03 14:46:44,252 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_filters.xml
2017-01-03 14:46:44,305 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_mail_server_view.xml
2017-01-03 14:46:44,350 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_model_view.xml
2017-01-03 14:46:44,403 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [137829]
2017-01-03 14:46:44,449 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [137837]
2017-01-03 14:46:44,607 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_attachment_view.xml
2017-01-03 14:46:44,642 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [137841]
2017-01-03 14:46:44,660 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_rule_view.xml
2017-01-03 14:46:44,668 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [137839]
2017-01-03 14:46:44,711 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_sequence_view.xml
2017-01-03 14:46:44,758 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_translation_view.xml
2017-01-03 14:46:44,802 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_ui_menu_view.xml
2017-01-03 14:46:44,846 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_ui_view_view.xml
2017-01-03 14:46:44,936 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_values_view.xml
2017-01-03 14:46:45,004 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_autovacuum.xml
2017-01-03 14:46:45,008 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_model_report.xml
2017-01-03 14:46:45,016 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.values records with IDs: [285]
2017-01-03 14:46:45,020 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/report_ir_model.xml
2017-01-03 14:46:45,037 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_logging_view.xml
2017-01-03 14:46:45,080 9998 INFO psti_soluciones openerp.modules.loading: loading base/ir/ir_qweb.xml
2017-01-03 14:46:45,089 9998 INFO psti_soluciones openerp.models.unlink: User #1 deleted ir.translation records with IDs: [162380, 162381, 162382, 162383]
2017-01-03 14:46:45,096 9998 INFO psti_soluciones openerp.modules.loading: loading base/workflow/workflow_view.xml
2017-01-03 14:46:45,155 9998 INFO psti_soluciones openerp.addons.base.ir.ir_ui_view: El elemento '' no puede ser localizado en la vista padre

Error context: View workflow.tree [view_id: 82, xml_id: base.view_workflow_tree, model: workflow, parent_id: 236] **
2017-01-03 14:46:45,155 9998 ERROR psti_soluciones openerp.modules.registry: Failed to load registry Traceback (most recent call last):

File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/odoo/odoo-server/openerp/modules/loading.py", line 279, in load_modules loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
File "/odoo/odoo-server/openerp/modules/loading.py", line 156, in load_module_graph _load_data(cr, module_name, idref, mode, kind='data')
File "/odoo/odoo-server/openerp/modules/loading.py", line 98, in _load_data tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/odoo/odoo-server/openerp/tools/convert.py", line 849, in convert_file convert_xml_import(cr, module, fp, idref, mode, noupdate, report) File "/odoo/odoo-server/openerp/tools/convert.py", line 932, in convert_xml_import obj.parse(doc.getroot(), mode=mode)
File "/odoo/odoo-server/openerp/tools/convert.py", line 799, in parse self.parse(rec, mode) File "/odoo/odoo-server/openerp/tools/convert.py", line 802, in parse self._tags[rec.tag](self.cr, rec, de, mode=mode)
File "/odoo/odoo-server/openerp/tools/convert.py", line 705, in _tag_record id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1119, in _update model_obj.write(cr, uid, [res_id], values, context=context)
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 383, in write context) File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/api.py", line 381, in old_api result = method(recs, *args, **kwargs)
File "/odoo/odoo-server/openerp/models.py", line 3846, in write self._write(old_vals) File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper return new_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/api.py", line 574, in new_api result = method(self._model, cr, uid, self.ids, *args, **old_kwargs) File "/odoo/odoo-server/openerp/models.py", line 4033, in _write recs._validate_fields(vals)
File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper return new_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/models.py", line 1281, in _validate_fields raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

**

Details of the "problem": The element ''cant be localized on the parent view
**

**

Error context: View workflow.tree [view_id: 82, xml_id:
base.view_workflow_tree, model: workflow, parent_id: 236] None" while parsing /odoo/odoo-server/openerp/addons/base/workflow/workflow_view.xml:59, near
**

<record id="view_workflow_tree" model="ir.ui.view">
      <field name="name">workflow.tree</field>
      <field name="model">workflow</field>
      <field name="arch" type="xml">
        <tree string="Workflow">
          <field name="name"/>
          <field name="osv"/>
          <field name="on_create"/>
        </tree>
      </field>
    </record>
2017-01-03 14:46:45,157 9998 CRITICAL psti_soluciones openerp.service.server: Failed to initialize database psti_soluciones. Traceback (most recent call last):

File "/odoo/odoo-server/openerp/service/server.py", line 893, in preload_registries registry = RegistryManager.new(dbname, update_module=update_module)
File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/odoo/odoo-server/openerp/modules/loading.py", line 279, in load_modules loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
File "/odoo/odoo-server/openerp/modules/loading.py", line 156, in load_module_graph _load_data(cr, module_name, idref, mode, kind='data')
File "/odoo/odoo-server/openerp/modules/loading.py", line 98, in _load_data tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/odoo/odoo-server/openerp/tools/convert.py", line 849, in convert_file convert_xml_import(cr, module, fp, idref, mode, noupdate, report) File "/odoo/odoo-server/openerp/tools/convert.py", line 932, in convert_xml_import obj.parse(doc.getroot(), mode=mode)
File "/odoo/odoo-server/openerp/tools/convert.py", line 799, in parse self.parse(rec, mode)
File "/odoo/odoo-server/openerp/tools/convert.py", line 802, in parse self._tags[rec.tag](self.cr, rec, de, mode=mode)
File "/odoo/odoo-server/openerp/tools/convert.py", line 705, in _tag_record id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1119, in _update model_obj.write(cr, uid, [res_id], values, context=context)
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 383, in write context)
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/api.py", line 381, in old_api result = method(recs, *args, **kwargs)
File "/odoo/odoo-server/openerp/models.py", line 3846, in write self._write(old_vals)
File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper return new_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/api.py", line 574, in new_api result = method(self._model, cr, uid, self.ids, *args, **old_kwargs) File "/odoo/odoo-server/openerp/models.py", line 4033, in _write recs._validate_fields(vals)
File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper return new_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/models.py", line 1281, in _validate_fields raise ValidationError('\n'.join(errors)) ParseError: "Invalid view definition
Detalles de error: El elemento '' no puede ser localizado en la vista padre

Error context: View workflow.tree [view_id: 82, xml_id: base.view_workflow_tree, model: workflow, parent_id: 236] None" while parsing /odoo/odoo-server/openerp/addons/base/workflow/workflow_view.xml:59, near
<record id="view_workflow_tree" model="ir.ui.view">
      <field name="name">workflow.tree</field>
      <field name="model">workflow</field>
      <field name="arch" type="xml">
        <tree string="Workflow">
          <field name="name"/>
          <field name="osv"/>
          <field name="on_create"/>
        </tree>
      </field>
    </record>
2017-01-03 14:47:59,925 9998 INFO psti_soluciones openerp.service.server: Initiating shutdown 2017-01-03 14:47:59,925 9998 INFO psti_soluciones openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

Expected behavior: Trying to fix without reinstall.

Video/Screenshot link (optional):

**Comment by pstisoluciones** [comment]
Well nothing, I will try to update to odoo10 and will see if fix the module base, I really dont care the Database, because is on production, But I want to save the "addons". What about if I follow your tutorial for fetch the new version of git?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
