### ISSUE TITLE
Installation of extension failes if a record is defined with a binding_model_id 'model_mrp_bom'

### ISSUE THREAD

**Issue by MarcSchaetz** [odoo/odoo#149619]
Impacted versions:
15.0

Steps to reproduce:
1. Create a new extension with an xml template (see Listing 1)
2. Try installing the extension

Current behavior:
The extension can not be installed because of a ValueError.

Expected behavior:
The extension should install just fine.

---

I'm currently creating an extension for our company and ran into the issue of not being able to install the
extension if the reports record has the following line.
```xml
<field name="binding_model_id" ref="model_mrp_bom" />
```
It seems that odoo searches for an entry in `ir.model.data` with an external id prefixed with my extension's name.

In the odoo forum there is a similar case from eight months ago, but without any solution. 
https://www.odoo.com/de_DE/forum/hilfe-1/can-t-get-report-to-appear-on-print-menu-after-moving-from-report-to-record-224035

I checked if my xml code was correct, because the last error in the stack trace shows a ParseError. The code however seems right.
The installation of the extension also succeeds if I remove the mentioned line.

I also created a new database with demo data to make sure the database is not the source of failure. But the same error pops up. 

The template and the stacktrace are listed below.
---

listings:
<details>
<summary>Listing 1: XML Template</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<odoo>

	<record id="action_pref_calculation_report" model="ir.actions.report">
		<field name="name">Preferential Calculation</field>
		<field name="model">mrp.bom</field>
		<field name="report_type">qweb-pdf</field>
		<field name="report_name">wz_supplier_declaration.preferential_calculation</field>
		<field name="binding_model_id" ref="model_mrp_bom" />
	</record>


	<template id="preferential_calculation">
		<t t-call="web.html_container">
			<t t-call="web.external_layout">
				<div class="page">
				</div>
			</t>
		</t>
	</template>

</odoo>

```

</details>

<details>
<summary>Listing 2: Error trace</summary>

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f81e839a8b0>, 'wz_supplier_declaration.model_mrp_bom')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 567, in _tag_record
    f_val = self.id_get(f_ref, raise_if_not_found=nodeattr2bool(rec, 'forcecreate', True))
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 666, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 672, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1970, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-37>", line 2, in _xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1963, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: wz_supplier_declaration.model_mrp_bom

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1328, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 469, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-76>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 580, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 748, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 814, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 734, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 696, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/wz_supplier_declaration/report/mrp_bom_structure.xml:4, somewhere inside
<record id="action_pref_calculation_report" model="ir.actions.report">
			<field name="name">Preferential Calculation</field>
			<field name="model">mrp.bom</field>
			<field name="report_type">qweb-pdf</field>
			<field name="report_name">wz_supplier_declaration.preferential_calculation</field>
			<field name="binding_model_id" ref="model_mrp_bom"/>
		</record>

```

</details>

**Comment by gdgellatly** [comment]
ref is an xml_id. Probably mrp.model_mrp_bom works, not that it makes sense, but it will.

**Comment by MarcSchaetz** [comment]
That indeed did the trick. Thanks a lot.
