### ISSUE TITLE
Listing models, Odoo Server Error - builtins.KeyError  on "ir.min.cron.mixin" model

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#150334]
# Impacted versions:
v17

# Steps to reproduce:

Make a query `search_read` on the model "ir.model"

# Current behavior:

An error occurred :

```python
Odoo Server Error - builtins.KeyError                                                             
  Traceback (most recent call last):                                                                
    File "/home/odoo/src/odoo/odoo/http.py", line 1722, in _serve_db                                
      return service_model.retrying(self._serve_ir_http, self.env)                                  
    File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying                         
      result = func()                                                                               
    File "/home/odoo/src/odoo/odoo/http.py", line 1749, in _serve_ir_http                           
      response = self.dispatcher.dispatch(rule.endpoint, args)                                      
    File "/home/odoo/src/odoo/odoo/http.py", line 1953, in dispatch                                 
      result = self.request.registry['ir.http']._dispatch(endpoint)                                 
    File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch           
      result = endpoint(**request.params)                                                           
    File "/home/odoo/src/odoo/odoo/http.py", line 722, in route_wrapper                             
      result = endpoint(self, *args, **params_ok)                                                   
    File "/home/odoo/src/odoo/odoo/addons/base/controllers/rpc.py", line 158, in jsonrpc            
      return dispatch_rpc(service, method, args)                                                    
    File "/home/odoo/src/odoo/odoo/http.py", line 388, in dispatch_rpc                              
      return dispatch(method, params)                                                               
    File "/home/odoo/src/odoo/odoo/service/model.py", line 37, in dispatch                          
      res = execute_kw(db, uid, *params[3:])                                                        
    File "/home/odoo/src/odoo/odoo/service/model.py", line 59, in execute_kw                        
      return execute(db, uid, obj, method, *args, **kw or {})                                       
    File "/home/odoo/src/odoo/odoo/service/model.py", line 65, in execute                           
      res = execute_cr(cr, uid, obj, method, *args, **kw)                                           
    File "/home/odoo/src/odoo/odoo/service/model.py", line 50, in execute_cr                        
      result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)                     
    File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying                         
      result = func()                                                                               
    File "/home/odoo/src/odoo/odoo/api.py", line 462, in call_kw                                    
      result = _call_kw_model(method, model, args, kwargs)                                          
    File "/home/odoo/src/odoo/odoo/api.py", line 435, in _call_kw_model                             
      result = method(recs, *args, **kwargs)                                                        
    File "/home/odoo/src/odoo/odoo/models.py", line 5730, in search_read                            
      return records._read_format(fnames=fields, **read_kwargs)                                     
    File "/home/odoo/src/odoo/odoo/models.py", line 3742, in _read_format                           
      vals[name] = convert(record[name], record, use_display_name)                                  
    File "/home/odoo/src/odoo/odoo/models.py", line 6577, in __getitem__                            
      return self._fields[key].__get__(self, type(self))                                            
    File "/home/odoo/src/odoo/odoo/fields.py", line 2886, in __get__                                
      return super().__get__(records, owner)                                                        
    File "/home/odoo/src/odoo/odoo/fields.py", line 1206, in __get__                                
      self.compute_value(recs)                                                                      
    File "/home/odoo/src/odoo/odoo/fields.py", line 1388, in compute_value                          
      records._compute_field_value(self)                                                            
    File "/home/odoo/src/odoo/odoo/models.py", line 4858, in _compute_field_value                   
      fields.determine(field.compute, self)                                                         
    File "/home/odoo/src/odoo/odoo/fields.py", line 101, in determine                               
      return needle(*args)                                                                          
    File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 213, in _inherited_models  
      parent_names = list(self.env[model.model]._inherits)                                          
    File "/home/odoo/src/odoo/odoo/api.py", line 526, in __getitem__                                
      return self.registry[model_name](self, (), ())                                                
    File "/home/odoo/src/odoo/odoo/modules/registry.py", line 213, in __getitem__                   
      return self.models[model_name]                                                                
  KeyError: 'ir.min.cron.mixin'
```

BTW Excluding this model from the listing (using `not in`) avoid the error.

**Comment by monty241** [comment]
Dito on 17.0 on Odoo.sh (same call stack): `hr.contract.employee.report` (see https://forums.invantive.com/t/itgenodo047-op-hr-contract-employee-report-bij-openen-database/4875).
