### ISSUE TITLE
[10.0] UnicodeDecodeError after database initialization

### ISSUE THREAD

**Issue by hgminh-pk** [odoo/odoo#15057]
**UnicodeDecodeError after database initialization**

Impacted versions:

 - 10.0

Steps to reproduce:

 1. Install a fresh Ubuntu 16.04
 2. Install postgresql using `apt install postgresql-9.5`
 3. Install anaconda for python
 4. Obtain odoo 10 source code in branch 10.0
 5. Run odoo, create new database

Current behavior:

 - Odoo response with `500 Internal Server`

```
2017-01-13 08:04:07,610 12953 INFO odoo10 odoo.addons.base.ir.ir_http: Generating routing map
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
Logged from file assetsbundle.py, line 385
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
Logged from file assetsbundle.py, line 385
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
Logged from file assetsbundle.py, line 385
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
Logged from file assetsbundle.py, line 385
2017-01-13 08:04:11,005 12953 INFO odoo10 werkzeug: 127.0.0.1 - - [13/Jan/2017 08:04:11] "GET /web/ HTTP/1.1" 500 -
2017-01-13 08:04:11,119 12953 ERROR odoo10 werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/hgminh/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/hgminh/Documents/odoo-10.0/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/hgminh/Documents/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/hgminh/Documents/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/home/hgminh/anaconda2/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/home/hgminh/Documents/odoo-10.0/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/hgminh/Documents/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 327, in checked_call
    result.flatten()
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 1257, in flatten
    self.response.append(self.render())
  File "/home/hgminh/Documents/odoo-10.0/odoo/http.py", line 1250, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/hgminh/Documents/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/hgminh/Documents/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_173_11
  File "<template>", line 3, in body_call_content_10
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)

Error to render compiling AST
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)
Template: 173
Path: /templates/t/t/t[1]/t[9]
Node: <t t-call="web.webclient_script"/>
```

**Note**: I try to install using `deb` file but it failed too.

**Comment by lem8r** [comment]
Probably your template1 is not in utf-8
See https://gist.github.com/ffmike/877447

**Comment by hgminh-pk** [comment]
My template1 is already in utf-8

```
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 odoo10    | hgminh   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
```

**Comment by hgminh-pk** [comment]
I find out that it is because I did not install `node` :stuck_out_tongue: 

However, Odoo failed to report that error

```
Traceback (most recent call last):
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/hgminh/Documents/odoo-10.0/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/home/hgminh/anaconda2/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
```

due to the error message contain non-ascii character (left/right single quotation mark)

```
/usr/bin/env: ‘node’: No such file or directory
```

**Comment by Yenthe666** [comment]
Hi @hgminh-pk,

Thank you for your report.
It is nice to see you've figured out the issue on your own. As you where missing a dependency I believe I can close this issue.
@mart-e perhaps there should be encoding on this error?

**Comment by mart-e** [comment]
Well actually it is indeed a missing dependency. The [source install instructions](https://www.odoo.com/documentation/10.0/setup/install.html#installing-dependencies) mention you need lessc via node.

You however raise a valid point the error was not properly encoded.
Done at d126529d1bf

**Comment by Kiplangatdan** [comment]
Installing node actually helped. Running Linux Mint 18.

**Comment by ayamemi** [comment]
Odoo Server Error

Traceback (most recent call last):
  File "O:\odoo10\falinwa_branch\report\controllers\main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "O:\odoo10\odoo\odoo\http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "O:\odoo10\falinwa_branch\report\controllers\main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "O:\odoo10\falinwa_branch\report\models\report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "O:\odoo10\falinwa_branch\report\models\report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "O:\odoo10\falinwa_branch\report\models\report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_ui_view.py", line 1037, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "O:\odoo10\falinwa_branch\web_editor\models\ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_ui_view.py", line 1057, in render
    return self.env[engine].render(self.id, qcontext)
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_qweb\ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_qweb\qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_qweb\qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: 'NoneType' object is not callable
Traceback (most recent call last):
  File "O:\odoo10\odoo\odoo\addons\base\ir\ir_qweb\qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_781_223
  File "<template>", line 3, in body_call_content_222
  File "<template>", line 4, in foreach_221
TypeError: 'NoneType' object is not callable

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: 781
Path: /templates/t/t/t/t
Node: <t t-raw="translate_doc(doc_id, doc_model, 'partner_id.lang', 'fal_invoice_delivery_fee.fal_saleorder_document_idf')"/>

**Comment by mart-e** [comment]
@ayamemi please open a new issue for different problem and don't forget to explain how to reproduce this issue to be valid.

**Comment by ayamemi** [comment]
@mart-e i will do that, thanks for you welcome.
