### ISSUE TITLE
Failed to install buggy odoo, with sigapore as default during installation. +Attached Screenshot

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15078]
Impacted versions: 9.0 C

Steps to reproduce: Create new database from latest revision for 9.0.

Current behavior: 9.0

Expected behavior: odoo too buggy, please remove bugs.
```
Video/Screenshot link (optional):
tejas-partners@partners-2gb-sgp1-01:/opt/odoo$ tail -n 100 odoo9c-singapore-cluster.log 
    im = self.resize(size, resample)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1536, in resize
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 200, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 417, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
ParseError: "decoder zip not available" while parsing /opt/odoo/openerp/addons/base/base_data.xml:26, near
<record id="main_partner" model="res.partner" context="{'default_is_company': True}">
            <field name="name">My Company</field>
            <field name="company_id" eval="None"/>
            <field name="image" type="base64" file="base/static/img/main_partner-image.png"/>
            <field name="customer" eval="False"/>
            <field name="is_company" eval="True"/>
            <field name="street"/>
            <field name="city"/>
            <field name="zip"/>
            <field name="phone"/>
            <field name="email">info@yourcompany.com</field>
            <field name="website">www.yourcompany.com</field>
        </record>
2017-01-16 10:24:39,645 8615 ERROR hvs openerp.http: 
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/opt/odoo/openerp/service/common.py", line 29, in exp_authenticate
    res_users = openerp.registry(db)['res.users']
  File "/opt/odoo/openerp/__init__.py", line 50, in registry
    return modules.registry.RegistryManager.get(database_name)
  File "/opt/odoo/openerp/modules/registry.py", line 355, in get
    update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 281, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 705, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1119, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_partner.py", line 508, in write
    tools.image_resize_images(vals)
  File "/opt/odoo/openerp/tools/image.py", line 265, in image_resize_images
    avoid_resize_big=True, avoid_resize_medium=False, avoid_resize_small=False))
  File "/opt/odoo/openerp/tools/image.py", line 254, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/opt/odoo/openerp/tools/image.py", line 143, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/opt/odoo/openerp/tools/image.py", line 73, in image_resize_image
    image = image_resize_and_sharpen(image, size)
  File "/opt/odoo/openerp/tools/image.py", line 93, in image_resize_and_sharpen
    image.thumbnail(size, Image.ANTIALIAS)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1793, in thumbnail
    im = self.resize(size, resample)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1536, in resize
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 200, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 417, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
ParseError: "decoder zip not available" while parsing /opt/odoo/openerp/addons/base/base_data.xml:26, near
<record id="main_partner" model="res.partner" context="{'default_is_company': True}">
            <field name="name">My Company</field>
            <field name="company_id" eval="None"/>
            <field name="image" type="base64" file="base/static/img/main_partner-image.png"/>
            <field name="customer" eval="False"/>
            <field name="is_company" eval="True"/>
            <field name="street"/>
            <field name="city"/>
            <field name="zip"/>
            <field name="phone"/>
            <field name="email">info@yourcompany.com</field>
            <field name="website">www.yourcompany.com</field>
        </record>
```

![screenshot from 2017-01-16 16-00-35](https://cloud.githubusercontent.com/assets/311413/21979462/f6eb68dc-dc04-11e6-8527-29e0e400402d.png)

**Comment by mart-e** [comment]
Hello,

Are you sure you have pillow installed instead of PIL?

```bash
sudo pip uninstall PIL
sudo pip install pillow 
```
