### ISSUE TITLE
[17.0][BUG] Product Configurator breaks on re-open with empty custom value attributes

### ISSUE THREAD

**Issue by john-herholz-dt** [odoo/odoo#151015]
Impacted versions:
17.0

Steps to reproduce:
See video or:
- Create attribute with custom value
- Add this attribute to a product together with other options
- Create quotation with this product
- On re-Open an error is shown

Current behavior:
- You cannot re-open the product configurator for a product with a custom value option together with other options

Expected behavior:
- Product Configurator can be used

Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/102949895/a78ce42b-168f-4259-a28e-1c902ebfa015

Error message:
```UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:916:101)
    at App.handleError (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:1006:19)

Caused by: TypeError: Cannot set properties of undefined (setting 'customValue')
    at ProductConfiguratorDialog._updatePTAVCustomValue (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:26322:203)
    at ProductConfiguratorDialog.<anonymous> (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:26310:780)
    at async Promise.all (index 0)
    at async ComponentNode.initiateRender (https://57040954-17-0-all.runbot163.odoo.com/web/assets/cb7ba64/web.assets_web.min.js:1005:36)```

**Comment by john-herholz-dt** [comment]
A similar issue was reported by me last year: https://github.com/odoo/odoo/issues/125792

**Comment by john-herholz-dt** [comment]
This was fixed by this commit:

https://github.com/odoo/odoo/commit/212b466adc2d0b26a724b6b31bd761bc1ab98a3d
