### ISSUE TITLE
Payslip Details print Error in Payroll. Odoo 10

### ISSUE THREAD

**Issue by mikeross6233m** [odoo/odoo#15119]
Impacted versions: Odoo 10

Steps to reproduce: 
1. Install Payroll with Indian Accounting.
2. Generate a payslip, compute it.
3. Click on Print->Payslip Details

Current behavior:
```
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/opt/odoo/odoo-10.0/addons/l10n_in_hr_payroll/report/report_payslip_details.py", line 21, in render_html
    return self.env['report'].render('l10n_in_hr_payroll.report_payslipdetails', docargs)
  File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: Unknown format 'monetary'
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_712_772
  File "<template>", line 3, in body_call_content_771
  File "<template>", line 4, in foreach_770
  File "<template>", line 5, in body_call_content_769
  File "<template>", line 53, in foreach_768
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 370, in format
    raise ValueError("Unknown format '%s'" % (formating,))
ValueError: Unknown format 'monetary'

Error to render compiling AST
ValueError: Unknown format 'monetary'
Template: 712
Path: /templates/t/t/t/t/div/table[2]/tbody/t/t[1]/tr/td[3]/strong/span
Node: <span t-esc="format(h['total'], 'monetary', o.company_id.currency_id)"/>
```
Expected behavior:

Payslip details should have been downloaded in pdf format.

Video/Screenshot link (optional):

**Comment by djpyoo** [comment]
I also get the same error in all my Odoo installations. Any solution?

**Comment by Yenthe666** [comment]
Hi @mikeross6233m,

Thank you for your report.
I just tried to reproduce this on the latest source code and I can print the report without any issues.
@djpyoo and @mikeross6233m could you both try again with the latest source code or try to reproduce this on a runbot (runbot.odoo.com)?
If you still can reproduce it please post back with more information on how to exactly trigger this.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @mikeross6233m,

I'm closing this bug report as there has been no feedback in over a month.
If you can still reproduce this on the latest Odoo then please post back with more information and I'll reopen this issue.

Regards,
Yenthe

**Comment by RishabhJadia** [comment]
I also get the same error on printing the payslip details.

**Comment by Hyperthinkk** [comment]
I am still having this error. Please reopen this thread

**Comment by Yenthe666** [comment]
Can you guys reproduce it on a runbot? Can you add more info and a screenshot please?

**Comment by Hyperthinkk** [comment]
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/odoo/odoo-server/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/odoo/odoo-server/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/odoo/odoo-server/addons/l10n_in_hr_payroll/report/report_payslip_details.py", line 21, in render_html
    return self.env['report'].render('l10n_in_hr_payroll.report_payslipdetails', docargs)
  File "/odoo/odoo-server/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1036, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1056, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: Unknown format 'monetary'
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_984_9334
  File "<template>", line 3, in body_call_content_9333
  File "<template>", line 4, in foreach_9332
  File "<template>", line 5, in body_call_content_9331
  File "<template>", line 53, in foreach_9330
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 370, in format
    raise ValueError("Unknown format '%s'" % (formating,))
ValueError: Unknown format 'monetary'

Error to render compiling AST
ValueError: Unknown format 'monetary'
Template: 984
Path: /templates/t/t/t/t/div/table[2]/tbody/t/t[1]/tr/td[3]/strong/span
Node: <span t-esc="format(h['total'], 'monetary', o.company_id.currency_id)"/>

**Comment by hilarak** [comment]
This bug is actually solved. look here
[https://github.com/odoo/odoo/commit/110613b2ccea313939f6ed6afe15ad6821fc1217](https://github.com/odoo/odoo/commit/110613b2ccea313939f6ed6afe15ad6821fc1217)

**Comment by bireumdione** [comment]
Hello can you help i got this erroe when i generate payslip


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 181, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 138, in get_html
    return report_model.render_html(docids, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/abstract_report.py", line 49, in render_html
    return self.env['report'].with_context(context).render(self._template, docargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 123, in render
    return view_obj.render_template(template, values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 249, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 323, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: can't adapt type 'hr.payslip.line'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 316, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_715_286
  File "<template>", line 3, in body_call_content_285
  File "<template>", line 4, in foreach_284
  File "<template>", line 221, in foreach_259
  File "/usr/lib/python2.7/dist-packages/odoo/addons/l10n_syscoa_payroll/report/syscoa_report_payslip.py", line 212, in get_rate_patronal
    rate = (payslip_line_comp[0].rate)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1017, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3074, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3018, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3142, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'hr.payslip.line'

Error to render compiling AST
ProgrammingError: can't adapt type 'hr.payslip.line'
Template: 715
Path: /templates/t/t/t/div/table[2]/tbody/tr/td[8]/span
Node: <span t-esc="get_rate_patronal(p)"/>
                                    

the code:
def get_rate_patronal(self, psline):
        env = odoo.api.Environment(self.cr, self.uid, {})
        psline_code_comp = psline.code + '_C'
        pooler = env['hr.payslip.line']
        payslip_line_comp_id = pooler.search([('slip_id', '=', psline.slip_id.id), ('code', '=', psline_code_comp)])
        payslip_line_comp = pooler.browse(payslip_line_comp_id)
        if payslip_line_comp:
            rate = (payslip_line_comp[0].rate)
            if round(float(rate), 2) == 100.00:
                return ''
            return formatl(rate, 2)
        return ''
