### ISSUE TITLE
[10.0] Send PO / RFQ by email server error

### ISSUE THREAD

**Issue by trapchik** [odoo/odoo#15114]
Impacted versions: 10.0

When I attempt to send a RFQ or PO by email to a supplier within odoo I encounter a server error, however I am able to send a quotation or invoice to the customers without any issues. 

Any assistance with this would be much appreciated.

Server Error: 
```
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/wizard/mail_compose_message.py", line 194, in send_mail_action
    return self.send_mail()
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/purchase/models/purchase.py", line 1094, in send_mail
    return super(MailComposeMessage, self.with_context(mail_post_autofollow=True)).send_mail(auto_commit=auto_commit)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/sale/wizard/mail_compose_message.py", line 17, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/account/models/account_invoice.py", line 1489, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/wizard/mail_compose_message.py", line 258, in send_mail
    **mail_values)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/models/mail_thread.py", line 1879, in message_post
    new_message = MailMessage.create(values)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/models/mail_message.py", line 723, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/models/mail_message.py", line 791, in _notify
    partners._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/models/res_partner.py", line 156, in _notify
    ('notify_email', '!=', 'none')])._notify_by_email(message, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/usr/local/lib/python2.7/site-packages/odoo-10.0.post20161230-py2.7.egg/odoo/addons/mail/models/res_partner.py", line 201, in _notify_by_email
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
KeyError: 'body'`
```

Thanks,

**Comment by trapchik** [comment]
Issue fixes, was caused by translations..
