### ISSUE TITLE
[10.0][Fleet] Server error when opening contract for vehicle when vehicle list is groupedby 

### ISSUE THREAD

**Issue by antonellaandreoni** [odoo/odoo#15154]
Impacted versions: 10.0

Steps to reproduce:
Group vehicle list by any variable (e.g. status)
Open a vehicle from the list
In vehicle page click on 'Contract'
This produces the error below.

Current behavior:
When I attempt to open a contract for vehicle when vehicle list is grouped by e.g. status
I obtain a server errror and need to log out and log in again.
This happens both in kanban and list view.

Expected behavior:
open the contract form

Server error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1911, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1939, in _read_group_raw
    annotated_groupbys = [self._read_group_process_groupby(gb, query) for gb in groupby_list]
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1752, in _read_group_process_groupby
    field_type = self._fields[split[0]].type
KeyError: u'state_id'

Any assistance with this would be much appreciated.

**Comment by Yenthe666** [comment]
Hi @antonellaandreoni,

Thank you for your report.
I've just tested this on the latest Odoo 10 and can confirm that this is a bug:
![image](https://cloud.githubusercontent.com/assets/6352350/22194676/10605f68-e144-11e6-9e4c-efac23be54cb.png)
@nim-odoo could you have a look at this?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Goob job @nim-odoo, thanks a lot!
