### ISSUE TITLE
PAD SERVER

### ISSUE THREAD

**Issue by nattanaiv** [odoo/odoo#151701]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by bayaderpack** [comment]
Same issue server is down or something cant do single thing

**Comment by bayaderpack** [comment]
This is log when I try to create new db 
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1798, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/odoo/src/odoo/saas-17.1/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1775, in _serve_ir_http
    return self._serve_ir_http(rule, args)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1783, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 2008, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 740, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 34, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 30, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/api.py", line 458, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.1/addons/website/models/website.py", line 634, in configurator_apply
    render, placeholders = _render_snippet(f'website.configurator_{page_code}_{snippet}')
  File "/home/odoo/src/odoo/saas-17.1/addons/website/models/website.py", line 605, in _render_snippet
    render = IrQweb._render(key, cta_data)
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/profiler.py", line 302, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_qweb.py", line 593, in _render
    rendering = render_template(irQweb, values)
  File "<None>", line 5, in not_found_template
ValueError: View 'website.configurator_pricing_s_comparisons' in website 1 not found

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://test131322131.odoo.com/web/assets/28ca7aa/web.assets_web.min.js:2909:163)
    at XMLHttpRequest.<anonymous> (https://test131322131.odoo.com/web/assets/28ca7aa/web.assets_web.min.js:2914:13)
    ```
