### ISSUE TITLE
[10.0] Javascript exception when creating a purchase order

### ISSUE THREAD

**Issue by JosefKaser** [odoo/odoo#15247]
Impacted versions:
odoo 10

Steps to reproduce:
Create a purchase order, select a supplier, click "Add an item", add one ore more items in the order line form view, click "Save & Close".

**_Important information:_**

```
<tree string="Purchase Order Lines" editable="bottom">
```

(line 212 in /addons/purchase/views/purchase_views.xml) has been changed with

```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <record id="xxx_purchase_order_form_list_details" model="ir.ui.view">
            <field name="name">xxx_purchase_order_form_list_details</field>
            <field name="model">purchase.order</field>
            <field name="inherit_id" ref="purchase.purchase_order_form"/>
            <field name="arch" type="xml">
                <xpath expr="//field[@name='order_line']/tree" position="attributes">
                    <attribute name="editable"/>
                </xpath>
            </field>
        </record>
    </data>
</odoo>
```

to open the form view instead of inline editing the order lines.

Current behavior:
```
Uncaught Error: Unknown field state in domain [["state","in",["purchase","to approve","done","cancel"]]]

http://localhost:8069/web/content/9879-5da04b0/web.assets_backend.js:1770
Traceback:
Error: Unknown field state in domain [["state","in",["purchase","to approve","done","cancel"]]]
    at compute_domain (http://localhost:8069/web/content/9879-5da04b0/web.assets_backend.js:1770:42)
    at Class.modifiers_for (http://localhost:8069/web/content/9879-5da04b0/web.assets_backend.js:2110:76)
    at eval (eval at _render (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2949:73), <anonymous>:51:39)
    at Object.foreach (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2919:18)
    at Engine.eval (eval at _render (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2949:73), <anonymous>:45:23)
    at Engine._render (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2948:296)
    at Object.call (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2918:23)
    at eval (eval at _render (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2949:73), <anonymous>:10:31)
    at Object.foreach (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2919:18)
    at Object.foreach (http://localhost:8069/web/content/7206-46089d9/web.assets_common.js:2920:6)

```
Expected behavior:
Add the purchase order lines.

Video/Screenshot link (optional):
No link, but a hint: The issue originates from the lines 215 and 224 in /addons/purchase/views/purchase_views.xml. Removing the domain expression in "attrs" solves the problem (at least it is a quick fix). odoo 9 did not have these domain expressions for the fields product_id and product_uom.

**Comment by bistaray** [comment]
I replicated this on runbot, by creating the inherited view interactively.

The same syntax works for sale.order on view: sale.order.form.editable.list to show the form when adding a line instead of inline editing.

**Comment by tchigy** [comment]
check my  answar on stackoverflow here:

[http://stackoverflow.com/questions/43768786/unknown-field-state-in-domain-when-editing-attribute/43777068#43777068](url)

**Comment by Yenthe666** [comment]
Hi all,

I was no longer able to reproduce this issue actually.
if you still have it then please update your Odoo to the latest source code and try again. If you can still reproduce it after that then please do post back with a video and I'll reopen it.

Regards,
Yenthe
