### ISSUE TITLE
ODOO 10 bug create new database latest revision.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15264]
Impacted versions: 10.0 latest revision

Steps to reproduce: Create new database.

Current behavior:
2017-01-30 07:34:14,849 27431 INFO xxxxxxess odoo.addons.base.res.res_config: next action is None
2017-01-30 07:34:14,853 27431 INFO xxxxxxess werkzeug: 49.34.113.165 - - [30/Jan/2017 07:34:14] "POST /web/dataset/call_button HTTP/1.1" 200 -
2017-01-30 07:34:15,205 27431 INFO xxxxxxess odoo.modules.loading: loading 1 modules...
2017-01-30 07:34:15,229 27431 INFO xxxxxxess odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2017-01-30 07:34:15,313 27431 INFO xxxxxxess odoo.modules.loading: loading 28 modules...
2017-01-30 07:34:15,411 27431 INFO xxxxxxess odoo.modules.loading: 28 modules loaded in 0.10s, 0 queries
2017-01-30 07:34:15,884 27431 INFO xxxxxxess odoo.modules.loading: Modules loaded.
2017-01-30 07:34:15,889 27431 INFO xxxxxxess odoo.addons.base.ir.ir_http: Generating routing map
2017-01-30 07:34:15,895 27431 INFO xxxxxxess odoo.addons.base.res.res_config: getting next operation
2017-01-30 07:34:15,896 27431 INFO xxxxxxess odoo.addons.base.res.res_config: getting next ir.actions.todo()
2017-01-30 07:34:15,900 27431 INFO xxxxxxess odoo.addons.base.res.res_config: next action is None
2017-01-30 07:34:15,909 27431 INFO xxxxxxess werkzeug: 49.34.113.165 - - [30/Jan/2017 07:34:15] "POST /web/dataset/call_button HTTP/1.1" 200 -
2017-01-30 07:34:21,307 27431 INFO xxxxxxess odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [248, 247]
2017-01-30 07:34:22,977 27431 INFO xxxxxxess odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [252]
2017-01-30 07:34:23,174 27431 INFO xxxxxxess odoo.sql_db: bad query: DELETE FROM ir_attachment WHERE id IN (248, 247)
2017-01-30 07:34:23,176 27431 INFO xxxxxxess odoo.sql_db: bad query:  SELECT "res_users"."id" as "id" FROM "res_users" LEFT JOIN "res_partner" as "res_users__partner_id" ON ("res_users"."partner_id" = "res_users__partner_id"."id")
                        WHERE "res_users".id IN (1)  ORDER BY "res_users__partner_id"."name" ,"res_users"."login"  
                    
2017-01-30 07:34:23,180 27431 INFO xxxxxxess werkzeug: 49.34.113.165 - - [30/Jan/2017 07:34:23] "GET /web HTTP/1.1" 200 -
2017-01-30 07:34:23,186 27431 INFO xxxxxxess werkzeug: 49.34.113.165 - - [30/Jan/2017 07:34:23] "GET /web HTTP/1.1" 500 -
2017-01-30 07:34:23,201 27431 ERROR xxxxxxess werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/odoobugs/odoo10/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/odoobugs/odoo10/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/odoobugs/odoo10/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoobugs/odoo10/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoobugs/odoo10/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/odoobugs/odoo10/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/home/odoobugs/odoo10/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoobugs/odoo10/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/odoobugs/odoo10/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoobugs/odoo10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoobugs/odoo10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoobugs/odoo10/odoo/http.py", line 327, in checked_call
    result.flatten()
  File "/home/odoobugs/odoo10/odoo/http.py", line 1257, in flatten
    self.response.append(self.render())
  File "/home/odoobugs/odoo10/odoo/http.py", line 1250, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoobugs/odoo10/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/qweb.py", line 320, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in get_template
    raise QWebException("load could not load template", name=template)
QWebException: None
Traceback (most recent call last):
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in get_template
    document = options.get('load', self.load)(template, options)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/home/odoobugs/odoo10/odoo/addons/base/ir/ir_ui_view.py", line 924, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-9>", line 2, in _read_template
  File "/home/odoobugs/odoo10/odoo/tools/cache.py", line 80, in lookup
    key = key0 + self.key(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/home/odoobugs/odoo10/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/home/odoobugs/odoo10/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/home/odoobugs/odoo10/odoo/models.py", line 3056, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoobugs/odoo10/odoo/addons/base/res/res_users.py", line 856, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/home/odoobugs/odoo10/odoo/addons/base/res/res_users.py", line 297, in read
    result = super(Users, self).read(fields=fields, load=load)
  File "/home/odoobugs/odoo10/odoo/models.py", line 2996, in read
    self._read_from_database(stored, inherited)
  File "/home/odoobugs/odoo10/odoo/models.py", line 3124, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoobugs/odoo10/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoobugs/odoo10/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

Expected behavior:
Stable create new database.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as @tejastank has been blocked from the Odoo repository.
An official response can be found on the thread https://github.com/odoo/odoo/issues/7466#issuecomment-378920731, to quote @mart-e:

> Due to the repeated aggressive tone (#16056 (comment), #8514 (comment), #1880 (comment), #7019 (comment), #7085 (comment)...) with the one that are trying to help you or just failing to give useful information to a point beyond bad faith (#10931 (comment), #3443 (comment), #4544 (comment),...), @tejastank is now blocked on the Odoo repository.
I was hoping we could manage a solution but, after almost 4 years, it seems sadly that we can not discuss constructively with him.
