### ISSUE TITLE
Error while updating to latest version of Odoo 7

### ISSUE THREAD

**Issue by lanouettea** [odoo/odoo#15304]
Impacted versions:
7.0
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I am attempting to update OpenERP 7 to the latest version on 7.0 branch. It has been a long time since the last update has been applied. (years). I checked out the project, then ran the update on a test database and I am getting a foreign key constraint violation. Is there any way to fix this?

`
2017-02-01 14:29:56,678 11932 DEBUG test2 openerp.osv.orm.schema: Table 'account_invoice': added foreign key 'commercial_partner_id' with definition=REFERENCES "res_partner" ON DELETE set null
2017-02-01 14:29:56,691 11932 ERROR test2 openerp.sql_db: bad query: ALTER TABLE "account_invoice" ADD FOREIGN KEY ("commercial_partner_id") REFERENCES "res_partner" ON DELETE set null
Traceback (most recent call last):
  File "/opt/openerp/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "account_invoice" violates foreign key constraint "account_invoice_commercial_partner_id_fkey"
DETAIL:  Key (commercial_partner_id)=(2049) is not present in table "res_partner".

2017-02-01 14:29:56,691 11932 ERROR test2 openerp.netsvc: insert or update on table "account_invoice" violates foreign key constraint "account_invoice_commercial_partner_id_fkey"
DETAIL:  Key (commercial_partner_id)=(2049) is not present in table "res_partner".
Traceback (most recent call last):
  File "/opt/openerp/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/openerp/service/web_services.py", line 439, in dispatch
    return fn(*params)
  File "/opt/openerp/openerp/service/web_services.py", line 444, in exp_login
    res = security.login(db, login, password)
  File "/opt/openerp/openerp/service/security.py", line 29, in login
    pool = pooler.get_pool(db)
  File "/opt/openerp/openerp/pooler.py", line 49, in get_pool
    return get_db_and_pool(db_name, force_demo, status, update_module)[1]
  File "/opt/openerp/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/opt/openerp/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/opt/openerp/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/opt/openerp/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/openerp/openerp/modules/loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp/openerp/modules/loading.py", line 165, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/openerp/openerp/modules/module.py", line 381, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/opt/openerp/openerp/osv/orm.py", line 3328, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/opt/openerp/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/openerp/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "account_invoice" violates foreign key constraint "account_invoice_commercial_partner_id_fkey"
DETAIL:  Key (commercial_partner_id)=(2049) is not present in table "res_partner".
`

**Comment by lukebranch** [comment]
@lanouettea ,

Unfortunately as far as i'm aware version 7.0 is no longer supported by the publisher. The oldest available supported version is version 8.0.

What I would suggest is close this github issue, and ask this question in the community mailing lists and forum:

http://help.odoo.com

https://www.odoo.com/groups

In your case I would suggest joining the Accounting & Finance mailing list and ask for suggestions and advice on that list, as the error message above points to the accounting module. 

There are a number of OpenERP 7 experts on that list that i'm sure will be happy to offer advice based on their own experience.

**Comment by Yenthe666** [comment]
Hi @lanouettea,

Thank you for your report.
However, as @lukebranch pointed out, we no longer support Odoo V7.
When I look at your stacktrace it doesn't look like a bug either, it looks like you've deleted a linked record somewhere along the line and this is now causing this error. The error is probably only on this record too I presume.
The help forums are a great place to help you further. See help.odoo.com.

Regards,
Yenthe
