### ISSUE TITLE
Odoo Livechat + Angular web app 16.x promise rejection

### ISSUE THREAD

**Issue by ljimenezsidoo** [odoo/odoo#153210]
Impacted versions: Odoo 16

Steps to reproduce: 
Go to runbot and copy the links from livechat app in channels section in the widget tab.
![image](https://github.com/odoo/odoo/assets/14888212/58d86c79-ddf2-4dca-9a50-883dc610123d)
Paste those links in the external angular web app

Current behavior: The livechat button does not appear visually in any way, the console show this errors:

zone.js:1046 TypeError: Promise.resolve(...).then(...).guardedCatch is not a function
    at external_lib.js:2725:127
    at new ZoneAwarePromise (zone.js:1422:21)
    at processJob (external_lib.js:2724:9)
    at Object.processJobs (external_lib.js:2732:1)
    at odoo.define (external_lib.js:2738:293)
    at 1:4:26
Error: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (external_lib.js:3010:101)
    at owl.App.handleError (external_lib.js:3636:29)
    at Fiber._render (external_lib.js:3035:19)
    at Fiber.render (external_lib.js:3033:6)
    at ComponentNode.initiateRender (external_lib.js:3101:47)
Uncaught (in promise) TypeError: this.env.services.public_livechat_service.mountLivechatButton is not a function
    at model._created (external_lib.js:5378:468)
    at ModelManager._executeCreatedRecordsCreated (external_lib.js:5174:148)
    at ModelManager._flushUpdateCycle (external_lib.js:5180:144)
    at ModelManager._executeCreatedRecordsComputes (external_lib.js:5172:21)
    at ModelManager._flushUpdateCycle (external_lib.js:5180:26)
    at ModelManager._notifyListenersInUpdateCycle (external_lib.js:5194:21)
    at ModelManager._flushUpdateCycle (external_lib.js:5180:64)
    at ModelManager.update (external_lib.js:5104:62)
    at model.update (external_lib.js:5251:137)
    at model.loadQWebTemplate (external_lib.js:5430:6)

Expected behavior: Fully working live chat

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Related issue before: #44058

**Comment by shazvi** [comment]
Hi. Did you manage to solve this issue? Im getting the exact same error when I integrate livechat in my external Angular app.

**Comment by ljimenezsidoo** [comment]
Hi @shazvi unfortunately I have only been able to make it work by making the angular application zone-less and this is not the way to do it.

**Comment by seb-odoo** [comment]
This should be resolved in recent versions as we no longer use `guardedCatch` which is in the error message.
