### ISSUE TITLE
Migrate modules to 17 version (ValueError: Element '<div id="emails">' cannot be located in parent view)

### ISSUE THREAD

**Issue by xFingerlinKx** [odoo/odoo#153388]
Impacted versions: 17

Steps to reproduce: Odoo.sh -> Upgrade button

Current behavior: Got the error in process of automatic migration from odoo 14 to odoo 17
`2024-02-09 07:56:07,215 10169 INFO db_1326679 odoo.modules.migration: module base: Running migration [$saas~16.5.1.3] end-01-attrs-views 
2024-02-09 07:56:12,506 10169 ERROR db_1326679 odoo.upgrade.util: Error in view 448 
Traceback (most recent call last):
  File "/tmp/tmpatsfopkp/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 607, in fix_archs
    comb_arch = v.inherit_id._get_combined_arch()
  File "/home/odoo/src/odoo/17.0/addons/website/models/ir_ui_view.py", line 498, in _get_combined_arch
    root = super()._get_combined_arch()
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 949, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 890, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 827, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 704, in _raise_view_error
    raise err from from_exception
ValueError: Element '<div id="emails">' cannot be located in parent view
2024-02-09 07:56:12,516 10169 ERROR db_1326679 odoo.upgrade.util: Error in view 466 
Traceback (most recent call last):
  File "/tmp/tmpatsfopkp/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 607, in fix_archs
    comb_arch = v.inherit_id._get_combined_arch()
  File "/home/odoo/src/odoo/17.0/addons/website/models/ir_ui_view.py", line 498, in _get_combined_arch
    root = super()._get_combined_arch()
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 949, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 890, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 827, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 704, in _raise_view_error
    raise err from from_exception
ValueError: Element '<div id="emails">' cannot be located in parent view`
Expected behavior:

Video/Screenshot link (optional):
These elements are only present here:
1) /odoo/addons/mail/views/res_config_settings_views.xml:10
2) /odoo/addons/base_setup/views/res_config_settings_views.xml:102
Support ticket number submitted via odoo.com/help (optional):

**Comment by psa-odoo** [comment]
Have you got any solutions? I am also getting the same kind of error while migrating from v16 to v17

Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 514, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpy1t9l99f/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 638, in migrate
    new_archs = fix_archs(info)
  File "/tmp/tmpy1t9l99f/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 614, in fix_archs
    arch = etree.fromstring(v.arch_db)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
ValueError: can only parse strings

**Comment by Senpaixyz** [comment]
Any solutions yet?  Whenever I pull the latest updates, this issue arises from 17.0.
