### ISSUE TITLE
IoTBox POS Display not working on RPi 5

### ISSUE THREAD

**Issue by intero-mat** [odoo/odoo#153676]
When running the IoTBox Image on a Raspberry Pi 5, the POS Display does not work on either an attached display (stays black and is not recognized on the web interface) or by clicking the button in the web interface of the IoTBox (causes an internal server error).

I have tried the same image on a Raspberry Pi 4 where it worked without problems.
I have also tried using a different Pi 5 with the same issues.

## Impacted versions
IoTBox Image Versions 23.11 and 24.01

## Steps to reproduce
Run the IoTBox Image on a Raspberry Pi 5 attached to a HDMI Monitor

## Current behavior
Booting the Device causes the Display to stay blank with following log output:
```
2024-02-12 14:19:21,275 1172 ERROR ? root:
2024-02-12 14:19:21,276 1172 ERROR ? root:
2024-02-12 14:19:21,276 1172 ERROR ? root: raise CalledProcessError(retcode, process.args,
2024-02-12 14:19:21,276 1172 ERROR ? root:
2024-02-12 14:19:21,276 1172 ERROR ? root: subprocess
2024-02-12 14:19:21,276 1172 ERROR ? root: .
2024-02-12 14:19:21,276 1172 ERROR ? root: CalledProcessError
2024-02-12 14:19:21,276 1172 ERROR ? root: :
2024-02-12 14:19:21,276 1172 ERROR ? root: Command '['vcgencmd', 'display_power', '-1', '2']' returned non-zero exit status 255.
```
Running that command in the shell:
```
root@raspberrypi:~# vcgencmd display_power -1 2
vc_gencmd_read_response returned -1
error=1 error_msg="Command not registered"
```

Clicking the `POS Display` Button in the web interface causes an `Internal Server Error` with the following log message:
```
2024-02-12 14:20:42,557 1172 ERROR ? odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/home/pi/odoo/odoo/http.py", line 2152, in __call__
    response = request._serve_nodb()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/odoo/odoo/http.py", line 1691, in _serve_nodb
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/odoo/odoo/http.py", line 1868, in dispatch
    return endpoint(**self.request.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py", line 226, in display
    display_identifier = DisplayDriver.get_default_display().device_identifier
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'device_identifier'
```

## Expected behavior
The IoTBox works properly like it does on the Pi 4

**Comment by lse-odoo** [comment]
@intero-mat hey :) If I am not mistaken, the IoT did fix this for the next IoT image. It was not released yet, but it should arrive pretty soon.
See related PR: https://github.com/odoo/odoo/pull/169633
