### ISSUE TITLE
Accounting: unable to configure japan chart of accounts

### ISSUE THREAD

**Issue by damdam-s** [odoo/odoo#15384]
Impacted versions:
10.0

Steps to reproduce:
Install `l10n_jp` and configure a company to use this chart of account in the menu `Accounting > Settings`

Current behavior:

Error is thrown:
```python
Traceback (most recent call last):
  File "/opt/odoo/src/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/src/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/src/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/src/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/src/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/src/odoo/addons/base/res/res_config.py", line 537, in execute
    getattr(self, method)()
  File "/opt/odoo/src/addons/account/models/res_config.py", line 261, in set_chart_of_accounts
    wizard.execute()
  File "/opt/odoo/src/addons/account/models/chart_template.py", line 821, in execute
    acc_template_ref, taxes_ref = self.chart_template_id._install_template(company, code_digits=self.code_digits, transfer_account_id=self.transfer_account_id)
  File "/opt/odoo/src/addons/account/models/chart_template.py", line 280, in _install_template
    tmp1, tmp2 = self._load_template(company, code_digits=code_digits, transfer_account_id=transfer_account_id, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/opt/odoo/src/addons/account/models/chart_template.py", line 336, in _load_template
    self.generate_fiscal_position(taxes_ref, account_ref, company)
  File "/opt/odoo/src/addons/account/models/chart_template.py", line 455, in generate_fiscal_position
    'position_id': new_fp
  File "/opt/odoo/src/addons/account/models/chart_template.py", line 350, in create_record_with_xmlid
    new_xml_id = str(company.id)+'_'+template_xmlid.name
TypeError: cannot concatenate 'str' and 'bool' objects
```

Expected behavior:

Chart of account is correctly configured for the desired company

Video/Screenshot link (optional):
![selection_012](https://cloud.githubusercontent.com/assets/8102312/22685563/148b11b2-ed21-11e6-97e4-1a88049eddfa.jpg)

**Comment by damdam-s** [comment]
@odony seems related to enterprise

**Comment by dbo-odoo** [comment]
Hello,

Indeed, this should not happen. I've moved the issue to our bugfixing team, they will contact you on the issue.

opw-707704

Regards,

**Comment by damdam-s** [comment]
Hello,

Thanks for the fix.
It works when installing `l10n_jp` but not when updating it `-u l10n_jp`.
Probably not real issue :smile:
