### ISSUE TITLE
Mass mails not sent when filter applied in different language than user

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15445]
Impacted versions: 9, 10

Steps to reproduce:

1. Install mass_mailing.
2. Install an additional language (i.e. Spanish).
3. Log in as demo user.
4. Create a new partner, set its country to be "Spain".
4. Change demo user's lang to Spanish.
5. Create a new mass mailing.
5. Choose customer recipients.
5. Select those customers whose country is "España".
4. Design the email.
3. Send it.

Current behavior:
The demo user sees 1 record selected, the admin user sees 0 records. This happens because admin's lang is English and no countries are found if you search for "España" under that context.
Since the queue is sent under the admin user context, no mails are sent.
Demo user scratches his head (in case he ever notices no mails were sent).

Expected behavior:
Queue should be run under the same language as the one in the context when the user pressed the "send" button, to avoid losing records when some domain is applied over translated fields.

@Tecnativa

**Comment by Yajo** [comment]
Further research revealed that the problem is not admin user's language, but cron job context.

To workaround this, go to the *Process Mass Mailing Queue* cron job, and set arguments to `({"lang": "es_ES"})`. Otherwise the job runs without lang.

Indeed this is a very ugly workaround. I think the best would be that when the user pressed "send", the domain changed to a context-independent one (such as `[("id", "in", destination_records.ids)]`.

**Comment by Yajo** [comment]
Even further research shows that applying the context workaround raises this error:

    2017-02-13 09:52:22,495 1 ERROR prod openerp.addons.base.ir.ir_cron: Call of self.pool.get('mail.mass_mailing')._process_mass_mailing_queue(cr, uid, *('lang',)) failed in Job 17
    Traceback (most recent call last):
      File "/opt/odoo/custom/src/odoo/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
        getattr(model, method_name)(cr, uid, *args)
      File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/custom/src/odoo/addons/mass_mailing/models/mass_mailing.py", line 834, in _process_mass_mailing_queue
        mass_mailing_ids = self.search(cr, uid, [('state', 'in', ('in_queue', 'sending')), '|', ('schedule_date', '<', now), ('schedule_date', '=', False)], context=context)
      File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/custom/src/odoo/openerp/models.py", line 1668, in search
        return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
      File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4788, in _search
        query = self._where_calc(cr, user, args, context=context)
      File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4549, in _where_calc
        if 'active' in self._fields and active_test and context.get('active_test', True):
    AttributeError: 'str' object has no attribute 'get'

So, no workaround available, I'll prepare a PR.

**Comment by danimaribeiro** [comment]
Add label to 11.0 too :)

I've created a fix following @odony idea about the problem. It does not fix all the cases, but at least users within the same language won't have surprises.

**Comment by simongoffin** [comment]
Closed with 6504bce60eb507af82707efa4c495943a5e9bc9a

**Comment by rafaelbn** [comment]
Thanks  @simongoffin ! Bravo! :smile:
