### ISSUE TITLE
new_value['id'] should be new_value['ID']

### ISSUE THREAD

**Issue by baptisteghesquiere** [odoo/odoo#154751]
https://github.com/odoo/odoo/blob/0751d887e6d4f810d779183d3bf17806cccaf97e/addons/account/models/account_tax.py#L326C108-L326C111

The dictionary new_value does not have a 'id' key but a 'ID' key and this gives a problem. Please fix this, as this throws an error when changing taxes.

TraceBack 

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo/odoo/service/model.py", line 135, in retrying
    [env.cr](http://env.cr/).flush()  # submit the changes to the database
    ^^^^^^^^^^^^^^
  File "/opt/odoo/odoo/odoo/sql_db.py", line 138, in flush
    self.precommit.run()
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 1220, in run
    func()
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 530, in _track_finalize
    tracking = records.with_context(context)._message_track(fnames, initial_values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 643, in _message_track
    record._message_log(
  File "/opt/odoo/odoo/addons/account/models/account_tax.py", line 360, in _message_log
    self._message_log_repartition_lines(tracked_value_id[2]['old_value_char'], tracked_value_id[2]['new_value_char'])
  File "/opt/odoo/odoo/addons/account/models/account_tax.py", line 326, in _message_log_repartition_lines
    repartition_line = self.env['account.tax.repartition.line'].search([('id', '=', new_value['id'])])
                                                                                    ~~~~~~~~~^^^^^^
KeyError: 'id'
The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://wax-it.odoo.accomodata.net/web/assets/9870367/web.assets_web.min.js:2867:163)
    at XMLHttpRequest.<anonymous> (https://wax-it.odoo.accomodata.net/web/assets/9870367/web.assets_web.min.js:2871:13)

![image](https://github.com/odoo/odoo/assets/85393159/d397d622-7a9f-4bf2-959e-2bd174155167)

**Comment by vava-odoo** [comment]
Hi @baptisteghesquiere 
Thanks for reporting. This seems to have been fixed with https://github.com/odoo/odoo/commit/f98dc05a03c98b237b0b5ced7add79f0da577cc8
I'm therefore closing the issue.
Cheers
