### ISSUE TITLE
[17] RPC_ERROR: Odoo Server Error when opening raw record data of employee in developer mode

### ISSUE THREAD

**Issue by Khalid100000** [odoo/odoo#154849]
Impacted versions:
17
Steps to reproduce:
when developer mode is activated and go to a any employee form view and try to view the Raw Record Data
I tested it also on the demo website and the error occurred

Current behavior:
an error occurs
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1847, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/odoo/src/odoo/saas-17.1/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1824, in _serve_ir_http
    return self._serve_ir_http(rule, args)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1832, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 2057, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 740, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 34, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 30, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/api.py", line 458, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/models.py", line 3661, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/saas-17.1/odoo/models.py", line 3872, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/home/odoo/src/odoo/saas-17.1/odoo/models.py", line 6664, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/home/odoo/src/odoo/saas-17.1/odoo/fields.py", line 1193, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/fields.py", line 1375, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/saas-17.1/addons/mail/models/mail_thread.py", line 416, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/saas-17.1/odoo/models.py", line 4982, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/saas-17.1/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/saas-17.1/addons/hr/models/hr_employee_base.py", line 81, in _compute_newly_hired
    employee.newly_hired = employee[new_hire_field] > new_hire_date
TypeError: '>' not supported between instances of 'bool' and 'datetime.datetime'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://demo4.odoo.com/web/assets/e3295b5/web.assets_web.min.js:2907:163)
    at XMLHttpRequest.<anonymous> (https://demo4.odoo.com/web/assets/e3295b5/web.assets_web.min.js:2912:13)

Expected behavior:
it should open the raw data of the data like with any other model record

**Comment by lathama** [comment]
Maybe related https://github.com/odoo/odoo/issues/157183

**Comment by vava-odoo** [comment]
Hi @Khalid100000 
Thanks for reporting. This was fixed in https://github.com/odoo/odoo/pull/159666
Cheers
