### ISSUE TITLE
Git pull or fresh install Odoo 8 from GitHub gives errors on Ubuntu 14:

### ISSUE THREAD

**Issue by sebytza05** [odoo/odoo#15498]
Impacted versions: 8.0

Odoo 8, odoo-server.log, on 02 14 2017

![image](https://cloud.githubusercontent.com/assets/19728451/22950924/fcf8059c-f30f-11e6-9da2-796c3ec17966.png)

2017-02-14 19:50:01,572 1421 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1296, in __call__
    self.load_addons()
  File "/opt/odoo/odoo-server/openerp/http.py", line 1306, in load_addons
    for module in sorted(os.listdir(str(addons_path))):

**Comment by Yenthe666** [comment]
Hi @sebytza05,

Thank you for your report.
Please do a new `git fetch` to update your source code and then update all modules by using the `-u all` parameter. This will fix your issue.

Regards,
Yenthe
