### ISSUE TITLE
Android notification

### ISSUE THREAD

**Issue by Sickboy** [odoo/odoo#15532]
Impacted versions:10.0-20170213

Steps to reproduce:push messages

Current behavior:error

Expected behavior:

Video/Screenshot link (optional):

**Comment by Sickboy** [comment]
I have an error on android when the notification come im 

Twoja skrzynka odbiorcza jest pusta
Tutaj pojawią się nowe wiadomości.
×
Odoo Błąd klienta
Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.

http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3141
Traceback:
TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
    at _send_native_notification (http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3141:68)
    at Object.send_notification (http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3140:278)
    at notify_incoming_message (http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3019:7)
    at http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3024:91
    at Function._.each._.forEach (http://192.168.1.19:8069/web/content/251-dd1bc0a/web.assets_common.js:12:558)
    at add_message (http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3020:202)
    at http://192.168.1.19:8069/web/content/918-730f4e6/web.assets_backend.js:3064:21
    at http://192.168.1.19:8069/web/content/251-dd1bc0a/web.assets_common.js:547:681
    at fire (http://192.168.1.19:8069/web/content/251-dd1bc0a/web.assets_common.js:541:299)
    at Object.add [as done] (http://192.168.1.19:8069/web/content/251-dd1bc0a/web.assets_common.js:542:467)

**Comment by Yenthe666** [comment]
@pimodoo any update?

**Comment by pimodoo** [comment]
Could you please reproduce it in with debug=assets in the url (e.g. https://www.odoo.com/web?debug=assets) to have the javascript traceback with the corresponding files and line numbers. 

Thanks

**Comment by Yenthe666** [comment]
@Sickboy could you try this again and give us a full traceback please?

**Comment by Sickboy** [comment]
No, I cant. It was over 4 months ago. I dont have this install at all. 
Maybe later I will install latest version on some virtual server and report if bug still be.
Give me 2-3 days.

**Comment by Yenthe666** [comment]
Hi @Sickboy,

I'm closing this issue as there has been no feedback in over a month.
If you can still reproduce this on the latest codebase please do reply and I'll reopen this issue.

Regards,
Yenthe
