### ISSUE TITLE
Caused by: TypeError: Cannot set property getLbsMapUrl of #<MapController> which has only a getter

### ISSUE THREAD

**Issue by lwdsw** [odoo/odoo#155495]
Impacted versions:
16
Steps to reproduce:

我在使用 patch 工具试图修补一个已存在的组件类 MapController 的时候，我向里面增加了一个 getter 方法。
代码很简单，只有两个文件（是继承了 web_map 模块，对 Map 视图进行了拓展）：

**inherit_map_controller.js**

`
/** @odoo-module **/

import { MapController } from "@web_map/map_view/map_controller";
import { patch } from '@web/core/utils/patch';

patch(MapController.prototype, "addGetLbsMapUrl", {

    //---- Getters ----

    get getLbsMapUrl() {
        return "https://www/baidu/com";
    },

});

`

**inherit_map_controller.xml**

`
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">

    <t t-name="my_module.MapView.Buttons" t-inherit="web_map.MapView.Buttons" t-inherit-mode="extension" owl="1">
        <xpath expr="//div[hasclass('o-map-view--buttons')]" position="inside">
            <a class="btn btn-primary text-white" t-att-href="getLbsMapUrl" target="_blank" data-hotkey="g">在高德地图</a>
        </xpath>
    </t>

</templates>

`

Current behavior:
我想这是一个错误

`
web.assets_backend.min.js:667 OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1247:101)
    at owl.App.handleError (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:2082:29)
    at Fiber._render (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1492:19)
    at Fiber.render (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1490:6)
    at ComponentNode.initiateRender (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1558:47)

Caused by: TypeError: Cannot set property getLbsMapUrl of #<MapController> which has only a getter
    at capture (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1661:81)
    at MapController.template (eval at compile (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:2045:370), <anonymous>:26:18)
    at node.renderFn (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1605:210)
    at Fiber._render (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1491:96)
    at Fiber.render (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1490:6)
    at ComponentNode.initiateRender (http://localhost:8016/web/assets/121-0b8aa75/web.assets_common.min.js:1558:47)
`

Expected behavior:

no error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by filwu8** [comment]
me too

**Comment by zyzcss** [comment]
me too

**Comment by zyzcss** [comment]
@filwu8 @lwdsw 
The following methods can be used
First
Set the get method corresponding to "Object.defineProperty" to undefined
after that
Delete the corresponding get method, such as "delete object.getName"
Finally, define a new get function

Case
`
import { ListRenderer } from "@web/views/list/list_renderer";

function setObjectGet(target, getName, getFunction) {
    Object.defineProperty(target, getName, {
        get: undefined
    });
    delete target[getName]
    Object.defineProperty(target, getName, {
        get: getFunction
    });
}

setObjectGet(ListRenderer.prototype, 'hasSelectors', function(){
    if (this.isX2Many) {
        return !this.props.readonly && !this.env.isSmall;
    }
    return this.props.allowSelectors && !this.env.isSmall;
})
`
