### ISSUE TITLE
RPC_ERROR Odoo Server Error When sending Quotation by Email in Persian

### ISSUE THREAD

**Issue by PadraAx** [odoo/odoo#155698]
installation environment as followed:

Python 3.10
Odoo17.0
Ubuntu22.04

Detail as followed:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/odoo/odoo/http.py", line 1765, in _serve_db
return service_model.retrying(self._serve_ir_http, self.env)
File "/opt/odoo/odoo/odoo/service/model.py", line 133, in retrying
result = func()
File "/opt/odoo/odoo/odoo/http.py", line 1792, in _serve_ir_http
response = self.dispatcher.dispatch(rule.endpoint, args)
File "/opt/odoo/odoo/odoo/http.py", line 1996, in dispatch
result = self.request.registry['ir.http']._dispatch(endpoint)
File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
response = super()._dispatch(endpoint)
File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
result = endpoint(**request.params)
File "/opt/odoo/odoo/odoo/http.py", line 722, in route_wrapper
result = endpoint(self, *args, **params_ok)
File "/opt/odoo/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/odoo/odoo/odoo/api.py", line 468, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/opt/odoo/odoo/odoo/api.py", line 453, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/opt/odoo/odoo/addons/web/models/models.py", line 1077, in onchange
snapshot1 = RecordSnapshot(record, fields_spec)
File "/opt/odoo/odoo/addons/web/models/models.py", line 1164, in init
self.fetch(name)
File "/opt/odoo/odoo/addons/web/models/models.py", line 1173, in fetch
lines = self.record[field_name]
File "/opt/odoo/odoo/odoo/models.py", line 6590, in getitem
return self._fields[key].get(self, self.env.registry[self._name])
File "/opt/odoo/odoo/odoo/fields.py", line 2893, in get
return super().get(records, owner)
File "/opt/odoo/odoo/odoo/fields.py", line 1152, in get
self.recompute(record)
File "/opt/odoo/odoo/odoo/fields.py", line 1367, in recompute
apply_except_missing(self.compute_value, recs)
File "/opt/odoo/odoo/odoo/fields.py", line 1340, in apply_except_missing
func(records)
File "/opt/odoo/odoo/odoo/fields.py", line 1389, in compute_value
records._compute_field_value(self)
File "/opt/odoo/odoo/odoo/models.py", line 4867, in _compute_field_value
fields.determine(field.compute, self)
File "/opt/odoo/odoo/odoo/fields.py", line 102, in determine
return needle(*args)
File "/opt/odoo/odoo/addons/mail/wizard/mail_compose_message.py", line 256, in _compute_attachment_ids
rendered_values = composer._generate_template_for_composer(
File "/opt/odoo/odoo/addons/mail/wizard/mail_compose_message.py", line 1242, in _generate_template_for_composer
template_values = self.template_id._generate_template(
File "/opt/odoo/odoo/addons/mail/models/mail_template.py", line 548, in _generate_template
template._generate_template_attachments(
File "/opt/odoo/odoo/addons/mail/models/mail_template.py", line 287, in _generate_template_attachments
report_name = safe_eval(
File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 363, in safe_eval
c = test_expr(expr, _SAFE_OPCODES, mode=mode, filename=filename)
File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 216, in test_expr
code_obj = compile(expr, filename or "", mode)
File "", line 1
(object.state in ('draft', 'sent') و 'پیش‌فاکتور - %s' % (object.name)) یا 'سفارش - %s' % (object.name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
at handleError (https://xxxxxx.xxx/web/assets/2c89626/web.assets_web.min.js:916:101)
at App.handleError (https://xxxxxx.xxx/web/assets/2c89626/web.assets_web.min.js:1542:29)
at ComponentNode.initiateRender (https://xxxxxx.xxx/web/assets/2c89626/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
at makeErrorFromResponse (https://xxxxxx.xxx/web/assets/2c89626/web.assets_web.min.js:2874:163)
at XMLHttpRequest. (https://xxxxxx.xxx/web/assets/2c89626/web.assets_web.min.js:2878:13)

**Comment by lathama** [comment]
maybe related https://github.com/odoo/odoo/issues/157183

**Comment by HLFH** [comment]
Same error

**Comment by HLFH** [comment]
Go to Settings > Technical > Analysis > Reports.
Search for the _sale.report_saleorder_raw_ model.
The error is that in the translation of the printed report name, the logical connectives (in, and, or) have also been translated (here in Persian).

Replace:

> (object.state in ('draft', 'sent') و 'پیش‌فاکتور - %s' % (object.name)) یا 'سفارش - %s' % (object.name)

by 

> (object.state in ('draft', 'sent') and 'پیش‌فاکتور  - %s' % (object.name)) "
"or 'سفارش - %s' % (object.name)

As shown in this file: https://github.com/odoo/odoo/blob/17.0/addons/sale/i18n/fa.po

**Comment by HLFH** [comment]
This issue can be closed @chevalierv
