### ISSUE TITLE
Odoo Latest Bug, v10 wrong operation on Model

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15576]
Impacted versions: 9, 10

Steps to reproduce:
settings -> database -> models -> added fields.
than remove fields. not allow....

Current behavior:
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 458, in unlink
    self._prepare_update()
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 436, in _prepare_update
    field = model._fields[record.name]
KeyError: u'x_codice_fiscale'
Expected behavior:

Video/Screenshot link (optional):

![fields - odoo](https://cloud.githubusercontent.com/assets/311413/23161428/175a080a-f850-11e6-9b1f-39c6821a3641.png)

**Comment by Yenthe666** [comment]
Hi @tejastank,

Thanks for your report.
I've just tested this on the latest Odoo source code and this bug is no longer in Odoo.
Please update your Odoo source code and try again.

Regards,
Yenthe

**Comment by tejastank** [comment]
I detected in latest too, 

@Yenthe666 thank for close without fix it. as odoo some benifit for close it.

Reported bugs never responsed in few week or day. but your kind of exta package do this dirty job.

Its better @Yenthe666 you ask to odoo why they not quick repsonse to community, community biggest give success to born tiny to openerp and to odoo.

**Comment by Yenthe666** [comment]
Hi @tejastank,

Can you make a video on the latest Odoo runbot which shows this bug? I'm happy to reopen it if you can reprocude it or explain me into more detail about how to reproduce this.

Regards,
Yenthe

**Comment by tejastank** [comment]
@Yenthe666 after many month in case you can't detect its useless, In case a odoo not response to customer / community in 2/3 weeks and world get suffered.

please quite it without feedback. @erpnnext is also good product compare to odoo.

So stop flattery of odoo and its bugs, leave in case you don't face anything which people reported.

I suggest your(@Yenthe666 ) kind of falletery to immidate check my bugs as I reported, not after months and years.
