### ISSUE TITLE
Odoo 17 eCommerce Checkout throws 500 error: `got an unexpected keyword argument 'sale_order_id'`

### ISSUE THREAD

**Issue by troykelly** [odoo/odoo#155803]
## Impacted versions

Odoo 17.0+e-20240216 (Enterprise Edition)

## Steps to reproduce

1. Odoo Enterprise Edition
2. Create Company
3. Enable Websites, eCommerce et al
4. Add products
5. Enable Wire transfer (or any other) payment method
6. From another session: Add products, go to cart
7. 500 Error

## Current behaviour

```text
2024-02-28 21:18:35,271 69 ERROR development odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2189, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1909, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_loyalty/controllers/main.py", line 47, in cart
    return super(WebsiteSale, self).cart(**post)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/main.py", line 797, in cart
    values.update(self._get_express_shop_payment_values(order))
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/main.py", line 1656, in _get_express_shop_payment_values
    payment_form_values = sale_portal.CustomerPortal._get_payment_values(
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/controllers/portal.py", line 218, in _get_payment_values
    payment_methods_sudo = request.env['payment.method'].sudo()._get_compatible_payment_methods(
  File "/opt/odoo-enterprise/sale_subscription/models/payment_method.py", line 25, in _get_compatible_payment_methods
    return super()._get_compatible_payment_methods(*args, sale_order_id=sale_order_id, **kwargs)
TypeError: PaymentMethod._get_compatible_payment_methods() got an unexpected keyword argument 'sale_order_id'
```

## Expected behaviour

The cart should comeup allowing the user to check out

## Video/Screenshot link (optional)

https://capture.dropbox.com/3Hy4dyzukqreOVu6
https://capture.dropbox.com/xaOyek8kF1vtGlTg

## Support ticket number submitted via odoo.com/help (optional)

`3774900 `

## Other Notes

Multi-company install

**Comment by 3gmgithub** [comment]
I also experience this same error, but on an estimate that is not confirmed.

**Comment by vava-odoo** [comment]
Hi @troykelly 
You only need to update the community repository as well, see this commit https://github.com/odoo/odoo/commit/e475a38da2b85691f8b4f18deecc1ec2e7a9c9d9 
Cheers

**Comment by 3gmgithub** [comment]
Thanks for the tip, we are running the Enterprise version though

**Comment by vava-odoo** [comment]
[The sale_subscription (enterprise) PR](https://github.com/odoo/enterprise/pull/54700) adds a new kwarg (`sale_order_id`) to the override method of `_get_compatible_payment_methods`, so the signature of the method in payment (community) was changed in [the linked community PR](https://github.com/odoo/odoo/pull/150120).
My feeling when reading your error is that you updated enterprise but not community.

**Comment by 3gmgithub** [comment]
Thank you!

**Comment by 3gmgithub** [comment]
I just updated the docker image, and the problems are fixed!  Thanks!
