### ISSUE TITLE
Error while using kanban_image in odoo 17, while in odoo 16, it works well 

### ISSUE THREAD

**Issue by MyAusweis** [odoo/odoo#156227]
Here the XML
  <img t-att-src="kanban_image('product.template','image_1920', record.id.raw_value)" alt="Product" class="o_image_64_contain"/>

when i use this function, error below shown, when i disable it, it works well in kanban but no image show. for your information, that function works well in odoo16 

============= The Error ================

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8015/web/assets/debug/web.assets_web.js:9163:35)
    at App.handleError (http://localhost:8015/web/assets/debug/web.assets_web.js:13354:20)
    at Fiber._render (http://localhost:8015/web/assets/debug/web.assets_web.js:9309:30)
    at Fiber.render (http://localhost:8015/web/assets/debug/web.assets_web.js:9298:18)
    at ComponentNode.initiateRender (http://localhost:8015/web/assets/debug/web.assets_web.js:9963:23)

Caused by: TypeError: Cannot read properties of undefined (reading 'type')
    at extractFieldsFromArchInfo (http://localhost:8015/web/assets/debug/web.assets_web.js:68100:66)
    at get modelParams (http://localhost:8015/web/assets/debug/web.assets_web.js:95496:42)
    at KanbanController.setup (http://localhost:8015/web/assets/debug/web.assets_web.js:95428:60)
    at new ComponentNode (http://localhost:8015/web/assets/debug/web.assets_web.js:9941:28)
    at http://localhost:8015/web/assets/debug/web.assets_web.js:13345:28
    at View.slot1 (eval at compile (http://localhost:8015/web/assets/debug/web.assets_web.js:13116:20), <anonymous>:13:36)
    at callSlot (http://localhost:8015/web/assets/debug/web.assets_web.js:10553:37)
    at WithSearch.template (eval at compile (http://localhost:8015/web/assets/debug/web.assets_web.js:13116:20), <anonymous>:8:12)
    at Fiber._render (http://localhost:8015/web/assets/debug/web.assets_web.js:9306:38)
    at Fiber.render (http://localhost:8015/web/assets/debug/web.assets_web.js:9298:18)

**Comment by intero-chz** [comment]
> Here the XML
> kanban_image('product.template','image_1920', record.id.raw_value)

I don't see XML. Could you add atleast some more XML please. `kanban_image` is used widely for example in the [kanban view](https://github.com/odoo/odoo/blob/b238770e5a3760d51e2d6c4786dd46648de87815/odoo/addons/base/views/res_partner_views.xml#L480-L498) of `res.partner`.

**Comment by MyAusweis** [comment]
<record id= "stock_kanban" model="ir.ui.view">
            <field name="name">analisa available stock kanban</field>
            <field name="model">analisa.available.stock.list</field>
            <field name="arch" type="xml">
                <kanban create="false">
                    <field name ="kode_barang"/>
                    <field name ="nama_barang"/>
                    <field name ="harga"/>
                    <field name ="berat"/>
                    <field name ="kuantitas"/>
                    <field name ="perusahaan"/>
                    <field name = "prod_id"/>
                    <field name = "modelku"/>
                    <field name = "nama_file" />


                         <progressbar field="activity_state" colors="{&quot;planned&quot;: &quot;success&quot;, &quot;today&quot;: &quot;warning&quot;, &quot;overdue&quot;: &quot;danger&quot;}"/>
                            <templates>
                                <t t-name="kanban-box">
                                    <div class="oe_kanban_card oe_kanban_global_click">
                                         <div class="o_kanban_image me-1">
                                      <img t-att-src="kanban_image('product.template'','image_1920', record.id.raw_value)" alt="Product" class="o_image_64_contain"/>
                                        </div>
                                        <div class="oe_kanban_details">
                                            <div class="o_kanban_record_top mb-0">
                                                <div class="o_kanban_record_headings">
                                                    <strong class="o_kanban_record_title">
                                                        <field name="kode_barang"/>
                                                    </strong>
                                                </div>
                                                <field name="nama_barang" widget="nama_barang"/>

                                            </div>
                                            <div name="product_lst_price" class="mt-1">
                                                Price: <field name="harga" widget="monetary" options="{'currency_field': 'currency_id', 'field_digits': True}"/>
                                            </div>
                                             <div name="company_name" class="mt-1">
                                                <field name="perusahaan" widget="perusahaan"/>
                                            </div>

                                        </div>
                                    </div>
                                </t>
                            </templates>
                

                         <field name="id" invisible="1"/>
                    
                </kanban>
            </field>
        </record>

**Comment by intero-chz** [comment]
There is a syntax error: `'product.template''` should be `'product.template'`

**Comment by MyAusweis** [comment]
i did it, but it still won't work
