### ISSUE TITLE
Edit Header button raise Odoo server Error

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#15661]
**Impacted versions:**
saas-14

**Steps to reproduce:**

1. Go to Settings > General Settings
2. At **Report Template** section, click on the **Edit Header** button.

![image](https://cloud.githubusercontent.com/assets/7593953/23382979/fb701e04-fd09-11e6-9882-fd7c55e8c625.png)

**Current behavior:**

A Odoo Server Error appears. This is the error return by **COPY THE FULL ERROR TO CLIPBOARD**  

```bash
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/web/controllers/main.py", line 884, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/web/controllers/main.py", line 872, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/report/models/base_config_settings.py", line 24, in edit_external_header
    return self._prepare_report_view_action('report.layout_'+self.external_report_layout)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/report/models/base_config_settings.py", line 14, in _prepare_report_view_action
    template_id = self.env.ref(template)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/api.py", line 785, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/base/ir/ir_model.py", line 1060, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/base/ir/ir_model.py", line 1044, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<string>", line 2, in xmlid_lookup
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/201013-saas-14-6e21c4/odoo/addons/base/ir/ir_model.py", line 1033, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.layout_standard
```

**Expected behavior:**

That the button works without giving me any error

**Video/Screenshot link (optional):**

https://youtu.be/JM3_fLtYgdI

**Comment by Yenthe666** [comment]
Hi @zaoral,

Thank you for your report.
I can confirm it is a bug in the SaaS-14:
![image](https://cloud.githubusercontent.com/assets/6352350/23395684/34ca9716-fd90-11e6-9836-29269c3c73e5.png)
@mart-e can you look at it? Looks like an invalid pointer to the QWeb.

Regards,
Yenthe

**Comment by mart-e** [comment]
@Yenthe666 the traceback is hidden in the "see details" now :wink: 

Introduced at 3d04e44880fb77812e65342ef25bb8ad06094ddc

@KangOl @fpodoo  was the intention [of this line](https://github.com/odoo/odoo/blob/5765b36c5ac9395fd481a35882beff507180f266/addons/report/models/base_config_settings.py#L24) `'report.external_layout_'+self.external_report_layout` ?

**Comment by zaoral** [comment]
FYI: I create a ticket related to this issue OPW 710501
