### ISSUE TITLE
Been unable to install modules in Odoo 10 lately

### ISSUE THREAD

**Issue by mgrigajtis** [odoo/odoo#15686]
Impacted versions: 10.0

Steps to reproduce: Install a module
```
Current behavior: Modules install gives the following error:
Traceback (most recent call last):
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/app/.heroku/odoo/addons/web/controllers/main.py", line 1129, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 972, in run
    res = func(action, eval_context=eval_context)
  File "/app/.heroku/odoo/addons/website/models/ir_actions.py", line 58, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 795, in run_action_code_multi
    safe_eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odooku/patches/registry.py", line 55, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/convert.py", line 780, in _tag_template
    return self._tag_record(record, data_node)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 353, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/models.py", line 3818, in create
    self._fields[key].determine_inverse(record)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 371, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/models.py", line 3550, in write
    self._write(old_vals)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/models.py", line 3696, in _write
    self._validate_fields(vals)
  File "/app/.heroku/odoo/lib/python2.7/site-packages/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ValueError: <class 'odoo.tools.convert.ParseError'>: "" while evaluating
u'records.button_immediate_install()'
```
Expected behavior: The module should install

Video/Screenshot link (optional): See copy and paste error

**Comment by Yenthe666** [comment]
Hi @mgrigajtis,

Thank you for your report.
Could you please update your Odoo codebase to the latest version and try again? How old is your code?
On the official Odoo test instances (runbot.odoo.com) the install button works perfectly.

Regards,
Yenthe

**Comment by mgrigajtis** [comment]
New update.  The modules that I wanted to install we in some strange "pending install" state. When attempting to force it after the code base update, I got the above error.  Then I cancelled the install, then attempted the install again and it worked.

Remember, if the user has a bad time, it's a bug.

**Comment by fahadmalik02011** [comment]
how to install in hosting server

**Comment by blaggacao** [comment]
@Yenthe666 Can confirm @mgrigajtis is right, it's a bug.
An aborted installation can easily happen when you have set a cpu time limit on workers...
Imagine: You first get to your instance and want to install all modules, besides the fact that you get an ugly "CPU Timeout" traceback (ok, that's responsibility of the hoster), then you cannot resume there installation from the app screen, and baam there is the support ticket.

// cc @odony
