### ISSUE TITLE
odoo 17 

### ISSUE THREAD

**Issue by direstrepo24** [odoo/odoo#157181]
Impacted versions: odoo 17
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 73, in web_save
    self = self.create(vals)
  File "<decorator-gen-188>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/digest/models/res_users.py", line 12, in create
    users = super(ResUsers, self).create(vals_list)
  File "<decorator-gen-151>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/res_users.py", line 342, in create
    users_with_email.with_context(create_user=True)._action_reset_password()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/res_users.py", line 224, in _action_reset_password
    account_created_template.send_mail(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 593, in send_mail
    values = self._generate_template(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 511, in _generate_template
    for _lang, (template, template_res_ids) in self._classify_per_lang(res_ids).items():
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_render_mixin.py", line 579, in _classify_per_lang
    for res_id, lang in self._render_lang(res_ids, engine=engine).items():
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_render_mixin.py", line 556, in _render_lang
    rendered_langs = self._render_template(self.lang, self.render_model, res_ids, engine=engine)
  File "/mnt/extra-addons/hide_odoo/models/mail_render_mixin.py", line 57, in _render_template
    orginal_rendered = super()._render_template(
TypeError: MailRenderMixin._render_template() got an unexpected keyword argument 'post_process'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://lapared.themakers.com.co/web/assets/4d2c2ac/web.assets_web.min.js:2878:163)
    at XMLHttpRequest.<anonymous> (https://lapared.themakers.com.co/web/assets/4d2c2ac/web.assets_web.min.js:2882:13)

Steps to reproduce: create new user

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by lathama** [comment]
Maybe related https://github.com/odoo/odoo/issues/157183
