### ISSUE TITLE
Issue removing any module - Ubuntu 16.04 + Odoo 10.00

### ISSUE THREAD

**Issue by gustavocp** [odoo/odoo#15719]
Impacted versions: 10.00

Steps to reproduce: i just installed using tutorial https://www.virtual-server.org/blog/install-odoo-10-on-ubuntu-16-04/ and then install module CRM, Project, Sales, Discuss. Just try to remove any module

Current behavior: loose all data from modules

Expected behavior: just unistall or install (simple operation)

ERROR FROM LOG
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_alias ALTER COLUMN alias_model_id SET NOT NULL
2017-03-06 03:03:38,331 29184 WARNING odoo odoo.models.schema: Table 'mail_followers': unable to set a NOT NULL constraint on column 'res_model' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_followers ALTER COLUMN res_model SET NOT NULL
2017-03-06 03:03:38,354 29184 INFO odoo odoo.sql_db: bad query: ALTER TABLE "mail_followers" ADD CONSTRAINT "mail_followers_partner_xor_channel" CHECK((partner_id IS NULL) != (channel_id IS NULL))
2017-03-06 03:03:38,355 29184 WARNING odoo odoo.models.schema: Table 'mail_followers': unable to add constraint 'CHECK((partner_id IS NULL) != (channel_id IS NULL))'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mail_followers" ADD CONSTRAINT "mail_followers_partner_xor_channel" CHECK((partner_id IS NULL) != (channel_id IS NULL))
2017-03-06 03:03:38,409 29184 WARNING odoo odoo.models.schema: Table 'mail_mail': unable to set a NOT NULL constraint on column 'mail_message_id' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_mail ALTER COLUMN mail_message_id SET NOT NULL
2017-03-06 03:03:38,441 29184 WARNING odoo odoo.models.schema: Table 'mail_channel': unable to set a NOT NULL constraint on column 'alias_id' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_channel ALTER COLUMN alias_id SET NOT NULL
2017-03-06 03:03:38,451 29184 WARNING odoo odoo.models.schema: Table 'mail_channel': unable to set a NOT NULL constraint on column 'name' !
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_channel ALTER COLUMN name SET NOT NULL
2017-03-06 03:03:38,563 29184 INFO odoo odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2017-03-06 03:03:38,689 29184 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/odoo/modules/registry.py", line 315, in init_models
    model._auto_init()
  File "/odoo/odoo-server/odoo/models.py", line 2503, in _auto_init
    self._init_column(name)
  File "/odoo/odoo-server/odoo/models.py", line 2273, in _init_column
    value = field.default(self)
  File "/odoo/odoo-server/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'
2017-03-06 03:03:38,690 29184 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/odoo/modules/registry.py", line 315, in init_models
    model._auto_init()
  File "/odoo/odoo-server/odoo/models.py", line 2503, in _auto_init
    self._init_column(name)
  File "/odoo/odoo-server/odoo/models.py", line 2273, in _init_column
    value = field.default(self)
  File "/odoo/odoo-server/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'
2017-03-06 03:03:38,691 29184 INFO odoo werkzeug: 187.180.232.85 - - [06/Mar/2017 03:03:38] "POST /web/dataset/call_button HTTP/1.1" 200 -
If you want to have it, you should update the records and execute manually:
ALTER TABLE mail_channel ALTER COLUMN name SET NOT NULL
2017-03-06 03:03:38,563 29184 INFO odoo odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2017-03-06 03:03:38,689 29184 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/odoo/modules/registry.py", line 315, in init_models
    model._auto_init()
  File "/odoo/odoo-server/odoo/models.py", line 2503, in _auto_init
    self._init_column(name)
  File "/odoo/odoo-server/odoo/models.py", line 2273, in _init_column
    value = field.default(self)
  File "/odoo/odoo-server/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'
2017-03-06 03:03:38,690 29184 ERROR odoo odoo.http: Exception during JSON request handling.

**Comment by treviser** [comment]
If you want to uninstall modules you get a warning about potential data loss. Due to data interdependencies, this can not be avoided and even more, sometimes leads to unexpected results. Therefore you should always make backup before uninstalling modules or installing new ones.

**Comment by gustavocp** [comment]
right @treviser thank you for reply. im new using odoo and i created again my enviroment. But , i would like to know what can i do to remove securely a module? Is it possible? 

To recreate:
I just install odoo, login, install modules crm/sales/discussions, create a few data simulation, remove app crm. After that, all crashes.

**Comment by treviser** [comment]
The apps you are mentioning here are quite critical as they have so many dependencies/relationships, especially the module Discuss. You need a test instance, there you try, and if you are sure, then set up a production instance. This is not about installing MS Word or so and needs quite a bit of experience.

**Comment by gustavocp** [comment]
Right, i understand your position. Sure, im doing all tests in labs enviroment. 

But, as developer i think that its an issue cause if you have one feature to "unistall" module, it need to check all dependency and remove them  or simple validation like "you cannot remove native modules" to not broken all system. As you said, its not MS Word its an ERP.

Im new here, im not criticizing only expresing my opinion

@treviser really thanks for all replies and explanations!

**Comment by JKE-be** [comment]
Thank @treviser for your prompt answer and thanks to @gustavocp for your opinion.

All apps depends of mail, so you should be not able to uninstall it, else doing it, you uninstall odoo.
But in your log, I see that you have : mail.mt_comment missing... Maybe you have manually deleted some default data, and not demo data ? 

As specified by @treviser , it is always better to test on a test environment ;)

**Comment by ealonzo7** [comment]
Same issue here, just Uninstall Discuss module and now all modules not working and i cannot install or re-install any module.
Im using Odoo 11 on Ubuntu server 14.4

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 135, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/odoo/modules/registry.py", line 302, in init_models
    model._auto_init()
  File "/odoo/odoo-server/odoo/models.py", line 2142, in _auto_init
    new = field.update_db(self, columns)
  File "/odoo/odoo-server/odoo/fields.py", line 1942, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/odoo/odoo-server/odoo/fields.py", line 853, in update_db
    self.update_db_notnull(model, column)
  File "/odoo/odoo-server/odoo/fields.py", line 893, in update_db_notnull
    model._init_column(self.name)
  File "/odoo/odoo-server/odoo/models.py", line 2059, in _init_column
    value = field.default(self)
  File "/odoo/odoo-server/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by aalonzolu** [comment]
Same here i'm triying to re-install mail module but i'm getting the same error.
I'm executing this command `./odoo-bin -u mail -d databasename`
raceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 924, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 135, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/odoo/modules/registry.py", line 302, in init_models
    model._auto_init()
  File "/odoo/odoo-server/odoo/models.py", line 2142, in _auto_init
    new = field.update_db(self, columns)
  File "/odoo/odoo-server/odoo/fields.py", line 1942, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/odoo/odoo-server/odoo/fields.py", line 853, in update_db
    self.update_db_notnull(model, column)
  File "/odoo/odoo-server/odoo/fields.py", line 893, in update_db_notnull
    model._init_column(self.name)
  File "/odoo/odoo-server/odoo/models.py", line 2059, in _init_column
    value = field.default(self)
  File "/odoo/odoo-server/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by febru** [comment]
try this : http://febru.solu-ent.com/2018/02/solved-error-odoomodulesregistry-failed.html

**Comment by JKE-be** [comment]
-i mail instead of -u to force réinitialisation from default data

**Comment by douno** [comment]
Make sure you install the [Database Cleanup](https://www.odoo.com/apps/modules/8.0/database_cleanup/) module.
After installation, go to Settings > General Settings > Database cleanup > Purge obsolete tables and purge the mail_message_compose line. Note this should be setup before you start installing and uninstalling modules. Written in more details [here](http://douno.net/2018/06/07/odoo-attributeerror-nonetype-object-has-no-attribute-id/).
