### ISSUE TITLE
Failing CI pipeline due to tests and (possibly unknown correct environment)

### ISSUE THREAD

**Issue by Foosec** [odoo/odoo#157946]
Impacted versions: 17.0

Steps to reproduce: install from source on ubuntu jammy docker, run all tests

Current behavior: Only managed to get to 1 failing test, python 3.11 makes a *lot* of tests fail, wrong postgres variants make *a lot of tests* fail

Expected behavior:
All vanilla tests passing within the requirements specified in Odoo documentation

The test we cannot manage to get to pass is below:

odoo-1      | 2024-03-16 14:47:56,810 1589 ERROR odoo odoo.addons.test_new_api.tests.test_indexed_translation: FAIL: TestIndexedTranslation.test_search_ilike
odoo-1      | Traceback (most recent call last):
odoo-1      |   File "/opt/odoo/odoo/odoo/addons/test_new_api/tests/test_indexed_translation.py", line 45, in test_search_ilike
odoo-1      |     with self.assertQueries(["""
odoo-1      |   File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
odoo-1      |     next(self.gen)
odoo-1      |   File "/opt/odoo/odoo/odoo/tests/common.py", line 497, in assertQueries
odoo-1      |     self.assertEqual(
odoo-1      | AssertionError: 'sele[80 chars]here("test_new_api_indexed_translation"."name"[55 chars]"id"' != 'sele[80 chars]here(jsonb_path_query_array("test_new_api_inde[144 chars]"id"'
odoo-1      | Diff is 651 characters long. Set self.maxDiff to None to see it. :
odoo-1      | ---- actual query:
odoo-1      | SELECT "test_new_api_indexed_translation"."id" FROM "test_new_api_indexed_translation" WHERE ("test_new_api_indexed_translation"."name"->>%s ILIKE %s) ORDER BY "test_new_api_indexed_translation"."id"
odoo-1      | ---- not like:
odoo-1      |
odoo-1      |             SELECT "test_new_api_indexed_translation"."id"
odoo-1      |             FROM "test_new_api_indexed_translation"
odoo-1      |             WHERE (jsonb_path_query_array("test_new_api_indexed_translation"."name", '$.*')::text ILIKE %s
odoo-1      |             AND "test_new_api_indexed_translation"."name"->>%s ILIKE %s)
odoo-1      |             ORDER BY "test_new_api_indexed_translation"."id"

Setting maxdiff to see the entire query we see:

expected:
SELECT "test_new_api_indexed_translation"."id"
FROM "test_new_api_indexed_translation"
WHERE (jsonb_path_query_array("test_new_api_indexed_translation"."name", '$.*')::text ILIKE %s
AND "test_new_api_indexed_translation"."name"->>%s ILIKE %s)
ORDER BY "test_new_api_indexed_translation"."id"

actual:
SELECT "test_new_api_indexed_translation"."id" 
FROM "test_new_api_indexed_translation"
WHERE ("test_new_api_indexed_translation"."name"->>%s ILIKE %s)
ORDER BY "test_new_api_indexed_translation"."id"

Im only writing this because i am probably at my wits end, no combination we tried works, among them but not limited to are:
Debian bullseye container, Ubuntu Jammy, postgres inside jammy, postgres as a seperate container bullseye and alpine, 
setting collation settings manually, pip version install, apt version install, a combination of the two, extracted dependencies from the official deb and installed. <nothing> works. 

Please help me not go crazy!

**Comment by Foosec** [comment]
Figured out its due to the test assuming that trigram matching is available, the expected query is generated when hasTrigram is true. 
As to why it is false, the CI process setup postgres with a database already created, and the create database procedures that enable the postgres extension only run on creation, not initialization. Will be creating relevant PR.
