### ISSUE TITLE
Index Error: list index out of range

### ISSUE THREAD

**Issue by CarlosROFA** [odoo/odoo#15831]
ODOO V8 in UBUNTU

After use a year, since yesterday when I enter in module Leads, I have this error:

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/v8/OCB/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/OCB/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/v8/OCB/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/opt/odoo/v8/OCB/openerp/http.py", line 914, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/v8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/OCB/openerp/models.py", line 5220, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/v8/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/OCB/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/v8/OCB/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/OCB/openerp/models.py", line 3190, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/v8/OCB/openerp/fields.py", line 1597, in convert_to_read
    return value_sudo.name_get()[0]
IndexError: list index out of range

I don't konw what hapen.
Help me, please

**Comment by Yenthe666** [comment]
Hi @CarlosROFA,

Could you please update your Odoo codebase to the latest version?
Can you reproduce this with the latest code?

Regards,
Yenthe

**Comment by CarlosROFA** [comment]
Thank you. I solved


Regards



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: "Yenthe V.G" <notifications@github.com>
Fecha: 13/3/17 8:51 (GMT+01:00)
Para: odoo/odoo <odoo@noreply.github.com>
Cc: CarlosROFA <mundiofi@hotmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [odoo/odoo] Index Error: list index out of range (#15831)


Hi @CarlosROFA<https://github.com/CarlosROFA>,

Could you please update your Odoo codebase to the latest version?
Can you reproduce this with the latest code?

Regards,
Yenthe

**Comment by droobtd** [comment]
An error occurred while loading the Point of Sale: 
list index out of range
