### ISSUE TITLE
[16.0] [Traceback] Send an Invitation Email

### ISSUE THREAD

**Issue by nikul-serpentcs** [odoo/odoo#158308]
Impacted versions: **16.0**

Steps to reproduce:
1. Create a new user
2. Click on **Send an Invitation Email** Button

Current behavior:

Traceback (most recent call last):
  File "/home/gost/workspace/16.0/addons/mail/models/mail_mail.py", line 429, in send
    smtp_session = self.env['ir.mail_server'].connect(mail_server_id=mail_server_id, smtp_from=smtp_from)
  File "/home/gost/workspace/16.0/odoo/addons/base/models/ir_mail_server.py", line 393, in connect
    connection = smtplib.SMTP(smtp_server, smtp_port, timeout=SMTP_TIMEOUT)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gost/workspace/16.0/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/gost/workspace/16.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/gost/workspace/16.0/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/gost/workspace/16.0/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/gost/workspace/16.0/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/gost/workspace/16.0/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/gost/workspace/16.0/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/gost/workspace/16.0/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/gost/workspace/16.0/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/gost/workspace/16.0/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/gost/workspace/16.0/addons/auth_signup/models/res_users.py", line 205, in action_reset_password
    template.send_mail(user.id, force_send=force_send, raise_exception=True, email_values=email_values)
  File "/home/gost/workspace/16.0/addons/mail/models/mail_template.py", line 402, in send_mail
    mail.send(raise_exception=raise_exception)
  File "/home/gost/workspace/16.0/addons/mail/models/mail_mail.py", line 434, in send
    **raise MailDeliveryException(_('Unable to connect to SMTP Server'), exc)
odoo.addons.base.models.ir_mail_server.MailDeliveryException: ('Unable to connect to SMTP Server', ConnectionRefusedError(111, 'Connection refused'))**

Expected behavior:
Raised Warning or Validation

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/17664321/1ca9a77e-e3b1-43b0-9a6c-5699811f6664)

**Comment by divyamaheshwari96** [comment]
Did you resolved this issue ?

**Comment by divyamaheshwari96** [comment]
i am facing same issue.

**Comment by nikul-serpentcs** [comment]
> Did you resolved this issue ?

Yes, It's resolved in base.

**Comment by divyamaheshwari96** [comment]
can we see what is fixed for this error ?
