### ISSUE TITLE
Calendar view not opening

### ISSUE THREAD

**Issue by allePansera** [odoo/odoo#158370]
Impacted versions: 17

Steps to reproduce: install calendar module and try to open the calendar

Current behavior: getting error reported next

Expected behavior: show me listed demo events

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8070/web/assets/859717d/web.assets_web.min.js:916:101)
    at App.handleError (http://localhost:8070/web/assets/859717d/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (http://localhost:8070/web/assets/859717d/web.assets_web.min.js:1006:19)

Caused by: AssetsLoadingError: The loading of /web/static/lib/fullcalendar/core/main.js failed
    at HTMLScriptElement.<anonymous> (http://localhost:8070/web/assets/859717d/web.assets_web.min.js:1604:270)

**Comment by lathama** [comment]
maybe related https://github.com/odoo/odoo/issues/157183
