### ISSUE TITLE
[17.0] - MRP - BoM OverView - KeyError: 'manufacture_delay'

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#158598]
Impacted versions: 17.0 Enterprise (odoo.sh)

Steps to reproduce:

- Bill of Material -> BoM Overview

Current behavior:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 16, in get_html
    res = self._get_report_data(bom_id=bom_id, searchQty=searchQty, searchVariant=searchVariant)
  File "/home/odoo/src/enterprise/mrp_plm/report/mrp_report_bom_structure.py", line 15, in _get_report_data
    res = super()._get_report_data(bom_id, searchQty, searchVariant)
  File "/home/odoo/src/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 120, in _get_report_data
    production_capacities = self._compute_production_capacities(bom_quantity, lines)
  File "/home/odoo/src/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 40, in _compute_production_capacities
    lead_time = bom_data['manufacture_delay']
KeyError: 'manufacture_delay'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://xxx.odoo.com/web/assets/ec6b347/web.assets_web.min.js:916:101)
    at App.handleError (https://xxx.odoo.com/web/assets/ec6b347/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (https://xxx.odoo.com/web/assets/ec6b347/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://xxx.odoo.com/web/assets/ec6b347/web.assets_web.min.js:2876:163)
    at XMLHttpRequest.<anonymous> (https://xxx.odoo.com/web/assets/ec6b347/web.assets_web.min.js:2880:13)
```

Expected behavior:

- No error when clicking on BoM Overview  (it worked well last week)

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/7898318/90c83455-fb16-4674-be55-3f73b6a6dacf)

Support ticket number submitted via odoo.com/help (optional):

**Comment by anhvu-sg** [comment]
I think it's related to this PR https://github.com/odoo/odoo/pull/144702

could you please take a look? @pfertyk

**Comment by pfertyk** [comment]
Hi @anhvu-sg !

Yes, it seems related to the changes I've made recently. I'll take a closer look.

Could you please send me a list of modules that are installed in your database? I mean mostly the stock-related ones, like Manufacturing, Purchase, Inventory etc.

**Comment by pfertyk** [comment]
Hi again @anhvu-sg ! I tried to recreate this issue, but already available BoMs in runbot seem to be working fine. Could you please tell me more about your setup? Like: what are the routes for the final product, what are the routes for components, are you using subcontracting anywhere? This will speed up the debugging process.

**Comment by anhvu-sg** [comment]
it works well, thanks @pfertyk
