### ISSUE TITLE
Odoo Error on Authorize.NET payment capture (error parsing XML API) after click Validate on Invoice Payment Registration

### ISSUE THREAD

**Issue by jleaders** [odoo/odoo#15930]
**Impacted versions:** Odoo Community 10.0

**Steps to reproduce:** 
Setup Authorize.NET payment gateway (use sandbox.authorize.net ).
Add a credit card via Auth.NET Sandbox Customer Information Management, copy Payment Method ID
Invoices > Customers > Payments > Credit Cards > Paste Payment Method ID
POS App > Setup Cash Electronic Journal called "Credit Card"
Add an invoice to that fake customer you created earlier
Invoices > Your Fake Invoice > Register Payment > Credit Card > Stored Credit Card > Validate

**Current behavior:**
```
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 878, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 870, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 679, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 664, in call_kw_model
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment\models\account_payment.py", line 37, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment\models\account_payment.py", line 56, in _do_payment
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment\models\payment_acquirer.py", line 594, in s2s_do_transaction
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment_authorize\models\payment.py", line 250, in authorize_s2s_do_transaction
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment_authorize\models\authorize_request.py", line 184, in auth_and_capture
  File "lxml.etree.pyx", line 953, in lxml.etree._Element.text.__set__ (src\lxml\lxml.etree.c:44956)
  File "apihelpers.pxi", line 685, in lxml.etree._setNodeText (src\lxml\lxml.etree.c:20341)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src\lxml\lxml.etree.c:26460)
TypeError: Argument must be bytes or unicode, got 'bool'
```

**Expected behavior:**
Failed gracefully with Authorize.NET error.

**Comment by jleaders** [comment]
I have a theory this may only occur when Authorize.NET is in a odd state (like a a unapproved sandbox account?) becauase I also saw some odd Auth errors earlier today. Regardless, a bool check on the return value at
`  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\payment_authorize\models\authorize_request.py", line 184, in auth_and_capture`

may be enough.

**Comment by jleaders** [comment]
Not sure if it's related, but I always get this error now, even when I don't believe I should:

```
Authorize.net Error Message(s):
User authentication failed due to invalid authentication values
```.

**Comment by Yenthe666** [comment]
@mart-e can you let somebody have a look at this?
P.S: Perhaps we have to extend https://github.com/odoo/odoo/wiki/BugManagement to add the payment method modules in the wiki too 😉

**Comment by jleaders** [comment]
bump

**Comment by santiagofs** [comment]
I'm having the same issue @jleaders said. 
Any news on if there's gonna be a fix for this or some workaround we can apply?

**Comment by jleaders** [comment]
Odoo 11 seems to be broken as well. I cannot get Authorize.NET to process a charge and appear in the sandbox on either Odoo 10 or 11. Is it fair to say Odoo does not support it's own payment modules anymore?

**Comment by Yenthe666** [comment]
@KangOl can you have a look / test?

**Comment by jleaders** [comment]
If anyone is able to get Authorize.NET to work from the odoo backend (not the customer portal), I'd be very interested, as we are hoping to use the backend to setup thousands of customers this month, but are blocked

**Comment by pedrobaeza** [comment]
@jleaders is this still happening? I'm understanding that the problem is on the backend manipulation, but not on frontend.

**Comment by jleaders** [comment]
@pedrobaeza I believe a coworker found a workaround, I'll double check

**Comment by pedrobaeza** [comment]
Thanks. Please report back.

**Comment by KaneTHP** [comment]
We've found a work-around to this. We've since moved to odoo11 but encountered similar problems. IIRC the fixes involved properly naming payment transactions and setting up the payment profiles on Authorize.NET

**Comment by jleaders** [comment]
I remember hearing the `aquirer_ref` had a lot of hacks around it. Perhaps that requires a new issue. Closing this one.
