### ISSUE TITLE
WHILE INSTALLING NEW MODULE : DOCUMENT MANAGEMENT

### ISSUE THREAD

**Issue by MED-B** [odoo/odoo#159614]
Impacted versions: 17

Steps to reproduce: install document manager on new database

Current behavior: error while trying to open app

Expected behavior: open app

Video/Screenshot link (optional): I can give the error instead : 

```
RPC_ERROR
404: Not Found
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 20, in _call_kw_readonly
    model_class = registry[params['model']]
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/registry.py", line 224, in __getitem__
    return self.models[model_name]
KeyError: 'documents.document'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 2252, in __call__
    response = request._serve_db()
  File "/home/odoo/src/odoo/saas-17.1/odoo/http.py", line 1823, in _serve_db
    ro = ro(registry, request)
  File "/home/odoo/src/odoo/saas-17.1/addons/web/controllers/dataset.py", line 22, in _call_kw_readonly
    raise NotFound() from e
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://mycompany8.odoo.com/web/assets/c70ce64/web.assets_web.min.js:947:101)
    at App.handleError (https://mycompany8.odoo.com/web/assets/c70ce64/web.assets_web.min.js:1573:29)
    at ComponentNode.initiateRender (https://mycompany8.odoo.com/web/assets/c70ce64/web.assets_web.min.js:1037:19)

Caused by: RPC_ERROR: 404: Not Found
    at makeErrorFromResponse (https://mycompany8.odoo.com/web/assets/c70ce64/web.assets_web.min.js:2911:163)
    at XMLHttpRequest.<anonymous> (https://mycompany8.odoo.com/web/assets/c70ce64/web.assets_web.min.js:2916:13)
```

Support ticket number submitted via odoo.com/help (optional): i did not create a ticket i was just trying to test the new version

**Comment by lathama** [comment]
related https://github.com/odoo/odoo/issues/157183
