### ISSUE TITLE
Whole Odoo breaks if one database name use a non ascii char

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#16002]
Impacted versions:
Odoo 10
Steps to reproduce:
Duplicate or create a db and choose a name containing non-ascii character (like "nouvelles catégories en menu rose" in my case). Try to delete it.
Current behavior:
Error 500 from werkzeug. The whole server is down. None of the other databases works anymore.
Odoo server log below:

---
2017-03-22 18:23:55,193 18749 INFO nouvelles catégories en menu rose werkzeug: 192.168.1.23 - - [22/Mar/2017 18:23:55] "GET /web?db=modele3 HTTP/1.1" 500 -
2017-03-22 18:23:55,197 18749 ERROR nouvelles catégories en menu rose werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1454, in dispatch
    odoo.registry(db).check_signaling()
  File "/usr/lib/python2.7/site-packages/odoo/__init__.py", line 52, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 55, in __new__
    return cls.new(db_name)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 67, in new
    registry.init(db_name)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 135, in init
    with closing(self.cursor()) as cr:
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 460, in cursor
    return self._db.cursor()
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 162, in connect
    for (k, v) in items])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)

---

Expected behavior:
In the best case, nothing should break. In the worst case, the other databases shouldn,t be affected.
At least, the database manager form should check the names

See also report #6958 and commit https://github.com/odoo/odoo/commit/26a8b438b6cc94241354af9fe218d8c592e17cfa

**Comment by zeroheure** [comment]
I forgot to say that database/manager nor database/selector works anymore.

**Comment by lukebranch** [comment]
I would suggest trying in a private tab (to access the db manager) and see if you can drop the db.

**Comment by zeroheure** [comment]
It wasn't possible. I've used CLI (tsudo -u odoo dropdb --interactive 'nouvelles catégories en menu rose') and
then deleted the werkzeug session files.

**Comment by zeroheure** [comment]
About solving this bug, dvarrazzo gives an interesting solution that will be in psycopg 2.7.
See his comments on https://github.com/psycopg/psycopg2/issues/331

**Comment by gokhanerdogdu** [comment]
Same problem exists when database name has Turkish special characters. System gives Internal Server 500 Error.

**Comment by Yenthe666** [comment]
Hi @zeroheure,

Thank you for your report.
This issue is no longer possible on V9/V10 ENT because you'll get a notification:
![image](https://cloud.githubusercontent.com/assets/6352350/26578340/bf90edb4-452f-11e7-8547-58b242b683f2.png)
I was able to duplicate a database with the name `nouvelles catégories en menu rose` in 9.0 (community) and could drop it without any issues too.
It looks like this is no longer a problem. Can you please try again with the latest code base?

Regards,
Yenthe
