### ISSUE TITLE
16.0 HrEmployeePublic.read() got an unexpected keyword argument 'load'

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#160106]
Impacted versions:
16.0
Hosted on Odoo.sh currently at abb67246820bce7ea4ace5d6d43a7396695cdcfa

Steps to reproduce:

1. Enable Multi Employees Per Session
2. Login with a user that doesn't have HR rights to access `hr.employee`
3. Try to open a new PoS session

Current behavior:
Raises a traceback on PoS UI:
``` log
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/point_of_sale/models/pos_session.py", line 1608, in load_pos_data
    loaded_data[model] = self._load_model(model)
  File "/home/odoo/src/odoo/addons/point_of_sale/models/pos_session.py", line 1600, in _load_model
    return loader(params())
  File "/home/odoo/src/odoo/addons/pos_hr/models/pos_session.py", line 31, in _get_pos_ui_hr_employee
    employees = self.env['hr.employee'].search_read(**params['search_params'])
  File "/home/odoo/src/odoo/odoo/models.py", line 5030, in search_read
    result = records.read(fields, **read_kwargs)
  File "/home/odoo/src/odoo/addons/hr/models/hr_employee.py", line 236, in read
    return self.env['hr.employee.public'].browse(self.ids).read(fields, load=load)
TypeError: HrEmployeePublic.read() got an unexpected keyword argument 'load'

```

Expected behavior:
The PoS should load normally without access rights to private employee information.

**Comment by vava-odoo** [comment]
Thanks for the report @mrawi. It was fixed in https://github.com/odoo/odoo/commit/a39d5780281e3958edd4246f546b67309124107a.
