### ISSUE TITLE
[17.0]  Critical error on upgrading to nightly 20240405  build  

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#160816]
Unable to upgrade my mid march instance to the 20240405  (nightly 20240405 deb + odoo-17.0+e.20240405 addons)

```
2024-04-05 15:30:59,004 41 INFO jacodoo5 odoo.modules.loading: loading website_sale/views/product_views.xml
2024-04-05 15:30:59,407 41 INFO jacodoo5 odoo.modules.loading: loading website_sale/views/sale_order_views.xml
2024-04-05 15:30:59,641 41 INFO jacodoo5 odoo.modules.loading: loading website_sale/views/templates.xml
2024-04-05 15:31:01,123 41 WARNING jacodoo5 odoo.modules.loading: Transient module states were reset
2024-04-05 15:31:01,134 41 ERROR jacodoo5 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:2101
Error while parsing or validating view:
Element '<xpath expr="//t[@t-if=&#39;website_sale_order.amount_total&#39;]">' cannot be located in parent view
View error context:
{'file': '/usr/lib/python3/dist-packages/odoo/addons/website_sale/views/templates.xml',
 'line': 1,
 'name': 'Delivery Costs',
 'view': ir.ui.view(2008,),
 'view.model': False,
 'view.parent': ir.ui.view(1963,),
 'xmlid': 'payment'}
```

https://github.com/odoo/odoo/blob/f5d6a8c4f801c0a577c4e0123c689298d4c421e9/addons/website_sale/views/website_sale_delivery_templates.xml#L47

refers to

https://github.com/odoo/odoo/blob/f5d6a8c4f801c0a577c4e0123c689298d4c421e9/addons/website_sale/views/templates.xml#L2130

the xpath query of the first part is changed from `t` to `div` with `name`-attribute. But the second part of the `|` statement it is still a `t` for the `t-if` attribute ... which no longer exists

**Comment by chapital** [comment]
same with 09-april-24 nightly

**Comment by chapital** [comment]
@bouvyd can you please check this?

**Comment by vava-odoo** [comment]
Hello @jwaes 
Thanks for your report. I made the feedback to the R&D team and they reverted the problematic change in https://github.com/odoo/odoo/pull/161274
Cheers
