### ISSUE TITLE
Cron run at specific time issue related to `to_datetime` in `fields.py`

### ISSUE THREAD

**Issue by mathisgauthey** [odoo/odoo#162057]
## Impacted versions

17.0

## Steps to reproduce

Create a cron job definied by XML like that : 

```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="ir_cron_send_rating_form_email" model="ir.cron">
        <field name="name">Send Rating Form Email</field>
        <field name="interval_number">1</field>
        <field name="nextcall" eval="(datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d 8:00:00')"/>
        <field name="interval_type">days</field>
        <field name="numbercall">-1</field>
        <field name="doall" eval="False"/>
        <field name="model_id" ref="model_MODULE_ride"/>
        <field name="code">model.send_rating_form_email()</field>
        <field name="state">code</field>
        <field name="active" eval="True"/>
    </record>
</odoo>
```

## Current behavior

When trying to update the cron by reloading the server, I get this error :

```
2024-04-16 11:41:37,489 174854 CRITICAL odoo-db odoo.service.server: Failed to initialize database `odoo-db`. 
Traceback (most recent call last):
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 456, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/models.py", line 5040, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/models.py", line 4971, in _load_records_write
    self.write(values)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/addons/base/models/ir_cron.py", line 442, in write
    return super(ir_cron, self).write(vals)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/models.py", line 4401, in write
    field.write(self, value)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/fields.py", line 1121, in write
    cache_value = self.convert_to_cache(value, records)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/fields.py", line 2300, in convert_to_cache
    return self.to_datetime(value)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/fields.py", line 2280, in to_datetime
    return datetime.strptime(value, DATETIME_FORMAT[:len(value)-2])
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 345, in _strptime
    raise ValueError("stray %% in format '%s'" % format) from None
ValueError: stray % in format '%Y-%m-%d %H:%M:%'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/mat/documents/odoo-dev/odoo_source/odoo/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/mat/documents/odoo-dev/MODULE/data/rating_mail_cron_data.xml:3, somewhere inside
<record id="ir_cron_send_rating_form_email" model="ir.cron">
        <field name="name">Send Rating Form Email</field>
        <field name="interval_number">1</field>
        <field name="nextcall" eval="(datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d 8:00:00')"/>
        <field name="interval_type">days</field>
        <field name="numbercall">-1</field>
        <field name="doall" eval="False"/>
        <field name="model_id" ref="model_MODULE_ride"/>
        <field name="code">model.send_rating_form_email()</field>
        <field name="state">code</field>
        <field name="active" eval="True"/>
    </record>
```

It comes from this [change](https://github.com/odoo/odoo/pull/35659), and more importantly from `to_datetime` function [here](https://github.com/odoo-dev/odoo/blob/092dbcc217734226b29dffb3157e7e4687d574ff/odoo/fields.py#L1786).

I don't understand why `return datetime.strptime(value, DATETIME_FORMAT[:len(value)-2])`, I can't seem to find out why would anyone slice the end of the DATETIME_FORMAT here. It is where the issue occurs.

The comment on this change is literally "WTF" -> [Link to the comment](https://github.com/odoo/odoo/pull/35659/commits/092dbcc217734226b29dffb3157e7e4687d574ff#r313302379)

## Expected behavior

I should be able to put a `datetime.strftime()` and the string should be evaluated correctly.

Note that this alternative workd : `<field name="nextcall" eval="(datetime.now() + timedelta(days=1)).replace(hour=8, minute=0, second=0)" />`.

**Comment by vava-odoo** [comment]
Hi @mathisgauthey 
Don't blame the code. It seems like you only forgot a 0 before the 8 in your format
```xml
<field name="nextcall" eval="(datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d 08:00:00')"/>
```
Cheers

**Comment by mathisgauthey** [comment]
> Hi @mathisgauthey Don't blame the code. It seems like you only forgot a 0 before the 8 in your format
> 
> ```
> <field name="nextcall" eval="(datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d 08:00:00')"/>
> ```
> 
> Cheers

Oh 😅 Simply hoped to help, how the turntables !

You're right, my mistake, I lost so much time on such a simple topic. Guess I def need better sleep.

In any case, thanks for the answer o/

**Comment by vava-odoo** [comment]
You're welcome :slightly_smiling_face:
