### ISSUE TITLE
Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Mamineee** [odoo/odoo#162142]
Impacted versions: 14

PS D:\odoo\odoo-14.0> py -m pip install -r requirements.txt
Ignoring Babel: markers 'python_version <= "3.9"' don't match your environment
Ignoring freezegun: markers 'python_version < "3.8"' don't match your environment
Ignoring gevent: markers 'sys_platform != "win32" and python_version < "3.7"' don't match your environment
Ignoring gevent: markers 'sys_platform == "win32" and python_version < "3.7"' don't match your environment
Ignoring gevent: markers 'python_version == "3.7"' don't match your environment
Ignoring gevent: markers 'python_version > "3.7" and python_version <= "3.9"' don't match your environment
Ignoring greenlet: markers 'python_version < "3.7"' don't match your environment
Ignoring greenlet: markers 'python_version == "3.7"' don't match your environment
Ignoring greenlet: markers 'python_version > "3.7" and python_version <= "3.9"' don't match your environment
Ignoring Jinja2: markers 'python_version < "3.8"' don't match your environment
Ignoring lxml: markers 'sys_platform != "win32" and python_version < "3.7"' don't match your environment
Ignoring lxml: markers 'sys_platform != "win32" and python_version == "3.7"' don't match your environment
Ignoring lxml: markers 'sys_platform != "win32" and python_version > "3.7"' don't match your environment
Ignoring ofxparse: markers 'python_version <= "3.9"' don't match your environment
Ignoring Pillow: markers 'python_version <= "3.7" and sys_platform != "win32"' don't match your environment
Ignoring Pillow: markers 'python_version <= "3.7" and sys_platform == "win32"' don't match your environment
Ignoring psycopg2: markers 'sys_platform != "win32" and python_version < "3.8"' don't match your environment
Ignoring python-ldap: markers 'sys_platform != "win32"' don't match your environment
Ignoring reportlab: markers 'python_version < "3.8"' don't match your environment
Ignoring requests: markers 'python_version <= "3.9"' don't match your environment
Ignoring Werkzeug: markers 'python_version <= "3.9"' don't match your environment
Ignoring xlrd: markers 'python_version < "3.8"' don't match your environment
Collecting Babel==2.9.1 (from -r requirements.txt (line 2))
  Using cached Babel-2.9.1-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting chardet==3.0.4 (from -r requirements.txt (line 3))
  Using cached chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting decorator==4.3.0 (from -r requirements.txt (line 4))
  Using cached decorator-4.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting docutils==0.14 (from -r requirements.txt (line 5))
  Using cached docutils-0.14-py3-none-any.whl.metadata (2.3 kB)
Collecting ebaysdk==2.1.5 (from -r requirements.txt (line 6))
  Using cached ebaysdk-2.1.5-py3-none-any.whl
Collecting freezegun==0.3.15 (from -r requirements.txt (line 8))
  Using cached freezegun-0.3.15-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting gevent==21.8.0 (from -r requirements.txt (line 13))
  Using cached gevent-21.8.0-cp310-cp310-win_amd64.whl.metadata (13 kB)
Collecting greenlet==1.1.2 (from -r requirements.txt (line 17))
  Using cached greenlet-1.1.2-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
Collecting idna==2.6 (from -r requirements.txt (line 18))
  Using cached idna-2.6-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting Jinja2==2.11.2 (from -r requirements.txt (line 21))
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting libsass==0.17.0 (from -r requirements.txt (line 22))
  Using cached libsass-0.17.0-cp310-cp310-win_amd64.whl
Collecting lxml (from -r requirements.txt (line 27))
  Using cached lxml-5.2.1-cp310-cp310-win_amd64.whl.metadata (3.5 kB)
Collecting Mako==1.0.7 (from -r requirements.txt (line 28))
  Using cached Mako-1.0.7-py3-none-any.whl
Collecting MarkupSafe==1.1.0 (from -r requirements.txt (line 29))
  Using cached MarkupSafe-1.1.0-cp310-cp310-win_amd64.whl
Collecting num2words==0.5.6 (from -r requirements.txt (line 30))
  Using cached num2words-0.5.6-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting ofxparse==0.21 (from -r requirements.txt (line 32))
  Using cached ofxparse-0.21-py3-none-any.whl
Collecting passlib==1.7.1 (from -r requirements.txt (line 33))
  Using cached passlib-1.7.1-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting Pillow==8.1.1 (from -r requirements.txt (line 36))
  Using cached Pillow-8.1.1.tar.gz (45.0 MB)
  Preparing metadata (setup.py) ... done
Collecting polib==1.1.0 (from -r requirements.txt (line 37))
  Using cached polib-1.1.0-py2.py3-none-any.whl.metadata (13 kB)
Collecting psutil==5.6.7 (from -r requirements.txt (line 38))
  Using cached psutil-5.6.7-cp310-cp310-win_amd64.whl
Collecting psycopg2==2.8.5 (from -r requirements.txt (line 40))
  Using cached psycopg2-2.8.5-cp310-cp310-win_amd64.whl
Collecting pydot==1.4.1 (from -r requirements.txt (line 41))
  Using cached pydot-1.4.1-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting PyPDF2==1.26.0 (from -r requirements.txt (line 43))
  Using cached PyPDF2-1.26.0-py3-none-any.whl
Collecting pyserial==3.4 (from -r requirements.txt (line 44))
  Using cached pyserial-3.4-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting python-dateutil==2.7.3 (from -r requirements.txt (line 45))
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl.metadata (7.5 kB)
Collecting pytz (from -r requirements.txt (line 46))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting pyusb==1.0.2 (from -r requirements.txt (line 47))
  Using cached pyusb-1.0.2-py3-none-any.whl
Collecting qrcode==6.1 (from -r requirements.txt (line 48))
  Using cached qrcode-6.1-py2.py3-none-any.whl.metadata (11 kB)
Collecting reportlab==3.5.55 (from -r requirements.txt (line 50))
  Using cached reportlab-3.5.55-cp310-cp310-win_amd64.whl
Collecting requests==2.25.1 (from -r requirements.txt (line 52))
  Using cached requests-2.25.1-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting urllib3==1.26.5 (from -r requirements.txt (line 53))
  Using cached urllib3-1.26.5-py2.py3-none-any.whl.metadata (43 kB)
Collecting zeep==3.2.0 (from -r requirements.txt (line 54))
  Using cached zeep-3.2.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting python-stdnum==1.8.1 (from -r requirements.txt (line 55))
  Using cached python_stdnum-1.8.1-py3-none-any.whl
Collecting vobject==0.9.6.1 (from -r requirements.txt (line 56))
  Using cached vobject-0.9.6.1-py3-none-any.whl
Collecting Werkzeug==2.0.2 (from -r requirements.txt (line 58))
  Using cached Werkzeug-2.0.2-py3-none-any.whl.metadata (4.5 kB)
Collecting XlsxWriter==1.1.2 (from -r requirements.txt (line 59))
  Using cached XlsxWriter-1.1.2-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting xlwt==1.3.* (from -r requirements.txt (line 60))
  Using cached xlwt-1.3.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting xlrd==1.2.0 (from -r requirements.txt (line 62))
  Using cached xlrd-1.2.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting pypiwin32 (from -r requirements.txt (line 63))
  Using cached pypiwin32-223-py3-none-any.whl.metadata (236 bytes)
Collecting six (from freezegun==0.3.15->-r requirements.txt (line 8))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting zope.event (from gevent==21.8.0->-r requirements.txt (line 13))
  Using cached zope.event-5.0-py3-none-any.whl.metadata (4.4 kB)
Collecting zope.interface (from gevent==21.8.0->-r requirements.txt (line 13))
  Using cached zope.interface-6.3-cp310-cp310-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from gevent==21.8.0->-r requirements.txt (line 13)) (65.5.0)
Collecting cffi>=1.12.2 (from gevent==21.8.0->-r requirements.txt (line 13))
  Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl.metadata (1.5 kB)
Collecting beautifulsoup4 (from ofxparse==0.21->-r requirements.txt (line 32))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pyparsing>=2.1.4 (from pydot==1.4.1->-r requirements.txt (line 41))
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting colorama (from qrcode==6.1->-r requirements.txt (line 48))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting certifi>=2017.4.17 (from requests==2.25.1->-r requirements.txt (line 52))
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting appdirs>=1.4.0 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting attrs>=17.2.0 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting cached-property>=1.3.0 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting defusedxml>=0.4.1 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting isodate>=0.5.4 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached isodate-0.6.1-py2.py3-none-any.whl.metadata (9.6 kB)
Collecting requests-toolbelt>=0.7.1 (from zeep==3.2.0->-r requirements.txt (line 54))
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting pywin32>=223 (from pypiwin32->-r requirements.txt (line 63))
  Using cached pywin32-306-cp310-cp310-win_amd64.whl.metadata (6.6 kB)
Collecting pycparser (from cffi>=1.12.2->gevent==21.8.0->-r requirements.txt (line 13))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting soupsieve>1.2 (from beautifulsoup4->ofxparse==0.21->-r requirements.txt (line 32))
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Using cached Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Using cached docutils-0.14-py3-none-any.whl (543 kB)
Using cached freezegun-0.3.15-py2.py3-none-any.whl (14 kB)
Using cached gevent-21.8.0-cp310-cp310-win_amd64.whl (1.6 MB)
Using cached greenlet-1.1.2-cp310-cp310-win_amd64.whl (101 kB)
Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Using cached num2words-0.5.6-py2.py3-none-any.whl (64 kB)
Using cached passlib-1.7.1-py2.py3-none-any.whl (498 kB)
Using cached polib-1.1.0-py2.py3-none-any.whl (25 kB)
Using cached pydot-1.4.1-py2.py3-none-any.whl (19 kB)
Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Using cached qrcode-6.1-py2.py3-none-any.whl (31 kB)
Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Using cached zeep-3.2.0-py2.py3-none-any.whl (98 kB)
Using cached Werkzeug-2.0.2-py3-none-any.whl (288 kB)
Using cached XlsxWriter-1.1.2-py2.py3-none-any.whl (142 kB)
Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Using cached lxml-5.2.1-cp310-cp310-win_amd64.whl (3.8 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Using cached pywin32-306-cp310-cp310-win_amd64.whl (9.2 MB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached zope.event-5.0-py3-none-any.whl (6.8 kB)
Using cached zope.interface-6.3-cp310-cp310-win_amd64.whl (204 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [184 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-310\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-310\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-r5o90sbm\pillow_c52e20707360407a9703a12f204f7fd6\setup.py", line 865, in <module>
          setup(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-r5o90sbm\pillow_c52e20707360407a9703a12f204f7fd6\setup.py", line 702, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-r5o90sbm\pillow_c52e20707360407a9703a12f204f7fd6\setup.py", line 922, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      C:\Users\Administrator\AppData\Local\Temp\pip-install-r5o90sbm\pillow_c52e20707360407a9703a12f204f7fd6\setup.py:44: RuntimeWarning: Pillow 8.1.1 does not support Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

**Comment by iifast2** [comment]
I also got alots of requirements issues, in odoo14, Try to upgrade the Pillow !
Instead of Pillow 8.1.1, try installing a newer version that is compatible with Python 3.10. You can add the following line to your requirements.txt

```
Pillow>=9.0.0
```

Then, Reinstall Requirements :

```
py -m pip install -r requirements.txt
```
