### ISSUE TITLE
Security Issue - database created without master password

### ISSUE THREAD

**Issue by dgagnon** [odoo/odoo#16268]
Impacted versions:
10.0

Steps to reproduce:
- install community version 10 with default settings
- Follow the post setup instructions
- Run OpenVAS security scan

Current behavior:
- Database are being created

Expected behavior:
- No database should be created

Video/Screenshot link (optional):

![odoo](https://cloud.githubusercontent.com/assets/1037561/24719665/8fade824-1a08-11e7-8c26-3a00300e374b.PNG)

postgres  6795  0.0  0.9 234844 19504 ?        Ss   03:07   0:00 postgres: odoo default;env [local] idle
postgres  6796  0.0  0.9 234844 19700 ?        Ss   03:07   0:00 postgres: odoo default env [local] idle
postgres  6797  0.0  1.4 234836 29160 ?        Ss   03:07   0:00 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres  6798  0.0  1.3 234836 27180 ?        Ss   03:07   0:00 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6799  0.0  1.4 234836 29944 ?        Ss   03:07   0:00 postgres: odoo exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6800  0.0  0.9 234844 20048 ?        Ss   03:07   0:00 postgres: odoo a;exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres  6801  0.0  1.0 234840 21300 ?        Ss   03:07   0:00 postgres: odoo a;exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6802  0.0  0.8 234064 16832 ?        Ss   03:07   0:00 postgres: odoo a;exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6803  0.0  1.1 234836 22716 ?        Ss   03:07   0:00 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres  6804  0.0  0.8 234072 17968 ?        Ss   03:07   0:00 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres  6805  0.0  1.1 234940 23896 ?        Ss   03:07   0:00 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6806  0.0  0.9 234064 19156 ?        Ss   03:07   0:00 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres  6807  0.0  1.4 234940 29540 ?        Ss   03:07   0:00 postgres: odoo exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres  6808  0.0  1.2 234892 25844 ?        Ss   03:07   0:00 postgres: odoo a`sleep 600` [local] idle
postgres  6809  0.0  0.9 234592 19232 ?        Ss   03:07   0:00 postgres: odoo a`sleep 600` [local] idle
postgres  6810  0.0  1.4 234940 29956 ?        Ss   03:07   0:00 postgres: odoo a`)` [local] idle
postgres  6812  0.0  1.0 234064 21384 ?        Ss   03:07   0:00 postgres: odoo a`)` [local] idle
postgres  6813  0.0  1.3 234892 26812 ?        Ss   03:07   0:00 postgres: odoo default [local] idle
postgres  6814  0.0  0.8 234064 17640 ?        Ss   03:07   0:00 postgres: odoo default [local] idle
postgres 13260  0.0  1.9 241696 40456 ?        Ss   02:54   0:12 postgres: odoo ;env [local] idle
postgres 13328  0.0  2.1 241660 43244 ?        Ss   02:54   0:12 postgres: odoo a;env [local] idle
postgres 13476  0.0  2.0 241616 42456 ?        Ss   02:54   0:11 postgres: odoo a);env [local] idle
postgres 13639  0.0  1.9 241632 40984 ?        Ss   02:54   0:11 postgres: odoo default;env [local] idle
postgres 13809  0.0  2.0 241580 41656 ?        Ss   02:54   0:12 postgres: odoo default env [local] idle
postgres 14152  0.0  2.0 241600 41268 ?        Ss   02:54   0:12 postgres: odoo a;exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres 14351  0.0  1.9 241648 41000 ?        Ss   02:54   0:13 postgres: odoo a;exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres 14524  0.0  2.0 241664 41692 ?        Ss   02:54   0:12 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres 14785  0.0  2.0 241640 42044 ?        Ss   02:54   0:12 postgres: odoo ';exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres 15081  0.0  2.1 241520 44672 ?        Ss   02:55   0:12 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres 15282  0.0  2.0 241664 42716 ?        Ss   02:55   0:12 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres 15485  0.0  2.1 241652 44432 ?        Ss   02:55   0:12 postgres: odoo exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres 15737  0.0  2.2 241724 45396 ?        Ss   02:55   0:12 postgres: odoo exit(base64_decode('dzRwMXQxX2V2YWw='));# [local] idle
postgres 15909  0.0  2.1 241660 44760 ?        Ss   02:55   0:11 postgres: odoo a`)` [local] idle
postgres 16148  0.0  2.0 241340 42304 ?        Ss   02:55   0:12 postgres: odoo a`sleep 600` [local] idle
postgres 16511  0.0  0.4 233964  8392 ?        Ss   Apr03   0:00 postgres: odoo postgres [local] idle
postgres 17108  0.0  2.0 241692 42524 ?        Ss   02:55   0:12 postgres: odoo default [local] idle
postgres 19512  0.0  0.7 234700 15928 ?        Ss   02:55   0:00 postgres: odoo ;env [local] idle
postgres 19535  0.0  0.7 234700 16164 ?        Ss   02:55   0:00 postgres: odoo a;env [local] idle
postgres 19551  0.0  0.9 234840 20112 ?        Ss   02:55   0:00 postgres: odoo a);env [local] idle
postgres 24748  0.0  1.0 234704 21984 ?        Ss   13:33   0:00 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle
postgres 24749  0.0  1.0 234628 22432 ?        Ss   13:33   0:00 postgres: odoo '.exit(base64_decode('dzRwMXQxX2V2YWw='));// [local] idle

**Comment by dgagnon** [comment]
I am unsure how it happens from the scan, but I can see that the master password changed to ";env" in the odoo.conf file.

**Comment by dgagnon** [comment]
Here are some log items that are interesting

2017-04-05 06:54:13,178 15187 INFO None odoo.service.db: Create database `;env`.
2017-04-05 06:54:13,183 15187 ERROR None odoo.http: database u';env' already exists!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 381, in dispatch
    return g[exp_method_name](*params)
  File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 92, in exp_create_database
    _create_empty_database(db_name)
  File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 84, in _create_empty_database
    raise DatabaseExists("database %r already exists!" % (name,))
DatabaseExists: database u';env' already exists!

**Comment by dgagnon** [comment]
Default configuration has no admin password.  The vulnerability scanner was then able to change the password and create databases.

We can see it here from the IDS:

OSSEC HIDS Notification.
2017 Apr 05 02:52:49

Received From: (ODOO) xxx.xxx.xxx.xxx ->syscheck
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

Integrity checksum changed for: '/etc/odoo/odoo.conf'
Size changed from '215' to '1235'
What changed:
2,3c2,5
< ; This is the password that allows database operations:
< ; admin_passwd = admin
---
> addons_path = /usr/lib/python2.7/dist-packages/odoo/addons
> admin_passwd = letmein
> csv_internal_sep = ,
> data_dir = /var/lib/odoo/.local/share/Odoo
4a7,9
> db_maxconn = 64
> db_name = False
> db_password = False
5a11
> db_template = template1
7,8c13,57
< db_password = False
< addons_path = /usr/lib/python2.7/dist-packages/odoo/addons
Old md5sum was: '5bde3a26d93dc6dd87f4472ab02561de'
New md5sum is : '00d2229b3984187a74f582b914a0d4d7'
Old sha1sum was: '43c43ce5dbcc1b4eeaed7f06398296a340791900'
New sha1sum is : '44588eb531888652167e7675bc137994defd3b62'
 --END OF NOTIFICATION


I highly recommend having a default admin password configured, or force the user to change the default password on installation.

**Comment by dgagnon** [comment]
Closing this as it is a configuration issue.
