### ISSUE TITLE
Bug trying compute price from bom with addon product_extended

### ISSUE THREAD

**Issue by mamcode** [odoo/odoo#16269]
Impacted versions:
10.0 CE

Steps to reproduce:
Click on "button" "Compute from BOM" in product form view

Current behavior:

Raise an error with the following traceback:
```
Traceback (most recent call last):
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/manuel/Envs/odoo10/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/manuel/Envs/odoo10/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/manuel/Envs/odoo10/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/manuel/Envs/odoo10/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/manuel/Envs/odoo10/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/manuel/Envs/odoo10/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/manuel/Envs/odoo10/odoo/addons/product_extended/models/product.py", line 15, in compute_price
    return template.product_variant_id.compute_price()
  File "/home/manuel/Envs/odoo10/odoo/addons/product_extended/models/product.py", line 29, in compute_price
    price = product._calc_price(bom)
  File "/home/manuel/Envs/odoo10/odoo/addons/product_extended/models/product.py", line 47, in _calc_price
    total_cost += (order.time_cycle_manual/60) * order.workcenter_id.costs_hour
AttributeError: 'mrp.workcenter' object has no attribute 'costs_hour'
```
Expected behavior:
Standard Price Computed from BOM.

![screenshot-localhost 8083-2017-04-05-20-01-33](https://cloud.githubusercontent.com/assets/334317/24731816/83ba71a4-1a3a-11e7-9461-a5fbae4eefa4.png)

![fireshot capture 14 - pcsc234 computer sc234 - odoo_ - http___localhost_8083_web](https://cloud.githubusercontent.com/assets/334317/24731829/a26a3026-1a3a-11e7-8799-9996d1a49b86.png)

**Comment by cpintofonseca** [comment]
I can confirm this issue.

The error is self explanatory, the field costs_hour doesn't exist in the mrp.workcenter object in Odoo CE because it's being created in mrp_account OE module.

**Comment by Yenthe666** [comment]
@jco-odoo could this be a leftover from changing something from CE to OE? Could you have a look?
Error is coming from line https://github.com/odoo/odoo/blob/10.0/addons/product_extended/models/product.py#L46 and it is because the field `costs_hour` is only available on ENT. 
Cc @mart-e

**Comment by Yenthe666** [comment]
@mart-e any update about https://github.com/odoo/odoo/pull/20899?

**Comment by mart-e** [comment]
Fixed at https://github.com/odoo/odoo/commit/ffbcf69af5a06b6d99d4208a17ffa4a368233845, thanks
