### ISSUE TITLE
Access denied is displayed after a successful login using keycloak

### ISSUE THREAD

**Issue by zhengdechang** [odoo/odoo#162777]
Impacted versions: 17.0

Steps to reproduce:

Current behavior:
2024-04-22 08:15:22,045 1 ERROR jancsitech-odoo odoo.addons.auth_oauth.controllers.main: Exception during request handling 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_oauth/controllers/main.py", line 139, in signin
    _, login, key = request.env['res.users'].with_user(SUPERUSER_ID).auth_oauth(provider, kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_oauth/models/res_users.py", line 124, in auth_oauth
    validation = self._auth_oauth_validate(provider, access_token)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_oauth/models/res_users.py", line 49, in _auth_oauth_validate
    raise Exception(validation['error'])
Exception: invalid_request
2024-04-22 08:15:22,046 1 INFO jancsitech-odoo werkzeug: 10.10.99.9 - - [22/Apr/2024 08:15:22] "GET /auth_oauth/signin?state=%7B%22d%22%3A+%22jancsitech-odoo%22%2C+%22p%22%3A+4%2C+%22r%22%3A+%22http%253A%252F%252F10.10.98.56%253A8069%252Fweb%22%7D&session_state=6120c20c-2d17-43b7-989d-2d2e618a84cd&iss=http%3A%2F%2Fkeycloak.corp.jancsitech.net%3A8080%2Frealms%2Fodoo&access_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzYjM1RENJYjNyOTRGLTVqMzZ1ZFFlaGJ4YUk5WExLanczNHBHeDdZNFRNIn0.eyJleHAiOjE3MTM3NzQ2MjEsImlhdCI6MTcxMzc3MzcyMSwiYXV0aF90aW1lIjoxNzEzNzY4ODg2LCJqdGkiOiJiNDRlYWU1OS0wOWIyLTQ5OTgtOWQ0OS1mZTk2ZTcwY2EzYTUiLCJpc3MiOiJodHRwOi8va2V5Y2xvYWsuY29ycC5qYW5jc2l0ZWNoLm5ldDo4MDgwL3JlYWxtcy9vZG9vIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJicm9rZXIiLCJhY2NvdW50Il0sInN1YiI6ImQ5YTlhNjFhLWFlNGQtNDg0MS05ZjRkLWRhYThjZjBlMzk3OCIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9kb28iLCJzZXNzaW9uX3N0YXRlIjoiNjEyMGMyMGMtMmQxNy00M2I3LTk4OWQtMmQyZTYxOGE4NGNkIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtb2RvbyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJvZG9vIjp7InJvbGVzIjpbIm9kb28tcm9sZSIsInVtYV9wcm90ZWN0aW9uIl19LCJicm9rZXIiOnsicm9sZXMiOlsicmVhZC10b2tlbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctYXBwbGljYXRpb25zIiwidmlldy1jb25zZW50Iiwidmlldy1ncm91cHMiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsImRlbGV0ZS1hY2NvdW50IiwibWFuYWdlLWNvbnNlbnQiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIG9kb28iLCJzaWQiOiI2MTIwYzIwYy0yZDE3LTQzYjctOTg5ZC0yZDJlNjE4YTg0Y2QiLCJ1cG4iOiJ6aGVuZ2RlY2hhbmciLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYWRkcmVzcyI6e30sIm5hbWUiOiJkZWNoYW5nIHpoZW5nIiwiZ3JvdXBzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1vZG9vIiwidW1hX2F1dGhvcml6YXRpb24iXSwicHJlZmVycmVkX3VzZXJuYW1lIjoiemhlbmdkZWNoYW5nIiwiZ2l2ZW5fbmFtZSI6ImRlY2hhbmciLCJmYW1pbHlfbmFtZSI6InpoZW5nIiwiZW1haWwiOiJ6aGVuZ2RlY2hhbmdAamFuY3NpdGVjaC5uZXQifQ.a5vgQa8B5Hgxvz5-8hHw4AYTCMjzkIvToN7DMvBk-lIzXJ3riBa25JvDwjX4tJbSMbJmmta-cpgO7xE9VfrSI-aXW5iclSxjodAiBEqxW-QP9pLTrn5-N12b-BHDkcyxyy8XHYxcL_qEwFRE3OjhSZegWwKq8_DRYcn41RmyOkcJTtmqUwxJ3z8OD_WZZYXV0f4npEuM4lpcE1AakLkl3YEOgPUAhWPiLZsb4P0Zo3I5kL-vgfVmHyu1hXYW0vM9R_ucK_M7hc3PQj8bhz8wMfjt4zV8i6fnYu6O-Uhb4zj_kWaLmlnfPjk0081SWPjG8wGjH8s-vf4W1ynMB6XqFA&token_type=Bearer&expires_in=900 HTTP/1.1" 303 - 2 0.001 0.014
2024-04-22 08:15:22,197 1 INFO jancsitech-odoo werkzeug: 10.10.99.9 - - [22/Apr/2024 08:15:22] "GET /web/login?oauth_error=2 HTTP/1.1" 200 - 5 0.005 0.0332024-04-22 08:15:22,368 1 INFO ? werkzeug: 10.10.99.9 - - [22/Apr/2024 08:15:22] "GET /web/static/src/libs/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 - 0 0.000 0.002

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/77528948/69d09c77-27e1-4858-94d4-38e9a66ee566)

**Comment by huangweixiao** [comment]
后来解决了吗

**Comment by notleanbarba** [comment]
did you get a solution?
