### ISSUE TITLE
error outgoing email

### ISSUE THREAD

**Issue by kochanA** [odoo/odoo#162909]
Impacted versions: 17

Steps to reproduce: configured my outgoing mail server, i did a test which went well, now try to send email

Current behavior: 
SMTPDataError: 550
5.7.60 SMTP; Client does not have permissions to send as this sender 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_mail_server.py", line 695, in send_email
    smtp.send_message(message, smtp_from, smtp_to_list)
  File "/usr/lib/python3.11/smtplib.py", line 986, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 908, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'5.7.60 SMTP; Client does not have permissions to send as this sender')

Expected behavior: correctly sent e-mail

Is it important that my email address is in Outlook and is different from the administrator's email address?

**Comment by kochanA** [comment]
Admin email need to be same as outgoing email server
