### ISSUE TITLE
[17.0][BUG] ValueError: can only parse strings

### ISSUE THREAD

**Issue by Senpaixyz** [odoo/odoo#163465]
Impacted versions: 17.0

Steps to reproduce: Pull the latest commit then restart development local server then go to Settings

Current behavior: File "src\lxml\parser.pxi", line 1912, in lxml.etree._parseMemoryDocument

Expected behavior: Supposedly there's no error should show up since I  just pull the previous updates from 17.0 branch

Video/Screenshot link (optional):

<img width="591" alt="parser-pxi-error" src="https://github.com/odoo/odoo/assets/64669453/1bc77443-6321-44a2-9579-6dbe447a70e0">

**Comment by bluesmooth22** [comment]
Im getting the same issue, hope anyone got a fix.

```
2024-04-29 02:37:37,060 14735 ERROR wproduction17c odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/Walkintour-community/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/Walkintour-community/odoo/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/Walkintour-community/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/Walkintour-community/odoo/odoo/modules/loading.py", line 249, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/home/odoo/Walkintour-community/odoo/odoo/addons/base/models/ir_ui_view.py", line 2103, in _validate_module_views
    view._check_xml()
  File "/home/odoo/Walkintour-community/odoo/odoo/addons/base/models/ir_ui_view.py", line 382, in _check_xml
    raise err from None
  File "/home/odoo/Walkintour-community/odoo/odoo/addons/base/models/ir_ui_view.py", line 372, in _check_xml
    combined_arch = view._get_combined_arch()
  File "/home/odoo/Walkintour-community/odoo/odoo/addons/base/models/ir_ui_view.py", line 949, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/Walkintour-community/odoo/odoo/addons/base/models/ir_ui_view.py", line 867, in _combine
    combined_arch = etree.fromstring(self.arch)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
odoo.exceptions.ValidationError: Error while parsing or validating view:

can only parse strings
2024-04-29 02:37:37,060 14735 WARNING wproduction17c odoo.http: Error while parsing or validating view:

can only parse strings 
```

**Comment by vava-odoo** [comment]
There were a few problems with lxlm lately, please have a look here https://github.com/odoo/odoo/issues/163370
