### ISSUE TITLE
odoo server error

### ISSUE THREAD

**Issue by FlorDir** [odoo/odoo#164849]
Traceback (most recent call last):
  File "/opt/odoo/sources/meli/odoo_connector_api_producteca/models/connection_binding_sale_order.py", line 716, in post_invoices
    inv.action_post()
  File "/opt/odoo/addons/sale/models/account_move.py", line 63, in action_post
    res = super(AccountMove, self).action_post()
  File "/opt/odoo/sources/rma/rma/models/account_move.py", line 41, in action_post
    return super().action_post()
  File "/opt/odoo/sources/odoo-argentina/account_payment_group/models/account_move.py", line 78, in action_post
    res = super(AccountMove, self).action_post()
  File "/opt/enterprise/account_accountant/models/account_move.py", line 24, in action_post
    res = super().action_post()
  File "/opt/odoo/addons/account/models/account_move.py", line 3739, in action_post
    other_moves._post(soft=False)
  File "/opt/enterprise/l10n_ar_edi/models/account_move.py", line 168, in _post
    self._cr.commit()
  File "/opt/odoo/odoo/sql_db.py", line 461, in commit
    self.flush()
  File "/opt/odoo/odoo/sql_db.py", line 134, in flush
    self.transaction.flush()
  File "/opt/odoo/odoo/api.py", line 870, in flush
    env_to_flush.flush_all()
  File "/opt/odoo/odoo/api.py", line 734, in flush_all
    self[model_name].flush_model()
  File "/opt/odoo/odoo/models.py", line 5598, in flush_model
    self._flush(fnames)
  File "/opt/odoo/odoo/models.py", line 5671, in _flush
    process(model, id_vals)
  File "/opt/odoo/odoo/models.py", line 5621, in process
    model.browse(ids)._write(vals)
  File "/opt/odoo/odoo/models.py", line 3862, in _write
    cr.execute(query, params + [sub_ids])
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SerializationFailure: no se pudo serializar el acceso debido a un update concurrente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/opt/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('res.users', <function Users._has_group at 0x7f0c32c3e4c0>, 132, 'base.group_public')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/sources/meli/odoo_connector_api_producteca/models/wizards.py", line 318, in producteca_sale_process
    raise e
  File "/opt/odoo/sources/meli/odoo_connector_api_producteca/models/wizards.py", line 305, in producteca_sale_process
    prorder.post_invoices()
  File "/opt/odoo/sources/meli/odoo_connector_api_producteca/models/connection_binding_sale_order.py", line 722, in post_invoices
    so.message_post(body=str(error))
  File "/opt/odoo/addons/sale/models/sale_order.py", line 1224, in message_post
    return super(SaleOrder, self.with_context(mail_post_autofollow=self.env.context.get('mail_post_autofollow', True))).message_post(**kwargs)
  File "/opt/odoo/addons/rating/models/mail_thread.py", line 15, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 2000, in message_post
    if self.env.user._is_public() and guest:
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 1054, in _is_public
    return self.has_group('base.group_public')
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 969, in has_group
    return self._has_group(group_ext_id)
  File "<decorator-gen-111>", line 2, in _has_group
  File "/opt/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/res_users.py", line 984, in _has_group
    self._cr.execute("""SELECT 1 FROM res_groups_users_rel WHERE uid=%s AND gid IN
  File "/opt/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InFailedSqlTransaction: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://186.138.215.48:8069/web/assets/17105-6898736/web.assets_backend.min.js:993:163)
    at XMLHttpRequest.<anonymous> (http://186.138.215.48:8069/web/assets/17105-6898736/web.assets_backend.min.js:1001:13)

**Comment by nikhilnakrani99** [comment]
File "/opt/odoo/sources/meli/odoo_connector_api_producteca/models/connection_binding_sale_order.py", line 716, in post_invoices

This suggests the error starts in a custom module called "**odoo_connector_api_producteca**".

This is not Odoo addons error.

Review the **post_invoices** method in the custom module.
