### ISSUE TITLE
Login page missing CSS: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/d7/d764ceb077964b7b3152235918b5c065424133d7'

### ISSUE THREAD

**Issue by gregory112** [odoo/odoo#165181]
Impacted versions:
odoo 17, Docker container, with PostgreSQL database (deployed with docker-compose)

Steps to reproduce:
Create a new Odoo with existing database.

Current behavior:
![image](https://github.com/odoo/odoo/assets/34415825/519e00ea-b417-4f1f-afde-49cbccd93ed3)

```
2024-05-13 06:32:10,509 1 INFO odoo werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/login HTTP/1.1" 200 - 5 0.012 0.062
2024-05-13 06:32:10,654 1 INFO ? werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/static/src/libs/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - 1 0.005 0.093
2024-05-13 06:32:10,662 1 INFO odoo werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/binary/company_logo HTTP/1.1" 200 - 3 0.009 0.075
2024-05-13 06:32:10,671 1 ERROR odoo odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2192, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1912, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/binary.py", line 136, in content_assets
    stream = request.env['ir.binary']._get_stream_from(attachment, 'raw', filename)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_binary.py", line 129, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_binary.py", line 73, in _record_to_stream
    return Stream.from_attachment(record)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 498, in from_attachment
    stat = os.stat(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/d7/d764ceb077964b7b3152235918b5c065424133d7'
2024-05-13 06:32:10,673 1 INFO odoo werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/assets/fa68d48/web.assets_frontend.min.css HTTP/1.1" 500 - 5 0.015 0.098
2024-05-13 06:32:10,824 1 INFO odoo werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/assets/5ec42d9/web.assets_frontend_minimal.min.js HTTP/1.1" 200 - 5 0.008 0.034
2024-05-13 06:32:10,933 1 INFO ? werkzeug: 172.18.0.12 - - [13/May/2024 06:32:10] "GET /web/static/img/favicon.ico HTTP/1.1" 200 - 1 0.006 0.035
```

Expected behavior:
Working as usual

**Comment by gregory112** [comment]
Is this somehow related to the data in database? Because I did see some WAL related errors when I backed up my PostgreSQL instance due to harddrive problems. I'm afraid data corruption might cause this? If so, is it possible to somehow reset it (as I now have good drive)?

**Comment by tjventurini** [comment]
I guess I have the same kind of issue.

![image](https://github.com/odoo/odoo/assets/4708070/976c7b6b-7a6e-4bac-9fc3-c4eb101bd31d)

Here is the repository: https://github.com/tjventurini/odoo-setup

At first everything goes well, but after a couple of hours the assets are broken. When I then try to regenerate the assets if first works well again but stops working completely shortly after.

**Comment by tjventurini** [comment]
Is it possible @gregory112 that you too changed the name of the service?
For me it is working again since I changed it back to `web`

**Comment by tjventurini** [comment]
ok, stopped working after dinner 😅

**Comment by gregory112** [comment]
@tjventurini Nope, I didn't change anything, other than migrating my database to other disk.
In fact it is broken since the first set up. Might probably a race condition or something. I saw some old issue that might be related too: https://github.com/odoo/odoo/issues/13808

**Comment by tjventurini** [comment]
Did you try to clear the cache using the query shown in this?
It did not help me but I would like to know if it fixed the issue for you ^^

**Comment by tjventurini** [comment]
I also tried to regenerate the asses again with the following command.
`docker compose exec --user postgres postgres psql --username=odoo --dbname=odoo -c "delete from ir_attachment where res_model='ir.ui.view' and name like '%assets_%'`

**Comment by markoppp** [comment]
Odoo 17, same problem

**Comment by chrisb-c01** [comment]
We are encountering the same issue after applying Odoo 17 commits after 27th of May ([this](https://github.com/odoo/odoo/commit/3383d5bd68bfc13b7881f72e5adbb7c27a6df30e) commit). Not quite sure what change is causing this.

Error log:

```
2024-06-13 16:42:57,406 2221 INFO odoo odoo.addons.base.models.ir_http: Generating routing map for key None
2024-06-13 16:43:00,419 2221 INFO odoo odoo.addons.base.models.ir_attachment: _file_write writing /opt/odoo/customer/staging/data/filestore/odoo/36/3670dc6c635e0fefe66991ec6aebae60a3427c76
Traceback (most recent call last):
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/addons/base/models/ir_attachment.py", line 135, in _file_write
    with open(full_path, 'wb') as fp:
PermissionError: [Errno 13] Permission denied: '/opt/odoo/customer/staging/data/filestore/odoo/36/3670dc6c635e0fefe66991ec6aebae60a3427c76'
2024-06-13 16:43:00,436 2221 INFO odoo odoo.addons.base.models.assetsbundle: Generating a new asset bundle attachment /web/assets/5699cba/web.assets_web.min.js (id:321)
2024-06-13 16:43:00,457 2221 INFO odoo odoo.addons.base.models.assetsbundle: Deleting attachments [270] (matching /web/assets/_______/web.assets_web.min.js) because it was replaced with /web/assets/5699cba/web.assets_web.min.js
2024-06-13 16:43:00,469 2221 ERROR odoo odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 2173, in __call__
    response = request._serve_db()
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 1748, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 1775, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 1892, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/addons/web/controllers/binary.py", line 136, in content_assets
    stream = request.env['ir.binary']._get_stream_from(attachment, 'raw', filename)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/addons/base/models/ir_binary.py", line 129, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/addons/base/models/ir_binary.py", line 73, in _record_to_stream
    return Stream.from_attachment(record)
  File "/opt/approot/build.20240613-183857-9acce3bf/parts/odoo/odoo/http.py", line 498, in from_attachment
    stat = os.stat(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/odoo/customer/staging/data/filestore/odoo/36/3670dc6c635e0fefe66991ec6aebae60a3427c76'
2024-06-13 16:43:00,471 2221 INFO odoo werkzeug: 89.91.80.137 - - [13/Jun/2024 16:43:00] "GET /web/assets/5699cba/web.assets_web.min.js HTTP/1.0" 500 - 35 0.089 3.526
2024-06-13 16:43:00,750 2218 INFO odoo odoo.addons.base.models.assetsbundle: Generating a new asset bundle attachment /web/assets/9c804b4/web.assets_web.min.css (id:322)
2024-06-13 16:43:00,753 2218 INFO odoo odoo.addons.base.models.assetsbundle: Deleting attachments [318] (matching /web/assets/_______/web.assets_web.min.css) because it was replaced with /web/assets/9c804b4/web.assets_web.min.css
2024-06-13 16:43:00,797 2218 INFO odoo werkzeug: 89.91.80.137 - - [13/Jun/2024 16:43:00] "GET /web/assets/9c804b4/web.assets_web.min.css HTTP/1.0" 200 - 36 0.100 3.848
2024-06-13 16:43:00,941 2224 INFO odoo werkzeug: 89.91.80.137 - - [13/Jun/2024 16:43:00] "GET /web/manifest.webmanifest HTTP/1.0" 200 - 9 0.005 0.006
2024-06-13 16:43:02,551 2221 INFO odoo werkzeug: 89.91.80.137 - - [13/Jun/2024 16:43:02] "GET /web/service-worker.js HTTP/1.0" 200 - 1 0.001 0.003
```

**Comment by mohammadalaaavalonaicom** [comment]
just run command in compose.yml--> command: odoo -u all -d <db_name> and in DB run DELETE FROM ir_attachment WHERE res_model='ir.ui.view' AND name LIKE '%assets_%'; then restart docker compose

**Comment by gregory112** [comment]
@mohammadalaaavalonaicom thanks, that works, I saw that already somewhere and thought that wouldn't work, but it does.
