### ISSUE TITLE
Odoo POS occasionally starts two sessions

### ISSUE THREAD

**Issue by multiwebinc** [odoo/odoo#16609]
**Impacted versions**: 10

**Steps to reproduce**: Unknown

**Current behavior**: Maybe once every couple of weeks I get a call from our staff members that they can't start a POS session. When I log in as their user and click on "Point of Sale" in the menu, I get the following error:

```
Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo10/addons/web/controllers/main.py", line 820, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/odoo10/addons/web/controllers/main.py", line 842, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo/odoo10/odoo/models.py", line 4671, in search_read
    result = records.read(fields)
  File "/opt/odoo/odoo10/odoo/models.py", line 3007, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/opt/odoo/odoo10/odoo/models.py", line 5186, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo10/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo10/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo10/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo10/odoo/fields.py", line 926, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/odoo10/addons/point_of_sale/models/pos_config.py", line 141, in _compute_current_session
    pos_config.current_session_id = session
  File "/opt/odoo/odoo10/odoo/fields.py", line 887, in __set__
    value = self.convert_to_cache(value, record)
  File "/opt/odoo/odoo10/odoo/fields.py", line 1901, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for pos.config.current_session_id: pos.session(165, 164)
```

Somehow two sessions are created instead of one and I have to delete them so that they can open a new working session. Unfortunately I don't know how to reproduce it. It has only happened to my staff members. Maybe they are double clicking on something instead of single clicking and no checks are being done server-side. Hopefully the error above should give someone a clue.

**Video/Screenshot link (optional)**:

<img src="http://i.imgur.com/Cwc2w8G.png">

**Comment by mart-e** [comment]
Hello,

The error when having two opened sessions should be fixed at ec17d636a9e0ccf4f0e9826832510a0faa163e0d
Please update your code.

**Comment by multiwebinc** [comment]
This error hadn't occurred for several months, however it just did again today:

<img src="https://imgur.com/a/jhuTq">

Installed version is greater than https://github.com/odoo/odoo/commit/ec17d636a9e0ccf4f0e9826832510a0faa163e0d

However there was no traceback, only a message that said something along the lines of "You cannot create two active sessions with the same user".

**Comment by multiwebinc** [comment]
After months of no errors, I'm now getting my staff calling me every 2-3 days with this error. I have no idea how to debug it, but I'm more than happy to provide logs or whatever information necessary to get it fixed. The only way to fix it is to delete both sessions that say "In Progress". Just a thought, could this be people double clicking instead of single clicking?

Also, perhaps it is worth noting that the details of all previous sessions change after the two sessions that cause the error are deleted. See below.

This is during the error condition:

![screenshot_20171029_155606](https://user-images.githubusercontent.com/901732/32148874-1dee6ba2-bcc2-11e7-8cf5-a9972619af16.png)

This is after I delete the two first sessions:

![screenshot_20171029_155515](https://user-images.githubusercontent.com/901732/32148872-1421851e-bcc2-11e7-84e7-3ceb807ebd19.png)

**Comment by mart-e** [comment]
Do you have some specific security rules on the pos.session object? Or do you use multi-company?
Could you try applying that commit to test? odoo-dev/odoo@53ef5c9d1f9

**Comment by estekadigital** [comment]
I know this bug is closed but I got the same problem on an odoo12 pos installation. Might be the case the user is double clicking on restore session?
