### ISSUE TITLE
Odoo clients error

### ISSUE THREAD

**Issue by Rushroastery** [odoo/odoo#166096]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of null (reading 'getElementById')
TypeError: Cannot read properties of null (reading 'getElementById')
    at get editable (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3691:56)
    at get $editable (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3692:31)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:2017:49)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:4:30)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:2281:7)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3695:321)
![Screenshot_20240519_204113_Gallery](https://github.com/odoo/odoo/assets/170245974/c9e96576-c0e8-4bc3-9b0a-55801b1bc8fc)
![Screenshot_20240519_204113_Gallery](https://github.com/odoo/odoo/assets/170245974/b6b7bf47-ad48-409a-897c-ebdd79f4c5fc)

### Log Output

```shell
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of null (reading 'getElementById')
TypeError: Cannot read properties of null (reading 'getElementById')
    at get editable (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3691:56)
    at get $editable (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3692:31)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:2017:49)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:4:30)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:2281:7)
    at WysiwygAdapterComponent.destroy (https://rushrostery.odoo.com/web/assets/4ce8dd1/website.backend_assets_all_wysiwyg.min.js:3695:321)
```

**Comment by vava-odoo** [comment]
Hi @Rushroastery 
Could you provide clear steps to reproduce the issue?
