### ISSUE TITLE
Server Error when installing eCommerce Delivery Module

### ISSUE THREAD

**Issue by ffadaei** [odoo/odoo#16664]
**Impacted versions:**
Odoo 10

**Steps to reproduce:**
eCommerce Check-out was timing out, so I uninstalled all the delivery modules and attempted to reinstall them...  But now I am getting a traceback error when I attempt to reinstall the eCommerce Delivery Module...  

**Current behavior:**
Will not install, still cannot process checkout beyond viewing cart

**Expected behavior:**
eCommerce Delivery Module should install! and eCommerce checkout should work!

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/9721960/25437706/dbe562a8-2a5c-11e7-8f0d-ad7a49523933.png)

**Traceback**

```
Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/delivery/models/delivery_carrier.py", line 253, in create
    res = super(DeliveryCarrier, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3867, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product/models/product.py", line 313, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3867, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/dist-packages/odoo/addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product/models/product_template.py", line 265, in create
    template = super(ProductTemplate, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3901, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1001286, null, 1.00, null, 1, null, 1, 1, null, null, 2017-04-26 13:40:51.71784, 1, t, t, null, 1, 1, null, null, null, 2017-04-26 13:40:51.71784, t, 1, null, f, consu, no-message, null, manual, order, no, none, null, null, null, 0, null, f, t, 0, empty, -272, null, null, null, null, null, null, f, 1, 1, null, receive, no-message, f, f, null, null, null, null, f, f, null, null, null, null, Days_7, null, null, null, null, null, f, null, null, f, f, null, null, f, null, Unlisted, null, null, null, Chinese, null, null, null, null, null, null).
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/website_sale_delivery/data/website_sale_delivery_data.xml:3, near
<record id="delivery.free_delivery_carrier" model="delivery.carrier">
        <field name="website_published" eval="True"/>
    </record>
```

**Comment by mart-e** [comment]
Hello,

Did you removed the delivery method "Free delivery charges" by any chance?
Please upgrade the delivery module first to get it back and the install should work fine.

**Comment by ffadaei** [comment]
Thank you, will try now

**Comment by ffadaei** [comment]
I have don as you suggested and made some progress, but still cannot get the module to work.  I am attaching screenshots so that you can see my process and configuration.  Am I missing something somewhere?  Thanks again for your help!

When a public user attempts to submit order after entering contact details
![image](https://cloud.githubusercontent.com/assets/9721960/25832201/cfc16874-342e-11e7-9045-ba7ac641020d.png)

![image](https://cloud.githubusercontent.com/assets/9721960/25832232/012f6c94-342f-11e7-85c9-b6e227d18160.png)

Public User receives the following error:
![image](https://cloud.githubusercontent.com/assets/9721960/25832281/3995d866-342f-11e7-84af-ac85b23e5ec3.png)



![image](https://cloud.githubusercontent.com/assets/9721960/25832025/a0c99614-342d-11e7-921a-e206b058293c.png)

![image](https://cloud.githubusercontent.com/assets/9721960/25832042/bf0f0014-342d-11e7-8bd7-45c27c8981bc.png)

![image](https://cloud.githubusercontent.com/assets/9721960/25832070/eb584ce8-342d-11e7-8f60-60ad063f87af.png)

**Comment by mart-e** [comment]
Hello,

Sorry but we try to keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

For your specific issue, please make sure the delivery methods are enabled in the website admin configuration,

Regards
