### ISSUE TITLE
Developer Mode produdes js error in odoo 10 enterprise

### ISSUE THREAD

**Issue by auditum-jsa** [odoo/odoo#16660]
Impacted versions: 10 Enterprise -bug is not present on odoo 10 community

Steps to reproduce: activate the developer mode (with or without assets, both lead to the error)

Current behavior: it is not possible to go into apps, a popup window shows up with an error 
"Uncaught TypeError: Cannot read property 'widgets' of undefined"
http://localhost:8069/web/content/494-7d88336/web.assets_backend.js:1899
Zurückverfolgung
TypeError: Cannot read property 'widgets' of undefined
    at Class.current_action_updated (http://localhost:8069/web/content/494-7d88336/web.assets_backend.js:1899:454)
    at Class.current_action_updated (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3013:616)
    at Class.current_action_updated (http://localhost:8069/web/content/494-7d88336/web.assets_backend.js:1715:934)
    at http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3127:11
    at Class.<anonymous> (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3125:81)
    at Class.trigger (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3099:180)
    at Class._trigger_up (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3103:365)
    at Class._trigger_up (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3103:449)
    at Class.trigger_up (http://localhost:8069/web/content/493-4e01932/web.assets_common.js:3103:280)
    at Object.<anonymous> (http://localhost:8069/web/content/494-7d88336/web.assets_backend.js:1633:31)

Expected behavior:  when the developer mode is activated, i should be able to use odoo as i usually do

Screenshot link :
![odoo_10e_js_fehler](https://cloud.githubusercontent.com/assets/22195128/25434527/eb21db04-2a8c-11e7-9df8-d39c9ee9d2d6.png)

**Comment by bistaray** [comment]
Can you replicate this problem on Runbot?  (I can't).

(for more information on Runbot, see https://www.odoo.com/forum/help-1/question/what-is-odoo-runbot-19410 )

1. Visit http://runbot.odoo.com

2. Click on odoo/enterprise at the top:

![image](https://cloud.githubusercontent.com/assets/13910162/25509722/ebece52c-2b6f-11e7-9fac-f4e519f3f364.png)

3.  Next, click on the launch (blue) button within any green build:

![image](https://cloud.githubusercontent.com/assets/13910162/25509744/0a66d102-2b70-11e7-84bd-0a1ae6912a1e.png)

4. The login and password is always **admin / admin**

5. Try to replicate your problem.

You can see there that I activated the Developer Mode in the current build of Odoo v10 and did not have the client error you posted:

![image](https://cloud.githubusercontent.com/assets/13910162/25509781/3f0f4844-2b70-11e7-99ba-c34c8b2381b2.png)

If the issue you post here cannot be replicated, then it is generally assumed that there is something in your local setup that is missing, or is causing the problem.

**Comment by xmo-odoo** [comment]
Can not replicate on either a local instance or runbot either, assuming some sort of local assets corruption until more information is provided.

Nice guide @bistaray
