### ISSUE TITLE
Cannot print, send email, or view pdf file. PDF content is 0KB. Odoo server error

### ISSUE THREAD

**Issue by arafatx** [odoo/odoo#16706]
Impacted versions: 

Odoo 10.0-20170428 (Community Edition)

Steps to reproduce: 1) Create a test invoice, validate the invoice then try to print it. 

OR 2) Create a test invoice, valildate the invoice and send the invoice to a customer.

Current behavior: The first time, when clicking on printing invoice, the browser downloaded a pdf file but the content inside pdf is 0kb (cannot view). The second time when clicking on printing invoice an error message appear (like in the screenshot). 

Expected behavior: Able to download pdf file or view it. the pdf file contains 0kb which is not viewable

Video/Screenshot link (optional):

Error message:

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 192, in get_pdf
    save_in_attachment = self._check_attachment_use(docids, report)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 326, in _check_attachment_use
    pdf = base64.decodestring(pdf)
  File "/usr/lib64/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None
```

**Comment by arafatx** [comment]
Solved this. I upgraded the Wkhtmltopdf to the latest version manually following this guide:
http://webkul.com/blog/odoo-wkhtmltopdf-upgrade-version/

**Comment by vadermemo** [comment]
This bug again, 
now in CentOS 7 distribution
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 192, in get_pdf
    save_in_attachment = self._check_attachment_use(docids, report)
  File "/usr/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 326, in _check_attachment_use
    pdf = base64.decodestring(pdf)
  File "/usr/lib64/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None
