### ISSUE TITLE
[V9,V10] Assertion error while saving a record.

### ISSUE THREAD

**Issue by MeetSCS** [odoo/odoo#16717]
Impacted versions:
V9, V10
Steps to reproduce:
1. Install Survey Module.
2. Create a new survey in draft stage with 1 page and 1 question.
4. Edit survey and create a new question set question type numeric value go to options tab and check validate entry check box, enter minimum value greater than 0 and keep maximum value 0 and save this question.
5. Save parent pages record and save parent record, it violate the min value constraint.
6. Open page we have created and delete the question line which we have created, save record and it will throw an assertion error.

Current behavior:

Assertion Error is thrown.

Expected behavior:

Assertion Error should not be displayed and record should be updated properly.

Video/Screenshot link (optional):

[assertion_issue.mp4.tar.gz](https://github.com/odoo/odoo/files/965932/assertion_issue.mp4.tar.gz)

**Comment by MeetSCS** [comment]
cc @Yenthe666 Can you please help with this ? It seems this issue is related to #9025.

**Comment by MeetSCS** [comment]
@Yenthe666 @pedrobaeza @dreispt  Can you please help to point out this issue to right person ? 

Regards.

**Comment by dreispt** [comment]
Can you post the traceback?

**Comment by MeetSCS** [comment]
@dreispt Thank you for your response. Here is the traceback.

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/addons/mail/models/mail_thread.py", line 281, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 3854, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 4012, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/osv/fields.py", line 829, in set
    obj.write(cr, user, [act[1]], act[2], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 3854, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 4012, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/osv/fields.py", line 831, in set
    obj.unlink(cr, user, [act[1]], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 3686, in unlink
    self.delete_workflow(cr, uid, ids, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/models.py", line 3615, in delete_workflow
    workflow.trg_delete(uid, self._name, res_id, cr)
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/workflow/__init__.py", line 45, in trg_delete
    return WorkflowService.new(cr, uid, res_type, res_id).delete()
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/workflow/service.py", line 19, in new
    return cls(Session(cr, uid), Record(model_name, record_id))
  File "/home/odoo/runbot/extra/runbot/static/build/226938-9-0-3bdea9/openerp/workflow/helpers.py", line 13, in __init__
    assert isinstance(record_id, (int, long))
AssertionError

**Comment by MeetSCS** [comment]
I had a look into the issue and found that dataset is not properly updated when o2m line is deleted. This issue replicates only when there is o2m field inside o2m and some constraint is fired based on child o2m field. I already attached video which will help to understand the exact problem.

**Comment by MeetSCS** [comment]
@dreispt Any updates on this issue ? Did you face the issue ?

**Comment by MeetSCS** [comment]
@ged-odoo @rim-odoo @mart-e   Can you please share your inputs on this issue ? As said by @mart-e traceback is not displayed in issue #16911 but this issue throws an traceback which is not good thing.

**Comment by MeetSCS** [comment]
ping

**Comment by MeetSCS** [comment]
@mart-e @ged-odoo @rim-odoo @Yenthe666 @dreispt @pedrobaeza Can you please share your valuable input on this issue ?

**Comment by Yenthe666** [comment]
@MeetSCS I understand that this issue is probably important for you but please don't ping a dozen of people a day.  Most of the guys at Odoo get pinged a lot and it only makes them grumpy. (I'm looking at you Martin 😉)
I just tried this on the latest runbot 10.0 (Enterprise) without any issues though?

**Comment by MeetSCS** [comment]
@Yenthe666 Sure. I was just curious about the issue. Can you please try it with community version ?

**Comment by Yenthe666** [comment]
@MeetSCS it works perfectly fine on the latest community version too. 
Your first comment says:
"Edit survey and create a new question set question type numeric value go to options tab and check validate entry check box, enter minimum value greater than 0 and keep maximum value 0 and save this question."

Hoever, this is no longer possible since there is a validation on this:
![image](https://cloud.githubusercontent.com/assets/6352350/26092010/e0ff3824-3a0e-11e7-9074-f1cd6fa6e685.png)
![image](https://cloud.githubusercontent.com/assets/6352350/26092023/edea88cc-3a0e-11e7-93bb-52168937cf15.png)

Can you please try again or update your own Odoo environment? 😉

**Comment by MeetSCS** [comment]
@Yenthe666 I just took latest pull of v9 and v10 and checked in both version issue is still there.

Once you face this "Max value..." constraint is fired and you will delete that line (question) and save the record you will face the assertion error. You can check video I have attached in description.

Here is the screenshot with latest v10 branch.
![latest_traceback](https://cloud.githubusercontent.com/assets/11327998/26092658/cb1d4f16-3a2f-11e7-9386-bbc55f895d36.png)

**Comment by MeetSCS** [comment]
@Yenthe666 I have traced the code of x2m widget and found a workaround.

 Main issue is that when some constraint is fired from o2m inside o2m field and user will delete that o2m line, it is not correctly deleted from the dataset.

I took a deeper look into x2m widget structure and data.js files.

Original Code:- 
https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/views/form_relational_widgets.js#L675
 
I found workaround attached in below screenshot. Please share your valuable input in this workaround.

![screenshot from 2017-05-16 12 11 31](https://cloud.githubusercontent.com/assets/11327998/26093164/55ddb03a-3a32-11e7-9de9-70d92a813110.png)

**Comment by adrian-chang-alcover** [comment]
Hi @MeetSCS,
your solution worked for me.

This is how I solved based on your solution

```javascript
var AbstractManyField = require('web.form_relational').AbstractManyField;

AbstractManyField.include({
    get_value: function() {
        var command_list = this._super();
        var self = this;

        command_list = _.filter(command_list, function (cl) {
            var id = cl[1];
            return cl[0] !== 2 || !isNaN(id) || id.indexOf(self.dataset.virtual_id_prefix) === -1;
        });

        return command_list;
    }
})
```

**Comment by JeyChou** [comment]
Hi @MeetSCS,
your solution worked but there is another issue: the deletion action doesn't work when you delete the origin record and do above actions at the same time.

**Comment by ged-odoo** [comment]
@pedrobaeza 

I still have nightmares about the old view code and the words 'one2many', 'onchange', 'editable list view', ...  Whenever those words were uttered, I knew that I could very well 'lose' a week of work to fix an issue, and I knew that my fix would definitely break something else, which will for sure come back to haunt me. In short, that code was not really maintainable (and with no tests!)

That was actually the main motivation behind the work on the new views. We did a lot of work done on nested one2many  and many2many fields with the new views, and it mostly works. Now, I am pretty sure that this specific issue will not be fixed, because this would likely be a very risky fix and also, this requires a lot of time and/or expertise.

But that is up to the bug fix team.

**Comment by pedrobaeza** [comment]
Well, I think it's enough if you say that this is not happening anymore on v11. I'm facing myself this on #17618 and a workaround is on https://github.com/OCA/commission/pull/151, but it's not satisfactory at all. Can you confirm then that this is fixed?

**Comment by ged-odoo** [comment]
@pedrobaeza 
oh, this bug is fixed in v11. I just retested it to confirm.  I meant that this issue will probably not be fixed in v10/v11.

**Comment by pedrobaeza** [comment]
Do you mean 'fixed in v12'?

**Comment by ged-odoo** [comment]
wow, I really am bad with numbers.

I meant: 
- it is fixed in v11 (and should be fixed forever after that: v12, ...)
- it is not fixed in v9/v10

I just tried this exact issue on the runbot http://332366-11-0-4ea383.runbot14.odoo.com/web#view_type=kanban&model=survey.survey&menu_id=533&action=737

(survey name is 'aaaaaaa')

I also tried on v10, and it is not fixed.

**Comment by pedrobaeza** [comment]
Thanks for confirming, Géry. Then I think we can close this with the hope that going through newer versions we won't fave this issue, although it would be desirable to have it fixed everywhere, but as said, it's not possible without having the risk of breaking other things.

By my part, I will investigate the other referred issue in v11 and tell you back if it's also solved, Géry.
