### ISSUE TITLE
[V10] T-cal Odoo Server error

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#16722]
Impacted versions: V10

Steps to reproduce: 
1.Get the latest odoo from git
2. Create new invoice and try to print

Current behavior:
Odoo Server Error
Traceback (most recent call last):
 File "/opt/odoo/odoo-10.0/addons/report/controllers/main.py", line 96, in report_download
 response = self.report_routes(reportname, docids=docids, converter='pdf')
 File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
 response = f(*args, **kw)
 File "/opt/odoo/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
 pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
 File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 178, in get_pdf
 html = self.with_context(context).get_html(docids, report_name, data=data)
 File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 144, in get_html
 return self.render(report.report_name, docargs)
 File "/opt/odoo/odoo-10.0/addons/report/models/report.py", line 120, in render
 return view_obj.render_template(template, values)
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1036, in render_template
 return self.browse(self.get_view_id(template)).render(values, engine)
 File "/opt/odoo/odoo-10.0/addons/website/models/ir_ui_view.py", line 110, in render
 return super(View, self).render(values, engine=engine)
 File "/opt/odoo/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
 return super(IrUiView, self).render(values=values, engine=engine)
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1056, in render
 return self.env[engine].render(self.id, qcontext)
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
 return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
 self.compile(template, options)(self, body.append, values or {})
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
 raise e
QWebException: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
 File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
 return compiled(self, append, values, options, log)
 File "<template>", line 1, in template_website_report_layout_1331
 File "<template>", line 3, in body_call_content_1330
AttributeError: 'NoneType' object has no attribute 'id'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'id'
Template: website_report.layout
Path: /templates/t/t/t[4]
Node: <t t-set="x_icon" t-value="'/web/image/website/%s/favicon/' % website.id"/>

Expected behavior:
Should be able to print the invoice
Video/Screenshot link (optional):

**Comment by septiadevica** [comment]
hello, may I know the solution for this issue ? cause I got the same issue
thankyou
