### ISSUE TITLE
Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by marciorpbradoo** [odoo/odoo#16780]
Impacted versions: Odoo 10.0 Enterprise

Steps to reproduce: Install Odoo 10 and configure Nginx as proxy, set proxy_mode = True and Workers any number greater than 0.

Current behavior: (problem description)
Currently I have two different databases on different machines that are showing the error below. The first appearence was a couple of months ago, ocasionally showing up in logs, sometimes multiple times in a row and other times only once during a day.

It happens only when running Odoo with proxy_mode = True and/or number of workers > 0. When the proxy is disabled, the error stops.

```
Traceback (most recent call last):

  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch

    result = self._call_function(**self.params)

  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper

    return f(dbname, *args, **kwargs)

  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call

    result = self.endpoint(*a, **kw)

  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__

    return self.method(*args, **kw)

  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap

    response = f(*args, **kw)

  File "/odoo/odoo-server/addons/bus/controllers/main.py", line 35, in poll

    raise Exception("bus.Bus unavailable")

Exception: bus.Bus unavailable
```

**This is my current Nginx configuration:**

```
upstream odoo10 {

server myipaddres:8069 weight=1 fail_timeout=0;

}



upstream odoo10-im {

server myipaddres:8072 weight=1 fail_timeout=0;

}



## http redirects to https ##

server {

listen 80;

server_name mydomain.com;



# Strict Transport Security add_header Strict-Transport-Security max-age=2592000;

rewrite ^/.*$ https://$host$request_uri? permanent;



}



server {

# server port and name listen 443 ssl;

server_name mydomain.com;



# Specifies the maximum accepted body size of a client request,

# as indicated by the request header Content-Length.

client_max_body_size 200m;



# add ssl specific settings keepalive_timeout 60;

ssl on;

ssl_certificate /etc/ssl/nginx/mydomain.crt;

ssl_certificate_key /etc/ssl/nginx/mydomain.key;



# limit ciphers ssl_ciphers HIGH:!ADH:!MD5;

ssl_protocols SSLv3 TLSv1;

ssl_prefer_server_ciphers on;



# increase proxy buffer to handle some OpenERP web requests proxy_buffers 16 64k;

proxy_buffer_size 128k;



#general proxy settings

# force timeouts if the backend dies proxy_connect_timeout 600s;

proxy_send_timeout 600s;

proxy_read_timeout 600s;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;



# set headers proxy_set_header Host $host;

proxy_set_header X-Real-IP $remote_addr;

proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;



# Let the OpenERP web service know that we’re using HTTPS, otherwise

# it will generate URL using http:// and not https://

proxy_set_header X-Forwarded-Proto https;



# by default, do not forward anything proxy_redirect off;

proxy_buffering off;



location / {

proxy_pass http://odoo10;

}



location /longpolling {

proxy_pass http://odoo10-im;

}



# cache some static data in memory for 60mins.

# under heavy load this should relieve stress on the OpenERP web interface a bit.

location /web/static/ {

proxy_cache_valid 200 60m;

proxy_buffering on;

expires 864000;

proxy_pass http://odoo10;

}

}

```

And the relevant part from etc/odoo-conf relating to performance:

```
[options] 

...

db_maxconn = 64  

limit_memory_hard = 2684354560 

limit_memory_soft = 2147483648 

limit_request = 8192 

limit_time_cpu = 600 
limit_time_real = 1200 
limit_time_real_cron = 2400 
max_cron_threads = 2 

osv_memory_age_limit = 1.0 

osv_memory_count_limit = False 

proxy_mode = True 

workers = 5 xmlrpc = True 

xmlrpc_interface = myipaddress 

netrpc_interface = myipaddress

...
```

This is currently running on Digital Ocean infra-structure, on a machine with 2GB of RAM and 2 CPU Cores.

 Expected behavior: The error is not supposed to be shown.

Video/Screenshot link (optional):

**Comment by DiogoBerti** [comment]
Same Problem here....

**Comment by mart-e** [comment]
Hello,

It should be working. Your configuration looks mostly good based on the [deployment page](https://www.odoo.com/documentation/10.0/setup/deploy.html#livechat) advises.
Try changing your configuration with:

> location / {
> proxy_pass http://odoo10;
> }
```
location / {
  proxy_redirect off;
   proxy_pass http://odoo10;
}
```

> proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;

`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

> workers = 5 xmlrpc = True 

I guess a typo and should be on two lines.

Could you check if there is any redirection/iptables on port 8072 that may introduce the error?

**Comment by shivam-kotwalia** [comment]
Does anyone of us, solution to this ?

**Comment by celm1990** [comment]
Hello,
When I use worker =0 and users using 8069 fine work, but when use worker >0 and use 8069 raise exception bus unavailable when Evented is installed, if connecting using port 8072 instead 8069 work fine. Is correct use 8072 port when workers >0 and Evented is installed???

**Comment by mart-e** [comment]
Please don't hijack other people issues. I have given what to correct to the original NGINX configuration. Check that your configuration based on the documentation and given advises.
