### ISSUE TITLE
printing: werkzeug: Error on request

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#16800]
Impacted versions:
10.0
Current behavior: 
```
2017-05-04 10:48:01,445 8499 INFO demo werkzeug: 196.70.248.45 - - [04/May/2017 10:48:01] "GET /report/pdf/purchase.report_purchasequotation/1 HTTP/1.1" 500 -
2017-05-04 10:48:01,454 8499 ERROR demo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1478, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/opt/odoo/odoo/odoo/addons/report/models/report.py", line 265, in get_pdf
    context.get('set_viewport_size'),
  File "/opt/odoo/odoo/odoo/addons/report/models/report.py", line 453, in _run_wkhtmltopdf
    raise UserError(message  % (str(process.returncode), err[-1000:]))
UserError: (u"Wkhtmltopdf a \xe9chou\xe9 (code d'erreur : -6). Message : The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/
runtime-user'\nQXcbConnection: Could not connect to display \n", None)
```

**Comment by Mungunshaga** [comment]
how to fix it?

**Comment by pedrobaeza** [comment]
This is because you are using a non Qt-patched version of wkhtmltopdf. Please use that one.

Closing as no real issue.
