### ISSUE TITLE
Problem starting OpenERP

### ISSUE THREAD

**Issue by AdrianJoel** [odoo/odoo#16816]
Hi.

I have a problem when I want to start my OpenERP. The following message appears:

OpenERP Server Error
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/http.py", line 470, in dispatch
    result = self._call_function(**self.params)
  File "/opt/openerp/server/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openerp/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/openerp/server/openerp/http.py", line 638, in __call__
    return self.method(*args, **kw)
  File "/opt/openerp/server/openerp/http.py", line 337, in response_wrap
    response = f(*args, **kw)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1242, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1234, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/openerp/server/openerp/addons/account/account_invoice.py", line 363, in fields_view_get
    res = super(account_invoice,self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=submenu)
  File "/opt/openerp/server/openerp/addons/mail/mail_thread.py", line 335, in fields_view_get
    res = super(mail_thread, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=submenu)
  File "/opt/openerp/server/openerp/osv/orm.py", line 1886, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/openerp/server/openerp/addons/base/ir/ir_ui_view.py", line 714, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/opt/openerp/server/openerp/addons/base/ir/ir_ui_view.py", line 291, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `valor_porcentaje` does not exist

Error context:
View `account.invoice.tree`
[view_id: 434, xml_id: account.invoice_tree, model: account.invoice, parent_id: n/a]

Also, I wanted to integrate OpenERP with Asterisk so I installed modules in the "addons" folder. After that, when I click on "Open Caller" this message appears:

OpenERP Server Error
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/http.py", line 470, in dispatch
    result = self._call_function(**self.params)
  File "/opt/openerp/server/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openerp/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/openerp/server/openerp/http.py", line 638, in __call__
    return self.method(*args, **kw)
  File "/opt/openerp/server/openerp/http.py", line 337, in response_wrap
    response = f(*args, **kw)
TypeError: get_record_from_my_channel() takes exactly 2 arguments (1 given)

Please help me :(

**Comment by Yenthe666** [comment]
Hi @AdrianJoel,

Can you please update your local Odoo to the latest version and try again?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
As this issue is identical to the other one I'm closing this issue. Please keep one issue per problem.

Regards,
Yenthe
