### ISSUE TITLE
AttributeError: 'function' object has no attribute 'cache'

### ISSUE THREAD

**Issue by qnqatop** [odoo/odoo#168149]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

'function' object has no attribute 'cache'
I dont't understant when i upgrade my custom app send error
AttributeError: 'function' object has no attribute 'cache'

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 27, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 19, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-83>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 650, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 583, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 205, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 576, in init_models
    env['ir.model']._reflect_models(model_names)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 429, in _reflect_models
    self.env['ir.model.data']._update_xmlids(data_list)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 2275, in _update_xmlids
    self._xmlid_lookup.cache.add_value(self, f"{module}.{name}", cache_value=(model, res_id))
AttributeError: 'function' object has no attribute 'cache'

The above server error caused the following client error:
RPC_ERROR://localhost:11017/web/assets/fc1bff6/web.assets_web.min.js:2873:163)
    at XMLHttpRequest.<anonymous> (http://localhost:11017/web/assets/fc1bff6/web.assets_web.min.js:2877:13)
```

**Comment by manlive** [comment]
any update on this ?

**Comment by qnqatop** [comment]
There was some kind of multi-layer cache and there were jambs with it
fortunately now I am no longer working with this project

> any update on this ?

**Comment by vava-odoo** [comment]
Thanks for the report. Fixed with https://github.com/odoo/odoo/commit/331d8451d9011aff6a8290c473a52fa77b30b358

**Comment by yeam-10** [comment]
Hello, how did you solve it?
