### ISSUE TITLE
Problem starting OpenERP

### ISSUE THREAD

**Issue by FreduxR** [odoo/odoo#16820]
I have a problem when I want to start my odoo.

![image](https://cloud.githubusercontent.com/assets/22806823/25734342/eee46e30-311e-11e7-91bb-8133775c1d06.png)

/opt/odoo/server/odoo-bin 
Traceback (most recent call last):
  File "/opt/odoo/server/odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1906, in declare_namespace
    declare_namespace(parent)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1922, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1889, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/opt/odoo/server/odoo/__init__.py", line 60, in <module>
    import modules
  File "/opt/odoo/server/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/opt/odoo/server/odoo/modules/graph.py", line 13, in <module>
    import odoo.osv as osv
  File "/opt/odoo/server/odoo/osv/__init__.py", line 4, in <module>
    import osv
  File "/opt/odoo/server/odoo/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/opt/odoo/server/odoo/exceptions.py", line 15, in <module>
    from tools.func import frame_codeinfo
  File "/opt/odoo/server/odoo/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/opt/odoo/server/odoo/tools/misc.py", line 22, in <module>
    import werkzeug.utils
ImportError: No module named werkzeug.utils

help me pleas :'(

**Comment by Yenthe666** [comment]
Hi @FreduxR,

Please only create one issue per problem.
You've already created one here https://github.com/odoo/odoo/issues/16816
Closing as it is a duplicate.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @FreduxR,

Have you installed the requirements? It looks like you're missing the dependency Werkzeug.
See https://github.com/odoo/odoo/blob/10.0/requirements.txt#L38
Can you install it, restart your Odoo and try again?

Regards,
Yenthe

**Comment by FreduxR** [comment]
Thanks

**Comment by Yenthe666** [comment]
Hi @FreduxR,

No problem. Is your problem solved now?

**Comment by FreduxR** [comment]
ammmm yeah 

i have this problem when initialised odoo

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by FreduxR** [comment]
@Yenthe666  Here is the log

2017-05-05 06:55:37,485 16951 INFO ? odoo: Odoo version 10.0
2017-05-05 06:55:37,485 16951 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2017-05-05 06:55:37,485 16951 INFO ? odoo: addons paths: ['/opt/odoo/.local/share/Odoo/addons/10.0', u'/opt/odoo/server/addons', '/opt/odoo/server/odoo/addons']
2017-05-05 06:55:37,486 16951 INFO ? odoo: database: odoo@default:default
2017-05-05 06:55:37,495 16951 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-05-05 06:55:38,439 12156 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2017-05-05 06:55:38,439 12156 INFO ? odoo.sql_db: Connection to the database failed
2017-05-05 06:55:38,439 12156 ERROR ? odoo.addons.bus.models.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/server/addons/bus/models/bus.py", line 170, in run
    self.loop()
  File "/opt/odoo/server/addons/bus/models/bus.py", line 148, in loop
    with odoo.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/server/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/server/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/server/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/server/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: No existe el archivo o el directorio
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by Yenthe666** [comment]
Hi @FreduxR,

This is another issue. Your Odoo is looking for your postgreSQL server on port 5432 but it is not installed on that port or not running on it.
See https://www.odoo.com/documentation/10.0/setup/install.html

Regards,
Yenthe

**Comment by FreduxR** [comment]
it works, thanks

but     not have style

![image](https://cloud.githubusercontent.com/assets/22806823/25737346/75236db0-3134-11e7-9506-851e5137afce.png)

**Comment by Yenthe666** [comment]
Hi @FreduxR,

Please update your whole Odoo database with the parameter `./odoo.py -u all` so that all less files get regenerated and updated.

Regards,
Yenthe

**Comment by FreduxR** [comment]
@Yenthe666 , Thanks

now i have a new problem

![image](https://cloud.githubusercontent.com/assets/22806823/25737984/df9dd63c-3137-11e7-952a-f80c5918de2b.png)



here is log


2017-05-05 08:03:36,953 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:36] "GET /web HTTP/1.1" 200 -
2017-05-05 08:03:40,109 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:40] "GET /web/webclient/qweb?mods=base_import HTTP/1.1" 304 -
2017-05-05 08:03:40,464 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:40] "GET /web_editor/static/src/xml/ace.xml HTTP/1.1" 404 -
2017-05-05 08:03:40,524 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:40] "POST /web/dataset/call HTTP/1.1" 200 -
2017-05-05 08:03:41,396 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:41] "GET /web_editor/static/src/xml/editor.xml HTTP/1.1" 404 -
2017-05-05 08:03:41,437 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:41] "POST /web/webclient/translations HTTP/1.1" 200 -
2017-05-05 08:03:41,555 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:41] "GET /web_editor/static/src/xml/snippets.xml HTTP/1.1" 404 -
2017-05-05 08:03:41,594 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:41] "POST /web/webclient/translations HTTP/1.1" 200 -
2017-05-05 08:03:41,822 1517 INFO test werkzeug: 127.0.0.1 - - [05/May/2017 08:03:41] "GET /web/webclient/locale/es_GT HTTP/1.1" 500 -
2017-05-05 08:03:42,061 1517 ERROR test werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/server/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/opt/odoo/server/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/server/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/server/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/server/odoo/http.py", line 1478, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/server/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/server/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 493, in load_locale
    addons_path = http.addons_manifest['web']['addons_path']
KeyError: 'web'
2017-05-05 08:03:43,639 5438 INFO ? odoo: Odoo version 10.0
2017-05-05 08:03:43,639 5438 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2017-05-05 08:03:43,639 5438 INFO ? odoo: addons paths: ['/opt/odoo/.local/share/Odoo/addons/10.0', u'/opt/odoo/server/addons', '/opt/odoo/server/odoo/addons']
2017-05-05 08:03:43,639 5438 INFO ? odoo: database: odoo@default:5433
2017-05-05 08:03:43,743 5438 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069

**Comment by FreduxR** [comment]
@Yenthe666  resolved , thanks

**Comment by Yenthe666** [comment]
Awesome. Best of luck with Odoo!

**Comment by carrotagileit** [comment]
@FreduxR I have the same problem. How did you resolve the problem? Thanks.

**Comment by xombix** [comment]
@FreduxR i have sampe problem, anybody have to fix it? thanks

**Comment by jl2035** [comment]
Why not describe how you've fixed the problem, @FreduxR ???

**Comment by jl2035** [comment]
`KeyError:` 'web' 

What's the meaning of that!?
