### ISSUE TITLE
[11.0] module: Expenses / Field `uom_id` does not exist

### ISSUE THREAD

**Issue by tkontogi** [odoo/odoo#168591]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [ ] 17.0
- [X] Other (specify)

### Steps to Reproduce

- Create UK DB with demo data
- Go to APPS add expenses module
-  Go back to expenses
- Select an expense
- Click on the Product

### Log Output

```shell
2024-06-09 14:29:40,801 1 INFO 20240207 werkzeug: 10.0.2.2 - - [09/Jun/2024 14:29:40] "POST /web/dataset/call_kw/product.product/get_formview_action HTTP/1.0" 200 -
2024-06-09 14:29:41,058 1 INFO 20240207 werkzeug: 10.0.2.2 - - [09/Jun/2024 14:29:41] "POST /web/dataset/call_kw/product.product/load_views HTTP/1.0" 200 -
2024-06-09 14:29:41,320 1 INFO 20240207 odoo.addons.base.ir.ir_ui_view: Field `uom_id` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
2024-06-09 14:29:41,321 1 ERROR 20240207 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 697, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 682, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1316, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1316, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1402, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1083, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 533, in raise_view_error
    raise ValueError(message)
ValueError: Field `uom_id` does not exist
```

**Comment by tkontogi** [comment]
Not duplicate of https://github.com/odoo/odoo/issues/21823 as there are no extra modules installed apart from the ones "Expenses" app installed.
