### ISSUE TITLE
TypeError: _prepare_refund() got an unexpected keyword argument 'date_invoice'

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#16908]
Impacted versions: 9.0

Steps to reproduce: Create a draft refund

Current behavior: TypeError: _prepare_refund() got an unexpected keyword argument 'date_invoice' 

Expected behavior: Create refund

Video/Screenshot link (optional):

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/wizard/account_invoice_refund.py", line 128, in invoice_refund
    return self.compute_refund(data_refund)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/wizard/account_invoice_refund.py", line 60, in compute_refund
    refund = inv.refund(form.date_invoice, date, description, inv.journal_id.id)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_invoice.py", line 1002, in refund
    description=description, journal_id=journal_id)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: _prepare_refund() got an unexpected keyword argument 'date_invoice'
```

**Comment by Yenthe666** [comment]
Hi @jayo2005,

Thank you for the report.
I've just tested this on the latest 9.0 and this issue is no longer present in Odoo. 
Please update your Odoo and try again.

Regards,
Yenthe
