### ISSUE TITLE
[17.0] module: ir_rule, Contact domain error [('user_id','=',user.id)]

### ISSUE THREAD

**Issue by Hankxi** [odoo/odoo#169017]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Access Error when setting Record Rules for the user group "Internal User" with the domain [('user_id','=',user.id)]

Description:
When setting Record Rules for the user group "Internal User" with the domain [('user_id','=',user.id)], an error occurs when trying to view a user not created by the logged-in user. The error message is as follows:

sql
Access Error
Uh-oh! Looks like you have stumbled upon some top-secret records.
Sorry, User (id=7) doesn't have 'read' access to:

Cause:
This error occurs because the system requires access to the create_uid field of the user record being viewed. Without permission to access the create_uid user record, the error is triggered.

Temporary Solution:
Using the domain ['|', ('user_id', '=', user.id), ('create_uid', '!=', user.id)] prevents the error but does not filter the desired records.

Example Scenario:

If the current Record Rules are set to ['|', ('user_id', '=', user.id), ('create_uid', '!=', user.id)], it prevents access errors but does not filter the records correctly. When a user tries to access a record created by another user, they must have access to the create_uid user's record to avoid errors. The proposed solution ensures correct access without compromising data integrity.

**Comment by shanei-bn** [comment]
Hi, do you have any idea on what happened here? I got this error last night, and can't find the solution since

Traceback (most recent call last):
  File "/home/admin/odoo/16/odoo/api.py", line 989, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 30

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/odoo/16/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/home/admin/odoo/16/odoo/api.py", line 996, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'sale.order.line(30,).qty_claimed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/odoo/16/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/admin/odoo/16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/admin/odoo/16/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/admin/odoo/16/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/admin/odoo/16/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/admin/odoo/16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/admin/odoo/16/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/admin/odoo/16/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/admin/odoo/16/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/admin/odoo/16/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/admin/odoo/16/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/admin/sunthi_addons/ss_sale/models/sale_rph.py", line 47, in action_done
    qty = self.sale_line_id.qty_claimed + self.qty_order
  File "/home/admin/odoo/16/odoo/fields.py", line 1186, in __get__
    recs._fetch_field(self)
  File "/home/admin/odoo/16/odoo/models.py", line 3190, in _fetch_field
    self._read(fnames)
  File "/home/admin/odoo/16/odoo/models.py", line 3247, in _read
    self._apply_ir_rules(query, 'read')
  File "/home/admin/odoo/16/odoo/models.py", line 4464, in _apply_ir_rules
    expression.expression(domain, self.sudo(), self._table, query)
  File "/home/admin/odoo/16/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/home/admin/odoo/16/odoo/osv/expression.py", line 674, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
ValueError: Invalid field sale.order.line.team_id in leaf ('team_id.member_ids', '=', 202)
