### ISSUE TITLE
[17.0] sale: TypeError on product type change from service to consumable after a sale

### ISSUE THREAD

**Issue by hnavarro-kernet** [odoo/odoo#169908]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I was testing Project creation on Sale confirmed, so I created a product with some basic defaults
- **Product Type**: Service
- **Invoicing Policy**: Prepaid/Fixed Price
- **Create on Order**: Project & Task
- **Project Template**: Project Template _(created by me)_

I made a sale of this product, confirmed... checked the project and I realized a task was created for 1h planned time.
Since I didn't want this I went to the product and changed some settings:

1. **Unit of Measure**: Units
2. **Purchase UoM**: Units
3. **Product Type**: Consumable

Then the error occurs.

I believe [this is the line](https://github.com/odoo/odoo/blob/3afef8250c829406a8fd227a6bd9f71c4f80ff29/addons/sale/models/product_product.py#L46) that creates the error, but I didn't do further testing.

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 1827, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/service/model.py", line 134, in retrying
    result = func()
             ^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 1805, in _serve_ir_http
    return self._serve_ir_http(rule, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 1812, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 2037, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/addons/base/models/ir_http.py", line 220, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/http.py", line 740, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/addons/web/controllers/dataset.py", line 38, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/addons/web/controllers/dataset.py", line 34, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/odoo/api.py", line 458, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/addons/web/models/models.py", line 1004, in onchange
    record._apply_onchange_methods(field_name, result)
  File "/home/odoo/src/odoo/saas-17.2/odoo/models.py", line 6909, in _apply_onchange_methods
    res = method(self)
          ^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/addons/sale_project/models/product.py", line 170, in _onchange_type
    res = super(ProductTemplate, self)._onchange_type()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.2/addons/sale/models/product_template.py", line 97, in _onchange_type
    res['warning'] = {
    ~~~^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

The above server error caused the following client error:
RPC_ERROR://demo6.odoo.com/web/assets/8610a80/web.assets_web.min.js:2947:163)
    at XMLHttpRequest.<anonymous> (https://demo6.odoo.com/web/assets/8610a80/web.assets_web.min.js:2952:13)
```

**Comment by hnavarro-kernet** [comment]
Weirdly I cannot reproduce the bug, but I have some comments about its behavior:

1. I get the `Warning` message now, but I can still click again on the save button and change the type of the product.

2.
```python
@api.onchange('type')
def _onchange_type(self):
    if self._origin and self.sales_count > 0:
        return {'warning': {
            'title': _("Warning"),
            'message': _("You cannot change the product's type because it is already used in sales orders.")
        }}
```
- Why would this depend on `self._origin`? Either the product is used or not, nonetheless its origin.
- Obviously, missing the `return super()._onchange_type()`
- This should be a constraint instead and the computation should be coupled closely instead of relying on a computed field. In fact I'd use a SQL query directly to optimize for time/performance.

3.
```python
def _compute_sales_count(self):
    r = {}
    self.sales_count = 0
    if not self.user_has_groups('sales_team.group_sale_salesman'):
        return r
    date_from = fields.Datetime.to_string(fields.datetime.combine(fields.datetime.now() - timedelta(days=365),
                                                                  time.min))

    done_states = self.env['sale.report']._get_done_states()

    domain = [
        ('state', 'in', done_states),
        ('product_id', 'in', self.ids),
        ('date', '>=', date_from),
    ]
    for product, product_uom_qty in self.env['sale.report']._read_group(domain, ['product_id'], ['product_uom_qty:sum']):
        r[product.id] = product_uom_qty
    for product in self:
        if not product.id:
            product.sales_count = 0.0
            continue
        product.sales_count = float_round(r.get(product.id, 0), precision_rounding=product.uom_id.rounding)
    return r
```
- Why is sales_count being set at 0? That might not be true.
- Why do I have to have sales access to compute the products sales count? The questions seems obvious, but when `sales_count` is being used for other fields like product type which depend on sales, its no more of use. Hence why again IMHO the `_onchange_type` should be a constraint and the computation should be as close as possible to the constraint method.
- Why does the sales count depend on a date? You either sold products or not. No estimates should be given here.

**Comment by nouraellm** [comment]
@hnavarro-kernet I suppose you recently migrated to 17.0?

**Comment by MohdAlmosawy** [comment]
Hello @hnavarro-kernet,

I appreciate the detailed discussion and have some thoughts:

### **Reflections on Current Implementations:**

**- Dependency on self._origin and Initial Sales Count:** These might be seen as issues, but they can also reflect intentional design choices based on specific business logic or performance considerations. 

_For example, using self._origin ensures that changes are compared against the original record state, which is crucial in scenarios where previous data states affect current processing rules, such as adjusting financial records only if they haven't been previously audited._

**- Sales Count and Access Control:** This design may be intended to maintain data security in a multi-user environment.
**though it’s worth considering if this restrictiveness impacts usability for other tasks that depend on sales count.**

**- Direct SQL Queries for Optimization:** While direct SQL can be tempting for performance optimization, adhering to Odoo’s ORM is recommended to maintain security, consistency, and integration across modules. The ORM helps ensure that data access respects security rules and relations are correctly managed. 
**Specific scenarios where ORM struggles with large datasets might warrant further discussion.**

### **Areas for Improvement:**

**- Use of Constraints vs. Computed Fields:** Shifting to database constraints for critical validations like changes to product types post-sale is a valid point. This method is more robust as it enforces rules at the database level, ensuring system integrity across all operational paths, not just via the UI.

The issue you raised itself illustrates how relying on onchange can lead to errors when the warning message can be bypassed by re-clicking save. **But I was not able to reproduce the issue as described.** However, I noticed that @nouraellm added the Confirmed label. I’m curious if they were able to reproduce the issue?

Here is how I think this should be implemented:

```
    @api.constrains('type')
    def _check_type_change(self):
        if self._origin and self.sales_count > 0:
            raise ValidationError(_("You cannot change the product's type because it is already used in sales orders."))
```

**- Missing super()._onchange_type():** This indeed needs correction. Failing to call super() in overridden methods can lead to bugs and unexpected behaviors as essential logic in the base class is skipped. In Odoo, where functionality is often extended via inheritance, maintaining the integrity of method chains is crucial.

Here is how I think it should be done:

```
    @api.onchange('type')
    def _onchange_type(self):
        res = super(ProductTemplate, self)._onchange_type()
        if self._origin and self.sales_count > 0:
            res['warning'] = {
                'title': _("Warning"),
                'message': _("You cannot change the product's type because it is already used in sales orders.")
            }
        return res
```

I would appreciate your opinion on my points. If @nouraellm confirmed the problem, I can do a pull request to modify this.

Looking forward to your feedback!

**Comment by hnavarro-kernet** [comment]
> - Dependency on self._origin and Initial Sales Count: These might be seen as issues, but they can also reflect intentional design choices based on specific business logic or performance considerations.
> 
> _For example, using self.origin ensures that changes are compared against the original record state, which is crucial in scenarios where previous data states affect current processing rules, such as adjusting financial records only if they haven't been previously audited.

If `_origin` is set when a change occurs, in this case when `type` changes, that seems ok and I might not have understood that initially.

> - Sales Count and Access Control: This design may be intended to maintain data security in a multi-user environment.
though it’s worth considering if this restrictiveness impacts usability for other tasks that depend on sales count.

The security check makes sense. Someone from another department might not need to know how many of this product were sold, ok.

~~But I do think it could impact the integrity of other tasks indeed, specially in these multi-user environments you mentioned if a user with no sale access were to change the product type to a service for example, I fear the stock module and their users would suffer its consequences. Like... "Hey I have this shipment that I've just done... I want to update my inventory but suddenly I can't create the `stock.quant` [because the product type is not a product.](https://github.com/odoo/odoo/blob/be261aab2659305033d24ef1b3e631cd43f250b7/addons/stock/models/stock_quant.py#L588)"~~

Looks like [this is handled on the stock module](https://github.com/odoo/odoo/blob/be261aab2659305033d24ef1b3e631cd43f250b7/addons/stock/models/product.py#L839) like it should be... But its also a warning instead of an exception.

> - Direct SQL Queries for Optimization: While direct SQL can be tempting for performance optimization, adhering to Odoo’s ORM is recommended to maintain security, consistency, and integration across modules. The ORM helps ensure that data access respects security rules and relations are correctly managed.
Specific scenarios where ORM struggles with large datasets might warrant further discussion.

Fair, but I'd still bypass the user check, not for the `sales_count`, but for the `type` field change. [Just like the `stock` module does](https://github.com/odoo/odoo/blob/be261aab2659305033d24ef1b3e631cd43f250b7/addons/stock/models/product.py#L839) using `sudo()` and `search_count`, giving us an internal count that does restrict the type change while maintaining the security between departments.

> The issue you raised itself illustrates how relying on onchange can lead to errors when the warning message can be bypassed by re-clicking save. But I was not able to reproduce the issue as described. However, I noticed that @nouraellm added the Confirmed label. I’m curious if they were able to reproduce the issue?

I'm honestly not sure how I did get that error other than the steps I mentioned, the stack trace its obvious and the missing `super` call is problematic, but the `product.product` call shouldn't be affecting the `product.template` error on the trace, which seems to be the case since we're unable to reproduce.

The MRE for the onchange problem seems to be consistent:
1. Go to demo.odoo.com
2. Create a new Sale
3. Create a new product with the default values the "Add a new line" provides.
4. Confirm the Sale
5. Click on the product and change the product type
- If changed to combo, a warning will appear, accept it, then save again.
- If changed to service, a warning will appear, accept it, save again and now a blocker will appear. Accept it, change the "Sales price" unit to the original "Units" unit, save again.

In my opinion:
- `super` should be called regardless of this issue report
- The compute should be done with the `sudo` and `search_count` method instead like the `stock` module does.
- Whether the function should be a check or an onchange, should be discussed further since the code is fulfilling the intended behavior of **warning** the user but not **blocking**. Functionally, the user decided to make this change, but the repercussions on other modules are unknown and I think like the stock warning advises, archiving the product and creating a new one is a better solution.

**Comment by nouraellm** [comment]
@hnavarro-kernet @MohdAlmosawy I appreciate your inputs and agree with your observations. However, I am no longer able to reproduce the issue on the demo environment. If you continue to experience this problem, could you please provide additional details about the steps to reproduce it? Once confirmed, PRs are welcome for review!
