### ISSUE TITLE
[10.0 - website_sale] product variants are not usable in shop (with currency with rounding factor=1)

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#17046]
Impacted versions:
10.0c tested on runbot today

Steps to reproduce:
Setup a company that uses a currency with rounding factor=1 (ie. XPF, )
Setup a product with 2 variant and fix a price different for the second variant
In the shop, clic on the product and select the second variant

Current behavior:
The Product variant price do not update
javascript console gives :
```
web.assets_common.js:96 Uncaught Error: [_.sprintf] huh?
    at Function.str_format.parse (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:96:12)
    at Object.str_format [as sprintf] (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:78:145)
    at price_to_str (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1871-78ebdba/web.assets_frontend.js:185:21)
    at Object.<anonymous> (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1871-78ebdba/web.assets_frontend.js:189:1433)
    at Object.<anonymous> (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:547:681)
    at fire (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:548:56)
    at fire (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://229242-10-0-ae1aec.runbot11.odoo.com/web/content/1869-5020c4d/web.assets_common.js:546:198)
```
Expected behavior:
The product variant price is shown and the image switches

Video/Screenshot link (optional):

**Comment by invitu** [comment]
PR : https://github.com/odoo/odoo/pull/17050
