### ISSUE TITLE
[16.0] account: creation of statement line on statement that contains existing lines

### ISSUE THREAD

**Issue by mourad-ehm** [odoo/odoo#171077]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to bank statement
- Select a bank statement with existing lines.
- Click on "Add a line"
![image](https://github.com/odoo/odoo/assets/15939329/6cd7c190-0b49-4b6d-b3a2-491a233ae247)
the bug is caused by this line https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_bank_statement.py#L117.
Because we can not sort value of type bool an str. For the new created line internal_index = False and it is considered as a bool type.

### Log Output

```shell
Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/src/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/odoo/src/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/src/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/links/extendable/models/ir_http.py", line 20, in _dispatch
    return super()._dispatch(endpoint)
  File "/odoo/src/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/src/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/src/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/src/odoo/models.py", line 6585, in onchange
    todo = [
  File "/odoo/src/odoo/models.py", line 6588, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/odoo/src/odoo/models.py", line 6371, in has_changed
    return self[name] != record[name]
  File "/odoo/src/odoo/models.py", line 5920, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/odoo/src/odoo/fields.py", line 1158, in __get__
    self.recompute(record)
  File "/odoo/src/odoo/fields.py", line 1370, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/odoo/src/odoo/fields.py", line 1343, in apply_except_missing
    func(records)
  File "/odoo/src/odoo/fields.py", line 1392, in compute_value
    records._compute_field_value(self)
  File "/odoo/src/odoo/models.py", line 4232, in _compute_field_value
    fields.determine(field.compute, self)
  File "/odoo/src/odoo/fields.py", line 98, in determine
    return needle(*args)
  File "/odoo/src/addons/account/models/account_bank_statement.py", line 117, in _compute_date_index
    sorted_lines = stmt.line_ids.sorted('internal_index')
  File "/odoo/src/odoo/models.py", line 5583, in sorted
    ids = tuple(item.id for item in sorted(self, key=key, reverse=reverse))
TypeError: '<' not supported between instances of 'str' and 'bool'

The above server error caused the following client error:
null
```

**Comment by SSanfilippo** [comment]
I get an error, in Odoo 16 Community, in bank statement, similar to previous post but the log message is:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16\server\odoo\api.py", line 997, in get
    cache_value = field_cache[record._ids[0]]
KeyError: <NewId origin=973>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16\server\odoo\fields.py", line 1161, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files\Odoo 16\server\odoo\api.py", line 1004, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.bank.statement.line(<NewId origin=973>,).running_balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16\server\odoo\http.py", line 1638, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 16\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Program Files\Odoo 16\server\odoo\http.py", line 1665, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Files\Odoo 16\server\odoo\http.py", line 1869, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Files\Odoo 16\server\odoo\addons\website\models\ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\Program Files\Odoo 16\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\Program Files\Odoo 16\server\odoo\http.py", line 700, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Program Files\Odoo 16\server\odoo\addons\web\controllers\dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 16\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 16\server\odoo\api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 16\server\odoo\api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 6548, in onchange
    snapshot0.fetch(name)
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 6360, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 6360, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 6352, in __init__
    self.fetch(name)
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 6362, in fetch
    self[name] = record[name]
  File "C:\Program Files\Odoo 16\server\odoo\models.py", line 5920, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "C:\Program Files\Odoo 16\server\odoo\fields.py", line 1219, in __get__
    raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign account.bank.statement.line(<NewId origin=973>, <NewId origin=972>, <NewId origin=971>, <NewId origin=970>, <NewId origin=969>, <NewId origin=968>).running_balance

The above server error caused the following client error:
null

Can anyone help me?
Thanks,
Simone
