### ISSUE TITLE
[10.0] ParseError when installing eCommerce app after having imported Pricelists in Sales

### ISSUE THREAD

**Issue by Kazebayashi** [odoo/odoo#17195]
Impacted versions: 10.0

Steps to reproduce:

- Import Pricelists in sales

- Install eCommerce app

Current behavior: `ParseError: "null value in column "name" violates not-null constraint`

Expected behavior: Installing eCommerce app

Video/Screenshot link (optional):
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website_sale/models/product.py", line 34, in create
    res = super(ProductPricelist, self).create(data)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3901, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (9, 1, null, 16, null, 1, 1, 2017-05-24 17:41:18.464016, t, 2017-05-24 17:41:18.464016, with_discount, null, 1, f).
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/website_sale/data/data.xml:38, near
<record model="product.pricelist" id="product.list0">
            <field name="selectable" eval="False"/>
            <field name="website_id" ref="website.default_website"/>
        </record>
```

I tried to delete the whole pricelists in Sales and then install again eCommerce, but there is still the ParseError.

Any idea how this can be fixed?
Thanks

**Comment by JKE-be** [comment]
You need to update the sale module.

The error is because you deleted a base price list, that e-commerce tries to update to add the new default value.

**Comment by Kazebayashi** [comment]
Thank you!
Since then I worked on a fresh install of 10.0, installing eCommerce from the beginining and I had no problem, but it's good to know this was the cause of the issue.

**Comment by danztensai** [comment]
i know its very late but i face the same problem, how to restore base price list? i've tried to input the data directly still no luck i cant install e-commerce module

**Comment by JKE-be** [comment]
@danztensai

The simple way is to make an « update » from sale module before to install website_sale module.

**Comment by danztensai** [comment]
so i have to remove website_sale module 1st? already try it, still no luck when i upgrade the sales module

    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (40, 1, null, 16, null, 1, 6, 2019-04-20 02:06:36.705967, t, 2019-04-20 02:06:36.705967, with_discount, null, 1, f).
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/website_sale/data/data.xml:38, near
<record model="product.pricelist" id="product.list0">
            <field name="selectable" eval="False"/>
            <field name="website_id" ref="website.default_website"/>
        </record>


is there any other way around like directly adding to database or something else?

**Comment by JKE-be** [comment]
Yes

You can create the record yourself

And manual add the ir.model.data 

Ask more information on the forum: forum.odoo.com

Good luck 

Jeremy Kersten
