### ISSUE TITLE
[master] Error when try reset to draft a customer invoice

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#17207]
Impacted versions:
master

Steps to reproduce:
1.- Configure the customer journal to allow cancel entries
2.- Create a new customer invoice with the journal configured in step 1
3.- Validate the invoice created on step 2
4.- Cancel the invoice
5.- Try reset to draft

Current behavior:
The next traceback
```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/service/model.py", line 120, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/addons/web/controllers/main.py", line 914, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/addons/web/controllers/main.py", line 902, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/addons/account/models/account_invoice.py", line 574, in action_invoice_draft
    attachment = self.env['ir.actions.report'].retrieve_attachment(invoice.id)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/addons/base/ir/ir_actions_report.py", line 191, in retrieve_attachment
    attachment_name = safe_eval(self.attachment, {'object': record_id, 'time': time})
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/tools/safe_eval.py", line 300, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/tools/safe_eval.py", line 165, in test_expr
    pycompat.reraise(ValueError, ValueError('"%s" while compiling\n%r' % (ustr(e), expr)), exc_info[2])
  File "/home/odoo/runbot/extra/runbot/static/build/231105-master-7d9981/odoo/tools/safe_eval.py", line 159, in test_expr
    expr = expr.strip()
ValueError: "'bool' object has no attribute 'strip'" while compiling
False
```

Expected behavior:
The invoice is reset to draft

Video/Screenshot link (optional):
https://youtu.be/P0KkUCU4vH4

**Comment by qdp-odoo** [comment]
@smetl looks like something for you

**Comment by smetl** [comment]
@qdp-odoo @luistorresm Fixed by https://github.com/odoo/odoo/pull/17262
