### ISSUE TITLE
[17.0] website_blog: description date_begin error logged from website_blog.posts_loop template

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#172426]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- After upgrade from 16.0 to 17.0 using website.blog
- View the log file
- Note the repeating message for all blog posts that continues regularly in the log file, substituting the format of date / time for each post.
ValueError: time data '2023-06-01+00:00:00' does not match format '%Y-%m-%d %H:%M:%S'

### Log Output

```shell
Traceback (most recent call last):
  File "/opt/odoo17/odoo/odoo/http.py", line 2189, in __call__
    response = request._serve_db()
  File "/opt/odoo17/odoo/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo17/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo17/odoo/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo17/odoo/odoo/http.py", line 1908, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo17/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo17/odoo/odoo/addons/base/models/ir_http.py", line 224, in _dispatch
    result.flatten()
  File "/opt/odoo17/odoo/odoo/http.py", line 1313, in flatten
    self.response.append(self.render())
  File "/opt/odoo17/odoo/odoo/http.py", line 1305, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/opt/odoo17/odoo/addons/website/models/ir_ui_view.py", line 442, in _render_template
    return super()._render_template(template, values=values)
  File "/opt/odoo17/odoo/odoo/addons/base/models/ir_ui_view.py", line 2051, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/opt/odoo17/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/opt/odoo17/odoo/odoo/addons/base/models/ir_qweb.py", line 599, in _render
    result = ''.join(rendering)
  File "<2260>", line 663, in template_2260
  File "<2260>", line 645, in template_2260_content
  File "<2260>", line 597, in template_2260_t_call_0
  File "<2247>", line 872, in template_2247
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: time data '2023-06-01+00:00:00' does not match format '%Y-%m-%d %H:%M:%S'
Template: website_blog.posts_loop
Path: /t/div/div[2]/div[1]/span[2]/t
Node: <t t-esc="date_begin" t-options="{\'widget\': \'date\', \'format\': \'MMM yyyy\'}"/>
```

**Comment by Himasnhu-AT** [comment]
Hey @gdrius , not sure if you are maintainer or not. I'm would love to contribute to odoo app. Let me know how i can
