### ISSUE TITLE
[17.0] mail: error when delete a tracking field

### ISSUE THREAD

**Issue by haumenphai** [odoo/odoo#172891]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I encountered an error when upgrading the database.
This error is because the `fname` does not exist in `self._fields` after the field has been removed in the code.

Here is all the traceback :
```
Traceback (most recent call last):
  File "/home/do/my_projects/odoo-17/odoo17/odoo/service/server.py", line 1313, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/do/my_projects/odoo-17/odoo17/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/do/my_projects/odoo-17/odoo17/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/do/my_projects/odoo-17/odoo17/odoo/modules/loading.py", line 536, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/home/do/my_projects/odoo-17/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 77, in _process_end
    return IrModelData._process_end._original_method(self, modules)
  File "/home/do/my_projects/odoo-17/odoo17/odoo/addons/base/models/ir_model.py", line 2558, in _process_end
    self._process_end_unlink_record(record)
  File "/home/do/my_projects/odoo-17/odoo17/odoo/addons/base/models/ir_model.py", line 2487, in _process_end_unlink_record
    record.unlink()
  File "/home/do/my_projects/odoo-17/odoo17/addons/mail/models/ir_model_fields.py", line 52, in unlink
    'sequence': self.env[field.model_id.model]._mail_track_get_field_sequence(field.name),
  File "/home/do/my_projects/odoo-17/odoo17/addons/mail/models/models.py", line 181, in _mail_track_get_field_sequence
    if isinstance(fname, IrModelFields):
KeyError: 'date_process'
```

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

**Comment by AEstLo** [comment]
Same issue

**Comment by AbdulrahmaanSaber** [comment]
go to setting/technical/discuss/tracking values
then search for field label or string not technical name, don't forget to show all records,
then group by field and select all old field records of the desired model as example it looks like: State (Contact)
then delete them all.
now upgrade the module and problem solved for now.
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٤٥٣٥٧](https://github.com/user-attachments/assets/f0387b23-5b47-44b2-957d-83e08314aad7)
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٥٠١٤٦](https://github.com/user-attachments/assets/05488cd4-bda4-41f3-a242-ffd5affa7cce)
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٥٠١٢٧](https://github.com/user-attachments/assets/2684d251-d095-4b2b-bdc5-854297b4dc16)
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٥٠٠١٨](https://github.com/user-attachments/assets/30487980-8d2b-44f5-b8f4-56ecf6baef1a)
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٤٥٩٥٢](https://github.com/user-attachments/assets/5711cb99-ce98-451a-99d8-b234a023445f)
![DeepinScreenshot_select-area_٢٠٢٤٠٩٠٥١٤٥٣٥٧](https://github.com/user-attachments/assets/aa1d5452-bc2e-4ad9-bbab-ff885b67ab8d)

**Comment by EwetoyeIbrahim** [comment]
Issue still persist in V18.
The current hack is to delete entries from `Settings > Technical > Discuss > Tracking Values` as explained above.

**Comment by Sibert-Aerts** [comment]
Confirming this is still an issue.
Also the tag "Marketing" on this issue is probably inappropriate, since tracking field values (and failing to delete tracked field values on upgrade) is is a pretty core Odoo framework issue, and doesn't really have anything to do with anything mailing related.
