### ISSUE TITLE
a recent commit makes the odoo upgrade failes commit ID -85b2ede4ee59bf18cdbee4ef97e9da3f023887c2

### ISSUE THREAD

**Issue by deviprasadcit** [odoo/odoo#173217]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

odoo db migration failed because of this commit. this code is committed on July 13 2024

### Log Output

```shell
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1313, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 205, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 574, in init_models
    model.init()
  File "/home/odoo/src/odoo/17.0/addons/phone_validation/models/mail_thread_phone.py", line 69, in init
    create_index(self.env.cr,
  File "/home/odoo/src/odoo/17.0/odoo/tools/sql.py", line 516, in create_index
    cr.execute(SQL(
  File "/home/odoo/src/odoo/17.0/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedObject: operator class "gin_trgm_ops" does not exist for access method "gin"
```

### Support Ticket

4054200.

**Comment by pedrobaeza** [comment]
Check https://github.com/odoo/odoo/pull/173101
