### ISSUE TITLE
[10.0] CoA in CSV accepting multiple tags per account, XML doesn't.

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#17401]
**Impacted versions:**
10.0

**Steps to reproduce:**
1. Change a working CoA with CSV to XML (the CoA in CSV had multiple tags per account)
2. Use `<field name="tag_ids" eval="[(6,0,[ref('account_tag_1', 'account_tag_11', 'account_tag_1101', 'account_tag_110103')])]"/>` for tag assignation on the XML format
2. Update Odoo with the new XML CoA

**Current behavior:**
Get the error:
```
2017-06-03 02:37:48,555 819 ERROR client odoo.tools.convert.init: Could not eval([(6,0,[ref('account_tag_1','account_tag_11','account_tag_1105')])]) for tag_ids in {}
2017-06-03 02:37:48,555 819 ERROR client odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 335, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 697, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 115, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/odoo/odoo-server/src/odoo/odoo/tools/convert.py", line 30, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/odoo/odoo-server/src/odoo/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ParseError: "<type 'exceptions.TypeError'>: "id_get() takes at most 3 arguments (4 given)" while evaluating
"[(6,0,[ref('account_tag_1','account_tag_11','account_tag_1105')])]"" while parsing /odoo/odoo-server/src/odoo/addons/l10n_do/data/account.account.template.xml:180, near
<record id="do_niif_11050600" model="account.account.template">
         <field name="name">Bienes Enviados No Facturados</field>
         <field name="code">11050600</field>
         <field name="chart_template_id" ref="do_chart_template"/>
         <field name="user_type_id" ref="account.data_account_type_current_assets"/>
         <field name="reconcile" eval="False"/>
         <field name="tag_ids" eval="[(6,0,[ref('account_tag_1','account_tag_11','account_tag_1105')])]"/>
      </record>
2017-06-03 02:37:48,556 819 CRITICAL client odoo.service.server: Failed to initialize database `client`.
```

**Expected behavior:**
The CoA should be uploaded with multiple tags, just as a normal CSV.

**Comment by gustavovalverde** [comment]
False alarm.
