### ISSUE TITLE
[10.0]Error Occurred When Alternative Product was added

### ISSUE THREAD

**Issue by puakinsin** [odoo/odoo#17402]
Impacted versions: 
Odoo 10.0

Steps to reproduce:
Adding Alternative Product

Current behavior:
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4696, in search_read
    result = records.read(fields)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3021, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 981, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/odoo-10.0/addons/product_stock_balance/models/product.py", line 23, in get_location_ids
    self.location_ids = self.location_ids.search([('usage','=','internal')])
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 864, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4823, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.template(12193, 12190)

**Comment by puakinsin** [comment]
The error above only shows up when open the selected product with alternative products other than from Point of Sales, I can open up the product just fine without any error

**Comment by dvdhinesh** [comment]
@puakinsin From the error log, i can see that the error was originating from the module `product_stock_balance`. 
Since it is not an official Odoo addon, i suggest you report directly to the module author or put a comment here https://www.odoo.com/apps/modules/10.0/product_stock_balance/ for them to review it.

**Comment by Yenthe666** [comment]
Hi @puakinsin,

Thank you for your report.
As @dvdhinesh has stated, this is not an official Odoo module but one from a partner.
The Github issue tracker is only for bugs/issues in the official Odoo code, not in custom developed modules. Please try to reach out to the creator of the app so that they can fix it.

Regards,
Yenthe
