### ISSUE TITLE
PayPal payment acquirer return to 500 internal server error

### ISSUE THREAD

**Issue by alexanderahlsen** [odoo/odoo#17421]
Impacted versions: 10.0

Steps to reproduce: enable and configure PayPal payment acquirer, make a purchase of event ticket using PayPal
Config: https://www.odoo.com/documentation/user/10.0/ecommerce/shopper_experience/paypal.html

Current behavior: When returning from PayPal I get a 500 internal server error

Expected behavior: Redirect to confirmation page

Video/Screenshot link (optional):
https://cl.ly/430b0j3r432m/o

Server log dump:
```
2017-06-05 22:39:20,111 3267 INFO xxx-domain-xxx.no odoo.addons.payment_paypal.controllers.main: Beginning Paypal DPN form_feedback with post data {'amt': u'1.00',
 'cc': u'NOK',
 'cm': u'{"return_url": "/shop/payment/validate"}',
 'item_name': u'Ethos Academy: SO017',
 'item_number': u'SO017',
 'st': u'Completed',
 'tx': u'0DL614781J401133U'}
2017-06-05 22:39:20,114 3267 INFO xxx-domain-xxx..no werkzeug: 127.0.0.1 - - [05/Jun/2017 22:39:20] "GET /payment/paypal/dpn/?amt=1.00&cc=NOK&cm=%7B%22return_url%22%3A%20%22%2Fshop%2Fpayment%2Fvalidate%22%7D&item_name=Ethos%20Academy%3A%20SO017&item_number=SO017&st=Complete$
2017-06-05 22:39:20,127 3267 ERROR xxx-domain-xxx..no werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1478, in dispatch
    result = ir_http._dispatch()
  File "/odoo/odoo-server/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 209, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/odoo/odoo-server/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 261, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/odoo/odoo-server/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/payment_paypal/controllers/main.py", line 92, in paypal_dpn
    return_url = self._get_return_url(**post)
  File "/odoo/odoo-server/addons/payment_paypal/controllers/main.py", line 24, in _get_return_url
    custom = json.loads(post.pop('custom', False) or post.pop('cm', False) or '{}')
AttributeError: 'module' object has no attribute 'unquote_plus'


2017-06-05 22:39:27,012 3267 INFO xxx-domain-xxx..no odoo.addons.payment_paypal.controllers.main: Paypal: validated data
2017-06-05 22:39:27,014 3267 INFO xxx-domain-xxx..no odoo.addons.payment_paypal.models.payment: Received a notification from Paypal with IPN version 3.8
2017-06-05 22:39:27,027 3267 INFO xxx-domain-xxx..no odoo.addons.payment_paypal.models.payment: Validated Paypal payment for tx SO017: set as done
```

**Comment by alexanderahlsen** [comment]
This was fixed by updating the PayPal plugin from the Odoo Github source. Seems to be some important updates we needed :)
