### ISSUE TITLE
[17.0] APPS - RPC_ERROR  Odoo Server Error 

### ISSUE THREAD

**Issue by nathonline** [odoo/odoo#174294]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Hello,

When I try to add a new plugin (.zip method on the UI).
I get this message :

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
        ~^^^^^
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.rule', <function IrRule._compute_domain at 0x7fb801f55ee0>, 2, False, 'base.import.module', 'write', ((1, 2, 3, 4),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/base_import_module/models/base_import_module.py", line 26, in import_module
    self.write({'state': 'done', 'import_message': res[0]})
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/models.py", line 4291, in write
    self.check_access_rule('write')
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/models.py", line 4088, in check_access_rule
    invalid = self - self._filter_access_rules_python(operation)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/models.py", line 4139, in _filter_access_rules_python
    dom = self.env['ir.rule']._compute_domain(self._name, operation)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-64>", line 2, in _compute_domain
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/base/models/ir_rule.py", line 135, in _compute_domain
    rules = self._get_rules(model_name, mode=mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/addons/base/models/ir_rule.py", line 118, in _get_rules
    self._cr.execute(query, (model_name, self._uid))
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20231105-py3.11.egg/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://xxxxxxxxxxxxx.fr/web/assets/8616a83/web.assets_web.min.js:2860:319
    makeErrorFromResponse@https://xxxxxxxxxxxxx.fr/web/assets/8616a83/web.assets_web.min.js:2863:163
    jsonrpc/promise</<@https://xxxxxxxxxxxxx.fr/web/assets/8616a83/web.assets_web.min.js:2867:34

I have any clue. Somebody could help me about this situation ? 

Regards,

### Log Output

_No response_

### Support Ticket

_No response_

**Comment by nathonline** [comment]
Hello @niyasraphy,

First of all, thank you for your feedback.

I am trying to install wk_backup_restore-17.0.1.0.2 but the zip is full of python files.
I really sorry about this question but ... how to install this package if python files are refused ?

Regards
