### ISSUE TITLE
KeyError when installing a module [9]

### ISSUE THREAD

**Issue by dstemple67** [odoo/odoo#17420]
Impacted versions: 9

Steps to reproduce: Install PrestaShop Odoo Connector

Current behavior: error

Expected behavior:

Video/Screenshot link (optional):

Here's the Traceback

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 132, in load_module_graph
    models = registry.load(cr, package)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/registry.py", line 169, in load
    model = cls._build_model(self, cr)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 591, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/registry.py", line 84, in __getitem__
    return self.models[model_name]
KeyError: 'base_multi_image.image'

**Comment by pedrobaeza** [comment]
This issue doesn't correspond here. Your problem is because you don't have all the needed dependencies. In this case, the module base_multi_image in OCA/server-tools. Please close the issue.

**Comment by Yenthe666** [comment]
Hi @dstemple67,

Thank you for your report.
The Github issue tracker is however only for bugs/issues in the official code, not for third party modules.
Please contact the app creator for support on this issue (base_multi_image in OCA/server-tools)

Regards,
Yenthe
