### ISSUE TITLE
[15.0] translations: have signs inside which break backend views in swedish localisation

### ISSUE THREAD

**Issue by x1g1** [odoo/odoo#174542]
### Odoo Version

- [X] 15.0
- [ ] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

When have swedisch localisation  and active as user has swedisch language configured
and go to product page
see Traceback

looks like this is not only for swedisch translations
think there is ” and ’ in italic also in other languages in some modules which

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/76dcd19d-9756-4be8-b9f7-fa8cad98447e">

How to identify:
SELECT id,lang,src,value,module FROM ir_translation WHERE value LIKE '%”%' or value LIKE '%’%'

mentioned also here
https://www.odoo.com/pl_PL/forum/pomoc-1/can-t-access-helpdesk-team-when-using-swedish-language-226580

### Log Output

```shell
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 368, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 921, in call
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 546, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1324, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 467, in call_kw
result = _call_kw_model(method, model, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 438, in _call_kw_model
result = method(recs, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 1640, in load_views
result['fields_views'] = {
File "/usr/lib/python3/dist-packages/odoo/models.py", line 1641, in
v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 249, in fields_view_get
r = super().fields_view_get(view_id, view_type, toolbar, submenu)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 1731, in fields_view_get
xarch, xfields = view.postprocess_and_fields(etree.fromstring(result['arch']), model=self._name)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1029, in postprocess_and_fields
name_manager = self._postprocess_view(node, model or self.model)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1076, in _postprocess_view
transfer_node_to_modifiers(node, node_info['modifiers'], self._context)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 88, in transfer_node_to_modifiers
modifiers.update(ast.literal_eval(attrs))
File "/usr/lib/python3/dist-packages/odoo/tools/_monkeypatches.py", line 65, in literal_eval
return orig_literal_eval(expr)
File "/usr/lib/python3.10/ast.py", line 64, in literal_eval
node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
File "/usr/lib/python3.10/ast.py", line 50, in parse
return compile(source, filename, mode, flags,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
raise exception.with_traceback(None) from new_cause
File "", line 1
”{’invisible’:
^
SyntaxError: invalid character '”' (U+201D)
```

### Support Ticket

4075413

**Comment by ossimantylahti** [comment]
Confirmed. This looks like a real defect for the translation. Unfortunately these every now and then slip in to the system.

Translations are managed in Transiflex. Here is the team link:
https://app.transifex.com/odoo/teams/41243/sv/

Perhaps @mart-e as the co-ordinator can see if any of the Swedish translation team could help out.
