### ISSUE TITLE
Odoo Migration Tool Issue: odoo15 to odoo16

### ISSUE THREAD

**Issue by aeraterta** [odoo/odoo#174618]
### Odoo Version

- [X] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Migration returns an error. 

Notes: 
- Sale Subscription relation is empty

### Log Output

```shell
2024-07-25 09:40:58,088 32 ERROR db_1870325 odoo.sql_db: bad query: 
        INSERT INTO sale_order (old_subscription_id, campaign_id, source_id, medium_id, client_order_ref,
                                name,
                                rating_last_value, message_main_attachment_id, stage_id, analytic_account_id,
                                company_id, partner_id, partner_invoice_id,

                                partner_shipping_id, recurring_monthly,
                                date_order, end_date, pricelist_id, close_reason_id, sale_order_template_id,
                                payment_term_id, note, user_id, team_id, country_id, industry_id,

                                access_token, payment_token_id, kpi_1month_mrr_delta, kpi_1month_mrr_percentage,
                                kpi_3months_mrr_delta, kpi_3months_mrr_percentage, percentage_satisfaction, health,
                                stage_category, to_renew, recurring_live,

                                state,
                                is_subscription, currency_id, create_date, create_uid, write_date, write_uid, recurrence_id,
                                start_date, next_invoice_date
                                ,picking_policy,warehouse_id)
             SELECT ss.id, ss.campaign_id, ss.source_id, ss.medium_id, ss.code,
                    -- match sub display_name
                    coalesce(nullif(concat_ws('/', sst.code, nullif(concat_ws(' - ', ss.code, p.display_name), '')), ''), ss.name),
                    ss.rating_last_value, ss.message_main_attachment_id, ss.stage_id, ss.analytic_account_id,
                    ss.company_id, COALESCE(ss.partner_id, 2), COALESCE(ss.partner_invoice_id, ss.partner_id, 2),

                    COALESCE(ss.partner_shipping_id, ss.partner_id, 2), ss.recurring_monthly,
                    COALESCE(ss.date_start, now() at time zone 'UTC'), ss.date, ss.pricelist_id, ss.close_reason_id, sot.id,
                    ss.payment_term_id, ss.description, ss.user_id, ss.team_id, ss.country_id, ss.industry_id,

                    ss.access_token, ss.payment_token_id, ss.kpi_1month_mrr_delta, ss.kpi_1month_mrr_percentage,
                    ss.kpi_3months_mrr_delta, ss.kpi_3months_mrr_percentage, ss.percentage_satisfaction, ss.health,
                    ss.stage_category, ss.to_renew, (ss.stage_category='progress'),

                    CASE
                        WHEN ss.stage_category='draft' THEN 'sent'
                        ELSE 'sale'
                    END,
                    TRUE, pl.currency_id, ss.create_date, ss.create_uid, ss.write_date, ss.write_uid, str.id,
                    ss.date_start, ss.recurring_next_date
                    ,'direct',('{"1": 1, "10": 6, "11": 7, "15": 8}'::jsonb->>ss.company_id::text)::int
               FROM sale_subscription ss
               JOIN sale_order_template sot
                 ON sot.old_template_id = ss.template_id
               JOIN product_pricelist pl
                 ON pl.id = ss.pricelist_id
               JOIN sale_temporal_recurrence str
                 ON ss.template_id = ANY(str._mig_sst_id)
               JOIN sale_subscription_template sst
                 ON sst.id = ss.template_id
          LEFT JOIN res_partner p
                 ON p.id = ss.partner_id
    
ERROR: column "note" is of type jsonb but expression is of type text
LINE 27:                     ss.payment_term_id, ss.description, ss.u...
                                                 ^
HINT:  You will need to rewrite or cast the expression.
 
2024-07-25 09:40:58,099 32 WARNING db_1870325 odoo.modules.loading: Transient module states were reset 
2024-07-25 09:40:58,099 32 ERROR db_1870325 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpbro6441i/migrations/sale_subscription/saas~15.3.1.1/pre-migrate.py", line 387, in migrate
    cr.execute(query, {"p": util.ref(cr, "base.partner_root")})
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.DatatypeMismatch: column "note" is of type jsonb but expression is of type text
LINE 27:                     ss.payment_term_id, ss.description, ss.u...
                                                 ^
HINT:  You will need to rewrite or cast the expression.
```

**Comment by nilshamerlinck** [comment]
Did you open a ticket on Odoo side already? https://odoo.com/support
This repository is focused on the Community Edition of odoo, which does not include the migration scripts.

**Comment by Sostenia-Odoo** [comment]
@aeraterta Did you manage to solve this issue somehow?

Kind regards,
Andrei

**Comment by andreisostenia** [comment]
@aeraterta Did you manage to solve this issue somehow?

Kind regards,
