### ISSUE TITLE
[16.0] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 103 during database connection

### ISSUE THREAD

**Issue by MuhammedMiiRanna** [odoo/odoo#174877]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I was Following this tutorial: https://www.youtube.com/watch?v=2_Yu_hX85NY&list=PLFSlYEuka9lvpCEFgciH4awFj3_7lm-9g&index=5

- I am trying trying to install odoo16 and run it on my machine, I am working on windows10, I installed Postgres and then tried installing odoo16 with both vs code and Pycharm, but I got this error: 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 103: invalid continuation byte

### Log Output

```shell
Traceback (most recent call last):
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 2037, in __call__
    request._post_init()
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 1214, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 1234, in _get_session_and_dbname
    all_dbs = db_list(force=True, host=host)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 303, in db_list
    dbs = odoo.service.db.list_dbs(force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\service\db.py", line 407, in list_dbs
    with closing(db.cursor()) as cr:
                 ^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 740, in cursor
    return Cursor(self.__pool, self.__dbname, self.__dsn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 267, in __init__
    self._cnx = pool.borrow(dsn)
                ^^^^^^^^^^^^^^^^
  File "<decorator-gen-2>", line 2, in borrow
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 668, in borrow
    result = psycopg2.connect(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 103: invalid continuation byte
2024-07-29 13:58:25,389 364 INFO ? werkzeug: 127.0.0.1 - - [29/Jul/2024 13:58:25] "GET /web/database/selector HTTP/1.1" 500 - 0 0.000 0.070
2024-07-29 13:58:25,517 364 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 2037, in __call__
    request._post_init()
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 1214, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 1234, in _get_session_and_dbname
    all_dbs = db_list(force=True, host=host)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\http.py", line 303, in db_list
    dbs = odoo.service.db.list_dbs(force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\service\db.py", line 407, in list_dbs
    with closing(db.cursor()) as cr:
                 ^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 740, in cursor
    return Cursor(self.__pool, self.__dbname, self.__dsn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 267, in __init__
    self._cnx = pool.borrow(dsn)
                ^^^^^^^^^^^^^^^^
  File "<decorator-gen-2>", line 2, in borrow
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\odoo\sql_db.py", line 668, in borrow
    result = psycopg2.connect(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Advanced\Desktop\odoo16\odoo16\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 103: invalid continuation byte
2024-07-29 13:58:25,518 364 INFO ? werkzeug: 127.0.0.1 - - [29/Jul/2024 13:58:25] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.063
2024-07-29 14:03:47,234 364 INFO ? odoo.service.server: Initiating shutdown 
2024-07-29 14:03:47,235 364 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-07-29 14:03:47,665 364 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 0 connections
```

**Comment by marcgardent** [comment]
same issue Windows 10 Installer Odoo 17.
