### ISSUE TITLE
Problem Sending message from Cron job

### ISSUE THREAD

**Issue by NeoGenesis1986** [odoo/odoo#17543]
Impacted versions: 10.0

Steps to reproduce: Create Cron job that calls the method message_post()

Current behavior: Cron runs in an infinite loop. Console shows the following message (exception happens after the cron function exits): 
```
insurance cron in
<h3>Notification</h3><br/>Le contrat d'assurance du véhicule <strong>'Polo ka7la'</strong> expire dans <strong>4</strong> jour(s).
<h3>Alerte</h3><br/><br/>Le véhicule <strong>'test'</strong> ne possède aucun contrat d'assurance.
<h3>Alerte</h3><br/><br/>Le véhicule <strong>'V001'</strong> ne possède aucun contrat d'assurance.
insurance cron out
2017-06-10 10:18:12,960 5250 ERROR khidma odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'_cron_check_insurance_expiration_date', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Check insurances expiration date', 'interval_type': u'days', 'numbercall': -1, 'nextcall': '2017-06-10 10:17:19', 'priority': 5, 'model': u'ostool.vehicule', 'doall': False, 'write_date': '2017-06-10 10:17:16.377941', 'active': True, 'create_date': '2017-06-10 10:17:16.377941', 'interval_number': 1, 'write_uid': 1, 'id': 17}
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_cron.py", line 235, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_cron.py", line 168, in _process_job
    job_cr.commit()
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 365, in commit
    func()
  File "/opt/odoo/odoo-10.0/addons/mail/models/res_partner.py", line 236, in send_notifications
    env = api.Environment(cr, SUPERUSER_ID, {})
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 726, in __new__
    env, envs = None, cls.envs
  File "/opt/odoo/odoo-10.0/odoo/tools/func.py", line 111, in __get__
    return self.fget.__get__(None, owner)()
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 699, in envs
    return cls._local.environments
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 71, in __getattr__
    raise AttributeError(name)
AttributeError: environments
```

Expected behavior: Cron runs once and exits normally as it does when you run the cron job manually

Additional info : 
Cron XML : 
```
        <record model="ir.cron" id="ostool_vehicule_insurance_cron">
            <field name="name">Check insurances expiration date</field>
            <field name="interval_number">1</field>
            <field name="interval_type">days</field>
            <field name="numbercall">-1</field>
            <field name="doall" eval="False"/>
            <field name="model" eval="'ostool.vehicule'"/>
            <field name="function" eval="'_cron_check_insurance_expiration_date'"/>
            <field name="args" eval="'()'" />
        </record>
```
Cron function : 
```
    def _cron_check_insurance_expiration_date(self):
        print "insurance cron in"
        vehicules_ids = self.search([])
        config = self.env['ostool.config'].search_read([], order='write_date DESC', limit=1)
        if not config:
            raise UserError("Configuration Introuvable")
        config = config[0]
        alert_period = config.get('alert_period')
        responsible_id = config.get('responsible_partner_id')
        for v_id in vehicules_ids:
            alert = False
            subject = u""
            body = u""
            insurances = self.env['ostool.insurance'].search_read([('vehicule_id', '=', v_id.id)], ['expiration'], order='end_date DESC')
            v = self.browse(v_id.id)
            if insurances:
                expiration = insurances[0].get('expiration')
                if expiration <= 0:
                    alert = True
                    subject = u"Alerte"
                    body = u"<h3>Alerte</h3><br/>Le contrat d'assurance du véhicule <strong>'" + v.name + u"'</strong> est expiré."
                elif expiration <= alert_period:
                    alert = True
                    subject = u"Notification"
                    body = u"<h3>Notification</h3><br/>Le contrat d'assurance du véhicule <strong>'" + v.name + u"'</strong> expire dans <strong>" + unicode(str(expiration), 'utf-8') + u"</strong> jour(s)."
            else:
                alert = True
                subject = u"Alerte"
                body = u"<h3>Alerte</h3><br/><br/>Le véhicule <strong>'" + v.name + u"'</strong> ne possède aucun contrat d'assurance."
            if alert:
                print body
                v.message_post(
                    subject=subject,
                    body=body,
                    partner_ids=[(4, responsible_id)]
                )
        print "insurance cron out"
        return True
```

**Comment by pedrobaeza** [comment]
I haven't found any problem posting messages in crons.

Do you still experiment same problems with latest code version?

**Comment by pedrobaeza** [comment]
Closing as no answer

**Comment by salfredogonzalez** [comment]
This code is not working for me, i would like 

`<?xml version="1.0" encoding="utf-8" ?>
<odoo>
    <data noupdate="1">
       <record id="_print_cron" model="ir.cron">
            <field name="name">Print</field>
            <field name="interval_number">1</field>
            <field name="interval_type">minutes</field>
            <field name="number_call">-1</field>
            <field name="doall" eval="False" />
            <field name="model" eval="'model.cronjob'"/>
            <field name="function" eval="'_print'"/>
            <field name="args" eval="'()'"/>
        </record>
    </data>
</odoo>`

`class Cronjob(models.Model):
    _name = 'model.cronjob'

    def _print(self):
        print('hello world')`
