### ISSUE TITLE
[17.0] product_expiry: cannot enable Expiration Dates in inventory setting

### ISSUE THREAD

**Issue by JosephCCN** [odoo/odoo#175469]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to Setting -> Inventory -> Traceability
- Enable Expiration Dates
- Hit Save
- Error appears

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/res_config.py", line 605, in execute
    installation_status = self._install_modules(to_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/res_config.py", line 32, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:3
Error while parsing or validating view:

Element '<xpath expr="//div[@name=&#39;lot_name&#39;]">' cannot be located in parent view

View error context:
{'file': '/home/odoo/src/odoo/addons/product_expiry/report/report_lot_barcode.xml',
 'line': 2,
 'name': 'report_lot_label_expiry',
 'view': ir.ui.view(2765,),
 'view.model': False,
 'view.parent': ir.ui.view(905,),
 'xmlid': 'report_lot_label_expiry'}


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://ettason-stage1-13877352.dev.odoo.com/web/assets/f6ed95e/web.assets_web.min.js:2883:319
    makeErrorFromResponse@https://ettason-stage1-13877352.dev.odoo.com/web/assets/f6ed95e/web.assets_web.min.js:2886:163
    jsonrpc/promise</<@https://ettason-stage1-13877352.dev.odoo.com/web/assets/f6ed95e/web.assets_web.min.js:2890:34
```

**Comment by ossimantylahti** [comment]
@JosephCCN I cannot repeat that on Runbot. What localisation and languages are you using? This could be i18n specific issue

**Comment by JosephCCN** [comment]
@ossimantylahti We are using odoo.sh with odoo 17.0+e, the location of the odoo.sh server is "Other Asia" in HK with English

**Comment by ossimantylahti** [comment]
@JosephCCN This is most probably HK English translation bug. Could you please try to change to US English or English UK and try again.

**Comment by JosephCCN** [comment]
Thanks @ossimantylahti , we have discovered it is due to unexpected source code changed to Sale module, after upgrading the Sale module everything works now.
