### ISSUE TITLE
[17.0] Odoo 17.4 Online: CSS Error When Creating New Database in Arabic

### ISSUE THREAD

**Issue by compnew2006** [odoo/odoo#175827]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

**Bug Report: CSS Error When Creating New Database in Arabic on SaaS 17.4**

**Description:**
Every time I attempt to create a new database with SaaS 17.4, I encounter a CSS error. The error message indicates that a CSS compilation error has occurred, causing the system to use an old style to render the page. This issue appears to be specific to the Arabic language setting, as the page renders correctly when set to English.

**Steps to Reproduce:**
1. Log in to Odoo SaaS 17.4.
2. Create a new database.
3. Set the language to Arabic.
4. Observe the rendering error on the page.

**Expected Behavior:**
The page should render correctly using the updated styles regardless of the selected language.

**Actual Behavior:**
The page falls back to an old style due to a CSS compilation error when the language is set to Arabic.

**Additional Information:**
- The error does not occur when the language is set to English.
- The style compilation failure is an administrative or development issue that needs resolution for the entire database.
- Please check the browser console or server logs for more details.

**Attempts to Resolve:**
- Tried creating databases with different accounts, but the issue persists.

Thank you for your assistance in resolving this issue.

**Comment by compnew2006** [comment]
Engilsh 
![image](https://github.com/user-attachments/assets/51929e79-b7f2-4f05-a70e-21cdd6989a3f)
Arabic
![image](https://github.com/user-attachments/assets/bed16784-e2cf-41a9-b2b4-37eeccfaa316)

**Comment by compnew2006** [comment]
trying it today and it's fixed but when make pos sales order and try to print it got this 

`undefined
undefined
time data '٢٠٢٤-٠٨-٠٩ ١٣:٣٠:١١' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/http.py", line 1966, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/model.py", line 134, in retrying
    result = func()
             ^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/http.py", line 1933, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/http.py", line 2177, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_http.py", line 223, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/web/controllers/dataset.py", line 35, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 459, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/pos_self_order/models/pos_order.py", line 54, in sync_from_ui
    return super().sync_from_ui(orders)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/pos_restaurant/models/pos_order.py", line 21, in sync_from_ui
    result = super().sync_from_ui(orders)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/enterprise/saas-17.4/pos_preparation_display/models/pos_order.py", line 11, in sync_from_ui
    data = super().sync_from_ui(orders)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/point_of_sale/models/pos_order.py", line 943, in sync_from_ui
    order_ids.append(self._process_order(order, existing_draft_order))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/point_of_sale/models/pos_order.py", line 115, in _process_order
    pos_order.write(order)
  File "/home/odoo/src/odoo/saas-17.4/addons/pos_online_payment_self_order/models/pos_order.py", line 31, in write
    return super().write(vals)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/point_of_sale/models/pos_order.py", line 481, in write
    return super(PosOrder, self).write(vals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/addons/mail/models/mail_thread.py", line 331, in write
    result = super(MailThread, self).write(values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 4546, in write
    field.write(self, value)
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1177, in write
    cache_value = self.convert_to_cache(value, records)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 2367, in convert_to_cache
    return self.to_datetime(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 2347, in to_datetime
    return datetime.strptime(value, DATETIME_FORMAT[:len(value)-2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '٢٠٢٤-٠٨-٠٩ ١٣:٣٠:١١' does not match format '%Y-%m-%d %H:%M:%S'

`
