### ISSUE TITLE
[17.0] Uncaught Promise > Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by tiborrr** [odoo/odoo#175801]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

# Odoo Error: Uncaught Promise > Cannot read properties of undefined (reading 'split')

## Steps to Reproduce

I'm unable to provide specific steps to reproduce this issue, as I'm not sure how it was initially caused. The error occurs when opening Odoo, and I've been unable to undo or resolve it.

## Current Behavior

When opening Odoo, the following error is thrown:

```log
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at formatTraceback (<https://company.odoo.com/web/assets/5784334/web.assets_web.min.js:2400:216>)
    at fullTraceback (<https://company.odoo.com/web/assets/5784334/web.assets_web.min.js:2385:83>)
    at completeUncaughtError (<company.odoo.com/web/assets/5784334/web.assets_web.min.js:2396:315>)
    at <https://company.odoo.com/web/assets/5784334/web.assets_web.min.js:2380:357>
```

## Relevant Code

The error originates from the following function:

```javascript
function formatTraceback(error) {
    let traceback = error.stack;
    const errorName = getErrorTechnicalName(error);
    const descriptionLine = `${errorName}: ${error.message}`;
    if (error.stack.split("\n")[0].trim() !== descriptionLine) {
        traceback = `${descriptionLine}\n${error.stack}`.replace(/\n/g, "\n    ");
    }
    return traceback;
}
```

## Root Cause

The error appears to be caused by a DOMException:

```javascript
{
    name: "AbortError",
    message: "Registration failed - push service error",
    code: 20
}
```

It seems that this DOMException does not have a `stack` property, causing `split` to be called on `undefined`.

## Additional Information

- The error is related to a push service registration failure.
- The DOMException lacks a `stack` property, which is expected in the `formatTraceback` function.

## Possible Solution

A potential fix could involve modifying the `formatTraceback` function to handle cases where `error.stack` is undefined:

```javascript
function formatTraceback(error) {
    let traceback = error.stack || error.toString();
    const errorName = getErrorTechnicalName(error);
    const descriptionLine = `${errorName}: ${error.message}`;
    if (error.stack && error.stack.split("\n")[0].trim() !== descriptionLine) {
        traceback = `${descriptionLine}\n${error.stack}`.replace(/\n/g, "\n    ");
    }
    return traceback;
}
```

This modification would prevent the function from throwing an error when `error.stack` is undefined, which appears to be the case with the DOMException being encountered.

### Support Ticket

4098708

**Comment by tirthbodawala** [comment]
I am facing the same issue!

**Comment by troykelly** [comment]
Same issue here with a completely fresh install.

**Comment by mrd116** [comment]
Same issue here with a completely fresh install. anyone had temp solution? Thanks a lot!

**Comment by troykelly** [comment]
> Same issue here with a completely fresh install. anyone had temp solution? Thanks a lot!

On four fresh installs - the "fix" for two of them was to completely remove any application storage for the domain in the browser. But this didn't work always, but might help you.

**Comment by mrd116** [comment]
> > Vấn đề tương tự ở đây với một cài đặt hoàn toàn mới. Bất cứ ai có giải pháp tạm thời? Cảm ơn nhiều!
> 
> Trên bốn cài đặt mới - "sửa chữa" cho hai trong số đó là xóa hoàn toàn mọi bộ nhớ ứng dụng cho miền trong trình duyệt. Nhưng điều này không phải lúc nào cũng hiệu quả, nhưng có thể giúp bạn.

It worked. Thanks you so much 👍

**Comment by F4LC0NN** [comment]
Hello, this problem is still present in version 18.0 on startup.
It occurs after activating the notifications (after clicking on Odoo Bots suggestion).
It does not occur when I reset the permissions from the browser.
I still do not know why the notifications would cause this though.

Note: The only module I installed was Discuss.

I hope it helps clarify ! :smiley:

**Comment by kavin-lee** [comment]
I encountered the same problem in odoo17, but google browser does not report errors, while microsoft edge browser reports errors. How can I solve this problem?

**Comment by PapaZigE** [comment]
Same error for multiple users...

**Comment by jabelchi** [comment]
One of my customers face the same problem (Odoo 17.0 on premise), but I can't reproduce it on my computer (from other network)

**Comment by troykelly** [comment]
@jabelchi Have they tried completely getting rid of the application storage and cache.
There were a couple of Odoo 17 builds that it worked for - if they are running one of those builds, that might be a fix.

**Comment by aqeebimtiaz-bista** [comment]
Hi! We're facing the same error ever so suddenly on different mobile devices. Has anyone have created a PR for the potential fix that was mentioned by @tiborrr in the original issue report?

**Comment by KingMob** [comment]
Still causing problems in May 2026.
