### ISSUE TITLE
[17.0] l10n_bd: Selecting Bangladesh as Fiscal Localization resulting error.

### ISSUE THREAD

**Issue by nsrshishir** [odoo/odoo#176437]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go To Accounting -> Configuration -> Settings: Select Bangladesh as Fiscal Localization; Save. 

### Log Output

```shell
2024-08-11 11:53:43,394 38204 ERROR  odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/odoo/odoo-server/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo-server/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fad9beff0a0>, 'l10n_bd.account_tags_tax_c_cog')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 606, in load_modules
    model._register_hook()
  File "/odoo/odoo-server/addons/account/models/ir_module.py", line 91, in _register_hook
    self.env.registry._auto_install_template(self.env)
  File "/odoo/odoo-server/addons/account/models/ir_module.py", line 68, in try_loading
    env['account.chart.template'].try_loading(
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 153, in try_loading
    return self._load(template_code, company, install_demo)
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 211, in _load
    self._load_data(data)
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 594, in _load_data
    'values': deref_values(record_vals, self.env[model]),
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 517, in deref_values
    values[fname] = [Command.set([
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 518, in <listcomp>
    self.ref(v).id
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 1039, in ref
    return self.env.ref(xmlid, raise_if_not_found)
  File "/odoo/odoo-server/odoo/api.py", line 580, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2187, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-43>", line 2, in _xmlid_lookup
  File "/odoo/odoo-server/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2180, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_bd.account_tags_tax_c_cog
2024-08-11 11:53:43,397 38204 INFO  odoo.modules.loading: loading 1 modules... 
2024-08-11 11:53:43,404 38204 INFO  odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2024-08-11 11:53:43,408 38204 INFO  odoo.modules.loading: loading 42 modules... 
2024-08-11 11:53:43,439 38204 INFO  odoo.modules.loading: 42 modules loaded in 0.03s, 0 queries (+0 extra) 
2024-08-11 11:53:43,543 38204 INFO  odoo.modules.loading: Modules loaded. 
2024-08-11 11:53:43,546 38204 INFO  odoo.modules.registry: Registry loaded in 0.151s 
2024-08-11 11:53:43,546 38204 ERROR  odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/odoo/odoo-server/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo-server/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fad9beff0a0>, 'l10n_bd.account_tags_tax_c_cog')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 2189, in __call__
    response = request._serve_db()
  File "/odoo/odoo-server/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/odoo/odoo-server/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/odoo-server/odoo/http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/odoo-server/odoo/http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/odoo-server/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/odoo/odoo-server/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 606, in load_modules
    model._register_hook()
  File "/odoo/odoo-server/addons/account/models/ir_module.py", line 91, in _register_hook
    self.env.registry._auto_install_template(self.env)
  File "/odoo/odoo-server/addons/account/models/ir_module.py", line 68, in try_loading
    env['account.chart.template'].try_loading(
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 153, in try_loading
    return self._load(template_code, company, install_demo)
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 211, in _load
    self._load_data(data)
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 594, in _load_data
    'values': deref_values(record_vals, self.env[model]),
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 517, in deref_values
    values[fname] = [Command.set([
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 518, in <listcomp>
    self.ref(v).id
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 1039, in ref
    return self.env.ref(xmlid, raise_if_not_found)
  File "/odoo/odoo-server/odoo/api.py", line 580, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2187, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-43>", line 2, in _xmlid_lookup
  File "/odoo/odoo-server/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_model.py", line 2180, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_bd.account_tags_tax_c_cog
```

**Comment by vin-odoo** [comment]
Hello, we will fix this issue. Thank you for reporting it :)

**Comment by vin-odoo** [comment]
Thank you again for the report, the fix has been merged and should be available in all databases by the end of the day.
