### ISSUE TITLE
[17.0] l10n_sa_edi, l10n_sa_edi_pos, l10n_sa_pos: Unable to open Customer Invoice

### ISSUE THREAD

**Issue by ossama-nvis** [odoo/odoo#176436]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Install modules: l10n_sa_edi, l10n_sa_edi_pos, l10n_sa_pos
- Create a new POS order, and select "Invoice" button when you pay
- Go to Customer Invoice (backend), and click on the generated Customer Invoice
- The following error will be displayed

Current behavior: trackback:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:916:101)
        at App.handleError (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:1543:29)
        at ComponentNode.initiateRender (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:1006:19)

Caused by: Error: "account.move"."show_update_fpos" field is undefined.
    at Field.parseFieldNode (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:7682:231)
    at http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:8556:865
    at visit (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4234:51)
    at visitChildren (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4233:171)
    at visit (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4234:129)
    at visitChildren (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4233:171)
    at visit (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4234:129)
    at visitXML (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:4234:202)
    at FormArchParser.parse (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:8556:791)
    at Object.props (http://localhost:9017/web/assets/3e02d24/web.assets_web.min.js:8742:1061)

Expected behavior:
Clicking on the generated invoice will open the invoice without any error

### Log Output

```shell
2024-08-11 12:09:37,225 26784 INFO 17-pos-ee werkzeug: 127.0.0.1 - - [11/Aug/2024 12:09:37] "POST /web/dataset/call_kw/account.move/web_search_read HTTP/1.1" 200 - 10 0.007 0.012
2024-08-11 12:09:37,485 26784 INFO 17-pos-ee werkzeug: 127.0.0.1 - - [11/Aug/2024 12:09:37] "POST /onboarding/account_invoice HTTP/1.1" 200 - 12 0.009 0.017
```

**Comment by duong77476-viindoo** [comment]
No error to me, please try upgrade your account module

**Comment by inst-sol4u** [comment]
Thank you... after upgrading the account module... I am able to open Customer Invoices.

**Comment by ossama-nvis** [comment]
Thank you... after upgrading the account module... I am able to open Customer Invoices.

**Comment by ossama-nvis** [comment]
Thank you... after upgrading the account module... I am able to open Customer Invoices.

**Comment by hetulhh** [comment]
Thank you... upgrading the account module. solved the problem

**Comment by ndd-odoo** [comment]
> Thank you... upgrading the account module. solved the problem

You are welcome bro
