### ISSUE TITLE
[16.0] pos_sale: 'sale.order.line' object has no attribute 'move_ids'

### ISSUE THREAD

**Issue by valero1120** [odoo/odoo#177317]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

When closing the point of sale session it generates this error.

### Log Output

```shell
Traceback (most recent call last):
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1649, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo16/16.0/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1676, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 1880, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo16/16.0/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo16/16.0/odoo/odoo/http.py", line 732, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo16/16.0/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo16/16.0/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo16/16.0/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo16/16.0/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/pos_session.py", line 284, in action_pos_session_closing_control
    return session.action_pos_session_validate(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/pos_session.py", line 289, in action_pos_session_validate
    return self.action_pos_session_close(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/pos_session.py", line 296, in action_pos_session_close
    return self._validate_session(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/pos_session.py", line 311, in _validate_session
    self._create_picking_at_end_of_session()
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/pos_session.py", line 618, in _create_picking_at_end_of_session
    pickings = self.env['stock.picking']._create_picking_from_pos_order_lines(location_dest_id, lines, picking_type)
  File "/opt/odoo16/16.0/odoo/addons/point_of_sale/models/stock_picking.py", line 45, in _create_picking_from_pos_order_lines
    positive_picking._create_move_from_pos_order_lines(positive_lines)
  File "/opt/odoo16/16.0/odoo/addons/pos_sale/models/stock_picking.py", line 15, in _create_move_from_pos_order_lines
    if any(wh != line.order_id.config_id.warehouse_id for wh in line.sale_order_line_id.move_ids.location_id.warehouse_id):
AttributeError: 'sale.order.line' object has no attribute 'move_ids'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:1669/web/assets/463-902f5bc/web.assets_backend.min.js:997:163)
        at XMLHttpRequest.<anonymous> (http://localhost:1669/web/assets/463-902f5bc/web.assets_backend.min.js:1005:13)
```

**Comment by duong77476-viindoo** [comment]
you need to install sale_stock module, normally it will be auto install , i guess you have done something which make it doesn't

**Comment by valero1120** [comment]
> you need to install sale_stock module, normally it will be auto install , i guess you have done something which make it doesn't

The most likely thing is that this module is not being installed correctly, since I checked and it was installed, what I did was update the sale_stock module and it now works correctly, thank you very much
