### ISSUE TITLE
Possible bug in Docker container - When changing reports, an error is raised, ValueError: Expected singleton: ir.actions.report.xml(300, 334)

### ISSUE THREAD

**Issue by meatballcoder** [odoo/odoo#17751]
I am using Docker.

I duplicated a report and got the error below.  I was able to fix it with, 

https://github.com/odoo/odoo/issues/9201

Impacted versions: 10 Stable

Steps to reproduce:

Log in in debug mode.  Go to Settings and Reports.  Create a backup of a report via duplicate.  Go back to report that was working.  Get error below:
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/point_of_sale/wizard/pos_details.py", line 49, in generate_report
    [], 'point_of_sale.report_saledetails', data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 293, in get_action
    'report_name': report.report_name,
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 863, in __get__
    record.ensure_one()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4798, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: ir.actions.report.xml(300, 334)
```
Current behavior:

Error above.

Expected behavior:

Report to work.

Video/Screenshot link (optional):

**Comment by meatballcoder** [comment]
Why was this closed?

**Comment by wtaferner** [comment]
> mart-e closed this in 71d3b14 an hour ago

**Comment by meatballcoder** [comment]
I am asking why it was closed.  The issue is outstanding, so I didn't understand.  Sorry.

**Comment by pedrobaeza** [comment]
No if you update your source.

**Comment by meatballcoder** [comment]
I do not understand.

**Comment by pedrobaeza** [comment]
The problem is solved. Update your code.

**Comment by meatballcoder** [comment]
Oh!  I see now.  Sorry for my ignorance.  Thanks for the fix.

**Comment by mart-e** [comment]
Thanks, fixed at https://github.com/odoo/odoo/commit/71d3b1469118cc5d1045501125bed3ee26177c40
