### ISSUE TITLE
XML Errors After Fix

### ISSUE THREAD

**Issue by awwea** [odoo/odoo#17803]
Impacted versions: 10

Steps to reproduce: #

Current behavior: #

Expected behavior: #

Video/Screenshot link (optional):

=============================
After this fix
https://github.com/odoo/odoo/commit/92be0df468c3f467e078be18a13ab1cf5215f376?diff=unified
threw XML errors in purchase & product_extended module.
File views/product_views.xml in stock module -if commented out lines 397 - 410, everything is fine

**Comment by odony** [comment]
Can you provide the complete XML errors you see?
Can you still reproduce this after forcing an update the `product` module? (in the list of installed Apps, or via command-line startup parameters `-d <db> -u product` )?

**Comment by awwea** [comment]
OUTPUT:
=======================

2017-07-05 20:29:11,635 348053 INFO awwea odoo.addons.base.ir.ir_ui_view: Element '<xpath expr="//label[@for='weight']">' cannot be located in parent view

Error context:
View `product.template_procurement`
[view_id: 1100, xml_id: stock.product_template_form_view_procurement_button, model: product.template, parent_id: 349]
2017-07-05 20:29:11,637 348053 ERROR awwea odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/opt/odoo/10/env/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_model.py", line 1189, in _update
    record.write(values)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/opt/odoo/10/env/odoo/models.py", line 3572, in write
    self._fields[key].determine_inverse(self)
  File "/var/opt/odoo/10/env/odoo/fields.py", line 1000, in determine_inverse
    getattr(records, self.inverse)()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/opt/odoo/10/env/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/var/opt/odoo/10/env/odoo/models.py", line 3715, in _write
    self._validate_fields(vals)
  File "/var/opt/odoo/10/env/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<xpath expr="//label[@for='weight']">' cannot be located in parent view

Error context:
View `product.template_procurement`
[view_id: 1100, xml_id: stock.product_template_form_view_procurement_button, model: product.template, parent_id: 349]
None" while parsing /var/opt/odoo/10/env/addons/purchase/views/purchase_views.xml:609, near
<record id="view_product_template_purchase_buttons_from" model="ir.ui.view">
            <field name="name">product.template.purchase.button.inherit</field>
            <field name="model">product.template</field>
            <field name="inherit_id" ref="product.product_template_only_form_view"/>
            <field name="groups_id" eval="[(4, ref('purchase.group_purchase_user'))]"/>
            <field name="arch" type="xml">
                <div name="button_box" position="inside">
                   <button class="oe_stat_button" name="%(purchase.action_purchase_line_product_tree)d" type="action" icon="fa-shopping-cart">
                       <field string="Purchases" name="purchase_count" widget="statinfo"/>
                   </button>
                </div>
            </field>
        </record>
2017-07-05 20:29:11,639 348053 CRITICAL awwea odoo.service.server: Failed to initialize database `awwea`.
Traceback (most recent call last):
  File "/var/opt/odoo/10/env/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/opt/odoo/10/env/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/opt/odoo/10/env/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/var/opt/odoo/10/env/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_model.py", line 1189, in _update
    record.write(values)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/opt/odoo/10/env/odoo/models.py", line 3572, in write
    self._fields[key].determine_inverse(self)
  File "/var/opt/odoo/10/env/odoo/fields.py", line 1000, in determine_inverse
    getattr(records, self.inverse)()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/opt/odoo/10/env/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/var/opt/odoo/10/env/odoo/models.py", line 3715, in _write
    self._validate_fields(vals)
  File "/var/opt/odoo/10/env/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Element '<xpath expr="//label[@for='weight']">' cannot be located in parent view

Error context:
View `product.template_procurement`
[view_id: 1100, xml_id: stock.product_template_form_view_procurement_button, model: product.template, parent_id: 349]
None" while parsing /var/opt/odoo/10/env/addons/purchase/views/purchase_views.xml:609, near
<record id="view_product_template_purchase_buttons_from" model="ir.ui.view">
            <field name="name">product.template.purchase.button.inherit</field>
            <field name="model">product.template</field>
            <field name="inherit_id" ref="product.product_template_only_form_view"/>
            <field name="groups_id" eval="[(4, ref('purchase.group_purchase_user'))]"/>
            <field name="arch" type="xml">
                <div name="button_box" position="inside">
                   <button class="oe_stat_button" name="%(purchase.action_purchase_line_product_tree)d" type="action" icon="fa-shopping-cart">
                       <field string="Purchases" name="purchase_count" widget="statinfo"/>
                   </button>
                </div>
            </field>
        </record>
2017-07-05 20:29:11,639 348053 INFO awwea odoo.service.server: Initiating shutdown

**Comment by awwea** [comment]
Was other module conflicting with xpath
