### ISSUE TITLE
[17.0] base: issue with record in cache `virtual_` while saving ir.actions.sever with child_ids

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#178541]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to Settings > Technical > Server Actions
- Add a Server Action with Type as Execute Existing Actions
- Add 2 action, anything, but set to Update Record then select action as Update, any many2one field, then select a value
- Save the Server Action

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1781, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1808, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 2012, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/web/models/models.py", line 73, in web_save
    self = self.create(vals)
  File "<decorator-gen-56>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/odoo/addons/base/models/ir_actions.py", line 78, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/models.py", line 4626, in create
    records = self._create(data_list)
  File "/data/build/odoo/odoo/models.py", line 4873, in _create
    field.create([
  File "/data/build/odoo/odoo/fields.py", line 4332, in create
    self.write_batch(record_values, True)
  File "/data/build/odoo/odoo/fields.py", line 4358, in write_batch
    self.write_real(records_commands_list, create)
  File "/data/build/odoo/odoo/fields.py", line 4910, in write_real
    comodel.browse(command[1]).write(command[2])
  File "/data/build/odoo/odoo/addons/base/models/ir_actions.py", line 84, in write
    res = super(IrActions, self).write(vals)
  File "/data/build/odoo/odoo/models.py", line 4456, in write
    fields[0].determine_inverse(real_recs)
  File "/data/build/odoo/odoo/fields.py", line 1398, in determine_inverse
    determine(self.inverse, records)
  File "/data/build/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/data/build/odoo/odoo/addons/base/models/ir_actions.py", line 984, in _set_resource_ref
    for action in self.filtered(lambda action: action.value_field_to_show == 'resource_ref'):
  File "/data/build/odoo/odoo/models.py", line 6128, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/odoo/models.py", line 6128, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/data/build/odoo/odoo/addons/base/models/ir_actions.py", line 984, in <lambda>
    for action in self.filtered(lambda action: action.value_field_to_show == 'resource_ref'):
  File "/data/build/odoo/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/odoo/models.py", line 4893, in _compute_field_value
    fields.determine(field.compute, self)
  File "/data/build/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/data/build/odoo/odoo/addons/base/models/ir_actions.py", line 964, in _compute_value_field_to_show
    if action.update_field_id.ttype in ('many2one', 'many2many'):
  File "/data/build/odoo/odoo/fields.py", line 2907, in __get__
    return super().__get__(records, owner)
  File "/data/build/odoo/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
  File "/data/build/odoo/odoo/models.py", line 3795, in _fetch_field
    self.fetch(fnames)
  File "/data/build/odoo/odoo/models.py", line 3845, in fetch
    fetched = self._fetch_query(query, fields_to_fetch)
  File "/data/build/odoo/odoo/models.py", line 3937, in _fetch_query
    self.env.cr.execute(query.select(*sql_terms))
  File "/data/build/odoo/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "v"
LINE 1: ...M "ir_act_server" WHERE ("ir_act_server"."id" IN ('v', 'i', ...
                                                             ^


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://67532705-17-0-all.runbot134.odoo.com/web/assets/8c51248/web.assets_web.min.js:2888:163)
        at XMLHttpRequest.<anonymous> (https://67532705-17-0-all.runbot134.odoo.com/web/assets/8c51248/web.assets_web.min.js:2892:13)
```

**Comment by jpp-odoo** [comment]
Hi,

Thank you for reporting the issue, unfortunately I wasn't able to reproduce your issue in a local db or in runbot. Could you please make a video that reproduce the issue (ideally on https://runbot.odoo.com/) to be sure I'm following the steps correctly to reproduce it?

Thank you,

**Comment by hoangtrann** [comment]
@jpp-odoo runbot doesn't allow me to create Server Actions so I go to demo.odoo.com instead. Please look into https://www.loom.com/share/c263c349d11541afb41d6852491c35e2?sid=f6b7197c-ea8d-4f99-b06a-300828c687f0

I proposed a PR to fix the issue btw

**Comment by jpp-odoo** [comment]
@hoangtrann Thanks for the video, I'm going to check the video and the PR.
