### ISSUE TITLE
[16.0] module: product.template - product.product cursor already closed

### ISSUE THREAD

**Issue by LucaWebDev** [odoo/odoo#179391]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Summary:
The stock_call function in Odoo triggers a PostgreSQL cursor issue every time it is executed. The function is responsible for fetching data from the product.template and product.product models, processing it, and then uploading creates csv file in memory. The problem likely stems from how the PostgreSQL cursor is being managed in combination with large datasets and multiple search and search_read operations.

Steps to Reproduce:
Run the stock_call function, which:
- Queries the product.template model to fetch all product templates.
- For each template, queries the product.product model to retrieve variant information.
- Processes the retrieved data and creates csv file in memory.

Expected Behavior the function should:
- Successfully iterate over the product.template data.
- Query the product.product model to fetch variants for each template.
- Upload the processed data to file in memory.

Actual Behavior:
- PostgreSQL raises a cursor-related issue during the execution of the function, especially when querying large datasets or performing consecutive search/search_read operations.
- The cursor might be getting exhausted, or the connection to the database might be dropped, especially in environments with large datasets.

My function:
```
    def stock_call(self):
        cron_job = self.get_value_from_sys_param('softway.stock.job')
        print('VALORE CRON JOB', cron_job)

        # Importazione dei moduli necessari
        product_template_model = self.env['product.template']
        product_variant_model = self.env['product.product']
        stock_quant_model = self.env['stock.quant']
        stock_move_model = self.env['stock.move']
        
        campi = ['product_code', 'product_brand', 'product_quantity', 'product_disponibility', 'product_ead']
        uploader = FTPUploader('impexp.softway.it', 'MotoMorini', 'swLM-2020z')

        data_array = []
        product_template_data = product_template_model.search([('id','!=', False)]) # prodotto vero a cui appartiene la variante
        
        count = 0
        for product in product_template_data:
            count += 1
            print(f'Total: {len(product_template_data)} Resolved: {count}')
            product_variant_data = product_variant_model.search_read( [('product_tmpl_id', '=', product[0]['id'])], ['product_tmpl_id','codice_pantera','qty_available'])
            list_of_values = {
                'product_code': product_variant_data[0].get('codice_pantera'),
                'product_brand': 'brand_da_definire',
                'product_quantity': product_variant_data[0].get('qty_available'),
                'product_disponibility': 'numero_da_definire',
                'product_ead': 'data_da_definire'
            }

            uploader.write_memory_file([list_of_values], campi)
 ```

### Log Output

```shell
The error message relates to PostgreSQL cursor exhaustion:

Traceback (most recent call last):
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/tools/safe_eval.py", line 391, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "ir.actions.server(613,)", line 1, in <module>
  File "/home/mastertoor/odoo/odoo16/addons/custom/boroni-addons/softway/models/cron_demo.py", line 409, in cron_demo_method
    self.stock_call()
  File "/home/mastertoor/odoo/odoo16/addons/custom/boroni-addons/softway/models/cron_demo.py", line 368, in stock_call
    product_variant_data = product_variant_model.search_read( [('product_tmpl_id', '=', product[0]['id'])], ['product_tmpl_id','codice_pantera','qty_available'])
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/models.py", line 5038, in search_read
    result = records.read(fields, **read_kwargs)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/models.py", line 3000, in read
    self._read(stored_fields)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/models.py", line 3287, in _read
    result += cr.fetchall()
psycopg2.InterfaceError: cursor already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/http.py", line 2061, in __call__
    response = request._serve_db()
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/http.py", line 1649, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/http.py", line 1676, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/http.py", line 1880, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/http.py", line 732, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/mastertoor/odoo/odoo16/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/mastertoor/odoo/odoo16/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/addons/base/models/ir_cron.py", line 103, in method_direct_trigger
    cron.with_user(cron.user_id).with_context({'lastcall': cron.lastcall}).ir_actions_server_id.run()
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/addons/base/models/ir_actions.py", line 675, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/addons/base/models/ir_actions.py", line 545, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "/home/mastertoor/odoo/odoo16/odoo/odoo/tools/safe_eval.py", line 405, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'psycopg2.InterfaceError'>: "cursor already closed" while evaluating
'model.with_context(cron_job_stock=True).cron_demo_method()'
```

**Comment by gdgellatly** [comment]
This is a custom module not an Odoo developed one, probably best to talk to the authors.
