### ISSUE TITLE
Blog Rss Feed Contents

### ISSUE THREAD

**Issue by Fuchur777** [odoo/odoo#17942]
Impacted versions: 10 CE Website / Blog

Steps to reproduce:
Go to blog, click RSS logo

Current behavior:
Not including contents of the blog. Only Summary which is the "subtitle" of the blog

Expected behavior:
To also be able to read the intro or full blog in an RSS reader

This could be the content of post.teaser or post.content however these are the full html which doesnt work well.

**Comment by Yenthe666** [comment]
@JKE-be can you give feedback please?

**Comment by JKE-be** [comment]
Yes, in v10 teaser has appear... we should use it...

I have a local diff , I will push it asap

```diff
--- addons/website_blog/views/website_blog_templates.xml
+++ addons/website_blog/views/website_blog_templates.xml
@@ -557,7 +557,7 @@
         <link t-att-href="'%s%s' % (base_url, post.website_url)"/>
         <id t-esc="'%s%s' % (base_url, post.website_url)"/>
         <author><name t-esc="post.sudo().author_id.name"/></author>
-        <summary t-esc="post.subtitle"/>
+        <summary t-esc="post.teaser"/>
         <updated t-esc="post.write_date.replace(' ', 'T') + 'Z'"/>
     </entry>
 </feed>

```

**Comment by Fuchur777** [comment]
![image](https://user-images.githubusercontent.com/798891/27740856-8f0b4896-5db3-11e7-9d58-9c56ceaa5592.png)
roblem with post.teaser and post.content is that it parses wrong in the feed.

See here and example with teaser:
https://ut4fp.org/blog/1/feed

**Comment by JKE-be** [comment]
thx ;)  good catch

```diff
diff --git odoo/addons/base/module/module.py odoo/addons/base/module/module.py
index 4d3e859..14827c6 100644
~/src/odoo/odoo [10.0 ↓5|✚4…1]$ git diff
diff --git addons/website_blog/controllers/main.py addons/website_blog/controllers/main.py
index 23af55a..040c9ac 100644
--- addons/website_blog/controllers/main.py
+++ addons/website_blog/controllers/main.py
@@ -178,6 +178,7 @@ class WebsiteBlog(http.Controller):
         v['blog'] = blog
         v['base_url'] = request.env['ir.config_parameter'].get_param('web.base.url')
         v['posts'] = request.env['blog.post'].search([('blog_id','=', blog.id)], limit=min(int(limit), 50))
+        v['html2plaintext'] = html2plaintext
         r = request.render("website_blog.blog_feed", v, headers=[('Content-Type', 'application/atom+xml')])
         return r
 
diff --git addons/website_blog/views/website_blog_templates.xml addons/website_blog/views/website_blog_templates.xml
index f6f3513..f6f5136 100644
--- addons/website_blog/views/website_blog_templates.xml
+++ addons/website_blog/views/website_blog_templates.xml
@@ -557,7 +557,7 @@
         <link t-att-href="'%s%s' % (base_url, post.website_url)"/>
         <id t-esc="'%s%s' % (base_url, post.website_url)"/>
         <author><name t-esc="post.sudo().author_id.name"/></author>
-        <summary t-esc="post.subtitle"/>
+        <summary t-esc="html2plaintext(post.teaser)"/>
         <updated t-esc="post.write_date.replace(' ', 'T') + 'Z'"/>
     </entry>
 </feed>

```

**Comment by Fuchur777** [comment]
@JKE-be tried the changes but doesnt lead to desired effect. Blog gives update error.

`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/addons/base/module/module.py", line 527, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo-server/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 333, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 628, in _tag_record
    model = self.env[rec_model]
  File "/opt/odoo/odoo-server/odoo/api.py", line 752, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 170, in __getitem__
    return self.models[model_name]
ParseError: "blog.blog" while parsing /opt/odoo/odoo-server/addons/website_blog/data/website_blog_data.xml:4, near
<record id="blog_blog_1" model="blog.blog">
            <field name="name">Our Blog</field>
            <field name="subtitle">Get in touch with us</field>
        </record>`

**Comment by JKE-be** [comment]
@Fuchur777 

You can just take the last version, It has been pushed in commit: https://github.com/odoo/odoo/commit/404033daf3e6828c2e0645a71f7da9bd2a80bf40

Test here: http://242094-10-0-15da33-all.runbot10.odoo.com/blog/1/feed

**Comment by Fuchur777** [comment]
@JKE-be Test looks good, let me try!

**Comment by Yenthe666** [comment]
Initial problem was fixed in https://github.com/odoo/odoo/commit/404033daf3e6828c2e0645a71f7da9bd2a80bf40 so this can be closed.
