### ISSUE TITLE
500 Internal error on giving Settings right to users.

### ISSUE THREAD

**Issue by satyakishores** [odoo/odoo#17997]
I have modified menu items in odoo10. After that users with the settings rights are getting 500 Internal Server error. Users without the settings access are able to access the web. I can access the Settings by adding the ?debug  in the url.

ERROR odoo_db werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 440, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/models/ir_http.py", line 17, in webclient_rendering_context
    'menu_data': request.env['ir.ui.menu'].load_menus(request.debug),
  File "<decorator-gen-218>", line 2, in load_menus

  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_tour/models/ir_ui_menu.py", line 35, in load_menus
    _find_subtree(menu_root, menu_id)['xmlid'] = menu_xmlid
TypeError: 'NoneType' object does not support item assignment

Please help.

**Comment by Yenthe666** [comment]
Hi @satyakishores,

This looks like a bug in your custom development.
The Github issue tracker however is only for bugs/issues in the official Odoo code, not in personal development.
Please ask this question on the official help forums where plenty of people can help you (http://odoo.com/help).
I'm closing this as it is a question about custom development (and there isn't even code in your topic).

Regards,
Yenthe

**Comment by satyakishores** [comment]
ok @Yenthe666 Thanks.

**Comment by MEmmanuel** [comment]
Hi @satyakishores, did you find where the problem came from or a solution ?
I'm in a totally different situation but I have the same traceback coming from nowhere.

@Yenthe666 I think, although the error probably come from custom development, that the error message should be more meaningful to allow debug. This traceback arise for me after some merges and keeps coming even if I rollback. I'm lost...
