### ISSUE TITLE
[10.0] Not dependent modules bug out functionality (or at least testing)

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#18002]
Impacted versions:
10.0

Steps to reproduce:

An example would be like this: install module `sale`. Create a module that depends only on `product` module. Make a test (in that module) that uses `copy` method for `product.product` record. For example `self.browse_ref('product_ext_id').copy()`.

**Current behavior:**

You would get something like this:

```python
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ERROR: test_code_unique_3 (odoo.addons.product_code_unique.tests.test_product_code_uniqueness.TestProductCodeUniqueness)
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` Test product with with unique code.
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: Traceback (most recent call last):
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/source/jurga/product_code_unique/tests/test_product_code_uniqueness.py", line 38, in test_code_unique_3
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     product2 = self.product_1.copy()
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/addons/product/models/product.py", line 358, in copy
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     return super(ProductProduct, self).copy(default=default)
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/models.py", line 4392, in copy
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     new = self.with_context(lang=None).create(vals)
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/addons/product/models/product.py", line 316, in create
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/addons/mail/models/mail_thread.py", line 228, in create
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     thread = super(MailThread, self).create(values)
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/models.py", line 3830, in create
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     record = self.browse(self._create(old_vals))
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/models.py", line 3891, in _create
2017-07-04 10:57:46,811 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     parent_id = self.env[parent_model].create(parent_vals).id
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/addons/product/models/product_template.py", line 265, in create
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     template = super(ProductTemplate, self).create(vals)
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/addons/mail/models/mail_thread.py", line 228, in create
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     thread = super(MailThread, self).create(values)
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/models.py", line 3830, in create
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     record = self.browse(self._create(old_vals))
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/models.py", line 3925, in _create
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/sql_db.py", line 141, in wrapper
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     return f(self, *args, **kwargs)
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `   File "/home/oerp/odoo10/odoo/odoo/sql_db.py", line 218, in execute
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: `     res = self._obj.execute(query, params)
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` IntegrityError: null value in column "sale_line_warn" violates not-null constraint
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` DETAIL:  Failing row contains (45, 0, 320.00, null, 1, 0, 1, 1, null, null, 2017-07-04 10:57:46.775553, 1, t, t, null, 1, 1, Color: White
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` Capacity: 16GB
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` Connectivity: Wifi
2017-07-04 10:57:46,812 2408 ERROR 1_portal_cart odoo.addons.product_code_unique.tests.test_product_code_uniqueness: ` Beautiful 7.9-inc..., null, null, 2017-07-04 10:57:46.775553, t, 6, iPad Mini, f, consu, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).
```

Expected behavior:
As you can see it does not find field `sale_line_warn`. Well that is kind of expected, because it is added on module `sale`, which my custom module does not depend on. But the problem is, that field is marked as `required` on database level (I mean in code it is marked `required=True`. So this causes an issue. **When my module is tested, it is not aware of that field (even if `sale` is installed), but database expects it regardless.**. **So I can't set that field (when running my module tests), but it must be set**.

Is there a workaround? I know I can depend on module `sale`, then it should work, but my module logic should depend only on `product` module. Depending on `sale` is kind of ridiculous, when it actually modifies only `product` module functionality.

**Comment by lekhnath** [comment]
Experiencing similar kind of issue here. I've dependency on 'product' addon only so that I could add some products from xml file but I've installed the whole 'sale' addon. When I tried to add some product records from xml I get error that says **null value in column "sale_line_warn" violates not-null constraint**. Even if I provide some value for that column(sale_line_warn) I get another error message that says **KeyError: 'sale_line_warn'**. I am also excited to know about the work around for this kind of issue if there exists any.

**Comment by pedrobaeza** [comment]
This is a know limitation on the framework, but you have an easy solution: put in your test code following lines:
```python
class Test(common...Case):
    post_install = True
    at_install = True
    ...
```
With this, your test is executed at the end of the modules loading, not having that errors.

Closing as know limitation, but with a workaround.

**Comment by alexis-via** [comment]
On Odoo v14, the workaround is different:

```
from odoo.tests.common import TransactionCase
from odoo.tests import tagged

@tagged('post_install', '-at_install')
class TestMyClass(TransactionCase):
```

**Comment by juancarlosonate-tecnativa** [comment]
the same issue with `sale_line_warn` in v18, `@tagged`, resolves it

**Comment by alexis-via** [comment]
yes, it's stupid to have sale_line_warn as required=True, but hopefully the workaround exists
