### ISSUE TITLE
[10.0] Bug (500) when customer saving own contacts in the portal

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#18235]
**Impacted versions:**
10

**Steps to reproduce:**
After the customer made a purchase, he can not save own contacts in the portal.
Page: 
`/my/account`

![screenshot_10](https://user-images.githubusercontent.com/11208423/28208482-7f2c841a-6896-11e7-9be9-699ba9daad23.png)

**Current behavior:**
In the log, I get this error:

2017-07-13 20:54:46,356 22285 ERROR marker1 odoo.addons.website.models.ir_http: 500 Internal Server Error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/var/lib/odoo/addons/10.0/pr1_url_redirect/controllers/override.py", line 211, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/website_portal/controllers/main.py", line 67, in details
    error, error_message = self.details_form_validate(post)
  File "/usr/lib/python2.7/site-packages/odoo/addons/website_portal_sale/controllers/main.py", line 184, in details_form_validate
    if 'vat' in partner and (data['vat'] or False) != (partner.vat or False):
KeyError: 'vat'

Expected behavior:
The client must successfully save his data and go to the page:
`/my/home`

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @collex100,

Thank you for your report.
I can't seem to reproduce this on the latest Odoo source code, could you make a video please? (CC @JKE-be)

Regards,
Yenthe

**Comment by collex100** [comment]
Hi @Yenthe666,
Ok, I'll try to make a video.

**Comment by online-odoo** [comment]
Hi Colkex,

Please update your python code to last version.

I have fixed this bug 2 week ago: https://github.com/odoo/odoo/commit/4322d96a0cad9eb67c74bb60ad260473cdb4891b

Best regards

**Comment by JKE-be** [comment]
Hi @collex100

Please update your python code to the last version.

I have fixed this bug 2 weeks ago: 4322d96

Best regards

**Comment by collex100** [comment]
Thank you @JKE-be and @Yenthe666 ! I updated the code, the error disappeared. Now, it seems to be working properly.
