### ISSUE TITLE
odoo odoo.modules.registry: Failed to load registry

### ISSUE THREAD

**Issue by hubeizys** [odoo/odoo#18248]
Impacted versions:10.0

Steps to reproduce:  
1.  run cmd     ` /usr/bin/python /usr/bin/odoo --config /etc/odoo/odoo.conf`
2.  run local   cmd   `wget localhost:8069`

Current behavior: load cvs file error and  cant start progam

Expected behavior: 

very long . . ..  

>  2017-07-15 09:17:34,416 3490 INFO ? odoo: Odoo version 10.0-20170712
2017-07-15 09:17:34,417 3490 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2017-07-15 09:17:34,417 3490 INFO ? odoo: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/10.0', u'/usr/lib/python2.7/dist-packages/odoo/addons']
2017-07-15 09:17:34,417 3490 INFO ? odoo: database: odoo@127.0.0.1:5432
2017-07-15 09:17:34,423 3490 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-07-15 09:17:40,168 3490 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2017-07-15 09:17:40,426 3490 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-07-15 09:17:40,427 3490 INFO ? odoo.addons.report.models.report: Wkhtmltopdf seems to be broken.
2017-07-15 09:17:40,551 3490 INFO ? odoo.http: HTTP Configuring static files
2017-07-15 09:17:40,769 3490 INFO odoo odoo.modules.loading: loading 1 modules...
2017-07-15 09:17:41,006 3490 INFO odoo odoo.modules.registry: module base: creating or updating database tables
2017-07-15 09:17:42,909 3490 INFO odoo odoo.modules.loading: loading base/res/res.lang.csv
2017-07-15 09:17:43,447 3490 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 280, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 839, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 895, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading base failed: file base/res/res.lang.csv could not be processed:
 Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\nAmharic / \u12a0\u121d\u1203\u122d\u129b\n10\n11\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\nArabic / \u0627\u0644\u0652\u0639\u064e\u0631\u064e\u0628\u064a\u0651\u0629\n9\n10\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\nBulgarian / \u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a\n12\n13\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\nCatalan / Catal\xe0\n15\n16\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\n%Y\u5e74%m\u6708%d\u65e5\n2\n3\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\n%Y\u5e74%m\u6708%d\u65e5 %A\n2\n3\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\n%Y\u5e74%m\u6708%d\u65e5\n2\n3\nordinal not in range(128)', None)
Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u'Error while validating constraint\n\nascii\n\xa0\n0\n1\nordinal not in range(128)', None)

Video/Screenshot link (optional):

![tim 20170715173328](https://user-images.githubusercontent.com/3355846/28238353-74a5c404-6984-11e7-897e-65b0e03937fa.jpg)

**Comment by q710245300** [comment]
hi ,I face same question like it . so can you tell me how do you  fix this error finally?

**Comment by hubeizys** [comment]
mongo charset error.       its need utf8 to work



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            朱云松
                            
                            
                                
                                    邮箱：124296140@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
            On 02/17/2018 20:19, q710245300 wrote: hi ,I face same question like it . so can you tell me how do you  fix this error finally?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/odoo/odoo","title":"odoo/odoo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/odoo/odoo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@q710245300 in #18248: hi ,I face same question like it . so can you tell me how do you  fix this error finally?"}],"action":{"name":"View Issue","url":"https://github.com/odoo/odoo/issues/18248#issuecomment-366437644"}}}
