### ISSUE TITLE
[17.0] Error: `odoo.modules.loading: Database XXXXXXX not initialized, you can force it with -i base` When Using Non-Default `POSTGRES_DB` in Dockerized Odoo

### ISSUE THREAD

**Issue by WildfootW** [odoo/odoo#182551]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

**Steps to reproduce**:

1. **Set up a PostgreSQL container with a custom database name** (not `postgres`):

    ```bash
    docker run -d \
      -e POSTGRES_USER=odoo \
      -e POSTGRES_PASSWORD=odoo \
      -e POSTGRES_DB=odoo1234567 \  # Custom database name
      --name db \
      postgres:15
    ```

2. **Run the Odoo container without specifying a database name**:

    ```bash
    docker run -p 8069:8069 \
      --name odoo \
      --link db:db \
      -t odoo
    ```

3. **Access Odoo via a web browser** at `http://localhost:8069`.

**Current behavior**:

- The Odoo container logs show an error upon accessing the web interface:

    ```
    ERROR ? odoo.modules.loading: Database odoo1234567 not initialized, you can force it with `-i base`
    ERROR odoo1234567 odoo.http: Exception during request handling.
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/odoo/http.py", line 1781, in _serve_db
        return service_model.retrying(self._serve_ir_http, self.env)
      ...
    KeyError: 'ir.http'
    ```

- The web interface returns a **500 Internal Server Error**, and the database selector or setup wizard does **not** appear.

**Expected behavior**:

- Odoo should start without errors, and upon accessing `http://localhost:8069`, the **database selector or setup wizard** should be displayed, allowing the user to create and initialize a new database.

**Additional details**:

- **Using the default `POSTGRES_DB=postgres` works as expected**. When the PostgreSQL container is started with `POSTGRES_DB=postgres`, and Odoo is run without specifying a database name, accessing `http://localhost:8069` brings up the database selector, and no errors are logged.

- **Entrypoint Command Verification**: I modified the `entrypoint.sh` script to add an `echo` before executing the Odoo process. Here is the updated entrypoint command:

    ```bash
    echo "ENTRYPOINT Executing: odoo $@ ${DB_ARGS[@]}"
    exec odoo "$@" "${DB_ARGS[@]}"
    ```

    When I start the container, the logs confirm that the entrypoint does not pass any `db_name` parameter:

    ```
    ENTRYPOINT Executing: odoo  --db_host 172.17.0.2 --db_port 5432 --db_user odoo --db_password odoo
    2024-10-06 15:30:36,649 1 INFO ? odoo: Odoo version 17.0-20240924
    2024-10-06 15:30:36,649 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
    2024-10-06 15:30:36,649 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/17.0', '/mnt/extra-addons']
    2024-10-06 15:30:36,649 1 INFO ? odoo: database: odoo@172.17.0.2:5432
    2024-10-06 15:30:36,738 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
    2024-10-06 15:30:36,891 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 279072b68209:8069
    2024-10-06 15:30:47,615 1 ERROR ? odoo.modules.loading: Database odoo1234567 not initialized, you can force it with `-i base`
    ```

    As you can see, the executing arguments do not pass the database name (`odoo1234567` in this case). It seems that Odoo searches through the available databases and attempts to connect to `odoo1234567`, which results in the error stating that it is not initialized. However, if I create a database named `postgres` in the PostgreSQL container, this behavior does not occur.

- **Workaround**: Running Odoo with `-i base` initializes the database, but it bypasses the setup wizard, preventing the selection of country code and other initial configurations, which is inconvenient.

    ```bash
    docker run -p 8069:8069 \
      --name odoo \
      --link db:db \
      -t odoo \
      odoo -i base
    ```

**References**:

- Similar issue reported: [Database 'db' not initialized, you can force it with `-i base`](https://github.com/odoo/odoo/issues/27447)
- [Selecting a specific Odoo country from the command line](https://www.odoo.com/forum/help-1/select-specific-odoo-country-from-command-line-152127)

**Possible Cause**:

- Odoo may be detecting the existence of the non-default database (`odoo1234567`) and, without explicit instruction, attempts to connect to it. Since it's not initialized, it throws an error instead of prompting for database creation.?

### Log Output

```shell
2024-10-06 23:30:36 2024-10-06 15:30:36,649 1 INFO ? odoo: Odoo version 17.0-20240924 
2024-10-06 23:30:36 2024-10-06 15:30:36,649 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2024-10-06 23:30:36 2024-10-06 15:30:36,649 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/17.0', '/mnt/extra-addons'] 
2024-10-06 23:30:36 2024-10-06 15:30:36,649 1 INFO ? odoo: database: odoo@172.17.0.2:5432 
2024-10-06 23:30:36 2024-10-06 15:30:36,738 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2024-10-06 23:30:36 2024-10-06 15:30:36,891 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 279072b68209:8069 
2024-10-06 23:30:47 2024-10-06 15:30:47,615 1 ERROR ? odoo.modules.loading: Database odoo1234567 not initialized, you can force it with `-i base` 
2024-10-06 23:30:47 2024-10-06 15:30:47,615 1 INFO ? odoo.modules.registry: Registry loaded in 0.008s 
2024-10-06 23:30:47 2024-10-06 15:30:47,616 1 ERROR odoo1234567 odoo.http: Exception during request handling. 
2024-10-06 23:30:47 Traceback (most recent call last):
2024-10-06 23:30:47   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1783, in _serve_db
2024-10-06 23:30:47     return service_model.retrying(self._serve_ir_http, self.env)
2024-10-06 23:30:47   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
2024-10-06 23:30:47     result = func()
2024-10-06 23:30:36 ENTRYPOINT Executing: odoo  --db_host 172.17.0.2 --db_port 5432 --db_user odoo --db_password odoo
2024-10-06 23:30:47   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1795, in _serve_ir_http
2024-10-06 23:30:47     ir_http = self.registry['ir.http']
2024-10-06 23:30:47   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 213, in __getitem__
2024-10-06 23:30:47     return self.models[model_name]
2024-10-06 23:30:47 KeyError: 'ir.http'
```

**Comment by WildfootW** [comment]
Okay, after spending a lot of time on this strange issue and narrowing down the possible causes (I originally suspected my installation steps during the source install), I finally found out that someone has mentioned this issue before: https://github.com/lefilament/ansible_role_odoo_docker/issues/7.

However, this behavior is still quite strange, and the error message is not intuitive. It doesn't clearly explain why Odoo is attempting to connect to an uninitialized database when no `db_name` is passed, especially when using a non-default database name.
