### ISSUE TITLE
[14.0 -> 18.0] google_gmail: SMTPServerDisconnected errors

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#182777]
### Odoo Version

- [X] 16.0
- [X] 17.0
- [X] 18.0
- [X] Other (14.0, 15.0)

### Steps to Reproduce

This is a race condition that's hard to reproduce but I get it around 3 times a month using Odoo version 14.0

## Current behaviour

* Install and configure google_gmail module
* Send emails
* You get this exception and mail will be in error

## Expected behaviour:

* no error raises
* all email send from the first call

## Log Output

```shell
Exception:
Traceback (most recent call last):
[...]
  File "/usr/local/lib/python3.9/site-packages/odoo/sql_db.py", line 456, in commit
    self.postcommit.run()
  File "/usr/local/lib/python3.9/site-packages/odoo/tools/misc.py", line 1201, in run
    func()
  File "/var/lib/odoo/addons-contrib/mail/models/mail_thread.py", line 2391, in send_notifications
    env['mail.mail'].browse(email_ids).send()
  File "/var/lib/odoo/addons-contrib/mail/models/mail_mail.py", line 281, in send
    smtp_session.quit()
  File "/usr/local/lib/python3.9/smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "/usr/local/lib/python3.9/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/local/lib/python3.9/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/local/lib/python3.9/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

# Analysis

Here is my personal analysis. I believes there is two matters:

## Token lifecycle

Using `google_gmail` module, a token is generated to access to the smtp server, this token is valid for 1 hour once generated.

I believe the race condition happens while connecting to the server when token is valid at the beginning of the transaction but not anymore while connecting to gmail server.

background probable are probably  Clock synchronization or just the time execution between token age check and connecting to google servers.

It's not a big matter because Odoo manage a fallback that should send the email the next run.

As far as I test, if session is started before token expire and the token expire after, it's not a big matter.

Anyway I would suggest to implement a threshold to force create a new token if the token expires in 3s to mitigate this matter.

this is the the part of the code checking the access token expired or not from `odoo.addons.google_gmail.models.google_gmail_mixin`

```python
        now_timestamp = int(time.time())
        if not self.google_gmail_access_token \
           or not self.google_gmail_access_token_expiration \
           or self.google_gmail_access_token_expiration < now_timestamp:
```

## Quitting a non open session

In such condition the smtp_session variable seems to be set but the connection is not alive, would suggest to try/catch the quit or run a noop() operation to check if the session is still valid before quitting the session.

Here is the copy of the `send` method from `odoo.addons.mail.models.mail_mail` from branch 14.0
```python
    def send(self, auto_commit=False, raise_exception=False):
        """ Sends the selected emails immediately, ignoring their current
            state (mails that have already been sent should not be passed
            unless they should actually be re-sent).
            Emails successfully delivered are marked as 'sent', and those
            that fail to be deliver are marked as 'exception', and the
            corresponding error mail is output in the server logs.

            :param bool auto_commit: whether to force a commit of the mail status
                after sending each mail (meant only for scheduler processing);
                should never be True during normal transactions (default: False)
            :param bool raise_exception: whether to raise an exception if the
                email sending process has failed
            :return: True
        """
        for server_id, batch_ids in self._split_by_server():
            smtp_session = None
            try:
                smtp_session = self.env['ir.mail_server'].connect(mail_server_id=server_id)
            except Exception as exc:
                if raise_exception:
                    # To be consistent and backward compatible with mail_mail.send() raised
                    # exceptions, it is encapsulated into an Odoo MailDeliveryException
                    raise MailDeliveryException(_('Unable to connect to SMTP Server'), exc)
                else:
                    batch = self.browse(batch_ids)
                    batch.write({'state': 'exception', 'failure_reason': exc})
                    batch._postprocess_sent_message(success_pids=[], failure_type="SMTP")
            else:
                self.browse(batch_ids)._send(
                    auto_commit=auto_commit,
                    raise_exception=raise_exception,
                    smtp_session=smtp_session)
                _logger.info(
                    'Sent batch %s emails via mail server ID #%s',
                    len(batch_ids), server_id)
            finally:
                if smtp_session:
                    smtp_session.quit()
```

**Comment by petrus-v** [comment]
It's time to close this as well special thanks to @reth-odoo for its time to review and forwords this patch from v16 to master 🥳
