### ISSUE TITLE
[17.0] base: TypeError: ProductPricelist.search_count() got an unexpected keyword argument 'limit'

### ISSUE THREAD

**Issue by spyker5** [odoo/odoo#183166]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Sometimes when I try to open some module, in this case is Pricelist, the backend return the following error. It happened with res.partner and sale.order already. A workaround that worked for me was override the web_search_read. Passing limit=None solves the problem.
```
@api.model
    def web_search_read(self, domain, specification, offset=0, limit=None, order=None, count_limit=None):
        limit = None
        return super(VZSaleOrder, self).web_search_read(domain, specification, offset, limit, order, count_limit)
```

### Log Output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 1063, in onchange
    record._apply_onchange_methods(field_name, result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6932, in _apply_onchange_methods
    res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/res_config_settings.py", line 49, in _onchange_group_sale_pricelist
    active_pricelist = self.env['product.pricelist'].sudo().search_count(
TypeError: ProductPricelist.search_count() got an unexpected keyword argument 'limit'
```

**Comment by duong77476-viindoo** [comment]
No, i'm guessing you might have some custom addons that ovveride the search count i guess,
the code at odoo/models.py line 1582 with method search_count the argument for limit is there
