### ISSUE TITLE
[18.0] Docker container: user odoo is problematic

### ISSUE THREAD

**Issue by Schweineschwarte** [odoo/odoo#183106]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

I rollout Odoo 18.0 via Ansible and Docker.
Current behaviour:
If I open the website I get an error:
```
"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
```
I looked into the Docker log of the odoo-container and I got this error:
`"PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local'"`

The folder in the container is a Docker volume on the host system (an Ubuntu 22.04 Server).
I identifyed the problem as the different UIDs and GIDs of the container user (named odoo) and the not existing odoo-user on the host. But I can not create the missing odoo-user on the host, because he needs the same UID and GID (Docker use the UID and GID to access the volume from the container). In the container, the UID and the GID of the user odoo is uid=100(odoo) gid=101(odoo) groups=101(odoo). That's awful, because my host Ubuntu used this IDs for system applications. The UID 100 is reserved for _apt and the GID 101 is reserved for systemd-journal. If I set the permissions of volumes on the host to _apt and systemd-journal:
```
chown -R _apt:systemd-journal /mnt/odoo-daten/addons/
chown -R _apt:systemd-journal /mnt/odoo-daten/config/
chown -R _apt:systemd-journal /mnt/odoo-daten/odoo-web-daten/
```

Odoo works. But I think this is a dirty solution! First, as far as I am informed, the UID range between 100-999 is dynamically and can be changed.* So, my configuration can be invalid, if a different user ID is available depending on the available user ID in the range at the time of creation. Furthermore, I think to use UIDs and GIDs from other system applications is problematic on a security view, because it invalidate the permissons concept.

With the information I have, I think the container user should be changed.

* [https://www.baeldung.com/linux/user-ids-reserved-values#the-application-users](https://www.baeldung.com/linux/user-ids-reserved-values#the-application-users)

Steps to reproduce:
1. Install an Ubuntu 22.04 Server.
2. Use in your Docker configuration volumes for the directories /var/lib/odoo and /etc/odoo
3. Rollout Odoo 18.0 with Docker
4. Open the odoo website from the container in the browser
5. Check your Docker logs of the odoo container to get the error message.
6. Get the IDs of odoo container user with: `docker exec -it <container-name> id odoo`
7. Get the system applications of the host, which use the IDs of the odoo container user: `grep ':<UID>:' /etc/passwd` and `grep ':<GID>:' /etc/group`
8. Change the permissions of the volume directories to this system applications.
```
chown -R <host user>:<host group> <your path to volume for /var/lib/odoo>
chown -R <host user>:<host group> <your path to volume for /etc/odoo>
```
9. Restart Odoo Docker container: docker restart <container-name>
10. Open Odoo website and check if it works now.

Expected behaviour:
No permission problems with the usage of Docker volumes.

### Log Output

```shell
2024-10-10 09:17:32,604 1 INFO ? odoo: Odoo version 18.0-20241007 
2024-10-10 09:17:32,605 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons'] 
2024-10-10 09:17:32,605 1 INFO ? odoo: database: odoo@odoo-db:5432 
Warn: Can't find .pfb for face 'Courier'
2024-10-10 09:17:32,731 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2024-10-10 09:17:32,737 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltoimage binary at /usr/local/bin/wkhtmltoimage 
2024-10-10 09:17:32,839 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on b733fc9b4f65:8069 
2024-10-10 09:17:47,180 1 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2356, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1454, in _get_session_and_dbname
    if not sid or not root.session_store.is_valid_key(sid):
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2280, in session_store
    path = odoo.tools.config.session_dir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 772, in session_dir
    os.makedirs(d, 0o700)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
2024-10-10 09:17:47,181 1 INFO ? werkzeug: 192.168.3.64 - - [10/Oct/2024 09:17:47] "GET / HTTP/1.1" 500 - 0 0.000 0.002
2024-10-10 09:18:01,345 1 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2356, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1454, in _get_session_and_dbname
    if not sid or not root.session_store.is_valid_key(sid):
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2280, in session_store
    path = odoo.tools.config.session_dir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 772, in session_dir
    os.makedirs(d, 0o700)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
2024-10-10 09:18:01,345 1 INFO ? werkzeug: 192.168.3.64 - - [10/Oct/2024 09:18:01] "GET /websocket?version=18.0-1 HTTP/1.1" 500 - 0 0.000 0.001
2024-10-10 09:18:14,460 1 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2356, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1454, in _get_session_and_dbname
    if not sid or not root.session_store.is_valid_key(sid):
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2280, in session_store
    path = odoo.tools.config.session_dir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 772, in session_dir
    os.makedirs(d, 0o700)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
2024-10-10 09:18:14,461 1 INFO ? werkzeug: 192.168.3.64 - - [10/Oct/2024 09:18:14] "GET /websocket?version=18.0-1 HTTP/1.1" 500 - 0 0.000 0.001
2024-10-10 09:19:15,512 1 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2356, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in _post_init
    self.session, self.db = self._get_session_and_dbname()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1454, in _get_session_and_dbname
    if not sid or not root.session_store.is_valid_key(sid):
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2280, in session_store
    path = odoo.tools.config.session_dir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 772, in session_dir
    os.makedirs(d, 0o700)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
2024-10-10 09:19:15,512 1 INFO ? werkzeug: 192.168.3.64 - - [10/Oct/2024 09:19:15] "GET /websocket?version=18.0-1 HTTP/1.1" 500 - 0 0.000 0.001
```

**Comment by shaneodoo** [comment]
The error you're encountering appears to be a permissions issue where Odoo is attempting to create a directory (/var/lib/odoo/.local) but is being denied permission by the system.

To resolve this issue, you can try the following steps:

Check the directory permissions: Ensure that the Odoo service has the necessary permissions to write to the /var/lib/odoo directory.

bash

```
sudo chown -R odoo:odoo /var/lib/odoo
sudo chmod -R 700 /var/lib/odoo
```

This will give ownership of the /var/lib/odoo directory to the Odoo user and set the correct permissions.

Verify that Odoo is running under the correct user: If you're running Odoo within a Docker container, ensure that the Odoo process inside the container is running as the correct user (usually odoo). If Odoo is running as root or another user, it might not have access to the necessary directories.

Check the Odoo configuration file: Ensure that the session_dir in the Odoo configuration file (odoo.conf) points to a directory where Odoo has write permissions. If the configuration points to a directory like /var/lib/odoo/.local, but Odoo can't write there, you may want to specify an alternative location like /tmp or another writable directory.

Example configuration change:

```
ini

    [options]
    session_dir = /tmp/odoo_sessions
```

After making the above changes, restart your Odoo instance and check if the issue is resolved.

**Comment by Schweineschwarte** [comment]
As I wrote, Odoo runs within a Docker container as the user odoo. To do `sudo chown -R odoo:odoo /var/lib/odoo` on the host system (Ubuntu 22.04 Server) won't work, because the user odoo does not exist and can not be created, due the trouble of IDs (which is the reason for this issue, see inital comment). **In the Docker container**, the permissions are correct: 
```
docker exec -it odoo ls -l /var/lib/ | grep odoo
drwxr-xr-x 3 odoo odoo 4096 Oct 11 09:24 odoo
```
To work with the odoo.conf is not practical if the configuration directory is used as a Docker volume too. Same problem as /var/lib/odoo. It will be only possible, if /etc/odoo is not accessible as a Docker volume, but then this configuration change is not persistent.

**Comment by pedrobaeza** [comment]
The second comment seems a ChatGPT answer without more interpretation and without knowing the prompt.

**Comment by 0xmex** [comment]
I am encountering the same error on a docker/Portainer installation on Alma Linux 9. Same output, same error.

**Comment by 0xmex** [comment]
I am encountering the same error on a docker/Portainer installation on Alma Linux 9. Same output, same error.
However I've found a "solution": The moment /var/lib/odoo is not being used as a volume on the host system, the installation works. Somehow something is overwriting the write permissions, even if the container folder is being set up with odoo:odoo permission.

**Comment by gdgellatly** [comment]
You don't need to create a user to set permissions. Just set the numbers. e.g. postgres user on docker standard postgres install is 70 so you can chown 70:70 - no need for text.  But setting UID/GID is really a docker issue and long since solved, esp if using ANsible.

**Comment by 0xmex** [comment]
> But setting UID/GID is really a docker issue and long since solved, esp if using ANsible.
Then add the 'correct' way to your documentation. Or add it in your docker-compose.yml. 
The only thing, which truly helped me, was this issue. Hard to believe, that his would be "the wrong way to do things".

**Comment by steffenstolze** [comment]
@Schweineschwarte have you ever found a solution / workaround? I'm running Odoo 18 in AWS ECS Fargate containers with filestore on AWS EFS and the only thing that worked was to to set the EFS Odoo directory owner `gid` and `uid` to `101` and permissions to `775`

**Comment by Schweineschwarte** [comment]
@steffenstolze I only found the workaround, I described in the [first message](https://github.com/odoo/odoo/issues/183106#issue-2578276700).

**Comment by lincoln6delta** [comment]
Setting the directory of the docker volume on the host to the ID/GID of the Odoo user in the container seem to work.

**Comment by wz2b** [comment]
Fastest way to see the problem:
```bash
root@dev:/home/cep# docker run --rm -it odoo:17.0 id -a odoo
uid=101(odoo) gid=101(odoo) groups=101(odoo)

root@dev:/home/cep# docker run --rm -it odoo:18.0 id -a odoo
uid=100(odoo) gid=101(odoo) groups=101(odoo)
```

The main directory that caused me grief was /var/lib/odoo/.local so a quick chown to odoo:odoo on that (recursively) solved the problem, then `find / -uid 101' inside your container (not the temporary one I created above) to see if there are others.

**Comment by wz2b** [comment]
Someone on reddit told me that changing UIDs of a released package is a "skills issue" - that's right, he addressed the problem by insulting me!  So anybody commenting on thread should rest assured that guy says this issue is all in your head.

For anybody curious about the actual root cause, it is that the docker image for 18.0 is built on ubuntu:noble and 17 was built on ubuntu:jammy.  I can prove this by comparing [Dockerfile 17](https://[raw.githubusercontent.com/odoo/docker/master/17.0/Dockerfile) and [Dockerfile 18.0](https://github.com/odoo/odoo/blob/18.0/debian/postinst) (first line) then look at those base images directly:

```
    chrisp@CYBERPC:~$ docker run --rm ubuntu:noble bash -c 'grep -e :100: -e :101: /etc/passwd'
    chrisp@CYBERPC:~$ docker run --rm ubuntu:jammy bash -c 'grep -e :100: -e :101: /etc/passwd'
    _apt:x:100:65534::/nonexistent:/usr/sbin/nologin
```

so 'jammy' (the older one) had a uid 100 named `_apt` but 'noble' does not.  The [postinst](https://github.com/odoo/odoo/blob/18.0/debian/postinst) for both is the same and includes this line:

`adduser --system --home $ODOO_DATA_DIR --quiet --group $ODOO_USER`

so it just grabs the next available UID.  Hence the difference.

Something in the file shows the best mitigation, though: before it creates the user it first sees if an 'odoo' user exists.  If one does, it will just use that.
