### ISSUE TITLE
[18.0] module: Base Error Installing on ES

### ISSUE THREAD

**Issue by pesatto** [odoo/odoo#183284]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

On creating a new database, on localization Spanish MEX 

### Log Output

```shell
2024-10-11 04:57:40,379 6772 ERROR pesatto odoo.sql_db: bad query: b' UPDATE "res_lang"\n                    SET "url_code" = "__tmp"."url_code"::VARCHAR, "write_date" = "__tmp"."write_date"::timestamp, "write_uid" = "__tmp"."write_uid"::int4\n                    FROM (VALUES (68, \'es\', \'2024-10-11T04:57:36.917274\'::timestamp, 1)) AS "__tmp"("id", "url_code", "write_date", "write_uid")\n                    WHERE "res_lang"."id" = "__tmp"."id"\n                '
ERROR: duplicate key value violates unique constraint "res_lang_url_code_uniq"
DETAIL:  Key (url_code)=(es) already exists.
 
2024-10-11 04:57:40,380 6772 WARNING pesatto odoo.modules.loading: Transient module states were reset 
2024-10-11 04:57:40,382 6772 ERROR pesatto odoo.modules.registry: Failed to load registry 
2024-10-11 04:57:40,382 6772 ERROR pesatto odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 437, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/models.py", line 5449, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/ubuntu/odoo/odoo/models.py", line 5367, in _load_records_write
    self.write(values)
  File "/home/ubuntu/odoo/odoo/addons/base/models/res_lang.py", line 357, in write
    self.env.flush_all()
  File "/home/ubuntu/odoo/odoo/api.py", line 833, in flush_all
    self[model_name].flush_model()
  File "/home/ubuntu/odoo/odoo/models.py", line 6698, in flush_model
    self._flush(fnames)
  File "/home/ubuntu/odoo/odoo/models.py", line 6775, in _flush
    model.browse(some_ids)._write_multi(vals_list)
  File "/home/ubuntu/odoo/odoo/models.py", line 4879, in _write_multi
    self.env.execute_query(SQL(
  File "/home/ubuntu/odoo/odoo/api.py", line 962, in execute_query
    self.cr.execute(query)
  File "/home/ubuntu/odoo/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "res_lang_url_code_uniq"
DETAIL:  Key (url_code)=(es) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/service/db.py", line 72, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, processed_modules = load_module_graph(
                                        ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 226, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 70, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 550, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/ubuntu/odoo/odoo/addons/base/data/res_lang_data.xml:17, somewhere inside
<record id="base.lang_es_419" model="res.lang">
            <field name="url_code">es</field>
        </record>
2024-10-11 04:57:40,386 6772 INFO pesatto odoo.modules.loading: loading 1 modules... 
2024-10-11 04:57:40,386 6772 INFO pesatto odoo.modules.loading: Loading module base (1/1) 
2024-10-11 04:57:40,399 6772 INFO pesatto odoo.modules.registry: module base: creating or updating database tables 
2024-10-11 04:57:41,532 6772 INFO pesatto odoo.models: Prepare computation of ir.module.module.menus_by_module 
2024-10-11 04:57:41,533 6772 INFO pesatto odoo.models: Prepare computation of ir.module.module.reports_by_module 
2024-10-11 04:57:41,533 6772 INFO pesatto odoo.models: Prepare computation of ir.module.module.views_by_module 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.user_id 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.commercial_partner_id 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.complete_name 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.company_registry 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.commercial_company_name 
2024-10-11 04:57:41,919 6772 INFO pesatto odoo.models: Prepare computation of res.partner.partner_share 
2024-10-11 04:57:42,027 6772 INFO pesatto odoo.models: Prepare computation of res.currency.decimal_places 
2024-10-11 04:57:42,107 6772 INFO pesatto odoo.models: Prepare computation of res.company.uses_default_logo 
2024-10-11 04:57:42,107 6772 INFO pesatto odoo.models: Prepare computation of res.company.logo_web 
2024-10-11 04:57:42,116 6772 INFO pesatto odoo.models: Computing parent_path for table res_company... 
2024-10-11 04:57:42,199 6772 INFO pesatto odoo.models: Prepare computation of res.users.signature 
2024-10-11 04:57:42,199 6772 INFO pesatto odoo.models: Prepare computation of res.users.share 
2024-10-11 04:57:43,781 6772 INFO pesatto odoo.modules.loading: loading base/data/res_bank.xml 
2024-10-11 04:57:43,783 6772 INFO pesatto odoo.modules.loading: loading base/data/res.lang.csv 
2024-10-11 04:57:43,805 6772 INFO pesatto odoo.modules.loading: loading base/data/res_lang_data.xml 
2024-10-11 04:57:43,823 6772 ERROR pesatto odoo.sql_db: bad query: b' UPDATE "res_lang"\n                    SET "url_code" = "__tmp"."url_code"::VARCHAR, "write_date" = "__tmp"."write_date"::timestamp, "write_uid" = "__tmp"."write_uid"::int4\n                    FROM (VALUES (68, \'es\', \'2024-10-11T04:57:40.386365\'::timestamp, 1)) AS "__tmp"("id", "url_code", "write_date", "write_uid")\n                    WHERE "res_lang"."id" = "__tmp"."id"\n                '
ERROR: duplicate key value violates unique constraint "res_lang_url_code_uniq"
DETAIL:  Key (url_code)=(es) already exists.
 
2024-10-11 04:57:43,825 6772 WARNING pesatto odoo.modules.loading: Transient module states were reset 
2024-10-11 04:57:43,825 6772 ERROR pesatto odoo.modules.registry: Failed to load registry 
2024-10-11 04:57:43,825 6772 ERROR pesatto odoo.addons.web.controllers.database: Database creation error. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/modules/registry.py", line 104, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'pesatto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 437, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/models.py", line 5449, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/ubuntu/odoo/odoo/models.py", line 5367, in _load_records_write
    self.write(values)
  File "/home/ubuntu/odoo/odoo/addons/base/models/res_lang.py", line 357, in write
    self.env.flush_all()
  File "/home/ubuntu/odoo/odoo/api.py", line 833, in flush_all
    self[model_name].flush_model()
  File "/home/ubuntu/odoo/odoo/models.py", line 6698, in flush_model
    self._flush(fnames)
  File "/home/ubuntu/odoo/odoo/models.py", line 6775, in _flush
    model.browse(some_ids)._write_multi(vals_list)
  File "/home/ubuntu/odoo/odoo/models.py", line 4879, in _write_multi
    self.env.execute_query(SQL(
  File "/home/ubuntu/odoo/odoo/api.py", line 962, in execute_query
    self.cr.execute(query)
  File "/home/ubuntu/odoo/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "res_lang_url_code_uniq"
DETAIL:  Key (url_code)=(es) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/odoo/addons/web/controllers/database.py", line 83, in create
    request.session.authenticate(name, credential)
  File "/home/ubuntu/odoo/odoo/http.py", line 1043, in authenticate
    registry = Registry(dbname)
               ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/modules/registry.py", line 106, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, processed_modules = load_module_graph(
                                        ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 226, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/ubuntu/odoo/odoo/modules/loading.py", line 70, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/ubuntu/odoo/odoo/tools/convert.py", line 550, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/ubuntu/odoo/odoo/addons/base/data/res_lang_data.xml:17, somewhere inside
<record id="base.lang_es_419" model="res.lang">
            <field name="url_code">es</field>
        </record>
```

**Comment by josiascruz-dobar** [comment]
I'm having the same issue with the es_DO language. 

Also, I'm noticing the following behaviours when creating new databases: 

1. The error above only throws if you put one of the es_* languages first in the --load_language switch. 
For example,  
`./odoo-bin -d odoo18_jc --load-language en_US,es_DO,it_IT --language it_IT` 
 installs the database, and the 3 languages. No error. However, if I change the order putting es_DO first, the error is raised. 

2. The --language switch seems not to work. In the same example above, install the database in en_US language by default.
