### ISSUE TITLE
[18.0] Database creation error: relation "ir_model" does not exist... 

### ISSUE THREAD

**Issue by bashman** [odoo/odoo#183611]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

It has happened to me that when I try to install Odoo 18, I get the following error:

![image](https://github.com/user-attachments/assets/0e73d634-cb52-4c70-8f59-3fd414217438)

I am installing the es_VE language.
![image](https://github.com/user-attachments/assets/889ade69-86df-4d37-8aed-5b83c171d036)

But if I install the en_US version and the country Venezuela it installs correctly. 

```
(base)  python3 --version
Python 3.12.4
(base)  

postgres=# select version();
                                                             version                                                             
---------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0, 64-bit
(1 row)

Ubuntu: 24. 

```

### Log Output

```shell
2024-10-14 15:25:45,211 290331 ERROR lims odoo.addons.web.controllers.database: Database creation error. 
Traceback (most recent call last):
  File "/home/bashman/devel/labodoo/odoo/odoo/modules/registry.py", line 104, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/bashman/.local/share/mise/installs/python/latest/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'lims'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bashman/devel/labodoo/odoo/addons/web/controllers/database.py", line 83, in create
    request.session.authenticate(name, credential)
  File "/home/bashman/devel/labodoo/odoo/odoo/http.py", line 1043, in authenticate
    registry = Registry(dbname)
               ^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/modules/registry.py", line 106, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/home/bashman/.local/share/mise/installs/python/latest/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/bashman/devel/labodoo/odoo/odoo/modules/loading.py", line 428, in load_modules
    registry.setup_models(cr)
  File "/home/bashman/.local/share/mise/installs/python/latest/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bashman/devel/labodoo/odoo/odoo/modules/registry.py", line 337, in setup_models
    env['ir.model']._add_manual_models()
  File "/home/bashman/devel/labodoo/odoo/odoo/addons/base/models/ir_model.py", line 491, in _add_manual_models
    cr.execute("SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'")
  File "/home/bashman/devel/labodoo/odoo/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...
                                              ^
```

**Comment by qpanizo** [comment]
I have the same error for PERU localization

**Comment by parciniegas** [comment]
This work for me: install with English language and country Colombia, after database creation add Spanish language and switch to this as default.

**Comment by adrianpaesani** [comment]
Another alternative solution is to install using the Spanish/Latin America language setting and then select the appropriate country. This approach ensures correct functionality. Once inside Odoo, you can install the specific language for each country as needed. Using the generic Spanish/Latin America setting provides compatibility with most Latin American Spanish variations.

**Comment by dobraslawa** [comment]
I have the same issue, i've tried engils language, no country, still same error.

**Comment by BagantEcuador** [comment]
> This work for me: install with English language and country Colombia, after database creation add Spanish language and switch to this as default.

Genial....Gracias....

**Comment by JoaquinMINT** [comment]
Hola, no es posible solo dejar el lenguaje en español requerido después de la instalación que no sea el latinoamericano? , ya que para todo momento aparece que puedes cambiar entre ambos idiomas y no lo considero una instalación limpia, en pruebas esto es particular de la versión 18 ya que en versiones menores no tiene este error.
Realice cambios en Postgres al parecer la configuración del "Collation" sin éxito para este error.

**Comment by hedgsagor** [comment]
> Esto me funcionó: instalar con idioma inglés y país Colombia, después de crear la base de datos agregar idioma español y cambiar a este como predeterminado.

muchas gracias, esto me ayudo ,para el pais Perú

**Comment by jamesvalladaresv** [comment]
I have the same problem and I also consider that it is not a clean installation, installing the English version and then adding the es_PE language. I don't see any light to fix this problem

**Comment by klap50** [comment]
Same error in Argentina, i try to make in docker, Vm, etc. 
  i install es_AR locale for PosgreSQL and odoo container, but dont work.

is a bug?

**Comment by jonaspm** [comment]
Same issue with Spanish MX

**Comment by pablotarja** [comment]
I had the same issue with Guatemala and English then try with Colombia and English but don't so I discard all changes and do a git pull with this resolved the issue. The error that I had was:  File "/home/pablo/Desktop/odoo/odoo/addons/base/models/ir_model.py", line 501, in _add_manual_models
    cr.execute("SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'")
  File "/home/pablo/Desktop/odoo/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...

**Comment by GanemoCorp** [comment]
Any update of this bug?

**Comment by Cravit-Hinesh** [comment]
I had same error, check permission on odoo source and file stores, i got this solved by given access to odoo user for file store directory

**Comment by AmroucheMaroua** [comment]
Just make sure to give access to users, applications, and packages to the sessions directory (specifically the filestore).
