### ISSUE TITLE
[17.0] odoo.modules.loading: ParseError on res_users_data.xml 

### ISSUE THREAD

**Issue by vekee** [odoo/odoo#183683]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

can not open odoo login page by this odoo loading error.
I can use it normally before this error happening.
```

    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/base/data/res_users_data.xml:15, somewhere inside
<record id="user_admin" model="res.users">
            <field name="login">admin</field>
            <field name="password">admin</field>
            <field name="partner_id" ref="base.partner_admin"/>
            <field name="company_id" ref="main_company"/>
            <field name="company_ids" eval="[Command.link(ref('main_company'))]"/>
            <field name="groups_id" eval="[Command.set([])]"/>
            <field name="signature">&lt;span&gt;-- &lt;br/&gt;
Administrator&lt;/span&gt;</field>
        </record>
```

### Log Output

```shell
2024-10-15 05:06:29,415 1 INFO test_odoo_db_prd odoo.modules.loading: loading 1 modules...
2024-10-15 05:06:29,416 1 INFO test_odoo_db_prd odoo.modules.loading: Loading module base (1/1)
2024-10-15 05:06:29,443 1 INFO test_odoo_db_prd odoo.modules.registry: module base: creating or updating database tables
2024-10-15 05:06:30,181 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_bank.xml
2024-10-15 05:06:30,190 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res.lang.csv
2024-10-15 05:06:30,554 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_lang_data.xml
2024-10-15 05:06:30,589 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_partner_data.xml
2024-10-15 05:06:30,727 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_currency_data.xml
2024-10-15 05:06:32,711 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_company_data.xml
2024-10-15 05:06:32,763 1 INFO test_odoo_db_prd odoo.modules.loading: loading base/data/res_users_data.xml
2024-10-15 05:06:33,516 1 ERROR test_odoo_db_prd odoo.sql_db: bad query: UPDATE "res_users" SET "share" = true, "write_date" = '2024-10-15T05:06:29.414853'::timestamp, "write_uid" = 1 WHERE id IN (2)
ERROR: new row for relation "res_users" violates check constraint "res_users_notification_type"
DETAIL:  Failing row contains (2, 1, 3, t, 2024-07-30 12:41:10.292895, admin, $pbkdf2-sha512$600000$dq7VOmcsBcA4Z6x1LiUEgA$d1LBmrU9lEojP0nVFfU..., null, 1, 1, <span data-o-mail-quote="1">-- <br data-o-mail-quote="1">
Admini..., t, 2024-10-15 05:06:29.414853, DCDI53ATHJER3YBDA6MZ56LR2JOMOXEM, inbox, onboarding_emoji, null, 1).

2024-10-15 05:06:33,518 1 WARNING test_odoo_db_prd odoo.modules.loading: Transient module states were reset
2024-10-15 05:06:33,519 1 ERROR test_odoo_db_prd odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'test_odoo_db_prd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 456, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5064, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4995, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1728, in write
    res = super(UsersView, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1429, in write
    res = super(UsersImplied, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 740, in write
    self.env['ir.model.access'].call_cache_clearing_methods()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 2086, in call_cache_clearing_methods
    self.env.invalidate_all()
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 711, in invalidate_all
    self.flush_all()
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 723, in flush_all
    self[model_name].flush_model()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6322, in flush_model
    self._flush(fnames)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6423, in _flush
    model.browse(ids)._write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4520, in _write
    cr.execute(SQL(
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.CheckViolation: new row for relation "res_users" violates check constraint "res_users_notification_type"
DETAIL:  Failing row contains (2, 1, 3, t, 2024-07-30 12:41:10.292895, admin, $pbkdf2-sha512$600000$dq7VOmcsBcA4Z6x1LiUEgA$d1LBmrU9lEojP0nVFfU..., null, 1, 1, <span data-o-mail-quote="1">-- <br data-o-mail-quote="1">
Admini..., t, 2024-10-15 05:06:29.414853, DCDI53ATHJER3YBDA6MZ56LR2JOMOXEM, inbox, onboarding_emoji, null, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 114, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 422, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/base/data/res_users_data.xml:15, somewhere inside
<record id="user_admin" model="res.users">
            <field name="login">admin</field>
            <field name="password">admin</field>
            <field name="partner_id" ref="base.partner_admin"/>
            <field name="company_id" ref="main_company"/>
            <field name="company_ids" eval="[Command.link(ref('main_company'))]"/>
            <field name="groups_id" eval="[Command.set([])]"/>
            <field name="signature">&lt;span&gt;-- &lt;br/&gt;
Administrator&lt;/span&gt;</field>
        </record>
2024-10-15 05:06:33,519 1 ERROR test_odoo_db_prd odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 87, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'test_odoo_db_prd'
```

**Comment by 1195655796** [comment]
I faced the similar issue in odoo 18.0,hope it to be solved soon!

**Comment by 1195655796** [comment]
but I faced it in adding mew module situation instead of login phase

**Comment by gauravsinghal-ovom** [comment]
I am facing the same problem, did you resolved this?

**Comment by aps2201** [comment]
stumbled upon this issue also, what postgres version were you using when this happened? I'm using 17.0

**Comment by aps2201** [comment]
Found the issue, for me its due to reinitializing the base module when already changing the admin password. You can alleviate this by running the odoo-bin again without --init

**Comment by vekee** [comment]
I didn't found this problem's solution.
Even I rebuild it by odoo18, I shutdown my server one week ago, today it happened again.

**Comment by Shjpr9** [comment]
I am facing the same issue on odoo 18 when going through Server Framework 101 tutorial (real state module) at chapter 4 when trying to add "[res_country_data.xml](https://raw.githubusercontent.com/odoo/odoo/e8697f609372cd61b045c4ee2c7f0fcfb496f58a/odoo/addons/base/data/res_country_data.xml)"

The command I run:
`./odoo-bin --addons-path=addons,tutorials -d mydb -u estate`

My manifest file:
```py
{
    'name': 'E-State App',
    'author': "ShayanJpr",
    'depends': [
        'base',
    ],
    'application': True,
    'data': [
        'data/res_country_data.xml',
        'data/res.country.state.csv',
        'security/ir.model.access.csv',
    ],
    'license': 'LGPL-3'
}
```

Some logs:
```
2025-03-09 22:00:17,274 17519 WARNING mydb odoo.modules.loading: Transient module states were reset 
2025-03-09 22:00:17,275 17519 ERROR mydb odoo.modules.registry: Failed to load registry 
2025-03-09 22:00:17,275 17519 CRITICAL mydb odoo.service.server: Failed to initialize database `mydb`.
```

Some more logs:
```
raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing .../odoo-18.0/tutorials/estate/data/res_country_data.xml:4, somewhere inside
<record id="ae" model="res.country">
            <field name="name">United Arab Emirates</field>
            <field name="code">ae</field>
            <field name="currency_id" ref="AED"/>
            <field eval="971" name="phone_code"/>
        </record>
```

**Comment by manhpham90vn** [comment]
same here

**Comment by vekee** [comment]
@aps2201 @SamanHamidi @manhpham90vn @Shjpr9 
After 6 month from upgrade to odoo18,  I didn' saw this problem happen again.
