### ISSUE TITLE
[16.0] Error occurs when selecting an export template Containing fields without group permission

### ISSUE THREAD

**Issue by kanda999** [odoo/odoo#184497]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

When a user without permissions selects an export template that includes fields they have no access, an error occurs.

Steps to Reproduce:

1, A user with the Inventory/Manager creates an export template for the Inventory Adjustment(stock.quant model).
During the creation of the export template, the field Inventoried Quantity is included.
(Inventoried Quantity is restricted by groups="stock.group_stock_manager", meaning users with the Inventory/User role do not have access to this field.)
![2024-10-21_19h46_55](https://github.com/user-attachments/assets/8ec9283f-4048-48e3-8eeb-77ae1e56163e)

2, A user with the Inventory/User try to export Inventory Adjustment (stock.quant) data and selects the template created in step 1.

3, A client-side error occurs.

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1652, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/odoo/odoo/http.py", line 1679, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/odoo/odoo/http.py", line 1883, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/odoo/odoo/http.py", line 734, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/odoo/addons/web/controllers/export.py", line 375, in namelist
    return [
  File "/data/build/odoo/addons/web/controllers/export.py", line 376, in <listcomp>
    {'name': field['name'], 'label': fields_data[field['name']]}
KeyError: 'inventory_quantity_auto_apply'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://69635752-16-0-all.runbot181.odoo.com/web/assets/1859-cee62c1/web.assets_backend.min.js:997:163)
        at XMLHttpRequest.<anonymous> (https://69635752-16-0-all.runbot181.odoo.com/web/assets/1859-cee62c1/web.assets_backend.min.js:1005:13)
```
### Video
https://drive.google.com/file/d/1gl9DAZvu21yhZnyCcRywJ1hj4XLrcTMa/view?usp=sharing

### Support Ticket

OPW: #4273856

@qrtl

**Comment by kanda999** [comment]
I confirmed this isuue has been resoleved in runbot env.
