### ISSUE TITLE
[18.0] Invoice Preview: 500: Internal Server Error

### ISSUE THREAD

**Issue by Alsheh** [odoo/odoo#184402]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

I'm unable to preview a sale invoice.

Steps to reproduce:
- Go to Translations and activate Arabic `ar_001`.
- Ensure the `l10n_sa` module is installed ([docs](https://www.odoo.com/documentation/master/applications/finance/fiscal_localizations/saudi_arabia.html#configuration)).
- Go to an existing invoice and click `Preview`.

![Screenshot 2024-10-19 at 12 44 11 PM](https://github.com/user-attachments/assets/5becfc50-bd73-440e-b751-7ad6d4a8946f)

### Log Output

QWeb:
```
Error message:

Error while render the template
KeyError: 'groups_by_subtotal'
Template: l10n_gcc_invoice.arabic_english_invoice
Path: /t/t/div/div[2]/div/div/table/t[2]/t[2]
Node: <t t-foreach="tax_totals[\'groups_by_subtotal\'][subtotal_to_show]" t-as="amount_by_group"/>
The error occurred while rendering the template l10n_gcc_invoice.arabic_english_invoice and evaluating the following expression: <t t-foreach="tax_totals[\'groups_by_subtotal\'][subtotal_to_show]" t-as="amount_by_group"/>
```

Traceback:
```
Traceback (most recent call last):
  File "<2283>", line 2222, in template_2283
  File "<2283>", line 2204, in template_2283_content
  File "<2283>", line 1348, in template_2283_t_call_0
KeyError: 'groups_by_subtotal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 1954, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 1921, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 2081, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_http.py", line 330, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 728, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/account_payment/controllers/portal.py", line 172, in portal_my_invoice_detail
    return super().portal_my_invoice_detail(invoice_id, amount=amount, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 728, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/account/controllers/portal.py", line 175, in portal_my_invoice_detail
    return self._show_report(model=invoice_sudo, report_type=report_type, report_ref='account.account_invoices', download=download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/portal/controllers/portal.py", line 443, in _show_report
    report = getattr(ReportAction, method_name)(report_ref, list(model.ids), data={'report_type': report_type})[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1076, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 755, in _render_template
    return view_obj._render_template(template, values).encode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_ui_view.py", line 2183, in _render_template
    return self.env['ir.qweb']._render(template, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/tools/profiler.py", line 304, in _tracked_method_render
    return method_render(self, template, values, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_qweb.py", line 600, in _render
    result = ''.join(rendering)
             ^^^^^^^^^^^^^^^^^^
  File "<808>", line 38, in template_808
  File "<808>", line 27, in template_808_content
  File "<807>", line 107, in template_807
  File "<807>", line 89, in template_807_content
  File "<807>", line 77, in template_807_t_call_0
  File "<2283>", line 2230, in template_2283
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'groups_by_subtotal'
Template: l10n_gcc_invoice.arabic_english_invoice
Path: /t/t/div/div[2]/div/div/table/t[2]/t[2]
Node: <t t-foreach="tax_totals[\'groups_by_subtotal\'][subtotal_to_show]" t-as="amount_by_group"/>
```

### Support Ticket

Ticket ID #4271299

**Comment by vava-odoo** [comment]
Fixed in https://github.com/odoo/odoo/commit/18e54c9fa12260927d0813dde7f77e66f7304c08
Thanks for reporting (but please don't duplicate issue and official ticket, the latter is sufficient).
