### ISSUE TITLE
[18.0] External API: Invalid language code error when reading account.move.line records

### ISSUE THREAD

**Issue by Alsheh** [odoo/odoo#184410]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- Use the XML API to read any records from the `account.move.line` model.
-  All read operations will fail unless the following fields are excluded: `l10n_gcc_invoice_tax_amount`, `l10n_gcc_line_name`
- Error: `xmlrpc.client.Fault: <Fault 2: 'Invalid language code: ar_001'>`

### Log Output

```shell
Traceback (most recent call last):
  File "<redacted>/odoo_api.py", line 2610, in <module>
    bill_line_ids = xml_rpc('account.move.line', 'search_read', args=[[['move_id', '=', 184362]]], kwargs={'fields':[]})
  File "/Users/hassanalshehri/Projects/alsheh/rohan-erp/odoo_api.py", line 312, in xml_rpc
    result = server.execute_kw(DB, UID, PASS, model, method, args, kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 2: 'Invalid language code: ar_001'>
```

**Comment by vava-odoo** [comment]
Thanks for the report.
This is probably because you don't have the language ar_001 installed in your database.
I wonder if the code shouldn't handle this case though. @myhy-odoo it seems related to https://github.com/odoo/odoo/commit/02e2fecce7813dee989e5f294ddaaf75ffafc012 could you have a look?

**Comment by myhy-odoo** [comment]
Hello! I took a look and the field `l10n_gcc_line_name`  and its compute method are now dead code because it is no longer being referenced in the arabic_english_invoice report as intended. My code version in the view has been replaced by this commit: https://github.com/odoo/odoo/commit/4aa131b8b5133c7c1508b512b97554647af0477f . Thus, the `l10n_gcc_line_name` and its compute method can be safely removed.

As for why the other field `l10n_gcc_tax_amount" needs to be excluded, I am not sure

**Comment by vava-odoo** [comment]
Thanks for the explanation @myhy-odoo but I don't know if we can safely remove the field. Maybe remove the content of the compute would do the trick?
@Alsheh Does it work if you only exclude `l10n_gcc_line_name`? I don't see any reason about `l10n_gcc_tax_amount` to be reworked.
