### ISSUE TITLE
[18.0] External API: KeyError when reading an invoice via the XML API

### ISSUE THREAD

**Issue by Alsheh** [odoo/odoo#184408]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- Use the XML API to read an invoice or bill.
- The read operation will fail with this error `KeyError: \'amount_total\`
- Exclude the `partner_credit` field and the read operation will succeed.

### Log Output

```shell
{'server_version': '18.0+e', 'server_version_info': [18, 0, 0, 'final', 0, 'e'], 'server_serie': '18.0', 'protocol_version': 1}
Traceback (most recent call last):
  File "<redacted>/odoo_api.py", line 2606, in <module>
    bill = xml_rpc('account.move', 'read', args=[184362], kwargs={'fields': []})
  File "/<redacted>/odoo_api.py", line 312, in xml_rpc
    result = server.execute_kw(DB, UID, PASS, model, method, args, kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: 'Traceback (most recent call last):\n  File "/home/odoo/src/odoo/18.0/odoo/addons/base/controllers/rpc.py", line 161, in xmlrpc_2\n    response = self._xmlrpc(service)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/custom/trial/saas_trial/controllers/main.py", line 294, in _xmlrpc\n    res = super(OdooRPC, self)._xmlrpc(service)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/addons/base/controllers/rpc.py", line 139, in _xmlrpc\n    result = dispatch_rpc(service, method, params)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 399, in dispatch_rpc\n    return dispatch(method, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 39, in dispatch\n    res = execute_kw(db, uid, *params[3:])\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 61, in execute_kw\n    return execute(db, uid, obj, method, *args, **kw or {})\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 68, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 52, in execute_cr\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 137, in retrying\n    result = func()\n             ^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 517, in call_kw\n    result = getattr(recs, name)(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 3806, in read\n    return self._read_format(fnames=fields, load=load)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4037, in _read_format\n    vals[name] = convert(record[name], record, use_display_name)\n                         ~~~~~~^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7000, in __getitem__\n    return self._fields[key].__get__(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1287, in __get__\n    self.compute_value(recs)\n  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1469, in compute_value\n    records._compute_field_value(self)\n  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 427, in _compute_field_value\n    return super()._compute_field_value(field)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5243, in _compute_field_value\n    fields.determine(field.compute, self)\n  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 109, in determine\n    return needle(*args)\n           ^^^^^^^^^^^^^\n  File
```

**Comment by vava-odoo** [comment]
Fixed by https://github.com/odoo/odoo/commit/a91144533a6c02cd543743c237cfea120c9129f1
Thanks for the report
