### ISSUE TITLE
[16.0,17.0] odoo: unclear error message on translation file error

### ISSUE THREAD

**Issue by hnavarro-kernet** [odoo/odoo#184630]
### Odoo Version

- [X] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- Add an extra `"` to a translation
- Reload web client to load translations for the language

Example of a `es.po`:
```
#. module: ke_deployments
#: model:ir.model.fields,field_description:ke_deployments.field_deployment_type__domain_api_access_key
msgid "Access Key (domains)"
msgstr "Llave de acceso (dominios)""
```

### Log Output

```shell
2024-10-21 19:24:57,696 92149 ERROR kernet-dirty odoo.tools.translate: couldn't read translation file [lang: es][format: po]
Traceback (most recent call last):
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.http', <function IrHttp.get_web_translations_hash at 0x1089eb250>, frozenset({<a lot of modules that clog the log and are not important>}), 'es_ES')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 1508, in _get_code_translations
    p = CodeTranslations._read_code_translations_file(fileobj, filter_func)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 1495, in _read_code_translations_file
    reader = TranslationFileReader(fileobj, fileformat='po')
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 587, in TranslationFileReader
    return PoFileReader(source)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 642, in __init__
    self.pofile = polib.pofile(source.read().decode())
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 139, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 87, in _pofile_or_mofile
    instance = parser.parse()
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 1347, in parse
    raise IOError('Syntax error in po file %s(line %s): '
OSError: Syntax error in po file (line 110): unescaped double quote found
```

**Comment by intero-chz** [comment]
This is probably the best error message for problems with translations that I have seen to date. But the error messages relating to translations are an absolute horror.

**Comment by duong77476-viindoo** [comment]
For me it not that unclear like you said, you will need to look in the log to see which po file is loading and base on the line 
`OSError: Syntax error in po file (line 110): unescaped double quote found` you can easily find the error because you already the po file and the error line number.

**Comment by hnavarro-kernet** [comment]
> For me it not that unclear like you said, you will need to look in the log to see which po file is loading and base on the line `OSError: Syntax error in po file (line 110): unescaped double quote found` you can easily find the error because you already the po file and the error line number.

```
2024-10-24 06:29:17,965 79767 INFO kernet-dirty odoo.modules.loading: 187 modules loaded in 1.10s, 0 queries (+0 extra)
2024-10-24 06:29:18,169 79767 INFO kernet-dirty odoo.modules.loading: Modules loaded.
2024-10-24 06:29:18,201 79767 INFO kernet-dirty odoo.modules.registry: Registry loaded in 1.827s
2024-10-24 06:29:29,015 79767 INFO kernet-dirty odoo.addons.base.models.ir_http: Generating routing map for key None
2024-10-24 06:29:29,349 79767 ERROR kernet-dirty odoo.tools.translate: couldn't read translation file [lang: es][format: po]
Traceback (most recent call last):
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.http', <function IrHttp.get_web_translations_hash at 0x1071e7490>, frozenset({'base_automation', 'ke_deployments', 'base_bank_from_iban', 'project_task_add_very_high', 'purchase_stock', 'phone_validation', 'account_reconcile_oca', 'sale_management', 'iap_crm', 'resource', 'project_task_default_stage', 'account_move_line_tax_editable', 'crm', 'hr_timesheet_attendance', 'mis_builder', 'mass_mailing_partner', 'hr_org_chart', 'report_xlsx', 'account_financial_report', 'l10n_es', 'account_usability', 'utm', 'sale_margin', 'digest', 'crm_sms', 'account', 'date_range', 'purchase', 'snailmail_account', 'hr_holidays_settings', 'hr', 'ke_kernet_portal', 'l10n_es_ticketbai_api_batuz', 'ke_postmark', 'mass_mailing_crm', 'auth_signup', 'l10n_es_aeat_mod347', 'calendar_sms', 'stock_sms', 'hr_holidays', 'account_payment_order', 'base_iso3166', 'report_qweb_parameter', 'bi_sql_editor', 'stock_account', 'delivery', 'l10n_es_ticketbai_batuz', 'snailmail', 'l10n_es_ticketbai', 'report_xlsx_helper', 'account_due_list_payment_mode', 'base_import', 'barcodes_gs1_nomenclature', 'queue_job', 'bryntum_gantt', 'payment_custom', 'account_payment_purchase', 'account_move_name_sequence', 'account_due_list', 'auth_oauth', 'spreadsheet_account', 'l10n_es_aeat_mod111', 'product', 'web_chatter_position', 'account_banking_mandate', 'ke_kernet_custom_various', 'iap', 'spreadsheet_dashboard_account', 'l10n_es_ticketbai_api', 'spreadsheet_dashboard', 'payment', 'web', 'sale_purchase', 'sale_stock', 'base_vat', 'account_statement_import_base', 'social_media', 'report_xml', 'sms', 'account_statement_base', 'account_payment', 'purchase_discount', 'sales_team', 'account_chart_update', 'hr_holidays_attendance', 'account_invoice_pricelist_sale', 'rating', 'server_action_mass_edit', 'account_payment_partner', 'account_asset_management', 'partner_autocomplete', 'board', 'crm_iap_enrich', 'web_unsplash', 'account_tax_balance', 'contract_payment_mode', 'account_invoice_tax_required', 'mail_bot', 'mass_mailing', 'account_payment_sale', 'web_tour', 'hr_contract', 'ke_restrict_invoice_deletion', 'l10n_es_account_asset', 'ke_api_rest', 'web_responsive', 'sale', 'account_credit_control', 'sale_project', 'ke_db_direct_access', 'account_statement_import_file', 'attachment_indexation', 'hr_timesheet_sheet', 'sale_expense', 'link_tracker', 'account_banking_sepa_direct_debit', 'analytic', 'google_account', 'uom', 'base_location_geonames_import', 'account_payment_mode', 'l10n_es_partner', 'google_calendar', 'hr_expense', 'stock', 'crm_iap_mine', 'account_analytic_parent', 'base_sparse_field', 'spreadsheet_dashboard_purchase', 'mass_mailing_sale', 'google_gmail', 'sale_timesheet', 'sale_crm', 'bus', 'project_timesheet_holidays', 'base_address_extended', 'l10n_generic_coa', 'project', 'account_edi_ubl_cii', 'spreadsheet_dashboard_sale', 'account_edi', 'web_widget_x2many_2d_matrix', 'portal', 'ke_grafana', 'http_routing', 'contract', 'barcodes', 'hr_attendance', 'base_setup', 'account_banking_pain_base', 'spreadsheet', 'base_revision', 'l10n_es_aeat_mod390', 'base_location', 'account_banking_sepa_credit_transfer', 'account_payment_purchase_stock', 'sql_request_abstract', 'crm_phonecall', 'ke_kernet_api', 'ke_kernet_custom_reports', 'iap_mail', 'contract_sale', 'l10n_es_partner_mercantil', 'web_editor', 'ke_tax_group_name', 'calendar', 'l10n_es_mis_report', 'partner_firstname', 'web_kanban_gauge', 'account_payment_term_extension', 'mail', 'l10n_es_facturae', 'account_invoice_pricelist', 'base', 'base_iban', 'web_advanced_search', 'l10n_es_aeat', 'hr_timesheet', 'mail_activity_board', 'account_invoice_constraint_chronology', 'contacts', 'account_lock_date_update', 'mis_builder_cash_flow', 'hr_hourly_cost', 'l10n_es_aeat_mod303', 'l10n_es_toponyms', 'l10n_es_vat_book'}), 'es_ES')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 1508, in _get_code_translations
    p = CodeTranslations._read_code_translations_file(fileobj, filter_func)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 1495, in _read_code_translations_file
    reader = TranslationFileReader(fileobj, fileformat='po')
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 587, in TranslationFileReader
    return PoFileReader(source)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/odoo/tools/translate.py", line 642, in __init__
    self.pofile = polib.pofile(source.read().decode())
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 139, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 87, in _pofile_or_mofile
    instance = parser.parse()
  File "/Users/hodeinavarro/Developer/kernet-it/environments/kernet/lib/python3.10/site-packages/polib.py", line 1347, in parse
    raise IOError('Syntax error in po file %s(line %s): '
OSError: Syntax error in po file (line 110): unescaped double quote found
2024-10-24 06:29:34,158 79767 INFO kernet-dirty werkzeug: 127.0.0.1 - - [24/Oct/2024 06:29:34] "GET /web HTTP/1.1" 200 - 113 0.216 4.931
```

The error is clear, the file which I'm supposed to fix is not. I'm not loading any i18n file, just start up the server and reload (or enter for the first time) the web client.

**Comment by duong77476-viindoo** [comment]
@hnavarro-kernet Oh year in this case, a quick tip is to update module in order make the log show which translation file is loading. I'm not sure they will merge this and i see you already commit it to your own fork so it ok then.
