### ISSUE TITLE
[18.0] Link sent to email with quotation gets 500 internal server error

### ISSUE THREAD

**Issue by tomasbond** [odoo/odoo#185180]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Please describe how to reproduce the issue with clear steps.
Fresh Odoo 18 on premise install, ubuntu 22.04, installed sales module and setup smtp outgoing server

Current behaviour: mail sent to customer with "accept and sign quotation" link doesnt work at first. When you click on the link it show you internal server error, only when you refresh again the link (no other changes) it shows you the client portal with the expected quotation.
Expected behaviour: click on "accept and sign quotation" direct transfer to customer portal with quotation
Video/Screenshot link (optional):
Mail received ok:
![image](https://github.com/user-attachments/assets/77449819-384f-476b-aeeb-5ba211546ab9)
First time click on "Accept and sign quotation":
![image](https://github.com/user-attachments/assets/7514467a-bf34-40a8-bc45-2ef9769de1ed)
After this Internal server error i just click on F5 (refresh page):
![image](https://github.com/user-attachments/assets/e18f26d6-ccb2-487b-a93a-a2b39da1acea)

### Log Output

```shell
2024-10-24 19:48:20,508 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:20] "GET /mail/view?access_token=38adcb45-ca80-4405-8373-04d3c2add0c6&auth_signup_token=AUGCImcAAAAAmxymf6Rx42NB9C7b01hkgybLaIS7mG7RPL38WPko8vhbNywgbnVsbCwgInNpZ251cCJd&hash=3fd1761e0e6abab6aada3b4ca419180fbebb56b629e930ed829031e458deda87&model=sale.order&pid=7&res_id=1 HTTP/1.1" 303 - 10 0.006 0.016
2024-10-24 19:48:20,821 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:20] "GET /my/orders/1?access_token=38adcb45-ca80-4405-8373-04d3c2add0c6&pid=7&hash=3fd1761e0e6abab6aada3b4ca419180fbebb56b629e930ed829031e458deda87 HTTP/1.1" 303 - 4 0.001 0.006
2024-10-24 19:48:21,147 72508 INFO odoo18-descartar odoo.addons.base.models.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: sale.order
2024-10-24 19:48:22,123 72508 INFO odoo18-descartar odoo.addons.base.models.ir_mail_server: No se logró entregar el correo con el servidor SMTP 'None'.
SMTPDataError: (553, b'Relaying disallowed as tomasbond153@gmail.com')
2024-10-24 19:48:22,123 72508 ERROR odoo18-descartar odoo.addons.mail.models.mail_mail: failed sending mail (id: 8) due to Falló la entrega del correo
No se logró entregar el correo con el servidor SMTP 'None'.
SMTPDataError: (553, b'Relaying disallowed as tomasbond153@gmail.com')
Traceback (most recent call last):
  File "/opt/odoo18/odoo/addons/base/models/ir_mail_server.py", line 736, in send_email
    smtp.send_message(message, smtp_from, smtp_to_list)
  File "/usr/lib/python3.10/smtplib.py", line 986, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
  File "/usr/lib/python3.10/smtplib.py", line 908, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (553, b'Relaying disallowed as tomasbond153@gmail.com')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo18/addons/mail/models/mail_mail.py", line 737, in _send
    res = SendIrMailServer.send_email(
  File "/opt/odoo18/odoo/addons/base/models/ir_mail_server.py", line 751, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
odoo.addons.base.models.ir_mail_server.MailDeliveryException: ('Falló la entrega del correo', "No se logró entregar el correo con el servidor SMTP 'None'.\nSMTPDataError: (553, b'Relaying disallowed as tomasbond153@gmail.com')")
2024-10-24 19:48:22,132 72508 INFO odoo18-descartar odoo.addons.mail.models.mail_mail: Sent batch 1 emails via mail server ID #1
2024-10-24 19:48:22,135 72508 ERROR odoo18-descartar odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/opt/odoo18/odoo/http.py", line 2364, in __call__
    response = request._serve_db()
  File "/opt/odoo18/odoo/http.py", line 1891, in _serve_db
    return self._transactioning(
  File "/opt/odoo18/odoo/http.py", line 1954, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/opt/odoo18/odoo/service/model.py", line 176, in retrying
    env.cr.commit()  # effectively commits and execute post-commits
  File "/opt/odoo18/odoo/sql_db.py", line 485, in commit
    self.postcommit.run()
  File "/opt/odoo18/odoo/tools/misc.py", line 1157, in run
    func()
  File "/opt/odoo18/addons/mail/models/mail_mail.py", line 598, in send_emails_with_new_cursor
    env['mail.mail'].browse(email_ids).send()
  File "/opt/odoo18/addons/mail/models/mail_mail.py", line 647, in send
    smtp_session.quit()
  File "/usr/lib/python3.10/smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.10/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.10/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.10/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2024-10-24 19:48:22,136 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /es/my/orders/1?access_token=38adcb45-ca80-4405-8373-04d3c2add0c6&pid=7&hash=3fd1761e0e6abab6aada3b4ca419180fbebb56b629e930ed829031e458deda87 HTTP/1.1" 500 - 73 0.065 0.941
2024-10-24 19:48:22,472 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 200 - 0 0.000 0.007
2024-10-24 19:48:22,473 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/util/index.js HTTP/1.1" 200 - 0 0.000 0.005
2024-10-24 19:48:22,474 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/dist/css/bootstrap.css HTTP/1.1" 200 - 0 0.000 0.011
2024-10-24 19:48:22,474 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/dom/event-handler.js HTTP/1.1" 200 - 0 0.000 0.004
2024-10-24 19:48:22,480 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/dom/data.js HTTP/1.1" 200 - 0 0.000 0.005
2024-10-24 19:48:22,481 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/dom/manipulator.js HTTP/1.1" 200 - 0 0.000 0.003
2024-10-24 19:48:22,801 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/util/config.js HTTP/1.1" 200 - 0 0.000 0.005
2024-10-24 19:48:22,807 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/base-component.js HTTP/1.1" 200 - 0 0.000 0.008
2024-10-24 19:48:22,813 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/dom/selector-engine.js HTTP/1.1" 200 - 0 0.000 0.010
2024-10-24 19:48:22,814 72508 INFO ? werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:22] "GET /web/static/lib/bootstrap/js/dist/collapse.js HTTP/1.1" 200 - 0 0.000 0.005
2024-10-24 19:48:23,569 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:23] "GET /favicon.ico HTTP/1.1" 303 - 4 0.002 0.006
2024-10-24 19:48:23,914 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:48:23] "GET /es/favicon.ico HTTP/1.1" 404 - 12 0.009 0.034
2024-10-24 19:49:16,958 72508 INFO odoo18-descartar odoo.addons.base.models.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: sale.order
2024-10-24 19:49:17,007 72508 INFO odoo18-descartar werkzeug: 200.126.241.41 - - [24/Oct/2024 19:49:17] "GET /es/my/orders/1?access_token=38adcb45-ca80-4405-8373-04d3c2add0c6&pid=7&hash=3fd1761e0e6abab6aada3b4ca419180fbebb56b629e930ed829031e458deda87 HTTP/1.1" 200 - 37 0.019 0.049`
```

**Comment by tomasbond** [comment]
same behaviour if customer log in to portal and access to quotations. on first try it gets internal server error. after this error if refresh it works okey. with development tools i can see cookies being inserted to session when it fails.
![image](https://github.com/user-attachments/assets/ab834d40-e0ae-43a5-ad03-2ca04e33352e)
After hitting F5 on the same website:
![image](https://github.com/user-attachments/assets/f894b11c-f4a6-4186-b428-6e2e98448933)

**Comment by tomasbond** [comment]
Done the same on 17.0 with exact same problem.

**Comment by tomasbond** [comment]
Tested on 16.0, works as expected. problem is in 17.0 and 18.0

**Comment by xxl4** [comment]
when smtp service have any issue, admin plane can't login in odoo 18.
