### ISSUE TITLE
[18.0] Error when adding company_dependent=True to HTML fields

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#185418]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

1. Define any HTML field and add company_dependent=True, for example:

```
html1 = fields.Html(company_dependent=True, sanitize=False)
```

Upon upgrading the module, the following error occurs:

```
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "<" is invalid.
CONTEXT:  JSON data, line 1: <...
```

2. The same error also appears when running the unit test in Odoo core:

```
./odoo-bin -c project.conf -i test_new_api --test-enable
```

### Log Output

```shell
2024-10-26 13:23:58,123 11672 CRITICAL dev-odoo18e-client-test odoo.service.server: Failed to initialize database `dev-odoo18e-client-test`.
Traceback (most recent call last):
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/service/server.py", line 1305, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viper/.pyenv/versions/odoo18-3.12.4/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/modules/loading.py", line 479, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/modules/loading.py", line 204, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/modules/registry.py", line 605, in init_models
    model._auto_init()
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/models.py", line 3406, in _auto_init
    new = field.update_db(self, columns)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/fields.py", line 1085, in update_db
    self.update_db_column(model, column)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/fields.py", line 1121, in update_db_column
    self._convert_db_column(model, column)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/fields.py", line 1761, in _convert_db_column
    sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/tools/sql.py", line 346, in convert_column
    _convert_column(cr, tablename, columnname, columntype, using)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/tools/sql.py", line 370, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/Users/developer/code/odoo/odoo-source/odoo-ce/odoo18/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "<" is invalid.
CONTEXT:  JSON data, line 1: <...
```
```


### Support Ticket

_No response_

**Comment by vmac-odoo** [comment]
Hello @anhvu-sg ,

Thanks for your feedback, but I'm not being able to reproduce this issue.

The database where you found the issue is a clean one or there is more data or custom modules?

If is possible add a video to get the exact steps to reproduce the issue.

Thanks!

**Comment by anhvu-sg** [comment]
Hi @vmac-odoo ,

This is for custom modules; I need to adjust the signature field in the res.users model to support multi-company:

`signature = fields.Html(company_dependent=True)`

I believe that significant changes related to JSONB column handling in v18 might be causing this issue.

Regards
