### ISSUE TITLE
[saas-17] After -i module - ImportError: cannot import name upload_data_thread

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#18542]
Impacted versions:

saas-17

Steps to reproduce:

just run ./odoo-bin -i anymodule -d database once loaded all and in the first visit in the system throught http:

```2017-07-29 07:57:12,398 851 INFO saas17 odoo.models: Computing parent left and right for table ir_ui_menu...
2017-07-29 07:57:12,448 851 INFO saas17 odoo.models: Computing parent left and right for table res_partner_category...
2017-07-29 07:57:12,452 851 INFO saas17 odoo.models: Computing parent left and right for table product_category...
2017-07-29 07:57:12,454 851 INFO saas17 odoo.models: Computing parent left and right for table website_menu...
2017-07-29 07:58:05,090 851 INFO saas17 odoo.addons.base.ir.ir_attachment: filestore gc 3 checked, 0 removed
2017-07-29 07:58:05,109 851 INFO saas17 odoo.addons.base.ir.ir_autovacuum: GC'd 0 user log entries
2017-07-29 08:11:58,815 851 INFO ? werkzeug: 127.0.0.1 - - [29/Jul/2017 08:11:58] "GET /web?debug HTTP/1.1" 500 -
2017-07-29 08:11:58,817 851 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/nhomar/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/nhomar/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/nhomar/odoo/odoo/service/server.py", line 251, in app
    return self.app(e, s)
  File "/home/nhomar/odoo/odoo/service/wsgi_server.py", line 177, in application
    return application_unproxied(environ, start_response)
  File "/home/nhomar/odoo/odoo/service/wsgi_server.py", line 163, in application_unproxied
    result = handler(environ, start_response)
  File "/home/nhomar/odoo/odoo/http.py", line 1293, in __call__
    self.load_addons()
  File "/home/nhomar/odoo/odoo/http.py", line 1314, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/home/nhomar/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 7, in <module>
    
ImportError: cannot import name upload_data_thread
2017-07-29 08:12:03,163 851 INFO saas17 odoo.addons.base.ir.ir_http: Generating routing map

```

Expected behavior:

No error.

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Forget it ... it is an erro on an incorrectly imported OCA module... the fix will be there.
