### ISSUE TITLE
[17.0] account: Unable to print invoice report

### ISSUE THREAD

**Issue by adrip-s73** [odoo/odoo#185673]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

To replicate the problem we have to complete the following steps:
1 - Have the 'account_edi' module installed
2 - Have an invoice which has an edi document
![image](https://github.com/user-attachments/assets/7195308e-bf59-4338-87f6-4cbac8a4fb89)
3 - Print the regular invoice and at this point is where the following error appears
![image](https://github.com/user-attachments/assets/90256c1f-4b08-434a-a9c9-ca66ad821b6d)

We have seen that this error comes from the change made in the following commit [e391863](https://github.com/odoo/odoo/commit/e3918634df50fc76e7f040770be7f4dfc824267d) but reverting the commit does not solve it because the library has been updated, so for now leaving the code in this way has worked for us.
![image](https://github.com/user-attachments/assets/1899afcd-d6c0-45ff-a13d-09b82cae6752)

### Log Output

raceback (most recent call last):
  File "/opt/odoo/src/odoo/odoo/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/src/odoo/odoo/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/src/oca/reporting-engine/report_xlsx_helper/controllers/main.py", line 51, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/opt/odoo/src/odoo/odoo/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/src/oca/reporting-engine/report_xlsx/controllers/main.py", line 51, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/opt/odoo/src/odoo/odoo/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/src/odoo/odoo/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/opt/odoo/src/oca/mis-builder/mis_builder/report/mis_report_instance_qweb.py", line 27, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids, data)
  File "/opt/odoo/src/odoo/odoo/addons/account/models/ir_actions_report.py", line 58, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/opt/odoo/src/oca/report-print-send/base_report_to_printer/models/ir_actions_report.py", line 159, in _render_qweb_pdf
    document, doc_format = super()._render_qweb_pdf(
  File "/opt/odoo/src/odoo/odoo/odoo/addons/base/models/ir_actions_report.py", line 911, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/src/odoo/odoo/addons/sale_pdf_quote_builder/models/ir_actions_report.py", line 15, in _render_qweb_pdf_prepare_streams
    result = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/src/enterprise/zenterprise/zenterprise/account_followup/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    res = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids)
  File "/opt/odoo/src/odoo/odoo/addons/account_edi/models/ir_actions_report.py", line 44, in _render_qweb_pdf_prepare_streams
    writer.write(new_pdf_stream)
  File "/venv/lib/python3.10/site-packages/pypdf/_writer.py", line 1394, in write
    self.write_stream(stream)
  File "/opt/odoo/src/odoo/odoo/odoo/tools/pdf/__init__.py", line 100, in write_stream
    self.add_metadata({
  File "/venv/lib/python3.10/site-packages/pypdf/_writer.py", line 1599, in add_metadata
    assert isinstance(self._info, DictionaryObject)
AssertionError

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/debug/web.assets_web.js:27958:19)
    at decoder.onload (http://localhost:8069/web/assets/debug/web.assets_web.js:27841:25)

**Comment by adrip-s73** [comment]
@xmo-odoo please Can you review this issue ?

**Comment by em230418** [comment]
Workaround until Odoo S.A.'s marketing feature stops producing bugs.

```diff
diff --git a/odoo/tools/pdf/__init__.py b/odoo/tools/pdf/__init__.py
old mode 100644
new mode 100755
index 4db42c32..34f0ebb4
--- a/odoo/tools/pdf/__init__.py
+++ b/odoo/tools/pdf/__init__.py
@@ -97,10 +97,10 @@ if hasattr(PdfWriter, 'write_stream'):
     # >= 2.x has a utility `write` which can open a path, so `write_stream` could be called directly
     class BrandedFileWriter(PdfWriter):
         def write_stream(self, *args, **kwargs):
-            self.add_metadata({
-                '/Creator': "Odoo",
-                '/Producer': "Odoo",
-            })
+#            self.add_metadata({
+#                '/Creator': "Odoo",
+#                '/Producer': "Odoo",
+#            })
             super().write_stream(*args, **kwargs)
 else:
     # 1.x has a monolithic write method
```

**Comment by em230418** [comment]
If it helps. output of pip freeze
```
attrs==24.2.0
babel==2.16.0
blinker==1.4
certifi==2024.8.30
cffi==1.15.0
chardet==5.2.0
charset-normalizer==3.4.0
click==8.0.3
colorama==0.4.4
cryptography==43.0.3
Cython==3.0.11
dbus-python==1.2.18
decorator==5.1.1
distro==1.7.0
distro-info==1.1+ubuntu0.2
docopt==0.6.2
documents==0.0.1
docutils==0.21.2
freetype-py==2.5.1
freezegun==1.5.1
geoip2==2.9.0
gevent==24.11.1
greenlet==3.1.1
httplib2==0.20.2
idna==3.10
importlib-metadata==4.6.4
importmagic3==0.2.0
iotop==0.6
isodate==0.7.2
jedi==0.19.2
jeepney==0.7.1
Jinja2==3.1.4
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libsass==0.20.1
log_colorizer==2.0.0
lxml==5.3.0
lxml_html_clean==0.3.1
MarkupSafe==3.0.2
maxminddb==2.6.2
more-itertools==8.10.0
npm==0.1.1
num2words==0.5.13
oauthlib==3.2.0
optional-django==0.1.0
parso==0.8.4
passlib==1.7.4
pdfminer.six==20240706
pillow==11.0.0
platformdirs==4.3.6
ply==3.11
polib==1.2.0
psutil==6.1.0
psycopg2==2.9.2
pycairo==1.20.1
pycparser==2.21
PyGObject==3.42.1
PyJWT==2.3.0
pyOpenSSL==24.2.1
pyparsing==2.4.7
pypdf==5.1.0
PyPDF2==1.26.0
python-apt==2.4.0+ubuntu4
python-dateutil==2.9.0.post0
python-debian==0.1.43+ubuntu1.1
python-magic==0.4.27
python-stdnum==1.20
pytz==2024.2
PyYAML==5.4.1
qrcode==8.0
reportlab==4.2.5
requests==2.32.3
requests-file==2.1.0
requests-toolbelt==1.0.0
rjsmin==1.2.3
rlPyCairo==0.3.0
SecretStorage==3.3.1
six==1.16.0
spark-parser==1.8.9
ssh-import-id==5.11
systemd-python==234
typing_extensions==4.12.2
ubuntu-drivers-common==0.0.0
unattended-upgrades==0.1
uncompyle6==3.9.2
urllib3==2.2.3
vobject==0.9.8
wadllib==1.3.6
wdb==3.3.0
Werkzeug==2.0.2
xdis==6.1.2
xkit==0.0.0
zeep==4.3.1
zipp==1.0.0
zope.event==5.0
zope.interface==7.1.1
```

**Comment by em230418** [comment]
Python 3.10.12

**Comment by adrip-s73** [comment]
@xmo-odoo When you tried to reproduce the issue, did you have the "account_edi" module installed and an EDI document generated on the invoice?

**Comment by StefanStahl-tec** [comment]
@adrip-s73 
We had a similar problem. However, the main trigger for us was the account_edi_ubl_cii module. Otherwise the same error message.     
We had installed a similar list of Python modules. Odoo 17.0 requires PyPDF2. We had migrated from an old system and therefore still had pypdf (also in version 5.1.0) installed.     

After we uninstalled pypdf and PyPDF2 was still on the server, printing worked again.     

I hope it helps you too.

**Comment by victoralmau** [comment]
Trying different solutions for the error I have found the following:

https://github.com/odoo/odoo/blob/83445d91a588958417fef8a04d1187974d4b3d9a/odoo/tools/pdf/__init__.py#L99

```
# Clear all data but keep the entry in PDF to prevent error
if not self.metadata:
    self.metadata = {}
self.add_metadata({
    '/Creator': "Odoo",
    '/Producer': "Odoo",
})
```

Is this the right solution or should another approach be considered?

I do not understand why this error has appeared now.

**Comment by juwu-odoo** [comment]
Hello all,

It seems that this issue is being caused by a change introduced in pypdf 5.0.0. Odoo currently imports PyPDF2/pypdf in this order:
> PyPDF2 v2.x > pypdf > PyPDF2 v1.x

So you will encounter this issue if you have the `PyPDF2==1.26.0` and `pypdf>=5.0.0` packages installed at the same time.

There are currently two workarounds without having to change the base code:
1. Downgrade pypdf to 4.3.1 by running `pip install pypdf==4.3.1`
or
2. Upgrade PyPDF2 to 2.12.1 by running `pip install PyPDF2==2.12.1`


@xmo-odoo We also have two tickets with this issue if you'd like to follow it internally:
opw-4372052
opw-4426881

Thanks!
