### ISSUE TITLE
No header on reports

### ISSUE THREAD

**Issue by zitycard** [odoo/odoo#18600]
Impacted versions: Enterprise 10

Steps to reproduce: I try to generate a report (any kind of it) and the header never appears.

Current behavior: The report is generated perfectly except because it doeesn't have header. The footer appears correctly.

Expected behavior: The header should appear.

I have added on System Parameters the report.url key and the web.base.url
I have also update wkhtmltopdf to the lattest version I found (0.12.4)

**Comment by Yenthe666** [comment]
Hi @zitycard,

Thank you for your report.
It is however not adviced to use `wkhtmltopdf` 0.12.2 or up (as you can see in our guidelines at https://github.com/odoo/odoo/wiki/Wkhtmltopdf).
Please change your `wkhtmltopdf` to version 0.12.1.x and try again.

Regards,
Yenthe

**Comment by zitycard** [comment]
I was using at first the 0.12.1, but I read on https://github.com/odoo/odoo/issues/9487 that on 0.12.4 it would work good. But in fact I have the same result with both versions

**Comment by Yenthe666** [comment]
Hmm is there custom development (on the reports)? Have you tried updating your Odoo to the latest source code?

**Comment by zitycard** [comment]
[Vista previa Reporte Externo.pdf](https://github.com/odoo/odoo/files/1193004/Vista.previa.Reporte.Externo.pdf)
That is what I get with the preview, so no custom develpment. Odoo installation has like 2 - 3 months.

**Comment by Yenthe666** [comment]
Hmm can you first try to update your source code and do a `-u all` please?

**Comment by zitycard** [comment]
I think I have update everything (I just click the Update option on the Applications module). If there is another way, please told me.
What I get from the -u all is:
2017-08-02 08:13:47,808 23836 INFO ? odoo: Odoo version 10.0
2017-08-02 08:13:47,808 23836 INFO ? odoo: addons paths: ['/root/.local/share/Odoo/addons/10.0', u'/odoo/odoo-server/odoo/addons', u'/odoo/odoo-server/addons']
2017-08-02 08:13:47,809 23836 INFO ? odoo: database: default@default:default
2017-08-02 08:13:47,813 23836 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 251, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by Yenthe666** [comment]
Hi @zitycard,

You need to update your Odoo environment with a `git fetch origin` and `git reset` (if you're on linux). You're not updating to the latest source code the way you mentioned above. On a sidenote: your `[Errno 98]` is going off because you haven't stopped your Odoo service first. You can do this with `sudo service odoo-server stop`

**Comment by zitycard** [comment]
Thank you for the information about how to update.
After that, what I get from -u all is:
2017-08-02 10:15:27,237 24722 INFO ? odoo: Odoo version 10.0
2017-08-02 10:15:27,238 24722 INFO ? odoo: addons paths: ['/root/.local/share/Odoo/addons/10.0', u'/odoo/odoo-server/odoo/addons', u'/odoo/odoo-server/addons']
2017-08-02 10:15:27,238 24722 INFO ? odoo: database: default@default:default
2017-08-02 10:15:27,243 24722 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 251, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args

**Comment by zitycard** [comment]
Hi @Yenthe666,
I will appreciate some answer as soon as possible.
Thank you in advance

**Comment by Yenthe666** [comment]
@zitycard can you give the last part of the stacktrace? I believe the real error is there 😉

**Comment by zitycard** [comment]
The lines that appear when I generate the external report preview. 

~~~
 2017-08-07 06:28:58,551 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:28:58] "POST /web/dataset/call_kw/base.config.settings/create HTTP/1.0" 200 -
2017-08-07 06:28:58,621 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:28:58] "POST /web/dataset/call_kw/base.config.settings/search_read HTTP/1.0" 200 -
2017-08-07 06:28:58,733 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:28:58] "POST /web/action/load HTTP/1.0" 200 -
2017-08-07 06:28:58,819 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:28:58] "POST /report/check_wkhtmltopdf HTTP/1.0" 200 -
2017-08-07 06:29:01,171 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:29:01] "POST /report/download HTTP/1.0" 200 -
2017-08-07 06:29:01,928 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [07/Aug/2017 06:29:01] "POST /web/dataset/call_kw/base.config.settings/search_read HTTP/1.0" 200 -
~~~

**Comment by Yenthe666** [comment]
@zitycard no problem there. What is your `report.url` and `web.base.url` parameter by the way? Does it match the Odoo including the port number?

**Comment by zitycard** [comment]
Yes, both of them match with the values they should have.

**Comment by zitycard** [comment]
@Yenthe666 any idea of what can cause that error?

**Comment by Yenthe666** [comment]
Hmm, no, not directly anymore. @mart-e do you have another idea?

**Comment by mart-e** [comment]
I do not know for the 0.12.4 but please check your version of wkhtmtopdf, see our warning about it [in the documentation](https://www.odoo.com/documentation/10.0/setup/install.html#enterprise).
If you are on Debian, we have published a binary.

Sorry but without errors, it is hard to help more, it is a guess game.

**Comment by zitycard** [comment]
Okey, I delete and reinstall the 0.12.1 version of wkhtmltopdf.
What I get from -u all is:

~~~
2017-08-08 11:08:45,963 342 INFO ? odoo: Odoo version 10.0
2017-08-08 11:08:45,964 342 INFO ? odoo: addons paths: ['/root/.local/share/Odoo/addons/10.0', u'/odoo/odoo-server/odoo/addons', u'/odoo/odoo-server/addons']
2017-08-08 11:08:45,964 342 INFO ? odoo: database: default@default:default
2017-08-08 11:08:45,969 342 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 251, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
~~~
And what I get on the log file when I generate the external preview is

~~~
2017-08-08 11:10:28,808 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [08/Aug/2017 11:10:28] "POST /web/action/load HTTP/1.0" 200 -
2017-08-08 11:10:28,907 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [08/Aug/2017 11:10:28] "POST /report/check_wkhtmltopdf HTTP/1.0" 200 -
2017-08-08 11:10:28,925 1879 INFO ? werkzeug: 192.168.0.100 - - [08/Aug/2017 11:10:28] "GET /web/static/src/img/spin.png HTTP/1.0" 200 -
2017-08-08 11:10:29,460 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [08/Aug/2017 11:10:29] "POST /report/download HTTP/1.0" 200 -
2017-08-08 11:10:30,398 1879 INFO pruebaConstrain werkzeug: 192.168.0.100 - - [08/Aug/2017 11:10:30] "POST /web/dataset/call_kw/base.config.settings/search_read HTTP/1.0" 200 -
~~~

**Comment by frankmtf** [comment]
Hello, 
I have the same problem. No header on my reports. I use odoo 10 CE
