### ISSUE TITLE
Odoo 10.0 CE - Calendar view Uncaught TypeError: Cannot read property '_week' of undefined

### ISSUE THREAD

**Issue by bnjroos** [odoo/odoo#18618]
Impacted versions: 10.0

Steps to reproduce: Installed Odoo on VPS and few Apps

Current behavior: When going to "Calendar View" I am getting the following error: 
```
Uncaught TypeError: Cannot read property '_week' of undefined

https://xxxx/web/content/791-7d70572/web.assets_backend.js:10831
Traceback:
TypeError: Cannot read property '_week' of undefined
    at get_fc_defaultOptions (https://xxxx/web/content/791-7d70572/web.assets_backend.js:10831:238)
    at Class.init_calendar (https://xxxx/web/content/791-7d70572/web.assets_backend.js:10847:165)
    at Class._do_show_init (https://xxxx/web/content/791-7d70572/web.assets_backend.js:10844:67)
    at fire (https://xxxx/web/content/251-ff1319d/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://xxxx/web/content/251-ff1319d/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) [as resolve] (https://xxxx/web/content/251-ff1319d/web.assets_common.js:548:56)
    at Class.do_show (https://xxxx/web/content/791-7d70572/web.assets_backend.js:10898:69)
    at Class.prototype.(anonymous function) [as do_show] (https://xxxx/web/content/251-ff1319d/web.assets_common.js:3010:559)
    at Class._display_view (https://xxxx/web/content/791-7d70572/web.assets_backend.js:1700:354)
    at Array.<anonymous> (https://xxxx/web/content/791-7d70572/web.assets_backend.js:1699:99)
```
It seems to come from the following line in the JS code:` firstDay:moment._locale._week.dow`

Any idea on how to resolve that ?

TIA

**Comment by Yenthe666** [comment]
Hi @bnjroos,

Thank you for your report.
I've just tested this on the newest Odoo 10 CE without any problems.
Can you reproduce this on an official Odoo instance? (runbot.odoo.com) from when is this Odoo installation? Have you updated it to the latest source code yet?

Regards,
Yenthe

**Comment by bnjroos** [comment]
Sorry Yenthe for the late answer, it was on a fresh Odoo 10 CE install on ubuntu server on which I installed apps.

**Comment by bnjroos** [comment]
Found the solution myself:

- Go to your odoo installation folder
- `cd /addons/web_calendar/static/src/js`
- edit web_calendar.js line 57 by replacing moment._locale._week.dow by moment()._locale._week.dow

This should fix the issue. I don't know why it was not working before.
