### ISSUE TITLE
[18.0] report template references a 'memo' field that doesn't exist in the 'account.move' model

### ISSUE THREAD

**Issue by QLFIT** [odoo/odoo#186189]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Go to sales - Orders - create new sales order normally ..
Add item then Conform - Click delivery from top - Validate the quantity & Confirm
Clock on sales order S00099 - Create invoice - Regular invoice - create Draft
Click confirm - then click Pay - Choose Cash - Create Payment
Click Payments from Top - Validate 

Here it comes: Click the Engine icon to choose "Payment Receipt"

Error:
RPC_ERROR

### Log Output

```shell
RPC_ERROR

Odoo Server Error

Occured on t011.odoo.com on 2024-11-04 17:08:08 GMT

Traceback (most recent call last):
  File "<1021>", line 933, in template_1021
  File "<1021>", line 915, in template_1021_content
  File "<1021>", line 689, in template_1021_t_call_0
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_qweb.py", line 2425, in _get_field
    field = record._fields[field_name]
            ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'memo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/addons/web/controllers/report.py", line 120, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1012, in _render_qweb_pdf
    collected_streams, report_type = self._pre_render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_actions_report.py", line 77, in _pre_render_qweb_pdf
    return super()._pre_render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1003, in _pre_render_qweb_pdf
    return self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids), 'pdf'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/sale_pdf_quote_builder/models/ir_actions_report.py", line 19, in _render_qweb_pdf_prepare_streams
    result = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/enterprise/18.0/account_followup/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    res = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/purchase/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_actions_report.py", line 25, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 853, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, all_res_ids_wo_stream, data=data)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1091, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 770, in _render_template
    return view_obj._render_template(template, values).encode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_ui_view.py", line 2187, in _render_template
    return self.env['ir.qweb']._render(template, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/tools/profiler.py", line 306, in _tracked_method_render
    return method_render(self, template, values, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_qweb.py", line 600, in _render
    result = ''.join(rendering)
             ^^^^^^^^^^^^^^^^^^
  File "<1022>", line 84, in template_1022
  File "<1022>", line 66, in template_1022_content
  File "<1022>", line 54, in template_1022_t_call_0
  File "<1021>", line 941, in template_1021
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'memo'
Template: account.report_payment_receipt_document
Path: /t/t/div[1]/table/tbody/t/t/tr[2]/td[3]/span
Node: <span t-field="payment.move_id.memo"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://t011.odoo.com/web/assets/4f4ee3a/web.assets_web.min.js:3072:163)
        at decoder.onload (https://t011.odoo.com/web/assets/4f4ee3a/web.assets_web.min.js:3058:7)
```

**Comment by QLFIT** [comment]
Issue:

When attempting to print a payment receipt in Odoo, users may encounter the following error:

`KeyError: 'memo'`

This error occurs because the report template references a 'memo' field that doesn't exist in the `'account.move' model.`

**Solution:**
To resolve this issue, modify the report template to reference the 'narration' field instead.

Steps to Implement the Solution:

Activate Developer Mode:

Log in to your Odoo instance.
Click on your user name in the top-right corner.
Select About from the dropdown menu.
In the dialog that appears, click on Activate the developer mode.
Access the Report Template:

Navigate to Settings > Technical > User Interface > Views.
In the search bar, enter 'report_payment_receipt_document' to locate the specific report template.
Edit the Template:

Open the 'account.report_payment_receipt_document' view.

Locate the line containing <span t-field="payment.move_id.memo"/>.

Replace payment.move_id.memo with payment.move_id.narration.

The updated line should read: 
<span t-field="payment.move_id.narration"/>.

Save and Test:

Save the changes to the template.
Attempt to print the payment receipt again to ensure the error is resolved.

By making this change, the report will reference the 'narration' field, which is present in the 'account.move' model, thereby preventing the KeyError related to the missing 'memo' field.

Disclaimer: Modifying Odoo's internal templates can have unintended consequences. It's recommended to back up your system before making changes. If you're not comfortable making these changes directly, consider consulting with a developer or reaching out to Odoo support for assistance.

QLF IT

**Comment by jpolin-dev** [comment]
This looks like an actual bug and the solution provided is a workaround, can we reopen this issue?

**Comment by QLFIT** [comment]
> This looks like an actual bug and the solution provided is a workaround, can we reopen this issue?

Done.
