### ISSUE TITLE
[SAAS-17] lead automation diagram view totally broken

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#18675]
Impacted versions:

saas-17 and above

Steps to reproduce:

- Install lead automation demo module.
- Go to the record created.
- Open one item (the second one).
- Try to see the diagram view.

Current behavior:

An error occurred:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 679, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 335, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/service/model.py", line 102, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 328, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 923, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/http.py", line 508, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/addons/web_diagram/controllers/main.py", line 41, in get_diagram_info
    des_node, label, (140, 180))
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/addons/base/ir/ir_ui_view.py", line 1146, in graph_get
    g.process(start)
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/tools/graph.py", line 680, in process
    self.rank()   # First step:Netwoek simplex algorithm
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/tools/graph.py", line 621, in rank
    self.normalize()
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/tools/graph.py", line 262, in normalize
    least_rank = min(x['x'] for x in pycompat.values(self.result.values))
  File "/home/odoo/runbot/extra/runbot/static/build/251342-saas-17-8ad872/odoo/tools/pycompat.py", line 13, in <lambda>
    values = lambda d: iter(d.itervalues())
AttributeError: 'builtin_function_or_method' object has no attribute 'itervalues'
```

Expected behavior:

Show properly the diagram view.

Video/Screenshot link (optional):

Runbot tested:

Record open.

![image](https://user-images.githubusercontent.com/338634/28953003-bb6f2cc0-789a-11e7-8b5b-d48f540d9e2e.png)

![image](https://user-images.githubusercontent.com/338634/28953015-cc4f656e-789a-11e7-81e8-f8ebc59ff0ee.png)

**Comment by Yenthe666** [comment]
Hi @nhomar,

Thanks a lot for the bug report.
This has been fixed in V10 in the meanwhile and shouldn't be a problem anymore:
![image](https://user-images.githubusercontent.com/6352350/36198551-2e0fddcc-1177-11e8-917d-7166c2f73b27.png)

I think you do agree that this can be closed.

Regards,
Yenthe
