### ISSUE TITLE
[18.0] Base: Company-dependent fields with translation enabled cause KeyError

### ISSUE THREAD

**Issue by safi-ibrahim-95** [odoo/odoo#186784]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

1. Extend the res.partner model as follows:
```py
  class ResPartner(models.Model):
      _inherit = 'res.partner'
      _check_company_auto = True
  
      code_company = fields.Char(company_dependent=True, translate=True)
```
2. Display the code_company field in the form view XML.
3. Enter text in the code_company field.
4. Save the record, then click the 'EN' language button next to the code_company field to start translating it.

### Current Behavior

- An exception occurs: KeyError: 'en_US'.
- After refreshing the page, the value disappears from the form but still exists in the database.

### Expected Behavior

- A wizard should open, allowing the user to translate the field into another language.

### Additional Context

- Screenshot from the database showing the saved field value:

![image](https://github.com/user-attachments/assets/a866527f-2a59-4370-8d88-24c225dbd821)

PS: when i refresh the page the value disappear  but it still exist in the database

### Log Output

```shell
RPC_ERROR

Odoo Server Error

Occured on localhost:8018 on model res.partner and id 15 on 2024-11-08 12:57:47 GMT

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1954, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1921, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2168, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 35, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 517, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3943, in get_field_translations
    val_en = self_lang.with_context(lang='en_US')[field_name]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6978, in __getitem__
    return self._fields[key].__get__(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1262, in __get__
    recs._fetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4037, in _fetch_field
    self.fetch(fnames)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4074, in fetch
    fetched = self._fetch_query(query, fields_to_fetch)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4178, in _fetch_query
    self.env.cache.insert_missing(fetched, field, values)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1242, in insert_missing
    **dict.fromkeys(langs, val['en_US']),  # fallback missing lang to en_US
                           ~~~^^^^^^^^^
KeyError: 'en_US'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost:8018/web/assets/209cc4a/web.assets_web_dark.min.js:947:101)
        at App.handleError (http://localhost:8018/web/assets/209cc4a/web.assets_web_dark.min.js:1579:29)
        at ComponentNode.initiateRender (http://localhost:8018/web/assets/209cc4a/web.assets_web_dark.min.js:1037:19)

Caused by: RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:8018/web/assets/209cc4a/web.assets_web_dark.min.js:3061:163)
        at XMLHttpRequest.<anonymous> (http://localhost:8018/web/assets/209cc4a/web.assets_web_dark.min.js:3066:13)
```

**Comment by willcoderwang** [comment]
I don't think company_dependent fields can be translated.
Please check file `odoo/fields.py`
`        if attrs.get('company_dependent'):
            if attrs.get('required'):
                warnings.warn(f"company_dependent field {self} cannot be required")
            if attrs.get('translate'):
                warnings.warn(f"company_dependent field {self} cannot be translated")`

**Comment by safi-ibrahim-95** [comment]
@willcoderwang 
I thought it was supported after I saw the change of the company dependent to a JSONB field and how it's stored. However, the behavior of throwing an exception error when pressing the translated button is still not good.
