### ISSUE TITLE
[18.0] project: Consistent test failure in Odoo.sh for subtasks check on tours

### ISSUE THREAD

**Issue by hwangh95** [odoo/odoo#186909]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Install project_enterprise on Odoo.sh and run tests on project, it will always fail at step 53 in the project_tour.

### Log Output

```shell
FAILED: [53/54] Tour project_tour → Step Close the sub-tasks list (trigger: .o_kanban_record .o_widget_subtask_counter .subtask_list_button:contains('1/2')).
The cause is that trigger (.o_kanban_record .o_widget_subtask_counter .subtask_list_button:contains('1/2')) element cannot be found in DOM. TIP: You can use :not(:visible) to force the search for an invisible element.
TIMEOUT: The step failed to complete within 10000 ms.

...

FAIL: TestProjectUpdateUi.test_01_project_tour
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/project/tests/test_project_update_ui.py", line 18, in test_01_project_tour
    self.start_tour("/odoo", 'project_tour', login="admin")
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2066, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, success_signal="tour succeeded", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2048, in browser_js
    self.fail('%s\n\n%s' % (message, error))
AssertionError: The test code "odoo.startTour('project_tour', {"stepDelay": 0, "keepWatchBrowser": false, "debug": false, "startUrl": "/odoo"})" failed

FAILED: [53/54] Tour project_tour → Step Close the sub-tasks list (trigger: .o_kanban_record .o_widget_subtask_counter .subtask_list_button:contains('1/2')).
The cause is that trigger (.o_kanban_record .o_widget_subtask_counter .subtask_list_button:contains('1/2')) element cannot be found in DOM. TIP: You can use :not(:visible) to force the search for an invisible element.
TIMEOUT: The step failed to complete within 10000 ms.
```

**Comment by FerCalatayud** [comment]
I have a similar error with test error on the project_todo module.

https://github.com/odoo/odoo/issues/192995

**Comment by xavierbol** [comment]
Hello @hwangh95 

Sorry for the delay. I cannot reproduce the issue, maybe the issue is fixed now. 🤷‍♂️

**Comment by zim0101** [comment]
I have had a similar test failure while building on odoo.sh. (odoo 18, development stage)

```
FAILED: [9/27] Tour mail_template_dynamic_placeholder_tour → Step Wait for the drop down to disappear (trigger: div[name="model_id"] .o-autocomplete:not(:has(.ui-autocomplete))).
Element (div[name="model_id"] .o-autocomplete:not(:has(.ui-autocomplete))) has not been found.
TIMEOUT: The step failed to complete within 10000 ms.
```

```
FAIL: TestMailTemplateUI.test_mail_template_dynamic_placeholder_tour
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/mail/tests/test_mail_template.py", line 422, in test_mail_template_dynamic_placeholder_tour
    self.start_tour("/odoo", 'mail_template_dynamic_placeholder_tour', login="admin")
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2087, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, timeout=timeout, success_signal="tour succeeded", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2063, in browser_js
    self.fail('%s\n\n%s' % (message, error))
AssertionError: The test code "odoo.startTour('mail_template_dynamic_placeholder_tour', {"stepDelay": 0, "keepWatchBrowser": false, "debug": false, "startUrl": "/odoo", "delayToCheckUndeterminisms": 0})" failed

FAILED: [9/27] Tour mail_template_dynamic_placeholder_tour → Step Wait for the drop down to disappear (trigger: div[name="model_id"] .o-autocomplete:not(:has(.ui-autocomplete))).
Element (div[name="model_id"] .o-autocomplete:not(:has(.ui-autocomplete))) has not been found.
TIMEOUT: The step failed to complete within 10000 ms.
```

My odoo dependencies are:

```
'depends': ['base', 'hr', 'hr_attendance', 'mail']
```

I have some invisible fields in some of my views, can that be an issue here?
