### ISSUE TITLE
Unable to print full receipt using EOM-POS thermal printer when receipt markup includes font='b'

### ISSUE THREAD

**Issue by cjlpowers** [odoo/odoo#18698]
Impacted versions:
Odoo 10
PosBox v16 (patched to commit 40197b38e550acc5ad9091096bbefd8a5291858d)

Steps to reproduce:
Use [EOM-POS (EOM-200) thermal printer](https://www.amazon.com/dp/B00WTTYP42/ref=twister_B01LMF1RGW?_encoding=UTF8&psc=1) with Odoo (via PosBox) and try printing a receipt via **Print Receipt** button.

Current behavior:
Printed receipt is not complete, it only contains the header logo.

Expected behavior:
The full receipt is printed.

Source of the Issue:
I have been able to track this problem down to the presence of **font='b'** in [this div](https://github.com/odoo/odoo/blob/cfc2a55c0678ce45b1c6b22fde68ea55760dcab3/addons/point_of_sale/static/src/xml/pos.xml#L702). If I remove that **font** attribute from the request made to **/hw_proxy/print_xml_receipt**, I get the fully printed receipt. The other printing functions (kitchen/orders, summary receipts, etc.) work as expected and are not impacted by this problem. This may not be a surprise because they do not contain the **font='b'** attribute in their payloads. Interestingly, the other print outputs control font weight without using the **font='b'** attribute so not sure what the right solution is here. Any idea why this might be happening or ways to work around it though configuration/settings?

**PosBox odoo-server.log**
These logs were taken during a period where receipts, orders, and summaries were being printed to investigate the issue. The printer responded to every attempt to print and was successful except for the issue described above. The printer would respond within 2-7 seconds of the request to print. Odoo Pos and PosBox were connected over a Wireless Network. Printer was connected to PosBox via USB. EOM-POS scanner and cash drawer worked during this period without issue.

>2017-08-05 21:17:32,237 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:17:39,265 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:25:15,983 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:25:25,057 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:49:05,859 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:49:12,909 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(32, 'Pipe error')
2017-08-05 21:49:21,330 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:49:28,872 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(32, 'Pipe error')
2017-08-05 21:49:41,336 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:49:49,395 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:52:15,124 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:52:23,156 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:52:33,969 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:52:42,014 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:53:09,583 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: ESC/POS Error: [Errno 110] Operation timed out
2017-08-05 21:53:09,584 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: [Errno 110] Operation timed out
Traceback (most recent call last):
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 171, in run
    printer.receipt(data)
  File "/home/pi/odoo/addons/hw_escpos/escpos/escpos.py", line 710, in receipt
    self.text(errmsg)
  File "/home/pi/odoo/addons/hw_escpos/escpos/escpos.py", line 826, in text
    self._raw(txt)
  File "/home/pi/odoo/addons/hw_escpos/escpos/printer.py", line 85, in _raw
    if len(msg) != self.device.write(self.out_ep, msg, self.interface, timeout=5000):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 633, in write
    self.__get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 771, in bulk_write
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 872, in __write
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 571, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
USBError: [Errno 110] Operation timed out
2017-08-05 21:53:11,615 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:53:20,982 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:54:07,959 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:54:15,532 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(32, 'Pipe error')
2017-08-05 21:57:46,142 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:57:54,178 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:58:13,657 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')
2017-08-05 21:58:21,511 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(32, 'Pipe error')
2017-08-05 21:59:02,514 1144 ERROR ? openerp.addons.hw_escpos.controllers.main: Can not get printer description: USBError(110, 'Operation timed out')

**lsusb -v output:**
                
>Bus 001 Device 023: ID 0485:7541 Nokia Monitors 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0485 Nokia Monitors
  idProduct          0x7541 
  bcdDevice            1.00
  iManufacturer           1 Texas Instruments
  iProduct                2 Generic Bulk Device
  iSerial                 3 12345678
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          5 Bulk Data Configuration
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0001
  Self Powered
Bus 001 Device 004: ID 05fe:1010 Chic Technology Corp. Optical Wireless
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x05fe Chic Technology Corp.
  idProduct          0x1010 Optical Wireless
  bcdDevice            0.01
  iManufacturer           1 WIT Electron Company
  iProduct                2 WIT 122-UFS V7.03
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      63
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               3
Device Status:     0x0000
  (Bus Powered)
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0xec00 SMSC9512/9514 Fast Ethernet Adapter
  bcdDevice            2.00
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           39
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol    255 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         2 TT per port
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0x9514 
  bcdDevice            2.00
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      1 Single TT
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      2 TT per port
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             5
  wHubCharacteristic 0x000d
    Per-port power switching
    Compound device
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent      1 milli Ampere
  DeviceRemovable    0x02
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
   Port 2: 0000.0303 lowspeed power enable connect
   Port 3: 0000.0103 power enable connect
   Port 4: 0000.0100 power
   Port 5: 0000.0100 power
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         0 Full speed (or root) hub
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            4.04
  iManufacturer           3 Linux 4.4.26-v7+ dwc_otg_hcd
  iProduct                2 DWC OTG Controller
  iSerial                 1 3f980000.usb
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             1
  wHubCharacteristic 0x0008
    Ganged power switching
    Per-port overcurrent protection
    TT think time 8 FS bits
  bPwrOn2PwrGood        1 * 2 milli seconds
  bHubContrCurrent      0 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
Device Status:     0x0001
  Self Powered

**Comment by cjlpowers** [comment]
I now believe this is a limitation of the EOM-POS printer. The [printer specifications](http://eompos.com/wp-content/uploads/2016/02/EOM-200-manual-2-16-2016.pdf) only mention font A in the supported character set. So that may be why **font='b'** was causing a problem.
