### ISSUE TITLE
Re :: werkzeug Issue , unable to start the application !!

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [odoo/odoo#18704]
Impacted versions: v 10.0

Steps to reproduce: Just try hit main odoo server url for instance:: http://localhost:8069

Current behavior: Error on the main screen::  "Internal Server Error"
Note: The installation, I followed in my local machine (Ubuntu 16.04) was tried in cloud instance (Ubuntu 16.04), everything was working fine in local instance but unable to access the application cloud instance.

**Error Log ::** 
```
2017-08-07 05:51:28,610 6296 INFO ? odoo.service.server: Initiating shutdown
2017-08-07 05:51:28,610 6296 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2017-08-07 05:51:30,126 7327 INFO ? odoo: Odoo version 10.0
2017-08-07 05:51:30,126 7327 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2017-08-07 05:51:30,126 7327 INFO ? odoo: addons paths: [u'/odoo/odoo-server/addons', u'/odoo/custom/addons', '/odoo/odoo-server/odoo/addons']
2017-08-07 05:51:30,126 7327 INFO ? odoo: database: odoo@default:default
2017-08-07 05:51:30,132 7327 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-08-07 05:52:33,581 7327 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2017-08-07 05:52:33,800 7327 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2017-08-07 05:52:33,907 7327 INFO ? werkzeug: 182.74.142.2 - - [07/Aug/2017 05:52:33] "GET / HTTP/1.1" 500 -
2017-08-07 05:52:33,909 7327 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1307, in __call__
    self.load_addons()
  File "/odoo/odoo-server/odoo/http.py", line 1316, in load_addons
    for module in sorted(os.listdir(str(addons_path))):
OSError: [Errno 2] No such file or directory: '/odoo/custom/addons'
2017-08-07 05:52:34,817 7327 INFO ? werkzeug: 182.74.142.2 - - [07/Aug/2017 05:52:34] "GET /favicon.ico HTTP/1.1" 500 -
2017-08-07 05:52:34,822 7327 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1445, in dispatch
    explicit_session = self.setup_session(httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1342, in setup_session
    session_gc(self.session_store)
  File "/odoo/odoo-server/odoo/tools/func.py", line 23, in __get__
    value = self.fget(obj)
  File "/odoo/odoo-server/odoo/http.py", line 1293, in session_store
    path = odoo.tools.config.session_dir
  File "/odoo/odoo-server/odoo/tools/config.py", line 600, in session_dir
    os.makedirs(d, 0700)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/lib/odoo'
```
DB configuration  : 
1) Created user with name 'odoo'
2) Gave complete priviliges on DB,though !!.

Any suggestion, please.

Regards,
Sai.

**Comment by Yenthe666** [comment]
@skalyanapu-mtuity the last part of your log says exactly what is wrong: you don't have enough rights to make directories in `/var/lib/odoo`. This is basically an implementation error, just rectify the rights so you can write in the directory.

**Comment by cierek** [comment]
sudo chmod permissions /var/lib/odoo

**Comment by Yenthe666** [comment]
As there has been no response by the creator in months and as it is clear this is an implementation issue I'm closing this.

**Comment by vasanthjagani** [comment]
for the first time i am using odoo ...
i got some erros how i rectify these errors....
please guide me
vasanth@ubuntu:~/odoo/odoo9$ ./odoo.py
2019-02-17 07:15:49,862 3342 INFO ? openerp: OpenERP version 9.0c
2019-02-17 07:15:49,863 3342 INFO ? openerp: addons paths: ['/home/vasanth/.local/share/Odoo/addons/9.0', u'/home/vasanth/odoo/odoo9/openerp/addons', u'/home/vasanth/odoo/odoo9/addons']
2019-02-17 07:15:49,863 3342 INFO ? openerp: database: default@default:default
2019-02-17 07:15:50,164 3342 INFO ? openerp.service.server: HTTP service (werkzeug) running on ubuntu:8069
2019-02-17 07:15:57,560 3342 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2019-02-17 07:15:57,574 3342 INFO ? openerp.sql_db: Connection to the database failed
2019-02-17 07:15:57,575 3342 ERROR ? openerp.addons.bus.models.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/home/vasanth/odoo/odoo9/addons/bus/models/bus.py", line 168, in run
    self.loop()
  File "/home/vasanth/odoo/odoo9/addons/bus/models/bus.py", line 146, in loop
    with openerp.sql_db.db_connect('postgres').cursor() as cr:
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 643, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 526, in _locked
    return fun(self, *args, **kwargs)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 594, in borrow
    **connection_info)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: fe_sendauth: no password supplied

2019-02-17 07:15:58,201 3342 INFO ? openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2019-02-17 07:15:58,451 3342 INFO ? openerp.http: HTTP Configuring static files
2019-02-17 07:15:58,457 3342 INFO ? openerp.sql_db: Connection to the database failed
2019-02-17 07:15:58,459 3342 INFO ? werkzeug: 127.0.0.1 - - [17/Feb/2019 07:15:58] "GET / HTTP/1.1" 500 -
2019-02-17 07:15:58,490 3342 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vasanth/odoo/odoo9/openerp/service/server.py", line 247, in app
    return self.app(e, s)
  File "/home/vasanth/odoo/odoo9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/vasanth/odoo/odoo9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1515, in __call__
    return self.dispatch(environ, start_response)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1489, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1651, in dispatch
    self.setup_db(httprequest)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1575, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1730, in db_monodb
    dbs = db_list(True, httprequest)
  File "/home/vasanth/odoo/odoo9/openerp/http.py", line 1703, in db_list
    dbs = openerp.service.db.list_dbs(force)
  File "/home/vasanth/odoo/odoo9/openerp/service/db.py", line 323, in list_dbs
    with closing(db.cursor()) as cr:
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 643, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 526, in _locked
    return fun(self, *args, **kwargs)
  File "/home/vasanth/odoo/odoo9/openerp/sql_db.py", line 594, in borrow
    **connection_info)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: fe_sendauth: no password supplied

**Comment by fanstar** [comment]
Test start "./odoo-bin" by root user is work!

**Comment by eGitHub19** [comment]
> Test start "./odoo-bin" by root user is work!

This is does not work for me ! other suggestions ?
