### ISSUE TITLE
[16.0] hr: recent changes mean billing users without hr access can no longer access many many documents

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#187811]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

@mart-e Since this commit https://github.com/odoo/odoo/commit/7050c6972fa23005e58ead618c91671a5c7c034a any users who do no have hr.group_hr_user access rights are unable to open any document (invoice, purchase, bank rec) if it contains any employee bank account. Any list view with bank accounts fail as well if a single record is an employee.

If a shell session is opened, it does work (kind of - if you are paying someone you actually need to see their bank account), but always traceback in web ui.

Steps to reproduce
Create a bank statement line to an employee.
Login as a user without hr.group_hr_user
Attempt to open.

### Log Output

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/src/odoo/odoo/http.py", line 1652, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/odoo/src/odoo/odoo/http.py", line 1679, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/src/odoo/odoo/http.py", line 1883, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/src/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/odoo/src/odoo-cloud-platform/monitoring_log_requests/models/ir_http.py", line 21, in _dispatch
    response = super()._dispatch(endpoint)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/src/odoo/odoo/http.py", line 734, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/src/odoo/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/odoo/src/odoo/odoo/models.py", line 5039, in search_read
    result = records.read(fields, **read_kwargs)
  File "/odoo/src/odoo/odoo/models.py", line 3003, in read
    return self._read_format(fnames=fields, load=load)
  File "/odoo/src/odoo/odoo/models.py", line 3184, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/odoo/src/odoo/odoo/fields.py", line 3009, in convert_to_read
    return (value.id, value.sudo().display_name)
  File "/odoo/src/odoo/odoo/fields.py", line 1219, in __get__
    raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign res.partner.bank(2941, 1598, 1531).display_name
```

### Support Ticket

opw-to-come odoo support down

**Comment by pedrobaeza** [comment]
Which PR?
