### ISSUE TITLE
[10.0][l10n_it] Failing reconciliation test

### ISSUE THREAD

**Issue by WohthaN** [odoo/odoo#18845]
Impacted versions:
10.0 @ 08886028 (and at least 4 weeks back in time...)

Steps to reproduce:
```
git clone https://github.com/odoo/odoo.git odoo
cd odoo
git checkout 08886028317bee684adca5d4850a7127a829e673  #if necessary
./odoo-bin --addons-path=./addons/ --log-level=test --logfile=/dev/stdout --stop-after-init --test-enable -d test --init=base_vat,base_iban,l10n_it
```
where test is a not-yet-created database.

Current behavior:
Test fails with:
```
ERROR test odoo.addons.account.tests.test_reconciliation: ERROR
INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_chf_transaction_chf (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_eur_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_usd (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
INFO test odoo.addons.account.tests.test_reconciliation: ======================================================================
ERROR test odoo.addons.account.tests.test_reconciliation: ERROR: test_statement_euro_invoice_usd_transaction_euro_full (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
ERROR test odoo.addons.account.tests.test_reconciliation: Traceback (most recent call last):
ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/addons/account/tests/test_reconciliation.py", line 252, in test_statement_euro_invoice_usd_transaction_euro_full
ERROR test odoo.addons.account.tests.test_reconciliation: `     self.assertTrue(invoice_rec_line.reconciled, 'The invoice should be totally reconciled')
ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/odoo/fields.py", line 864, in __get__
ERROR test odoo.addons.account.tests.test_reconciliation: `     record.ensure_one()
ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/odoo/models.py", line 4822, in ensure_one
ERROR test odoo.addons.account.tests.test_reconciliation: `     raise ValueError("Expected singleton: %s" % self)
ERROR test odoo.addons.account.tests.test_reconciliation: ` ValueError: Expected singleton: account.move.line(125, 124)
INFO test odoo.addons.account.tests.test_reconciliation: Ran 12 tests in 26.484s
ERROR test odoo.addons.account.tests.test_reconciliation: FAILED
INFO test odoo.addons.account.tests.test_reconciliation:  (errors=1, skipped=1)
INFO test odoo.modules.module: odoo.addons.account.tests.test_reconciliation tested in 26.49s, 31473 queries
ERROR test odoo.modules.module: Module account: 0 failures, 1 errors
```

Expected behavior:
Test passes.

**Comment by WohthaN** [comment]
As of 2a9e6e6a3b4b9593af96cf0495c8feaa970aaeb3, `l10n_it` is still breaking `account`: 

```
git checkout 2a9e6e6a3b4b9593af96cf0495c8feaa970aaeb3
./odoo-bin --addons-path=./addons/ --log-level=test --logfile=/dev/stdout --stop-after-init --test-enable -d test --init=base_vat,base_iban,l10n_it

[...]
2017-12-12 18:51:32,887 12778 ERROR test odoo.addons.account.tests.test_reconciliation: ERROR
2017-12-12 18:51:32,895 12778 INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_chf_transaction_chf (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
2017-12-12 18:51:36,667 12778 INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_eur_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
2017-12-12 18:51:39,691 12778 INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
2017-12-12 18:51:43,315 12778 INFO test odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_usd (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
2017-12-12 18:51:46,443 12778 INFO test odoo.addons.account.tests.test_reconciliation: ======================================================================
2017-12-12 18:51:46,443 12778 ERROR test odoo.addons.account.tests.test_reconciliation: ERROR: test_statement_euro_invoice_usd_transaction_euro_full (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
2017-12-12 18:51:46,443 12778 ERROR test odoo.addons.account.tests.test_reconciliation: Traceback (most recent call last):
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/addons/account/tests/test_reconciliation.py", line 253, in test_statement_euro_invoice_usd_transaction_euro_full
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `     self.assertTrue(invoice_rec_line.reconciled, 'The invoice should be totally reconciled')
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/odoo/fields.py", line 904, in __get__
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `     record.ensure_one()
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `   File "/tmp/odoo/odoo/models.py", line 4820, in ensure_one
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: `     raise ValueError("Expected singleton: %s" % self)
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: ` ValueError: Expected singleton: account.move.line(125, 124)
2017-12-12 18:51:46,444 12778 INFO test odoo.addons.account.tests.test_reconciliation: Ran 12 tests in 34.455s
2017-12-12 18:51:46,444 12778 ERROR test odoo.addons.account.tests.test_reconciliation: FAILED
2017-12-12 18:51:46,445 12778 INFO test odoo.addons.account.tests.test_reconciliation:  (errors=1, skipped=1)
2017-12-12 18:51:46,445 12778 INFO test odoo.modules.module: odoo.addons.account.tests.test_reconciliation tested in 34.46s, 31393 queries
2017-12-12 18:51:46,445 12778 ERROR test odoo.modules.module: Module account: 0 failures, 1 errors
2017-12-12 18:51:46,446 12778 INFO test odoo.modules.module: odoo.addons.account.tests.test_search run
```

I am fairly new to the odoo world, so please excuse my most naive questions...
- Am I doing something wrong maybe?
- Aren't all tests of all modules supposed to be run? Why the runbot is green and only l10n_us is tested? [runbot log](http://runbot8.odoo.com/runbot/static/build/285830-10-0-fix-bad-sudo-ape-2a9e6e/logs/job_20_test_all.txt)

I'm an experienced developer, but i'm not an accountant. For the little I understand, this failure could be due to the fact that the failing  test in account assumes a different configuration that l10n_it is changing (in which case, either the test is wrong and should be somehow generalized or made aware of this situations,  or probably better  l10n_it should replace it with a correct one for the new data somehow), but 
could as well be a real nasty bug  in the account module...

Is there anybody willing to help me in fixing this, at least figuring out where is the problem and what would be (at least theoretically) an acceptable solution for me to implement?  
I'm prone to believe that failing accountancy tests are quite a big issue on this kind of software...

**Comment by eLBati** [comment]
Hello @WohthaN I can't find this error in latest runbot builds
http://runbot9.odoo.com/runbot/static/build/287992-10-0-2aa313/logs/job_20_test_all.txt

**Comment by WohthaN** [comment]
Hello @eLBati : I'm afraid that's actually part of the problem, I cannot find any reference whatsoever to any localization module being tested by the runbut [1]. It seems like only l10n_us is being tested.
If then I run the italian localization modules tests locally, even one by one every time dropping the database in between, l10n_it and all the others depending on it fail with the error I mentioned before 
(same error concept, but some database line ids are different sometimes). 

[1]
```
$ cat job_20_test_all.txt | grep -i l10n_ | grep loading
2017-12-21 13:04:52,165 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/data/l10n_generic_coa_chart_data.xml
2017-12-21 13:04:52,291 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/data/account_chart_template_data.yml
2017-12-21 13:04:52,865 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/../account/demo/account_bank_statement.yml
2017-12-21 13:04:53,022 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/../account/demo/account_invoice_demo.yml
2017-12-21 13:04:57,568 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/../account/test/account_bank_statement.yml
2017-12-21 13:04:57,916 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_generic_coa/../account/test/account_invoice_state.yml
2017-12-21 13:04:59,265 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_us/views/res_config_view.xml
2017-12-21 13:04:59,376 13459 INFO 287992-10-0-2aa313-all odoo.modules.loading: loading l10n_us/data/res_company_data.xml
```

**Comment by eLBati** [comment]
@WohthaN you are right: some chart of accounts modules, like l10n_it, are not tested by runbot. This is something @odoo should take care of

**Comment by pedrobaeza** [comment]
The problem here is that localizations can't be tested currently this way, as the system is not prepared for that. There's an ongoing work for master for being able to test localizations in a proper way. There was even a mail on community mails about that.

Closing as no possible solution yet.
