### ISSUE TITLE
Odoo 10: "InternalError: no such savepoint" error when importing data model field

### ISSUE THREAD

**Issue by daloro** [odoo/odoo#18857]
Impacted versions:
10
Steps to reproduce:
Import a data model field
Current behavior:
"Odoo Internal error message"

The following entries in the odoo-server.log

2017-08-15 00:15:05,369 8962 INFO eydsys_mysol werkzeug: 187.140.253.132 - - [15/Aug/2017 00:15:05] "POST /web/dataset/call_kw/base_import.import/do HTTP/1.1" 200 - 2017-08-15 00:15:49,050 8962 INFO eydsys_mysol werkzeug: 187.140.253.132 - - [15/Aug/2017 00:15:49] "POST /longpolling/poll HTTP/1.1" 200 - 2017-08-15 00:16:39,368 8962 INFO eydsys_mysol werkzeug: 187.140.253.132 - - [15/Aug/2017 00:16:39] "POST /longpolling/poll HTTP/1.1" 200 - 2017-08-15 00:16:56,299 8962 INFO eydsys_mysol odoo.addons.base_import.models.base_import: importing 1 rows...

2017-08-15 00:16:56,741 8962 INFO eydsys_mysol odoo.sql_db: bad query: RELEASE SAVEPOINT model_load_save 2017-08-15 00:16:56,742 8962 INFO eydsys_mysol odoo.sql_db: bad query: ROLLBACK TO SAVEPOINT model_load_save 2017-08-15 00:16:56,742 8962 ERROR eydsys_mysol odoo.http: Exception during JSON request handling.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch

    result = self._call_function(**self.params)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper

    return f(dbname, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call

    result = self.endpoint(*a, **kw)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__

    return self.method(*args, **kw)

  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap

    response = f(*args, **kw)

  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 878, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw

    return call_kw_multi(method, model, args, kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi

    result = method(recs, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/addons/base_import/models/base_import.py", line 667, in do

    import_result = self.env[self.res_model].with_context(import_file=True).load(import_fields, data)

  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 887, in load

    cr.execute('ROLLBACK TO SAVEPOINT model_load_save')

  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper

    return f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute

    res = self._obj.execute(query, params)

InternalError: no such savepoint
Expected behavior:
Create new data model field, update existing definition
Video/Screenshot link (optional):

**Comment by vcloud9ray** [comment]
I just got this when importing ir.model.fields data via CSV.  Did you resolve it?

**Comment by pedrobaeza** [comment]
Due to the special nature of the model ir.model.fields (which is a reflect of the Python data model), I don't expect this to work correctly. You should do your customizations in data model through Odoo studio or Python modules.

Closing as "won't fix" due to the complexity behind it.
