### ISSUE TITLE
Automated Tests Failed with `--init account --test-commit`

### ISSUE THREAD

**Issue by pedrovagner** [odoo/odoo#18933]
Impacted versions: `Odoo version 10.0-20170207`

Steps to reproduce:

```bash
odoo --database my-app --stop-after-init --log-level test --logfile None --workers 0 --init account --test-enable --test-commit
```

Current behavior: Tests should pass

Expected behavior:

```
2017-08-18 17:20:18,862 15 INFO my-app odoo.modules.module: odoo.addons.account.tests.test_account_supplier_invoice running tests.
2017-08-18 17:20:18,862 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice: test_supplier_invoice (odoo.addons.account.tests.test_account_supplier_invoice.TestAccountSupplierInvoice)
2017-08-18 17:20:19,274 15 INFO my-app odoo.models.unlink: User #1 deleted account.analytic.line records with IDs: [3]
2017-08-18 17:20:19,476 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: FAIL
2017-08-18 17:20:19,486 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice: test_supplier_invoice2 (odoo.addons.account.tests.test_account_supplier_invoice.TestAccountSupplierInvoice)
2017-08-18 17:20:20,247 15 INFO my-app odoo.models.unlink: User #1 deleted account.analytic.line records with IDs: [5]
2017-08-18 17:20:20,445 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: FAIL
2017-08-18 17:20:20,447 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice: ======================================================================
2017-08-18 17:20:20,447 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: FAIL: test_supplier_invoice (odoo.addons.account.tests.test_account_supplier_invoice.TestAccountSupplierInvoice)
2017-08-18 17:20:20,447 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: Traceback (most recent call last):
2017-08-18 17:20:20,447 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/account/tests/test_account_supplier_invoice.py", line 43, in test_supplier_invoice
2017-08-18 17:20:20,447 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     invoice.move_id.button_cancel()
2017-08-18 17:20:20,447 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     self.gen.next()
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/dist-packages/odoo/tests/common.py", line 122, in _assertRaises
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     yield cm
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: ` AssertionError: UserError not raised
2017-08-18 17:20:20,448 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice: ======================================================================
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: FAIL: test_supplier_invoice2 (odoo.addons.account.tests.test_account_supplier_invoice.TestAccountSupplierInvoice)
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: Traceback (most recent call last):
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/dist-packages/odoo/addons/account/tests/test_account_supplier_invoice.py", line 105, in test_supplier_invoice2
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     invoice.move_id.button_cancel()
2017-08-18 17:20:20,448 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
2017-08-18 17:20:20,449 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     self.gen.next()
2017-08-18 17:20:20,449 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `   File "/usr/lib/python2.7/dist-packages/odoo/tests/common.py", line 122, in _assertRaises
2017-08-18 17:20:20,449 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: `     yield cm
2017-08-18 17:20:20,449 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: ` AssertionError: UserError not raised
2017-08-18 17:20:20,449 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice: Ran 2 tests in 1.585s
2017-08-18 17:20:20,449 15 ERROR my-app odoo.addons.account.tests.test_account_supplier_invoice: FAILED
2017-08-18 17:20:20,449 15 INFO my-app odoo.addons.account.tests.test_account_supplier_invoice:  (failures=2)
2017-08-18 17:20:20,449 15 ERROR my-app odoo.modules.module: Module account: 2 failures, 0 errors
```

If `--test-commit` isn't passed, tests run successfully.

**Comment by pedrobaeza** [comment]
Indeed this is expected, as --test-commit doesn't rollback the changes made, and thus the DB gets in an inconsistent state with data modified according the previous tests.

Closing as no real issue.
