### ISSUE TITLE
Report / Partnership Analysis - Error

### ISSUE THREAD

**Issue by ddico** [odoo/odoo#1894]
While browsing the reports on the runbot 8.0 i've noticed this error:

Odoo
OpenERP Server Error
Traceback (most recent call last):
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 495, in dispatch
    result = self._call_function(**self.params)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 685, in __call__
    return self.method(*args, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/http.py", line 360, in response_wrap
    response = f(*args, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/api.py", line 233, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/models.py", line 2147, in read_group
    cr.execute(query, where_clause_params)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/sql_db.py", line 230, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "crm_partner_report_assign" does not exist
LINE 3:             FROM "crm_partner_report_assign"
                         ^

![screen shot 2014-08-20 at 10 11 52 pm](https://cloud.githubusercontent.com/assets/7885477/3990982/ac84dc6a-28d8-11e4-9f1d-b79bf0b0ac6e.png)

It doesn't look like it was reported before.

**Comment by Yenthe666** [comment]
Hi @ddico,

This issue is no longer present in the latest Odoo 8.0 (runbot):
![image](https://cloud.githubusercontent.com/assets/6352350/15776598/21a0b4f8-2989-11e6-920b-28fdac5931a5.png)
Closing this since it has been fixed.

Regards,
Yenthe
