### ISSUE TITLE
Odoo 9.0 error to validate customer invoices

### ISSUE THREAD

**Issue by reilco** [odoo/odoo#18963]
Impacted versions:
I'm getting error for some invoices which are in draft status for some customers and products which they have been invoiced before without any problems, but few invoices

Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 899, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/odoo/odoo-server/openerp/http.py", line 1272, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/odoo/odoo-server/openerp/http.py", line 1040, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/odoo/odoo-server/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/odoo/odoo-server/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 194, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/odoo/odoo-server/openerp/service/model.py", line 188, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/odoo/odoo-server/openerp/service/model.py", line 170, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3627, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/odoo/odoo-server/openerp/workflow/__init__.py", line 67, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/odoo/odoo-server/openerp/workflow/service.py", line 73, in validate
    res2 = wi.validate(signal)
  File "/odoo/odoo-server/openerp/workflow/instance.py", line 62, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 102, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 230, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 239, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 77, in create
    workflow_item.process(stack=stack)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 98, in process
    if not self._execute(activity, stack):
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 144, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 295, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/odoo/odoo-server/openerp/workflow/workitem.py", line 273, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/odoo/odoo-server/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account_asset/account_asset_invoice.py", line 17, in action_move_create
    result = super(AccountInvoice, self).action_move_create()
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account/models/account_invoice.py", line 832, in action_move_create
    move = account_move.with_context(ctx_nolang).create(move_vals)
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 107, in create
    move = super(AccountMove, self.with_context(check_move_validity=False, partner_id=vals.get('partner_id'))).create(vals)
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4169, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4360, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/odoo/odoo-server/openerp/osv/fields.py", line 826, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 1127, in create
    new_line = super(AccountMoveLine, self).create(vals)
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4169, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 4313, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/odoo/odoo-server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ValueError: "new row for relation "account_move_line" violates check constraint "account_move_line_credit_debit2"
DETAIL:  Failing row contains (2854, 2017-08-21 11:45:04.081668, null, 208, null, null, 2017-08-21, null, 2305, f, null, 1, null, 1, null, -0.15, null, 0.0, f, 0.0, 0.0, 2017-08-21 11:45:04.081668, 2017-08-21, 1, 1117, /, null, null, null, 459, null, 0.0, null, 0.0, 0.0, 1.00, null).
" while evaluating
u'action_move_create()'

Please help.....

**Comment by Yenthe666** [comment]
Hi @reilco,

Thank you for your report but we really need more feedback.
What do you do to get this? Can you reproduce this on an official Odoo test instance at runbot.odoo.com?
Have you tried updating your Odoo first?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
