### ISSUE TITLE
JS Error setting taxes on accounts - master

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19052]
Impacted versions: master

Steps to reproduce:
In runbot, master go to Sales Orders
Edit or create a sales order - whatever you need to do be able open a product from a Sale Line
Open a product
Open its Category
Open the income account
Set a default tax
Click Save

Current behavior:
Error:
Uncaught TypeError: Cannot read property 'type' of undefined

http://257501-master-4eb83c.runbot5.odoo.com/web/content/2063-a2b468d/web.assets_backend.js:2284
Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class.reload (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2063-a2b468d/web.assets_backend.js:2284:386)
    at Class._onReload (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2063-a2b468d/web.assets_backend.js:2428:160)
    at Class.<anonymous> (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3906:11)
    at Class.trigger (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3904:180)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:365)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:449)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:449)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:449)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:449)
    at Class._trigger_up (http://257501-master-4eb83c.runbot5.odoo.com/web/content/2056-670543e/web.assets_common.js:3910:449)

A bit more invstigation showed two things.
1. Despite the error the tax saved.
2. When not going through a modal dialog it worked as expected.

So I suspect this is a more general error associated with updating records through a modal although I couldn't reproduce.

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thank you for your report. I've just tested this and can confirm it is a bug:
![image](https://user-images.githubusercontent.com/6352350/29704780-7fe17392-897b-11e7-92ff-795b0a28d2aa.png)
@ged-odoo and @qdp-odoo could you guys have a look at it?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
looks like a bug with the new views. I added this issue in our team's internal todo list

**Comment by aab-odoo** [comment]
Commit 96b1db4cd44ab70c5a7014ee36a8b475e1c5e38a fixes the issue.
