### ISSUE TITLE
[18.0] sale_planning: description

### ISSUE THREAD

**Issue by vince-dynapps** [odoo/odoo#190515]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

If you initialise a new demo database with the sale_planning module installed, and open a shell session and run the following code (or execute it via a RPC call):
env["planning.slot"].search_read([])
A singleton error will be raised.

### Log Output

```shell
Traceback (most recent call last):
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 6193, in ensure_one
    _id, = self._ids
    ^^^^
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 6074, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 4016, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
                         ~~~~~~^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 6983, in __getitem__
    return self._fields[key].__get__(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/fields.py", line 3024, in __get__
    return super().__get__(records, owner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/fields.py", line 1287, in __get__
    self.compute_value(recs)
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/fields.py", line 1469, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 5222, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/fields.py", line 109, in determine
    return needle(*args)
           ^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/enterprise/sale_planning/models/planning_slot.py", line 97, in _compute_template_autocomplete_ids
    super(PlanningSlot, planned_slots)._compute_template_autocomplete_ids()
  File "/opt/odoo/buildouts/odoo18/parts/odoo/enterprise/planning/models/planning.py", line 412, in _compute_template_autocomplete_ids
    domain = self._get_domain_template_slots()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/enterprise/sale_planning/models/planning_slot.py", line 207, in _get_domain_template_slots
    if self.sale_line_plannable:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/fields.py", line 1228, in __get__
    record.ensure_one()
  File "/opt/odoo/buildouts/odoo18/parts/odoo/odoo/odoo/models.py", line 6196, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
```

**Comment by vince-dynapps** [comment]
What is the status of this ticket? I see this issue was assigned on 18 dec, but is it currently being fixed?

**Comment by xavierbol** [comment]
Hello @vince-dynapps 

Sorry for the delay, it will be fixed in https://github.com/odoo/enterprise/pull/77318
