### ISSUE TITLE
[18.0] Database Initialization Fails After Removing MRP Module in Odoo

### ISSUE THREAD

**Issue by aminekhazraj** [odoo/odoo#190680]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

 I encountered a critical issue when attempting to remove the Manufacturing (MRP) module and its dependencies from Odoo 18.0 while running Odoo in a Docker container. After deleting the modules from the addons directory and restarting Odoo, the system fails to initialize a new database, raising the following error:

```
psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...
```
**Steps to Reproduce:**

1. Clone the Odoo 18.0 repository
2. Remove the MRP-related modules from the addons directory `["sale_mrp", "sale_mrp_margin", "project_mrp_stock_landed_costs",  "project_mrp_account", "project_mrp_sale", "pos_mrp", "project_mrp",  "purchase_mrp", "mrp", "mrp_account", "mrp_landed_costs",  "mrp_product_expiry", "mrp_repair", "mrp_subcontracting",  "mrp_subcontracting_account", "mrp_subcontracting_dropshipping",  "mrp_subcontracting_landed_costs", "mrp_subcontracting_purchase",  "mrp_subcontracting_repair"]
`

3. Rebuild the environment.
4. Start Odoo and create a new database 

this is my dockerfile : 
`FROM ubuntu:noble

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

ENV LANG=en_US.UTF-8
ARG TARGETARCH

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        dirmngr \
        fonts-noto-cjk \
        gnupg \
        libssl-dev \
        node-less \
        npm \
        python3-magic \
        python3-num2words \
        python3-odf \
        python3-pdfminer \
        python3-pip \
        python3-phonenumbers \
        python3-pyldap \
        python3-qrcode \
        python3-renderpm \
        python3-setuptools \
        python3-slugify \
        python3-vobject \
        python3-watchdog \
        python3-xlrd \
        python3-xlwt \
        xz-utils && \
    if [ -z "${TARGETARCH}" ]; then \
        TARGETARCH="$(dpkg --print-architecture)"; \
    fi; \
    WKHTMLTOPDF_ARCH=${TARGETARCH} && \
    case ${TARGETARCH} in \
      "amd64") WKHTMLTOPDF_ARCH=amd64 && WKHTMLTOPDF_SHA=967390a759707337b46d1c02452e2bb6b2dc6d59 ;; \
      "arm64") WKHTMLTOPDF_SHA=90f6e69896d51ef77339d3f3a20f8582bdf496cc ;; \
      "ppc64le"|"ppc64el") WKHTMLTOPDF_ARCH=ppc64el && WKHTMLTOPDF_SHA=5312d7d34a25b321282929df82e3574319aed25c ;; \
    esac && \
    curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_${WKHTMLTOPDF_ARCH}.deb && \
    echo ${WKHTMLTOPDF_SHA} wkhtmltox.deb | sha1sum -c - && \
    apt-get install -y --no-install-recommends ./wkhtmltox.deb && \
    rm -rf /var/lib/apt/lists/* wkhtmltox.deb

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ noble-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
    && GNUPGHOME="$(mktemp -d)" \
    && export GNUPGHOME \
    && repokey='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' \
    && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
    && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/pgdg.gpg.asc \
    && gpgconf --kill all \
    && rm -rf "$GNUPGHOME" \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        postgresql-client \
        libpq-dev \
        build-essential \
        python3-venv \
        python3-dev \
        libldap2-dev \
        libsasl2-dev \
        libxml2-dev \
        libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g rtlcss

WORKDIR /opt/odoo
COPY . /opt/odoo

RUN useradd -m -U -r -d /opt/odoo odoo \
    && mkdir -p /etc/odoo \
    && mkdir -p /var/lib/odoo/sessions \
    && chown -R odoo:odoo /opt/odoo /etc/odoo /var/lib/odoo

RUN python3 -m venv /opt/odoo/venv \
    && /opt/odoo/venv/bin/pip install --no-cache-dir --upgrade pip \
    && /opt/odoo/venv/bin/pip install --no-cache-dir -r /opt/odoo/requirements.txt

COPY entrypoint.sh /
COPY odoo.conf /etc/odoo/
RUN chmod +x /entrypoint.sh && chown -R odoo:odoo /etc/odoo

VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

EXPOSE 8069 8071 8072

ENV ODOO_RC=/etc/odoo/odoo.conf

COPY wait-for-psql.py /usr/local/bin/wait-for-psql.py

USER odoo
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/opt/odoo/venv/bin/python", "/opt/odoo/odoo-bin", "-c", "/etc/odoo/odoo.conf"]
`

### Log Output

```shell
odoo  | 2024-12-16 08:27:05,254 1 INFO None odoo.modules.loading: loading base/views/ir_default_views.xml 
odoo  | 2024-12-16 08:27:05,271 1 INFO None odoo.modules.loading: loading base/data/ir_config_parameter_data.xml 
odoo  | 2024-12-16 08:27:05,275 1 INFO None odoo.modules.loading: loading base/data/ir_cron_data.xml                                                              
odoo  | 2024-12-16 08:27:05,288 1 INFO None odoo.modules.loading: loading base/report/ir_model_report.xml 
odoo  | 2024-12-16 08:27:05,292 1 INFO None odoo.modules.loading: loading base/report/ir_model_templates.xml                                                      
odoo  | 2024-12-16 08:27:05,300 1 INFO None odoo.modules.loading: loading base/views/ir_logging_views.xml 
odoo  | 2024-12-16 08:27:05,317 1 INFO None odoo.modules.loading: loading base/views/ir_qweb_widget_templates.xml                                                 
odoo  | 2024-12-16 08:27:05,329 1 INFO None odoo.modules.loading: loading base/views/ir_module_views.xml 
odoo  | 2024-12-16 08:27:05,377 1 INFO None odoo.modules.loading: loading base/data/ir_module_category_data.xml 
odoo  | 2024-12-16 08:27:05,435 1 INFO None odoo.modules.loading: loading base/data/ir_module_module.xml 
odoo  | 2024-12-16 08:27:05,477 1 WARNING None odoo.modules.loading: Transient module states were reset 
odoo  | 2024-12-16 08:27:05,478 1 ERROR None odoo.modules.registry: Failed to load registry 
odoo  | 2024-12-16 08:27:05,478 1 ERROR None odoo.service.db: CREATE DATABASE failed:                                                                             
odoo  | Traceback (most recent call last):                                                                                                                        
odoo  |   File "/opt/odoo/odoo/tools/cache.py", line 103, in lookup
odoo  |     r = d[key]                                                                                                                                            
odoo  |         ~^^^^^                                                                                                                                            
db    | 2024-12-16 08:27:05.500 UTC [108] ERROR:  relation "ir_model" does not exist at character 39                                                              
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
db    | 2024-12-16 08:27:05.500 UTC [108] STATEMENT:  SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'
odoo  |     return caller(func, *(extras + args), **kw)                                                                                                           
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/func.py", line 97, in locked                                                                                                 
odoo  |     return func(inst, *args, **kwargs)
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                    
odoo  |   File "/opt/odoo/odoo/tools/lru.py", line 33, in __getitem__                                                                                             
odoo  |     a = self.d[obj]                                                                                                                                       
odoo  |         ~~~~~~^^^^^                                                                                                                                       
odoo  | KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7ff4a16739c0>, 'base.module_category_manufacturing_manufacturing')
odoo  |                                                                                                                                                           
odoo  | During handling of the above exception, another exception occurred:                                                                                       
odoo  |                                                                                                                                                           
odoo  | Traceback (most recent call last):                                                                                                                        
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 537, in _tag_root                                                                                          
odoo  |     f(rec)
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 400, in _tag_record                                                                                        
odoo  |     f_val = self.id_get(f_ref, raise_if_not_found=nodeattr2bool(rec, 'forcecreate', True))                                                                
odoo  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 519, in id_get                                                                                             
odoo  |     res = self.model_id_get(id_str, raise_if_not_found)
odoo  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                   
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 525, in model_id_get                                                                                       
odoo  |     return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)                                            
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
odoo  |   File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 2245, in _xmlid_to_res_model_res_id
odoo  |     return self._xmlid_lookup(xmlid)                                                                                                                      
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
odoo  |     return caller(func, *(extras + args), **kw)
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/cache.py", line 110, in lookup                                                                                               
odoo  |     value = d[key] = self.method(*args, **kwargs)                                                                                                         
odoo  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                         
odoo  |   File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 2238, in _xmlid_lookup
odoo  |     raise ValueError('External ID not found in the system: %s' % xmlid)                                                                                   
odoo  | ValueError: External ID not found in the system: base.module_category_manufacturing_manufacturing                                                         
odoo  |                                                                                                                                                           
odoo  | The above exception was the direct cause of the following exception:                                                                                      
odoo  | 
odoo  | Traceback (most recent call last):                                                                                                                        
odoo  |   File "/opt/odoo/odoo/service/db.py", line 72, in _initialize_db                                                                                         
odoo  |     registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)                                                                
odoo  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
odoo  |     return caller(func, *(extras + args), **kw)                                                                                                           
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/func.py", line 97, in locked                                                                                                 
odoo  |     return func(inst, *args, **kwargs)                                                                                                                    
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                    
odoo  |   File "/opt/odoo/odoo/modules/registry.py", line 127, in new
odoo  |     odoo.modules.load_modules(registry, force_demo, status, update_module)                                                                                
odoo  |   File "/opt/odoo/odoo/modules/loading.py", line 422, in load_modules                                                                                     
odoo  |     loaded_modules, processed_modules = load_module_graph(                                                                                                
odoo  |                                         ^^^^^^^^^^^^^^^^^^                                                                                                
odoo  |   File "/opt/odoo/odoo/modules/loading.py", line 227, in load_module_graph
odoo  |     load_data(env, idref, mode, kind='data', package=package)                                                                                             
odoo  |   File "/opt/odoo/odoo/modules/loading.py", line 71, in load_data                                                                                         
odoo  |     tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)                                                                          
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 608, in convert_file                                                                                       
odoo  |     convert_xml_import(env, module, fp, idref, mode, noupdate)
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 679, in convert_xml_import                                                                                 
odoo  |     obj.parse(doc.getroot())                                                                                                                              
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 594, in parse                                                                                              
odoo  |     self._tag_root(de)                                                                                                                                    
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 537, in _tag_root
odoo  |     f(rec)                                                                                                                                                
odoo  |   File "/opt/odoo/odoo/tools/convert.py", line 550, in _tag_root                                                                                          
odoo  |     raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (                                                                                      
odoo  | odoo.tools.convert.ParseError: while parsing /opt/odoo/odoo/addons/base/data/ir_module_module.xml:117, somewhere inside                                   
odoo  | <record model="ir.module.module" id="base.module_mrp_plm">
odoo  |             <field name="name">mrp_plm</field>                                                                                                            
odoo  |             <field name="shortdesc">Product Lifecycle Management (PLM)</field>                                                                            
odoo  |             <field name="category_id" ref="base.module_category_manufacturing_manufacturing"/>                                                            
odoo  |             <field name="sequence">155</field>                                                                                                            
odoo  |             <field name="application" eval="True"/>
odoo  |             <field name="summary">PLM, ECOs, Versions</field>                                                                                             
odoo  |             <field name="license">OEEL-1</field>                                                                                                          
odoo  |             <field name="author">Odoo S.A.</field>                                                                                                        
odoo  |             <field name="to_buy" eval="True"/>                                                                                                            
odoo  |             <field name="icon">/base/static/img/icons/mrp_plm.png</field>                                                                                 
odoo  |             <field name="website">https://www.odoo.com/app/plm?utm_source=db&amp;utm_medium=module</field>
odoo  |         </record>                                                                                                                                         
odoo  | 2024-12-16 08:27:05,490 1 INFO None odoo.modules.loading: loading 1 modules...                                                                            
odoo  | 2024-12-16 08:27:05,499 1 INFO None odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra)                                                 
odoo  | 2024-12-16 08:27:05,500 1 ERROR None odoo.sql_db: bad query: b"SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'"                     
odoo  | ERROR: relation "ir_model" does not exist
odoo  | LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...                                                                                   
odoo  |                                               ^                                                                                                           
odoo  |                                                                                                                                                           
odoo  | 2024-12-16 08:27:05,502 1 WARNING None odoo.modules.loading: Transient module states were reset                                                           
odoo  | 2024-12-16 08:27:05,502 1 ERROR None odoo.modules.registry: Failed to load registry 
odoo  | 2024-12-16 08:27:05,502 1 ERROR None odoo.addons.web.controllers.database: Database creation error.                                                       
odoo  | Traceback (most recent call last):                                                                                                                        
odoo  |   File "/opt/odoo/odoo/modules/registry.py", line 104, in __new__                                                                                         
odoo  |     return cls.registries[db_name]                                                                                                                        
odoo  |            ~~~~~~~~~~~~~~^^^^^^^^^                                                                                                                        
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
odoo  |     return caller(func, *(extras + args), **kw)                                                                                                           
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/func.py", line 97, in locked                                                                                                 
odoo  |     return func(inst, *args, **kwargs)                                                                                                                    
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo  |   File "/opt/odoo/odoo/tools/lru.py", line 33, in __getitem__                                                                                             
odoo  |     a = self.d[obj]                                                                                                                                       
odoo  |         ~~~~~~^^^^^                                                                                                                                       
odoo  | KeyError: 'delta'                                                                                                                                         
odoo  | 
odoo  | During handling of the above exception, another exception occurred:                                                                                       
odoo  |                                                                                                                                                           
odoo  | Traceback (most recent call last):                                                                                                                        
odoo  |   File "/opt/odoo/addons/web/controllers/database.py", line 83, in create                                                                                 
odoo  |     request.session.authenticate(name, credential)
odoo  |   File "/opt/odoo/odoo/http.py", line 1042, in authenticate                                                                                               
odoo  |     registry = Registry(dbname)                                                                                                                           
odoo  |                ^^^^^^^^^^^^^^^^                                                                                                                           
odoo  |   File "/opt/odoo/odoo/modules/registry.py", line 106, in __new__                                                                                         
odoo  |     return cls.new(db_name)                                                                                                                               
odoo  |            ^^^^^^^^^^^^^^^^
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
odoo  |     return caller(func, *(extras + args), **kw)                                                                                                           
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/func.py", line 97, in locked                                                                                                 
odoo  |     return func(inst, *args, **kwargs)
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                    
odoo  |   File "/opt/odoo/odoo/modules/registry.py", line 127, in new                                                                                             
odoo  |     odoo.modules.load_modules(registry, force_demo, status, update_module)                                                                                
odoo  |   File "/opt/odoo/odoo/modules/loading.py", line 429, in load_modules                                                                                     
odoo  |     registry.setup_models(cr)
odoo  |   File "/opt/odoo/venv/lib/python3.12/site-packages/decorator.py", line 232, in fun                                                                       
odoo  |     return caller(func, *(extras + args), **kw)                                                                                                           
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
odoo  |   File "/opt/odoo/odoo/tools/func.py", line 97, in locked                                                                                                 
odoo  |     return func(inst, *args, **kwargs)                                                                                                                    
odoo  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo  |   File "/opt/odoo/odoo/modules/registry.py", line 333, in setup_models                                                                                    
odoo  |     env['ir.model']._add_manual_models()                                                                                                                  
odoo  |   File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 501, in _add_manual_models                                                                   
odoo  |     cr.execute("SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'")                                                                   
odoo  |   File "/opt/odoo/odoo/sql_db.py", line 354, in execute
odoo  |     res = self._obj.execute(query, params)                                                                                                                
odoo  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                
odoo  | psycopg2.errors.UndefinedTable: relation "ir_model" does not exist                                                                                        
odoo  | LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...                                                                                   
odoo  |                                               ^
odoo  |                                                                                                                                                           
odoo  | 2024-12-16 08:27:05,975 1 INFO None odoo.sql_db: ConnectionPool(read/write;used=2/count=2/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=delta host=db port=5432 application_name=odoo-1 sslmode=prefer'
odoo  | 2024-12-16 08:27:06,026 1 INFO None werkzeug: 172.18.0.1 - - [16/Dec/2024 08:27:06] "POST /web/database/create HTTP/1.1" 200 - 10836 3.959 5.452
db    | 2024-12-16 08:27:10.807 UTC [125] FATAL:  database "odoo" does not exist
```

**Comment by intero-chz** [comment]
you just forgot module `mrp_plm` and probably others?

**Comment by aminekhazraj** [comment]
> you just forgot module `mrp_plm` and probably others?

Thank you for your response. If you meant that I should remove the folder mrp_plm, please note that there is no such folder in the addons directory. If you were referring to something else, a bit more clarification would be greatly appreciated. Thank you!

**Comment by intero-chz** [comment]
I didn't look into details, but the mistake was too obvious for me.

Odoo tries to create all available modules on database creation, so that you can install stuff. The mentioned module `mrp_plm` is an enterprise module so you have to remove some more modules from other module folders. Judging by the Dockerfile, the folder `mnt/extra-addons` probably is the other modules folder on your setup.

**Comment by aminekhazraj** [comment]
> I didn't look into details, but the mistake was too obvious for me.
> 
> Odoo tries to create all available modules on database creation, so that you can install stuff. The mentioned module `mrp_plm` is an enterprise module so you have to remove some more modules from other module folders. Judging by the Dockerfile, the folder `mnt/extra-addons` probably is the other modules folder on your setup.


Hi @intero-chz,

Thank you for your clarification. I’ve taken your advice and removed all MRP-related modules, including their dependencies and the enterprise modules in the mnt/extra-addons directory. However, I’m still facing the same database initialization error.

Here’s the process I followed:

Cloned the Odoo source code from GitHub.
Removed all MRP-related modules (and their dependencies).
Rebuilt the environment and attempted to start Odoo.
Despite these steps, the error persists. Could you please help clarify if there are additional steps I’m missing or other files I need to modify to safely delete these modules and allow the database to initialize correctly? Specifically:

1. Are there references in configuration files, XML data, or other parts of the source code that I need to update or clean up?

1. Is there a sequence I should follow when removing the modules and rebuilding?

I greatly appreciate your guidance on this issue!

Thanks again for your help.

**Comment by intero-chz** [comment]
For the sake of interest: why do you want to remove modules at all?
