### ISSUE TITLE
[18.0]  ./odoo-bin fails running from source

### ISSUE THREAD

**Issue by andreas-roehler** [odoo/odoo#190724]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [ ] 18.0
- [X] Other (specify)

### Steps to Reproduce

Running ./odoo-bin of master-branch in Bash from Linux fails

### Log Output

```shell
Traceback (most recent call last):
    File "PATH_TO_SOURCE/odoo/./odoo-bin", line 5, in <module>
      import odoo
    File "PATH_TO_SOURCE/odoo/odoo/__init__.py", line 49, in <module>
      _monkeypatches.patch_all()
    File "PATH_TO_SOURCE/odoo/odoo/_monkeypatches/__init__.py", line 22, in patch_all
      from .pytz import patch_pytz
    File "PATH_TO_SOURCE/odoo/odoo/_monkeypatches/pytz.py", line 18, in <module>
      import pytz
  ModuleNotFoundError: No module named 'pytz'

Error might be in pytz.py:

>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PATH_TO_SOURCE/odoo/odoo/_monkeypatches/pytz.py", line 18, in <module>
    import pytz
  File "PATH_TO_SOURCE/odoo/odoo/_monkeypatches/pytz.py", line 122, in <module>
    original_pytz_timezone = pytz.timezone
AttributeError: partially initialized module 'pytz' has no attribute 'timezone' (most likely due to a circular import)
```

**Comment by andreas-roehler** [comment]
This error goes after installing pytz.py via pip. However, there is another module missing now. New ticket for this?

**Comment by pumppi** [comment]
Hi,

probably you didn't install requirements.txt with pip? Custom environment? Have you checked docker for running Odoo, it's easier to setup.

**Comment by andreas-roehler** [comment]
BTW, when looking inside debinstall.sh, it seems not the right thing to do in a source/developer environment. Maybe drop that suggestion?

**Comment by andreas-roehler** [comment]
Seems the belongs to https://github.com/odoo/documentation/issues Closing it here.
