### ISSUE TITLE
[10.0] point_of_sale: Can't close the POS Session if a "not allowed" refund is done

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#19086]
### Impacted versions:
All

### Steps to reproduce:
1. Set the **Cash** journal with just an `inbound_payment_method_ids`. (do not set an `outbound_payment_method_ids`)
2. Set `journal_user` to True, so it can be used on the POS.
3. Start a POS Session.
4. Sell a product of $100 using Cash journal.
5. Refund the product of $100 using the Cash Journal
6. Close the Session
7. Validate

### Current behavior:
This error arrises:
`The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: payment_method_id - payment.method.id]`

And in the log something like this:
```
2017-08-25 04:41:51,828 1103 DEBUG client odoo.api: call pos.session(21,).action_pos_session_closing_control()
2017-08-25 04:41:56,583 1103 INFO client odoo.sql_db: bad query: INSERT INTO "account_payment" ("id", "payment_date", "name", "communication", "payment_difference_handling", "journal_id", "move_name", "currency_id", "partner_type", "state", "payment_type", "amount", "partner_id", "payment_method_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_payment_id_seq'), '2017-08-17', 'POS/2017/08/17/21', 'Cafeteria AASE/0438: ', 'open', 20, NULL, 74, 'supplier', 'reconciled', 'outbound', 65.0, 103152, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-08-25 04:41:56,585 1103 DEBUG client odoo.service.model: IntegrityError
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 246, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 265, in action_pos_session_close
    st.with_context(ctx).sudo().button_confirm_bank()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 238, in button_confirm_bank
    st_line.fast_counterpart_creation()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 831, in fast_counterpart_creation
    st_line.process_reconciliation(new_aml_dicts=[vals])
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 932, in process_reconciliation
    'name': self.statement_id.name,
  File "/odoo/odoo-server/src/odoo/addons/payment/models/account_payment.py", line 34, in create
    account_payment = super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "payment_method_id" violates not-null constraint
DETAIL:  Failing row contains (5805, 2017-08-25 04:41:51.828322, Cafeteria AASE/0438: , 20, 74, 103152, null, 2017-08-17, open, null, reconciled, null, 1, null, supplier, 2017-08-25 04:41:51.828322, 1, POS/2017/08/17/21, null, 65.0, outbound, null, null, null, null, null).
```

### Expected behavior:
If a journal is not set with an `outbound_payment_method_ids`, then it should not allow the cashier to make a refund using this journal, otherwise the session can't be closed.

I would expect a fix with a warning like: "This payment method can't be used to make refunds" or something similar. This way not much logic has to be changed and it's still compatible with the stable version guidelines.

**Tested on runbot**
cc: @jorenvo

**Comment by gustavovalverde** [comment]
Ok, after adding an `outbound_payment_method_ids` this also generates an unwanted behavior on the Backend, as I could use the same payment method for refunds, but this does not mean that we're going to use this method as an outbound payment method in the **backend** (it's only for refunds in the POS).

### Context:
We use a **Credit Cards** journal in the POS as an _inbound method_, and if we make a refund we use the same journal **Credit Cards** (as this is possible in real life).

But this doesn't mean that I need to have a  `outbound_payment_method_ids` in the Credits Cards **journal** configuration. As this might also add a bunch of unreal `outbound methods` of payment. This can lead to great mistakes on using an _inbound method_ were an _outbound method_ was supposed to be used.

The POS shouldn't require that for refunding the payment method has to be _outbound_, or otherwise there should be a differentiation between what's used for refunds and what's used as a payment method (which I'm almost sure would add a complexity not possible for stable).

cc: @qdp-odoo

**Comment by mdurbar** [comment]
Facing a similar issue now, were you able to resolve it? Can't close the session either.

**Comment by gustavovalverde** [comment]
@mdurbar Not a fix yet. 
@Yenthe666, who could help us here?

**Comment by Yenthe666** [comment]
@jorenvo or @mart-e can. :)

**Comment by gustavovalverde** [comment]
Ticket 777073

**Comment by gustavovalverde** [comment]
OPW Closed with:
![image](https://user-images.githubusercontent.com/16890942/39784998-80713e28-52e8-11e8-8bd7-f44e35130b87.png)

**Comment by Yenthe666** [comment]
Hey @gustavovalverde,

I guess there is no point in keeping this one open then. Looks like this won't be changed, maybe in one of the upcoming versions, who knows. (sorry)
