### ISSUE TITLE
Odoo Studio - unicode buffer error

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19147]
Impacted versions: Master

Steps to reproduce:
Open a view - say product template view
Open Studio
Drag and drop field

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/258598-master-c8bfd2/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/258598-master-c8bfd2/odoo/http.py", line 309, in _handle_exception
    raise exception
TypeError: 'unicode' does not have the buffer interface
```
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo not sure who from your team works on the studio. Can you pass this along?

**Comment by dhannyz** [comment]
@Yenthe666 
Not sure if semi-related.
There are also issues with the studio and python 3 support. (The usual bytes-like vs str issues)
```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 309, in _handle_exception
    raise exception
  File "/opt/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/enterprise/web_studio/controllers/main.py", line 557, in edit_view
    arch = etree.parse(io.BytesIO(studio_view_arch), parser).getroot()
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Yenthe666** [comment]
Thank you for the update @dhannyz 
@ged-odoo the JS error is most likely from one of your guys and as for the unicode: @xmo-odoo it looks like there is something still not converted well for PY3 & Odoo 11 😉

**Comment by xmo-odoo** [comment]
bytes/text confusion should be fixed in saas-17.
