### ISSUE TITLE
[17.0] issue at the cleanup in models

### ISSUE THREAD

**Issue by oaliflint** [odoo/odoo#191592]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

batch payslips on create action 
expected: normal creation form
actual: validation error 
<img width="490" alt="Screenshot 2024-12-24 at 1 02 21 PM" src="https://github.com/user-attachments/assets/0357d917-b3c2-452a-98a8-74c117a21000" />

https://github.com/user-attachments/assets/e1880ad7-6e5b-4e94-b20e-64d9b90de878

### Log Output

```shell
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/models/models.py", line 1075, in onchange
    result['value'] = snapshot1.diff(snapshot0, force=first_call)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/models/models.py", line 1206, in diff
    [result] = self.record.web_read(simple_fields_spec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/models/models.py", line 117, in web_read
    vals['id']: cleanup(vals)
                ^^^^^^^^^^^^^
  File "/Users/omarkhaled/odoo/odoo17-server/addons/web/models/models.py", line 94, in cleanup
    vals['id'] = vals['id'].origin or False
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'origin'

The above server error caused the following client error:
OwlError: The following error occurred in onWillStart: "Odoo Server Error"
    Error: The following error occurred in onWillStart: 
        at wrapError (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1044:77)
        at onWillStart (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1050:117)
        at useModel (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:5865:104)
        at PayslipBatchFormController.setup (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:8655:99)
        at PayslipBatchFormController.setup (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:12923:446)
        at PayslipBatchFormController.setup (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:18174:692)
        at ComponentNode (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1002:202)
        at http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1541:6
        at View.slot1 (eval at compile (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1501:374), <anonymous>:15:36)
        at callSlot (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:1109:25)

Caused by: RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:2884:163)
        at XMLHttpRequest.<anonymous> (http://127.0.0.1:8069/web/assets/2/05fd455/web.assets_web.min.js:2888:13)
```

**Comment by oaliflint** [comment]
the following is my version of the cleanup method:

def cleanup(vals: Dict) -> Dict:
    """ Fixup vals['id'] of a new record. """
    if vals.get('id'):
        if hasattr(vals['id'], 'origin'):
            vals['id'] = vals['id'].origin or False
        else:
            vals['id'] = vals['id'] or False
    return vals

**Comment by vincentius** [comment]
Do you have automated actions that try to clear Many2One fields? We encountered the same error with this type of actions:

![Image](https://github.com/user-attachments/assets/fa4aaa22-777d-41f3-977b-c8c0da762b30)

**Comment by jujuna** [comment]
@oaliflint do you have solution for that?
