### ISSUE TITLE
Cannot uninstall base_import_module

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#19158]
Impacted versions: 10.0 ce/ee

Steps to reproduce:
1. Install base_import_module.
2. Uninstall it.

Current behavior:

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/module/wizard/base_module_upgrade.py", line 76, in upgrade_module
    odoo.modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/modules/loading.py", line 393, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/module/module.py", line 425, in module_uninstall
    self.write({'state': 'uninstalled', 'latest_version': False})
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3560, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3773, in _write
    self.recompute()
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 5314, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 5314, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 5210, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 956, in determine_value
    self.compute_value(recs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 936, in compute_value
    self._compute_value(records)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/module/module.py", line 188, in _get_views
    if module.state not in ('installed', 'to upgrade', 'to remove'):
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 972, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3066, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3010, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3134, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_module_module.imported does not exist
LINE 1:  SELECT "ir_module_module"."imported" as "imported","ir_modu...
                ^
```

Expected behavior:
It should be uninstalled, but it seems the uninstallation process tries to read a field that has been removed from `ir.module.module` model. This affects any addon that extends this model.

@Tecnativa

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yajo** [comment]
It should be, the fix is in #19161, still open.

**Comment by Yenthe666** [comment]
Verified - it is still a bug 😉

**Comment by pedrobaeza** [comment]
@rco-odoo do you know if this is still happening?

**Comment by Yenthe666** [comment]
Hey both,

This should have been fixed in the meanwhile as it is now working at my end.
If you can still reproduce it on the latest 10.0 then do let me know but I believe this is solved now.

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
Thanks. Then you can close the linked PR also.
