### ISSUE TITLE
[17.0] hr_recruitment: cannot install without SMS installed which is not a dependency

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#191635]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- On a database without SMS installed, try to install hr_recruitment. (or after both are installed, remove SMS module and then try to update hr_recruitment)
- You get a traceback :
```
odoo.tools.convert.ParseError: while parsing /opt/odoo/addons/hr_recruitment/views/hr_candidate_views.xml:220
Invalid model name “sms.composer” in action definition.
```

This is related to https://github.com/odoo/odoo/pull/125787 which added a view on sms.composer model which comes from SMS module, but there is no dependency between hr_recruitment and sms.

This should go in a glue module module between hr_recruitment and SMS instead of adding a new dependency to hr_recruitment.

### Log Output

```shell
RPC_ERROR

Odoo Server Error

Occured on 72409518-18-0-all.runbot239.odoo.com on model ir.module.module and id 25 on 2024-12-24 12:56:40 GMT

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/data/build/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/http.py", line 2171, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/addons/web/controllers/dataset.py", line 40, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/api.py", line 517, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 671, in button_immediate_upgrade
    return self._button_immediate_function(self.env.registry[self._name].button_upgrade)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 604, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/build/odoo/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/data/build/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/data/build/odoo/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/data/build/odoo/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/build/odoo/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/data/build/odoo/odoo/tools/convert.py", line 548, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /data/build/odoo/addons/hr_recruitment/views/hr_candidate_views.xml:220
Invalid model name “sms.composer” in action definition.

View error context:
'-no context-'


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://72409518-18-0-all.runbot239.odoo.com/web/assets/0ba9f6c/web.assets_web.min.js:3113:338
    makeErrorFromResponse@https://72409518-18-0-all.runbot239.odoo.com/web/assets/0ba9f6c/web.assets_web.min.js:3116:163
    rpc._rpc/promise</<@https://72409518-18-0-all.runbot239.odoo.com/web/assets/0ba9f6c/web.assets_web.min.js:3121:34
```

**Comment by duong77476-viindoo** [comment]
This kind of issue already exist, i try to add dependency but they said it auto install so being uninstall at some point is not expected so i think we only need to install sms module to fix this

**Comment by remi-filament** [comment]
Hi @duong77476-viindoo thank you for commenting on this one, actually, you are right that by default you have sms as auto install, but for many customers who want to improve security on their database, most of external calls are disabled, leading to IAP / SMS / others being uninstalled.

You may also have noticed that these auto installed apps are modified in OCB repository with https://github.com/OCA/OCB/pull/1242 leaving decision to admin to install those or not.

Having SMS disabled, you cannot install / upgrade hr_recruitment anymore, which is a pity since this is because only one record for sms marketing !

In my opinion, only for adding one record, this hr_recruitment module should not depend on sms and therefore this record should be added elsewhere...

**Comment by pedrobaeza** [comment]
I agree that it's totally incorrect to add that hidden dependency.

**Comment by duong77476-viindoo** [comment]
Not sure though hihi
