### ISSUE TITLE
Installation from src python dependency problem.

### ISSUE THREAD

**Issue by nsrshishir** [odoo/odoo#191762]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

In fresh Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-130-generic x86_64)

python3 -m pip install -r https://github.com/odoo/odoo/raw/17.0/requirements.txt

### Log Output

```shell
Collecting gevent==21.8.0 (from -r https://github.com/odoo/odoo/raw/17.0/requirements.txt (line 17))
  Downloading gevent-21.8.0.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 92.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types
      
      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 50, in <module>
        File "/tmp/pip-install-aut1ejni/gevent_e0c503ad00aa44bbbc149e640826e5b1/_setuputils.py", line 237, in cythonize1
          new_ext = cythonize(
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-vs_w4t0s/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Ma4eteS** [comment]
The problem is solved with 
gevent==24.11.1

**Comment by mdavalos1993** [comment]
thanks @Ma4eteS

**Comment by manhpham90vn** [comment]
thanks @Ma4eteS

**Comment by petros** [comment]
I am new to Odoo development, and I am trying to install the dependencies of Odoo 16, and I am getting the same issue. Why does `requirements.txt` have this issue if it's going to support 3.10 (by mentioning it in the requirements file itself)? Wouldn't it make sense to "fix" this by adding 24.11.1 as an option in requirements? I may totally be missing something about how these things work, as I am also new to Python. 🙇‍♂
