### ISSUE TITLE
Problems when running unit tests - many tests of built-in modules fail

### ISSUE THREAD

**Issue by D4N** [odoo/odoo#19276]
Impacted versions:
10.0

Steps to reproduce:
* Clone Odoo from git
* Write a custom module which has unit tests using odoo.tests
* Invoke Odoo via:
`./odoo-bin --db_host=xx.yy.zz.aa --db_port=5432 --db_user=USER --db_password=PW --addons-path=addons,/path/to/my_module/ -i my_module --test-enable`
This runs the unit tests for my module, but also for many other (probably all installed) addons. Unfortunately I have found no way to run the tests only for my module & to do it without killing odoo manually (--stop-after-init does not run the tests).

Current behavior:
Many of the builtin tests fail due to an assertion that self.test_cr is not None. For example:
```
2017-09-05 13:21:33,817 23765 INFO CGC_odoo odoo.modules.module: odoo.addons.base.tests.test_xmlrpc running tests.
2017-09-05 13:21:33,817 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: test_01_xmlrpc_login (odoo.addons.base.tests.test_xmlrpc.TestXMLRPC)
2017-09-05 13:21:33,818 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` Try to login on the common service.
2017-09-05 13:21:33,819 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ERROR
2017-09-05 13:21:33,825 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: test_xmlrpc_ir_model_search (odoo.addons.base.tests.test_xmlrpc.TestXMLRPC)
2017-09-05 13:21:33,825 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2017-09-05 13:21:33,825 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ERROR
2017-09-05 13:21:33,830 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: ======================================================================
2017-09-05 13:21:33,830 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ERROR: test_01_xmlrpc_login (odoo.addons.base.tests.test_xmlrpc.TestXMLRPC)
2017-09-05 13:21:33,831 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` Try to login on the common service.
2017-09-05 13:21:33,831 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: Traceback (most recent call last):
2017-09-05 13:21:33,831 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `   File "/home/dan/packages/odoo/odoo/tests/common.py", line 248, in setUp
2017-09-05 13:21:33,831 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `     self.registry.enter_test_mode()
2017-09-05 13:21:33,831 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `   File "/home/dan/packages/odoo/odoo/modules/registry.py", line 430, in enter_test_mode
2017-09-05 13:21:33,832 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `     assert self.test_cr is None
2017-09-05 13:21:33,832 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` AssertionError
2017-09-05 13:21:33,832 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: ======================================================================
2017-09-05 13:21:33,832 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ERROR: test_xmlrpc_ir_model_search (odoo.addons.base.tests.test_xmlrpc.TestXMLRPC)
2017-09-05 13:21:33,832 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2017-09-05 13:21:33,833 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: Traceback (most recent call last):
2017-09-05 13:21:33,833 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `   File "/home/dan/packages/odoo/odoo/tests/common.py", line 248, in setUp
2017-09-05 13:21:33,833 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `     self.registry.enter_test_mode()
2017-09-05 13:21:33,833 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `   File "/home/dan/packages/odoo/odoo/modules/registry.py", line 430, in enter_test_mode
2017-09-05 13:21:33,833 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: `     assert self.test_cr is None
2017-09-05 13:21:33,834 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: ` AssertionError
2017-09-05 13:21:33,834 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc: Ran 2 tests in 0.013s
2017-09-05 13:21:33,834 23765 ERROR CGC_odoo odoo.addons.base.tests.test_xmlrpc: FAILED
2017-09-05 13:21:33,834 23765 INFO CGC_odoo odoo.addons.base.tests.test_xmlrpc:  (errors=2)
2017-09-05 13:21:33,835 23765 ERROR CGC_odoo odoo.modules.module: Module base: 0 failures, 2 errors
```
This makes finding errors in my module more of a hasle.

Also, when run with --stop-after-init, Odoo does not run the unit tests. Furthermore the --test-file option does not seem to do anything.

Honestly, I think I am doing something fundamentally wrong, as the unit test failures look like they have to be invoked without a database?

Expected behavior:
The unit tests from the builtin modules should not fail.
It would be also very nice if I could specify which unit tests are run and to stop odoo after they have been run, so that I could run the unit tests in a CI.

Video/Screenshot link (optional):

**Comment by blaggacao** [comment]
I'm running into this as well, I'll feed back what's going on in a while...

**Comment by blaggacao** [comment]
I think I found the answer in this patch: http://gitlab.opengest.solutions/opengest/odoo/commit/673f4aa4a77161dc58e0e1bf97e8f713b1e88491?view=parallel

Meaning that one cannot have a browser window open with odoo during a test run, *after* completion it's no problem. That solved my problem.

**Comment by D4N** [comment]
Nice find, thanks!

I haven't touched odoo for a while and started developing again with version 11. There I had no problems, although I also had no browser window open. I'll try that too.

Is there a way how to prevent that from happening? Maybe launch odoo on a different port during testing, so that the browser cannot accidentally grab the connection? (Although that is incredibly hacky and can fail for various other reasons)

**Comment by pedrobaeza** [comment]
What you have to do is first to install your module without `--test-enable` for installing it and all of its dependencies.

Once installed, put the same command with `--test-enable`, and only your module will be tested.

Closing this as answered. Please use the forums for more doubts like this one.
