### ISSUE TITLE
when i try to send Customer Invoices by mail show this error

### ISSUE THREAD

**Issue by esgindy** [odoo/odoo#19535]
the send mail is working good with Qut and sales order but in the invoice i show this error how can i fix it ??
i use odoo v 9 

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 62, in action_invoice_sent
    action_dict = super(account_invoice, self).action_invoice_sent(cr, uid, ids, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_invoice.py", line 396, in action_invoice_sent
    default_template_id=template.id,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by OpenCode** [comment]
The database is a new database or an existing one? Maybe the template with xml_id "email_template_edi_invoice" doesn't exist, yet. Have you deleted it?

**Comment by esgindy** [comment]
it's exciting one but yesterday i try to edit the template after i try to change something in it it give me error so i duplicate another template (portal) and change the name that's all i do after that i found this error so what should i do

**Comment by Yenthe666** [comment]
Hi @esgindy,

Thank you for your report.
Can you reproduce this on an official Odoo instance (runbot.odoo.com)?

**Comment by Yenthe666** [comment]
Closing as there has been no feedback.
