### ISSUE TITLE
[saas-18] Create new user is broken.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#19576]
Impacted versions: **saas-18**

Steps to reproduce:

Go and try to create a new user in the normal way (setting -> users)
- Set a valid name.
- Set a valid email.
 Save or try to change the field (to trigger the onchange).

Current behavior:
traceback.

```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/addons/web/controllers/main.py", line 910, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/addons/web/controllers/main.py", line 902, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/models.py", line 4950, in onchange
    record.mapped(dotname)
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/models.py", line 4409, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/models.py", line 4388, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/models.py", line 4388, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/runbot/extra/runbot/static/build/265634-saas-18-8635ff/odoo/models.py", line 4655, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'sel_groups_56_57'
```

Expected behavior:

Save normally.

Video/Screenshot link (optional):

Runbot: http://265634-saas-18-8635ff.runbot9.odoo.com/web?#id=&view_type=form&model=res.users&action=65&menu_id=4

proof: 
![image](https://user-images.githubusercontent.com/338634/30629616-65d6806a-9da2-11e7-8f39-0685ddd8b6ee.png)

**Comment by odony** [comment]
Thanks, should be solved after 3069734d4f13ff5b09331def54d85a4f2d607178 :-)
