### ISSUE TITLE
Unicodeescape' codec can't decode bytes in  malformed \N character escape

### ISSUE THREAD

**Issue by danielmwai** [odoo/odoo#19628]
Impacted versions:
Master
Steps to reproduce:
Virtualenv  with  Python 3.6 
Current behavior:
    017-09-21 15:11:59,487 21478 INFO ? werkzeug: 127.0.0.1 - - [21/Sep/2017 15:11:59] "GET /favicon.ico HTTP/1.1" 500 -
2017-09-21 15:11:59,490 21478 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/nzaniela/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/odoo3/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/nzaniela/apps/CODING_DEV_APPS/VIRTUALENV_PROJECTS/odoo3/lib/python3.6/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/nzaniela/apps/CODING_DEV_APPS/ODOO_PROJECTS/odoo/odoo/service/wsgi_server.py", line 155, in application
    return application_unproxied(environ, start_response)
  File "/home/nzaniela/apps/CODING_DEV_APPS/ODOO_PROJECTS/odoo/odoo/service/wsgi_server.py", line 143, in application_unproxied
    result = handler(environ, start_response)
  File "/home/nzaniela/apps/CODING_DEV_APPS/ODOO_PROJECTS/odoo/odoo/http.py", line 1299, in __call__
    self.load_addons()
  File "/home/nzaniela/apps/CODING_DEV_APPS/ODOO_PROJECTS/odoo/odoo/http.py", line 1314, in load_addons
    manifest = ast.literal_eval(open(manifest_path).read())
  File "/usr/lib64/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", line 3
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: malformed \N character escape
2017-09-21 15:12:09,358 21480 DEBUG ? odoo.service.server: WorkerCron (21480) polling for jobs

**Comment by danielmwai** [comment]
Closing issues , was using python 3.6  with odoo 10  config  file and this was leading to malformed \N character escape ,  solved  it  by  generating  a  new  config with  odoo 11  which is using  python 3  and the  error  was  gone
