### ISSUE TITLE
Allow eight decimal places for defining cryptocurrencies.

### ISSUE THREAD

**Issue by rossigee** [odoo/odoo#19668]
Impacted versions: All

Steps to reproduce: Create a journal for a Bitcoin wallet, create transactions, attempt to reconcile account.

Current behavior: Only able to enter transactions with 6 decimal places of precision.

Expected behavior: Ability to enter transactions with 8 or more decimal places of precision.

**Comment by rossigee** [comment]
This ticket is to follow on from PR #18255, in which I made a fairly crude attempt to hack the hard-coded value of decimal places in 'res_currency' from 6 to 8. The patch was understandably rejected, and advice was given (by @mart-e) on how to do the patch properly for potential inclusion in an upcoming release...

"You can make the precision configurable with a decimal precision record.
For instance, the price_unit field uses the Product Price precision."

I am currently using Odoo to track a few crypto wallets. It's not completely impossible, but I lose considerable precision in my records and have to make manual adjustments when reconciling.

I am keen to write a new (decent, test-driven) PR to cover this, so that I can move forward with other patches/modules for Odoo that will make it more useful for crypto users (i.e. automatic reconciliation from the blockchain) but my Odoo development experience (and spare time) are both lacking, so it may be a while before anything comes of it.

BTW, if there are any other internal/public issues or projects going on in the Odoo Community related to making Odoo an appropriate choice for organisations that deal with cryptocurrency, please link to them here (or from them to this ticket). I'd be interested in following them, plus any advice, assistance or support in resolving this issue would be greatly appreciated.

**Comment by rossigee** [comment]
So, I think I figured it out, and have come up with a basic patch...

https://github.com/odoo/odoo/compare/10.0...rossigee:decimal-precision-for-currency?expand=1

However, when initialised with a clean database it is failing with...

```
./odoo-bin --test-enable --log-level=debug --dev=all
...
2017-09-24 10:56:15,833 15709 INFO odoo odoo.modules.loading: init db
2017-09-24 10:56:16,791 15709 INFO odoo odoo.modules.loading: loading 1 modules...
2017-09-24 10:56:16,791 15709 DEBUG odoo odoo.modules.loading: loading module base (1/1)
2017-09-24 10:56:16,821 15709 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/loading.py", line 280, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/loading.py", line 135, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 288, in setup_models
    model._setup_base(partial)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/models.py", line 2813, in _setup_base
    self._add_field(name, field.new())
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/models.py", line 393, in _add_field
    field.setup_base(self, name)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 405, in setup_base
    self._setup_attrs(model, name)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 468, in _setup_attrs
    if not (self.store and self.column_type) or self.manual or self.deprecated:
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 1167, in column_type
    return ('numeric', 'numeric') if self.digits is not None else \
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 1174, in digits
    return self._digits(cr)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/addons/decimal_precision/__init__.py", line 10, in change_digit
    precision = env['decimal.precision'].precision_get(application)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 174, in __getitem__
    return self.models[model_name]
KeyError: 'decimal.precision'
```

What am I doing wrong?!

**Comment by gdgellatly** [comment]
Copy and paste the dp import from another module. It's wrong.

**Comment by rossigee** [comment]
@gdgellatly - It seems there are two ways that other modules within the odoo repo import 'dp'. I've tried both with the same result.

```
import odoo.addons.decimal_precision as dp
```

...and...

```
from odoo.addons import decimal_precision as dp
```

**Comment by gdgellatly** [comment]
It needs to be the from version for import. Also your module must depend on
decimal_precision in manifest.

**Comment by gdgellatly** [comment]
Actually that makes for an interesting problem. You probably are going to
need to put your record creation elsewhere. Either a separate module or in
decimal precision itself or else you will have circular dependencies.

**Comment by rossigee** [comment]
@gdgellatly - Thanks for that. I'm starting to get the picture now.

I'm not sure what you're saying about the import style. AFAICS, the two import statements are equivalent and both approaches seem to be used inconsistently across base without any problems.

The real problem definitely seems to be the circular dependency - a base model (currency) depending on an addon (decimal_places). Am I correct in my understanding that base modules should not depend on addons?

It'd probably complicate things considerably, but it seems to me (perhaps naively) that the decimal places addon therefore belongs in base in order for this to sit right. :grimacing:

What are your thoughts/suggestions?

**Comment by gdgellatly** [comment]
@rossigee I'm not sure where you are searching, maybe an older version, I have just looked at master, there are 48 cases of this import in core, all of them use 
```
from odoo.addons import decimal_precision as dp
```  
I was not aware you could even import addons the old way under python 3.  I just tried it and it works as I just happened to be writing a module with that import, but given its 48-0 in master I'd say stick with using the method above.

Anyway resolving the dependency is up to you and odoo.  I don't know if putting decimal_precision in base is necessarily the correct answer.  I also don't know if putting the xml records into decimal_precision is either.  Or if creating a 3rd module is the right way.  

But I have a sense you are right, decimal_precision in base would make sense, its more historical from v5 when we had no decimal_precision so an extra module was created.

**Comment by rossigee** [comment]
So I spent some time seeing if I could move decimal_precision into base as cleanly as possible. I learned a bit more about Odoo's code along the way, but I'm still stuck with an error on running up 'odoo-bin' with a fresh database.

https://github.com/odoo/odoo/compare/master...rossigee:decimal-precision-for-currency

The output I'm getting is now...

```
2017-09-30 08:51:47,966 7744 INFO odoo odoo.modules.loading: init db
2017-09-30 08:51:48,835 7744 INFO odoo odoo.modules.loading: loading 1 modules...
2017-09-30 08:51:48,855 7744 ERROR odoo odoo.sql_db: bad query: b"select digits from decimal_precision where name='Currency'"
ERROR: relation "decimal_precision" does not exist
LINE 1: select digits from decimal_precision where name='Currency'
                           ^

2017-09-30 08:51:48,855 7744 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('decimal.precision', <function DecimalPrecision.precision_get at 0x7fc6d86019d8>, 'Currency')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/loading.py", line 282, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/loading.py", line 134, in load_module_graph
    registry.setup_models(cr)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/modules/registry.py", line 272, in setup_models
    model._setup_base()
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/models.py", line 2314, in _setup_base
    self._add_field(name, field.new())
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/models.py", line 288, in _add_field
    field.setup_base(self, name)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 385, in setup_base
    self._setup_attrs(model, name)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 451, in _setup_attrs
    if not (self.store and self.column_type) or self.manual or self.deprecated:
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 1169, in column_type
    return ('numeric', 'numeric') if self.digits is not None else \
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/fields.py", line 1176, in digits
    return self._digits(cr)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/addons/base/res/res_decimal_precision.py", line 9, in change_digit
    precision = env['decimal.precision'].precision_get(application)
  File "<decorator-gen-35>", line 2, in precision_get
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/addons/base/res/res_decimal_precision.py", line 28, in precision_get
    self.env.cr.execute('select digits from decimal_precision where name=%s', (application,))
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/rossg/clients/golder/odoo-cryptocurrency-patch/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "decimal_precision" does not exist
LINE 1: select digits from decimal_precision where name='Currency'

```

I can't figure out for the life of me *how* or *where* the 'decimal_places' table actually gets created, but I would guess the problem is that it is not being created *before* it tries to create the 'res_currency' table.

Can anyone help point me in the right direction from here?

**Comment by rossigee** [comment]
This is starting to present a serious roadblock to progress with tracking my accounts right now, and I currently lack the time or Odoo development experience to address it myself, so I'm currently willing to fund development of this feature. Please contact me privately if you're capable and interested.

**Comment by mart-e** [comment]
Hello,

Actually, it is a bit harder than I thought. The `decimal.precision` model is defined in the `decimal_precision` module, so is not available in `base`.
There is several solutions:
- adding the precision on res.currency in a different module (e.g. account)
- moving decimal_precision to base (submitted the feedback)
- move res.currency out of base (currently evaluated by R&D)

Solution 2 or 3 are the cleanest but will take time before being realised.
If you just want something that work in your development, you can add something like (untested):

```python
# -*- coding: utf-8 -*-

from odoo import fields, models, api, _
from odoo.addons import decimal_precision as dp


class ResCurrency(models.Model):
    _inherit = "res.currency"

    rate = fields.Float(digits=dp.get_precision('Currency Precision'))
    rounding = fields.Float(digits=dp.get_precision('Currency Precision'))


class ResCurrencyRate(models.Model):
    _inherit = "res.currency.rate"

    rate = fields.Float(digits=dp.get_precision('Currency Precision'))

```
and in your data files
```xml
<record forcecreate="True" id="decimal_currency" model="decimal.precision">
            <field name="name">Currency Precision</field>
            <field name="digits" eval="6"/>
</record>
```
