### ISSUE TITLE
[10.0] upgrading website_sale_delivery crash the server 

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#19692]
Impacted versions: 10.0

Steps to reproduce: I suppose that happens because Free delivery was removed (see #16664). 

Current behavior: running odoo -d [my_db] -u website_sale_delivery results in critical error. Nobody can log in or even access database selector page (server error). Need to remove sessions files first. Traceback below.

Upgrade was done with latest nightly. Downgrading odoo does nothing (tried with several versions up to one from june 2017). Only solution was to restoring yesterday's backup.

-bash-4.2$ odoo -u website_sale_delivery -d modele7
2017-09-25 15:51:14,596 20617 INFO ? odoo: Odoo version 10.0-20170925
2017-09-25 15:51:14,596 20617 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/10.0', u'/usr/lib/python2.7/site-packages/odoo/addons']
2017-09-25 15:51:14,596 20617 INFO ? odoo: database: default@default:default
2017-09-25 15:51:14,605 20617 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-09-25 15:51:14,612 20617 INFO modele7 odoo.modules.loading: loading 1 modules...
2017-09-25 15:51:14,691 20617 INFO modele7 odoo.modules.loading: 1 modules loaded in 0.08s, 0 queries
2017-09-25 15:51:14,843 20617 INFO modele7 odoo.modules.loading: loading 108 modules...
Warn: Can't find .pfb for face 'Times-Roman'
2017-09-25 15:51:15,001 20617 INFO modele7 odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-09-25 15:51:15,918 20617 INFO modele7 odoo.modules.registry: module website_sale_delivery: creating or updating database tables
2017-09-25 15:51:16,048 20617 INFO modele7 odoo.modules.loading: loading website_sale_delivery/views/website_sale_delivery_templates.xml
2017-09-25 15:51:16,244 20617 INFO modele7 odoo.models.unlink: User #1 deleted ir.translation records with IDs: [76166]
2017-09-25 15:51:16,278 20617 INFO modele7 odoo.modules.loading: loading website_sale_delivery/views/website_sale_delivery_views.xml
2017-09-25 15:51:16,297 20617 INFO modele7 odoo.models.unlink: User #1 deleted ir.translation records with IDs: [53232, 76626]
2017-09-25 15:51:16,397 20617 INFO modele7 odoo.modules.loading: loading website_sale_delivery/data/website_sale_delivery_data.xml
2017-09-25 15:51:16,416 20617 INFO modele7 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [18736]
2017-09-25 15:51:16,461 20617 INFO modele7 odoo.sql_db: bad query: INSERT INTO "product_template" ("id", "list_price", "sequence", "tracking", "uom_id", "availability", "sale_ok", "purchase_method", "purchase_ok", "company_id", "track_service", "uom_po_id", "type", "website_published", "expense_policy", "purchase_line_warn", "active", "categ_id", "rental", "sale_delay", "website_sequence", "invoice_policy", "website_size_x", "website_size_y", "sale_line_warn", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('product_template_id_seq'), '1.00', 1, 'none', 1, 'in_stock', true, 'receive', true, 1, 'manual', 1, 'product', false, 'no', 'no-message', true, 1, false, 1.0,  -311, 'order', 1, 1, 'no-message', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-09-25 15:51:16,461 20617 ERROR modele7 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 335, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/site-packages/odoo/addons/delivery/models/delivery_carrier.py", line 253, in create
    res = super(DeliveryCarrier, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3887, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/site-packages/odoo/addons/product/models/product.py", line 316, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3887, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/site-packages/odoo/addons/product/models/product_template.py", line 267, in create
    template = super(ProductTemplate, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xab name \xbb
D\xc9TAIL : La ligne en \xe9chec contient (5274, null, 1.00, null, 1, null, 1, 1, null, null, 2017-09-25 15:51:16.002007, 1, t, t, null, 1, 1, null, null, null, 2017-09-25 15:51:16.002007, t, 1, null, f, product, no-message, null, manual, order, no, null, in_stock, null, null, 1, null, null, null, f, 1, -311, null, null, 1, null, none, null, receive, no-message, null, null)
" while parsing /usr/lib/python2.7/site-packages/odoo/addons/website_sale_delivery/data/website_sale_delivery_data.xml:3, near
<record id="delivery.free_delivery_carrier" model="delivery.carrier">
        <field name="website_published" eval="True"/>
    </record>
2017-09-25 15:51:16,464 20617 CRITICAL modele7 odoo.service.server: Failed to initialize database `modele7`.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 335, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/site-packages/odoo/addons/delivery/models/delivery_carrier.py", line 253, in create
    res = super(DeliveryCarrier, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3887, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/site-packages/odoo/addons/product/models/product.py", line 316, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3887, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/usr/lib/python2.7/site-packages/odoo/addons/product/models/product_template.py", line 267, in create
    template = super(ProductTemplate, self).create(vals)
  File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xab name \xbb
D\xc9TAIL : La ligne en \xe9chec contient (5274, null, 1.00, null, 1, null, 1, 1, null, null, 2017-09-25 15:51:16.002007, 1, t, t, null, 1, 1, null, null, null, 2017-09-25 15:51:16.002007, t, 1, null, f, product, no-message, null, manual, order, no, null, in_stock, null, null, 1, null, null, null, f, 1, -311, null, null, 1, null, none, null, receive, no-message, null, null)
" while parsing /usr/lib/python2.7/site-packages/odoo/addons/website_sale_delivery/data/website_sale_delivery_data.xml:3, near
<record id="delivery.free_delivery_carrier" model="delivery.carrier">
        <field name="website_published" eval="True"/>
    </record>

**Comment by zeroheure** [comment]
To repair, just update the Delivery Costs (technical name `delivery`) module either on the broken database or on a restored backup.
