### ISSUE TITLE
Odoo11 ImportError: No module named web_kanban

### ISSUE THREAD

**Issue by n37r06u3** [odoo/odoo#19891]
Impacted versions:
odoo11

**Comment by Yenthe666** [comment]
Hi @n37r06u3,

Thank you for your report.
Please follow the template and add in more information about the problem.
How did you get it? Can you reproduce it? Can you trigger it on an official instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by n37r06u3** [comment]
It was my odoo.conf error, odoo11 no need web_kanban~
server_wide_modules = web,web_kanban

**Comment by tejastank** [comment]
python3 odoo-bin --addons-path addons  --xmlrpc-port 8811

Gives bug.

python3 odoo-bin --addons-path addons  --xmlrpc-port 8811 
2017-11-24 12:41:47,345 25836 INFO ? odoo: Odoo version 11.0
2017-11-24 12:41:47,346 25836 INFO ? odoo: Using configuration file at /home/devid/.odoorc
2017-11-24 12:41:47,346 25836 INFO ? odoo: addons paths: ['/home/devid/.local/share/Odoo/addons/11.0', '/home/devid/source/odoo/odoo-11c/addons', '/home/devid/source/odoo/odoo-11c/odoo/addons']
2017-11-24 12:41:47,347 25836 INFO ? odoo: database: default@default:default
2017-11-24 12:41:47,393 25836 CRITICAL ? odoo.modules.module: Couldn't load module web_kanban
2017-11-24 12:41:47,393 25836 CRITICAL ? odoo.modules.module: No module named 'web_kanban'
2017-11-24 12:41:47,393 25836 ERROR ? odoo.service.server: Failed to load server-wide module `web_kanban`.
Traceback (most recent call last):
  File "/home/devid/source/odoo/odoo-11c/odoo/service/server.py", line 866, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/devid/source/odoo/odoo-11c/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/devid/source/odoo/odoo-11c/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'web_kanban'
2017-11-24 12:41:47,396 25836 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8811
2017-11-24 12:41:47,574 25836 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf



In addons don't found web_kanban ?

**Comment by harked** [comment]
does this issue has been fixed?

**Comment by tuksik** [comment]
Remove ~/.odoorc and try again.

**Comment by mehdi-24** [comment]
does this issue has been fixed? I face the same error on windows with odoo 13

**Comment by Floggedhorse** [comment]
> Remove ~/.odoorc and try again. 

Cheers tuksik ... For any other lost souls....
Line 2 of the error states "2017-11-24 12:41:47,346 25836 INFO ? odoo: Using **configuration** file at /home/devid/.odoorc"

in my case it was /.openerp_serverrc

vim into this and read...you'll quickly realise why the error, mine was left over from a odoo 9 install :(
