### ISSUE TITLE
[11.0]: Point of sale configuration generates error

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#19908]
Impacted versions:
version 11 (source dated: 3 Oct 2017)

Steps to reproduce:
Point of Sale > Configuration > Point of Sale create a record, check either "Is a Bar/Restaurant" or "Global Discounts" and then save.

Current behavior:
```
Error:
TypeError: this.editor.snippetsMenu is undefined

http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1981
Traceback:
commitChanges@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1981:1
OdooClass.extend/</prototype[name]</<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:3811:485
commitChanges/defs<@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1259:184
_.collect@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:13:270
commitChanges@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1259:123
exec/<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:3997:295
then/</</<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:802:678
fire@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:796:281
add@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:797:467
then/</<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:802:631
each@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:625:758
then/<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:802:553
Deferred@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:803:189
then@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:802:518
exec@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:3997:257
saveRecord@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1248:787
saveRecord@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1345:354
OdooClass.extend/</prototype[name]</<@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:3811:485
_onSave@http://192.168.1.110/web/content/976-9cf9e67/web.assets_backend.js:1350:777
dispatch@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:892:378
add/elemData.handle@http://192.168.1.110/web/content/745-d241ab8/web.assets_common.js:865:151
```

**Comment by Yenthe666** [comment]
Hi @peterhoth,

Thank you for your report.
I've just checked this on the latest 11.0 and it works without any problems:
![image](https://user-images.githubusercontent.com/6352350/31265676-4fc08ae8-aa70-11e7-92a1-c7df62873cc8.png)
Could you try it again on an official Odoo instance (at runbot.odoo.com) or after updating your own Odoo?

Regards,
Yenthe

**Comment by peterhoth** [comment]
Hi @Yenthe666,

I downloaded the latest source (4 oct 2017) and this seems to fix the issue. Will do further test. Thanks!

**Comment by Yenthe666** [comment]
You're welcome - best of luck!

**Comment by Yenthe666** [comment]
As a sidenote: fixed by https://github.com/odoo/odoo/commit/94cddf69e453ff4cb80a070d1d8b301b0a4b9298 on 04/10/2017.

**Comment by sandhya834** [comment]
Point of sale for odoo11 generates error while configuration.Please help.I am new to odoo.just installed odoo11 and its throwing these errors.
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7ff0812bb158>, 'point_of_sale.fruits_vegetables')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: point_of_sale.fruits_vegetables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 641, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 113, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 28, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: point_of_sale.fruits_vegetables" while evaluating
"[(6, 0, [ref('point_of_sale.fruits_vegetables')])]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_config.py", line 347, in create
    pos_config.sudo()._check_modules_to_install()
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_config.py", line 385, in _check_modules_to_install
    module_to_install.button_immediate_install()
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 641, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 113, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 28, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "<class 'ValueError'>: "External ID not found in the system: point_of_sale.fruits_vegetables" while evaluating
"[(6, 0, [ref('point_of_sale.fruits_vegetables')])]"" while parsing /usr/lib/python3/dist-packages/odoo/addons/pos_restaurant/data/pos_restaurant_demo.xml:8, near
<record id="kitchen_printer" model="restaurant.printer">
            <field name="name">Kitchen Printer</field>
            <field name="proxy_ip">localhost</field>
            <field name="product_categories_ids" eval="[(6, 0, [ref('point_of_sale.fruits_vegetables')])]"/>
        </record>

**Comment by zeintiz** [comment]
hi . also in odoo 13 i  want install pos , it generate error or odoo notification arise connection lost. after 2 second connect restore  again. please help me.
![pose](https://user-images.githubusercontent.com/32398254/91642626-1f2ceb00-ea42-11ea-9a46-6adad492a9de.png)

**Comment by mamiu** [comment]
@zeintiz Your issue is (very likely) unrelated to this Github issue. It seems like that you have longpolling misconfigured. If you're using a proxy make sure that longpolling is setup properly. As described here: https://odoo-development.readthedocs.io/en/latest/admin/longpolling.html
