### ISSUE TITLE
[11.0] Inventory doesn't work

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#19905]
Impacted versions:
v11e

Steps to reproduce:
1. Create a Product.
2. Click on "Update Qty on Hand".
3. Input a quantity and click apply.

Current behavior:
1. Quantity is not being really updated, product will still show zero (0) quantity.
2. Movement is shown on inventory but isn't really affecting the product.
3. Other modules like MRP keep waiting for the quantity to become available, meaning inventory isn't really being updated.

Expected behavior:
1. Movement to get applied when Qty On Hand is set affecting the product's availability.

Video/Screenshot link (optional):

**Comment by edsersolis** [comment]
I changed the title because I now notice that nothing from inventory actually works, moves show in the Stock Moves report.

But I tried receiving stock through the Update Qty on Hand, through Purchases, through Inventory Adjustments and nothing work.

Trying to do an inventory adjustment always shows this error (note: there are no custom modules only oem):

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/stock/models/stock_inventory.py", line 190, in action_start
    vals.update({'line_ids': [(0, 0, line_values) for line_values in inventory._get_inventory_lines_values()]})
  File "/odoo/odoo-server/src/odoo/addons/stock/models/stock_inventory.py", line 251, in _get_inventory_lines_values
    GROUP BY product_id, location_id, lot_id, package_id, partner_id """ % domain, args)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 3:             WHERE  location_id in () AND company_id = 1 AND ...
                                           ^`

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Thank you for your report.
Something does look off here and I also found another bug.
1. Create a product
2. Open the tab "inventory"
3. Check and uncheck the different routes for the product
4. Behold, a  JavaScript traceback:
![image](https://user-images.githubusercontent.com/6352350/31265589-ea1dff4a-aa6f-11e7-9923-a05dbd087ddb.png)

**Comment by Yenthe666** [comment]
@mart-e and @nim-odoo could one of you look at this? It tends to break very fast on one of the most used Odoo features 😉

**Comment by nim-odoo** [comment]
@Yenthe666 : you should better ping @sle-odoo for logistic issues for the time being.

**Comment by Yenthe666** [comment]
Alright, thank you for letting me know!

**Comment by sle-odoo** [comment]
@edsersolis Hello, i tried reproducing your steps and it worked at my end. Could you be more specific? Did you work on a database with demo data or an empty one? What are the installed modules? Did you enable the multi locations options?

This error happens when you create an inventory adjustment on a disabled location (the first step is to make a child_of with the orm, if the location is disabled it returns nothing and this traceback is displayed).

**Comment by edsersolis** [comment]
@sle-odoo empty DB. All 46 stock applications (plus all dependencies that give a total of 150). No multi-locations.

Everything is set up correctly, I enabled the multi-locations to make sure the selected location was enabled and still not working.

Then I tried with multi-warehouse but when trying to create a new warehouse I get the following error:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/stock/models/stock_warehouse.py", line 90, in create
    vals['view_location_id'] = self.env['stock.location'].create(loc_vals).id
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3281, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3407, in _create
    pleft = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

**Comment by jco-odoo** [comment]
update module maybe first for recalculating parent_left/right

**Comment by wtaferner** [comment]
@jco-odoo 
I got a similar issue that the parent_left/right was not calculated properly from the start (fresh db), probably with an incomplete install or issue during the installation, but mainly b/c the columns are created and not recalculated later...so the solution is to delete the columns and upgrade the module again to let them be computed.

I had this before and it is very difficult to spot...maybe we can do some kind of consistency check for parent_left and parent_right on module upgrade in order to recreate them automatically in case the check fails?

**Comment by edsersolis** [comment]
After updating the module as @jco-odoo suggested I now get the quantities updated but still they don't get displayed on the Qty Available nor Forcasted buttons:

![image](https://user-images.githubusercontent.com/6585110/31396548-ab63aaa8-adb1-11e7-917f-5012e7f79033.png)

![image](https://user-images.githubusercontent.com/6585110/31396579-bf441db4-adb1-11e7-807d-7432dcaef055.png)

But when I try to make a SO it warns that I have no units available to sell. When I go to the location and check to see the current stock it has nothing shows:

![image](https://user-images.githubusercontent.com/6585110/31396984-c6d5cfe0-adb2-11e7-8604-f6fd2c4fcb5b.png)

Apparently the issue is within the WH and Locations because when I try to create a new WH the error in my past comment shows up.

**Comment by edsersolis** [comment]
After uninstalling and reinstalling the Inventory module everything is working fine. **I would suggest to have a check on the installation process when multiple modules are selected and mass installed.**

**Comment by janarthanandev** [comment]
We are also facing the same issue in v10. we have customer data so we would not able to uninstall the module is there any other possible ways.

**Comment by jco-odoo** [comment]
update the module

**Comment by afwanwh** [comment]
Dear All,

Just let you know that I found the problem on v9 too.

**Comment by janarthanandev** [comment]
hi @afwanwh do module update if it not seems to be working then manually update the correct value of parent_left/parent_right

**Comment by flotho** [comment]
Hi, @jco-odoo , updating the module does not seem to recompute parent_left and right fields.
So deleting them first is needed.
