### ISSUE TITLE
[11.0]: Translated Terms synchronize Error 

### ISSUE THREAD

**Issue by hanyelbanna** [odoo/odoo#19911]
Impacted versions:
11.0
Steps to reproduce:
Translations -> Synchronize Terms -> Language : Arabic
Current behavior:
Error:
Odoo Server Error
```
Error:
Traceback (most recent call last):
  File "/Users/rubyonrails/odoo/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rubyonrails/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/rubyonrails/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/Users/rubyonrails/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rubyonrails/odoo/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rubyonrails/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rubyonrails/odoo/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rubyonrails/odoo/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/Users/rubyonrails/odoo/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/Users/rubyonrails/odoo/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rubyonrails/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rubyonrails/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rubyonrails/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rubyonrails/odoo/odoo/addons/base/module/wizard/base_update_translations.py", line 42, in act_update
    tools.trans_load_data(self._cr, buf, 'csv', this.lang, lang_name=lang_name)
  File "/Users/rubyonrails/odoo/odoo/tools/translate.py", line 1034, in trans_load_data
    fileobj.seek(0)
ValueError: I/O operation on closed file.
```
Expected behavior:
Do Synchronize Terms

**Comment by Yenthe666** [comment]
Hi @hanyelbanna,

Thank you for your report.
I can confirm that there is a bug here:
![image](https://user-images.githubusercontent.com/6352350/31279958-24da821c-aaab-11e7-881e-74c0cf098bbe.png)
On a sidenote: it is in every language, so it is the method itself that is broken. The error is coming from https://github.com/odoo/odoo/blob/11.0/odoo/tools/translate.py#L1034
@mart-e could you have a look? This is broken in all languages on any 11.0 instance. By just looking at the code I couldn't see anything off.

Regards,
Yenthe

**Comment by mart-e** [comment]
@hanyelbanna thanks for the report, we will look at it.
But just wondering: what do you think this button does? I believe we should remove it because it does not what people think.

**Comment by hanyelbanna** [comment]
Hi,
I think it synchronize new terms to translate it.

Kind regards,
Hany

**Comment by mart-e** [comment]
That is what I thought :-)
To do so, you must use the "load translation" button.
The synchronize terms will recreate missing empty translations for new records (e.g. after import). It is rarely useful, I will see if we can remove/hide it instead.

**Comment by mart-e** [comment]
The error was fixed and the interface should be clarified now
