### ISSUE TITLE
Website Builder Installation Failed odoo 11 Enterprise Edition

### ISSUE THREAD

**Issue by injazllc** [odoo/odoo#19931]
Try to install website builder but it shows error on odoo 11 Enterprise Edition

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 70, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 437, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 530, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 341, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 240, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 130, in load_module_graph
    model_names = registry.load(cr, package)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 248, in load
    model = cls._build_model(self, cr)
  File "/odoo/odoo-server/odoo/models.py", line 426, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'sms.provider' does not exist in registry.

**Comment by Yenthe666** [comment]
Hi @injazllc,

Thank you for your bug report.
I can confirm that this is a bug in Odoo:
![image](https://user-images.githubusercontent.com/6352350/31310245-e000402e-ab94-11e7-85d2-31ae8d032161.png)

@JKE-be could you please have a look? Quite a big breaker.

Regards,
Yenthe

**Comment by JKE-be** [comment]
Hi,

Thanks for the reporting. But I cannot reproduce 

Are you sure that you have the last code (community et enterprise pulled) ?
or that your don't install the database before the 2 octobre? 

This code has been deleted in commit: https://github.com/odoo/enterprise/commit/08c2180da71e237bcde6d4e3bc02c8eab073ef82

Best regards

ps @Yenthe666 : your traceback is not the same, if you arrive to reproduce it, maybe I can take a look :)

**Comment by gdgellatly** [comment]
odoo-bin -u base -d mydb --workers=0 --stop-after-init

Standard stuff, when models are in change prerelease.

**Comment by purit** [comment]
Hi Yenthe666
I have the same problem with you.
Please tell me how to fix it.
I use odoo 10 installed on ubuntu 16 on Google Cloud platform.

Best regards

**Comment by Yenthe666** [comment]
@purit can you provide us with a way to reproduce it then please?

**Comment by purit** [comment]
I follow by your way.
https://www.odoo.yenthevg.com/installing-odoo-10-ubuntu-16-04/
