### ISSUE TITLE
[Odoo 11.0] Google Calendar sync broke Odoo Calendar

### ISSUE THREAD

**Issue by jboilesen** [odoo/odoo#19955]
Impacted versions: 
Odoo 11.0-20171004 (Community Edition)

Steps to reproduce:
1. Configure Google Calendar Integration through Google API
2. Create future event on Calendar
3. Sync it with google and authorize it
4. Try to delete event and sync with google calendar
5. It should appear an "Odoo server error" message with this stack trace:
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4123, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1653, in search
    events = self.browse(events.get_recurrent_ids(args, order=order))
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1131, in get_recurrent_ids
    return [r['id'] for r in sorted(result_data, key=key)]
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1039, in __lt__
    def __lt__(self, other): return self.val > other.val
TypeError: unorderable types: str() > int()

Current behavior:
Unable to sync Google Calendar with Odoo calendar

Expected behavior:
Should be able to sync Odoo calendar with Google Calendar

**Comment by Yenthe666** [comment]
@JKE-be this looks like one for you.

**Comment by C3POdoo** [comment]
Dear @jboilesen,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
