### ISSUE TITLE
SBError: [Errno None] couldn't opendir(): No such file or directory

### ISSUE THREAD

**Issue by yhugir** [odoo/odoo#19953]
Impacted versions:
10
Steps to reproduce:
i have installed odoo on docker on Fedora 26
i have installed hw_proxy and escpos  
this haben with or without PosBox
Current behavior:

2017-10-08 15:24:45,424 1 INFO ? odoo.addons.hw_escpos.controllers.main: error : [Errno None] couldn't opendir(): No such file or directory
2017-10-08 15:24:45,424 1 ERROR ? odoo.addons.hw_escpos.controllers.main: ESC/POS Error: [Errno None] couldn't opendir(): No such file or directory
2017-10-08 15:24:45,424 1 ERROR ? odoo.addons.hw_escpos.controllers.main: [Errno None] couldn't opendir(): No such file or directory
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/hw_escpos/controllers/main.py", line 148, in run
    printer = self.get_escpos_printer()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/hw_escpos/controllers/main.py", line 101, in get_escpos_printer
    printers = self.connected_usb_devices()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/hw_escpos/controllers/main.py", line 79, in connected_usb_devices
    for printer in printers:
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1175, in device_iter
    for dev in backend.enumerate_devices():
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 386, in enumerate_devices
    _check(_lib.usb_find_busses())
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
USBError: [Errno None] couldn't opendir(): No such file or directory

when i check the http://0.0.0.0:8070/hw_proxy/status 
i get  
![screenshot-2017-10-8 odoo s posbox](https://user-images.githubusercontent.com/19690178/31318382-f2949972-ac59-11e7-9015-af239690a0f4.png)

Expected behavior:
shuold be able to print recipies

Video/Screenshot link (optional):

**Comment by C3POdoo** [comment]
Dear @yhugir,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
