### ISSUE TITLE
[11.0] UnicodeDecodeError when translate

### ISSUE THREAD

**Issue by dnt83** [odoo/odoo#20075]
Impacted versions: 11 Community

Steps to reproduce: 
1. Add new vietnamese lanague
2. Click translate in website
![ari homepage ari logistics](https://user-images.githubusercontent.com/5275039/31478449-a587cc88-af3a-11e7-8cd8-6e049a695f37.png)

IN Server raise error:
```
> "GET /web/webclient/locale/vi_VN HTTP/1.1" 500 -
> 2017-10-11 09:56:04,609 3345 ERROR ARILogistics werkzeug: Error on request:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
>     execute(self.server.app)
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 168, in execute
>     application_iter = app(environ, start_response)
>   File "/opt/odoo/odoo/service/server.py", line 254, in app
>     return self.app(e, s)
>   File "/opt/odoo/odoo/service/wsgi_server.py", line 166, in application
>     return application_unproxied(environ, start_response)
>   File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
>     result = handler(environ, start_response)
>   File "/opt/odoo/odoo/http.py", line 1298, in __call__
>     return self.dispatch(environ, start_response)
>   File "/opt/odoo/odoo/http.py", line 1272, in __call__
>     return self.app(environ, start_wrapped)
>   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 591, in __call__
>     return self.app(environ, start_response)
>   File "/opt/odoo/odoo/http.py", line 1473, in dispatch
>     result = ir_http._dispatch()
>   File "/opt/odoo/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
>     return super(IrHttp, cls)._dispatch()
>   File "/opt/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
>     return super(Http, cls)._dispatch()
>   File "/opt/odoo/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
>     return super(IrHttp, cls)._dispatch()
>   File "/opt/odoo/odoo/addons/http_routing/models/ir_http.py", line 397, in _dispatch
>     result = super(IrHttp, cls)._dispatch()
>   File "/opt/odoo/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
>     response = super(IrHttp, cls)._dispatch()
>   File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
>     return cls._handle_exception(e)
>   File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 159, in _handle_exception
>     return super(Http, cls)._handle_exception(exception)
>   File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
>     return request._handle_exception(exception)
>   File "/opt/odoo/odoo/http.py", line 761, in _handle_exception
>     return super(HttpRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
>     raise value
>   File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
>     result = request.dispatch()
>   File "/opt/odoo/odoo/http.py", line 820, in dispatch
>     r = self._call_function(**self.params)
>   File "/opt/odoo/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo/http.py", line 927, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 522, in load_locale
>     momentjs_locale = f.read()
>   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 492: ordinal not in range(128)
```
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @dnt83,

Thank you for your report.
I've just tried this on the latest Odoo 11 (at runbot.odoo.com) but couldn't reproduce the issue. Perhaps there is something odd in your custom page.
@xmo-odoo could this be one of those P3 conversion issues?

Regards,
Yenthe

**Comment by xmo-odoo** [comment]
@Yenthe666 like a lack of conversion issue more than a conversion one, but it's a bit odd as the default encoding for python3 `open` should be utf-8, not ascii. Looking into it.

**Comment by xmo-odoo** [comment]
@dnt83 are you per chance running Odoo on Windows?

**Comment by thomas15v** [comment]
@xmo-odoo Same issue on docker. Tried logging in with a user that has its language set to "Dutch (BE)", and it [crashed ](https://gist.github.com/thomas15v/46eeb439671766ffcac9fc3498a00559/)on `/web/webclient/locale/nl_BE`.

**Comment by dnt83** [comment]
@xmo-odoo i run on Ubuntu (Docker)

**Comment by xmo-odoo** [comment]
> @Yenthe666 like a lack of conversion issue more than a conversion one, but it's a bit odd as the default encoding for python3 open should be utf-8, not ascii. Looking into it.

So it *is* in fact a lack of conversion more than an incorrect conversion, but my recollection was incorrect, Python 3's `open` actually defaults to the encoding advertised by the underlying machine if no encoding is provided, so e.g. if LC_ALL is defined as `X.ascii` bare `open(p, 'r')` calls will be decoded in ascii which obviously is not what we want.

Now these calls should be rare as Odoo has a `file_open` wrapper which forces the encoding to UTF-8 for "text" reads and we generally try to use "binary" IO (`rb`), but the momentjs locale file was in fact a case of both "text" IO and "native" open.

**Comment by dnt83** [comment]
Thank you very much @xmo-odoo @Yenthe666

**Comment by Ademord** [comment]
Also present in Spanish (BO), the docker image is yet to be updated/pushed.
