### ISSUE TITLE
[11.0 E] Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by thegunshow** [odoo/odoo#20099]
Impacted versions: 11.0 Enterprise

Steps to reproduce: Set worker > 0

Current behavior: Slow response and pages dont load

Expected behavior: Odoo should be faster with worker > 0

Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

**Comment by mlaitinen** [comment]
Are you accessing Odoo via port 8072? How is your reverse proxy configured?  I have seen this happen due to reverse proxy misconfiguration where all traffic was forwarded to 8072 instead of 8069.

**Comment by mah007** [comment]
File "/home/odoo/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable


i have the same error and i have no firewall and proxy server

**Comment by aydi-nebil** [comment]
`> /home/nebil/Odoo/odoo/addons/bus/controllers/main.py(37)poll()
-> raise Exception("bus.Bus unavailable")
(Pdb) `
Same Problem here :(

**Comment by arafatx** [comment]
@mlaitinen Mine is already forwarded to 8069. I set worker to 0, when I print invoice it took about 10 seconds to generate the PDF file. When I put worker more than 0, I can go to bed.

**Comment by mlaitinen** [comment]
@arafatx does it help if you set `report.url` to `http://localhost:8069` in system parameters?

**Comment by arafatx** [comment]
@mlaitinen that seems to solve the issue. Thanks
