### ISSUE TITLE
[11.0] Portal Access Management In Partner

### ISSUE THREAD

**Issue by milanpatel1519** [odoo/odoo#20140]
Impacted versions: 11.0

Steps to reproduce: Server action Portal Access Management in Partner view as per screen shots

Current behavior: If I enable then gets an error.

Expected behavior: Has to tick that check box and onchange event.

Video/Screenshot link (optional):

![res](https://user-images.githubusercontent.com/21196280/31545477-36830704-b03d-11e7-9103-6fa8d1697e98.png)

![checkbox](https://user-images.githubusercontent.com/21196280/31545480-3a2ba190-b03d-11e7-89c4-9a5934d7969f.png)

![error](https://user-images.githubusercontent.com/21196280/31545483-3bf127d4-b03d-11e7-8797-f4f55d93bb08.png)

Error: 
Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:3993
Traceback:
Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
    at Object.setSelectionRange (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:3993:92)
    at http://127.0.0.11:11000/web/content/1389-2153b98/web.assets_backend.js:1511:467
    at http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:802:681
    at fire (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:796:299)
    at Object.add [as done] (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:797:467)
    at Array.<anonymous> (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:802:649)
    at Function.each (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:625:767)
    at Object.<anonymous> (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:802:560)
    at Function.Deferred (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:803:194)
    at Object.then (http://127.0.0.11:11000/web/content/1388-c3fcdcf/web.assets_common.js:802:525)

**Comment by Yenthe666** [comment]
Hi @milanpatel1519,

Thanks a lot for your report.
This is indeed a bug. @ged-odoo this looks JS related 😉

**Comment by jjordaan79** [comment]
Hi,

Is there perhaps any fix for this issue yet? I have searched all over but was unable to find any.

**Comment by mge-odoo** [comment]
Hi @milanpatel1519 

Thanks for reporting this issue.

The rev. https://github.com/odoo/odoo/commit/9f7af9f9b742d08ca69a4d4d0b963f625c4b4bba has fixed it. Do not hesitate to reopen it if I'm wrong.

Regards,

Martin
