### ISSUE TITLE
[11.0] install: CREATE DATABASE failed due to to concurrent update

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20175]
### Impacted versions:
11.0

### Steps to reproduce:
**Install Odoo with this specifications:**
- Ubuntu Xenial 
- Python 3.5.4
- PostgreSQL 9.6
- Demo data

**PostgreSQL Optimization**
```shell
max_connections = 800
shared_buffers = 1GB
effective_cache_size = 2GB
work_mem = 10MB
maintenance_work_mem = 256MB
min_wal_size = 2GB
max_wal_size = 4GB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
```

### Current behavior:
```python
2017-10-16 00:40:24,517 366 INFO pruebas odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...

2017-10-16 00:40:24,800 366 ERROR pruebas odoo.sql_db: bad query: b"UPDATE ir_model SET name='Users',state='base',info=' User class. A res.users record models an OpenERP user and is different\n        from an employee.\n\n        res.users class now inherits from res.partner. The partner model is\n        used to store the data related to the partner: lang, name, address,\n        avatar, ... The user model is now dedicated to technical data.\n    ',transient=false WHERE model='res.users' RETURNING id"
ERROR: could not serialize access due to concurrent update

2017-10-16 00:40:24,800 366 ERROR pruebas odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 135, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 307, in init_models
    func()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 272, in _reflect
    self.env['ir.model']._reflect_model(self)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_model.py", line 247, in _reflect_model
    query_update(cr, self._table, params, ['model'])
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_model.py", line 54, in query_update
    cr.execute(query, values)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update

2017-10-16 00:40:24,802 366 ERROR pruebas odoo.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/service/db.py", line 62, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/src/odoo/odoo/modules/loading.py", line 135, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo-server/src/odoo/odoo/modules/registry.py", line 307, in init_models
    func()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 272, in _reflect
    self.env['ir.model']._reflect_model(self)
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_model.py", line 247, in _reflect_model
    query_update(cr, self._table, params, ['model'])
  File "/odoo/odoo-server/src/odoo/odoo/addons/base/ir/ir_model.py", line 54, in query_update
    cr.execute(query, values)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update

```

### Expected behavior:
Successful Odoo install

**Comment by gustavovalverde** [comment]
@odony, I think this is in your kingdom
