### ISSUE TITLE
install of ldap module on odoo 11 throws error

### ISSUE THREAD

**Issue by sterbhai** [odoo/odoo#20171]
Impacted versions: 11 on ubuntu 16.04 with installed dependencies
```
$ sudo apt install python3-dateutil python3-tz python3-pil
$ sudo dpkg -i python3-qrcode_5.3-1_all.deb
$ sudo dpkg -l python3-pyldap_2.4.25.1-2ubuntu1_amd64.deb
$ sudo dpkg -i python3-vobject_0.9.3-3_all.deb
```
Steps to reproduce: install ldap module from apps
Current behavior: throws error
Expected behavior: no error - install module

Video/Screenshot link (optional):

Fehler:
Odoo Server Error

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 971, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 316, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 700, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 649, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 564, in apply_inheritance_specs
    node = self.locate_node(source, spec)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 505, in locate_node
    nodes = etree.ETXPath(spec.get('expr'))(arch)
  File "src/lxml/xpath.pxi", line 482, in lxml.etree.ETXPath.__init__
  File "src/lxml/xpath.pxi", line 423, in lxml.etree.XPath.__init__
  File "<string>", line None
lxml.etree.XPathSyntaxError: Invalid expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/opt/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/odoo/fields.py", line 1045, in determine_inverse
    # the result is saved to database by BaseModel.recompute()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3011, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3164, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 975, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nInvalid expression', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/module/module.py", line 70, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 437, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 530, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/opt/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 384, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/odoo/fields.py", line 1045, in determine_inverse
    # the result is saved to database by BaseModel.recompute()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 253, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 400, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3011, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3164, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 975, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Invalid expression
None" while parsing None:13, near
<data inherit_id="web.webclient_bootstrap" name="App Drawer - Web Client">

        <xpath expr="//div[@contains('class', 'o_sub_menu')]" position="replace"/>

        <xpath expr="//t[@t-set='head']" position="inside">
            <meta charset="utf-8"/>
            <meta http-equiv="cleartype" content="on"/>
            <meta name="MobileOptimized" content="320"/>
            <meta name="HandheldFriendly" content="True"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        </xpath>

        <xpath expr="//nav[@id='oe_main_menu_navbar']" position="replace">

            <t t-set="body_classname" t-value="'drawer drawer--left o_web_client'"/>

            <header role="banner">
                <nav id="odooAppDrawer" class="app-drawer-nav drawer-nav" role="navigation">
                    <t t-call="web.menu"/>
                </nav>

                <nav class="navbar navbar-default main-nav" role="navigation" groups="base.group_user,base.group_portal">
                    <div class="container-fluid">

                        <div class="navbar-header">

                            <a class="drawer-toggle navbar-collapse collapse btn btn-default app-drawer-toggle" accesskey="A">
                                <span class="sr-only">Toggle App Drawer</span>
                                <i class="fa fa-th fa-lg app-drawer-icon-open" t-translation="off" aria-hidden="true"/>
                            </a>

                            <button type="button" class="app-drawer-toggle drawer-toggle pull-left navbar-toggle collapsed">
                                <span class="sr-only">Toggle App Drawer</span>
                                <div class="fa fa-th fa-lg app-drawer-icon-open"/>
                            </button>

                            <button type="button" id="odooMenuBarToggle" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#odooMenuBarNav">
                                <span class="sr-only">Toggle Navigation</span>
                                <i class="fa fa-bars fa-lg" t-translation="off" aria-hidden="true"/>
                            </button>

                        </div>

                        <div class="collapse navbar-collapse" id="odooMenuBarNav" data-parent="#odooMenuBarToggle" aria-expanded="false">
                            <div class="o_sub_menu" groups="base.group_user,base.group_portal">
                                <t t-call="web.menu_secondary"/>
                            </div>
                        </div>
                    </div>
                    <div class="nav navbar-nav navbar-right navbar-systray o_menu_systray">
                        <ul class="nav navbar-nav navbar-right navbar-systray-item oe_user_menu_placeholder"/>
                        <ul class="nav navbar-nav navbar-right navbar-systray-item oe_systray"/>
                    </div>
                </nav>

            </header>

        </xpath>

    </data>
```

**Comment by mah007** [comment]
when some one answer why 
call me :D

**Comment by firehang** [comment]
@mah007 How can install pyldap in windows10

**Comment by sterbhai** [comment]
got it working - not sure why.
on the third install it worked with the modules mentioned above.
