### ISSUE TITLE
Recurring tasks cannot be saved and crash calendar

### ISSUE THREAD

**Issue by zeljkot** [odoo/odoo#20216]
**Impacted versions:** 11, docker-compose with PostgreSQL

**Steps to reproduce:** Create daily or weekly recurring task.

**Current behavior:** Task creation crashes. Usually, whole calendar app stops working.

**Expected behavior:** Task should be saved. Calendar app should work.

**Video/Screenshot link (optional):**

**Error when I try to save task:**

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 911, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f734feee780>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1502, in create
    meeting = super(Meeting, self).create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 869, in _inverse_dates
    meeting.start = meeting.start_datetime
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 954, in __set__
    record.write({self.name: write_value})
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1459, in write
    self.env['calendar.alarm_manager'].notify_next_alarm(partners_to_notify)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 446, in notify_next_alarm
    notif = self.sudo(user.id).get_next_notif()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 401, in get_next_notif
    all_notif.append(self.do_notif_reminder(alert))
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 428, in do_notif_reminder
    message = meeting.display_time
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1026, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 982, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 973, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 821, in _compute_display_time
    meeting.display_time = self._get_display_time(meeting.start, meeting.stop, meeting.duration, meeting.allday)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 686, in _get_display_time
    date_str = date.strftime(format_date).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Error when I try to access calendar**

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4123, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1653, in search
    events = self.browse(events.get_recurrent_ids(args, order=order))
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1131, in get_recurrent_ids
    return [r['id'] for r in sorted(result_data, key=key)]
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1039, in __lt__
    def __lt__(self, other): return self.val > other.val
TypeError: unorderable types: int() > str()
```

**Comment by Elkasitu** [comment]
@zeljkot fixed in rev f5df4fb
