### ISSUE TITLE
Problem when saving event on Agenda

### ISSUE THREAD

**Issue by neoprogress** [odoo/odoo#20254]
**Impacted versions:**
Odoo 11

**Steps to reproduce:**
- Add new entrie on the Agenda
- Fill Title, Participant, Start time, Tag, Description, Notification, Laps of time, and address
- Save

**Current behavior:**
Message when trying to save.
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 911, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f5831c19940>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 916, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/crm/models/calendar.py", line 38, in create
    event = super(CalendarEvent, self).create(vals)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 1502, in create
    meeting = super(Meeting, self).create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1045, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 869, in _inverse_dates
    meeting.start = meeting.start_datetime
  File "/odoo/odoo-server/odoo/fields.py", line 954, in __set__
    record.write({self.name: write_value})
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 1459, in write
    self.env['calendar.alarm_manager'].notify_next_alarm(partners_to_notify)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 446, in notify_next_alarm
    notif = self.sudo(user.id).get_next_notif()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 411, in get_next_notif
    all_notif.append(self.do_notif_reminder(alert))
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 428, in do_notif_reminder
    message = meeting.display_time
  File "/odoo/odoo-server/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1026, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 982, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 973, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 821, in _compute_display_time
    meeting.display_time = self._get_display_time(meeting.start, meeting.stop, meeting.duration, meeting.allday)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 686, in _get_display_time
    date_str = date.strftime(format_date).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```
After having remove all notification, saving is possible.
**Expected behavior:**
Save the entrie.

**Video/Screenshot link (optional):**

**Comment by sswapnesh** [comment]
@Yenthe666  Similar to #20238 and #20216

**Comment by Yenthe666** [comment]
Hi @neoprogress,

Thank you for your report. I'm closing this one in favour of https://github.com/odoo/odoo/issues/20216 as it is both the same bug.
@sswapnesh thanks for the ping & info 😉 

Regards,
Yenthe
