### ISSUE TITLE
Google sync python 3 error

### ISSUE THREAD

**Issue by totalard** [odoo/odoo#20322]
Impacted versions:11

Steps to reproduce:
Sync with Google Calendar

Solution I think:
It is decoding an already decoded string.. check error message

Current behavior:
Error... 

Expected behavior:
Should work

Video/Screenshot link (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fcf4c314ef0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/google_calendar.py", line 589, in synchronize_events
    res = recs.update_events(lastSync)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/google_calendar.py", line 805, in update_events
    self.create_from_google(event, my_partner_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/google_calendar.py", line 406, in create_from_google
    res = self.with_context(context_tmp).update_from_google(False, event.GG.event, "create")
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/google_calendar.py", line 518, in update_from_google
    res = CalendarEvent.create(result).id
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1502, in create
    meeting = super(Meeting, self).create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3289, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 890, in _inverse_rrule
    meeting.update(data)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4465, in update
    record[name] = value
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4669, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 987, in __set__
    record.write({self.name: write_value})
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/calendar.py", line 25, in write
    return super(Meeting, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 1459, in write
    self.env['calendar.alarm_manager'].notify_next_alarm(partners_to_notify)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 446, in notify_next_alarm
    notif = self.sudo(user.id).get_next_notif()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 401, in get_next_notif
    all_notif.append(self.do_notif_reminder(alert))
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 428, in do_notif_reminder
    message = meeting.display_time
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1059, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1015, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1006, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 821, in _compute_display_time
    meeting.display_time = self._get_display_time(meeting.start, meeting.stop, meeting.duration, meeting.allday)
  File "/usr/lib/python3/dist-packages/odoo/addons/calendar/models/calendar.py", line 686, in _get_display_time
    date_str = date.strftime(format_date).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by xmo-odoo** [comment]
Dupe-ish of #20260
