### ISSUE TITLE
[11.0] Cannot use SKR04 - Error chart_template.py

### ISSUE THREAD

**Issue by johnny-longneck** [odoo/odoo#20379]
Impacted versions:

11.0

Steps to reproduce:

Fresh install Odoo 11. (Yenthe Script - Thanks)
Create Database - Choose Germany
Enable Sales and Accounting Module
Settings: Change Chart of Account from SKR03 to SKR04 (already both installed)

Current behavior:
Error in chart_template.py
Short: 
`File "/odoo/odoo-server/addons/account/models/chart_template.py", line 910, in execute
    IrDefault.sudo().set('product.template', "taxes_id", [taxes_ref[self.sale_tax_id.id]], company_id=company.id)
KeyError: 19`

Expected behavior:
SKR04 is applied

Full error:

`Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 924, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 912, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/res/res_config.py", line 544, in execute
    self.set_values()
  File "/odoo/odoo-server/addons/crm/models/res_config_settings.py", line 50, in set_values
    super(ResConfigSettings, self).set_values()
  File "/odoo/odoo-server/addons/sale/models/res_config_settings.py", line 155, in set_values
    super(ResConfigSettings, self).set_values()
  File "/odoo/odoo-server/addons/account/models/res_config_settings.py", line 100, in set_values
    wizard.execute()
  File "/odoo/odoo-server/addons/account/models/chart_template.py", line 910, in execute
    IrDefault.sudo().set('product.template', "taxes_id", [taxes_ref[self.sale_tax_id.id]], company_id=company.id)
KeyError: 19`

**Comment by Yenthe666** [comment]
Hi @johnny-longneck,

Thank you for your report! I'm happy to see you're using my scripts by the way. 😉 
@lap-odoo perhaps you could have a look at this and/or getting it handled? Since you're **the** localisation/accounting person at the moment

**Comment by lap-odoo** [comment]
@johnny-longneck @Yenthe666 Thanks for reporting this ! 

@kebeclibre is already working on fixing this issue ;)

**Comment by johnny-longneck** [comment]
I am amazed about the good response. 
This issue prevents us from switching to odoo 11 yet.

And again Yenthe, I used the script like 20 times already. I have Odoo running in 2 companies.

**Comment by johnny-longneck** [comment]
The commit from referencing task #20323 does not seem to fix the issue for me - but maybe it was too soon. 
I was checking out the latest 11.0 branch and created a new database.
