### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/new_image'

### ISSUE THREAD

**Issue by jameh198p** [odoo/odoo#20480]
**Impacted versions:**
Odoo 10.0

**Steps to reproduce:**
1. Purchased module "image_upload" for URL, and unzip to my custom addon folder.
2. Module installed successfully at Odoo 10. "App" page.
3. All tabs show up as expect.
4. Export product.template csv/xlxs file  as instruction and copy paste URL into the form.
5. Import products images, then error popup by system.
6. 1st error said IOError: [Errno 21] permission denies /New_image,
7. I create directory/folder "mkdir /New_image under root diectory. and chmod and chown command assigned permission for this folder.
8. The new error shows   IOError: [Errno 21] Is a directory: '/new_image'

**Current behavior:**
=============
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/james/odoo-addons/import_image/wizard/import_image_wizard.py", line 102, in get_file
    self.write_image(csv_data)
  File "/home/james/odoo-addons/import_image/wizard/import_image_wizard.py", line 78, in write_image
    image_path = urllib.urlretrieve(row.get('image'), os.path.join(os.getcwd(), 'new_image'))[0]
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 21] Is a directory: '/new_image'
=============
Expected behavior:
How can I fix the issues? Please help.
Thanks in advance.

**Comment by Yenthe666** [comment]
Hi @jameh198p,

I believe you've bought on of these modules? https://www.odoo.com/apps/modules/browse?search=image_upload
Since these are no modules made by Odoo (and the Github tracker is only for bugs in the official code) there isn't much we can do.
You should try to reach out to the creator of the app and ask him to fix this bug. If your problems persist or the creater of the module doesn't respond you can e-mails apps@odoo.com. Odoo will then try to help you.

Regards,
Yenthe
