### ISSUE TITLE
[11.0] JS Webclient: Merging two contacts and trying to change the target partner

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#20529]
Impacted versions: saas-16 and later

Steps to reproduce:

Got to runbot (enterprise) and try to merge two contacts. The following exception is raised trying to change the target partner.

```
Error:
Uncaught Error: TypeError: 'float' object is unsubscriptable

http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:181
Traceback:
Error: TypeError: 'float' object is unsubscriptable
    at Object.py.PY_getItem (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:181:73)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:266:74)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:261:204)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:261:204)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:262:43)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:265:111)
    at Object.py.evaluate (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:267:99)
    at Object.py.eval (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:272:284)
    at http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2159-803f24e/web.assets_backend.js:380:136
    at Function._.each._.forEach (http://273922-11-0-ebfc55.runbot13.odoo.com/web/content/2080-fd8e974/web.assets_common.js:12:558)

```
Video/Screenshot link (optional):
![merging_contacts](https://user-images.githubusercontent.com/362478/32102958-c6a0bcc8-bb1e-11e7-8a35-63ad40a427e4.JPG)

@ged-odoo @nim-odoo 
Hi Gerry, thank you for your quick bugfixes. Here is another little JS glitch with a many2one wizard modal selection field. Hope it is clear for you...otherwise just let me know.

**Comment by Yenthe666** [comment]
Yup - confirmed. Good find @wtaferner!
A more clear screenshot to prove it:
![image](https://user-images.githubusercontent.com/6352350/32103464-c985eb3c-bb20-11e7-9ece-45ffe23a0a03.png)

**Comment by ged-odoo** [comment]
fixed in commit https://github.com/odoo/odoo/commit/f14aab1827bb3c8ad7090a0c0f259a57e5ca6204.

Thank for the bug report
