### ISSUE TITLE
Export traslate error

### ISSUE THREAD

**Issue by anishukserg** [odoo/odoo#20555]
Error when I export translate 
Impacted versions: 
11.0 from github repo 
Steps to reproduce:
I run 
python3.6 ./odoo-bin --stop-after-init -d test1 -c ../odoo.cfg -l ru --i18n-export=../ru.po --modules base 
I have 
Traceback (most recent call last):
  File "/home/projects/odoo/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/home/projects/odoo/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/home/projects/odoo/odoo/cli/server.py", line 175, in run
    main(args)
  File "/home/projects/odoo/odoo/cli/server.py", line 154, in main
    export_translation()
  File "/home/projects/odoo/odoo/cli/server.py", line 106, in export_translation
    config["translate_modules"] or ["all"], buf, fileformat, cr)
  File "/home/projects/odoo/odoo/tools/translate.py", line 713, in trans_export
    _process(format, modules, translations, buffer, lang)
  File "/home/projects/odoo/odoo/tools/translate.py", line 669, in _process
    writer.write_infos(modules)
  File "/home/projects/odoo/odoo/tools/translate.py", line 622, in write_infos
    'now': datetime.utcnow().strftime('%Y-%m-%d %H:%M')+"+0000",
  File "/home/projects/odoo_dev/odoo11_36/lib64/python3.6/codecs.py", line 719, in write
    return self.writer.write(data)
  File "/home/projects/odoo_dev/odoo11_36/lib64/python3.6/codecs.py", line 378, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes

**Comment by Yenthe666** [comment]
@xmo-odoo since you've fixed those other byte related ones too - can you have a look please?
