### ISSUE TITLE
JS error web.assets_backend.js:2441 when adding custum pivot view to Dashboard

### ISSUE THREAD

**Issue by bozaka** [odoo/odoo#20579]
Impacted versions: Odoo 10 Enterprise

Steps to reproduce:
Add custum pivot view in dashboard (module board)
Click on Search view / Favorites / Add to my Dashboard

Video/Screenshot link (optional):

Uncaught TypeError: Cannot read property 'find' of undefined
http://base_url//web/content/391-999b684/web.assets_backend.js:2441
Retraçage :
TypeError: Cannot read property 'find' of undefined
    at Array.<anonymous> (http://base_url/web/content/391-999b684/web.assets_backend.js:2441:229)
    at fire (http://base_url/web/content/299-93febd7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://base_url/web/content/299-93febd7/web.assets_common.js:546:198)
    at Array.<anonymous> (http://base_url/web/content/299-93febd7/web.assets_common.js:547:874)
    at fire (http://base_url/web/content/299-93febd7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://base_url//web/content/299-93febd7/web.assets_common.js:546:198)
    at Object.<anonymous> (http:/base_url/web/content/299-93febd7/web.assets_common.js:549:491)
    at fire (http://base_url/web/content/299-93febd7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://base_url/web/content/299-93febd7/web.assets_common.js:546:198)
    at Object.<anonymous> (http://base_url/web/content/299-93febd7/web.assets_common.js:547:874)

**Comment by Yenthe666** [comment]
Hi @bozaka,

Thanks a lot for your bug report!
I've just tested this on the latest Odoo 10 Enterprise and it works without any problems:
![image](https://user-images.githubusercontent.com/6352350/32177442-ad75a9c0-bd8a-11e7-9fea-57c787d3ff09.png)

Can you reproduce this on an official Odoo instance (at runbot.odoo.com)? Have you updated your Odoo to the latest code base?
If you're on the latest version or can reproduce it on an official runbot: on which view did you create a custom dashboard items?

Regards,
Yenthe

**Comment by dan18fan** [comment]
Maybe an archived contact?

**Comment by bozaka** [comment]
Thank you for your answers
Update is the solution. It's work fine with new versions
