### ISSUE TITLE
[11.0] Error when copy paste content from MS Word to html editor

### ISSUE THREAD

**Issue by dntq83** [odoo/odoo#20642]
Impacted versions: 11.0
Steps to reproduce: Error when copy paste content from MS Word to html editor (some special tag <o:p>)

Current behavior:
> Odoo Server Error
> Traceback (most recent call last):
>  
>  File "/opt/odoo/odoo/fields.py", line 944, in __get__
>     value = record.env.cache.get(record, self)
>   File "/opt/odoo/odoo/api.py", line 960, in get
>     value = self._data[field][record.id][key]
> KeyError: <odoo.api.Environment object at 0x7fbc74a79780>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 646, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo/http.py", line 683, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo/http.py", line 927, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 920, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 912, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/odoo/addons/website_blog/models/website_blog.py", line 214, in write
>     result = super(BlogPost, self).write(vals)
>   File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 277, in write
>     result = super(MailThread, self).write(values)
>   File "/opt/odoo/odoo/models.py", line 3005, in write
>     self._write(old_vals)
>   File "/opt/odoo/odoo/models.py", line 3103, in _write
>     self.env['ir.translation']._sync_terms_translations(self._fields[name], self)
>   File "/opt/odoo/odoo/addons/base/ir/ir_translation.py", line 454, in _sync_terms_translations
>     value = record[field.name]
>   File "/opt/odoo/odoo/models.py", line 4654, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/opt/odoo/odoo/fields.py", line 948, in __get__
>     self.determine_value(record)
>   File "/opt/odoo/odoo/fields.py", line 1049, in determine_value
>     record._prefetch_field(self)
>   File "/opt/odoo/odoo/models.py", line 2562, in _prefetch_field
>     result = records.read([f.name for f in fs], load='_classic_write')
>   File "/opt/odoo/odoo/models.py", line 2506, in read
>     self._read_from_database(stored, inherited)
>   File "/opt/odoo/odoo/models.py", line 2639, in _read_from_database
>     vals[name] = translate(vals['id'], vals[name])
>   File "/opt/odoo/odoo/fields.py", line 1338, in translate
>     return self.translate(src_trans.get, value)
>   File "/opt/odoo/odoo/tools/translate.py", line 323, in html_translate
>     result = translate_xml_node(root, callback, parse_html, serialize_html)
>   File "/opt/odoo/odoo/tools/translate.py", line 270, in translate_xml_node
>     has_text, node = process(node)
>   File "/opt/odoo/odoo/tools/translate.py", line 230, in process
>     child_has_text, child = process(child)
>   File "/opt/odoo/odoo/tools/translate.py", line 230, in process
>     child_has_text, child = process(child)
>   File "/opt/odoo/odoo/tools/translate.py", line 230, in process
>     child_has_text, child = process(child)
>   File "/opt/odoo/odoo/tools/translate.py", line 218, in process
>     result = etree.Element(node.tag, node.attrib, node.nsmap)
>   File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
>   File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
>   File "src/lxml/apihelpers.pxi", line 122, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17442)
>   File "src/lxml/apihelpers.pxi", line 218, in lxml.etree._setNodeNamespaces (src/lxml/lxml.etree.c:18568)
>   File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
> TypeError: Argument must be bytes or unicode, got 'NoneType'

```
Expected behavior:

Video/Screenshot link (optional):
![2017-11-02_14-18-51](https://user-images.githubusercontent.com/5275039/32314158-0302119e-bfd9-11e7-8945-e5caf13ea6ca.png)
![2017-11-02_14-20-57](https://user-images.githubusercontent.com/5275039/32314175-1b09b13e-bfd9-11e7-8c98-b508e6ef2938.png)

**Comment by Yenthe666** [comment]
Hi @dnt83,

Thanks a lot for your bug report.
Can you please provide with word file and/or the text you tried to copy? This makes it easier to test and reproduce.
@xmo-odoo this looks like `NoneType` issues when pasting specific content.

**Comment by dnt83** [comment]
Please check file in this link https://yadi.sk/i/WQZtZETp3PLJXi
@Yenthe666 Thank you very much

**Comment by Yenthe666** [comment]
Hmm, this seems to work fine for me. Where in Odoo did you try this? In which field? Can you reproduce it on an official Odoo runbot (at runbot.odoo.com)?

**Comment by dnt83** [comment]
I don't know how to using runbot (Can you introduce me).
That error occurred using field html (content field in blog module). 
https://youtu.be/M8-sjw-ANHc

**Comment by C3POdoo** [comment]
Dear @dntq83,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
