### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#20653]
Impacted versions: 10.0

Steps to reproduce:
<ul>
<li>1- Create a RFQ</li>
<li>2- Go to the graph view</li>
<li>3- Click the line chart button</li>
</ul>

Current behavior: 
I get this:
_Uncaught TypeError: Cannot read property 'tooltip' of undefined_

Expected behavior:
Should display  the line char of the current purchase order

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31063466/32337455-fc844d8a-bfe9-11e7-9f5d-86585f6cbf29.png)

**Comment by Yenthe666** [comment]
Hi @guidev224,

I've just tried to reproduce this on the latest Odoo 10 but it works without any problems:
![image](https://user-images.githubusercontent.com/6352350/32363783-4babbd1c-c071-11e7-9971-7cb5b637c2d0.png)
Can you reproduce this on an official Odoo instance (at runbot.odoo.com)? Have you tried updating your Odoo codebase to the latest version?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
I'm closing this bug report as there has been no response on the latest comment. Everything should be working fine.

**Comment by manabendra** [comment]
Hi,

I am using odoo 12. When I am trying to edit the view. I am getting this error

Error:
Uncaught TypeError: Cannot read property 'tooltip' of undefined

http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1559
Traceback:
TypeError: Cannot read property 'tooltip' of undefined
    at Class._addFieldTooltip (http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1559:735)
    at http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1646:343
    at Function._.each._.forEach (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:12:558)
    at Class._updateView (http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1646:3)
    at http://localhost:8069/web/content/635-48ed65a/web.assets_backend.js:1644:1373
    at http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:801:198)
    at deferred.<computed> (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:803:56)
    at fire (http://localhost:8069/web/content/532-8e853a2/web.assets_common.js:796:299)

How can I fix this issue?

**Comment by munesu** [comment]
@manabendra I had the same issue but this did the trick for me: Settings -> Activate developer mode (with assets)
