### ISSUE TITLE
Issue with adding images to products

### ISSUE THREAD

**Issue by jawkhan** [odoo/odoo#20655]
Impacted versions: Odoo Version 11

Steps to reproduce:
Add a product to the inventory. Do not have the option to add a product image. Also occurs in the user view in settings too.

Current behavior:
Continues to print out "Could not display the selected image"

Expected behavior:
Should allow me to add a picture to the product.

<img width="1680" alt="screen shot 2017-11-02 at 17 50 22" src="https://user-images.githubusercontent.com/20640729/32341766-593762ae-bff6-11e7-803a-c96e6e73bcd4.png">

**Comment by Yenthe666** [comment]
Hi @jawkhan,

Thank you for your report.
Can you please update your Odoo to the latest codebase? Can you try to reproduce this on an official Odoo test instance (at runbot.odoo.com)? I've just tried this on the latest Odoo 10.0 and it works without any problems:
![image](https://user-images.githubusercontent.com/6352350/32364036-d7ebfb42-c072-11e7-9eee-9d25d7d12d07.png)

Regards,
Yenthe

**Comment by ThijsvOers** [comment]
Hi,
I had the same issue with images on my local 10 CE Odoo version. I think it started after installing a new module (and of course i do not remember which module it was...)

![one_module_too_many](https://user-images.githubusercontent.com/30256071/32502223-71fe1fe8-c3da-11e7-8f52-2c804dc3a247.png)
When i want to open a product i get the following error, perhaps this helps to solve the issue.

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 827, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 849, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/odoo/odoo-server/odoo/models.py", line 4682, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/models.py", line 1518, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 4224, in _search
    query = self._where_calc(args)
  File "/odoo/odoo-server/odoo/models.py", line 4023, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo/odoo-server/odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "/odoo/odoo-server/odoo/osv/expression.py", line 821, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field u'config_ok' in leaf "<osv.ExtendedLeaf: (u'config_ok', u'=', False) on product_template (ctx: )>"

**Comment by Yenthe666** [comment]
Hi @jawkhan and @ThijsvOers,

I've tried this again on a clean install but everything works fine.
Please update your Odoo and try again. If you can still reproduce it on an official runbot (runbot.odoo.com) then please do let me know and I'll reopen this.

Regards,
Yenthe
