### ISSUE TITLE
[11] create new page with add to menu fails

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#20681]
Impacted versions: 11.0 nightly revision

Steps to reproduce: 
- download, install with website module.
- create a page (no problem), no special page name needed.
- create a page with 'add page in menu' => return 500 see logs below

workaround: create a page without adding to menu, then add to menu, work good. 

Current behavior: adding new page with 'add page to menu' option goes to 500. page is not created too.

Expected behavior: should create the page and add it to menu

Video/Screenshot link (optional):

Error Message:
unsupported operand type(s) for +: 'NoneType' and 'int'

Traceback (most recent call last):
  File "/opt/projects/odoo-v11/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/projects/odoo-v11/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/opt/projects/odoo-v11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/projects/odoo-v11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/projects/odoo-v11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/projects/odoo-v11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/projects/odoo-v11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/projects/odoo-v11/odoo/addons/website/controllers/main.py", line 260, in pagenew
    page = request.env['website'].new_page(path, add_menu=add_menu, **template)
  File "/opt/projects/odoo-v11/odoo/addons/website/models/website.py", line 135, in new_page
    'website_id': self.get_current_website().id,
  File "/opt/projects/odoo-v11/odoo/models.py", line 3275, in create
    record = self.browse(self._create(old_vals))
  File "/opt/projects/odoo-v11/odoo/models.py", line 3393, in _create
    pleft = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thanks a lot for your report.
I've just tried to create a new webpage with the setting "Add page to menu" on and it works fine as is:
![image](https://user-images.githubusercontent.com/6352350/32417536-6850ff5e-c25b-11e7-890f-2963700a515c.png)
Can you try to reproduce this on an official Odoo test instance (at runbot.odoo.com) or try to update your Odoo to the latest source code please?

Regards,
Yenthe

**Comment by ddfs** [comment]
seems good on runbot. I will check again and let you know when I have time to test it on local setup.

**Comment by Yenthe666** [comment]
Thank you! It should be working fine now. 😄

**Comment by ravindragullapalli** [comment]
Still I am getting an error. I created a new database and tried to add new page (Add to menu) as well as new menu. Here is the Traceback

> Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 832, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/website/controllers/main.py", line 261, in pagenew
    page = request.env['website'].new_page(path, add_menu=add_menu, **template)
  File "/opt/odoo/addons/website/models/website.py", line 148, in new_page
    'website_id': self.get_current_website().id,
  File "/opt/odoo/odoo/models.py", line 3415, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/models.py", line 3533, in _create
    pleft = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
