### ISSUE TITLE
[11.0] sinc with google calendar

### ISSUE THREAD

**Issue by enrique90** [odoo/odoo#20733]
Impacted versions: 11.0

Steps to reproduce: 

1. install and set up google calendar
2. create one event in google calender
3. sinc in odoo 
4. then create other event in google calendar
5. sinc again in odoo

Current behavior:
show an error

Expected behavior:
sinc in the right way without errors

File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 692, in update_events
    ('google_internal_event_id', 'in', all_event_from_google.keys())
I think the erros could be because the function keys() doesn´t return a list in python >=3.3

https://stackoverflow.com/questions/16819222/how-to-return-dictionary-keys-as-a-list-in-python

Video/Screenshot link (optional):
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 589, in synchronize_events
    res = recs.update_events(lastSync)
  File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 692, in update_events
    ('google_internal_event_id', 'in', all_event_from_google.keys())
  File "/opt/odoo/odoo11/odoo/models.py", line 1411, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo11/odoo/models.py", line 3677, in _search
    query = self._where_calc(args)
  File "/opt/odoo/odoo11/odoo/models.py", line 3474, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/opt/odoo/odoo11/odoo/osv/expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "/opt/odoo/odoo11/odoo/osv/expression.py", line 1214, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('google_internal_event_id', 'in', dict_keys(['2t36vm9r1ksrh4k8k6jn6fa1ul']))

**Comment by Yenthe666** [comment]
@JKE-be this looks like one for you to check. 😉

**Comment by JKE-be** [comment]
Hi

It has been fixed one week ago in commit 185820e13420517eccfb24a68490cb952e4f9ad8

Please, always pull the last code before to open an issue. 

Best regards
