### ISSUE TITLE
Priority widget always returns string even when column type is int

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#20746]
Impacted versions: 10

Steps to reproduce: 
```
rating = field.Selection([(0, 'Abysmal'), (5, 'Excellent'), ...])

<kanban>
    <field name="rating"/>
</kanban>
```
Current behavior:
Clicking a star on the priority widget

Expected behavior:

Video/Screenshot link (optional):

**Comment by fasnakp** [comment]
> Impacted versions: 10
> 
> Steps to reproduce:
> 
> ```
> rating = field.Selection([(0, 'Abysmal'), (5, 'Excellent'), ...])
> 
> <kanban>
>     <field name="rating"/>
> </kanban>
> ```
> 
> Current behavior: Clicking a star on the priority widget always sends a string value to the server. Because the frontend has no idea weather the selection field is of type string or int.
> 
> ```
> Traceback (most recent call last):
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 640, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 677, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 333, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/karlis/odoo/10/odoo/odoo/service/model.py", line 101, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 326, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 935, in __call__
>     return self.method(*args, **kw)
>   File "/home/karlis/odoo/10/odoo/odoo/http.py", line 506, in response_wrap
>     response = f(*args, **kw)
>   File "/home/karlis/odoo/10/odoo/addons/web/controllers/main.py", line 885, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/home/karlis/odoo/10/odoo/addons/web/controllers/main.py", line 877, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/home/karlis/odoo/10/odoo/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/home/karlis/odoo/10/odoo/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/home/karlis/odoo/10/odoo/addons/mail/models/mail_thread.py", line 274, in write
>     result = super(MailThread, self).write(values)
>   File "/home/karlis/odoo/10/odoo/odoo/models.py", line 3566, in write
>     record._cache.update(record._convert_to_cache(new_vals, update=True))
>   File "/home/karlis/odoo/10/odoo/odoo/models.py", line 4912, in _convert_to_cache
>     for name, value in values.iteritems()
>   File "/home/karlis/odoo/10/odoo/odoo/models.py", line 4913, in <dictcomp>
>     if name in fields
>   File "/home/karlis/odoo/10/odoo/odoo/fields.py", line 1780, in convert_to_cache
>     raise ValueError("Wrong value for %s: %r" % (self, value))
> ValueError: Wrong value for website.form.submission.user_rating: u'5'
> ```
> 
> On possible workaround:
> 
> ```
> web/static/src/js/widgets/priority.js
>     ...
>     events: {
>         ...
>         'click > a': function(e) {
>             e.preventDefault();
>             e.stopPropagation();
>             
>             var old_value = this.value;
>             this.value = $(e.target).data('value');
> 
>             // all column values should be ether integer or varchar
>             if (typeof this.values[0][0] == "string") {
>                 this.value = String(this.value);
>             }
> 
>             if (this.values
>             if(old_value === this.value) {
>                 this.value = this.empty_value;
>             }
> 
>             this._render_value();
>             this.trigger('update', {value: this.value});
>         },
>     },
> ```

how solve this issue,i have same issue
