### ISSUE TITLE
Can't refund an invoice - KeyError: 'team_id'

### ISSUE THREAD

**Issue by kbirkbr** [odoo/odoo#20875]
Impacted versions: 10.0

Steps to reproduce:

1. Install Accounting module (Only).
2. Create and Validate Customer invoice
3. Click on Refund invoice.
4. Choose 'Create draft invoice' as Refund method, and  enter the Reason.
5. Click on Create refund button.

Current behavior: Getting a KeyError: 'team_id'.
Full Traceback:
   
ERROR refund odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/account/wizard/account_invoice_refund.py", line 126, in invoice_refund
    return self.compute_refund(data_refund)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/account/wizard/account_invoice_refund.py", line 60, in compute_refund
    refund = inv.refund(form.date_invoice, date, description, inv.journal_id.id)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/account/models/account_invoice.py", line 1063, in refund
    description=description, journal_id=journal_id)
  File "/home/shar/Projects/odoo-10.0-20170528/odoo/addons/account/models/account_invoice.py", line 1025, in _prepare_refund
    if invoice._fields[field].type == 'many2one':
KeyError: 'team_id'

Expected behavior: Create a Refund Invoice in draft state.

Video/Screenshot link (optional):

**Comment by wtaferner** [comment]
You should update your sources...it was fixed in https://github.com/odoo/odoo/commit/abb71fea51eac0c26a5296c03d1fb7b9657c08d2#diff-eb374e5f26e99054eaf8b40daaebf6f9 (six months ago) and the log somehow communicates that you are using a version from ```odoo-10.0-20170528``` (2017-05-28) two days before it was fixed.

**Comment by Yenthe666** [comment]
Indeed - this bug has been fixed ages ago. Please update your Odoo source code and it'll be fixed.
Thank you for the input @wtaferner!
