### ISSUE TITLE
[11.0] database manager interaction with odoo-bin database parameter

### ISSUE THREAD

**Issue by dion-pci** [odoo/odoo#20999]
Impacted versions:
11.0 enterprise, maybe 11.0 community too.

Steps to reproduce:
1. Run Odoo from command line with either `-d <database>` or `--database <database>` parameter
2. Open Odoo database manager
3. Delete the database specified in the command line parameter

Current behavior:
- Odoo only show the specified database from command line parameter in the database manager
- "500 Internal Server Error" after deleting said database, also can't get back to Odoo

Expected behavior:
- The database manager shows other available database if exist, not only the specified database
- Odoo automatically returns to database manager/selector after deleting the specified database

Video/Screenshot link (optional):

**Comment by dion-pci** [comment]
Log from the terminal.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/data/odoo11/odoo/service/server.py", line 251, in app
    return self.app(e, s)
  File "/data/odoo11/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/data/odoo11/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/data/odoo11/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/data/odoo11/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/data/odoo11/odoo/http.py", line 1471, in dispatch
    result = _dispatch_nodb()
  File "/data/odoo11/odoo/http.py", line 1449, in _dispatch_nodb
    result = request.dispatch()
  File "/data/odoo11/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/data/odoo11/odoo/http.py", line 340, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/data/odoo11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/data/odoo11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/data/odoo11/addons/web/controllers/main.py", line 680, in selector
    return self._render_template(manage=False)
  File "/data/odoo11/addons/web/controllers/main.py", line 670, in _render_template
    d['incompatible_databases'] = odoo.service.db.list_db_incompatible(d['databases'])
  File "/data/odoo11/odoo/service/db.py", line 391, in list_db_incompatible
    with closing(db_connect(database_name).cursor()) as cr:
  File "/data/odoo11/odoo/sql_db.py", line 634, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/data/odoo11/odoo/sql_db.py", line 178, in __init__
    self._cnx = pool.borrow(dsn)
  File "/data/odoo11/odoo/sql_db.py", line 517, in _locked
    return fun(self, *args, **kwargs)
  File "/data/odoo11/odoo/sql_db.py", line 585, in borrow
    **connection_info)
  File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "odoo11e" does not exist
```

**Comment by Yenthe666** [comment]
Hi @dion-pci,

Thank you for your report.
I don't really agree with your report though. The `-d` and `-database` parameters are used to exactly use and show that specific database. If you delete this database from somewhere else but run your Odoo with this parameter it is (in my opinion) your job to change the parameter. 
I don't consider this a bug but the final call is up to @mart-e 

Regards,
Yenthe

**Comment by mart-e** [comment]
Yes exactly. As of Odoo v11, the `--database` parameters acts as the database list.
Check slide 19 of https://www.odoo.com/slides/slide/securing-odoo-deployments-529

**Comment by dion-pci** [comment]
Thank you for the explanation @mart-e.

However, in [Odoo official documentation](https://www.odoo.com/documentation/11.0/reference/cmdline.html) the parameter is still mentioned as only used when installing or updating modules. Perhaps we can have small update in the documentation to clear out the confusion and better explain the new behaviour?

**Comment by mart-e** [comment]
Thanks for the notice, we will clarify the documentation
