### ISSUE TITLE
Failure to create additional Point of Sale (POS) Terminals

### ISSUE THREAD

**Issue by haveyougotanypets** [odoo/odoo#21000]
Impacted versions:
* Odoo 11.0-20171113 (Community Edition)
* Installed using .deb installer
* Running on Ubuntu Server 16.04

Steps to reproduce:
1. Setup new instance
2. Install POS module 
3. POS > Configure > Point of Sale > Create (create a new POS termainl)
4. Fill out form - Submit
5. Error returned as seen below

Current behavior:
* Unable to add new POS. Only the factory default one can be used. 
* Am able to export default POS then re-import - tried changing the name. This succeeded however it just replaced the existing default POS rather than creating another.

Expected behavior:
* To create a new additional POS terminal.

Video/Screenshot link (optional):

<pre>
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_config.py", line 335, in create
    'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting
</pre>

**Comment by Yenthe666** [comment]
Hi @haveyougotanypets,

Thank you for your report.
I've just tried this on the latest Odoo 10.0 (community) and it seems to work fine:
![image](https://user-images.githubusercontent.com/6352350/32885210-23e62c08-cabd-11e7-97eb-03abe884691f.png)
Can you reproduce this on an official runbot (at runbot.odoo.com)? 
@d-fence could this be OS related - I really don't think so?

Regards,
Yenthe

**Comment by haveyougotanypets** [comment]
I have had a look at your runbot and tested on the 11 version. Seems to work fine there.

Is there anything from the error given that would indicate where the error is coming from? my python is a bit rusty and I don't know the codebase.

Also to add: I did initially the v10 branch installed I apt-get purged this and changed the source path to the 11 release and apt-get installed again. I'm not sure if that could have had an effect?

Any feedback welcome. Thanks for your initial fast response!

**Comment by haveyougotanypets** [comment]
p.s. If there is an easy way to amend a exported POS terminal so that when it is re imported it creates a new one rather than overriding itself that would be a good workaround for the time being.

**Comment by Yenthe666** [comment]
@haveyougotanypets not sure about the apt-get purged - I personally haven't used it yet. Perhaps it is worth the try/effort to do a clean V11 install (on another location) to see if that fixes your issues?
About the export/import: you will run into the same issue as the `create` function will be triggered from the import too, which in return would trigger this error I believe.

**Comment by Yenthe666** [comment]
This should have been handled/fixed. I've tried again without any problems. Please try a clean install.
