### ISSUE TITLE
OSError: File not found: l10n_mx_edi/data/3.3/cadenaoriginal.xslt

### ISSUE THREAD

**Issue by GGMEX** [odoo/odoo#21015]
Hi,

I'm having issues to create an invoice on the Mexican Localization or CDFI 3.3
As I understand, the file **l10n_mx_edi/data/3.3/cadenaoriginal.xslt** is missing, but where can I find it?.
Thanks in advance!.

This is the follow error:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo/addons/account/models/account_invoice.py", line 775, in action_invoice_open
    return to_open_invoices.invoice_validate()
  File "/usr/lib/python3.6/site-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 942, in invoice_validate
    record._l10n_mx_edi_retry()
  File "/usr/lib/python3.6/site-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 898, in _l10n_mx_edi_retry
    cfdi_values = inv._l10n_mx_edi_create_cfdi()
  File "/usr/lib/python3.6/site-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 875, in _l10n_mx_edi_create_cfdi
    cadena = self.l10n_mx_edi_generate_cadena(CFDI_XSLT_CADENA % version, tree)
  File "/usr/lib/python3.6/site-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 244, in l10n_mx_edi_generate_cadena
    xslt_root = etree.parse(tools.file_open(xslt_path))
  File "/usr/lib/python3.6/site-packages/odoo/tools/misc.py", line 198, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3.6/site-packages/odoo/tools/misc.py", line 256, in _fileopen
    raise IOError('File not found: %s' % basename)
OSError: File not found: l10n_mx_edi/data/3.3/cadenaoriginal.xslt

**Comment by nhomar** [comment]
- Can you pull your code? because that is not happening at my end.
- And allow us to know which is the process to test your first invoice that you used?

BTW this must be called only when you used to download locally the XSD files with the server action, Did you do that?

Thanks in advance for the report.

**Comment by GGMEX** [comment]
What do you mean about been called only when i'm using to download the XSD files?.
Si es posible, podría comprenderlo mejor en español.

Gracias!.

**Comment by nhomar** [comment]
I am talking [about this.](https://www.odoo.com/documentation/user/11.0/accounting/localizations/mexico.html#enabling-explicit-errors-on-the-cfdi-using-the-xsd-local-validator-cfdi-3-3)

But BTW: There is not know error as the one you are showing I need to understand the steps you follow, because the only way I see it can happen is that you moved the odoo's filestore or something like that.

Can you give me the step by step that you followed?.

and

Can you help me updating properly your code please? and re-check you have the very last version of your enterprise version?

**Comment by GGMEX** [comment]
I have the Enterprise v11.
I already sent you a video.

Do you received it?.

**Comment by nhomar** [comment]
@GGMEX 

Gustavo, what I meant about the version is "when and how did you download it?".

If you download it some weeks, please update your code and re-download all today and re-try AFAICR we solved an error like that few weeks ago.

**Comment by nhomar** [comment]
Another option.

Do the OS odoo's user have permissions for the file system? Windows or Linux!?

**Comment by sle-odoo** [comment]
xslt files seem to not be imported in the [manifest](https://github.com/odoo/odoo/blob/11.0/MANIFEST.in)

@GGMEX Hello, did you install Odoo with our debian package?

**Comment by nhomar** [comment]
ouch....

thanks @sle-odoo I always tests with github, let me test with the debian package.

**Comment by enriquejaquez** [comment]
Hi, 

Thank you for your comments, @nhomar , @sle-odoo and @GGMEX.  I installed Odoo 11 Enterprise and some files were ignored in 3.3 directory.  I copied the .xslt files manually.  Now, the mexican invoicing process is working correctly.

**Comment by GGMEX** [comment]
Quick feedback:

We include all the missing files and now the 3.3 invoicing is working.
Thanks to all especially to @nhomar and @sle-odoo for their help.
