### ISSUE TITLE
Error saving in res.partner

### ISSUE THREAD

**Issue by smartboxid** [odoo/odoo#21021]
Impacted versions:11

Steps to reproduce:Add new address type "Other" and save, while saving partner it will give error

Current behavior:

Expected behavior:

Video/Screenshot link (optional):Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/p5q-pro/PycharmProjects/odoo11/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/addons/base/res/res_partner.py", line 514, in write
    result = result and super(Partner, self).write(vals)
  File "/home/p5q-pro/PycharmProjects/odoo11/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/models.py", line 3011, in write
    self._write(old_vals)
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/models.py", line 3136, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/fields.py", line 2253, in write
    comodel.create(act[2])
  File "/home/p5q-pro/PycharmProjects/odoo11/odoo/addons/base/res/res_partner.py", line 530, in create
    vals['image'] = self._get_default_image(vals.get('type'), vals.get('is_company'), vals.get('parent_id'))
  File "/home/p5q-pro/PycharmProjects/odoo11/custom/tms/models/res_partner.py", line 46, in _get_default_image
    image = parent_image and parent_image.decode('base64') or None
LookupError: 'base64' is not a text encoding; use codecs.decode() to handle arbitrary codecs

**Comment by Elkasitu** [comment]
Hi, it seems the code is being executed from a custom/third-party module named "tms" which uses base64 decoding which is no longer supported in python 3, you should either uninstall this module or try running odoo on python 2

**Comment by Yenthe666** [comment]
Indeed, this bug is not related to Odoo itself but to the custom development.
Your best best is to change the `base64` decoding to support P3.
If you should be stuck with this you can ask help on the official help forums (at help.odoo.com).

Regards,
Yenthe

**Comment by ruifranco** [comment]
I'm actually running against this problem too and with a demo database with just the "sale management" installed. No custom module in my error trail. (also, "base64" is used all over the place in v11, so, how can there be any sort of incompatibility with Python3?)

The quick way I got to fix this was actually overriding the original code:

```
try:
    image = parent_image and parent_image.decode('base64') or None
except:
    image = False

```

**Comment by Elkasitu** [comment]
Hi @ruifranco you are right, I guess I went too quickly over the traceback... I retract my previous statement on base64 not being supported in P3, however there can be incompatibilities indeed since the behaviour has changed from P2 to P3 and that's why we changed it in commit 3824b5dc

cc @xmo-odoo

**Comment by zefoo** [comment]
I'm seeing this too. It seems to happen when I create a res.partner contact that is an address of a parent contact, I mark the type as "other" (it's an address of parent), and then I set the parent_id, then the issue is here in odoo/addons/base/res/res_partner.py(289)_get_default_image():

287             if partner_type in ['other'] and parent_id:
288                 parent_image = self.browse(parent_id).image
289  ->             image = parent_image and parent_image.decode('base64') or None

Sure, I'm writing a custom migration script, but I'm not passing an image to it. I think the image it's trying to pull is the icon image for a company (since this "other" address has the parent_id of a contact type which has the parent_id of a company)... and somehow that's causing the error. I'm relatively new to Odoo, not sure on the solution here but wanted to make note.
