### ISSUE TITLE
[11] stock_location error when -u all

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21098]
Impacted versions: 11

Steps to reproduce:
1 Create testdb with demodata
2 Install app website_sale and delivery
3 git pull odoo to current head
4 restart instance with param -u all

Current behavior:
```
ERROR testdb odoo.sql_db: bad query: b'DELETE FROM stock_location WHERE id IN (35)'
ERROR: FEHLER:  NULL-Wert in Spalte »location_id« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (26, [LAP-CUS] Angepasster Laptop, 10, 1, 2017-11-20 15:29:46.911673, 2017-11-20 15:30:09, 1, 2017-11-20 15:30:09, 34, 15.000, 15.0, 15.000, 1, null, null, 9, null, 14, null, confirmed, null, null, make_to_stock, f, null, null, null, t, null, null, null, null, null, f, Chic/OUT/00001, 1, 1, 2017-11-20 15:30:26.529885, null, null, null, null, null, 0.00, 3).
CONTEXT:  SQL-Anweisung »UPDATE ONLY "public"."stock_move" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id"«

2017-11-20 15:39:34,463 11552 ERROR testdb odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/workspace/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'testdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/workspace/odoo11/odoo/modules/loading.py", line 377, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/workspace/odoo11/odoo/addons/base/ir/ir_model.py", line 1607, in _process_end
    record.unlink()
  File "/opt/workspace/odoo11/odoo/models.py", line 2857, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/workspace/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: FEHLER:  NULL-Wert in Spalte »location_id« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (26, [LAP-CUS] Angepasster Laptop, 10, 1, 2017-11-20 15:29:46.911673, 2017-11-20 15:30:09, 1, 2017-11-20 15:30:09, 34, 15.000, 15.0, 15.000, 1, null, null, 9, null, 14, null, confirmed, null, null, make_to_stock, f, null, null, null, t, null, null, null, null, null, f, Chic/OUT/00001, 1, 1, 2017-11-20 15:30:26.529885, null, null, null, null, null, 0.00, 3).
CONTEXT:  SQL-Anweisung »UPDATE ONLY "public"."stock_move" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id"«

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/workspace/odoo11/odoo/modules/loading.py", line 284, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/workspace/odoo11/odoo/modules/loading.py", line 135, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 310, in init_models
    models[0].recompute()
  File "/opt/workspace/odoo11/odoo/models.py", line 4794, in recompute
    field, recs = self.env.get_todo()
  File "/opt/workspace/odoo11/odoo/api.py", line 911, in get_todo
    field = min(self.all.todo, key=self.registry.field_sequence)
TypeError: unorderable types: NoneType() < NoneType()
```

Expected behavior:
No errors when param -u all . Update all without any problems.

**Comment by Elkasitu** [comment]
Hi, this looks like a python 3 issue, basically in python 2 None objects were orderable but in python 3 they aren't, thus raising the error.

I'll give it a look tomorrow and try to fix it

**Comment by Elkasitu** [comment]
After further inspection, I've determined that the issue is not P3-related but a problem with the location_id field from stock.move, the issue happens when trying to uninstall a module (triggered during the update), some other module uses location_id for something and when it is being deleted it tries to set location_id to null which violates a constraint, and thus the Exception is raised, the last traceback is just a byproduct of this since self.all.todo should not contain any None values.

@Karsten-77 would you mind running this query in your db `SELECT name, state FROM ir_module_module WHERE state='to remove';` and telling me the result ?

**Comment by Karsten-77** [comment]
There is no result.

**Comment by Elkasitu** [comment]
@Karsten-77 I cannot seem to reproduce your issue locally, can you reproduce it on a brand new database? The database that this happened on, was it brand new or had you previously installed/uninstalled applications on?

**Comment by Karsten-77** [comment]
Yes I can reproduce on a brand new database.
1. starting my intance with:
/opt/Envs/Odoo11Python3/bin/python /opt/workspace/ide/pycharm-2017.2.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 37145 --file /opt/workspace/odoo11/odoo-bin -c /opt/workspace/odoo11/odoo-server.conf
2. I go to database/manager and create a testdb with flag for demo data
3. After login I install website_sale and delivery in that sequence
4. i restart instance with param -u all like:
/opt/Envs/Odoo11Python3/bin/python /opt/workspace/ide/pycharm-2017.2.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 37145 --file /opt/workspace/odoo11/odoo-bin -c /opt/workspace/odoo11/odoo-server.conf -u all

getting same error:
```
2017-11-29 10:33:29,933 612 ERROR testdb odoo.sql_db: bad query: b'DELETE FROM stock_location WHERE id IN (34)'
ERROR: FEHLER:  NULL-Wert in Spalte »location_id« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (27, [E-COM07] iPad Mini, 10, 1, 2017-11-29 10:21:03.227306, 2017-11-29 10:21:20, 1, 2017-11-29 10:21:20, 17, 180.000, 180.0, 180.000, 1, null, null, 9, null, 15, null, confirmed, null, null, make_to_stock, f, null, null, null, t, null, null, null, null, null, f, Chic/OUT/00002, 1, 1, 2017-11-29 10:21:32.824304, null, null, null, null, null, 59.40, 3).
CONTEXT:  SQL-Anweisung »UPDATE ONLY "public"."stock_move" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id"«

2017-11-29 10:33:29,934 612 ERROR testdb odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/workspace/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'testdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/workspace/odoo11/odoo/modules/loading.py", line 377, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/workspace/odoo11/odoo/addons/base/ir/ir_model.py", line 1607, in _process_end
    record.unlink()
  File "/opt/workspace/odoo11/odoo/models.py", line 2857, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/workspace/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: FEHLER:  NULL-Wert in Spalte »location_id« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (27, [E-COM07] iPad Mini, 10, 1, 2017-11-29 10:21:03.227306, 2017-11-29 10:21:20, 1, 2017-11-29 10:21:20, 17, 180.000, 180.0, 180.000, 1, null, null, 9, null, 15, null, confirmed, null, null, make_to_stock, f, null, null, null, t, null, null, null, null, null, f, Chic/OUT/00002, 1, 1, 2017-11-29 10:21:32.824304, null, null, null, null, null, 59.40, 3).
CONTEXT:  SQL-Anweisung »UPDATE ONLY "public"."stock_move" SET "location_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "location_id"«

2017-11-29 10:33:29,939 612 INFO testdb odoo.modules.loading: loading 1 modules...
2017-11-29 10:33:29,939 612 DEBUG testdb odoo.modules.loading: loading module base (1/1)
2017-11-29 10:33:30,062 612 INFO testdb odoo.modules.registry: module base: creating or upda
```

that results in a loop of updating modules.
Regards.

**Comment by Elkasitu** [comment]
@Karsten-77 Can I have a look at your conf file? Also are you using the packaged version of Odoo or from source code? Windows or Linux/MacOS?

**Comment by Karsten-77** [comment]
```
[options]
addons_path = /opt/workspace/odoo11/addons,/opt/workspace/ODOO11-ADDON-RESSOURCES/tom-addons,/opt/workspace/ODOO11-ADDON-RESSOURCES/connector/,/opt/workspace/ODOO11-ADDON-RESSOURCES/queue/,/opt/workspace/ODOO11-ADDON-RESSOURCES/community-addons/
admin_passwd = XXX
csv_internal_sep = ,
data_dir = /opt/workspace/odoo11/.local/
database = testdb
db_host = False
db_maxconn = 64
db_name = False
db_password = XXX
db_port = False
db_sslmode = prefer
db_template = template1
db_user = karsten
dbfilter = testdb
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
http_enable = True
http_interface = 127.0.0.1
http_port = 8069
import_partial = 
limit_memory_hard = 8589934592
limit_memory_soft = 4294967296
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 600
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = debug
logfile = False
logrotate = False
longpolling_port = 8069
max_cron_threads = 5
netrpc_interface = 127.0.0.1
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = False
proxy_mode = True
reportgz = False
server_wide_modules = web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 0


```


karsten@tomws01:/opt/workspace/odoo$ git rev-parse HEAD
6c996723b212b8ea85aa7b5d6e935d80e37b83a9

**Comment by Elkasitu** [comment]
Closed, unreproducible on runbot
