### ISSUE TITLE
[11.0]Uncaught Error: QWeb2: Template 'ActionManager' not found

### ISSUE THREAD

**Issue by judaa11** [odoo/odoo#21117]
Impacted versions: 11.0

Steps to reproduce:
Fresh installation both ubuntu 16.04 & windows (10)
Adding some custom modules
Make some updates/modules

Current behavior:
Qweb crash
Chrome console:
```
Violation] Forced reflow while executing JavaScript took 40ms
web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'ActionManager' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.renderElement (web.assets_common.js:3932)
    at web.assets_common.js:3932
    at web.assets_common.js:802
    at fire (web.assets_common.js:796)
    at Object.add [as done] (web.assets_common.js:797)
    at Array.<anonymous> (web.assets_common.js:802)
    at Function.each (web.assets_common.js:625)
exception @ web.assets_common.js:3689
_render @ web.assets_common.js:3734
render @ web.assets_common.js:3730
renderElement @ web.assets_common.js:3932
(anonymous) @ web.assets_common.js:3932
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
__widgetRenderAndInsert @ web.assets_common.js:3932
appendTo @ web.assets_common.js:3932
set_action_manager @ web.assets_backend.js:505
(anonymous) @ web.assets_backend.js:505
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
script.onload.script.onreadystatechange @ web.assets_common.js:3838
web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'CrashManager.error' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.show_error (web.assets_backend.js:578)
    at window.onerror (web.assets_backend.js:505)
```
Log File:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\0112\\AppData\\Local\\OpenERP S.A.\\Odoo\\filestore\\demo\\54/549f82ae56b7397db7fcd8ca1a179494b0cfda03'
2017-11-21 11:59:07,365 1532 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading C:\Users\0112\AppData\Local\OpenERP S.A.\Odoo\filestore\demo\fd/fd16bb9261211d4bd81b4a530213f0f7a4c13ac6
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x0333CDF8>, 1, False, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x043BC7B0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\0112\\AppData\\Local\\OpenERP S.A.\\Odoo\\filestore\\demo\\fd/fd16bb9261211d4bd81b4a530213f0f7a4c13ac6'
2017-11-21 11:59:07,366 1532 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading C:\Users\0112\AppData\Local\OpenERP S.A.\Odoo\filestore\demo\b8/b852566dfbab47cf169684f3e98f3ba097561fab
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x0333CDF8>, 1, False, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x043BC7B0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\0112\\AppData\\Local\\OpenERP S.A.\\Odoo\\filestore\\demo\\b8/b852566dfbab47cf169684f3e98f3ba097561fab'
```
Expected behavior:
module updated
Video/Screenshot link (optional):

The only solution is to delete the DB & clear filestore.

**Comment by mart-e** [comment]
Sorry but because of the

> Adding some custom modules
> Make some updates/modules

I have to reject this report.

To have a valid bug, you need to give us a way to reproduce the bug on a standard Odoo.
You can obviously do whatever you want in custom modules or customizations and eventually crash your instance, but this is not a bug.

**Comment by judaa11** [comment]
After some workaround, this error occur when there is some borken python/Java dependancies. But, I'm not really sure why those errors are been the reason of qweb crashes (instead of 500 INTERNAL SERVER ERROR + Log-Error).

P.S.: when this bug occur, even _/web?debug=assets_ will crash.

**Comment by chickahoona** [comment]
I just had the same problem, which was caused by addon folders, that I configured, but were not present. 

(I assume that this can also happen if addon folders are not readable for the user.)

Odoo does not load some ressources, and returns the standard 404 page, which causes most of the website to fall apart.

**Comment by bloublou2014** [comment]
Check file /etc/odoo/odoo.conf for your custom addons
Example:

```
[options]
addons_path = /xxxxx/user,/xxxx/enterprise
```

check if all directories listed on `addons_path` exists.

**Comment by lalaki0921** [comment]
I have the same problem after installing the module "Open HRMS Core". The Odoo (v11.0) was deployed via Bitnami on GCP.
