### ISSUE TITLE
odoo 8.0 crash after update crm module

### ISSUE THREAD

**Issue by Danultimate** [odoo/odoo#21265]
I have been using my odoo 8.0 on ubuntu 14.04 for a long time.

Today I tried to to update the crm module and I started to got this error

XmlHttpRequestError INTERNAL SERVER ERROR 500

On the terminal Im getting this:

    `ERROR formativa-restore openerp.addons.base.ir.ir_ui_view: El elemento '<search string="Leads Analysis">' no puede ser localizado en la vista padre
    
    Error de contexto:
    Vista `crm.lead.report.select`
    [view_id: 332, xml_id: crm.view_report_crm_lead_filter, model: crm.lead.report, parent_id: 325]
    formativa-restore openerp.service.server: Failed to initialize database .
    Traceback (most recent call last):
      File "/opt/odoo/openerp/service/server.py", line 929, in preload_registries
        registry = RegistryManager.new(dbname, update_module=update_module)
      File "/opt/odoo/openerp/modules/registry.py", line 370, in new
        openerp.modules.load_modules(registry._db, force_demo, status, update_module)
      File "/opt/odoo/openerp/modules/loading.py", line 351, in load_modules
        force, status, report, loaded_modules, update_module)
      File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
        loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
      File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
        _load_data(cr, module_name, idref, mode, kind='data')
      File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
        tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
      File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
        convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
      File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
        obj.parse(doc.getroot(), mode=mode)
      File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
        self._tags[rec.tag](self.cr, rec, n, mode=mode)
      File "/opt/odoo/openerp/tools/convert.py", line 763, in _tag_record
        id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
      File "/opt/odoo/openerp/api.py", line 241, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1050, in _update
        model_obj.write(cr, uid, [res_id], values, context=context)
      File "/opt/odoo/openerp/api.py", line 241, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 282, in write
        context)
      File "/opt/odoo/openerp/api.py", line 241, in wrapper
        return old_api(self, *args, **kwargs)
      File "/opt/odoo/openerp/api.py", line 363, in old_api
        result = method(recs, *args, **kwargs)
      File "/opt/odoo/openerp/models.py", line 3778, in write
        self._write(old_vals)
      File "/opt/odoo/openerp/api.py", line 239, in wrapper
        return new_api(self, *args, **kwargs)
      File "/opt/odoo/openerp/api.py", line 547, in new_api
        result = method(self._model, cr, uid, self.ids, *args, **kwargs)
      File "/opt/odoo/openerp/models.py", line 3949, in _write
        recs._validate_fields(vals)
      File "/opt/odoo/openerp/api.py", line 239, in wrapper
        return new_api(self, *args, **kwargs)
      File "/opt/odoo/openerp/models.py", line 1271, in _validate_fields
        raise ValidationError('\n'.join(errors))
    ParseError: "ValidateError
    Field(s) `arch` failed against a constraint: Invalid view definition
    
    Error details:
    El elemento '<search string="Leads Analysis">' no puede ser localizado en la vista padre
    
    Error de contexto:
    Vista `crm.lead.report.select`
    [view_id: 332, xml_id: crm.view_report_crm_lead_filter, model: crm.lead.report, parent_id: 325]" while parsing /opt/odoo/addons/crm/report/crm_lead_report_view.xml:63, near
    ``<record id="view_report_crm_lead_filter" model="ir.ui.view">
                <field name="name">crm.lead.report.select</field>
                <field name="model">crm.lead.report</field>
                <field name="arch" type="xml">
                    <search string="Leads Analysis">
                        <filter name="lead" string="Lead" domain="[('type','=', 'lead')]" help="Show only lead"/>
                        <filter name="opportunity" string="Opportunity" domain="[('type','=','opportunity')]" help="Show only opportunity"/>
                        <separator/>
                        <filter string="Won" name="won" domain="['&amp;', ('stage_id.probability', '=', 100), ('stage_id.on_change', '=', 1)]"/>
                        <filter string="Lost" name="lost" domain="['&amp;', ('stage_id.probability', '=', 0), ('stage_id.sequence', '!=', 1)]"/>
                        <field name="section_id" context="{'invisible_section': False}" groups="base.group_multi_salesteams"/>
                        <field name="user_id" string="Salesperson"/>
                        <group expand="0" string="Extended Filters">
                            <field name="partner_id" filter_domain="[('partner_id','child_of',self)]"/>
                            <field name="stage_id" domain="[('section_ids', '=', 'section_id')]"/>
                            <field name="campaign_id"/>
                            <field name="medium_id"/>
                            <field name="source_id"/>
                            <field name="company_id" groups="base.group_multi_company"/>
                            <separator orientation="vertical"/>
                            <field name="stage_id" widget="selection" domain="[('section_ids', '=', 'section_id')]"/>
                            <field name="campaign_id" widget="selection"/>
                            <field name="medium_id" widget="selection"/>
                            <field name="source_id" widget="selection"/>
                            <separator orientation="vertical"/>
                            <field name="company_id" widget="selection" groups="base.group_multi_company"/>
                            <newline/>
                            <field name="create_date"/>
                            <field name="opening_date"/>
                            <field name="date_closed"/>
                        </group>
                        <group expand="1" string="Group By">
                            <filter string="Salesperson" context="{'group_by':'user_id'}"/>
                            <filter string="Sales Team" context="{'group_by':'section_id'}" groups="base.group_multi_salesteams"/>
                            <filter string="Country" context="{'group_by':'country_id'}"/>
                            <filter string="Company" context="{'group_by':'company_id'}" groups="base.group_multi_company"/>
                            <filter string="Stage" context="{'group_by':'stage_id'}"/>
                            <separator orientation="vertical"/>
                            <filter string="Creation Month" context="{'group_by':'create_date:month'}" name="month"/>
                        </group>
                    </search>
                </field>
            </record>`

Im using postgresql 9.3 

Could I solve it updating the database or the views? how?

**Comment by Danultimate** [comment]
Solved
