### ISSUE TITLE
[BUG][10] Orm creates bad sql query for fields with capital letters in name

### ISSUE THREAD

**Issue by d3stozaur** [odoo/odoo#21348]
Impacted versions:
10.0
Steps to reproduce:
add field with capital letter to model for example x_Test type integer
then go to sale order tree view and add to that view our newly added field, then add some group by to the view and try to sort by our new field
Current behavior:
we get an error:
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/models.py", line 1928, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/models.py", line 2018, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/282732-10-0-ba73fd/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "x_test" does not exist
LINE 6:             ORDER BY x_Test ASC
                             ^
HINT:  Perhaps you meant to reference the column "sale_order.x_Test".

Expected behavior:
the view should sort by that column
in orm where the sql query is created order by should be in quatiation like ORDER BY "x_Test" ASC or be in qualifield name form like "sale_order"."x_Test"

Video/Screenshot link (optional):

**Comment by d3stozaur** [comment]
Hi i recorded how to reproduce it on runbot runbot.odoo.com 10.0 branch
http://webm.land/media/kU9m.webm

**Comment by Elkasitu** [comment]
@d3stozaur Thanks, very helpful, I'll take a look at it

**Comment by Elkasitu** [comment]
Fixed in rev. c338e24, you can cherry-pick it locally or wait for the forward-port
