### ISSUE TITLE
[ Odoo Failed ] Getting critical bug during database upgrade via -u all !!!

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#2140]
ERROR xxxxx openerp.addons.base.ir.ir_ui_view: Element '<xpath expr="//div[@name='div_type'][field[@name='use_parent_address']] | //field[@name='child_ids']//div[@name='div_type']">' cannot be located in parent view

Error context:
View `res.partner.view.address_type`
[view_id: 1030, xml_id: sale.res_partner_address_type, model: res.partner, parent_id: 126]
2014-09-02 14:11:18,660 2992 CRITICAL xxxxxxx openerp.service.server: Failed to initialize database `xxxxx`.
Traceback (most recent call last):
  File "/var/run/odoo/odoo/openerp/service/server.py", line 856, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/run/odoo/odoo/openerp/modules/registry.py", line 322, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/run/odoo/odoo/openerp/modules/loading.py", line 353, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/var/run/odoo/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/var/run/odoo/odoo/openerp/modules/loading.py", line 198, in load_module_graph
    registry['ir.ui.view']._validate_module_views(cr, SUPERUSER_ID, module_name)
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1191, in _validate_module_views
    if not self._check_xml(cr, uid, [vid]):
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 267, in _check_xml
    view_def = self.read_combined(cr, uid, view.id, None, context=context)
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 626, in read_combined
    cr, uid, arch_tree, root_id, base.model, context=context)
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 578, in apply_view_inheritance
    source = self.apply_inheritance_specs(cr, uid, source, specs_tree, view_id, context=context)
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 556, in apply_inheritance_specs
    self.raise_view_error(cr, uid, _("Element '%s' cannot be located in parent view") % tag, inherit_id, context=context)
  File "/var/run/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/run/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 441, in raise_view_error
    raise AttributeError(message)
AttributeError: Element '<xpath expr="//div[@name='div_type'][field[@name='use_parent_address']] | //field[@name='child_ids']//div[@name='div_type']">' cannot be located in parent view

Error context:
View `res.partner.view.address_type`
[view_id: 1030, xml_id: sale.res_partner_address_type, model: res.partner, parent_id: 126]

**Comment by Yenthe666** [comment]
Hi @tejastank,

I'm closing this issue since you've managed to solve this yourself. Good job!

Regards,
Yenthe
