### ISSUE TITLE
"RuntimeError: object unbound" when calling xmlrpc read() on product_product

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#21530]
### Impacted versions:
11.0

### Steps to reproduce:
* Install `website_sale_sotck`
* Make an XMLRPC connection with a remote Odoo Server (in my particular case i'm connecting with two different machines. It worked well testing with two DB's in the same server)
* Try to `read(id)` from product_product

### Current behavior:

It throws this error:

```
Traceback (most recent call last):
File "/home/odoo/instance/odoo/odoo/fields.py", line 944, in __get__
value = record.env.cache.get(record, self)
File "/home/odoo/instance/odoo/odoo/api.py", line 960, in get
value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f4fff606fd0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/instance/odoo/odoo/http.py", line 115, in dispatch_rpc
result = dispatch(method, params)
File "/home/odoo/instance/odoo/odoo/service/model.py", line 39, in dispatch
res = fn(db, uid, *params)
File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/home/odoo/instance/odoo/odoo/modules/registry.py", line 436, in manage_changes
yield self
File "/home/odoo/instance/odoo/odoo/service/model.py", line 39, in dispatch
res = fn(db, uid, *params)
File "/home/odoo/instance/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/instance/odoo/odoo/service/model.py", line 160, in execute
res = execute_cr(cr, uid, obj, method, *args, **kw)
File "/home/odoo/instance/odoo/odoo/service/model.py", line 149, in execute_cr
return odoo.api.call_kw(recs, method, args, kw)
File "/home/odoo/instance/odoo/odoo/api.py", line 689, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/home/odoo/instance/odoo/odoo/api.py", line 680, in call_kw_multi
result = method(recs, *args, **kwargs)
File "/home/odoo/instance/odoo/odoo/models.py", line 2520, in read
values[name] = field.convert_to_read(record[name], record, use_name_get)
File "/home/odoo/instance/odoo/odoo/models.py", line 4657, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/home/odoo/instance/odoo/odoo/fields.py", line 948, in __get__
self.determine_value(record)
File "/home/odoo/instance/odoo/odoo/fields.py", line 1059, in determine_value
self.compute_value(recs)
File "/home/odoo/instance/odoo/odoo/fields.py", line 1022, in compute_value
record.env.cache.set_failed(record, [self], exc)
File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/home/odoo/instance/odoo/odoo/api.py", line 812, in _do_in_mode
yield
File "/home/odoo/instance/odoo/odoo/fields.py", line 1022, in compute_value
record.env.cache.set_failed(record, [self], exc)
File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/home/odoo/instance/odoo/odoo/api.py", line 869, in protecting
yield
File "/home/odoo/instance/odoo/odoo/fields.py", line 1015, in compute_value
self._compute_value(records)
File "/home/odoo/instance/odoo/odoo/fields.py", line 1006, in _compute_value
getattr(records, self.compute)()
File "/home/odoo/instance/odoo/addons/website_sale_stock/models/product_product.py", line 14, in _compute_cart_qty
website = getattr(request, 'website', None)
File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 343, in __getattr__
return getattr(self._get_current_object(), name)
File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 302, in _get_current_object
return self.__local()
File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 135, in _lookup
raise RuntimeError('object unbound')
RuntimeError: object unbound
```

### Expected behavior:
Return the field values of the product.

I found two issues related to this case:

#14939
#21442

**Comment by ebirbe** [comment]
> ... (in my particular case i'm connecting with two different machines. It worked well testing with two DB's in the same server)

I tested again, and confirm this error also happens with both databases in the same server. I was testing with an outdated environment.

**Comment by JKE-be** [comment]
https://github.com/odoo/odoo/commit/b4863378efa6a30acc507fd05dc977195c3ff254 should fixed it.

FYI: https://github.com/odoo/odoo/issues/​​​​​​24183

**Comment by dduarte-odoogap** [comment]
Tested again with latest commit 11.0 from 22-05-2018 and get same error.
i can read 'product.template' but cannot do same for 'product.product'
