### ISSUE TITLE
Error while install Sales Management clean 11 CE 

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21584]
Impacted versions:
11.0 CE, fresh version, Linux Mint, Python 3.5
Steps to reproduce:
Clean base. Newly installed. Click install Sales Managment-module.
Current behavior:
`Traceback (most recent call last):
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_sequence.py", line 148, in create
    _create_sequence(self._cr, "ir_sequence_%03d" % seq.id, values.get('number_increment', 1), values.get('number_next', 1))
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_sequence.py", line 18, in _create_sequence
    cr.execute(sql, (number_increment, number_next))
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ОШИБКА:  отношение "ir_sequence_001" уже существует

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mintuser/dev/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/mintuser/dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/mintuser/dev/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/mintuser/dev/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mintuser/dev/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/mintuser/dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/mintuser/dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/mintuser/dev/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/mintuser/dev/odoo/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/mintuser/dev/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/mintuser/dev/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/mintuser/dev/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/mintuser/dev/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/mintuser/dev/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/mintuser/dev/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/mintuser/dev/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_sequence.py", line 148, in create
    _create_sequence(self._cr, "ir_sequence_%03d" % seq.id, values.get('number_increment', 1), values.get('number_next', 1))
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_sequence.py", line 18, in _create_sequence
    cr.execute(sql, (number_increment, number_next))
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "Error:   "ir_sequence_001" allready exists
" while parsing /home/mintuser/dev/odoo/addons/account/data/account_data.xml:48, near
<record id="sequence_reconcile_seq" model="ir.sequence">
            <field name="name">Account reconcile sequence</field>
            <field name="code">account.reconcile</field>
            <field name="prefix">A</field>
            <field eval="1" name="number_next"/>
            <field eval="1" name="number_increment"/>
            <field eval="False" name="company_id"/>
        </record>`

**Comment by Elkasitu** [comment]
Hi, can you tell me if you're using a packaged installation or if it's from source?

**Comment by sergeiruzkiicode** [comment]
I've cloned odoo/odoo repo. Branch 11.0
I think, it's about some depencencies, because module was installed through website installation.

**Comment by Elkasitu** [comment]
I can't seem to reproduce on the runbot, have you tried with another brand new database? It would seem that your current one is trying to create the table ir_sequence_001 but it already exists, you can try creating a brand new database

**Comment by sergeiruzkiicode** [comment]
DB was fully clean

**Comment by Elkasitu** [comment]
But does creating new databases create the same issue for you?

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

I've also tried this on a local VM with the latest Odoo 11 source code. Just like you I've did a clone of odoo/odoo, made a new database and directly installed the `sales_management` app. This installed without any problems.
I believe this issue has been handled in the meanwhile or is because of a misconfiguration of your own environment. If you can still reproduce it with the latest source code then please do post back here with more info.

Regards,
Yenthe
