### ISSUE TITLE
Error workflow wmf while creating a quote in V8

### ISSUE THREAD

**Issue by tarsoman** [odoo/odoo#2160]
Traceback (most recent call last): 
  File "/home/admin/odoo/openerp/http.py", line 476, in _handle_exception 
    return super(JsonRequest, self)._handle_exception(exception) 
  File "/home/admin/odoo/openerp/http.py", line 495, in dispatch 
    result = self._call_function(*_self.params) 
  File "/home/admin/odoo/openerp/http.py", line 311, in _call_function 
    return checked_call(self.db, *args, *_kwargs) 
  File "/home/admin/odoo/openerp/service/model.py", line 113, in wrapper 
    return f(dbname, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/http.py", line 308, in checked_call 
    return self.endpoint(_a, *_kw) 
  File "/home/admin/odoo/openerp/http.py", line 685, in __call__ 
    return self.method(_args, *_kw) 
  File "/home/admin/odoo/openerp/http.py", line 360, in response_wrap 
    response = f(_args, *_kw) 
  File "/home/admin/odoo/addons/web/controllers/main.py", line 941, in call_kw 
    return self._call_kw(model, method, args, kwargs) 
  File "/home/admin/odoo/addons/web/controllers/main.py", line 933, in _call_kw 
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/api.py", line 233, in wrapper 
    return old_api(self, _args, *_kwargs) 
  File "/home/admin/odoo/addons/sale/sale.py", line 360, in create 
    new_id = super(sale_order, self).create(cr, uid, vals, context=ctx) 
  File "/home/admin/odoo/openerp/api.py", line 233, in wrapper 
    return old_api(self, _args, *_kwargs) 
  File "/home/admin/odoo/addons/mail/mail_thread.py", line 378, in create 
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context) 
  File "/home/admin/odoo/openerp/api.py", line 233, in wrapper 
    return old_api(self, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/api.py", line 328, in old_api 
    result = method(recs, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/models.py", line 3920, in create 
    record = self.browse(self._create(old_vals)) 
  File "/home/admin/odoo/openerp/api.py", line 231, in wrapper 
    return new_api(self, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/api.py", line 460, in new_api 
    result = method(self._model, cr, uid, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/models.py", line 4130, in _create 
    self.create_workflow(cr, user, [id_new], context=context) 
  File "/home/admin/odoo/openerp/api.py", line 233, in wrapper 
    return old_api(self, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/models.py", line 3442, in create_workflow 
    workflow.trg_create(uid, self._name, res_id, cr) 
  File "/home/admin/odoo/openerp/workflow/__init__.py", line 73, in trg_create 
    return WorkflowService.new(cr, uid, res_type, res_id).create() 
  File "/home/admin/odoo/openerp/workflow/service.py", line 81, in create 
    WorkflowInstance.create(self.session, self.record, wkf_id) 
  File "/home/admin/odoo/openerp/workflow/instance.py", line 54, in create 
    WorkflowItem.create(session, record, activity, instance_id, stack) 
  File "/home/admin/odoo/openerp/workflow/workitem.py", line 95, in create 
    workflow_item.process(stack=stack) 
  File "/home/admin/odoo/openerp/workflow/workitem.py", line 120, in process 
    ok = self._split_test(activity['split_mode'], signal, stack) 
  File "/home/admin/odoo/openerp/workflow/workitem.py", line 222, in _split_test 
    cr.execute('select \* from wkf_transition where act_from=%s ORDER BY sequence,id', (self.workitem['act_id'],)) 
  File "/home/admin/odoo/openerp/sql_db.py", line 155, in wrapper 
    return f(self, _args, *_kwargs) 
  File "/home/admin/odoo/openerp/sql_db.py", line 230, in execute 
    res = self._obj.execute(query, params) 
ProgrammingError: column "sequence" does not exist 
LINE 1: ... \* from wkf_transition where act_from=10 ORDER BY sequence,i... 
                                                             ^

**Comment by Yenthe666** [comment]
Hi @tarsoman,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
