### ISSUE TITLE
Error in project_forecast while try to forecast with emploee without user

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21647]
Impacted versions:
11.0
Steps to reproduce:
Go to rubot
http://286209-11-0-57ae16.runbot8.odoo.com/web?#view_type=kanban&model=project.project&action=549&menu_id=381
click Forecast on Data Import/Export Plugin tab
Current behavior:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/addons/project_timesheet_forecast_sale/models/project.py", line 14, in view_monthly_forecast
    return super(Project, self.with_context(project_task_display_forecast=True)).view_monthly_forecast()
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/addons/project_forecast/models/project.py", line 42, in view_monthly_forecast
    context = dict(self.env.context, default_project_id=self.id, default_employee_id=self.user_id.employee_ids[0].id)
  File "/home/odoo/runbot/extra/runbot/static/build/286209-11-0-57ae16/odoo/models.py", line 4661, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range`

The problem goes out if you choose as project manager emploee without relation to user. 
There must be additional filter: employes with user_id only

**Comment by Yenthe666** [comment]
hi @sergeiruzkiicode,

Thanks for the report.
How did you create an employee without an user attached to it though? I either create a new user, a new contact (customer) or a new employee.
When you create a new user you obviously have a user, when you create a new employee (without attaching it to a user) it doesn't show up.
I must be missing something small. Can you add a few more details please? 😄

**Comment by Gorash** [comment]
I create a fix for your issue: https://github.com/odoo/enterprise/pull/1707

**Comment by Yenthe666** [comment]
Yep - tested and it is fixed with https://github.com/odoo/enterprise/commit/904a667e94184b97aea3d5668b1f6a0b284892ce
