### ISSUE TITLE
Projects. Float division by zero error

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21641]
Impacted versions:
11.0e
Steps to reproduce:
Go to Projects. Click ovewriew on project tab.
Current behavior:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/addons/sale_timesheet/controllers/main.py", line 16, in plan
    values = self._prepare_plan_values(domain)
  File "/opt/odoo/odoo-server/odoo/addons/project_timesheet_forecast_sale/controllers/project.py", line 31, in _prepare_plan_values
    values = super(TimesheetForecastController, self)._prepare_plan_values(domain)
  File "/opt/odoo/odoo-server/odoo/addons/sale_timesheet/controllers/main.py", line 59, in _prepare_plan_values
    dashboard_values['rates'][billable_type] = round(data.get('unit_amount') / dashboard_total_hours * 100, 2)
ZeroDivisionError: float division by zero`

I have 3 open projects. 
![image](https://user-images.githubusercontent.com/34267807/33984885-1222ebe6-e0ca-11e7-8c5c-90e05ba8d17b.png)
If I click on left and right - error. If i click on tab in center - no error, all zeros in overview.

I've checked, what we become in dashboard_total_hours: 
for projects with errors: 0.0 (float) because unit_amount is 0.0 in dashboard_data
for project without error: 0 (int) because dashboard_data list is empty, loop on line 53 doesn't start

So we need a ZeroDivisionError check in _prepare_plan_values function in odoo/addons/sale_timesheet/controllers/main.py ?

**Comment by xmo-odoo** [comment]
Or a special case for a `unit_amount` of 0, assuming that's a valid value.

@jem-odoo that seems to be your bailiwick.

**Comment by sergeiruzkiicode** [comment]
You can check it on runbot http://286209-11-0-57ae16.runbot8.odoo.com/web?#view_type=kanban&model=project.project&action=549&menu_id=381

Click "Overview" on Data Import/Export Plugin tab

**Comment by jem-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/f9ce42c763389573ed6a19bbb1a4a9784d82a1bb
Regards
