### ISSUE TITLE
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not Binary)

### ISSUE THREAD

**Issue by gswf-sha** [odoo/odoo#21682]
Impacted versions:
odoo10, odoo11
Steps to reproduce:
While using ERPpeek(XMLRPC protocol) to create new res.partner record with image(field image), TypeError occurs:
Code on client machine:
```
import erppeek
srv1, db1, admin1, passwd1 = 'XXX','XXX','XXX','XXX'
api11=erppeek.Client(srv1, db1, admin1, passwd1)
Partner = api11.model('res.partner')
Partner.create({
          'name': 'Tenth ERPpeek',
        'create_uid':8,
            'image':encoded_string # encoded_string is base64 encoded image bytes
        })
```
The above code works fine with Odoo8, but fails with Odoo10 and Odoo11, (not tested on Odoo9)

Current behavior:
The Error Msg on the Server side:

```
2017-12-16 13:08:04,626 24181 ERROR test11 odoo.http: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not Binary)
Traceback (most recent call last):
  File "/home/odoo11/miniconda/lib/python3.6/base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'Binary'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo11/miniconda/lib/python3.6/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/home/odoo11/miniconda/lib/python3.6/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/home/odoo11/miniconda/lib/python3.6/base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not Binary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 39, in dispatch
    res = fn(db, uid, *params)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 160, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 149, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/addons/base/res/res_partner.py", line 531, in create 
      tools.image_resize_images(vals)
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/image.py", line 274, in image_resize_images
    avoid_resize_big=True, avoid_resize_medium=False, avoid_resize_small=False))
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/image.py", line 261, in image_get_resized_images
    return_dict[big_name] = image_resize_image_big(base64_source, avoid_if_small=avoid_resize_big)
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/image.py", line 143, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/image.py", line 56, in image_resize_image
    image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not Binary)
Expected behavior:
```
Video/Screenshot link (optional):

Debug:
I did a little debug myself and find that because xmlrpc.client.binary is not bytes type, so codecs.decode can not decode it)
Add an if  check for the xmlrpc.client.Binary type in the image_get_resized_images function of  File "/home/odoo11/odoo-dev/odoo/odoo/tools/image.py" will fix the bug:
```py
from xmlrpc.client import Binary
if isinstance(base64_source, Binary):
    base64_source = base64_source.data
```

**Comment by Yenthe666** [comment]
@xmo-odoo can you check this one please?

**Comment by xmo-odoo** [comment]
@gswf-sha I think we've had some fixes wrt image resizing & P3, is this still an issue?

**Comment by keshrath** [comment]
This problem seems to still exist but at least for me the workaround of @gswf-sha worked.
Thank you! 

```
line 56, in image_resize_image
image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not Binary
```

**Comment by pedrobaeza** [comment]
@xmo-odoo it seems that this still happens

**Comment by xmo-odoo** [comment]
@keshrath do you have a repro case? aka what are you doing specifically when you hit that issue.

**Comment by keshrath** [comment]
I made a mini example script that uses the demo and tries to create a new partner.

```
from xmlrpc import client

BASE_64_IMAGE = b'iVBORw0KGgoAAAANSUhEUgAAAG4AAAB/CAMAAAA5Dwf3AAAAY1BMVEX////Pz8/8/Pzv7+/k5OT39/fFxcXAwMDZ2dne3t7W1tbq6uq8vLzKysqhoaHz8/OQkJCHh4ewsLBSUlKZmZlcXFxvb299fX10dHSoqKhoaGgRERFXV1dFRUU5OTk/Pz8nJyfdtBD2AAADUElEQVRogb1biXKbMBR84kZckgzGUNvN/39lcdrGxuYQOnZnkjEM8QbQvluUEhApNQmOLWmIIoZiY9Hjd5Zh2P7z/GX1jedTrAr/bEX18zFIYt9scRK8HKTB+pUuEKSzG2o8yy9t5sehV/kl4fsZn/JbWvo898WW86WzvuTwIoEZPp+wC6yuirfV6gYbGptp0Q02LUjhXA7J5oKIVl6rKaod65879UbZrrhceiMd0+FODnqGsXQkh7jUuiwonchB+2vceAf9l+LCOxxZcvZy2JfAK5ilN8oPPp89c7CN48YpafavWYNBImAhB6M/jY2DMzO3aSo/UytoJj9zG88N5Jcthl16YIeDs8LKIB2Vg20ufGyVma/mny84oCEHkeOR3Og9zzHBWsz9CTdRv678XAVVernRcp5jAp2npP/M97EfnGmGXY743LLt6td1qrbtjdwnolty8FHlWq/U+anhrd2DrxJJtfiGQscZ6BNL68/a56wjWFCXm3RpGZ9qdpUMLuPdMvouvM7tvr862hKDO5+zjmcwaBfkaSIIPj+5Jfg8/mZ6/MQULFxhA67mx8UpJzWZyexxvs7rKVqTrriUaLiULEhbRaEYvk/1goZWhrwXjNJMUF2PIZ8UmLYlRUJZGOy6Tcb8Ft2L3+zM+nyYbii4NB2pc9axGx+jW94Kpa6splt45yMb+bk2p+tD6quaukJSre7X0/TU+Nf4VQ2cZDlQWXZ5Kym+sIFOoaRW1cQs6EQadbylU9FTW57jfLLHklHYKRF31RhfstNEx6srl/GvsCeRjJG0oGvkJYtSqkNFacTP083SMFnJOhFnXoiLorYom35ikFI2isqIiX4wpzuKuK9HSL/sH5rjGeg2gp//PvLcp/rGM2RBtFGxHmFeW7Ot1O0B682xsQo4EsPGmdgoGpsjYDMgbH6HzV7BuTm28oCtq2CrRtiaGLbip9/c3m5a6wFbrQXXorGVdmwf4fhis/FG2B4QtsOF7d9hu5Pg3iu2s4ztm2OnAux915FaoIvamn7SjJ1XAU/jYGeNsJNU2Dkx7BQcdsYPO8GInc8ET59iZ2uxk8PYuWjs1Dd2ph07sY/djwDebYHdS4LdKYPdB4Td5eRbAq+Y5IDdofYHT4AbHMS4t48AAAAASUVORK5CYII='

info = client.ServerProxy('https://demo.odoo.com/start').start()
url, db, username, password = info['host'], info['database'], info['user'], info['password']

common  = client.ServerProxy('{}/xmlrpc/2/common'.format(url))
models = client.ServerProxy('{}/xmlrpc/2/object'.format(url))

uid = common.authenticate(db, username, password, {})

id = models.execute_kw(db, uid, password, 'res.partner', 'create', [{
    'name': "New Partner",
    'image': BASE_64_IMAGE,
}])
```

I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'Binary'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not Binary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/11.0/odoo/service/wsgi_server.py", line 124, in wsgi_xmlrpc
    result = odoo.http.dispatch_rpc(service, method, params)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 39, in dispatch
    res = fn(db, uid, *params)
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 153, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 160, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 149, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/home/odoo/src/odoo/11.0/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/res/res_partner.py", line 538, in create
    tools.image_resize_images(vals)
  File "/home/odoo/src/odoo/11.0/odoo/tools/image.py", line 274, in image_resize_images
    avoid_resize_big=True, avoid_resize_medium=False, avoid_resize_small=False))
  File "/home/odoo/src/odoo/11.0/odoo/tools/image.py", line 261, in image_get_resized_images
    return_dict[big_name] = image_resize_image_big(base64_source, avoid_if_small=avoid_resize_big)
  File "/home/odoo/src/odoo/11.0/odoo/tools/image.py", line 143, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/home/odoo/src/odoo/11.0/odoo/tools/image.py", line 56, in image_resize_image
    image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not Binary)
```

I hope this help :)

**Comment by xmo-odoo** [comment]
@keshrath pass in the base64 data as str, not bytes (~Binary).

**Comment by keshrath** [comment]
@xmo-odoo Great, that worked! :)

```
from xmlrpc import client

BASE_64_IMAGE = b'iVBORw0KGgoAAAANSUhEUgAAAG4AAAB/CAMAAAA5Dwf3AAAAY1BMVEX////Pz8/8/Pzv7+/k5OT39/fFxcXAwMDZ2dne3t7W1tbq6uq8vLzKysqhoaHz8/OQkJCHh4ewsLBSUlKZmZlcXFxvb299fX10dHSoqKhoaGgRERFXV1dFRUU5OTk/Pz8nJyfdtBD2AAADUElEQVRogb1biXKbMBR84kZckgzGUNvN/39lcdrGxuYQOnZnkjEM8QbQvluUEhApNQmOLWmIIoZiY9Hjd5Zh2P7z/GX1jedTrAr/bEX18zFIYt9scRK8HKTB+pUuEKSzG2o8yy9t5sehV/kl4fsZn/JbWvo898WW86WzvuTwIoEZPp+wC6yuirfV6gYbGptp0Q02LUjhXA7J5oKIVl6rKaod65879UbZrrhceiMd0+FODnqGsXQkh7jUuiwonchB+2vceAf9l+LCOxxZcvZy2JfAK5ilN8oPPp89c7CN48YpafavWYNBImAhB6M/jY2DMzO3aSo/UytoJj9zG88N5Jcthl16YIeDs8LKIB2Vg20ufGyVma/mny84oCEHkeOR3Og9zzHBWsz9CTdRv678XAVVernRcp5jAp2npP/M97EfnGmGXY743LLt6td1qrbtjdwnolty8FHlWq/U+anhrd2DrxJJtfiGQscZ6BNL68/a56wjWFCXm3RpGZ9qdpUMLuPdMvouvM7tvr862hKDO5+zjmcwaBfkaSIIPj+5Jfg8/mZ6/MQULFxhA67mx8UpJzWZyexxvs7rKVqTrriUaLiULEhbRaEYvk/1goZWhrwXjNJMUF2PIZ8UmLYlRUJZGOy6Tcb8Ft2L3+zM+nyYbii4NB2pc9axGx+jW94Kpa6splt45yMb+bk2p+tD6quaukJSre7X0/TU+Nf4VQ2cZDlQWXZ5Kym+sIFOoaRW1cQs6EQadbylU9FTW57jfLLHklHYKRF31RhfstNEx6srl/GvsCeRjJG0oGvkJYtSqkNFacTP083SMFnJOhFnXoiLorYom35ikFI2isqIiX4wpzuKuK9HSL/sH5rjGeg2gp//PvLcp/rGM2RBtFGxHmFeW7Ot1O0B682xsQo4EsPGmdgoGpsjYDMgbH6HzV7BuTm28oCtq2CrRtiaGLbip9/c3m5a6wFbrQXXorGVdmwf4fhis/FG2B4QtsOF7d9hu5Pg3iu2s4ztm2OnAux915FaoIvamn7SjJ1XAU/jYGeNsJNU2Dkx7BQcdsYPO8GInc8ET59iZ2uxk8PYuWjs1Dd2ph07sY/djwDebYHdS4LdKYPdB4Td5eRbAq+Y5IDdofYHT4AbHMS4t48AAAAASUVORK5CYII='

info = client.ServerProxy('https://demo.odoo.com/start').start()
url, db, username, password = info['host'], info['database'], info['user'], info['password']

common  = client.ServerProxy('{}/xmlrpc/2/common'.format(url))
models = client.ServerProxy('{}/xmlrpc/2/object'.format(url))

uid = common.authenticate(db, username, password, {})

id = models.execute_kw(db, uid, password, 'res.partner', 'create', [{
    'name': "New Partner",
    'image': BASE_64_IMAGE.decode(),
}])
```

**Comment by Yenthe666** [comment]
@gswf-sha do you still face this issue? @pedrobaeza it looks like you where able to reproduce it too?

**Comment by pedrobaeza** [comment]
No, I wasn't able to reproduce it.
