### ISSUE TITLE
Uncaught Exception on '/jsonrpc' url path

### ISSUE THREAD

**Issue by barsi** [odoo/odoo#2170]
direct HTTP request to /jsonrpc produce uncaught exception.

***Impacted versions:***

- 8.0
- master

***Steps to reproduce:***

1. point your browser to localhost:8069/jsonrpc
 

***Current behavior:***

browser response:  **500 Internal Server Errror**

traceback log:

```
127.0.0.1 - - [03/Sep/2014 15:41:39] "GET /jsonrpc HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 1219, in __call__
    return self.dispatch(environ, start_response)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 1193, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 1360, in dispatch
    result = ir_http._dispatch()
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/addons/base/ir/ir_http.py", line 136, in _dispatch
    return self._handle_exception(e)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/addons/base/ir/ir_http.py", line 105, in _handle_exception
    return request._handle_exception(exception)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 593, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/addons/base/ir/ir_http.py", line 132, in _dispatch
    result = request.dispatch()
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 605, in dispatch
    r = self._call_function(**self.params)
  File "/home/mbarsi/Desktop/PROJECTS/OPENERP/V8/odoo/openerp/http.py", line 262, in _call_function
    % (self.endpoint.original, self.httprequest.path, self.endpoint.routing['type'], self._request_type))
Exception: <function jsonrpc at 0x7f6720f7cc80>, /jsonrpc: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

```

***Expected behavior:***

browser response: **400 Bad Request**

and a clean log with just one line:

```127.0.0.1 - - [03/Sep/2014 15:46:24] "GET /jsonrpc HTTP/1.1" 400 -```

Regards.

**Comment by bistaray** [comment]
I'm suggesting this is resolved.

Doing this at version 9.0 today does not give the exception, and does show the clean log:

2015-10-27 17:19:56,345 17820 INFO [Database Name] werkzeug: [IP ADDRESS] - - [27/Oct/2015 17:19:56] "GET /jsonrpc HTTP/1.1" 400 -
