### ISSUE TITLE
auth_oauth does not work with Azure AD

### ISSUE THREAD

**Issue by jheidecker** [odoo/odoo#21718]
Impacted versions: 11

Steps to reproduce: 

The OAUTH2 module _should_ work with AzureAD's generic OAUTH2 services with the following settings:

  **Provider name:** AzureAD
  **Client ID:** Client ID provided when registering Application
  **Body:** Login with Microsoft
  **Authentication URL:** https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  **Scope:** User.Read User.ReadBasic.All
  **Validation URL:** https://graph.microsoft.com/v1.0/me

Current behavior:

An exception is raised during login and the user is redirected to the access denied page because the "Authorization: Bearer access_token" is not being passed to the validation url. "Bearer access token is empty."

Expected behavior:

res_users model should send this header on the condition that the azure graph api is being used for validation. For example:

```
    @api.model
    def _auth_oauth_rpc(self, endpoint, access_token):
        return requests.get(endpoint, headers={'Authorization': 'Bearer {}'.format(access_token)}).json()
```

I tested this on v11 and it works fine, however my company would really like to see this working for odoo online before we purchase it.

**Comment by jheidecker** [comment]
Some more info if your interested in testing. The reason this works is because https://graph.microsoft.com/v1.0/me returns id in the json, just like facebook, so you can set the odoo users OAuth ID to that (it is a uuid) and it works fine when auth_oauth looks it up against the users.

**Comment by Yenthe666** [comment]
@tivisse could you have a look please?

**Comment by HYROPES** [comment]
@jheidecker Your question and detailed explanation helped me a lot. I have the same error code in V11.

```
Traceback (most recent call last):
File "/home/odoo/src/odoo/addons/auth_oauth/controllers/main.py", line 142, in signin
credentials = env['res.users'].sudo().auth_oauth(provider, kw)
File "/home/odoo/src/odoo/addons/auth_oauth/models/res_users.py", line 96, in auth_oauth
validation = self._auth_oauth_validate(provider, access_token)
File "/home/odoo/src/odoo/addons/auth_oauth/models/res_users.py", line 36, in _auth_oauth_validate
raise Exception(validation['error'])
Exception: {'message': 'Access token is empty.', 'innerError': {'request-id': '<APP ID >', 'date': '<Date>'}, 'code': 'InvalidAuthenticationToken'}
```
The configuration in Azure APP:
```
Required permissions - Windows Azure Active Directory - Grant permissions - Sign in and read user profile, Sign in and read user profile , Access the directory as the signed-in user
Required permissions - Microsoft Graph - Grant permissions - Access the directory as the signed-in user, Sign users in , View users' email address
Edit manifest - "oauth2AllowImplicitFlow": true,
```
The Odoo OAuth setting:
```
Provider name | Microsoft graph
Body | Login with Azure
Authentication URL | https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Scope | User.Read User.ReadBasic.All User.ReadWrite.All Contacts.ReadWrite Calendars.ReadWrite
Validation URL | https://graph.microsoft.com/v1.0/me
Data URL | graph.microsoft.com
```
The above settings will recreate the issue, hopefully someone can continue work on this OAuth connector for Azure/ Microsoft / Office 365.

BTW: you can try odoo.sh which run custom module code with all odoo online function.

**Comment by HYROPES** [comment]
Update: for anyone who interested in using Microsoft Graph OAuth to login user as B2B, using the following steps.

Install the module from @gdgellatly 
https://github.com/odoonz/odoonz-addons/tree/11.0/auth_oauth_microsoft_graph
Get the user Object ID from Azure AD
setup user profile in odoo, 
```
profile - oauth - Oauth provider - Microsoft graph
profile - oauth - Oauth user ID - user Object ID from Azure AD
```
setup Odoo OAuth setting
Note: you shall configure the endpoints (Authentication URL in below) to suite your needs:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints
```
Provider name | Microsoft graph
Body | Login with Azure
Authentication URL | https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Scope | User.Read User.ReadBasic.All User.ReadWrite.All Contacts.ReadWrite Calendars.ReadWrite
Validation URL | https://graph.microsoft.com/v1.0/me
Data URL | <Empty>
```
The configuration in Azure APP:
```
Enable multi-tenanted in Azure App - setting - properties
Required permissions - Windows Azure Active Directory - Grant permissions - Sign in and read user profile, Sign in and read user profile , Access the directory as the signed-in user
Required permissions - Microsoft Graph - Grant permissions - Access the directory as the signed-in user, Sign users in , View users' email address
Edit manifest - "oauth2AllowImplicitFlow": true,
```
If you like to enable user to signup, just turn on the B2C login in odoo - setting - Users - Customer Account

Then the question is, is this Azure / Microsoft / office 365 login with graph OAuth be part of standard odoo function? Or we will need to install the module for fixing the issue?
Other related issues:https://github.com/odoo/odoo/issues/25835

**Comment by C3POdoo** [comment]
Dear @jheidecker,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1835535 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.
