### ISSUE TITLE
Account Module

### ISSUE THREAD

**Issue by echeverrifm** [odoo/odoo#2171]
Hello

When a try to install website_sale module, i have this traceback

2014-09-03 16:43:33,479 8607 ERROR ecommerce_8 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 495, in dispatch
    result = self._call_function(*_self.params)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 308, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 685, in __call__
    return self.method(_args, *_kw)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/http.py", line 360, in response_wrap
    response = f(_args, *_kw)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/addons/odoo/v8/web/controllers/main.py", line 1015, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/addons/odoo/v8/web/controllers/main.py", line 1003, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/registry.py", line 322, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/tools/convert.py", line 993, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/tools/convert.py", line 1083, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/tools/convert.py", line 945, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/tools/convert.py", line 775, in _tag_record
    model = self.pool[rec_model]
  File "/home/echeverrifm/Documents/proyectos/software/openerp/source/odoo/odoo/openerp/modules/registry.py", line 100, in __getitem__
    return self.models[model_name]
ParseError: "web.tip" while parsing /home/echeverrifm/Documents/proyectos/software/openerp/source/addons/odoo/v8/account/account_tip_data.xml:4, near
<record model="web.tip" id="account_tip_1">
            <field name="title">&lt;b&gt;Reconciliation on bank statement&lt;/b&gt;</field>
            <field name="description">Click here to automatically reconcile your bank statements with the related entries. Do it later by clicking on "Reconcile Bank Statement" under periodical processing menu.</field>
            <field name="action_id" ref="account.action_bank_statement_tree"/>
            <field name="model">account.bank.statement</field>
            <field name="type">form</field>
            <field name="mode">form</field>
            <field name="trigger_selector">header button span:contains("Reconcile"):visible</field>
            <field name="highlight_selector">header button:nth-child(1)</field>
            <field name="placement">bottom</field>
        </record>

Regards

**Comment by Yenthe666** [comment]
Hi @echeverrifm,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
