### ISSUE TITLE
[11.0] Can't create a POS when using Spanish es_DO

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#21733]
### Impacted versions:
11.0

### Steps to reproduce:
Use Spanish (DO)
Create an additional Point of Sale (Main is created by Odoo)

### Current behavior:
```python
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_config.py", line 335, in create
    'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting
```
### Expected behavior:
Create the POS without errors

**Comment by gustavovalverde** [comment]
This might be in your realm @mart-e

**Comment by mart-e** [comment]
Thanks, leftover of old translations from previous versions

**Comment by marti1125** [comment]
I have the same error if you use the docker version (spanish) https://store.docker.com/images/odoo
