### ISSUE TITLE
odoo.addons.website.models.ir_http: 403 Forbidden:

### ISSUE THREAD

**Issue by wangsamas** [odoo/odoo#21783]
Impacted versions: 
11

Steps to reproduce:
don't know

Current behavior:
WARNING wangsamas odoo.addons.website.models.ir_http: 403 Forbidden:

Traceback (most recent call last):
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fd383e19eb8>

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/http_routing/models/ir_http.py", line 425, in _postprocess_args
    _, path = rule.build(arguments)
  File "/opt/odoo11/python/lib/python3.6/site-packages/Werkzeug-0.11.11-py3.6.egg/werkzeug/routing.py", line 798, in build
    add(self._converters[data].to_url(values[data]))
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/http_routing/models/ir_http.py", line 187, in to_url
    return slug(value)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/http_routing/models/ir_http.py", line 88, in slug
    identifier, name = value.id, value.display_name
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 951, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 993, in getter
    raise exception
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 1020, in compute_value
    self._compute_value(record)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 1006, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 1420, in _compute_display_name
    names = dict(self.name_get())
File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/product/models/product_template.py", line 330, in name_get
    for template in self]
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/product/models/product_template.py", line 330, in <listcomp>
    for template in self]
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 2571, in _prefetch_field
    result = self.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 2523, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 4660, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/addons/product/models/product_template.py", line 330, in <listcomp>
    for template in self]
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 2571, in _prefetch_field
    result = self.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 2523, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/models.py", line 4660, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo11/apps/odoo/lib/odoo-11.0.post20171019-py3.6.egg/odoo/api.py", line 993, in getter
    raise exception
odoo.exceptions.AccessError: ('Kegiatan yang diminta tidak bisa diselesaikan karena batasan keamanan. Hubungi administrator sistem Anda.\n\n(Tipe dokumen: product.template, kegiatan: read)', None)

what is this error means & what should I do to fix this?
thx

**Comment by Yenthe666** [comment]
Hi @wangsamas,

Thank you for your report but this really doesn't look like a bug (from Odoo itself)
The `AccessError` means that your user doesn't have suffecient access rights on the model `product.template`. Please give the user more rights 😉 

P.S: If you've made custom development - which I believe you did - you should also make sure that all the code you've added has enough rights too.

Regards,
Yenthe

**Comment by wangsamas** [comment]
Hi yenthe,

Tx alot for your kind reply. I have some questions that i still don't understand.

1. Please teach me which group should i give the read product.template right?
I've tried to give right for administrator group but it keep on generate the error.
I thought i should give group_user the right, but i couldn't find it. I only found group_public, group_portal & employee. Administrator didn't inherit from one of those.

2. I agree that this should be about access right. But sometimes it's not just product.template, sometimes it's about http_py, and sometimes about other things that i don't understand.
The obvious strange thing is about a theme module called web_responsive that suppose have nothing to do with access right, but i always get ACL uid 4 warning if that module installed. Sometimes i get warning for uid 2 too.
What is uid 2, uid 4 means? 
Are there any other uids? 
How can i know what they means?

3. What operating system is the best for odoo?
I'm using debian 9 in google cloud, so it's no problem for me to switch os. I tried to follow odoo installation guide but never success. Some of the command doesn't work as pip3, npm, etc. (I'm so dumb)
That's why i use bitnami stack, but the installation is not that smooth also, i think some of the python dependencies are not up to date, or not compatible for odoo.
I also think that this error might be because something wrong with bitnami stack, because i tried to run fresh installation without any 3rd party module, but i still get some errors.
So please suggest me what os should i use and how to install odoo complete and properly?

**Comment by wangsamas** [comment]
Btw, scaffold command doesn't works too...

**Comment by Yenthe666** [comment]
Hi @wangsamas,

It looks like you're facing multiple issues. Most likely a custom module (or downloaded module) is interfering with the default behaviour of Odoo.
The only way to figure out this is to deinstall apps and keep testing untill you found the issue or the responsible module.

> Please teach me which group should i give the read product.template right?

Not an out of the box answer - by default products should always be accessible in the backend so this falls back to some custom development / other module most likely.

> What is uid 2, uid 4 means?
Are there any other uids?
How can i know what they means?

The UID is the database ID of the user. 4 can represent the demo user for example while 1 is for the administrator.

> What operating system is the best for odoo?
Absolutely Ubuntu. Ubuntu is used by most of the people and is  very stable.
As for installation: have a look at the documentation at https://www.odoo.com/documentation/11.0/setup/install.html or you can alternatively use my (unofficial) installation script that does a lot for you. You can find my script at https://github.com/Yenthe666/InstallScript

**Comment by wangsamas** [comment]
I've tried to install without any 3rd party module and i don't use any demo samples?

I'll try ubuntu

**Comment by Yenthe666** [comment]
Probably your best bet. I know bitnami has some issues and is usually behind quite a lot on updates/fixes..

**Comment by wangsamas** [comment]
Tx alot.
I'll try your installscript & do it on ubuntu.

**Comment by wangsamas** [comment]
Hi Yenthe666, 
when I install I get this

The directory '/home/wangsamax/.cache/pip/http' or its parent directory is not owned by the current user and the ca
che has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you ma
y want sudo's -H flag.
The directory '/home/wangsamax/.cache/pip' or its parent directory is not owned by the current user and caching whe
els has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want 
sudo's -H flag.

is this okay or I should do something?

**Comment by wangsamas** [comment]
I try to follow the installation script and then I go to browser and this is what I get

This site can’t be reached

what should I do?

**Comment by Yenthe666** [comment]
@wangsamas I believe you've ran the script without `sudo`? Please do run it with `sudo`

**Comment by wangsamas** [comment]
I ran it exactly as in the instruction (copy paste)
I'm sure I do it with sudo.
The third time I try, I use sudo su before ran the script and the warning is gone

**Comment by wangsamas** [comment]
but i still unable to make it on air.
I try sudo service odoo-server restart but nothing happen

**Comment by wangsamas** [comment]
Hi Yenthe, your installscript is great. it do its job.
But I really frustrate with odoo... 
I'm using google cloud and I couldn't even make it online. 
so I don't know the odoo installation is working or not.
I've read the tutorial in https://www.odoo.com/documentation/11.0/setup/deploy.html and I don't understand. I've try to follow it but still can't make it online. 
Are there any easy step by step tutorial for idiots like me ?
