### ISSUE TITLE
Invoicing and charts accounts

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21791]
Impacted versions:
11.0 CE
Steps to reproduce:
You must install Chart Template where you have codes like 001, 01, 010000, 001000. You can see such chart example in odoo catalogue l10n_by

If you try to choose this account chart plan in Invoicing-->Settings-->Fiscal Localization, you will become this while save:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/mintuser/dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/mintuser/dev/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mintuser/dev/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/mintuser/dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/mintuser/dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/addons/base/res/res_config.py", line 544, in execute
    self.set_values()
  File "/home/mintuser/dev/odoo/addons/account/models/res_config_settings.py", line 100, in set_values
    wizard.execute()
  File "/home/mintuser/dev/odoo/addons/account/models/chart_template.py", line 909, in execute
    acc_template_ref, taxes_ref = self.chart_template_id._install_template(company, code_digits=self.code_digits, transfer_account_id=self.transfer_account_id)
  File "/home/mintuser/dev/odoo/addons/account/models/chart_template.py", line 293, in _install_template
    tmp1, tmp2 = self._load_template(company, code_digits=code_digits, transfer_account_id=transfer_account_id, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/mintuser/dev/odoo/addons/account/models/chart_template.py", line 329, in _load_template
    account_template_ref = self.generate_account(taxes_ref, account_ref, code_digits, company)
  File "/home/mintuser/dev/odoo/addons/account/models/chart_template.py", line 408, in generate_account
    new_account = self.create_record_with_xmlid(company, account_template, 'account.account', vals)
  File "/home/mintuser/dev/odoo/addons/account/models/chart_template.py", line 365, in create_record_with_xmlid
    return ir_model_data._update(model, template_xmlid.module, vals, xml_id=new_xml_id, store=True, noupdate=True, mode='init', res_id=False)
  File "/home/mintuser/dev/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/mintuser/dev/odoo/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/home/mintuser/dev/odoo/odoo/models.py", line 3371, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "account_account_code_company_uniq"
DETAIL:  Ключ "(code, company_id)=(010000, 1)" уже существует.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mintuser/dev/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/mintuser/dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/mintuser/dev/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/mintuser/dev/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/mintuser/dev/odoo/odoo/service/model.py", line 141, in wrapper
    raise ValidationError(inst[0])
TypeError: 'IntegrityError' object does not support indexing`

Codes are chars in account_account_template, but when unique() works, it seems that chars are going to integers, so "001" and "01", "010" and "0010" are the same for db. 

How can we avoid this?

PS If I have active company and import the same csv file in "Accounting Management" - it works

**Comment by smetl** [comment]
Hello,

To avoid this problem, you should set a code digits = 0 on the chart template.
It doesn't work in your case because, suppose a code digits = 6, Odoo will add some '0' as suffix to reach a minimum code size of 6 and then, 01 and 010 will both become 010000 (and then raise an error).

Regards,

**Comment by gustavovalverde** [comment]
@smetl why can't the error be raised? I got here (this issue) because I got the same `"TypeError: 'IntegrityError' object does not support indexing"` implementing trying to violate a constraint; but this is supposed to raise an legible error to the user; instead of crashing.
