### ISSUE TITLE
[11.0] Field `uom_id` does not exist

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#21823]
Error occurs when installing the point_of_sale
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 983, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 838, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 838, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 798, in postprocess
    xarch, xfields = self.with_context(base_model_name=model).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 1011, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Field `uom_id` does not exist

Error context:
View `Return lines`
[view_id: 554, xml_id: n/a, model: stock.return.picking, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `uom_id` does not exist\n\nError context:\nView `Return lines`\n[view_id: 554, xml_id: n/a, model: stock.return.picking, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/odoo_11/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/odoo_11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/odoo_11/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/odoo_11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/local/odoo_11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/odoo_11/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/odoo_11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    """
  File "/usr/local/odoo_11/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    self._cr.commit()
  File "/usr/local/odoo_11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/odoo_11/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/local/odoo_11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/local/odoo_11/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/local/odoo_11/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/local/odoo_11/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/local/odoo_11/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/local/odoo_11/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/usr/local/odoo_11/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/local/odoo_11/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `uom_id` does not exist

Error context:
View `Return lines`
[view_id: 554, xml_id: n/a, model: stock.return.picking, parent_id: n/a]
None" while parsing /usr/local/odoo_11/addons/stock/wizard/stock_picking_return_views.xml:7, near
<record id="view_stock_return_picking_form" model="ir.ui.view">
        <field name="name">Return lines</field>
        <field name="model">stock.return.picking</field>
        <field name="arch" type="xml">
            <form>
                <field name="move_dest_exists" invisible="1"/>
                <group attrs="{'invisible': [('move_dest_exists', '=', False)]}">
                    <div class="oe_grey">
                        <p>This picking appears to be chained with another operation. Later, if you receive the goods you are returning now, make sure to <b>reverse</b> the returned picking in order to avoid logistic rules to be applied again (which would create duplicated operations)</p>
                    </div>
                </group>
                <group>
                    <field name="product_return_moves" nolabel="1">
                        <tree editable="top" create="0">
                            <field name="product_id" options="{'no_create': True, 'no_open': True}" force_save="1"/>
                            <field name="quantity"/>
                            <field name="uom_id" readonly="1" groups="product.group_uom"/>
                        </tree>
                    </field>
                </group>
                <group>
                    <field name="parent_location_id" invisible="1"/>
                    <field name="original_location_id" invisible="1"/>
                    <field name="location_id" options="{'no_create': True, 'no_open': True}" groups="stock.group_stock_multi_locations"/>
                </group>
                <footer>
                    <button name="create_returns" string="Return" type="object" class="btn-primary"/>
                    <button string="Cancel" class="btn-default" special="cancel"/>
                </footer>
            </form>
        </field>
    </record>
```

**Comment by Yenthe666** [comment]
Hi @satriani-vai,

Thanks for the report.
Can you please update your source code to the latest version? I've just tried this on the latest 11.0 and it works fine out of the box both on a runbot and on a local instance.
Could you add more information if you can still reproduce it?

Regards,
Yenthe

**Comment by satriani-vai** [comment]
All-clear...
I deleted some modules that I last extracted to the addons folder and everything works fine again.
I apologize for the hasty warning.
