### ISSUE TITLE
error when installing module

### ISSUE THREAD

**Issue by newander13** [odoo/odoo#21942]
I have a problem with odoo 11.0 in Xubuntu.

The next error when installing any module

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/newander13/odoo-11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/newander13/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/newander13/odoo-11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/newander13/odoo-11.0/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/newander13/odoo-11.0/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/newander13/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/newander13/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/newander13/odoo-11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "/home/newander13/odoo-11.0/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/newander13/odoo-11.0/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "/home/newander13/odoo-11.0/addons/modulo_ander/models/__init__.py", line 3, in <module>
    from . import models
  File "/home/newander13/odoo-11.0/addons/modulo_ander/models/models.py", line 5
    class modulo_ander(models.Model):
    ^
IndentationError: unexpected indent

**Comment by gdgellatly** [comment]
Its a python error in a custom module.  Nothing to do with Odoo really.
Fix the error at line 5 of your own module.

**Comment by newander13** [comment]
I corrected it and now the following error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/newander13/odoo-11.0/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 957, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Modelo no encontrado: modulo_ander.modulo_ander

Contexto del error:
Vista `modulo_ander list`
[view_id: 841, xml_id: n/a, model: modulo_ander.modulo_ander, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/newander13/odoo-11.0/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/newander13/odoo-11.0/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nModelo no encontrado: modulo_ander.modulo_ander\n\nContexto del error:\nVista `modulo_ander list`\n[view_id: 841, xml_id: n/a, model: modulo_ander.modulo_ander, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/newander13/odoo-11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/newander13/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/newander13/odoo-11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/newander13/odoo-11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/newander13/odoo-11.0/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/newander13/odoo-11.0/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/newander13/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/newander13/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/newander13/odoo-11.0/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/newander13/odoo-11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/newander13/odoo-11.0/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/newander13/odoo-11.0/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/newander13/odoo-11.0/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/newander13/odoo-11.0/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/home/newander13/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/newander13/odoo-11.0/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/home/newander13/odoo-11.0/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

Modelo no encontrado: modulo_ander.modulo_ander

Contexto del error:
Vista `modulo_ander list`
[view_id: 841, xml_id: n/a, model: modulo_ander.modulo_ander, parent_id: n/a]
None" while parsing /home/newander13/odoo-11.0/addons/modulo_ander/views/views.xml:5, near
<record model="ir.ui.view" id="modulo_ander.list">
      <field name="name">modulo_ander list</field>
      <field name="model">modulo_ander.modulo_ander</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="value"/>
          <field name="value2"/>
        </tree>
      </field>
    </record>

**Comment by gdgellatly** [comment]
Again its an error in your code, not in Odoo.  You would be better off
following a basic tutorial/ asking questions on the forums/ googling the
errors.  These are all simple problems in the learning curve, but github
issues is for bugs not support.
