### ISSUE TITLE
[11.0] db connection error when trying to get interactive shell

### ISSUE THREAD

**Issue by nehemiascr** [odoo/odoo#22066]
I am trying to get into an interactive shell with odoo 11 but when using the **-d** option it gives me an error, I can get into the interactive shell without **-d** option but then I have no environment object, when trying to connect to the database from this environment-less shell I get the same db connection error, I am trying this using the official _odoo 11 docker image_ and also tried with _bitnami odoo 11 image_, same error with both.
Impacted versions: 11

Steps to reproduce:
```bash
odoo@21ad17f724ce:/$ odoo shell -d universidad
```
Current behavior:
```bash
odoo@21ad17f724ce:/$ odoo shell -d universidad
2018-01-07 18:53:39,951 134 INFO ? odoo: Odoo version 11.0-20171030
2018-01-07 18:53:39,952 134 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-01-07 18:53:39,952 134 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-01-07 18:53:39,953 134 INFO ? odoo: database: default@default:default
2018-01-07 18:53:39,963 134 INFO ? odoo.service.server: Initiating shutdown
2018-01-07 18:53:39,963 134 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-01-07 18:53:39,964 134 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'universidad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/shell.py", line 124, in run
    self.shell(config['db_name'])
  File "/usr/lib/python3/dist-packages/odoo/cli/shell.py", line 110, in shell
    registry = odoo.registry(dbname)
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 73, in new
    registry.init(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 141, in init
    with closing(self.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 472, in cursor
    return self._db.cursor()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 634, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 178, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 517, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 585, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
Also tried:
```bash
odoo@21ad17f724ce:/$ odoo shell
2018-01-07 19:18:09,991 186 INFO ? odoo: Odoo version 11.0-20171030
2018-01-07 19:18:09,991 186 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-01-07 19:18:09,991 186 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-01-07 19:18:09,992 186 INFO ? odoo: database: default@default:default
2018-01-07 19:18:10,002 186 INFO ? odoo.service.server: Initiating shutdown
2018-01-07 19:18:10,003 186 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
No environment set, use `/usr/bin/odoo shell -d dbname` to get one.
odoo: <module 'odoo' from '/usr/lib/python3/dist-packages/odoo/__init__.py'>
openerp: <module 'odoo' from '/usr/lib/python3/dist-packages/odoo/__init__.py'>
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
(Console)
>>> dir()
['__builtins__', 'odoo', 'openerp']
>>> from openerp.service import db
>>> db.list_dbs()
2018-01-07 19:18:47,924 186 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 362, in list_dbs
    with closing(db.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 634, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 178, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 517, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 585, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
>>> 
```
Expected behavior:
I should be able to get into the shell with the environment object available
Video/Screenshot link (optional):

**Comment by d-fence** [comment]
The problem seems that the Unix socket file is isolated in the Postgresql conatainer and the Odoo container cannot reach it.
I'm not sure that there is an easy solution to that.

**Comment by vivishow** [comment]
Check if there is a file /tmp/.s.PGSQL.5432 instead of /var/run/postgresql/.s.PGSQL.5432. 
you can run odoo with '-s'  and edit ～/.odoorc set db_host='/tmp'

**Comment by nehemiascr** [comment]
I was able to get it working by mounting the **/var/run/postgresql** folder from both the postgres and odoo containers into a volume.

**Comment by d-fence** [comment]
Thanks for the feedback. I close it then.
