### ISSUE TITLE
[11.0] Odoo.sh: Random phantom_poll TEST Fail

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22070]
### Impacted versions:
11.0

### Steps to reproduce:
In Odoo.sh upload a commit

### Current behavior:
The build can upload successfully or not, if not it's with the error:
```
2018-01-08 00:03:16,137 4 ERROR  odoo.addons.account_reports.tests.test_ui: FAIL
2018-01-08 00:03:16,139 4 ERROR  odoo.addons.account_reports.tests.test_ui: FAIL: test_ui (odoo.addons.account_reports.tests.test_ui.TestUi)
2018-01-08 00:03:16,141 4 ERROR  odoo.addons.account_reports.tests.test_ui: Traceback (most recent call last):
2018-01-08 00:03:16,180 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/home/odoo/src/odoo/odoo/tests/common.py", line 360, in phantom_poll
2018-01-08 00:03:16,181 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` self.fail(pformat(json.loads(line[prefix:])))
2018-01-08 00:03:16,183 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
2018-01-08 00:03:16,184 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` return _default_decoder.decode(s)
2018-01-08 00:03:16,185 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
2018-01-08 00:03:16,186 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2018-01-08 00:03:16,187 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
2018-01-08 00:03:16,188 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` raise JSONDecodeError("Expecting value", s, err.value) from None
2018-01-08 00:03:16,189 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-01-08 00:03:16,191 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` 
2018-01-08 00:03:16,192 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` During handling of the above exception, another exception occurred:
2018-01-08 00:03:16,193 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` 
2018-01-08 00:03:16,195 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` Traceback (most recent call last):
2018-01-08 00:03:16,196 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/home/odoo/src/enterprise/account_reports/tests/test_ui.py", line 10, in test_ui
2018-01-08 00:03:16,197 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` self.phantom_js("/", "odoo.__DEBUG__.services['web_tour.tour'].run('account_reports_widgets', 'test')", "odoo.__DEBUG__.services['web_tour.tour'].tours.account_reports_widgets", login='admin')
2018-01-08 00:03:16,198 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/home/odoo/src/odoo/odoo/tests/common.py", line 457, in phantom_js
2018-01-08 00:03:16,200 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` self.phantom_run(cmd, timeout)
2018-01-08 00:03:16,201 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/home/odoo/src/odoo/odoo/tests/common.py", line 384, in phantom_run
2018-01-08 00:03:16,203 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` result = self.phantom_poll(phantom, timeout)
2018-01-08 00:03:16,204 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` File "/home/odoo/src/odoo/odoo/tests/common.py", line 362, in phantom_poll
2018-01-08 00:03:16,205 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` self.fail(lline)
2018-01-08 00:03:16,207 4 ERROR  odoo.addons.account_reports.tests.test_ui: ` AssertionError: error tour account_reports_widgets failed at step .o_account_reports_body
2018-01-08 00:03:16,208 4 ERROR  odoo.addons.account_reports.tests.test_ui: FAILED
2018-01-08 00:03:16,210 4 ERROR  odoo.modules.module: Module account_reports: 1 failures, 0 errors
```
### Expected behavior
Consistency on this FAIL, or otherwise treat it as a Warning.

**Comment by gustavovalverde** [comment]
By the way, this happens when installing ln10_do as a dependency, even tried once with l10n_us and had the same result.

**Comment by Yenthe666** [comment]
@dbo-odoo could you have a look and answer this one please?

**Comment by gustavovalverde** [comment]
@nim-odoo, I think your commit 00039883c130c781803417ffb043fefaa29cf13f is closing this one.

**Comment by nim-odoo** [comment]
indeed

**Comment by dbo-odoo** [comment]
@Yenthe666 just an FYI: I'm no longer on the odoo.sh project :)

**Comment by Yenthe666** [comment]
@dbo-odoo oh I see 😢 Who is now?

**Comment by dbo-odoo** [comment]
@Yenthe666 I've edited https://github.com/odoo/odoo/wiki/BugManagement to reflect the change, odoosh is listed there :)

**Comment by Yenthe666** [comment]
Yikes, more information on the BugManagement page! 🎉 Thanks a lot @dbo-odoo! 
P.S: Feel free to expand all the rest too, this is really helpfull for me.
