### ISSUE TITLE
[11.0]Bug: snippet_latest_posts crashes the web page (500: Internal Server Error)

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#22089]
Impacted versions:
11.0
Steps to reproduce:
Insert the "Latest Post"-Snippet on a web page

Current behavior:
From time to time, the corresponding web page crashes and can not be recovered. It is necessary to delete the snippet code manually in the backend.

Traceback:
```
2018-01-08 09:53:21,792 23199 ERROR steakhouse-brunnen odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_838_400
  File "<template>", line 2, in body_call_content_399
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 257, in _get_field
    field = record._fields[field_name]
AttributeError: 'NoneType' object has no attribute '_fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1249, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1242, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1158, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1167, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'NoneType' object has no attribute '_fields'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_838_400
  File "<template>", line 2, in body_call_content_399
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 257, in _get_field
    field = record._fields[field_name]
AttributeError: 'NoneType' object has no attribute '_fields'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute '_fields'
Template: 838
Path: /templates/t/t/div/section[10]/div/div/div[1]/div[2]/h4
Node: <h4 class="media-heading" t-field="p.name"/>
```

Expected behavior:
The snippet works as expected.
Video/Screenshot link (optional):

**Comment by njeudy** [comment]
When changing the page where snippet is, odoo write rendered view of the snippet and not only le snippet block when changing pas content .. here is the wrong code:

```
<section class="s_latest_posts">
        <div class="container">
          <h2 class="text-center o_default_snippet_text">Latest Posts</h2>
          <div class="js_get_posts" data-loading="true" data-template="snippet_latest_posts.media_list_template">
            <div class="post media media_list_template">
              <div class="pull-left">
                <a href="/blog/1/post/2">
                  <div class="o_blog_cover_container cover container-fluid cover_full media-object loading_container thumb">
                    <div class="o_blog_cover_component o_blog_cover_image" data-oe-field="arch" data-oe-id="538" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/div[1]/div[1]" style="background-image: url(/web/image/website_blog.blog_post_cover_02);"/>
                    <div data-oe-field="arch" data-oe-id="538" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/div[1]/div[2]" class="o_blog_cover_component o_blog_cover_filter oe_black" style="opacity: 0.0;"/>
                    <div class="progress js-loading" style="display: none;">
                      <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;"/>
                    </div>
                  </div>
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading" t-field="p.name"/>
                <p t-field="p.subtitle"/>
                <a class="btn btn-default" data-oe-field="arch" data-oe-id="566" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/t[2]/div[1]/div[2]/a[1]" href="/blog/1/post/2">Read More</a>
              </div>
            </div>
            <div class="post media media_list_template">
              <div class="pull-left">
                <a href="/blog/1/post/1">
                  <div class="o_blog_cover_container cover container cover_narrow media-object loading_container thumb">
                    <div class="o_blog_cover_component o_blog_cover_image" data-oe-field="arch" data-oe-id="538" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/div[1]/div[1]" style="background-image: url(/web/image/website_blog.blog_post_cover_01);"/>
                    <div data-oe-field="arch" data-oe-id="538" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/div[1]/div[2]" class="o_blog_cover_component o_blog_cover_filter oe_black" style="opacity: 0.0;"/>
                    <div class="progress js-loading" style="display: none;">
                      <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;"/>
                    </div>
                  </div>
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading" t-field="p.name"/>
                <p t-field="p.subtitle"/>
                <a class="btn btn-default" data-oe-field="arch" data-oe-id="566" data-oe-model="ir.ui.view" data-oe-xpath="/t[1]/t[2]/div[1]/div[2]/a[1]" href="/blog/1/post/1">Read More</a>
              </div>
            </div>
          </div>
          <hr/>
        </div>
      </section>
```

In place you should have:

```
<section class="s_latest_posts">
        <div class="container">
          <h2 class="text-center o_default_snippet_text">Latest Posts</h2>
          <div class="js_get_posts" data-loading="true" data-template="snippet_latest_posts.media_list_template"/>
          <hr/>
        </div></section>
```

@Yenthe666 I don't know actually how to correct this.

**Comment by qsm-odoo** [comment]
Nice, it appears that an improvement I made in > 11.0 versions is automatically fixing that bug :smile: I will have to find a workaround for stable versions though. I will merge the solution today.

**Comment by njeudy** [comment]
@qsm-odoo thanks :)

**Comment by treviser** [comment]
@qsm-odoo Thanks from me too!

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/59e1bdff221f4a099f6000eb9884f84f772c38bb :relieved:

**Comment by younessiysa** [comment]
@qsm-odoo  Thanks
