### ISSUE TITLE
[10.0] Bixolon srp 350 plus not working!!

### ISSUE THREAD

**Issue by jbeltranarens** [odoo/odoo#22099]
Impacted versions: 
10.0

Steps to reproduce:

1. odoo in ubuntu 16.04 with posboxless

-$ odoo/odoo-bin --pidfile=posbox.pid --db-filter=posbox -d posbox --log-level=error --load=web,hw_posbox_homepage,hw_escpos

2018-01-09 01:55:15,856 28735 ERROR ? odoo.addons.hw_escpos.controllers.main: Can not get printer description: The device does not support the specified langid
2018-01-09 01:55:15,874 28735 INFO ? odoo.addons.hw_escpos.controllers.main: connected : Connected to Unknown printer (in=0x81,out=0x01)
/bin/sh: 1: ifconfig: not found
2018-01-09 01:55:15,944 28735 INFO ? odoo.addons.hw_escpos.controllers.main: error : write() got multiple values for keyword argument 'timeout'
2018-01-09 01:55:15,944 28735 ERROR ? odoo.addons.hw_escpos.controllers.main: ESC/POS Error: write() got multiple values for keyword argument 'timeout'
2018-01-09 01:55:15,945 28735 ERROR ? odoo.addons.hw_escpos.controllers.main: write() got multiple values for keyword argument 'timeout'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/odoo/odoo/addons/hw_escpos/controllers/main.py", line 167, in run
    self.print_status(printer)
  File "/home/odoo/odoo/addons/hw_escpos/controllers/main.py", line 201, in print_status
    eprint.text('\n\n')
  File "/home/odoo/odoo/addons/hw_escpos/escpos/escpos.py", line 824, in text
    self._raw(txt)
  File "/home/odoo/odoo/addons/hw_escpos/escpos/printer.py", line 85, in _raw
    if len(msg) != self.device.write(self.out_ep, msg, self.interface, timeout=5000):
TypeError: write() got multiple values for keyword argument 'timeout'
------------------------------------------------------------

Expected behavior:
printer work, pls

Video/Screenshot link (optional):

**Comment by pimodoo** [comment]
Hello,
It seems that "ifconfig" command is not even found on your system see: "/bin/sh: 1: ifconfig: not found"

Here is the documentation page explaining the basis of POSBoxless installation: https://www.odoo.com/documentation/user/11.0/point_of_sale/overview/setup.html#posboxless-guide-advanced . This warns you that the the installation process is not foolproof and that you can run issues due to your specific distribution.

More over, your printer "Bixolon srp 350" is not on the recommended software page: https://www.odoo.com/page/point-of-sale-hardware#part_7 

So we cannot help you more on this issue, I can only suggest you to buy a POSBox or build one yourself  with a raspberry Pi and the image on our nightly server. Then test your printer and change it by a recommended one if it doesn't work.

Best regards
