### ISSUE TITLE
Error Cannot compute cost price with product_extended on variants product and standard products

### ISSUE THREAD

**Issue by ofrmax** [odoo/odoo#22149]
Impacted versions:

 I'm using odoo v10 and the product_extended version is the last one from GitHub 

I know that someone as already "fix" this issue but it doesn't seem to work for me.

Steps to reproduce:

-install the addons
-go on the product and click on compute BOM cost

Current behavior:

here is the error I get when i try to compute the cost from a product without variant but with a BOM 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product_extended/models/product.py", line 15, in compute_price
    return template.product_variant_id.compute_price()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product_extended/models/product.py", line 29, in compute_price
    price = product._calc_price(bom)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/product_extended/models/product.py", line 46, in _calc_price
    total_cost += (order.time_cycle/60) * order.workcenter_id.costs_hour
AttributeError: 'mrp.workcenter' object has no attribute 'costs_hour'

Also i dont see the button to compute the variant cost. is it possible ? where is the button ?

![image](https://user-images.githubusercontent.com/19998638/34789360-fcd2d60a-f60b-11e7-9b4b-65caa7b6df70.png)

thanks for your help

**Comment by Yenthe666** [comment]
@sle-odoo could you have a look? The field `costs_hour` does exist on `mrp.workcenter` though.

**Comment by ofrmax** [comment]
Hi @Yenthe666 ,

thanks for your quick answer. For the plugin i downloaded the whole odoo branch like that : 

![image](https://user-images.githubusercontent.com/19998638/34826722-babb3f92-f6a5-11e7-9a8c-688423353509.png)

It not really familiar with GitHub so maybe I did something wrong. also here how I installed the addon:

-uninstall the current version of the addon
-on the server side, i deleted the addon folder
-I pushed the new addon folder on the server
-I rebooted the server
-I made an app update list  and I installed the addon


hope this is the right way to do it

**Comment by ofrmax** [comment]
HI, any update on this behavior? @sle-odoo  @Yenthe666 

Best regards,

**Comment by sle-odoo** [comment]
Hi @ofrmax,
Sorry but i can't reproduce your issue. Can you try on the last v10 [runbot](http://runbot.odoo.com/runbot)?

Are you working on a new database? Fyi, it's not recommended to update only a single addon. Please upgrade all your Odoo codebase and see if the issue is still happening.

Also, are you using community modules?

Regards

**Comment by ofrmax** [comment]
Hi @sle-odoo ,

thanks a lot for your support. I'm really not familliar with programming and testing so its possible i made something wrong. 

Would it be possible to point me how I can do an "upgrade all". Like a tutorial or something. i did not find anything about this.

Best regards,

**Comment by Yenthe666** [comment]
Hi @ofrmax,

If you've installed it from git:
- Navigate to your Odoo (for example /odoo/odoo)
- sudo git fetch origin 10.0
- sudo git reset --hard origin/10.0
- Run the Odoo from the terminal and provide -u all in the parameters or do a sudo service odoo-server restart -u all

Regards,
Yenthe
