### ISSUE TITLE
[8.0] [CRM_CLAIM] When print report crm claim its gives traceback.

### ISSUE THREAD

**Issue by jir-odoo** [odoo/odoo#2216]
Hi ,

In master as well as v8 when we clicked on analysis report crm_claim 
it will raise an traceback:

Traceback (most recent call last):
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 496, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 513, in dispatch
    result = self._call_function(**self.params)
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 279, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/jir/odoo/odoo_80/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 276, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 723, in __call__
    return self.method(*args, **kw)
  File "/home/jir/odoo/odoo_80/openerp/http.py", line 372, in response_wrap
    response = f(*args, **kw)
  File "/home/jir/odoo/odoo_80/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/jir/odoo/odoo_80/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/jir/odoo/odoo_80/openerp/api.py", line 234, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jir/odoo/odoo_80/openerp/models.py", line 2183, in read_group
    d.update(data_dict[d['id']])
KeyError: 18

Steps to reproduce:
--------------------------

1) Add more claim stages then case stage.
2) Assign max claim stage id  in claim.
3) Click on analysis report ( Reporting -> Sales -> Claim analysis ).

Solution :
------------

Its occurs due to wrong model 'crm.case.stage' in reference of stage_id field in crm_claim_report object.

'stage_id': fields.many2one ('crm.case.stage', 'Stage', readonly=True,domain="[('section_ids','=',section_id)]"),

Its solve by replacing.

'stage_id': fields.many2one ('crm.claim.stage', 'Stage', readonly=True,domain="[('section_ids','=',section_id)]"),

Thanks.

**Comment by yk2kus** [comment]
Please fix and merge it.

**Comment by antonylesuisse** [comment]
Fix landed in 9d6786bc4324fa94d4c73db70ccc83dec58c18c8
