### ISSUE TITLE
[11.0] Error Uploading Company Logo on Save

### ISSUE THREAD

**Issue by ChaosPower** [odoo/odoo#22222]
Impacted versions:
11.0 `3b80a059ff4305fe10c9b40a3118508b1b849ead`

Steps to reproduce:

Settings -> Companies -> Click on a Company -> Edit -> Highlight Company Logo Box -> Click Edit Icon -> Upload an Image

Current behavior:

Pop's out **Odoo Server Error** Dialog

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/admin/odoo/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/home/admin/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fa3edf90828>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/local/lib/python3.6/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/local/lib/python3.6/base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/admin/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/admin/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/admin/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/admin/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/admin/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/admin/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/admin/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/admin/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/admin/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/admin/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/admin/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/admin/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/admin/odoo/addons/account/models/company.py", line 139, in write
    return super(ResCompany, self).write(values)
  File "/home/admin/odoo/addons/product/models/res_company.py", line 70, in write
    return super(ResCompany, self).write(values)
  File "/home/admin/odoo/odoo/addons/base/res/res_company.py", line 236, in write
    return super(Company, self).write(values)
  File "/home/admin/odoo/odoo/models.py", line 3016, in write
    self._fields[key].determine_inverse(self)
  File "/home/admin/odoo/odoo/fields.py", line 1083, in determine_inverse
    self.inverse(records)
  File "/home/admin/odoo/odoo/fields.py", line 608, in _inverse_related
    other[field.name] = record_value[record]
  File "/home/admin/odoo/odoo/models.py", line 4668, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/admin/odoo/odoo/fields.py", line 990, in __set__
    record.write({self.name: write_value})
  File "/home/admin/odoo/odoo/addons/base/res/res_partner.py", line 514, in write
    result = result and super(Partner, self).write(vals)
  File "/home/admin/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/home/admin/odoo/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/admin/odoo/odoo/models.py", line 3223, in _write
    self.recompute()
  File "/home/admin/odoo/odoo/models.py", line 4801, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/admin/odoo/odoo/models.py", line 4801, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/admin/odoo/odoo/models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/admin/odoo/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/home/admin/odoo/odoo/fields.py", line 1038, in determine_value
    self.compute_value(recs)
  File "/home/admin/odoo/odoo/fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "/home/admin/odoo/odoo/fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "/home/admin/odoo/odoo/addons/base/res/res_company.py", line 135, in _compute_logo_web
    company.logo_web = tools.image_resize_image(company.partner_id.image, (180, None))
  File "/home/admin/odoo/odoo/tools/image.py", line 56, in image_resize_image
    image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)
```

Expected behavior:

Save and Show update logo

**Comment by Chlpn** [comment]
yes we are also facing this error with zero customisation

**Comment by fmdl** [comment]
I find where is come, this fix works, but is not the best : https://github.com/odoo/odoo/pull/22225

**Comment by fmdl** [comment]
@alexkuhn 
it come from this commit https://github.com/odoo/odoo/commit/41fe7f9d1113d026b226b136b4477aaaf9f1f638#diff-d9fe4c084619a0a6aa0b72cbf30cd9fc

**Comment by fmdl** [comment]
Maybe this error in linked:
![image](https://user-images.githubusercontent.com/16716992/34920120-c7d9bf62-f96d-11e7-8b07-0669f0a161fa.png)

**Comment by Yenthe666** [comment]
Hi @ChaosPower,

Thanks a lot for your report. I've just tested this and I can confirm that it is a bug:
![image](https://user-images.githubusercontent.com/6352350/34931046-dfd0775a-f9cc-11e7-81a1-5a4e2fd9b16c.png)

@mart-e this is a bit odd though, this was fixed a while ago. The bug is quite similar to the previous one (cc @xmo-odoo)

Regards,
Yenthe

**Comment by wtaferner** [comment]
Very fresh and annoying :-) Thank you for fixing this asap ;-)

**Comment by Elkasitu** [comment]
should be working again as of 2a54886, I'll re-open the issue if it is not the case

**Comment by Yenthe666** [comment]
Hi @Elkasitu,

I've just tested this and it seems to work fine!

Regards,
Yenthe

**Comment by ChaosPower** [comment]
Thanks for the quick fix!

**Comment by saadalee** [comment]
Same issue with python 3.6 and commit  2a54886.

**Comment by tejastank** [comment]
Just pulled latest in OdooCE11, yet same issue !!!
