### ISSUE TITLE
Error when install app module V11

### ISSUE THREAD

**Issue by kelvinthonyInti** [odoo/odoo#22321]
I update my instance of odoo v11 from github, before I have this problem.
Thanks for your answers. 

`Traceback (most recent call last):
  File "/intitec_dev/intitec_dev-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/intitec_dev/intitec_dev-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f6de2d0d730>, 'web.qunit_mobile_suite')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/intitec_dev/intitec_dev-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.qunit_mobile_suite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/intitec_dev/intitec_dev-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/intitec_dev/intitec_dev-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/intitec_dev/intitec_dev-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/intitec_dev/intitec_dev-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/intitec_dev/intitec_dev-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/intitec_dev/intitec_dev-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/intitec_dev/intitec_dev-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/intitec_dev/intitec_dev-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/intitec_dev/intitec_dev-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/intitec_dev/intitec_dev-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/intitec_dev/intitec_dev-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/intitec_dev/intitec_dev-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/intitec_dev/intitec_dev-server/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: web.qunit_mobile_suite" while parsing None:50, near
<data name="mail_mobile_tests" inherit_id="web.qunit_mobile_suite">
            <xpath expr="//t[@t-set='head']" position="inside">
                <script type="text/javascript" src="/mail/static/tests/client_action_mobile_tests.js"/>
            </xpath>
        </data>`

**Comment by Yenthe666** [comment]
Hi @kelvinthonyInti,

Thanks for your report.
Can you please add steps about what you did / which app you've installed etc? This is not enough information to help you.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in almost a month and as we need more information in order to help you.

Regards,
Yenthe

**Comment by edv-schuster** [comment]
I have the same problem now. Odoo11 nearly fresh installation. Only one module installed (contactlist)
cant install any other modules - always get this error...

**Comment by neroswords** [comment]
i have already try it. if u just drop your database and then reinstall. it's will work fine
