### ISSUE TITLE
Internal Server Error odoo 11

### ISSUE THREAD

**Issue by brunobronks** [odoo/odoo#22345]
Impacted versions: 11.0

Steps to reproduce:

Current behavior:

2018-01-18 11:32:12,400 6314 WARNING ? odoo.addons.base.res.res_currency: The num2words python library is not installed, l10n_mx_edi features won't be fully available.
2018-01-18 11:32:28,417 6314 INFO ? werkzeug: 127.0.0.1 - - [18/Jan/2018 11:32:28] "GET / HTTP/1.1" 500 -
2018-01-18 11:32:28,440 6314 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/opt/odoo/odoo/http.py", line 1319, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/opt/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 21, in <module>

ImportError: No module named 'sales_odoo_std_template'

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @brunobronks,

I see that your import error mentions `sales_odoo_std_template`. This module however is not a default module from Odoo S.A. This looks like something about your custom development. Did you forget to add the module?

Regards,
Yenthe

**Comment by brunobronks** [comment]
Hi @Yenthe666,

Thanks for your help...

But I don't find this module, will it sale management?

I can't find sales_odoo_std_template....

Regards,
brunobronks

**Comment by adekock11** [comment]
@brunobronks can you give the output from your `odoo-server.conf` file, specifically the `addons_path` line inside that file.

**Comment by Ecnart** [comment]
Please help :dancing_men: 
ERROR tperp werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1319, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1474, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 146, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 250, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/odoo/odoo/models.py", line 428, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'ir.http' does not exist in registry.
