### ISSUE TITLE
[11.0] Allow take more thant the lot availability

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#22352]
Impacted versions:
11.0 (saas)
Steps to reproduce:

Current behavior:
traceback:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/11.0/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/11.0/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/11.0/addons/sale_stock/models/stock.py", line 37, in write
    res = super(StockMove, self).write(vals)
  File "/home/odoo/src/odoo/11.0/addons/stock/models/stock_move.py", line 427, in write
    res = super(StockMove, self).write(vals)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3133, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 2263, in write
    comodel.browse(act[1]).write(act[2])
  File "/home/odoo/src/odoo/11.0/addons/stock_account/models/stock.py", line 100, in write
    correction_value = self.env['stock.move']._run_fifo(move_id, quantity=qty_difference)
  File "/home/odoo/src/odoo/11.0/addons/stock_account/models/stock.py", line 249, in _run_fifo
    'price_unit': -tmp_value / move.product_qty,
ZeroDivisionError: float division by zero
```

Expected behavior:

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
product_qty should never be 0 on a done move ; what steps did you take to be able to validate this move?

Regards

**Comment by nhomar** [comment]
@sle-odoo did you fixed in some place the division by 0?

**Comment by sle-odoo** [comment]
Nope. I'm not able to reproduce it at my end and you did not give me some steps to reproduce. Did you face the issue again?

**Comment by sle-odoo** [comment]
Sorry for the closing but we're trying to clean our opened issues.

**Comment by nhomar** [comment]
ok, but even if not reproducible (I have a test saas environment that I will share), this is a division by 0, this traceback should not appear. you should control such 0 elements to avoid the traceback in my opinion.

**Comment by sle-odoo** [comment]
A move done should always have an initial demand. This is one of the assumption we made. This could be enforced by a python constraint i agree.

Anyway if you ever stumble over it again feel free to contact me directly with some steps to reproduce or the database. I'll be happy to fix it.

Regards

**Comment by nhomar** [comment]
Hello @sle-odoo 

Another point is that I do not understand in which case the initial demand can and/or should be used as a denominator for a division that brings a division by 0.

I mean the code is proper explanatory.

```
-tmp_value / move.product_qty,
```

In which case this can be 0? well.

1.- Create a picking.
2.- Unlock (Because you did a mistake).
3.- Set to 0 because you will re-start the process again.
```

Due to the fact that we did not have a return/cancel process this is a way to avoid some extra documents, (at least from an usability stand point it is viable).

Can you enlight me?, Please.

**Comment by sle-odoo** [comment]
Hum. Well. I did not think of this flow...
I'll think about it tomorrow. Thank you.
I guess we could skip the move having an initial demand of 0 when looking for fifo IN candidates...

**Comment by wtaferner** [comment]
@sle-odoo 
This got me thinking and I am completely confused now...please enlight me as well in https://github.com/odoo/odoo/pull/23132#issuecomment-367427654

**Comment by rwfnf** [comment]
@sle-odoo I am facing this same issue as a consequence, it seems, of some pickings having been unlocked and quantities set to zero. It's blocking some operations. Is there a workaround/fix available?

Thanks
