### ISSUE TITLE
[11.0] requirements.txt giving error message while updating from it after windows conditional

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22378]
#### Impacted versions:
11.0

#### Steps to reproduce:
Update from requirements.txt after commit 3ede4c72df9e22a2b0c3129edc20d69201de2520
Using this command: `cat requirements.txt | xargs -n 1 pip install --no-cache-dir`

#### Current behavior:
This error: 
```python
Invalid requirement: ''
Traceback (most recent call last):
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "''"

Collecting sys_platform
  Could not find a version that satisfies the requirement sys_platform (from versions: )
No matching distribution found for sys_platform
Invalid requirement: '!='
Traceback (most recent call last):
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 2670, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/odoo/venv/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'!='"

Collecting win32

```
Expected behavior:
No error, maybe instead a warning. But this might need a more complex requirements.txt conditions. 

cc: @qdp-odoo

**Comment by Yenthe666** [comment]
Hmm not really for qdp though. @xmo-odoo or @d-fence this is most likely for one of you.

**Comment by qdp-odoo** [comment]
wrong command line... I guess you didn't try using 
```bash
$> pip install -r requirements.txt
```
