### ISSUE TITLE
[11.0] [Docker] Can't print any documents: Unexpected end of JSON input

### ISSUE THREAD

**Issue by pokapow** [odoo/odoo#22398]
Impacted versions:11.0

Steps to reproduce: Run Odoo docker-compose official exemple, in debian 9.

In a fresh Docker install, with Odoo 11, I can't print any document, invoice or whatever. There is a time of 1 minutes charging, and then this error:
```
Erreur:
Uncaught SyntaxError: Unexpected end of JSON input

https://exemple.fr/web#id=1&view_type=form&model=account.invoice&menu_id=123&action=198:1
Retraçage :
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at HTMLIFrameElement. (https://exemple.fr/web/content/369-daca186/web.assets_common.js:3843:379)
at HTMLIFrameElement.dispatch (https://exemple.fr/web/content/369-daca186/web.assets_common.js:892:451)
at HTMLIFrameElement.elemData.handle (https://exemple.fr/web/content/369-daca186/web.assets_common.js:865:173)
```

The URL here is OK. I can't find the "the web.base.url paramter in Settings>>Parameters>> Sytem Parameters" as say in this thread: https://www.odoo.com/fr_FR/forum/aide-1/question/openerp-client-error-uncaught-syntaxerror-unexpected-end-of-input-what-does-that-mean-62326

wkhtmltopdf seems to be install in the docker container, because when I enter the command "wkhtmltopdf" inside the container, the system recognizes it.

I don't find any pertinent logs about it. Where can I find good debug log ?

**Comment by pokapow** [comment]
Problem solve: I just remove the upstream parameter in my nginx reverse proxy ... Spent 3h just for that.
