### ISSUE TITLE
Error uploading Company Logo

### ISSUE THREAD

**Issue by Taekus** [odoo/odoo#22402]
Impacted versions: Odoo 11, commit 3b80a059ff4305fe10c9b40a3118508b1b849ead

Steps to reproduce: Attempt to upload Company Logo

Current behavior: Error: Expectance

Expected behavior: Accept Image and display as uploaded.

Video/Screenshot link (optional):

Error Displayed:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f11685bcc50>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/account/models/company.py", line 139, in write
    return super(ResCompany, self).write(values)
  File "/odoo/odoo-server/addons/product/models/res_company.py", line 70, in write
    return super(ResCompany, self).write(values)
  File "/odoo/odoo-server/odoo/addons/base/res/res_company.py", line 236, in write
    return super(Company, self).write(values)
  File "/odoo/odoo-server/odoo/models.py", line 3016, in write
    self._fields[key].determine_inverse(self)
  File "/odoo/odoo-server/odoo/fields.py", line 1083, in determine_inverse
    self.inverse(records)
  File "/odoo/odoo-server/odoo/fields.py", line 608, in _inverse_related
    other[field.name] = record_value[record]
  File "/odoo/odoo-server/odoo/models.py", line 4668, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/odoo/odoo-server/odoo/fields.py", line 990, in __set__
    record.write({self.name: write_value})
  File "/odoo/odoo-server/odoo/addons/base/res/res_partner.py", line 514, in write
    result = result and super(Partner, self).write(vals)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/odoo/odoo-server/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3223, in _write
    self.recompute()
  File "/odoo/odoo-server/odoo/models.py", line 4801, in recompute
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/odoo/models.py", line 4801, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/odoo/models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1038, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/odoo-server/odoo/addons/base/res/res_company.py", line 135, in _compute_logo_web
    company.logo_web = tools.image_resize_image(company.partner_id.image, (180, None))
  File "/odoo/odoo-server/odoo/tools/image.py", line 56, in image_resize_image
    image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)

**Comment by sswapnesh** [comment]
Hello @Taekus 
This issues has been resolved last week. 
Please upgrade your source code and try again.
Related to #22222 and #22231

**Comment by Yenthe666** [comment]
Indeed, this has been fixed in the meanwhile (just double checked that it is all working fine).
Please update your Odoo source code and it'll be fixed.

Regards,
Yenthe
