### ISSUE TITLE
m2m default_get

### ISSUE THREAD

**Issue by cormaza** [odoo/odoo#22401]
Impacted versions: 11.0

Steps to reproduce:

I create an assistant with trasientModel, in my example it is one that shows the lines of the invoice, where I pass by default in the assistant the taxes and the analytical labels of each line of invoice

The structure of a wizard is as follows, we have a field o2m which has m2m fields within its structure.

By means of default_get, [(0, 0, data)] are created, within the data step, assignation in the fields m2m [(6, 0, m2m_ids)]

Current behavior:

However in the class basic_model.js in the function _makeDefaultRecord when loading the fields type o2m does not fetch the data m2m inside the field, so I get the following error:

Uncaught TypeError: Cannot read property 'res_ids' of undefined
http://localhost:9069/web/static/src/js/views/basic/basic_model.js:2640
Rastreo de error:
TypeError: Cannot read property 'res_ids' of undefined
    at Class._generateX2ManyCommands (http://localhost:9069/web/static/src/js/views/basic/basic_model.js:2640:38)
    at Class._generateChanges (http://localhost:9069/web/static/src/js/views/basic/basic_model.js:2520:29)
    at Class._generateX2ManyCommands (http://localhost:9069/web/static/src/js/views/basic/basic_model.js:2703:44)
    at Class._generateChanges (http://localhost:9069/web/static/src/js/views/basic/basic_model.js:2520:29)
    at http://localhost:9069/web/static/src/js/views/basic/basic_model.js:865:32
    at Object.<anonymous> (http://localhost:9069/web/static/src/js/core/concurrency.js:216:31)
    at Object.<anonymous> (http://localhost:9069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:9069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://localhost:9069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://localhost:9069/web/static/lib/jquery/jquery.js:3275:77)

Expected behavior:

The fetch of the data of the m2m fields should be made

Video/Screenshot link (optional):

https://youtu.be/6qqvA-4udx0

**Comment by celm1990** [comment]
Hello Christopher, I get same error, is related to framework, but as patch, first  create new recordset and pass values, after show wizard to user.

![image](https://user-images.githubusercontent.com/7775116/35189983-e534c500-fe24-11e7-9839-ba9f3e3ee538.png)
It work fine

On many place get same error, but this patch is solved.

it would be good to correct that in the framework

**Comment by mge-odoo** [comment]
Bad reference, the mentioned commit was for the issue #22353

**Comment by mge-odoo** [comment]
Hi @cormaza 

Thanks a lot for reporting the issue which wasn't easy to spot.
I has been fixed in 11.0

Regards,

Martin

**Comment by cormaza** [comment]
Thanks a lot
