### ISSUE TITLE
[11.0] export 60k rows record raise MemoryError

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#22475]
Impacted versions:
11.0

Steps to reproduce:
when export data that large 60k as excel, it raise python MemoryError.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 74, in wrap
>     return f(*args, **kwargs)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1438, in index
>     return self.base(data, token)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 1386, in base
>     import_data = records.export_data(field_names, self.raw_data).get('datas',[])
>   File "/opt/odoo/odoo11/odoo/models.py", line 725, in export_data
>     return {'datas': self._export_rows(fields_to_export)}
>   File "/opt/odoo/odoo11/odoo/models.py", line 677, in _export_rows
>     value = record[name]
>   File "/opt/odoo/odoo11/odoo/models.py", line 4657, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/opt/odoo/odoo11/odoo/fields.py", line 948, in __get__
>     self.determine_value(record)
>   File "/opt/odoo/odoo11/odoo/fields.py", line 1057, in determine_value
>     recs = record._in_cache_without(self)
>   File "/opt/odoo/odoo11/odoo/models.py", line 4687, in _in_cache_without
>     recs = self + (recs - self)[:(limit - len(self))]
>   File "/opt/odoo/odoo11/odoo/models.py", line 4568, in __sub__
>     return self.browse([id for id in self._ids if id not in other_ids])
>   File "/opt/odoo/odoo11/odoo/models.py", line 4237, in browse
>     return self._browse(ids, self.env, prefetch)
>   File "/opt/odoo/odoo11/odoo/models.py", line 4224, in _browse
>     prefetch[cls._name].update(ids)
> MemoryError

**Comment by Elkasitu** [comment]
Hi, thanks for the report, can you tell me if you have a memory limit different than the default for your instance?

**Comment by jeffery9** [comment]
standalone Odoo instance with 128G physical RAM installed.   running with those settings   

> workers = 20
> limit_memory_soft = 2684354560    # 2.5G
> limit_memory_hard = 3221225472  # 3G
 
default limit_memory_soft  is 2G, and default limit_memory_hard  is 2.5G

**Comment by xmo-odoo** [comment]
@jeffery9 I merged odoo/odoo#22494 which *should* significantly improve memory consumption during imports, could you check with d28f8f7?
