### ISSUE TITLE
[11.0] Not possible to use the "Customize Theme" feature with CDN is activated.

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#22516]
Impacted versions:
11.0

Steps to reproduce:
1. Activate the Content Delivery Network (CDN) settings.
2. Go to the website and open the "Customize Theme" panel.
3. Change the "Layout" to "Boxed"

Current behavior:
1. The screen freezes
2. Error message in JavaScript
```
web.assets_common.js:3832 Server application error
{
	"data": {
		"exception_type": "internal_error",
		"debug": "Traceback (most recent call last):\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 646, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/tslai/ws/sst/odoo/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/tslai/ws/sst/odoo/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 927, in __call__\n    return self.method(*args, **kw)\n  File \"/home/tslai/ws/sst/odoo/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/tslai/ws/sst/odoo/addons/website/controllers/main.py\", line 378, in theme_customize\n    return request.env[\"ir.qweb\"]._get_asset('web.assets_frontend', options=context)\n  File \"/home/tslai/ws/sst/odoo/addons/website/models/ir_qweb.py\", line 29, in _get_asset\n    values = dict(values, url_for=website.get_cdn_url)\nTypeError: 'NoneType' object is not iterable\n",
		"name": "builtins.TypeError",
		"message": "'NoneType' object is not iterable",
		"arguments": ["'NoneType' object is not iterable"]
	},
	"message": "Odoo Server Error",
	"code": 200
}
```

3. Python Error:
```
2018-01-25 10:41:50,140 25409 ERROR tsst3 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/tslai/ws/sst/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/tslai/ws/sst/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/tslai/ws/sst/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/tslai/ws/sst/odoo/addons/website/controllers/main.py", line 378, in theme_customize
    return request.env["ir.qweb"]._get_asset('web.assets_frontend', options=context)
  File "/home/tslai/ws/sst/odoo/addons/website/models/ir_qweb.py", line 29, in _get_asset
    values = dict(values, url_for=website.get_cdn_url)
TypeError: 'NoneType' object is not iterable
```

Screenshots:
The "Customize Theme" panel
![image](https://user-images.githubusercontent.com/27185427/35385174-6f4c0844-0202-11e8-8070-957ce538a9ab.png)

**Comment by Yenthe666** [comment]
@ged-odoo this should be of interest to you!

**Comment by lukebranch** [comment]
confirmed, i've got the same issue behind a CDN.

**Comment by qsm-odoo** [comment]
Hello,
The bug already appeared in 10.0 so I merged a fix in there https://github.com/odoo/odoo/commit/a93a9d43e6b383a8ade8395017110e49b80d48cd. This will be forward-ported to 11.0 in the upcoming days.
