### ISSUE TITLE
[11.0] Error when creating Assets from PO

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22527]
Impacted versions: v11e

Steps to reproduce:
1. Create an Asset Category with Degressive Method, with a number of 0 entries and every 1 month.
2. Create a PO
3. Select Product.
4. Set Asset Category
5. Click Save.

Current behavior:
1. If the asset is created by the assets menu (Accounting > Adviser > Assets) it can be created with no issues using the same category.
2. If the asset is created directly from the PO it will raise the following error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f9848e8c9b0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/purchase/models/account_invoice.py", line 209, in create
    invoice = super(AccountInvoice, self).create(vals)
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_invoice.py", line 465, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3435, in _create
    self.recompute()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4801, in recompute
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4801, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1038, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "<decorator-gen-189>", line 2, in _get_asset_date
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/src/odoo/addons/account_asset/models/account_invoice.py", line 62, in _get_asset_date
    raise UserError(_('The number of depreciations or the period length of your asset category cannot be null.'))
NameError: name 'UserError' is not defined
```

The logic around this piece of code requires revision.

Expected behavior:
- Allow to create the asset from the PO.

Video/Screenshot link (optional):

******************************
CC: @gustavovalverde

**Comment by gustavovalverde** [comment]
This was fixed by #22460, is not in 11.0 but it should be forwarded in the following days.

This can be closed.
