### ISSUE TITLE
Edit Header raises error when template field blank

### ISSUE THREAD

**Issue by gridworkz** [odoo/odoo#22622]
Impacted versions: 11

Steps to reproduce: Developer mode -> General Settings -> Blank template field -> Edit Header

Current behavior: Error

Expected behavior: Message

Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/opt/Mamme Market/Mamme Market/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Mamme Market/Mamme Market/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/Mamme Market/Mamme Market/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/Mamme Market/Mamme Market/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Mamme Market/Mamme Market/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Mamme Market/Mamme Market/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Mamme Market/Mamme Market/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Mamme Market/Mamme Market/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/Mamme Market/Mamme Market/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/Mamme Market/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/Mamme Market/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Mamme Market/Mamme Market/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/Mamme Market/Mamme Market/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/Mamme Market/addons/base_setup/models/res_config_settings.py", line 93, in edit_external_header
    return self._prepare_report_view_action('web.external_layout_' + self.external_report_layout)
TypeError: Can't convert 'bool' object to str implicitly

**Comment by sswapnesh** [comment]
I can also confirm this Issue.
Cc: @Yenthe666
