### ISSUE TITLE
Export full language as TGZ format fails

### ISSUE THREAD

**Issue by simosuu** [odoo/odoo#22700]
Impacted versions: 11.0 (20.1.2018)

Steps to reproduce:

Export full language as TGZ format. Please see the attachment. 

Current behavior:

```
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/wizard/base_export_language.py", line 38, in act_getfile
    tools.trans_export(lang, mods, buf, this.format, self._cr)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 713, in trans_export
    _process(format, modules, translations, buffer, lang)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 700, in _process
    _process('po', [mod], modrows, buf, lang)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 669, in _process
    writer.write_infos(modules)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 622, in write_infos
    'now': datetime.utcnow().strftime('%Y-%m-%d %H:%M')+"+0000",
  File "/usr/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/lib/python3.5/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

Expected behavior:

Succesful export.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23297584/35673472-582cb3e6-074a-11e8-8082-6f712a3d07de.png)

**Comment by xmo-odoo** [comment]
Thanks for the report, this should now be fixed.

**Comment by xmo-odoo** [comment]
By the way @simosuu if you don't mind: what's your use case for this specific export / export format?

**Comment by simosuu** [comment]
Export/Import terms between odoo instances.

---
Best regards,
Simo
