### ISSUE TITLE
Pressing ESC button on editable tree view exception Uncaught TypeError: record.evalModifiers is not a function

### ISSUE THREAD

**Issue by cantecim** [odoo/odoo#22718]
Impacted versions:
11.0

Steps to reproduce:
1 - Open a v11 enterprise instance on runbot
2 - Login with admin
2 - Activate debug mode
3 - Go to admin user details and enable "Manage Product Variants" then save it
4 - Go to Sales app, refresh the page then open "Configuration -> Products -> Attributes" menu
5 - Click on some entry to edit, press ESC

Current behavior:
I think it assumes the record was modified, so it throws the exception

Expected behavior:
Closing edit mode without any exception

Video/Screenshot link (optional):

## Exception with traceback
Error:
Uncaught TypeError: record.evalModifiers is not a function

http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_renderer.js:665
Traceback:
TypeError: record.evalModifiers is not a function
    at http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_renderer.js:665:66
    at Function._.each._.forEach (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/lib/underscore/underscore.js:145:9)
    at Class._updateAllModifiers (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_renderer.js:664:11)
    at Class.confirmChange (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_renderer.js:114:24)
    at Class.confirmChange (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/list/list_editable_renderer.js:97:28)
    at Class.confirmChange (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/core/class.js:133:38)
    at Class._confirmChange (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_controller.js:275:30)
    at http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/src/js/views/basic/basic_controller.js:514:22
    at fire (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://298939-11-0-bb26d6.runbot9.odoo.com/web/static/lib/jquery/jquery.js:3165:49)

**Comment by Yenthe666** [comment]
Hi @cantecim,

Thanks a lot for the bug report. I can confirm that this is an issue:
![image](https://user-images.githubusercontent.com/6352350/35686467-9e7d1576-076c-11e8-851d-ef2634b9e6ec.png)

@ged-odoo could you have a look / assign somebody?

Regards,
Yenthe

**Comment by mge-odoo** [comment]
Hi @cantecim 

Thanks for reporting the bug.
It has been fixed in 11.0

Martin
