### ISSUE TITLE
Recompute of related field with groups restriction raises AccessError

### ISSUE THREAD

**Issue by christophlsa** [odoo/odoo#22840]
**Impacted versions:** 11.0

**Steps to reproduce:**

In general I want to create a product with an user which has no access to the backend. See the code steps I did here. The problem is that the recompute function wants to set the related field `activity_date_deadline` which has the parameter `groups="base.group_user"` set. I'm not sure if this is the intended behaviour but this makes it not possible to create a product by an user without backend access.

This happens to all models which use the mixin (this means also sale.order etc).

In odoo shell:

```python
test_group = env['res.groups'].create({'name': 'Test'})
test_user = env['res.users'].create({'name': 'Test User', 'login': 'testuser', 'groups_id': [(6, 0, [test_group.id])], 'lang': 'en_US'})
env['ir.model.access'].create({'name': 'Test Product Template', 'model_id': env.ref('product.model_product_template').id, 'group_id': test_group.id, 'perm_read': True, 'perm_write': True, 'perm_create': True})
env['ir.model.access'].create({'name': 'Test Product Product', 'model_id': env.ref('product.model_product_product').id, 'group_id': test_group.id, 'perm_read': True, 'perm_write': True, 'perm_create': True})
env['ir.model.access'].create({'name': 'Test UOM', 'model_id': env.ref('product.model_product_uom').id, 'group_id': test_group.id, 'perm_read': True})
env['ir.model.access'].create({'name': 'Test Category', 'model_id': env.ref('product.model_product_category').id, 'group_id': test_group.id, 'perm_read': True})
env['ir.model.access'].create({'name': 'Test Partner', 'model_id': env.ref('base.model_res_partner').id, 'group_id': test_group.id, 'perm_read': True})
product = env['product.product'].with_context(lang='en_US').sudo(test_user.id).create({'name': 'Test Product'})
```

**Current behavior:**

```
2018-02-06 12:13:03,505 10762 INFO ticket159 odoo.models: Access Denied by ACLs for operation: write, uid: 43, model: product.template, fields: activity_date_deadline
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/var/www/addons/product/models/product.py", line 300, in create
    product = super(ProductProduct, self.with_context(create_product_product=True)).create(vals)
  File "/var/www/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/var/www/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/var/www/odoo/models.py", line 3335, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/var/www/addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "/var/www/addons/product/models/product_template.py", line 287, in create
    template = super(ProductTemplate, self).create(vals)
  File "/var/www/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/var/www/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/var/www/odoo/models.py", line 3435, in _create
    self.recompute()
  File "/var/www/odoo/models.py", line 4809, in recompute
    target._write(dict(vals))
  File "/var/www/odoo/models.py", line 3031, in _write
    self.check_field_access_rights('write', list(vals))
  File "/var/www/odoo/models.py", line 2472, in check_field_access_rights
    (self._description, operation))
odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Product Template, Operation: write)', None)
```

**Expected behavior:**

The creation of the product works without access to the backend group.

**Comment by C3POdoo** [comment]
Dear @christophlsa,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
