### ISSUE TITLE
short dump in creating an Analytic Entry

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#22884]
Impacted versions:
10
Steps to reproduce:
press button "create" Analytic Entry
the following short system dump has occurred
Current behavior:
short dump 
Expected behavior:
no system dump at all

Traceback (most recent call last):
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 5474, in onchange
    value = record[name]
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 5208, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo10/odoo.10-dev/odoo/odoo/fields.py", line 912, in __get__
    self.determine_draft_value(record)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/fields.py", line 1033, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo10/odoo.10-dev/odoo/addons/project_timesheet_currency/models/analytic.py", line 38, in _get_amount_currency
    aal.account_id.currency_id)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/addons/base/res/res_currency.py", line 152, in compute
    assert self, "compute from unknown currency"
AssertionError: compute from unknown currency

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thanks for the bug report.
Can you reproduce this on an official Odoo test instance at runbot.odoo.com? Can you add screenshots / more details? I don't seem to have any issue.

Regards,
Yenthe

**Comment by vcloud9ray** [comment]
I was unable to replicate on runbot at http://300876-11-0-7ff518.runbot8.odoo.com

It could be due to https://apps.odoo.com/apps/modules/10.0/project_timesheet_currency/ which is a community module.

A better place to log this might be https://github.com/OCA/project/issues

**Comment by ccandito** [comment]
solved!!!
thanks for your suggestion
Regards
claudio candito
