### ISSUE TITLE
[11.0] mass_mailing link.tracker search view error

### ISSUE THREAD

**Issue by jbofill** [odoo/odoo#23014]
Impacted versions:

11.0

Steps to reproduce:

1. Create a new database o use an existing one, with mass_mailing.
2. Activate developer mode
3. Goto link tracker menu

Current behavior:

Nothing happens but log throws this error.

```
Traceback (most recent call last):
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/user/odoo-dev/odoo/odoo11.0/addons/web/controllers/main.py", line 1206, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_actions.py", line 197, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/models.py", line 2520, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/fields.py", line 1062, in determine_value
    self.compute_value(recs)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_actions.py", line 157, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/models.py", line 1305, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/models.py", line 1268, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/home/user/odoo-dev/odoo/odoo11.0/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: L'element '<search string="Enllaç Seguit">' no pot ser localitzat en la vista superior

Error de contexte:
Mireu `link.tracker.search`
[view_id: 312, xml_id: mass_mailing.view_mail_mass_mailing_links_search, model: link.tracker, parent_id: 231]
```

Expected behavior:
Show Link Tracker Tree

Work around:
addons/mass_mailing/views/link_tracker_views.xml
Remove or comment view id=view_mail_mass_mailing_links_search

**Comment by Yenthe666** [comment]
Hi @jbofill,

Thanks a lot for the bug report.
Have you updated your code to the latest version? Can you reproduce it on an official Odoo test instance at runbot.odoo.com?
It seems to work fine out of the box on the latest Odoo 11 (both in English and French):
![image](https://user-images.githubusercontent.com/6352350/36137232-87b02af0-1094-11e8-9584-86e8b73b89e3.png)

**Comment by jbofill** [comment]
Using latest code from github branch 11.0.

The problem arises when Catalan translation is used.
The cause is that the view is inheriting from an other view without giving the position.
It works correctly if in `addons/mass_mailing/views/link_tracker_views.xml` you change view id `view_mail_mass_mailing_links_search`

from:
`<search string="Tracked Link">`
to:
`<search position="inside">`

**Comment by Yenthe666** [comment]
Hi @jbofill,

Thanks for the extra info, I was able to reproduce it in Catalan. This is an internationalization issue really.
@mart-e can you have a look and can you see if you're okay with the search string change? It looks good to me.
