### ISSUE TITLE
 docker Odoo becomes entirely defunct by trying to attach an addons volume

### ISSUE THREAD

**Issue by deepdad** [odoo/odoo#23060]
I want to share documents privately for editing and didn't find this possible in the default apps. In the app store there is Share any Document although it is for 8.0 (this may be a cause for what's below).

Either way, docker Odoo becomes entirely defunct by trying to attach an addons volume. Maybe I'm giving the wrong docker command: not sure it connects to the standard (docker) postgres here.

Impacted versions:
docker latest

Steps to reproduce:
1. docker stop a14cd26c8e2a
2. docker commit a14cd26c8e2a newimagename
3. download https://www.odoo.com/apps/modules/8.0/share/ into /home/ubuntu/addons/
4. mv into share.zip
5. unzip share.zip
6. ~$ docker run -p 8069:8069 --link db:db  -ti -v /home/ubuntu/addons/share:/mnt/extra-addons newimagename

Current behavior:
~$ docker run -p 8069:8069 --link db:db  -ti -v /home/ubuntu/addons/share:/mnt/extra-addons newimagename 
2018-02-14 11:50:34,322 1 INFO ? odoo: Odoo version 11.0-20180122
2018-02-14 11:50:34,322 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-02-14 11:50:34,322 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-02-14 11:50:34,323 1 INFO ? odoo: database: odoo@172.17.0.2:5432
2018-02-14 11:50:34,333 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-02-14 11:50:34,416 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-02-14 11:50:43,179 1 INFO ? odoo.http: HTTP Configuring static files
2018-02-14 11:50:43,193 1 INFO db_name odoo.modules.loading: loading 1 modules...
2018-02-14 11:50:43,210 1 INFO db_name odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2018-02-14 11:50:43,227 1 INFO db_name odoo.modules.loading: loading 29 modules...
2018-02-14 11:50:43,284 1 WARNING db_name odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not installed. Try: pip install phonenumbers.
2018-02-14 11:50:43,298 1 INFO db_name odoo.modules.loading: 29 modules loaded in 0.07s, 0 queries
2018-02-14 11:50:43,591 1 INFO db_name odoo.modules.loading: Modules loaded.
2018-02-14 11:50:43,595 1 INFO db_name odoo.addons.base.ir.ir_http: Generating routing map
2018-02-14 11:50:44,097 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:50:44] "GET / HTTP/1.1" 200 -
2018-02-14 11:50:44,241 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:50:44] "GET /web/image/website.s_image_text_default_image HTTP/1.1" 304 -
2018-02-14 11:50:44,257 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/d5/d5cce68bf4bb4ab57beaf766f3fb775cf8df0c83
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea360c898>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea35279e8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea35279e8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/d5/d5cce68bf4bb4ab57beaf766f3fb775cf8df0c83'
2018-02-14 11:50:44,258 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:50:44] "GET /web/image/website.s_background_image_07 HTTP/1.1" 304 -
2018-02-14 11:50:44,261 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:50:44] "GET /web/image/res.company/1/logo?unique=207c9e4 HTTP/1.1" 200 -
2018-02-14 11:50:44,330 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:50:44] "GET /web/image/website/1/favicon/ HTTP/1.1" 304 -
2018-02-14 11:51:59,486 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:51:59] "GET / HTTP/1.1" 200 -
2018-02-14 11:51:59,615 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:51:59] "GET /web/image/website.s_image_text_default_image HTTP/1.1" 304 -
2018-02-14 11:51:59,628 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:51:59] "GET /web/image/website.s_background_image_07 HTTP/1.1" 304 -
2018-02-14 11:51:59,713 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:51:59] "GET /web/image/website/1/favicon/ HTTP/1.1" 304 -
2018-02-14 11:52:18,207 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:52:18] "GET /web HTTP/1.1" 303 -
2018-02-14 11:52:18,354 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:52:18] "GET /web/login HTTP/1.1" 200 -
2018-02-14 11:52:18,565 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:52:18] "GET /web/image/website/1/favicon/ HTTP/1.1" 304 -
2018-02-14 11:52:57,309 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:52:57] "POST /web/login HTTP/1.1" 303 -
2018-02-14 11:52:57,509 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/bb/bb2dd524fdf12b73f3ae30d72fb8b88257608297
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea352deb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/bb/bb2dd524fdf12b73f3ae30d72fb8b88257608297'
2018-02-14 11:52:57,512 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/43/43c6740905a73c92f02235faacdd207d9d924e62
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea352deb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/43/43c6740905a73c92f02235faacdd207d9d924e62'
2018-02-14 11:52:57,514 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea352deb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31'
2018-02-14 11:52:57,515 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea352deb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d'
2018-02-14 11:52:57,516 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea352deb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03'
2018-02-14 11:52:57,989 1 INFO db_name werkzeug: IP - - [14/Feb/2018 11:52:57] "GET /web HTTP/1.1" 200 -
2018-02-14 11:53:24,125 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/bb/bb2dd524fdf12b73f3ae30d72fb8b88257608297
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, None, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea353e6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/bb/bb2dd524fdf12b73f3ae30d72fb8b88257608297'
2018-02-14 11:53:24,126 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/43/43c6740905a73c92f02235faacdd207d9d924e62
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, None, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea353e6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/43/43c6740905a73c92f02235faacdd207d9d924e62'
2018-02-14 11:53:24,127 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, None, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea353e6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31'
2018-02-14 11:53:24,129 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, None, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea353e6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d'
2018-02-14 11:53:24,131 1 INFO db_name odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/db_name/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f7eb28fd268>, 1, None, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f7ea353e6d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/db_name/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03'

**Comment by Yenthe666** [comment]
@d-fence docker related issue.

**Comment by deepdad** [comment]
I'm new o Odoo whatsoever. But I guess that must be it then? It's not backward compatible. Luckily it's just a docker image.

**Comment by Yenthe666** [comment]
@deepdad no you can't combine apps from different versions. Almost every Odoo version works slightly different, especially when you take the leap from V8 to V11.
