### ISSUE TITLE
[Odoo 11.0] Error appear when giving discount in POS

### ISSUE THREAD

**Issue by arafatx** [odoo/odoo#23126]
**Impacted versions**: 11.0

**Steps to reproduce:**

1) Go to Point Of Sale
2) Click on any product
3) Click on Discount 
4) Apply any number of discount
5) Click OK
6) Error appear

**Current behavior:**
Error appear

**Expected behavior:**
Item got discount and no error appear

**Video/Screenshot link (optional):**

https://s10.postimg.org/chghyy45l/error-odoo-11-pos.png

Error message:

Uncaught SyntaxError: Unexpected token u in JSON at position 0
http://192.164.0.147:8069/pos/web/#action=pos.ui:1
Traceback:
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at child.add_product (http://192.164.0.147:8069/web/content/989-6b00226/point_of_sale.assets.js:209:58)
    at Class.apply_discount (http://192.164.0.147:8069/web/content/989-6b00226/point_of_sale.assets.js:421:72)
    at Class.confirm (http://192.164.0.147:8069/web/content/989-6b00226/point_of_sale.assets.js:420:454)
    at Class.click_confirm (http://192.164.0.147:8069/web/content/989-6b00226/point_of_sale.assets.js:328:1288)
    at HTMLDivElement.<anonymous> (http://192.164.0.147:8069/web/content/693-de3212b/web.assets_common.js:3917:11)
    at HTMLDivElement.dispatch (http://192.164.0.147:8069/web/content/693-de3212b/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (http://192.164.0.147:8069/web/content/693-de3212b/web.assets_common.js:865:173)

**Comment by arafatx** [comment]
odoo server log is not generated because this problem is related to javascript.

**Comment by Yenthe666** [comment]
Hi @arafatx,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 11.0 and it works fine out of the box. Can you reproduce it on an official Odoo test instance at runbot.odoo.com? Is your Odoo running on the latest code? Perhaps you have custom development added?

Regards,
Yenthe

**Comment by jorenvo** [comment]
It is because your discount product is not available in the point of sale. You can make it available in the Sales tab of your product.

**Comment by Yenthe666** [comment]
Ah good catch Joren! Perhaps we could build in a check with a clean warning for this?

**Comment by blfernandez** [comment]
Get the same error in ODOO 11 POS
![odoo11error](https://user-images.githubusercontent.com/31223119/53685422-d41d0500-3cf0-11e9-9136-8c6a665aa6ee.png)

**Comment by blfernandez** [comment]
var product = self.pos.db.get_product_by_id(self.coupon_product); Return NULL 

order.add_product(product, {quantity: 1, price: price}); Give a Error, product is null.
