### ISSUE TITLE
[11.0] Point of sale - Can't perform sales

### ISSUE THREAD

**Issue by grocav** [odoo/odoo#23135]
Impacted versions: 11

Steps to reproduce:
Go to POS module
start new POS session
Open session
Start sales
error screen appears

Current behavior:
not go to sales screen
Expected behavior:
error screen

------------------------------------------
TypeError: url.indexOf is not a function
    at Object.loaded (http://localhost:8069/web/content/1206-f5ae659/point_of_sale.assets.js:467:153)
    at Object.<anonymous> (http://localhost:8069/web/content/1206-f5ae659/point_of_sale.assets.js:124:58)
    at Object.<anonymous> (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:801:198)
    at Object.<anonymous> (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:802:874)
    at fire (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:801:198)
    at done (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:1192:95)
    at XMLHttpRequest.callback (http://localhost:8069/web/content/313-c3ba8a3/web.assets_common.js:1212:15)

![image](https://user-images.githubusercontent.com/36600959/36353297-f9652970-149a-11e8-8db5-4265c51fe301.png)

**Comment by grocav** [comment]
seems to be a problem with printers config

**Comment by pimodoo** [comment]
Hello,

Could you please open your POS while beeing in 'Developer mode' and send us the traceback, it will provide us more information about the location of the problem.

Thanks

**Comment by frbn** [comment]
Hi,
isn't this a jquery issue ?
https://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

**Comment by halsanei** [comment]
Hi,
i Had same error please find below the error with developer mode 


TypeError: url.indexOf is not a function
    at Object.loaded (http://localhost:8069/web/content/355-9e57c69/point_of_sale.assets.js:472:153)
    at Object.<anonymous> (http://localhost:8069/web/content/355-9e57c69/point_of_sale.assets.js:125:58)
    at Object.<anonymous> (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:801:198)
    at Object.<anonymous> (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:802:874)
    at fire (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:801:198)
    at done (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:1192:95)
    at XMLHttpRequest.callback (http://localhost:8069/web/content/336-c00a520/web.assets_common.js:1212:15)

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem with runbot and paste the same the log in developer mode (with proper quoting using ` ``` `)

**Comment by halsanei** [comment]
its working with no error on runbot,but in my laptop its showing error

**Comment by pedrobaeza** [comment]
Then you will have outdated code or a custom module that breaks the system.

I'm closing this issue while no further trace of Odoo problem is given.
