### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ebo2007** [odoo/odoo#23183]
Impacted versions: 11

Steps to reproduce: final steps (Running Odoo Server)

when trying to execute the command : ./odoo-bin --addons-path=addons,../mymodules --db-filter=mydb$
I get this error  how can I solve it ?

Running as user 'root' is a security risk.
Traceback (most recent call last):
  File "./odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/Users/ebouh/odoo/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/Users/ebouh/odoo/odoo/cli/server.py", line 175, in run
    main(args)
  File "/Users/ebouh/odoo/odoo/cli/server.py", line 124, in main
    odoo.tools.config.parse_config(args)
  File "/Users/ebouh/odoo/odoo/tools/config.py", line 334, in parse_config
    odoo.netsvc.init_logger()
  File "/Users/ebouh/odoo/odoo/netsvc.py", line 95, in init_logger
    resetlocale()
  File "/Users/ebouh/odoo/odoo/tools/translate.py", line 1183, in resetlocale
    for ln in get_locales():
  File "/Users/ebouh/odoo/odoo/tools/translate.py", line 1152, in get_locales
    lang = locale.getdefaultlocale()[0]
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by vnnw** [comment]
I think this url will have the answer you need: https://www.odoo.com/forum/help-1/question/locale-issue-valueerror-unknown-locale-utf-8-with-odoo-8-106892

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by JDSalcedo** [comment]
I dont have the enough karma(7) to post my answer in help.odoo.com, I got the same problem when I try to debug but I can solve this problem configuring the compatibility off languaje with programs no Unicode compatibility, I cost me a day and a half of swimming into the Odoo core, and I found the problem related to 'locale' library. Go to Control panel > Region > Administrative > Languaje to no Unicode programs:
![image](https://user-images.githubusercontent.com/8197930/54647924-5be56c00-4a72-11e9-8f6c-4542f9dd06e7.png)

Save the changes and restart your computer, try again.
