### ISSUE TITLE
Tengo instalado odoo 11 en Google_Cloud_Platform

### ISSUE THREAD

**Issue by Joel1971** [odoo/odoo#23206]
Impacted versions:
Odoo 11

Steps to reproduce:
Esta se instalo sin problemas al instalar el modulo "user_login_alert" el servidor presento error en la instalación. al cancelar la instalación, el servidor ya no reacciono. presentando la sig traza.

Current behavior:

2018-02-20 19:01:34,031 28680 INFO ? odoo: Odoo version 11.0-20180217
2018-02-20 19:01:34,031 28680 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-02-20 19:01:34,031 28680 INFO ? odoo: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/11.0', '/usr/lib/python3/dist-packages/odoo/addons']
2018-02-20 19:01:34,032 28680 INFO ? odoo: database: odoo@default:default
2018-02-20 19:01:34,039 28680 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-02-20 19:01:34,121 28680 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2018-02-20 19:02:46,778 28680 INFO ? werkzeug: 201.102.112.175 - - [20/Feb/2018 19:02:46] "GET / HTTP/1.1" 500 -
2018-02-20 19:02:46,780 28680 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1303, in __call__
    self.load_addons()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1325, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 23, in <module>
ImportError: No module named 'controllers'

Expected behavior:

la situacion es que no encuentro que modulo esta intentando llamar a "controllers"

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Joel1971,

Thanks for the report.
My spanish is really bad but if I understand you correctly you've installed the module `user_login_alert` and now you're getting an `ImportError` after trying to install this community module?

**Comment by Joel1971** [comment]
so, my english is bad.

but you understand

tanks, your help

**Comment by Yenthe666** [comment]
Hi @Joel1971,

The Github.com issue tracker is only for bugs and issues in the official code though. You should try to reach out to the developer of that module in order to get help. 
The developer has a problem with the importing of folders and files. 

Regards,
Yenthe
