### ISSUE TITLE
Error after upgrading via apt

### ISSUE THREAD

**Issue by dudeunix67** [odoo/odoo#23297]
Impacted versions: 11.0.20180222 CRM

Upgraded via apt to version listed above.

Steps to reproduce:
1) Login to our odoo instance.
2) Click on CRM module
3) Click on Sales Channel.
4) Window opens showing pipeline button and ## Open Opportunities.  Click on either one and following error.
++++++++++++++++++++++++++++++
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 936, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f99480b7940>, 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 872, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 894, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4156, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2535, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4675, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 943, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f99480b7940>, 10)
+++++++++++++++++++++++
Current behavior:  

Get odoo server error pop up window

Expected behavior:

It should take me to a list of my current opportunities.

Video/Screenshot link (optional):

**Comment by dudeunix67** [comment]
Here is the pre and post version as well
odoo:amd64 (11.0.20171119, 11.0.20180222)

**Comment by SnakeO** [comment]
I get a similar error:

2018-02-25 03:02:50,716 25975 INFO webdb werkzeug: 127.0.0.1 - - [25/Feb/2018 03:02:50] "POST /longpolling/poll HTTP/1.0" 200 -
2018-02-25 03:03:07,136 25980 DEBUG webdb odoo.modules.registry: Multiprocess signaling check: [Registry - 8 -> 8] [Cache - 198 -> 198]
2018-02-25 03:03:07,139 25980 ERROR webdb odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

**Comment by SnakeO** [comment]
Quick update -- this solution worked for me: https://stackoverflow.com/questions/38672884/exceptionbus-bus-unavailable-in-odoo#41591214

**Comment by dudeunix67** [comment]
The error calls out a SQL issue and not a bus issue. I already have that set in the webservers config.

**Comment by dudeunix67** [comment]
I digging a bit further I did find this in the log file at startup after the upgrade.  I might have spoken too soon.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/models/bus.py", line 167, in loop
    conn.poll()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/models/bus.py", line 181, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/models/bus.py", line 176, in loop
    event.set()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 404, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 288, in close
    return self._close(False)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 318, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
+++++++++++++++++++++++++

**Comment by Yenthe666** [comment]
Hey guys,

I've just tried to reproduce this on the latest 11.0 and it seems to work fine. Can you update and try again?

**Comment by Yenthe666** [comment]
On a sidenote.. I have a V11 customer that is having loads of these `psycopg2` errors right now too. Example when taking a backup:
```
2018-02-27 08:50:03,572 23223 ERROR my_db werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 267, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 255, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1304, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1278, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 609, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1472, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo/http.py", line 279, in __exit__
    self._cr.commit()
  File "/opt/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 375, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed
```

Not sure if it is related.

**Comment by dudeunix67** [comment]
It might be related. After going back to our original version a new issue cropped up.  If you try to access general settings, it throws the following error in the /var/log/odod/odoo-server.log

+++++
2018-02-27 18:13:39,921 466 INFO odoo odoo.addons.base.ir.ir_ui_view: Field `project_time_mode_id` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
2018-02-27 18:13:39,922 466 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1230, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1230, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_config.py", line 391, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1316, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 919, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 489, in raise_view_error
    raise ValueError(message)
ValueError: Field `project_time_mode_id` does not exist

+++++++++++++++++++

Based on this my guess is that the DB somehow did get modify on the upgrade and we are now missing a db entry somewhere.   I will try going to the latest one tonight after the staff leaves.

**Comment by dudeunix67** [comment]
Alright.  I update to the latest version and now the setting errors goes away with the dropped view.  But I am back to my original issue.  

Here is the current output straight from the odoo-server.log file:
++++++++++++++++
2018-02-28 03:06:29,514 31355 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 936, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7622d2ba90>, 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 872, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 894, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4156, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2535, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4675, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 943, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7622d2ba90>, 10)
+++++++++++++++++

**Comment by ilmir-k** [comment]
@Yenthe666 
I've reproduced this error only when used incorrect master password for duplication or removing DB. Otherwise I haven't such problem. Maybe this info could help anyone

```
2018-02-27 08:50:03,572 23223 ERROR my_db werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 267, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 255, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1304, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1278, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 609, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1472, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo/http.py", line 279, in __exit__
    self._cr.commit()
  File "/opt/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 375, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed
```

**Comment by dudeunix67** [comment]
No results in chasing this one down.  I am going to close this issue.
