### ISSUE TITLE
latest 11.0 pull error when creating 2nd company 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23308]
edit: a better approach to fix the problem i will try to have the same setup like the first time 

steps
1 set up new db  in spanish for spain 
2 make a 2nd company 
3 go to install sale_management

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/odoo-server/addons/mail/models/mail_message.py", line 735, in create
    values['email_from'] = self._get_default_from()
  File "/home/odoo/odoo-server/addons/mail/models/mail_message.py", line 30, in _get_default_from
    return formataddr((self.env.user.name, self.env.user.email))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u0103' in position 6: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-43>", line 2, in button_immediate_install
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/odoo/odoo-server/addons/mail/models/mail_message.py", line 735, in create
    values['email_from'] = self._get_default_from()
  File "/home/odoo/odoo-server/addons/mail/models/mail_message.py", line 30, in _get_default_from
    return formataddr((self.env.user.name, self.env.user.email))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
odoo.tools.convert.ParseError: "ascii
admin@ărcaș.com
6
7
ordinal not in range(128)" while parsing /home/odoo/odoo-server/addons/mail/data/mail_channel_data.xml:12, near
<record model="mail.message" id="module_install_notification" context="{'mail_notify_noemail': True}">
            <field name="model">mail.channel</field>
            <field name="res_id" ref="mail.channel_all_employees"/>
            <field name="message_type">email</field>
            <field name="subtype_id" ref="mail.mt_comment"/>
            <field name="subject">Welcome to Odoo!</field>
            <field name="body">&lt;p&gt;Welcome to the #general channel.&lt;/p&gt;
            &lt;p&gt;This channel is accessible to all users to &lt;b&gt;easily share company information&lt;/b&gt;.&lt;/p&gt;</field>
        </record>
```

![image](https://user-images.githubusercontent.com/17784575/36642337-6b260b9e-1a3e-11e8-8b21-1563e07c27c7.png)

edit2 this dont have anything t do with 2nd company is with admin email if using international domain name

**Comment by sswapnesh** [comment]
Hello @icf20 
I just tested it on Runbot and I can create new Company without any Issue.
Runbot link: [http://305741-11-0-a4e05f.runbot9.odoo.com/web/login](http://305741-11-0-a4e05f.runbot9.odoo.com/web/login)

**Comment by icf20** [comment]
@sswapnesh that runbot is not a clean install, i will try to replicate this again ( i removed that db) and note the order of the modules installed in order to replicate this better

**Comment by sswapnesh** [comment]
Will be great If you can mention module installation sequence.
