### ISSUE TITLE
Leave Management : Crash when change holiday_type to "By Employee Tag"

### ISSUE THREAD

**Issue by Harvys789** [odoo/odoo#23345]
**Impacted versions:**
Odoo 11.0 (Community Edition)

**Steps to reproduce:**
Install Leave Management 
Create a new leave allocation
Try to change the field Mode (holiday_type) from "By Employee" to "By Employee Tag"

**Current behavior:**
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/admin/Workspace/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/admin/Workspace/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/Users/admin/Workspace/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/Users/admin/Workspace/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/admin/Workspace/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/admin/Workspace/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/admin/Workspace/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/admin/Workspace/odoo/odoo/models.py", line 5011, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/Users/admin/Workspace/odoo/odoo/models.py", line 4907, in _onchange_eval
    method_res = method(self)
  File "/Users/admin/Workspace/odoo/addons/hr_holidays/models/hr_holidays.py", line 219, in _onchange_employee_id
    self.department_id = self.employee_id and self.employee_id.department_id
  File "/Users/admin/Workspace/odoo/odoo/fields.py", line 958, in __set__
    value = self.convert_to_cache(value, record)
  File "/Users/admin/Workspace/odoo/odoo/fields.py", line 1971, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for hr.holidays.department_id: hr.employee()

**Expected behavior:**

**Video/Screenshot link (optional):**

**Comment by sswapnesh** [comment]
I can confirm this bug.
![](https://image.prntscr.com/image/fvR_CxxTRDugKEtTDeom7g.png)

![](https://image.prntscr.com/image/9DdRTySIRZmayfx36sbbrQ.png)
Introduced at Commit 825180867a993a2b9241600a09cb8a581dc8b156

**Comment by Yenthe666** [comment]
@tbe-odoo can you check please? This might be introduced by your commit.

**Comment by Yenthe666** [comment]
Yep, just stumbled into it too. I made a ticket, OPW 1820069.
