### ISSUE TITLE
odoo 11website

### ISSUE THREAD

**Issue by almustafago** [odoo/odoo#23371]
Impacted versions:odoo 11

Steps to reproduce: when i disable automatic footer in website i get this internal error server

Current behavior:
HOME
BACK
500: Internal Server Error
Error
Error message:

None
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fe999126d08>, 'website.layout', ('en_US', True, None, None, False, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View._read_template at 0x7fe9993570d0>, frozenset({1, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 32, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 46, 50, 51, 72, 73, 74, 75, 76, 77, 78, 79, 82, 83, 84, 85, 86, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126}), 617, ('en_US', True, None, None, False, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_qweb/qweb.py", line 367, in get_template
    document = options.get('load', self.load)(template, options)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 1053, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-28>", line 2, in _read_template
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 1044, in _read_template
    arch = self.browse(view_id).read_combined(['arch'])['arch']
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 667, in apply_view_inheritance
    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//*[@id='products']">' cannot be located in parent view

Error context:
View `Link to frontend portal`
[view_id: 2483, xml_id: affiliate_management.my_account_link, model: n/a, parent_id: 617]

load could not load template
Template: website.layout
Traceback

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @almustafago,

Thanks a lot for your bug report.
I see your Odoo is from 2017-12-18 - can you please update it to the latest code?
I just tried to reproduce this on the latest Odoo 11.0 and it works fine there.

**Comment by almustafago** [comment]
ok, this error also face me in upadatble  version of odoo 11 , also that happend when i disable automatic footer , now i have 2 databse the first one(mwasm) cotain this error and the second one(mwasm_test) with no error
![d1](https://user-images.githubusercontent.com/15360515/36784433-62201ac2-1c90-11e8-8f86-e3aca67bf38a.PNG)
![d2](https://user-images.githubusercontent.com/15360515/36784435-6257d8a4-1c90-11e8-9d69-be29a059ffb0.PNG)

**Comment by almustafago** [comment]
thank you alot , i opserve taht for our model9affiliate) and now we must fix it

**Comment by JKE-be** [comment]
Not related to Odoo but module affiliate_management

**Comment by Kirankumar-hk** [comment]
File "D:\odoo 13\odoo-13.0\odoo\tools\cache.py", line 85, in lookup

    r = d[key]

  File "D:\odoo 13\odoo-13.0\odoo\tools\func.py", line 69, in wrapper

    return func(self, *args, **kwargs)

  File "D:\odoo 13\odoo-13.0\odoo\tools\lru.py", line 44, in __getitem__

    a = self.d[obj].me

KeyError: ('ir.qweb', <function IrQWeb.compile at 0x049132B0>, 219, (None, None, None, None, None, None))



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 315, in compile

    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)

ValueError: Name node can't be used with 'None' constant



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\tools\safe_eval.py", line 351, in safe_eval

    return unsafe_eval(c, globals_dict, locals_dict)

  File "", line 1, in <module>

  File "d:\odoo 13\odoo-13.0\addons\web\models\models.py", line 390, in _get_asset_style_b64

    company_styles = template_style.render({

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 1185, in render

    return self.env[engine].render(self.id, qcontext)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 58, in render

    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 260, in render

    self.compile(template, options)(self, body.append, values or {})

  File "<decorator-gen-54>", line 2, in compile

  File "D:\odoo 13\odoo-13.0\odoo\tools\cache.py", line 90, in lookup

    value = d[key] = self.method(*args, **kwargs)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 113, in compile

    return super(IrQWeb, self).compile(id_or_xml_id, options=options)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 323, in compile

    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)

odoo.addons.base.models.qweb.QWebException: Name node can't be used with 'None' constant

Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\tools\cache.py", line 85, in lookup

    r = d[key]

  File "D:\odoo 13\odoo-13.0\odoo\tools\func.py", line 69, in wrapper

    return func(self, *args, **kwargs)

  File "D:\odoo 13\odoo-13.0\odoo\tools\lru.py", line 44, in __getitem__

    a = self.d[obj].me

KeyError: ('ir.qweb', <function IrQWeb.compile at 0x049132B0>, 219, (None, None, None, None, None, None))



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 315, in compile

    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)

ValueError: Name node can't be used with 'None' constant



Error when compiling AST

ValueError: Name node can't be used with 'None' constant

Template: web.styles_company_report

Path: /t/t/t[10]

Node: <t t-elif="layout == 'web.external_layout_standard'">

                &amp;.o_report_layout_standard {

                    h2 {

                        color: <t t-esc="primary"/>;

                    }

                    #informations strong {

                        color: <t t-esc="secondary"/>;

                    }

                    #total strong{

                        color: <t t-esc="primary"/>;

                    }

                    table {

                        thead {

                            color: <t t-esc="secondary"/>;

                        }

                    }

                }

            </t>

            }

        



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 712, in parse

    self._tag_root(de)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root

    f(rec)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root

    f(rec)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 563, in _tag_record

    f_val = _eval_xml(self, field, env)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 117, in _eval_xml

    return safe_eval(a_eval, idref2)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 32, in <lambda>

    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)

  File "D:\odoo 13\odoo-13.0\odoo\tools\safe_eval.py", line 374, in safe_eval

    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])

  File "D:\odoo 13\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise

    raise value.with_traceback(tb)

  File "D:\odoo 13\odoo-13.0\odoo\tools\safe_eval.py", line 351, in safe_eval

    return unsafe_eval(c, globals_dict, locals_dict)

  File "", line 1, in <module>

  File "d:\odoo 13\odoo-13.0\addons\web\models\models.py", line 390, in _get_asset_style_b64

    company_styles = template_style.render({

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 1185, in render

    return self.env[engine].render(self.id, qcontext)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 58, in render

    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 260, in render

    self.compile(template, options)(self, body.append, values or {})

  File "<decorator-gen-54>", line 2, in compile

  File "D:\odoo 13\odoo-13.0\odoo\tools\cache.py", line 90, in lookup

    value = d[key] = self.method(*args, **kwargs)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 113, in compile

    return super(IrQWeb, self).compile(id_or_xml_id, options=options)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 323, in compile

    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)

ValueError: <class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating

'obj()._get_asset_style_b64()'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\odoo 13\odoo-13.0\odoo\service\db.py", line 62, in _initialize_db

    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)

  File "D:\odoo 13\odoo-13.0\odoo\modules\registry.py", line 86, in new

    odoo.modules.load_modules(registry._db, force_demo, status, update_module)

  File "D:\odoo 13\odoo-13.0\odoo\modules\loading.py", line 421, in load_modules

    processed_modules += load_marked_modules(cr, graph,

  File "D:\odoo 13\odoo-13.0\odoo\modules\loading.py", line 313, in load_marked_modules

    loaded, processed = load_module_graph(

  File "D:\odoo 13\odoo-13.0\odoo\modules\loading.py", line 225, in load_module_graph

    load_data(cr, idref, mode, kind='data', package=package, report=report)

  File "D:\odoo 13\odoo-13.0\odoo\modules\loading.py", line 68, in load_data

    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 736, in convert_file

    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 803, in convert_xml_import

    obj.parse(doc.getroot())

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 715, in parse

    pycompat.reraise(

  File "D:\odoo 13\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise

    raise value.with_traceback(tb)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 712, in parse

    self._tag_root(de)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root

    f(rec)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root

    f(rec)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 563, in _tag_record

    f_val = _eval_xml(self, field, env)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 117, in _eval_xml

    return safe_eval(a_eval, idref2)

  File "D:\odoo 13\odoo-13.0\odoo\tools\convert.py", line 32, in <lambda>

    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)

  File "D:\odoo 13\odoo-13.0\odoo\tools\safe_eval.py", line 374, in safe_eval

    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])

  File "D:\odoo 13\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise

    raise value.with_traceback(tb)

  File "D:\odoo 13\odoo-13.0\odoo\tools\safe_eval.py", line 351, in safe_eval

    return unsafe_eval(c, globals_dict, locals_dict)

  File "", line 1, in <module>

  File "d:\odoo 13\odoo-13.0\addons\web\models\models.py", line 390, in _get_asset_style_b64

    company_styles = template_style.render({

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 1185, in render

    return self.env[engine].render(self.id, qcontext)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 58, in render

    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 260, in render

    self.compile(template, options)(self, body.append, values or {})

  File "<decorator-gen-54>", line 2, in compile

  File "D:\odoo 13\odoo-13.0\odoo\tools\cache.py", line 90, in lookup

    value = d[key] = self.method(*args, **kwargs)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\ir_qweb.py", line 113, in compile

    return super(IrQWeb, self).compile(id_or_xml_id, options=options)

  File "D:\odoo 13\odoo-13.0\odoo\addons\base\models\qweb.py", line 323, in compile

    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)

odoo.tools.convert.ParseError: "<class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating

'obj()._get_asset_style_b64()'" while parsing file:/d:/odoo%2013/odoo-13.0/addons/web/data/report_layout.xml:2, near

and the odoo 13 code i have downloaded from the github, please can you help me 
why i am getting this error i have imported all modules required and while running server getting error as above

**Comment by JKE-be** [comment]
thanks @Kirankumar-hk 

Please don't hack closed issue because there are one word in common.

https://docs.python.org/3/reference/datamodel.html#object.__getitem__
