### ISSUE TITLE
[Odoo 11] New Installation 1st March 2018 problem

### ISSUE THREAD

**Issue by arafatx** [odoo/odoo#23401]
Can anyone explain about this problem? I just run a new installation (as today 1st March 2018) and when I create new database, I got the following error: 

New fresh installation from github with new database.

Please give a hint about this error

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 164, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1304, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1278, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1468, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 767, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 826, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 335, in checked_call
    result.flatten()
  File "/opt/odoo/odoo/http.py", line 1255, in flatten
    self.response.append(self.render())
  File "/opt/odoo/odoo/http.py", line 1248, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1158, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1065, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1325, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup

  File "/opt/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.login

and sometimes I got this error: Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

**Comment by arafatx** [comment]
Found the problem: Everytime if I need to create a new database, I need to log out as the current user. Or in another word, clear the browser cache!

**Comment by jovin2** [comment]
If you need more with`[ odoo customization](https://www.confianzit.com/openerp-customization)` and installation visit https://www.confianzit.com

**Comment by arafatx** [comment]
Today I tried again creating new database and it works. I didn't make any changes to the codes no git fetch or pull etc..  definitely a random bug.

**Comment by arafatx** [comment]
After few months keep having the same problem. Finally this was the issue:

https://github.com/odoo/odoo/issues/22985

**Comment by Yenthe666** [comment]
Then please don't reopen the bug report if it is fixed. Happy that you've solved it.

**Comment by arafatx** [comment]
Actually, I know the reason why running ./odoo-bin -d odoo works but running with the custom configuration doesn't work. The reason is that I forgot to put the addons path for /odoo/odoo/addons. There are 2 addons path. Hope this help others.

TQ

**Comment by andech** [comment]
In my case all paths (I have three paths) will be added to the config file, but it doesn't take effect. And it works only with new database.

**Comment by Yenthe666** [comment]
@arafatx haha happy to hear that you've got excited though! 😉 
@andech that means you've got some misconfigurations in your deployment

**Comment by janarthanandev** [comment]
If anyone facing this issue consider upgrading your postgres version. its solved for my case.

**Comment by Dester05** [comment]
change the version of your postgresql database to a higher version (9.6 up) and reinstall Odoo
