### ISSUE TITLE
install  "Project" app Error: Failed to render template

### ISSUE THREAD

**Issue by chulaihunde** [odoo/odoo#23430]
mpacted versions:
11 community & enterprise

Steps to reproduce:

install  "Project" app

database language： Chinese

错误:
Odoo Server Error
```
Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
KeyError: 'body'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/long/odoo_py3/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/long/odoo_py3/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
odoo.tools.convert.ParseError: "body" while parsing /home/long/odoo_py3/odoo/addons/project/data/project_demo.xml:123, near
<record id="project_task_1" model="project.task">
            <field name="planned_hours" eval="40.0"/>
            <field name="remaining_hours" eval="40.0"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_1"/>
            <field name="name">Prepare Requirements Document</field>
            <field name="stage_id" ref="project_stage_0"/>
            <field name="color">3</field>
        </record>

==========================================================================

2018-03-02 12:37:08,952 24710 INFO odooDB odoo.addons.mail.models.mail_template: Failed to load template '\n% 设置公司 = ctx.get(\'company\', user.company_id)\n\n% if <div>ctx.get(\'has_button_access\'):\n\n \n \\<div itemscope itemtype="http://schema.org/EmailMessage">n \\<div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">n \\<link itemprop="target" href="${ctx[\'button_access\'][\'url\']}"/>n \\<link itemprop="url" href="${ctx[\'button_access\'][\'url\']}"/>n\n<meta itemprop="name" content="View ${ctx[\'model_name\']}"/>% e</div>nd</div>if\n% if not ctx[\'is_discussion\'] or not len(ctx[\'actions\']) == 0 or ctx.get(\'has_button_access\'):\n\n\n\n <div summary="o_mail_notification" style="padding: 0px; width:600px;">\n<table cellspacing="0" cellpadding="0" border="0" style="width: 600px; margin-top: 5px;"> %<tbody><tr> if<td valign="center"> ctx.get(\'has_button_access\'):\n ${ctx[\'<a href="${ctx[\'button_access\'][\'url\']}" style="padding: 8px 12px; font-size: 12px; color: #FFFFFF; text-decoration: none !important; font-weight: 400; background-color: #875A7B; border: 0px solid #875A7B; border-radius:3px">button_access\'][\'title\']}\n % en</a>dif\n\n % if ctx.get(\'has_button_follow\'):\n % if ctx.get(\'has_button_access\'):\n |\n % endif\n ${ctx[\'<a href="${ctx[\'button_follow\'][\'url\']}" style="color: #875A7B; text-decoration: none !important;">button_follow\'][\'title\']}\n % el</a>if ctx.get(\'has_button_unfollow\'):\n % if ctx.get(\'has_button_access\'):\n |\n % endif\n ${ctx[\'<a href="${ctx[\'button_unfollow\'][\'url\']}" style="color: #875A7B; text-decoration: none !important;">button_unfollow\'][\'title\']}\n % en</a>dif\n\n % if ctx.get(\'actions\'):\n % for action in ctx[\'actions\']:\n |\n ${actio<a href="${action[\'url\']}" style="color: #875A7B; text-decoration:none !important;">n[\'title\']}\n % en</a>dfor\n % endif\n \n \n \\</td>n \\<td valign="center" align="right">n\n<img src="/logo.png?company=${company.id}" style="padding: 0px; margin: 0px; height: auto; max-width: 80px; max-height: 40px;" alt="${company.name}">\n </td>\n</tr> \\<tr>n %<td colspan="2" style="text-align:center;"> if<hr width="100%"\n style="background-color:rgb(204,204,204);border:medium none;clear:both;display:block;font-size:0px;min-height:1px;line-height:0; margin:10px 0;"> ctx.get(\'subtype\') and ctx.get(\'subtype\').internal:\n \n内部通信：<p style="background-color: #f2dede; padding: 5px; margin-bottom: 16px;">答复将<strong>发布内部说明。部下将不会收到任何电子邮件通知</strong>。\n \n % endif\n \n\n\n\n% endif\n\n ${object.body | safe}\n\n% if ctx.get(\'tracking\'):\n</p>\n % 用于追踪 ctx</td>[\'</tr>tr</tbody></table>ac</div>king\']\n ${<div>tracking[0]} : ${tracking[</div>1]} -&gt; ${tracking[2]}\n % e<ul>ndfor\n \n% endif\n\n% if ctx.get（“签名”）：\n ${ctx[\'signature\'] | safe}\n% endif\n \n\n 由谁发送 \n % if ctx.get(\'website_url\'):\n \n % endif\n ${ctx.get(\'company_name\')}\n % if ctx.get(\'website_url\'):\n \n % endif\n 使用 \n Odoo.\n\n<li></li></ul><br/><p style="color: #555555;"><a href="${ctx[\'website_url\']}" style="text-decoration:none; color: #875A7B;"></a><a target="_blank" href="https://www.odoo.com" style="text-decoration:none; color: #875A7B;"></a></p></div>'
Traceback (most recent call last):
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_template.py", line 351, in render_template
    template = mako_env.from_string(tools.ustr(template_txt))
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 2, in template
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 135, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 88, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 81, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 50, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag '设置公司'.
2018-03-02 12:37:08,953 24710 INFO odooDB odoo.addons.mail.models.mail_template: Failed to load template "${object.subject 或 (object.record_name 和 'Re: %s' % object.record_name) 或 (object.parent_id and object.parent_id.subject 和 'Re: %s' % object.parent_id.subject) 或 (object.parent_id 和 object.parent_id.record_name 和 'Re: %s' % object.parent_id.record_name)}"
Traceback (most recent call last):
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_template.py", line 351, in render_template
    template = mako_env.from_string(tools.ustr(template_txt))
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/parser.py", line 872, in subparse
    self.stream.expect('variable_end')
  File "/home/long/odoo_py3/lib/python3.6/site-packages/jinja2/lexer.py", line 374, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '或'
2018-03-02 12:37:08,955 24710 WARNING odooDB odoo.modules.loading: Transient module states were reset
2018-03-02 12:37:08,979 24710 ERROR odooDB odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
KeyError: 'body'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
odoo.tools.convert.ParseError: "body" while parsing /home/long/odoo_py3/odoo/addons/project/data/project_demo.xml:123, near
<record id="project_task_1" model="project.task">
            <field name="planned_hours" eval="40.0"/>
            <field name="remaining_hours" eval="40.0"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_1"/>
            <field name="name">Prepare Requirements Document</field>
            <field name="stage_id" ref="project_stage_0"/>
            <field name="color">3</field>
        </record>
2018-03-02 12:37:08,981 24710 ERROR odooDB odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
KeyError: 'body'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/long/odoo_py3/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/long/odoo_py3/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/long/.local/share/Trash/files/odoo.2/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/long/odoo_py3/odoo/addons/project/models/project.py", line 651, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 254, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 502, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/home/long/odoo_py3/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_thread.py", line 1896, in message_post
    new_message = MailMessage.create(values)
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 776, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/home/long/odoo_py3/odoo/addons/mail/models/mail_message.py", line 861, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/home/long/odoo_py3/odoo/addons/mail/models/res_partner.py", line 190, in _notify
    new_emails, new_recipients_nbr = self._notify_send(fol_values['body'], fol_values['subject'], recipient_template_values['followers'], **base_mail_values)
odoo.tools.convert.ParseError: "body" while parsing /home/long/odoo_py3/odoo/addons/project/data/project_demo.xml:123, near
<record id="project_task_1" model="project.task">
            <field name="planned_hours" eval="40.0"/>
            <field name="remaining_hours" eval="40.0"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_1"/>
            <field name="name">Prepare Requirements Document</field>
            <field name="stage_id" ref="project_stage_0"/>
            <field name="color">3</field>
        </record>
2018-03-02 12:37:08,985 24710 INFO odooDB odoo.modules.loading: loading 1 modules...
```

**Comment by mart-e** [comment]
Hello,

I believe most of the wrong translation was already fixed.
I have fixed the remaining one at f51d213f43e (you need to reload the translations to do so).
Please let me know if you have other issue and how to reproduce it
