### ISSUE TITLE
[11.0] Could not uninstall Invoicing module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23446]
Impacted versions: 11.0

Steps to reproduce: Uninstall Invoicing (account) module (Sale module was installed)

Current behavior:
![](https://image.prntscr.com/image/f5z7zpDnRkW2BfN6AyiHBA.png)
Traceback (most recent call last):
```
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/loading.py", line 403, in load_modules
    cr.commit()
  File "/home/swapnesh/Workspace/11_odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/sql_db.py", line 377, in commit
    func()
  File "<string>", line 19, in update_dashboard_graph_model
  File "/home/swapnesh/Workspace/11_odoo/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/registry.py", line 181, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice.report'
2018-03-03 18:31:16,468 22621 ERROR github_sale odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/swapnesh/Workspace/11_odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/swapnesh/Workspace/11_odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/swapnesh/Workspace/11_odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/swapnesh/Workspace/11_odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/addons/base/module/wizard/base_module_uninstall.py", line 55, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-43>", line 2, in button_immediate_uninstall
  File "/home/swapnesh/Workspace/11_odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/addons/base/module/module.py", line 566, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/home/swapnesh/Workspace/11_odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/loading.py", line 403, in load_modules
    cr.commit()
  File "/home/swapnesh/Workspace/11_odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/11_odoo/odoo/sql_db.py", line 377, in commit
    func()
  File "<string>", line 19, in update_dashboard_graph_model
  File "/home/swapnesh/Workspace/11_odoo/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/swapnesh/Workspace/11_odoo/odoo/modules/registry.py", line 181, in __getitem__
    return self.models[model_name]
KeyError: 'account.invoice.report'

```
Expected behavior:
Should be Uninstalled
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Related Issue #23270 and PR #23286

**Comment by sswapnesh** [comment]
Hello @Elkasitu, I am facing these kind of Issues again. (Related to module Uninstallation). Should I Create separate issue for them or Add description here?

**Comment by Elkasitu** [comment]
@sswapnesh Hi, if it's related (or you think it is) to this particular issue then you can post it here I guess, otherwise making new issues is fine.
