### ISSUE TITLE
(code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by hengsoheak** [odoo/odoo#23493]
I installed Odoo10 on Ubuntu16 last week it work well many day but now I can not start service 

Impacted versions:10
OS: Ubuntu16.4
Steps to reproduce:
Current behavior: Testing projectsExpected behavior: POS=>Report=>order

`Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1931, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/models.py", line 2036, in _read_group_raw
    result = [self._read_group_format_result(d, annotated_groupbys, groupby, domain) for d in data]
  File "/opt/odoo/odoo/models.py", line 1876, in _read_group_format_result
    tzinfo=tzinfo, locale=locale
  File "/usr/local/lib/python2.7/dist-packages/babel/dates.py", line 716, in format_datetime
    locale = Locale.parse(locale)
  File "/usr/local/lib/python2.7/dist-packages/babel/core.py", line 333, in parse
    raise UnknownLocaleError(input_id)
UnknownLocaleError: unknown locale u'km_KM'

`

**Comment by hazemomr** [comment]
i have same problem ... any help plzzzzzzzzz

**Comment by Yenthe666** [comment]
Dear @hengsoheak,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
