### ISSUE TITLE
[odoo11] backup error

### ISSUE THREAD

**Issue by dataorz** [odoo/odoo#23543]
```
2018-03-08 09:14:19,054 1 ERROR hr-data odoo.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 735, in backup
    dump_stream = odoo.service.db.dump_db(name, None, backup_format)
  File "<decorator-gen-8>", line 2, in dump_db
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 216, in dump_db
    odoo.tools.exec_pg_command(*cmd)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 128, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpjywzgb35/dump.sql', 'hr-data') error 1
2018-03-08 09:14:19,106 1 INFO hr-data odoo.sql_db: ConnectionPool(used=1/count=1/max=64): Closed 2 connections to 'dbname=hr-data user=odoo password=xxxx host=172.17.0.3 port=5432 sslmode=prefer'
2018-03-08 09:14:19,111 1 INFO hr-data werkzeug: 123.234.57.219 - - [08/Mar/2018 09:14:19] "POST /web/database/backup HTTP/1.1" 500 -
2018-03-08 09:14:19,114 1 ERROR hr-data werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1466, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 279, in __exit__
    self._cr.commit()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 375, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed

```

**Comment by dataorz** [comment]
i have excuted the sqls below. it does not worked. 
GRANT ALL PRIVILEGES ON SCHEMA schema_name TO role_name; 
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA schema_name TO role_name; 
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA schema_name TO role_name;

**Comment by mart-e** [comment]
Hello,

If you believe this is a bug in Odoo, please explain clearly how we can reproduce this issue. Here you do not give much info.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by CasVissers** [comment]
This seems like a postgres mismatch to me. Are you trying to run a back-up from a machine which is running an older postgres version? (most likely 9.x  and 10)

**Comment by jameshickman** [comment]
Same problem and error in log. Just updated from the repo (apt-get update, upgrade and rebooted). On Ubuntu 16.04 in AWS EC2, Postgres 9.5.12.
