### ISSUE TITLE
Error While fetching mail from IMAP server

### ISSUE THREAD

**Issue by vivekp-ept** [odoo/odoo#23575]
Impacted versions: 10.0 Enterprise

Steps to reproduce: Don't Know. Might be because of email content

Current behaviour: Getting error

Traceback (most recent call last):
```
 File "/usr/lib/python2.7/dist-packages/odoo/addons/fetchmail/models/fetchmail.py", line 179, in fetch_mail
 res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
 File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1269, in message_process
 msg = self.message_parse(msg_txt, save_original=save_original)
 File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1543, in message_parse
 msg_dict['body'], msg_dict['attachments'] = self._message_extract_payload(message, save_original=save_original)
 File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1455, in _message_extract_payload
 body, attachments = self._message_extract_payload_postprocess(message, body, attachments)
 File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1361, in _message_extract_payload_postprocess
 root = lxml.html.fromstring(body)
 File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 867, in fromstring
 doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
 File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 752, in document_fromstring
 value = etree.fromstring(html, parser, **kw)
 File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
 File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124471)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

Expected behaviour: Email should be imported.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @vivekp-ept,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
