### ISSUE TITLE
[8.0] issue account_asset

### ISSUE THREAD

**Issue by ibonejuaristi** [odoo/odoo#2361]
When pressing the button "change duration" of a confirmed asset, I obtain the following traceback:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 379, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 398, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 235, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-3/openerp/service/model.py", line 114, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 232, in checked_call
    return self.func(*a, **kw)
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 562, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/saas-3/addons/web/controllers/main.py", line 1537, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/home/odoo/src/odoo/saas-3/openerp/http.py", line 649, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoo/src/odoo/saas-3/openerp/addons/base/ir/ir_actions.py", line 294, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/odoo/src/odoo/saas-3/openerp/osv/orm.py", line 3320, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/home/odoo/src/odoo/saas-3/openerp/osv/orm.py", line 3443, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/home/odoo/src/odoo/saas-3/openerp/osv/fields.py", line 1229, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/odoo/src/odoo/saas-3/openerp/addons/base/ir/ir_actions.py", line 235, in _search_view
    'search', context=context)
  File "/home/odoo/src/odoo/saas-3/addons/account_asset/wizard/account_asset_change_duration.py", line 59, in fields_view_get
    node = doc.xpath("//field[@name='method_end']")[0]
IndexError: list index out of range

**Comment by beledouxdenis** [comment]
Closed with fb4c8220009d167c594acb93816014c48bed6cb2.
