### ISSUE TITLE
[11.0] Marketing automation crashes when having multiple companies and when changing the source e-mail from a restricted user

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#23674]
Impacted versions: 11.0

Steps to reproduce:
**Tip: do this part with the administrator user!**
1. Create an environment with multiple companies and create a user with the following access rights:
![image](https://user-images.githubusercontent.com/6352350/37452533-2befdffe-2835-11e8-83c2-4b06fef655cb.png)
Make sure that you have multiple companies:
![image](https://user-images.githubusercontent.com/6352350/37452565-3f3f3ff0-2835-11e8-91a6-d1fdf57b9b36.png)
2. Create a new marketing campaign and give it a name, for example "123pallets.nl". Set the target model to "Contacts" and create a filter so that just some contacts are selected. For example, filter out anything with "asus" in the name.
3. Create a workflow on this marketing campaign that sends an e-mail 9 days after the beginning of the campagin and attach a newly created email template to it:
![image](https://user-images.githubusercontent.com/6352350/37452720-b9337718-2835-11e8-96c2-1f3f05f4a14e.png)
My example e-mail template looks like this:
![image](https://user-images.githubusercontent.com/6352350/37452742-cb6ab9dc-2835-11e8-95be-e2536a1c0c45.png)
Remember the "From" which contains "Administrator <admin@yourcompany.example.com>", the issue will come from this later on.

4. Switch to the other user ("Yenthe" in my example), go to the marketing campaign and click on the workflow item. Then open up the e-mail template and change the "From" address in this e-mail template.
![image](https://user-images.githubusercontent.com/6352350/37453066-d89fe022-2836-11e8-9030-1e2ce994a851.png)
![image](https://user-images.githubusercontent.com/6352350/37453104-f6a42db2-2836-11e8-9c6d-7974bd979db9.png)
Now click save twice.

5. Click on "Launch a test" and save this record. For example:
![image](https://user-images.githubusercontent.com/6352350/37452946-7b6074bc-2836-11e8-87d5-b9d7986f5663.png)
6. Now click on the play button to start the test:
![image](https://user-images.githubusercontent.com/6352350/37452980-9cb25d06-2836-11e8-9b59-acdec41e7e09.png)

7. Now behold, a traceback happens.

Current behavior:  A traceback, which actually has two issues! The first is that you have insufficient access rights:

> Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:\n- Website/Editor and Designer\n\n(Document model: link.tracker)

The second is that the encoding of the error is wrong because of `e.message`, which does not work well on Python 3.x.
![image](https://user-images.githubusercontent.com/6352350/37452915-5339de74-2836-11e8-9034-36bbbfac7b11.png)

Traceback (most recent call last):
```
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f088cfa7840>, 498, 'link.tracker', 'create', True, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/marketing_automation/models/marketing_campaign.py", line 519, in _execute_email
    mailing.send_mail(res_ids)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/mass_mailing/models/mass_mailing.py", line 675, in send_mail
    'body': mailing.convert_links()[mailing.id],
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/marketing_automation/models/mass_mailing.py", line 30, in convert_links
    blacklist=['/unsubscribe_from_list']
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/link_tracker/models/link_tracker.py", line 61, in convert_links
    link = self.create(vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/link_tracker/models/link_tracker.py", line 184, in create
    link = super(link_tracker, self).create(create_vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/models.py", line 3268, in create
    self.check_access_rights('create')
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/models.py", line 2796, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-20>", line 2, in check
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/base/ir/ir_model.py", line 1183, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ('Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:\n- Website/Editor and Designer\n\n(Document model: link.tracker)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/marketing_automation/models/marketing_participant.py", line 159, in action_execute
    self.activity_id.execute_on_traces(self)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/marketing_automation/models/marketing_campaign.py", line 466, in execute_on_traces
    activity_method(traces_allowed)
  File "/home/odoo/runbot/runbot/runbot/static/build/310284-11-0-ddc7a9/odoo/addons/marketing_automation/models/marketing_campaign.py", line 525, in _execute_email
    'state_msg': _('Exception in mass mailing: %s') % e.message,
AttributeError: 'AccessError' object has no attribute 'message'
```

Expected behavior: Changing the e-mail template "From" works fine or is not shown to the user with the limited access rights. Everything should continue fine.

Video/Screenshot link (optional):
https://youtu.be/JQ0qNHvjH3c

**Comment by Yenthe666** [comment]
This was fixed in https://github.com/odoo/enterprise/commit/d7061c1a2b65509277f8b8bb6db6ea0212eef339 and in https://github.com/odoo/enterprise/commit/3cd21e5c19785ef2606b5cf3ad1799b9ed9f2f30
