### ISSUE TITLE
value.format is not a function Why this error

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#23687]
Impacted versions: Odoo 11

Steps to reproduce:

Current behavior:

```
value.format is not a function
When copy a date string in date field or any date field value into another date field
```

Expected behavior: it was working fine in odoo 8 9 10

Video/Screenshot link (optional): Error:
# Uncaught TypeError: value.format is not a function

http://192.168.1.39:8069/web/static/src/js/fields/field_utils.js:118
Traceback:
TypeError: value.format is not a function
at Object.formatDate [as date] (http://192.168.1.39:8069/web/static/src/js/fields/field_utils.js:118:18)
at Class.renderBodyCell (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:289:60)
at http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:576:25
at Function..map._.collect (http://192.168.1.39:8069/web/static/lib/underscore/underscore.js:164:24)
at Class._renderRow [as _super] (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:575:24)
at Class.renderRow (http://192.168.1.39:8069/web/static/src/js/views/list/list_editable_renderer.js:499:32)
at Class.renderRow (http://192.168.1.39:8069/web/static/src/js/core/class.js:123:38)
at Function..map..collect (http://192.168.1.39:8069/web/static/lib/underscore/underscore.js:164:24)
at Class._renderRows (http://192.168.1.39:8069/web/static/src/js/views/list/list_renderer.js:597:18)
at Class._renderRows (http://192.168.1.39:8069/web/static/src/js/views/list/list_editable_renderer.js:515:26)

**Comment by Yenthe666** [comment]
Please don't create duplicated issues. Closing because of https://github.com/odoo/odoo/issues/23672

**Comment by sandeepksrana** [comment]
can you please ask someone to answer this one or we should change odoo backend for resolving this
