### ISSUE TITLE
Error when editing records with fields of a reference type

### ISSUE THREAD

**Issue by ChistIvan** [odoo/odoo#23701]
Impacted versions: 11.0-20180316 

Steps to reproduce: 

I have a tree view of my model with attribute `editable="bottom"`.
One field in this model have Reference type to 2 differnt models.
When I add new records everything is OK, but then I try to edit existing records
I get this error:

Ошибка:
Odoo Server Error

Traceback (most recent call last):
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4994, in onchange
    record.mapped(dotname)
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4442, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4423, in _mapped_func
    return vals[0].union(*vals)         # union of all recordsets
  File "c:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4623, in union
    raise TypeError("Mixing apples and oranges: %s.union(%s)" % (self, arg))
TypeError: Mixing apples and oranges: granite.slab(3615,).union(granite.crust(377,))

**Comment by Yenthe666** [comment]
Hi @ChistIvan,

This is actually not a bug in the Odoo core but in your custom development. Somewhere in your custom development you're trying to compare records from two models (the raw records) and this is failing.
Please ask for help on the official help forums at help.odoo.com and add your custom code in the question so that they can see what you did wrong.

Regards,
Yenthe
