### ISSUE TITLE
Odoo11 Issue loading image in web editor: "local variable 'res_id' referenced before assignment"

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#23738]
**Impacted versions:**
Odoo 11

**Steps to reproduce:**
1. clean installation of windows server 2012 R2 with all microsoft update
2. installation of all available VCRedist package
3. installation all odoo11 and postgresql
4. installation of e.commerce app
5. in the home page, in edit mode, insert a "cover block" try to upload an image and you will get the error "local variable 'res_id' referenced before assignment"

**Current behavior:**
I've a clean installation of odoo 11 on windows server 2012 r2, with just odoo and postgresql, and all vcredist.

After the install of e-commerce module, if I try to upload an image from local file system, I get the following error:

   local variable 'res_id' referenced before assignment

Looking in the log I can find the following:

_Traceback (most recent call last):

File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web_editor\controllers\main.py", line 191, in attach

#'res_id': res_id,

UnboundLocalError: local variable 'res_id' referenced before assignment

2018-03-18 13:39:27,252 1212 INFO odoo werkzeug: 127.0.0.1 - - [18/Mar/2018 13:39:27] "POST /web_editor/attachment/add HTTP/1.1" 200 -

2018-03-18 13:39:27,566 1212 ERROR odoo odoo.sql_db: bad query: b'SELECT res_model, res_id, create_uid, public FROM ir_attachment WHERE id IN ()'

ERROR: ERRORE: errore di sintassi a o presso ")"

LINE 1: ...res_id, create_uid, public FROM ir_attachment WHERE id IN ()

**Expected behavior:**
The user should be able tu upload the imabe from "Select Media" window to build the website

**Video/Screenshot link:**
![image](https://user-images.githubusercontent.com/37513316/37592248-647761bc-2b6e-11e8-929d-9428bfb46285.png)

**Comment by kimasplund** [comment]
I started to get the same today after git refresh. Running on Amazon aws ubuntu.

**Comment by kimasplund** [comment]
`2018-03-19 14:37:23,369 12775 ERROR www.servername.online odoo.addons.web_editor.controllers.main: Failed to upload image to attachment
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web_editor/controllers/main.py", line 191, in attach
    'res_id': res_id,
UnboundLocalError: local variable 'res_id' referenced before assignment
2018-03-19 14:37:23,373 12775 INFO www.servername.online werkzeug: 127.0.0.1 - - [19/Mar/2018 14:37:23] "POST /web_editor/attachment/add HTTP/1.0" 200 -
2018-03-19 14:37:23,491 12775 ERROR www.servername.online odoo.sql_db: bad query: b'SELECT res_model, res_id, create_uid, public FROM ir_attachment WHERE id IN ()'
ERROR: syntax error at or near ")"
LINE 1: ...res_id, create_uid, public FROM ir_attachment WHERE id IN ()
                                                                      ^

2018-03-19 14:37:23,491 12775 ERROR www.servername.online odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-29>", line 2, in generate_access_token
  File "/odoo/odoo-server/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 447, in generate_access_token
    self.write({'access_token': access_token})
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 405, in write
    self.check('write', values=vals)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 312, in check
    self._cr.execute('SELECT res_model, res_id, create_uid, public FROM ir_attachment WHERE id IN %s', [tuple(self.ids)])
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 1: ...res_id, create_uid, public FROM ir_attachment WHERE id IN ()
                                                                      ^

2018-03-19 14:37:23,493 12775 INFO www.servername.online werkzeug: 127.0.0.1 - - [19/Mar/2018 14:37:23] "POST /web/dataset/call_kw/ir.attachment/generate_access_token HTTP/1.0" 200 -
`

**Comment by mge-odoo** [comment]
@nim-odoo probably introduced in https://github.com/odoo/odoo/commit/4e507faaafdf5bd0a048106159663d01c820d866

**Comment by alaherma** [comment]
got the same problem here

**Comment by pedrobaeza** [comment]
Please update your code, as it's already solved.

**Comment by gibugeorge** [comment]
How to update in case of a live instance which is about to commision the website using odoo?
