### ISSUE TITLE
Odoo Database creation error: Access denied

### ISSUE THREAD

**Issue by etiennebonnafoux** [odoo/odoo#23750]
Hello everyone 😃 

Impacted versions:
V 11.0
Steps to reproduce:
I installed Odoo on Debian 6.3.0 following this step: https://www.getopenerp.com/install-odoo-11-on-ubuntu-16-04/

Current behavior:
When I want to create a new database a red indication appear :"Database creation error: Access denied"

And in the consol this error:

2018-03-19 16:29:45,993 11961 ERROR odoo odoo.sql_db: bad query: b"\n        SELECT c.relname\n          FROM pg_class c\n          JOIN pg_namespacen ON (n.oid = c.relnamespace)\n         WHERE c.relname IN ('ir_module_module')\n           AND c.relkind IN ('r', 'v', 'm')\n           AND n.nspname = 'public'\n    "
ERROR: 'ascii' codec can't encode character '\u20ac' in position 3789: ordinal not in range(128)
2018-03-19 16:29:45,994 11961 ERROR odoo odoo.sql_db: bad query: b"UPDATE ir_module_module SET state='installed' WHERE state IN ('to remove', 'to upgrade')"
ERROR: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
               ^

2018-03-19 16:29:45,994 11961 ERROR odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/root/opt/odoo/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/root/opt/odoo/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/root/opt/odoo/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/opt/odoo/odoo/odoo/modules/loading.py", line 260, in load_modules
    odoo.modules.db.initialize(cr)
  File "/root/opt/odoo/odoo/odoo/modules/db.py", line 32, in initialize
    cr.execute(base_sql_file.read())
  File "/root/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/root/opt/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 3789: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/opt/odoo/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.reset_modules_state(db_name)
  File "/root/opt/odoo/odoo/odoo/modules/loading.py", line 449, in reset_modules_state
    "UPDATE ir_module_module SET state='installed' WHERE state IN ('to remove', 'to upgrade')"
  File "/root/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/root/opt/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...

Has anyone a solution for me?
Thank you very much!

**Comment by etiennebonnafoux** [comment]
I already check the passeword in the server-odoo.conf and it's 'admin'

**Comment by relghazi** [comment]
Verify your right access to the filestore directory

**Comment by Yenthe666** [comment]
Since there hasn't been an update and 11.0 is end of life this can be closed off anyways. Sorry that nobody from Odoo got around to checking your case! Feel free to create a new ticket if you can reproduce it in V12/V13/V14.
