### ISSUE TITLE
Error "Sales Channel" - Unable to access the sales channel

### ISSUE THREAD

**Issue by thiago95macedo** [odoo/odoo#23835]
Impacted versions: 11.0
```
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adax-erp/adaxtechnology/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax-erp/adaxtechnology/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/adax-erp/adaxtechnology/core/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax-erp/adaxtechnology/core/addons/web/controllers/main.py", line 872, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/adax-erp/adaxtechnology/core/addons/web/controllers/main.py", line 894, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/adax-erp/adaxtechnology/core/odoo/models.py", line 4152, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/adax-erp/adaxtechnology/core/odoo/models.py", line 1422, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/adax-erp/adaxtechnology/core/odoo/models.py", line 3703, in _search
    query = self._where_calc(args)
  File "/opt/adax-erp/adaxtechnology/core/odoo/models.py", line 3498, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/adax-erp/adaxtechnology/core/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/opt/adax-erp/adaxtechnology/core/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'type_team' in leaf "<osv.ExtendedLeaf: ('type_team', '=', 'sale') on crm_team (ctx: )>"
```

**Comment by pedrobaeza** [comment]
Can you please try to reproduce the problem on runbot (http://runbot.odoo.com/runbot)? and please describe the steps followed to get that error.

**Comment by thiago95macedo** [comment]
Could not play through runbot.
The error happened after restoring my database in the current version of the core.

Is there any command that can do some adjustment in the database in relation to the core?

This is the only problem I noticed after reestablishing my database.

**Comment by pedrobaeza** [comment]
The problem is that you have a custom or community module in your DB that adds the field `type_team`, and now that module is not available, and thus the error. Restore that module in your new installation and should be OK.

**Comment by thiago95macedo** [comment]
Thanks, I was able to locate and resolve with your help.
