### ISSUE TITLE
Crash when open LDAP module to install it

### ISSUE THREAD

**Issue by Harvys789** [odoo/odoo#23900]
**Impacted versions:**
Odoo 11.0 (Community Edition)

**Steps to reproduce:**
Click on LDAP Module to install it

**Current behavior:**
Erreur:
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/username/Workspace/odoo/odoo/fields.py", line 936, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/username/Workspace/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x115145358>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Workspace/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/username/Workspace/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/username/Workspace/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/username/Workspace/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/Users/username/Workspace/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/username/Workspace/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/username/Workspace/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/username/Workspace/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/Users/username/Workspace/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/Users/username/Workspace/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/username/Workspace/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/username/Workspace/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/username/Workspace/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/username/Workspace/odoo/odoo/models.py", line 2535, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/Users/username/Workspace/odoo/odoo/models.py", line 4688, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Users/username/Workspace/odoo/odoo/fields.py", line 940, in __get__
    self.determine_value(record)
  File "/Users/username/Workspace/odoo/odoo/fields.py", line 1051, in determine_value
    self.compute_value(recs)
  File "/Users/username/Workspace/odoo/odoo/fields.py", line 1007, in compute_value
    self._compute_value(records)
  File "/Users/username/Workspace/odoo/odoo/fields.py", line 998, in _compute_value
    getattr(records, self.compute)()
  File "/Users/username/Workspace/odoo/odoo/addons/base/module/module.py", line 192, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2675, in indent
    definitionlistitem, blank_finish = self.definition_list_item(context)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2796, in definition_list_item
    self.nested_parse(indented, input_offset=line_offset, node=definition)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2371, in line
    line=self.state_machine.abs_line_number())
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/Users/username/.virtualenvs/odoo-test/lib/python3.6/site-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: <string>:34: (SEVERE/4) Unexpected section title or transition.

---------------------

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
AFAIK, official Odoo support is for Python 3.5, so please try with that version.

**Comment by Harvys789** [comment]
Clear all my python environnement and create new database, problem still exists

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/olivierbourrel/Workspace/odoo/odoo/fields.py", line 936, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x1145ebef0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/olivierbourrel/Workspace/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/Users/olivierbourrel/Workspace/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/models.py", line 2535, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/models.py", line 4688, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Users/olivierbourrel/Workspace/odoo/odoo/fields.py", line 940, in __get__
    self.determine_value(record)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/fields.py", line 1051, in determine_value
    self.compute_value(recs)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/fields.py", line 1007, in compute_value
    self._compute_value(records)
  File "/Users/olivierbourrel/Workspace/odoo/odoo/fields.py", line 998, in _compute_value
    getattr(records, self.compute)()
  File "/Users/olivierbourrel/Workspace/odoo/odoo/addons/base/module/module.py", line 192, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2675, in indent
    definitionlistitem, blank_finish = self.definition_list_item(context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2796, in definition_list_item
    self.nested_parse(indented, input_offset=line_offset, node=definition)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2371, in line
    line=self.state_machine.abs_line_number())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: <string>:34: (SEVERE/4) Unexpected section title or transition.

---------------------

**Comment by pedrobaeza** [comment]
OK, thanks for trying. Can you specify when this happens? Installing the module?

**Comment by Harvys789** [comment]
Just click on hidden module in the app list. Impossible to open the form of the module. **The others hidden modules work.**

![capture d ecran 2018-03-27 a 16 40 07](https://user-images.githubusercontent.com/36884331/37974584-9073be8a-31dd-11e8-8541-a2e217893ae0.png)

**Comment by Harvys789** [comment]
Ok, it works in English. Thank you
