### ISSUE TITLE
8.0 doesn't work with uwsgi in ubutnu 14.04

### ISSUE THREAD

**Issue by rainberg** [odoo/odoo#2391]
uwsgi log:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 2
16, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 2
02, in application_unproxied
    result = handler(environ, start_response)
  File "./http.py", line 1171, in __call__
    return self.dispatch(environ, start_response)
  File "./http.py", line 1145, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call_
_
    return self.app(environ, start_response)
  File "./http.py", line 1312, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.p
y", line 49, in _dispatch
    request.website = None
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 355, in <lambd
a>
    __setattr__ = lambda x, n, v: setattr(x._get_current_object(), n, v)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_c
urrent_object
    return self.__local()
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 132, in _looku
p
    raise RuntimeError('object unbound')
RuntimeError: object unbound
[pid: 530|app: 0|req: 1/2] 61.140.171.143 () {42 vars in 777 bytes} [Mon Sep 15
07:26:45 2014] GET / => generated 0 bytes in 2990 msecs (HTTP/1.1 500) 0 headers
 in 0 bytes (0 switches on core 0)

**Comment by kamanazan** [comment]
hello, i get similiar error message when i run odoo from pycharm. The error happened every time i open the web app.

**Comment by rafaelreuber** [comment]
I'm getting the same error when I try to execute it from pycharm

**Comment by coffeeshopmillionaire** [comment]
Helo anyone got any solution ?
