### ISSUE TITLE
[11.0] ORM test fails when user language is not English

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#23965]
Impacted versions: Atleast 11.0

Steps to reproduce: 
1. Set the administrator his language preferences to another language than English, for example Dutch
2. Run Odoo with `--test-enable` to trigger all Odoo tests

Current behavior: The test `test_copy` from the ORM tests fails on this line:
https://github.com/odoo/odoo/blob/ea6e7379a35e91f9ad064e5ad1e87c5177ea067b/odoo/addons/base/tests/test_orm.py#L242
Odoo assumes that the output is `Foo (copy)` but when you're in another language it will not be `Foo (copy)` but `Foo (kopie)`.

Traceback:
```
2018-03-30 12:31:55,285 16255 ERROR abc odoo.addons.base.tests.test_orm: ` During handling of the above exception, another exception occurred:
2018-03-30 12:31:55,285 16255 ERROR abc odoo.addons.base.tests.test_orm: ` 
2018-03-30 12:31:55,285 16255 ERROR abc odoo.addons.base.tests.test_orm: ` Traceback (most recent call last):
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: `   File "/odoo11ent/odoo11ent-server/odoo/tools/misc.py", line 815, in deco
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: `     return func(*args, **kwargs)
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: `   File "/odoo11ent/odoo11ent-server/odoo/addons/base/tests/test_orm.py", line 242, in test_copy
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: `     self.assertEqual(user_bar.name, 'Foo (copy)')
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` AssertionError: 'Foo (kopie)' != 'Foo (copy)'
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` - Foo (kopie)
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` ?      ^  ^^
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` + Foo (copy)
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` ?      ^  ^
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: ` 
2018-03-30 12:31:55,286 16255 ERROR abc odoo.addons.base.tests.test_orm: FAILED
```
Expected behavior: The test does not fail when the user his language is another language then English.

**Comment by Yenthe666** [comment]
OPW 1832972

**Comment by Yenthe666** [comment]
Apparently this is normal and desired behaviour. Feedback from Odoo:

> Dear Customer,
> This is actually the expected behavior, the tests are intended to work only in the Eglish language, not with other ones.

**Comment by Yenthe666** [comment]
It is not just one test by the way. Have four others:
```
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: Traceback (most recent call last):
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: `   File "/odoo11ent/odoo11ent-server/addons/decimal_precision/tests/test_qweb_float.py", line 21, in test_basic_float
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: `     "42.0")
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` AssertionError: '42,0' != '42.0'
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` - 42,0
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` ?   ^
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` + 42.0
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` ?   ^
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` 
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: FAIL: test_precision_domain (odoo.addons.decimal_precision.tests.test_qweb_float.TestFloatExport)
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: Traceback (most recent call last):
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: `   File "/odoo11ent/odoo11ent-server/addons/decimal_precision/tests/test_qweb_float.py", line 55, in test_precision_domain
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: `     '42.00')
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` AssertionError: '42,00' != '42.00'
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` - 42,00
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` ?   ^
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` + 42.00
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` ?   ^
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: ` 
2018-03-30 15:20:44,135 25007 ERROR abc odoo.addons.decimal_precision.tests.test_qweb_float: FAILED
2018-03-30 15:20:44,136 25007 ERROR abc odoo.modules.module: Module decimal_precision: 2 failures, 0 errors
2018-03-30 15:20:57,830 25007 ERROR abc odoo.addons.mail.tests.test_invite: FAIL
2018-03-30 15:20:57,832 25007 ERROR abc odoo.addons.mail.tests.test_invite: FAIL: test_invite_email (odoo.addons.mail.tests.test_invite.TestInvite)
2018-03-30 15:20:57,832 25007 ERROR abc odoo.addons.mail.tests.test_invite: Traceback (most recent call last):
2018-03-30 15:20:57,832 25007 ERROR abc odoo.addons.mail.tests.test_invite: `   File "/odoo11ent/odoo11ent-server/odoo/tools/misc.py", line 815, in deco
2018-03-30 15:20:57,832 25007 ERROR abc odoo.addons.mail.tests.test_invite: `     return func(*args, **kwargs)
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: `   File "/odoo11ent/odoo11ent-server/addons/mail/tests/test_invite.py", line 31, in test_invite_email
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: `     'invite wizard: subject of invitation email is incorrect')
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: ` AssertionError: 'Uitnodiging om te volgen Test Mail Model: Pigs' != 'Invitation to follow Test Mail Model: Pigs'
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: ` - Uitnodiging om te volgen Test Mail Model: Pigs
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: ` + Invitation to follow Test Mail Model: Pigs
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: `  : invite wizard: subject of invitation email is incorrect
2018-03-30 15:20:57,833 25007 ERROR abc odoo.addons.mail.tests.test_invite: FAILED
2018-03-30 15:20:57,833 25007 ERROR abc odoo.modules.module: Module mail: 1 failures, 0 errors
2018-03-30 15:21:00,756 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: FAIL
2018-03-30 15:21:03,210 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: FAIL: test_message_compose (odoo.addons.mail.tests.test_mail_features.TestMessagePost)
2018-03-30 15:21:03,210 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: Traceback (most recent call last):
2018-03-30 15:21:03,210 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: `   File "/odoo11ent/odoo11ent-server/odoo/tools/misc.py", line 815, in deco
2018-03-30 15:21:03,210 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: `     return func(*args, **kwargs)
2018-03-30 15:21:03,210 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: `   File "/odoo11ent/odoo11ent-server/addons/mail/tests/test_mail_features.py", line 235, in test_message_compose
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: `     self.assertEqual(composer.subject, 'Re: %s' % self.test_pigs.name)
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: ` AssertionError: 'Antw: Pigs' != 'Re: Pigs'
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: ` - Antw: Pigs
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: ` + Re: Pigs
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: ` 
2018-03-30 15:21:03,211 25007 ERROR abc odoo.addons.mail.tests.test_mail_features: FAILED
2018-03-30 15:21:03,211 25007 ERROR abc odoo.modules.module: Module mail: 1 failures, 0 errors
2018-03-30 15:21:11,452 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: FAIL
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: FAIL: test_add_context_action (odoo.addons.mail.tests.test_mail_template.TestMailTemplate)
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: Traceback (most recent call last):
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: `   File "/odoo11ent/odoo11ent-server/addons/mail/tests/test_mail_template.py", line 137, in test_add_context_action
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: `     self.assertEqual(action.name, 'Send Mail (%s)' % self.email_template.name)
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` AssertionError: 'Verstuur mail (Pigs Template)' != 'Send Mail (Pigs Template)'
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` - Verstuur mail (Pigs Template)
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` ? ^ ^^^^^^^^
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` + Send Mail (Pigs Template)
2018-03-30 15:21:12,652 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` ? ^ ^^^^
2018-03-30 15:21:12,653 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: ` 
2018-03-30 15:21:12,653 25007 ERROR abc odoo.addons.mail.tests.test_mail_template: FAILED
2018-03-30 15:21:12,653 25007 ERROR abc odoo.modules.module: Module mail: 1 failures, 0 errors
2018-03-30 15:21:13,328 25007 ERROR abc odoo.addons.mail.tests.test_message_track: FAIL
2018-03-30 15:21:13,329 25007 ERROR abc odoo.addons.mail.tests.test_message_track: FAIL: test_message_track (odoo.addons.mail.tests.test_message_track.TestTracking)
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` Testing auto tracking of fields. Warning, it has not be cleaned and should probably be.
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: Traceback (most recent call last):
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: `   File "/odoo11ent/odoo11ent-server/addons/mail/tests/test_message_track.py", line 107, in test_message_track
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: `     self.assertEqual(last_msg.tracking_value_ids.field_desc, 'Name')
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` AssertionError: 'Naam' != 'Name'
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` - Naam
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` ?   -
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` + Name
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` ?    +
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: ` 
2018-03-30 15:21:13,330 25007 ERROR abc odoo.addons.mail.tests.test_message_track: FAILED
2018-03-30 15:21:13,330 25007 ERROR abc odoo.modules.module: Module mail: 1 failures, 0 errors
2018-03-30 15:21:14,065 25007 ERROR abc odoo.addons.mail.tests.test_portal: FAIL
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: FAIL: test_invite_email_portal (odoo.addons.mail.tests.test_portal.TestPortal)
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: Traceback (most recent call last):
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: `   File "/odoo11ent/odoo11ent-server/odoo/tools/misc.py", line 815, in deco
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: `     return func(*args, **kwargs)
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: `   File "/odoo11ent/odoo11ent-server/addons/mail/tests/test_portal.py", line 67, in test_invite_email_portal
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: `     'invite: subject of invitation email is incorrect')
2018-03-30 15:21:14,379 25007 ERROR abc odoo.addons.mail.tests.test_portal: ` AssertionError: 'Uitnodiging om te volgen Test Mail Model: Pigs' != 'Invitation to follow Test Mail Model: Pigs'
2018-03-30 15:21:14,380 25007 ERROR abc odoo.addons.mail.tests.test_portal: ` - Uitnodiging om te volgen Test Mail Model: Pigs
2018-03-30 15:21:14,380 25007 ERROR abc odoo.addons.mail.tests.test_portal: ` + Invitation to follow Test Mail Model: Pigs
2018-03-30 15:21:14,380 25007 ERROR abc odoo.addons.mail.tests.test_portal: `  : invite: subject of invitation email is incorrect
2018-03-30 15:21:14,380 25007 ERROR abc odoo.addons.mail.tests.test_portal: FAILED
```
