### ISSUE TITLE
[11.0] - WRONG  LEAVES MODULE - hr_holidays

### ISSUE THREAD

**Issue by Pereiral01** [odoo/odoo#24051]
Impacted versions: ODOO 11 - installed in UBUNTU - with PYTHON 3.5

I have a problem in the LEAVES (ausencias) module  since a few days ago, I explain:
When I try to create an employee's LEAVE (for example with 16 days of vacations available) when choosing the type of leave (for example, Holidays with 16 days available, the following occurs:

1º They do not charge the 16 days, in the "DAYS" section (it stays at "0")
2º When I choose the start date and the end date, the next error jumps:

**Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 4995, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/odoo/models.py", line 4891, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/addons/hr_holidays/models/hr_holidays.py", line 319, in _onchange_date_to
    self.number_of_days_temp = self._get_number_of_days(date_from, date_to, self.employee_id.id)
  File "/odoo/odoo-server/addons/hr_holidays/models/hr_holidays.py", line 287, in _get_number_of_days
    return employee.get_work_days_count(from_dt, to_dt)
  File "/odoo/odoo-server/addons/resource/models/resource_mixin.py", line 48, in get_work_days_count
    return self.get_work_days_data(from_datetime, to_datetime, calendar=calendar)['days']
  File "/odoo/odoo-server/addons/resource/models/resource_mixin.py", line 56, in get_work_days_data
    compute_leaves=True):
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 437, in _iter_work_intervals
    resource_id=resource_id)
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 353, in _get_day_work_intervals
    working_intervals = [att_interval for att_interval in self._iter_day_attendance_intervals(day_date, start_time, end_time)]
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 353, in <listcomp>
    working_intervals = [att_interval for att_interval in self._iter_day_attendance_intervals(day_date, start_time, end_time)]
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 322, in _iter_day_attendance_intervals
    for calendar_working_day in self._get_day_attendances(day_date, start_time, end_time):
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 240, in _get_day_attendances
    if start_time and float_to_time(attendance.hour_to) < start_time:
  File "/odoo/odoo-server/addons/resource/models/resource.py", line 21, in float_to_time
    return datetime.time(int(math.modf(float_hour)[1]), int(60 * math.modf(float_hour)[0]), 0)
ValueError: hour must be in 0..23**

I understand that both are related, and that has to do with some change produced by an app or by some instance of PYTHON but could someone help me, please?

Thank you very much

**Comment by pedrobaeza** [comment]
Can you reproduce this in runbot?

Please explain all the steps with detail to get to the error.

**Comment by Pereiral01** [comment]
Many thanks Pedro, the runbot is:

- Access to Odoo> Leaves
- Go to LEAVES  (ausencias para aprobar > Ausencias)
- CREATE> choose Employee and Leaves type (Ex: Holidays with 32 free days)
- Usually when I choose it days´ field show the days to use (ex: 32 free days), but now it hold in "0" 
- Go to Star date and then End date ... when I choose end date, the wrong goin on.
Attached a Video File in ZIP.
[Sin título.zip](https://github.com/odoo/odoo/files/1880687/Sin.titulo.zip)

if this can help, last days I installed this PYTHON packages:
PANDAS
PYCOUNTY
UNIDECODE
CACHETOOLS
CHECKSUMDIR
PARAMIKO
UNIDECODECSV
ZEEP
TESSEROCR
PDFCONV

And this ODOO MODULES (l10n_es AEAT, BASE ISO3166)


To TRY to fix and  back, I UNISTALLED these:
TESSEROCR
ZEEP
TESSEROCR
PANDAS
PYCOUNTY

But the wrong is there yet!

Many thanks again!

**Comment by pedrobaeza** [comment]
Thanks for the information, @Pereiral01.

@Yenthe666 who can check this?

**Comment by Yenthe666** [comment]
@pedrobaeza see https://github.com/odoo/odoo/wiki/BugManagement#issues for the best list.
@tde-banana-odoo @jem-odoo or @tivisse basically.

**Comment by pedrobaeza** [comment]
OK, thanks. As I didn't see a direct entry, in the table, that's why I asked.

**Comment by Yenthe666** [comment]
Yeah I know, some are not very clear (yet) as there are some cases where there is no specific "owner" of a module. This happens to be one of those.

**Comment by sswapnesh** [comment]
Seems working well now. (I tried with new Database With and w/o Demo data)

**Comment by pedrobaeza** [comment]
Then closing until further notices.
