### ISSUE TITLE
In warehouse --> Inventory Control --> Inventory Adjustment --> when trying to press "Start inventory" I got the following error message

### ISSUE THREAD

**Issue by adnredwan77** [odoo/odoo#24121]
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/stock.py", line 2810, in prepare_inventory
    vals = self._get_inventory_lines(cr, uid, inventory, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock/stock.py", line 2838, in _get_inventory_lines
    ''', args)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 3:            FROM stock_quant WHERE location_id in ()
                                                                                         ^

**Comment by Yenthe666** [comment]
Hi @adnredwan77,

Thanks for the report.
Please follow the provided template though. On which version did you get this? How exactly do you reproduce it? Can you reproduce it on the latest code? Can you reproduce it on an official test instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by sle-odoo** [comment]
Hi,
It looks like the parent_left, parent_right is not correctly computed. You'll have to upgrade the stock module to recompute them.

Regards

**Comment by sswapnesh** [comment]
@adnredwan77  Is odoo v8?

**Comment by adnredwan77** [comment]
Hi, I'm using odoo 8

**Comment by sswapnesh** [comment]
@adnredwan77 Odoo v8 is no longer officially supported.
