### ISSUE TITLE
cannot edit/open/create contact on odoo 11.0

### ISSUE THREAD

**Issue by seifyba** [odoo/odoo#24134]
Impacted versions:11.0

Have you any idea how to solve this error ?
I can not edit or add new contact ?

Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x07D03110>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 2520, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 951, in __get__
    self.determine_value(record)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1062, in determine_value
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\bi_crm_claim\models\crm_claim.py", line 116, in _claim_count
    for partner_id in self
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\bi_crm_claim\models\crm_claim.py", line 116, in <dictcomp>
    for partner_id in self
TypeError: search_count() missing 1 required positional argument: 'args'

**Comment by pedrobaeza** [comment]
The module that causes the error is not an Odoo core module. You should contact original authors of that module for fixing the problem.
