### ISSUE TITLE
[11.0] Creating an internal transfer with multiple lines of same product causes error

### ISSUE THREAD

**Issue by manney** [odoo/odoo#24167]
**Impacted versions:**
Only tested on 11.0

**Steps to reproduce:**
1. Go to the Inventory App
2. From a 'Internal Transfers' Kanban card, click on the title or 'x Transfers' button
3. Click the 'Create' button in the tree view
4. Under the 'Operations' tab, create 2 or more lines that contain the same product, changing nothing else
5. Click the 'Save' button
6. An error (below) will appear

**Current behavior:**
On saving, a server error will appear:
```
Traceback (most recent call last):
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/aaron/Documents/work/odoo/dev/11/core/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/models.py", line 2565, in read
    self._read_from_database(stored, inherited)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/models.py", line 2684, in _read_from_database
    cr.execute(query_str, params)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/aaron/Documents/work/odoo/dev/11/core/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "stock.picking(7,)"
LINE 1: ...FROM "stock_picking" WHERE "stock_picking".id IN ('stock.pic...
 ```

**Expected behavior:**
Successfully saves or throws a UserError or ValidationError if this is not acceptable input

**Video/Screenshot link (optional):**
None

**Comment by manney** [comment]
An external module is being loaded (but is not installed) and causing the issue.  Sorry to waste anyone's time.
