### ISSUE TITLE
Not possible to access the current request on XML-RPC calls

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#24183]
Impacted versions: 8-11

## Current behavior:

If during an XMLRPC call you try to get anything from `http.request`, you'd get a `RuntimeError` such as this one:

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 56, in xmlrpc_return
    result = odoo.http.dispatch_rpc(service, method, params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/custom/src/odoo/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  [...]
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 135, in _lookup
    raise RuntimeError(\'object unbound\')
RuntimeError: object unbound
```

This renders imposible in practice to fix issues such as https://github.com/OCA/server-tools/issues/1125 or to implement https://github.com/odoo/odoo/pull/22212#issuecomment-380425764.

## Expected behavior:

XML-RPC calls should have request, since after all they belong to one. Otherwise, at least there should be an alternate way to access the request parameters.

**Comment by nhomar** [comment]
@Yajo Can you share a snippet of the script you are using, please? I can not reproduce on my side.

**Comment by Yajo** [comment]
Yes, you need to try to get the request details from a method that can be called from a XMLRPC call. I.e.:

```python
from odoo import api, http, models
class ResUsers(models.Model):
  @api.model
  def check_credentials(self):
    # Log the remote login IP
    print(http.request.httprequest.remote_addr)
    return super(ResUsers, self).check_credentials()
```

Then you have to connect to that database through XMLRPC and execute that method. In the example, that happens just by authenticating, [like explained in the docs](https://www.odoo.com/documentation/11.0/webservices/odoo.html#logging-in).

A [quick search](https://github.com/odoo/odoo/issues?utf8=%E2%9C%93&q=%22RuntimeError%3A+object+unbound%22) revealed related issues such as https://github.com/odoo/odoo/issues/21530 or https://github.com/odoo/odoo/issues/14939.

**Comment by odony** [comment]
This is the expected behavior as of today, as the XML-RPC layer is implemented separately from the regular web layer. This is from historical reasons, and originally allowed the XML-RPC stack to operate without the web client.
You could either rephrase this issue as a Wishlist request for converting the XMLRPC layer to a normal controller, or close it as "not a bug".

Issues like #21530 or #14939 seem to indicate that `odoo.http.request` was used without precautions in addons code where it is not guaranteed to exist (e.g. when called via XMLRPC, or when invoked by an `ir.cron` job, etc.)

**Comment by mreficent** [comment]
This can be closed, right?
