### ISSUE TITLE
Error boleto Itau Bank

### ISSUE THREAD

**Issue by brunobrobks** [odoo/odoo#24206]
Impacted versions: 11

Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 1663, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/addons/br_nfe/reports/danfe_report.py", line 24, in render_qweb_pdf
    res_ids, data=data)
  File "/opt/odoo/addons/br_boleto/reports/report.py", line 44, in render_qweb_pdf
    pdf_string = Boleto.get_pdfs(boleto_list)
  File "/opt/odoo/addons/br_boleto/boleto/document.py", line 148, in get_pdfs
    boleto.drawBoleto(boleto_list[i])
  File "/usr/local/lib/python3.6/dist-packages/pyboleto/pdf.py", line 822, in drawBoleto
    d = self._drawReciboCaixa(boleto_dados, x, y)
  File "/usr/local/lib/python3.6/dist-packages/pyboleto/pdf.py", line 674, in _drawReciboCaixa
    boleto_dados.format_nosso_numero()
  File "/usr/local/lib/python3.6/dist-packages/pyboleto/bank/itau.py", line 48, in format_nosso_numero
    self.dv_nosso_numero)
  File "/usr/local/lib/python3.6/dist-packages/pyboleto/bank/itau.py", line 34, in dv_nosso_numero
    return self.modulo10(composto)
  File "/usr/local/lib/python3.6/dist-packages/pyboleto/data.py", line 458, in modulo10
    parcial = int(c) * peso
ValueError: invalid literal for int() with base 10: '/'

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

**Comment by brunobrobks** [comment]
ok, sorry.
