### ISSUE TITLE
Error on selecting file for account.bank.statement.line import

### ISSUE THREAD

**Issue by EliasSuess** [odoo/odoo#24202]
Impacted versions: v11

Steps to reproduce: import CSV on account.bank.statement.line

Current behavior:

Fehler:
Uncaught Error: Unknown field belongs_to_company in domain

https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1746-88158c3/web.assets_backend.js:293
Zurückverfolgung
Error: Unknown field belongs_to_company in domain
    at Class.compute (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1746-88158c3/web.assets_backend.js:293:55)
    at https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1746-88158c3/web.assets_backend.js:295:830
    at Function._.every._.all (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:19:571)
    at Class.compute (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1746-88158c3/web.assets_backend.js:295:780)
    at Array.<anonymous> (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1746-88158c3/web.assets_backend.js:1509:32)
    at Array.<anonymous> (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:802:681)
    at fire (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:801:198)
    at Array.<anonymous> (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:802:874)
    at fire (https://odoo-sh-manatec-demo11cl.odoo.com/web/content/1537-f84e22e/web.assets_common.js:796:299)

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this happening on runbot (http://runbot.odoo.com/)? Can you provide the CSV in that case?

**Comment by EliasSuess** [comment]
it's happening on an odoo sh instance.

it seem to be a multi company related problem. the computed filed "belongs_to_company" from the model account.journal seems to be refered to as "belong_to_company" somewhere in the code if i'm not mistaken which is probably a typo

**Comment by Yenthe666** [comment]
@dbo-odoo when was Odoo.sh last updated? It looks like there is still a bug in there.
@EliasSuess can you reproduce this on the latest runbot instance? I assume this has been fixed in the meanwhile but that the latest Odoo fixes are not yet updated on Odoo.sh.

**Comment by pedrobaeza** [comment]
Thanks for the tracking, @sswapnesh. Closing this.
