### ISSUE TITLE
[11.0] Odoo server error (Print pdf) - "Free version"

### ISSUE THREAD

**Issue by LGx0** [odoo/odoo#24217]
Impacted versions:
Odoo 11.0-20180313
Steps to reproduce: All time. Invoice created, proforma created, and anybody create
Use language: Hungarian (magyar)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

``Hiba:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\generic.py", line 484, in readFromStream
    return NameObject(name.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 10: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1663, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 641, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\ir\ir_actions_report.py", line 551, in _post_pdf
    writer.write(result_stream)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\generic.py", line 579, in readFromStream
    value = readObject(stream, pdf)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\generic.py", line 60, in readObject
    return NameObject.readFromStream(stream, pdf)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\PyPDF2\generic.py", line 492, in readFromStream
    raise utils.PdfReadError("Illegal character in Name Object")
PyPDF2.utils.PdfReadError: Illegal character in Name Object``

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment. In concrete, using Windows per se is a big problem, as the library installation and so is a pain. Try on Linux. Check the installation steps on https://www.odoo.com/documentation/11.0/setup/install.html. Maybe you can mitigate the problem using a report name that doesn't contain an illegal character.

I'm closing this issue now.

**Comment by LGx0** [comment]
Thank you, i try linux system...
