### ISSUE TITLE
[11.0] Create company using import CSV the warehouse can't update quantity when receive product stockable

### ISSUE THREAD

**Issue by rofisyaifulamin** [odoo/odoo#24287]
Impacted versions:
odoo 11c
Commit : https://github.com/odoo/odoo/commit/0b1b860d975c5d997c34367074b76b98bb4ea049 
Demo data : No

Steps to reproduce:
1. Create company by Import CSV
    - create company using import CSV
    - create user and give access to imported company 
    - create vendor and create product
    - create PO and receive product
2. Create company by odoo interface
    - create company using odoo interface
    - create user and give access to company created from odoo interface 
    - create vendor and create product
    - create PO and receive product

Current behavior:
- When create Company (Company A) Using Import CSV and create new user (User A) even we create PO and have Quantity, Quantity On Hands in (Product A) is not updated, but
- When Create Company (Company B) Using Odoo Interface  and create new user (User B) than we create PO and have Quantity, Quantity On Hands in (Product A) will updated
-  When company using import CSV the warehouse can't update quantity when receive product stockable

Expected behavior:
- Even we create company using import file csv or using odoo interface and create PO then receive the product the quantity on Hands should updated.
- Also warehouse should update the quantity when receive product stockable

Video/Screenshot link (optional):
- Company A from import CSV
![image](https://user-images.githubusercontent.com/14796607/38909816-8dcf8348-42f0-11e8-9852-610cb7e8b755.png)

- Create PO and Receive product
![image](https://user-images.githubusercontent.com/14796607/38909942-1fd6fb2c-42f1-11e8-9dcf-a37d1927b85b.png)

- Quantity on Hands is still empty
![image](https://user-images.githubusercontent.com/14796607/38909969-4e1a925a-42f1-11e8-974d-6bae529e2055.png)

- Product Valuation is sill empty
![image](https://user-images.githubusercontent.com/14796607/38909993-7e547a80-42f1-11e8-8e45-eaaa6a8e5812.png)

- And when i check in stock.location, i have an empty parent_left and parent_right in company which i create using import CSV.
![screenshot from 2018-04-18 10-24-55](https://user-images.githubusercontent.com/14796607/38910372-39f030d0-42f3-11e8-9660-4f1bfe86b08d.png)

**Comment by gdgellatly** [comment]
Interesting.  I think you have found the source of another problem, where bug maintainers insist a properly configured Odoo won't have parent problem and close bugs saying its a user issue, yet  people I trust have been experiencing it on stock locations in particular.

Anyway, as a dirty workaround, normally when I get these issues I tend to just drop the parent_left and parent_right columns and upgrade, in this case the stock module.  That will recalculate the column values.

**Comment by rofisyaifulamin** [comment]
Yes, thanks @gdgellatly , i already try your suggestions and work Good. and now when i using user form imported company. and try to create new PO and Receive product the quantity on hands will updated.

but, how users can do when got same bugs?

I hope user never got that issues at the first time when create company using import csv and no need to drop the parent_left and parent_right columns and upgrade :)

**Comment by pedrobaeza** [comment]
For me the problem here is clear: you are creating the company via CSV, and this doesn't trigger the creation of all the needed things. It's not something that you can easily patch and I see a bit cumbersome and weird to import companies via CSV.

**Comment by sle-odoo** [comment]
we stumbled over this issue quite a few times but never found the root cause :-/
sharing your csv file could help
cc @rco-odoo

**Comment by gdgellatly** [comment]
@pedrobaeza other issue reports for this have not been importing via csv, merely we hopefully finally have a reproducible case where someone has recorded the exact actions they took and they are simle to replicate.  As you can see from the report the correct things are triggered e.g. warehouses and stock locations are created but the parent locations are not computed correctly.

**Comment by bimajatiwijaya** [comment]
Interesting issue @rofisyaifulamin ,
I have experience (custom module odoo C v9.0) when creating contact with some configuration will generate warehouse, routing etc and i follow sample code from creation res.company which automatically generate a warehouse.

During deployment all setting fully worked via import csv with hundreds data.

**Comment by MohsenWaleed** [comment]
I got the same issue when I imported warehouses from xls file when I tried to do inventory adjustment from one product only and once click on start inventory I got the below error:

ERROR WL.Demo odoo.sql_db: bad query: b'SELECT product_id, sum(quantity) as product_qty, location_id, lot_id as prod_lot_id, package_id, owner_id as partner_id\n            FROM stock_quant\n            LEFT JOIN product_product\n            ON product_product.id = stock_quant.product_id\n            WHERE  location_id in () AND active = TRUE AND company_id = 1 AND product_id = 60\n            GROUP BY product_id, location_id, lot_id, package_id, partner_id '
ERROR: syntax error at or near ")"
LINE 5:             WHERE  location_id in () AND active = TRUE AND c...
                                           ^

2019-09-27 15:34:39,279 1740 ERROR WL.Demo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\odoo\odoo-11.0_Test\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\odoo\odoo-11.0_test\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\odoo\odoo-11.0_test\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\odoo\odoo-11.0_test\addons\stock\models\stock_inventory.py", line 197, in action_start
    vals.update({'line_ids': [(0, 0, line_values) for line_values in inventory._get_inventory_lines_values()]})
  File "c:\odoo\odoo-11.0_test\addons\stock\models\stock_inventory.py", line 260, in _get_inventory_lines_values
    GROUP BY product_id, location_id, lot_id, package_id, partner_id """ % domain, args)
  File "C:\odoo\odoo-11.0_Test\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 5:             WHERE  location_id in () AND active = TRUE AND c...

And the on hand Quantity not updated.

**Comment by C3POdoo** [comment]
Dear @rofisyaifulamin,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
