### ISSUE TITLE
[V11] odoo.http: Exception during JSON request handling

### ISSUE THREAD

**Issue by rogerv95** [odoo/odoo#24298]
Impacted versions:
V11, Ubuntu Server 16
Steps to reproduce:
Clean install + odoo modules (any combination of them) + discuss + calendar

Current behavior:
Messages on discuss and chats don't appear after being send. It's necessary to refresh the page.

> 2018-04-18 10:25:10,886 20243 INFO TESTVELL werkzeug: 147.83.178.20 - - [18/Apr/2018 10:25:10] "POST /web/dataset/call_kw/mail.channel/channel_fetch_listeners HTTP/1.1" 200 -
2018-04-18 10:25:15,132 20243 ERROR TESTVELL odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

I get this error lots of times on the log. Always with the same lines being called.
I've asked in the odoo forum too some days ago but I've got no answer and reading the log I thought it may be an issue.
https://www.odoo.com/forum/help-1/question/v11-community-odoo-http-error-json-request-132457

**Comment by Yenthe666** [comment]
Hi @rogerv95,

Have you already tried to update to the latest source code?
Do you have the chatter configured on a different port?

**Comment by rogerv95** [comment]
No, I used the script (the updated from chris) and proceeded with the installation as it was with the script. 
Should I change something on the script to make it get the latest source code from GitHub?
I haven't change anything on the chatter port so it should be on default.

**Comment by Yenthe666** [comment]
@rogerv95 the script in fact pulls the latest version. 😉 So that answers the question.
Any extra security / Nginx configurations?

**Comment by rogerv95** [comment]
No, I was looking to use Nginx for the SSL but haven't done it till I get all the setup and testing as I need it.

**Comment by sswapnesh** [comment]
Should be because of odoo configuration. Have enabled workers?

**Comment by rogerv95** [comment]
I'm not sure if this is related, but today I made a clean install again (this time from the repository as stated in the official odoo documentation). I didn't get that error until I installed openssl, parmiko and pysftp (being used by the auto_backup module). So i'm thinking if it has something to do with openssl or paramiko or I'm completely wrong?
The error is exactly the same:

> 2018-04-19 16:42:33,965 1282 INFO TEST20 werkzeug: 147.83.178.20 - - [19/Apr/2018 16:42:33] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-04-19 16:42:33,974 1278 ERROR TEST20 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

**Comment by vasi26ro** [comment]
> My bad, the error came up when enabling workers = 9 or something different to 0. After that the longpolling wouldn't connect to the client. I had to set up the reverse proxy with nginx to be able to use multiple workers and get the chat working. If disabling workers without reverse proxy works as normal, for multiple workers looks like reverse proxy is needed.

I am using 5 workers and nginx reverse proxy with certbot certificates, but I still have this error.

@rogerv95 can you help me with an example of the nginx config?

**Comment by filwu8** [comment]
2022-10-15 16:23:35,222 1 INFO ? odoo: Odoo version 14.0-20221012 
2022-10-15 16:23:35,776 34 INFO ? odoo.service.server: Worker WorkerHTTP (34) alive
2022-10-15 16:23:35,777 36 INFO ? odoo.service.server: Worker WorkerHTTP (36) alive2022-10-15 16:23:35,777 39 INFO ? odoo.service.server: Worker WorkerHTTP (39) alive
2022-10-15 16:23:35,780 51 INFO ? odoo.service.server: Worker WorkerCron (51) alive
2022-10-15 16:23:35,781 55 INFO ? odoo.service.server: Worker WorkerCron (55) alive
2022-10-15 16:23:36,816 42 INFO ? odoo: Odoo version 14.0-20221012
2022-10-15 16:23:36,817 42 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2022-10-15 16:23:36,817 42 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/14.0', '/mnt/extra-addons', '/mnt/extra-addons-plus']
2022-10-15 16:23:36,817 42 INFO ? odoo: database: erp@erpdbv2:5432
2022-10-15 16:23:37,218 42 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2022-10-15 16:23:37,264 42 INFO ? odoo.service.server: Evented Service (longpolling) running on 0.0.0.0:8072
2022-10-15 16:23:58,523 30 INFO ? odoo.http: HTTP Configuring static files 
2022-10-15 16:23:58,756 30 INFO Erp odoo.modules.loading: loading 1 modules... 
2022-10-15 16:23:58,765 30 INFO Erp odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2022-10-15 16:24:00,274 30 INFO Erp odoo.modules.loading: loading 325 modules... 
2022-10-15 16:24:08,408 30 INFO Erp odoo.modules.loading: 325 modules loaded in 8.13s, 0 queries (+0 extra) 
2022-10-15 16:24:09,263 30 INFO Erp odoo.modules.loading: Modules loaded. 
2022-10-15 16:24:09,299 30 INFO Erp odoo.addons.base.models.ir_http: Generating routing map for key 1 

2022-10-15 16:24:09,451 30 ERROR Erp odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_presence/controllers/bus_controller.py", line 24, in poll
    return super(BusController, self).poll(channels, last, options=options)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 35, in poll
    raise Exception("bus.Bus unavailable")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: bus.Bus unavailable

2022-10-15 16:24:09,454 30 INFO Erp werkzeug: 223.167.141.124 - - [15/Oct/2022 16:24:09] "POST /longpolling/poll HTTP/1.1" 200 - 360 0.278 10.545
2022-10-15 16:24:26,892 30 ERROR Erp odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_presence/controllers/bus_controller.py", line 24, in poll
    return super(BusController, self).poll(channels, last, options=options)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 35, in poll
    raise Exception("bus.Bus unavailable")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: bus.Bus unavailable
