### ISSUE TITLE
RML Report Deprecated

### ISSUE THREAD

**Issue by mrezki** [odoo/odoo#24383]
Impacted versions: 10

Steps to reproduce: Click Export XLSX on module OCA

Current behavior: raise error access denied

Expected behavior: Export to Excel

Video/Screenshot link (optional):

Additional Info:
In the RML Report V10 should not have been deprecated, but in the latest odoo already deprecated, so some reports become inaccessible, then raise error access denied.

this is the log while error
Traceback (most recent call last):
  File "/opt/odoo10/odoo-custom/falinwa_branch/web/controllers/main.py", line 68, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo10/odoo-custom/falinwa_branch/web/controllers/main.py", line 1463, in index
    action["report_name"], report_ids, report_data, context])
  File "/opt/odoo10/odoo10-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo10/odoo10-server/odoo/service/report.py", line 32, in dispatch
    security.check(db,uid,passwd)
  File "/opt/odoo10/odoo10-server/odoo/service/security.py", line 13, in check
    return res_users.check(db, uid, passwd)
  File "/opt/odoo10/odoo10-server/odoo/addons/base/res/res_users.py", line 506, in check
    raise AccessDenied()
AccessDenied: Access denied

**Comment by Yenthe666** [comment]
Hi @mrezki,

Sorry but the Odoo Github tracker is only for issues in the official code. You're using an OCA module which tries to use deprecated RML reports. Do reach out to the OCA owner or make a PR to handle it there.
CC @pedrobaeza
