### ISSUE TITLE
Accounting tests not idempotent on repetitive execution

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24454]
On the same database, if I execute tests twice, I get the following trace back:

```bash
<<<< odoo.tools.convert.ParseError >>>>
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 855, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 925, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 806, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/tools/convert.py", line 809, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 717, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1190, in _update
    record.write(values)
  File "/opt/odoo/odoo/models.py", line 3570, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3734, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1087, in _validate_fields
    check(self)
  File "<decorator-gen-146>", line 2, in _check_lines
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons/90-odoo-cc/account/models/account_invoice.py", line 1449, in _check_lines
    raise ValidationError(_('A Payment Term should have only one line of type Balance.'))
ParseError: "A Payment Term should have only one line of type Balance.
None" while parsing /opt/odoo/addons/90-odoo-cc/account/data/account_data.xml:28, near
<record id="account_payment_term_15days" model="account.payment.term">
            <field name="name">15 Days</field>
            <field name="note">Payment term: 15 Days</field>
            <field name="line_ids" eval="[(0, 0, {'value': 'balance', 'value_amount': 0.0, 'sequence': 500, 'days': 15, 'option': 'day_after_invoice_date'})]"/>
        </record>

```

It would be expected from
```python
        group.add_option("--test-commit", action="store_true", dest="test_commit",
                         my_default=False, help="Commit database changes performed by YAML or XML tests.")
```
That without this flag, tests execution is idempotent.

**Comment by blaggacao** [comment]
It is fixed in v11 by https://github.com/odoo/odoo/commit/dbe6aa4292dc3190987855f4b59a737503d1f7f6

**Comment by luisiniguezh** [comment]
@pedrobaeza can we reopen this issue for v10 I can confirm it's happening on v10 and am willing to make a PR porting the code of https://github.com/odoo/odoo/commit/dbe6aa4292dc3190987855f4b59a737503d1f7f6

**Comment by Yenthe666** [comment]
@luisiniguezh if you really want it you can backport it to 10.0 and make a PR here. Please don't reopen the issue for this :)
