### ISSUE TITLE
http erreur 

### ISSUE THREAD

**Issue by ikrape** [odoo/odoo#24491]
Hello ,
i already have this erreur odoo10 i think that this cause by JSON i have not access 

```

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
>   File "/home/ikram/odoo/odoo-10/odoo/service/wsgi_server.py", line 186, in application
   return application_unproxied(environ, start_response)
>   File "/home/ikram/odoo/odoo-10/odoo/service/wsgi_server.py", line 172, in application_unproxied
>   result = handler(environ, start_response)
>   File "/home/ikram/odoo/odoo-10/odoo/http.py", line 1313, in __call__
   self.load_addons()
>   File "/home/ikram/odoo/odoo-10/odoo/http.py", line 1322, in load_addons
  for module in sorted(os.listdir(str(addons_path))):
> ```

thanks for help

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
