### ISSUE TITLE
Error when inheriting res.partner and adding a new field using Odoo 11

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#24502]
Impacted versions: 
odoo-11.0.post20180429

Steps to reproduce:
1. Was following the link ([here](https://www.odoo.com/documentation/11.0/howtos/backend.html#view-inheritance)) to build the `openacademy` module
2. So far earlier sections of the 'tutorial' was running ok with no problem until i tried out the model inheritance.
3. created this `openacademy/partner.py` file:
```
# -*- coding: utf-8 -*-
from odoo import fields, models

class Partner(models.Model):
    _inherit = 'res.partner'

    # Add a new column to the res.partner model, by default partners are not
    # instructors
    instructor = fields.Boolean("Instructor", default=False)

    session_ids = fields.Many2many('openacademy.session', string="Attended Sessions", readonly=True)
```
4. updated the `openacademy/__init__.py` file to include the partner file:
```
# -*- coding: utf-8 -*-
from . import controllers
from . import models
from . import partner
```
5. From the website, i went to apps > openacademy and select upgrade. System was upgraded with no error. I checked the odoo log and there was no error. However, res_partner table does not have the new field `instructor` and `sessions_ids` added.

6. I restarted the odoo server, refresh the website and the browser shows "Internal Error" and the website was not loaded.

7. Went to check the odoo log and i can see the following:
```
2018-04-30 12:53:15,467 15306 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-04-30 12:54:02,326 15306 DEBUG ? odoo.service.server: cron0 polling for jobs
2018-04-30 12:54:03,326 15306 DEBUG ? odoo.service.server: cron1 polling for jobs
2018-04-30 12:54:05,473 15306 INFO odoo11_test werkzeug: 192.168.1.8 - - [30/Apr/2018 12:54:05] "POST /longpolling/poll HTTP/1.1" 200 -
2018-04-30 12:54:55,603 15306 INFO odoo11_test werkzeug: 192.168.1.8 - - [30/Apr/2018 12:54:55] "POST /longpolling/poll HTTP/1.1" 200 -
2018-04-30 12:55:02,356 15306 DEBUG ? odoo.service.server: cron0 polling for jobs
2018-04-30 12:55:04,357 15306 DEBUG ? odoo.service.server: cron1 polling for jobs
2018-04-30 12:55:33,493 15306 ERROR odoo11_test odoo.sql_db: bad query: b'SELECT "res_partner"."id" as "id","res_partner"."website" as "website","res_partner"."is_company" as "is_company","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."message_last_post" as "message_last_post","res_partner"."tz" as "tz","res_partner"."opt_out" as "opt_out","res_partner"."debit_limit" as "debit_limit","res_partner"."display_name" as "display_name","res_partner"."email" as "email","res_partner"."picking_warn" as "picking_warn","res_partner"."company_id" as "company_id","res_partner"."team_id" as "team_id","res_partner"."write_date" as "write_date","res_partner"."date" as "date","res_partner"."function" as "function","res_partner"."user_id" as "user_id","res_partner"."color" as "color","res_partner"."comment" as "comment","res_partner"."company_name" as "company_name","res_partner"."signup_expiration" as "signup_expiration","res_partner"."picking_warn_msg" as "picking_warn_msg","res_partner"."barcode" as "barcode","res_partner"."active" as "active","res_partner"."partner_share" as "partner_share","res_partner"."street" as "street","res_partner"."instructor" as "instructor","res_partner"."credit_limit" as "credit_limit","res_partner"."create_uid" as "create_uid","res_partner"."ref" as "ref","res_partner"."phone" as "phone","res_partner"."title" as "title","res_partner"."customer" as "customer","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."activity_date_deadline" as "activity_date_deadline","res_partner"."street2" as "street2","res_partner"."calendar_last_notif_ack" as "calendar_last_notif_ack","res_partner"."type" as "type","res_partner"."invoice_warn" as "invoice_warn","res_partner"."state_id" as "state_id","res_partner"."write_uid" as "write_uid","res_partner"."mobile" as "mobile","res_partner"."supplier" as "supplier","res_partner"."last_time_entries_checked" as "last_time_entries_checked","res_partner"."parent_id" as "parent_id","res_partner"."commercial_partner_country_id" as "commercial_partner_country_id","res_partner"."zip" as "zip","res_partner"."signup_token" as "signup_token","res_partner"."invoice_warn_msg" as "invoice_warn_msg","res_partner"."create_date" as "create_date","res_partner"."country_id" as "country_id","res_partner"."vat" as "vat","res_partner"."employee" as "employee","res_partner"."message_bounce" as "message_bounce","res_partner"."lang" as "lang","res_partner"."name" as "name","res_partner"."city" as "city","res_partner"."signup_type" as "signup_type","res_partner"."industry_id" as "industry_id" FROM "res_partner" WHERE "res_partner".id IN (3)'
ERROR: column res_partner.instructor does not exist
LINE 1: ...partner_share","res_partner"."street" as "street","res_partn...
                                                             ^

2018-04-30 12:55:33,502 15306 ERROR odoo11_test odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo11/odootest/odoo-11.0.post20180429/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/odootest/odoo-11.0.post20180429/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f570cf1bda0>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo11/odootest/odoo-11.0.post20180429/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/odootest/odoo-11.0.post20180429/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f570cf1bda0>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo11/odootest/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_35
  File "<template>", line 2, in body_call_content_34
  File "/opt/odoo11/odootest/odoo-11.0.post20180429/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
```

8. I went to remark the line in the file `openacademy/__init__.py` that import the partner.py and restarted odoo and the system is running ok again.
```
# -*- coding: utf-8 -*-
from . import controllers
from . import models
#from . import partner
```

Did i miss something ?

Expected behavior:
res_partner table should be updated with the new fields.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@peterhoth,

You should not add the `from .  import partner` in `openacademy/__init.py` but in `openacademy/models/__init.py__`

**Comment by peterhoth** [comment]
@Yenthe666 
I did that initially but it gives the same error. I moved it the openacademy/partner.py and updated the openacademy/__init__.py but still the same error.

**Comment by peterhoth** [comment]
i did the changes but still error. -u also doesn't work. Finally, i tried Apps > openacademy > Uninstall and then install again. The issue seems fixed.
