### ISSUE TITLE
Error when update apps list (Client side

### ISSUE THREAD

**Issue by TagElMaaly** [odoo/odoo#24549]
Impacted versions:
odd 11

Steps to reproduce:
go to setting 
activate developer mode
go to apps
click on update apps list

Current behavior:
Error:
Uncaught TypeError: Cannot read property 'toggleClass' of undefined

http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1287
Traceback:
TypeError: Cannot read property 'toggleClass' of undefined
    at _apply (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1287:13)
    at Class._applyModifiers (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1285:565)
    at Class._registerModifiers (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1295:65)
    at Class._renderTagSeparator (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1356:964)
    at Class._renderNode (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1342:246)
    at Function._.map._.collect (http://localhost:8069/web/content/244-f61f3d3/web.assets_common.js:13:270)
    at Class._renderTagForm (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1349:18)
    at Class._renderNode (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1342:246)
    at Class._renderView (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1356:1365)
    at Class._render (http://localhost:8069/web/content/245-e980dcd/web.assets_backend.js:1296:178)

Expected behavior:

Video/Screenshot link (optional):

**Comment by TagElMaaly** [comment]
Hi @Yenthe666 
Well i have the latest source code
and i tested it at runbot and the error appeared
![capture](https://user-images.githubusercontent.com/32971486/39584321-6ffdf6fc-4ef2-11e8-9d4d-1f5c0110c628.PNG)

**Comment by TagElMaaly** [comment]
@Yenthe666 
i also have the latest chrome update
could this cause the problem?

**Comment by Yenthe666** [comment]
@TagElMaaly tested on Chrome 66.0.3359.139 without any issues. Could you make a little video please?

**Comment by TagElMaaly** [comment]
Okay
give a couple of minutes

**Comment by TagElMaaly** [comment]
@Yenthe666 
https://drive.google.com/file/d/1bQy7JLiNTpdkPXElmPFgkOcnSxdQE9Ai/view?usp=sharing

**Comment by Yenthe666** [comment]
Weird, I really don't get this error. Exactly which chrome version do you have? Do you have other plugins installed that alter CSS/JS/elements?

**Comment by TagElMaaly** [comment]
Thank you very much @Yenthe666 , you are right, it is an extension called Readium that I installed in chrome that made a conflict with updating Apps list, it worked fine after I uninstall this extension, thanks a lot ,,,

**Comment by Yenthe666** [comment]
Great to hear, thanks a lot for the feedback!
