### ISSUE TITLE
Server Error in entering lot in manufacturing order

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#24579]
Impacted versions:
Odoo 10.0 (Community Edition)

Steps to reproduce:
create a MO with Finished Product and/or Material Components managed with lots

Current behavior:
in entering lot for FP o changing it for Parts list a short dump has occurred (system log reported below)

Expected behavior:
lots detailed into MOs should be automatically copied into the workorders when performing WOs closure.

Thanks
Claudio Candito

Traceback (most recent call last):
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
TypeError: write() got an unexpected keyword argument 'context'

**Comment by pedrobaeza** [comment]
Is this reproducible in runbot?

**Comment by ccandito** [comment]
sorry, I've never used it

2018-05-05 16:55 GMT+02:00 Pedro M. Baeza <notifications@github.com>:

**Comment by pedrobaeza** [comment]
Please try and tell me if the problem is there: https://runbot.odoo.com

**Comment by pedrobaeza** [comment]
No further answer, so I close.
