### ISSUE TITLE
Sharing a document (for example RFQ) doesn't work

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#2457]
Hi

I have a customer that wants to use Odoo to communicate with their suppliers for exchange of documents.

I have tried to test this by selecting a RFQ and sharing it in two different ways:
1. Share by giving a unique URL. This gives an access error.
2. Share with a known user. I first created a sharing user for a supplier, then sent the RFQ to the supplier. The supplier got email saying that a Request for Quotation had been shared, clicked the link, got the login prompt, logged in but then got the portal screen with inbox etc and no RFQ.
3. Share by giving an Email. Gave same result as in 2.
4. Share with a group. Selected the portal group. Got exception (see below)

So, how is this going to work, and is this a bug in v8?

-Torvald
## 

Torvald Baade Bringsvor
Bringsvor Consulting AS - Odoo (formerly OpenERP) implementation partner

Traceback (most recent call last):
  File "/home/tbri/bc/latest/openerp/http.py", line 496, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/tbri/bc/latest/openerp/http.py", line 513, in dispatch
    result = self._call_function(*_self.params)
  File "/home/tbri/bc/latest/openerp/http.py", line 279, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/tbri/bc/latest/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/tbri/bc/latest/openerp/http.py", line 276, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/tbri/bc/latest/openerp/http.py", line 729, in __call__
    return self.method(_args, *_kw)
  File "/home/tbri/bc/latest/openerp/http.py", line 372, in response_wrap
    response = f(_args, *_kw)
  File "/home/tbri/bc/latest/addons/web/controllers/main.py", line 947, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/tbri/bc/latest/addons/web/controllers/main.py", line 935, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/tbri/bc/latest/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/tbri/bc/latest/addons/share/wizard/share_wizard.py", line 679, in go_step_2
    group_id, new_ids, existing_ids = self._create_share_users_group(cr, uid, wizard_data, context=context)
  File "/home/tbri/bc/latest/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/tbri/bc/latest/addons/portal/wizard/share_wizard.py", line 129, in _create_share_users_group
    self._create_shared_data_menu(cr, uid, wizard_data, group.id, context=context)
  File "/home/tbri/bc/latest/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/tbri/bc/latest/addons/portal/wizard/share_wizard.py", line 95, in _create_shared_data_menu
    root_menu_id = self._sharing_root_menu_id(cr, uid, portal, context=context)
  File "/home/tbri/bc/latest/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/tbri/bc/latest/addons/portal/wizard/share_wizard.py", line 84, in _sharing_root_menu_id
    parent_menu_id = self._create_or_get_submenu_named(cr, uid, portal.parent_menu_id.id, SHARED_DOCS_MENU, context=context)
AttributeError: 'int' object has no attribute 'parent_menu_id'

**Comment by crea** [comment]
Same here with an invoice.

**Comment by omalbastin** [comment]
i am facing this issue in openerp7. when sharing record using the share button under more option, it sends a mail to the shared person. but when that person tried to login, he is getting only a blank page

**Comment by seyed-mohammad-motahar** [comment]
Is this fixed ?

**Comment by Yenthe666** [comment]
Hi @bringsvor,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
