### ISSUE TITLE
Javascript error when adding an invoice line

### ISSUE THREAD

**Issue by vincentius** [odoo/odoo#24773]
**Impacted versions:**
11.0 Community, 11.0 Enterprise (tested on the official Odoo Runbot)

**Steps to reproduce:**
Line 57 of the `account.invoice_form` Form View currently looks like this: `<tree string="Invoice Lines" editable="bottom">`
1. Remove `editable="bottom"` from the `account.invoice_form` Form View on line 57.
It should now look like this: `<tree string="Invoice Lines">`
2. Try to add an invoice line to an invoice

**Current behavior:**
Javascript error:
```
http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3575
Traceback:
TypeError: Cannot read property 'views' of undefined
    at Class._processX2ManyCommands (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3575:30)
    at Class.applyDefaultValues (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:268:32)
    at Object.<anonymous> (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3378:29)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62)
    at Object.<anonymous> (http://localhost:8069/web/static/src/js/services/ajax_service.js:13:33)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
```
**Expected behavior:**
A modal opens with the invoice line form view.

**Comment by vincentius** [comment]
This worked with the release of a couple of weeks ago IIRC. But OK, i'll just redefine the form view then...
