### ISSUE TITLE
[11.0] wrong redirect after drop db

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24788]
Impacted versions: 11.0

Steps to reproduce: In FF. Goto /web/database/manager and delete a db from list

Current behavior: You will be redirected to /web/database/drop and get an error 500

Expected behavior: You should stay in /web/database/manager and view the reduced db list

**Comment by Yenthe666** [comment]
Hi @DR4RCON,

This actually works fine. Just tested on the last 11.0 and dropped a database in Firefox.
The direct to /web/database/drop is also intended and desired behaviour.

**Comment by DR4RCON** [comment]
Thanks for your response. What does I have to expect at that path?

**Comment by DR4RCON** [comment]
Yes, was my mistake. Wrong Tracker. That problem relies to queue_job, which raises an exception, when the database is dropped.
```
2018-05-17 14:12:58,856 6866 ERROR ? odoo.addons.queue_job.jobrunner.runner: exception: sleeping 5s and retrying
Traceback (most recent call last):
  File "/opt/workspace/ODOO11-ADDON-RESSOURCES/queue/queue_job/jobrunner/runner.py", line 397, in run
    self.wait_notification()
  File "/opt/workspace/ODOO11-ADDON-RESSOURCES/queue/queue_job/jobrunner/runner.py", line 375, in wait_notification
    conn.poll()
psycopg2.OperationalError: SSL connection has been closed unexpectedly
```
Will report there.
Thx @Yenthe666
