### ISSUE TITLE
[10.0] Can't open POS after upgrading to last commit

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#24812]
Impacted versions:
10.0

Steps to reproduce:
Upgrade
Open POS

Current behavior:
```javascript
models.js:515 Unexpected token u in JSON at position 0 SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Class.load (http://erp.client.com.do/point_of_sale/static/src/js/db.js:141:25)
    at Class.get_cashier (http://erp.client.com.do/point_of_sale/static/src/js/db.js:487:21)
    at child.get_cashier (http://erp.client.com.do/point_of_sale/static/src/js/models.js:580:24)
    at Object.loaded (http://erp.client.com.do/point_of_sale/static/src/js/models.js:243:33)
    at Object.<anonymous> (http://erp.client.com.do/point_of_sale/static/src/js/models.js:511:46)
    at Object.<anonymous> (http://erp.client.com.do/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://erp.client.com.do/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://erp.client.com.do/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://erp.client.com.do/web/static/lib/jquery/jquery.js:3283:104)
```

Expected behavior:
Open the POS

**Comment by gustavovalverde** [comment]
@kebeclibre might this be related to your commit?

**Comment by gustavovalverde** [comment]
It's weird, I actually cleaned the storage with Chrome's developer tool and also the cache; it still happened. Just doing it on an Incognito made it work.

I'll close this, as there might be something hanged there.
