### ISSUE TITLE
[8.0] Image upload to products is no longer possible in web cms

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#2485]
@amigrave Since your commits last night image uploads fails for me in most cases in the web cms:

Steps to Reproduce:
* create a new product through Webpage
* Try to upload an image for the product

2014-09-17 09:43:43,972 17933 ERROR odoo_8rc1_fundraising openerp.addons.website.controllers.main: Failed to upload image to attachment
Traceback (most recent call last):
  File "/Users/mkarrer/Desktop/GITTEST/odoo-mixed-branch/odoo_8.0/addons/website/controllers/main.py", line 342, in attach
    image_data = image_save_for_web(image)
  File "/Users/mkarrer/Desktop/GITTEST/odoo-mixed-branch/odoo_8.0/openerp/tools/image.py", line 138, in image_save_for_web
    image.save(img, **opt)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1439, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 491, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file

**Comment by yelizariev** [comment]
There is some issue with pillow package. I've updated one and it works now.

apt-get install python-dev
apt-get install libjpeg-dev
apt-get install libjpeg8-dev
apt-get install libpng3 
apt-get install libfreetype6-dev

pip install pillow

**Comment by Danisan** [comment]
This solved the problem in my case. It only happenned when trying to download big images, which needed to be adjusted.
Thank you.
