### ISSUE TITLE
[11.0] Portal user getting error when accessing event menu

### ISSUE THREAD

**Issue by Daemo00** [odoo/odoo#24935]
Impacted versions:
11.0

Steps to reproduce:

0) Install website_event, configure website as B2C
1) Log out from any user
2) In the frontend, click on "don't have an account" and create a user (that by default should be created with only 'portal' group)
3) Click on 'Event' menu

Current behavior:
500 Internal Server error

Expected behavior:
See events list

**Comment by Elkasitu** [comment]
Can you provide the traceback from your server logs? Thanks

**Comment by Daemo00** [comment]
Thanks for the fast reply, here the stack:
```2018-05-28 16:31:42,562 5334 INFO odoo11 odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 8, model: event.registration
2018-05-28 16:31:42,570 5334 INFO odoo11 odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 8, model: event.registration
2018-05-28 16:31:42,738 5334 ERROR odoo11 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f1f538a7550>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_444_85
  File "<template>", line 2, in body_call_content_84
  File "<template>", line 42, in foreach_81
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 993, in getter
    raise exception
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 1013, in compute_value
    self._compute_value(record)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/home/path/PycharmProjects/odoo11-env/odoo/addons/website_event/models/event.py", line 35, in _compute_is_participating
    event.is_participating = self.env['event.registration'].search_count(domain)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 1457, in search_count
    res = self.search(args, count=True)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 3759, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 2862, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-20>", line 2, in check
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_model.py", line 1190, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Events/User\n\n(Modello Documento: event.registration)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/http.py", line 1267, in flatten
    self.response.append(self.render())
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/http.py", line 1260, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1189, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/path/PycharmProjects/odoo11-env/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/home/path/PycharmProjects/odoo11-env/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1198, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Events/User\n\n(Modello Documento: event.registration)', None)
Traceback (most recent call last):
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f1f538a7550>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_444_85
  File "<template>", line 2, in body_call_content_84
  File "<template>", line 42, in foreach_81
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 961, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/api.py", line 993, in getter
    raise exception
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 1013, in compute_value
    self._compute_value(record)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/home/path/PycharmProjects/odoo11-env/odoo/addons/website_event/models/event.py", line 35, in _compute_is_participating
    event.is_participating = self.env['event.registration'].search_count(domain)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 1457, in search_count
    res = self.search(args, count=True)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 3759, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/models.py", line 2862, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-20>", line 2, in check
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/path/PycharmProjects/odoo11-env/odoo/odoo/addons/base/ir/ir_model.py", line 1190, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Events/User\n\n(Modello Documento: event.registration)', None)

Error to render compiling AST
AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Events/User\n\n(Modello Documento: event.registration)', None)
Template: 444
Path: /templates/t/t/div/div[2]/div[3]/div[2]/ul/li/div/h4/small[1]
Node: <small t-if="event.is_participating" class="label label-info">Participating</small>```

I've also managed to reproduce the issue in runbot

**Comment by Daemo00** [comment]
Hi there, any news on this?
Thanks

**Comment by pedrobaeza** [comment]
@tde-banana-odoo maybe you can check this one, as it's event related

**Comment by rdeodoo** [comment]
Hello, thanks for reporting the issue and sorry for the delay.
If I am not mistaken, it was fixed with https://github.com/odoo/odoo/commit/cda2ac9b71ef3ad6dc07e1c0418e560261503d33#diff-f351f4fe87388a784e46191f4cf85808
Let me know if it is not the case but everything looks alright on runbot

**Comment by Daemo00** [comment]
Confirming that now it's solved. Thanks!
