### ISSUE TITLE
Unable to install Sales Management App on Odoo 11.0

### ISSUE THREAD

**Issue by mbenmoumene** [odoo/odoo#24945]
Impacted versions:
v11.0
Steps to reproduce:
When i install the sale_Management A^pp

Current behavior:
Throws an install error :

Erreur:
![image](https://user-images.githubusercontent.com/39374134/40616476-bde4ef10-627a-11e8-8afe-9928b9616c23.png)

Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/odoo/odoo-server/addons/sales_team/models/crm_team.py", line 284, in create
    team = super(CrmTeam, self.with_context(mail_create_nosubscribe=True)).create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 236, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (11, null, t, 1, null, null, null, sales, sale.report, day, month, null, 1, 2018-05-28 13:20:57.666257, 1, 2018-05-28 13:20:57.666257, f, f, 558, day, t, t, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/odoo/odoo-server/addons/sales_team/models/crm_team.py", line 284, in create
    team = super(CrmTeam, self.with_context(mail_create_nosubscribe=True)).create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 236, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (11, null, t, 1, null, null, null, sales, sale.report, day, month, null, 1, 2018-05-28 13:20:57.666257, 1, 2018-05-28 13:20:57.666257, f, f, 558, day, t, t, null).
" while parsing /odoo/odoo-server/addons/sale/data/sale_data.xml:10, near
<record model="crm.team" id="sales_team.team_sales_department">
            <field name="use_quotations" eval="True"/>
            <field name="use_invoices" eval="True"/>
            <field name="dashboard_graph_model">sale.report</field>
        </record>

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Try also in a fresh database.

If you still feel that the problem is due to Odoo, please provide detailed information for reproducing the problem and any possible tip about what's going on.
