### ISSUE TITLE
Unable to upload any attachment with Safari

### ISSUE THREAD

**Issue by JanJSmejkal** [odoo/odoo#24941]
**Impacted versions:**
11

**Steps to reproduce:**
Upload any attachment (on a Mac) with Safari (without any plugins). Chrome and Firefox works fine

**Current behavior:**
Throws an upload error

**Expected behavior:**
No error

**Video/Screenshot link (optional):**
![upload_error](https://user-images.githubusercontent.com/11542155/40609436-e474715c-626e-11e8-8efb-a5f7e9d561e6.png)

**Console error log:**
Traceback (most recent call last):
  File "/opt/odoo/53511happyhair/addons/web/controllers/main.py", line 1127, in upload_attachment
    'res_id': int(id)
  File "/opt/odoo/53511happyhair/odoo/addons/base/ir/ir_attachment.py", line 438, in create
    values = self._check_contents(values)
  File "/opt/odoo/53511happyhair/odoo/addons/base/ir/ir_attachment.py", line 243, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/opt/odoo/53511happyhair/odoo/addons/base/ir/ir_attachment.py", line 235, in _compute_mimetype
    mimetype = mimetypes.guess_type(values['datas_fname'])[0]
  File "/usr/lib/python3.5/mimetypes.py", line 289, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python3.5/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/lib/python3.5/urllib/parse.py", line 862, in splittype
    match = _typeprog.match(url)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by intero-chz** [comment]
Have you tried without any safari plugin? We had a customer using some plugins/addons, which didn't work very well with Odoo.

**Comment by JanJSmejkal** [comment]
Yes, I have tried it without any plugins (updated issue description)

**Comment by C3POdoo** [comment]
Dear @JanJSmejkal,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
