### ISSUE TITLE
[9.0] Creating a new shipment: Uncaught TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by MouTio** [odoo/odoo#24989]
Impacted versions: 9.0

Steps to reproduce: 
1. Create a purchase order with a product/products.
2. Confirm order.
3. Receive products -> Set all the quantities to receive all products.
4. Validate.
5. Click on create button.

Current behavior:
Odoo crashes and this message appears:
```
Odoo Client Error
Uncaught TypeError: Cannot read property 'fields' of undefined
http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3557
Traceback:
TypeError: Cannot read property 'fields' of undefined
    at http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3557:41
    at Function._.each._.forEach (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1647-9216bd0/web.assets_common.js:12:650)
    at http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3557:3
    at Function._.each._.forEach (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1647-9216bd0/web.assets_common.js:12:650)
    at Class._build_onchange_specs (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3556:63)
    at Class.do_onchange (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3559:108)
    at Array.<anonymous> (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1651-c44587f/web.assets_backend.js:3548:526)
    at fire (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1647-9216bd0/web.assets_common.js:644:299)
    at Object.fireWith [as resolveWith] (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1647-9216bd0/web.assets_common.js:649:198)
    at Object.<anonymous> (http://332873-9-0-1ad3d1.runbot13.odoo.com/web/content/1647-9216bd0/web.assets_common.js:652:491)
```

Expected behavior:
Odoo should not crash.

Video/Screenshot link (optional):
Click here:
![image](https://user-images.githubusercontent.com/17930296/40772680-fb082004-64c0-11e8-968b-dcedeebf45a7.png)

Crash:
![image](https://user-images.githubusercontent.com/17930296/40772511-6b19107a-64c0-11e8-8efa-b9256010dcbf.png)

**Comment by Yenthe666** [comment]
@ged-odoo for you guys

**Comment by pedrobaeza** [comment]
Is this reproducible on runbot? I'm not sure this is an Odoo issue

**Comment by MouTio** [comment]
Yes @pedrobaeza . The screenshots are from runbot

**Comment by pedrobaeza** [comment]
Yeah, I see in the trace. OK, let's see what can be.

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported I'm closing this issue.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe
