### ISSUE TITLE
[11] Could not re-install account module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25005]
Impacted versions: 11

Steps to reproduce: Install account module --> Uninstall it --> Install again

Current behaviour: 

![](https://image.prntscr.com/image/fpanTXHpSVCSb_Osp5ZjKA.png)

Expected behaviour: Module should be installed

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Could you provide the server logs of when this happens? Unfortunately this kind of error doesn't say much, thanks.

**Comment by sswapnesh** [comment]
Sure

```
2018-06-01 00:48:15,562 2486 ERROR blabla odoo.sql_db: bad query: b'INSERT INTO "account_invoice_line" ("id", "sequence", "discount", "account_id", "product_id", "quantity", "price_unit", "invoice_id", "is_rounding_line", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval(\'account_invoice_line_id_seq\'), 10, \'0.00\', NULL, 36, \'5.000\', \'642.00\', 1, false, 1, 1, (now() at time zone \'UTC\'), (now() at time zone \'UTC\')) RETURNING id'
ERROR: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, 10, 1, null, 36, null, 642.00, null, null, null, 5.000, 0.00, null, null, null, null, f, 1, 2018-06-01 00:48:13.810605, 1, 2018-06-01 00:48:13.810605).

2018-06-01 00:48:15,562 2486 ERROR blabla odoo.tools.yaml_import: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, 10, 1, null, 36, null, 642.00, null, null, null, 5.000, 0.00, null, null, null, null, f, 1, 2018-06-01 00:48:13.810605, 1, 2018-06-01 00:48:13.810605).
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 797, in process
    self._process_node(node)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 808, in _process_node
    self.process_record(node)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 316, in process_record
    module, record_dict, record_id, noupdate=self.isnoupdate(record), mode=self.mode)
  File "/home/swapnesh/Workspace/11/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/swapnesh/Workspace/11/addons/account/models/account_invoice.py", line 464, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "/home/swapnesh/Workspace/11/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3516, in _create
    field.write(self.with_context(rel_context), vals[name], create=True)
  File "/home/swapnesh/Workspace/11/odoo/fields.py", line 2257, in write
    comodel.create(act[2])
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3462, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/swapnesh/Workspace/11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, 10, 1, null, 36, null, 642.00, null, null, null, 5.000, 0.00, null, null, null, null, f, 1, 2018-06-01 00:48:13.810605, 1, 2018-06-01 00:48:13.810605).

2018-06-01 00:48:15,576 2486 WARNING blabla odoo.modules.loading: Transient module states were reset
2018-06-01 00:48:15,579 2486 ERROR blabla odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/swapnesh/Workspace/11/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/swapnesh/Workspace/11/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/swapnesh/Workspace/11/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/swapnesh/Workspace/11/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/swapnesh/Workspace/11/odoo/tools/convert.py", line 786, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 854, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 797, in process
    self._process_node(node)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 808, in _process_node
    self.process_record(node)
  File "/home/swapnesh/Workspace/11/odoo/tools/yaml_import.py", line 316, in process_record
    module, record_dict, record_id, noupdate=self.isnoupdate(record), mode=self.mode)
  File "/home/swapnesh/Workspace/11/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/swapnesh/Workspace/11/addons/account/models/account_invoice.py", line 464, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "/home/swapnesh/Workspace/11/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3516, in _create
    field.write(self.with_context(rel_context), vals[name], create=True)
  File "/home/swapnesh/Workspace/11/odoo/fields.py", line 2257, in write
    comodel.create(act[2])
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3369, in create
    record = self.browse(self._create(old_vals))
  File "/home/swapnesh/Workspace/11/odoo/models.py", line 3462, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/swapnesh/Workspace/11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, 10, 1, null, 36, null, 642.00, null, null, null, 5.000, 0.00, null, null, null, null, f, 1, 2018-06-01 00:48:13.810605, 1, 2018-06-01 00:48:13.810605).

```
