### ISSUE TITLE
[11] Properly connector for Postgres 10

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25030]
Hi guys, i'm testing `odoo` 11 with docker and i get an error when i try to make a backup  from my database.
**Steps to reproduce:**
I go to the database manager section and i try to get a backup.

**Current behavior:**
Creating a `zip` file i get this:
```
odoo_11.web | 2018-06-01 22:22:28,216 1 INFO rotafilo odoo.sql_db: ConnectionPool(used=1/count=1/max=64): Closed 6 connections to 'dbname=rotafilo user=odoo password=xxxx host=db port=5432 sslmode=prefer'
odoo_11.web | 2018-06-01 22:22:28,219 1 INFO rotafilo werkzeug: 172.19.0.1 - - [01/Jun/2018 22:22:28] "GET /web/database/manager HTTP/1.1" 200 -
odoo_11.web | 2018-06-01 22:22:28,235 1 INFO ? werkzeug: 172.19.0.1 - - [01/Jun/2018 22:22:28] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 200 -
odoo_11.web | 2018-06-01 22:22:28,235 1 INFO ? werkzeug: 172.19.0.1 - - [01/Jun/2018 22:22:28] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 200 -
odoo_11.web | 2018-06-01 22:22:44,807 1 INFO rotafilo odoo.service.db: DUMP DB: rotafilo format dump
odoo_11.web | pg_dump: server version: 10.4 (Debian 10.4-1.pgdg90+1); pg_dump version: 9.6.7
odoo_11.web | pg_dump: aborting because of server version mismatch
odoo_11.web | 2018-06-01 22:22:45,664 1 INFO rotafilo werkzeug: 172.19.0.1 - - [01/Jun/2018 22:22:45] "POST /web/database/backup HTTP/1.1" 200 -
odoo_11.web | 2018-06-01 22:22:57,004 1 INFO rotafilo odoo.addons.base.ir.ir_cron: Starting job `Mail: Email Queue Manager`.
odoo_11.web | 2018-06-01 22:23:11,605 1 INFO rotafilo werkzeug: 172.19.0.1 - - [01/Jun/2018 22:23:11] "POST /longpolling/poll HTTP/1.1" 200 -
odoo_11.web | 2018-06-01 22:23:19,273 1 INFO rotafilo odoo.service.db: DUMP DB: rotafilo format zip
odoo_11.web | 2018-06-01 22:23:19,888 1 ERROR rotafilo odoo.addons.web.controllers.main: Database.backup
odoo_11.web | Traceback (most recent call last):
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 735, in backup
odoo_11.web |     dump_stream = odoo.service.db.dump_db(name, None, backup_format)
odoo_11.web |   File "<decorator-gen-8>", line 2, in dump_db
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 40, in if_db_mgt_enabled
odoo_11.web |     return method(self, *args, **kwargs)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 216, in dump_db
odoo_11.web |     odoo.tools.exec_pg_command(*cmd)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 128, in exec_pg_command
odoo_11.web |     raise Exception('Postgres subprocess %s error %s' % (args2, rc))
odoo_11.web | Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpnma1ho1f/dump.sql', 'rotafilo') error 1
odoo_11.web | 2018-06-01 22:23:19,953 1 INFO rotafilo odoo.sql_db: ConnectionPool(used=1/count=1/max=64): Closed 2 connections to 'dbname=rotafilo user=odoo password=xxxx host=db port=5432 sslmode=prefer'
odoo_11.web | 2018-06-01 22:23:19,958 1 INFO rotafilo werkzeug: 172.19.0.1 - - [01/Jun/2018 22:23:19] "POST /web/database/backup HTTP/1.1" 500 -
odoo_11.web | 2018-06-01 22:23:19,987 1 ERROR rotafilo werkzeug: Error on request:
odoo_11.web | Traceback (most recent call last):
odoo_11.web |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
odoo_11.web |     execute(self.server.app)
odoo_11.web |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
odoo_11.web |     application_iter = app(environ, start_response)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
odoo_11.web |     return self.app(e, s)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
odoo_11.web |     return application_unproxied(environ, start_response)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
odoo_11.web |     result = handler(environ, start_response)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
odoo_11.web |     return self.dispatch(environ, start_response)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
odoo_11.web |     return self.app(environ, start_wrapped)
odoo_11.web |   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
odoo_11.web |     return self.app(environ, start_response)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1466, in dispatch
odoo_11.web |     response = self.get_response(httprequest, result, explicit_session)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 279, in __exit__
odoo_11.web |     self._cr.commit()
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
odoo_11.web |     return f(self, *args, **kwargs)
odoo_11.web |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 375, in commit
odoo_11.web |     result = self._cnx.commit()
odoo_11.web | psycopg2.InterfaceError: connection already closed
```
 In the other case, for `dump` data i get a empty file. 

**Expected behavior:**
Get a full `dump` file or a zip file with the database backup; full restoring database.

I'm using latest version for `odoo` and `postgres` in `docker` with `docker-compose`.

**Comment by pedrobaeza** [comment]
Are you doing this with official Docker image?

@Yenthe666 do you know who is the Docker responsible?

**Comment by SalahAdDin** [comment]
@pedrobaeza  yes, i'm using the official image.

**Comment by sswapnesh** [comment]
@pedrobaeza  I believe @d-fence  is right person for this.

**Comment by lem8r** [comment]
Odoo 11 image is based on Debian Stretch which has Postgresql version 9.6.
pgdump v9.6 is executed with database server version 10 which causes error.

You have to build your own image with pg-client upgraded to version 10.

Here is example Dockerfile

```Dockerfile
FROM odoo:11.0

USER root

RUN set -x; \
    wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - \
    && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' \
    && apt-get update \
    && apt-get install  -y --no-install-recommends postgresql-client-10

USER odoo
```

**Comment by SalahAdDin** [comment]
@lem8r Thank you very much, i will test it.

**Comment by lem8r** [comment]
No, you don't.
It is already included in `odoo:11.0` image.

**Comment by Yenthe666** [comment]
Indeed, it is @d-fence for Docker images.

**Comment by SalahAdDin** [comment]
@lem8r 
```
+ wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O -
/bin/sh: 1: wget: not found
+ apt-key add -
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
```

**Comment by SalahAdDin** [comment]
Finally i did this:
```
FROM odoo:11.0

USER root

RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
        wget gnupg \
        && wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - \
        && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' \
        && apt-get update \
        && apt-get install  -y --no-install-recommends postgresql-client-10

RUN pip3 install boto3 phonenumbers

USER odoo
FROM odoo:11.0

USER root

RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
        wget gnupg \
        && wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - \
        && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' \
        && apt-get update \
        && apt-get install  -y --no-install-recommends postgresql-client-10

RUN pip3 install boto3 phonenumbers

USER odoo
```

**Comment by d-fence** [comment]
@lem8r perfectly answered this issue. Odoo 11 Docker image is made to be run alongside Postgres 9.6.
So, this issue is not really Odoo related that's why I close it.

That said, I think,that @SalahAdDin last issue with gnupg and wget that are missing in the image can be easily solved with something like that in your Dockerfile:
`
&& apt-get update \
&& apt-get install  -y --no-install-recommends \
      wget \
      gnupg2 \
      postgresql-client-10
`

You could also use "curl" instead of "wget" ...

**Comment by SalahAdDin** [comment]
@d-fence i solved in first way, i don't know how can i use `curl` in that case.

**Comment by d-fence** [comment]
Something like that should work:
```
curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
```

**Comment by SalahAdDin** [comment]
```bash

curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
```

**Comment by d-fence** [comment]
My bad, I forgot to remove the trailing "-O -" from the copy paste :-)
```
curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
```
AFAIK curl will use stdout by default.
