### ISSUE TITLE
Data export fails with message: "copy_from cannot be used with an asynchronous callback" 

### ISSUE THREAD

**Issue by stephanuse** [odoo/odoo#25060]
Impacted versions: 11

Steps to reproduce:  (To export Tasks) 
1) Navigate to Projects > Tasks and select List View
2) Tick records to be exported
3) Select Action > Export

Current behavior:
I get below error message when exporting records from any module (account, task, project, etc..) Running on AWS - T2 medium. Odoo 11 CE from BItnami.  I have updated all modules to latest versions.  

Expected behavior:
Selected records or exported to CSV file

Video/Screenshot link (optional):
{"code": 200, "message": "Odoo Server Error", "data": {"name": "psycopg2.ProgrammingError", "debug": "Traceback (most recent call last):\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/addons/web/controllers/main.py\", line 78, in wrap\n    return f(*args, **kwargs)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/addons/web/controllers/main.py\", line 1421, in index\n    return self.base(data, token)\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/addons/web/controllers/main.py\", line 1403, in base\n    import_data = records.export_data(field_names, self.raw_data).get('datas',[])\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/models.py\", line 794, in export_data\n    return {'datas': self._export_rows(fields_to_export)}\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/models.py\", line 718, in _export_rows\n    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))\n  File \"/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180518-py3.6.egg/odoo/models.py\", line 682, in __ensure_xml_id\n    columns=fields,\npsycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.\n", "message": "copy_from cannot be used with an asynchronous callback.", "arguments": ["copy_from cannot be used with an asynchronous callback."], "exception_type": "internal_error"}}

**Comment by Yenthe666** [comment]
Hi @stephanuse,

Thanks a lot for your report.
I've just tested this on the latest Odoo 11.0 but it seems to work fine out of the box! Can you reproduce it on an official Odoo instance at runbot.odoo.com? Can you update your source code and try again?

Regards,
Yenthe

**Comment by xmo-odoo** [comment]
@stephanuse it looks like you're performing the export (and accessing Odoo?) from the gevent worker (that's the only place where we're using asynchronous connections normally), this is not the expected or normal mode of operation: the gevent worker is only for chat & notifications, normal interactions should go through regular workers.

You'll want to check your deployment options, possibly with the providers of the package. Unless you manage to reproduce this on runbot.odoo.com as @Yenthe666 noted.

**Comment by stephanuse** [comment]
Hi Yenthe,

Thanks for responding, appreciate.

I've not made any source code customisations to the Bitnami odoo V11 instance - it's box standard, launched from the Bitnami console and instanced on Amazon AWS.  I have run  App > Updates and get the "Well done! All your Apps are up-to-date!" Response

This problem has also been reported by other AWS users:

https://www.odoo.com/forum/help-1/question/data-will-not-export-134247
https://github.com/odoo/odoo/issues/24145
https://community.bitnami.com/t/odoo-11-export-to-excel-cvs-error-copy-from-cannot-be-used-with-an-asynchronous-callback/57528

Bitnami Support considers this error an odoo application-specific error.  I therefore appreciate your feedback that the odoo official V11 version on runbot does function properly.  However, this problem is not going to go away, as the export functionality is critical for the proper setup and use by all those hundreds/thousands of Bitnami odoo users.  

I will pass your feedback on to the Bitnami team and see how they respond. Will it be possible for you to keep this Github ticket open for the next approx 48 hours?  I will let you know the moment I get feedback from Bitnami.

**Comment by stephanuse** [comment]
Hi xmo-odoo,
Txs for responding.  I'm using the export functionality from a normal browser page.  I'm logged in with admin rights.  I'll forward your comments to the Bitnami team.

kind rgds, 
Stephan

**Comment by stephanuse** [comment]
Hi Yenthe & xmo-odoo,

I have some more feedback on when this error occurs.  I made a odoo DB backup from an odoo Windows Docker environment (using the odoo browser Database Management function).  The database was restored to an odoo AWS EC2 instance (using the odoo browser Database Management function).  

The error appears under the following conditions:
- The odoo export function (browser) WORKS on the odoo Windows Docker database that was backed up.
- The export function FAILS on the exact same database restored to the Amazon AWS EC2 instance (no transactions added, no changes made).
- The export function does WORK with the odoo V11 default Bitnami database which is installed as part of the Bitnami AWS EC2 instance.

I have repeated the above backup-restore routine twice - both times the error behaviour is exactly the same.

It seems the error is specific to the backup database that was restored on AWS.  Do you guys have any suggestions/pointers of what I can do to to repair the DB (or any other way of fixing the problem)?  Could there be an issue with the database backup-restore utility?

kind regards,
Stephan

**Comment by gasimons** [comment]
Following.  Have same issue in Google Cloud Platform

**Comment by UnixedIT** [comment]
Also I have the same issue in GCP

**Comment by RalfWeiss** [comment]
I have the same issue in an bitname/AWS-environment using Odoo 11.
It seems it has something to do with the **XmlID** (maybe within: **__ensure_xml_id**).
As long as the records to export have an external identifier everything works fine.
But when I create a new record and try to export it this error shows up.
If I create an XmlID for newly created record and try to export it again the export works fine.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment. Specifically, on the workers option deployment, reusing the Gevent worker, so it's not an Odoo issue at all. Please comment on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), for asking for help in the deployment.

Closing this by the reason above.

**Comment by cargohec** [comment]
I'm using the Bitmani Odoo image for Azure on Ubuntu. I have the exact same issue. Out of the box the export works. Once other apps are added I get the same error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/addons/web/controllers/main.py", line 78, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/addons/web/controllers/main.py", line 1425, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/addons/web/controllers/main.py", line 1407, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/models.py", line 794, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/models.py", line 718, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/models.py", line 682, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.

**Comment by cargohec** [comment]
I have solved this issue in my deployment.

The error is has to do with the xml_id as @RalfWeiss mentions above. Looks like it only affects Bitnami deployments and my guess is that is has to do with the way the postgres database is installed in Bitnami. For some reason when a psycopg2 copy instructions is executed the system attempts to do it a asynchronously.

This error happens when a record that is being exported has no xml_id. Odoo creates one and attempts to add it to the ir_model_data table. The copy_from instruction si trying to insert a new id into the table. As it fails returning the error mentioned here the export fails.

_Fix:
Change the following in the file /opt/bitnami/apps/odoo/lib/odoo-11.0.post20180618-py3.6.egg/odoo/models.py_

_Line 37:_

        from contextlib import closing

_to_

        from contextlib import closing, contextmanager

_Lines 671 - 683_

        cr.copy_from(io.StringIO(
            u'\n'.join(
                u"%s\t%s\t%s\t%d" % (
                    modname,
                    record._name,
                    xids[record.id][1],
                    record.id,
                )
                for record in missing
            )),
            table='ir_model_data',
            columns=fields,
        )

_to_

        @contextmanager
        def _paused_thread():
            try:
                thread = psycopg2.extensions.get_wait_callback()
                psycopg2.extensions.set_wait_callback(None)
                yield
            finally:
                psycopg2.extensions.set_wait_callback(thread)
        with _paused_thread():
            cr.copy_expert("COPY ir_model_data (module, model, name, res_id) FROM STDIN",
                io.StringIO(u''.join(
                      u"%s\t%s\t%s\t%d" % (
                           modname,
                           record._name,
                           xids[record.id][1],
                           record.id,
                      )
                      for record in missing
                   )
               ))

This will do a async bulk insert into the database of the missing xml_id's and the export will finish.

Hope this helps!

**Comment by crgb001** [comment]
@cargohec I've tried to fix this issue with your solution but everytime I make the change it brakes my deployment and I cant get it back and ihave to restart allover again. am I missing something?

**Comment by cargohec** [comment]
@crgb001, set log level to debug run:

`sudo su -c "/opt/bitnami/python/bin/python3 /opt/bitnami/apps/odoo/bin/odoo-bin -c /opt/bitnami/apps/odoo/conf/odoo-server.conf --workers 0 -d bitnami_odoo -u all _&"
`
See what is reported in the log file.

**Comment by cargohec** [comment]
@crgb001 Forgot to mention. The code I uploaded ha tabs in it. Replace them with spaces and make sure the indentation is correct.

**Comment by crgb001** [comment]
@cargohec not sure if this is what you were asking...
this is what the log file got when the error occurs:

2018-08-27 15:28:32,531 716 INFO odoo_gaea odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-27 15:28:33,986 716 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 19 -> 19]
2018-08-27 15:28:42,802 716 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 19 -> 19]
2018-08-27 15:28:42,803 716 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 19 -> 19]
2018-08-27 15:28:42,804 716 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 19 -> 19]
2018-08-27 15:28:42,813 716 DEBUG odoo_gaea odoo.api: call ir.exports().search_read(domain=[['resource', '=', 'product.pricelist']], fields=['name'])
2018-08-27 15:28:52,128 716 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 19 -> 19]
2018-08-27 15:28:52,143 716 ERROR odoo_gaea odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 78, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1425, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1407, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 794, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 718, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 682, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.

**Comment by cargohec** [comment]
Looks like the problem has to do with indentation and tabs.

Set this values in the conf file: 

log_handler = :DEBUG
log_level = debug

**Comment by crgb001** [comment]
2018-08-27 15:35:38,718 1197 ERROR odoo_gaea odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 78, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1425, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1407, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 794, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 718, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 682, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.
2018-08-27 15:35:38,721 1197 INFO odoo_gaea odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-27 15:35:41,707 1197 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 20 -> 20]

**Comment by crgb001** [comment]
"Looks like the problem has to do with indentation and tabs." ... you mean the original fix, correct? 
I'll try to write it down myself instead of copy and paste

**Comment by crgb001** [comment]
@cargohec,
I wrote down the code and I got the same result:

> /opt/bitnami/apps/odoo/scripts/odoo_gevent.sh : odoo_gevent could not be started
> /opt/bitnami/apps/odoo/scripts/odoo_background_worker.sh : odoo_background_worker could not be started

Checking the log file I found this:
**psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.**


LOG FILE:
2018-08-28 08:30:54,814 1197 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 20 -> 20]
2018-08-28 08:30:54,820 1197 DEBUG odoo_gaea odoo.api: call ir.exports().search_read(domain=[['resource', '=', 'product.pricelist']], fields=['name'])
2018-08-28 08:30:58,815 1197 DEBUG odoo_gaea odoo.modules.registry: Multiprocess signaling check: [Registry - 10 -> 10] [Cache - 20 -> 20]
2018-08-28 08:30:58,818 1197 ERROR odoo_gaea odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 78, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1425, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 1407, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 794, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 718, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 682, in __ensure_xml_id
    columns=fields,
**psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.**

**Comment by crgb001** [comment]
this is the code I have in the models.py

>        @contextmanager
>         def _paused_thread():
>                 try:
>                         thread = psycopg2.extensions.get_wait_callback()
>                         psycopg2.extensions.set_wait_callback(None)
>                         yield
>                 finally:
>                         psycopg2.extensions.set_wait_callback(thread)
>         with _paused_thread():
>                 cr.copy_expert("COPY ir_model_data (module, model, name, res_id) FROM STDIN",
>                         io.StringIO(u'\n'.join(
>                 u"%s\t%s\t%s\t%d" % (
>                     modname,
>                     record._name,
>                     xids[record.id][1],
>                     record.id,
>                 )
>                 for record in missing
>                 )
>             ))

**Comment by cargohec** [comment]
Clear the log file. Make sure Postgres is running and run

`sudo su -c "/opt/bitnami/python/bin/python3 /opt/bitnami/apps/odoo/bin/odoo-bin -c /opt/bitnami/apps/odoo/conf/odoo-server.conf --workers 0 -d bitnami_odoo -u all _&"`

and post what shows up after the commands runs and in the log file.

**Comment by crgb001** [comment]
post:

> /opt/bitnami/python/lib/python3.6/site-packages/pkg_resources/__init__.py:1235: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
>   warnings.warn(msg, UserWarning)
> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/bin/odoo-bin", line 5, in <module>
>     __import__('pkg_resources').declare_namespace('odoo.addons')
>   File "/opt/bitnami/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2160, in declare_namespace
>     declare_namespace(parent)
>   File "/opt/bitnami/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2176, in declare_namespace
>     _handle_ns(packageName, path_item)
>   File "/opt/bitnami/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2111, in _handle_ns
>     loader.load_module(packageName)
>   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 823, in load_module
>   File "<frozen importlib._bootstrap_external>", line 682, in load_module
>   File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/__init__.py", line 86, in <module>
>     from . import osv
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/osv/__init__.py", line 4, in <module>
>     from . import osv
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/osv/osv.py", line 5, in <module>
>     from .orm import Model, TransientModel, AbstractModel
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/osv/orm.py", line 8, in <module>
>     from ..models import (
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/models.py", line 672
>     def _paused_thread():
>                         ^
> TabError: inconsistent use of tabs and spaces in indentation

log:
empty

**Comment by crgb001** [comment]
im editing it with nano

**Comment by cargohec** [comment]
Make it look like this:
![view](https://user-images.githubusercontent.com/20497102/44729609-cd44d980-aaa4-11e8-80cf-a4eceb962c73.png)

**Comment by crgb001** [comment]
Great!... go it working!!!!... thanks for you patience!!! export problem fixed!!! Thanks!

**Comment by Gelson15** [comment]
Hi everyone, I'm getting this error when then creating a list view from the query in odoo, can someone help me?


Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-47>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 307, in init_models
    model.init()
  File "/opt/odoo/odoo/odoo/addons/gestao_compras/models/consultaDocumentoPendente.py", line 19, in init
    tools.drop_view_if_exists(self._cr, 'consutdocum_consutdocum')
  File "/opt/odoo/odoo/odoo/tools/sql.py", line 206, in drop_view_if_exists
    cr.execute("DROP view IF EXISTS %s CASCADE" % (viewname,))
  File "/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: "consutdocum_consutdocum" is not a view
HINT:  Use DROP TABLE to remove a table.

thank you

**Comment by aek** [comment]
This is an issue introduced in v11, I have it too. I will try the solution as seems to be what solve this kind of scenarios.

**Comment by sehrishnaz** [comment]
Try this one: http://learnopenerp.blogspot.com/2019/10/how-to-use-self-env-cr-copy-from-to-save-data-in-database.html
