### ISSUE TITLE
[11] Could not reinstall CRM module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25080]
Impacted versions: 11.0

Steps to reproduce: Install CRM --> Uninstall CRM --> Uninstall Discuss module --> Install CRM

Current behavior:
 ```
File "/home/swapnesh/Workspace/11/odoo/models.py", line 2136, in _init_column
    value = field.default(self)
  File "/home/swapnesh/Workspace/11/addons/mail/wizard/mail_compose_message.py", line 126, in <lambda>
    subtype_id = fields.Many2one(default=lambda self: self.sudo().env.ref('mail.mt_comment', raise_if_not_found=False).id)
AttributeError: 'NoneType' object has no attribute 'id'
```
Expected behavior: Module should be installed

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Not specific to CRM, Happens with all module having dependency of `mail` module.

**Comment by Yenthe666** [comment]
Oh no, not even more of those. 😕

**Comment by marcos-mendez** [comment]
> Oh no, not even more of those.

I didn't understand. Did you solve the problem?

I Have a very similar one 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 673, in call_kw_model
    return downgrade(method, result, recs, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 272, in downgrade
    return convert(value)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3347, in <lambda>
    @api.returns('self', lambda value: value.id)
AttributeError: 'NoneType' object has no attribute 'id'

Can someone help me?

**Comment by marcos-mendez** [comment]
Please check permissions on user/contact

**Comment by Elkasitu** [comment]
Is this with or without demo data?

**Comment by pedrobaeza** [comment]
No answer, so closing.

**Comment by sswapnesh** [comment]
> Does this happen without demo data?

Yes, It is.
