### ISSUE TITLE
Access error on read_followers_data for portal user

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#2511]
https://github.com/odoo/odoo/blob/master/addons/mail/mail_thread.py#L181
When is_uid = uid in map(lambda x: x.id, follower.user_ids) access error is thrown:

<code><pre>
2014-09-18 09:21:42,436 8768 ERROR pbxware_production openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 516, in dispatch
    result = self._call_function(*_self.params)
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/srv/odoo_pbxware/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 279, in checked_call
    return self.endpoint(_a, *_kw)
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 732, in __call__
    return self.method(_args, *_kw)
  File "/srv/odoo_pbxware/odoo/openerp/http.py", line 375, in response_wrap
    response = f(_args, *_kw)
  File "/srv/odoo_pbxware/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/odoo_pbxware/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/srv/odoo_pbxware/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/odoo_pbxware/odoo/addons/mail/mail_thread.py", line 181, in read_followers_data
    is_uid = uid in map(lambda x: x.id, follower.user_ids)
  File "/srv/odoo_pbxware/odoo/openerp/fields.py", line 717, in __get__
    return record._cache[self]
  File "/srv/odoo_pbxware/odoo/openerp/models.py", line 5775, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/srv/odoo_pbxware/odoo/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)')
</pre></code>

It comes from the following record rule: res_partner: portal/public: read access on my commercial partner from openerp/addons/base/security/base_security.xml.

**Comment by yannprada** [comment]
I saw that the code is not the same as when you made your fix @a0c 
but the same error occurs, on the line 
https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L187

**Comment by Yenthe666** [comment]
Hi @litnimax ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
