### ISSUE TITLE
Cannot read property 'journal_id' of undefined

### ISSUE THREAD

**Issue by BalramY** [odoo/odoo#25141]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by BalramY** [comment]
Hello @pedrobaeza Thanks for your quick response. 

Can you please check the following issue.
I configured SaaS on my system so when I login to client database and create a pos order then on payment page it give me following error-

Uncaught TypeError: Cannot read property 'journal_id' of undefined
http://url:8069/web/content/4455-7df45a7/point_of_sale.assets.js:191
Traceback:
TypeError: Cannot read property 'journal_id' of undefined
    at child.initialize (http://url:8069/web/content/4455-7df45a7/point_of_sale.assets.js:191:68)
    at child.Backbone.Model (http://url:8069/web/content/4458-12c263d/web.assets_backend.js:39:1299)
    at new child (http://url:8069/web/content/4458-12c263d/web.assets_backend.js:81:455)
    at child.add_paymentline (http://url:8069/web/content/4455-7df45a7/point_of_sale.assets.js:219:634)
    at Class.click_numpad (http://url:8069/web/content/4455-7df45a7/point_of_sale.assets.js:387:44)
    at HTMLButtonElement.<anonymous> (http://url:8069/web/content/4455-7df45a7/point_of_sale.assets.js:388:191)
    at HTMLDivElement.dispatch (http://url:8069/web/content/310-f683414/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (http://url:8069/web/content/310-f683414/web.assets_common.js:865:173)

**Comment by pedrobaeza** [comment]
I think this is something related to your installation. Please try to reproduce the problem in runbot: https://runbot.odoo.com (admin/admin), and if the problem is there, please indicate all the detailed steps.
