### ISSUE TITLE
Odoo Server Error - Gestion de ventas

### ISSUE THREAD

**Issue by flasso** [odoo/odoo#25392]
Impacted versions: 11

Steps to reproduce: setup module sales management (Gestion de ventas)

Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoocloud/odoocloud-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/odoocloud/odoocloud-server/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/odoocloud/odoocloud-server/addons/sales_team/models/crm_team.py", line 284, in create
    team = super(CrmTeam, self.with_context(mail_create_nosubscribe=True)).create(values)
  File "/odoocloud/odoocloud-server/addons/mail/models/mail_thread.py", line 236, in create
    thread = super(MailThread, self).create(values)
  File "/odoocloud/odoocloud-server/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/odoocloud/odoocloud-server/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoocloud/odoocloud-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoocloud/odoocloud-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (7, null, t, 1, null, null, null, sales, sale.report, day, month, null, 1, 2018-06-21 12:15:14.666346, 1, 2018-06-21 12:15:14.666346, f, f, 17, day, t, t, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoocloud/odoocloud-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoocloud/odoocloud-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoocloud/odoocloud-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoocloud/odoocloud-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoocloud/odoocloud-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoocloud/odoocloud-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoocloud/odoocloud-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoocloud/odoocloud-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoocloud/odoocloud-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoocloud/odoocloud-server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoocloud/odoocloud-server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoocloud/odoocloud-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoocloud/odoocloud-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/odoocloud/odoocloud-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoocloud/odoocloud-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoocloud/odoocloud-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoocloud/odoocloud-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoocloud/odoocloud-server/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoocloud/odoocloud-server/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoocloud/odoocloud-server/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoocloud/odoocloud-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/odoocloud/odoocloud-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoocloud/odoocloud-server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoocloud/odoocloud-server/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/odoocloud/odoocloud-server/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/odoocloud/odoocloud-server/addons/sales_team/models/crm_team.py", line 284, in create
    team = super(CrmTeam, self.with_context(mail_create_nosubscribe=True)).create(values)
  File "/odoocloud/odoocloud-server/addons/mail/models/mail_thread.py", line 236, in create
    thread = super(MailThread, self).create(values)
  File "/odoocloud/odoocloud-server/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/odoocloud/odoocloud-server/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoocloud/odoocloud-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoocloud/odoocloud-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (7, null, t, 1, null, null, null, sales, sale.report, day, month, null, 1, 2018-06-21 12:15:14.666346, 1, 2018-06-21 12:15:14.666346, f, f, 17, day, t, t, null).
" while parsing /odoocloud/odoocloud-server/addons/sale/data/sale_data.xml:10, near
<record model="crm.team" id="sales_team.team_sales_department">
            <field name="use_quotations" eval="True"/>
            <field name="use_invoices" eval="True"/>
            <field name="dashboard_graph_model">sale.report</field>
        </record>

Expected behavior:
success instalation module

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
It is working well in Runbot and local instance too.

**Comment by pedrobaeza** [comment]
Closing while no further details (and in English)

**Comment by flasso** [comment]
It does not allow to install the sales module, it has CRM installed, but if you try to update it, it throws the same error.
Also the electronic commerce module throws this same error.

**Comment by pedrobaeza** [comment]
You should have your DB corrupted. Try on a fresh database or fix the underlying problem on current DB, but it's not a problem of Odoo itself.

**Comment by flasso** [comment]
Recommends that when starting to work with odoo should all the modules be installed before entering information to avoid these future database failures?

**Comment by pedrobaeza** [comment]
No, that shouldn't happen unless you remove base records, like UoMs or similar. Any way, try updating base module before installing the other one for restoring missing data.

**Comment by flasso** [comment]
I worry about losing the information to date.

**Comment by flasso** [comment]
How can I update the base module?

**Comment by pedrobaeza** [comment]
Not updating the base module

**Comment by pedrobaeza** [comment]
You should make that kind of basic questions on forums, not here.

**Comment by flasso** [comment]
The error is not basic, it is information that odoo allowed to be corrupt. I will try to enter the database and evaluate the corrupt data. regards
