### ISSUE TITLE
[11.0] Inventory: Can't  assign owner for Stock transfer in case have more than one product line.

### ISSUE THREAD

**Issue by UnixedIT** [odoo/odoo#25410]
Impacted versions:
11.00

Steps to reproduce:

- Inventory - Setting - tick "Consignment" box.
- Create Sales order with two lines>
- Confirm SO.
-Click on truck image in order to validate the transfer.
- Edit the transfer.
- Choose the Stock owner.
- Click "Assign Owner"
- Odoo server error.

Current behavior:

- It works if clicked on each product line and assign the owner for each one separately.
- It works if you have one product line in the sales order.

Expected behavior:

 - Assign the owner for all product lines via one shot using "Assign Owner".

Video/Screenshot link (optional):

**Comment by UnixedIT** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-203>", line 2, in action_assign_owner
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/stock/models/stock_picking.py", line 547, in action_assign_owner
    self.move_line_ids.write({'owner_id': self.owner_id.id})
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/stock_account/models/stock.py", line 129, in write
    return super(StockMoveLine, self).write(vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/mrp/models/stock_move.py", line 45, in write
    return super(StockMoveLine, self).write(vals)
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/addons/stock/models/stock_move_line.py", line 271, in write
    new_product_uom_qty = self.product_id.uom_id._compute_quantity(new_product_qty, self.product_uom_id, rounding_method='HALF-UP')
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/fields.py", line 935, in __get__
    record.ensure_one()
  File "/home/odoo/runbot/runbot/runbot/static/build/340884-11-0-1740b1/odoo/models.py", line 4362, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move.line(915, 916)
