### ISSUE TITLE
[Odoo 11.0] Google Calendar sync Odoo error

### ISSUE THREAD

**Issue by jeroenbroerseSmarterliving** [odoo/odoo#25432]
Impacted versions:
Odoo 11

Steps to reproduce:
Installed google calendar and setup the API.
Pressed sync with google in Calendar
several agenda point synced from google to Odoo and receive error:
```
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 589, in synchronize_events
    res = recs.update_events(lastSync)
  File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 782, in update_events
    event_to_synchronize[base_event][current_event].compute_OP(modeFull=not lastSync)
  File "/opt/odoo/odoo11/addons/google_calendar/models/google_calendar.py", line 85, in compute_OP
    if self.OE.update.split('.')[0] != self.GG.update.split('.')[0]:
AttributeError: 'NoneType' object has no attribute 'split'
```

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mart-e any clue about this?

**Comment by mart-e** [comment]
Not sure, it means we do have a status but no `oe_update_date`
https://github.com/odoo/odoo/blob/85f8e4761b9ad1d05ed787de4235fbbdfd33d7dd/addons/google_calendar/models/google_calendar.py#L84-L85
https://github.com/odoo/odoo/blob/85f8e4761b9ad1d05ed787de4235fbbdfd33d7dd/addons/google_calendar/models/google_calendar.py#L752-L753

Could it be from a duplicated event?
https://github.com/odoo/odoo/blob/85f8e4761b9ad1d05ed787de4235fbbdfd33d7dd/addons/google_calendar/models/calendar.py#L28-L35

**Comment by pedrobaeza** [comment]
The weird thing is that `ev_to_sync.OE.update` is `None`, not `False`, so we should be missing other thing.

**Comment by jeroenbroerseSmarterliving** [comment]
I just checked my agenda for double entries but there aren't any.
If you need additional information from me, please ask

**Comment by C3POdoo** [comment]
Dear @jeroenbroerseSmarterliving,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
