### ISSUE TITLE
[11.0]  ValueError: Unknown path: /base/res/res.lang.csv

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25440]
Impacted versions:
`11.0 20180622`

Steps to reproduce:
Create a new clean database(destroying old volumes), without using demo data.

Current behavior:
```bash
2018-06-22 14:14:58,783 1 WARNING rotafilo odoo.modules.loading: Transient module states were reset
2018-06-22 14:14:58,788 1 ERROR rotafilo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
2018-06-22 14:14:58,789 1 CRITICAL rotafilo odoo.service.server: Failed to initialize database `rotafilo`.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
```
Expected behavior:
No problems

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by SalahAdDin** [comment]
@pedrobaeza I just replicated the official `odoo` `docker` image but using the nightly build and adding some packages for `OCA` modules(dependencies).

**Comment by SalahAdDin** [comment]
But as well i'm testing i got that this problem is with the addons module's path.
