### ISSUE TITLE
No exception message popup in Kanban view when create record

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#25574]
Impacted versions: 9.0

Steps to reproduce:
- inherid model `crm.lead`, add to `def create(self, vals)` a validate method and raise exception, example:
```python
    @api.model
    def create(self, vals):
        if not self.env.user.company_id.parent_id:
            raise exceptions.ValidationError(_("You cannot create Lead for GLOBAL COMPANY!"))
        return super(CrmLead, self).create(vals)
```
- (or) inherit model `crm.lead`, add new requirement field, example:
```python
class CrmLead(models.Model):
    _inherit = 'crm.lead'

    test_requirement = fields.Char(string="Test", required=True)
```
- restart odoo server, install / update module
- in kanban lead view, add new record

Current behavior:
```
Uncaught TypeError: event.preventDefault is not a function
http://localhost:8069/web_kanban/static/src/js/kanban_view.js:689
Traceback:
TypeError: event.preventDefault is not a function
    at Object.on_fail (http://localhost:8069/web_kanban/static/src/js/kanban_view.js:689:19)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as fail] (http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49)
```

Expected behavior:
   Exception popup

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5380820/42197983-a849835e-7eaf-11e8-8d28-9b785f522564.png)

**Comment by pedrobaeza** [comment]
You shouldn't put that on the `create` method, but include a method with `@api.constrains(fields)` that do it instead, so the error in the misuse is expected. Please use proper methods for performing validations.

**Comment by NothingCtrl** [comment]
Thanks @pedrobaeza, but the error happen if add a required field to model, you can see the second example.
```python
class CrmLead(models.Model):
    _inherit = 'crm.lead'

    test_requirement = fields.Char(string="Test", required=True)
```

**Comment by pedrobaeza** [comment]
@NothingCtrl, for that case, you should provide a default value that assures that the creation from kanban is correct. If that default value is not possible, then you shouldn't use the kanban quick create option.
