### ISSUE TITLE
Odoo Error when scanning for Internal Transfers

### ISSUE THREAD

**Issue by femioz** [odoo/odoo#25585]
I get this error when scanning barcodes for internal transfers in the inventory app. It happens after the second scan.

Odoo Server Error

**Impacted versions:**

Odoo 10

**Steps to reproduce:**

Openened the Odoo inventory app
Selected Internal Transfers
On first scan of barcode all seems fine 
On second scan I get the error below

**Current behavior:**

I get this error below

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5496, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5394, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/barcodes/models/barcode_events_mixin.py", line 21, in _on_barcode_scanned
    return self.on_barcode_scanned(barcode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/gait_do_scan/models/stock.py", line 32, in on_barcode_scanned
    res = super(StockPicking, self).on_barcode_scanned(barcode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/stock_barcode/models/inherited_stock_picking.py", line 226, in on_barcode_scanned
    package_source = self.env['stock.quant.package'].search([('name', '=', barcode), ('location_id', 'child_of', self.location_id.id)], limit=1)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1518, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4242, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: memory exhausted at or near "("
LINE 1: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((..

Expected behavior:

No error should pop up. I can send all configuration details if needed. Please help

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
May be it is because of  custom `gait_do_scan` module or
better to add Official ticket at https://www.odoo.com/help as `stock_barcode` is enterprise module.

**Comment by sswapnesh** [comment]
@Yenthe666  We can close this as there is no Response (and also It seems it is because of custom `gait_do_scan` module or )
