### ISSUE TITLE
[8.0 bitnami] Could not get content for defined in bundle 'web.assets_backend'

### ISSUE THREAD

**Issue by etiennebonnafoux** [odoo/odoo#25613]
Impacted versions: 8.0

Steps to reproduce: I restart my odoo v8.0 server and this happend

Current behavior: Not loading the .css links

Expected behavior:

Video/Screenshot link (optional): 
![error](https://user-images.githubusercontent.com/23340020/42307690-7e369a02-805d-11e8-8d88-515a7a23e7f7.png)

And I get in my openerp-server.log this:
2018-07-05 03:29:45,647 5579 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 1355, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/opt/bitnami/python/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/routing.py", line 1423, in match
    raise NotFound()
NotFound: 404: Not Found

Please, someone had a solution?
Thank you very much

**Comment by pedrobaeza** [comment]
8.0 is a deprecated non supported version, but any way, this error is something on the Bitnami side.

Closing by the reasons above.
