### ISSUE TITLE
Google Calendar : Can't sync, UserError object has no attribute 'code'

### ISSUE THREAD

**Issue by ertus-odoo** [odoo/odoo#25627]
Impacted versions:
Odoo 10.0 Enterprise Edition

Steps to reproduce:
I was invited in Google Event by mail, I accepted, redirected to Google Calendar when I clicked "Yes" on the invitation in Google mail. Everything works. But when I was back in Odoo and clicked on "Sync with Google Calendar" I had this error message.

Current behavior:
Traceback (most recent call last):
  File "/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/ert/ert10/odoo/odoo_20180627/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/current/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/odoo/current/addons/google_calendar/models/google_calendar.py", line 591, in synchronize_events
    res = recs.update_events(lastSync)
  File "/odoo/current/addons/google_calendar/models/google_calendar.py", line 848, in update_events
    if e.code in (401, 410,):
AttributeError: 'UserError' object has no attribute 'code'

Expected behavior:

Video/Screenshot link (optional):
https://lh3.googleusercontent.com/7kjk2N7nzE2DELcA1dooStJGzEY31xlC5-nT-ob1YSEFPhDJUrqR7bcWcXGLZiJBEZy8QW5X4Z33LIJ6DFjTH7tBYQL5T0-h3bgBTAwUygTg1UEC5wpQpK46lxghUXx4TzukcMwF

**Comment by mart-e** [comment]
@nim-odoo seems you already fixed it in 11.0 at 6bbf38e171ab0ba694e1acb9bcc9e1909
No objection to backport it to 10?

**Comment by mart-e** [comment]
Fixed in 10.0 at 8b8adcb5e6391d25fab9499c9cf1ccb585515db2
Please note that you get an error but it was not properly catched. Now you will see the correct error message.
