### ISSUE TITLE
exporting to Excel fields longer than 32767 characters results in error

### ISSUE THREAD

**Issue by gmarcon** [odoo/odoo#25653]
Impacted versions: 10.0 (maybe others)

Steps to reproduce: try to export a field longer than 32.767 characters

Current behavior: Exception: String longer than 32767 characters is thrown

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 74, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 1421, in index
    return self.base(data, token)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 1366, in base
    return request.make_response(self.from_data(columns_headers, import_data),
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 1457, in from_data
    workbook.save(fp)
  File "/usr/lib/python2.7/site-packages/xlwt/Workbook.py", line 643, in save
    doc.save(filename, self.get_biff_data())
  File "/usr/lib/python2.7/site-packages/xlwt/Workbook.py", line 618, in get_biff_data
    shared_str_table   = self.__sst_rec()
  File "/usr/lib/python2.7/site-packages/xlwt/Workbook.py", line 580, in __sst_rec
    return self.__sst.get_biff_record()
  File "/usr/lib/python2.7/site-packages/xlwt/BIFFRecords.py", line 77, in get_biff_record
    self._add_to_sst(s)
  File "/usr/lib/python2.7/site-packages/xlwt/BIFFRecords.py", line 92, in _add_to_sst
    u_str = upack2(s, self.encoding)
  File "/usr/lib/python2.7/site-packages/xlwt/UnicodeUtils.py", line 55, in upack2
    raise Exception('String longer than 32767 characters')
Exception: String longer than 32767 characters

Expected behavior: Export should work

Proposed patch:

Excel does not allow cells with text longer than 32.767 characters, just truncate such strings.

addons/web/controllers/main.py
1449c1449
<                     cell_value = re.sub("\r", " ", cell_value)
---
>                     cell_value = re.sub("\r", " ", cell_value)[:32767]

**Comment by moylop260** [comment]
You are right:
 - https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
   - `Total number of characters that a cell can contain | 32,767 characters`

**Comment by mart-e** [comment]
@gmarcon thank you for the report and patch. Would you mind making a pull request so we can give you the right attribution?

**Comment by gmarcon** [comment]
Pull request created: https://github.com/odoo/odoo/pull/25698
Being my first pull request, please be gentle! ;)

**Comment by gmarcon** [comment]
I closed the previous pull request and created a new one targeting version 11: https://github.com/odoo/odoo/pull/25700
