### ISSUE TITLE
[11.0]   Odoo 11 Server Error 

### ISSUE THREAD

**Issue by bacargan** [odoo/odoo#25708]
Hi, I am trying to use odoo in Turkish. When i enter Quotations > create > and customer section, it works. but when i press "add an item" section it generates an error. After i change language to english(also german and spanish) in preferances and try again it works perfectly fine.
Could someone help me about the error? what is wrong?

The error code is:
```
Hata:
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 5095, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4990, in _onchange_eval
    method_res = method(self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_stock\models\sale_order.py", line 161, in _onchange_product_id_uom_check_availability
    self._onchange_product_id_check_availability()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\sale_stock\models\sale_order.py", line 176, in _onchange_product_id_check_availability
    (self.product_uom_qty, self.product_uom.name, product.virtual_available, product.uom_id.name, self.order_id.warehouse_id.name)
TypeError: not enough arguments for format string
```

**Comment by Yenthe666** [comment]
@mart-e this might be a language related thing. Could you check please?

**Comment by mart-e** [comment]
@Yenthe666 these errors are due to a missing/bad `%s` placeholder in the translation, anyone with a Transifex account can easily check it ;-)
But in this case it was already fixed at
https://www.transifex.com/odoo/odoo-11/translate/#tr/sale_stock/119301218?q=text%3A'You+plan+to+sell'

@bacargan it was fixed 2 weeks ago, please check your Odoo sources are up to date and then reload your translation (Settings > Load a Translation and be sure to be in developer mode and check the "overwrite existing terms" box)

**Comment by Yenthe666** [comment]
Yeah, I just didn't have enough time. Thanks @mart-e

**Comment by Yenthe666** [comment]
Thanks for the tip, indeed that would narrow it down quite fast. 😉

**Comment by bacargan** [comment]
Thanks guys. I have cleared message argument line 176. Now it rocks! Before that I updated source and language but nothing has changed. As you have told there is bad %s argument. Thanks Mart-e!
