### ISSUE TITLE
WMS Location error in creation / duplicating existing record

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#2572]
install wms
-----  go to warehouse
----> go to location
----> Create new or 
-------------------select the existing location = Physical Locations/WH/Stock ( go to more and duplicate the existing one)
Traceback (most recent call last):
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/opt/orchiderp/trading_demo/odoo/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/opt/orchiderp/trading_demo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/orchiderp/trading_demo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/models.py", line 4724, in copy
    new_id = self.create(cr, uid, data, context)
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/addons/stock/stock.py", line 160, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/models.py", line 3972, in create
    record = self.browse(self._create(old_vals))
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/orchiderp/trading_demo/odoo/openerp/models.py", line 4139, in _create
    cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by pna-odoo** [comment]
I can't reproduce it with latest code.

**Comment by quiero** [comment]
I encountered a very similar one with the latest code.. v9c
Please contact me if you need any more information (like a database backup)

2016-06-10 13:34:22,599 4490 ERROR v9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 896, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/stock/stock.py", line 3796, in create
    wh_loc_id = location_obj.create(cr, uid, loc_vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/stock/stock.py", line 147, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4317, in _create
    cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by jco-odoo** [comment]
Are you sure that parent_left and parent_right were calculated in your database?  (that the current location has values for the parent_left/parent_right fields?)

**Comment by quiero** [comment]
Hello, Josse,

no, not at all,
though I just started exploring this part of functionality. Supposedly they
should be in place by default, right? Where can I check up on that?
(I'm familiar with the shell mode and can explore database directly if
needed) so you can tell me in plain language, lol )

Thanks for a prompt reply,
Paul

**Comment by lukastorres** [comment]
I encountered a similar issue.
Can you help me to fix this issue?
Thanks.
