### ISSUE TITLE
[11.0] POS Error using pricelists based in another pricelist

### ISSUE THREAD

**Issue by Luckin93** [odoo/odoo#25740]
Impacted versions:
11
Steps to reproduce:
1. Set the pricelist in POS
2. Open POS
3. Select Product
Current behavior
Uncaught Error: QWeb2 - template['Product']: Runtime Error: TypeError: Cannot read property 'items' of undefined
http://localhost:8069/web/content/1807-d3e68cc/web.assets_common.js:3689
Rastreo de error:
Error: QWeb2 - template['Product']: Runtime Error: TypeError: Cannot read property 'items' of undefined
    at Object.exception (http://localhost:8069/web/content/1807-d3e68cc/web.assets_common.js:3689:7)
    at Engine.eval (eval at _render (http://localhost:8069/web/content/1807-d3e68cc/web.assets_common.js:3731:73), <anonymous>:32:29)
    at Engine._render (http://localhost:8069/web/content/1807-d3e68cc/web.assets_common.js:3730:296)
    at Engine.render (http://localhost:8069/web/content/1807-d3e68cc/web.assets_common.js:3730:151)
    at Class.render_product (http://localhost:8069/web/content/1912-8062fd4/point_of_sale.assets.js:357:312)
    at Class.renderElement (http://localhost:8069/web/content/1912-8062fd4/point_of_sale.assets.js:359:149)
    at Class.<anonymous> (http://localhost:8069/web/content/1912-8062fd4/point_of_sale.assets.js:356:1911)
    at triggerEvents (http://localhost:8069/web/content/1813-57f6297/web.assets_backend.js:39:179)
    at child.trigger (http://localhost:8069/web/content/1813-57f6297/web.assets_backend.js:34:223)
    at child._onModelEvent (http://localhost:8069/web/content/1813-57f6297/web.assets_backend.js:67:14)

Expected behavior:
Get price of pricelist formula in pricelist. 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you put both pricelists as available in POS config?

**Comment by sswapnesh** [comment]
@pedrobaeza 
I can confirm this Behaviour.
This will happen if Dependent Pricelist are not available in `Available Pricelists` in PoS Configuration.

@Luckin93 
To solve it add all dependent Pricelists in `Available Pricelists` in your PoS Configuration
![85](https://user-images.githubusercontent.com/16624719/42648146-99cc0b50-8623-11e8-85dd-0572551a3f3b.png)

**Comment by Luckin93** [comment]
Thanks for  you help @pedrobaeza and @sswapnesh ! The problem is solved now!

**Comment by sswapnesh** [comment]
@pedrobaeza 
I will prefer to keep this Issue open as We can Improve situation by handling this in PoS config.(May be forcefully add all dependent Pricelist as available )

**Comment by pedrobaeza** [comment]
@sswapnesh Adding that kind of checks is to get complicated code for something that is very logical. For me, that's a configuration option easily fixable, not a bug/improvement. It's not like other checks that prevent an inconsistent state.

**Comment by mthiermann** [comment]
> @sswapnesh Adding that kind of checks is to get complicated code for something that is very logical. For me, that's a configuration option easily fixable, not a bug/improvement. It's not like other checks that prevent an inconsistent state.

While the last post is from 2018, I don't find this as logical as you do, because all price lists configured under "Avaialble Pricelists" are then selectable in the POS, which I don't think makes any sense at all. Especially when price lists reference each other.
