### ISSUE TITLE
[11.0] Wrong field sequence in account_invoice_view.xml

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#25757]
Impacted versions: 11

Steps to reproduce: with account installed start instance with -u account

Current behavior: xml error, cause line https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_invoice_view.xml#L224 not finds the required field has_outstanding, cause that is defined firsttime in https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_invoice_view.xml#L227

```
2018-07-13 12:59:59,592 20822 INFO XXX odoo.addons.base.ir.ir_ui_view: Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]
2018-07-13 12:59:59,604 20822 WARNING XXX odoo.modules.loading: Transient module states were reset
2018-07-13 12:59:59,605 20822 ERROR XXX odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1055, in postprocess_and_fields
    for name, lines in itertools.groupby(sorted(missing), itemgetter(0)):
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
    'xmlid': view.xml_id or not_avail,
ValueError: Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"
```

Expected behavior: no errors when update

**Comment by DR4RCON** [comment]
Same as https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_invoice_view.xml#L366 and https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_invoice_view.xml#L369

**Comment by mart-e** [comment]
Hello,

This shouldn't be an issue. The field value must be present in the view but it doesn't have to be be present.
Are you sure you do not have another module removing this field in an xpath (e.g. `position="replace"` in upper level)?
Could you reproduce this on a standard Odoo?

**Comment by DR4RCON** [comment]
perhaps has something to do with account_payment, here full traceback

```
2018-07-13 13:46:36,058 21982 INFO XXXX odoo.modules.loading: loading account_payment/views/account_invoice_views.xml
2018-07-13 13:46:36,193 21982 INFO XXXX odoo.addons.base.ir.ir_ui_view: Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]
2018-07-13 13:46:36,198 21982 WARNING XXXX odoo.modules.loading: Transient module states were reset
2018-07-13 13:46:36,199 21982 ERROR XXXX odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'XXXX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1061, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3108, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nField \'has_outstanding\' used in attributes must be present in view but is missing:\n - \'has_outstanding\' in attrs="{\'invisible\': [(\'has_outstanding\',\'=\',False)]}"\n\nFehler Kontext:\nAnsicht `account.invoice.view.form.inherit.payment`\n[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1473, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3108, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]
None" while parsing /opt/odoo/addons/account_payment/views/account_invoice_views.xml:3, near
<record id="account_invoice_view_form_inherit_payment" model="ir.ui.view">
            <field name="name">account.invoice.view.form.inherit.payment</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
                    <xpath expr="//div[@name='button_box']" position="inside">
                        <button name="action_view_transactions" type="object" class="oe_stat_button" icon="fa-money" attrs="{'invisible': [('payment_tx_count', '=', 0)]}">
                            <field name="payment_tx_count" widget="statinfo" string="Transactions"/>
                        </button>
                    </xpath>
            </field>
    </record>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'XXXX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1061, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3108, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nField \'has_outstanding\' used in attributes must be present in view but is missing:\n - \'has_outstanding\' in attrs="{\'invisible\': [(\'has_outstanding\',\'=\',False)]}"\n\nFehler Kontext:\nAnsicht `account.invoice.view.form.inherit.payment`\n[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1437, in _update
    record.write(values)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3108, in write
    field.determine_inverse(records)
  File "/opt/odoo/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Field 'has_outstanding' used in attributes must be present in view but is missing:
 - 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Fehler Kontext:
Ansicht `account.invoice.view.form.inherit.payment`
[view_id: 1525, xml_id: account_payment.account_invoice_view_form_inherit_payment, model: account.invoice, parent_id: 460]
None" while parsing /opt/odoo/addons/account_payment/views/account_invoice_views.xml:3, near
<record id="account_invoice_view_form_inherit_payment" model="ir.ui.view">
            <field name="name">account.invoice.view.form.inherit.payment</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
                    <xpath expr="//div[@name='button_box']" position="inside">
                        <button name="action_view_transactions" type="object" class="oe_stat_button" icon="fa-money" attrs="{'invisible': [('payment_tx_count', '=', 0)]}">
                            <field name="payment_tx_count" widget="statinfo" string="Transactions"/>
                        </button>
                    </xpath>
            </field>
    </record>
```

**Comment by mart-e** [comment]
Are  you updating account or account_payment? 
Could you check the list of views that inherit from `account.invoice_form`?
You can check that in Settings > Technical > User Interface > Views, in the tab Inherited Views

**Comment by DR4RCON** [comment]
680 | 16 | Account Invoice | sale.account_invoice_form
687 | 16 | account.invoice.form.inherit.sale | sale.invoice_form_inherit_sale
951 | 16 | account.invoice.form.sale.stock | sale_stock.invoice_form_inherit_sale_stock
1,525 | 16 | account.invoice.view.form.inherit.payment | account_payment.account_invoice_view_form_inherit_payment

**Comment by DR4RCON** [comment]
First question is answered with account. Using -u account

**Comment by DR4RCON** [comment]
Content seems  to be same. When go into edit mode in backend for that view, and integrate a space as example I cannot save it anymore and get as response:
```
Error while validating constraint

Field 'has_outstanding' used in attributes must be present in view but is missing:
- 'has_outstanding' in attrs="{'invisible': [('has_outstanding','=',False)]}"

Error context:
View `account.invoice.form`
[view_id: 460, xml_id: account.invoice_form, model: account.invoice, parent_id: n/a] 
```

**Comment by DR4RCON** [comment]
I tried to switch positions of that invisible field in header and in sheet, but get same result.

**Comment by DR4RCON** [comment]
Could it be a problem, that this attribute definition which uses has_outstanding is outside header or sheet?

**Comment by DR4RCON** [comment]
Upps what have I made wrong?

**Comment by mart-e** [comment]
@DR4RCON I merged all comments in one to keep it easier for the reading ;-)

Regarding your problem, are you sure the account.invoice_form do contains the ` <field name="has_outstanding" invisible="1"/>` field?

**Comment by DR4RCON** [comment]
Yes it has the field in it. We are speaking about a database on a production server. This instance is running with --workers=5
Before started to try update it, I made a backup. When I load the backup to my local machine and update there all works fine. But Iam using pycharm which currently doesnt support --workers but all other from this environments are equal. I often have thought that there is a lot diffrent when using this param. Sometimes I get this errors:  ```ERROR: could not serialize access due to concurrent update```
Could my problems when updating rely on that param workers?

**Comment by mart-e** [comment]
As you are not able to save the view by just adding a space, it makes me believe the source of the issue is in the database.
I believe the issue in the view(s?) was present for some time but never noticed. We added a better validation of the views a few months ago, at 7b3796d77c198553b1f9fe422a46eb477df3e3f3.
So now, even adding a space triggers the validation, which fails.

Sorry but I don't really know with that information. To investigate more, it would require a direct access to the server/database.
If you have a support contract, you can contact them to do so.

**Comment by DR4RCON** [comment]
Ok, cause I could update the production database on local system, its not longer a problem. And I could not reproduce with databases based on current head I close this.
Thank you for investigating.

**Comment by mstuttgart** [comment]
Same error here, with `sale.order` view of `sale_timesheet` module. In my case, the group tag of field cause this error.

https://www.odoo.com/forum/help-1/question/error-when-installing-ecommerce-module-mo-count-odoo-11-enterprise-127417

I need to remove group attributes of fields (keep tag attribute in xml file) to work.
