### ISSUE TITLE
html = '<html><body>%s</body></html>'.encode('ascii') % html TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

### ISSUE THREAD

**Issue by Fransmoiz** [odoo/odoo#25797]
> I have some proble whene I was creating odoo 11 postgres 

2018-07-17 06:22:37,661 3034 ERROR moiztest werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/moiztest/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/opt/odoo/moiztest/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/moiztest/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/moiztest/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/moiztest/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/moiztest/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/moiztest/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/moiztest/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/moiztest/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/moiztest/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/moiztest/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/moiztest/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/moiztest/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/moiztest/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/opt/odoo/moiztest/odoo/http.py", line 1269, in flatten
    self.response.append(self.render())
  File "/opt/odoo/moiztest/odoo/http.py", line 1262, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/moiztest/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/qweb.py", line 349, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: unsupported operand type(s) for %: 'bytes' and 'bytes'
Traceback (most recent call last):
  File "/opt/odoo/moiztest/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/moiztest/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/moiztest/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7fd491abf9d8>, 'web.assets_common', 'en_US', True, False, None, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/moiztest/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/moiztest/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/moiztest/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_content at 0x7fd491abfb70>, 'web.assets_common', 'en_US', (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_171_23
  File "<template>", line 2, in body_call_content_22
  File "<template>", line 3, in set_17
  File "<decorator-gen-38>", line 2, in _get_asset_nodes
  File "/opt/odoo/moiztest/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 295, in _get_asset_nodes
    files, remains = self._get_asset_content(xmlid, options)
  File "<decorator-gen-39>", line 2, in _get_asset_content
  File "/opt/odoo/moiztest/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/moiztest/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 324, in _get_asset_content
    for el in html.fragments_fromstring(template):
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 623, in fragments_fromstring
    html = '<html><body>%s</body></html>'.encode('ascii') % html
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

Error to render compiling AST
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
Template: 171
Path: /templates/t/t/t[1]/t[1]
Node: <t t-call-assets="web.assets_common" t-js="false"/>

> Please help me

**Comment by xmo-odoo** [comment]
You are running Odoo on Python 3.4, which is not supported. We support 2.7, 3.5 and 3.6 (and work is ongoing to fix 3.7).

One of the reasons we start support of Python 3 at 3.5 are porting/cross-versions features like the `%` operators on byte strings.

**Comment by pawansharma123** [comment]
Hello Yenthe
i am getting same error while creating database. I'm installed odoo v11 on 10/Aug/2018 from you installation script -->  https://github.com/Yenthe666/InstallScript.git. I am using odoo different versions 9.0/10.0/11.0 on same machine.
