### ISSUE TITLE
[11.0] Can't install or update any addons from windows

### ISSUE THREAD

**Issue by p4cm4n** [odoo/odoo#25808]
Impacted versions: 11.0

Steps to reproduce: After a default install I can't seem to use any option from the applications menu

Current behavior: I tried every menu option, but it doesn't seem to accept any of the orders, it shows the apps and modules available, but no option really works, here's a log of the event:

`

    2018-07-17 07:40:18,205 4004 DEBUG MiCompany odoo.api: call base.module.update(29,).
    update_module()
    2018-07-17 07:40:18,205 4004 INFO MiCompany odoo.addons.base.module.module: ALLOW access to module.update_list on [] to user MiUsername #1 via 172.16.0.108
    2018-07-17 07:40:21,263 4004 INFO ? werkzeug: 172.16.0.108 - - [17/Jul/2018 07:40:21] "GET /web/static/src/img/spin.png HTTP/1.1" 200 -
    2018-07-17 07:40:21,497 4004 INFO MiCompany werkzeug: 172.16.0.108 - - [17/Jul/2018 07:40:21] "POST /web/dataset/call_button HTTP/1.1" 200 -
    2018-07-17 07:40:23,244 4004 DEBUG MiCompany odoo.api: call base.module.update().default_get(['state', 'updated', 'added'])
    2018-07-17 07:40:23,260 4004 INFO MiCompany werkzeug: 172.16.0.108 - - [17/Jul/2018 07:40:23] "POST /web/dataset/call_kw/base.module.update/default_get HTTP/1.1" 200 -
    2018-07-17 07:40:23,400 4004 DEBUG MiCompany odoo.api: call res.users().check_access_rights(operation='write', raise_exception=False)
    2018-07-17 07:40:23,400 4004 INFO MiCompany werkzeug: 172.16.0.108 - - [17/Jul/2018 07:40:23] "POST /web/dataset/call_kw/res.users/check_access_rights HTTP/1.1" 200 -
    2018-07-17 07:40:23,416 4004 DEBUG MiCompany odoo.api: call ir.model.data().xmlid_to_res_id(xmlid='base.group_no_one')`

Expected behavior: It should install/update the modules as needed.

Video/Screenshot link (optional):

**Comment by p4cm4n** [comment]
Furthermore, if i set all permissions to 777 (total control for all users, in win) i get the following error:

`

Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 924, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 912, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\wizard\base_module_upgrade.py", line 76, in upgrade_module
    odoo.modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'bi_professional_reports_templates-11'

`

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or deployment issues.

The error you are showing us suggest you have an issue with a custom module `bi_professional_reports_templates`, not the supported ones.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by p4cm4n** [comment]
Yeah, I downloaded that one and copied manually to help testing (as I said in the last comment) but the bug is not with that add on, the bug is "Can't install or update any addons from windows"

**Comment by mart-e** [comment]
Then, please share more information. Maybe give a video to show what is not working exactly. I can't figure it out from your message.

**Comment by ikram-alaoui-belrhiti** [comment]
i have the same issue i can't install or update module odoo 11 !!!
how you are going to solve the problem?

`2019-12-17 11:03:07,867 8208 INFO Test odoo.addons.base.module.module: ALLOW access to module.update_list on [] to user ikram.alaoui@ingenov.com #1 via 127.0.0.1
2019-12-17 11:03:10,926 8208 INFO ? werkzeug: 127.0.0.1 - - [17/Dec/2019 11:03:10] "GET /web/static/src/img/spin.png HTTP/1.1" 200 -
2019-12-17 11:03:45,539 8208 INFO Test werkzeug: 127.0.0.1 - - [17/Dec/2019 11:03:45] "POST /longpolling/poll HTTP/1.1" 200 -
c2019-12-17 11:04:36,109 8208 INFO Test werkzeug: 127.0.0.1 - - [17/Dec/2019 11:04:36] "POST /longpolling/poll HTTP/1.1" 200 -
2019-12-17 11:05:26,671 8208 INFO Test werkzeug: 127.0.0.1 - - [17/Dec/2019 11:05:26] "POST /longpolling/poll HTTP/1.1" 200 -
2019-12-17 11:05:35,802 8208 INFO db_prod odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.`
