### ISSUE TITLE
adding tag_ids to the lines of timesheet form causes a Javascript exception

### ISSUE THREAD

**Issue by gmarcon** [odoo/odoo#25821]
Impacted versions: 10.0

Steps to reproduce:
- add tag_ids fields to the tree of timesheet_ids in the view form for hr_timesheet_sheet.sheet
- edit timesheet in the summary page adding some hours, as soon as you change focus on the next cell the Exception is triggered
- if editing the timesheet in the details page no error is triggered

Current behavior: Javascript Exception
```http://odoo10/web/static/src/js/views/form_relational_widgets.js:472
Traceback:
TypeError: (ids || []).slice is not a function
    at Class.set_value (http://odoo10/web/static/src/js/views/form_relational_widgets.js:472:27)
    at Class.prototype.(anonymous function) [as set_value] (http://odoo10/web/static/src/js/framework/class.js:89:38)
    at http://odoo10/web/static/src/js/views/form_relational_widgets.js:979:23
    at Function._.each._.forEach (http://odoo10/web/static/lib/underscore/underscore.js:150:9)
    at http://odoo10/web/static/src/js/views/form_relational_widgets.js:975:15
    at Function._.every._.all (http://odoo10/web/static/lib/underscore/underscore.js:237:12)
    at Class.is_valid (http://odoo10/web/static/src/js/views/form_relational_widgets.js:974:23)
    at Class.is_syntax_valid (http://odoo10/web/static/src/js/views/form_relational_widgets.js:874:36)
    at Class.<anonymous> (http://odoo10/web/static/src/js/views/form_view.js:1167:23)
    at Class.trigger (http://odoo10/web/static/src/js/framework/mixins.js:222:31)
```

Expected behavior: no exception

The cause is in the flattening performed by generate_o2m_value in the WeeklyTimesheet  widget:
https://github.com/odoo/odoo/blob/10.0/addons/hr_timesheet_sheet/static/src/js/timesheet.js#L330-L340

The solution is to just ignore the tag_ids field in the widget, as the field line_id is ignored; this is the only many2many field of the model account.analytic.line and can be safely ignored.

**Comment by Yenthe666** [comment]
Dear @gmarcon,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
