### ISSUE TITLE
odoo12 failed to create database

### ISSUE THREAD

**Issue by hillbun** [odoo/odoo#25837]
Impacted versions:
odoo12, github master branch, postgres:9.6.3  

Steps to reproduce:

when create database, it returns errors:

Database creation error: hash could not be identified

2018-07-18 09:52:51,166 1 ERROR abcde odoo.http: hash could not be identified
Traceback (most recent call last):
  File "/odoo/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/odoo/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/odoo/odoo/service/common.py", line 30, in exp_authenticate
    return res_users.authenticate(db, login, password, user_agent_env)
  File "/odoo/odoo/addons/base/models/res_users.py", line 562, in authenticate
    uid = cls._login(db, login, password)
  File "/odoo/odoo/addons/base/models/res_users.py", line 540, in _login
    user.sudo(user_id).check_credentials(password)
  File "/odoo/addons/auth_crypt/models/res_users.py", line 63, in check_credentials
    return super(ResUsers, self).check_credentials(password)
  File "/odoo/odoo/addons/base/models/res_users.py", line 299, in check_credentials
    .verify_and_update(password, hashed)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/passlib/context.py", line 2615, in verify_and_update
    record = self._get_or_identify_record(hash, scheme, category)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/passlib/context.py", line 2260, in _get_or_identify_record
    return self._identify_record(hash, category)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/passlib/context.py", line 1457, in identify_record
    raise ValueError("hash could not be identified")
ValueError: hash could not be identified

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why do you put the same issue with the exact information like the previous one? Any way, you are using a branch that is under development, and thus it's expected to fail sometimes. You should only report possible issues under stable branches.

**Comment by hillbun** [comment]
what's odoo12 stable branch?

**Comment by Yenthe666** [comment]
@hillbun Odoo 12 is not yet out and there is no stable branch for it.

**Comment by gustavovalverde** [comment]
I was almost going to report a few things from v12. So we're not supposed to report anything while in the `master` branch?

**Comment by gdgellatly** [comment]
@gustavovalverde Personally I have always reported issues for master in the 2 months prior to release, usually by directly pinging the author or commenting on testing the PR's that come through.  

I'd rather do that, than wait another year after release to have major issues fixed.  I know it saved some absolute whoppers from making it into v11.

But I think there is a big difference between people with years of history working on the project and who understand it, and know what a mistake/bug is rather than just a broken master branch, than someone who decides to install master for the first time.

**Comment by jeffery9** [comment]
have the same issue...    
 date
`Tue Nov 13 01:51:53 PST 2018`


![image](https://user-images.githubusercontent.com/1404460/48405219-d58be700-e76c-11e8-8179-396124d7830c.png)
