### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute ' '

### ISSUE THREAD

**Issue by zhafariirsyad** [odoo/odoo#25884]
I'm From Indonesia, can you help me what should i do to fix the errors
I really need your help to solve my error when i klik button print report using QWEB in odoo 10
---------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fai/odoo-10.0/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/fai/odoo-10.0/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/fai/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/home/fai/odoo-10.0/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/home/fai/odoo-10.0/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/home/fai/odoo-10.0/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/fai/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: 'NoneType' object has no attribute 'barang'
Traceback (most recent call last):
  File "/home/fai/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_612_17
  File "<template>", line 3, in body_call_content_16
  File "<template>", line 4, in foreach_15
  File "<template>", line 5, in body_call_content_14
AttributeError: 'NoneType' object has no attribute 'barang'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'barang'
Template: 612
Path: /templates/t/t/t/t/div/table/t
Node: <t t-foreach="latihan.barang" t-as="l">
                                <tr>
                                    <td><span t-field="l.name"/></td>
                                    <td><span t-field="l.jenis"/></td>
                                    <td><span t-field="l.stok"/></td>
                                    <td><span t-field="l.harga"/></td>
                                    
                                    <td><span t-field="l.distributor"/></td>
                                    <td><span t-field="l.tgl_masuk"/></td>
                                    <td><span t-field="l.description"/></td>
                                </tr>
                            </t>    
		                    
---------------------------------------------------------------------------------------------------------------------------------

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

You can make also a question on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
