### ISSUE TITLE
Facturación

### ISSUE THREAD

**Issue by MariaGamez** [odoo/odoo#25931]
Me sale este error al intentar imprimir facturas, no con todas solo con algunas.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_with_payments_1909
  File "<template>", line 2, in body_call_content_1908
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 306, in l10n_mx_edi_amount_to_text
    words = self.currency_id.with_context(lang=self.partner_id.lang or 'es_ES').amount_to_text(amount_i).upper()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 110, in amount_to_text
    amt_value=_num2words(int(integer_value), lang=lang.iso_code),
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 97, in _num2words
    return num2words(number, lang=lang).title()
  File "/usr/local/lib/python3.5/dist-packages/num2words/__init__.py", line 91, in num2words
    lang = lang[:2]
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1600, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1549, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 624, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 662, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1189, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1198, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_495_1828
  File "<template>", line 2, in body_call_content_1827
  File "<template>", line 3, in foreach_1826
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_with_payments_1909
  File "<template>", line 2, in body_call_content_1908
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_mx_edi/models/account_invoice.py", line 306, in l10n_mx_edi_amount_to_text
    words = self.currency_id.with_context(lang=self.partner_id.lang or 'es_ES').amount_to_text(amount_i).upper()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 110, in amount_to_text
    amt_value=_num2words(int(integer_value), lang=lang.iso_code),
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 97, in _num2words
    return num2words(number, lang=lang).title()
  File "/usr/local/lib/python3.5/dist-packages/num2words/__init__.py", line 91, in num2words
    lang = lang[:2]
TypeError: 'bool' object is not subscriptable

Error to render compiling AST
TypeError: 'bool' object is not subscriptable
Template: account.report_invoice_document_with_payments
Path: /templates/t/t/div/t[3]/p/span
Node: <span t-esc="o.l10n_mx_edi_amount_to_text()"/>

**Comment by moylop260** [comment]
cc @luistorresm

**Comment by luistorresm** [comment]
Hola @MariaGamez 

Pudieras por favor proporcionarme un video donde muestres la configuración del partner de una de las facturas que te da el error? Especificamente el idioma,

Y más información de los SHA que tienes en tu servidor?

Saludos

**Comment by MariaGamez** [comment]
![aadvgsdg](https://user-images.githubusercontent.com/41591368/43147948-1ce93c4e-8f19-11e8-8cee-3e38b6321b6f.png)

**Comment by Yenthe666** [comment]
Hi guys,

This report is really missing info, reproducable steps and its not in English.
Please make a new bug report in English with clear information.

**Comment by nhomar** [comment]
@MariaGamez Can you share pliz the enterprise code and a proper Issue in odoo.com? the support of this modules is only under enterprise.

BTW, remember try to put issues here (which are valid) in english.

Regards.

**Comment by nhomar** [comment]
>> enterprise code

I meant Enterprise Issue in odoo.com (not the code)
