### ISSUE TITLE
[11.0] TypeError: __init__() missing 2 required positional arguments: 'model' and 'dotnames' when creating a purchase order

### ISSUE THREAD

**Issue by HaraldPanten** [odoo/odoo#25969]
Impacted versions: Odoo V11 Community and Enterprise

Steps to reproduce: Just create a Request for Quotation in purchase management module, select a supplier and then add a new order line.

Current behavior: An error is shown.

Expected behavior: It should let the user create several order lines.

Video/Screenshot link (optional): No Screenshot

This is the error message:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5198, in onchange
    result['value'] = diff(record, before, after)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5116, in diff
    line_diff = diff(line, vals0, vals, subnames)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5109, in diff
    result[name] = field.convert_to_onchange(new[name], record, subnames)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2221, in convert_to_onchange
    names = names.copy()
TypeError: __init__() missing 2 required positional arguments: 'model' and 'dotnames'`

**Comment by Yenthe666** [comment]
Hi @HaraldPanten,

Thanks a lot for your bug report. I've just tested this and I can confirm this is indeed a bug in the 11.0 stable:
![image](https://user-images.githubusercontent.com/6352350/43199790-75ee1bc0-9013-11e8-9a1b-3820fa0bc3c0.png)

@mart-e, @nim-odoo or @sle-odoo can one of you resolve this one? Its a very quick one to get.

**Comment by nle-odoo** [comment]
Hi @Yenthe666 

We are testing this fix https://github.com/odoo-dev/odoo/commit/53c1b0179

**Comment by Yenthe666** [comment]
Thanks a lot for the quick feedback, happy to hear that.

**Comment by HaraldPanten** [comment]
Perfect,

Thank you!

**Comment by Yenthe666** [comment]
Yep, works fine again!
