### ISSUE TITLE
error delegation from res.users model

### ISSUE THREAD

**Issue by mluchkin** [odoo/odoo#25987]
Hello Developers ! 
Odoo - 10.0

I have model with _inherits = {'res.users': 'user'}

```
class Man(models.Model):
    _inherits = {'res.users': 'user'}

    user = fields.Many2one(comodel_name='res.users', required=True,
                               ondelete='restrict')
    email = fields.Char(related='user.partner_id.email', inherited=True)
    phone = fields.Char(related='user.partner_id.phone', inherited=True)
```

On create record with this model all fine

if i change phone or email in record i have error : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/myadd/models/man.py", line 61, in write
    return super(Man, self).write(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3557, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3702, in _write
    self.env[parent_model].browse(parent_ids).write(parent_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/res_users.py", line 57, in write
    write_res = super(Users, self).write(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_users.py", line 805, in write
    res = super(UsersView, self).write(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_users.py", line 643, in write
    res = super(UsersImplied, self).write(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_users.py", line 358, in write
    res = super(Users, self).write(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3557, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3643, in _write
    cr.execute(query, params + (sub_ids,))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "odoo"
LINE 1: ..."write_date"=(now() at time zone 'UTC') WHERE id IN ('odoo')
```

`bad query: UPDATE "res_users" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN ('odoo')`

Why does this error occur?

**Comment by nhomar** [comment]
this is not for technical questions, can you kindly make it in help.odoo.com?
