### ISSUE TITLE
Buy route

### ISSUE THREAD

**Issue by rogeriojlle** [odoo/odoo#26049]
Impacted versions: 12.0.1.2

Steps to reproduce: on install module "purchase" on a fresh Odoo

Current behavior: "Buy route" is not showing on product 
```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 655, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3691, in _load_records
    data['record'].write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 147, in write
    vals['buy_pull_id'] = self._create_buy_rule()
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 178, in _create_buy_rule
    buy_pull_vals = self._get_buy_pull_rule()
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 122, in _get_buy_pull_rule
    raise UserError(_("Can't find any Buy route. Please create a route with the 'Buy' action for your receipts operation types."))
odoo.exceptions.UserError: ("Can't find any Buy route. Please create a route with the 'Buy' action for your receipts operation types.", '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 440, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 533, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 422, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 317, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 789, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 850, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 742, in parse
    self.parse(rec, mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 655, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3691, in _load_records
    data['record'].write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 147, in write
    vals['buy_pull_id'] = self._create_buy_rule()
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 178, in _create_buy_rule
    buy_pull_vals = self._get_buy_pull_rule()
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase_stock/models/stock.py", line 122, in _get_buy_pull_rule
    raise UserError(_("Can't find any Buy route. Please create a route with the 'Buy' action for your receipts operation types."))
odoo.tools.convert.ParseError: "Can't find any Buy route. Please create a route with the 'Buy' action for your receipts operation types.
" while parsing /usr/lib/python3/dist-packages/odoo/addons/purchase_stock/data/purchase_stock_data.xml:15, near
<record id="stock.warehouse0" model="stock.warehouse">
            <field name="buy_to_resupply" eval="True"/>
        </record>
```

Expected behavior: nothing issue

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @rogeriojlle,

Thanks a lot for your report but at the moment Odoo 12 is not yet released and it is not yet a stable version. I'm closing it off for this reason.
@sle-odoo you might want to check this in master 😉
