### ISSUE TITLE
[crm_partner_assign]: Traceback in reporting in Partnership Analysis

### ISSUE THREAD

**Issue by aba-odoo** [odoo/odoo#2604]
In master as well as v8 when we clicked on analysis report crm_claim 
it will raise an traceback:

Traceback (most recent call last):
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 476, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 495, in dispatch
result = self._call_function(*_self.params)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 311, in _call_function
return checked_call(self.db, *args, *_kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/service/model.py", line 113, in wrapper
return f(dbname, _args, *_kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 308, in checked_call
return self.endpoint(_a, *_kw)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 685, in __call__
return self.method(_args, *_kw)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/http.py", line 360, in response_wrap
response = f(_args, *_kw)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/addons/web/controllers/main.py", line 983, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/addons/web/controllers/main.py", line 975, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/api.py", line 204, in wrapper
return old_api(self, _args, *_kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/models.py", line 2127, in read_group
cr.execute(query, where_clause_params)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/sql_db.py", line 155, in wrapper
return f(self, _args, *_kwargs)
File "/home/bak/runbot/extra/runbot/static/build/17906-master-2d3c23/openerp/sql_db.py", line 230, in execute
res = self._obj.execute(query, params)
ProgrammingError: relation "crm_partner_report_assign" does not exist
LINE 3: FROM "crm_partner_report_assign" LEFT JOIN "res_

**Comment by Yenthe666** [comment]
I'm closing this issue as the other one is fixed and this is a duplicate.

Regards,
Yenthe
