### ISSUE TITLE
IntegrityError upgrading from 9f481d6c to 86eeea12

### ISSUE THREAD

**Issue by Nick-OpusVL** [odoo/odoo#2606]
If I upgrade a fairly large and feature-rich database to the latest 8.0 head (86eeea12) from revision 9f481d6c, with `--stop-after-init -d ep_stage1 -u all`, I get the following traceback in the log:

```
2014-09-22 10:33:16,622 29285 INFO ep_stage1 openerp.modules.module: module base: creating or updating database tables
2014-09-22 10:33:17,905 29285 ERROR ep_stage1 openerp.sql_db: bad query: ALTER TABLE "ir_act_window_view" ADD FOREIGN KEY ("act_window_id") REFERENCES "ir_act_window" ON DELETE cascade
Traceback (most recent call last):
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "ir_act_window_view" violates foreign key constraint "ir_act_window_view_act_window_id_fkey"
DETAIL:  Key (act_window_id)=(677) is not present in table "ir_act_window".

2014-09-22 10:33:17,906 29285 CRITICAL ep_stage1 openerp.service.server: Failed to initialize database `ep_stage1`.
Traceback (most recent call last):
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/modules/loading.py", line 304, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/modules/module.py", line 290, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/models.py", line 2740, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/nick.booker/cu/ep/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "ir_act_window_view" violates foreign key constraint "ir_act_window_view_act_window_id_fkey"
DETAIL:  Key (act_window_id)=(677) is not present in table "ir_act_window".

2014-09-22 10:33:17,909 29285 INFO ep_stage1 openerp.service.server: Initiating shutdown
2014-09-22 10:33:17,910 29285 INFO ep_stage1 openerp.service.server: Hit CTRL-C again or send a second signal to for
```

**Comment by Yenthe666** [comment]
Hi @Nick-OpusVL,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some. Sorry for this.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
