### ISSUE TITLE
could not start Odoo community version 11

### ISSUE THREAD

**Issue by skyzluo** [odoo/odoo#26090]
I just installed all requirements. Then, in Ubuntu 16.04, when I run

sudo python3 odoo-bin -w odoo -r odoo --addons-path=addons,../mymodules --db-filter=mydb$

I saw:

Traceback (most recent call last):
  File "odoo-bin", line 5, in <module>
    import odoo
  File "/var/www/odoo/odoo/odoo/__init__.py", line 84, in <module>
    from . import modules
  File "/var/www/odoo/odoo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/www/odoo/odoo/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/var/www/odoo/odoo/odoo/tools/__init__.py", line 10, in <module>
    from .convert import *
  File "/var/www/odoo/odoo/odoo/tools/convert.py", line 22, in <module>
    from .yaml_import import convert_yaml_import
  File "/var/www/odoo/odoo/odoo/tools/yaml_import.py", line 23, in <module>
    from .safe_eval import safe_eval
  File "/var/www/odoo/odoo/odoo/tools/safe_eval.py", line 21, in <module>
    from psycopg2 import OperationalError
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 104
    connection_factory=None, cursor_factory=None, async=False, **kwargs):
                                                      ^
SyntaxError: invalid syntax

Does anyone here know why?

Thanks,

**Comment by gdgellatly** [comment]
Because you are using python 3.7. And async is a reserved keyword in 3.7.

**Comment by skyzluo** [comment]
I see. Then, which version of Python should I use? Thanks

**Comment by skyzluo** [comment]
I see. Then, which version of Python should I use? Thanks

**Comment by gdgellatly** [comment]
You can use 3.7 but if you choose to install incompatible dependencies then
really that's on you to sort out. 3.6 will be safe.

**Comment by skyzluo** [comment]
Thank you very much for help. I change to Python 3.5. But I saw a new
problem which I don't know how to solve. Do you know why? Thanks

2018-08-01 02:45:44,696 9853 INFO ? odoo: Odoo version 11.0
2018-08-01 02:45:44,696 9853 INFO ? odoo: addons paths:
['/home/odoo/.local/share/Odoo/addons/11.0',
'/var/www/odoo/odoo/odoo/addons', '/var/www/odoo/odoo/addons',
'/usr/lib/python3/dist-packages/odoo/addons']
2018-08-01 02:45:44,696 9853 INFO ? odoo: database: odoo@localhost:5432
2018-08-01 02:45:44,707 9853 INFO ? odoo.service.server: HTTP service
(werkzeug) running on think-ThinkPad-T440p:8069
2018-08-01 02:45:44,786 9853 INFO ? odoo.addons.base.ir.ir_actions_report:
You need Wkhtmltopdf to print a pdf version of the reports.

**Comment by skyzluo** [comment]
I solved this problem. My database password is wrong. Thanks a lot!
