### ISSUE TITLE
trying to connect odoo but werkzeug error

### ISSUE THREAD

**Issue by Cherkah** [odoo/odoo#26109]
Impacted versions:
11

Steps to reproduce:
connect to odoo

Current behavior:
1)browser page
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

2) & terminal:
2018-08-01 14:13:57,664 17701 INFO ? odoo.sql_db: Connection to the database failed
2018-08-01 14:13:57,666 17701 INFO ? werkzeug: 127.0.0.1 - - [01/Aug/2018 14:13:57] "GET / HTTP/1
2018-08-01 14:13:57,670 17701 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
File "/home/abdul/.virtualenvs/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line
execute(self.server.app)
 File "/home/abdul/.virtualenvs/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line
application_iter = app(environ, start_response)
File "/home/abdul/Git/odoo/odoo/service/server.py", line 250, in app
return self.app(e, s)
 File "/home/abdul/Git/odoo/odoo/service/wsgi_server.py", line 166, in application
return application_unproxied(environ, start_response)
File "/home/abdul/Git/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
result = handler(environ, start_response)
File "/home/abdul/Git/odoo/odoo/http.py", line 1318, in __call__
return self.dispatch(environ, start_response)
File "/home/abdul/Git/odoo/odoo/http.py", line 1455, in dispatch
self.setup_db(httprequest)
File "/home/abdul/Git/odoo/odoo/http.py", line 1387, in setup_db
httprequest.session.db = db_monodb(httprequest)
File "/home/abdul/Git/odoo/odoo/http.py", line 1538, in db_monodb
dbs = db_list(True, httprequest)
File "/home/abdul/Git/odoo/odoo/http.py", line 1506, in db_list
dbs = odoo.service.db.list_dbs(force)
File "/home/abdul/Git/odoo/odoo/service/db.py", line 366, in list_dbs
with closing(db.cursor()) as cr:
File "/home/abdul/Git/odoo/odoo/sql_db.py", line 634, in cursor
return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
File "/home/abdul/Git/odoo/odoo/sql_db.py", line 178, in __init__
self._cnx = pool.borrow(dsn)
File "/home/abdul/Git/odoo/odoo/sql_db.py", line 517, in _locked
return fun(self, *args, **kwargs)
File "/home/abdul/Git/odoo/odoo/sql_db.py", line 585, in borrow
**connection_info)
File "/home/abdul/.virtualenvs/odoo-venv/lib/python3.6/site-packages/psycopg2/__init__.py", lin
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

3) my /etc/postgresql/10/main/pg_hba.conf seems good

 84 # Database administrative login by Unix domain socket
 85 local   all             postgres                                password
 86
 87 # TYPE  DATABASE        USER            ADDRESS                 METHOD
 88
 89 # "local" is for Unix domain socket connections only
 90 local   all             all                                     password
 91 # IPv4 local connections:
 92 host    all             all             127.0.0.1/32            md5
 93 # IPv6 local connections:
 94 host    all             all             ::1/128                 md5
 95 # Allow replication connections from localhost, by a user with the
 96 # replication privilege.
 97 local   replication     all                                     peer
 98 host    replication     all             127.0.0.1/32            md5
 99 host    replication     all             ::1/128                 md5

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, it seems something with the connection to Postgres database.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
