### ISSUE TITLE
error message - when install apps

### ISSUE THREAD

**Issue by luis-inagaki** [odoo/odoo#26174]
Impacted versions:
odoo 11 Community edition.
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Erro:
Uncaught TypeError: this.$buttons.off(...).destroy is not a function

http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:2098
Traceback:
TypeError: this.$buttons.off(...).destroy is not a function
    at Class.destroy (http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:2098:4805)
    at Class.prototype.(anonymous function) [as destroy] (http://localhost:8069/web/content/568-0505974/web.assets_common.js:3816:488)
    at Class.destroy (http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:406:326)
    at http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:421:219
    at Function._.map._.collect (http://localhost:8069/web/content/568-0505974/web.assets_common.js:13:270)
    at Class.clear_action_stack (http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:421:159)
    at Array.<anonymous> (http://localhost:8069/web/content/667-9945aae/web.assets_backend.js:413:151)
    at fire (http://localhost:8069/web/content/568-0505974/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/568-0505974/web.assets_common.js:801:198)
    at Array.deferred.(anonymous function) (http://localhost:8069/web/content/568-0505974/web.assets_common.js:803:56)

![image](https://user-images.githubusercontent.com/6526707/43691449-248e9e38-98f3-11e8-8a66-bbd6ba1d8151.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
