### ISSUE TITLE
Pillow==4.0.0 in odoo 11.0 requirements.txt is not compatible with python 3.7

### ISSUE THREAD

**Issue by IDeveLooper** [odoo/odoo#26175]
Impacted versions: 
Odoo 11.0 with Python 3.7

Steps to reproduce: 
Try to install required packages of python
`pip install -r requirements.txt`

Current behavior:
```
E:\odoo\odoo-11.0>pip install Pillow==4.0.0
Collecting Pillow==4.0.0
  Using cached https://files.pythonhosted.org/packages/8d/80/eca7a2d1a3c2dafb960f32f844d570de988e609f5fd17de92e1cf6a01b0a/Pillow-4.0.0.tar.gz
Requirement already satisfied: olefile in c:\users\USERNAME\appdata\local\programs\python\python37\lib\site-packages (from Pillow==4.0.0) (0.45.1)
Installing collected packages: Pillow
  Found existing installation: Pillow 5.2.0
    Uninstalling Pillow-5.2.0:
      Successfully uninstalled Pillow-5.2.0
  Running setup.py install for Pillow ... error
    Complete output from command c:\users\USERNAME\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip-install-idqtacjm\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\IF432~1.KER\AppData\Local\Temp\pip-record-u6tonck1\install-record.txt --single-version-externally-managed --compile:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_util.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing requirements to Pillow.egg-info\requires.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-idqtacjm\Pillow\setup.py", line 779, in <module>
        zip_safe=not debug_build(), )
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\USERNAME\appdata\local\programs\python\python37\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-idqtacjm\Pillow\setup.py", line 549, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-idqtacjm\Pillow\setup.py", line 791, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html



    ----------------------------------------
  Rolling back uninstall of Pillow
```

Expected behavior:
Successful installation of odoo requirements

Solution:
According to [Pillow documentation](http://pillow.readthedocs.io/en/latest/installation.html#notes) Python 3.7 only supports Pillow >= 5.2.0 .
So I think requirements.txt should be update Pillow version like this:

```
Pillow==4.0.0 ;  and python_version < '3.7'
Pillow==5.2.0 ;  python_version >= '3.7'
```

**Comment by Yenthe666** [comment]
@d-fence another package related one for you to check 😉

**Comment by gdgellatly** [comment]
pillow has lib dependencies like zlib, jpg tiff etc that need installing if
trying from source. Not really a py 3.7 issue. Even latest version would
fail.

**Comment by moylop260** [comment]
I have created a PR to test odoo with python3.7 from our teavis CI and this package is working well

More details:

https://github.com/OCA/maintainer-quality-tools/pull/562

@nhomar could you close this issue?

**Comment by Yenthe666** [comment]
@moylop260 you can always ping me too. Thanks for testing!

**Comment by MusharrafSakran** [comment]
If you are running `Python>=3.7` You should then use `Pillow==5.2.0`

**Comment by moylop260** [comment]
Check the following conclusion of how to fix it:
 -https://github.com/odoo/odoo/pull/30205#issuecomment-454485118

**Comment by engelbertlamercanceran** [comment]
Hi, Im facing the same error. I have odoo version 13 and py version 3.8.

**Comment by phamdinhhau** [comment]
> Hi, Im facing the same error. I have odoo version 13 and py version 3.8, on windows.

Pillow in odoo 13 version 6.1.0 not support py 3.8. Please change to version 6.2.1 or 6.2.2 in requirements.txt (https://pillow.readthedocs.io/en/latest/installation.html)
