### ISSUE TITLE
ModuleNotFoundError: No module named 'odoo.exceptions'

### ISSUE THREAD

**Issue by gethino** [odoo/odoo#26198]
I'm trying to run Odoo11 from source code on my Ubuntu 18.04 but I get the following error:
```
max@max-go:~$ cd Workspace/
max@max-go:~/Workspace$ cd odoo11
max@max-go:~/Workspace/odoo11$ ./odoo-bin
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/home/max/Workspace/odoo11/odoo/__init__.py", line 84, in <module>
    from . import modules
  File "/home/max/Workspace/odoo11/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/max/Workspace/odoo11/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/home/max/Workspace/odoo11/odoo/tools/__init__.py", line 20, in <module>
    from .xml_utils import *
  File "/home/max/Workspace/odoo11/odoo/tools/xml_utils.py", line 4, in <module>
    from odoo.exceptions import UserError
ModuleNotFoundError: No module named 'odoo.exceptions'
```
What am I doing wrong? Can someone help please.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem. You can also ask for help in the forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
