### ISSUE TITLE
[11.0] error when trying to access product or product variant

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#26236]
Impacted versions: [11.0]

Steps to reproduce: try accessing product or product variant
![image](https://user-images.githubusercontent.com/26357404/43827526-362ccfc4-9b24-11e8-885d-babcf003530e.png)

not sure is it because i update odoo to latest one 

Current behavior:
`Traceback (most recent call last):
  File "/odoo-production/odoo-production-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo-production/odoo-production-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo-production/odoo-production-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo-production/odoo-production-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo-production/odoo-production-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo-production/odoo-production-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo-production/odoo-production-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo-production/odoo-production-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo-production/odoo-production-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo-production/odoo-production-server/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo-production/odoo-production-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo-production/odoo-production-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo-production/odoo-production-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo-production/odoo-production-server/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/odoo-production/odoo-production-server/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo-production/odoo-production-server/addons/mail/models/mail_thread.py", line 370, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo-production/odoo-production-server/odoo/models.py", line 1381, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/odoo-production/odoo-production-server/odoo/addons/base/ir/ir_ui_view.py", line 1048, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/odoo-production/odoo-production-server/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Field `scrap` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]`

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you haven't update modules in the DB. You can do it through "Update" button on the module list (the recommended one is to update `base` module for updating all) or via command line with `-u all` parameter.

Closing as no real issue.

**Comment by Boss1669** [comment]
@pedrobaeza i did following

sudo git fetch origin 11.0
sudo git reset --hard origin/11.0
sudo service odoo-production-server restart -u all

**Comment by pedrobaeza** [comment]
That's not valid, as the command for restarting is not to launch Odoo in command line. Do the other thing then if you don't figure out how to do launch Odoo in command line.
