### ISSUE TITLE
allow for use of specific schema in postgres

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#26371]
Impacted versions: v11

Steps to reproduce:

begin;
create schema  if not exists odoo;
alter database <tst_database_name> set search_path to odoo;
grant all on schema odoo to odoo;
grant all on all tables in schema odoo to odoo;
grant all on all sequences in schema odoo to odoo;
grant all on all functions in schema odoo to odoo;
commit;

Current behavior: does not work in v11

Expected behavior: did work in v10

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Can you enlgiht us which is the point of use schemas? and which is the behavior that you got? simply "It does not work but it worked" is not enough to help.

**Comment by ahetland** [comment]
schemas are an excellent way for segregating a database into different distinct "black-boxes" and can have several use cases, for security to separate company internal tables from external tables, for development (its easier to create and destroy schemas), to use odoo with other system but in same database there are many more I am sure ... when creating the database in v10 (I would create an empty database first then create the schemas as per above and then at last start the server with the "--without-demo=True" flag set .. this would work in 10 but does not anymore. The below error is created

**Comment by ahetland** [comment]
2018-08-14 10:08:44,756 14560 INFO ? odoo.modules.loading: init db
2018-08-14 10:08:47,653 14560 INFO test_02 odoo.modules.loading: loading 1 modules...
2018-08-14 10:08:47,737 14560 INFO test_02 odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-14 10:08:47,930 14560 INFO test_02 odoo.modules.registry: module base: creating or updating database tables
2018-08-14 10:08:48,320 14560 ERROR test_02 odoo.sql_db: bad query: b'CREATE TABLE "ir_model_data" (id SERIAL NOT NULL, PRIMARY KEY(id))'
ERROR: relation "ir_model_data" already exists

2018-08-14 10:08:48,325 14560 WARNING test_02 odoo.modules.loading: Transient module states were reset
2018-08-14 10:08:48,327 14560 ERROR test_02 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/stage/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/stage/odoo/odoo/modules/loading.py", line 321, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/stage/odoo/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/odoo/stage/odoo/odoo/modules/registry.py", line 306, in init_models
    model._auto_init()
  File "/home/odoo/stage/odoo/odoo/addons/base/ir/ir_model.py", line 1288, in _auto_init
    res = super(IrModelData, self)._auto_init()
  File "/home/odoo/stage/odoo/odoo/models.py", line 2195, in _auto_init
    tools.create_model_table(cr, self._table, self._description)
  File "/home/odoo/stage/odoo/odoo/tools/sql.py", line 51, in create_model_table
    cr.execute('CREATE TABLE "{}" (id SERIAL NOT NULL, PRIMARY KEY(id))'.format(tablename))
  File "/home/odoo/stage/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/stage/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "ir_model_data" already exists

2018-08-14 10:08:48,330 14560 CRITICAL test_02 odoo.service.server: Failed to initialize database `test_02`.
Traceback (most recent call last):
  File "/home/odoo/stage/odoo/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/stage/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/stage/odoo/odoo/modules/loading.py", line 321, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/stage/odoo/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/odoo/stage/odoo/odoo/modules/registry.py", line 306, in init_models
    model._auto_init()
  File "/home/odoo/stage/odoo/odoo/addons/base/ir/ir_model.py", line 1288, in _auto_init
    res = super(IrModelData, self)._auto_init()
  File "/home/odoo/stage/odoo/odoo/models.py", line 2195, in _auto_init
    tools.create_model_table(cr, self._table, self._description)
  File "/home/odoo/stage/odoo/odoo/tools/sql.py", line 51, in create_model_table
    cr.execute('CREATE TABLE "{}" (id SERIAL NOT NULL, PRIMARY KEY(id))'.format(tablename))
  File "/home/odoo/stage/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/stage/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "ir_model_data" already exists

**Comment by nhomar** [comment]
The error is telling you what is happening:

```
 psycopg2.ProgrammingError: relation "ir_model_data" already exists
```

It means you are not using an empty database schema, and odoo in v11.0 check such **blank** state which is necessary to land with -i in a database.

I think what you are having is an expected behavior (and in the contrary it was a bug in 10.0 that this was not being done).

If you want to use schemas in the way you say, those schemas can not have the base data-structure set, just copy the base schemas in postgres as your new ones and all will be ok.!

regards.
