### ISSUE TITLE
Server Error - Mexican Localization Reports after security update

### ISSUE THREAD

**Issue by ulisesgamboa** [odoo/odoo#26389]
Impacted versions:
11 +e Mexican Localization
Steps to reproduce:
1. Update Odoo 11 Enterprise after security report following     https://www.odoo.com/r/update-howto
2. Restart Odoo Service
3. Run Mexican Localization Reports 
Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/enterprise/addons/account_reports/models/account_report.py", line 315, in get_report_informations
    'main_html': self.get_html(options),
  File "/odoo/enterprise/addons/l10n_mx_reports/models/trial_balance.py", line 309, in get_html
    options, line_id, additional_context)
  File "/odoo/enterprise/addons/account_reports/models/account_report.py", line 485, in get_html
    lines = self.with_context(self.set_context(options)).get_lines(options, line_id=line_id)
  File "/odoo/enterprise/addons/account_reports/models/account_report_coa.py", line 143, in get_lines
    lines = self._post_process(grouped_accounts, initial_balances, options, comparison_table)
  File "/odoo/enterprise/addons/l10n_mx_reports/models/trial_balance.py", line 78, in _post_process
    line.children_ids, grouped_accounts, initial_balances, options, comparison_table)
  File "/odoo/enterprise/addons/l10n_mx_reports/models/trial_balance.py", line 127, in _get_lines_second_level
    comparison_table)
  File "/odoo/enterprise/addons/l10n_mx_reports/models/trial_balance.py", line 160, in _get_lines_third_level
    [('cash_basis_base_account_id', '!=', False)], ['cash_basis_base_account_id'])
  File "/odoo/odoo-server/odoo/models.py", line 4223, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/addons/account/models/account.py", line 840, in search
    return super(AccountTax, self).search(args, offset, limit, order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 3774, in _search
    query = self._where_calc(args)
  File "/odoo/odoo-server/odoo/models.py", line 3564, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo/odoo-server/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/odoo/odoo-server/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'cash_basis_base_account_id' in leaf "<osv.ExtendedLeaf: ('cash_basis_base_account_id', '!=', False) on account_tax (ctx: )>"
Expected behavior:
Run Reports
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/33880229/44132512-d515c58c-a01f-11e8-9570-ee6263c62c97.png)

**Comment by nhomar** [comment]
Do you have an enterprise code for this issue? just to make the follow up....

on our side I am reviewing.

Regard.s

**Comment by nhomar** [comment]
SOrry, I meant "Issue ID posted in odoo.com related with your licence"

**Comment by ulisesgamboa** [comment]
No yet, could you please tell me where I should create this ID. Regards

**Comment by nhomar** [comment]
@pedrobaeza DO NOT close this kind of issues please.

**Comment by nhomar** [comment]
@ulisesgamboa With your licence number go to https://odoo.com/help.

In the mean while try to to answer me the questions above.

**Comment by luistorresm** [comment]
Hello @nhomar @ulisesgamboa 

FYI: This requires the module account_cash_basis_base_account to be installed.
As it has been added as an auto_install module in odoo/odoo@1631889, it may not be available in some old installs. Installing it solves the issue.

@nhomar 

Could you close this Issue, please?

Regards

**Comment by ulisesgamboa** [comment]
@luistorresm @nhomar thanks for your help, this was solved.
@luistorresm thanks for your support.

Regards
