### ISSUE TITLE
Error when upgrading Module

### ISSUE THREAD

**Issue by etiennebonnafoux** [odoo/odoo#26424]
Impacted versions: odoo 11

Steps to reproduce: Try to upgrade any module

Current behavior: When I try to upgrade any module (base or custom one) I got this error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
    try:
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
    def __call__(self, *args, **kw):
  File "/opt/odoo/odoo11/odoo/http.py", line 516, in response_wrap
    def response_wrap(*args, **kw):
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-47>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 602, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 546, in _button_immediate_function
    config = env['ir.module.module'].next() or {}
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 528, in next
    return active_todo.action_launch()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 668, in action_launch
    result = action.read()[0]
IndexError: list index out of range
```

All XML files are upgraded but the code in python are not changed 

Expected behavior: Good Upgrade

**Comment by pedrobaeza** [comment]
Have you restart your Odoo service?

**Comment by etiennebonnafoux** [comment]
I just restart Odoo to check and I still have the same error.

( I installed Odoo following this tutorial: https://linuxize.com/post/how-to-deploy-odoo-11-on-ubuntu-18-04/)

**Comment by etiennebonnafoux** [comment]
When I read the journalctl of Odoo I see this error, do you think it can be link?

```
 File "/opt/odoo/odoo11/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/odoo11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'probespoke'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
     force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
   perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 137, in load_module_graph
     load_openerp_module(package.name)
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 82, in load_module
août 17 16:43:25 vps562789 odoo11[30068]:     exec(open(modfile, 'rb').read(), new_mod.__dict__)
   File "<string>", line 4, in <module>
août 17 16:43:25 vps562789 odoo11[30068]:   File "/opt/odoo/odoo11-custom-addons/probespokeq/models/__init__.py", line 3, in <module>
     from . import models
  File "/opt/odoo/odoo11-custom-addons/probespokeq/models/models.py", line 31
]:     def get_report_values(self, docids, data=None):                                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by pedrobaeza** [comment]
Then you have the answer :wink: : the custom module `probespokeq` is provoking the problem.

Closing as this is not Odoo related.

**Comment by etiennebonnafoux** [comment]
Please give me a chance:) 
How can I upgrade or delete this module since Odoo doesn't want to change the Python code it has in memory?
I have already try to delete it but the models stay...
And it don't explain why it's propage in other module.

**Comment by pedrobaeza** [comment]
Well, this is out of the scope of this issue tracker and my voluntary work, but try:

* Go to the previous code version
* Or fix the code
* Remove the folder, restart and uninstall the module in your DB

For further questions, please go to the forums.
