### ISSUE TITLE
Actions server python code : transformAction is not a function

### ISSUE THREAD

**Issue by ertus-odoo** [odoo/odoo#26538]
**Impacted versions:**
Odoo 11 Enterprise

**Steps to reproduce:**
Go to actions server, add a title, select Pyhon code (state = code) et delete text in Code Python, popup appear with error JS.

**Current behavior:**
Erreur:
Uncaught TypeError: n.getMode(...).transformAction is not a function

http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:6752
Retraçage :
TypeError: n.getMode(...).transformAction is not a function
    at b.remove (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:6752:37)
    at Object.exec (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:6160:15)
    at http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:5509:34
    at o.r._emit.r._dispatchEvent (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:1746:46)
    at o.exec (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:5528:45)
    at s.$callKeyboardHandlers (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:2116:54)
    at s.onCommandKey (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:2122:18)
    at b.onCommandKey (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:6675:29)
    at o (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:767:71)
    at HTMLTextAreaElement.<anonymous> (http://localhost:8069/web/static/lib/ace/ace.odoo-custom.js:881:25)

Expected behavior:

Video/Screenshot link (optional):
![capture d ecran 2018-08-23 a 10 20 42](https://user-images.githubusercontent.com/37842397/44513723-6bf4c300-a6be-11e8-8c82-f91e1e487880.png)

**Comment by sswapnesh** [comment]
Hello @ertus-odoo 
I am not able to Reproduce on Latest [Runbot](http://365324-11-0-83a323.runbot14.odoo.com/web?debug#id=1129&view_type=form&model=ir.actions.server&action=6&menu_id=4) build.
![screenshot from 2018-08-23 22-15-46](https://user-images.githubusercontent.com/16624719/44539591-3386d080-a722-11e8-9b40-0344c927a294.png)
![screenshot from 2018-08-23 22-16-02](https://user-images.githubusercontent.com/16624719/44539600-384b8480-a722-11e8-9353-0c31b7d9b8d6.png)

**Comment by ertus-odoo** [comment]
Hi,

I have a french database with last version of Odoo 11.

[24471521-1fdf-4fe2-yeb1-7020442ee8ec-quicktime.mov.zip](https://github.com/odoo/odoo/files/2317492/24471521-1fdf-4fe2-yeb1-7020442ee8ec-quicktime.mov.zip)

**Comment by ertus-odoo** [comment]
I create a new database in english without any datas, same problem.

**Comment by ertus-odoo** [comment]
I found ! Need to clean my cache deeply, shortcut on Mac OS for delete cache seems useless, need to do this directly in the browser.

Thank you
