### ISSUE TITLE
mrp_operations fails installation on odoo 11

### ISSUE THREAD

**Issue by criley645** [odoo/odoo#26558]
Impacted versions: 11

Steps to reproduce:
I am trying to install mrp_operations on a new installation of ODOO 11. From the UI the module is available to install and when I click the install button I receive the stack trace below.  It looks like there is a version conflict in fields.py as many of the functions have been renamed eg. fields.related has been depricated.  Is there a port of mrp_operations that uses the new fields module or is there a bigger issue here?
Thanks in advance
Chris

Current behavior:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 137, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/odoo/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 23, in <module>
  File "/opt/odoo/odoo/addons/mrp_operations/mrp_operations.py", line 54, in <module>
    class mrp_production_workcenter_line(osv.osv):
  File "/opt/odoo/odoo/addons/mrp_operations/mrp_operations.py", line 104, in mrp_production_workcenter_line
    'production_state':fields.related('production_id','state',
AttributeError: module 'odoo.fields' has no attribute 'related'

**Comment by pedrobaeza** [comment]
mrp_operations no longer exists in v11. Are you trying to migrate the module?

**Comment by sswapnesh** [comment]
and also there is no more fields.related

**Comment by criley645** [comment]
Excuse me as I am new to ODOO.   My understanding is that mrp_operations allowed a manufacturing order start date to flow to its children work orders.  Is there a replacement for that functionality in another odoo 11 module?
Thanks

**Comment by pedrobaeza** [comment]
That feature is already integrated in mrp module. Any way, this issue tracker is only for reporting issues with Odoo modules, not with custom developments (and an Odoo module tried to be migrated to other version counts as custom module).

**Comment by criley645** [comment]
OK, Thank you
