### ISSUE TITLE
After uninstall theme, cannot access odoo with Error to render compiling AST web.menu_secondary

### ISSUE THREAD

**Issue by olragon** [odoo/odoo#26560]
## Steps to reproduce:

1. install theme backend_theme_v11
2. uninstall theme backend_theme_v11
https://apps.odoo.com/apps/themes/11.0/backend_theme_v11/

## Current behavior: 

cannot access `odoo-url/?web` or `odoo-url/?web&debug`

## Expected behavior: 

access `odoo-url/?web` or `odoo-url/?web&debug`

## Video/Screenshot link (optional):

Error log
```
2018-08-24 02:40:33,405 14014 INFO odoo_ondinh odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [534, 533, 532, 531]
2018-08-24 02:40:34,403 14014 INFO odoo_ondinh odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [535]
2018-08-24 02:40:34,612 14014 INFO odoo_ondinh werkzeug: 172.16.0.22 - - [24/Aug/2018 02:40:34] "GET /web? HTTP/1.0" 500 -
2018-08-24 02:40:34,625 14014 ERROR odoo_ondinh werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/data/asaleo/www/opensource/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/http_routing/models/ir_http.py", line 393, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/data/asaleo/www/opensource/odoo/addons/website/models/ir_http.py", line 169, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/asaleo/www/opensource/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1269, in flatten
    self.response.append(self.render())
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1262, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/data/asaleo/www/opensource/odoo-addons/app_odoo_customize/models/ir_ui_view.py", line 18, in render_template
    return super(View, self).render_template(template, values=values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/data/asaleo/www/opensource/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in _compiled_fn
    raise e
QWebException: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_menu_secondary_284
TypeError: 'NoneType' object has no attribute '__getitem__'

Error to render compiling AST
TypeError: 'NoneType' object has no attribute '__getitem__'
Template: web.menu_secondary
Path: /templates/t/ul/t
Node: <t t-foreach="menu['children']" t-as="menu">
                <li>
                    <t t-if="menu['children']">
                        <a>
                            <t t-esc="menu['name']"/>
                            <span class="fa arrow"/>
                        </a>
                    </t>
                    <t t-if="not menu['children']">
                        <t t-call="web.menu_link"/>
                    </t>
                    <t t-call="web.menu_secondary_submenu"/>
                </li>
            </t>
2018-08-24 02:42:14,222 14014 INFO odoo_ondinh odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [534, 533, 532, 531]
2018-08-24 02:42:15,222 14014 INFO odoo_ondinh odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [535]
2018-08-24 02:42:15,469 14014 INFO odoo_ondinh werkzeug: 172.16.0.22 - - [24/Aug/2018 02:42:15] "GET /web?debug HTTP/1.0" 500 -
2018-08-24 02:42:15,483 14014 ERROR odoo_ondinh werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/data/asaleo/www/opensource/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/http_routing/models/ir_http.py", line 393, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/data/asaleo/www/opensource/odoo/addons/website/models/ir_http.py", line 169, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/asaleo/www/opensource/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1269, in flatten
    self.response.append(self.render())
  File "/data/asaleo/www/opensource/odoo/odoo/http.py", line 1262, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/data/asaleo/www/opensource/odoo-addons/app_odoo_customize/models/ir_ui_view.py", line 18, in render_template
    return super(View, self).render_template(template, values=values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/data/asaleo/www/opensource/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in _compiled_fn
    raise e
QWebException: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/data/asaleo/www/opensource/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_menu_secondary_350
TypeError: 'NoneType' object has no attribute '__getitem__'

Error to render compiling AST
TypeError: 'NoneType' object has no attribute '__getitem__'
Template: web.menu_secondary
Path: /templates/t/ul/t
Node: <t t-foreach="menu['children']" t-as="menu">
                <li>
                    <t t-if="menu['children']">
                        <a>
                            <t t-esc="menu['name']"/>
                            <span class="fa arrow"/>
                        </a>
                    </t>
                    <t t-if="not menu['children']">
                        <t t-call="web.menu_link"/>
                    </t>
                    <t t-call="web.menu_secondary_submenu"/>
                </li>
            </t>

```

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

One tip: try to update your DB with `-u all`

**Comment by olragon** [comment]
@pedrobaeza thank you very much! Update DB with `-u all` save us!

**Comment by MistahK24** [comment]
@pedrobaeza Why would updating all modules solve the issue?

**Comment by pedrobaeza** [comment]
Because it's the way Odoo recognizes "new things" in data model, views, etc.

**Comment by MistahK24** [comment]
@pedrobaeza Right, but in this case the user uninstalled a module. Why would uninstalling backend_theme_v11 break existing code (assuming of course that the user did not depend on anything in backend_theme_v11)? It seems like a strange error to encounter. Could it be that Odoo did not properly clean up after an uninstall?

**Comment by pedrobaeza** [comment]
Because the module has touched other records from standard modules, and no uninstall hook has been provided in the module for a proper cleanup.
