### ISSUE TITLE
Error with the website_report.layout template with Website Builder installed in a Docker container

### ISSUE THREAD

**Issue by commodus-sebastien** [odoo/odoo#26727]
Hi everybody,

I will try to be as clear as possible but if there is any useful information I can add or clarify, please let me know!

**Impacted versions:** 
Odoo 11 docker image (Community Edition), build 20180808

**Steps to reproduce:**
I reproduice systematically with the latest docker image (20180808) by following these steps:
- I use traefik as a reverse proxy, version 1.6.6 but I am not sure there is an impact
- I use the following docker-compose.yml file:
```
version: '2'
services:
  web:
    image: odoo:latest
    depends_on:
      -  db
    restart: always
    ports:
      - 8069:8069
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=complexpassword
    networks:
      - web
      - default
    volumes:
      - ./data-web:/var/lib/odoo
      - ./data-addons:/mnt/extra-addons
    labels:
      - "traefik.backend=odoo"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:myhostname.com"
      - "traefik.enable=true"
      - "traefik.port=8069"
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=complexpassword
      - POSTGRES_USER=odoo
    volumes:
      - ./data-db:/var/lib/postgresql/data/pgdata
networks:
  web:
    external: true
```
- docker-compose up -d in the folder containing this docker-compose.yml file
- I can connect to the Odoo configuration wizard. I create a new empty DB
- I install the CRM and Sales Management apps
- At this point everything is ok, I can create an invoice and print it for example
- If I install the Website Builder app, then I am unable to print an invoice anymore

**Current behavior:**
The following error is displayed:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_report_layout_1008
  File "<template>", line 2, in body_call_content_1007
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 628, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 666, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions_report.py", line 470, in render_template
    return view_obj.render_template(template, values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_640_892
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_html_container_986
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 349, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_report_layout_1008
  File "<template>", line 2, in body_call_content_1007
AttributeError: 'NoneType' object has no attribute 'id'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'id'
Template: website_report.layout
Path: /templates/t/t/t[4]
Node: <t t-set="x_icon" t-value="'/web/image/website/%s/favicon/' % website.id"/>
```
- If I uninstall the Website Builder app I am able to print an invoice again

@zimbora69 in the issue #20822 spoke about an issue also spotted on Docker, perhaps there is a link between the two issues?

**Expected behavior:**
The Website Builder app should not block the report and invoices generation

**Thanks for your help!**

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, the traefik proxy configuration seems to make Odoo to recognize current website, and thus the error. You can try other Docker base solutions like (https://github.com/Tecnativa/doodba - sorry for the "advertisement", but we have this very sophisticated and without that problem).

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by commodus-sebastien** [comment]
Hi,

Thanks for your quick answer! 
I will investigate in detail my deployment, the traefik impact and take a look at doodba.

I will post a new comment if I find something.
Thanks

**Comment by commodus-sebastien** [comment]
Hi,

I tested it on a local container with direct access and the result was the same.
Instead of using the latest postgresql image as I did, I specified the version 9.4 as in the odoo documentation.

It solved my problem.
Thanks!
