### ISSUE TITLE
"./odoo --language=fr_FR --i18n-export=/tmp/fr_FR.po -d database" command doesn't work

### ISSUE THREAD

**Issue by LucasPollet** [odoo/odoo#26725]
Impacted versions: 10.0

OS: Ubuntu 16.04

Steps to reproduce: 

-Log as root user 

-Create a role 'root' on Postgres and set your root password for the user 'root'

- execute the command "./odoo --language=fr_FR --i18n-export=/tmp/fr_FR.po -d database" in the /usr/bin folder (replace "database" by the name of your own database)

Current behavior:

When you execute this command, you should have the error :
```
 2018-08-31 15:10:16,098 2200 ERROR ? odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 80, in new
    registry.setup_signaling()
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 371, in setup_signaling
    cr.execute("CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1")
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "base_registry_signaling" already exists

Traceback (most recent call last):
  File "./odoo", line 9, in <module>
    odoo.cli.main()
  File "/usr/lib/python2.7/dist-packages/odoo/cli/command.py", line 64, in main
    o.run(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 175, in run
    main(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 154, in main
    export_translation()
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 102, in export_translation
    registry = odoo.modules.registry.Registry.new(dbname)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 80, in new
    registry.setup_signaling()
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 371, in setup_signaling
    cr.execute("CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1")
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "base_registry_signaling" already exists
```

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as I'm able to do it perfectly:

![seleccion_004](https://user-images.githubusercontent.com/7165771/44930266-06f43980-ad5e-11e8-8e7e-e2ae3fa3a0b7.png)

so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
