### ISSUE TITLE
Adding a field to the res.partner model prevents login and module upgrade via UI or RPC 

### ISSUE THREAD

**Issue by initialpuppet** [odoo/odoo#26757]
This is cross posted from: https://www.odoo.com/forum/help-1/question/adding-a-field-to-the-res-partner-model-prevents-login-and-module-upgrade-via-ui-or-rpc-139275

# Impacted versions
Tested on Odoo 10

# Steps to reproduce

1. Create a custom module
2. Extend the `res.partner` model using Odoo's _Extension inheritance_, e.g. set the field `_inherit` but not `_name`.
3. Add a field to the model, e.g. `my_field = fields.Boolean()`
4. Restart the Odoo server (do not update the module via CLI)
5. Attempt to log in via the UI

# Current behavior

- An exception is thrown reporting a bad query. The error from Postgres is `Missing field in SELECT`.

# Expected behavior

- Login via UI is possible

# Comments

We run multiple Odoo instances and have written management software for them which uses the Odoo RPC API. When we deploy a new version of one of our modules, our software copies the files to each of the servers and upgrades the module by logging in and 'clicking' the module upgrade button via RPC.

This works great unless we add a field to a core model, such as res.partner, via 'Extension' inheritance. In that case, because the code is executed before the module is upgraded, the SELECT on the database includes the new field name and Odoo crashes.

Googling around shows plenty of people who have run into this issue and the advice is always to perform the module upgrade from the command line. While this is possible for us, using the RPC API to upgrade modules is much more useful as its fits well into the existing infrastructure we use for other things (such as updating settings on individual Odoo instances or installing new modules). Programatically issuing commands via SSH is something we would rather avoid.

I understand that this may not be considered a bug, but I am posting here as I think it is a topic worthy of discussion - we got to this point having been pretty careful about following Odoo guidelines and reading documentation, so perhaps even if there is not a technical solution, there is a documentation improvement in here somewhere.

**Comment by sbidoul** [comment]
Can you post the stack trace?

**Comment by pedrobaeza** [comment]
@initialpuppet the requirement is to upgrade the module in the DB before doing anything else. You should develop your orchestration in something outside Odoo (Puppet, Swarm, Kubernetes...), not via RPC API.

There has been several mails about this topic. Just check on Odoo mailing lists or start a new thread there.

Closing as no real issue.

**Comment by sbidoul** [comment]
@pedrobaeza I think this is worth discussing. Odoo has a mechanism to upgrade modules from the UI, and upgrading a module wich adds fields to res.partner causes a stack trace, so strictly speaking it's a bug.

I suggest we look at the stack trace first.

**Comment by pedrobaeza** [comment]
I don't think so, @sbidoul. It's simply that you are accessing a model that hasn't been upgraded. You should upgrade via command line, not UI or RPC.

**Comment by sbidoul** [comment]
@pedrobaeza when I've had this error, it was simply because Odoo was accessing res.partner to get the lang of the admin user trying to run the module upgrade. This is admitedly a edge case but it'd be nice to have a clean behaviour in that scenario.

**Comment by pedrobaeza** [comment]
Are you saying this prevents to upgrade through command line?

**Comment by sbidoul** [comment]
It works with `-u` but it breaks if you try to launch the upgrade from a shell script (such as launching module_auto_update entry point).

**Comment by pedrobaeza** [comment]
We always update through `module_auto_update` and I haven't faced this problem yet. Do you have one case for trying?

**Comment by sbidoul** [comment]
I don't have a fresh example, but I think it occurred doing this:
* install a custom module
* stop Odoo
* create a class that `_inherit` `res.partner` and add a new field in it
* launch Odoo shell
* run `env['ir.module.module'].upgrade_changed_checksum()`

**Comment by initialpuppet** [comment]
@sbidoul @pedrobaeza Thanks to both of you for engaging regarding this issue. I realise that it is an edge case and I appreciate your time.

To give a bit of background regarding the use-case, our estate is a mixture of on-premise bare metal deployments and cloud VMs. We provide a fully managed service for our clients. Using containers or Puppet / Chef etc is not something we have explorered in detail, but managing instances via Odoo RPC has proved to be very effective for us since it integrates well with the rest of our management software, used by a variety of technical and non-technical users within and outside our company.

The stack trace for the error is as follows:

```
2018-09-04 14:48:55,121 20707 INFO kamooni werkzeug: 127.0.0.1 - - [04/Sep/2018 14:48:55] "GET / HTTP/1.1" 303 -
2018-09-04 14:48:55,143 20707 INFO kamooni odoo.sql_db: bad query:  SELECT [FIELDS REDACTED] FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2018-09-04 14:48:55,330 20707 INFO kamooni werkzeug: 127.0.0.1 - - [04/Sep/2018 14:48:55] "GET /web HTTP/1.1" 500 -
2018-09-04 14:48:55,439 20707 ERROR kamooni werkzeug: Error on request:
Traceback (most recent call last):
  File "odoo/env/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "odoo/env/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "odoo/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "odoo/odoo/http.py", line 1323, in __call__
    return self.dispatch(environ, start_response)
  File "odoo/odoo/http.py", line 1297, in __call__
    return self.app(environ, start_wrapped)
  File "odoo/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "odoo/odoo/http.py", line 1496, in dispatch
    result = ir_http._dispatch()
  File "odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "odoo/odoo/http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "odoo/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "odoo/addons/web/controllers/main.py", line 445, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "odoo/addons/report/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "odoo/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "odoo/addons/barcodes/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "odoo/addons/web/models/ir_http.py", line 30, in session_info
    "user_context": request.session.get_context() if request.session.uid else {},
  File "odoo/odoo/http.py", line 1097, in get_context
    self.context = request.env['res.users'].context_get() or {}
  File "<decorator-gen-30>", line 2, in context_get
    
  File "odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "odoo/odoo/addons/base/res/res_users.py", line 429, in context_get
    res = getattr(user, k) or False
  File "odoo/odoo/fields.py", line 914, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1026, in determine_value
    self.compute_value(recs)
  File "odoo/odoo/fields.py", line 980, in compute_value
    self._compute_value(records)
  File "odoo/odoo/fields.py", line 973, in _compute_value
    self.compute(records)
  File "odoo/odoo/fields.py", line 624, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "odoo/odoo/models.py", line 5224, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/odoo/fields.py", line 914, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1016, in determine_value
    record._prefetch_field(self)
  File "odoo/odoo/models.py", line 3065, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "odoo/odoo/models.py", line 3009, in read
    self._read_from_database(stored, inherited)
  File "odoo/odoo/models.py", line 3133, in _read_from_database
    cr.execute(query_str, params)
  File "odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.foo does not exist
LINE 1: ..."company_id","res_partner"."team_id" as "team_id","res_partn...
```

**Comment by initialpuppet** [comment]
I have not come across `module_auto_update` before (looks very useful!) but I would expect that if it authenticates against the Odoo instance it is upgrading in order to perform module upgrades, it will encounter this same problem.

**Comment by sbidoul** [comment]
Your stack trace confirms what I suspected and is the same problem I encountered. The errors occurs when building the context before even attempting to launch your rpc method. 

My take is that catching exceptions to return default values in `odoo/odoo/addons/base/res/res_users.py", line 429` would make sense, but I'm not sure it would be accepted by Odoo.

**Comment by pedrobaeza** [comment]
Can you open a PR for checking your proposal?

**Comment by sbidoul** [comment]
@initialpuppet @pedrobaeza #26773 is what I have in mind, and similar to what I implemented as a workaround in click-odoo-upgrade

**Comment by initialpuppet** [comment]
@sbidoul I just tried my code against your PR and it looks like the system is still querying the res_partner table, although your exception handling is also being triggered. I tried running with `debug` logging but I couldn't see anything that would indicate where the query was coming from.

Sorry this isn't more helpful, I'm pretty new to Odoo's internals.

```
2018-09-04 16:53:09,764 27958 INFO localkamooni odoo.modules.loading: loading 1 modules...
2018-09-04 16:53:09,784 27958 INFO localkamooni odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2018-09-04 16:53:09,831 27958 INFO localkamooni odoo.modules.loading: loading 53 modules...
2018-09-04 16:53:10,010 27958 INFO localkamooni odoo.modules.loading: 53 modules loaded in 0.18s, 0 queries
2018-09-04 16:53:10,618 27958 INFO localkamooni odoo.modules.loading: Modules loaded.
2018-09-04 16:53:10,623 27958 INFO localkamooni odoo.addons.base.ir.ir_http: Generating routing map
2018-09-04 16:53:10,734 27958 INFO localkamooni odoo.sql_db: bad query:  SELECT [FIELDS REDACTED] FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2018-09-04 16:53:10,734 27958 WARNING localkamooni odoo.addons.base.res.res_users: Error getting attribute tz of res.users(1,)
Traceback (most recent call last):
  File "odoo/odoo/addons/base/res/res_users.py", line 431, in context_get
    res = getattr(user, k) or False
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1027, in determine_value
    self.compute_value(recs)
  File "odoo/odoo/fields.py", line 981, in compute_value
    self._compute_value(records)
  File "odoo/odoo/fields.py", line 974, in _compute_value
    self.compute(records)
  File "odoo/odoo/fields.py", line 625, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "odoo/odoo/models.py", line 5236, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1017, in determine_value
    record._prefetch_field(self)
  File "odoo/odoo/models.py", line 3073, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "odoo/odoo/models.py", line 3017, in read
    self._read_from_database(stored, inherited)
  File "odoo/odoo/models.py", line 3141, in _read_from_database
    cr.execute(query_str, params)
  File "odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.foo does not exist
LINE 1: ...ate" as "date","res_partner"."mobile" as "mobile","res_partn...
                                                             ^

2018-09-04 16:53:10,737 27958 INFO localkamooni odoo.sql_db: bad query:  SELECT [FIELDS REDACTED] FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2018-09-04 16:53:10,737 27958 WARNING localkamooni odoo.addons.base.res.res_users: Error getting attribute lang of res.users(1,)
Traceback (most recent call last):
  File "odoo/odoo/addons/base/res/res_users.py", line 431, in context_get
    res = getattr(user, k) or False
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1027, in determine_value
    self.compute_value(recs)
  File "odoo/odoo/fields.py", line 981, in compute_value
    self._compute_value(records)
  File "odoo/odoo/fields.py", line 974, in _compute_value
    self.compute(records)
  File "odoo/odoo/fields.py", line 625, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "odoo/odoo/models.py", line 5236, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1017, in determine_value
    record._prefetch_field(self)
  File "odoo/odoo/models.py", line 3073, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "odoo/odoo/models.py", line 3017, in read
    self._read_from_database(stored, inherited)
  File "odoo/odoo/models.py", line 3141, in _read_from_database
    cr.execute(query_str, params)
  File "odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

2018-09-04 16:53:10,738 27958 INFO localkamooni odoo.sql_db: bad query:  SELECT "res_partner"."is_company" as "is_company","res_partner"."street2" as "street2","res_partner"."id_passport" as "id_passport","res_partner"."opt_out" as "opt_out","res_partner"."message_last_post" as "message_last_post","res_partner"."purchase_warn_msg" as "purchase_warn_msg","res_partner"."display_name" as "display_name","res_partner"."create_uid" as "create_uid","res_partner"."partner_share" as "partner_share","res_partner"."phone" as "phone","res_partner"."parent_id" as "parent_id","res_partner"."id" as "id","res_partner"."street" as "street","res_partner"."state_id" as "state_id","res_partner"."sale_warn" as "sale_warn","res_partner"."active" as "active","res_partner"."ref" as "ref","res_partner"."credit_limit" as "credit_limit","res_partner"."supplier" as "supplier","res_partner"."message_bounce" as "message_bounce","res_partner"."notify_email" as "notify_email","res_partner"."lang" as "lang","res_partner"."agent_discount" as "agent_discount","res_partner"."city" as "city","res_partner"."debit_limit" as "debit_limit","res_partner"."create_date" as "create_date","res_partner"."date" as "date","res_partner"."mobile" as "mobile","res_partner"."foo" as "foo","res_partner"."signup_expiration" as "signup_expiration","res_partner"."commission_partner" as "commission_partner","res_partner"."is_agent" as "is_agent","res_partner"."write_uid" as "write_uid","res_partner"."comment" as "comment","res_partner"."email" as "email","res_partner"."sale_warn_msg" as "sale_warn_msg","res_partner"."last_time_entries_checked" as "last_time_entries_checked","res_partner"."employee" as "employee","res_partner"."picking_warn" as "picking_warn","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."zip" as "zip","res_partner"."country_id" as "country_id","res_partner"."invoice_warn" as "invoice_warn","res_partner"."type" as "type","res_partner"."team_id" as "team_id","res_partner"."signup_token" as "signup_token","res_partner"."barcode" as "barcode","res_partner"."color" as "color","res_partner"."pin" as "pin","res_partner"."fax" as "fax","res_partner"."name" as "name","res_partner"."agent_dorm_rate" as "agent_dorm_rate","res_partner"."company_name" as "company_name","res_partner"."tz" as "tz","res_partner"."invoice_warn_msg" as "invoice_warn_msg","res_partner"."customer" as "customer","res_partner"."title" as "title","res_partner"."function" as "function","res_partner"."write_date" as "write_date","res_partner"."signup_type" as "signup_type","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."vat" as "vat","res_partner"."agent_private_rate" as "agent_private_rate","res_partner"."website" as "website","res_partner"."prefer_ereceipt" as "prefer_ereceipt","res_partner"."picking_warn_msg" as "picking_warn_msg","res_partner"."purchase_warn" as "purchase_warn","res_partner"."user_id" as "user_id","res_partner"."company_id" as "company_id" FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2018-09-04 16:53:10,742 27958 INFO localkamooni werkzeug: 127.0.0.1 - - [04/Sep/2018 16:53:10] "GET /web HTTP/1.1" 500 -
2018-09-04 16:53:10,786 27958 ERROR localkamooni werkzeug: Error on request:
Traceback (most recent call last):
  File "odoo/env/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "odoo/env/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "odoo/odoo/service/server.py", line 245, in app
    return self.app(e, s)
  File "odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "odoo/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)
  File "odoo/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "odoo/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "odoo/odoo/http.py", line 1499, in dispatch
    result = ir_http._dispatch()
  File "odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "odoo/odoo/http.py", line 775, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "odoo/odoo/http.py", line 834, in dispatch
    r = self._call_function(**self.params)
  File "odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "odoo/addons/web/controllers/main.py", line 446, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "odoo/addons/report/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "odoo/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "odoo/addons/barcodes/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "odoo/addons/web/models/ir_http.py", line 34, in session_info
    "name": user.name,
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1027, in determine_value
    self.compute_value(recs)
  File "odoo/odoo/fields.py", line 981, in compute_value
    self._compute_value(records)
  File "odoo/odoo/fields.py", line 974, in _compute_value
    self.compute(records)
  File "odoo/odoo/fields.py", line 625, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "odoo/odoo/models.py", line 5236, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "odoo/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "odoo/odoo/fields.py", line 1017, in determine_value
    record._prefetch_field(self)
  File "odoo/odoo/models.py", line 3073, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "odoo/odoo/models.py", line 3017, in read
    self._read_from_database(stored, inherited)
  File "odoo/odoo/models.py", line 3141, in _read_from_database
    cr.execute(query_str, params)
  File "odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by sbidoul** [comment]
Yes, it's not surprising, because you are attempting to do a full fledged login. Here it breaks when reading the user name.

My use case was a bit simpler as I was working in a `odoo shell` which does not initialize a full session. So having a proper context was sufficient to launch the upgrade. 

I'm afraid there is no solution in sight for your case, since xmlrpc requires a login.

**Comment by initialpuppet** [comment]
Ahh yes, I just tried it using the Python Odoo RPC client and get the same error.

Never mind, it's been interesting anyway. Thanks again to you and @pedrobaeza for your help.

**Comment by pedrobaeza** [comment]
This is how we autoupdate from command line: executing a shell script (https://github.com/Tecnativa/doodba/blob/master/bin/autoupdate) through this interpreter (https://github.com/Tecnativa/doodba/blob/master/bin/python-odoo-shell)

**Comment by initialpuppet** [comment]
@pedrobaeza thank you. As far as I can tell the main advantages of auto update over the -u switch are that there is no need to stop the Odoo server and the upgrade time will be less since only updated modules are upgraded. I guess also there is no need for the caller to know what modules to upgrade. Is this correct? What is the experience for active users on the server during the upgrade?

@sbidoul we actually do use ssh to restart the Odoo server when we deploy new code. I have just preferred RPC for the module upgrade since it is easier to parse and return the output from the operation. But, clearly it’s more important  for the upgrade to actually work than have a nice error message when it doesn’t!

**Comment by mianObaid14** [comment]
Hi
I recently started working on odoo framework and getting this similar error.Any one of you solution.

LINE 1: ...e","res_partner"."company_name" as "company_name","res_partn...
                                                             ^
 
2020-08-27 07:17:27,053 4888 ERROR task1 odoo.addons.base.models.ir_cron: Unexpected exception while processing cron job {'id': 39, 'ir_actions_server_id': 396, 'cron_name': 'Calendar: Event Reminder', 'user_id': 1, 'active': True, 'interval_number': 30, 'interval_type': 'minutes', 'numbercall': -1, 'doall': False, 'nextcall': datetime.datetime(2020, 8, 27, 7, 16, 58), 'lastcall': datetime.datetime(2020, 8, 27, 6, 47, 2), 'priority': 5, 'create_uid': 1, 'create_date': datetime.datetime(2020, 8, 19, 8, 16, 56, 348414), 'write_uid': 1, 'write_date': datetime.datetime(2020, 8, 19, 8, 16, 56, 348414)} 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1002, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(1,).tz', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1002, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(2,).tz', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_cron.py", line 237, in _process_jobs
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_cron.py", line 138, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1788, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1026, in __get__
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3920, in _compute_field_value
    field.compute(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 579, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 5619, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 1009, in __get__
    recs._fetch_field(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 2947, in _fetch_field
    self._read(fnames)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3019, in _read
    cr.execute(query_str, params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column res_partner.custome_stages does not exist
LINE 1: ...e","res_partner"."company_name" as "company_name","res_partn...

**Comment by mianObaid14** [comment]
This result's when i try to restart my server.
