### ISSUE TITLE
AttributeError: 'product.product' object has no attribute 'sale_delay'

### ISSUE THREAD

**Issue by tycoi2005** [odoo/odoo#26855]
**Impacted versions:**
11.0

**Steps to reproduce:**
install on ubuntu: 
 173  wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
  174  echo "deb http://nightly.odoo.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
  175  apt-get update && apt-get install odoo
install ecomerence and create some product.
open shop, add one product to cart
**Current behavior:**
error when add product to cart

**Video/Screenshot link (optional):**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in call
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/main.py", line 405, in cart_update
    attributes=self._filter_attributes(**kw),
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/sale_order.py", line 165, in _cart_update
    values = self._website_product_id_change(self.id, product_id, qty=1)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/sale_order.py", line 108, in _website_product_id_change
    'customer_lead': product.sale_delay,
AttributeError: 'product.product' object has no attribute 'sale_delay'

**Comment by sswapnesh** [comment]
Hello @simongoffin, 
I can confirm this bug.
`sale_delay` is part of [stock](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/product.py#L395) module which is not installed when you install `website_sale`.
