### ISSUE TITLE
Automated action with Trigger condition >> Based on Form Modification

### ISSUE THREAD

**Issue by KhichadiyaVK** [odoo/odoo#26902]
Impacted versions: odoo 11

Steps to reproduce: None

Current behavior: throw an error

Expected behavior: run the python code written in action

Video/Screenshot link (optional): 
![screenshot from 2018-09-11 16-51-14](https://user-images.githubusercontent.com/11441159/45357116-f015d880-b5e2-11e8-9477-e93caa2d0180.png)

Description : I'm creating a channel and put a message to update a variable that needed for lead in further process. The same python code will run when Trigger condition is On update and I get the result that I want .. But the same thing give me an error when I choose Based on Form Modification.

**Comment by pedrobaeza** [comment]
Please put the error you get (stack trace)

**Comment by KhichadiyaVK** [comment]
Server Error

Traceback (most recent call last):
  File "/home/odoo/Workspace/V11-Odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/Workspace/V11-Odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f6ed5a5bf98>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/Workspace/V11-Odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/Workspace/V11-Odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/Workspace/V11-Odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/Workspace/V11-Odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/models.py", line 5103, in onchange
    record.mapped(dotname)
  File "/home/odoo/Workspace/V11-Odoo/odoo/models.py", line 4512, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/Workspace/V11-Odoo/odoo/models.py", line 4491, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/Workspace/V11-Odoo/odoo/models.py", line 4491, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/Workspace/V11-Odoo/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/Workspace/V11-Odoo/odoo/fields.py", line 943, in __get__
    self.determine_draft_value(record)
  File "/home/odoo/Workspace/V11-Odoo/odoo/fields.py", line 1063, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo/Workspace/V11-Odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/Workspace/V11-Odoo/addons/mail/models/mail_thread.py", line 205, in _get_message_needaction
    (self.env.user.partner_id.id, self._name, tuple(self.ids),))
  File "/home/odoo/Workspace/V11-Odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/Workspace/V11-Odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 4: ...           WHERE msg.model = 'crm.lead' AND msg.res_id in ()

**Comment by pedrobaeza** [comment]
The stack trace shows an incorrect use of the code, so please fix it.

Closing as no real Odoo issue.

**Comment by sehrishnaz** [comment]
How automated action works: https://learnopenerp.blogspot.com/2020/05/how-to-create-scheduled-action-in-odoo.html
