### ISSUE TITLE
[11.0 POS Module] Order ID error - Orders cannot sync, session cannot close.

### ISSUE THREAD

**Issue by svenv** [odoo/odoo#27014]
**Impacted versions:** 

11.0 Community Edition

**Steps to reproduce:**

Not sure, we just validated an order in a POS session and the error popped up.

**Current behavior:**

Orders can't validate and remain in queue.

**Expected behavior:**

Orders can validate. We've been using Odoo POS for 8 months now and never had an issue. There are two custom plugin installed for Loyalty Management and Stock display, which have been working well for at least the past 1-2 months.

Video/Screenshot link (optional): 

**Error**

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/domains/pos.onc.co.ke/odoo/addons/pos_loyalty_management/models/pos_loyalty_management.py", line 227, in create_from_ui
    values.update({'pos_order_id': order['data']['lines'][0][2]['order_id'],
KeyError: 'order_id'
```

**Comment by svenv** [comment]
It seems it was Webkul's [loyalty management module ]([Webkul Loyalty Management Module](https://store.webkul.com/OpenERP-POS-Loyalty-Management.html))that was causing the issue. I had to re-install it.... but now the whole loyalty point database has dissapeared..! Any way to retrieve it?

**Comment by pedrobaeza** [comment]
No if you have uninstalled it. You should restore a backup of the full DB or copy data from it.

Closing as the error you are mentioning corresponds to a custom module or code. This issue tracker is for notifying problems with standard Odoo code.
