### ISSUE TITLE
ir.attachment has no attribute generate_access_token

### ISSUE THREAD

**Issue by andrewyova** [odoo/odoo#27084]
Impacted versions:11c/e

Steps to reproduce:
I just want to add an attachment in field HTML type
and error occurs like this : 
Traceback (most recent call last):
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11_andrew/odoo11c/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11_andrew/odoo11c/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11_andrew/odoo11c/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo11_andrew/odoo11c/odoo/api.py", line 685, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'ir.attachment' has no attribute 'generate_access_token'

Video/Screenshot link (optional):

![error11](https://user-images.githubusercontent.com/25319332/45737615-8ae06980-bc18-11e8-8bc0-3392da4f9876.png)

is there missing lib or anything else?
I have cloned this September 2018

**Comment by pedrobaeza** [comment]
Are you putting `fields.Html(attachment=True)` in your custom code?

**Comment by andrewyova** [comment]
> Are you putting `fields.Html(attachment=True)` in your custom code?

this is base module, i not use any custom module , only appear in my local

**Comment by andrewyova** [comment]
> Then it's for sure a deployment problem, as I'm not able to reproduce this problem in latest runbot version, and I'm going to close this issue.
> 
> If you are still experimenting the same problem in your side, try first to update your source code to latest version, restart your server, and make a general module update for being sure that the problem is not there.
> 
> If the problem continues, then it can be due to a third party module or indeed an Odoo bug. For discarding the first one, you have to try the use case in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

can u show me what python lib for need in odoo11?, hope can solve this issue

**Comment by pedrobaeza** [comment]
You should ask on forums, not here. Any way, there's a requirements.txt file for standard pip deployment.

**Comment by andrewyova** [comment]
i solve it with another odoo11 with old version, dont know what it cause anyway but thx @pedrobaeza
