### ISSUE TITLE
[11.0][Enterprise] account_reports: throws error if Cash Flow Statement is deleted

### ISSUE THREAD

**Issue by MartinAavastik** [odoo/odoo#27183]
Impacted versions:
 - 11.0

Steps to reproduce:
Install **account_reports**, then delete "Cash Flow Statement".
Try to view any report but for example "Profit and Loss" report and it throws error.

Current behavior:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fee9907d6a8>, 'account_reports.account_financial_report_cashsummary0')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 825, in __getitem__
    res = FormulaLine(self.curObj, self.currency_table, self.financial_report, type='sum')
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 783, in __init__
    fields = obj._get_sum(currency_table, financial_report)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 499, in _get_sum
    res = self.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to)._compute_line(currency_table, financial_report, group_by=self.groupby, domain=self.domain)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 420, in _compute_line
    sql, params = self._get_with_statement(financial_report)
  File "/mnt/common-addons/l10n_ee_reports/models/account_financial_report.py", line 30, in _get_with_statement
    and (financial_report == self.env.ref('account_reports.account_financial_report_cashsummary0', raise_if_not_found=True) or self.env.context.get('cash_basis')):
  File "/opt/odoo/odoo/api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1350, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account_reports.account_financial_report_cashsummary0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 849, in __getitem__
    res = FormulaLine(line_id.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to), self.currency_table, self.financial_report, linesDict=self.linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 825, in __getitem__
    res = FormulaLine(self.curObj, self.currency_table, self.financial_report, type='sum')
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 783, in __init__
    fields = obj._get_sum(currency_table, financial_report)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 499, in _get_sum
    res = self.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to)._compute_line(currency_table, financial_report, group_by=self.groupby, domain=self.domain)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 420, in _compute_line
    sql, params = self._get_with_statement(financial_report)
  File "/mnt/common-addons/l10n_ee_reports/models/account_financial_report.py", line 30, in _get_with_statement
    and (financial_report == self.env.ref('account_reports.account_financial_report_cashsummary0', raise_if_not_found=True) or self.env.context.get('cash_basis')):
  File "/opt/odoo/odoo/api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1350, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "External ID not found in the system: account_reports.account_financial_report_cashsummary0" while evaluating
' -sum.balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 849, in __getitem__
    res = FormulaLine(line_id.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to), self.currency_table, self.financial_report, linesDict=self.linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 849, in __getitem__
    res = FormulaLine(line_id.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to), self.currency_table, self.financial_report, linesDict=self.linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 825, in __getitem__
    res = FormulaLine(self.curObj, self.currency_table, self.financial_report, type='sum')
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 783, in __init__
    fields = obj._get_sum(currency_table, financial_report)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 499, in _get_sum
    res = self.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to)._compute_line(currency_table, financial_report, group_by=self.groupby, domain=self.domain)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 420, in _compute_line
    sql, params = self._get_with_statement(financial_report)
  File "/mnt/common-addons/l10n_ee_reports/models/account_financial_report.py", line 30, in _get_with_statement
    and (financial_report == self.env.ref('account_reports.account_financial_report_cashsummary0', raise_if_not_found=True) or self.env.context.get('cash_basis')):
  File "/opt/odoo/odoo/api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1350, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "<class 'ValueError'>: "External ID not found in the system: account_reports.account_financial_report_cashsummary0" while evaluating
' -sum.balance'" while evaluating
' OPINC.balance + OIN.balance - COS.balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/enterprise/account_reports/models/account_report.py", line 315, in get_report_informations
    'main_html': self.get_html(options),
  File "/mnt/enterprise/account_reports/models/account_report.py", line 485, in get_html
    lines = self.with_context(self.set_context(options)).get_lines(options, line_id=line_id)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 146, in get_lines
    ).get_lines(self, currency_table, options, linesDicts)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 691, in get_lines
    r = line.with_context(date_from=date_from, date_to=date_to, strict_range=strict_range)._eval_formula(financial_report, debit_credit, currency_table, linesDicts[k])
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 599, in _eval_formula
    res = FormulaLine(self, currency_table, financial_report, linesDict=linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 849, in __getitem__
    res = FormulaLine(line_id.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to), self.currency_table, self.financial_report, linesDict=self.linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 849, in __getitem__
    res = FormulaLine(line_id.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to), self.currency_table, self.financial_report, linesDict=self.linesDict)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 775, in __init__
    fields = obj.get_balance(linesDict, currency_table, financial_report)[0]
  File "<decorator-gen-87>", line 2, in get_balance
  File "/opt/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 519, in get_balance
    raise err
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 514, in get_balance
    res[field] = safe_eval(formula, c, nocopy=True)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 825, in __getitem__
    res = FormulaLine(self.curObj, self.currency_table, self.financial_report, type='sum')
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 783, in __init__
    fields = obj._get_sum(currency_table, financial_report)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 499, in _get_sum
    res = self.with_context(strict_range=strict_range, date_from=date_from, date_to=date_to)._compute_line(currency_table, financial_report, group_by=self.groupby, domain=self.domain)
  File "/mnt/enterprise/account_reports/models/account_financial_report.py", line 420, in _compute_line
    sql, params = self._get_with_statement(financial_report)
  File "/mnt/common-addons/l10n_ee_reports/models/account_financial_report.py", line 30, in _get_with_statement
    and (financial_report == self.env.ref('account_reports.account_financial_report_cashsummary0', raise_if_not_found=True) or self.env.context.get('cash_basis')):
  File "/opt/odoo/odoo/api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1350, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1334, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'ValueError'>: "<class 'ValueError'>: "<class 'ValueError'>: "External ID not found in the system: account_reports.account_financial_report_cashsummary0" while evaluating
' -sum.balance'" while evaluating
' OPINC.balance + OIN.balance - COS.balance'" while evaluating
' INC.balance - LEX.balance'
```

Expected behavior:

Not throw error.

Notes:
This error comes from account_reports/models/account_financial_report.py function **_get_with_statement** where there is self.env.ref('account_reports.account_financial_report_cashsummary0').

It should be self.env.ref('account_reports.account_financial_report_cashsummary0', raise_if_not_found=False)

**Comment by mart-e** [comment]
Hello,

Sorry but the issue seems to be with the module `l10n_ee_reports`. This module is not one we have made so we can't help you much here.
Please check with the developer of the module.
