### ISSUE TITLE
[Account] should restricted move line name as required.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#27281]
Impacted versions:
12 

Steps to reproduce:

1. enable analystic accounting
2. create account move manually, and set analystic account for move line
3. post the move,  raise `IntegrityError`  exception.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

fix this line
https://github.com/odoo/odoo/blob/d3ee7a7a1597cd4fd93fc36c627bbade3eafa6eb/addons/account/views/account_view.xml#L1468
to enable `required`

**Comment by mart-e** [comment]
Hello,

Could you detail where did you get an IntegirtyError exactly? If you have a traceback with more info, it is a good idea to post it.
I jusst tried but did not get an error.

**Comment by jeffery9** [comment]
```
2018-09-28 11:50:27,860 17384 DEBUG odoo12 odoo.api: call account.move(10,).action_post() 
2018-09-28 11:50:27,861 17384 INFO odoo12 werkzeug: 127.0.0.1 - - [28/Sep/2018 11:50:27] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 - 2 0.004 0.007
2018-09-28 11:50:27,922 17384 ERROR odoo12 odoo.sql_db: bad query: b'INSERT INTO "account_analytic_line" ("id", "create_uid", "create_date", "write_uid", "write_date", "account_id", "amount", "company_id", "date", "general_account_id", "move_id", "name", "partner_id", "product_id", "product_uom_id", "ref", "unit_amount", "user_id") VALUES (nextval(\'account_analytic_line_id_seq\'), 2, (now() at time zone \'UTC\'), 2, (now() at time zone \'UTC\'), 27, 0.0, 3, \'2018-09-28\', 106, 22, NULL, NULL, NULL, NULL, \'test\', 0.0, 2) RETURNING id'
ERROR: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (40, null, 2018-09-28, 0.0, 0, null, 27, null, 2, 3, null, null, 2, 2018-09-28 11:50:27.861568, 2, 2018-09-28 11:50:27.861568, null, 106, 22, null, test, null, null, null, null, null, null, null, null).
 
2018-09-28 11:50:27,924 17384 DEBUG odoo12 odoo.service.model: IntegrityError 
Traceback (most recent call last):
  File "E:\_odoo\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\_odoo\odoo\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\_odoo\odoo\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "E:\_odoo\odoo\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "E:\_odoo\odoo\addons\web\controllers\main.py", line 944, in call_button
    action = self._call_kw(model, method, args, {})
  File "E:\_odoo\odoo\addons\web\controllers\main.py", line 932, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\_odoo\odoo\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "E:\_odoo\odoo\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "E:\_odoo\odoo\addons\account\models\account_move.py", line 325, in action_post
    return self.post()
  File "E:\_odoo\odoo\addons\account_asset\models\account.py", line 24, in post
    return super(AccountMove, self).post(invoice=invoice)
  File "E:\_odoo\odoo\addons\account\models\account_move.py", line 288, in post
    move.line_ids.create_analytic_lines()
  File "E:\_odoo\odoo\addons\account\models\account_move.py", line 1236, in create_analytic_lines
    self.env['account.analytic.line'].create(vals_line)
  File "<decorator-gen-378>", line 2, in create
  File "E:\_odoo\odoo\odoo\api.py", line 430, in _model_create_single
    return create(self, arg)
  File "E:\_odoo\odoo\addons\sale\models\analytic.py", line 21, in create
    result = super(AccountAnalyticLine, self).create(values)
  File "<decorator-gen-333>", line 2, in create
  File "E:\_odoo\odoo\odoo\api.py", line 430, in _model_create_single
    return create(self, arg)
  File "E:\_odoo\odoo\addons\hr_timesheet\models\hr_timesheet.py", line 67, in create
    result = super(AccountAnalyticLine, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "E:\_odoo\odoo\odoo\api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "E:\_odoo\odoo\odoo\models.py", line 3499, in create
    records = self._create(data_list)
  File "E:\_odoo\odoo\odoo\models.py", line 3599, in _create
    cr.execute(query, params)
  File "E:\_odoo\odoo\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "E:\_odoo\odoo\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (40, null, 2018-09-28, 0.0, 0, null, 27, null, 2, 3, null, null, 2, 2018-09-28 11:50:27.861568, 2, 2018-09-28 11:50:27.861568, null, 106, 22, null, test, null, null, null, null, null, null, null, null).

2018-09-28 11:50:28,331 17384 INFO odoo12 werkzeug: 127.0.0.1 - - [28/Sep/2018 11:50:28] "POST /web/dataset/call_button HTTP/1.1" 200 - 40 0.044 0.431
2018-09-28 11:50:28,393 17384 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2018 11:50:28] "GET /web/static/src/xml/dialog.xml HTTP/1.1" 200 - - - -
2018-09-28 11:50:36,780 17384 INFO odoo12 werkzeug: 127.0.0.1 - - [28/Sep/2018 11:50:36] "POST /longpolling/poll HTTP/1.1" 200 - 8 0.022 50.030
2018-09-28 11:50:36,811 17384 DEBUG odoo12 odoo.modules.registry: Multiprocess signaling check: [Registry - 13 -> 13] [Cache - 46 -> 46]
```
