### ISSUE TITLE
[12] Could not Open Attendance Configuration

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27407]
Impacted versions: 12.0

Steps to reproduce: Go to `Attendances` --> `Configuration`
Performed on [Runbot](http://380908-27403-2b2773.runbot16.odoo.com/web?debug=true&reload=#action=305&menu_id=219)
Current behavior:
```
Uncaught TypeError: Cannot read property 'settingView' of undefined
http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:5
Traceback:
TypeError: Cannot read property 'settingView' of undefined
    at Class._moveToTab (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:5:42)
    at Class._renderLeftPanel (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:8:315)
    at Class._render (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:7:716)
    at Class.prototype.(anonymous function) [as _render] (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2098-797ddc4/web.assets_common.js:3537:488)
    at Class.start (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:1260:335)
    at Class.prototype.(anonymous function) [as start] (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2098-797ddc4/web.assets_common.js:3537:488)
    at Class.start (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:1585:20)
    at Class.prototype.(anonymous function) [as start] (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2098-797ddc4/web.assets_common.js:3537:488)
    at Class.start (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2099-ede9c3a/web.assets_backend.js:3:654)
    at Class.prototype.(anonymous function) [as start] (http://380908-27403-2b2773.runbot16.odoo.com/web/content/2098-797ddc4/web.assets_common.js:3537:488)
```
![127](https://user-images.githubusercontent.com/16624719/46437691-93d54d00-c779-11e8-9f9c-1326cca3d4a5.png)

Expected behavior: Open Settings

Video/Screenshot link (optional):

**Comment by jpr-odoo** [comment]
Hello @sswapnesh 
 I've just tested it and it's working fine. thanks for report 
rev no: http://396870-12-0-dcc077.runbot16.odoo.com

**Comment by infoedgarpc1** [comment]
I also have the same error but I am lost I do not know what the javascript code is to correct I would like it to help me do not open the view of general options

**Comment by infoedgarpc1** [comment]
my error is 

Error:
Uncaught TypeError: Cannot read property 'settingView' of undefined

http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:5
Rastreo de error:
TypeError: Cannot read property 'settingView' of undefined
    at Class._moveToTab (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:5:42)
    at Class._renderLeftPanel (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:8:315)
    at Class._render (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:7:716)
    at Class.prototype.(anonymous function) [as _render] (http://192.168.174.125/web/content/13317-f8f9bf2/web.assets_common.js:33:30534)
    at Class.start (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:1274:335)
    at Class.prototype.(anonymous function) [as start] (http://192.168.174.125/web/content/13317-f8f9bf2/web.assets_common.js:33:30534)
    at Class.start (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:1607:20)
    at Class.prototype.(anonymous function) [as start] (http://192.168.174.125/web/content/13317-f8f9bf2/web.assets_common.js:33:30534)
    at Class.start (http://192.168.174.125/web/content/13380-68620f1/web.assets_backend.js:3:654)
    at Class.prototype.(anonymous function) [as start] (http://192.168.174.125/web/content/13317-f8f9bf2/web.assets_common.js:33:30534)

**Comment by infoedgarpc1** [comment]
![image](https://user-images.githubusercontent.com/45404476/55195629-2b40b900-517b-11e9-8447-0042fbc8606a.png)
