### ISSUE TITLE
[12] Could not Duplicate Database

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27404]
Impacted versions: 12

Steps to reproduce: Go to `http://localhost:8069/web/database/manager`

Current behavior:
```
   application_iter = app(environ, start_response)
  File "/home/swapnesh/Workspace/12/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/home/swapnesh/Workspace/12/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/home/swapnesh/Workspace/12/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/swapnesh/Workspace/12/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/home/swapnesh/Workspace/12/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/swapnesh/Workspace/12/odoo/http.py", line 1489, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/home/swapnesh/Workspace/12/odoo/http.py", line 284, in __exit__
    self._cr.commit()
  File "/home/swapnesh/Workspace/12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/swapnesh/Workspace/12/odoo/sql_db.py", line 372, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed - - -

```
Expected behavior:
Able to Duplicate Database
Video/Screenshot link (optional):

**Comment by HirenDangar** [comment]
Yes I also face same issue.

**Comment by wamdam** [comment]
Yes, I have this too on my local dev machine. However line numbers have changed meanwhile.

`Traceback (most recent call last):
  File "/home/dk/develop/odoo11/env/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/dk/develop/odoo11/env/lib/python3.6/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/dk/develop/odoo11/odoo/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/home/dk/develop/odoo11/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/dk/develop/odoo11/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/dk/develop/odoo11/odoo/odoo/http.py", line 1319, in __call__
    return self.dispatch(environ, start_response)
  File "/home/dk/develop/odoo11/odoo/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/home/dk/develop/odoo11/env/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/dk/develop/odoo11/odoo/odoo/http.py", line 1495, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/home/dk/develop/odoo11/odoo/odoo/http.py", line 282, in __exit__
    self._cr.commit()
  File "/home/dk/develop/odoo11/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/dk/develop/odoo11/odoo/odoo/sql_db.py", line 375, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed
`

**Comment by Elkasitu** [comment]
There seem to be some missing steps as I cannot reproduce this locally...

Did you try this on a production database or in a fresh one? Did you use a zip backup or a pg_dump bacup? What apps did you have installed on your instance? etc.

**Comment by sswapnesh** [comment]
> There seem to be some missing steps as I cannot reproduce this locally...

I can not reproduce this now, Duplicating DB works well now.


> Did you try this on a production database or in a fresh one ?  What apps did you have installed on your instance ? etc.

It was Fresh DB.

> Did you use a zip backup or a pg_dump bacup?

![screenshot](https://user-images.githubusercontent.com/16624719/53180332-618a9600-361b-11e9-89c6-1d5a7e4ca070.png)
