### ISSUE TITLE
[12] Uncaught TypeError: self.menu.change_menu_section is not a function

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27436]
Impacted versions: 12.0

Steps to reproduce: Set Home Action --> Login Again

Current behavior:
![136](https://user-images.githubusercontent.com/16624719/46487679-3e9f4700-c81e-11e8-987b-dcb9ec0c5988.png)

Expected behavior:
Should Load Action
Video/Screenshot link (optional):

**Comment by C-Fu** [comment]
Same problem when installing Inventory from Apps
Inventory shows installed though

Oh and the copy to clipboard function doesn't work

Installed odoo via docker

Uncaught TypeError: self.menu.change_menu_section is not a function
http://localhost:8069/web/content/426-18b7e3a/web.assets_backend.js:563
Traceback:
TypeError: self.menu.change_menu_section is not a function
    at http://localhost:8069/web/content/426-18b7e3a/web.assets_backend.js:563:433
    at http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:801:198)
    at deferred.(anonymous function) (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:803:56)
    at fire (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:801:198)
    at http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:802:874
    at fire (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/363-ce9ee69/web.assets_common.js:801:198)

**Comment by C-Fu** [comment]
The commit works on my end! Cool thanks 🕺
