### ISSUE TITLE
12.0 docker version failed

### ISSUE THREAD

**Issue by debianmaster** [odoo/odoo#27446]
Impacted versions:
12.0  docker version

Steps to reproduce:
point 12.0  to a database that is running with 11.0   (shutdown 11.0 and bring up 12.0)

Current behavior:
```sh

2018-10-05 08:56:35,468 1 WARNING odoo odoo.modules.module: module web_planner: module not found
--
  | 2018-10-05 08:56:35,471 1 ERROR odoo odoo.sql_db: bad query: b'SELECT "res_lang"."id" as "id","res_lang"."time_format" as "time_format","res_lang"."name" as "name","res_lang"."active" as "active","res_lang"."write_uid" as "write_uid","res_lang"."write_date" as "write_date","res_lang"."thousands_sep" as "thousands_sep","res_lang"."date_format" as "date_format","res_lang"."create_uid" as "create_uid","res_lang"."translatable" as "translatable","res_lang"."decimal_point" as "decimal_point","res_lang"."week_start" as "week_start","res_lang"."iso_code" as "iso_code","res_lang"."create_date" as "create_date","res_lang"."grouping" as "grouping","res_lang"."direction" as "direction","res_lang"."code" as "code" FROM "res_lang" WHERE "res_lang".id IN (1)'
  | ERROR: column res_lang.week_start does not exist
  | LINE 1: ...le","res_lang"."decimal_point" as "decimal_point","res_lang"...
  | ^
  |  
  | 2018-10-05 08:56:35,472 1 ERROR odoo odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" WHERE (("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'web.login_layout\')) ORDER BY "ir_ui_view"."priority" ,"ir_ui_view"."name" ,"ir_ui_view"."id"  '
  | ERROR: current transaction is aborted, commands ignored until end of transaction block
  |  
  | 2018-10-05 08:56:35,565 1 INFO odoo werkzeug: 10.1.4.1 - - [05/Oct/2018 08:56:35] "GET /web/login HTTP/1.1" 500 - 74 0.084 0.684
  | 2018-10-05 08:56:35,572 1 ERROR odoo werkzeug: Error on request:
  | Traceback (most recent call last):
  | File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi


```
Expected behavior:
odoo up and running

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

The version 12.0 and 11.0 are not compatible, you need to migrate your database first.
The upgrade to v12 will soon be available for enterprise customers at https://upgrade.odoo.com/

**Comment by debianmaster** [comment]
Fresh docker 12.0 is failing too 

this is failing too
```sh
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo  --name db postgres:9.4
docker run -p 8069:8069 -d --link db:db --name=odoo  odoo:12.0
```


```sh
chakwifi:~ cjonagam$ docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo  --name db postgres:9.4
51a1534ccddcfc5a0a766285369ce6b04348bf46bf553d9ddaccc207ea6d703b
chakwifi:~ cjonagam$ docker run -p 8069:8069 -d --link db:db --name=odoo  odoo:12.0
9c8bd0327099ac67852400f369d56649b4430c1874099afc6ee81619c8fa63dd
chakwifi:~ cjonagam$ docker logs -f odoo
2018-10-05 09:55:46,473 1 INFO ? odoo: Odoo version 12.0-20181004
2018-10-05 09:55:46,474 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-10-05 09:55:46,474 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-10-05 09:55:46,474 1 INFO ? odoo: database: odoo@172.17.0.2:5432
2018-10-05 09:55:46,568 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-10-05 09:55:46,673 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 9c8bd0327099:8069
2018-10-05 09:56:10,133 1 INFO ? odoo.http: HTTP Configuring static files
2018-10-05 09:56:10,162 1 ERROR odoo odoo.modules.loading: Database odoo not initialized, you can force it with `-i base`
2018-10-05 09:56:10,165 1 INFO odoo werkzeug: 172.17.0.1 - - [05/Oct/2018 09:56:10] "GET / HTTP/1.1" 500 - 10 0.010 0.020
2018-10-05 09:56:10,171 1 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1470, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
```

**Comment by debianmaster** [comment]
created another issue for this https://github.com/odoo/odoo/issues/27447

**Comment by phatminh** [comment]
So how can i Fix it?

**Comment by jlegido** [comment]
@phatminh  the fix is use an older version of Postgres.

I tested several combinations, and in my case Odoo 13.0 works OK with Postgres 10.4, and fails with versions 10.5 and above.

Hope this can help.
