### ISSUE TITLE
[12] FacturX error printed Invoice with description

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#27459]
**Impacted versions:**
12
**Steps to reproduce:**
Create a Customer invoice, set Reference/Description, Validate Invoice, Try print PDF, get error 

![image](https://user-images.githubusercontent.com/7775116/46561319-a02ae880-c8e6-11e8-866f-33d14908dfa6.png)

![image](https://user-images.githubusercontent.com/7775116/46561197-34e11680-c8e6-11e8-962e-5e7d7365501e.png)

**Current behavior:**
When Invoice has field **Reference/Description**, get error on report
Error on [this lines](https://github.com/odoo/odoo/blob/12.0/addons/account_facturx/data/facturx_templates.xml#L162) bad format string possibly
Note: If invoice has not fill Name/Description, no error
**Expected behavior:**
No error at printed report
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Same Error on Email template too.
![screenshot 4](https://user-images.githubusercontent.com/16624719/46622797-5a218f00-cb49-11e8-8bc9-8828b9e79f5c.png)
![screenshot 5](https://user-images.githubusercontent.com/16624719/46622963-c43a3400-cb49-11e8-950e-3c17bd64bcf6.png)
![screenshot 6](https://user-images.githubusercontent.com/16624719/46622994-d9af5e00-cb49-11e8-932b-634d7c052ad1.png)

**Comment by celm1990** [comment]
@nguyenquangtoan not is same error, please scroll to bottom for better log information

**Comment by nguyenquangtoan** [comment]
Sorry, this is my log:
---------------------------
"Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_190_1486
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 387, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 126, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/odoo/odoo-server/addons/snailmail/models/ir_qweb_fields.py", line 13, in value_to_html
    return super(Contact, self).value_to_html(value, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 646, in value_to_html
    name_get = value.name_get()[0][1]
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 628, in name_get
    name = partner._get_name()
  File "/odoo/odoo-server/addons/website/models/res_partner.py", line 43, in _get_name
    name = super(Partner, self)._get_name()
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 611, in _get_name
    name = name + "\n" + partner._display_address(without_company=True)
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 843, in _display_address
    return address_format % args
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1668, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1609, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 665, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo/enterprise/addons/web_studio/models/ir_actions_report.py", line 15, in render_qweb_html
    return super(IrActionsReport, self).render_qweb_html(docids, data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 699, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 489, in render_template
    return view_obj.render_template(template, values)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1269, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 229, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1278, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/enterprise/addons/web_studio/models/ir_qweb.py", line 48, in render
    return super(IrQWeb, self).render(template, values=values, **options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_575_1583
  File "<template>", line 2, in body_call_content_1582
  File "<template>", line 3, in foreach_1581
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_573_1636
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_191_1474
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 351, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'name'
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_190_1486
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 387, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 126, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/odoo/odoo-server/addons/snailmail/models/ir_qweb_fields.py", line 13, in value_to_html
    return super(Contact, self).value_to_html(value, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 646, in value_to_html
    name_get = value.name_get()[0][1]
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 628, in name_get
    name = partner._get_name()
  File "/odoo/odoo-server/addons/website/models/res_partner.py", line 43, in _get_name
    name = super(Partner, self)._get_name()
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 611, in _get_name
    name = name + "\n" + partner._display_address(without_company=True)
  File "/odoo/odoo-server/odoo/addons/base/models/res_partner.py", line 843, in _display_address
    return address_format % args
KeyError: 'name'

Error to render compiling AST
KeyError: 'name'
Template: 190
Path: /templates/t/div[1]/div[3]/div/div
Node: <div t-field="company.partner_id" t-options="{&quot;widget&quot;: &quot;contact&quot;, &quot;fields&quot;: [&quot;address&quot;, &quot;name&quot;], &quot;no_marker&quot;: true}"/>"

**Comment by Yenthe666** [comment]
Hi guys,

https://github.com/odoo/odoo/pull/27669 should handle this!

**Comment by celm1990** [comment]
Hi, 
Thanks so much, I tested with latest code and no error, sent email without error too.

@nguyenquangtoan your error is different, please open new issue, not related here
