### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by gokusanSK** [odoo/odoo#27580]
Impacted versions:
odoo12

Steps to reproduce:
i have created two view one is re-declaration of predefined view which is( delivery.sale.order.form.view.with_carrier) and inherited sale.order.form.inherit for other view 
Current behavior:
when i try to open sale order record in form view i got the error 
Uncaught TypeError: Cannot read property 'type' of undefined
```
http://localhost:1456/web/content/635-2dd910a/web.assets_backend.js:1441
Traceback:
TypeError: Cannot read property 'type' of undefined
    at http://localhost:1456/web/content/635-2dd910a/web.assets_backend.js:1441:395
    at Function._.each._.forEach (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:12:558)
    at Class._parseServerData (http://localhost:1456/web/content/635-2dd910a/web.assets_backend.js:1441:290)
    at http://localhost:1456/web/content/635-2dd910a/web.assets_backend.js:1452:450
    at Function._.each._.forEach (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:12:558)
    at Object.<anonymous> (http://localhost:1456/web/content/635-2dd910a/web.assets_backend.js:1452:37)
    at Object.<anonymous> (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:802:681)
    at fire (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:1456/web/content/634-18d1f74/web.assets_common.js:803:56)
```
Expected behavior:
it should open form view with customization

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Sorry but we do not have enough details to help you. You do not give the code you have made. At least give your code in [debug asset mode](https://odoo-development.readthedocs.io/en/latest/odoo/usage/debug-assets-mode.html) so we have more details.

Also, keep in mind that github is only for bugs reporting on the standard Odoo. Not for questions or development help.
If you believe there is a bug, give us a scenario where we can reproduce the issue.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by Yenthe666** [comment]
Hi,

As we haven't recieved more feedback in the meanwhile we're closing off this issue.
If you can still reproduce it on the latest Odoo instance then don't hesitate to respond back with more steps about how to reproduce it.

Regards,
Yenthe
