### ISSUE TITLE
email marketing error

### ISSUE THREAD

**Issue by atelier-siva** [odoo/odoo#27653]
Impacted versions: 11

Steps to reproduce:

start with a fresh odoo's database
language french and country canada
install the email marketing module
create a contact for Newsletter
create a newsletter in mass mailing
when i click on the many2many_tag to select a mailing list i got an error.

Current behavior:

> `Uncaught TypeError: Cannot read property 'apply' of undefined
https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:296
Retraçage :
TypeError: Cannot read property 'apply' of undefined
    at OdooClass.normalizeArray (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:296:920)
    at Class._initialize (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:699:158)
    at Class.prototype.(anonymous function) [as _initialize] (https://domain.com/web/content/806-7781941/web.assets_common.js:3816:488)
    at Class._redraw (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:701:176)
    at Class.setDomain (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:699:73)
    at Class._render (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:941:301)
    at Class.reset (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:892:353)
    at https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:1323:237
    at Function._.each._.forEach (https://domain.com/web/content/806-7781941/web.assets_common.js:12:558)
    at Class.confirmChange (https://domain.com/web/content/1514-3bd5d39/web.assets_backend.js:1323:78)`

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please try on runbot (https://runbot.odoo.com with admin/admin). I think this error can be because you have switch very quick from one field to another.

**Comment by atelier-siva** [comment]
Finally, instead to reuse my backup before installing the email marketing module, i unistall it and it mass mailing campain. After i reinstalled the modules my error gone and all seem to work well!
