### ISSUE TITLE
[12.0]After deleting the model in the code, updating the module will prompt you to not find the model and will not automatically clear the relevant information.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#27758]
Impacted versions:
12.0
Steps to reproduce:
- i create a model 'sale.recycling'
- i update module
- i remove code ,throw error
- According to the past, the system will automatically clear this information.
`
"
Odoo Server Error
Traceback (most recent call last):
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x11438f2b0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model(343,).count', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/models.py", line 5039, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/addons/base/models/ir_model.py", line 138, in _compute_count
    records = self.env[model.model]
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/api.py", line 820, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/Users/linjun/PycharmProjects/odoo_source/odoo/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'sale.recycling'
"
`
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Did you restart server and upgraded module after removing your code?

**Comment by sum1201** [comment]
I tried to restart the service, but I still get an error.  @sswapnesh @pedrobaeza 
I have been using Odoo's development experience for 6 years.

**Comment by sswapnesh** [comment]
@sum1201
I have tested it on latest v12 community and Confirm this is a Bug.

> I have been using Odoo's development experience for 6 years.
That's Great , I don't have any Doubt on that. (y)

**Comment by sum1201** [comment]
Thank you very much, I look forward to fixing this bug as soon as possible.

**Comment by sum1201** [comment]
@Yenthe666 ,@pedrobaeza, please help me

**Comment by sswapnesh** [comment]
This is still happening on latest v12.

**Comment by gdgellatly** [comment]
Yep, the only solution I found was

```sql
DELETE FROM ir_model WHERE model = <model>;
```

Then it all seems to go OK.

**Comment by wtaferner** [comment]
To extend the cleanup @gdgellatly proposed you could use these statements to get rid of dead model data.

```sql
DELETE FROM ir_model_fields WHERE model = '<model>';
DELETE FROM ir_model_constraint WHERE model = (SELECT id FROM ir_model WHERE model = '<model>');
DELETE FROM ir_model_relation WHERE model = (SELECT id FROM ir_model WHERE model = '<model>');
DELETE FROM ir_model WHERE model = '<model>';
```

**Comment by jeffery9** [comment]
发自我的华为手机
the same issue

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [12.0]After deleting the model in the code, updating the module will prompt you to not find the model and will not automatically clear the relevant information. (#27758)
发件人：odooqs
收件人：odoo/odoo
抄送：Subscribed


I think this is a bug ,odoo should be fix it

**Comment by jeffery9** [comment]
thanks

**Comment by sswapnesh** [comment]
wILL BE CLOSED BY pr https://github.com/odoo/odoo/pull/29247

**Comment by sswapnesh** [comment]
Closed in https://github.com/odoo/odoo/commit/1c79723a754980e1281afd6d20502532d50f8a17

**Comment by YASSlNE** [comment]
> Yep, the only solution I found was
> 
> ```sql
> DELETE FROM ir_model WHERE model = <model>;
> ```
> 
> Then it all seems to go OK.

This solved my problem

**Comment by mark-wellson** [comment]
the same issue in version 15.0 but solved by @gdgellatly and @wtaferner solution!!

**Comment by totalard** [comment]
still not solved, faced same issue in odoo 17

**Comment by progsmile** [comment]
+1 For odoo 17
