### ISSUE TITLE
hr_holidays: ValueError: Expected singleton: hr.leave(4, 1)

### ISSUE THREAD

**Issue by qndi** [odoo/odoo#27846]
Impacted versions: 12

Steps to reproduce:
Create a new company-wide leave request and confirm it (there should be at least one employee).
Afterwards open the new leave by clicking on the entry in the list view.

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f755bc28d68>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.leave(4,).number_of_hours_display', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/models.py", line 5042, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "/home/andreas/gitrepos/demo12e/ext/odoo/addons/hr_holidays/models/hr_leave.py", line 358, in _compute_number_of_hours_display
    calendar = self.employee_id.resource_calendar_id or self.env.user.company_id.resource_calendar_id
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/fields.py", line 968, in __get__
    record.ensure_one()
  File "/home/andreas/gitrepos/demo12e/ext/odoo/odoo/models.py", line 4643, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: hr.leave(4, 1)

Expected behavior:
No Stacktrace

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Fixed in commit d56a45ffd29ad2be3ed96b0c999f478b145e57 (PR  https://github.com/odoo/odoo/pull/27862)

**Comment by Yenthe666** [comment]
Has been fixed indeed, thanks for the report!
