### ISSUE TITLE
[11.0] issue during install base_sparse_field in migrated database.

### ISSUE THREAD

**Issue by AMhadhbi** [odoo/odoo#27890]
Impacted versions:
11.0
Steps to reproduce:
I want to use fields.Serialized so I added base_sparse_field, during install base_sparse_field module, 
I found issue **TypeError: 'NoneType' object does not support item assignment**
Current behavior:
`2018-10-17 12:55:06,049 16712 WARNING odoo_migrated odoo.modules.loading: Transient module states were reset
2018-10-17 12:55:06,051 16712 ERROR odoo_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/www/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/var/www/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/var/www/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/var/www/odoo/modules/registry.py", line 274, in setup_models
    model._setup_base()
  File "/var/www/odoo/models.py", line 2400, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/var/www/odoo/addons/base/ir/ir_model.py", line 893, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/var/www/odoo/addons/base/ir/ir_model.py", line 884, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/var/www/addons/base_sparse_field/models/models.py", line 49, in _instanciate_attrs
    attrs['sparse'] = serialization_record.name
TypeError: 'NoneType' object does not support item assignment
2018-10-17 12:55:06,060 16712 ERROR odoo_migrated_yarabb odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/var/www/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/www/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/var/www/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/var/www/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/var/www/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/www/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/var/www/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/var/www/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/www/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/var/www/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/var/www/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/var/www/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/var/www/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/var/www/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/var/www/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/var/www/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/var/www/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/var/www/odoo/modules/registry.py", line 274, in setup_models
    model._setup_base()
  File "/var/www/odoo/models.py", line 2400, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/var/www/odoo/addons/base/ir/ir_model.py", line 893, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/var/www/odoo/addons/base/ir/ir_model.py", line 884, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/var/www/addons/base_sparse_field/models/models.py", line 49, in _instanciate_attrs
    attrs['sparse'] = serialization_record.name
TypeError: 'NoneType' object does not support item assignment
`
Thanks

**Comment by pedrobaeza** [comment]
What do you mean by "migration database"?

**Comment by AMhadhbi** [comment]
After migrate database erp7 to odoo 11.
I have fields.serialized in erp7 so I migrated to  fields.Serialized because ( AttributeError: module 'odoo.fields' has no attribute 'Serialized' ) I added dependency in customise module **base_sparse_field** I found this issue during install base_sparse_field

**Comment by AMhadhbi** [comment]
Fixed by delete Base External Referentials module in the apps
so everything is fine , this issue related my local database, I will close this issue. thanks
