### ISSUE TITLE
[12.0] res.partner haven't field 'street_name'

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#27973]
Impacted versions:
12.0
Steps to reproduce:

> ``2018-10-19 10:30:26,448 7486 ERROR j-well odoo.addons.base.models.ir_cron: Unexpected exception while processing cron job {'priority': 1000, 'cron_name': 'Mail: Notify channel moderators', 'numbercall': -1, 'ir_actions_server_id': 100, 'interval_number': 1, 'write_date': datetime.datetime(2018, 10, 18, 23, 58, 8, 29459), 'user_id': 1, 'nextcall': datetime.datetime(2018, 10, 18, 23, 58, 10), 'interval_type': 'days', 'doall': False, 'create_date': datetime.datetime(2018, 10, 18, 23,
58, 8, 29459), 'active': True, 'write_uid': 1, 'id': 4, 'create_uid': 1}
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f68ceb08048>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(1,).tz', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f68ceb08048>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(2,).tz', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_cron.py", line 223, in _process_jobs
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_cron.py", line 129, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "/odoo/odoo-server/odoo/fields.py", line 1655, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "/odoo/odoo-server/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 1034, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/odoo/fields.py", line 608, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/odoo/odoo-server/odoo/models.py", line 5039, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/odoo/fields.py", line 974, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1075, in determine_value
    record._prefetch_field(self)
  File "/odoo/odoo-server/odoo/models.py", line 2813, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/odoo/odoo-server/odoo/models.py", line 2757, in read
    self._read_from_database(stored, inherited)
  File "/odoo/odoo-server/odoo/models.py", line 2876, in _read_from_database
    cr.execute(query_str, params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_partner.street_name does not exist
LINE 1: ...street2","res_partner"."parent_id" as "parent_id","res_partn...
                                                             ^``

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That aren't the steps to reproduce but the error, so how do you get to that error? Put all the detailed steps, your configuration (company country, etc).

**Comment by sum1201** [comment]
@pedrobaeza
module :partner_autocomplete_address_extended   auto_install: true
module: base_address_extended auto_install: false

The definition of the field street_name is in the module base_address_extended. The module partner_autocomplete_address_extended has the field stree_name.

I think this is a bug.
