### ISSUE TITLE
Multi worker:  timed out

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#28084]
Impacted versions: 8.0
using multi worker produce this Error:
```
2018-10-23 20:55:22,987 15946 INFO DBase werkzeug: 102.102.241.172 - - [23/Oct/2018 20:55:22] "GET /web/js/web.assets_backend/7e3ea98 HTTP/1.1" 200 -
2018-10-23 20:55:24,491 15946 ERROR DBase openerp.service.server: Worker (15946) Exception occured, exiting...
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/service/server.py", line 766, in run
    self.process_work()
  File "/opt/odoo/odoo/openerp/service/server.py", line 799, in process_work
    self.process_request(client, addr)
  File "/opt/odoo/odoo/openerp/service/server.py", line 790, in process_request
    self.server.process_request(client, addr)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
timeout: timed out
2018-10-23 20:55:24,641 15952 INFO ? openerp.service.server: Worker WorkerHTTP (15952) alive

```

**Comment by pedrobaeza** [comment]
Hi, 8.0 is no longer supported.

The currently supported versions are 10.0, 11.0 and 12.0.
