### ISSUE TITLE
Can't open details of account movements in general ledger report

### ISSUE THREAD

**Issue by tomeyro** [odoo/odoo#28302]
**Impacted versions**: 12.0+e

**Steps to reproduce**:

Go the accounting module and open general ledger report in a database with current year earnings,
and try to expand the line for the current earnings account:

![image](https://user-images.githubusercontent.com/8657959/47754136-89668000-dc5f-11e8-85ef-59e1ccf5240e.png)

**Current behavior**:

The following error is raised:

![image](https://user-images.githubusercontent.com/8657959/47754080-591ee180-dc5f-11e8-94ed-fbec38f24f83.png)

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/account_reports/models/account_report.py", line 649, in get_html
    lines = self._get_lines(options, line_id=line_id)
  File "/home/odoo/src/enterprise/account_reports/models/account_general_ledger.py", line 321, in _get_lines
    remaining_lines = grouped_accounts[account]['total_lines'] - offset - len(amls)
KeyError: 'total_lines'
```

**Expected behavior**:

The report and the details of the account are opened correctly.

**Comment by tomeyro** [comment]
opw-1904935

**Comment by Yenthe666** [comment]
Hi @tomeyro,

I believe this issue has been fixed in the meanwhile, a fix should have been done in the last 48 hours.
Can you reproduce it on the latest 12.0 (on a runbot)?

Regards,
Yenthe

**Comment by tomeyro** [comment]
Hi @Yenthe666 

It seems to be correct now.

Thanks to: [9fb7c1](https://github.com/odoo/enterprise/commit/9fb7c1dde06ef6596ae8ffbb9753a40d70500871) :+1:
