### ISSUE TITLE
Cant reinstall POS module

### ISSUE THREAD

**Issue by alexlarraga1** [odoo/odoo#28337]
Impacted versions: 12.0

Steps to reproduce: Uninstall POS module and reinstaling

Current behavior:
Cant reinstall POS module
Expected behavior:  Success in reinstall POS module

Video/Screenshot link (optional):
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/opt/odoo12/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fde99d38c80>, 'product.product_category_1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_model.py", line 1366, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/odoo12/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_model.py", line 1355, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: product.product_category_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_model.py", line 1366, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/odoo12/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_model.py", line 1355, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: product.product_category_1" while parsing /opt/odoo12/odoo/addons/point_of_sale/data/point_of_sale_data.xml:28, near
<record id="product_category_pos" model="product.category">
            <field name="parent_id" ref="product.product_category_1"/>
            <field name="name">PoS</field>
        </record>
```

**Comment by pedrobaeza** [comment]
This seems to be a demo data mess. Does it happen on a fresh database?

**Comment by Yenthe666** [comment]
Seems to work fine on the latest 12.0 though.

**Comment by mart-e** [comment]
This is because you have most likely removed the product category "All".
Update the product module to get it back.

It is a classical problem, there is some data that are considered as "mandatory" for Odoo such as the main product category.
We plan to add a flag on these data to make them "undeletable" but that wasn't done yet.

**Comment by avnkhanh** [comment]
it same in Odoo 13 :
ValueError: External ID not found in the system: product.product_category_1

how to resolve this without deleting product catalogs?

**Comment by moniltrivedi53** [comment]
how to update product modual
