### ISSUE TITLE
base: SQL constraints are crashing instead of showing the error

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#28381]
### Impacted versions:
11.0, 12.0

### Steps to reproduce:
Try to violate any of the existing SQL constraints

### Current behavior:
It crashes the interface with the following error:

```python
psycopg2.IntegrityError: duplicate key value violates unique constraint "account_invoice_out_invoice_unique"
DETAIL:  Key (type, reference)=(out_invoice, B0200004688) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 141, in wrapper
    raise ValidationError(inst[0])
TypeError: 'IntegrityError' object does not support indexing
```

### Expected behavior:
Show the resulting error to the user

**Comment by pedrobaeza** [comment]
I don't get that, but the message you put on the SQL constraint. Please try to reproduce the steps on runbot and put screenshots/video.

**Comment by gustavovalverde** [comment]
Just as a heads-up if I change `raise ValidationError(inst[0])` to `raise ValidationError(inst)` the next message is correctly shown to the user:

> psycopg2.IntegrityError: duplicate key value violates unique constraint "account_invoice_out_invoice_unique"
> DETAIL:  Key (type, reference)=(out_invoice, B0200004688) already exists.

Otherwise it crashes like above

**Comment by gustavovalverde** [comment]
Perfect, thank you @sswapnesh
