### ISSUE TITLE
Error updating WEBSITE module. PLEASE HELP

### ISSUE THREAD

**Issue by mojowebs** [odoo/odoo#2841]
I have had this error for two days now. PLEASE HELP. 

Also reported here: https://github.com/odoo/odoo/issues/2813  and https://github.com/odoo/odoo/issues/2798

I run this -> /opt/odoo/odoo-server/openerp-server -u website -d app

I get this:
2014-10-01 18:01:38,617 1533 INFO ? openerp: OpenERP version 8.0
2014-10-01 18:01:38,617 1533 INFO ? openerp: addons paths: ['/opt/odoo/.local/share/Odoo/addons/8.0', u'/opt/odoo/odoo-server/openerp/addons', u'/opt/odoo/odoo-server/addons']
2014-10-01 18:01:38,617 1533 INFO ? openerp: database hostname: localhost
2014-10-01 18:01:38,617 1533 INFO ? openerp: database port: 5432
2014-10-01 18:01:38,618 1533 INFO ? openerp: database user: odoo
2014-10-01 18:01:38,737 1533 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2014-10-01 18:01:38,750 1533 INFO app openerp.modules.loading: loading 1 modules...
2014-10-01 18:01:38,936 1533 INFO app openerp.modules.loading: 1 modules loaded in 0.18s, 0 queries
2014-10-01 18:01:39,091 1533 INFO app openerp.modules.loading: loading 62 modules...
2014-10-01 18:01:39,221 1533 INFO app openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2014-10-01 18:01:40,102 1533 INFO app openerp.modules.module: module website: creating or updating database tables
2014-10-01 18:01:40,890 1533 INFO app openerp.modules.loading: loading website/data/data.xml
2014-10-01 18:01:40,946 1533 INFO app openerp.modules.loading: loading website/security/ir.model.access.csv
2014-10-01 18:01:41,044 1533 INFO app openerp.modules.loading: loading website/security/ir_ui_view.xml
2014-10-01 18:01:41,081 1533 INFO app openerp.modules.loading: loading website/views/website_templates.xml
2014-10-01 18:01:41,422 1533 ERROR app openerp.addons.base.ir.ir_ui_view: Element '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' cannot be located in parent view

Error context:
View `Editor`
[view_id: 263, xml_id: website.editor_head, model: n/a, parent_id: 260]
2014-10-01 18:01:41,424 1533 CRITICAL app openerp.service.server: Failed to initialize database `app`.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 827, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1024, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 282, in write
    context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3693, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3855, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1306, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//t[@t-call-assets="website.assets_frontend"][@t-js]">' cannot be located in parent view

Error context:
View `Editor`
[view_id: 263, xml_id: website.editor_head, model: n/a, parent_id: 260]" while parsing None:182, near
<data inherit_id="website.layout" name="Editor">
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-js]" position="after">
        <t t-call-assets="website.assets_editor" t-js="false"/>
    </xpath>
    <xpath expr="//t[@t-call-assets=&quot;website.assets_frontend&quot;][@t-css]" position="after">
        <t t-call-assets="website.assets_editor" t-css="false"/>
    </xpath>
</data>

**Comment by Yenthe666** [comment]
Hi @mojowebs,

Please update your codebase again and this problem will be fixed. You've probably had an update that contained one fault that wasn't fixed at the point that you've updated.
A new update will fix all your issues.

Regards,
Yenthe
