### ISSUE TITLE
Validation Error when extending Filter

### ISSUE THREAD

**Issue by bileser** [odoo/odoo#28436]
Impacted versions: 12

Steps to reproduce: write a module with following code

```
        <record id="view_res_partner_filter_extension" model="ir.ui.view">
            <field name="name">view_res_partner_filter_extension</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_res_partner_filter"/>
            <field name="arch" type="xml">
                <field name="name" position="after">
                    <filter help="Meine Kunden" domain="[('zip','=', 555)]"/>
                </field>
            </field>
        </record>

```

Current behavior:

```
2018-11-06 13:21:49,132 62687 ERROR odoo12 odoo.tools.view_validation: <string>:0:0:ERROR:RELAXNGV:RELAXNG_ERR_ATTRVALID: Element filter failed to validate attributes 
2018-11-06 13:21:49,132 62687 ERROR odoo12 odoo.tools.view_validation: <string>:3:0:ERROR:RELAXNGV:RELAXNG_ERR_NOELEM: Expecting an element field, got nothing 
2018-11-06 13:21:49,132 62687 ERROR odoo12 odoo.tools.view_validation: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element search has extra content: field 
2018-11-06 13:21:49,132 62687 ERROR odoo12 odoo.tools.view_validation: Invalid XML:  Get RNG validator and validate RNG file. 
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverschneider/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/oliverschneider/odoo12/odoo/modules/loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/Users/oliverschneider/odoo12/odoo/modules/loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/Users/oliverschneider/odoo12/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/Users/oliverschneider/odoo12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/Users/oliverschneider/odoo12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/Users/oliverschneider/odoo12/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/Users/oliverschneider/odoo12/odoo/models.py", line 3803, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/Users/oliverschneider/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/Users/oliverschneider/odoo12/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/Users/oliverschneider/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/Users/oliverschneider/odoo12/odoo/models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "/Users/oliverschneider/odoo12/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/Users/oliverschneider/odoo12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/Users/oliverschneider/odoo12/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/Users/oliverschneider/odoo12/odoo/models.py", line 3257, in write
    self._write(store_vals)
  File "/Users/oliverschneider/odoo12/odoo/models.py", line 3401, in _write
    self._validate_fields(vals)
  File "/Users/oliverschneider/odoo12/odoo/models.py", line 1100, in _validate_fields
    check(self)
  File "/Users/oliverschneider/odoo12/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view res.partner.select.course.extension definition in cdc_base/views/partner.xml
None" while parsing /Users/oliverschneider/repository/11.0/cdc_base/views/partner.xml:122, near
<record id="cdc_view_res_partner_filter" model="ir.ui.view">
            <field name="name">res.partner.select.course.extension</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_res_partner_filter"/>
            <field name="arch" type="xml">
                <field name="name" position="after">
                    <filter help="Meine Kunden" domain="[('zip','=', 555)]"/>
                </field>
            </field>
        </record>
```

Expected behavior: should just extend the filter, it worked in odoo 11

Video/Screenshot link (optional):

**Comment by celm1990** [comment]
Hi,

All filters must have a **name**, your code must be:
`<filter name="my_filter_name" help="Meine Kunden" domain="[('zip','=', 555)]"/>`

**Comment by bileser** [comment]
Thanks celm1990, this seams to solve the problem. Odoo logs are soo featureless ... why on earth can't they include into the logs that there ist the **name** attribute missing? Or did I miss something?

**Comment by techspawn** [comment]
> Hi,
> 
> All filters must have a **name**, your code must be:
> `<filter name="my_filter_name" help="Meine Kunden" domain="[('zip','=', 555)]"/>`

this is right

**Comment by gabbyRamos** [comment]
> Hi,
> 
> All filters must have a **name**, your code must be:
> `<filter name="my_filter_name" help="Meine Kunden" domain="[('zip','=', 555)]"/>`

Tks, you save me day :)
