### ISSUE TITLE
install "Project" app Error: Failed to render template (vietnamese)

### ISSUE THREAD

**Issue by duybq86** [odoo/odoo#28490]
Traceback (most recent call last):
  File "/odoo/server/addons/mail/models/mail_template.py", line 371, in render_template
    render_result = template.render(variables)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/server/odoo/addons/base/ir/ir_model.py", line 1488, in _update
    record = record.create(values)
  File "/odoo/server/addons/project/models/project.py", line 658, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 259, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 509, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 1913, in message_post
    new_message = MailMessage.create(values)
  File "/odoo/server/addons/mail/models/mail_message.py", line 788, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/odoo/server/addons/mail/models/mail_message.py", line 873, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/odoo/server/addons/mail/models/res_partner.py", line 188, in _notify
    fol_values = template_fol.generate_email(message.id, fields=['body_html', 'subject'])
  File "/odoo/server/addons/mail/models/mail_template.py", line 476, in generate_email
    post_process=(field == 'body_html'))
  File "/odoo/server/addons/mail/models/mail_template.py", line 374, in render_template
    raise UserError(_("Failed to render template %r using values %r")% (template, variables))
odoo.exceptions.UserError: ('Thất bại khi render mẫu <Template memory:7f2d9d0c8f60> sử dụng giá trị {\'format_date\': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c730>, \'format_tz\': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c488>, \'format_amount\': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c0d0>, \'user\': res.users(1,), \'ctx\': {\'install_mode_data\': {\'xml_file\': \'/odoo/server/addons/project/data/project_demo.xml\', \'xml_id\': \'project_task_1\', \'model\': \'project.task\', \'module\': \'project\'}, \'install_mode\': True, \'mail_create_nolog\': True, \'default_project_id\': 38, \'lang\': \'vi_VN\', \'signature\': \'<span data-o-mail-quote="1">-- <br data-o-mail-quote="1">\\nAdministrator</span>\', \'website_url\': \'http://www.example.com\', \'company\': res.company(1,), \'company_name\': \'YourCompany\', \'model_name\': \'Task\', \'record\': project.task(98,), \'record_name\': \'Prepare Requirements Document\', \'tracking\': [(\'Task Title\', False, \'Prepare Requirements Document\'), (\'Stage\', \'\', \'To Do\'), (\'Kanban State\', False, \'In Progress\'), (\'Project\', \'\', \'Website for Sales & WMS\'), (\'Assigned to\', \'\', \'Demo User\'), (\'Project Manager\', \'\', \'Demo User\')], \'is_discussion\': False, \'subtype\': mail.message.subtype(102,), \'actions\': [], \'has_button_access\': True, \'button_access\': {\'url\': \'/mail/view?message_id=1040\', \'title\': \'Xem Task\'}, \'has_button_follow\': False, \'button_follow\': {\'url\': \'/mail/follow?model=project.task&res_id=98&token=1e13be2f3299b99fd6c95669c7ce0a91fba7c591\', \'title\': \'Theo dõi\'}, \'has_button_unfollow\': True, \'button_unfollow\': {\'url\': \'/mail/unfollow?model=project.task&res_id=98&token=a3955889e4808a869c8d889d94c08ff224fb7f93\', \'title\': \'Ngừng theo dõi\'}, \'followers\': res.partner(6,), \'not_followers\': res.partner(), \'safe\': True}, \'object\': mail.message(1040,)}', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/odoo/server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/server/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/server/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/server/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/server/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/server/odoo/modules/loading.py", line 184, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/odoo/server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/server/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/server/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/server/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/odoo/server/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/odoo/server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/server/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/server/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/server/odoo/addons/base/ir/ir_model.py", line 1488, in _update
    record = record.create(values)
  File "/odoo/server/addons/project/models/project.py", line 658, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 259, in create
    track_thread.message_track(tracked_fields, initial_values)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 509, in message_track
    record.message_post(subtype=subtype_xmlid, tracking_value_ids=tracking_value_ids)
  File "/odoo/server/addons/mail/models/mail_thread.py", line 1913, in message_post
    new_message = MailMessage.create(values)
  File "/odoo/server/addons/mail/models/mail_message.py", line 788, in create
    user_signature=self.env.context.get('mail_notify_user_signature', True))
  File "/odoo/server/addons/mail/models/mail_message.py", line 873, in _notify
    ])._notify(self, force_send=force_send, send_after_commit=send_after_commit, user_signature=user_signature)
  File "/odoo/server/addons/mail/models/res_partner.py", line 188, in _notify
    fol_values = template_fol.generate_email(message.id, fields=['body_html', 'subject'])
  File "/odoo/server/addons/mail/models/mail_template.py", line 476, in generate_email
    post_process=(field == 'body_html'))
  File "/odoo/server/addons/mail/models/mail_template.py", line 374, in render_template
    raise UserError(_("Failed to render template %r using values %r")% (template, variables))
odoo.tools.convert.ParseError: "Thất bại khi render mẫu <Template memory:7f2d9d0c8f60> sử dụng giá trị {'format_date': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c730>, 'format_tz': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c488>, 'format_amount': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f2d6e85c0d0>, 'user': res.users(1,), 'ctx': {'install_mode_data': {'xml_file': '/odoo/server/addons/project/data/project_demo.xml', 'xml_id': 'project_task_1', 'model': 'project.task', 'module': 'project'}, 'install_mode': True, 'mail_create_nolog': True, 'default_project_id': 38, 'lang': 'vi_VN', 'signature': '<span data-o-mail-quote="1">-- <br data-o-mail-quote="1">\nAdministrator</span>', 'website_url': 'http://www.example.com', 'company': res.company(1,), 'company_name': 'YourCompany', 'model_name': 'Task', 'record': project.task(98,), 'record_name': 'Prepare Requirements Document', 'tracking': [('Task Title', False, 'Prepare Requirements Document'), ('Stage', '', 'To Do'), ('Kanban State', False, 'In Progress'), ('Project', '', 'Website for Sales & WMS'), ('Assigned to', '', 'Demo User'), ('Project Manager', '', 'Demo User')], 'is_discussion': False, 'subtype': mail.message.subtype(102,), 'actions': [], 'has_button_access': True, 'button_access': {'url': '/mail/view?message_id=1040', 'title': 'Xem Task'}, 'has_button_follow': False, 'button_follow': {'url': '/mail/follow?model=project.task&res_id=98&token=1e13be2f3299b99fd6c95669c7ce0a91fba7c591', 'title': 'Theo dõi'}, 'has_button_unfollow': True, 'button_unfollow': {'url': '/mail/unfollow?model=project.task&res_id=98&token=a3955889e4808a869c8d889d94c08ff224fb7f93', 'title': 'Ngừng theo dõi'}, 'followers': res.partner(6,), 'not_followers': res.partner(), 'safe': True}, 'object': mail.message(1040,)}
" while parsing /odoo/server/addons/project/data/project_demo.xml:123, near
<record id="project_task_1" model="project.task">
            <field name="planned_hours" eval="40.0"/>
            <field name="remaining_hours" eval="40.0"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_1"/>
            <field name="name">Prepare Requirements Document</field>
            <field name="stage_id" ref="project_stage_0"/>
            <field name="color">3</field>
        </record>

**Comment by pedrobaeza** [comment]
You should fix the template translation in Transifex then. Check https://github.com/odoo/odoo/wiki/Translations.

Closing as no Odoo issue, but bad translation.
