### ISSUE TITLE
psycopg2.InterfaceError: connection already closed - - -

### ISSUE THREAD

**Issue by jmchza** [odoo/odoo#28821]
Impacted versions: V12 running locally on a Mac latest version, recommended Postgres version by the guide. 

Steps to reproduce: After few navigations and modules activation, I lose access to any other application other than the website.
In one encounter I have the error after installing the website module.
and every time I end-up starting from zero by installing it on a new DB. (Installation done from gitHub repo so latest code as of yesterday 19/11/2018)

Current behavior:
```
2018-11-20 09:19:57,691 66619 ERROR Odoo-dev2 odoo.sql_db: bad query: b'DELETE FROM ir_attachment WHERE id IN (385)'
ERROR: cursor already closed 
2018-11-20 09:19:57,695 66619 INFO Odoo-dev2 werkzeug: 127.0.0.1 - - [20/Nov/2018 09:19:57] "GET /web HTTP/1.1" 500 - 331 0.293 0.527
2018-11-20 09:19:57,710 66619 ERROR Odoo-dev2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Workspaces/Storyx-WKS/odoo/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/Workspaces/Storyx-WKS/odoo/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/Workspaces/Storyx-WKS/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/Workspaces/Storyx-WKS/odoo/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/Workspaces/Storyx-WKS/odoo/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/Workspaces/Storyx-WKS/odoo/odoo/http.py", line 1489, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/Workspaces/Storyx-WKS/odoo/odoo/http.py", line 289, in __exit__
    self._cr.close()
  File "/Workspaces/Storyx-WKS/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Workspaces/Storyx-WKS/odoo/odoo/sql_db.py", line 285, in close
    return self._close(False)
  File "/Workspaces/Storyx-WKS/odoo/odoo/sql_db.py", line 315, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed - - -

```
Expected behavior:
keep accessing the Setting, CRm calendar, etc modules instead of having connection closed unexpectedly. (Se sniplet pasted above please).

And I get always a : 
with a URL: http://localhost:8069/web#menu_id=4&action=
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Video/Screenshot link (optional):
Any help to fix this will be super appreciated.
Cheers,

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
