### ISSUE TITLE
bug facturation : invoice

### ISSUE THREAD

**Issue by NajlaeB** [odoo/odoo#28974]
Impacted versions: verson 11

Steps to reproduce: update my own modul

Current behavior: show this error on clic on invoice menu : 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f05a3c05eb8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4239, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2601, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "<decorator-gen-108>", line 2, in _kanban_dashboard
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 369, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal_dashboard.py", line 16, in _kanban_dashboard
    self.kanban_dashboard = json.dumps(self.get_journal_dashboard_datas())
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal_dashboard.py", line 200, in get_journal_dashboard_datas
    (number_waiting, sum_waiting) = self._count_results_and_sum_amounts(query_results_to_pay, currency)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_journal_dashboard.py", line 252, in _count_results_and_sum_amounts
    rslt_sum += type_factor * cur.compute(result.get('amount_total'), target_currency)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 202, in compute
    return to_currency.round(to_amount) if round else to_amount
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_currency.py", line 135, in round
    return tools.float_round(amount, precision_rounding=self.rounding)
  File "/usr/lib/python3/dist-packages/odoo/tools/float_utils.py", line 73, in float_round
    normalized_value = value / rounding_factor # normalize
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this issue as there has been no further feedback/steps since november.

Regards,
Yenthe
