### ISSUE TITLE
Unported base module prevents porting other modules, line 432, in ir_values.py

### ISSUE THREAD

**Issue by sraps** [odoo/odoo#2899]
Fact that even base module is not ported to new API, renders new API overloading practically impossible. 
Following test module generates error in almost every other model displayed in UI. I specially removed any unnecessary constructions from the module, to clearly display case when new API conflicts with all the rest facilities in the system, which are not ported to new API.

To reproduce install the module. At the end of installation modules view gets reloaded and raises error.
http://ge.tt/7v80DZ02/v/0?c

In the module there is read function for ir.actions.report.xml model overloaded, which in turn is the wrapper that just loads the same method from ancestor class. It simulates ordinary practice. This read method from ir.actions.report.xml is being used by unported core system functionality, which expects dict instead of the list...

The solution would be not porting the method, but this in turn makes this method incompatible with other subsystems, raising various recursion errors, etc. So there is no option of not porting this to new API.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/base/module/module.py", line 149, in fields_view_get
    res = super(module, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=False)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/models.py", line 1597, in fields_view_get
    resprint = ir_values_obj.get(cr, uid, 'action', 'client_print_multi', [(self._name, False)], False, context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/calendar/calendar.py", line 619, in get
    meta, context, res_id_req, without_user, key2_req)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/base/ir/ir_values.py", line 501, in get
    return self._map_legacy_model_list(models, do_get, merge_results=True)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/base/ir/ir_values.py", line 458, in _map_legacy_model_list
    result = map_fn(model, res_id)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/base/ir/ir_values.py", line 500, in do_get
    return self.get_actions(cr, uid, action_slot=key2, model=model, res_id=res_id, context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0rc1-py2.7.egg/openerp/addons/base/ir/ir_values.py", line 432, in get_actions
    groups = action_def.get('groups_id')
AttributeError: 'list' object has no attribute 'get'
```

**Comment by Yenthe666** [comment]
Hi @sraps,

Odoo 10 should be dropping the support from the old API and at the moment Odoo developers are migrating all the code to the new API (against the master version).
All these inconsistency problems will be fixed in the next version. Since the rules for our versions are quite strict to guarantee correct behaviour of live versions this won't be fixed any earlier.
Closing this since this will be automatically fixed in V10 and cannot be undone anymore at this point.

Regards,
Yenthe
