### ISSUE TITLE
odoo 10.0 docker Installation

### ISSUE THREAD

**Issue by aelmizeb** [odoo/odoo#29173]
Impacted versions:
10.0
Steps to reproduce:
Install odoo on a docker image
Current behavior:
Get Internal Error

2018-11-28 15:25:14,495 1 ERROR spqrdb werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 247, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1499, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 775, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 834, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 330, in checked_call
    result.flatten()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1277, in flatten
    self.response.append(self.render())
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1270, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 249, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 318, in _compiled_fn
    raise e
QWebException: <lambda>() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 316, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_web_login_layout_11
  File "<template>", line 3, in body_call_content_10
  File "<template>", line 5, in set_8
  File "<string>", line 2, in _get_asset
  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 194, in _get_asset
    return asset.to_html(css=css, js=js, debug=debug, async=async, url_for=(values or {}).get('url_for', lambda url: url))
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 121, in to_html
    css_attachments = self.css()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 271, in css
    self.save_attachment("css", ' '.join(page), inc=idx)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 218, in save_attachment
    attachment = ira.sudo().create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 459, in create
    return super(IrAttachment, self).create(values)
  File "/mnt/spqr-addons/spqr/models/component_event_base.py", line 80, in create
    record = super(Base, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3854, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1046, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 214, in _inverse_datas
    super(IrAttachment, attach.sudo()).write(vals)
  File "/mnt/spqr-addons/spqr/models/component_event_base.py", line 89, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/mnt/spqr-addons/spqr/models/component_event_base.py", line 76, in _event
    return collecter.collect_events(name)
  File "/mnt/spqr-addons/spqr/models/component_event_event.py", line 154, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/usr/local/lib/python2.7/dist-packages/cachetools/__init__.py", line 82, in wrapper
    k = key(*args, **kwargs)
TypeError: <lambda>() takes exactly 2 arguments (1 given)

Error to render compiling AST
TypeError: <lambda>() takes exactly 2 arguments (1 given)
Template: web.login_layout
Path: /templates/t/t/t[2]/t[1]
Node: <t t-call-assets="web.assets_common" t-js="false"/>
 
Expected behavior:
The docker worked fine in  the past

Video/Screenshot link (optional):
![docker error](https://user-images.githubusercontent.com/19288561/49279588-32371380-f488-11e8-985b-5030746f2a5a.png)

**Comment by d-fence** [comment]
Hello, I'm not able to reproduce.
Can you give more informations ?
How did you start the Postgres DB docker image ?
How did you start the Odoo:10.0 docker image ?

**Comment by aelmizeb** [comment]
Hello,

Yes, you are right it not coming from the odoo, but a third party module (cachetools upgrad to 3.0.0).

You can close the ticket.

Regards,

**Comment by d-fence** [comment]
Ok ,thanks for the feedback.
