### ISSUE TITLE
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src\lxml\lxml.etree.c:194922)      AssertionError: Element odoo has extra content: data, line 3

### ISSUE THREAD

**Issue by zlycong** [odoo/odoo#29332]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by ChayaGavali** [comment]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "D:\pycwrk\odoo-16.0\odoo\service\model.py", line 134, in retrying
    result = func()
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "d:\pycwrk\odoo-16.0\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "D:\pycwrk\odoo-16.0\odoo\http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "d:\pycwrk\odoo-16.0\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_upgrade
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 678, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "D:\pycwrk\odoo-16.0\odoo\addons\base\models\ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "D:\pycwrk\odoo-16.0\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\pycwrk\odoo-16.0\odoo\modules\registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 373, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "D:\pycwrk\odoo-16.0\odoo\modules\loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "D:\pycwrk\odoo-16.0\odoo\tools\convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "D:\pycwrk\odoo-16.0\odoo\tools\convert.py", line 812, in convert_xml_import
    relaxng.assert_(doc)
  File "src\lxml\etree.pyx", line 3633, in lxml.etree._Validator.assert_
AssertionError: Element odoo has extra content: record, line 3

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:967:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8082/web/assets/395-4dd4510/web.assets_backend.min.js:974:13)

<?xml version="1.0" encoding="UTF-8"?>
<odoo>



































</odoo>

plz help me

**Comment by ChayaGavali** [comment]
my xml code is

<?xml version="1.0" encoding="UTF-8"?>
<odoo>



































</odoo>

**Comment by ChayaGavali** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<odoo>



































</odoo>
