### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by hanyelbanna** [odoo/odoo#29368]
Impacted versions:
12 and master
Steps to reproduce:
installing website module
Current behavior:
ValueError: signal only works in main thread error
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you specify better the problem?

**Comment by hanyelbanna** [comment]
Operating system: Ubuntu 18.4 and Mac OS 10.14
Python: 3.6.7 and 3.7.1
Odoo: 12 and master

Steps:
1- run command: ./odoo-bin -d testdb1 --test-enable --addons-path="enterprise,addons,odoo/addons"

2- login to Odoo as admin and install website module.

3- get this error on terminal logs:

2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: ERROR 
2018-12-09 04:01:31,590 1297 INFO testdb1 odoo.addons.website.tests.test_ui: ====================================================================== 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: ERROR: test_admin_tour_rte_translator (odoo.addons.website.tests.test_ui.TestUiTranslate) 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: Traceback (most recent call last): 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `   File "/Users/odoo_erp/Desktop/odoo_folder/odoo/addons/website/tests/test_ui.py", line 9, in test_admin_tour_rte_translator 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `     self.phantom_js("/", "odoo.__DEBUG__.services['web_tour.tour'].run('rte_translator')", "odoo.__DEBUG__.services['web_tour.tour'].tours.rte_translator.ready", login='admin', timeout=120) 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `   File "/Users/odoo_erp/Desktop/odoo_folder/odoo/odoo/tests/common.py", line 904, in browser_js 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `     self.start_browser(self._logger) 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `   File "/Users/odoo_erp/Desktop/odoo_folder/odoo/odoo/tests/common.py", line 807, in start_browser 
2018-12-09 04:01:31,590 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `     cls.browser = ChromeBrowser(logger, cls.browser_size) 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `   File "/Users/odoo_erp/Desktop/odoo_folder/odoo/odoo/tests/common.py", line 472, in __init__ 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `     signal.signal(signal.SIGXCPU, self.signal_handler) 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 47, in signal 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: `     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler)) 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: ` ValueError: signal only works in main thread 
2018-12-09 04:01:31,591 1297 INFO testdb1 odoo.addons.website.tests.test_ui: Ran 1 test in 0.182s 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.addons.website.tests.test_ui: FAILED 
2018-12-09 04:01:31,591 1297 INFO testdb1 odoo.addons.website.tests.test_ui:  (errors=1) 
2018-12-09 04:01:31,591 1297 ERROR testdb1 odoo.modules.module: Module website: 0 failures, 1 errors

**Comment by pedrobaeza** [comment]
Well, that's a question about configuring properly v12 environment, using Chrome headerless for that. You can see in runbot (https://runbot.odoo.com) that everything is working properly.

Closing as deployment issue.

**Comment by fotisp** [comment]
Sorry to jump on this issue even though it is 2 years old. But @pedrobaeza, if it is a question about configuring it property then you chould chime in on that please?

I have tried a re-read everything, and this is still occuring in 13.0 if workers > 0 i.e. multiprocess.

Furthermore this is the only hit on Google, so I am assuming I am probably all alone on this error.

**Comment by pedrobaeza** [comment]
Well, that's the problem: you should perform tests always with workers=0

**Comment by fotisp** [comment]
Yes I understand that, but for example I am getting the same problem on 13.0 on 2 production instances, and that mean that I can't run on multiprocess.

Yet, I can't find any indication as to what may be causing this. 

Regardless of tests.
