### ISSUE TITLE
changing the sales team `oe_gauge` graph value lead to error

### ISSUE THREAD

**Issue by jam-odoo** [odoo/odoo#2944]
Chaning the sales team graph `oe_gauge` values to more then 10 digits trigger trackback (pasted below).
I understand the technical limitation but instead of showing trace to end user their should be right error handling and warning message about this: 

```
OpenERP Server Error
Traceback (most recent call last):
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/addons/sale/sales_team.py", line 68, in action_forecast
    return self.write(cr, uid, [id], {'invoiced_forecast': round(float(value))}, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/addons/mail/mail_thread.py", line 427, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/models.py", line 3688, in write
    self._write(old_vals)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/models.py", line 3798, in _write
    'where id IN %s', upd1 + [sub_ids])
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/20557-8-0-884397/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range
```

bests

**Comment by NothingCtrl** [comment]
Yup, field `invoiced_target` is fields.Interger() so maximum is: 2147483647
In my country (VN), this number not enought to set Team target.

Reference: #8437

**Comment by Yenthe666** [comment]
Hmm this one is still open. @mart-e couldn't we just change this by changing the field to float in master?

**Comment by mart-e** [comment]
@Yenthe666 actually the field `invoiced_forecast` no longer exists in 9.0. We can not change a field type as it would have impact on the database (but it is true, it should have been a float).
Closing as, not going to patch the 8.0 for this for stability reason.

**Comment by NothingCtrl** [comment]
Hello,

I'm just test on runbot v9c, v10c, menu **Sales >> Dashboard**, when setup a team target lager than **2147483647** the error occurred.

For version 9:
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/addons/sale/sales_team.py", line 66, in update_invoiced_target
    return self.write(cr, uid, [id], {'invoiced_target': round(float(value or 0))}, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/addons/crm/sales_team.py", line 108, in write
    res = super(crm_team, self).write(cr, uid, ids, vals, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/addons/mail/models/mail_thread.py", line 281, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/models.py", line 3854, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/models.py", line 3972, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254720-9-0-06019d/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range
```

For version 10:
```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/addons/sale/models/sales_team.py", line 56, in update_invoiced_target
    return self.write({'invoiced_target': round(float(value or 0))})
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/addons/crm/models/crm_team.py", line 44, in write
    result = super(Team, self).write(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/addons/mail/models/mail_thread.py", line 274, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/models.py", line 3560, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/models.py", line 3646, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/254725-10-0-98661b/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range
```
