### ISSUE TITLE
[11.0][12.0] JS Error on  pop up screen to add a link to a text in chatter 

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoo/odoo#29445]
Impacted versions: 11.0, 12.0

Steps to reproduce:

Using Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Go to lead and create a note. Press the button to pop up the will window for text editing.
![image](https://user-images.githubusercontent.com/7683926/49833435-ba55cc80-fd56-11e8-8521-2f5accf2f64d.png)

Then add some text and press the button to add an hyperlink:

![image](https://user-images.githubusercontent.com/7683926/49833461-cc376f80-fd56-11e8-81aa-c58ef594764c.png)

Inmediately cancel the pop up window:

![image](https://user-images.githubusercontent.com/7683926/49833490-e40ef380-fd56-11e8-8de8-97030e6408c7.png)

Current behavior:
You will get this error:

![image](https://user-images.githubusercontent.com/7683926/49833509-f1c47900-fd56-11e8-8448-f25b7af6ecce.png)

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 9 is larger than the node's length (0).
http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:133
Traceback:
Error: Failed to execute 'setEnd' on 'Range': The offset 9 is larger than the node's length (0).
    at nativeRange (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:133:515)
    at WrappedRange.select (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:133:906)
    at Editor.restoreRange (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:217:119)
    at EventHandler.invoke (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:379:1506)
    at Object.<anonymous> (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1215-bc68a22/web_editor.summernote.js:298:1268)
    at fire (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1213-b8d0d86/web.assets_common.js:796:299)
    at Object.fireWith [as rejectWith] (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1213-b8d0d86/web.assets_common.js:801:198)
    at Object.<anonymous> (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1213-b8d0d86/web.assets_common.js:802:874)
    at fire (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1213-b8d0d86/web.assets_common.js:796:299)
    at Object.fireWith [as rejectWith] (http://413307-12-0-34d356.runbot14.odoo.com/web/content/1213-b8d0d86/web.assets_common.js:801:

Expected behavior:

Video/Screenshot link (optional):

**Comment by jbeficent** [comment]
@ged-odoo maybe you've come across this issue?

**Comment by C3POdoo** [comment]
Dear @JordiBForgeFlow,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
