### ISSUE TITLE
Dates on Sales Order: Exception while importing `sale.order.line`

### ISSUE THREAD

**Issue by davispuh** [odoo/odoo#29463]
Impacted versions: `11.0` (didn't checked other versions)

Steps to reproduce:

1. Import (using RPC API) `stock.picking` with empty `date`
2. Try to import `sale.order.line`

Current behavior:

* Importing `sale.order.line` raises exception

```
2018-12-12 09:44:03,581 15678 ERROR odoo odoo.models: Error while loading record
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fe25d21a780>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/models.py", line 844, in load
    xml_id=xid, noupdate=noupdate, res_id=id))
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1488, in _update
    record = record.create(values)
  File "/home/odoo/odoo/addons/sale_stock/models/sale_order.py", line 97, in create
    line._action_launch_procurement_rule()
  File "/home/odoo/odoo/addons/procurement_jit/sale.py", line 12, in _action_launch_procurement_rule
    res = super(SaleOrderLine, self)._action_launch_procurement_rule()
  File "/home/odoo/odoo/addons/sale_stock/models/sale_order.py", line 280, in _action_launch_procurement_rule
    self.env['procurement.group'].run(line.product_id, product_qty, procurement_uom, line.order_id.partner_shipping_id.property_stock_customer, line.name, line.order_id.name, values)
  File "/home/odoo/odoo/addons/stock/models/procurement.py", line 186, in run
    getattr(rule, '_run_%s' % rule.action)(product_id, product_qty, product_uom, location_id, name, origin, values)
  File "/home/odoo/odoo/addons/stock/models/procurement.py", line 81, in _run_move
    move._action_confirm()
  File "/home/odoo/odoo/addons/stock/models/stock_move.py", line 771, in _action_confirm
    moves._assign_picking()
  File "/home/odoo/odoo/addons/stock/models/stock_move.py", line 707, in _assign_picking
    move.write({'picking_id': picking.id})
  File "/home/odoo/odoo/addons/sale_stock/models/stock.py", line 37, in write
    res = super(StockMove, self).write(vals)
  File "/home/odoo/odoo/addons/stock/models/stock_move.py", line 444, in write
    res = super(StockMove, self).write(vals)
  File "/home/odoo/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/home/odoo/odoo/odoo/models.py", line 3318, in _write
    self.recompute()
  File "/home/odoo/odoo/odoo/models.py", line 4905, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/odoo/odoo/models.py", line 4905, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/odoo/odoo/models.py", line 4759, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/home/odoo/odoo/odoo/fields.py", line 1028, in determine_value
    self.compute_value(recs)
  File "/home/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/home/odoo/odoo/odoo/fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/odoo/addons/sale_order_dates/models/sale_order.py", line 50, in _compute_picking_ids
    order.effective_date = fields.Datetime.to_string(min(dates_list))
TypeError: unorderable types: NoneType() < datetime.datetime()
```

Expected behavior:

* Either raise an exception that empty `date` for `stock.picking` isn't allowed or don't raise excpetion when importing `sale.order.line`
 
Context:

```python
    def _compute_picking_ids(self):
        super(SaleOrder, self)._compute_picking_ids()
        for order in self:
            dates_list = []
            for pick in order.picking_ids:
                dates_list.append(fields.Datetime.from_string(pick.date))
            if dates_list:
                order.effective_date = fields.Datetime.to_string(min(dates_list))
```
`pick.date` is `False`

**Comment by pedrobaeza** [comment]
Sorry, but this is a misuse of the external API. There are always some constraints you have to know and attend when calling low level methods like create, write and so on. In this case, sales business logic always expects a date, so you should provide it. The not null constraint on that field was removed by other reasons, and it's forbidden in UI, but external API isn't the priority for politing things, so no error is triggered on this initial wrong "import", but as you can see, you should provide it.

Closing by the reasons stated.

**Comment by davispuh** [comment]
> There are always some constraints you have to know and attend when calling low level methods like create, write and so on. 

I don't see any way how could I know about such constraints, especially as such `stock.picking`  imported fine without any issues.
I think it should provide errors for API too.

**Comment by pedrobaeza** [comment]
Well, this is a very specific case. Normally the required=True in the field constrains this. But as you know now the solution, no more problem, isn't it? :wink:

**Comment by davispuh** [comment]
> Well, this is a very specific case. Normally the required=True in the field constrains this. But as you know now the solution, no more problem, isn't it? wink

yeah, now I know it, but it doesn't stop others from encountering same issue unless they find this PR.
