### ISSUE TITLE
Full Accounting Features & Arabic language

### ISSUE THREAD

**Issue by alzubairy** [odoo/odoo#29523]
When using Arabic language and activate the "Show Full Accounting Features", Invoicing not work.
This problem exists in all versions of "Odoo 12 Community" from the date 02-12-2018 to Now.
>>>>>>>>>>>>
خطأ:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1370, in load_views
    for [v_id, v_type] in views
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1370, in <dictcomp>
    for [v_id, v_type] in views
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1449, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1412, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 780, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 729, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 707, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//span[@name="button_import_placeholder"]">' cannot be located in parent view

Error context:
View `account.journal.dashboard.kanban.inherit`
[view_id: 602, xml_id: account_bank_statement_import.journal_dashboard_view_inherit, model: account.journal, parent_id: 567]

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by alzubairy** [comment]
> مرحبًا ، شكرًا على الإبلاغ. هل يمكنك إعادة إنتاج المشكلة في البنية الأساسية لـ runbot ( http://runbot.odoo.com/runbot - admin / admin)؟

Don't allow "validate Closing & Post Entries" if the quantity is negative.
http://runbot.odoo.com/runbot/build/414447

**Comment by alzubairy** [comment]
> Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

Hi..
Thanks for your reply, please look at the link
http://runbot.odoo.com/runbot/build/414447

**Comment by alzubairy** [comment]
The problem occurs in Arabic only

**Comment by alzubairy** [comment]
[
![1](https://user-images.githubusercontent.com/45852699/49969623-0876f580-ff3a-11e8-9210-cd96c92eea03.png)
](url)

**Comment by alzubairy** [comment]
I have developed a detailed problem in the attached Images:
Image NO. 1: Activate all accounting features and then update the browser.
Image NO. 2: When you open "Invoicing" , the system works fine.
Image NO. 3: When you convert the system language to Arabic and then try to open the "Invoicing" message appears as in Image NO. 4

![1](https://user-images.githubusercontent.com/45852699/49969652-204e7980-ff3a-11e8-818d-c41583b2848d.png)
![2](https://user-images.githubusercontent.com/45852699/49969663-27758780-ff3a-11e8-858f-20bac2170c05.png)
![3](https://user-images.githubusercontent.com/45852699/49969674-2c3a3b80-ff3a-11e8-8e8d-ad818599fc06.png)
![4](https://user-images.githubusercontent.com/45852699/49969681-2e03ff00-ff3a-11e8-8764-1d45ee8e8410.png)

**Comment by pedrobaeza** [comment]
Thanks! This is more helpful indeed!

**Comment by william-andre** [comment]
I guess it has been solved. Please get back if you still have the issue.
![screenshot at 2019-01-10 14-37-24](https://user-images.githubusercontent.com/44770049/50971848-610fc300-14e5-11e9-8f4d-8e410db7f9c2.png)
