### ISSUE TITLE
[12.0] website_sale: multi-website pricelist, zero prices

### ISSUE THREAD

**Issue by offlove** [odoo/odoo#29553]
odo12

We have choice the function of "Manage multiple website", and also create several websites. While we be an editor to inside & view the function of "Manage multiple website", we can see the products price of all websites be showed correct. But if we quit and view our websites as visitor, the products price showed as “0”， and while you try to add to cart, the website have notice like " Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."... But if the visitor login, then the problems do not happen.

the detail Log as below:

`2018-12-15 09:17:36,937 24686 ERROR website odoo.addons.website_sale.models.website: Fail to find pricelist for partner "Public user for A1" (id 8) 
2018-12-15 09:17:36,967 24686 INFO website werkzeug: 127.0.0.1 - - [15/Dec/2018 09:17:36] "POST /product_configurator/show_optional_products_website HTTP/1.0" 200 - 37 0.026 0.026
2018-12-15 09:17:37,051 24687 ERROR website odoo.addons.website_sale.models.website: Fail to find pricelist for partner "Public user for A1" (id 8) 
2018-12-15 09:17:37,064 24687 ERROR website odoo.sql_db: bad query: b'INSERT INTO "sale_order" ("id", "create_uid", "create_date", "write_uid", "write_date", "cart_recovery_email_sent", "company_id", "date_order", "name", "note", "partner_id", "partner_invoice_id", "partner_shipping_id", "payment_term_id", "picking_policy", "pricelist_id", "require_payment", "require_signature", "sale_order_template_id", "state", "team_id", "user_id", "validity_date", "warehouse_id", "website_id") VALUES (nextval(\'sale_order_id_seq\'), 1, (now() at time zone \'UTC\'), 1, (now() at time zone \'UTC\'), false, 2, \'2018-12-15 09:17:37\', \'SO017\', \'\', 8, 8, 8, 1, \'direct\', NULL, false, false, NULL, \'draft\', NULL, NULL, NULL, 2, 4) RETURNING id'
ERROR: null value in column "pricelist_id" violates not-null constraint
DETAIL:  Failing row contains (17, SO017, null, null, null, draft, 2018-12-15 09:17:37, null, f, f, 2018-12-15 09:17:37.036813, null, null, 8, 8, 8, null, null, null, , null, null, null, null, 1, null, 2, null, null, null, null, null, 1, 1, 2018-12-15 09:17:37.036813, null, null, direct, 2, null, null, null, null, null, null, f, 4, null).
 
2018-12-15 09:17:37,066 24687 ERROR website odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/website_sale/controllers/main.py", line 398, in cart_update
    sale_order = request.website.sale_get_order(force_create=True)
  File "/opt/odoo12/odoo/addons/website_sale/models/website.py", line 230, in sale_get_order
    sale_order = self.env['sale.order'].sudo().create(so_data)
  File "<decorator-gen-358>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo12/odoo/addons/sale/models/sale.py", line 380, in create
    result = super(SaleOrder, self).create(vals)
  File "<decorator-gen-125>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo12/odoo/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3506, in create
    records = self._create(data_list)
  File "/opt/odoo12/odoo/odoo/models.py", line 3606, in _create
    cr.execute(query, params)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "pricelist_id" violates not-null constraint
DETAIL:  Failing row contains (17, SO017, null, null, null, draft, 2018-12-15 09:17:37, null, f, f, 2018-12-15 09:17:37.036813, null, null, 8, 8, 8, null, null, null, , null, null, null, null, 1, null, 2, null, null, null, null, null, 1, 1, 2018-12-15 09:17:37.036813, null, null, direct, 2, null, null, null, null, null, null, f, 4, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/opt/odoo12/odoo/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 139, in wrapper
    raise ValidationError(msg)
odoo.exceptions.ValidationError: ('The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: pricelist_id - pricelist.id]', None)
 
2018-12-15 09:17:37,066 24687 ERROR website odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE (("ir_ui_view"."active" = true)  AND  (("ir_ui_view"."key" = \'website.500\')  AND  (("ir_ui_view"."website_id" in (4)) OR "ir_ui_view"."website_id" IS NULL))) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-12-15 09:17:37,067 24687 ERROR website odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE (("ir_ui_view"."active" = true)  AND  (("ir_ui_view"."key" = \'website.http_error\')  AND  (("ir_ui_view"."website_id" in (4)) OR "ir_ui_view"."website_id" IS NULL))) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-12-15 09:17:37,071 24687 INFO website werkzeug: 127.0.0.1 - - [15/Dec/2018 09:17:37] "POST /shop/cart/update HTTP/1.0" 500 - 30 0.018 0.025
2018-12-15 09:17:37,076 24687 ERROR website werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 126, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo12/odoo-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1486, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo12/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/http_routing/models/ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo12/odoo/addons/website/models/ir_http.py", line 239, in _handle_exception
    html = request.env['ir.ui.view'].render_template('website.http_error', values)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1276, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "<decorator-gen-244>", line 2, in get_view_id
    
  File "/opt/odoo12/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 223, in get_view_id
    view = self.search(domain, order='website_id', limit=1)
  File "/opt/odoo12/odoo/odoo/models.py", line 1555, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo12/odoo/odoo/models.py", line 4063, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block - - -`

![17_20_31__12_15_2018](https://user-images.githubusercontent.com/43988295/50041374-d0cd9200-008e-11e9-97ec-df0ce1541ab4.jpg)
<img width="1162" alt="20181215172102" src="https://user-images.githubusercontent.com/43988295/50041375-d1662880-008e-11e9-8494-9a250bd033cb.png">
<img width="1246" alt="20181215172451" src="https://user-images.githubusercontent.com/43988295/50041376-d1662880-008e-11e9-98eb-bd6b1d7b1453.png">

**Comment by rdeodoo** [comment]
Hello,

Same as https://github.com/odoo/odoo/issues/27861#issuecomment-432444785

I will keep you updated once fixed

**Comment by popiahalex** [comment]
has this been solve yet?

**Comment by popiahalex** [comment]
> Hello,
> 
> Same as [#27861 (comment)](https://github.com/odoo/odoo/issues/27861#issuecomment-432444785)
> 
> I will keep you updated once fixed

Hi! @rdeodoo has solution for this yet?

**Comment by rdeodoo** [comment]
Hello, it has been merged today at https://github.com/odoo/odoo/pull/28301
The 0 prices (leading to the error when adding to cart afterward) was coming from the fact there was no pricelists available for any websites other than the first one.
See point 2. of https://github.com/odoo/odoo/commit/2d970942bae15a6e5378a05deec18295435c235f
Note that this error also happens in 11.0 or any versions if you don't have any pricelists available, which is a misconfiguration (eg delete all pricelists).
With this commit, the public pricelist will be generic (shared between websites), thus 0 prices will be avoided when creating a new website.
