### ISSUE TITLE
[12] Issue with jQuert

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#29564]
Impacted versions: 12

Steps to reproduce: Try to assign a task to another person
same error obtained when tring to create note and when click on the arrows to extend to rich text format.

Current behavior: Error message:
Erreur:
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.

http://192.168.1.113:8069/web/content/2448-9902a62/web_editor.assets_editor.js:241
Retraçage :
Error: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.
    at getMatchedCSSRules (http://192.168.1.113:8069/web/content/2448-9902a62/web_editor.assets_editor.js:241:168)
    at Object.styleToClass (http://192.168.1.113:8069/web/content/2448-9902a62/web_editor.assets_editor.js:264:128)
    at Class._renderEdit (http://192.168.1.113:8069/web/content/2447-382bd27/web.assets_backend.js:2390:597)
    at Class._render (http://192.168.1.113:8069/web/content/2447-382bd27/web.assets_backend.js:1040:36)
    at http://192.168.1.113:8069/web/content/2447-382bd27/web.assets_backend.js:1037:1521
    at http://192.168.1.113:8069/web/content/2370-fc0c7d8/web.assets_common.js:802:681
    at fire (http://192.168.1.113:8069/web/content/2370-fc0c7d8/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.1.113:8069/web/content/2370-fc0c7d8/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.1.113:8069/web/content/2370-fc0c7d8/web.assets_common.js:802:649)
    at Function.each (http://192.168.1.113:8069/web/content/2370-fc0c7d8/web.assets_common.js:625:767)

Expected behavior: allow to get list of employees to choose one

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by aitalinassim** [comment]
Sir,

The issue is present in runbot.
Please try by the following steps:
- http://415045-master-c33ac7.runbot19.odoo.com/?db=415045-master-c33ac7-all
- Goto projects
- Goto After Sales Services
- Select one task
- Try now to add a follower

Now in same task click on log note then on the right click on full composer (arrows).

Same errors on a local hosted deployment on a local machine.

Please check.

**Comment by pedrobaeza** [comment]
Thanks for the extra info, Nassim

I have just tried what you explained and I don't get the problem:

![peek 17-12-2018 16-28](https://user-images.githubusercontent.com/7165771/50096946-128a4400-0219-11e9-9c82-cccccb54b26a.gif)

so maybe I'm missing something on the steps to reproduce or it's something on your local testing environment. Can you check again the steps I put on my video to see if there's something missing. Also check that you have latest browsers version.

**Comment by ivastanin** [comment]
Odoo raise this error when Kaspersky Anti-Banner is turned on in browser. Tested on Mozilla and Chrome.

**Comment by pedrobaeza** [comment]
@ivastanin thanks for the insight. Then the problem is not in Odoo itself, but with that 3rd party blocker. @aitalinassim can you confirm this?

**Comment by aitalinassim** [comment]
Yes, I confirm.
I installed Kaspersky and it was the reason.
Thanks so much for your assistance.

**Comment by aliounezeyn** [comment]
In my case, I had an activated AdBlocker chrome extension.. it can obstruct some actions. so deativate it and try againg
