### ISSUE TITLE
[12.0] sales order: send email with Arabic language

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#29635]
Impacted versions:
12.0

Steps to reproduce:
1. Create sales order
2. click on "Send by email"

Current behavior:
Appear below error
```python
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
NameError: name 'aaaa' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/models.py", line 5430, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/models.py", line 5283, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/mail/wizard/mail_compose_message.py", line 369, in onchange_template_id_wrapper
    values = self.onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/mail/wizard/mail_compose_message.py", line 391, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/mail/wizard/mail_compose_message.py", line 526, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/mail/models/mail_template.py", line 474, in generate_email
    result, format = report.render_qweb_pdf([res_id])
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/base/models/ir_actions_report.py", line 654, in render_qweb_pdf
    attachment_id = self.retrieve_attachment(record_id)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/addons/base/models/ir_actions_report.py", line 152, in retrieve_attachment
    attachment_name = safe_eval(self.attachment, {'object': record, 'time': time})
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/runbot/runbot/runbot/static/build/416300-12-0-4a9bfe/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: <class 'NameError'>: "name 'aaaa' is not defined" while evaluating
'aaaa'
```

**Comment by pedrobaeza** [comment]
Hi @abdallamhafeez this seems something on the translation of that template that is incorrect. Please check how to translate it correctly in https://github.com/odoo/odoo/wiki/Translations

**Comment by abdallamhafeez** [comment]
@pedrobaeza But I test it in runbot without any changes in odoo translation for Arabic language

**Comment by pedrobaeza** [comment]
Runbot contains the same community translation that is done on Transifex, and doesn't depend on Odoo itself. Please check this.

**Comment by abdallamhafeez** [comment]
Ok, Thanks

**Comment by mart-e** [comment]
Closing as no more information.
Let us know if still happening on an up to date database
