### ISSUE TITLE
Error install all application

### ISSUE THREAD

**Issue by CheckB** [odoo/odoo#29644]
Impacted versions:
12.0

1. Removed application projects and chats.
2. Trying to put on a new one.

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 197, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2404, in _auto_init
    new = field.update_db(self, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2092, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 871, in update_db
    self.update_db_notnull(model, column)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 911, in update_db_notnull
    model._init_column(self.name)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_alias.py", line 234, in _init_column
    IM._reflect_model(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 266, in _reflect_model
    ids = query_update(cr, self._table, params, ['model'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 65, in query_update
    cr.execute(query, values)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "is_mail_thread" of relation "ir_model" does not exist
LINE 1: UPDATE ir_model SET is_mail_thread=true,transient=false,info...
                            ^

```

**Comment by CheckB** [comment]
What is it and how to fix it?

**Comment by CheckB** [comment]
> 3 karma is required to perform this action. You can earn karma by having your answers upvoted by the community.

Hmm ... very useful, for someone who uses odoo for the first time.

**Comment by pedrobaeza** [comment]
The karma is for avoiding spam. Just registering and confirming your email you will have enough karma AFAIK.

**Comment by sswapnesh** [comment]
@pedrobaeza
I can confirm this issue in latest v12 Community.

Uninstall `Discuss` module --> Install again (`Discuss` or any other module)

![screenshot](https://user-images.githubusercontent.com/16624719/50297870-d1599480-04a3-11e9-977c-cc806a165c47.png)

**Comment by pedrobaeza** [comment]
Well, uninstalling Discuss (`mail`) is the same as uninstalling `base` or `web`: very deep in the heart of Odoo as to be done without repercussions and nothing that anybody is going to do except that for a playground.

Said that, it's good to hunt everything if possible. I'm tagging this, but for sure this is not going a total priority thing.

**Comment by sswapnesh** [comment]
What about preventing uninstall of Discuss (`mail`) module too like this.
![screenshot](https://user-images.githubusercontent.com/16624719/50298575-788afb80-04a5-11e9-9aa2-9c29c9abad96.png)

**Comment by pedrobaeza** [comment]
Yeah, I have already thought about that, but if it's a separate module is because a reason: you may not need to install it on certain uses of Odoo. Very weird in our usual flows, I know, but check some things like this use of Odoo: https://koozic.net/ without `mail` module.

**Comment by Yenthe666** [comment]
Oh no, not these ones again. We had quite a few of those in V11 too, where they had to patch in SQL queries hehe. I can't remember who fixed it anymore..

**Comment by Nikunja-Maharana** [comment]
Is there any solution that how to fix that issue ??
Because i am also facing that situation on V12 while creating a custom-module and before that i installed the Discuss module and again uninstalled it.After that the error arrise.
Please give any solution how to fix ??

**Comment by rizagokay** [comment]
This problem also occured on my environment. A workaround would be nice if possible

**Comment by ruturajchavda182** [comment]
Only one solution that I found backup your database, create another database and reinstall all app again.

**Comment by smartickle** [comment]
hmm still waiting for this...

**Comment by Jonna99** [comment]
Add the following columns: is_mail_blacklist, is_mail_thread, is_mail_actitivity, must be of boolean type to the ir_model table, restart the server, install the applications again
