### ISSUE TITLE
payslip odoo 10 error when printing

### ISSUE THREAD

**Issue by bireumdione** [odoo/odoo#29663]
Hello can you help i got this erroe when i generate payslip

Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
response = self.report_routes(reportname, docids=docids, converter='pdf')
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 181, in get_pdf
html = self.with_context(context).get_html(docids, report_name, data=data)
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 138, in get_html
return report_model.render_html(docids, data=data)
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/abstract_report.py", line 49, in render_html
return self.env['report'].with_context(context).render(self._template, docargs)
File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 123, in render
return view_obj.render_template(template, values)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
return self.browse(self.get_view_id(template)).render(values, engine)
File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
return super(IrUiView, self).render(values=values, engine=engine)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
return self.env[engine].render(self.id, qcontext)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 249, in render
self.compile(template, options)(self, body.append, values or {})
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 323, in _compiled_fn
raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: can't adapt type 'hr.payslip.line'
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 316, in _compiled_fn
return compiled(self, append, values, options, log)
File "", line 1, in template_715_286
File "", line 3, in body_call_content_285
File "", line 4, in foreach_284
File "", line 221, in foreach_259
File "/usr/lib/python2.7/dist-packages/odoo/addons/l10n_syscoa_payroll/report/syscoa_report_payslip.py", line 212, in get_rate_patronal
rate = (payslip_line_comp[0].rate)
File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 915, in get
self.determine_value(record)
File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1017, in determine_value
record._prefetch_field(self)
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3074, in _prefetch_field
result = records.read([f.name for f in fs], load='_classic_write')
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3018, in read
self._read_from_database(stored, inherited)
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3142, in _read_from_database
cr.execute(query_str, params)
File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
return f(self, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
res = self._obj.execute(query, params)
File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'hr.payslip.line'

Error to render compiling AST
ProgrammingError: can't adapt type 'hr.payslip.line'
Template: 715
Path: /templates/t/t/t/div/table[2]/tbody/tr/td[8]/span
Node:

the code:
def get_rate_patronal(self, psline):
env = odoo.api.Environment(self.cr, self.uid, {})
psline_code_comp = psline.code + '_C'
pooler = env['hr.payslip.line']
payslip_line_comp_id = pooler.search([('slip_id', '=', psline.slip_id.id), ('code', '=', psline_code_comp)])
payslip_line_comp = pooler.browse(payslip_line_comp_id)
if payslip_line_comp:
rate = (payslip_line_comp[0].rate)
if round(float(rate), 2) == 100.00:
return ''
return formatl(rate, 2)
return ''

**Comment by pedrobaeza** [comment]
This is due to a custom module `l10n_syscoa_payroll`, so you should ask to be fixed there, not here on Odoo.

Closing as no issue with Odoo.
