### ISSUE TITLE
Google Calendar Sync

### ISSUE THREAD

**Issue by scrimo** [odoo/odoo#29684]
Impacted versions:
12.0
Steps to reproduce:
Sync with Google Calendar

Odoo Server Error
Traceback (most recent call last):
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/addons/google_calendar/models/google_calendar.py", line 590, in synchronize_events
    res = recs.update_events(lastSync)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/addons/google_calendar/models/google_calendar.py", line 784, in update_events
    event_to_synchronize[base_event][current_event].compute_OP(modeFull=not lastSync)
  File "/Users/jakobsaxinger/DEV/odoo12/odoo/addons/google_calendar/models/google_calendar.py", line 85, in compute_OP
    if abs(self.OE.update - self.GG.update) > timedelta(seconds=1):
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'

**Comment by pedrobaeza** [comment]
@mart-e any clue about this? Surfing a bit over the code, might be an unitialized variable (`update`) on the Google part.

**Comment by mart-e** [comment]
Not sure, if it is case, it could be that the event has no `updated` value. According to the comment, linked to a deleted event?
@JKE-be quite old but maybe you remember the meaning of the comment?

https://github.com/odoo/odoo/blob/ddc5cc186fc6e2efa92fea6a83ad4bbed72d648c/addons/google_calendar/models/google_calendar.py#L774

**Comment by JKE-be** [comment]
From what I understand from my comment,

When you delete a event in google and ask all modification from last 2weeks, you get the deleted event without any ´updated’ attrributes 

Basically it works until now because py2 allow the comparison of date to Nonetype

**Comment by scrimo** [comment]
> From what I understand from my comment,
> 
> When you delete a event in google and ask all modification from last 2weeks, you get the deleted event without any ´updated’ attrributes
> 
> Basically it works until now because py2 allow the comparison of date to Nonetype

alright thank you!
when do you plan to fix that bug?

**Comment by C3POdoo** [comment]
Dear @scrimo,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
