### ISSUE TITLE
[12.0] mail/leaves/partner: crash on Test Import

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#29714]
"Test Import" feature failed for some employees, while "Import" worked as expected. Not sure what was the difference between the employee - DB entries were same except name and IDs.

Assumption is that email should not even have been generated?

```
2018-12-21 13:25:37,265 13 ERROR brainbeanapps werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 126, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/lib/python3/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1490, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 284, in __exit__
    self._cr.commit()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 374, in commit
    func()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/res_partner.py", line 182, in send_notifications
    env['mail.mail'].browse(email_ids).send()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 246, in send
    for server_id, batch_ids in self._split_by_server():
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 223, in _split_by_server
    groups[mail.mail_server_id.id].append(mail.id)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 977, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1036, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1074, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1046, in compute_value
    self._compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in _compute_value
    self.compute(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 605, in _compute_related
    values = [first(value[name]) for value in values]
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 605, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5049, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1036, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1074, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in _compute_value
    self.compute(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 605, in _compute_related
    values = [first(value[name]) for value in values]
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 605, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5049, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 977, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1036, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1074, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2770, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5049, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1036, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1074, in getter
    raise exception
odoo.exceptions.MissingError: ('Record does not exist or has been deleted.', None) - - -
```

**Comment by Yenthe666** [comment]
@alexey-pelykh thanks for the report. Can you add some extra info or an example file to import please?

**Comment by alexey-pelykh** [comment]
@Yenthe666 in my debugging, it turns out that it's not directly related to data. Only IDs and names of the employees were different, everything else (including user, employee, partner data) were literally same. I suspect that it's due to https://github.com/odoo/odoo/blob/47aae6fabafcb48d6838dffb0a3d0aa90ad6998c/addons/mail/models/res_partner.py#L187
and nature of "Test Import" - after test is successful, transaction closes, changes are removed and _then_ emails are trying to be sent - while there are no more emails with such ids

**Comment by alexey-pelykh** [comment]
Yet my knowledge of Odoo internals is not deep enough to validate this assumption, thus unfortunately, I'm not that helpful here. The only thing I'm 99% sure about - it's not the _content_ of data.

**Comment by Yenthe666** [comment]
@tde-banana-odoo I summon you 😉

**Comment by Yenthe666** [comment]
@tde-banana-odoo pretty please?

**Comment by alexey-pelykh** [comment]
See #30523 I guess

**Comment by Yenthe666** [comment]
@tde-banana-odoo hi, did you ever get around to checking this?

**Comment by Yenthe666** [comment]
@alexey-pelykh I'm actually pretty sure it has been fixed in https://github.com/odoo/odoo/commit/c7b6fcb9f23671847f7e3a3ccd1b7b781a7b51ca

**Comment by gustavovalverde** [comment]
@Yenthe666 I'm experiencing this behavior on the last commit when importing leave allocations (_hr.leave.allocation_). And I'm actually stuck with an import because of it

Error:
```python
Traceback (most recent call last):
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 126, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1490, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 284, in __exit__
    self._cr.commit()
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 374, in commit
    func()
  File "/odoo/odoo-server/src/odoo/addons/mail/models/res_partner.py", line 182, in send_notifications
    env['mail.mail'].browse(email_ids).send()
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_mail.py", line 247, in send
    for server_id, batch_ids in self._split_by_server():
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_mail.py", line 224, in _split_by_server
    groups[mail.mail_server_id.id].append(mail.id)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 988, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1086, in getter
    raise exception
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1057, in compute_value
    self._compute_value(record)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1045, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 609, in _compute_related
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 609, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5097, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1086, in getter
    raise exception
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1045, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 609, in _compute_related
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 609, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5097, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 988, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1086, in getter
    raise exception
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 2787, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 5097, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 1086, in getter
    raise exception
odoo.exceptions.MissingError: ('El registro no existe o ha sido eliminado.', None) 205 0.076 0.157

Maybe @nim-odoo could have a look at it.

```
