### ISSUE TITLE
[11] Odoo accounting Mexico not redering reports, date error

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#29839]
Impacted versions:
0doo 11 Enterprise
Steps to reproduce:

Try to generate the Balanza de comprobación or COA.  Sometimes it trows this error, sometimes it generates it. 

The date today is 31 of december, maybe it is related. 

Current behavior:

```
Error:
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reports/models/account_report.py", line 297, in get_report_informations
    options = self.apply_date_filter(options)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reports/models/account_report.py", line 516, in apply_date_filter
    options['date']['string'] = self.format_date(dt_to, dt_from, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reports/models/account_report.py", line 502, in format_date
    return _('As of %s') % (format_date(self.env, dt_to.strftime(DEFAULT_SERVER_DATE_FORMAT)),)
AttributeError: 'bool' object has no attribute 'strftime'

```
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you reported the problem in odoo.com/help?

**Comment by hydrosIII** [comment]
This seems to be solved in the most recent version of odoo enterprise. I updated the code, and it is not giving the error anymore. Version of january 17th.
