### ISSUE TITLE
[12] Could not reinstall (or wrong error after install) website_sale module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29843]
Impacted versions: 12.0

Reproduced on : http://420643-12-0-76e46b.runbot15.odoo.com/web#action=32&model=ir.module.module&view_type=kanban&menu_id=5

Steps to reproduce: Install (`website_sale`) -->Remove (`Sale - Sales internal machinery` module) --> Install again `website_sale` module

Current behavior: 
![screenshot](https://user-images.githubusercontent.com/16624719/50575010-f6da8c80-0e19-11e9-93c8-b773075d39a1.png)

Expected behavior: Module should be installed

Video/Screenshot link (optional):

Log: 
```
2019-01-01 17:34:14,488 3557 ERROR 12website odoo.tools.convert.init: Could not eval([{                 'xml_id': 'sale.product_template_attribute_value_3',                 'record': obj().env.ref('product.product_template_attribute_line_1').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_4',                 'record': obj().env.ref('product.product_template_attribute_line_4').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_5',                 'record': obj().env.ref('product.product_template_attribute_line_2').product_template_value_ids[1],                 'noupdate': True,             }]) for None in {} 
2019-01-01 17:34:14,489 3557 WARNING 12website odoo.modules.loading: Module sale demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/swapnesh/Workspace/12/odoo/models.py", line 5053, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 342, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 187, in _eval_xml
    return_val = _eval_xml(self, n, env)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 112, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 27, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/swapnesh/Workspace/12/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/swapnesh/Workspace/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/swapnesh/Workspace/12/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/swapnesh/Workspace/12/odoo/models.py", line 5053, in __getitem__
    return self._browse((self._ids[key],), self.env)
ValueError: <class 'IndexError'>: "tuple index out of range" while evaluating
"[{                 'xml_id': 'sale.product_template_attribute_value_3',                 'record': obj().env.ref('product.product_template_attribute_line_1').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_4',                 'record': obj().env.ref('product.product_template_attribute_line_4').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_5',                 'record': obj().env.ref('product.product_template_attribute_line_2').product_template_value_ids[1],                 'noupdate': True,             }]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/home/swapnesh/Workspace/12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/swapnesh/Workspace/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 342, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 187, in _eval_xml
    return_val = _eval_xml(self, n, env)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 112, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 27, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/swapnesh/Workspace/12/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/swapnesh/Workspace/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/swapnesh/Workspace/12/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/swapnesh/Workspace/12/odoo/models.py", line 5053, in __getitem__
    return self._browse((self._ids[key],), self.env)
odoo.tools.convert.ParseError: "<class 'IndexError'>: "tuple index out of range" while evaluating
"[{                 'xml_id': 'sale.product_template_attribute_value_3',                 'record': obj().env.ref('product.product_template_attribute_line_1').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_4',                 'record': obj().env.ref('product.product_template_attribute_line_4').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_5',                 'record': obj().env.ref('product.product_template_attribute_line_2').product_template_value_ids[1],                 'noupdate': True,             }]"" while parsing /home/swapnesh/Workspace/12/addons/sale/data/sale_demo.xml:784, near
<function model="ir.model.data" name="_update_xmlids">
            <value model="base" eval="[{                 'xml_id': 'sale.product_template_attribute_value_3',                 'record': obj().env.ref('product.product_template_attribute_line_1').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_4',                 'record': obj().env.ref('product.product_template_attribute_line_4').product_template_value_ids[0],                 'noupdate': True,             }, {                 'xml_id': 'sale.product_template_attribute_value_5',                 'record': obj().env.ref('product.product_template_attribute_line_2').product_template_value_ids[1],                 'noupdate': True,             }]"/>
        </function>
2019-01-01 17:34:14,903 3557 INFO 12website odoo.modules.registry: module website_payment: creating or updating database tables 
2019-01-01 17:34:14,981 3557 INFO 12website odoo.modules.loading: loading website_payment/views/payment_acquirer.xml 
2019-01-01 17:34:15,053 3557 INFO 12website odoo.modules.loading: Module website_payment: loading demo 
2019-01-01 17:34:15,424 3557 INFO 12website odoo.modules.registry: module website_sale: creating or updating database tables 
2019-01-01 17:34:15,908 3557 INFO 12website odoo.models: Storing computed values of account.invoice.website_id 
2019-01-01 17:34:16,369 3557 INFO 12website odoo.modules.loading: loading website_sale/security/ir.model.access.csv 
2019-01-01 17:34:16,439 3557 INFO 12website odoo.modules.loading: loading website_sale/security/website_sale.xml 
2019-01-01 17:34:17,378 3557 INFO 12website odoo.modules.loading: loading website_sale/data/data.xml 
2019-01-01 17:34:17,437 3557 INFO 12website odoo.modules.loading: loading website_sale/data/mail_template_data.xml 
2019-01-01 17:34:17,446 3557 INFO 12website odoo.modules.loading: loading website_sale/data/digest_data.xml 
2019-01-01 17:34:17,454 3557 INFO 12website odoo.modules.loading: loading website_sale/views/product_views.xml 
2019-01-01 17:34:18,057 3557 INFO 12website odoo.modules.loading: loading website_sale/views/account_views.xml 
2019-01-01 17:34:18,186 3557 INFO 12website odoo.modules.loading: loading website_sale/views/onboarding_views.xml 
2019-01-01 17:34:18,223 3557 INFO 12website odoo.modules.loading: loading website_sale/views/sale_report_views.xml 
2019-01-01 17:34:18,314 3557 INFO 12website odoo.modules.loading: loading website_sale/views/sale_order_views.xml 
2019-01-01 17:34:18,871 3557 INFO 12website odoo.modules.loading: loading website_sale/views/crm_team_views.xml 
2019-01-01 17:34:18,931 3557 INFO 12website odoo.modules.loading: loading website_sale/views/templates.xml 
2019-01-01 17:34:20,567 3557 INFO 12website odoo.modules.loading: loading website_sale/views/snippets.xml 
2019-01-01 17:34:20,603 3557 INFO 12website odoo.modules.loading: loading website_sale/views/res_config_settings_views.xml 
2019-01-01 17:34:21,069 3557 INFO 12website odoo.modules.loading: loading website_sale/views/digest_views.xml 
2019-01-01 17:34:21,128 3557 INFO 12website odoo.modules.loading: Module website_sale: loading demo 
2019-01-01 17:34:21,128 3557 INFO 12website odoo.modules.loading: loading website_sale/data/demo.xml 
2019-01-01 17:34:21,137 3557 WARNING 12website odoo.modules.loading: Module website_sale demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'sale.product_product_1_product_template'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/home/swapnesh/Workspace/12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/swapnesh/Workspace/12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/swapnesh/Workspace/12/odoo/tools/convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
odoo.tools.convert.ParseError: "Cannot update missing record 'sale.product_product_1_product_template'" while parsing /home/swapnesh/Workspace/12/addons/website_sale/data/demo.xml:8, near
<record id="sale.product_product_1_product_template" model="product.template">
            <field name="website_sequence">100</field>
            <field name="website_published" eval="True"/>
        </record>

```

**Comment by seb-odoo** [comment]
I don't think this is related to website, even just removing `sale` and installing it again will create the issue?

**Comment by sswapnesh** [comment]
I think it will create same issue (Not tested yet)

**Comment by Yenthe666** [comment]
Hmm converting to framework as it seems to be more general atleast.

**Comment by sswapnesh** [comment]
@seb-odoo  Got same error again (as mentioned on Issue)
![screenshot](https://user-images.githubusercontent.com/16624719/50598956-7035b600-0ed2-11e9-9809-d6305a18f139.png)

> 
> And finally this between uninstall and reinstall :
> 
> 2019-01-02 14:48:19,934 25635 WARNING 12.0 odoo.modules.registry: Models have no table: account.invoice.report. 
> 2019-01-02 14:48:19,935 25635 INFO 12.0 odoo.modules.registry: Recreate table of model account.invoice.report. 

This logger seems related to  #23528, #23529, #23530

**Comment by seb-odoo** [comment]
I think the first step should be to override `_module_data_uninstall` (or `module_uninstall`) in `product` to remove the created products before their corresponding attributes/values.

But I'm not sure if a specific fix is in order here... This seems like a potentially general issue with the order on which to delete models.

Or disable foreign key constrains during uninstall.

I'll stop my investigation here, this seems like an issue for framework/ORM.

**Comment by sswapnesh** [comment]
@Elkasitu should see this as he has solved most of the similar issues like this.

**Comment by Elkasitu** [comment]
Actually this is a safeguard for modules which introduce "bad" demo data, you will find that `website_sale` installs anyway, but without demo data (at least that's what I was able to reproduce locally).

There are 2 bugs here:

1) Some demo data introduced by either `website_sale` or `sale` does not work properly when reinstalling, this happens sometimes and is the reason for the introduction of the aforementioned safeguard, we don't really _care_ that much about this since demo data is for demo purposes and not for production databases

2) The failed demo data mechanism seems to not display correct information, it is supposed to display which demo data from which module failed (cc @xmo-odoo)

None of which are blocking IMO, let me know if this actually blocks the installation of the `webiste_sale` module.

**Comment by sswapnesh** [comment]
Reinstall of website_sale works fine (Without demo data)

**Comment by Yenthe666** [comment]
@Elkasitu has anything been changed in the meanwhile?

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by sswapnesh** [comment]
> Is this still happening?

Yes
(Reproduced at https://2157813-12-0-940426.runbot31.odoo.com/web#action=32&model=ir.module.module&view_type=kanban&menu_id=5)

**Comment by pedrobaeza** [comment]
OK, @Elkasitu maybe you can re-check this

**Comment by deepakv-ksolves** [comment]
Try using this in your conf file 
without_demo=WITHOUT_DEMO

and create a new database by renaming it

**Comment by Yenthe666** [comment]
What a shitty advice. 😆

**Comment by hasan918** [comment]
![errorinventory](https://user-images.githubusercontent.com/60201118/161380056-524ba5a3-38f8-4328-90bf-02786c33869b.PNG)
 hi guys I m facing this error , I m new to odoo
 and I m just following a tutorial on Youtube.
 the guy that I m following have just  installed inventory module without getting an error (with developer mode activated and with the demo data) i followed him and when I installed inventory module  I got this error  can any1 help me 
thanks for advice

**Comment by mukeshbigscal** [comment]
Maybe Because of you deleted the data directory from the in built module
