### ISSUE TITLE
Odoo displays error message when I try to open user list

### ISSUE THREAD

**Issue by olubiyi80** [odoo/odoo#30007]
Please how do I resolve this error from odoo, I installed the smile access control addon, and I got the error message below, I think the error comes from security --> record rules, but I don't know how to identity the problem.

Impacted versions:
12.0

Steps to reproduce:

Install and uninstall smile access control addon.

Current behavior:
Odoo displays error when I click users to view the list of users

Odoo Server Error
Traceback (most recent call last):
  File "/odoo24/odoo24-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo24/odoo24-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo24/odoo24-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo24/odoo24-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo24/odoo24-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo24/odoo24-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo24/odoo24-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo24/odoo24-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo24/odoo24-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo24/odoo24-server/addons/web/controllers/main.py", line 904, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo24/odoo24-server/addons/web/controllers/main.py", line 926, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/odoo24/odoo24-server/odoo/models.py", line 4509, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo24/odoo24-server/odoo/models.py", line 1555, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo24/odoo24-server/odoo/addons/base/models/res_users.py", line 421, in _search
    access_rights_uid=access_rights_uid)
  File "/odoo24/odoo24-server/odoo/models.py", line 4045, in _search
    query = self._where_calc(args)
  File "/odoo24/odoo24-server/odoo/models.py", line 3836, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo24/odoo24-server/odoo/osv/expression.py", line 670, in __init__
    self.parse()
  File "/odoo24/odoo24-server/odoo/osv/expression.py", line 851, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'is_user_profile' in leaf "<osv.ExtendedLeaf: ('is_user_profile', '=', False) on res_users (ctx: )>"

Expected behavior:
To open user lists

Video/Screenshot link (optional):

**Comment by olubiyi80** [comment]
Wrong password. I cannot login to the runbot. admin/admin not working

Thanks

**Comment by pedrobaeza** [comment]
This is someone unrespectful that has changed it. Please try another instance or later.

**Comment by Boudmir-Ibrahim** [comment]
This is not a Odoo SA module. It is developed by Smile open source Solutions.
You can reach out the developers of that module by posting your issue here : https://github.com/Smile-SA/odoo_addons/issues

Regards.
