### ISSUE TITLE
xmlrpc message_post fail in odoo 12 enterprise

### ISSUE THREAD

**Issue by kasper-f** [odoo/odoo#30076]
**Impacted versions:** 
Enterprise 12.0 - 12.latest
(Works in odoo 11.*)
**Steps to reproduce:**
*  Boot odoo enterprise docker image (build with official build script and enterprise dep package)
```
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name odoo-db postgres:10
docker run -p 8069:8069 --link odoo-db:db --name odoo -t clean-entarprise-odoo
```
*  create database with demo data: database:'test', password:'testing'
*  install contacts app
*  post note via xml-rpx: `curl --data @postnote.txt -H 'Content-Type: text/xml' http://localhost:8069/xmlrpc/2/object
`
Please note the xml file attachment (as txt) [postnote.txt](https://github.com/odoo/odoo/files/2741220/postnote.txt)
* confirm in contact -> Oscar Morgan that the note is posted
* install helpdesk app
*  post note again, and it will fail. See the error bellow

**Current behavior:**
Calling `message_post` with arguments and helpdesk app installed fails with following error:
```
2019-01-09 14:10:15,861 1 ERROR test odoo.http: dictionary update sequence element #0 has length 1; 2 is required 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 120, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 39, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 153, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 160, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 149, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 734, in _call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4728, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
2019-01-09 14:10:15,863 1 INFO test werkzeug: 172.17.0.1 - - [09/Jan/2019 14:10:15] "POST /xmlrpc/2/object HTTP/1.1" 200 - 3 0.002 0.009

```
Without helpdesk or without arguments the method succeeds

**Expected behavior:**
message_post via xml-rpc should also work when the helpdesk is installed 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Strange way to reproduce the problem, but any way, this is something of enterprise, so you should report it to www.odoo.com/help.

**Comment by Donderda** [comment]
@kasper-f where you or the odoo team able to fix this? I have exactly the same problem, but  I want to add a comment to an order...

**Comment by kasper-f** [comment]
@Donderda They say that the message_post does not take any arguments in odoo 12 via xml_rpc? Think that sounds strange as I can use the method with arguments until I install the helpdesk module.

However I am now using the method without any arguments and posting all content via the **kwargs.
If you need to add attachments they should be created first and then the attachment ID should be added to the **kwargs as well
