### ISSUE TITLE
Uncaught ReferenceError: pyeval is not defined (ERROR AFTER FETCH TO LAST UPDATE)

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#30379]
Impacted versions: 12

Steps to reproduce: **Git Fetch to origin 12.0**

Current behavior: Error while accessing to purchases any many many modules

Erreur:
**Uncaught ReferenceError: pyeval is not defined**

http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:984
Retraçage :
ReferenceError: pyeval is not defined
    at Object.get_context (http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:984:531)
    at http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:894:19
    at Function._.each._.forEach (http://192.168.1.120:8069/web/content/2641-0dc0b5b/web.assets_common.js:12:558)
    at child.Collection.(anonymous function) [as each] (http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:68:545)
    at Class.build_search_data (http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:893:214)
    at Array.<anonymous> (http://192.168.1.120:8069/web/content/2642-13eed7b/web.assets_backend.js:502:127)
    at Array.<anonymous> (http://192.168.1.120:8069/web/content/2641-0dc0b5b/web.assets_common.js:802:681)
    at fire (http://192.168.1.120:8069/web/content/2641-0dc0b5b/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.1.120:8069/web/content/2641-0dc0b5b/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.1.120:8069/web/content/2641-0dc0b5b/web.assets_common.js:802:649)

Expected behavior: no errors shall apear

**Comment by pedrobaeza** [comment]
It seems that is a legit problem according #30378, but only reproducible when the action window has a context. That one should fix it. You can use that one or wait until merged.

**Comment by pedrobaeza** [comment]
Closing as duplicated of #30377

**Comment by aitalinassim** [comment]
Great, fixed.
