### ISSUE TITLE
Missing dependence of pyeval.

### ISSUE THREAD

**Issue by zyyang** [odoo/odoo#30377]
Impacted versions:
12, both community & enterprise.

Steps to reproduce:
1. Checkout latest code, create a blank database and install stock app.
2. Group by warehouse, and save current search result as default.
3. Try to get into Stock app again.

Current behavior:
`Uncaught ReferenceError: pyeval is not defined
http://127.0.0.1:8069/web/static/src/js/views/search/favorites_menu.js:201
Trace:
ReferenceError: pyeval is not defined
    at Object.get_context (http://127.0.0.1:8069/web/static/src/js/views/search/favorites_menu.js:201:25)
    at http://127.0.0.1:8069/web/static/src/js/views/search/search_view.js:545:33
    at Function._.each._.forEach (http://127.0.0.1:8069/web/static/lib/underscore/underscore.js:145:9)
    at child.Collection.(anonymous function) [as each] (http://127.0.0.1:8069/web/static/lib/backbone/backbone.js:956:24)
    at Class.build_search_data (http://127.0.0.1:8069/web/static/src/js/views/search/search_view.js:538:20)
    at Array.<anonymous> (http://127.0.0.1:8069/web/static/src/js/chrome/action_manager_act_window.js:328:49)
    at Array.<anonymous> (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3275:77)`

Expected behavior:
No error.

Video/Screenshot link (optional):
None

Possible Fix:
/web/static/src/js/views/search/favorites_menu.js:201
Change pyeval to pyUtils.

**Comment by pedrobaeza** [comment]
Fixed in #30378
