### ISSUE TITLE
Email working fine except from sale order form, in every state like quotation, confirmed)

### ISSUE THREAD

**Issue by faizankarim** [odoo/odoo#30375]
Impacted versions: 12.0+e

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_295_6261
  File "/home/odoo/src/odoo/12.0/addons/sale/models/sale.py", line 882, in get_access_action
    if not self.sale_order_template_id or (not user.share and not self.env.context.get('force_website')):
AttributeError: 'sale.order' object has no attribute 'sale_order_template_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/12.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/12.0/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/addons/mail/wizard/mail_compose_message.py", line 193, in action_send_mail
    self.send_mail()
  File "/home/odoo/src/odoo/12.0/addons/website_sale/models/mail_compose_message.py", line 21, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/home/odoo/src/odoo/12.0/addons/mail/wizard/mail_compose_message.py", line 267, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/home/odoo/src/odoo/12.0/addons/sale/models/sale.py", line 634, in message_post
    return super(SaleOrder, self.with_context(mail_post_autofollow=True)).message_post(**kwargs)
  File "/home/odoo/src/odoo/12.0/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/home/odoo/src/odoo/12.0/addons/mail/models/mail_thread.py", line 2058, in message_post
    self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/src/odoo/12.0/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
    return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/src/odoo/12.0/addons/mail/models/mail_thread.py", line 2080, in _message_post_after_hook
    mail_auto_delete=mail_auto_delete,
  File "/home/odoo/src/odoo/12.0/addons/mail/models/mail_message.py", line 1050, in _notify
    model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/src/enterprise/12.0/ocn_client/models/mail_message.py", line 18, in _notify_recipients
    super(MailMessage, self)._notify_recipients(rdata, record, msg_vals, **kwargs)
  File "/home/odoo/src/odoo/12.0/addons/mail/models/mail_message.py", line 1127, in _notify_recipients
    self.env['res.partner']._notify(self, partner_email_rdata, record, force_send=force_send, send_after_commit=send_after_commit, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/home/odoo/src/custom/trial/saas_trial/models/mail.py", line 88, in _notify
    return super(ResPartner, self)._notify(*args, **kwargs)
  File "/home/odoo/src/odoo/12.0/addons/mail/models/res_partner.py", line 135, in _notify
    mail_body = base_template.render(template_ctx, engine='ir.qweb', minimal_qcontext=True)
  File "/home/odoo/src/odoo/12.0/addons/website/models/ir_ui_view.py", line 253, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/12.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/ir_ui_view.py", line 1288, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/qweb.py", line 351, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'sale.order' object has no attribute 'sale_order_template_id'
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_295_6261
  File "/home/odoo/src/odoo/12.0/addons/sale/models/sale.py", line 882, in get_access_action
    if not self.sale_order_template_id or (not user.share and not self.env.context.get('force_website')):
AttributeError: 'sale.order' object has no attribute 'sale_order_template_id'

Error to render compiling AST
AttributeError: 'sale.order' object has no attribute 'sale_order_template_id'
Template: 295
Path: /templates/t/table/tr[1]/td/table/tbody/tr[1]/td/t[1]
Node: <t t-set="access_action" t-value="record.with_context(force_website=True).get_access_action()"/>

**Comment by pedrobaeza** [comment]
You should update your addons in the installation, as the field exists and it's defined in `sale_management` module:

https://github.com/odoo/odoo/blob/d657d6457f4b6cde57646a4a10a992b49105ee51/addons/sale_management/models/sale_order.py#L14

Closing as no real issue.

**Comment by moylop260** [comment]
The module sale is using a field defined of sale_management and it is not dependency of sale.
It was fixed from:
https://github.com/odoo/odoo/commit/13b104bf9e66aaaa7f77345da4efc1c1af7f32cf
