### ISSUE TITLE
[12 EE] When changing color through customize it fails

### ISSUE THREAD

**Issue by JurreCl** [odoo/odoo#30547]
Impacted versions: 12 Enterprise

Steps to reproduce:
Go to website --> Customize --> Customize Theme (with default theme) --> change any color
I managed to reproduce this issue in runbot
Current behavior:
It fails and generates traceback

`2019-01-25 10:57:13,147 20256 ERROR test odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/controllers/main.py", line 450, in save_scss
    IrUiView.create(new_view)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3516, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3602, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1934, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1946, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.ui.view.type: 'data'
`

Expected behavior:

Color to be adjusted 
I've already opened a ticket through the website.
Can also confirm this works just normally in Odoo CE so its just the enterprise branch

Video/Screenshot link (optional):
https://box.logicq.be/runbot.webm

**Comment by JurreCl** [comment]
It seems over the weekend the issue resolved itself. Maybe it was a 3rd partly library that triggered the error? I didnt do any updates (that I know of) on my instance.

**Comment by pedrobaeza** [comment]
Maybe you have restarted the service. Closing this then.

**Comment by JurreCl** [comment]
@pedrobaeza haven't restarted the service. Same goes for the runbot environment. Thats why it seemed odd to me. ;) But yes. Can be closed!
