### ISSUE TITLE
[12] server error when accessing invoice if selecting arabic as language

### ISSUE THREAD

**Issue by imahmedyousif** [odoo/odoo#30591]
Impacted versions: 12

Steps to reproduce:  
                                1- create new database with language set to Arabic
                                2- install invoicing app
                                2- activate full accounting feature in user setting
                                3- open invoice app

Current behavior:  server error (see below error code)

Expected behavior: invoice should open normally without error

Video/Screenshot link (optional):

خطأ:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1370, in load_views
    for [v_id, v_type] in views
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1370, in <dictcomp>
    for [v_id, v_type] in views
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1449, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1412, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 780, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 729, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 707, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//span[@name="button_import_placeholder"]">' cannot be located in parent view

Error context:
View `account.journal.dashboard.kanban.inherit`
[view_id: 601, xml_id: account_bank_statement_import.journal_dashboard_view_inherit, model: account.journal, parent_id: 566]

**Comment by pedrobaeza** [comment]
Are you sure the error is due to the language? According log, that's a typical view error after modifying something in the views. Have you install third party modules? Is this reproducible in runbot?

**Comment by imahmedyousif** [comment]
Thank you @pedrobaeza for your response, the test was done on new installation of odoo with only invoicing app installed and no third party apps active nor installed, also I tried it on runbot but for some reason UI language is not changing and after testing on the local server its appear that if select English in database creation page you can not change the user language anymore I tried Arabic and french with no luck UI still in English even after refresh and server restart and even on a new user, but if I select Arabic in database creation page UI appears in Arabic and I can change it to English but not other Language because UI language will appear as English, I will open another issue for this and edit the procedure for this one.

**Comment by imahmedyousif** [comment]
Solved by new clean installation of Odoo, thanks you all for your support.
