### ISSUE TITLE
[8.0] Stock Wizard Transfer Error

### ISSUE THREAD

**Issue by damlu** [odoo/odoo#3062]
Error while trying to run transfer product on order.

Impacted versions:
8.0

Steps to reproduce:

Go to Sales menu
Choose any order
Click on the red button "View Delivery Order"
On the next screen, click the red button "Transfer"
Click apply on the next screen (popup window)
Current behavior:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 391, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 395, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/stock/wizard/stock_transfer_details.py", line 106, in do_detailed_transfer
    self.picking_id.do_transfer()
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
TypeError: do_transfer() takes at least 4 arguments (4 given)

**Comment by Yenthe666** [comment]
Hi @damlu,

Thank you for your report. As I can not reproduce it either and as Odoo 8 is no longer supported as a stable version I'm closing this report.

Regards,
Yenthe
