### ISSUE TITLE
error happen when install the module Associations: Members

### ISSUE THREAD

**Issue by rainberg** [odoo/odoo#3063]
```
Traceback (most recent call last):
  File "/usr/local/src/odoo/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/src/odoo/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/src/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/src/odoo/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/usr/local/src/odoo/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/src/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/src/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/local/src/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/addons/mail/mail_group.py", line 131, in create
    mail_group_id = super(mail_group, self).create(cr, uid, vals, context=create_context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 3963, in create
    record = self.browse(self._create(old_vals))
  File "/usr/local/src/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 4164, in _create
    self.pool[model_name]._store_set_values(cr, user, ids, fields2, context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 4273, in _store_set_values
    result = self._columns[val[0]].get(cr, self, ids, val, SUPERUSER_ID, context=context)
  File "/usr/local/src/odoo/openerp/osv/fields.py", line 1312, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/local/src/odoo/addons/mail/mail_group.py", line 42, in _get_image
    result[obj.id] = tools.image_get_resized_images(obj.image)
  File "/usr/local/src/odoo/openerp/tools/image.py", line 216, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/usr/local/src/odoo/openerp/tools/image.py", line 154, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/usr/local/src/odoo/openerp/tools/image.py", line 96, in image_resize_image
    image.save(background_stream, filetype)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1631, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 191, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 413, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
ParseError: "decoder zip not available" while parsing /usr/local/src/odoo/addons/website_mail/data/mail_groups.xml:5, near
<record model="mail.group" id="group_all_employees">
            <field name="name">Discussion Group</field>
            <field name="public">public</field>
            <field name="description">Public Discussion Group</field>
        </record>
```

**Comment by Yenthe666** [comment]
Hi @rainberg,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
