### ISSUE TITLE
External XML-RPC: TypeError: cannot marshal <class 'datetime.date'> objects

### ISSUE THREAD

**Issue by yassineselmi** [odoo/odoo#30630]
Impacted versions:
12.0

Steps to reproduce:
Call any model's read method using external XML-RPC API  that returns a date field. Example with python-based xml-rpc client (same problem using ripcord as PHP library):

```
import xmlrpc.client

models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))

res = models.execute_kw(db, uid, password,
    'account.invoice', 'read',
    [150], {'fields': ['date_invoice']})
```

Current behavior:
Calling the methpd 'read' produces:

```
xmlrpc.client.Fault: <Fault 1: 'Traceback (most recent call last):
File "/usr/lib/python3.5/xmlrpc/client.py", line 509, in __dump    f = self.dispatch[type(value)]
KeyError: <class 'datetime.date'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 36, in xmlrpc_2\n    response = self._xmlrpc(service)
File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 17, in _xmlrpc
  return dumps((result,), methodresponse=1, allow_none=False)
 File "/usr/lib/python3.5/xmlrpc/client.py", line 951, in dumps
   data = m.dumps(params)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 523, in __dump\
   f(self, value, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 576, in dump_array
   dump(v, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 594, in dump_struct
    dump(v, write)
 File "/usr/lib/python3.5/xmlrpc/client.py", line 513, in __dump
 
 raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'datetime.date'> objects
'>
```
Expected behavior:
Return the invoice date. 

FYI: I tried to pass `allow_none=True` but doesn't work.

Any suggestions please?

**Comment by moylop260** [comment]
I have created the following script using latest v12.0 from runbot:

```python
import xmlrpc.client


HOST = "http://437355-12-0-6a2466.runbot20.odoo.com"
PORT = 80
DB = "437355-12-0-6a2466-all"
USER = "admin"
PASS = "admin"


root = '%s:%d/xmlrpc/' % (HOST, PORT)
uid = xmlrpc.client.ServerProxy(root + 'common').login(
    DB, USER, PASS)
sock = xmlrpc.client.ServerProxy(root + 'object')
invoice_ids = sock.execute(
    DB, uid, PASS, 'account.invoice', 'search', [])
res = sock.execute(
    DB, uid, PASS, 'account.invoice', 'read', invoice_ids, ['date_invoice'])
print(res)
```

The output is:
`[{'id': 35, 'date_invoice': False}, {'id': 37, 'date_invoice': '2019-01-15'}, {'id': 33, 'date_invoice': '2019-01-13'}, {'id': 32, 'date_invoice': '2019-01-08'}, {'id': 31, 'date_invoice': '2019-01-08'}, {'id': 34, 'date_invoice': '2019-01-01'}, {'id': 30, 'date_invoice': '2019-01-01'}, {'id': 36, 'date_invoice': '2019-01-01'}]`

Could you share your full script used connecting to runbot 12.0, please?

**Comment by yassineselmi** [comment]
Thank you very much for your help.  I had an old Docker image hosted in my own registry. 
I pulled the latest version of Odoo:12 image and the bug has been fixed!

Also, I changed my Dockerfile to pull always the latest version of the Odoo:12 official docker image when I rebuild my custom one.


Thank you again!
