### ISSUE TITLE
[BUG]PDF generating exotic language  

### ISSUE THREAD

**Issue by tailaijin** [odoo/odoo#30684]
The app is generated by
https://github.com/tailaijin/odoo.git

Impacted versions:
Docker version 18.09.1, build 4c52b90
odoo 12.0 - 20190130
wkhtmltopdf 0.12.5 (with patched qt)

Steps to reproduce: Print (Generate pdf)

Current behavior: Files can be downloaded, but all characters, except English, are disappeared.

Expected behavior: Pdf file with all info

Video/Screenshot link (optional): NA

Sys log:

```
2019-01-30 10:10:04,071 1 INFO play odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/play/1d/1d0d0b6b25d36e69c8419c3c674c76f7f701e6b5 
**Traceback (most recent call last):**
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(2,).image_small', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 377

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(377,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/play/1d/1d0d0b6b25d36e69c8419c3c674c76f7f701e6b5'

```

**Comment by tailaijin** [comment]
I use Chinese.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
