### ISSUE TITLE
New version of a module with removed model cannot be updated

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#30804]
Impacted versions: 12.0; probably 11.0 too

Steps to reproduce:

* Add Dummy model to module ``note``:
```
class Dummy(models.Model):

    _name = "note.dummy"
```

* Install module ``note``
* delete dummy class from the module
* restart odoo
* update module ``note``

Current behavior:
```

Odoo Server Error
Traceback (most recent call last):
  File "/mnt/odoo-source/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-source/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/odoo-source/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/odoo-source/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-source/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-source/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-source/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-source/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/odoo-source/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/odoo-source/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/mnt/odoo-source/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/mnt/odoo-source/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/mnt/odoo-source/odoo/addons/base/models/ir_module.py", line 596, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/mnt/odoo-source/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/mnt/odoo-source/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/odoo-source/odoo/modules/loading.py", line 460, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/mnt/odoo-source/odoo/addons/base/models/ir_model.py", line 1621, in _process_end
    record.unlink()
  File "/mnt/odoo-source/odoo/addons/base/models/ir_model.py", line 637, in unlink
    self._prepare_update()
  File "/mnt/odoo-source/odoo/addons/base/models/ir_model.py", line 584, in _prepare_update
    model = self.env[rec.model]
  File "/mnt/odoo-source/odoo/api.py", line 820, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/mnt/odoo-source/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'note.dummy'
```
Expected behavior: 

Successfull upgrade

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@rco-odoo I remember this was happening before and it was fixed. Is it a regression?

**Comment by Elkasitu** [comment]
Related to https://github.com/odoo/odoo/issues/27758 and (supposedly) fixed at https://github.com/odoo/odoo/pull/29247

Is your code up to date? Your traceback displays `model = self.env[rec.model]` but the aforementioned patch (and current 12.0 revision) use `get()`: https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_model.py#L594

**Comment by yelizariev** [comment]
Right. It works with latest odoo 12. I tried to find a similar issue, but checked first page of the search only, while #27758 was on the third https://github.com/odoo/odoo/search?q=KeyError&type=Issues :smile:

**Comment by Mantu105** [comment]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo_ce_16/odoo/api.py", line 997, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 881

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo_ce_16/odoo/fields.py", line 1161, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo_ce_16/odoo/api.py", line 1004, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.actions.act_window(881,).search_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo_ce_16/odoo/http.py", line 1636, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo_ce_16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo_ce_16/odoo/http.py", line 1663, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo_ce_16/odoo/http.py", line 1867, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo_ce_16/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo_ce_16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo_ce_16/odoo/http.py", line 700, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo_ce_16/addons/web/controllers/action.py", line 34, in load
    action = request.env[action_type].sudo().browse([action_id]).read()
  File "/opt/odoo/odoo_ce_16/odoo/addons/base/models/ir_actions.py", line 274, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/opt/odoo/odoo_ce_16/odoo/models.py", line 2996, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo_ce_16/odoo/models.py", line 3175, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo_ce_16/odoo/models.py", line 5920, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/opt/odoo/odoo_ce_16/odoo/fields.py", line 1210, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo_ce_16/odoo/fields.py", line 1392, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo_ce_16/odoo/models.py", line 4232, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo_ce_16/odoo/fields.py", line 98, in determine
    return needle(*args)
  File "/opt/odoo/odoo_ce_16/odoo/addons/base/models/ir_actions.py", line 242, in _compute_search_view
    fvg = self.env[act.res_model].get_view(act.search_view_id.id, 'search')
  File "/opt/odoo/odoo_ce_16/odoo/api.py", line 550, in __getitem__
    return self.registry[model_name](self, (), ())
  File "/opt/odoo/odoo_ce_16/odoo/modules/registry.py", line 190, in __getitem__
    return self.models[model_name]
KeyError: 'dms.file'

The above server error caused the following client error:
RPC_ERROR://localhost:8003/web/assets/4773-df5ea47/web.assets_backend.min.js:985:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8003/web/assets/4773-df5ea47/web.assets_backend.min.js:993:13)   how to resolve this issue
