### ISSUE TITLE
POS : scanner is blocked while scanning product on the ticket page 

### ISSUE THREAD

**Issue by tglukhov** [odoo/odoo#30848]
Hello, 
Can you help me with this issue please? 

Impacted versions: Odoo v10

Steps to reproduce: 
In Point of Sale with POSBox connected: 
Seize products then pay them (no matter the way of payment). 
On the ticket screen without making "Next Order" scan another product with barcode scanner. 

Current behavior:
Error message, scanner is blocked, need to restart the page. Order is gone.

Uncaught Error: Finalized Order cannot be modified
http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:209
Retraçage :
Error: Finalized Order cannot be modified
    at child.assert_editable (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:209:127)
    at child.add_product (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:216:6)
    at child.scan_product (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:142:343)
    at Class.barcode_product_action (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:338:616)
    at Class.scan (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:308:144)
    at Object.<anonymous> (http://easycaisse.easypme.com/web/content/1933-9327c7c/point_of_sale.assets.js:310:6)
    at Object.<anonymous> (http://easycaisse.easypme.com/web/content/1666-977dcc2/web.assets_common.js:802:681)
    at fire (http://easycaisse.easypme.com/web/content/1666-977dcc2/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://easycaisse.easypme.com/web/content/1666-977dcc2/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) (http://easycaisse.easypme.com/web/content/1666-977dcc2/web.assets_common.js:803:56)

Expected behavior:
Nothing happens 

Video/Screenshot link (optional):
![screenshot from 2019-02-05 17-03-11](https://user-images.githubusercontent.com/45606959/52318331-05134f80-2968-11e9-8017-372300a3525d.png)

**Comment by cvinh** [comment]
Please test it in runbot

**Comment by cvinh** [comment]
@tglukhov how about v11 and v12 ? Thanks

**Comment by tglukhov** [comment]
Here is solution:
[https://github.com/invitu/odoo/commit/8fd5358878b591f01d9f672d6bf6730aff8f7d3c](url)
the issue is the same for Odoo V11 & V12 (runbot too)
thanks, the issue can be closed.

**Comment by cvinh** [comment]
@tglukhov do a PR please
