### ISSUE TITLE
[BUG][11.0] web: strange behavior on two imbricate One2many fields

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30970]
Impacted versions:
11.0 and maybe oter

Steps to reproduce:
Update the view "product.template.supplier.form.inherit" by this on runbot (http://444954-11-0-4e75b1.runbot13.odoo.com/web)
```xml
<?xml version="1.0"?>
<data><page name="sales" position="after">
                    <page string="Purchase" name="purchase" attrs="{'invisible': [('purchase_ok','=',False)]}">
                        <group string="Vendors" name="vendors" attrs="{'invisible': [('product_variant_count','&gt;',1)]}">
                            <field name="seller_ids" context="{'default_product_tmpl_id':context.get('product_tmpl_id',active_id), 'product_template_invisible_variant': True}" nolabel="1">
                              <tree editable="top">
                                    <field name="sequence" widget="handle"/>
                                    <field name="name"/>
                                    <field name="product_id" invisible="context.get('product_template_invisible_variant', False)" groups="product.group_product_variant"/>
                                    <field name="product_tmpl_id" string="Product" invisible="context.get('visible_product_tmpl_id', True)"/>
                                    <field name="min_qty"/>
                                    <field name="price" string="Price"/>
                                    <field name="delay"/>
                                    <field name="date_start"/>
                                    <field name="date_end"/>
                                </tree>
                            </field>
                        </group>
                        <group string="Vendors" name="variant_vendors" attrs="{'invisible': [('product_variant_count','&lt;=',1)]}">
                            <field name="variant_seller_ids" context="{'default_product_tmpl_id': context.get('product_tmpl_id', active_id)}" nolabel="1"/>
                        </group>
                    </page>
                </page>
                <group name="invoicing" position="inside">
                    <group string="Purchase Bills" name="bill" attrs="{'invisible': [('purchase_ok','=',False)]}" groups="purchase.group_purchase_manager">
                        <field name="purchase_method" widget="radio"/>
                    </group>
                </group>
                <group name="purchase_warning" position="replace">
                    <group string="Warning when Purchasing this Product" groups="purchase.group_warning_purchase">
                        <field name="purchase_line_warn" nolabel="1"/>
                        <field name="purchase_line_warn_msg" colspan="3" nolabel="1" attrs="{'required':[('purchase_line_warn','!=','no-message')],'readonly':[('purchase_line_warn','=','no-message')], 'invisible':[('purchase_line_warn','=','no-message')]}"/>
                    </group>
                </group>
                <group name="description" position="inside">
                    <group string="Description for Vendors" attrs="{'invisible': [('purchase_ok','=',False)]}">
                       <field name="description_purchase" nolabel="1" placeholder="This note will show up on purchase orders."/>
                    </group>
                </group>
            </data>
```
Go to manufacture/
Create new bill of material.
Add a new line
write a unknow product (exemple `cdcsdqcq`)
select "Create and Edit"
Issue : try to a add a supplier Info in the Purcase Page

```
Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/base/res/res_partner.py", line 588, in name_get
    name = partner.name or ''
  File "/data/build/odoo/fields.py", line 931, in __get__
    self.determine_value(record)
  File "/data/build/odoo/fields.py", line 1032, in determine_value
    record._prefetch_field(self)
  File "/data/build/odoo/models.py", line 2651, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/data/build/odoo/models.py", line 2591, in read
    self._read_from_database(stored, inherited)
  File "/data/build/odoo/models.py", line 2714, in _read_from_database
    cr.execute(query_str, params)
  File "/data/build/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/data/build/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "cdcsdqcq"
LINE 16: ...description"."res_id") WHERE "res_partner".id IN ('cdcsdqcq'...
```

Note : if you make te same thing without type the unkonw product, there is no issue.

Info:
In the `name_get` function if you put `print(self)`, you see `res.partner('cdcsdqcq')`.

This issue is generic

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=aUwocTUWcxI

@nim-odoo @rco-odoo 

Regards

**Comment by Boudmir-Ibrahim** [comment]
Hi @fmdl ,

This is not reproducible in V11. I followed your steps and my bill of materials is successfully created.
Can you check again in runbot ?
![bills](https://user-images.githubusercontent.com/43453694/52528112-c964e680-2cd5-11e9-8361-d91a65d3a417.png)
