### ISSUE TITLE
ValueError: Field `website_published` does not exist

### ISSUE THREAD

**Issue by OLPHVER** [odoo/odoo#31005]
Impacted versions: Latest nightly (12.0.20190211)

Steps to reproduce: Installed Odoo and the following apps: CRM, Website, Project, Invoicing, Sales, Notes, Purchase, Employees, Expenses, Contacts, Discuss and Calendar, then created two employees, some expenses, started to create website pages and then error occured

Current behavior: Can't open contacts app

Expected behavior: Opening the contact app should work

Video/Screenshot link (optional):

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in call_kw
>     return _call_kw_model(method, model, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 718, in _call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/models.py", line 1376, in load_views
>     for [v_id, v_type] in views
>   File "/usr/lib/python3/dist-packages/odoo/models.py", line 1376, in <dictcomp>
>     for [v_id, v_type] in views
>   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
>     res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
>   File "/usr/lib/python3/dist-packages/odoo/models.py", line 1462, in fields_view_get
>     xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1095, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
>     raise ValueError(message)
> ValueError: Field `website_published` does not exist
> 
> Error context:
> View `res.partner.form`
> [view_id: 113, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by OLPHVER** [comment]
Hi Pedro.

I have been able to reproduce the error now, I have been working on this the whole morning.

First I attempted to install the **Contact Form** app for the website, which gave me the following error:

`
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fe04811b730>, 'website.contactus')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1377, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1366, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: website.contactus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 649, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 740, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 746, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1377, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1366, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: website.contactus" while parsing None:3, near
<data name="Contact Form" inherit_id="website.contactus" customize_show="True">
            <xpath expr="//div[@name='mail_button']" position="replace">
                <div>
                    <form action="/website_form/" method="post" data-model_name="crm.lead" data-success_page="/contactus-thank-you" class="s_website_form container-fluid mt32" enctype="multipart/form-data" data-editable-form="false">
                        <div class="form-group row form-field o_website_form_required_custom">
                            <label class="col-lg-3 col-md-4 col-form-label" for="contact_name">Your Name</label>
                            <div class="col-lg-7 col-md-8">
                                <input type="text" class="form-control o_website_form_input" name="contact_name" t-att-value="request.params.get('contact_name', '')" required=""/>
                            </div>
                        </div>
                        <div class="form-group row form-field">
                            <label class="col-lg-3 col-md-4 col-form-label" for="phone">Phone Number</label>
                            <div class="col-lg-7 col-md-8">
                                <input type="text" class="form-control o_website_form_input" name="phone" t-att-value="request.params.get('phone', '')"/>
                            </div>
                        </div>
                        <div class="form-group row form-field o_website_form_required_custom">
                            <label class="col-lg-3 col-md-4 col-form-label" for="email_from">Email</label>
                            <div class="col-lg-7 col-md-8">
                                <input type="text" class="form-control o_website_form_input" name="email_from" required="" t-att-value="request.params.get('email_from', '')"/>
                            </div>
                        </div>
                        <div class="form-group row form-field o_website_form_required_custom">
                            <label class="col-lg-3 col-md-4 col-form-label" for="partner_name">Your Company</label>
                            <div class="col-lg-7 col-md-8">
                                <input type="text" class="form-control o_website_form_input" name="partner_name" required="" t-att-value="request.params.get('partner_name', '')"/>
                            </div>
                        </div>
                        <div class="form-group row form-field o_website_form_required">
                            <label class="col-lg-3 col-md-4 col-form-label" for="name">Subject</label>
                            <div class="col-lg-7 col-md-8">
                                <input type="text" class="form-control o_website_form_input" name="name" required="" t-att-value="request.params.get('name', '')"/>
                            </div>
                        </div>
                        <div class="form-group row form-field o_website_form_required_custom">
                            <label class="col-lg-3 col-md-4 col-form-label" for="description">Your Question</label>
                            <div class="col-lg-7 col-md-8">
                                <textarea class="form-control o_website_form_input" name="description" required=""><t t-esc="request.params.get('description', '')"/></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="offset-lg-3 offset-md-4 col-md-8 col-lg-7">
                                <a href="#" role="button" class="btn btn-primary btn-lg o_website_form_send">Send</a>
                                <span id="o_website_form_result"/>
                            </div>
                        </div>
                    </form>
                </div>
			</xpath>
		</data>
`

After this error I can't access the contacts anymore, I am receiving the error quoted in my initial message.

**Comment by OLPHVER** [comment]
Running a manual upgrade of the Website app helped resolving the issue. The problem was that the contactus page was missing, an upgrade restored that page.
