### ISSUE TITLE
[10.0, 11.0, 12.0] Framework: adding computed fields on pivot reports results in tracebacks

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#31063]
Impacted versions: 10.0, 11.0, 12.0 (fully tested all cases on 11.0)

Steps to reproduce:
1. Add a custom field to the `sale.order` report which has a `compute` and is not stored. For example:
```
class SaleOrder(models.Model):
    _inherit = 'sale.order'
    gross_margin = fields.Monetary(string='Gross margin', compute='_compute_gross_margin', digits=dp.get_precision('Account')

    @api.multi
    def _compute_gross_margin(self):
        for order in self:
            order.gross_margin = 10 # Just hardcoded for easy reproducability
```

2. Inherit the `sale.report` model to add a custom field to the sale report available from Sales > Reporting > Sales:
```
# -*- coding: utf-8 -*-
from odoo import tools
from odoo import models, fields, api


class SaleReport(models.Model):
    _inherit = 'sale.report'

    gross_margin = fields.Float('Gross margin', readonly=True)

    def init(self):
        return super(SaleReport, self).init()

    def _select(self):
        return super(SaleReport, self)._select() + ", s.gross_margin as gross_margin"

    def _group_by(self):
        return super(SaleReport, self)._group_by() + ", s.gross_margin"

    def _from(self):
        return super(SaleReport, self)._from()

```

3. Install this module (or update it) and you'll see a traceback in the logs:

```
Traceback (most recent call last):
  File "/odoo11community/odoo11community-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo11community/odoo11community-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo11community/odoo11community-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo11community/odoo11community-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo11community/odoo11community-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo11community/odoo11community-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo11community/odoo11community-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo11community/odoo11community-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo11community/odoo11community-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo11community/odoo11community-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo11community/odoo11community-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo11community/odoo11community-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo11community/odoo11community-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/odoo11community/odoo11community-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo11community/odoo11community-server/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo11community/odoo11community-server/odoo/addons/base/module/module.py", line 543, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo11community/odoo11community-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo11community/odoo11community-server/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo11community/odoo11community-server/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo11community/odoo11community-server/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo11community/odoo11community-server/odoo/modules/registry.py", line 307, in init_models
    model.init()
  File "/odoo11/custom/addons/custom/custom_sales_flow/models/sale_report.py", line 13, in init
    return super(SaleReport, self).init()
  File "/odoo11community/odoo11community-server/addons/sale/report/sale_report.py", line 131, in init
    )""" % (self._table, self._select(), self._from(), self._group_by()))
  File "/odoo11community/odoo11community-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo11community/odoo11community-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column s.gross_margin does not exist
LINE 47:         , s.gross_margin as gross_margin, s.gross_margin_fac...
```
Current behavior: Traceback on the custom field `gross_margin` because the field on the model `sale.report` is a readonly which links back to the field `gross_margin` on the `sale.order` model, which is a computed field. If a field does not have `store=True` when it is a `compute` the pivot view will fail.
If you start editing and tinkering with it you can even be thrown out of your database and be locked out untill you fixed it (just didn't find a reproducable way directly).

Expected behavior:
There is a clear error in the logfile and/or a dialog in the screen stating something along the lines of:
```
The field 'gross_margin' on the table 'sale.order' is a computed field which is not stored. Computed fields that are not stored cannot be used in pivot views.
```

Video/Screenshot link (optional):

**Comment by Boudmir-Ibrahim** [comment]
Hi @Yenthe666 , 
You can't use a non stored computed field in a SQL request as you clearly mentioned. 
Can you enlighten more how do you expect the logs should look like ? 
Regards.

**Comment by Yenthe666** [comment]
@Boudmir-Ibrahim yeah I'm aware but it is very easy to miss and figuring it out (plus the tracebacks) can cost you quite some time. As I stated, a message something like this should be neat:
"The field 'gross_margin' on the table 'sale.order' is a computed field which is not stored. Computed fields that are not stored cannot be used in pivot views."

**Comment by Boudmir-Ibrahim** [comment]
@Yenthe666 , 
I think, from a developer's point of view, the message in the logs is readable and supposedly understandable enough to deduce that the field is not stored in the database. This is purely technical thing to solve. 
I don't think it is mandatory to be adjusted to suit the client understanding and be considered as an issue... But still, a nice to have !

**Comment by mart-e** [comment]
Hi,
Sorry but I agree with @Boudmir-Ibrahim and I have to reject that one
The pivot table is to aggregate data stored in database. It is not even linked to your computed field but, in point 2, you are modifying the SQL query to reference to column that is not present in the database (it is not odoo-related, purely SQL here).
You would get the same error if you made a typo in your field name, but would not call it an ORM bug ;-)
As we are bypassing the ORM to write direct SQL queries, the ORM is kind of powerless here...

**Comment by madux** [comment]
Hi Yenthe, kindly add this attribute,  'store=True '
That works like magic!
