### ISSUE TITLE
Cannot give a Portal Access Management to customer in Odoo 12

### ISSUE THREAD

**Issue by akshayjangra** [odoo/odoo#31087]
I am facing following error on "Grant Portal Access" to a contact.
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/addons/portal/wizard/portal_wizard.py", line 59, in action_apply
    self.user_ids.action_apply()
  File "/opt/odoo12/odoo/addons/portal/wizard/portal_wizard.py", line 138, in action_apply
    user_portal = wizard_user.sudo().with_context(company_id=company_id)._create_user()
  File "/opt/odoo12/odoo/addons/portal/wizard/portal_wizard.py", line 168, in _create_user
    'company_ids': [(6, 0, [company_id])],
  File "/opt/odoo12/odoo/addons/auth_signup/models/res_users.py", line 138, in _create_user_from_template
    raise ValueError(_('Signup: invalid template user'))
ValueError: Signup: invalid template user`
```

**Comment by Yenthe666** [comment]
Hi,

This comes from the following piece of code:
https://github.com/odoo/odoo/blob/ef03db9edd9472201cb2c08a32d20ff0f33a5fdf/addons/auth_signup/models/res_users.py#L134-L138

It looks like you've deleted the parameter which is used to assign the right template user. Can you check?

**Comment by sswapnesh** [comment]
I got similar error with another template on Odoo website. Not sure where to submit🤔

**Comment by mart-e** [comment]
Probably deleted the template user. Unfortunately, it is not very easy to set it back (very technical hidden feature)
@tde-banana-odoo another record that should not be deletable or find a fallback?

**Comment by sswapnesh** [comment]
Same case on odoo website for Slide share feature (email template does not exists with that xml id)

**Comment by sswapnesh** [comment]
Hello @mart-e 
Do we have any plan to Prevent Unlink of these types of records linked to specific xml-ids ? (Similar to `noupdate="1"` )

**Comment by mart-e** [comment]
@sswapnesh this is a recurring discussion. We often talk about adding this at  the ORM level but in the end, it is often weak functional code that should be improved and not rely on master data.

**Comment by pydasuresh** [comment]
**It is simple**

Activate developer Mode in settings page.

Go to  settings -> users & companies ->  users , 

and filter inactive users.

Check if " Portal User Template "  is exists or not, if not 
Just create

 one user template  with name " Portal User Template " and make it inactive. 


![Capture22](https://user-images.githubusercontent.com/5470717/62125633-508d3180-b2eb-11e9-95af-7efa7a9cbf21.JPG)

and find the 'id'  of the portal user template in URL , it is number 

then Goto Settings-> technical-> system parameters 

Then Find  base.template_portal_user_id if not exists cteate that feild and add the id  value of  portal user template

**Comment by mart-e** [comment]
Closing as no news from initial reporter and most likely found the reason (user deleted).

**Comment by hawadet** [comment]
> Closing as no news from initial reporter and most likely found the reason (user deleted).

when Grant portal access for contact i find this message : The user cannot have more than one user types.
