### ISSUE TITLE
Stock Picking - Mark as Todo - Memory error when having a very large number of moves

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#31220]
Impacted versions:

11.0

Steps to reproduce:

* Create a product tracked by serial number
* Create 10+ millions tracked serial numbers
* Create 10+ millions stock moves
* Go to Inventory > Delivery Order (3 Dots) > Planned Transfer
* Select the product and set quantity to 1
* Save and Mark as Todo

Current behavior:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 939, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 55

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/stock/models/stock_picking.py", line 508, in create
    res = super(Picking, self).create(vals)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 238, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3394, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3551, in _create
    self.recompute()
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4931, in recompute
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4931, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 943, in __get__
    self.determine_value(record)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1030, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1010, in compute_value
    self._compute_value(records)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1003, in _compute_value
    self.compute(records)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 584, in _compute_related
    values = list(others)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4659, in __iter__
    yield self._browse((id,), self.env, self._prefetch, False)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4342, in _browse
    records.env = env
MemoryError
```

Expected behavior:

The picking and its moves are confirmed.

Further information:

All the time and resources is taken running queries like this one:

```
SELECT "stock_move"."id" as "id","stock_move"."unbuild_id" as "unbuild_id","stock_move"."product_id" as "product_id","stock_move"."sequence" as "sequence","stock_move"."state" as "state","stock_move"."priority" as "priority","stock_move"."group_id" as "group_id","stock_move"."warehouse_id" as "warehouse_id","stock_move"."remaining_qty" as "remaining_qty","stock_move"."write_uid" as "write_uid","stock_move"."write_date" as "write_date","stock_move"."purchase_line_id" as "purchase_line_id","stock_move"."picking_id" as "picking_id","stock_move"."create_date" as "create_date","stock_move"."price_unit" as "price_unit","stock_move"."consume_unbuild_id" as "consume_unbuild_id","stock_move"."product_uom" as "product_uom","stock_move"."ordered_qty" as "ordered_qty","stock_move"."rule_id" as "rule_id","stock_move"."remaining_value" as "remaining_value","stock_move"."created_production_id" as "created_production_id","stock_move"."created_purchase_line_id" as "created_purchase_line_id","stock_move"."origin_returned_move_id" as "origin_returned_move_id","stock_move"."date" as "date","stock_move"."is_done" as "is_done","stock_move"."procure_method" as "procure_method","stock_move"."operation_id" as "operation_id","stock_move"."product_qty" as "product_qty","stock_move"."push_rule_id" as "push_rule_id","stock_move"."name" as "name","stock_move"."production_id" as "production_id","stock_move"."sale_line_id" as "sale_line_id","stock_move"."date_expected" as "date_expected","stock_move"."additional" as "additional","stock_move"."to_refund" as "to_refund","stock_move"."product_uom_qty" as "product_uom_qty","stock_move"."workorder_id" as "workorder_id","stock_move"."product_packaging" as "product_packaging","stock_move"."picking_type_id" as "picking_type_id","stock_move"."origin" as "origin","stock_move"."location_dest_id" as "location_dest_id","stock_move"."scrapped" as "scrapped","stock_move"."company_id" as "company_id","stock_move"."raw_material_production_id" as "raw_material_production_id","stock_move"."restrict_partner_id" as "restrict_partner_id","stock_move"."partner_id" as "partner_id","stock_move"."note" as "note","stock_move"."value" as "value","stock_move"."location_id" as "location_id","stock_move"."inventory_id" as "inventory_id","stock_move"."reference" as "reference","stock_move"."create_uid" as "create_uid","stock_move"."propagate" as "propagate","stock_move"."unit_factor" as "unit_factor","stock_move"."bom_line_id" as "bom_line_id" FROM "stock_move" WHERE "stock_move".id IN (501345, 501346, 501347, 501348, 501349, 501350, 501351, 501352, 501353, 501354, 501355, 501356, 501357, 501358, 501359, 501360, 501361, 501362, 501363, 501364, 501365, 501366, 501367, 501368, 501369, 501370, 501371, 501372, 501373, 501374, 501375, 501376, 501377, 501378, 501379, 501380, 501381, 501382, 501383, 501384, 501385, 501386, 501387, 501388, 501389, 501390, 501391, 501392, 501393, 501394, 501395, 501396, 501397, 501398, 501399, 501400, 501401, 501402, 501403, 501404, 501405, 501406, 501407, 501408, 501409, 501410, 501411, 501412, 501413, 501414, 501415, 501416, 501417, 501418, 501419, 501420, 501421, 501422, 501423, 501424, 501425, 501426, 501427, 501428, 501429, 501430, 501431, 501432, 501433, 501434, 501435, 501436, 501437, 501438, 501439, 501440, 501441, 501442, 501443, 501444, 501445, 501446, 501447, 501448, 501449, 501450, 501451, 501452, 501453, 501454, 501455, 501456, 501457, 501458, 501459, 501460, 501461, 501462, 501463, 501464, 501465, 501466, 501467, 501468, 501469, 501470, 501471, 501472, 501473, 501474, 501475, 501476, 501477, 501478, 501479, 501480, 501481, 501482, 501483, 501484, 501485, 501486, 501487, 501488, 501489, 501490, 501491, 501492, 501493, 501494, 501495, 501496, 501497, 501498, 501499, 501500, 501501, 501502, 501503, 501504, 501505, 501506, 501507, 501508, 501509, 501510, 501511, 501512, 501513, 501514, 501515, 501516, 501517, 501518, 501519, 501520, 501521, 501522, 501523, 501524, 501525, 501526, 501527, 501528, 501529, 501530, 501531, 501532, 501533, 501534, 501535, 501536, 501537, 501538, 501539, 501540, 501541, 501542, 501543, 501544, 501545, 501546, 501547, 501548, 501549, 501550, 501551, 501552, 501553, 501554, 501555, 501556, 501557, 501558, 501559, 501560, 501561, 501562, 501563, 501564, 501565, 501566, 501567, 501568, 501569, 501570, 501571, 501572, 501573, 501574, 501575, 501576, 501577, 501578, 501579, 501580, 501581, 501582, 501583, 501584, 501585, 501586, 501587, 501588, 501589, 501590, 501591, 501592, 501593, 501594, 501595, 501596, 501597, 501598, 501599, 501600, 501601, 501602, 501603, 501604, 501605, 501606, 501607, 501608, 501609, 501610, 501611, 501612, 501613, 501614, 501615, 501616, 501617, 501618, 501619, 501620, 501621, 501622, 501623, 501624, 501625, 501626, 501627, 501628, 501629, 501630, 501631, 501632, 501633, 501634, 501635, 501636, 501637, 501638, 501639, 501640, 501641, 501642, 501643, 501644, 501645, 501646, 501647, 501648, 501649, 501650, 501651, 501652, 501653, 501654, 501655, 501656, 501657, 501658, 501659, 501660, 501661, 501662, 501663, 501664, 501665, 501666, 501667, 501668, 501669, 501670, 501671, 501672, 501673, 501674, 501675, 501676, 501677, 501678, 501679, 501680, 501681, 501682, 501683, 501684, 501685, 501686, 501687, 501688, 501689, 501690, 501691, 501692, 501693, 501694, 501695, 501696, 501697, 501698, 501699, 501700, 501701, 501702, 501703, 501704, 501705, 501706, 501707, 501708, 501709, 501710, 501711, 501712, 501713, 501714, 501715, 501716, 501717, 501718, 501719, 501720, 501721, 501722, 501723, 501724, 501725, 501726, 501727, 501728, 501729, 501730, 501731, 501732, 501733, 501734, 501735, 501736, 501737, 501738, 501739, 501740, 501741, 501742, 501743, 501744, 501745, 501746, 501747, 501748, 501749, 501750, 501751, 501752, 501753, 501754, 501755, 501756, 501757, 501758, 501759, 501760, 501761, 501762, 501763, 501764, 501765, 501766, 501767, 501768, 501769, 501770, 501771, 501772, 501773, 501774, 501775, 501776, 501777, 501778, 501779, 501780, 501781, 501782, 501783, 501784, 501785, 501786, 501787, 501788, 501789, 501790, 501791, 501792, 501793, 501794, 501795, 501796, 501797, 501798, 501799, 501800, 501801, 501802, 501803, 501804, 501805, 501806, 501807, 501808, 501809, 501810, 501811, 501812, 501813, 501814, 501815, 501816, 501817, 501818, 501819, 501820, 501821, 501822, 501823, 501824, 501825, 501826, 501827, 501828, 501829, 501830, 501831, 501832, 501833, 501834, 501835, 501836, 501837, 501838, 501839, 501840, 501841, 501842, 501843, 501844, 501845, 501846, 501847, 501848, 501849, 501850, 501851, 501852, 501853, 501854, 501855, 501856, 501857, 501858, 501859, 501860, 501861, 501862, 501863, 501864, 501865, 501866, 501867, 501868, 501869, 501870, 501871, 501872, 501873, 501874, 501875, 501876, 501877, 501878, 501879, 501880, 501881, 501882, 501883, 501884, 501885, 501886, 501887, 501888, 501889, 501890, 501891, 501892, 501893, 501894, 501895, 501896, 501897, 501898, 501899, 501900, 501901, 501902, 501903, 501904, 501905, 501906, 501907, 501908, 501909, 501910, 501911, 501912, 501913, 501914, 501915, 501916, 501917, 501918, 501919, 501920, 501921, 501922, 501923, 501924, 501925, 501926, 501927, 501928, 501929, 501930, 501931, 501932, 501933, 501934, 501935, 501936, 501937, 501938, 501939, 501940, 501941, 501942, 501943, 501944, 502089, 502090, 502091, 502092, 502093, 502094, 502107, 502108, 502109, 502110, 502111, 502112, 502113, 502114, 502115, 502116, 502117, 502118, 502119, 502120, 502121, 502122, 502123, 502124, 502125, 502126, 502127, 502128, 502129, 502130, 502131, 502132, 502133, 502134, 502135, 502136, 502137, 502138, 502139, 502140, 502141, 502142, 502143, 502144, 502145, 502146, 502147, 502148, 502149, 502150, 502151, 502152, 502153, 502154, 502155, 502156, 502157, 502158, 502159, 502160, 502161, 502162, 502163, 502164, 502165, 502166, 502167, 502168, 502169, 502170, 502171, 502172, 502173, 502174, 502175, 502176, 502177, 502178, 502179, 502180, 502181, 502182, 502183, 502184, 502185, 502186, 502187, 502188, 502189, 502190, 502191, 502192, 502193, 502194, 502195, 502196, 502197, 502198, 502199, 502200, 502201, 502202, 502203, 502204, 502205, 502206, 502207, 502208, 502209, 502210, 502211, 502212, 502213, 502214, 502215, 502216, 502217, 502218, 502219, 502220, 502221, 502222, 502223, 502224, 502225, 502226, 502227, 502228, 502229, 502230, 502231, 502232, 502233, 502234, 502235, 502236, 502237, 502238, 502239, 502240, 502241, 502242, 502243, 502244, 502245, 502246, 502247, 502248, 502249, 502250, 502251, 502252, 502253, 502254, 502255, 502256, 502257, 502258, 502259, 502260, 502261, 502262, 502263, 502264, 502265, 502266, 502267, 502268, 502269, 502270, 502271, 502272, 502273, 502274, 502275, 502276, 502277, 502278, 502279, 502280, 502281, 502282, 502283, 502284, 502285, 502286, 502287, 502288, 502289, 502290, 502291, 502292, 502293, 502294, 502295, 502296, 502297, 502298, 502299, 502300, 502301, 502302, 502303, 502304, 502305, 502306, 502307, 502308, 502309, 502310, 502311, 502312, 502313, 502314, 502315, 502316, 502317, 502318, 502319, 502320, 502321, 502322, 502323, 502324, 502325, 502326, 502327, 502328, 502329, 502330, 502331, 502332, 502333, 502334, 502335, 502336, 502337, 502338, 502339, 502340, 502341, 502342, 502343, 502344, 502345, 502346, 502347, 502348, 502349, 502350, 502351, 502352, 502353, 502354, 502355, 502356, 502357, 502358, 502359, 502360, 502361, 502362, 502363, 502364, 502365, 502366, 502367, 502368, 502369, 502370, 502371, 502372, 502373, 502374, 502375, 502376, 502377, 502378, 502379, 502380, 502381, 502382, 502383, 502384, 502385, 502386, 502387, 502388, 502389, 502390, 502391, 502392, 502393, 502394, 502395, 502396, 502397, 502398, 502399, 502403, 502404, 502405, 502406, 502407, 502408, 502409, 502410, 502411, 502412, 502413, 502414, 502415, 502416, 502417, 502418, 502419, 502420, 502421, 502422, 502423, 502424, 502425, 502426, 502427, 502428, 502429, 502430, 502431, 502432, 502433, 502434, 502435, 502436, 502437, 502438, 502439, 502440, 502441, 502442, 502443, 502444, 502445, 502446, 502447, 502448, 502449, 502450, 502451, 502452, 502453, 502454, 502455, 502456, 502457, 502458, 502459, 502460, 502461, 502462, 502463, 502464, 502465, 502466, 502467, 502468, 502469, 502470, 502471, 502472, 502473, 502474, 502475, 502476, 502477, 502478, 502479, 502480, 502481, 502482, 502483, 502484, 502485, 502486, 502487, 502488, 502489, 502490, 502491, 502492, 502493, 502494, 502495, 502496, 502497, 502498, 502499, 502500, 502501, 502502, 502503)
```

**Comment by max3903** [comment]
Enterprise Ticket #1942509

**Comment by C3POdoo** [comment]
Dear @max3903,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1942509 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.
