### ISSUE TITLE
[11.0, 12.0] @api.profile fails with ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#31278]
Impacted versions: 11.0, 12.0

Steps to reproduce:
1. Create a function and add the profiler to it. An example:
```
from odoo.tools.profiler import profile

    @profile('/tmp/test.profile')
    @api.multi
    def process_file(self, filename):
        print('we would do something here')
```
2. Update and restart your Odoo

Current behavior:
```
Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo12/odoo12-server/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/odoo12/odoo12-server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>
  File "/odoo12/custom/addons/abc/abc_customisations/models/__init__.py", line 8, in <module>
    from . import account_invoice_line
  File "/odoo12/custom/addons/abc/abc_customisations/models/account_invoice_line.py", line 15, in <module>
    class AccountInvoiceLine(models.Model):
  File "/odoo12/custom/addons/abc/abc_customisations/models/account_invoice_line.py", line 82, in AccountInvoiceLine
    @profile('tmp/test.profile')
  File "/odoo12/odoo12-server/odoo/tools/profiler.py", line 197, in profile
    wrapper = decorator(_odooProfile, method)
  File "/usr/local/lib/python3.6/dist-packages/decorator.py", line 242, in decorator
    return decorate(_func, caller)
  File "/usr/local/lib/python3.6/dist-packages/decorator.py", line 232, in decorate
    evaldict, __wrapped__=func)
  File "/usr/local/lib/python3.6/dist-packages/decorator.py", line 212, in create
    name, rest = obj.strip().split('(', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Expected behavior:
The profiler works and outputs data to the file you've specified. It does work with `@api.profile` as output is directed to the logfile and not written into a file.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Gorash is there any chance you could look at this profiler issue? Perhaps it is related to Python 3.6?

**Comment by sswapnesh** [comment]
Maybe because of typo tmp/test.profile - - > /tmp/test.profile

**Comment by Yenthe666** [comment]
Hmm I think I tested both but I will double check tommorow to be absolutely sure.

**Comment by Yenthe666** [comment]
Tested both with `/tmp/test.profile` and `tmp/test.profile`, both the same result.

**Comment by danhvophuong** [comment]
Hi, do we have any update on it?

**Comment by Yenthe666** [comment]
@danhvophuong are you facing the same issue? Nobody looked further on my report so I consider it open & unhandled still.

**Comment by danhvophuong** [comment]
@Yenthe666 Yes, the same issue as you. It works fine with @api.profile as directed output, but not a file

**Comment by Yenthe666** [comment]
As nobody seems to care here I've reported it through an official enterprise license. The ticket ID is 2038941

**Comment by mreficent** [comment]
can be closed

**Comment by Yenthe666** [comment]
Yep indeed. I'd rather see a good fix than just adding an extra line to the docs though. One of those functions should probably be renamed.
