### ISSUE TITLE
Can not login/reset admin user

### ISSUE THREAD

**Issue by Ducnv5** [odoo/odoo#31418]
Impacted versions: 12

Steps to reproduce:

Current behavior:
When I login with admin user, it's always fail. The odoo.log file show that 

> 
2019-02-26 09:00:53,110 2704 ERROR Odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\site-packages\werkzeug\serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\site-packages\werkzeug\serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\server.py", line 350, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\site-packages\werkzeug\wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 1486, in dispatch
    result = ir_http._dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\auth_signup\models\ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web_editor\models\ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\http_routing\models\ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\utm\models\ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\website\models\ir_http.py", line 177, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\utm\models\ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 1076, in content_image
    default_mimetype='image/png', related_id=related_id, access_mode=access_mode, access_token=access_token)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 435, in binary_content
    env=env)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\website\models\ir_http.py", line 260, in binary_content
    access_mode=access_mode, env=env)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_http.py", line 365, in binary_content
    mimetype = guess_mimetype(base64.b64decode(content), default=default_mimetype)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
> 
But it's ok with other user
I tried to change admin password in table "res_users" (encrypted by passlib CryptContext(['pbkdf2_sha512']) ) but the bug still happen.
Expected behavior:

Video/Screenshot link (optional):

**Comment by Ducnv5** [comment]
I followed the link https://github.com/odoo/odoo/issues/9806.
But in my db, there is no column named "password_crypt", all columns are "id, active, login, password, company_id, partner_id, create_date, signature, action_id, share, create_uid, write_uid, write_date, alias_id, notification_type, odoobot_state, sale_team_id, target_sales_won, target_sales_done, website_id, employee_id, oauth_provider_id, oauth_uid, oauth_access_token, pos_security_pin"
and also no "openerp-server.conf" file

**Comment by pedrobaeza** [comment]
Have you previously manipulated that password through Postgres or similar?

**Comment by Ducnv5** [comment]
No, I haven't do it before the bug happen.
I installed MS Office in server and maybe after that, the bug happen. I uninstalled MS Office but only the user which are not admin can login, the admin still can not.

**Comment by pedrobaeza** [comment]
But on v12, there's no admin at all... You become superuser through an option. Are you talking about that?

**Comment by pedrobaeza** [comment]
The backtrace seems incomplete any way.

**Comment by Ducnv5** [comment]
Yes I changed password of superuser

**Comment by pedrobaeza** [comment]
Sorry, then this is a bad manipulation, and you should ask for help on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
