### ISSUE TITLE
Traceback when registering payment for invoice from tree view and amount is 0

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#31411]
Impacted versions:
- 12.0

Steps to reproduce:
- Create an invoice
- Validate the invoice
- On the tree view, check the invoice and click Actions -> Register payment
- Leave the amount empty or set it to zero

Current behavior:
The following traceback is shown:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 5468, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/build/odoo/models.py", line 5321, in _onchange_eval
    method_res = method(self)
  File "/data/build/odoo/addons/account_check_printing/models/account_payment.py", line 30, in _onchange_amount
    super(AccountRegisterPayments, self)._onchange_amount()
  File "/data/build/odoo/addons/account/models/account_payment.py", line 202, in _onchange_amount
    jrnl_filters = self._compute_journal_domain_and_types()
  File "/data/build/odoo/addons/account/models/account_payment.py", line 188, in _compute_journal_domain_and_types
    if self.currency_id.is_zero(self.amount) and self.has_invoices:
AttributeError: 'account.register.payments' object has no attribute 'has_invoices'
```

Expected behavior:
No traceback

**Comment by luisg123v** [comment]
opw-1945142.

CC @hbto @yaniaular

**Comment by C3POdoo** [comment]
Dear @luisg123v,

_This is an automated message._
This issue is linked to the Odoo support ticket opw-1945142 that has been closed.
We hope you got an answer to your issue.

If you believe the problem is not solved yet and would like to keep this issue open, please let us know to reopen it.
