### ISSUE TITLE
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by dafaallah-exp** [odoo/odoo#31429]
I do pull last update form odoo community 11.0 , after running , I have error below :

Traceback (most recent call last):
File "/opt/server/odoo/addons/base/ir/ir_cron.py", line 223, in _process_jobs
registry[cls._name]._process_job(job_cr, job, lock_cr)
File "/opt/server/odoo/addons/base/ir/ir_cron.py", line 129, in _process_job
now = fields.Datetime.context_timestamp(cron, datetime.now())
File "/opt/server/odoo/fields.py", line 1580, in context_timestamp
tz_name = record._context.get('tz') or record.env.user.tz
File "/opt/server/odoo/fields.py", line 944, in **get**
self.determine_value(record)
File "/opt/server/odoo/fields.py", line 1055, in determine_value
self.compute_value(recs)
File "/opt/server/odoo/fields.py", line 1011, in compute_value
self._compute_value(records)
File "/opt/server/odoo/fields.py", line 999, in _compute_value
for record in records:
File "/opt/server/odoo/models.py", line 4659, in **iter**
yield self._browse((id,), self.env, self._prefetch, False)
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given
2019-02-26 12:41:33,216 4363 ERROR test2 odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'priority': 5, 'ir_actions_server_id': 78, 'create_uid': 1, 'write_date': '2019-02-21 06:13:18.376535', 'interval_number': 3, 'active': True, 'numbercall': -1, 'user_id': 1, 'nextcall': '2019-02-21 15:13:18', 'doall': False, 'create_date': '2019-02-21 06:13:18.376535', 'id': 3, 'write_uid': 1, 'interval_type': 'hours', 'cron_name': 'Update user roles'}
Traceback (most recent call last):
File "/opt/server/odoo/fields.py", line 940, in **get**
value = record.env.cache.get(record, self)
File "/opt/server/odoo/api.py", line 967, in get
value = self._data[key][field][record._ids[0]]
KeyError: 1

**Comment by Yenthe666** [comment]
@dafaallah-exp your custom scheduled action "Update user roles" is not correctly coded.

**Comment by pedrobaeza** [comment]
This is because you have a low level method overwritten, and that one has changed. Please update that cron job with latest definition.

**Comment by MathAndrews** [comment]
Hi,
