### ISSUE TITLE
Reordering Rule - Creation - Memory error when having a very large number of moves

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#31442]
Impacted versions:

11.0

Steps to reproduce:

* Create a product tracked by serial number
* Create 10+ millions tracked serial numbers
* Create 10+ millions stock moves
* Go to Inventory > Master Data > Reordering Rules
* Create a new rule for the previous product
* Save

Current behavior:

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 939, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 939, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3402, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1075, in determine_inverse
    self.inverse(records)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 598, in _inverse_related
    other[field.name] = record_value[record]
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4794, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 982, in __set__
    record.write({self.name: write_value})
  File "/opt/odoo/odoo/addons/stock/models/product.py", line 373, in write
    res = super(Product, self).write(values)
  File "/opt/odoo/odoo/addons/product/models/product.py", line 319, in write
    res = super(ProductProduct, self).write(values)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 284, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/addons/mail/models/mail_activity.py", line 343, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3271, in _write
    self.env[parent_model].browse(parent_ids).write(parent_vals)
  File "/opt/odoo/odoo/addons/stock/models/product.py", line 527, in write
    return super(ProductTemplate, self).write(vals)
  File "/opt/odoo/odoo/addons/product/models/product_template.py", line 316, in write
    res = super(ProductTemplate, self).write(vals)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 284, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/addons/mail/models/mail_activity.py", line 343, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3109, in write
    self._write(old_vals)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 3339, in _write
    self.recompute()
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4931, in recompute
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4931, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 943, in __get__
    self.determine_value(record)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1030, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1010, in compute_value
    self._compute_value(records)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1003, in _compute_value
    self.compute(records)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 586, in _compute_related
    values = [first(value[name]) for value in values]
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 586, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 943, in __get__
    self.determine_value(record)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/fields.py", line 1044, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 2621, in _prefetch_field
    records = self._in_cache_without(field)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4813, in _in_cache_without
    for record_id in self.env.cache.get_missing_ids(recs - self, field):
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4696, in __sub__
    return self.browse([id for id in self._ids if id not in other_ids])
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4361, in browse
    return self._browse(ids, self.env, prefetch)
  File "/opt/odoo/env/lib64/python3.6/site-packages/odoo-11.0-py3.6.egg/odoo/models.py", line 4348, in _browse
    prefetch[cls._name].update(ids)
MemoryError
```

Expected behavior:

The reordering rule is saved successfully.

**Comment by sle-odoo** [comment]
We have really really large customers with millions of moves and this issue was never raised. I guess if you want to handle that much records you need to have proper hardware to run Python. Anyway, we pushed a bunch of peformance improvements since v11 (even today on the RR) so i'm closing this issue.

Regards
