### ISSUE TITLE
Not able to  merge partner with it's duplicate  contact name

### ISSUE THREAD

**Issue by pja-odoo** [odoo/odoo#3154]
There is now a way of merging duplicate partners but it does not seem to work. 
When I try to merge a parent partner with his child (which is identical), it does not work.

Steps to reproduce this issue:

1> Add contact in partner with same name as a partner name.
2> Go to Sale -> Tools -> Duplicate Contacts.
3> Check name in 'Search duplicates based on duplicated data in'
4> Click on button 'Merge with manual check'
5> Select child contact in Destination Contacts and try to merge.
It's given following traceback

Traceback (most recent call last):
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/crm/base_partner_merge.py", line 737, in merge_cb
    self._merge(cr, uid, partner_ids, this.dst_partner_id, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/tools/misc.py", line 1126, in deco
    return func(_args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/crm/base_partner_merge.py", line 323, in _merge
    call_it(self._update_values)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/crm/base_partner_merge.py", line 319, in <lambda>
    context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/crm/base_partner_merge.py", line 285, in _update_values
    dst_partner.write(values)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/account_followup/account_followup.py", line 296, in write
    return super(res_partner, self).write(cr, uid, ids, vals, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/crm_profiling/crm_profiling.py", line 213, in write
    return super(partner, self).write(cr, uid, ids, vals, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/base/res/res_partner.py", line 551, in write
    result = super(res_partner, self).write(vals)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/mail/mail_thread.py", line 427, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 3660, in write
    self._write(old_vals)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 3708, in _write
    result = self._store_get_values(cr, user, ids, vals.keys(), context) or []
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 4204, in _store_get_values
    target_id_results[target_func_id_] = [i for i in store_trigger[target_ids_func_](self, cr, SUPERUSER_ID, ids, context) if i]
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/base/res/res_partner.py", line 221, in <lambda>
    'res.partner': (lambda self,cr,uid,ids,context=None: self.search(cr, uid, [('id','child_of',ids)], context=dict(active_test=False)),
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 1669, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/addons/base/res/res_partner.py", line 643, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 4518, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/models.py", line 4341, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/osv/expression.py", line 803, in parse
    dom = child_of_domain(left, ids2, model)
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/osv/expression.py", line 733, in child_of_domain
    return [(left, 'in', recursive_children(ids, left_model, parent or left_model._parent_name))]
  File "/home/bak/runbot/extra/runbot/static/build/22794-8-0-5402e3/openerp/osv/expression.py", line 732, in recursive_children

**Comment by Yenthe666** [comment]
Hi @pja-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
