### ISSUE TITLE
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by blackwaremayank** [odoo/odoo#31583]
Impacted versions: 12

Steps to reproduce: Load French_CA language.
```
Current behavior: Odoo Server Error
Traceback (most recent call last):
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/test/workspace/odoo-12E/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/test/workspace/odoo-12E/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/test/workspace/odoo-12E/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/test/workspace/odoo-12E/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/test/workspace/odoo-12E/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/test/workspace/odoo-12E/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/test/workspace/odoo-12E/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/test/workspace/odoo-12E/addons/base/wizard/base_language_install.py", line 36, in lang_install
    mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
  File "/home/test/workspace/odoo-12E/addons/base/models/ir_module.py", line 877, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/home/test/workspace/odoo-12E/addons/base/models/ir_translation.py", line 764, in load_module_terms
    tools.trans_load(self._cr, base_trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/home/test/workspace/odoo-12E/odoo/tools/translate.py", line 1011, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/home/test/workspace/odoo-12E/odoo/tools/translate.py", line 1155, in trans_load_data
    irt_cursor.finish()
  File "/home/test/workspace/odoo-12E/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/home/test/workspace/odoo-12E/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/test/workspace/odoo-12E/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

Expected behavior: Should not raise this error.
```
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mart-e have you experimented this?

**Comment by mart-e** [comment]
This can happen if you are loading translations from a pre-v12 module in version 12.0.
Check in the logs which file it was loading before the error to know the module where there is a problem.

**Comment by luisg123v** [comment]
@blackwaremayank check if this was solved with https://github.com/odoo/odoo/pull/31683

**Comment by moylop260** [comment]
You can @blackwaremayank 
Could you try using `odoo-bin --load-language=fr_CA` in order to see the real module with the error?

**Comment by blackwaremayank** [comment]
Hi @moylop260 

I'm still facing the issue when i load **fr_CA** language with **Overwrite Existing Terms**. And i also confirm that sale module has this latest update #31683.

Please find below log details which may help you to track this issue.

2019-03-09 05:38:19,290 7851 INFO test_odoo12e odoo.addons.base.models.ir_translation: module payment: loading translation file (fr_CA) for language fr_CA 
2019-03-09 05:38:19,291 7851 INFO test_odoo12e odoo.tools.translate: loading /home/bwt/workspace/odoo-12E/addons/payment/i18n/fr_CA.po 
2019-03-09 05:38:19,615 7851 INFO test_odoo12e odoo.addons.base.models.ir_translation: module sale: loading base translation file fr for language fr_CA 
2019-03-09 05:38:19,615 7851 INFO test_odoo12e odoo.tools.translate: loading /home/bwt/workspace/odoo-12E/addons/sale/i18n/fr.po 
2019-03-09 05:38:24,865 7851 ERROR test_odoo12e odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           AND noupdate IS NOT TRUE\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments)\n                            WHERE EXCLUDED.value IS NOT NULL AND EXCLUDED.value != '';\n                       "
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2019-03-09 05:38:24,865 7851 ERROR test_odoo12e odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/bwt/workspace/odoo-12E/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bwt/workspace/odoo-12E/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/bwt/workspace/odoo-12E/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/bwt/workspace/odoo-12E/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/bwt/workspace/odoo-12E/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/bwt/workspace/odoo-12E/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/bwt/workspace/odoo-12E/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/bwt/workspace/odoo-12E/addons/l10n_multilang/models/l10n_multilang.py", line 105, in lang_install
    res = super(BaseLanguageInstall, self).lang_install()
  File "/home/bwt/workspace/odoo-12E/addons/base/wizard/base_language_install.py", line 36, in lang_install
    mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
  File "/home/bwt/workspace/odoo-12E/addons/base/models/ir_module.py", line 877, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/home/bwt/workspace/odoo-12E/addons/base/models/ir_translation.py", line 764, in load_module_terms
    tools.trans_load(self._cr, base_trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/home/bwt/workspace/odoo-12E/odoo/tools/translate.py", line 1011, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/home/bwt/workspace/odoo-12E/odoo/tools/translate.py", line 1155, in trans_load_data
    irt_cursor.finish()
  File "/home/bwt/workspace/odoo-12E/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/home/bwt/workspace/odoo-12E/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/bwt/workspace/odoo-12E/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

Let me know if you still need any further information.

**Comment by luisg123v** [comment]
Hi @blackwaremayank,

I'm not able to replicate your issue. Were you able to replicate it on a recent Runbot? (after https://github.com/odoo/odoo/pull/31683)

**Comment by moylop260** [comment]
In order to see if there are duplicated items I just ran the following command:
 - `msgfmt -c ~/odoo_git/addons/sale/i18n/fr_CA.po`

 - <img width="885" alt="Screen Shot 2019-03-09 at 9 00 14 AM" src="https://user-images.githubusercontent.com/6644187/54073195-d54ab680-4249-11e9-9a14-79714a742cbf.png">

But there are not duplicated items.

Then, I just have created a new database using the modules of your logger, 
`odoo-bin -d fr_lang_test -i payment,sale --load-language=fr_CA --stop-after-init --log-level=warn`

 - <img width="1609" alt="Screen Shot 2019-03-09 at 8 58 16 AM" src="https://user-images.githubusercontent.com/6644187/54073166-83099580-4249-11e9-92e0-03195ce50457.png">

And the translation is correctly installed.

Your traceback come from:
 - https://github.com/odoo/odoo/blob/6b2e519fbd7343f2bff373ec14955e6cc9505b9b/odoo/addons/base/models/ir_translation.py#L148-L156


Check @mart-e comment:
https://github.com/odoo/odoo/issues/31583#issuecomment-469615008

**Comment by mart-e** [comment]
Are you sure your source code is up to date? I was able to reproduce your problem was reproducible before #31683 but I can't anymore.

**Comment by blackwaremayank** [comment]
Hi @mart-e 

I'm using latest **Odoo 12.0+e-20190311 (Enterprise Edition)**.

I got below error when i'm trying to load **fr_CA** language.

Error:
Odoo Server Error
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
action = self._call_kw(model, method, args, {})
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/l10n_multilang/models/l10n_multilang.py", line 114, in lang_install
res = super(BaseLanguageInstall, self).lang_install()
File "/usr/lib/python3/dist-packages/odoo/addons/website/wizard/base_language_install.py", line 25, in lang_install
action = super(BaseLanguageInstall, self).lang_install()
File "/usr/lib/python3/dist-packages/odoo/addons/base/wizard/base_language_install.py", line 36, in lang_install
mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
File "/usr/lib/python3/dist-packages/odoo/addons/account_reports/models/account_financial_report.py", line 1324, in _update_translations
res = super(IrModuleModule, self)._update_translations(filter_lang=filter_lang)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 877, in _update_translations
self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 778, in load_module_terms
tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1011, in trans_load
result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1155, in trans_load_data
irt_cursor.finish()
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 156, in finish
""" % (self._model_table, self._table))
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
return f(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

**Comment by mart-e** [comment]
Thanks for the info, I may have an explanation.
Could you confirm that:
- you are using a packaged version (e.g. `.deb` file)?
- the file `/usr/lib/python3/dist-packages/odoo/addons/sale/i18n/sale.pot` does **not** exist?
- the file `/usr/lib/python3/dist-packages/odoo/addons/sale/i18n/fr.po` contains **twice** the string `field_res_config_settings__module_website_sale_digital`?

If this is so, it is just that you are still before the last Transifex fetch 9d4aad2d67019a3dd2ff5c45c89f3cc1a6202e78 that reflect the changes made at fa1210befd094dbb3f3f49251a16f8e114817991

We just realise that the packaged version do not include the `.pot` files. It is usually not a big deal as the `.po` is kept synchronised thanks to Transifex but you may get an outdated version like you did.
We will work to add the .pot inside the package too.
In the meantime, you can add [the missing file](https://github.com/odoo/odoo/raw/12.0/addons/sale/i18n/sale.pot) and let me know if it solves your issue.

**Comment by blackwaremayank** [comment]
Hi @mart-e 

Please find below answers to your questions. 
1. Yes, I'm using .deb package file.
2. The file /usr/lib/python3/dist-packages/odoo/addons/sale/i18n/sale.pot didn't exist so i added it.
3. The file /usr/lib/python3/dist-packages/odoo/addons/sale/i18n/fr.po contains **field_res_config_settings__module_website_sale_digital** string only once. 

But still i'm facing the same issue if i use **Overwrite Existing Terms** while loading **fr_CA** language.

**Comment by mart-e** [comment]
And the issue is still on sale/i18n/fr.po ? Could you please give a bit more context in your error log to see what actions it was doing before ?

**Comment by blackwaremayank** [comment]
Hi @mart-e 

As per your request please find full error log.

2019-03-14 12:16:34,169 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module rating: loading translation file (fr_CA) for language fr_CA 
2019-03-14 12:16:34,169 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/rating/i18n/fr_CA.po 
2019-03-14 12:16:34,215 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module project: loading base translation file fr for language fr_CA 
2019-03-14 12:16:34,215 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/project/i18n/fr.po 
2019-03-14 12:16:34,726 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module project: no translation for language fr_CA 
2019-03-14 12:16:34,739 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module auth_signup: loading base translation file fr for language fr_CA 
2019-03-14 12:16:34,740 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/auth_signup/i18n/fr.po 
2019-03-14 12:16:34,858 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module auth_signup: loading translation file (fr_CA) for language fr_CA 
2019-03-14 12:16:34,859 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/auth_signup/i18n/fr_CA.po 
2019-03-14 12:16:34,926 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module account_online_sync: loading base translation file fr for language fr_CA 
2019-03-14 12:16:34,926 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/account_online_sync/i18n/fr.po 
2019-03-14 12:16:34,996 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module account_online_sync: loading translation file (fr_CA) for language fr_CA 
2019-03-14 12:16:34,997 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/account_online_sync/i18n/fr_CA.po 
2019-03-14 12:16:35,019 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module account_plaid: loading base translation file fr for language fr_CA 
2019-03-14 12:16:35,019 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/account_plaid/i18n/fr.po 
2019-03-14 12:16:35,043 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module account_plaid: loading translation file (fr_CA) for language fr_CA 
2019-03-14 12:16:35,044 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/account_plaid/i18n/fr_CA.po 
2019-03-14 12:16:35,060 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module project_enterprise: no translation for language fr_CA 
2019-03-14 12:16:35,061 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module web_grid: loading base translation file fr for language fr_CA 
2019-03-14 12:16:35,061 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/web_grid/i18n/fr.po 
2019-03-14 12:16:35,139 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module web_grid: loading translation file (fr_CA) for language fr_CA 
2019-03-14 12:16:35,139 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/web_grid/i18n/fr_CA.po 
2019-03-14 12:16:35,183 22835 INFO March_latest_12E odoo.addons.base.models.ir_translation: module analytic_enterprise: loading base translation file fr for language fr_CA 
2019-03-14 12:16:35,183 22835 INFO March_latest_12E odoo.tools.translate: loading /usr/lib/python3/dist-packages/odoo/addons/analytic_enterprise/i18n/fr.po 
2019-03-14 12:16:35,218 22835 ERROR March_latest_12E odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           AND noupdate IS NOT TRUE\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments)\n                            WHERE EXCLUDED.value IS NOT NULL AND EXCLUDED.value != '';\n                       "
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2019-03-14 12:16:35,219 22835 ERROR March_latest_12E odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/wizard/base_language_install.py", line 36, in lang_install
    mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 877, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 764, in load_module_terms
    tools.trans_load(self._cr, base_trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1011, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1155, in trans_load_data
    irt_cursor.finish()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

Please let me know if you still need any further informations.

**Comment by mart-e** [comment]
Thanks, ok weare progressing, sale is no longer the issue, it is analytic_enterprise now.
This is +/- the same problem, in the .deb there is no `analytic_enterprise.pot` file that will be used as reference and the `fr.po` file was outdated.

We have changed our package yesterday to include the .pot files too. If you update to Odoo 12.0+e-20190314 (or later), you should get all the needed files and should not get this issue anymore.
I will work to make sure all the remaining .po file are correctly up to date but you should not get the error with the latest package.

Could you confirm?

**Comment by blackwaremayank** [comment]
Hi @mart-e 

Yes, i confirm it's resolved in latest .deb package.

Thanks

**Comment by davidgonzalezb** [comment]
Hello, How you reselved the error?. We have the same problem. Thanks 

The app Multi-DB Synchronization by Odoo S.A., Serpent Consulting Services Pvt. Ltd.
         

 psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

**Comment by Byloth** [comment]
> @davidgonzalezb: Hello, How you reselved the error?. We have the same problem. Thanks

Hi, everybody!  
Just to share the knowledge... I found out what the problem is.

Hopefully, it could be useful for someone else! 🙃

---

From Odoo 12 on, the basic structure of the `*.po` files has changed.

This problem occurs when you try to load a `*.po` file that was generated on a previous version of Odoo (e.g. Odoo 11).

---

To solve this problem, you have to export a new file `*.po` directly from the latest Odoo version.

That's it.

**Comment by davidgonzalezb** [comment]
Hello @Byloth
Thanks for your information
What file * .po do you mean? Do you have any examples? the file path?
Thank you
________________________________
De: Matteo Bilotta <notifications@github.com>
Enviado: viernes, 6 de septiembre de 2019 04:53:14 a. m.
Para: odoo/odoo <odoo@noreply.github.com>
CC: davidgonzalezb <david_gonzalezb@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [odoo/odoo] psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time (#31583)


@davidgonzalezb<https://github.com/davidgonzalezb>: Hello, How you reselved the error?. We have the same problem. Thanks

Hi, everybody!
Just to share the knowledge... I found out what the problem is.

Hopefully, it could be useful for someone else! 🙃

________________________________

From Odoo 12 on, the basic structure of the *.po files has changed.

This problem occurs when you try to load a *.po file that was generated on a previous version of Odoo (e.g. Odoo 11).

________________________________

To solve this problem, you have to export a new file *.po directly from the latest Odoo version.

That's it.

**Comment by cvinh** [comment]
cc @tglukhov @lpasquini

**Comment by tglukhov** [comment]
cc @luceeasypme
