### ISSUE TITLE
Duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by asiamatrix** [odoo/odoo#31689]
Impacted versions: Odoo 12 Enterprise Version

Showing error when click Validate button in POS Screen

2019-03-08 04:47:38,663 9556 ERROR xdbx_832019 odoo.sql_db: bad query: b'INSERT INTO "stock_picking" ("id", "create_uid", "create_date", "write_uid", "write_date", "company_id", "date", "date_done", "immediate_transfer", "is_locked", "location_dest_id", "location_id", "move_type", "name", "note", "origin", "partner_id", "picking_type_id", "printed") VALUES (nextval(\'stock_picking_id_seq\'), 2, (now() at time zone \'UTC\'), 2, (now() at time zone \'UTC\'), 1, \'2019-03-08 04:47:38\', \'2019-03-08 04:47:38.440000\', false, true, 9, 12, \'direct\', \'POS00190\', \'\', \'Shop19030180\', 928, 37, false) RETURNING id'
ERROR: duplicate key value violates unique constraint "stock_picking_name_uniq"
DETAIL:  Key (name, company_id)=(POS00190, 1) already exists.
 
2019-03-08 04:47:38,663 9556 ERROR xdbx_832019 odoo.addons.point_of_sale.models.pos_order: 
Could not fully process the POS Order: duplicate key value violates unique constraint "stock_picking_name_uniq"
DETAIL:  Key (name, company_id)=(POS00190, 1) already exists.
 
2019-03-08 04:47:38,664 9556 ERROR xdbx_832019 odoo.sql_db: bad query: b"\n                SELECT substr(p.res_id, 13)::integer, r.id\n                FROM ir_property p\n                LEFT JOIN account_account r ON substr(p.value_reference, 17)::integer=r.id\n                WHERE p.fields_id=2843\n                    AND (p.company_id=1 OR p.company_id IS NULL)\n                    AND (p.res_id IN ('res.partner,928') OR p.res_id IS NULL)\n                ORDER BY p.company_id NULLS FIRST\n            "
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2019-03-08 04:47:38,664 9556 ERROR xdbx_832019 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 928

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(928,).property_account_receivable_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "c:\odoo-12.0+e.20181210\addons\wk_pos_partial_payment\models\pos_order.py", line 25, in create_from_ui
    order_ids = return_data = super(PosOrder, self).create_from_ui(orders)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 750, in create_from_ui
    pos_order.action_pos_order_invoice()
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 681, in action_pos_order_invoice
    invoice = Invoice.new(order._prepare_invoice())
  File "c:\odoo-12.0+e.20181210\addons\xdbx_template\models\sale_order.py", line 40, in _prepare_invoice
    res = super(PosOder, self)._prepare_invoice()
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\point_of_sale\models\pos_order.py", line 174, in _prepare_invoice
    'account_id': self.partner_id.property_account_receivable_id.id,
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 967, in __get__
    self.determine_value(record)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1027, in _compute_value
    self.compute(records)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 647, in _compute_company_dependent
    values = Property.get_multi(self.name, self.model_name, records.ids)
  File "c:\program files (x86)\odoo 12.0e\server\odoo\addons\base\models\ir_property.py", line 268, in get_multi
    cr.execute(query, params + [sub_refs])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

2019-03-08 04:47:38,668 9556 INFO xdbx_832019 werkzeug: 127.0.0.1 - - [08/Mar/2019 04:47:38] "POST /web/dataset/call_kw/pos.order/create_from_ui HTTP/1.1" 200 - 117 0.096 0.129
2019-03-08 04:47:38,998 9556 INFO xdbx_832019 werkzeug: 127.0.0.1 - - [08/Mar/2019 04:47:38] "GET /point_of_sale/static/src/sounds/error.wav HTTP/1.1" 404 - 11 0.005 0.006
2019-03-08 04:47:39,315 9556 INFO xdbx_832019 werkzeug: 127.0.0.1 - - [08/Mar/2019 04:47:39] "GET /point_of_sale/static/src/sounds/error.wav HTTP/1.1" 404 - 11 0.003 0.009

**Comment by moylop260** [comment]
You have the POS sequence broken
You should re-assign the value of `next number` > to last current value

**Comment by asiamatrix** [comment]
Hello,

Good Day To You!

Thank you for your email. 
We will contact you back as soon as possible.

MAY SUCCESS BE WITH YOUR BUSINESS...
Best Regards,

Ko Kyaw Zin Oo
Founder & Managing Director
ASIA MATRIX COMPANY LIMITED
+959783355903, +959768064691
http://www.asiamatrixsoftware.com

**Comment by asiamatrix** [comment]
Can you show me sample code?

**Comment by asiamatrix** [comment]
I tried to like that but showing error.
select max(id) from stock_picking;
select nextval('stock_picking_id_seq')

SELECT setval('stock_picking_id_seq', (SELECT MAX(id) FROM stock_picking)+1);

**Comment by pedrobaeza** [comment]
This is not an Odoo issue per se, but a manipulated bad data as stated by @moylop260, so closing this. Any further question should be done on the forums or mailing lists.
