### ISSUE TITLE
Erron on webp image

### ISSUE THREAD

**Issue by As400it** [odoo/odoo#31907]
Impacted versions:
[10] -   
Steps to reproduce:
when load a product image on webp format I can see the icon but when sve the product i have the error 
Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/hr_expense/models/product_template.py", line 18, in create
    return super(ProductTemplate, self).create(vals)
  File "/data/build/odoo/addons/product/models/product_template.py", line 266, in create
    tools.image_resize_images(vals)
  File "/data/build/odoo/tools/image.py", line 277, in image_resize_images
    avoid_resize_big=True, avoid_resize_medium=True, avoid_resize_small=False))
  File "/data/build/odoo/tools/image.py", line 259, in image_get_resized_images
    return_dict[big_name] = image_resize_image_big(base64_source, avoid_if_small=avoid_resize_big)
  File "/data/build/odoo/tools/image.py", line 143, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/data/build/odoo/tools/image.py", line 57, in image_resize_image
    image = Image.open(image_stream)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2319, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x7fdc61ce5470>
Current behavior:
tested on runbot  

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Webp is not supported in Odoo yet, so it's normal that you get an error.

Closing as no bug, but unsupported format.
