### ISSUE TITLE
[12.0] Abandoned Cart Send Recovery Email For Multiple SO: issue Error Expected singleton

### ISSUE THREAD

**Issue by actonsys** [odoo/odoo#32028]
Impacted versions: 12.0 CE & EE, tested on runbot

Steps to reproduce: 
1. Go to Website > Orders > Abandoned Carts
2. Select more than one SO
3. Click on Button Action > Send a Cart Recovery Email

Current behavior: 
**(reproducible on runbot)**
Raise the following error
```
raise ValueError("Expected singleton: %s" % self)
ValueError: <class 'ValueError'>: "Expected singleton: sale.order(47, 48, 46, 52, 53)" while evaluating
'if records:\n                action = records.action_recovery_email_send()'
```

Expected behavior:
Open Wizard to Set and Send an Email

Video/Screenshot link (optional):
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/models.py", line 4688, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 2, in <module>
  File "/data/build/odoo/addons/website_sale/models/sale_order.py", line 315, in action_recovery_email_send
    self._portal_ensure_token()
  File "/data/build/odoo/addons/portal/models/portal_mixin.py", line 33, in _portal_ensure_token
    if not self.access_token:
  File "/data/build/odoo/fields.py", line 974, in __get__
    record.ensure_one()
  File "/data/build/odoo/models.py", line 4691, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: sale.order(47, 48, 46, 52, 53)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1269, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/data/build/odoo/addons/base/models/ir_actions.py", line 566, in run
    res = func(action, eval_context=eval_context)
  File "/data/build/odoo/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/data/build/odoo/addons/base/models/ir_actions.py", line 442, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/data/build/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/data/build/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/data/build/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 2, in <module>
  File "/data/build/odoo/addons/website_sale/models/sale_order.py", line 315, in action_recovery_email_send
    self._portal_ensure_token()
  File "/data/build/odoo/addons/portal/models/portal_mixin.py", line 33, in _portal_ensure_token
    if not self.access_token:
  File "/data/build/odoo/fields.py", line 974, in __get__
    record.ensure_one()
  File "/data/build/odoo/models.py", line 4691, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: <class 'ValueError'>: "Expected singleton: sale.order(47, 48, 46, 52, 53)" while evaluating
'if records:\n                action = records.action_recovery_email_send()'
```

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/32032
