### ISSUE TITLE
ir.attachment cascade unlink issue

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#32027]
```
class EntryLog(models.Model):
    _name = 'barrier.entry_log'
...

class EntryLogPicture(models.Model):
    _name = 'barrier.entry_log_picture'
   entry = fields.Many2one(comodel_name='barrier.entry_log',
                            ondelete='cascade')
   picture = fields.Binary(attachment=True)
```

When entry_log record is deleted it cascade deletes entry_log_picture records leaving ir.attachment pictures on the file system!

Here is the log:

```
>>> env['barrier.entry_log'].search([]).unlink()
2019-03-21 17:00:28,159 663 INFO barrier odoo.models.unlink: User #1 deleted barrier.entry_log records with IDs: [16]
True
>>> env['barrier.entry_log_picture'].search([]).unlink()
True
```

And here is the log when we manually unlink dependent records:

```
>>> env['barrier.entry_log_picture'].search([]).unlink()
2019-03-21 17:01:10,787 663 INFO barrier odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [682]
2019-03-21 17:01:10,802 663 INFO barrier odoo.models.unlink: User #1 deleted barrier.entry_log_picture records with IDs: [16]
True
>>> env['barrier.entry_log'].search([]).unlink()
2019-03-21 17:01:14,301 663 INFO barrier odoo.models.unlink: User #1 deleted barrier.entry_log records with IDs: [16]
True
```

Or also can be proved by browsing ir.attachment:
```
>>> env['barrier.entry_log'].search([]).unlink()
2019-03-21 17:05:03,311 663 INFO barrier odoo.models.unlink: User #1 deleted barrier.entry_log records with IDs: [16]
True
>>> env['ir.attachment'].browse(682).res_id;
16
```

But when attachment is deleted
```
>>> env['barrier.entry_log_picture'].search([]).unlink()
2019-03-21 17:05:43,371 663 INFO barrier odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [682, 681, 680]
2019-03-21 17:05:43,389 663 INFO barrier odoo.models.unlink: User #1 deleted barrier.entry_log_picture records with IDs: [16]
True
>>> env['ir.attachment'].browse(682).res_id;
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 682

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(682,).res_name', None)
```

**Comment by litnimax** [comment]
By the way, very strange and long traceback:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5218, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1039, in compute_value
    self._compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 45, in _compute_res_name
    if attachment.res_model and attachment.res_id:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1039, in compute_value
    self._compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 45, in _compute_res_name
    if attachment.res_model and attachment.res_id:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1039, in compute_value
    self._compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 45, in _compute_res_name
    if attachment.res_model and attachment.res_id:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 45, in _compute_res_name
    if attachment.res_model and attachment.res_id:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1043, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1081, in getter
    raise exception
```
and so on and on....

**Comment by pedrobaeza** [comment]
This seems something in your end, as attachments are deleted when removing models by default. Can you try in a clean environment?

**Comment by litnimax** [comment]
Pedro thanks for your quick reply.
But this is a clean database.
You can easily reproduce it by creating to models.
1) With binary field with attachment=True (in my case it's entry log picture)
2) With relation to the 1-st model with ondelete='cascade'. 
And after that try to unlink model 2.

**Comment by pedrobaeza** [comment]
OK, I'm not able to analyze it right now, but I have tagged the issue. You haven't indicated any way the version.

**Comment by litnimax** [comment]
12.0

**Comment by jakub-bacic** [comment]
We came across this issue as well. I haven't got much time to analyse it but it looks like the root cause of it is the fact that cascade deletes are implemented on the database level (using FK constraints and `ON DELETE CASCADE` clause) and it's not possible to implement the same mechanism in case of attachments (because they are related to different db tables based on `res_model` column value). If that's true, it means this issues is related only to `ir.attachment` model.

As a workaround, I can suggest overriding `unlink` method in "parent" model (`EntryLog` in the example above) and manually iterate over the list of attachments and unlink them explicitly.
