### ISSUE TITLE
Error when registering payment for invoice from tree view and currency is cleared

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#32064]
Impacted versions:
- 12.0

Steps to reproduce:
- Enable multi-currency
- Create an invoice
- Validate the invoice
- On the tree view, check the invoice and click Actions -> Register payment
- Clear currency

Current behavior:
The following traceback is shown:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/models.py", line 4688, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 5468, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/build/odoo/models.py", line 5321, in _onchange_eval
    method_res = method(self)
  File "/data/build/odoo/addons/account_check_printing/models/account_payment.py", line 31, in _onchange_amount
    self.check_amount_in_words = self.currency_id.amount_to_text(self.amount)
  File "/data/build/odoo/addons/base/models/res_currency.py", line 101, in amount_to_text
    self.ensure_one()
  File "/data/build/odoo/models.py", line 4691, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()
```

Expected behavior:
No traceback

This is very similar to https://github.com/odoo/odoo/issues/31411, but that issue occurs when clearing the amount and this one occurs when clearing the currency.

**Comment by luisg123v** [comment]
CC @yaniaular @moylop260

**Comment by luisg123v** [comment]
opw-1958888

**Comment by sswapnesh** [comment]
@luisg123v
Added Fix at https://github.com/odoo/odoo/pull/32068

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/32202

**Comment by pedrobaeza** [comment]
Already merged, so closing.
