### ISSUE TITLE
payment carrier not defined when price 0 in module website_sales

### ISSUE THREAD

**Issue by hviniciusg** [odoo/odoo#32184]
Impacted versions:
12.0
11.0

Steps to reproduce:

Create a product with sale price 0
Go to website and buy the product
Current behavior:
When you get to the step to confirm the order, you get the following error:
Error:

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2765, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2892, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "False"
LINE 5: ...er__name"."res_id") WHERE "payment_acquirer".id IN ('False')
                                                               ^
```
Expected behavior:
When you press the confirm order button on the website with a total of 0. the order should be processed and no further action required.

this is a use case for adding a trial or free products on your website.

Video/Screenshot link (optional):
http://g.recordit.co/6CfBvewXWt.gif

**Comment by pedrobaeza** [comment]
As said before, have you tried on runbot?

**Comment by pedrobaeza** [comment]
Confirmed it happens also in runbot in #32138

**Comment by hviniciusg** [comment]
i've been doing some research on what is causing the issue. and i have found the following that may you:

on the payment_transfer module, there is a check for amounts greater to 0
```
diff --git a/addons/payment_transfer/models/payment.py b/addons/payment_transfer/models/payment.py
index e7bc14e3f79..3c31fbef736 100644
--- a/addons/payment_transfer/models/payment.py
+++ b/addons/payment_transfer/models/payment.py
@@ -88,9 +88,9 @@ class TransferPaymentTransaction(models.Model):

     def _transfer_form_get_invalid_parameters(self, data):
         invalid_parameters = []
-
-        if float_compare(float(data.get('amount', '0.0')), self.amount, 2) != 0:
-            invalid_parameters.append(('amount', data.get('amount'), '%.2f' % self.amount))
+        #_logger.debug("######### _transfrer_form_get_invalid amount: $s" % data.get('ammont'))
+        #if float_compare(float(data.get('amount', '0.0')), self.amount, 2) != 0:
+        #    invalid_parameters.append(('amount', data.get('amount'), '%.2f' % self.amount))
```

but for some reason, the value that is received here is empty (IE ''), so it raises an exeption. this only happens because i disabled this checks on the templates, that allows me to show the pay buttons:

```
diff --git a/addons/website_sale/views/templates.xml b/addons/website_sale/views/templates.xml
index e9ed17c7f52..7b6ace80c97 100644
--- a/addons/website_sale/views/templates.xml
+++ b/addons/website_sale/views/templates.xml
@@ -1334,7 +1334,7 @@

                             <div class="oe_structure clearfix mt-3" id="oe_structure_website_sale_payment_1"/>

-                            <div id="payment_method" class="mt-3" t-if="(acquirers or tokens) and website_sale_order.amount_total">
+                           <div id="payment_method" class="mt-3" t-if="(acquirers or tokens)">
                                 <h3 class="mb24">Pay with </h3>
                                 <t t-call="payment.payment_tokens_list">
                                     <t t-set="mode" t-value="'payment'"/>
@@ -1361,7 +1361,7 @@
                                         <i class="fa fa-arrow-right"></i> Add payment acquirers
                                 </a>
                             </div>
-                            <div class="js_payment mt-3" t-if="not website_sale_order.amount_total" id="payment_method">
+                            <div class="js_payment mt-3"  id="payment_method">
                                 <form target="_self" action="/shop/payment/validate" method="post" class="float-right">
                                     <input type="hidden" name="csrf_token" t-att-value="request.csrf_token()" />
                                     <a role="button" class="btn btn-primary a-submit">
```
 
i disabled those IFs, because i was debugin the JS code and saw that it was being logged that
`DOM doesn't contain '.o_payment_form`

and the message that is shown when you make the payment is caused by payment_tx_id.acquirer_id.id = False :

```
line 1580 template.xml
<template id="payment_confirmation_status">
        <div class="oe_website_sale_tx_status mt-3" t-att-data-order-id="order.id">
            <t t-set="payment_tx_id" t-value="order.get_portal_last_transaction()"/>
            <div class="card">
                <div t-att-class="'card-header %s' % (
                    (payment_tx_id.state == 'pending' and 'bg-info') or
                    (payment_tx_id.state == 'done' and 'bg-success') or
                    (payment_tx_id.state == 'authorized' and 'bg-success') or
                    'bg-danger')">
                    **<a role="button" groups="base.group_system" class="btn btn-sm btn-link text-white float-right" target="_blank" aria-label="Edit" title="Edit"
                            t-att-href="'/web#model=%s&amp;id=%s&amp;action=%s&amp;view_type=form' % ('payment.acquirer', payment_tx_id.acquirer_id.id, 'payment.action_payment_acquirer')">**
```

hope to be usefull. and if you give some pointers im more than happy to fix this by myself

**Comment by hviniciusg** [comment]
Ok, finally found a solution. its a litle bit hacki, but fix the problem. should i submit a pull request?

here is the code.

```
diff --git a/addons/website_sale/controllers/main.py b/addons/website_sale/controllers/main.py
index 603d0176086..6b53b1e5168 100644
--- a/addons/website_sale/controllers/main.py
+++ b/addons/website_sale/controllers/main.py
@@ -961,6 +961,25 @@ class WebsiteSale(ProductConfiguratorController):
             tx = request.env['payment.transaction'].sudo().browse(transaction_id)
             assert tx in order.transaction_ids()
         elif order:
+                if order.amount_total ==0:
+                    vals = {'acquirer_id': 5,
+                    'return_url': '/shop/payment/validate'}
+
+                    vals['type'] = 'form_save'
+                    tx = order._create_payment_transaction(vals)
+
+                    # store the new transaction into the transaction list and if there's an old one, we remove it
+                    # until the day the ecommerce supports multiple orders at the same time
+                    last_tx_id = request.session.get('__website_sale_last_tx_id')
+                    last_tx = request.env['payment.transaction'].browse(last_tx_id).sudo().exists()
+                    if last_tx:
+                        PaymentProcessing.remove_payment_transaction(last_tx)
+                    PaymentProcessing.add_payment_transaction(tx)
+                    request.session['__website_sale_last_tx_id'] = tx.id
+                    tx.state = 'done'
+                    order.action_confirm()
+                else:
+                    tx = order.get_portal_last_transaction()
             tx = order.get_portal_last_transaction()
         else:
             tx = None
```
please let me know if the code looks ok so i can proceed and submit it

**Comment by hviniciusg** [comment]
Made pull request #32267

**Comment by rdeodoo** [comment]
See https://github.com/odoo/odoo/pull/32267
