### ISSUE TITLE
error print quotation KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x03C46468>, 'sale.action_report_saleorder')

### ISSUE THREAD

**Issue by david270291** [odoo/odoo#32204]
I cant print quotation the error completed is :
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x03C46468>, 'sale.action_report_saleorder')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\sale\models\sale.py", line 389, in print_quotation
    return self.env.ref('sale.action_report_saleorder').report_action(self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1356, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1340, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1329, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: sale.action_report_saleorder

**Comment by pedrobaeza** [comment]
You have remove that action in your DB, so it's not Odoo fault. Update your `sale` module for fixing it.

Closing as no real issue.
