### ISSUE TITLE
short dump in stock picking validate

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#32219]
Impacted versions:
Community version 12

Steps to reproduce:
validate a goods receipt from purchase order

Current behavior:
short dump occurred (reported below)

Expected behavior:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo12/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 31, in process
    self._process()
  File "<decorator-gen-199>", line 2, in _process
  File "/home/odoo12/odoo/odoo/api.py", line 372, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo12/odoo/odoo/api.py", line 372, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo12/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 23, in _process
    self.pick_ids.action_done()
  File "/home/odoo12/odoo/addons/delivery/models/stock_picking.py", line 111, in action_done
    res = super(StockPicking, self).action_done()
  File "/home/odoo12/odoo/addons/stock/models/stock_picking.py", line 630, in action_done
    todo_moves._action_done()
  File "/home/odoo12/odoo/addons/purchase_stock/models/stock.py", line 86, in _action_done
    res = super(StockMove, self)._action_done()
  File "/home/odoo12/odoo/addons/stock_account/models/stock.py", line 359, in _action_done
    res = super(StockMove, self)._action_done()
  File "/home/odoo12/odoo/addons/stock/models/stock_move.py", line 1113, in _action_done
    new_move = move._split(qty_split)
  File "/home/odoo12/odoo/addons/stock/models/stock_move.py", line 1208, in _split
    new_move = new_move._action_confirm(merge=False)
TypeError: _action_confirm() got an unexpected keyword argument 'merge'

**Comment by pedrobaeza** [comment]
Is this in a runbot instance or something locally?

**Comment by ccandito** [comment]
this is not related to a standard odoo module
sorry for wasting your time
Regards
