### ISSUE TITLE
V8: openerp.sql_db: Programming error: column ir_ui_view.arch does not exist

### ISSUE THREAD

**Issue by bikalexander** [odoo/odoo#3225]
Hi, 
sorry for my English.

after the I of "git pull" from Version: 

commit 9b48b181ed14452dd6cbe649382a5474d6229308 
Author: Richard Mathot rim@openerp.com 
Date: Tue Oct 7 10:18:12 2014 +0200 

on 

commit acaab83756e7f0363cd0cd1a1789ade26033584c 
Merge: 83b8e41 3af6bed 
Author: Arthur Maniet me@whisno.be 
Date: Thu Oct 16 14:13:42 2014 +0200 

've updated, I get the following error message:

2014-10-16 12:47:24,502 27200 INFO TestGrossGmbH4 passlib.registry: registered crypt handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2014-10-16 12:47:24,502 27200 INFO TestGrossGmbH4 passlib.registry: registered crypt handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2014-10-16 12:47:25,287 27200 ERROR TestGrossGmbH4 openerp.sql_db: Programming error: column ir_ui_view.arch does not exist
LINE 1: ...e_date",ir_ui_view."name",ir_ui_view."create_uid",ir_ui_view...
                                                             ^
, in query  SELECT ir_ui_view."inherit_id",ir_ui_view."create_date",ir_ui_view."name",ir_ui_view."create_uid",ir_ui_view."arch",ir_ui_view."write_uid",ir_ui_view."priority",ir_ui_view."mode",ir_ui_view."write_date",ir_ui_view."active",ir_ui_view."model",ir_ui_view."model_data_id",ir_ui_view."type",ir_ui_view."id",ir_ui_view."field_parent" FROM "ir_ui_view"
                    WHERE ir_ui_view.id IN %s AND (TRUE)
                    ORDER BY priority,name

2014-10-16 12:47:25,417 27200 ERROR TestGrossGmbH4 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/test-odoo/odoo/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/opt/test-odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/test-odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/test-odoo/odoo/openerp/http.py", line 1215, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/test-odoo/odoo/openerp/http.py", line 1189, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in **call**
    return self.app(environ, start_response)
  File "/opt/test-odoo/odoo/openerp/http.py", line 1361, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/test-odoo/odoo/openerp/http.py", line 1296, in get_response
    result = request.registry['ir.http']._handle_exception(e)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/test-odoo/odoo/openerp/http.py", line 596, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/test-odoo/odoo/openerp/http.py", line 1293, in get_response
    result.flatten()
  File "/opt/test-odoo/odoo/openerp/http.py", line 1166, in flatten
    self.response.append(self.render())
  File "/opt/test-odoo/odoo/openerp/http.py", line 1160, in render
    context=request.context)
  File "/opt/test-odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/test-odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 182, in get_template
    xml_doc = qwebcontext.loader(name)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1005, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/test-odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in read_template

  File "/opt/test-odoo/odoo/openerp/tools/cache.py", line 119, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 851, in read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/test-odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 522, in read_combined
    while v.mode != 'primary':
  File "/opt/test-odoo/odoo/openerp/fields.py", line 751, in **get**
    self.determine_value(record)
  File "/opt/test-odoo/odoo/openerp/fields.py", line 846, in determine_value
    record._prefetch_field(self)
  File "/opt/test-odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/models.py", line 3159, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/test-odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/models.py", line 3104, in read
    self._read_from_database(stored)
  File "/opt/test-odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/models.py", line 3216, in _read_from_database
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/opt/test-odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/test-odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_ui_view.arch does not exist
LINE 1: ...e_date",ir_ui_view."name",ir_ui_view."create_uid",ir_ui_view...
                                                             ^

How can it be, and what has to adapt? 

Thanks in advance!

**Comment by Yenthe666** [comment]
Hi @bikalexander,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
