### ISSUE TITLE
Can't print sale order

### ISSUE THREAD

**Issue by pja-odoo** [odoo/odoo#3241]
Can't print sale order.

Effected version : 7.0

Steps to reproduce error.

1> Install project_mrp and sale_stock module.
2>  Now uninstall sale_stock module.
3> Create sale order and click on 'print' button.

It's given following traceback 

Server Traceback (most recent call last):
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/addons/audittrail/audittrail.py", line 532, in execute_cr
    return fct_src(cr, uid, model, method, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/addons/sale/sale.py", line 423, in print_quotation
    'form': self.read(cr, uid, ids[0], context=context),
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/orm.py", line 3703, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/orm.py", line 3826, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/osv/fields.py", line 1152, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/bak/runbot/extra/runbot/static/build/23222-7-0-78a29b/openerp/addons/project_mrp/project_mrp.py", line 70, in _picked_rate
    res = super(sale_order, self)._picked_rate(cr, uid, ids, name, arg, context=context)
AttributeError: 'super' object has no attribute '_picked_rate'

**Comment by Yenthe666** [comment]
Hi @pja-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
