### ISSUE TITLE
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given after update CE11

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#32476]
I have this error after update.  Anyone have idea why?

2684 DEBUG ? odoo.http: Loading website_video_preview
2019-04-06 15:26:33,357 2684 DEBUG ? odoo.http: Loading whatsapp_redirect
2019-04-06 15:26:33,358 2684 DEBUG ? odoo.http: Loading wk_show_password
2019-04-06 15:26:33,360 2684 DEBUG ? odoo.http: Loading wk_wizard_messages
2019-04-06 15:26:33,387 2684 INFO ? odoo.http: HTTP Configuring static files
2019-04-06 15:26:34,492 2684 DEBUG bugfree_v11 odoo.service.server: cron0 started!
2019-04-06 15:26:34,493 2684 DEBUG bugfree_v11 odoo.service.server: cron1 started!
2019-04-06 15:26:34,493 2684 DEBUG bugfree_v11 odoo.modules.registry: Multiprocess signaling check: [Registry - 1207 -> 1207] [Cache - 73801 -> 73801]
2019-04-06 15:26:34,494 2684 DEBUG bugfree_v11 odoo.modules.registry: Multiprocess signaling check: [Registry - 1207 -> 1207] [Cache - 73801 -> 73801]
2019-04-06 15:26:34,513 2684 INFO bugfree_v11 odoo.addons.base.ir.ir_http: Generating routing map
2019-04-06 15:26:34,518 2684 DEBUG bugfree_v11 odoo.modules.registry: Multiprocess signaling check: [Registry - 1207 -> 1207] [Cache - 73801 -> 73801]
2019-04-06 15:26:34,518 2684 INFO bugfree_v11 odoo.addons.base.ir.ir_http: Generating routing map
2019-04-06 15:26:34,551 2684 INFO bugfree_v11 odoo.addons.base.ir.ir_http: Generating routing map
2019-04-06 15:26:34,686 2684 DEBUG bugfree_v11 odoo.modules.registry: Multiprocess signaling check: [Registry - 1207 -> 1207] [Cache - 73801 -> 73801]
2019-04-06 15:26:34,696 2684 INFO bugfree_v11 odoo.addons.base.ir.ir_http: Generating routing map
2019-04-06 15:26:35,213 2684 ERROR bugfree_v11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "w:\odoo\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\bus\controllers\main.py", line 42, in poll
    return self._poll(request.db, channels, last, options)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\calendar\controllers\bus.py", line 14, in _poll
    channels.append((request.db, 'calendar.alarm', request.env.user.partner_id.id))
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 948, in __get__
    self.determine_value(record)
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2653, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\res\res_users.py", line 943, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\res\res_users.py", line 320, in read
    return super(Users, self).read(fields=fields, load=load)
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2596, in read
    data = [(record, {'id': record._ids[0]}) for record in self]
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2596, in <listcomp>
    data = [(record, {'id': record._ids[0]}) for record in self]
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 4659, in __iter__
    yield self._browse((id,), self.env, self._prefetch, False)
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given
2019-04-06 15:26:35,217 2684 ERROR bugfree_v11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "w:\odoo\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\bus\controllers\main.py", line 42, in poll
    return self._poll(request.db, channels, last, options)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\calendar\controllers\bus.py", line 14, in _poll
    channels.append((request.db, 'calendar.alarm', request.env.user.partner_id.id))
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 948, in __get__
    self.determine_value(record)
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2653, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\res\res_users.py", line 943, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\res\res_users.py", line 320, in read
    return super(Users, self).read(fields=fields, load=load)
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2596, in read
    data = [(record, {'id': record._ids[0]}) for record in self]
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 2596, in <listcomp>
    data = [(record, {'id': record._ids[0]}) for record in self]
  File "w:\odoo\Odoo 11.0\server\odoo\models.py", line 4659, in __iter__
    yield self._browse((id,), self.env, self._prefetch, False)
TypeError: _browse() takes from 3 to 4 positional arguments but 5 were given
2019-04-06 15:26:35,232 2684 INFO bugfree_v11 werkzeug: 127.0.0.1 - - [06/Apr/2019 15:26:35] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-06 15:26:35,233 2684 INFO bugfree_v11 werkzeug: 127.0.0.1 - - [06/Apr/2019 15:26:35] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-06 15:26:35,245 2684 ERROR bugfree_v11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

**Comment by sswapnesh** [comment]
What was your last Rev ?
Ps: You got some bug in `bugfree_v11`(Just kidding)

**Comment by pedrobaeza** [comment]
I think you have `base_suspend_security` in your system. Please update it to latest version:

https://github.com/OCA/server-backend/commit/4ee3ee65c41e994301a9831e8433b8e66eb6e49f

**Comment by sswapnesh** [comment]
@Alexandre-Bernardes 
Have a look at https://github.com/odoo/odoo/commit/dcc752aaabc10aee8bbccc1474b43d224b57023c


@pedrobaeza 
> I think you have `base_suspend_security` in your system. Please update it to latest version:

Commit mentioned on OCA/server-backend@4ee3ee6 doesn't looks correct.

**Comment by Alexandre-Bernardes** [comment]
Now I like as free bug for all!!!! :D
this error in CEv11 (20190406)

**Comment by sswapnesh** [comment]
Please check if one of your custom module overrides `def _browse`  (add extra parameter in the definition method as mentioned in above commit if it is the case)

**Comment by Alexandre-Bernardes** [comment]
> I think you have `base_suspend_security` in your system. Please update it to latest version:
> 
> [OCA/server-backend@4ee3ee6](https://github.com/OCA/server-backend/commit/4ee3ee65c41e994301a9831e8433b8e66eb6e49f)

I dont have.

**Comment by Alexandre-Bernardes** [comment]
> Please check if one of your custom module overrides `def _browse` (add extra parameter in the definition method as mentioned in above commit if it is the case)

I will check.  thanks.

**Comment by Alexandre-Bernardes** [comment]
thank you guys!!!!
the module `muk_security` has defined `_browse` without de `add_prefetch=True` parameter in the file `res_users.py`
god blessed you
