### ISSUE TITLE
[12.0] Error when try get the xlsx file from Partner Ledger 

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#32533]
Impacted versions:
12.0
Steps to reproduce:

1. Open a partner with movements

2. Press the Customer Ledger option

3. Try to get the XLSX file

What is the current behavior that you observe?

I get the next traceback

```
Odoo Server Error

Traceback (most recent call last):

File "/data/build/odoo/addons/account_reports/controllers/main.py", line 31, in get_report

report_obj.get_xlsx(options, response)

File "/data/build/odoo/addons/account_reports/models/account_report.py", line 1199, in get_xlsx

cell_name = fields.Date.to_date(cell_name)

File "/data/build/odoo/fields.py", line 1601, in to_date

return datetime.strptime(value, DATE_FORMAT).date()

File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime

tt, fraction = _strptime(data_string, format)

File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime

(data_string, format))

ValueError: time data '04/09/2019' does not match format '%Y-%m-%d'
```

What would be your expected behavior in this case?

The xlsx file is generated

https://www.youtube.com/watch?v=2evHGKXKzDU

**Comment by luistorresm** [comment]
OPW #1966228

@nim-odoo could you help me with this ticket, please?

Regards
