### ISSUE TITLE
Cant close POS session with cash control

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#32754]
Impacted versions:11

Steps to reproduce:I enabled cash control while session was still open. No sales had gone through session. Tried to close session but get error. Now stuck and cant close session or turn off cash control

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
```
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 4390, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 269, in action_pos_session_validate
    self.action_pos_session_close()
  File "/odoo/custom/addons/pos_multi_session/models/pos_multi_session_models.py", line 83, in action_pos_session_close
    res = super(PosSession, self).action_pos_session_close()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 286, in action_pos_session_close
    self.with_context(ctx)._confirm_orders()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 42, in _confirm_orders
    orders_to_reconcile.sudo()._reconcile_payments()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_order.py", line 508, in _reconcile_payments
    partial_reconcile.create_tax_cash_basis_entry(cash_basis_percentage_before_rec[move])
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 1726, in create_tax_cash_basis_entry
    self.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 4393, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.partial.reconcile()`

```

**Comment by gustavovalverde** [comment]
Are you in the latest commit? I recall this being fixed a few days ago.

**Comment by gustavovalverde** [comment]
Here: https://github.com/odoo/odoo/commit/a7ac88e68cc24d3033c65606415449e8f347f7b3

**Comment by Yenthe666** [comment]
@jayo2005 can you please update your Odoo instance and check again? It should be solved in the meanwhile.

**Comment by jayo2005** [comment]
Yes updating solved the issue. Thanks
