### ISSUE TITLE
[12.0] Error when confirm purchase order

### ISSUE THREAD

**Issue by barachka** [odoo/odoo#32760]
Impacted versions:
12.0 Enterprise

Steps to reproduce:
Create Purchase order with more 2 lines

Current behavior:
Traceback:
Error:
Odoo Server Error
```
Traceback (most recent call last):
  File "/odoo/src/odoo/models.py", line 4688, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/src/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/src/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/src/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/src/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/src/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/src/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/src/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/src/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/src/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/src/addons/purchase/models/purchase.py", line 331, in button_confirm
    order.button_approve()
  File "/odoo/src/addons/purchase_stock/models/purchase.py", line 87, in button_approve
    self._create_picking()
  File "/odoo/src/addons/purchase_stock/models/purchase.py", line 208, in _create_picking
    moves = order.order_line._create_stock_moves(picking)
  File "/odoo/src/addons/purchase_stock/models/purchase.py", line 354, in _create_stock_moves
    return self.env['stock.move'].create(values)
  File "<decorator-gen-169>", line 2, in create
  File "/odoo/src/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/addons/stock/models/stock_move.py", line 383, in create
    res = super(StockMove, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/src/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/src/odoo/fields.py", line 1110, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/src/addons/stock/models/stock_move.py", line 656, in onchange_date
    if self.date_expected:
  File "/odoo/src/odoo/fields.py", line 974, in __get__
    record.ensure_one()
  File "/odoo/src/odoo/models.py", line 4691, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move(9366, 9367, 9368)
```

**I think this problem after merged https://github.com/odoo/odoo/pull/31471**

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment]
@pedrobaeza hmm I made a PR but now that I look at the code again I'm actually assuming there is custom dev on that environment. The field `date_expected` is on the line so it should work fine.
@barachka could you try on the latest 12.0 runbot and make a video?

**Comment by pedrobaeza** [comment]
Yes, that was my suspect and thus I prefer confirmation on runbot.

**Comment by barachka** [comment]
Ok, we found problem. Thanks for fast answers
