### ISSUE TITLE
ir.config_parameter in res.config.settings does not respect XML ID

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#32806]
**Impacted versions:**
12.0
**Steps to reproduce:**
Go into general settings. Uncheck Show Effect option. Save. Check Show Effect option. Save. Go to applications. Upgrade base_setup module.
**Current behavior:**
```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/data/build/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/data/build/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/data/build/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-53>", line 2, in create
  File "/data/build/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/base/models/ir_config_parameter.py", line 99, in create
    return super(IrConfigParameter, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/data/build/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/models.py", line 3533, in create
    records = self._create(data_list)
  File "/data/build/odoo/models.py", line 3633, in _create
    cr.execute(query, params)
  File "/data/build/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/data/build/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(base_setup.show_effect) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/data/build/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/build/odoo/addons/base/models/ir_module.py", line 622, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/data/build/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/data/build/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/build/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/data/build/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/data/build/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/data/build/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/data/build/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/data/build/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/data/build/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/data/build/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/data/build/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/data/build/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/data/build/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/data/build/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/data/build/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-53>", line 2, in create
  File "/data/build/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/base/models/ir_config_parameter.py", line 99, in create
    return super(IrConfigParameter, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/data/build/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/models.py", line 3533, in create
    records = self._create(data_list)
  File "/data/build/odoo/models.py", line 3633, in _create
    cr.execute(query, params)
  File "/data/build/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/data/build/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(base_setup.show_effect) already exists.
" while parsing /data/build/odoo/addons/base_setup/data/base_setup_data.xml:4, near
<record model="ir.config_parameter" id="show_effect">
            <field name="key">base_setup.show_effect</field>
            <field name="value">True</field>
        </record>
```
**Expected behavior:**
Should update `base_setup` module.
Video/Screenshot link (optional):

[cfg-param-bug.ogv.tar.gz](https://github.com/odoo/odoo/files/3094578/cfg-param-bug.ogv.tar.gz)

Note. This behavior happens, because `ir.config_parameter` record is first deleted, when you uncheck the option. Then when you check it, it is created, but original parameter record had XML ID, where recreated parameter does not. So when trying to upgrade `base_setup`, odoo tries to create parameter again (because its XML ID no longer exist), but parameter with same key, does exist -> error.

Lets look at method in question:
```python
    @api.model
    def set_param(self, key, value):
        """Sets the value of a parameter.

        :param string key: The key of the parameter value to set.
        :param string value: The value to set.
        :return: the previous value of the parameter or False if it did
                 not exist.
        :rtype: string
        """
        param = self.search([('key', '=', key)])
        if param:
            old = param.value
            if value is not False and value is not None:
                if str(value) != old:
                    param.write({'value': value})
            else:
                param.unlink()
            return old
        else:
            if value is not False and value is not None:
                self.create({'key': key, 'value': value})
            return False
```
If value is either `False` or `None`, it will remove parameter. I guess this is intended, but it can have various unexpected consequences as in this issue. Wouldn't it be better to always keep parameter, but set some `Falsy` value, instead of removing parameter entirely?

**Comment by mart-e** [comment]
Hi,

Thanks for the report and the deep analysis, I have fixed it at https://github.com/odoo/odoo/commit/a7c774849c000a7910d4db3d026cb9569297dc21
Changing the way the `set_param` behave is risky as some code may rely on it and have side-effect.
Instead I have made an alternative patch that will avoid to recreate the entry when updating the module.

**Comment by oerp-odoo** [comment]
Hi,
Ok. Thanks for fix. Maybe this would be improved at new release? Cause this
could accidentally remove param when you dont expect it. We had this issue
with False value. Where we expected to just set False value on param, but
instead it would remove param entirely. Then we had to use repr(False) to
avoid it when setting new value.
I think it would be more consistent to try keeping param than removing it?

**Comment by mart-e** [comment]
The problem is that the parameters are currently not used consistently in Odoo.  For instance, take the following code that will test the _existence_ of the parameter, whatever its value is.

https://github.com/odoo/odoo/blob/3f681b208c5f483bc7e523527d1f4406f4d47075/addons/google_calendar/models/google_calendar.py#L432
https://github.com/odoo/odoo/blob/3f681b208c5f483bc7e523527d1f4406f4d47075/addons/google_calendar/models/google_calendar.py#L929-L930

IMHO, in the future the parameters should be strong typed to avoid this kind of issue (instead of always being a string). But this is not a trivial change...
