### ISSUE TITLE
ON CONFLICT DO UPDATE command cannot affect row a second time Odoo 12

### ISSUE THREAD

**Issue by support-atharva** [odoo/odoo#32801]
**Impacted versions:** 12.0 community

**Steps to reproduce:** 
1. Load a language (e.g. French)
2. Export the translations of both  `base` and `mail` module in a po file (works too with `calendar` and `calendar_sms`)
3. Import the translation file with "Overwrite Existing Terms"

**Current behavior:** 
File not imported due to format mismatch or a malformed file. (Valid formats are .csv, .po, .pot)

**Technical Details:**
ON CONFLICT DO UPDATE command cannot affect row a second time
HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

**Comments:**
I have taken the latest pull for 12.0 version and tried to follow the same steps but still, we are getting an error.

Importing using the same process above, after removing entries from the database and NOT checking the overwrite box appears to complete successfully.  Some of the newer terms load in fine as we see more translated on the screen than before.

However, our second error appears when some of the terms we translated are not appearing.  In troubleshooting, we looked at an example translated term, "Congratulations, your inbox is empty" in the Discussion / Mail application.  The Chinese term was translated and imported into the ir_translation table.  What appeared to be missing was the module field - it was NULL.  Changing to "mail" resulted in the translated term properly showing up in Odoo.

Can you please get back on this issue?

Thanks.

**Comment by mart-e** [comment]
Hi,

Please share specifi information like the .po file you are trying to import, the full traceback, the options you have chosen,...
This error typically comes when trying to import an invalid po file (e.g. import a 11.0 po file in a 12.0 database)

**Comment by support-atharva** [comment]
Hi @mart-e 

I am trying to import a translation for the French language. Please find attached .po file.

[fr.zip](https://github.com/odoo/odoo/files/3096960/fr.zip)

**Traceback:**
2019-04-19 03:56:11,227 4111 INFO test12 odoo.tools.translate: loading translation file for language fr_FR 

2019-04-19 03:56:12,882 4111 ERROR test12 odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           AND noupdate IS NOT TRUE\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments)\n                            WHERE EXCLUDED.value IS NOT NULL AND EXCLUDED.value != '';\n                       "
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2019-04-19 03:56:12,882 4111 ERROR test12 odoo.addons.base.wizard.base_import_language: File unsuccessfully imported, due to format mismatch. 
Traceback (most recent call last):
  File "/opt/odoo/12.0/odoo/addons/base/wizard/base_import_language.py", line 41, in import_lang
    lang_name=this.name, context=this._context)
  File "/opt/odoo/12.0/odoo/tools/translate.py", line 1155, in trans_load_data
    irt_cursor.finish()
  File "/opt/odoo/12.0/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/opt/odoo/12.0/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/12.0/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

2019-04-19 03:56:12,883 4111 ERROR test12 odoo.sql_db: bad query: b"SELECT value FROM ir_translation\n                       WHERE lang='en_US' AND type in ('code', 'sql_constraint') AND src='File not imported due to format mismatch or a malformed file. (Valid formats are .csv, .po, .pot)\n\nTechnical Details:\n%s' AND md5(src)=md5('File not imported due to format mismatch or a malformed file. (Valid formats are .csv, .po, .pot)\n\nTechnical Details:\n%s')"
ERROR: current transaction is aborted, commands ignored until end of transaction block

Thanks.

**Comment by mart-e** [comment]
Thanks for the details. Indeed the po file is invalid as two entries are referring to the same field:
```po
#: model:ir.model.fields,field_description:base.field_ir_ui_view__type
#: model:ir.model.fields,field_description:mail.field_ir_ui_view__type
msgid "View Type"
msgstr "Type de Vue"
```

However, this is possible to reproduce easily in standard.
I have updated the "steps to reproduce" section to explain how to reproduce it without a custom po file.
Still need to investigate on what is the best way to fix it.

**Comment by support-atharva** [comment]
Hi @mart-e 

Thanks for the prompt response. I have exported this file from odoo itself and without doing any changes I have just imported it again.

Note: I have not selected any module while exporting a translation.

Please let us know the solution to this.

Thanks.

**Comment by akselon** [comment]
@Yenthe666 Is it possible, that it also affects Odoo 13? I added following code to my module, that exdends the Fleet app:
`class FleetServiceType(models.Model):   
    _inherit = 'fleet.service.type'
    
    category = fields.Selection(selection_add=[
        ('contract-leasing', 'Leasing contract'),
        ('contract-insurance', 'Insurance contract'),
        ('contract', 'Other contract'),
    ], help='Choose whether the service refer to contracts or vehicle services')`

When I generate translation strings for my module and the fleet module as well (Settings->Translations->Export Translation) , I get:
`#. modules: custom_fleet, fleet
#: model:ir.model.fields,field_description:custom_fleet.field_fleet_service_type__category
#: model:ir.model.fields,field_description:custom_fleet.field_fleet_vehicle_log_contract__cost_subtype_id_category
#: model:ir.model.fields,field_description:custom_fleet.field_fleet_vehicle_log_damage__category
#: model:ir.model.fields,field_description:fleet.field_fleet_service_type__category
msgid "Category"
msgstr "Kategorie"`

When trying to install the German language (Settings->Languages->Refresh icon), I get and Error:
`psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.`
![image](https://user-images.githubusercontent.com/14870018/69440187-a4af9c00-0d48-11ea-83dc-ce888b720315.png)

**Comment by Yenthe666** [comment]
Yeah it is and I've seen it happen before. Nothing I can do though, Odoo has to check it.

**Comment by yucer** [comment]
There is a new instance of this error after the merge of this [commit](https://github.com/odoo/odoo/commit/5db13a3a61f722447365b28feab1daff6cbd2578).

It is from three days ago and introduce conflicting translations to the temporary translation import table: **tmp_ir_translation_import**.

The **PostgreSQL** statements **ON CONFLICT** ... **DO_UPDATE** doesn't allow the same row to be updated twice for conflict resolutions.

This error might be noted just in Odoo instances that load the french language.  

This time the conflict is with [stock](https://github.com/odoo/odoo/blob/5db13a3a61f722447365b28feab1daff6cbd2578/odoo/addons/base/i18n/fr.po#L28461) in *fr.po* and [Stock](https://github.com/odoo/odoo/blob/5db13a3a61f722447365b28feab1daff6cbd2578/odoo/addons/base/i18n/base.pot#L19286) in *base.pot*

**Comment by yucer** [comment]
I did a [patch](https://gist.github.com/yucer/0c68310f8ce282fbbd3f61db545478c9) for debugging such duplicated import rows.

**Comment by yucer** [comment]
I have updated the [patch](https://gist.github.com/yucer/0c68310f8ce282fbbd3f61db545478c9), it reports the duplicated rows that cause the error and also delete the duplicated rows.

The cases I have found are conflicts between the **.po** and **.pot** files, mostly in translation for models.

Anybody is free to use that code as an start to propose a solution.

**Comment by Yenthe666** [comment]
@mart-e could you have an extra look? I'm being hit by this one every once in a while on new runbot instances too. Loading the Dutch language on a runbot seems to cause it quite often.

**Comment by mart-e** [comment]
@Yenthe666 what you are reporting is a different problem.
The reported problem is exporting terms of several modules in the same translation file will crash when importing. This is not a scenario we handle at the moment.

Issues like #41364 are bugs where we must correct the source of the problem (e.g. bad .pot file). Don't report them here.

We could remove duplicates as I did at #32826 but I don't want to merge this as it would hide real issues (like in  #41364).

**Comment by yucer** [comment]
> We could remove duplicates as I did at #32826 but I don't want to merge this as it would hide real issues (like in #41364).

@mart-e Nevertheless we might be able to log them before deletion right ? They can be even shown in the UI wizard.

But I guess that a new translation is not so important to stop the update.

**Comment by C3POdoo** [comment]
Dear @support-atharva,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
