### ISSUE TITLE
Fresh install, XMLRPC error

### ISSUE THREAD

**Issue by hdezela** [odoo/odoo#32889]
Impacted versions:

12.0

Steps to reproduce:

1. Install Odoo per "https://www.odoo.com/documentation/12.0/setup/install.html#setup-install-source"
2. Proxy with Nginx
3. GET "https://[ODOOURL].com/xmlrpc/2/common"

Current behavior:

Error:

```
<?xml version='1.0'?>
<methodResponse>
<fault>
<value><struct>
<member>
<name>faultCode</name>
<value><int>1</int></value>
</member>
<member>
<name>faultString</name>
<value><string>Traceback (most recent call last):
  File "/webdata/odoo/odoo/addons/base/controllers/rpc.py", line 63, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/webdata/odoo/odoo/addons/base/controllers/rpc.py", line 42, in _xmlrpc
    params, method = loads(data)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1020, in loads
    p.close()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 448, in close
    parser.Parse(b"", True) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0
</string></value>
</member>
</struct></value>
</fault>
</methodResponse>
```

Expected behavior:

Identity JSON string

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/99411/56626759-a83f4100-6608-11e9-9f24-b10906b2d05c.png)

**Comment by hdezela** [comment]
Oh God...never mind, was calling it with an empty body. I'm going to go kill myself now for posting this.
