### ISSUE TITLE
[8.0]Field(s) `arch` failed against a constraint: Invalid view definition

### ISSUE THREAD

**Issue by rainberg** [odoo/odoo#3307]
Happened when i tried to instalal the module website_event

This is the version i used:

commit ae02468e0af40958f76671f0b064ffd54c893f01
Merge: 92183e5 3dff287
Author: Josse Colpaert jco@odoo.com
Date:   Fri Oct 24 19:58:48 2014 +0200

This is thte detail of errors

```
Traceback (most recent call last):
  File "/usr/local/src/odoo/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/src/odoo/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/src/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/src/odoo/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/usr/local/src/odoo/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/src/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/src/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/local/src/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/src/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 827, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/usr/local/src/odoo/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/usr/local/src/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 3965, in create
    record = self.browse(self._create(old_vals))
  File "/usr/local/src/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 4156, in _create
    recs._validate_fields(vals)
  File "/usr/local/src/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/src/odoo/openerp/models.py", line 1300, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//ul[@id='products']">' cannot be located in parent view

Error context:
View `Footer Events Link`
[view_id: 2304, xml_id: n/a, model: n/a, parent_id: 266]" while parsing None:19, near
<data inherit_id="website.footer_default" name="Footer Events Link">
    <xpath expr="//ul[@id='products']" position="inside">
        <li><a href="/event">Events</a></li>
    </xpath>
</data>
```

**Comment by rainberg** [comment]
Element '<xpath expr="//ul[@id='products']">' cannot be located in parent view

for me it didn't resolved until ,it seems to be related to the data I used,if i start a new instance without data,i cant install the event module ,if i recovered from the data before ,then i will get the same error again

Element '<xpath expr="//ul[@id='products']">' cannot be located in parent view

**Comment by carrasquel2016** [comment]
Tengo un error similar espero me puedan orientar:

 File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 530, in _handle_exception
  File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 567, in dispatch
  File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 303, in _call_function
  File "C:\Program Files\Odoo 8.0\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 300, in checked_call
  File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 796, in __call__
  File "C:\Program Files\Odoo 8.0\server\.\openerp\http.py", line 396, in response_wrap
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 940, in call_button
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 928, in _call_kw
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "C:\Program Files\Odoo 8.0\server\.\openerp\modules\registry.py", line 368, in new
  File "C:\Program Files\Odoo 8.0\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files\Odoo 8.0\server\.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files\Odoo 8.0\server\.\openerp\modules\loading.py", line 176, in load_module_graph
  File "C:\Program Files\Odoo 8.0\server\.\openerp\modules\loading.py", line 118, in _load_data
  File "C:\Program Files\Odoo 8.0\server\.\openerp\tools\convert.py", line 901, in convert_file
  File "C:\Program Files\Odoo 8.0\server\.\openerp\tools\convert.py", line 987, in convert_xml_import
  File "C:\Program Files\Odoo 8.0\server\.\openerp\tools\convert.py", line 853, in parse
  File "C:\Program Files\Odoo 8.0\server\.\openerp\tools\convert.py", line 763, in _tag_record
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\base\ir\ir_model.py", line 1077, in _update
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files\Odoo 8.0\server\openerp\addons\base\ir\ir_ui_view.py", line 264, in create
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 336, in old_api
  File "C:\Program Files\Odoo 8.0\server\.\openerp\models.py", line 4059, in create
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 462, in new_api
  File "C:\Program Files\Odoo 8.0\server\.\openerp\models.py", line 4250, in _create
  File "C:\Program Files\Odoo 8.0\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files\Odoo 8.0\server\.\openerp\models.py", line 1267, in _validate_fields
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Modelo no encontrado: False

Error de contexto:
Vista `view.pickup.form`
[view_id: 1079, xml_id: n/a, model: n/a, parent_id: n/a]" while parsing file:///C:/Program%20Files/Odoo%208.0/server/openerp/addons/PROYECTO_GLOBAL/views/Pickup_order.xml:5, near
<record id="view_pickup_form" model="ir.ui.view">			
			<field name="name">view.pickup.form</field>
			<field name="res_model">pickup</field>
			<field name="arch" type="xml">
 				<form string="Pickup Order" version="7.0">
					<notebook colspan="4" position="inside">

						  <page string="General">
						  
						  <sheet>

						  <group col="4">
										<group>								
												<field name="consecutivo"/>
												<field name="creation_date_time"/>								
												<field name="Pick_up"/>
												<field name="delivery_date"/>
												<field name="destination_agent"/>
												<field name="issued_by"/>


												
										</group>						
										<group>
										</group>
						</group>
						</sheet>
							    <group col="4">
												<group>						   
												</group>
												<group>
												</group>							
								</group>
						</page>


							
							<page string="Shipper ">
								<sheet>
								<group col="3">
									<group>
										<field name="shipper"/>	
										<field name="pickup_location"/>
										<field name="place"/>
									</group>
									<group col="4">
								</group>
								</group>
							</sheet>								
							</page>	

															  
					<page string="Consiggnee ">
				    <sheet>	
					            <group col="4">
								<group>
										<field name="consignee" help="Selected Consignes of list."/>	
										<field name="consignee_location" help="localizacion"/>
                                        <field name="place"/>
																				
								 </group> 
						         </group>
					             <group col="2">
								 </group>
								 <group>
									   <field name="cliente_to_bill"/>
									   <field name="cliente_to_bill_2"/>										   
								 </group>
						     	 <group col="4">
					       	     </group>
		               </sheet>								 
					   </page>						
	
								
							<page string="Supplier">
				            <sheet>							
								<group col="4">
									<group>
										<field name="Name" widget="handle"/>
										<field name="invoice_number" widget="handle"/>	 
										<field name="Purchase_order_number" widget="handle"/>			
									</group>
								<group col="4">
								</group>
								</group>
					        </sheet>
							</page>

							
							<page string="Carrier">
							<sheet>
							<group col="4">
									<group>
										
										<field name="carrier"/>
										<field name="pro_number"/>	 
										<field name="driver_name" widget="handle"/>
										<field name="driver_licence" widget="handle"/>
										<field name="tracking_number" widget="handle"/>
										<field name="arrier" widget="handle"/>
										<field name="bookin" widget="handle"/>
										<field name="preferred" widget="handle"/>
									</group>
								</group>
							</sheet>
							</page>

							
						<page string="Comoditties">
		                <sheet>								 						
						<group col="4">
										<group>
										<field name="consecutivo2"/>	    
									    <field name="pack"/> 
								         <field name="loc"/>
										<field name="descrip"/>  
										<field name="notes" widget="handle"/>
						 </group>				
						 </group>
       					 </sheet>								 

									     <notebook>
										 <page string="Calculo de Piezas"> 
										 <field name="dimensiones"/>  
								         </page>
								     	 </notebook>
										 							         
										</page>


														
								<page string="Notes">
							   <sheet>		
								<group col="4">
									<group>
										<field name="consecutivo3" widget="handle"/>	 
										<field name="notes_1" widget="handle"/>		
							            <field name="issued_by2"/>						   
										
									</group>
								</group>
							   </sheet>
							   </page> 
	
								
								<page string="Events">
							   <sheet>
								<group col="1">
									<group>
									<field name="consecutivo5" widget="handle"/>	 							
									</group>
								    </group>
									<page string="Events"> 
									<field name="dato"/>										
									</page>									 
						        </sheet>
								</page> 

                    
								<page string="Charged">
								<sheet>
								<group col="2">
									<group>
										<field name="consecutivo6" widget="handle"/>
								    </group></group>
									<strong><H4>Totals</H4></strong>
									<table style="width: 600px;">
									<td style="width: 100px;"><p>Facturado</p><field name="invoice" widget="masked"/></td>
									<td style="width: 100px;"><p>Expensas</p><field name="expence"/></td>
									<td style="width: 100px;"><p>Beneficio</p><field name="profit_total"/></td>
									</table>
								<notebook>
										<page string="Pagos"> 
											<field name="charged_ids"/>
										</page>		
									     <page string="Cobros"> 
											<field name="income"/></page>
								        </notebook>	 
										</sheet>
							           </page> 


	
									
							<page string="POD">
							<sheet>	
								<group col="4">
								<group>
										
										<field name="delivery_date2" widget="handle"/>
										<field name="received_by" widget="handle"/>	 
										<field name="comments" widget="handle"/>
										<field name="internal_comments" widget="handle"/>

							    </group>
								</group>
							</sheet>
							</page>
								

							
			   <page string="Internal Notes">
               <sheet>
		     	<group col="4">
				<group>
						<field name="create_date"/>
						<field name="issued_by3"/>						   
						
				</group>
				</group>
						<notebook>
								<page string="Resumen de Notas Internas">
							    <field name="nota_ids"/>	
							    </page>
						</notebook> 
						</sheet>
			        </page>

									
							<page string="Hazardous">
							<sheet>
								<group col="4">
									<group>
										
										<field name="ident_number"/> 	 
										<field name="mat_class" widget="handle"/>
										<field name="class_qualifier" widget="handle"/>
										<field name="mat_description" widget="handle"/>
										<field name="emer_contact" widget="handle"/>
										<field name="material_page" widget="handle"/>
										<field name="flashpoint_temp" widget="handle"/> 
									    <field name="special_instruction" widget="handle"/> 
										<field name="description_class" widget="handle"/> 
										<field name="hazardous_level" widget="handle"/> 
									</group>
								</group>
							    </sheet>
							    </page>



					</notebook>
				</form>
	           </field>
		</record>
2016-08-16 20:45:38,948 3392 INFO Global openerp.modules.loading: loading 1 modules...
2016-08-16 20:45:38,982 3392 INFO Global openerp.modules.loading: 1 modules loaded in 0.03s, 0 queries

**Comment by Yenthe666** [comment]
Hi @rainberg,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
