### ISSUE TITLE
[12] Traceback on closing "Link to" wizard on HTML editor

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#33085]
Impacted versions: 12

Steps to reproduce: 

![](https://image.prntscr.com/image/utq3333LQZCY_V0JssmM5Q.png)
![Screenshot - 2019-05-01T235727 748](https://user-images.githubusercontent.com/16624719/57034343-e540ae80-6c6c-11e9-968b-ea31db027a7b.png)
![Screenshot from 2019-05-02 00-03-34](https://user-images.githubusercontent.com/16624719/57034663-c2fb6080-6c6d-11e9-856c-44f90b2e0d01.png)

Current behavior:
```
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 135 is larger than the node's length (0).
    at nativeRange (http://510441-12-0-2efcef.runbot17.odoo.com/web_editor/static/lib/summernote/src/js/core/range.js:131:20)
    at WrappedRange.select (http://510441-12-0-2efcef.runbot17.odoo.com/web_editor/static/lib/summernote/src/js/core/range.js:176:25)
    at Editor.restoreRange (http://510441-12-0-2efcef.runbot17.odoo.com/web_editor/static/lib/summernote/src/js/module/Editor.js:97:13)
    at EventHandler.invoke (http://510441-12-0-2efcef.runbot17.odoo.com/web_editor/static/lib/summernote/src/js/EventHandler.js:71:31)
    at Object.<anonymous> (http://510441-12-0-2efcef.runbot17.odoo.com/web_editor/static/lib/summernote/src/js/module/LinkDialog.js:123:17)
    at fire (http://510441-12-0-2efcef.runbot17.odoo.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (http://510441-12-0-2efcef.runbot17.odoo.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://510441-12-0-2efcef.runbot17.odoo.com/web/static/lib/jquery/jquery.js:3283:104)
    at fire (http://510441-12-0-2efcef.runbot17.odoo.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as rejectWith] (http://510441-12-0-2efcef.runbot17.odoo.com/web/static/lib/jquery/jquery.js:3231:49)
```
Expected behavior: Close Wizard

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
I actually just ran into this one. Reported under OPW 1981751

**Comment by sswapnesh** [comment]
Hello @Yenthe666 
Did it passed through their Functional Analyst ?

**Comment by Yenthe666** [comment]
@sswapnesh yeah, it is in the bug fixing state!

**Comment by Yenthe666** [comment]
Fixed at https://github.com/odoo/odoo/commit/6843e4d5eb33768d11151ffa98be1d13f43129a4
