### ISSUE TITLE
[12.0] group by does not work for multiple fields (via filter context)

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#33149]
**Impacted versions:**
12.0
**Steps to reproduce:**
Have a search view that groups by more than one field. For example:

```xml
    <record id="mail_activity_view_search" model="ir.ui.view">
        <field name="name">mail.activity.search</field>
        <field name="model">mail.activity</field>
        <field name="priority" eval="100"/>
        <field name="arch" type="xml">
            <search>
                <field name="res_id"/>
                <field name="res_model_id"/>
                <field name="summary"/>
                <field name="activity_type_id"/>
                <field name="date_deadline"/>
                <separator/>
                <group expand="0" string="Group By">
                    First, group by model and just then by ID, because ID
                        might be the same for different models.
                    <filter string="Related Document" name="related_document" context="{'group_by': ['res_model_id', 'res_id']}"/>
                </group>
            </search>
        </field>
    </record>
```
**Current behavior:**
Throws error when loading view:

```js
Uncaught TypeError: Cannot read property 'type' of undefined
http://127.0.0.1:8059/web/static/src/js/views/search/groupby_menu.js:156
Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class._prepareItem (http://127.0.0.1:8059/web/static/src/js/views/search/groupby_menu.js:156:74)
    at Class.prototype.(anonymous function) [as _prepareItem] (http://127.0.0.1:8059/web/static/src/js/core/class.js:90:38)
    at Function._.each._.forEach (http://127.0.0.1:8059/web/static/lib/underscore/underscore.js:145:9)
    at Class.init (http://127.0.0.1:8059/web/static/src/js/views/search/groupby_menu.js:69:11)
    at Class.prototype.(anonymous function) [as init] (http://127.0.0.1:8059/web/static/src/js/core/class.js:90:38)
    at new Class (http://127.0.0.1:8059/web/static/src/js/core/class.js:107:33)
    at Class._createGroupByMenu (http://127.0.0.1:8059/web/static/src/js/views/search/search_view.js:971:16)
    at http://127.0.0.1:8059/web/static/src/js/views/search/search_view.js:452:46
    at http://127.0.0.1:8059/web/static/lib/jquery/jquery.js:3276:89
    at fire (http://127.0.0.1:8059/web/static/lib/jquery/jquery.js:3119:58)
```

**Expected behavior:**
Should group by multiple items.

Additional Notes. This syntax used to work on 11.0 and I just noticed it during one of our module's migration to Odoo 12.0. Was this feature dropped and it no longer works? Or it is expected to work and it is a bug?

Also, I tried other ways to make it work. So If I change group by context from `['res_model_id', 'res_id']` to `'res_model_id: res_id'`, it won't explode on view load. But if I try to group by that filter, it will throw an exception saying: 
`
Invalid "order" specified. A valid "order" specification is a comma-separated list of valid field names (optionally followed by asc/desc for the direction)
`
So if I understood message correctly, you need to separate it by comma (though, it probably means to use a list, but it does not work either). So I tried `'res_model_id, res_id'`. But then it throwed me same error as showed in my XML sample where I used list of field names. 

So either message is misleading what to do, or this feature is not working correctly?

P.S. you can also check out attached video to see how it behaves when I change group by context (I do same thing as I described here).

[groupby-bug.ogv.zip](https://github.com/odoo/odoo/files/3142665/groupby-bug.ogv.zip)

**Comment by Yenthe666** [comment]
@rco-odoo any chance you can shed some light on this?

**Comment by obayit** [comment]
I am also affected by this. My use case is that, I want to (make WBS on tasks) group project.task by multiple levels,
I set a new level model, with a parent field. And add 10 fields to the task which are its level_id, and the other 9 are related = 'level_id.parent_id', related='level_id.parent_id.parent_id' ..etc
Anyhow I don't see the group_by used on more than one field in all Odoo addons, but it says on the documentation that it should work. But this is a real world case in which the group_by on multiple fields is needed.

**Comment by litnimax** [comment]
The same here. 
```
                    <filter string="Area &amp;Project"
                            domain="[]" name="by_area_and_project"
                            context="{'group_by': ['area', 'project'] }"/>                                                
```
Works on 11.0 and fails on 12.0.

**Comment by oerp-odoo** [comment]
@erp27 can you make pull request for this fix? Would be useful to fix it for everyone.

**Comment by albertopoljak** [comment]
14&15 is impacted too, any solutions?

**Comment by domibarton** [comment]
> 14&15 is impacted too, any solutions? Edit: Nvm switched to searchpanel as alternative

Can you shed some light on this? How did you solve it?

**Comment by albertopoljak** [comment]
> > 14&15 is impacted too, any solutions? Edit: Nvm switched to searchpanel as alternative
> 
> Can you shed some light on this? How did you solve it?

I didn't solve it, the original issue is still present.
Instead I used Odoo `searchpanel` view as an alternative, it gives me a menu on the side with groupings thus simplifying user experience, something I wanted to archive with what this issue is about but it's bugged so I dropped it.

For my case the searchpanel was even better.
