### ISSUE TITLE
Problem during new module installation

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#33164]
Impacted versions:
**12**

Steps to reproduce:
Install the module Project timeline downloaded from https://apps.odoo.com/apps/modules

Current behavior:
Error when installing
**Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1109, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field 'billable_type' used in attributes must be present in view but is missing:
 - 'billable_type' in attrs="{'column_invisible': ['|', ('parent.is_project_map_empty', '=', True), ('parent.billable_type', '!=', 'employee_rate')]}"

Contexte de l'erreur :
Vue `project.task.form`
[view_id: 2126, xml_id: n/a, model: project.task, parent_id: 401]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Erreur lors de la validation de la contrainte\n\nField \'billable_type\' used in attributes must be present in view but is missing:\n - \'billable_type\' in attrs="{\'column_invisible\': [\'|\', (\'parent.is_project_map_empty\', \'=\', True), (\'parent.billable_type\', \'!=\', \'employee_rate\')]}"\n\nContexte de l\'erreur :\nVue `project.task.form`\n[view_id: 2126, xml_id: n/a, model: project.task, parent_id: 401]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Erreur lors de la validation de la contrainte

Field 'billable_type' used in attributes must be present in view but is missing:
 - 'billable_type' in attrs="{'column_invisible': ['|', ('parent.is_project_map_empty', '=', True), ('parent.billable_type', '!=', 'employee_rate')]}"

Contexte de l'erreur :
Vue `project.task.form`
[view_id: 2126, xml_id: n/a, model: project.task, parent_id: 401]
None" while parsing /opt/odoo12/odoo/addons/project_timeline/views/project_task_view.xml:47, near
<record id="view_task_form2" model="ir.ui.view">
        <field name="name">project.task.form</field>
        <field name="model">project.task</field>
        <field name="inherit_id" ref="project.view_task_form2"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='date_assign']" position="before">
                <field name="date_start"/>
                <field name="date_end"/>
            </xpath>
        </field>
    </record>**

Expected behavior:
Module installs without errors

**Comment by pedrobaeza** [comment]
Incorrect place for this.
