### ISSUE TITLE
base_automation error "'<=' not supported between instances of 'datetime.datetime' and 'bool'"

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#33225]
Impacted versions: 11

Steps to reproduce: run base action rule

Current behavior: error

Expected behavior:

Video/Screenshot link (optional):

after setting up some automatic actions I got this error:

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\tools\safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base_automation\models\base_automation.py", line 356, in _check
    if last_run <= action_dt < now:
TypeError: '<=' not supported between instances of 'datetime.datetime' and 'bool'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "w:\odoo\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "w:\odoo\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\ir\ir_cron.py", line 76, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\ir\ir_actions.py", line 554, in run
    res = func(action, eval_context=eval_context)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\website\models\ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base\ir\ir_actions.py", line 430, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "w:\odoo\Odoo 11.0\server\odoo\tools\safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "w:\odoo\Odoo 11.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "w:\odoo\Odoo 11.0\server\odoo\tools\safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "w:\odoo\Odoo 11.0\server\odoo\addons\base_automation\models\base_automation.py", line 356, in _check
    if last_run <= action_dt < now:
ValueError: <class 'TypeError'>: "'<=' not supported between instances of 'datetime.datetime' and 'bool'" while evaluating
'model._check(True)'

**Comment by nhomar** [comment]
This is not a bug, it is a check in the framework to avoid compare pears with apples.
