### ISSUE TITLE
[12.0] Can't create address on contact(res.partner) neither link contact to a contact company

### ISSUE THREAD

**Issue by altoch** [odoo/odoo#33481]
Impacted versions:
12.0
Steps to reproduce:
Create an  address or link a contact to an existing contact
Current behavior:
Create an  address or link a contact to an existing contact
Throws error

Expected behavior:

Crate the address or link the contact.

Video/Screenshot link (optional):

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_partner.py", line 571, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo12/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo12/odoo/addons/mail/models/mail_activity.py", line 578, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3307, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3434, in _write
    field.write(other, vals[field.name])
  File "/opt/odoo12/odoo/odoo/fields.py", line 2526, in write
    flush()
  File "/opt/odoo12/odoo/odoo/fields.py", line 2487, in flush
    comodel.create(vals_list)
  File "<decorator-gen-84>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_partner.py", line 598, in create
    partner._fields_sync(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_partner.py", line 495, in _fields_sync
    self._commercial_sync_from_company()
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_partner.py", line 473, in _commercial_sync_from_company
    sync_vals = commercial_partner.with_prefetch()._update_fields_values(self._commercial_fields())
  File "/opt/odoo12/odoo/odoo/addons/base/models/res_partner.py", line 430, in _update_fields_values
    for fname in fields:
TypeError: 'NoneType' object is not iterable

```

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by altoch** [comment]
Just found the conflicting module, it's sale_stock_picking_blocking from OCA.
Closing, not related.
