### ISSUE TITLE
[12.0] Validation error (Document is empty) when trying to save customized SCSS

### ISSUE THREAD

**Issue by ahukkanen** [odoo/odoo#33545]
Impacted versions: 12.0

Steps to reproduce:

- Create an Odoo instance with the website and eCommerce modules installed.
- Go to the home page
- Click "Customize"
- Click "HTML/CSS Editor"
- Change the mode to "SCSS (CSS)"
- Pick *any* asset
- Click enter and backspace anywhere in the opened SCSS file (you don't have to do any actual customizations, just do any change)
- Click "Save"

Here is a list of all the installed modules:
![odoo-installed](https://user-images.githubusercontent.com/864340/58128593-b0e36100-7c20-11e9-819e-46879a7829bc.png)

Current behavior:

Produces the attached error popup (below)

Expected behavior:

Saves the CSS/SCSS and adds the customization.

Video/Screenshot link (optional):

![odoo-error](https://user-images.githubusercontent.com/864340/58128667-d4a6a700-7c20-11e9-8742-3d6ec51d5a06.png)

The error visible in the console is extracted to text here:

<details>
<summary>Traceback (most recent call last):... [click for more]</summary>
<pre>
<code>
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 343, in _check_xml
    view_arch = etree.fromstring(view.arch.encode('utf-8'))
  File "src/lxml/etree.pyx", line 3211, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web_editor/controllers/main.py", line 458, in save_scss
    IrUiView.create(new_view)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-32>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 1109, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 54, in write
    super(View, view).write(vals)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo-server/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo-server/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Virhe rajoitteen tarkistuksessa\n\nDocument is empty, line 1, column 1', None)
</code>
</pre>
</details>

I extracted the data using the logger that it was trying to save:

```
{
  'name': '/website/static/src/scss/website.custom.web.assets_frontend.scss',
  'key': 'web_editor.scss_623272',
  'mode': 'extension',
  'inherit_id': 774,
  'arch': """
    <data inherit_id="website.assets_frontend" name="/website/static/src/scss/website.custom.web.assets_frontend.scss">
        <xpath expr="//link[@href='/website/static/src/scss/website.scss']" position="attributes">
            <attribute name="href">/website/static/src/scss/website.custom.web.assets_frontend.scss</attribute>
        </xpath>
    </data>
  """,
  'website_id': 1
}
```

**Comment by ahukkanen** [comment]
For further information, this only happens with the CSS/SCSS customizations, the view customizations all work properly.

**Comment by rdeodoo** [comment]
Thank you for this very nice report, sorry we could not investigate it sooner.

Meanwhile, did the issue get solved? I tried to reproduce it on runbot community 12.0 and it was working as expected, see video: https://drive.google.com/file/d/1O7hxep8QV8Xebt3M9IMgdNAAsOC_7UGN/view

**Comment by ahukkanen** [comment]
Yes, this seems to work now as expected. Tested it locally in few instances and with different UI languages enabled.

It could have been some missing dependency issue or something but hard to say from the error message.
