### ISSUE TITLE
[11][enterprise] account_bank_reconciliation_report: TypeError

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#33656]
**Impacted versions:** v11

**Steps to reproduce:**
Video: https://drive.google.com/file/d/1FeOuPGiaK_Hwfhz0q6gyA7bnK5f81fR0/view 
Tested in http://526923-11-0-debc7a.runbot16.odoo.com

**Current behavior:**
The following error is shown

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/account_reports/models/account_report.py", line 342, in get_report_informations
    'main_html': self.get_html(options),
  File "/data/build/odoo/addons/account_reports/models/account_report.py", line 513, in get_html
    lines = self.with_context(ctx).get_lines(options, line_id=line_id)
  File "/data/build/odoo/addons/account_reports/models/account_bank_reconciliation_report.py", line 105, in get_lines
    lines.append(self.add_title_line(options, _("Current Balance in GL"), start_amount))
  File "/data/build/odoo/addons/account_reports/models/account_bank_reconciliation_report.py", line 32, in add_title_line
    'columns': [{'name': v} for v in [options['date']['date'], '', self.format_value(amount, line_currency)]],
  File "/data/build/odoo/addons/account_reports/models/account_report.py", line 599, in format_value
    if currency_id.is_zero(value):
  File "/data/build/odoo/addons/base/res/res_currency.py", line 173, in is_zero
    return tools.float_is_zero(amount, precision_rounding=self.rounding)
  File "/data/build/odoo/tools/float_utils.py", line 126, in float_is_zero
    return abs(float_round(value, precision_rounding=epsilon)) < epsilon
  File "/data/build/odoo/tools/float_utils.py", line 73, in float_round
    normalized_value = value / rounding_factor # normalize
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Expected behavior:**
Display the Conciliation report

--------------------------------------
![image](https://user-images.githubusercontent.com/5191766/58371814-d99a7d80-7ee2-11e9-90d0-9155da916881.png)

Here (account_reports/models/account_bank_reconciliation_report.py) after the query is executed the fetchone() only return a 'None' value, when it can not find the account_ids in account_move_line, so 'start_amount' will be 'None, and the error is displayed.

The start_amount must have some value even when fetchone() is None, so it could be something this like:

`start_amount = self._cr.fetchone()[0] or 0.0`

**Comment by goliveirab** [comment]
FYI @luistorresm

**Comment by luistorresm** [comment]
@goliveirab 

Could you make the PR with the fix, please?

Regards

**Comment by C3POdoo** [comment]
Dear @goliveirab,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
