### ISSUE TITLE
[12.0] Full composer throws unhashable list error since last update

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#33712]
Impacted versions: 12.0, latest update

Steps to reproduce: 
- Get latest 12.0 update (all Odoo.sh servers and our local updated servers are behaving this way)
- In any document with send message/log note, click "Full composer"

Current behavior: Odoo throws a TypeError: unhashable type: 'list'

Traceback:

```
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 5478, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/odoo/models.py", line 5331, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/odoo/addons/mail/wizard/mail_compose_message.py", line 371, in onchange_template_id_wrapper
    setattr(self, fname, value)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1002, in __set__
    value = self.convert_to_cache(value, record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 2258, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/home/odoo/src/odoo/odoo/tools/misc.py", line 1051, in __init__
    self._map = OrderedDict((elem, None) for elem in elems)
TypeError: unhashable type: 'list'

```

**Comment by Yenthe666** [comment]
Hi @reinaldoramosarxi,

Thanks for the report! I can confirm that this has been broken:
![image](https://user-images.githubusercontent.com/6352350/58466378-da791c80-8139-11e9-902e-93c2a8c89286.png)


Regards,
Yenthe

**Comment by Yenthe666** [comment]
Issue is also present in V11.

**Comment by tde-banana-odoo** [comment]
It seems a "bug fix" changed the returned result of default_get, making a lot of crash within the composer. Reads like a super nice bug fix :face_with_head_bandage:

**Comment by Yenthe666** [comment]
Otherwise you'd be bored and wouldn't have any work besides of some e-learning anyways, right? 😉 
Looking forward to the fix! Or do you want an OPW escalation?

**Comment by tde-banana-odoo** [comment]
There are already branches working on it (https://github.com/odoo/odoo/pull/33707#issuecomment-496500986 for example). Bugfix team is hard at work on it.

**Comment by nim-odoo** [comment]
Hot fix ongoing at https://github.com/odoo/odoo/pull/33706 and https://github.com/odoo/odoo/pull/33707

**Comment by sswapnesh** [comment]
This has been fixed.

**Comment by Yenthe666** [comment]
V11 at https://github.com/odoo/odoo/pull/33706/commits/78a87e3663fd4417d47ff8bf1c945828f056c699
V12 at https://github.com/odoo/odoo/pull/33707/commits/0e6d6f02497c76fb2df4ce9453a1ccb57344166e
