### ISSUE TITLE
Onsip Odoo Voip throwing error

### ISSUE THREAD

**Issue by EKGreenhouses** [odoo/odoo#33965]
Impacted versions:
v12 
Steps to reproduce:
testing the native onsip voip functions and it throws error
Current behavior:
Error:
Uncaught TypeError: Cannot read property 'remote_target' of undefined

https://www.emeraldkingdomgreenhouse.info/web/content/20781-2a8d78f/web.assets_backend.js:3827
Traceback:
TypeError: Cannot read property 'remote_target' of undefined
    at InviteServerContext.sendRequest (https://www.emeraldkingdomgreenhouse.info/web/content/20781-2a8d78f/web.assets_backend.js:3827:294)
    at InviteServerContext.bye (https://www.emeraldkingdomgreenhouse.info/web/content/20781-2a8d78f/web.assets_backend.js:3826:50)
    at Class.hangup (https://www.emeraldkingdomgreenhouse.info/web/content/20781-2a8d78f/web.assets_backend.js:4307:186)
    at Class._onHangupButtonClick (https://www.emeraldkingdomgreenhouse.info/web/content/20781-2a8d78f/web.assets_backend.js:4291:3083)
    at HTMLButtonElement.<anonymous> (https://www.emeraldkingdomgreenhouse.info/web/content/20780-a10d85b/web.assets_common.js:3643:11)
    at HTMLDivElement.dispatch (https://www.emeraldkingdomgreenhouse.info/web/content/20780-a10d85b/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (https://www.emeraldkingdomgreenhouse.info/web/content/20780-a10d85b/web.assets_common.js:865:173)
Expected behavior:
* for it to work

**Comment by pedrobaeza** [comment]
As this is an enterprise module, please put an enterprise ticket at odoo.com/help instead.

**Comment by andrp92** [comment]
Same here. Enterprise ticket #2161684

**Comment by andrp92** [comment]
@Yenthe666 @pedrobaeza

**Comment by C3POdoo** [comment]
Dear @EKGreenhouses,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
