### ISSUE TITLE
Exception: bus.Bus unavailable in odoo12 

### ISSUE THREAD

**Issue by baixinan** [odoo/odoo#33970]
2019-06-07 07:38:36,932 3353 INFO b2 werkzeug: 127.0.0.1 - - [07/Jun/2019 07:38:36] "POST /longpolling/poll HTTP/1.1" 200 - 1 0.000 0.004
2019-06-07 07:38:46,937 3360 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=a2 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:38:46,952 3360 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=b1 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:38:46,964 3360 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=b2 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:38:46,978 3360 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=a1 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:38:47,942 3354 ERROR b2 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/root/baixinan/odoo12/odoo-12.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/root/baixinan/odoo12/odoo-12.0/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/root/baixinan/odoo12/odoo-12.0/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
2019-06-07 07:38:47,943 3354 INFO b2 werkzeug: 127.0.0.1 - - [07/Jun/2019 07:38:47] "POST /longpolling/poll HTTP/1.1" 200 - 1 0.000 0.003
2019-06-07 07:39:10,680 3361 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=a2 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:39:10,695 3361 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=b1 host=127.0.0.1 port=5432 sslmode=prefer' 
2019-06-07 07:39:10,709 3361 INFO b2 odoo.addons.base.models.ir_cron: Starting job `Post process payment transactions`. 
----------------------------------------------------------------------------------------------
my nginx conf:
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;

	server {
    listen 80;
    server_name www.modelt.cn;
    return	  301 https://$server_name$request_uri;    
	}	
	server {
	 listen 443;
	 server_name www.modelt.cn;
	 
	  # Add Headers for odoo proxy mode
	 proxy_set_header X-Forwarded-Host $host;
	 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	 proxy_set_header X-Forwarded-Proto $scheme;
	 proxy_set_header X-Real-IP $remote_addr;
	 
	 ssl on;
	 ssl_certificate   /etc/nginx/1727569_www.modelt.cn.pem;
	 ssl_certificate_key  /etc/nginx/1727569_www.modelt.cn.key;
	 ssl_session_timeout 5m;
	 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	 ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
	 ssl_prefer_server_ciphers on;
	 
	 
	 location / {  
        proxy_pass        http://127.0.0.1:8069/;  
        
   			proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

        proxy_redirect off;

        # set headers

        proxy_set_header    Host            $host;

        proxy_set_header    X-Real-IP       $remote_addr;

        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header    X-Forwarded-Proto https;
		}  
		  
		location /longpolling {  
		        proxy_pass        http://127.0.0.1:8072/longpolling;  
		        # force timeouts if the backend dies

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

        proxy_redirect off;

        # set headers

        proxy_set_header    Host            $host;

        proxy_set_header    X-Real-IP       $remote_addr;

        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header    X-Forwarded-Proto https;
		}  
		
	}
	
}

#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
----------------------------------------------------------------------------------------------
my odoo.conf:
[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = 127.0.0.1
db_maxconn = 64
db_port = 5432
db_sslmode = prefer
db_user = odoo
db_password = odoo
list_db = True
max_cron_threads = 2
logfile = /root/baixinan/odoo12/odoo-12.0/log/odoo12_portal.log
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
;addons_path = /root/baixinan/odoo12/odoo-12.0/addons
timezone = Asia/Shanghai
xmlrpc_port = 8069
workers = 3
proxy_mode = True
------------------------------------------------------------------------------------------------------
thanks

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you have troubles, you can make a question on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
