### ISSUE TITLE
[POS] add product after receipt reprint

### ISSUE THREAD

**Issue by andrp92** [odoo/odoo#33996]
****reprocuded on runbot****
http://535644-11-0-7b2a4b.runbot19.odoo.com/pos/web/#action=pos.ui
---------------------------------
Impacted versions:
11.0
Steps to reproduce:
Create an order on the pos (with invoice option turned on), pay it, go to a table, press reprint button, go back to the table, try to add a product. 
Current behavior:
The following error shows up: 
Uncaught TypeError: Cannot read property 'add_product' of null
http://535644-11-0-7b2a4b.runbot19.odoo.com/web/content/2060-4d041ad/point_of_sale.assets.js:218
Traceback:
TypeError: Cannot read property 'add_product' of null
    at child.add_product (http://535644-11-0-7b2a4b.runbot19.odoo.com/web/content/2060-4d041ad/point_of_sale.assets.js:218:134)
    at Class.click_product (http://535644-11-0-7b2a4b.runbot19.odoo.com/web/content/2060-4d041ad/point_of_sale.assets.js:372:257)
    at Object.click_product_action (http://535644-11-0-7b2a4b.runbot19.odoo.com/web/content/2060-4d041ad/point_of_sale.assets.js:371:951)
    at HTMLSpanElement.click_product_handler (http://535644-11-0-7b2a4b.runbot19.odoo.com/web/content/2060-4d041ad/point_of_sale.assets.js:367:1738)
Expected behavior:
Should allow to add products or open tablets as usual. 
Video/Screenshot link (optional):
https://youtu.be/LJkCkmQT-wM

**Comment by jayo2005** [comment]
I am having the same issue. Is there a fix for this?

**Comment by C3POdoo** [comment]
Dear @andrp92,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
