### ISSUE TITLE
Unexpected response when validating an account.invoice via XMLRPC API

### ISSUE THREAD

**Issue by marmargar** [odoo/odoo#34037]
Impacted versions: 

Odoo 12.0+e Versión Enterprise (Odoo SaaS)

Steps to reproduce:

When validating an `account.invoice` via XMLRPC API:
```
$response = $models->execute_kw(
	$db,
	$uid,
	$pass,
	'account.invoice',
	'action_invoice_open',
	[80]
);
```
Current behavior:

The action seems to be executed but I'm getting the following response:
```
Traceback (most recent call last):
File "/home/odoo/src/odoo/12.0/odoo/addons/base/controllers/rpc.py", line 63, in xmlrpc_2
  response = self._xmlrpc(service)
File "/home/odoo/src/odoo/12.0/odoo/addons/base/controllers/rpc.py", line 44, in _xmlrpc
  return dumps((result,), methodresponse=1, allow_none=False)
File "/usr/lib/python3.6/xmlrpc/client.py", line 971, in dumps
  data = m.dumps(params)
File "/usr/lib/python3.6/xmlrpc/client.py", line 502, in dumps
  dump(v, write)
File "/usr/lib/python3.6/xmlrpc/client.py", line 524, in __dump
  f(self, value, write)
File "/usr/lib/python3.6/xmlrpc/client.py", line 528, in dump_nil
  raise TypeError("cannot marshal None unless allow_none is enabled")
TypeError: cannot marshal None unless allow_none is enabled
```

If I execute the action on an already validated `account.invoice`, I get the expected response.

Expected behavior:

Should return `true` or `false` depending on the result.

**Comment by pedrobaeza** [comment]
This is because there return is None. Check source code for finding which path makes it to return None instead of True, and possibly creates a PR amending that for returning False.
