### ISSUE TITLE
[12.0] sale: error when creatig sale order without company set

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#34066]
**Impacted versions:**
12.0 at least
**Steps to reproduce:**
Enable multi-company feature. Create sale order without company specified (unset default company before trying to create).
Current behavior:
```python
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 266

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/data/build/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('sale.order(266,).currency_rate', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 747, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 727, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-497>", line 2, in create
  File "/data/build/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/sale/models/sale.py", line 389, in create
    result = super(SaleOrder, self).create(vals)
  File "<decorator-gen-128>", line 2, in create
  File "/data/build/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/data/build/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/models.py", line 3607, in create
    self.recompute()
  File "/data/build/odoo/models.py", line 5270, in recompute
    vals = {n: rec[n] for n in ns}
  File "/data/build/odoo/models.py", line 5270, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/data/build/odoo/models.py", line 5117, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/data/build/odoo/fields.py", line 1074, in determine_value
    self.compute_value(recs)
  File "/data/build/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/data/build/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/data/build/odoo/addons/sale/models/sale.py", line 220, in _compute_currency_rate
    order.currency_rate = self.env['res.currency']._get_conversion_rate(order.company_id.currency_id, order.currency_id, order.company_id, order.date_order)
  File "/data/build/odoo/addons/base/models/res_currency.py", line 184, in _get_conversion_rate
    currency_rates = (from_currency + to_currency)._get_rates(company, date)
  File "/data/build/odoo/addons/base/models/res_currency.py", line 57, in _get_rates
    self._cr.execute(query, (date, company.id, tuple(self.ids)))
  File "/data/build/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/data/build/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: operator does not exist: integer = boolean
LINE 4: ...          AND (r.company_id IS NULL OR r.company_id = false)
                                                               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
**Expected behavior:**
It should either create sale order and correctly compute amounts using sale order currency, or sale order should require company (it should not be optional).

I was able to guess that without company set, SO either would crash, or would compute amounts incorrectly, because I noticed inconsistency here.

That `company_id` field is optional on `sale.order`, yet company is required when converting from one currency to another. For example `res.currency` method `_convert` even does assert for `company` argument. Though from sale order, company is passed like its a required field and is expected to always be set (but for some reason it allows user to make it False - wanted to give global access to some sale orders in multicompany environments?).

Also if you would workaround this bug - to use user company, in my opinion, that would not be correct way, because user could be from some random company and it would compute amounts with rates of that company. And then conversions would be saved on sale order. When other user from different company would see such sale order (without company set), he would see rates from that other company it was set. And it would update again only if user would change dependents fields, that trigger computations (for example, change company or pricelist etc.). So I think it is not good idea to base computed fields on current user.

It looks like correct way would be to force require company on sale order (and then probably correct record rules, because it now allows to access SO for users from any company, if SO does not have company set).

**Video/Screenshot link (optional):**
This bug can easily be reproduced on runbot.odoo.com
You can see video where I was able to reproduce it on runbot: 
[sale-order-company-bug.ogv.zip](https://github.com/odoo/odoo/files/3281039/sale-order-company-bug.ogv.zip)

**Comment by pedrobaeza** [comment]
I think `company_id` should be required.

@dbo-odoo any reason for not being required?

**Comment by Yenthe666** [comment]
and before somebody changes that: that would be a model change in stable 😉

**Comment by pedrobaeza** [comment]
Yes, but this is an extreme case as a bug fixing. It doesn't mean in fact change in DB layout if the condition is not met or you don't update, so I think this can be acceptable.

**Comment by oerp-odoo** [comment]
Also if this bug was since start of 12.0, then you would probably not able to create sale orders without company anyway. Meaning, it would be able to set required constraint on company (no SOs without company set).

**Comment by oerp-odoo** [comment]
Kind of strange fix. So now it will compute incorrectly in multi-company, multi-currency environment with sales orders without company? Is it really more important to not change `company_id` requirement on SO, than to workaround with fix that potentially computes values incorrectly?

Is this going to be improved on future versions at least?
I mean I don't know any company that would use Odoo in a way that it would compute values incorrectly. So this fix basically just hides an error, by paying a price with incorrect computations. In other words, problem itself was not fixed. You still can't use sales orders without company (to avoid incorrect values), but it is now worse, because user might think it is working correctly (no error), when in reality he might get unexpected conversions between currencies.

**Comment by nim-odoo** [comment]
Hum I didn't realize the company was not mandatory on the `res.currency.rate`, I though it was. I'll double check.

**Comment by oerp-odoo** [comment]
@nim-odoo I checked build: http://539968-12-0-b044a6.runbot18.odoo.com/web and actually this change did not even fix error I reported. It still crashes if you try to create sales order without company. So I really don't know what was the reasoning to change the way currency rate was computed?

**Comment by nim-odoo** [comment]
> Is it really more important to not change `company_id` requirement on SO, than to workaround with fix that potentially computes values incorrectly?

In a mono-currency environment, there is no issue to have `company_id` not filled in. Anyway, a better fix should be #34146. As long as all your companies use the same currency and the same rates (i.e. no company set on the currency rates), it should be fine.

Anyway, the philosophy is usually to leave the doors opened to the most flexible configuration. That being said, if you mix currencies and companies without properly setting the company of each object, then you'll probably face inconsistencies at some point.

**Comment by oerp-odoo** [comment]
Well actually there is. As I said before, conversion expects company to be there. So there are holes in sales order, which can cause it to crash (any time it tries to convert to another currency and there is no company, it will crash). And the reason is, because it allows you to create sales order without company. I was able to crash sales order again. it tries to use `_convert` and crashes, because there is no company set.

To reproduce this second crash. Create sales order without company, select pricelist with different currency than company currency. Try to add sales order line. It should crash.

I was able to reproduce an error on this build: http://540197-12-0-opw-2009044-rate-nim-a480fb.runbot24.odoo.com/

Here is traceback:
```python
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 5507, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/build/odoo/models.py", line 5351, in _onchange_eval
    method_res = method(self)
  File "/data/build/odoo/addons/event_sale/models/sale_order.py", line 86, in _onchange_event_ticket_id
    self.event_ticket_id.price, self.order_id.currency_id, self.order_id.company_id, self.order_id.date_order or fields.Date.today())
  File "/data/build/odoo/addons/base/models/res_currency.py", line 200, in _convert
    assert company, "convert amount from unknown company"
AssertionError: convert amount from unknown company
```
Here is video how to reproduce it:
[sale-order-company-bug-2.ogv.zip](https://github.com/odoo/odoo/files/3291050/sale-order-company-bug-2.ogv.zip)


P.S. why sales order does not require company anyway? For example purchase.order or account.invoice does require it. Why sales order is different here? Is there any benefit to it?

**Comment by nim-odoo** [comment]
> And the reason is, because it allows you to create sales order without company. I was able to crash sales order again. It tries to use `_convert` and crashes, because there is no company set.

[The refactoring](https://github.com/odoo/odoo/commit/7a282c99655d4f154ac1808fcb8a70339dc70930) (introduction of `_convert` instead of `compute`) is causing the crashes. Before the refactoring, a SO could have no company set without crashing. That means we need to fix the refactoring, not make the company mandatory on the SO.

If you really want the company to be mandatory on the SO, make it mandatory in the view in a customized module. Problem solved.

**Comment by oerp-odoo** [comment]
Yes I know I can do it myself. Though I wanted to know a reason why its not mandatory. And its not like I want company to be mandatory or not. It does not matter. What I want is it to work correctly. Currently it looks like mandatory company should work more consistently than it being not mandatory. 
But if you fix refactoring problem, maybe it will work in any case then.
