### ISSUE TITLE
Stock: Field access on non-singleton

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#34162]
https://github.com/odoo/odoo/blob/3e46eaca77f16b5cbfb6b058b49cad65f45e6f49/addons/stock/models/stock_warehouse.py#L442

The containing method is potentially called as a non-singleton.

Here is the traceback, though not needed to grasp the error:
```bash
Traceback (most recent call last):
... [ non relevant ]
  File "/opt/odoo/vendor/odoo/cc/addons/stock/models/stock_warehouse.py", line 492, in _create_missing_locations
    sub_locations = self._get_locations_values(vals)
  File "/opt/odoo/vendor/xoe/improvements/purchase_import/models/stock_warehouse.py", line 117, in _get_locations_values
    data = super(StockWarehouse, self)._get_locations_values(vals)
  File "/opt/odoo/vendor/odoo/cc/addons/mrp/models/stock_warehouse.py", line 170, in _get_locations_values
    values = super(StockWarehouse, self)._get_locations_values(vals)
  File "/opt/odoo/vendor/odoo/cc/addons/stock/models/stock_warehouse.py", line 442, in _get_locations_values
    code = vals.get('code') or self.code
  File "/opt/odoo/vendor/odoo/cc/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/opt/odoo/vendor/odoo/cc/odoo/models.py", line 4706, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.warehouse(5, 6, 7, 8, 9, 23, 28)
Error: Expected singleton: stock.warehouse(5, 6, 7, 8, 9, 23, 28)

```

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem in core?

**Comment by sswapnesh** [comment]
> Steps to reproduce the problem in core?

Execute this w/o any custom code
`self.env["stock.warehouse"].search([]).write({})`

Tested on latest DB (With demodata)
```
>>> self.env["stock.warehouse"].search([]).write({})
Traceback (most recent call last):
  File "/home/swapnesh/Workspace/12/odoo/models.py", line 4718, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/swapnesh/Workspace/12/addons/stock/models/stock_warehouse.py", line 129, in write
    warehouses._create_missing_locations(vals)
  File "/home/swapnesh/Workspace/12/addons/stock/models/stock_warehouse.py", line 492, in _create_missing_locations
    sub_locations = self._get_locations_values(vals)
  File "/home/swapnesh/Workspace/12/addons/stock/models/stock_warehouse.py", line 442, in _get_locations_values
    code = vals.get('code') or self.code
  File "/home/swapnesh/Workspace/12/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/home/swapnesh/Workspace/12/odoo/models.py", line 4721, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.warehouse(1, 2, 3)

```

**Comment by blaggacao** [comment]
Not necessary, I guess. It's an obvious error...

**Comment by pedrobaeza** [comment]
OK, then please create the proper PR.

**Comment by sswapnesh** [comment]
> OK, then please create the proper PR.

This https://github.com/odoo/odoo/pull/34164 should be enough to fix this.
Did I missed something?🤔

**Comment by pedrobaeza** [comment]
OK then. As you didn't refer the PR here, I thought it was still pending.

**Comment by sswapnesh** [comment]
It is referenced above. ( And Issue reference on PR too)

**Comment by pedrobaeza** [comment]
@sswapnesh I meant you don't explicitly put a comment here linking the PR (the reference was put when you create the PR), but not notified through mail in this thread. Any way, all clear now.
