### ISSUE TITLE
[12.0] keyerror loading Dutch translations when having l10n_be installed

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#34179]
Impacted versions: 12.0

Steps to reproduce:
1. Install Odoo 12 in English
2. Install `l10n_be` and all accounting modules
3. Install the Dutch language

Current behavior:
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/l10n_multilang/models/l10n_multilang.py", line 140, in lang_install
    coa._process_accounts_translations(company.id, [self.lang], 'name')
  File "/opt/odoo/addons/l10n_multilang/models/l10n_multilang.py", line 77, in _process_accounts_translations
    in_ids, out_ids = self._get_template_from_model(company_id, 'account.account')
  File "/opt/odoo/addons/l10n_multilang/models/l10n_multilang.py", line 115, in _get_template_from_model
    in_records += self.env[model + '.template'].browse(in_xml_ids[name].res_id)
KeyError: 'l10nbe_chart_template_liquidity_transfer'

Coming from
https://github.com/odoo/odoo/blob/979b2de459982088da3639d190b19e303453d5a4/addons/l10n_be/i18n_extra/nl.po#L1278-L1281

Expected behavior: Able to load translations for Dutch when you have `l10n_be` installed

**Comment by Yenthe666** [comment]
@mart-e could it be you forgot to update just this term maybe?
