### ISSUE TITLE
[11.0] website_sale installation after account breaks product testing for european localization

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [odoo/odoo#34392]
website_sale demo data modifies public pricelist currency set previously by account:

https://github.com/odoo/odoo/blob/11.0/addons/website_sale/data/demo.xml#L724
```xml
        <record model="product.pricelist" id="product.list0">
            <field name="selectable" eval="True" />
            <field name="website_id" ref="website.default_website" />
            <field name="sequence">3</field>
            <field name="currency_id" ref="base.USD"/>
        </record>
```

https://github.com/odoo/odoo/blob/11.0/addons/account/models/chart_template.py#L904
```python
        # When we install the CoA of first company, set the currency to price types and pricelists
        if company.id == 1:
            for reference in ['product.list_price', 'product.standard_price', 'product.list0']:
                try:
                    tmp2 = self.env.ref(reference).write({'currency_id': self.currency_id.id})
                except ValueError:
                    pass
```

Impacted versions:
11.0
Steps to reproduce:

1. Create a new database with demo data and an european country with localization (e.g. Spain, l10n_es)
1. Install account module
2. Install website_sale module
3. Test product module

Current behavior:
```bash
odoo.addons.product.tests.test_pricelist running tests.
FAIL
Module product: 2 failures, 0 errors
FAIL
FAIL: test_10_discount (odoo.addons.product.tests.test_pricelist.TestPricelist)
Traceback (most recent call last):
`   File "/home/odoo/addons/product/tests/test_pricelist.py", line 47, in test_10_discount
`     self.assertEqual(usb_adapter_with_pricelist.price, usb_adapter_without_pricelist.price*0.9)
` AssertionError: 63.0 != 96.318
FAIL: test_20_pricelist_uom (odoo.addons.product.tests.test_pricelist.TestPricelist)
Traceback (most recent call last):
`   File "/home/odoo/addons/product/tests/test_pricelist.py", line 101, in test_20_pricelist_uom
`     test_unit_price(2, kg, tonne_price / 1000.0)
`   File "/home/odoo/addons/product/tests/test_pricelist.py", line 98, in test_unit_price
`     self.assertAlmostEqual(unit_price, expected_unit_price, msg='Computed unit price is wrong')
` AssertionError: 0.15289 != 0.1 within 7 places : Computed unit price is wrong
FAILED
```
Expected behavior:
Module product: 0 failures, 0 errors
Video/Screenshot link (optional):

Any ideas on how should i proceed? Thank you.

**Comment by C3POdoo** [comment]
Dear @ljsalvatierra-binovo,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
