### ISSUE TITLE
load could not load template

### ISSUE THREAD

**Issue by hugo49** [odoo/odoo#34480]
Impacted versions: 12

I install website_logo sour my odoo. 
I am blocked by one or more errors. 
https://www.odoo.com/apps/modules/12.0/website_logo/
​What can I do? 

None 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).name', None) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 3 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.partner(3,).name', None) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn 
return compiled(self, append, new, options, log) 
File "", line 1, in template_website_layout_8935 
File "", line 2, in body_call_content_8934 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1098, in determine_value 
self.compute_value(recs) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in compute_value 
self._compute_value(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in _compute_value 
self.compute(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 612, in _compute_related 
record[self.name] = value[self.related_field.name] 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 5117, in _getitem_ 
return self._fields[key].__get__(self, type(self)) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.ProgrammingError: column res_partner.github_team_qty does not exist 
LINE 1: ...partner"."picking_warn_msg" as "picking_warn_msg","res_partn... 

During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).groups_id', None) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 372, in get_template 
document = options.get('load', self.load)(template, options) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 122, in load 
template = env['ir.ui.view'].read_template(name) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1174, in read_template 
return self._read_template(self.get_view_id(xml_id)) 
File "", line 2, in _read_template 
File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 86, in lookup 
key = key0 + self.key(*args, **kwargs) 
File "", line 1, in 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1180, in read 
res = super(UsersView, self).read(other_fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 418, in read 
return super(Users, self).read(fields=fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 369, in _read_from_database 
super(Users, self)._read_from_database(field_names, inherited_field_names) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block 
load could not load template 
Template: website.layout 
QWeb 
Message d'erreur : 
load could not load template 
Template: website.layout 
Une erreur est survenue pendant le rendu du template website.layout 
Retraçage 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 

During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).name', None) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 3 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.partner(3,).name', None) 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn 
return compiled(self, append, new, options, log) 
File "", line 1, in template_website_layout_8935 
File "", line 2, in body_call_content_8934 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1098, in determine_value 
self.compute_value(recs) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in compute_value 
self._compute_value(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in _compute_value 
self.compute(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 612, in _compute_related 
record[self.name] = value[self.related_field.name] 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 5117, in _getitem_ 
return self._fields[key].__get__(self, type(self)) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.ProgrammingError: column res_partner.github_team_qty does not exist 
LINE 1: ...partner"."picking_warn_msg" as "picking_warn_msg","res_partn... 
^ 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).groups_id', None) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 372, in get_template 
document = options.get('load', self.load)(template, options) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 122, in load 
template = env['ir.ui.view'].read_template(name) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1174, in read_template 
return self._read_template(self.get_view_id(xml_id)) 
File "", line 2, in _read_template 
File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 86, in lookup 
key = key0 + self.key(*args, **kwargs) 
File "", line 1, in 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1180, in read 
res = super(UsersView, self).read(other_fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 418, in read 
return super(Users, self).read(fields=fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 369, in _read_from_database 
super(Users, self)._read_from_database(field_names, inherited_field_names) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _dispatch 
result = request.dispatch() 
File "/usr/lib/python3/dist-packages/odoo/http.py", line 835, in dispatch 
r = self._call_function(**self.params) 
File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function 
return checked_call(self.db, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper 
return f(dbname, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in checked_call 
result.flatten() 
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1270, in flatten 
self.response.append(self.render()) 
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1263, in render 
return env["ir.ui.view"].render_template(self.template, self.qcontext) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1284, in render_template 
return self.browse(self.get_view_id(template)).render(values, engine) 
File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 319, in render 
return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext) 
File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render 
return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1293, in render 
return self.env[engine].render(self.id, qcontext) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 59, in render 
result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 274, in render 
self.compile(template, options)(self, body.append, values or {}) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 348, in _compiled_fn 
raise e 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn 
return compiled(self, append, new, options, log) 
File "", line 1, in template_2792_8863 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 351, in _compiled_fn 
element, document = self.get_template(template, options) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 376, in get_template 
raise QWebException("load could not load template", name=template) 
odoo.addons.base.models.qweb.QWebException: None 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).name', None) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 3 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.partner(3,).name', None) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn 
return compiled(self, append, new, options, log) 
File "", line 1, in template_website_layout_8935 
File "", line 2, in body_call_content_8934 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1098, in determine_value 
self.compute_value(recs) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in compute_value 
self._compute_value(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1045, in _compute_value 
self.compute(records) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 612, in _compute_related 
record[self.name] = value[self.related_field.name] 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 5117, in _getitem_ 
return self._fields[key].__get__(self, type(self)) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.ProgrammingError: column res_partner.github_team_qty does not exist 
LINE 1: ...partner"."picking_warn_msg" as "picking_warn_msg","res_partn... 
^ 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get 
value = self._data[key][field][record._ids[0]] 
KeyError: 2 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in _get_ 
value = record.env.cache.get(record, self) 
File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get 
raise CacheMiss(record, field) 
odoo.exceptions.CacheMiss: ('res.users(2,).groups_id', None) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 372, in get_template 
document = options.get('load', self.load)(template, options) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 122, in load 
template = env['ir.ui.view'].read_template(name) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1174, in read_template 
return self._read_template(self.get_view_id(xml_id)) 
File "", line 2, in _read_template 
File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 86, in lookup 
key = key0 + self.key(*args, **kwargs) 
File "", line 1, in 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 985, in _get_ 
self.determine_value(record) 
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1088, in determine_value 
record._prefetch_field(self) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2836, in _prefetch_field 
result = records.read([f.name for f in fs], load='_classic_write') 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1180, in read 
res = super(UsersView, self).read(other_fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 418, in read 
return super(Users, self).read(fields=fields, load=load) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2774, in read 
self._read_from_database(stored, inherited) 
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 369, in _read_from_database 
super(Users, self)._read_from_database(field_names, inherited_field_names) 
File "/usr/lib/python3/dist-packages/odoo/models.py", line 2901, in _read_from_database 
cr.execute(query_str, params) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper 
return f(self, args, *kwargs) 
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute 
res = self._obj.execute(query, params) 
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block 
load could not load template 
Template: website.layout

**Comment by pedrobaeza** [comment]
This is not something that belongs here, but it's due to a third party module. Any way, I can say that the problem with that third party module is that you have modified the base template, and thus, the error.

Closing by what stated above.
