### ISSUE TITLE
[12.0] Error in  hr_timesheet_attendance pivot

### ISSUE THREAD

**Issue by i-vyshnevska** [odoo/odoo#34612]
Impacted versions:
  12
Steps to reproduce:
   install hr_timesheet_attendance, go to Timesheet->Reporting-> Timesheet Attendance
open one item in pivot
![Screenshot(1)](https://user-images.githubusercontent.com/45663766/60716045-18324780-9f27-11e9-86db-d6c26d446e23.png)

 hit the first line
![Screenshot(2)](https://user-images.githubusercontent.com/45663766/60716065-21231900-9f27-11e9-8846-79ae7f3b4447.png)

Current behavior:
   Error raised
Expected behavior:
  analytic line opened in form view
Video/Screenshot link (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 745, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 732, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 2840, in read
    self._read_from_database(stored, inherited)
  File "/data/build/odoo/models.py", line 2988, in _read_from_database
    values = [convert(value, target, validate=False) for value in values]
  File "/data/build/odoo/models.py", line 2988, in <listcomp>
    values = [convert(value, target, validate=False) for value in values]
  File "/data/build/odoo/fields.py", line 1670, in convert_to_cache
    raise TypeError("%s (field %s) must be string or date, not datetime." % (value, self))
TypeError: 2019-07-01 00:00:00+00:00 (field hr.timesheet.attendance.report.date) must be string or date, not datetime.

**Comment by sswapnesh** [comment]
Fix at https://github.com/odoo/odoo/pull/34046

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/34741/commits/b471ec98ed64403075ff6409be6359673b34d20c PR https://github.com/odoo/odoo/pull/34741
Cc: @LucasLefevre
