### ISSUE TITLE
[13] Error in res.users

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#34636]
Impacted versions: 13

Steps to reproduce:

Current behavior:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/api.py", line 696, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/api.py", line 683, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/models.py", line 5618, in onchange
    record = self.new(values, origin=self)
  File "/data/build/odoo/models.py", line 5047, in new
    record._update_cache(values, validate=False)
  File "/data/build/odoo/models.py", line 4905, in _update_cache
    field_values = [(fields[name], value) for name, value in values.items()]
  File "/data/build/odoo/models.py", line 4905, in <listcomp>
    field_values = [(fields[name], value) for name, value in values.items()]
Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/V34rF9eG61w

**Comment by Yenthe666** [comment]
Ehh version 13 is not out yet and is still in full development. Usually it has no point reporting them untill Odoo is atleast in beta.

Regards,
Yenthe
