### ISSUE TITLE
[12.0] hr_timesheet_attendance upgrade error

### ISSUE THREAD

**Issue by Axel-G** [odoo/odoo#34840]
```
2019-07-12 22:29:43,283 43 ERROR dbase odoo.sql_db: bad query: b'CREATE OR REPLACE VIEW hr_timesheet_attendance_report AS (\n            SELECT\n                max(id) AS id,\n                t.user_id,\n                t.date,\n                coalesce(sum(t.attendance), 0) AS total_attendance,\n                coalesce(sum(t.timesheet), 0) AS total_timesheet,\n                coalesce(sum(t.attendance), 0) - coalesce(sum(t.timesheet), 0) as total_difference\n            FROM (\n                SELECT\n                    -hr_attendance.id AS id,\n                    resource_resource.user_id AS user_id,\n                    hr_attendance.worked_hours AS attendance,\n                    NULL AS timesheet,\n                    hr_attendance.check_in::date AS date\n                FROM hr_attendance\n                LEFT JOIN hr_employee ON hr_employee.id = hr_attendance.employee_id\n                LEFT JOIN resource_resource on resource_resource.id = hr_employee.resource_id\n            UNION ALL\n                SELECT\n                    ts.id AS id,\n                    ts.user_id AS user_id,\n                    NULL AS attendance,\n                    ts.unit_amount AS timesheet,\n                    ts.date AS date\n                FROM account_analytic_line AS ts\n                WHERE ts.project_id IS NOT NULL\n            ) AS t\n            GROUP BY t.user_id, t.date\n            ORDER BY t.date\n        )\n        '
ERROR: cannot change data type of view column "date" from timestamp with time zone to date
 
2019-07-12 22:29:43,291 43 WARNING dbase odoo.modules.loading: Transient module states were reset 
2019-07-12 22:29:43,293 43 ERROR dbase odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 297, in init_models
    model.init()
  File "/usr/share/odoo/odoo/addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py", line 51, in init
    """ % self._table)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: cannot change data type of view column "date" from timestamp with time zone to date

2019-07-12 22:29:43,294 43 CRITICAL dbase odoo.service.server: Failed to initialize database `dbase`. 
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 297, in init_models
    model.init()
  File "/usr/share/odoo/odoo/addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py", line 51, in init
    """ % self._table)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: cannot change data type of view column "date" from timestamp with time zone to date

2019-07-12 22:29:43,295 43 INFO dbase odoo.service.server: Stopping gracefully 
```

**Comment by pedrobaeza** [comment]
It is saying that a change of column type is being done. In which Odoo commit this change has been performed?

**Comment by sswapnesh** [comment]
Seems regression of https://github.com/odoo/odoo/pull/34741/commits/937acb53f6fe84912a04874ad35d18399286cbc5  (PR https://github.com/odoo/odoo/pull/34741)
Cc: @LucasLefevre

**Comment by pedrobaeza** [comment]
Yeah, it seems so. Tagging.

**Comment by LucasLefevre** [comment]
Hello @Axel-G ,
Thanks for reporting the issue.
We decided to keep the fix despite this module upgrade problem.
If you are on prem, to upgrade your module, you need to first drop the postgresql view.
`DROP VIEW hr_timesheet_attendance_report;`

**Comment by pedrobaeza** [comment]
@LucasLefevre I think you must bump version number and include a migration script performing that query.

**Comment by gdgellatly** [comment]
OMFG, "we" decided to break everyones upgrades, and put the advice to fix in a github issue. I'd love to know who "we" is. A -u base takes 20 minutes or so on a good day, just wasting peoples time. Lucky I already knew the issue was here so not wasting any more time trying to work out why.

**Comment by pedrobaeza** [comment]
FYI a patch is in progress in #34851

**Comment by pedrobaeza** [comment]
PR has been merged, so closing this.
