### ISSUE TITLE
Workflow integrity error when creating sales invoice

### ISSUE THREAD

**Issue by mejerome** [odoo/odoo#349]
When creating a sales invoice from a sale order, a workflow integrity error displays saying:
"duplicate key value violates unique constraint "wkf_witm_trans_inst_id_trans_id_key"
DETAIL: Key (inst_id, trans_id)=(33, 36) already exists."

Backend log:
2014-06-05 08:53:57,186 14266 ERROR testing openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/Users/jerometabiri/PycharmProjects/odoo/openerp/http.py", line 464, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/jerometabiri/PycharmProjects/odoo/openerp/http.py", line 483, in dispatch
    result = self._call_function(**self.params)
  File "/Users/jerometabiri/PycharmProjects/odoo/openerp/http.py", line 299, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/jerometabiri/PycharmProjects/odoo/openerp/service/model.py", line 151, in wrapper
    raise openerp.osv.orm.except_orm(_('Integrity Error'), inst[0])
except_orm: ('Integrity Error', 'duplicate key value violates unique constraint "wkf_witm_trans_inst_id_trans_id_key"\nDETAIL:  Key (inst_id, trans_id)=(33, 36) already exists.\n')
2014-06-05 08:53:57,187 14266 INFO testing werkzeug: 127.0.0.1 - - [05/Jun/2014 08:53:57] "POST /web/dataset/call_button HTTP/1.1" 200 -

**Comment by Yenthe666** [comment]
Dear @mejerome ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
