### ISSUE TITLE
[Master] crm: creating lead mining request results in traceback

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#34910]
Impacted versions: Master

Steps to reproduce:
1. Go to CRM > Settings > Lead Mining Requests and create a new item with the following values as example:
![image](https://user-images.githubusercontent.com/6352350/61291572-21e16800-a7cf-11e9-943c-ad8b1df3ff08.png)
2. Click on submit.

Current behavior: Traceback:
```
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 92, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 390, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/crm_iap_lead/models/crm_iap_lead_mining_request.py", line 202, in action_submit
    results = self._perform_request()
  File "/data/build/odoo/addons/crm_iap_lead/models/crm_iap_lead_mining_request.py", line 159, in _perform_request
    raise e
  File "/data/build/odoo/addons/crm_iap_lead/models/crm_iap_lead_mining_request.py", line 153, in _perform_request
    response = jsonrpc(endpoint, params=params, timeout=300)
  File "/data/build/odoo/addons/iap/models/iap.py", line 68, in jsonrpc
    raise e
odoo.addons.iap.models.iap.InsufficientCreditError: {"body": "\n        <div class=\"container-fluid\">\n            <div class=\"row\">\n                <div class=\"col-sm-7 col-md-offset-1 mt32 mb32\">\n                    <h2>You do not have enough credits to submit this request.</h2>\n                    Recharge your IAP account and try again.\n                </div>\n            </div>\n        </div>\n    ", "base_url": "https://iap.odoo.com/iap/1/credit", "message": "You don't have enough credits on your account to use this service.", "credit": 10.0, "service_name": "reveal"}
```
Expected behavior:
The lead mining request is submitted.

**Comment by Yenthe666** [comment]
@mart-e I'm not sure who is responsible on this part :)

**Comment by rrahir** [comment]
@Yenthe666  It seems to be an unfortunate side-effect of the refactoring of the crash manager introduced in https://github.com/odoo/odoo/pull/32132 -> fix in progress as it seems
Expected behaviour: the error is properly caught by the crash manager and invites the user to recharge his iap account to use the service.

**Comment by Yenthe666** [comment]
Thanks for the feedback! I'll leave it open as a reminder, both for me and the devs. I'll recheck it in a while again to see if it has been fixed :)

**Comment by sswapnesh** [comment]
Submitting issue for master?🤔

**Comment by Yenthe666** [comment]
Yeah I know, I like being a rebel. 🌵 Since we're slowly closing in on the release (october) I thought it might be a good time to start reporting issues if I see them.

**Comment by mart-e** [comment]
The master is still very unstable. If you really want to test the pre-release, probably a better idea to check the saas-12.3 or saas-12.4, it is already unstable enough ;-)

**Comment by Yenthe666** [comment]
@mart-e so you'd rather have me test 12.3/12.4 and report those here than master?

**Comment by mart-e** [comment]
@Yenthe666 these are also unsupported versions (only the main versions are) but at least a bit more stable than the master

**Comment by kig-odoo** [comment]
Fixed here: https://github.com/odoo/odoo/pull/35111
