### ISSUE TITLE
Unable to use comparison operators in email templates

### ISSUE THREAD

**Issue by alorence** [odoo/odoo#35053]
Impacted versions:
Odoo 12.0-20190424 Community Edition (docker based)

Steps to reproduce:
- Create a fresh database
- Install any module (ex: Sales)
- Enable "developer mode"
- Go to Settings > Technical > Templates and open "Digest: Default main template
- Click on Edit then **enable code view** to directly edit HTML
- Navigate to the line
`% if data['lastweek'][kpi]['margin'] &gt; 0.0:`

- Now edit the line to fix the operator issue. `$gt;` should become `>`
- Save
- Try to send the digest email (from General Settings > Users > Digest Email)

Current behavior:
- The mail is received empty
- Odoo logs show the following error

```
2019-07-22 08:57:00,567 1 INFO default odoo.addons.mail.models.mail_template: Failed to load template '\n<table style="border-collapse:collapse;width: 100%; border-spacing: 0; font-family: Helvetica,Arial,Verdana,sans-serif;">\n    <tbody><tr>\n        <td style="border-collapse: collapse; padding: 0" valign="top" align="center">\n            % set user = ctx.get(\'user\', user)\n            % set company = user.company_id\n            % set data = object.compute_kpis(company, user)\n            % set tips = object.compute_tips(company, user)\n            % set kpi_actions = object.compute_kpis_actions(company, user)\n            % set kpis = data.yesterday.keys()\n            <table style="border-collapse:collapse;width: 100%; max-width: 600px; border-spacing: 0; border: 1px solid #e7e7e7; border-bottom: none; color: #6e7172; line-height: 23px; text-align: left;">\n                <tbody><tr>\n                    <td style="border-collapse: collapse; padding: 10px 40px; text-align: left;">\n                        <strong style="font-weight:bolder;margin-left: -22px; color: #000000; font-size: 22px; line-height: 32px;">${company.name} at a glance</strong>\n                        <div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;color: #000000; font-size: 15px; margin-left:-22px;">${datetime.date.today().strftime(\'%B %d, %Y\')}</div>\n                    </td>\n                    <td style="text-align: right; padding: 10px 40px">\n                        <img style="border-style:none;vertical-align:middle;padding: 0px; margin: 0px; height: auto; width: 80px;" src="/logo.png?company=${company.id}">\n                    </td>\n                </tr>\n                <tr><td colspan="2" style="text-align: center;">\n                    <hr style="border-style:solid none none none;margin:1rem 0 1rem 0;border-top-width:1px;border-top-color:rgba(0, 0, 0, 0.1);border-image-width:1;border-image-source:none;border-image-slice:100%;border-image-repeat:stretch;border-image-outset:0;border-left-width:0px;border-left-color:currentcolor;border-bottom-width:0px;border-bottom-color:currentcolor;border-right-width:0px;border-right-color:currentcolor;overflow-y:visible;overflow-x:visible;height:0px;box-sizing:content-box;background-color: rgb(204,204,204); border: medium none; clear: both; display: block; font-size: 0px; min-height: 1px; line-height: 0; margin: 16px 0px 16px 14px;" width="95%">\n                </td></tr>\n            </tbody></table>\n            % for kpi in kpis:\n                <table style="border-collapse:collapse;border-spacing: 0; width: 100%; max-width: 600px;">\n                    <tbody><tr>\n                        <td style="border-collapse: collapse; background-color: #ffffff; border-left: 1px solid #e7e7e7; border-right: 1px solid #e7e7e7; line-height: 21px; padding: 0 20px 10px 20px; text-align: left;"><br>\n                            <span style="color: #3d466e; font-size: 18px; font-weight: 500; line-height: 23px;">${object.fields_get()[kpi][\'string\']}</span>\n                            %if kpi in kpi_actions:\n                                <span style="float: right;">\n                                    <a href="/web#action=${kpi_actions[kpi]}" style="text-decoration:none;background-color:transparent;color:rgb(77, 119, 143);">View more</a>\n                                </span>\n                            %endif\n                        </td>\n                    </tr>\n                    <tr>\n                        <td style="border-collapse: collapse; margin: 0; padding:0;">\n                            <table style="border-collapse:collapse;width: 100%; border-spacing: 0; background-color: #f9f9f9; border: 1px solid #e7e7e7; border-top: none;">\n                                <tbody><tr>\n                                    <td style="border-collapse: collapse; margin: 0; padding: 0; display: block; border-top: 2px solid #56b3b5;">\n                                        <table style="border-collapse:collapse;width: 100%; max-width: 199px; border-spacing: 0;">\n                                            <tbody><tr>\n                                                <td style="border-collapse: collapse; padding: 20px; text-align: center;">\n                                                    <span style="color: #56b3b5; font-size: 35px; font-weight: bold; text-decoration: none; line-height: 36px;">${data[\'yesterday\'][kpi][kpi]}</span><br>\n                                                    <span style="color: #888888; display: inline-block; font-size: 12px; line-height: 18px; text-transform: uppercase;">Yesterday</span>\n                                                    % if data[\'yesterday\'][kpi][\'margin\'] != 0.0:\n                                                        <span style="color: #888888; display: block; font-size: 12px; line-height: 18px; text-transform: uppercase;">\n                                                            % if data[\'yesterday\'][kpi][\'margin\'] &gt; 0.0:\n                                                                <span style="color: #0bbc22;">▲</span>${"%.2f" % data[\'yesterday\'][kpi][\'margin\']} %\n                                                            % endif\n                                                            % if data[\'yesterday\'][kpi][\'margin\'] &lt; 0.0:\n                                                                <span style="color: #ff0000;">▼</span>${"%.2f" % data[\'yesterday\'][kpi][\'margin\']} %\n                                                            % endif\n                                                        </span>\n                                                    % endif\n                                                </td>\n                                            </tr>\n                                        </tbody></table>\n                                    </td>\n                                    <td style="border-collapse: collapse; margin: 0; padding: 0; border-top: 2px solid #9a5b82;">\n                                        <table style="border-collapse:collapse;width: 100%; max-width: 199px; border-spacing: 0; margin: 0; padding: 0;">\n                                            <tbody><tr>\n                                                <td style="border-collapse: collapse; padding: 20px; text-align: center;">\n                                                    <span style="color: #9a5b82; font-size: 35px; font-weight: bold; text-decoration: none; line-height: 36px;">${data[\'lastweek\'][kpi][kpi]}</span><br>\n                                                    <span style="color: #888888; display: inline-block; font-size: 12px; line-height: 18px; text-transform: uppercase;">Last 7 Days</span>\n                                                    % if data[\'lastweek\'][kpi][\'margin\'] != 0.0:\n                                                        <span style="color: #888888; display: block; font-size: 12px; line-height: 18px; text-transform: uppercase;">\n                                                            % if data[\'lastweek\'][kpi][\'margin\'] &gt; 0.0:\n                                                                <span style="color: #0bbc22;">▲</span>${"%.2f" % data[\'lastweek\'][kpi][\'margin\']} %\n                                                            % endif\n                                                            % if data[\'lastweek\'][kpi][\'margin\'] &lt; 0.0:\n                                                                <span style="color: #ff0000;">▼</span>${"%.2f" % data[\'lastweek\'][kpi][\'margin\']} %\n                                                            %endif\n                                                        </span>\n                                                    %endif\n                                                </td>\n                                            </tr>\n                                        </tbody></table>\n                                    </td>\n                                    <td style="border-collapse: collapse; margin: 0; padding: 0; border-top: 2px solid #56b3b5;">\n                                        <table style="border-collapse:collapse;width: 100%; max-width: 199px; border-spacing: 0; margin: 0; padding: 0;">\n                                            <tbody><tr>\n                                                <td style="border-collapse: collapse; margin: 0; padding: 20; text-align: center;">\n                                                    <span style="color: #56b3b5; font-size: 35px; font-weight: bold; text-decoration: none; line-height: 36px">${data[\'lastmonth\'][kpi][kpi]}</span><br>\n                                                    <span style="color: #888888; display: inline-block; font-size: 12px; line-height: 18px; text-transform: uppercase;">Last 30 Days</span>\n                                                    % if data[\'lastmonth\'][kpi][\'margin\'] != 0.0:\n                                                        <span style="color: #888888; display: block; font-size: 12px; line-height: 18px; text-transform: uppercase;">\n                                                             % if data[\'lastmonth\'][kpi][\'margin\'] &gt; 0.0:\n                                                                <span style="color: #0bbc22;">▲</span>${"%.2f" % data[\'lastmonth\'][kpi][\'margin\']} %\n                                                            % endif\n                                                            % if data[\'lastmonth\'][kpi][\'margin\'] &lt; 0.0:\n                                                                <span style="color: #ff0000;">▼</span>${"%.2f" % data[\'lastmonth\'][kpi][\'margin\']} %\n                                                            %endif\n                                                        </span>\n                                                    %endif\n                                                </td>\n                                            </tr>\n                                        </tbody></table>\n                                    </td>\n                                </tr>\n                            </tbody></table>\n                        </td>\n                    </tr>\n                </tbody></table>\n            % endfor\n            % if tips:\n                <table style="border-collapse:collapse;width: 100%; max-width: 600px; margin-top: 5px; border: 1px solid #e7e7e7;">\n                    <tbody><tr>\n                        <td style="border-collapse: collapse; background-color: #ffffff; line-height: 21px; padding: 0px 20px;"><br>\n                            <div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;color: #3d466e; line-height: 23px;">${ctx[\'tip_description\']|safe}</div>\n                        </td>\n                    </tr>\n                </tbody></table>\n            % endif\n            <table style="border-collapse:collapse;width: 100%; max-width: 600px; margin-top: 5px; border: 1px solid #e7e7e7;">\n                <tbody><tr>\n                    <td style="border-collapse: collapse; background-color: #ffffff; line-height: 21px; padding: 0 20px 10px 20px; text-align: center;"><br>\n                        <div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;color: #3d466e; font-size: 16px; font-weight: 600; line-height: 23px;">Run your business from anywhere with Odoo Mobile.</div>\n                    </td>\n                </tr>\n                <tr>\n                    <td>\n                        <div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;text-align: center;"><a href="https://play.google.com/store/apps/details?id=com.odoo.mobile" target="_blank" style="text-decoration:none;background-color:transparent;color:rgb(77, 119, 143);"><img src="/digest/static/src/img/google_play.png" style="border-style:none;vertical-align:middle;display: inline-block; height: 30px; margin-left: auto; margin-right: 12px;"></a><a href="https://itunes.apple.com/us/app/odoo/id1272543640" target="_blank" style="text-decoration:none;background-color:transparent;color:rgb(77, 119, 143);"><img src="/digest/static/src/img/app_store.png" style="border-style:none;vertical-align:middle;display: inline-block; height: 30px; margin-left: 12px; margin-right: auto;"></a>\n                        </div>\n                    </td>\n                </tr>\n            </tbody></table>\n            <table style="border-collapse:collapse;margin-top: 5px; border: 1px solid #e7e7e7; font-size: 15px; width: 100%; max-width: 600px;">\n                <tbody><tr>\n                    <td style="border-collapse: collapse; margin: 0; padding: 10px 20px;">\n                        % if user.has_group(\'base.group_system\'): \n                            <div style="font-size:13px;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;margin-top: 20px;"> \n                                Want to customize the email?\n                                <a href="/web#view_type=form&amp;model=digest.digest&amp;id=${object.id}" target="_blank" style="text-decoration:none;background-color:transparent;color: #875A7B;">Choose the metrics you care about</a>\n                            </div>\n                            <br>\n                        % endif\n                        <p style="margin:0px 0 1rem 0;font-family:&quot;Lucida Grande&quot;, Helvetica, Verdana, Arial, sans-serif;font-size: 11px; margin-top: 10px;">\n                            <strong style="font-weight:bolder;">\n                                Sent by\n                                <a href="https://www.odoo.com" style="background-color:transparent;color:rgb(77, 119, 143);text-decoration: none; color: #875A7B;">Odoo</a> - <a href="/web#view_type=form&amp;model=digest.digest&amp;id=${object.id}" target="_blank" style="text-decoration:none;background-color:transparent;color: #888888;">Unsubscribe</a>\n                            </strong>\n                        </p>\n                    </td>\n                </tr>\n            </tbody></table>\n        </td>\n    </tr>\n</tbody></table>\n        '
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 315, in _render_template
    template = mako_env.from_string(tools.ustr(template_txt))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 49, in template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 121, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 189, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 156, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 121, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 203, in parse_if
    'name:endif'))
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 156, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 121, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 201, in parse_if
    node.test = self.parse_tuple(with_condexpr=False)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 616, in parse_tuple
    args.append(parse())
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 608, in <lambda>
    parse = lambda: self.parse_expression(with_condexpr=False)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 391, in parse_expression
    return self.parse_or()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 408, in parse_or
    left = self.parse_and()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 417, in parse_and
    left = self.parse_not()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 428, in parse_not
    return self.parse_compare()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 432, in parse_compare
    expr = self.parse_add()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 454, in parse_add
    left = self.parse_sub()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 464, in parse_sub
    left = self.parse_concat()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 474, in parse_concat
    args = [self.parse_mul()]
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 484, in parse_mul
    left = self.parse_div()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 494, in parse_div
    left = self.parse_floordiv()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 504, in parse_floordiv
    left = self.parse_mod()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 514, in parse_mod
    left = self.parse_pow()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 524, in parse_pow
    left = self.parse_unary()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 543, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 668, in parse_postfix
    node = self.parse_subscript(node)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 710, in parse_subscript
    self.stream.expect('rbracket')
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 378, in expect
    next(self)
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 349, in __next__
    self.current = next(self._iter)
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 552, in wrap
    for lineno, token, value in stream:
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 734, in tokeniter
    name, filename)
jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 4907
2019-07-22 08:57:00,802 1 INFO default odoo.addons.mail.models.mail_mail: Mail with ID 11 and Message-Id '<617330557198078.1563785820.590140581130981-openerp-1-digest.digest@5bf9a27cc6a9>' successfully sent
```

Expected behavior:
- The template is correctly rendered, the mail received contains correct information (= Is not empty)

Video/Screenshot link (optional):
None

Additional information :
Going back to template edition shows the operator is always replaced by the equivalent HTML code, even when edited in *code view*.
Closed issue #30819 mention the exact same issue, but has been closed because modifying from code editor should fix the issue. This is not the case here, as edition from code view actually replace `<` and `>` chars by `&lt;` and `&gt;`.

Regards

**Comment by pedrobaeza** [comment]
The error you are facing is:
```
jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 4907
```
so check that dangled character in your mail template

**Comment by alorence** [comment]
I understand, that's why I tried to explain exactly what happen:

Each time i correct the template saved in DB (replacing `&gt;` by `>`) and save, it is reset to `&gt;` which is the wrong value (the HTML escape code corresponding to `>`). According to your advices on #30819, editing in "code view" mode should avoid this behavior, but this does not work for me : the operator is always replaced by its HTML escape code.

**Comment by pedrobaeza** [comment]
But are you sure the error corresponds to that character, or is it another one?

**Comment by alorence** [comment]
Yes, I am sure. On the first line of the traceback, the full template is reproduced.

I copy/pasted it to my preferred editor, correctly replaced `\n` by proper newlines, removed excape characters, and used the "Go to char" menu to go to 4907th character. It is the first `&` of the line `% if data['yesterday'][kpi]['margin'] &gt; 0.0:`

**Comment by gdgellatly** [comment]
Translations?

**Comment by alorence** [comment]
I use french translation but the template I redproduce the issue with is not translated (see https://github.com/odoo/odoo/blob/12.0/addons/digest/i18n/fr.po#L179).

In addition, I can reproduce this with a clean database and the default English language.

**Comment by alorence** [comment]
I just verified the behavior is observable on Odoo Entreprise demo :
https://demo3.odoo.com/web?debug#id=19&action=117&model=mail.template&view_type=form&menu_id=4

Edit the template, switch to "code view" and scroll to the middle of the document 👍 
```
                                                            % if data['yesterday'][kpi]['margin'] &gt; 0.0:
                                                                <span style="color: #0bbc22;">▲</span>${"%.2f" % data['yesterday'][kpi]['margin']} %
                                                            % endif
                                                            % if data['yesterday'][kpi]['margin'] &lt; 0.0:
                                                                <span style="color: #ff0000;">▼</span>${"%.2f" % data['yesterday'][kpi]['margin']} %
                                                            % endif
```
As you can see, `<` and `>` operators were converted to corresponding HTML escape code. You can restore the correct chars and save, but they will be reconverted to `&gt;` and `&lt;`.

**Comment by pedrobaeza** [comment]
@qsm-odoo are you aware of this behavior in the code editor?

**Comment by alorence** [comment]
Today, in order to fix email digest (still received empty every week), I tried to edit the template directly in the DB (to make sure no characters conversion is performed). Unfortunately, Odoo "don't see" the change and still use the wrong version of the template (with `&lt;` and `&gt;`). I tried to update "mail" module from Applications, and I tried to restart Odoo instance, but the proper template (in the DB) is not re-read.

**Comment by icoro** [comment]
I'm having the same issue. > and < are causing the issue. If I edit the digest template and save it without changes, the error happens. The editor changes > and < characters.

**Comment by icoro** [comment]
is there any workaround for this using the editor?

**Comment by alorence** [comment]
@icoro I did not find any workaround, the digest emails are still received empty. I succeed to set the correct characters by editing directly in the postgres DB, but I can't find a way to reload the template content from DB. Odoo seems to use the wrong version anyway.

**Comment by icoro** [comment]
@alorence I was able to reload it by deleting the digest thru technical menu and then refresh the mail app. It is sad that there is no workaround. At least the odoo team should provide a way to edit the templates in plain txt without editor thru the UI.

**Comment by alorence** [comment]
Thanks for the tip. This template has now a correct content and the digest email is correctly sent, until somebody else will try to re-edit it :)

**Comment by mgrenson** [comment]
I confirm we still have this issue in 14.0 with &gt; or &lt; 
On my side, as a workaround, I computed a value in data model which made the comparison, so inside jinja template I just had to make a test with a boolean.
