### ISSUE TITLE
Odoo v6 keep throwing me "ERROR testdb openerp: Failed to initialize database `testdb`"

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#3508]
Hi all,

I created a dup of the actual db called testdb and tried to run some simple yaml tests. However, it keeps throwing the error mentioned in the title. The funny thing is that if I ran the test on an empty db, it just executed without any errors.

Here is the log:
2014-11-06 17:51:12,206 8740 ERROR testdb openerp: Failed to initialize database `testdb` and run test file `addons/my-custom/test/example.yml`.
Traceback (most recent call last):
  File "/home/my/workspace/server/my-6.1/openerp-server", line 108, in run_test_file
    openerp.tools.convert_yaml_import(cr, 'base', file(test_file), {}, 'test', True)
  File "/media/sf_workspace/server/my-6.1/openerp/tools/yaml_import.py", line 911, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/media/sf_workspace/server/my-6.1/openerp/tools/yaml_import.py", line 843, in process
    for node in yaml.load(yaml_string):
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 386, in parse_block_sequence_entry
    return self.parse_block_node()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 265, in parse_block_node
    return self.parse_node(block=True)
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 371, in parse_node
    token.start_mark)
ParserError: while parsing a block node
expected the node content, but found '?'
  in "<string>", line 5, column 1:
    !python {model: zerp.example}: |
    ^
2014-11-06 17:51:12,270 8740 WARNING ? openerp.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.

My simple yaml test script:

```
-
!python {model: zerp.example}: |
    assert True, "Testing True!"
    assert False, "Testing False!"
```

I am pretty sure that I followed the fortmat of the yaml structure and used a corret command to run it. However, I just cannot get rid of this error to run my test.

I also tried to run some default *.yml. I found some of them actually execute with the testdb but some did give me the same error above.

Any help will be grealy aprreicated.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your report.
This is however about an Odoo version that is no longer supported (Odoo only supports three versions back) and it is about custom development.
You might want to ask this question at http://odoo.com/help if you still face it.

Regards,
Yenthe
