### ISSUE TITLE
[12.0] Issue open partner with Arabic language

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#35233]
Impacted versions:
12.0 C 
Runbot link: http://573943-12-0-bdc762.runbot13.odoo.com
Steps to reproduce:
1. Load Arabic language
2. Go to "Contacts"

Current behavior:
Below error appear after run debug assets:
```
خطأ:
Uncaught TypeError: Cannot read property 'trim' of undefined

http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/core/utils.js:147
تتبع الأثر:
TypeError: Cannot read property 'trim' of undefined
    at Object.human_size (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/core/utils.js:147:49)
    at Object.binaryToBinsize (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/core/utils.js:37:25)
    at formatBinary (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/fields/field_utils.js:44:18)
    at http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/views/kanban/kanban_record.js:467:27
    at Function._.each._.forEach (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/lib/underscore/underscore.js:145:9)
    at Class._transformRecord (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/views/kanban/kanban_record.js:451:11)
    at Class._setState (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/views/kanban/kanban_record.js:399:28)
    at Class.init (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/views/kanban/kanban_record.js:57:14)
    at Class.prototype.<computed> [as init] (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/core/class.js:90:38)
    at new Class (http://573943-12-0-bdc762.runbot13.odoo.com/web/static/src/js/core/class.js:107:33)
```

Video/Screenshot link (optional):
https://drive.google.com/file/d/1uAIazLirqhf9knhM0YFBoFna4sxqpvV3/view?usp=sharing

**Comment by Yenthe666** [comment]
Hi @abdallamhafeez,

I've just tested this on the latest 12.0 runbot but it seems to work fine now!
Could you test it again on the latest 12.0 runbot please? I assume there was an issue in one of the translation terms which has already been fixed. 

Regards,
Yenthe

**Comment by abdallamhafeez** [comment]
@Yenthe666 It is working now, Thanks
