### ISSUE TITLE
[10.0] error 500 related to variant image on archived product

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#35241]
Impacted versions: 10 (untested on others)

Steps to reproduce: publish a product on ecommerce, then archive it, try to access its web page

Current behavior: error 500 because of template error. See below full error log 

Error log from server :
========
```
2019-07-28 16:11:47,538 29912 ERROR www odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/website/models/ir_http.py", line 274, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 775, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 834, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 330, in checked_call
    result.flatten()
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1277, in flatten
    self.response.append(self.render())
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1270, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 1052, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/site-packages/odoo/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 1072, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 251, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 325, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 318, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_682_970
  File "<template>", line 3, in body_call_content_969
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5273, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: 682
Path: /templates/t/t/div/section[1]/div[2]/div[1]/t/t[1]
Node: <t t-set="variant_img" t-value="product.product_variant_ids[0].image_variant"/>
              

2019-07-28 16:11:47,669 29912 INFO www werkzeug: 127.0.0.1 - - [28/Jul/2019 16:11:47] "GET /shop/product/bebjtpo-jouet-a-tirer-en-bois-poisson-513 HTTP/1.0" 500 -
```

**Comment by Yenthe666** [comment]
@JKE-be and @rdeodoo  for your interest

**Comment by JKE-be** [comment]
You cannot have one template without variant ! You should archive the template instead.

Already improved in next version 

Most of the code in 10 assume that you have at least 1 variant ...

**Comment by zeroheure** [comment]
Could you explain a bit ? Because I'm not sure to understand :
am I supposed to archive the product template ?
or should I add at least one (fictional) variant to make it work properly ?
thanks

**Comment by Yenthe666** [comment]
@zeroheure you should always archive the template. If you create a template there is always a variant product created in the background too by the way ;)

**Comment by zeroheure** [comment]
But if I archive the template, I got the reported error 500 on its ecommerce page !

**Comment by JKE-be** [comment]
@zeroheure 

This bug has been already fixed.

I just checked in your db and the view is not updated ! 

![image](https://user-images.githubusercontent.com/4848797/62061322-3427c100-b227-11e9-8894-bd391e838e60.png)

check commit: e88f91ba41d6af028df019893d656a5f50b35d28 and 60280e6

The best is probably to copy past the view from runbot to your own db.

KR

**Comment by zeroheure** [comment]
@JKE-be good idea, thanks.
