### ISSUE TITLE
Marketing automation error

### ISSUE THREAD

**Issue by younismahsud** [odoo/odoo#35267]
Impacted versions:
Odoo v11

Steps to reproduce:
Go to marketing automation tool. Create New compaign. Then click add an item to add workflow. Select server action and create new server action named Create new lead. Now select Create new record as Action to do. Select model as Quotation and Create/Write model as CRM/LEAD. Click save to save the record. Click save to save the activity. Now click Launch a test and click the play button to execute. You will get the following error message.

```
Traceback (most recent call last):
  File "/home/younis/odoo/odoo11/enterprise/marketing_automation/models/marketing_campaign.py", line 504, in _execute_action
    action.run()
  File "/home/younis/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 567, in run
    res = func(action, eval_context=eval_context)
  File "/home/younis/odoo/odoo11/odoo/addons/base/ir/ir_actions.py", line 482, in run_action_object_create
    res = self.env[action.crud_model_id.model].create(res)
  File "/home/younis/odoo/odoo11/addons/sale/models/sale.py", line 302, in create
    result = super(SaleOrder, self).create(vals)
  File "/home/younis/odoo/odoo11/addons/mail/models/mail_thread.py", line 238, in create
    thread = super(MailThread, self).create(values)
  File "/home/younis/odoo/odoo11/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/home/younis/odoo/odoo11/odoo/models.py", line 3465, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/younis/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/younis/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "partner_id" violates not-null constraint
DETAIL:  Failing row contains (41050, null, 2019-07-29 14:02:31.435541, 1, 1, null, 2019-07-29 14:02:31, null, , null, null, null, 1, null, draft, null, null, 1, null, null, null, 2019-07-29 14:02:31.435541, null, null, null, null, SO134387, null, 10, direct, null, 1, null, null, null, 7, null, null, f, null, null, 7, null, null, null, 7f7ba9b2-41f2-403d-a9ca-d14c26763b80, null, null, f, null, null, null, f, null, Standard, null, f, null, null, null, null, null, null, null, f, null, null, null, null, null, null, null, f, f, f, null, f, f, f, f).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/younis/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/younis/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/younis/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/younis/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/younis/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/younis/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/younis/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/younis/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/younis/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/younis/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/younis/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/younis/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/younis/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/younis/odoo/odoo11/enterprise/marketing_automation/models/marketing_participant.py", line 159, in action_execute
    self.activity_id.execute_on_traces(self)
  File "/home/younis/odoo/odoo11/enterprise/marketing_automation/models/marketing_campaign.py", line 478, in execute_on_traces
    activity_method(traces_allowed)
  File "/home/younis/odoo/odoo11/enterprise/marketing_automation/models/marketing_campaign.py", line 510, in _execute_action
    'state_msg': _('Exception in server action: %s') % str(e),
  File "/home/younis/odoo/odoo11/odoo/models.py", line 3089, in write
    self._write(old_vals)
  File "/home/younis/odoo/odoo11/odoo/models.py", line 3190, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/younis/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/younis/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block
```
I experienced the same error message on Odoo runbot.

Current behavior:
It throws an error message.

Expected behavior:
It should create lead

Video/Screenshot link (optional):

**Comment by younismahsud** [comment]
This is closed now. There is no bug in Marketing automation module. I was added wrong value for crm state field. Thanks
