### ISSUE TITLE
Unicode file name handling in tools/osutil.py

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#3533]
During a database update i got this error:
```
2014-11-09 16:32:01,639 19437 CRITICAL XXXXX openerp.service.server: Failed to initialize database `XXXXX`.
Traceback (most recent call last):
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/service/server.py", line 907, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/registry.py", line 340, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/loading.py", line 126, in load_module_graph
    migrations = openerp.modules.migration.MigrationManager(cr, graph)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/migration.py", line 68, in __init__
    self._get_files()
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/migration.py", line 83, in _get_files
    self.migrations[pkg.name]['module'] = get_module_filetree(pkg.name, 'migrations') or {}
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/module.py", line 141, in get_module_filetree
    files = openerp.tools.osutil.listdir(path, True)
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/tools/osutil.py", line 46, in listdir
    for root, dirs, files in walksymlinks(dir):
  File "/openerp/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/tools/osutil.py", line 56, in walksymlinks
    for dirpath, dirnames, filenames in os.walk(top, topdown, onerror):
  File "/openerp/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/openerp/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf5 in position 9: ordinal not in range(128)
```
As per this answer points out you need to use os.walk(unicode(path)):
http://stackoverflow.com/a/16926375/2163315

So at tools/osutil.py line 56 this sould be:
```python
for dirpath, dirnames, filenames in os.walk(unicode(top, sys.getfilesystemencoding()), topdown, onerror):
```

This handling in posixpath.py is fixed in Python 3.1+

**Comment by tsabi** [comment]
UP!

**Comment by mart-e** [comment]
As said on the #3536, not clear enough of the source of the issue. It seems to me that the source is a file on your system that somehow got incompatible with your system encoding.
If more concrete example on how to reproduce (meaning how did you end up with these files), we can reopen but I prefer avoiding making patch relying too much on assumptions.
