### ISSUE TITLE
[master] Hierarchy view is not working on base trial balance.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#35428]
* Impacted versions:

**[master]**

* Steps to reproduce:

try to generate the trial balance on hierarchy view

![image](https://user-images.githubusercontent.com/338634/62432548-fd095200-b6f5-11e9-8c53-896a6b6971fd.png)

* Current behavior:

**traceback**

```
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 92, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1105, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1097, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 371, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 358, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/enterprise/account_reports/models/account_report.py", line 1159, in get_report_informations
    'main_html': self.get_html(options),
  File "/data/build/enterprise/account_reports/models/account_report.py", line 1197, in get_html
    lines = self._get_lines(options, line_id=line_id)
  File "/data/build/enterprise/account_reports/models/account_report_coa.py", line 136, in _get_lines
    lines = self._create_hierarchy(lines)
TypeError: _create_hierarchy() missing 1 required positional argument: 'options'
```

* Expected behavior:

**works**

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo for you ;-)

**Comment by pedrobaeza** [comment]
Is this something of enterprise only?

**Comment by nhomar** [comment]
We detected it is only when no transactions available, once you make the first transaction it **works** but duplicates the tree structure.

**Comment by jco-odoo** [comment]
@smetl

**Comment by luistorresm** [comment]
Hello @nhomar @smetl @qdp-odoo 

I was created the PR with the fix [here](https://github.com/odoo/enterprise/pull/5087).

Regards

**Comment by luistorresm** [comment]
@nhomar 

This was fixed [here](https://github.com/odoo/enterprise/pull/5087)

Could you fix this issue, please?

Regards

**Comment by william-andre** [comment]
@nhomar @luistorresm There is also this fix https://github.com/odoo/enterprise/pull/5486 that is going a step further

@pedrobaeza Yes, accounting reports are only in enterprise.

**Comment by pedrobaeza** [comment]
Then I think this should go through regular Odoo enterprise ticket system (and more being something about master), isn't it?

**Comment by nhomar** [comment]
>> Then I think this should go through regular Odoo enterprise ticket system (and more being something about master), isn't it?

No, it is master and it is R&D and it is public and as we talked... the topic can be discussed here... once it is fxed I will close the issue with no problem, you can relax @pedrobaeza 

@william-andre thanks for the update. Once merged I take care of this issue.

**Comment by william-andre** [comment]
@nhomar https://github.com/odoo/enterprise/pull/5486 and https://github.com/odoo/enterprise/pull/5087 are both merged
