### ISSUE TITLE
(master) account: (Non-auto-validate) Reconciliation models created for one Journal do not work for Others

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35619]
Impacted versions:
master
Steps to reproduce [video](https://youtu.be/u5s01mdn8xw):
- Create Journal A,
- Create for Journal A a reconciliation model like this.

![Screen Shot 2019-08-09 at 2 37 26 PM](https://user-images.githubusercontent.com/7598010/62827148-74743100-bb8f-11e9-8e7c-3fa8d821c06f.png)

- Import Bank Statement file in a way that it can be suggested as reconciliation when reconciliation button is hit.

![Screen Shot 2019-08-09 at 2 39 33 PM](https://user-images.githubusercontent.com/7598010/62827183-0714d000-bb90-11e9-8d98-d1ba6c22de03.png)

- Create a Journal B,
- Modify the previous reconciliation model made for A to include Journal B like this.

<img width="1151" alt="Screen Shot 2019-08-10 at 3 11 13 PM" src="https://user-images.githubusercontent.com/7598010/62827210-5bb84b00-bb90-11e9-800a-4532fba2fd26.png">

- Import a Bank Statement file in a way that it can be suggested as reconciliation when reconciliation button is hit in the kanban view ***(this does not happen from the form view)***

<img width="532" alt="Screen Shot 2019-08-10 at 3 04 58 PM" src="https://user-images.githubusercontent.com/7598010/62827278-9f5f8480-bb91-11e9-8fa7-7f2371b3b338.png">

When hitting the reconcile button the following message is shown:

<img width="997" alt="Screen Shot 2019-08-10 at 3 24 13 PM" src="https://user-images.githubusercontent.com/7598010/62827248-daad8380-bb90-11e9-93ce-f79d5d84662a.png">

```
Error:


Traceback:
TypeError: Cannot read property 'has_second_line' of undefined
    at Class.quickCreateProposition (http://localhost:32771/web/content/791-0c0e6ba/web.assets_backend.js:3776:870)
    at http://localhost:32771/web/content/791-0c0e6ba/web.assets_backend.js:3811:59
    at async Promise.all (index 4)
```

**Comment by C3POdoo** [comment]
Dear @hbto,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
