### ISSUE TITLE
[master] Trial balance errors with hierarchy

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#35666]
Impacted versions:
master

Steps to reproduce:
1. Configure the group in one account with movements in the period (The account must be shown in the trial balance)
2. Get the trial balance, and use the option to `hierarchy and subtotals`

Current behavior:
I get the next traceback:
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 92, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1105, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1097, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 371, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 358, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/enterprise/account_reports/models/account_report.py", line 1160, in get_report_informations
    'main_html': self.get_html(options),
  File "/home/odoo/enterprise/account_reports/models/account_report.py", line 1198, in get_html
    lines = self._get_lines(options, line_id=line_id)
  File "/home/odoo/enterprise/account_reports/models/account_report_coa.py", line 136, in _get_lines
    lines = self._create_hierarchy(lines, options)
  File "/home/odoo/enterprise/account_reports/models/account_report.py", line 676, in _create_hierarchy
    add_line_to_hierarchy(no_group_line, codes, no_group_hierarchy)
  File "/home/odoo/enterprise/account_reports/models/account_report.py", line 600, in add_line_to_hierarchy
    code = codes[1]
IndexError: list index out of range
```

Expected behavior:
The trial balance is generated, maybe if it cannot be generated with all accounts configured, that adds a hierarchy group with `Accounts without group`

Video/Screenshot link (optional):
https://youtu.be/3y3aYEnTaNM

**Comment by pedrobaeza** [comment]
This is something of enterprise modules, so better to report it at odoo.com/help
