### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by kelvinthonyInti** [odoo/odoo#35741]
Hello, I need your help.

Impacted versions: 
11.0

Steps to reproduce:
1. Install Postgresql 
`docker run -p 8002:5432 -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name  pg95test postgres:9.5`
2. Install Odoo 
`docker run -p 8072:8069 --name myodoo --link pg95test:db -t odoo:11`

3. Add Odoo enterprise path to `Odoo.conf`.
```
[options]
addons_path = /mnt/extra-addons,/mnt/enterprise,/mnt/my-tools,/mnt/locationpe,/mnt/myextras-addons
admin_passwd = $pbkdf2-sha512$25000$p9R6rzUmREgpBaAUovTe.w$JaOd2lJ0eV3wwSvcCzW7wd25p/rCxDRSIamoOblECKJXMx2L3P0rRVgGKL4XehiUrQ95oRTnhg2jHCVCIkdZaQ
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = 172.17.0.31
db_maxconn = 64
db_name = False
db_password = odoo
db_port = 5432
db_sslmode = prefer
db_template = template1
db_user = odoo
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = None
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = False
reportgz = False
server_wide_modules = web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 0
```
Current behavior:
It happens when: I install an application or an update, sometimes only when I navigate on Odoo.

```
2019-08-14 16:22:21,747 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1458, in dispatch
    request = self.get_request(httprequest)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1407, in get_request
    return JsonRequest(httprequest)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 616, in __init__
    self.params = dict(self.jsonrequest.get("params", {}))
ValueError: dictionary update sequence element #0 has length 8; 2 is required
2019-08-14 16:22:22,490 1 INFO BD_POC werkzeug: 190.236.206.50 - - [14/Aug/2019 16:22:22] "POST /longpolling/poll HTTP/1.1" 200 -
2019-08-14 16:22:23,471 1 INFO ? werkzeug: 82.196.0.91 - - [14/Aug/2019 16:22:23] "POST / HTTP/1.1" 500 -
2019-08-14 16:22:23,475 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1458, in dispatch
    request = self.get_request(httprequest)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1407, in get_request
    return JsonRequest(httprequest)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 616, in __init__
    self.params = dict(self.jsonrequest.get("params", {}))
AttributeError: 'list' object has no attribute 'get'
2019-08-14 16:22:25,131 1 INFO ? werkzeug: 82.196.0.91 - - [14/Aug/2019 16:22:25] "POST / HTTP/1.1" 500 -
2019-08-14 16:22:25,136 1 ERROR ? werkzeug: Error on request:
```

Expected behavior:
Install, update and navigate normally.

Video/Screenshot link (optional):
![WhatsApp Image 2019-08-13 at 18 03 07](https://user-images.githubusercontent.com/33042751/63042099-ed74d080-be8e-11e9-8f7e-b9a08d05092e.jpeg)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about deployment. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Check also installation instructions on https://www.odoo.com/documentation/12.0/setup/install.html.

Closing this by the reason above.
