### ISSUE TITLE
(master) account_asset: Resuming Depreciation on an Asset is not working

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35753]
(master) account_asset: Resuming Depreciation on an Asset is not working
=
Impacted versions:
-

master

Current behavior:
-

- Create an asset as follows.
<img width="1086" alt="Screen Shot 2019-08-16 at 4 21 26 AM" src="https://user-images.githubusercontent.com/7598010/63157822-769a1d80-bfdd-11e9-859a-e4b4d22617d2.png">

- Confirm it and Run some previous Depreciation Items (Post some Journal Entries).
<img width="1086" alt="Screen Shot 2019-08-16 at 4 22 08 AM" src="https://user-images.githubusercontent.com/7598010/63157854-8ca7de00-bfdd-11e9-81df-7a560df06e1c.png">

- Pause Depreciation.
<img width="994" alt="Screen Shot 2019-08-16 at 4 23 50 AM" src="https://user-images.githubusercontent.com/7598010/63157899-aba67000-bfdd-11e9-9f9e-a36f585a2460.png">

- Depreciation has been paused.
<img width="1094" alt="Screen Shot 2019-08-16 at 4 26 49 AM" src="https://user-images.githubusercontent.com/7598010/63158093-240d3100-bfde-11e9-8bf1-ffac22d09988.png">

- Now Resume Depreciation Wizard.
<img width="994" alt="Screen Shot 2019-08-16 at 4 24 44 AM" src="https://user-images.githubusercontent.com/7598010/63157952-d0024c80-bfdd-11e9-9a03-5ea19b3efb16.png">

- And hit Modify button

```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 92, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 1110, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 1098, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 373, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 360, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/enterprise/account_asset/wizard/asset_modify.py", line 48, in modify
    already_depreciated_amount = sum([m.amount for m in posted_depreciation_move_ids])
  File "/home/odoo/enterprise/account_asset/wizard/asset_modify.py", line 48, in <listcomp>
    already_depreciated_amount = sum([m.amount for m in posted_depreciation_move_ids])
AttributeError: 'account.move' object has no attribute 'amount'
```

Expected Behavior
=
Be able to resume Depreciation on Asset.

**Comment by C3POdoo** [comment]
Dear @hbto,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
