### ISSUE TITLE
IPv6: support `--http-interface=::`

### ISSUE THREAD

**Issue by eugene-bright** [odoo/odoo#35782]
Impacted versions:

> All

Steps to reproduce:

> Run with command line option `--http-interface=::`

Current behavior:

```
2019-08-17 20:40:26,084 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on :::8069 
Traceback (most recent call last):                                               
File "/usr/bin/odoo", line 8, in <module>                                      
  odoo.cli.main()                                                              
File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main    
  o.run(args)                                                                  
File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 176, in run     
  main(args)                                                                   
File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 170, in main    
  rc = odoo.service.server.start(preload=preload, stop=stop)                   
File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1188, in start
  rc = server.run(preload, stop)                                               
File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 797, in run 
  self.start()                                                                 
File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 768, in start
  self.socket.bind(self.address)                                               
socket.gaierror: [Errno -9] Address family for hostname not supported
```

Expected behavior:

> Server listens on all addressed including IPv6

Video/Screenshot link (optional):

Example [`Echo server program`][py_socket] teaches how to open a socket in the right way.

[py_socket]: https://docs.python.org/3/library/socket.html

**Comment by boospy** [comment]
thanks for this info, that help me a lot :+1:

**Comment by pedrobaeza** [comment]
@xmo-odoo @odony do you know something about this topic?

**Comment by mgielissen** [comment]
I've tested it with v14 and xmlrpc_interface = :: in odoo.conf. This works within an IPv6 only enviroment (with DNS64/NAT64 for access to ancient IPv4 sites like github).

**Comment by xmo-odoo** [comment]
@mgielissen it looks like things work fine in threaded mode (the default) where Odoo essentially just hands out the entire thing to Werkzeug's `ThreadedWSGIServer`, but it does not work in prefork mode (`--workers=x`, the "production" mode) where the socket work is done internally by odoo.

**Comment by babarlhr** [comment]
Have any update regarding this issue?
