### ISSUE TITLE
[master] runbot: unable to use base databases - internal server error

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35884]
Impacted versions: Master

Steps to reproduce:
1. Go to http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7?search= and open the latest build from the master branch
2. Switch to the xx-base database

Current behavior:
Internal server error
![image](https://user-images.githubusercontent.com/6352350/63412453-14d01e00-c3f8-11e9-9557-bf4086f2fa1e.png)

Expected behavior:
Able to open and use an empty database to test stuff

**Comment by Yenthe666** [comment]
@mart-e maybe for you?

**Comment by mart-e** [comment]
Hi,

Sorry but I have to reject this.
The runbot is a shared instance between anyone wanting to use it. People can connect to it, mess up with it, change passwords, remove users, uninstall base or whaterver to make it crash but it is kind of the point of the runbot.
The fact that you can't connect on one specific instance does not explain much.
We won't spend time investigating specific broken runbot instances, especially not if it is the master version (where we do not accept bug report anyway).

The runbot is an easy way to try something on the latest code version but should not replace a proper installation for efficient testing.
If there is really a bug, a traceback must be provided (an "internal server error" does not says much). You can get run logs from a runbot build itself (you have a dropdown "Full run logs").

And by the way, if you believe the issue is on the runbot itself, you can report it at https://github.com/odoo/runbot

**Comment by Yenthe666** [comment]
@mart-e maybe I was not clear enough. It happens on every single master build, I've tested 7 instances.
They all seem to do this for the base build:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/data/build/odoo/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/data/build/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/data/build/odoo/odoo/http.py", line 1272, in __call__
    return self.dispatch(environ, start_response)
  File "/data/build/odoo/odoo/http.py", line 1245, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/data/build/odoo/odoo/http.py", line 1440, in dispatch
    result = ir_http._dispatch()
  File "/data/build/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/data/build/odoo/addons/website/models/ir_http.py", line 100, in _dispatch
    request.env['website.visitor']._handle_webpage_dispatch(response, cls._extract_website_page(response))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/data/build/odoo/odoo/http.py", line 269, in env
    self._env = odoo.api.Environment(self.cr, self.uid, self.context)
  File "/data/build/odoo/odoo/http.py", line 239, in cr
    raise RuntimeError('request not bound to a database')
RuntimeError: request not bound to a database - - -
```

**Comment by mart-e** [comment]
Sorry but still have to reject it because it is the master version which is not supported, 
And by the way your traceback includes website_sale, so is not a base database (or somebody installed it on it).
