### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by DexterMorg4n** [odoo/odoo#359]
Check your system! It's not working on ubuntu 13.04.

error: pathspec 'master' did not match any file(s) known to git.
Traceback (most recent call last):
  File "<stdin>", line 162, in <module>
  File "<stdin>", line 154, in main
  File "<stdin>", line 144, in cmd_setup
  File "<stdin>", line 96, in cmd_setup_git
  File "<stdin>", line 39, in run
  File "/usr/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('git', 'checkout', 'master')' returned non-zero exit status 1

All dependencies installed. New system, not flaws. 
New version, same story over and over again

**Comment by Yenthe666** [comment]
Dear @DexterMorg4n,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
