### ISSUE TITLE
Error activating sales_quotation_builder on instance in Spanish

### ISSUE THREAD

**Issue by crece365** [odoo/odoo#35936]
Impacted versions: 12.0

Steps to reproduce:

1. The language of odoo must be Spanish
2. Install the module sale_management.
3. Go to the configuration of the sales module and activate the Quotation Builder option
4. After installing, the error message is displayed.
5. Try to enter the configuration again and the error will appear.
6. You cannot enter the option to configure the sales module.

Current behavior:

You cannot enter the option to configure the sales module. The module sale_quotation_builder no install

Expected behavior:
No server error should appear. Sale_quotation_builder should be installed

Video/Screenshot link (optional):

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/odoo/odoo-server/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo/odoo-server/odoo/addons/base/models/res_config.py", line 395, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/odoo/odoo-server/odoo/models.py", line 1455, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo/odoo-server/odoo/models.py", line 1418, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 794, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 743, in apply_view_inheritance
    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 743, in apply_view_inheritance
    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 742, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/enterprise/addons/web_studio/models/ir_ui_view.py", line 152, in apply_inheritance_specs
    return super(View, self).apply_inheritance_specs(source, specs_tree, inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 720, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//label[@for='module_sale_quotation_builder']/following::div/em">' no puede ser localizado en la vista padre

Contexto del error:
Vista `res.config.settings.view.form.inherit.sale.management.inherit.sale.quotation.builder`
[view_id: 1933, xml_id: sale_quotation_builder.res_config_settings_view_form_inherit, model: res.config.settings, parent_id: 1037]`

fla
![error_quotation_builder](https://user-images.githubusercontent.com/50924836/63467983-4ebb1780-c42c-11e9-9711-a5fe594f8f47.png)

**Comment by Yenthe666** [comment]
This is most likely an issue with an incorrectly translated term.

**Comment by pedrobaeza** [comment]
Yes, it seems so. I would say that you try on runbot instance with latest code and DB base to check if the problem has been solved meanwhile.

**Comment by Illuminati1-organization** [comment]
Hello!! Do you wish to be famous, wealthy and powerful? Be part of this elite organization called THE ILLUMINATI SOCIETY filled with world leaders, business authorities, innovators, artists, and other influential members of this planet...If Interested, message me at stevemorrison0001@gmail.com
 HAIL THE LIGHT🔯![](https://ibin.co/4sMQ0Xu1axDM.png)

**Comment by crece365** [comment]
> Yes, it seems so. I would say that you try on runbot instance with latest code and DB base to check if the problem has been solved meanwhile.

This error is also manifested in the runbot

http://598053-12-0-99c8f6.runbot27.odoo.com/web?#action=1029&model=sale.order&view_type=list&menu_id=690

![image](https://user-images.githubusercontent.com/50924836/63559469-5f948780-c517-11e9-88af-db64fb17252a.png)

**Comment by pedrobaeza** [comment]
Great, then the offending translated string should be located.

**Comment by mart-e** [comment]
This one is the culprit I think ;-)
https://www.transifex.com/odoo/odoo-12/translate/#es/sale_management/162272440?q=text%3A'Design+your+quotation+templates+using+building+blo'

**Comment by mart-e** [comment]
I have corrected the translation, it will be in the next synchronisation (on Sunday)
Thanks for the report

**Comment by pedrobaeza** [comment]
I have improved it as well :smiley: I'm seeing a lot of people removes HTML tags that are somewhat hidden by Transifex. Is there maybe an option to enforce then to be on the translation? Or maybe to not hide them at all?

**Comment by mart-e** [comment]
The "HTML tags are preserved in the translation." check is already enabled to the warning level. We can not set it to blocking as there is always false negative where content is understood as html or where it does makes sense to change it (e.g. change some attributes).
