### ISSUE TITLE
master/13.0 base: `default` ignored from computed fields

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#35932]
## Impacted versions:
master/13.0
After https://github.com/odoo/odoo/pull/35659
https://github.com/odoo/odoo/commit/9920f20e4c7753bc17bea71dea3a90f7de687196

## Steps to reproduce:

Install module with the following basic code
```python
from odoo import models, fields, api


class compute_error(models.Model):
    _name = 'compute_error.compute_error'

    name = fields.Char()
    value = fields.Integer(compute="_compute_values", default=0)

    @api.depends('name')
    def _compute_values(self):
        if self.name == 'hello':
            self.value = 1
```

Notice `default=0`

Also, you can use the following gists:
 - https://gist.github.com/moylop260/041b45964f228fa543792aeb123ed9cc

Now, run the following script from odoo-bin shell:

```python
record = self.env['compute_error.compute_error'].create({'name': 'hola'})
record._compute_values()
print(record.value)
```

## Current behavior:
```bash
Traceback (most recent call last):
  File "odoo/api.py", line 719, in get
    value = self._data[field][record._ids[0]]
KeyError: 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "odoo/cli/command.py", line 60, in main
    o.run(args)
  File "odoo/cli/shell.py", line 125, in run
    self.shell(config['db_name'])
  File "odoo/cli/shell.py", line 118, in shell
    self.console(local_vars)
  File "odoo/cli/shell.py", line 67, in console
    exec(sys.stdin.read(), local_vars)
  File "<string>", line 3, in <module>
  File "odoo/fields.py", line 1058, in __get__
    value = env.cache.get(record, self)
  File "odoo/api.py", line 726, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('compute_error.compute_error(15,).value', None)
```

## Expected behavior:

See a value of `0` since that it is the default value defined from fields.
I saw the following comment:
https://github.com/odoo/odoo/issues/35886#issuecomment-523448919

`ORM refactoring where compute methods need to write in all cases, even falsy ones`

FYI I just ran the following command:
`rgrep "depends(" ~/odoo/addons/ --include=*.py -A10 | grep  "        if " -B5 -A4`
In order to get similar cases and there are a lot of them.

However, the error from screen is not giving more details and there are not unittest covering these cases.
 - ![image](https://user-images.githubusercontent.com/6644187/63451064-ff172480-c408-11e9-98d3-b8e9db901652.png)

Then, A lot of modules will fail silently because of this reason after install them.
So it is a huge effort for many modules OCA, odoo, enterprise, custom.

The good part is that we will have an improvement of performance using this refactoring.
The question is:
 - Is not possible use a default value if the field was not set?
The community will love it.

If the answer is not, so Is there a way to raise it early?
In order to avoid false green and raise error in live production after use it.

## Video/Screenshot link (optional):
 - ![hbto error](https://user-images.githubusercontent.com/6644187/63433721-61f8c380-c3e9-11e9-8b16-27f21aafa180.gif)

cc @rco-odoo @beledouxdenis

**Comment by moylop260** [comment]
I closed this issue since that we (oca, vauxoo, odoo, ...) have migrated all our code to new style and it was not replied.
