### ISSUE TITLE
(master) CRM: Traceback appear when add suggested customer

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#35984]
Impacted versions: Master

Steps to reproduce:
1. Go to CRM > lead
2. Type Partner Name in Customer field and click on Suggested partner 
3. Traceback appear once click

Check attached videos for more info

Current behavior:
Traceback appear when add suggested partner
```
=========================================
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/api.py", line 719, in get
    value = self._data[field][record._ids[0]]
KeyError: '<NewId 0x7f7ed6ec1a20>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/fields.py", line 1031, in __get__
    value = env.cache.get(record, self)
  File "/data/build/odoo/odoo/api.py", line 726, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ("res.country('<NewId 0x7f7ed6ec1a20>',).name", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 325, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 357, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 92, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 350, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 894, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 522, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1106, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1098, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 394, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 381, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 1585, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/data/build/odoo/odoo/models.py", line 5332, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1038, in __get__
    recs._fetch_field(self)
  File "/data/build/odoo/odoo/models.py", line 2850, in _fetch_field
    self._read(fnames)
  File "/data/build/odoo/odoo/models.py", line 2921, in _read
    cr.execute(query_str, params)
  File "/data/build/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/data/build/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "<NewId 0x7f7ed6ec1a20>"
LINE 7: ...__vat_label"."res_id") WHERE "res_country".id IN ('<NewId 0x...
                                                             ^
```
Expected behavior:
Suggested partner should be add

Video/Screenshot link (optional):
https://drive.google.com/open?id=1phNHScrKc0vig4sO0YQOaXxaEms4WwoN

**Comment by mart-e** [comment]
Hi,

As explained on the other issue, thanks for the testing but no need to report master bugs about tracebacks (issues like #35841 are fine but because it brings useful analysis). It is still heavily developed and bug fixed. Making report on the master will be very quickly outdated.
If you have identified the problem and wants to provide a fix, do not hesitate to create a PR.
