### ISSUE TITLE
Odoo in Visual Studio 

### ISSUE THREAD

**Issue by mikrokode** [odoo/odoo#36042]
Hi
 I found the following error in running odoo12 in visual studio 2017. May I know how to solve?

2019-08-25 00:08:37,293 7848 INFO ? odoo: Odoo version 12.0
2019-08-25 00:08:37,303 7848 INFO ? odoo: addons paths: ['c:\\users\\admin\\appdata\\local\\openerp s.a\\odoo\\addons\\12.0', 'c:\\odoo-12.0\\odoo\\addons', 'C:\\odoo-12.0\\odoo\\addons']
2019-08-25 00:08:37,303 7848 INFO ? odoo: database: odoo@default:default
2019-08-25 00:08:39,834 7848 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf version of the reports.
2019-08-25 00:08:53,964 7848 CRITICAL ? odoo.modules.module: Couldn't load module web
2019-08-25 00:08:53,964 7848 CRITICAL ? odoo.modules.module: No module named 'web'
2019-08-25 00:08:53,964 7848 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "C:\odoo-12.0\odoo\service\server.py", line 1063, in load_server_wide_modules     odoo.modules.module.load_openerp_module(m)
  File "C:\odoo-12.0\odoo\modules\module.py", line 368, in load_openerp_module     __import__('odoo.addons.' + module_name)
  File "C:\odoo-12.0\odoo\modules\module.py", line 61, in load_module  f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'web'
2019-08-25 00:08:54,004 7848 INFO ? odoo.service.server: HTTP service (werkzeug)
 running on admin-PC:8069

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip: Check the loaded configuration file with the corresponding addons path.

Closing this by the reason above.
