### ISSUE TITLE
[8.0] Timesheet analysis json problem

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#3609]
```
2014-11-13 13:08:16,791 1613 INFO CYM2015 werkzeug: 192.168.1.30 - - [13/Nov/2014 13:08:16] "POST /web/dataset/call_kw/hr.timesheet.report/read_group HTTP/1.1" 200 -
2014-11-13 13:08:16,803 1613 ERROR CYM2015 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 2180, in read_group
    data_dict = {d['id']: d for d in self.read(cr, uid, data_ids, many2onefields, context=context)}
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3082, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3125, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5459, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 760, in __get__
    return record._cache[self]
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5793, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 53, in get
    raise self.exception
AccessError: ('AccessError', u"L'op\xe9ration demand\xe9e ne peut pas \xeatre effectu\xe9e en raison de la politique de s\xe9curit\xe9. Veuillez contacter votre administrateur syst\xe8me.(Type de document: hr.timesheet.report, Op\xe9ration: read)")
```

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.
