### ISSUE TITLE
[12] res_config error when accessing to global settings

### ISSUE THREAD

**Issue by soward42** [odoo/odoo#36158]
Impacted versions:
12

Steps to reproduce:
- Install invoicing module
- Go to the settings page
- Go to in the menu technical->mail->template
- Delete the invoice template (Invoice: Send by email)
- Install sale module
- Go to global parameters

Current behavior:

When i'm accessing to global parameters odoo is returning an error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/mnt/extra-addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/mnt/extra-addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/base/models/res_config.py", line 529, in default_get
    value = self.env[field.comodel_name].browse(int(value)).exists().id
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Expected behavior:

Access to global settings without problem

**Comment by pedrobaeza** [comment]
Which menu is `technical->mail->models`?

**Comment by soward42** [comment]
Sorry I'm using odoo in french so i didn't have the right name.
So it is on settings page, in the technical menu, within the mail section, and then you click on template.

**Comment by pedrobaeza** [comment]
Yes, but that's something expected. You can't delete records that are expected to be there as part of the modules needed info.

Simply don't delete that template and you won't have the problem.

Closing as no issue, but improper data manipulation.

**Comment by pedrobaeza** [comment]
Just upgrade account module again.

**Comment by soward42** [comment]
Thank you ! I wasn't aware that update a module recreate data that have been deleted.
