### ISSUE TITLE
ERROR:  Adding a field in contacts by using the developer mode

### ISSUE THREAD

**Issue by DrMaravich** [odoo/odoo#36455]
I tried to add a new field in contacts by using the developer mode. I didn't write the proper code hence an the following error ocurred. The problem is that I don't know how to fix it (I use Odoo 12.0)

Error:
Uncaught Error: Domain x_deporte,!==,futbol uses an unsupported operator

http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:378
Rastreo de error:
Error: Domain x_deporte,!==,futbol uses an unsupported operator
    at Class.compute (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:378:659)
    at evalModifier (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1392:91)
    at Class._evalModifiers (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1393:46)
    at Class._registerModifiers (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1570:101)
    at Class._renderFieldWidget (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1577:190)
    at Class._renderInnerGroupField (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1628:382)
    at http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1626:44
    at Function._.each._.forEach (http://odoo.realtracksystems.com/web/content/5098-d0fd127/web.assets_common.js:12:558)
    at Class._renderInnerGroup (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1623:63)
    at Class._renderTagGroup (http://odoo.realtracksystems.com/web/content/5099-e0d9d65/web.assets_backend.js:1637:228)

**Comment by sswapnesh** [comment]
> Uncaught Error: Domain x_deporte,!==,futbol uses an unsupported operator

You should use `!=` instead of `!==`

**Comment by Yenthe666** [comment]
Indeed, just remove an is equal sign and it'll work.

**Comment by DrMaravich** [comment]
> Indeed, just remove an is equal sign and it'll work.

I know but I don't know where I could make this change, I cannot access by using the developer mode.

Thanks for the comments anyway =)

**Comment by Yenthe666** [comment]
Find the view from settings > technical > views and fix it there :) Requires developer mode to be on.

**Comment by DrMaravich** [comment]
> Find the view from settings > technical > views and fix it there :) Requires developer mode to be on.

Thank you!!! I just fixed it =D

**Comment by Yenthe666** [comment]
You're welcome, best of luck with Odoo!
