### ISSUE TITLE
Mrp scheduler Error

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#36451]
Impacted versions: 10.0
I got this error in the log file:
```
2019-09-05 06:48:57,159 85092 INFO DB odoo.addons.base.ir.ir_cron: Starting job Generation of contracts costs based on the costs frequency.
2019-09-05 06:48:58,065 85092 ERROR DB odoo.addons.base.ir.ir_cron: Call of self.env[u'fleet.vehicle.log.contract'].run_scheduler(*()) failed in Job #15
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/ir/ir_cron.py", line 126, in _callback
    getattr(model, method_name)(*args)
  File "/opt/odoo/addons/fleet/models/fleet.py", line 657, in run_scheduler
    self.scheduler_manage_auto_costs()
  File "/opt/odoo/addons/fleet/models/fleet.py", line 623, in scheduler_manage_auto_costs
    while (startdate <= today) & (startdate <= fields.Date.from_string(contract.expiration_date)):
TypeError: can't compare datetime.date to NoneType

```

**Comment by jco-odoo** [comment]
Nothing to do with mrp, but with fleet.

**Comment by sswapnesh** [comment]
Maybe one of the contract has no `expiration_date` in it

**Comment by Yenthe666** [comment]
Hi all,

I'm sorry but the Odoo 10 version is no longer official supported as Odoo 13 was released today.
If you can reproduce it in version 11 or higher then please do reply back or create a new issue.

Regards,
Yenthe
