### ISSUE TITLE
payment_stripe_sca in 11.0 Invalid token (imposible to pay with stripe)

### ISSUE THREAD

**Issue by crazy-projects** [odoo/odoo#36589]
Impacted versions: 
11.0 last commit (903e4f52ec9109ae6b489899b55bd8c3d55081be)
This error is reproducible in my local instance and in odoo's runbot.

Steps to reproduce:
1. Go to runbot, choose the 11.0 branch, make sure the payment_stripe_sca module is installed (in runbot it's installed by default).
2. Go to Invoicing > configuration > Payments > Payment Acquirers
3. Enable stripe, there is no need to introduce credentials (even with credentials this error happens)
4. Try to make a credit card payment: For example, pay an invoice. In invoicing settings, enable online payments, create an invoice, validate it, try to sent it by email, double click the button, and copy the link (since runbot can't send emails) open the link in new incognito tab.
5. Choose stripe as payment method
6. Press pay now
7. your browser will send a post request to  /invoice/pay/<id>/s2s_json_token_tx/

Current behavior:
The request fails silently, the pay now apparently does nothing, and the post request sent to odoo returns a 200-ok code, but with an error message inside:
{
	"jsonrpc": "2.0",
	"id": 981004519,
	"error": {
		"code": 200,
		"message": "Odoo Server Error",
		"data": {
			"name": "odoo.exceptions.UserError",
			"debug": "Traceback (most recent call last):
                      File \"/data/build/odoo/odoo/http.py\", line 653, in _handle_exception
                        return super(JsonRequest, self)._handle_exception(exception)
                      File \"/data/build/odoo/odoo/http.py\", line 312, in _handle_exception
                        raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
                      File \"/data/build/odoo/odoo/tools/pycompat.py\", line 87, in reraise
                        raise value
                      File \"/data/build/odoo/odoo/http.py\", line 695, in dispatch
                        result = self._call_function(**self.params)
                      File \"/data/build/odoo/odoo/http.py\", line 344, in _call_function
                        return checked_call(self.db, *args, **kwargs)
                      File \"/data/build/odoo/odoo/service/model.py\", line 97, in wrapper
                        return f(dbname, *args, **kwargs)
                      File \"/data/build/odoo/odoo/http.py\", line 337, in checked_call
                        result = self.endpoint(*a, **kw)
                      File \"/data/build/odoo/odoo/http.py\", line 939, in __call__
                        return self.method(*args, **kw)
                      File \"/data/build/odoo/odoo/http.py\", line 517, in response_wrap
                        response = f(*args, **kw)
                      File \"/data/build/odoo/addons/account_payment/controllers/payment.py\", line 112, in invoice_pay_token_json
                        raise UserError(_('Invalid token'))
                    odoo.exceptions.UserError: ('Invalid token', '')
            ",
			"message": "Invalid token\n",
			"arguments": ["Invalid token", ""],
			"exception_type": "user_error"
		}
	}
}

Expected behavior:
If you didin't setup stripe credentials in odoo:
you get an error about not being able to communicate with stripe

If you set up odoo with stripe credentials.
A form for the credit card info pops-up

Removing the payment_stripe_sca module, restores the stripe payments functionality (altought you are not prepared to SCA)

**Comment by pedrobaeza** [comment]
@dbo-odoo can you please check?

**Comment by jcarlosmontoya** [comment]
I agree with @crazy-projects, (latest odoo v11) when to click pay now button dont redirects to stripe form
only get  a 200 code in log
![image](https://user-images.githubusercontent.com/7680456/64690467-c232d080-d490-11e9-98dd-28d95990280a.png)

**Comment by gityopie** [comment]
the error message throw in the browser console (using runbot: http://615287-11-0-e8ecb9.runbot23.odoo.com)
```
Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Invalid Token
 
 Error data debug:
 Traceback (most recent call last):
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 913, in payment_token_json
    pm_id = int(pm_id)
ValueError: invalid literal for int() with base 10: 'form_8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 915, in payment_token_json
    raise UserError(_('Invalid Token'))
odoo.exceptions.UserError: ('Invalid Token', '')
```

**Comment by Feyensv** [comment]
@nla-odoo could you take a look at this error ? :)

**Comment by nla-odoo** [comment]
Hello @Feyensv 

Here is the PR for V11.0 https://github.com/odoo/odoo/pull/36739

@nim-odoo same will be applied on saas-11.3, should I create the same PR for it?

Thanks

**Comment by nim-odoo** [comment]
@nla-odoo PR will be created automatically

**Comment by Yenthe666** [comment]
forward bot (@fw-bot) for the win 😉
