### ISSUE TITLE
[8.0] Error when importing customers

### ISSUE THREAD

**Issue by jbvidex** [odoo/odoo#3659]
Odoo seems to have a problem importing records with a "State" field.  If I exclude the "State" from import, the file will validate correctly.  If I try to import "State", I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/base_import/models.py", line 327, in do
    cr, uid, import_fields, data, context=context)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/models.py", line 1090, in load
    context=context, log=messages.append):
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/models.py", line 1263, in _convert_records
    converted = convert(record, lambda field, err:\
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/base/ir/ir_fields.py", line 68, in fn
    converted[field], ws = converters[field](value)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/base/ir/ir_fields.py", line 364, in _str_to_many2one
    id, _, w2 = self.db_id_for(model, field, subfield, reference)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp-8.0_83bd9ee-py2.7.egg/openerp/addons/base/ir/ir_fields.py", line 316, in db_id_for
    ids = RelatedModel.name_search(name=value, operator='=')
TypeError: location_name_search() takes at least 3 arguments (3 given)

```

**Comment by thomich** [comment]
how long does it take to apply this fix from nicobustillos? still not working also on latest runbot...

**Comment by nicobustillos** [comment]
As you can see from the comments in the proposed FIX commit (#3703), the issue seem to have a more profound impact than I had seen. So the issue has been derived to @rco-odoo for a more definitive solution. And as far as I know there is still no fix to apply.

**Comment by thomich** [comment]
jep, i also read more about that issue and saw that it's not just a simple problem.. but a major function does not work correct... so hope soon is a fix released and available here...

**Comment by thomich** [comment]
Workaround
* create or import all states which are needed
* get the id's of the states (enhance state view, open each one and get id from url)
![shot-selection-016](https://cloud.githubusercontent.com/assets/4398840/5676519/6ddc6956-97d7-11e4-854f-7c11b409395f.png)
![shot-selection-017](https://cloud.githubusercontent.com/assets/4398840/5676500/19235e7e-97d7-11e4-85e4-4df25e3dc8b8.png)
* create customer import csv, column name for state `state_id/id` and values like:
`__export__.res_country_state_56`
check this example csv:
https://dl.dropboxusercontent.com/u/5636258/odoo8/odoo-customers.csv

**Comment by thomich** [comment]
Workaround UPDATE

replace all `__export__.res_country_state_??` values with only the id, eg:
`__export__.res_country_state_56 becomes 56`

Then on import change the column for state to: State / Database ID (don't know the shortcut for it)
Now validation and import will/should work...

**Comment by jbvidex** [comment]
Thanks for the workaround, @thomich.

If you use the "State / External ID" mapping for the column, you don't have to strip off the ID to use by itself.  You can just use the `__export__.res_country_state_56` value by itself.

**Comment by thomich** [comment]
If you use `__export__.res_country_state_56` and you never made a export from partners where any partners state_id was 56 you can't import it... check table ir.model.data...

1. Create states similar to this screenshot, here id 56 is available:
![shot-selection-023](https://cloud.githubusercontent.com/assets/4398840/5699616/7bbc2686-9a2c-11e4-9c4a-ea3f457fa3d5.png)
2. Take this CSV: https://dl.dropboxusercontent.com/u/5636258/odoo8/odoo-customers_exported.csv
Load and validate it, you will get similar result after validation:
![shot-selection-021](https://cloud.githubusercontent.com/assets/4398840/5699591/0dbd75a4-9a2c-11e4-9134-bca71e914392.png)
3. Now click on the link to **Get all possible values**, and check for lines with `__export__.res_country_state_??`, you will not find any with id 56:
![shot-selection-022](https://cloud.githubusercontent.com/assets/4398840/5699609/44399158-9a2c-11e4-88b9-5793a1485231.png)

For me it looks strange, cause import will only work correct, if you ever made a export where states are also exported... If you start with a empty Odoo DB.. you how ever will be able to import partners with states?

If states are created, it should also create this `__export__` values in `ir.model.data` , then import will work...
