### ISSUE TITLE
Mrp scheduler MemoryError

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#36604]
Impacted versions: 10.0
_CPU:8
RAM:55G_
**odoo.conf:**
_limit_memory_hard = 1395864371
limit_memory_soft = 1358092426
limit_time_cpu = 5600
limit_time_real = 7400
max_cron_threads = 5
workers = 17_

```
2019-09-10 01:08:19,079 74222 ERROR DB odoo.addons.base.ir.ir_cron: Call of self.env[u'procurement.order'].run_scheduler(*(True,)) failed in Job #5
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/ir/ir_cron.py", line 126, in _callback
    getattr(model, method_name)(*args)
  File "/opt/odoo/addons/stock/models/procurement.py", line 249, in run_scheduler
    self.sudo()._procure_orderpoint_confirm(use_new_cursor=use_new_cursor, company_id=company_id)
  File "/opt/custom_addons/custom_procurement/models/procurement.py", line 181, in _procure_orderpoint_confirm
    orderpoints_noprefetch = orderpoints_noprefetch[1000:]
  File "/opt/odoo/odoo/models.py", line 5253, in __getitem__
    return self._browse(self._ids[key], self.env)
  File "/opt/odoo/odoo/models.py", line 4822, in _browse
    prefetch[cls._name].update(ids)
MemoryError 
```

**Comment by pedrobaeza** [comment]
Check your PG memory limits. Any way, this is not an Odoo issue, but a question about deployment. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
