### ISSUE TITLE
Sales Order Paypal Missing Issue

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#3672]
Hey all this was generated in my logs and this is how it came about.

1) When to customer profile
2) Created Sale Order / Quote with existing product
3) Saved and confirmed
4) Generated Invoice
5) Customer logged in in front of me to pay invoice
6) Went through Paypal as an instant payment
7) Transaction went through and redirected to dpn page.
8) DPN page showed http 500
9) Logs show the following with client data omitted

2014-11-15 17:18:25,077 1218 INFO odoo openerp.addons.payment_paypal.controllers.main: Beginning Paypal IPN form_feedback with post data {'address_city': u'private',
 'address_country': u'United Kingdom',
 'address_country_code': u'GB',
 'address_name': u'private',
 'address_state': u'',
 'address_status': u'confirmed',
 'address_street': u'private',
 'address_zip': u'private',
 'business': u'sales@andrews-enterprise.co.uk',
 'charset': u'windows-1252',
 'custom': u'',
 'first_name': u'private',
 'handling_amount': u'0.00',
 'ipn_track_id': u'private',
 'item_name': u'Andrews Enterprise B2B Ltd: SAJ/2014/0002',
 'item_number': u'SAJ/2014/0002',
 'last_name': u'private',
 'mc_currency': u'GBP',
 'mc_fee': u'3.87',
 'mc_gross': u'108.00',
 'notify_version': u'3.8',
 'payer_email': u'private',
 'payer_id': u'private',
 'payer_status': u'verified',
 'payment_date': u'09:01:24 Nov 15, 2014 PST',
 'payment_fee': u'',
 'payment_gross': u'',
 'payment_status': u'Completed',
 'payment_type': u'instant',
 'protection_eligibility': u'Eligible',
 'quantity': u'1',
 'receiver_email': u'sales@andrews-enterprise.co.uk',
 'receiver_id': u'private',
 'residence_country': u'GB',
 'shipping': u'0.00',
 'tax': u'0.00',
 'transaction_subject': u'',
 'txn_id': u'private code',
 'txn_type': u'web_accept',
 'verify_sign': u'secret code'}
2014-11-15 17:18:25,668 1218 INFO odoo openerp.addons.payment_paypal.controllers.main: Paypal: validated data
2014-11-15 17:18:25,671 1218 ERROR odoo openerp.addons.payment_paypal.models.paypal: Paypal: received data for reference SAJ/2014/0002; no order found
2014-11-15 17:18:25,679 1218 INFO odoo werkzeug: 127.0.0.1 - - [15/Nov/2014 17:18:25] "POST /payment/paypal/ipn/ HTTP/1.0" 500 -
2014-11-15 17:18:25,713 1218 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1215, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1189, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1356, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 125, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 130, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 201, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 596, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/openerp/http.py", line 614, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/payment_paypal/controllers/main.py", line 68, in paypal_ipn
    self.paypal_validate_data(*_post)
  File "/opt/odoo/addons/payment_paypal/controllers/main.py", line 57, in paypal_validate_data
    res = request.registry['payment.transaction'].form_feedback(cr, SUPERUSER_ID, post, 'paypal', context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/opt/odoo/addons/website_sale/models/payment.py", line 19, in form_feedback
    res = super(PaymentTransaction, self).form_feedback(cr, uid, data, acquirer_name, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 432, in form_feedback
    tx = getattr(self, tx_find_method_name)(cr, uid, data, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/payment_paypal/models/paypal.py", line 201, in _paypal_form_get_tx_from_data
    raise ValidationError(error_msg)
ValidationError: Paypal: received data for reference SAJ/2014/0002; no order found

**Comment by Yenthe666** [comment]
Hi @AidenAndrews,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
