### ISSUE TITLE
Overriding custom translation terms breaks the translation loading

### ISSUE THREAD

**Issue by ahukkanen** [odoo/odoo#37213]
**Impacted versions:**
12.0, possibly future versions

**Steps to reproduce:**
- Fresh Odoo v12 installation with sample demo data
- Enable developer mode
- Go to Settings > Translations > Load a Translation
- Load Finnish language and choose "Overwrite Existing"
- Go to Settings > Translations > Export Translation
- Select "Finnish", "PO File" format and for Apps To Export, the following list:
  * Sales (`sale`)
  * Sales (`sale_management`)
- Download the generated fi.po file
- Go to the Odoo addons folder and find a folder named "sale"
- Create a new folder there named `i18n_extra`
- Drop the downloaded fi.po file there
- Go to Settings > Translations > Load a Translation
- Load Finnish language and choose "Overwrite Existing"
- Kaboom

**Current behavior:**
You will get see an exception.

**Expected behavior:**
You would not see an exception and the translation import would work.

Why would someone want to do such a horrible thing that would cause this?

We'd like to customize some core translations separately from the core files in a custom module. The behavior is exactly the same when you do this also from custom modules (or just inside a `i18n_extra` folder).

**Possibly related issues:**

https://github.com/odoo/odoo/issues/31583
https://github.com/odoo/docker/issues/219
https://www.odoo.com/fr_FR/forum/aide-1/question/on-conflict-do-update-problem-141853

**Stacktrace:**

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/path/to/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/path/to/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/path/to/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/path/to/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/path/to/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/path/to/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/path/to/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/path/to/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/path/to/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/path/to/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/path/to/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/path/to/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/path/to/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/path/to/addons/website/wizard/base_language_install.py", line 25, in lang_install
    action = super(BaseLanguageInstall, self).lang_install()
  File "/path/to/odoo/addons/base/wizard/base_language_install.py", line 36, in lang_install
    mods.with_context(overwrite=self.overwrite)._update_translations(self.lang)
  File "/path/to/odoo/addons/base/models/ir_module.py", line 885, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/path/to/odoo/addons/base/models/ir_translation.py", line 832, in load_module_terms
    tools.trans_load(self._cr, trans_extra_file, lang, verbose=False, module_name=module_name, context=context)
  File "/path/to/odoo/tools/translate.py", line 1016, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/path/to/odoo/tools/translate.py", line 1160, in trans_load_data
    irt_cursor.finish()
  File "/path/to/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/path/to/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/path/to/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

**Comment by mart-e** [comment]
Hi

Isn't this the same as #32801 (with patch at #32826)

**Comment by ahukkanen** [comment]
@mart-e It sure is! It seems to work correctly with the patch.

Thanks! Closing in favor of #32801.
