### ISSUE TITLE
[12] Survey: Internal Server Error

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#37224]
**Impacted** versions:

12.0

**Steps** to reproduce:

1. Create new database
2. Install "Surveys" module
3. Create new survey with page and question
4. Select "Login required" in Options
5. Test Survey -> Submit answers
6. Click on "review your answers"
7. Internal Server Error

**Comment by Elkasitu** [comment]
Hi,

Just tried this locally and found no errors with just `website_survey` installed, did you try this on [runbot](runbot.odoo.com)?

**Comment by grzekru** [comment]
Hello,

Install "survey" not "website_survey"

**Comment by grzekru** [comment]
Probably missing dependency in survey module.
Also "PRINT SURVEY" button throws error

**Comment by sswapnesh** [comment]
> Probably missing dependency in survey module.

I think same.

@Elkasitu  I can reproduce error with `survey` module
On  `review your answers` (or `Print Survey`)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/home/richa/WS/12.0/odoo/service/server.py", line 409, in app
    return self.app(e, s)
  File "/home/richa/WS/12.0/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/home/richa/WS/12.0/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/richa/WS/12.0/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/home/richa/WS/12.0/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/richa/WS/12.0/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/home/richa/WS/12.0/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/richa/WS/12.0/addons/http_routing/models/ir_http.py", line 397, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/richa/WS/12.0/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/richa/WS/12.0/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/home/richa/WS/12.0/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/home/richa/WS/12.0/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/richa/WS/12.0/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/richa/WS/12.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/richa/WS/12.0/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/home/richa/WS/12.0/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/home/richa/WS/12.0/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/richa/WS/12.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/richa/WS/12.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/richa/WS/12.0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/richa/WS/12.0/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/richa/WS/12.0/addons/survey/controllers/main.py", line 255, in print_survey
    if survey.auth_required and request.env.user == request.website.user_id:
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'HttpRequest' object has no attribute 'website' - - -

```
