### ISSUE TITLE
[8.0] Can't fetch emails

### ISSUE THREAD

**Issue by westito** [odoo/odoo#3735]
When I set up email account, i get this error when fetch new emails: Routing: posting a message without model should be with a parent_id (private mesage).
There is no issue with 7.0

Used version: Nightly 8.0

**Comment by Atheryl** [comment]
Same problem here. Any update ?

**Comment by Yajo** [comment]
Seems like when Odoo does not know where to put an email, it just dies painfully. The very moment a spam email reaches your inbox and Odoo reads it, you get your logs full of this:

```
2016-02-10 08:57:58,287 16 INFO grupoesoc openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server ***
2016-02-10 08:57:58,781 16 ERROR grupoesoc openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server ***
Traceback (most recent call last):
  File "/opt/odoo/extra-addons/core-addons/fetchmail/fetchmail.py", line 246, in fetch_mail
    context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/extra-addons/core-addons/mail/mail_thread.py", line 1213, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/extra-addons/core-addons/mass_mailing/models/mail_thread.py", line 73, in message_route
    return super(MailThread, self).message_route(cr, uid, message, message_dict, model, thread_id, custom_values, context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/extra-addons/core-addons/mail/mail_thread.py", line 1096, in message_route
    update_author=True, assert_model=True, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/extra-addons/core-addons/mail/mail_thread.py", line 850, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
```

And UI gets locked. :unamused: :tada:

**Comment by cmsalmeida** [comment]
check this module https://github.com/thinkopensolutions/tko-social/tree/8.0/tko_fix_mail_private_message_exception

this solution fixes it, even if you receive an email for example from a mailing list with the header TO: to an existent alias.

**Comment by Yenthe666** [comment]
Hi @westito ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
