### ISSUE TITLE
[11.0] [base]: Translation file import fails from the command line

### ISSUE THREAD

**Issue by zachwaite** [odoo/odoo#37393]
Impacted versions: 11.0

Steps to reproduce:

1) Create a translations file on the odoo server filesystem e.g. /tmp/fr_CA.po
2) Use the command line with the --i18n-import option to load it

`./odoo8273-server/odoo-bin -d test --i18n-import=/tmp/test-fr_CA.po --language=fr_CA`

Current behavior:

Error is raised indicating unknown path:

```
Traceback (most recent call last):
  File "./odoo8273-server/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/home/odoo8273/odoo8273-server/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/home/odoo8273/odoo8273-server/odoo/cli/server.py", line 175, in run
    main(args)
  File "/home/odoo8273/odoo8273-server/odoo/cli/server.py", line 158, in main
    import_translation()
  File "/home/odoo8273/odoo8273-server/odoo/cli/server.py", line 119, in import_translation
    cr, config["translate_in"], config["language"], context=context,
  File "/home/odoo8273/odoo8273-server/odoo/tools/translate.py", line 1005, in trans_load
    with file_open(filename, mode='rb') as fileobj:
  File "/home/odoo8273/odoo8273-server/odoo/tools/misc.py", line 175, in file_open
    return _fileopen(name, mode=mode, basedir=base, pathinfo=pathinfo, basename=basename)
  File "/home/odoo8273/odoo8273-server/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /tmp/test-fr_CA.po
```

Expected behavior:

Odoo should import the file from the filesystem location if the odoo system user has permissions to read that file.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hi,

It is because you can not import files outside of the odoo addons-path (for security reasons). It is used to import a file in a module, e.g.
```
$ python odoo-bin -d 11 --i18n-import addons/web/i18n/fr.po -l fr_CA
```
should work
