### ISSUE TITLE
[master] cannot create database (the environment retrieval fails)

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#37795]
Impacted versions: master (13.0alpha1)

Steps to reproduce: create a new database from /web/database/selector

Current behavior:
```
2019-10-02 13:38:50,901 14838 INFO None odoo.service.db: Create database `test`. 
2019-10-02 13:38:51,743 14838 ERROR None odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/home/benoit/Bureau/odoo/odoo/service/db.py", line 60, in _initialize_db
    cr.commit()
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 165, in wrapper
    return f(self, *args, **kwargs)
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 389, in commit
    env = get_env(currentframe(), 2)
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 72, in get_env
    env = getattr(frame.f_locals.get('self'), 'env', SENTINEL)
  File "/home/benoit/Bureau/odoo/odoo/http.py", line 268, in env
    self._env = odoo.api.Environment(self.cr, self.uid, self.context)
  File "/home/benoit/Bureau/odoo/odoo/http.py", line 238, in cr
    raise RuntimeError('request not bound to a database')
RuntimeError: request not bound to a database
2019-10-02 13:38:51,747 14838 ERROR None odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/benoit/Bureau/odoo/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/benoit/Bureau/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/benoit/Bureau/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benoit/Bureau/odoo/odoo/modules/registry.py", line 83, in new
    registry.setup_signaling()
  File "/home/benoit/Bureau/odoo/odoo/modules/registry.py", line 388, in setup_signaling
    self.registry_sequence, self.cache_sequence)
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 423, in __exit__
    self.commit()
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 165, in wrapper
    return f(self, *args, **kwargs)
  File "/home/benoit/Bureau/odoo/odoo/sql_db.py", line 391, in commit
    env['base'].flush()
KeyError: 'base'
2019-10-02 13:38:51,747 14838 WARNING test odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller. 
```

Note that it works well if I revert https://github.com/odoo/odoo/commit/eafdf1812d3ef545400bf9f6acd6842de807a33a

**Comment by sswapnesh** [comment]
Seems to be fixed in https://github.com/odoo/odoo/pull/37005
@Linekio  Can you please update source code and try ? (saas-12.5 branch will be 13)

**Comment by Linekio** [comment]
Oh, yes it works with that branch
