### ISSUE TITLE
Web interface blocked

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#37906]
Impacted versions: 11.0

I have a problem with a file in a database `/web/content/15497-0955739/web.assets_backend.js` everytime the web interface is **blocked**.

![image](https://user-images.githubusercontent.com/7910752/66140915-d3d44780-e5fa-11e9-923e-3705fd8cd034.png)

 it work when **I delete** it from the database 
this is the error in the log 
```
2019-10-03 15:20:23,651 19715 INFO database werkzeug: 127.0.0.1 - - [03/Oct/2019 15:20:23] "GET /web/content/15396-2dc443d/web.assets_common.js HTTP/1.0" 304 -
2019-10-03 15:20:23,653 19721 INFO database odoo.addons.base.ir.ir_attachment: _read_file reading /home/user/.local/share/Odoo/filestore/database/e8/e8731996c27a5f73536d1883e688988edfae2fab
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 15493

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/Odoo/filestore/database/e8/e8731996c27a5f73536d1883e688988edfae2fab'
2019-10-03 15:20:23,657 19721 INFO database odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2019-10-03 15:20:23,659 19721 INFO database werkzeug: 127.0.0.1 - - [03/Oct/2019 15:20:23] "GET /web/content/15493-0955739/web.assets_backend.js HTTP/1.0" 304 -
```

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by m3asmi** [comment]
how is that possible?
 I have the same database duplicated to 3 and the problem is only in one ?!

**Comment by pedrobaeza** [comment]
I can't say, you will need to check the differences, your intermediate proxy, etc.

**Comment by m3asmi** [comment]
if it is a problem with the deployment it should occur to other database too. and it's not the case here!

**Comment by pedrobaeza** [comment]
The reverse can apply as well: if it works in the other, it's not something of Odoo. I can assure you that this problem is not happening in Odoo. I would check some things like file permissions in your side.

**Comment by m3asmi** [comment]
that the first think I did.
All files have the 644 for the user of odoo
