### ISSUE TITLE
Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#3793]
I launched Odoo with apache2 + mod_wsgi. Odoo seems to be working, except for im_chat. When I open chat, it becomes unresponsive or it does not recognize that user is logged in etc. And in log I get this error all the time:
```
[Fri Nov 21 08:14:50 2014] [error] ERROR:openerp.http:Exception during JSON request handling.
[Fri Nov 21 08:14:50 2014] [error] Traceback (most recent call last):
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 500, in _handle_exception
[Fri Nov 21 08:14:50 2014] [error]     return super(JsonRequest, self)._handle_exception(exception)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 517, in dispatch
[Fri Nov 21 08:14:50 2014] [error]     result = self._call_function(**self.params)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 283, in _call_function
[Fri Nov 21 08:14:50 2014] [error]     return checked_call(self.db, *args, **kwargs)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
[Fri Nov 21 08:14:50 2014] [error]     return f(dbname, *args, **kwargs)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 280, in checked_call
[Fri Nov 21 08:14:50 2014] [error]     return self.endpoint(*a, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 733, in __call__
[Fri Nov 21 08:14:50 2014] [error]     return self.method(*args, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 376, in response_wrap
[Fri Nov 21 08:14:50 2014] [error]     response = f(*args, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/addons/bus/bus.py", line 188, in poll
[Fri Nov 21 08:14:50 2014] [error]     raise Exception("bus.Bus unavailable")
```

If there is something I'm missing?

My configuration:
apache site:
```
<VirtualHost *:80>
    ServerName domain.eu
    ServerAlias *.domain.eu // Use this if you want dbfillter on subdomain
    WSGIDaemonProcess oe user=oerp group=www-data processes=2 python-path=/opt/odoo/odoo/ display-name=apache-odoo
    WSGIScriptAlias / /opt/odoo/openerp-wsgi.py
    WSGIProcessGroup oe
    ErrorLog /var/log/odoo/odoo-error.log
    CustomLog /var/log/odoo/odoo-access.log combined
    <Directory /opt/odoo/odoo>
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```
my openerp-wsgi.py:
```
import logging
logging.basicConfig()
import sys
sys.path.append("/opt/odoo/odoo")
import os
activate_this = os.path.expanduser("/opt/odoo/venv/bin/activate_this.py")
execfile(activate_this, dict(__file__=activate_this))
import openerp

#----------------------------------------------------------
# Common
#----------------------------------------------------------
openerp.multi_process = True # Nah!

# Equivalent of --load command-line option
openerp.conf.server_wide_modules = ['web']
conf = openerp.tools.config

# Path to the OpenERP Addons repository (comma-separated for
# multiple locations)

conf['addons_path'] = '/opt/odoo/addons/,/opt/odoo/extra-addons/odoo/addons/,/opt/odoo/odoo/addons/,/opt/odoo/odoo/openerp/addons/'

# Optional database config if not using local socket
conf['db_host'] = '127.0.0.1'
conf['db_user'] = 'user'
conf['db_port'] = 5432
conf['db_password'] = 'password'
conf['dbfilter'] = '^%d$'
conf['longpolling_port'] = 8072

#----------------------------------------------------------
# Generic WSGI handlers application
#----------------------------------------------------------
application = openerp.service.wsgi_server.application

openerp.service.server.load_server_wide_modules()

#----------------------------------------------------------
# Gunicorn
#----------------------------------------------------------
# Standard OpenERP XML-RPC port is 8069
bind = '0.0.0.0:8069'
pidfile = '.gunicorn.pid'
workers = 4
timeout = 240
max_requests = 2000
```

**Comment by jem-odoo** [comment]
Maybe this can help you : https://www.odoo.com/documentation/8.0/setup/deploy.html#odoo-as-a-wsgi-application

**Comment by flotho** [comment]
Hy @oerp-odoo , also have a look there : #3437

**Comment by oerp-odoo** [comment]
I tried @harkx solution (the one without mod_wsgi), but it still not working. Now I don't get bus.bus unavailable error, but chat is still not working. In odoo logs there is nothing. But checking nginx log I see this (everytime it tries to access longpolling):

```
2015/05/08 07:54:09 [error] 32494#0: *8 connect() failed (111: Connection refused) while connecting to upstream, client: IP address, server: _, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://127.0.0.1:8072/longpolling/poll", host: "db.host.eu", referrer: "http://db.host.eu/web"
```

And when I try to connect to `8072` port via telnet:
```
$ telnet 127.0.0.1 8072
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```
But trying for example:
```
oerp@nodvm:~$ telnet 127.0.0.1 8069
Trying 127.0.0.1...
Connected to 127.0.0.1.
```
So it seems that 8072 port is not used?
In my odoo config it is set to be like this:

```
longpolling_port = 8072
xmlrpc_port = 8069
workers = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
```
It seems like it is never using that port. Do I need to somehow enable it for Odoo to start using it?..

**Comment by flotho** [comment]
@oerp-odoo @jssuzanne thanks to both of you, you saved my days

**Comment by galch99** [comment]
<VirtualHost *:80>
ProxyRequests Off
  ProxyPreserveHost On
  ProxyVia full
  ProxyTimeout 18000
  SetEnv proxy-nokeepalive 1
  ProxyPass / http://localhost:8072/
  ProxyPassReverse / http://localhost:8072/
  LogLevel warn
  ErrorLog  /var/log/apache2/1instance.error.log
  CustomLog /var/log/apache2/1instance.access.log combined
</VirtualHost>
error is gone.

**Comment by shyrock** [comment]
I have the same issue 'bus.bus unavailable'. But even after install psycogreen 1.0, longpolling port 8072 is still not opened.
I checked odoo 10.0 source code and found only one line will use longpolling_port, which is in the __init__() of GeventServer, and only when the odoo is configured to use gevent server, the GeventServer will be constructed instead of PreforkServer.

Judge from the code, there is no way to open 8072 under multiprocess mode, then how to get rid of 'bus.bus unavailable' error ?
