### ISSUE TITLE
[13] Uncaught TypeError: Cannot read property 'Search' of undefined

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#37945]
Impacted versions: 13

Steps to reproduce: Edit Form View -->  `Ctrl + F`
![Screenshot (3)](https://user-images.githubusercontent.com/16624719/66161437-e4f87500-e649-11e9-9108-2ebed44bded2.png)

Current behavior: 

```
Error:
Uncaught TypeError: Cannot read property 'Search' of undefined

http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:12203
Traceback:
TypeError: Cannot read property 'Search' of undefined
    at http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:12203:63
    at http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:4467:27
    at Array.forEach (<anonymous>)
    at http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:4466:23
    at _require (http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:88:37)
    at req (http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:138:24)
    at afterLoad (http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:4462:9)
    at HTMLScriptElement.s.onload.s.onreadystatechange (http://640010-13-0-4cc4c9.runbot13.odoo.com/web/static/lib/ace/ace.js:4105:17)


```
Expected behavior: No tracback

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This one was hidden behind

![Screenshot from 2019-10-04 01-56-01](https://user-images.githubusercontent.com/16624719/66161541-26892000-e64a-11e9-80dc-444cff927eee.png)

**Comment by Yenthe666** [comment]
@ged-odoo probably for your team.
