### ISSUE TITLE
[12.0] Scaffold command rises an error 

### ISSUE THREAD

**Issue by estagumor** [odoo/odoo#37964]
**Impacted versions:**
12.0

**Steps to reproduce:** 

./odoo-bin scaffold your_module_name addons/

**Current behavior:** 

`Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/home/solisdm/Documentos/odoo/odoo-12/odoo/__init__.py", line 125, in <module>
    from . import modules
  File "/home/solisdm/Documentos/odoo/odoo-12/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/solisdm/Documentos/odoo/odoo-12/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/home/solisdm/Documentos/odoo/odoo-12/odoo/tools/__init__.py", line 10, in <module>
    from .convert import *
  File "/home/solisdm/Documentos/odoo/odoo-12/odoo/tools/convert.py", line 12, in <module>
    from dateutil.relativedelta import relativedelta
  File "/usr/local/lib/python3.6/dist-packages/dateutil/relativedelta.py", line 118
    raise TypeError, "relativedelta only diffs datetime/date"
                   ^
SyntaxError: invalid syntax`

**Expected behavior:** 

Scaffold a new module in the location I've selected

**Video/Screenshot link (optional):**

![Captura de pantalla de 2019-10-04 11-45-39](https://user-images.githubusercontent.com/19464609/66198354-83adc180-e69c-11e9-9365-6e4727c5b611.png)

**Comment by sswapnesh** [comment]
> ./odoo-bin scaffold your_module_name addons/

Seems working well
![Screenshot from 2019-10-04 23-49-06](https://user-images.githubusercontent.com/16624719/66230359-a1614200-e701-11e9-87d6-789242b45fba.png)

**Comment by Yenthe666** [comment]
Indeed, working fine at my end too. I assume you're local instance has a misconfiguration.
