### ISSUE TITLE
13.0 - Error when installing CRM app on Debian 9

### ISSUE THREAD

**Issue by ibnsaid1** [odoo/odoo#37996]
Impacted versions: 13.0

Steps to reproduce: Install CRM App on Debian 9

Current behavior:
Get the following error message:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1242, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1230, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 365, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python3/dist-packages/odoo/addons/crm/__init__.py", line 5, in <module>
    from . import models
  File "/usr/lib/python3/dist-packages/odoo/addons/crm/models/__init__.py", line 6, in <module>
    from . import crm_lead
  File "/usr/lib/python3/dist-packages/odoo/addons/crm/models/crm_lead.py", line 5, in <module>
    from psycopg2 import sql, extras
ImportError: cannot import name 'sql'

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@d-fence maybe?

**Comment by pedrobaeza** [comment]
But if `psycopg2` is installed, `psycopg2.sql` should be available as well. This seems weird.

What is the installation method you have used?

**Comment by ibnsaid1** [comment]
1. First, I installed postgresql

2. then wkhtmltopdf

3. install git python3-pip build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less

4. pip3
install Babel decorator docutils ebaysdk feedparser gevent greenlet html2text Jinja2 lxml Mako MarkupSafe mock num2words ofxparse passlib Pillow psutil psycogreen psycopg2 pydot pyparsing PyPDF2 pyserial python-dateutil python-openid pytz pyusb PyYAML qrcode reportlab requests six suds-jurko vatnumber vobject Werkzeug XlsxWriter xlwt xlrd polib

5. Then I finally ran:
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/13.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list

apt-get update

apt-get install odoo

I also installed webmin and virtualmin. I recieved a prompt to update odoo to 20191005 earlier today which I did.

- All of the modules/apps have installed fine and so far seem to be working fine, except, the CRM app. To clarify, I'm using Odoo Community Edition

**Comment by pedrobaeza** [comment]
I see several weird steps, like doing `apt-get install odoo`.

Why don't you follow https://www.odoo.com/documentation/13.0/setup/install.html?

Any way, this is not a problem of Odoo itself, but the deployment method, so we should close the issue. If you have more doubts, please open a question on the forums.

**Comment by ibnsaid1** [comment]
apt-get install odoo is also on the link that you've shared

**Comment by ibnsaid1** [comment]
apt-get install odoo is also on the link that you shared.

**Comment by pedrobaeza** [comment]
Right, I didn't remember that step. Any way, you can check on runbot that everything is working fine.

**Comment by d-fence** [comment]
I'll try that this morning and re-open if needed.
The only thing I see is that you try that on Debian 9 (Stretch). Odoo 13 Debian package is built against Debian 10 (Buster). Anyway, it may work with Debian 9 but without any guarantee.

**Comment by ibnsaid1** [comment]
Thanks. I've installed it on Debian 10
