### ISSUE TITLE
[13.0] In the Customer Portal "adding an optional product" gives "Internal Server Error" if Website module not installed

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#38020]
Impacted versions: 13.0, when you click to add a product on the webportal it gives "Internal server error".

Steps to reproduce:
- Install the Sales application and NOT the website application
- Add an additional product to a quotation
- Click on the "Customer Preview" button on the Sales Order
- Under the Options click the "add to cart" button
- Get "Internal server error" screen

Current behavior: when you do not have the Website application installed, you get an error "Internal Server Error" if you want to add an additional product.

Expected behavior: that a user can add an additional product without the need of the website application. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/39414107/66267635-b0481180-e833-11e9-8c9b-680a1239596d.png)

**Comment by pedrobaeza** [comment]
Do you have the corresponding log/traceback of the error?

**Comment by BusinessAgilityMasters** [comment]
2019-10-06 11:04:04,731 7 INFO businessagilitymasters-t-f-g-acceptatie-623981 werkzeug: 24.132.255.159 - - [06/Oct/2019 11:04:04] "POST /web/dataset/call_kw/web_tour.tour/get_consumed_tours HTTP/1.0" 200 - 10 0.004 0.006
2019-10-06 11:04:08,896 7 ERROR businessagilitymasters-t-f-g-acceptatie-623981 odoo.addons.http_routing.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
result = request.dispatch()
File "/home/odoo/src/odoo/odoo/http.py", line 803, in dispatch
r = self._call_function(**self.params)
File "/home/odoo/src/odoo/odoo/http.py", line 345, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/service/model.py", line 93, in wrapper
return f(dbname, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/http.py", line 338, in checked_call
result = self.endpoint(*a, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 909, in __call__
return self.method(*args, **kw)
File "/home/odoo/src/odoo/odoo/http.py", line 510, in response_wrap
response = f(*args, **kw)
File "/home/odoo/src/odoo/addons/sale_management/controllers/portal.py", line 80, in add
return request.redirect(option_sudo.order_id.get_portal_url(anchor='details'))
File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 449, in <lambda>
request.redirect = lambda url, code=302: werkzeug.utils.redirect(url_for(url), code)
File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 185, in url_for
if not request.env['ir.http']._rewrite_len.get(request.website_routing):
File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
AttributeError: 'HttpRequest' object has no attribute 'website_routing'

2019-10-06 11:04:08,951 7 ERROR businessagilitymasters-t-f-g-acceptatie-623981 odoo.sql_db: bad query: UPDATE "sale_order_option" SET "write_uid"=2,"line_id"=46,"write_date"=(now() at time zone 'UTC') WHERE id IN (1)
ERROR: insert or update on table "sale_order_option" violates foreign key constraint "sale_order_option_line_id_fkey"
DETAIL: Key (line_id)=(46) is not present in table "sale_order_line".

2019-10-06 11:04:08,953 7 INFO businessagilitymasters-t-f-g-acceptatie-623981 werkzeug: 24.132.255.159 - - [06/Oct/2019 11:04:08] "GET /my/orders/3/add_option/1?access_token=fdae858f-4fe6-4796-8925-0f75c74403e5 HTTP/1.0" 500 - 70 0.033 0.071
2019-10-06 11:04:08,960 7 ERROR businessagilitymasters-t-f-g-acceptatie-623981 werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/home/odoo/src/odoo/odoo/service/server.py", line 414, in app
return self.app(e, s)
File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 140, in application
return ProxyFix(application_unproxied)(environ, start_response)
File "/usr/local/lib/python3.6/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
return self.app(environ, start_response)
File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1281, in __call__
return self.dispatch(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1251, in __call__
return self.app(environ, start_wrapped)
File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 766, in __call__
return self.app(environ, start_response)
File "/home/odoo/src/odoo/odoo/http.py", line 1450, in dispatch
result = ir_http._dispatch()
File "/home/odoo/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
return super(Http, cls)._dispatch()
File "/home/odoo/src/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
return super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
response = super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 500, in _dispatch
result = super(IrHttp, cls)._dispatch()
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
return cls._handle_exception(e)
File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
response = super(IrHttp, cls)._handle_exception(exc)
File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 626, in _handle_exception
html = env['ir.ui.view'].render_template('http_routing.http_error', values)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 418, in __exit__
self.commit()
File "/home/odoo/src/odoo/odoo/sql_db.py", line 163, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 388, in commit
flush_env(self)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 67, in flush_env
env['base'].flush()
File "/home/odoo/src/odoo/odoo/models.py", line 5215, in flush
process(self.env[model_name], id_vals)
File "/home/odoo/src/odoo/odoo/models.py", line 5206, in process
recs._write(vals)
File "/home/odoo/src/odoo/odoo/models.py", line 3522, in _write
cr.execute(query, params + [sub_ids])
File "/home/odoo/src/odoo/odoo/sql_db.py", line 163, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 240, in execute
res = self._obj.execute(query, params)
psycopg2.IntegrityError: insert or update on table "sale_order_option" violates foreign key constraint "sale_order_option_line_id_fkey"
DETAIL: Key (line_id)=(46) is not present in table "sale_order_line". - - -

**Comment by sswapnesh** [comment]
I can confirm this Issue from Runbot too

**Comment by Feyensv** [comment]
Fixed by https://github.com/odoo/odoo/pull/38191 and https://github.com/odoo/odoo/commit/85c2a18dae3f31daad05f16053277d1b30a4bedb.
Thanks for reporting the bug :+1: .
