### ISSUE TITLE
Procurement  8.0

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#3807]
I get this error for products that are marked as Call for Bids !!!

2014-11-21 22:15:31,791 9913 ERROR coma8 openerp.sql_db: bad query: INSERT INTO "purchase_requisition" ("id", "origin", "exclusive", "multiple_rfq_per_supplier", "user_id", "name", "picking_type_id", "date_end", "company_id", "warehouse_id", "state", "procurement_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('purchase_requisition_id_seq'), '/', 'multiple', false, 1, 'TE00011', 1, '2014-11-26 21:49:05', 1, 2, 'draft', 3, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/odoo-8.0/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "purchase_requisition" violates foreign key constraint "purchase_requisition_picking_type_id_fkey"
DETAIL:  Key (picking_type_id)=(1) is not present in table "stock_picking_type".

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/procurement/wizard/schedulers_all.py", line 62, in _procure_calculation_all
    proc_obj.run_scheduler(new_cr, uid, use_new_cursor=new_cr.dbname, company_id = comp, context=context)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/stock/procurement.py", line 276, in run_scheduler
    super(procurement_order, self).run_scheduler(cr, uid, use_new_cursor=use_new_cursor, context=context)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/procurement/procurement.py", line 320, in run_scheduler
    self.run(cr, SUPERUSER_ID, ids, autocommit=use_new_cursor, context=context)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/stock/procurement.py", line 210, in run
    res = super(procurement_order, self).run(cr, uid, new_ids, autocommit=autocommit, context=context)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/procurement/procurement.py", line 207, in run
    res = self._run(cr, uid, procurement, context=context or {})
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/purchase_requisition/purchase_requisition.py", line 410, in _run
    'product_qty': procurement.product_qty
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/openerp/models.py", line 3972, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/openerp/models.py", line 4110, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/odoo-8.0/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo-8.0/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "purchase_requisition" violates foreign key constraint "purchase_requisition_picking_type_id_fkey"
DETAIL:  Key (picking_type_id)=(1) is not present in table "stock_picking_type".

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
Besides of this it looks like an issue with custom development?

Regards,
Yenthe
