### ISSUE TITLE
[Odoo] v11 Google Calendar Synchro Error

### ISSUE THREAD

**Issue by anabeladamas** [odoo/odoo#38172]
**Impacted versions:**
v11 [11.0-20191004]

**Steps to reproduce:**
I've installed the google calendar app. 
At this moment 8 users from my database have done "Google Sync". 

**Current behavior:**
Each user encounter his own error and for others everything is sync without error.

1.) when user 28 tries to sync the error is several similar to this :
```
 2019-10-08 08:51:46,723 100775 ERROR godoo odoo.addons.google_account.models.google_service: Bad google request : b'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "forbidden",\n    "message": "Forbidden"\n   }\n  ],\n  "code": 403,\n  "message": "Forbidden"\n }\n}\n' !
Traceback (most recent call last):
  File "/opt/godoo/odoo11/odoo/addons/google_account/models/google_service.py", line 172, in _do_request
    res.raise_for_status()
  File "/opt/godoo/odoo11-venv/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/calendar/v3/calendars/primary/events/4fian3a4pqgvidmh4v4tc70qlk_20210222T091500Z?access_token=y....
```
2.) when user 131 tries to sync the error is this :
```
2019-10-08 08:52:35,264 100775 ERROR godoo odoo.sql_db: bad query: UPDATE "calendar_attendee" SET "state"='needsAction',"google_internal_event_id"='6m97lt3jk88jmomdpuouibc2ij_20191016T100000Z',"write_uid"=131,"write_date"=(now() at time zone 'UTC') WHERE id IN (10566)
ERROR: duplicate key value violates unique constraint "calendar_attendee_google_id_uniq"
DETAIL:  Key (google_internal_event_id, partner_id, event_id)=(6m97lt3jk88jmomdpuouibc2ij_20191016T100000Z, 4534, 2282) already exists.

2019-10-08 08:52:35,264 100775 INFO godoo odoo.addons.google_calendar.models.google_calendar: [131] Calendar Synchro - Exception : duplicate key value violates unique constraint "calendar_attendee_google_id_uniq"
DETAIL:  Key (google_internal_event_id, partner_id, event_id)=(6m97lt3jk88jmomdpuouibc2ij_20191016T100000Z, 4534, 2282) already exists.
```

3.)  when user 97 tries to sync the error is this :
```
2019-10-08 08:52:35,485 100775 ERROR godoo odoo.sql_db: bad query: UPDATE "res_users" SET "google_calendar_token_validity"='2019-10-08 09:52:35.485192',"google_calendar_token"='y.....',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (97)
ERROR: current transaction is aborted, commands ignored until end of transaction block
```

4.) In calendars that sync runs without error, duplicated events are being created in google calendar by Odoo.
![calendar_duplicated](https://user-images.githubusercontent.com/10194171/66384068-f927d380-e9b5-11e9-82cb-5610d0b8ca2b.PNG)

5.) When Sync a recursive meeting that was created in Google Calendar, the Odoo sends several emails with the invite to all attendees. 

Can you help to fix this? 
Or explain me the steps to understand what is wrong?

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Some of the problems you have reported are bad deployment, with incorrect tokens or duplicated configs, and others require more information for saying what happens.

Any way, this issue as is can't be qualified for a proper solution as it mixes a lot of things, and lacks any information for being able to take actions, so I'm going to close it.

If you have an enterprise contract, you can issue a request at odoo.com/help for being attended with more detail, or if you focus on thing with detailed steps to reproduce the problem, you can put it here as issue.

Thanks for your understanding.
