### ISSUE TITLE
[13] website module multi language psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update 

### ISSUE THREAD

**Issue by maartenleijnse** [odoo/odoo#38192]
Impacted versions:[13] psycopg2.extensions.TransactionRollbackError

Steps to reproduce: 
load website module, enable on the frontend two languages on a clean db.
switch to another language.
ubuntu 18.04, postgresql 10.10

Current behavior:
Traceback (most recent call last):
  File "/opt/odoo13/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo13/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo13/odoo/service/server.py", line 414, in app
    return self.app(e, s)
  File "/opt/odoo13/odoo/service/wsgi_server.py", line 140, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/opt/odoo13/odoo13-venv/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo13/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo13/odoo/http.py", line 1281, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo13/odoo/http.py", line 1251, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo13/odoo13-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo13/odoo/http.py", line 1454, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo13/odoo/http.py", line 280, in __exit__
    self._cr.commit()
  File "/opt/odoo13/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/odoo/sql_db.py", line 388, in commit
    flush_env(self)
  File "/opt/odoo13/odoo/sql_db.py", line 67, in flush_env
    env['base'].flush()
  File "/opt/odoo13/odoo/models.py", line 5215, in flush
    process(self.env[model_name], id_vals)
  File "/opt/odoo13/odoo/models.py", line 5206, in process
    recs._write(vals)
  File "/opt/odoo13/odoo/models.py", line 3522, in _write
    cr.execute(query, params + [sub_ids])
  File "/opt/odoo13/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update - - -

Expected behavior:
select (edit / view) the other language (either in logged in user or guest)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have several processes at the same time, producing that problem, but this is not something of Odoo itself, but your deployment or other processes accessing the DB.

Closing then.

**Comment by maartenleijnse** [comment]
clean deployment on lxc container with ubuntu 18.04. 
using setup https://github.com/Yenthe666/InstallScript
started with a clean database

can you indicate those processes you see ?

**Comment by maartenleijnse** [comment]
on website turn off Track Visitor (Customize menu) and the error disappears.

**Comment by sammie520** [comment]
Fixed with commit https://github.com/odoo/odoo/commit/cc88a36744dc3c2949c47e8b163e1de98f5dbd95

**Comment by pedrobaeza** [comment]
Thanks for the follow-up and this is one of the weird cases where the concurrency is provoked by some Odoo code. Sorry for not considering that.
