### ISSUE TITLE
payment with CB stripe waiting odoo but ok in stripe.

### ISSUE THREAD

**Issue by hugo49** [odoo/odoo#38422]
**Impacted versions: odoo 12**

Hello,

I have a problem with the base odoo stripe api. Once the purchase order and payment made, odoo makes the invoice. But since a few days, this message is displayed ... The transaction is pending. the 3secure is ok. On the dashboard stripe. everything is OK.

**The transaction SO756-1 with Credit Card for 30,00 € is pending.
A transaction SO756-1 with Bank Card initiated using XXXXXXXXXXXX7266 credit card. Waiting for payment confirmation ...**

**********Dashboard stripe******************

Ce paiement a été vérifié avec la protection 3D Secure et est protégé des contestations pour fraude
Paiement réussi - Paiement démarré - Détails du paiement
Montant 30,00 €
Frais 0,67 €
Net 29,33 €
Statut Réussi
Description SO756-1

Moyen de paiement
Numéro
•••• 7266
Empreinte xxxxxxxx
Expire le xx / xxxxx
Type carte Visa debit
3D Secure Authentifié via 1.0.2
ID pm_*********************************
Adresse Aucune adresse
Origine France Vérification CVC
Réussi

200 OK POST /v1/payment_intents/pi_*******************/confirm
200 OK POST /v1/payment_intents 10/10/2019 

Evénements
La tentative de paiement pi_******************* de 30,00 € a réussi	
xxx@xxx.fr a été facturé d'un montant de 30,00 €		
Une nouvelle tentative de paiement pi_******************* de 30,00 € a été créée	

account.updated
10/10/2019 16:55:48
Détails de l’événement
ID evt_***********************
Date 10/10/2019 16:55:48
Type account.updated
Source Automatique
Données de l’événement
{
  "object": {
    "id": "acct_**********************",
    "object": "account",
    "business_profile": {
      "mcc": "7372",
      "name": "XXXX",
      "support_address": {
        "city": "XXX",
        "country": "FR",
        "line1": "XXXX",
        "line2": null,
        "postal_code": "XXXX",
        "state": "49"
      },
      "support_email": "XXXXX",
      "support_phone": "XXXXX",
      "support_url": "XXXXX.FR",
      "url": "http://XXXX.FR"
    },
    "capabilities": {
      "legacy_payments": "active"
    },
    "charges_enabled": true,
    "country": "FR",
    "default_currency": "eur",
    "details_submitted": true,
    "email": "XXX@XXX.fr",
    "payouts_enabled": true,
    "settings": {
      "branding": {
        "icon": "file_*********************",
        "logo": null,
        "primary_color": "#ffffff"
      },
      "card_payments": {
        "statement_descriptor_prefix": null
      },
      "dashboard": {
        "display_name": "XXXXX",
        "timezone": "Europe/Paris"
      },
      "payments": {
        "statement_descriptor": "AGENCE DE COM",
        "statement_descriptor_kana": null,
        "statement_descriptor_kanji": null
      }
    },
    "type": "standard"
  },
  "previous_attributes": {
  }
}	

---------------------------------------

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/account_payment.py", line 75, in action_validate_invoice_payment
    res = super(AccountPayment, self).action_validate_invoice_payment()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_payment.py", line 683, in action_validate_invoice_payment
    return self.post()
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/account_payment.py", line 103, in post
    transactions.s2s_do_transaction()
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_acquirer.py", line 970, in s2s_do_transaction
    return getattr(trans, custom_method_name)(**kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/payment_stripe_sca/models/payment.py", line 215, in stripe_s2s_do_transaction
    acquirer_ref=self.payment_token_id.acquirer_ref, email=self.partner_email
  File "/usr/lib/python3/dist-packages/odoo/addons/payment_stripe_sca/models/payment.py", line 203, in _stripe_create_payment_intent
    res = self.acquirer_id._stripe_request("payment_intents", charge_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/payment_stripe_sca/models/payment.py", line 54, in _stripe_request
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.stripe.com/v1/payment_intents

**Comment by dbo-odoo** [comment]
Bonjour @hugo49 

Normalement nous n'acceptons pas les reports de bug par Github (le service support est réservé au client payant l'édition Enterprise).

Cependant, dans la mesure ou ce flux est récent suite à un changement de réglementation européenne, je préfère être à l'écoute de certains problèmes.

Pourriez-vous jeter un oeil au logs présents juste avant et juste après cette erreur? Notamment une section débutant par `_stripe_create_payment_intent: Sending values to stripe, values: [...]`? A priori, l'API Github se plaint de ne pas avoir reçu des informations cohérentes pour cet appel, et nous logguons les valeurs envoyées.

Je ne promets pas de résoudre le problème, mais je suis quand même intéressé par les détails si vous en avez.

Je vous conseille par contre de supprimer toutes les informations sensibles (e.g. clés de type `pm_<valeur>` (je viens de le faire pour votre précédent message).

**Comment by hugo49** [comment]
Thank you, but I think I found the worry. The application of the stripe side was up to date. The only problem is that they do not prevent. I noticed it by logging into my account, in the development tab. That is not very practical. That's why the information was not properly formatted.
