### ISSUE TITLE
Error upon google calendar sync

### ISSUE THREAD

**Issue by reilly3000** [odoo/odoo#3853]
I received the following error after setting up Google Calendar sync. The oAuth process worked fine and appears to be configured correctly- this error hit upon using the calendar "Sync now" button. 

OpenERP Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 516, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 279, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 732, in __call__
    return self.method(_args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/http.py", line 375, in response_wrap
    response = f(_args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/google_calendar/google_calendar.py", line 545, in synchronize_events
    res = self.update_events(cr, uid, lastSync, context)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/google_calendar/google_calendar.py", line 803, in update_events
    calendar_event.unlink(cr, uid, "%s-%s" % (parent_oe_id, new_google_event_id), can_be_deleted=True, context=context)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/google_calendar/google_calendar.py", line 947, in unlink
    return super(calendar_event, self).unlink(cr, uid, ids, can_be_deleted=can_be_deleted, context=context)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/calendar/calendar.py", line 1687, in unlink
    res = self.write(cr, uid, id_to_exclure, {'active': False}, context=context)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/google_calendar/google_calendar.py", line 934, in write
    return super(calendar_event, self).write(cr, uid, ids, vals, context=context)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/calendar/calendar.py", line 1532, in write
    real_event_id = calendar_id2real_id(event_id)
  File "/opt/bitnami/apps/openerp/lib/openerp-8.0_911db9d-py2.7.egg/openerp/addons/calendar/calendar.py", line 43, in calendar_id2real_id
    return int(real_id)
ValueError: invalid literal for int() with base 10: 'False'

**Comment by tsbrents** [comment]
Are you still receiving this error?  We're receiving a different error after performing the same actions.

We successfully setup the Google Calendar sync and it works great for standard @gmail accounts.   However, when we create a user with a @googleapps email address the sync fails with this error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 562, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 299, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 791, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 395, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/google_calendar/google_calendar.py", line 563, in synchronize_events
    res = self.update_events(cr, uid, lastSync, context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/google_calendar/google_calendar.py", line 790, in update_events
    res = self.update_from_google(cr, uid, False, event.GG.event, "create", context=context_tmp)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/google_calendar/google_calendar.py", line 421, in update_from_google
    attendee_id = res_partner_obj.search(cr, uid, [('email', '=', google_attendee['email'])], context=context)
KeyError: 'email'

**Comment by Danisan** [comment]
So a workaround for this, should be use a Gmail account and share the calendar with the google apps one.

**Comment by Yenthe666** [comment]
This was fixed at https://github.com/odoo/odoo/commit/caac19c1022344367efa173fda198277e6f0cf85
