### ISSUE TITLE
odoo server error after ocr on "Update Status" button

### ISSUE THREAD

**Issue by herve-guerin-pro** [odoo/odoo#38548]
Impacted versions: v12

Steps to reproduce:
(I think that it can be reproduced, but the stack dump could be meaningful)
from document module, load an purchase invoice as pdf file, transform to bill, launch the ocr recognition
I don't know what happened next, because this was done by a colleague,
sometimes after, I reopen the bill in draft mode, I see that button the green button "Update Status" is there, so I click on it to integrate the result of OCR and I got the error bellow

Current behavior: as described

Expected behavior: integrate the values found by OCR without such error

Complementary information : 

The stack dump : 

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/enterprise/account_invoice_extract/models/account_invoice.py", line 497, in check_status
    self.set_field_with_text(feature, value["selected_text"][0])
  File "/home/odoo/odoo/enterprise/account_invoice_extract/models/account_invoice.py", line 457, in set_field_with_text
    if currency.exists():
AttributeError: 'NoneType' object has no attribute 'exists'

**Comment by pedrobaeza** [comment]
As this involves enterprise modules, please report as an enterprise ticket in odoo.com/help

**Comment by herve-guerin-pro** [comment]
thank you @pedrobaeza and apologies for this misplaced post
