### ISSUE TITLE
[ERROR] :: Multithreading :: long_polling_sapwn :: subprocess.Popen()

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#3878]
#### c22ed1390bcebc3ed5797de874a6c6eadc0cb760 (V8.0)

**_Spontaneously**_ in my instance (with workers, gevented)
all python processes where killed completely
leaving the following ERROR log entry (last entry before restart of odoo service):

```
2014-11-25 07:58:03,009 14436 ERROR ? openerp.service.server: unknown encoding: string-escape
Traceback (most recent call last):
  File "/home/odoo/odoo/openerp/service/server.py", line 633, in run
    self.process_spawn()
  File "/home/odoo/odoo/openerp/service/server.py", line 550, in process_spawn
    self.long_polling_spawn()
  File "/home/odoo/odoo/openerp/service/server.py", line 477, in long_polling_spawn
    popen = subprocess.Popen([sys.executable] + nargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1245, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 971, in load_string
    self.append(rep.decode("string-escape"))
LookupError: unknown encoding: string-escape
```

This seems a borrowed problem of the pickles module however could be related to improper use, google is not very helpful. Only experts might have sufficient insight to make sense of this and fix it.

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
