### ISSUE TITLE
[12.0] auto_join attribute not supported on field product.pricelist.country_group_ids

### ISSUE THREAD

**Issue by DamonLiu0814** [odoo/odoo#39010]
Impacted versions: odoo 12 Comunity

Steps to reproduce:

- set  auto_join=True on all many2mang fields

- update one record on res.partner 

Current behavior: **rasie NotImplementedError: auto_join attribute not supported on field product.pricelist.country_group_ids**

this is full error message:
===============================================================
auto_join attribute not supported on field product.pricelist.country_group_ids Traceback (most recent call last): 
File "/opt/odoo/addons/partner_autocomplete/models/res_partner.py", line 183, in write res = super(ResPartner, self).write(values) 
File "/opt/odoo/odoo/addons/base/models/res_partner.py", line 571, in write result = result and super(Partner, self).write(vals) 
File "/opt/odoo/addons/mail/models/mail_thread.py", line 322, in write result = super(MailThread, self).write(values) 
File "/opt/odoo/addons/mail/models/mail_activity.py", line 579, in write return super(MailActivityMixin, self).write(vals) 
File "/opt/odoo/odoo/models.py", line 3347, in write fields[0].determine_inverse(records) 
File "/opt/odoo/odoo/fields.py", line 1117, in determine_inverse getattr(records, self.inverse)() 
File "<decorator-gen-154>", line 2, in _inverse_product_pricelist 
File "/opt/odoo/odoo/api.py", line 372, in loop result = [method(rec, *args, **kwargs) for rec in self] File "/opt/odoo/odoo/api.py", line 372, in <listcomp> result = [method(rec, *args, **kwargs) for rec in self] 
File "/opt/odoo/addons/product/models/res_partner.py", line 29, in _inverse_product_pricelist limit=1 
File "/opt/odoo/odoo/models.py", line 1561, in search res = self._search(args, offset=offset, limit=limit, order=order, count=count) 
File "/opt/odoo/odoo/models.py", line 4104, in _search query = self._where_calc(args) 
File "/opt/odoo/odoo/models.py", line 3896, in _where_calc e = expression.expression(domain, self) File "/opt/odoo/odoo/osv/expression.py", line 672, in __init__ self.parse() 
File "/opt/odoo/odoo/osv/expression.py", line 901, in parse raise NotImplementedError('auto_join attribute not supported on field %s' % field) 
NotImplementedError: auto_join attribute not supported on field product.pricelist.country_group_ids

**Comment by pedrobaeza** [comment]
The error is clear: you can't use auto_join in that table. If you want to do it massively (which is not advisable), you must exclude that field.

Closing as no issue.
