### ISSUE TITLE
[V8]Create invoice with a filter activated create an error

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#3906]
Go to invoice
Filter by any field you want (eg the name of a partner)
Create an invoice,

You'll have this message : 

```
Traceback (most recent call last):
  File "/home/openerp/odoo/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openerp/odoo/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/home/openerp/odoo/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openerp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openerp/odoo/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/openerp/odoo/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/home/openerp/odoo/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/openerp/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/openerp/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/openerp/odoo/openerp/models.py", line 5754, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/openerp/odoo/openerp/models.py", line 5688, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/home/openerp/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/openerp/odoo/addons/account/account_invoice.py", line 533, in onchange_company_id
    if p.property_account_payable and p.property_account_receivable and \
  File "/home/openerp/odoo/openerp/fields.py", line 767, in __get__
    self.determine_value(record)
  File "/home/openerp/odoo/openerp/fields.py", line 860, in determine_value
    record._prefetch_field(self)
  File "/home/openerp/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/models.py", line 3165, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/openerp/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/home/openerp/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/models.py", line 3222, in _read_from_database
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/home/openerp/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openerp/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: ERREUR:  syntaxe en entrée invalide pour l'entier : « jaubert »
LIGNE 2 :                     WHERE res_partner.id IN ('jaubert') AND ...
```

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
