### ISSUE TITLE
[13.0] "Add new countries" in "EU Digital Goods VAT": issue ValueError: Invalid field 'account_id' in leaf

### ISSUE THREAD

**Issue by actonsys** [odoo/odoo#39147]
Impacted versions:13.0 CE & EE, tested on runbot

Steps to reproduce:

1. Go to Invoicing or Accounting > Configuration > Settings
2. Check "EU Digital Goods VAT" and click Save
3. Click on "Add new countries" in "EU Digital Goods VAT"

Current behavior:
**(reproducible on runbot)**
Raise the following error
`ValueError: Invalid field 'account_id' in leaf "<osv.ExtendedLeaf: ('account_id', '!=', False) on account_tax (ctx: )>"`

Expected behavior:
Open Wizard and setup Fiscal Positions and Taxes accordingly.

Video/Screenshot link (optional):
`Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 406, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 379, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 1153, in default_get
    defaults[name] = field.default(self)
  File "/data/build/odoo/addons/l10n_eu_service/wizard/wizard.py", line 34, in _default_tax_id
    ('amount_type', '=', 'percent'), ('account_id', '!=', False)], limit=1, order='amount desc')
  File "/data/build/odoo/odoo/models.py", line 1556, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/data/build/odoo/addons/account/models/account.py", line 1296, in _search
    return super(AccountTax, self)._search(args, offset, limit, order, count=count, access_rights_uid=access_rights_uid)
  File "/data/build/odoo/odoo/models.py", line 4282, in _search
    query = self._where_calc(args)
  File "/data/build/odoo/odoo/models.py", line 4021, in _where_calc
    e = expression.expression(domain, self)
  File "/data/build/odoo/odoo/osv/expression.py", line 673, in __init__
    self.parse()
  File "/data/build/odoo/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'account_id' in leaf "<osv.ExtendedLeaf: ('account_id', '!=', False) on account_tax (ctx: )>"`

**Comment by Yenthe666** [comment]
I've also been bitten by this issue so I've reported it through my customer his enterprise license. Odoo ticket `2123656`

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/87f2aae6c91e70f4f4102bf7ea41858db7dee16f
