### ISSUE TITLE
account module raise column reference "credit" is ambiguous

### ISSUE THREAD

**Issue by jellyhappy** [odoo/odoo#39152]
Impacted versions: 12.0

Steps to reproduce:

1. open an point of sale
2. sale something
3. close the session

Current behavior:

raise an exception:

```
2019-10-22 05:57:44,164 23887 ERROR odoo odoo.sql_db: bad query: 
            SELECT line.move_id, ROUND(SUM(debit - credit), currency.decimal_places)
            FROM account_move_line line
            JOIN account_move move ON move.id = line.move_id
            JOIN account_journal journal ON journal.id = move.journal_id
            JOIN res_company company ON company.id = journal.company_id
            JOIN res_currency currency ON currency.id = company.currency_id
            WHERE line.move_id IN (134)
            GROUP BY line.move_id, currency.decimal_places
            HAVING ROUND(SUM(debit - credit), currency.decimal_places) != 0.0;
        
ERROR: column reference "credit" is ambiguous
LINE 2: ...           SELECT line.move_id, ROUND(SUM(debit - credit), c...
                                                             ^
 
2019-10-22 05:57:44,165 23887 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_session.py", line 273, in action_pos_session_validate
    self.action_pos_session_close()
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_session.py", line 290, in action_pos_session_close
    self.with_context(ctx)._confirm_orders()
  File "/home/ubuntu/odoo/orssica/pos_retail/models/pos/pos_session.py", line 28, in _confirm_orders
    company_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_order.py", line 164, in _create_account_move
    return self.env['account.move'].sudo().create({'ref': ref, 'journal_id': journal_id, 'date': date_tz_user})
  File "<decorator-gen-267>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 278, in create
    move.assert_balanced()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 401, in assert_balanced
    ''', [tuple(self.ids)])
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column reference "credit" is ambiguous
LINE 2: ...           SELECT line.move_id, ROUND(SUM(debit - credit), c...
```

**Comment by block-cat** [comment]
the relevant commit is [this](https://github.com/odoo/odoo/commit/d00e3158cd30067f7cc8d524eff81ccd6e620342)

**Comment by Yenthe666** [comment]
@nim-odoo and @jev-odoo for you guys

**Comment by pedrobaeza** [comment]
Any news about this?
