### ISSUE TITLE
Website Editor - Edit Menu doest save after adding category

### ISSUE THREAD

**Issue by kuhnnl** [odoo/odoo#3929]
The Website Editor won't let me save a new created category in the "Edit Menu".  

I've tried with Internet Explorer, Firefox, Chrome neither will save the new category  

My version of Odoo 8 is installed on a Windows PC with the latest release.

Thanks in advance.

Update : In a new installation on a Linux server there are no problems with saving categories

**Comment by cfrancois7** [comment]
Hello,

I've the same issue on my W8 PC but not on my MacOSX (yosemite), everything is fine.

```
Traceback (most recent call last):
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\addons\website\models\ir_http.py", line 204, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\addons\base\ir\ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 617, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\addons\base\ir\ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 635, in dispatch
    r = self._call_function(**self.params)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\service\model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\addons\website\controllers\main.py", line 171, in pagenew
    }, context=request.context)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\models.py", line 3999, in create
    record = self.browse(self._create(old_vals))
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "C:\Bitnami\odoo-8.0-6\apps\odoo\Lib\site-packages\odoo-8.0_a2115ef-py2.7.egg\openerp\models.py", line 4165, in _create
    cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by Yenthe666** [comment]
Hi @kuhnnl ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
