### ISSUE TITLE
[11.0][stock] (Critical) cannot install stock addon since last pull 2019-10-30

### ISSUE THREAD

**Issue by 234234neios** [odoo/odoo#39581]
Impacted versions: 11.0

Steps to reproduce: creating a DB without demo data, log with admin, install stock addon

Current behavior:
2019-10-30 12:53:31,302 8315 INFO 12time_odoo odoo.modules.loading: loading sms/views/templates.xml
2019-10-30 12:53:31,559 8315 WARNING 12time_odoo odoo.fields: Field stock.return.picking.line.move_id with unknown comodel_name 'stock.move'
2019-10-30 12:53:31,560 8315 WARNING 12time_odoo odoo.fields: Field stock.return.picking.picking_id with unknown comodel_name 'stock.picking'
2019-10-30 12:53:31,560 8315 WARNING 12time_odoo odoo.fields: Field stock.return.picking.original_location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,560 8315 WARNING 12time_odoo odoo.fields: Field stock.return.picking.parent_location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,560 8315 WARNING 12time_odoo odoo.fields: Field stock.return.picking.location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,561 8315 WARNING 12time_odoo odoo.fields: Field stock.change.product.qty.lot_id with unknown comodel_name 'stock.production.lot'
2019-10-30 12:53:31,561 8315 WARNING 12time_odoo odoo.fields: Field stock.change.product.qty.location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,562 8315 WARNING 12time_odoo odoo.fields: Field stock.immediate.transfer.pick_ids with unknown comodel_name 'stock.picking'
2019-10-30 12:53:31,563 8315 WARNING 12time_odoo odoo.fields: Field stock.backorder.confirmation.pick_ids with unknown comodel_name 'stock.picking'
2019-10-30 12:53:31,563 8315 WARNING 12time_odoo odoo.fields: Field stock.overprocessed.transfer.picking_id with unknown comodel_name 'stock.picking'
2019-10-30 12:53:31,564 8315 WARNING 12time_odoo odoo.fields: Field stock.warn.insufficient.qty.location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,564 8315 WARNING 12time_odoo odoo.fields: Field stock.warn.insufficient.qty.quant_ids with unknown comodel_name 'stock.quant'
2019-10-30 12:53:31,565 8315 WARNING 12time_odoo odoo.fields: Field stock.warn.insufficient.qty.scrap.scrap_id with unknown comodel_name 'stock.scrap'
2019-10-30 12:53:31,565 8315 WARNING 12time_odoo odoo.fields: Field stock.warn.insufficient.qty.scrap.location_id with unknown comodel_name 'stock.location'
2019-10-30 12:53:31,565 8315 WARNING 12time_odoo odoo.fields: Field stock.warn.insufficient.qty.scrap.quant_ids with unknown comodel_name 'stock.quant'
2019-10-30 12:53:31,581 8315 WARNING 12time_odoo odoo.modules.loading: Transient module states were reset
2019-10-30 12:53:31,584 8315 ERROR 12time_odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/models.py", line 2435, in _setup_fields
    field.setup_full(self)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/fields.py", line 472, in setup_full
    self._setup_related_full(model)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/fields.py", line 509, in _setup_related_full
    field = target._fields[name]
KeyError: 'product_uom'
2019-10-30 12:53:31,586 8315 ERROR 12time_odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/ddrapeau/Projets/odoo/11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/ddrapeau/Projets/odoo/11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/models.py", line 2435, in _setup_fields
    field.setup_full(self)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/fields.py", line 472, in setup_full
    self._setup_related_full(model)
  File "/home/ddrapeau/Projets/odoo/11.0/odoo/fields.py", line 509, in _setup_related_full
    field = target._fields[name]
KeyError: 'product_uom'

Expected behavior:
Module should be installed without any error or warning messsage
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
