### ISSUE TITLE
[Master] [500 Internal Server Error] domain.tld/website/info

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#3960]
Hey all i came across this error today. When the website information view is deactivated instead of showing 404 error it throws a 500 error on browser and the following in the log file.

```
 File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)2014-11-30 13:17:34,115 18490 ERROR ae werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 234, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1215, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1189, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1356, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/addons/website/models/ir_http.py", line 128, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 110, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/addons/website/models/ir_http.py", line 258, in _handle_exception
    html = request.website._render('website.http_error', values)
  File "/opt/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/addons/website/models/website.py", line 311, in _render
    return self.pool['ir.ui.view'].render(cr, uid, template, values=values, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 189, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1079, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 246, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 313, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 290, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 439, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 246, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 313, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 313, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 318, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 313, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 290, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/addons/website/models/ir_qweb.py", line 76, in render_tag_call_assets
    qwebcontext.context['url_for'] = request.website.get_cdn_url
  File "/opt/odoo/openerp/tools/misc.py", line 1250, in __setitem__
    raise NotImplementedError("'__setitem__' not supported on frozendict")
QWebException: '__setitem__' not supported on frozendict
```

Done by disabling view with technical view privileges on settings -> ui -> views -> website information.

version 8 stable shows 404 this version show's 500 and extra bug when view disabled still shows on sitemap.

**Comment by mart-e** [comment]
Hello,

I can not reproduce this 500 error anymore and a disable option was added in 8.0 at f025d3e (so no need to add group on the view).
Also please reports bugs on stable versions only as the master is unstable so it is very likely that you get temporary issues.

**Comment by ddfs** [comment]
option is available but website/info still reachable. should be able to remove it from http.routes since it is not really necessary on public pages. it could be moved to back-end maybe ??
