### ISSUE TITLE
UnicodeEncodeError on error when setting VAT number

### ISSUE THREAD

**Issue by fr3aker** [odoo/odoo#39690]
Impacted versions:
Odoo 13 (branch `13.0`) (5e562eae40c2c09cfc0545ed78ad2e91af525dd5)

Steps to reproduce:
1. Set up Odoo with german language
2. Try to set invalid VAT number

Current behavior:
internal exception, no user feedback

Expected behavior:
Error message shown, indicating the error/problem

Error log:

```
Traceback (most recent call last):
  File "/svr/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/svr/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/svr/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/svr/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/svr/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/svr/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/svr/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/svr/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/svr/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/svr/odoo/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/svr/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/svr/odoo/odoo/odoo/api.py", line 411, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/svr/odoo/odoo/odoo/api.py", line 398, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/svr/odoo/odoo/addons/account/models/company.py", line 253, in write
    return super(ResCompany, self).write(values)
  File "/svr/odoo/odoo/addons/product/models/res_company.py", line 65, in write
    return super(ResCompany, self).write(values)
  File "/svr/odoo/odoo/odoo/addons/base/models/res_company.py", line 248, in write
    return super(Company, self).write(values)
  File "/svr/odoo/odoo/odoo/models.py", line 3494, in write
    fields[0].determine_inverse(real_recs)
  File "/svr/odoo/odoo/odoo/fields.py", line 1160, in determine_inverse
    self.inverse(records)
  File "/svr/odoo/odoo/odoo/fields.py", line 655, in _inverse_related
    target[field.name] = record_value[record]
  File "/svr/odoo/odoo/odoo/models.py", line 5488, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/svr/odoo/odoo/odoo/fields.py", line 1129, in __set__
    records.write({self.name: write_value})
  File "/svr/odoo/odoo/addons/base_vat/models/res_partner.py", line 420, in write
    return super(ResPartner, self).write(values)
  File "/svr/odoo/odoo/addons/snailmail/models/res_partner.py", line 24, in write
    return super(ResPartner, self).write(vals)
  File "/svr/odoo/odoo/addons/partner_autocomplete/models/res_partner.py", line 197, in write
    res = super(ResPartner, self).write(values)
  File "/svr/odoo/odoo/odoo/addons/base/models/res_partner.py", line 520, in write
    result = result and super(Partner, self).write(vals)
  File "/svr/odoo/odoo/addons/mail/models/mail_activity.py", line 680, in write
    return super(MailActivityMixin, self).write(vals)
  File "/svr/odoo/odoo/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/svr/odoo/odoo/addons/website/models/mixins.py", line 164, in write
    return super(WebsitePublishedMixin, self).write(values)
  File "/svr/odoo/odoo/odoo/models.py", line 3489, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/svr/odoo/odoo/odoo/models.py", line 1115, in _validate_fields
    check(self)
  File "/svr/odoo/odoo/addons/base_vat/models/res_partner.py", line 186, in check_vat
    raise ValidationError(msg)
odoo.exceptions.ValidationError: 
#012During handling of the above exception, another exception occurred:#012
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 31: ordinal not in range(128)
#012During handling of the above exception, another exception occurred:#012
Traceback (most recent call last):
  File "/svr/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/svr/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/svr/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/svr/odoo/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/svr/odoo/odoo/odoo/http.py", line 680, in dispatch
    return self._handle_exception(e)
  File "/svr/odoo/odoo/odoo/http.py", line 626, in _handle_exception
    _logger.warning(exception)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1524, in callHandlers
    lastResort.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 918, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "/usr/lib64/python3.6/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 64: ordinal not in range(128)
#012During handling of the above exception, another exception occurred:#012
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 3808: ordinal not in range(128)
#012During handling of the above exception, another exception occurred:#012
Traceback (most recent call last):
  File "/svr/odoo/odoo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/svr/odoo/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/svr/odoo/odoo/odoo/http.py", line 1281, in __call__
    return self.dispatch(environ, start_response)
  File "/svr/odoo/odoo/odoo/http.py", line 1251, in __call__
    return self.app(environ, start_wrapped)
  File "/svr/odoo/venv/lib64/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/svr/odoo/odoo/odoo/http.py", line 1450, in dispatch
    result = ir_http._dispatch()
  File "/svr/odoo/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/svr/odoo/odoo/addons/website/models/ir_http.py", line 168, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/svr/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/svr/odoo/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/svr/odoo/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/svr/odoo/odoo/addons/http_routing/models/ir_http.py", line 505, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/svr/odoo/odoo/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
    return cls._handle_exception(e)
  File "/svr/odoo/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/svr/odoo/odoo/addons/http_routing/models/ir_http.py", line 596, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/svr/odoo/odoo/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
    return request._handle_exception(exception)
  File "/svr/odoo/odoo/odoo/http.py", line 628, in _handle_exception
    _logger.exception("Exception during JSON request handling.")
  File "/usr/lib64/python3.6/logging/__init__.py", line 1343, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1524, in callHandlers
    lastResort.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 918, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "/usr/lib64/python3.6/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 64: ordinal not in range(128)


```

**Comment by intero-chz** [comment]
Do you mean Odoo 13 oder Odoo master (14)? The latest enterprise runbot for 13 is working as expected:

> Die UStID Nummer [DE1111] des Partners [Test German] weicht vom erwarteten Format DE123456788 ab und konnte nicht erfolgreich durch die VIES VAT Prüfung validiert werden.

The problematic character is obviously `ü`.

**Comment by fr3aker** [comment]
Sorry, I meant branch `13.0`

**Comment by C3POdoo** [comment]
Dear @fr3aker,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
