### ISSUE TITLE
[13.0] eCommerce: Error upon enabling Accept Terms & Conditions: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by L00N1** [odoo/odoo#39814]
Impacted versions:
13c + 13e

Steps to reproduce:
- Log in as admin
- Go to website
- Add random product into basket
- Go through to checkout page
- Click on: Customize -> Allow Accept Terms & Conditions
- Error

Current behavior:
- Error
- Cannot Confirm purchase and checkout

Traceback:
TypeError: Cannot read property 'data' of undefined
    at Class._adaptPayButton (http://localhost:8069/web/content/713-0059446/1/web.assets_frontend_lazy.js:251:509)
    at Class._onCGVCheckboxClick (http://localhost:8069/web/content/713-0059446/1/web.assets_frontend_lazy.js:251:751)
    at HTMLInputElement.<anonymous> (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:3845:11)
    at HTMLDivElement.dispatch (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:925:447)
    at HTMLDivElement.elemData.handle (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:911:166)
    at Object.trigger (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:1142:227)
    at HTMLInputElement.<anonymous> (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:1148:258)
    at Function.each (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:624:170)
    at jQuery.fn.init.each (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:615:192)
    at jQuery.fn.init.trigger (http://localhost:8069/web/content/712-c5c2e2a/1/web.assets_common_lazy.js:1148:229)

This happens to localhost (Windows) as well as on servers (Linux)

Browsers: Chrome + Brave

Thanks in advance for your help.

Expected behavior:
- No error
- Payment button working to checkout

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I can confirm this error too
![Screenshot (1)](https://user-images.githubusercontent.com/16624719/68232819-eab7f080-0023-11ea-89c9-6f64b251e132.png)

```
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Class._adaptPayButton (website_sale_payment.js:30)
    at Class._onCGVCheckboxClick (website_sale_payment.js:45)
    at HTMLInputElement.<anonymous> (mixins.js:277)
    at HTMLDivElement.dispatch (jquery.js:5183)
    at HTMLDivElement.elemData.handle (jquery.js:4991)
    at Object.trigger (jquery.js:8249)
    at HTMLInputElement.<anonymous> (jquery.js:8327)
    at Function.each (jquery.js:354)
    at jQuery.fn.init.each (jquery.js:189)
    at jQuery.fn.init.trigger (jquery.js:8326)
```

**Comment by Yenthe666** [comment]
OPW `2122942`
