### ISSUE TITLE
Issue in message channel notification mechanism 

### ISSUE THREAD

**Issue by juppe** [odoo/odoo#39896]
Impacted versions:
12.0 (7d1d3fe1e6be91746e5cc969315a7bb95161bd3f)

Steps to reproduce:
1. Create new db with demodata and install the Sales module
1. Log in as Mitchell Admin in two separate tabs and keep them both open
1. Create a new private discussion channel and check that only Micthell is a member of that channel
1. Add the newly created private discussion channel as a follower on the _FURN_6666 Acoustic Bloc Screens_ product template
1. Update Marc Demo's access rights to Sales --> Manager
1. Create an Scheduled Action that operates on the Product Template model and executes this Python code:
```
marc = env['res.users'].search([('name','=','Marc Demo')])
product_tmpl = env['product.template'].search([('default_code','=','FURN_6666')])
product_tmpl.sudo(marc.id).message_post(body='New Test', message_type="comment", subtype="mt_comment")
```
7. Run the Scheduled action

Current behavior:
The members of a private discussion group are notified with an Odoo Server Error stacktrace dialog when we run e.g a scheduled action, or some other script, where we post a message on a record, with a private discussion group as a follower, and the `.message_post()` is called using `.sudo(someuser.id)` where the someuser is not a member of the private message group.

The notification data that goes into bus.bus looks like this:
https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_channel.py#L512-L524
Note that here `'channel_ids': []` 

```[
  [
    (
      '12testdb', 
      'mail.channel', 
      5
    ), 
    {'id': 208, 
    'body': '<p>Test</p>', 
    'date': datetime.datetime(2019, 11, 6, 14, 43, 50), 
    'author_id': (
      7, 
      'YourCompany, 
      Marc Demo'
    ), 
    'email_from': 'Marc Demo <mark.brown23@example.com>', 
    'message_type': 'comment', 
    'subtype_id': (1, 'Discussions'), 
    'subject': False, 
    'model': 'product.template', 
    'res_id': 23, 
    'record_name': '[FURN_6666] Acoustic Bloc Screens', 
    'channel_ids': [], 
    'partner_ids': [], 
    'starred_partner_ids': [], 
    'moderation_status': False, 
    'customer_email_status': 'sent', 
    'customer_email_data': [], 
    'attachment_ids': [], 
    'tracking_value_ids': [], 
    'needaction_partner_ids': [], 
    'is_note': False, 
    'is_discussion': True, 
    'is_notification': False, 
    'subtype_description': False, 
    'module_icon': '/product/static/description/icon.png'
    }
  ]
]
```

When the same data arrives in the JS notification handler it looks loke this:
https://github.com/odoo/odoo/blob/13.0/addons/mail/static/src/js/services/mail_notification_manager.js#L583-L611
Note that now `"channel_ids": ["product.template_23"]`

```[
  [
    [
      "12testdb",
      "mail.channel",
      5
    ],
    {
      "id": 208,
      "body": "<p>Test</p>",
      "date": "2019-11-06 14:43:50",
      "author_id": [
        7,
        "YourCompany, Marc Demo"
      ],
      "email_from": "Marc Demo <mark.brown23@example.com>",
      "message_type": "comment",
      "subtype_id": [
        1,
        "Discussions"
      ],
      "subject": false,
      "model": "product.template",
      "res_id": 23,
      "record_name": "[FURN_6666] Acoustic Bloc Screens",
      "channel_ids": [
        "product.template_23"
      ],
      "partner_ids": [],
      "starred_partner_ids": [],
      "moderation_status": false,
      "customer_email_status": "sent",
      "customer_email_data": [],
      "attachment_ids": [],
      "tracking_value_ids": [],
      "needaction_partner_ids": [],
      "is_note": false,
      "is_discussion": true,
      "is_notification": false,
      "subtype_description": false,
      "module_icon": "/product/static/description/icon.png"
    }
  ]
]
```

The `"product.template_23"` string is treated as a channel id, which it's not, and therefore we crash followingly:
```
Odoo Server Error
Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 'product.template_23'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 989, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ("mail.channel('product.template_23',).channel_last_seen_partner_ids", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/johan/Sites/odoo-12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/Users/johan/Sites/odoo-12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/johan/Sites/odoo-12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/addons/mail/models/mail_channel.py", line 810, in channel_join_and_get_info
    added = self.action_follow()
  File "/Users/johan/Sites/odoo-12/addons/mail/models/mail_channel.py", line 285, in action_follow
    channel_partner = self.mapped('channel_last_seen_partner_ids').filtered(lambda cp: cp.partner_id == self.env.user.partner_id)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4870, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4849, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4849, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 5120, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 993, in __get__
    self.determine_value(record)
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 1096, in determine_value
    record._prefetch_field(self)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2842, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2780, in read
    self._read_from_database(stored, inherited)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2907, in _read_from_database
    cr.execute(query_str, params)
  File "/Users/johan/Sites/odoo-12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "product.template_23"
LINE 1: ..." FROM "mail_channel" WHERE "mail_channel".id IN ('product.t...
                                                             ^
```
I was not able to locate the exact code where the string representation of the record to which the message is posted gets inserted in the `channel_ids` list, so I'm hoping someone can help me with that, so we can fix this issue.

Expected behavior:
I would expect that the message notification mechanism would work correctly, also when the user posting the message is not a member of the private discussion channel, that is a follower of the specific record where the message is posted.

Video/Screenshot link:
https://youtu.be/ZG1GMae7yZY

**Comment by pedrobaeza** [comment]
@tivisse can this be something for you?

**Comment by juppe** [comment]
Here's also the relevant piece of the server log:

```
2019-11-06 15:15:28,678 2218 INFO 12testdb werkzeug: 127.0.0.1 - - [06/Nov/2019 15:15:28] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 - 4 0.003 0.007
2019-11-06 15:15:34,869 2218 INFO 12testdb werkzeug: 127.0.0.1 - - [06/Nov/2019 15:15:34] "POST /web/dataset/call_button HTTP/1.1" 200 - 52 0.042 0.035
2019-11-06 15:15:34,876 2218 INFO 12testdb werkzeug: 127.0.0.1 - - [06/Nov/2019 15:15:34] "POST /longpolling/poll HTTP/1.1" 200 - 11 0.008 18.027
2019-11-06 15:15:34,914 2218 INFO 12testdb werkzeug: 127.0.0.1 - - [06/Nov/2019 15:15:34] "POST /web/dataset/call_kw/ir.cron/read HTTP/1.1" 200 - 16 0.016 0.018
2019-11-06 15:15:34,916 2218 ERROR 12testdb odoo.sql_db: bad query: SELECT "mail_channel"."id" as "id" FROM "mail_channel" WHERE "mail_channel".id IN ('product.template_23') AND ((("mail_channel"."public" = 'public')  OR  (("mail_channel"."public" = 'private')  AND  ("mail_channel"."id" in (SELECT "channel_id" FROM "mail_channel_partner" WHERE "partner_id" IN (3)))))  OR  (("mail_channel"."public" = 'groups')  AND  ("mail_channel"."group_public_id" in (2,22,26,7,1,18,21,36,3,23,6,30,20,19))))
ERROR: invalid input syntax for integer: "product.template_23"
LINE 1: ..." FROM "mail_channel" WHERE "mail_channel".id IN ('product.t...
                                                             ^
 
2019-11-06 15:15:34,916 2218 ERROR 12testdb odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 'product.template_23'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 989, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ("mail.channel('product.template_23',).channel_last_seen_partner_ids", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/johan/Sites/odoo-12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/Users/johan/Sites/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/Users/johan/Sites/odoo-12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/johan/Sites/odoo-12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/addons/mail/models/mail_channel.py", line 810, in channel_join_and_get_info
    added = self.action_follow()
  File "/Users/johan/Sites/odoo-12/addons/mail/models/mail_channel.py", line 285, in action_follow
    channel_partner = self.mapped('channel_last_seen_partner_ids').filtered(lambda cp: cp.partner_id == self.env.user.partner_id)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4870, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4849, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 4849, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 5120, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 993, in __get__
    self.determine_value(record)
  File "/Users/johan/Sites/odoo-12/odoo/fields.py", line 1096, in determine_value
    record._prefetch_field(self)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2842, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2780, in read
    self._read_from_database(stored, inherited)
  File "/Users/johan/Sites/odoo-12/odoo/models.py", line 2907, in _read_from_database
    cr.execute(query_str, params)
  File "/Users/johan/Sites/odoo-12/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/johan/Sites/odoo-12/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "product.template_23"
LINE 1: ..." FROM "mail_channel" WHERE "mail_channel".id IN ('product.t...
                                                             ^
2019-11-06 15:15:34,941 2218 INFO 12testdb werkzeug: 127.0.0.1 - - [06/Nov/2019 15:15:34] "POST /web/dataset/call_kw/mail.channel/channel_join_and_get_info HTTP/1.1" 200 - 2 0.002 0.037
```

**Comment by tivisse** [comment]
Thanks for the feedback. 

Indeed it seems strange ;)

cc @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
:face_with_head_bandage:

**Comment by C3POdoo** [comment]
Dear @juppe,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
