### ISSUE TITLE
Export audit file - General Ledger gives an error

### ISSUE THREAD

**Issue by bizzappdevteam** [odoo/odoo#39932]
Impacted versions:
Module : l10n_nl_reports
Branch : 12.0
Repository : enterprise

Steps to reproduce:
- When we go to accounting - reporting - general ledger and click on the button "Export (XAF)", we got the following error.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_nl_reports_xaf_audit_file_1201
  File "<template>", line 26, in foreach_1152
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/enterprise/account_reports/controllers/main.py", line 51, in get_report
    content = report_obj.get_xaf(options)
  File "/opt/odoo/enterprise/l10n_nl_reports/models/account_general_ledger.py", line 138, in get_xaf
    audit_content = self.env['ir.qweb'].render('l10n_nl_reports.xaf_audit_file', values)
  File "/opt/odoo/enterprise/web_studio/models/ir_qweb.py", line 43, in render
    return super(IrQWeb, self).render(template, values=values, **options)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 274, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_nl_reports_xaf_audit_file_1201
  File "<template>", line 26, in foreach_1152
TypeError: 'bool' object is not subscriptable

Error to render compiling AST
TypeError: 'bool' object is not subscriptable
Template: l10n_nl_reports.xaf_audit_file
Path: /templates/t/*/*[2]/*[6]/*/*[2]
Node: <custSupName xmlns="http://www.auditfiles.nl/XAF/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" t-esc="p.name[:50]"/>

**Comment by pedrobaeza** [comment]
Why are you opening 3 issues for the same thing and more that it's an enterprise thing? Please report it to odoo.com/help instead.

**Comment by Yenthe666** [comment]
@bizzappdevteam guys, Erwin/ Odoo Experts has a partnership license and so does the customer so report it through odoo.com/help as @pedrobaeza mentioned ;)
