### ISSUE TITLE
2 employees in Chrome and IE browsers cannot see POS View - Odoo 13

### ISSUE THREAD

**Issue by ivaqmo123** [odoo/odoo#40071]
Impacted versions: Odoo 13

Steps to reproduce:
1.- Go to POS>Configuration>Point of Sale , then select Bar. Enable "Login with Employees", save.
2.- in chrome browser. Go to Dashboard and resume/start session in Bar, and Click on Cashier and select an employee (e.g. admin), select a table (e.g. T1) and add some orderlines, go back to table mgmt view.
3. in IE Browser, login to odoo with the same user used in step 2. Go to Dashboard and resume session in Bar, then click on Cashier and select ANOTHER employee (e.g. demo). select the same table selected in step 2 (i.e. T1) and error appears

Current behavior: 2 employees using odoo in Chrome and IE  cannot see table orders in POS Restaurant

Expected behavior: 2 employees using odoo in Chrome and IE  should be table to manage orders in POS Restaurant

Error:
Object doesn't support property or method 'finally'
http://54.85.96.229:8069/web/content/369-d49ff37/point_of_sale.assets.js:571
Traceback:
TypeError: Object doesn't support property or method 'finally'
   at set_table (http://54.85.96.229:8069/web/content/369-d49ff37/point_of_sale.assets.js:571:136)
   at click_handler (http://54.85.96.229:8069/web/content/369-d49ff37/point_of_sale.assets.js:537:1178)
   at Anonymous function (http://54.85.96.229:8069/web/content/369-d49ff37/point_of_sale.assets.js:547:295)
   at jQuery.event.dispatch (http://54.85.96.229:8069/web/content/353-fdb1abc/web.assets_common.js:1030:368)
   at elemData.handle (http://54.85.96.229:8069/web/content/353-fdb1abc/web.assets_common.js:1016:76)

**Comment by pedrobaeza** [comment]
IE is not a supported browser in 13.0 AFAIK, and if Chrome is outdated neither.

Closing as it should be that. If not, please comment back.
