### ISSUE TITLE
Why odoo delete some products after -u all?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#40113]
Impacted versions:10
I'm trying to update my DB by -u all
I found that odoo try to delete some products !!
this is the log file:
```

2019-11-12 10:52:47,946 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138970]
2019-11-12 10:52:47,964 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24263]
2019-11-12 10:52:47,965 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24262@product.template (product.product_template_testext_16392)
2019-11-12 10:52:48,282 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138969]
2019-11-12 10:52:48,298 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24262]
2019-11-12 10:52:48,299 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24261@product.template (product.product_template_testext_16391)
2019-11-12 10:52:48,616 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138968]
2019-11-12 10:52:48,630 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24261]
2019-11-12 10:52:48,631 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24260@product.template (product.product_template_testext_16390)
2019-11-12 10:52:48,941 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138967]
2019-11-12 10:52:48,956 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24260]
2019-11-12 10:52:48,956 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24259@product.template (product.product_template_testext_16389)
2019-11-12 10:52:49,276 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138966]
2019-11-12 10:52:49,290 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24259]
2019-11-12 10:52:49,291 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24258@product.template (product.product_template_testext_16388)
2019-11-12 10:52:49,608 17047 INFO DataBase odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [138965]
2019-11-12 10:52:49,622 17047 INFO DataBase odoo.models.unlink: User #1 deleted product.template records with IDs: [24258]
2019-11-12 10:52:49,623 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24257@product.template (product.product_template_testext_16387)
2019-11-12 10:52:49,623 17047 INFO DataBase odoo.addons.base.ir.ir_model: Deleting 24256@product.template (product.product_template_testext_16386)
2019-11-12 10:52:49,818 17047 INFO DataBase odoo.sql_db: bad query: DELETE FROM product_template WHERE id IN (24256)
2019-11-12 10:52:49,829 17047 WARNING DataBase odoo.modules.loading: Transient module states were reset
2019-11-12 10:52:49,829 17047 ERROR DataBase odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo10/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo10/odoo/modules/loading.py", line 409, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/odoo/odoo10/odoo/addons/base/ir/ir_model.py", line 1410, in _process_end
    record.unlink()
  File "/opt/odoo/odoo10/addons/mail/models/mail_thread.py", line 292, in unlink
    res = super(MailThread, self).unlink()
  File "/opt/odoo/odoo10/odoo/models.py", line 3434, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/odoo10/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo10/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "product_id" violates not-null constraint
DETAIL:  Failing row contains (31497, -1.00, 173, null, -1.00, 2018-10-02 06:59:46.88108, testext_001, null, 173, Emplacements physiques/LUS76/Stock 76, 22, 3, Coté Gauche, null, 4566, 2018-10-02 07:08:27.62932, null, 1, null).
CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_inventory_line" SET "product_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "product_id""


```

**Comment by pedrobaeza** [comment]
This is because you have declared in custom modules some XML-ID that belongs to `product` module, which causes this side effect.

Closing this as not issue, but misuse of the ORM framework.

**Comment by m3asmi** [comment]
there is no XML-ID in  custom models !
the xml-id of that product created after exporting it 
for example that product xml-id is : **__export__.product_product_21177**

**Comment by pedrobaeza** [comment]
The products that are being removed have XML-IDs like `product.product_template_testext_XXXXX`

**Comment by m3asmi** [comment]
when I removed those  External Identifiers product.product_template_testext_XXXXX  
it's good now
