### ISSUE TITLE
Odoo v13 : Client Error on Purchase Order 

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#40117]
Impacted versions: V13

Steps to reproduce:

1. Create po and add product
2. Try to edit the price on line with double click
3. Client error appear

Current behavior: Error appear as 
Error:

Traceback:
TypeError: Cannot read property 'length' of undefined
    at Class.isFocusable (http://684417-13-0-4bba87.runbot28.odoo.com/web/content/1939-db90f5f/web.assets_backend.js:825:170)
    at Class.activate (http://684417-13-0-4bba87.runbot28.odoo.com/web/content/1939-db90f5f/web.assets_backend.js:823:1458)
    at Class._activateFieldWidget (http://684417-13-0-4bba87.runbot28.odoo.com/web/content/1939-db90f5f/web.assets_backend.js:1384:942)
    at http://684417-13-0-4bba87.runbot28.odoo.com/web/content/1939-db90f5f/web.assets_backend.js:2014:92
Expected behavior: Price should be update as expected

Video/Screenshot link (optional):
https://drive.google.com/open?id=1w-IZZ9uHDPPfDGbiXt0QlMT6Sv6gQ_1R

**Comment by sle-odoo** [comment]
I can't reproduce this one.
If you still encounter it, feel free to comment and i'll reopen. Thanks!

**Comment by b881659b** [comment]
@sle-odoo: I have a client who encountered the same problem when trying to create a quotation.

The line numbers in the JS files are slightly different. The issue is intermittent (about once every 2 weeks), not easily reproducible and does not appear to be limited to a specific user/PC.
