### ISSUE TITLE
Odoo 13 installation error: "configure: error: cannot run C compiled programs."

### ISSUE THREAD

**Issue by Myced** [odoo/odoo#40152]
Impacted versions:13 latest (Enterprise Edition)

Steps to reproduce: Using CentOs 7, with python3.6 and pip 9.0.3
Install required dependencies like python3-devel
Untar source and in to install required packages with pip3

Current behavior: Install packages but does not successfully run setup.py

Expected behavior: Run pip3 install -r requirements.txt end exit without any errors

Video/Screenshot link (optional):
Here is there error log
`  copying gevent/event.py -> build/lib.linux-x86_64-3.6/gevent
    running build_ext
    Running '(cd  "/tmp/pip-build-7m5atfxp/gevent/libev"  && /bin/sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /tmp/pip-build-7m5atfxp/gevent/build/temp.linux-x86_64-3.6/libev
    configure: error: in `/tmp/pip-build-7m5atfxp/gevent/libev':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 516, in <module>
        run_setup(ext_modules, run_make=run_make)
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 502, in run_setup
        **setup_kwds
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 305, in build_extension
        self.gevent_prepare(ext)
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 302, in gevent_prepare
        configure(self, ext)
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 196, in configure_libev
        rc = _system(libev_configure_command)
      File "/tmp/pip-build-7m5atfxp/gevent/setup.py", line 172, in _system
        return check_call(cmd, shell=True)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '(cd  "/tmp/pip-build-7m5atfxp/gevent/libev"  && /bin/sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m5atfxp/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ezgozn10-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7m5atfxp/gevent/
![odoo exhibit a](https://user-images.githubusercontent.com/22053178/68692232-6a3e4600-0575-11ea-8989-a73667366fa0.png)
![odoo exhibit b](https://user-images.githubusercontent.com/22053178/68692233-6a3e4600-0575-11ea-91e5-c4f5aac6ffb2.png)
`

**Comment by Myced** [comment]
I just checked on my system too and the specified directory **( /tmp/pip-build-7m5atfxp/gevent/libev)** from the cd command does not exist

**Comment by Yenthe666** [comment]
Its not an issue with Odoo itself but with one of the packages Odoo utilizes. This is out of the scope of Odoo itself honestly.
@pedrobaeza you agree?

**Comment by pedrobaeza** [comment]
Yeah, indeed this is something specific of the deployment that is not covered by official instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by Myced** [comment]
I am writing now to help any other person who might encounter this same problem and gets to this issue.

The requirements.txt file contains this portion here
`gevent==1.1.2 ; sys_platform != 'win32' and python_version < '3.7'
gevent==1.3.4 ; sys_platform != 'win32' and python_version >= '3.7'
gevent==1.4.0 ; sys_platform == 'win32' and python_version >= '3.7'
`

So on a  Cent OS 7 server with Python 3.6 and pip 9.0.3, this will delegate to installing **gevent 1.1.2** since the python version is less than 3.7

But installation of gevent 1.1.2 is what was causing the error mentioned above.

Once I upgraded my python version to python 3.7, **gevent 1.4.0** was installed successfully without any errors.

So I guess gevent 1.1.2 cannot be installed on CentOS 7 with Python 3.6. 
So its not an odoo problem but a gevent problem. 

@pedrobaeza @Yenthe666 I would like to know your thoughts

**Comment by Yenthe666** [comment]
@d-fence is our packages guy so worth a read/check for him.

**Comment by pedrobaeza** [comment]
That requirements.txt is thought for Debian/Ubuntu, so this kind on versioning incompatibilities can happen, but I let @d-fence to give his opinion.

**Comment by d-fence** [comment]
I can only confirm that CentOS is not supported because a lot of Python3 packages are MIA, leading to this kind of problem.
Anyway, it seems that you need a compiler and the python libs.
This could help you to compile the needed gevent version:
`yum  install python3-devel gcc`
Hope this help

**Comment by Myced** [comment]
Yes. That helps. I have done `yum install python3-devel gcc`. 
And upgraded from python36 to python37.

`pip3 install -r requirements.txt` ran without any issues. 
Have odoo now running fine..
