### ISSUE TITLE
ERROR ODOO 13 MRP Module

### ISSUE THREAD

**Issue by creichhardt** [odoo/odoo#40231]
Impacted versions: 13

Steps to reproduce: When I press Plan, after reserve the material. Odoo show me an error. 

Current behavior: Continues with the error and I can't plan the production

Expected behavior: 

Video/Screenshot link (optional):

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/enterprise/addons/mrp_workorder/models/mrp_production.py", line 13, in button_plan
    res = super(MrpProduction, self).button_plan()
  File "/odoo/odoo-server/addons/mrp/models/mrp_production.py", line 694, in button_plan
    order._plan_workorders()
  File "/odoo/odoo-server/addons/mrp/models/mrp_production.py", line 727, in _plan_workorders
    if to_date < best_finished_date:
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by 159820** [comment]
@pedrobaeza 
/addons/mrp/modules/mrp_production.py
=================================
line 724:
to_date = workcenter.resource_calendar_id.plan_hours(duration_expected / 60.0, from_date, compute_leaves=True, resource=workcenter.resource_id, domain=[('time_type', 'in', ['leave', 'other'])])

                # Check if this workcenter is better than the previous ones
                if to_date < best_finished_date:

to_date is False here, so   if to_date < best_finished_date:   will raise exception.

please check.

**Comment by pedrobaeza** [comment]
But that are not the steps to reproduce the problem, only an assumption on code. Please give how you reproduce it in the system doing the steps.

**Comment by creichhardt** [comment]
Ya lo arregle. Era un problema de configuración de fechas. Ya no tengo ese problema.

**Comment by tanzilkhan** [comment]
If I create MO from SO then this error occurs.

Runbot: http://729626-13-0-8108ef.runbot11.odoo.com/

Error:   

_File "/data/build/enterprise/mrp_workorder/models/mrp_production.py", line 13, in button_plan
    res = super(MrpProduction, self).button_plan()
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 694, in button_plan
    order._plan_workorders()
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 729, in _plan_workorders
    if to_date < best_finished_date:
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'_
