### ISSUE TITLE
Замість "in" - "у" 

### ISSUE THREAD

**Issue by joyshmitz** [odoo/odoo#40387]
@
https://github.com/odoo/odoo/blob/c1d25b9be61a97d4280797445f069af79db5634e/addons/purchase/i18n/uk.po#L31

Помилка:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 2031, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "/opt/odoo13/odoo/odoo/tools/safe_eval.py", line 347, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/odoo13/odoo/odoo/tools/safe_eval.py", line 206, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    (object.state у ('чернетці', 'відправлено') та 'Запит на комерційну пропозицію - %s' % (object.name) або                 'Замовлення на купівлю - %s' % (object.name))
                  ^
SyntaxError: invalid syntax

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment]
Besides this actually looks like an issue in the translations term then.

**Comment by mart-e** [comment]
Indeed, so please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo/public), not Github.

Please submit your changes there and let me know if you have issues.

Thanks

**Comment by mart-e** [comment]
To be precise, it is probably this translation that needs to be fixed
https://www.transifex.com/odoo/odoo-13/translate/#uk/purchase/180739865?q=translation_text%3A'%D0%BD%D0%B0+%D0%BA%D0%BE%D0%BC%D0%B5%D1%80%D1%86%D1%96%D0%B9%D0%BD%D1%83+%D0%BF%D1%80%D0%BE%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D1%96%D1%8E'
