### ISSUE TITLE
Odoo13 Internal server error when process to pay an online order

### ISSUE THREAD

**Issue by ocanal2015** [odoo/odoo#40636]
Hello,
I use a community Odoo13 and I have an Internal server Error when I want to pay an order via Paypal !
Can you help me?
Below my logs:

 2019-11-21 13:56:14,116 1 INFO Ping werkzeug: 173.0.82.126 - - [21/Nov/2019 13:56:14] "POST /payment/paypal/ipn/ HTTP/1.1" 500 - 6 0.007 0.016
 2019-11-21 13:56:14,124 1 ERROR Ping werkzeug: Error on request:
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
     execute(self.server.app)
   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
 The files belonging to this database system will be owned by user "postgres".
     application_iter = app(environ, start_response)
 This user must also own the server process.
   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 414, in app

     return self.app(e, s)
 The database cluster will be initialized with locale "en_US.utf8".
   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 142, in application
 The default database encoding has accordingly been set to "UTF8".
     return application_unproxied(environ, start_response)
 The default text search configuration will be set to "english".
   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied

     result = odoo.http.root(environ, start_response)
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1281, in __call__
     return self.dispatch(environ, start_response)
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1251, in __call__
     return self.app(environ, start_wrapped)
 Data page checksums are disabled.
   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__

     return self.app(environ, start_response)
 fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in dispatch
 creating subdirectories ... ok
     result = ir_http._dispatch()
 selecting dynamic shared memory implementation ... posix
   File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
 selecting default max_connections ... 100
     return super(IrHttp, cls)._dispatch()
 selecting default shared_buffers ... 128MB
   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 168, in _dispatch
 selecting default time zone ... Etc/UTC
     response = super(Http, cls)._dispatch()
 creating configuration files ... ok
   File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
 running bootstrap script ... ok
     return super(Http, cls)._dispatch()
 performing post-bootstrap initialization ... ok
   File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
 syncing data to disk ... ok
     return super(IrHttp, cls)._dispatch()
   File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
     response = super(IrHttp, cls)._dispatch()
   File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 505, in _dispatch
     result = super(IrHttp, cls)._dispatch()

   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 233, in _dispatch

     return cls._handle_exception(e)
 Success. You can now start the database server using:
   File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception

     response = super(IrHttp, cls)._handle_exception(exc)
     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
   File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 596, in _handle_exception

     return super(IrHttp, cls)._handle_exception(exception)
 initdb: warning: enabling "trust" authentication for local connections
   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
 You can change this by editing pg_hba.conf or using the option -A, or
     return request._handle_exception(exception)
 --auth-local and --auth-host, the next time you run initdb.
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 744, in _handle_exception
 waiting for server to start....2019-11-21 10:43:45.972 UTC [43] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
     return super(HttpRequest, self)._handle_exception(exception)
 2019-11-21 10:43:46.354 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
 2019-11-21 10:43:46.552 UTC [44] LOG:  database system was shut down at 2019-11-21 10:43:43 UTC
     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
     raise value
   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
     result = request.dispatch()
 2019-11-21 10:43:46.625 UTC [43] LOG:  database system is ready to accept connections
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 803, in dispatch
  done
     r = self._call_function(**self.params)
 server started
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
     return checked_call(self.db, *args, **kwargs)
   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
     return f(dbname, *args, **kwargs)
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call

     result = self.endpoint(*a, **kw)
 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__

     return self.method(*args, **kw)
 2019-11-21 10:43:46.682 UTC [43] LOG:  received fast shutdown request
   File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
 waiting for server to shut down....2019-11-21 10:43:46.734 UTC [43] LOG:  aborting any active transactions
     response = f(*args, **kw)
 2019-11-21 10:43:46.735 UTC [43] LOG:  background worker "logical replication launcher" (PID 50) exited with exit code 1
   File "/usr/lib/python3/dist-packages/odoo/addons/payment_paypal/controllers/main.py", line 96, in paypal_ipn
 2019-11-21 10:43:46.736 UTC [45] LOG:  shutting down
     self.paypal_validate_data(**post)
 .2019-11-21 10:43:47.800 UTC [43] LOG:  database system is shut down
   File "/mnt/extra-addons/fix_paypal_v13/controllers/main.py", line 37, in paypal_validate_data
  done
     paypal_url = tx.acquirer_id.paypal_get_form_action_url()
 server stopped
   File "/usr/lib/python3/dist-packages/odoo/addons/payment_paypal/models/payment.py", line 113, in paypal_get_form_action_url

     self.ensure_one()
 PostgreSQL init process complete; ready for start up.
   File "/usr/lib/python3/dist-packages/odoo/models.py", line 4892, in ensure_one

     raise ValueError("Expected singleton: %s" % self)
 2019-11-21 10:43:47.930 UTC [1] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 ValueError: Expected singleton: payment.acquirer() - - -

**Comment by pedrobaeza** [comment]
This is a configuration problem: the payment acquirer is not available somehow on your system. Please verify how it's configured.

Closing this meanwhile as it's not an Odoo issue per se.
