### ISSUE TITLE
[13.0]Reference Unit Error: External ID not found in the system: uom.product_uom_kgm

### ISSUE THREAD

**Issue by arsow** [odoo/odoo#40745]
**Impacted versions:**
     13.0
**Steps to reproduce:**
     Delete the wight reference unit "kg" by mistake. Or change the wight reference unit from "kg" to "g". The following error occurs when create a new product.
**Current behavior:**
     Error occurs when create a new product. It won't resolve the problem even create the same reference unit again:

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0xb28f4a94>, 'uom.product_uom_kgm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1196, in default_get
    defaults[name] = field.default(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 36, in _get_default_weight_uom
    return self._get_weight_uom_name_from_ir_config_parameter()
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 286, in _get_weight_uom_name_from_ir_config_parameter
    return self._get_weight_uom_id_from_ir_config_parameter().display_name
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 282, in _get_weight_uom_id_from_ir_config_parameter
    return self.env.ref('uom.product_uom_kgm')
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 509, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1664, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1648, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1637, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: uom.product_uom_kgm

**Expected behavior:**
  how to resolve this error?
**Video/Screenshot link (optional):**

**Comment by sswapnesh** [comment]
Upgrade the `uom` module and try again

**Comment by sswapnesh** [comment]
Cc @mart-e  (Based on https://github.com/odoo/odoo/issues/31087#issuecomment-468578681)

**Comment by Yenthe666** [comment]
Yeah this is one of those cases that is default behaviour in Odoo and only resolvable by reloading the module(s)..

**Comment by pedrobaeza** [comment]
Yes, but I don't consider it an Odoo issue: some data mustn't be deleted, and if so, the simply update mechanism will restore it. To include code for avoiding that deletion is to bloat the number of lines without too much benefit.

Closing this by the stated reasons.

**Comment by matteoopenf** [comment]
I have the same problem on odoo 12.0, I update the uom module, but the unit of meausre is not recreated.
have you other solution?

**Comment by mm82299** [comment]
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data noupdate="0">
        <record id="product_uom_kgm" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="name">kg</field>
            <field name="factor" eval="1"/>
            <field name="uom_type">reference</field>
        </record>
    </data>
</odoo>

Add this file in module UOM, add reference in __manifest__.py file and update your module.

**Comment by ZahdiM** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data noupdate="0">
        <record id="product_uom_kgm" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="name">kg</field>
            <field name="factor" eval="1"/>
            <field name="uom_type">reference</field>
        </record>
    </data>
</odoo>
```

Add a new xml file, with the code above, inside data folder of your module UOM, add reference in __manifest__.py file and update your module.
