### ISSUE TITLE
UnicodeEncodeError while open POS or SO while the active language is non-latin

### ISSUE THREAD

**Issue by ahmadio** [odoo/odoo#40833]
Impacted versions:
10.0
Steps to reproduce:
1. log in as a non-admin user
2. change the user language to a non-latin language (Arabic in my case)
3. try to open new POS session, or save SO
4. the error message will show up

Current behavior:
This error message modal shows up
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Software/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/Software/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/Software/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/Software/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/Software/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/Software/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Software/models.py", line 3042, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python2.7/site-packages/Software/models.py", line 5269, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 931, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 1045, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 997, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 988, in _compute_value
    getattr(records, self.compute)()
  File "<string>", line 2, in _compute_currency
  File "/usr/lib/python2.7/site-packages/Software/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python2.7/site-packages/Software/addons/account/models/account_bank_statement.py", line 89, in _compute_currency
    self.currency_id = self.journal_id.currency_id or self.company_id.currency_id
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 931, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/Software/fields.py", line 1035, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/Software/models.py", line 3087, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/Software/models.py", line 3027, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/Software/models.py", line 3205, in _read_from_database
    + ' - ({} {}, {} {})'.format(_('Records:'), self.ids[:6], _('User:'), self._uid)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
```
and this shows up in browser console:

```
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 684, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 334, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 327, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 942, in __call__\n    return self.method(*args, **kw)\n  File \"/usr/lib/python2.7/site-packages/odoo/http.py\", line 507, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py\", line 895, in call_kw\n    return self._call_kw(model, method, args, kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py\", line 887, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/odoo/models.py\", line 3042, in read\n    data[record][name] = convert(record[name], record, use_name_get)\n  File \"/usr/lib/python2.7/site-packages/odoo/models.py\", line 5269, in __getitem__\n    return self._fields[key].__get__(self, type(self))\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 931, in __get__\n    self.determine_value(record)\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 1045, in determine_value\n    self.compute_value(recs)\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 997, in compute_value\n    self._compute_value(records)\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 988, in _compute_value\n    getattr(records, self.compute)()\n  File \"<string>\", line 2, in _compute_currency\n  File \"/usr/lib/python2.7/site-packages/odoo/api.py\", line 369, in loop\n    result = [method(rec, *args, **kwargs) for rec in self]\n  File \"/usr/lib/python2.7/site-packages/odoo/addons/account/models/account_bank_statement.py\", line 89, in _compute_currency\n    self.currency_id = self.journal_id.currency_id or self.company_id.currency_id\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 931, in __get__\n    self.determine_value(record)\n  File \"/usr/lib/python2.7/site-packages/odoo/fields.py\", line 1035, in determine_value\n    record._prefetch_field(self)\n  File \"/usr/lib/python2.7/site-packages/odoo/models.py\", line 3087, in _prefetch_field\n    result = records.read([f.name for f in fs], load='_classic_write')\n  File \"/usr/lib/python2.7/site-packages/odoo/models.py\", line 3027, in read\n    self._read_from_database(stored, inherited)\n  File \"/usr/lib/python2.7/site-packages/odoo/models.py\", line 3205, in _read_from_database\n    + ' - ({} {}, {} {})'.format(_('Records:'), self.ids[:6], _('User:'), self._uid)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)\n","exception_type":"internal_error","message":"ascii\nالمستخدم:\n0\n8\nordinal not in range(128)","name":"exceptions.UnicodeEncodeError","arguments":["ascii","المستخدم:",0,8,"ordinal not in range(128)"]}}
```

Expected behavior:
No errors show show up

This line of code is the source of this error
https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L3205

**Comment by pedrobaeza** [comment]
10.0 is not a supported version anymore, as only last 3 versions are. Please check if the problem still happens in these versions, and if so, you can post a new issue with it. You should check also in runbot, not in your custom installation.

Closing due to this.
