### ISSUE TITLE
[13.0] [auth_ldap] LDAP login fails if it creates a new user

### ISSUE THREAD

**Issue by janverb** [odoo/odoo#41060]
**Impacted versions:** 13.0

### Steps to reproduce:
- Set up LDAP authentication with *Create User* enabled
- Log in with an LDAP identity that doesn't have an account yet

### Current behavior:
One of three things happens:
1. Usually Odoo shows a 403 page. Refreshing gives the same page. After a few minutes it's possible to log in again and everything works as usual. It's also possible to log in from a different session/browser/private window.
2. Sometimes Odoo shows the login page again without an error message. It's then possible to log in as usual.
3. Rarely, the login succeeds, but the newly created user is still marked as "never connected".

### Expected behavior:
- Logging in creates the new user and works on the first try.

### Technical details:
When a session token is generated the new user isn't found, probably because it was created in a separate, younger transaction. [This SQL query in `_compute_session_token`](https://github.com/odoo/odoo/blob/4205cb2/odoo/addons/base/models/res_users.py#L681) fails, so `False` is returned, which breaks things.

Putting `self.env.cr.commit()` right before the query makes it succeed because that makes the new user visible, but that doesn't seem like the right solution.

**Comment by hbrunn** [comment]
can you trace this on a request level? Just to verify that this is caused by transactions within one request to ``/web/login``, or if - and the indeterminism might point into this direction - this is a timing issue and while we create the user something else happens. So when you debugged the call to `_compute_session_token`, did you inspect the `odoo.http.request` object?

The [`pg_locks`](https://www.postgresql.org/docs/current/view-pg-locks.html) table is helpful for this situations. You can also inspect [`odoo.api.env.all`](https://github.com/odoo/odoo/blob/13.0/odoo/api.py#L457), and look at the database from the other envs' point of view.

**Comment by janverb** [comment]
`odoo.http.request` is the same object at the time the user is created and at the time the session token is generated.

It already has a cursor allocated to it before the user is created. There are a couple of environments in `env.all` while the user is being created, but they have only three distinct cursors (when I looked). One of them is used for creating the user, one of them is bound to `odoo.http.request`, and the other I don't know and could have nothing to do with the request for all I know.

The cursor that's ultimately used to create the user is created in [the `auth_ldap` implementation of `res.users._login`](https://github.com/odoo/odoo/blob/4205cb2/addons/auth_ldap/models/res_users.py#L17).

Another bad fix for the problem is to create the user using the same cursor as the request, i.e. `SudoUser = odoo.http.request.env['res.users'].sudo().with_context(no_reset_password=True)`.

**Comment by auroraeosrose** [comment]
Seeing this as well - the 403 is the worst part - it's generated because the false session object throws a TypeError exception which is never caught or handled properly but allowed to bubble up .  So really, the security.py code should be fixed to check/handle not having a correct session object - AS WELL as fix the ldap module itself 

![Untitled](https://user-images.githubusercontent.com/282573/73948058-7745a980-48c6-11ea-85a4-8a8b6f548a3f.png)

**Comment by Yenthe666** [comment]
@odony I think this LDAP issue might interest you.

**Comment by MeeleCode** [comment]
Experiencing the same problem, has this been fixed?

**Comment by agavariat** [comment]
I have the next error when firsttime login with LDAP in odoo 13

500: Internal Server Error
Traza

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in _getitem_
    a = self.d[obj].me
KeyError: ('res.users', <function Users.context_get at 0x7f18e71af940>, 24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in _call_
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/controllers/main.py", line 97, in web_login
    response = super(Website, self).web_login(redirect=redirect, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 895, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1017, in authenticate
    if uid: self.get_context()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1058, in get_context
    self.context = dict(request.env['res.users'].context_get() or {})
  File "<decorator-gen-84>", line 2, in context_get
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 581, in context_get
    values = user.read(list(name_to_key), load=False)[0]
IndexError: list index out of range

thanks to help

**Comment by wagnerpereirasp** [comment]
[13.0] I've got the same problem, had to add self.env.cr.commit() to _compute_session_token to make it workable.

**Comment by azmeuk** [comment]
@wagnerpereirasp Would you please consider submitting a patch?

**Comment by wagnerpereirasp** [comment]
I can submit a patch, however besides the self.env.cr.commit() on that specific spot, I can't think of a better solution. The good thing is that I have it in production and I can attest it's working properly. Should I submit this solution? I know is not preferrable...

**Comment by Fnux** [comment]
I've got the same problem with `14.0+e.20201013`. Adding `self.env.cr.commit()` to _compute_session_token did not work around the issue. Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 805, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/controllers/main.py", line 112, in web_login
    return super().web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1010, in authenticate
    if not user._mfa_url():
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_totp/models/res_users.py", line 37, in _mfa_url
    if self.totp_enabled:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 975, in __get__
    self.compute_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1112, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4020, in _compute_field_value
    getattr(self, field.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_totp/models/res_users.py", line 43, in _compute_totp_enabled
    r.totp_enabled = bool(v.totp_secret)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 954, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: res.users(22,), User: 22)
```

**Comment by wagnerpereirasp** [comment]
Hi Timothée, on 13.0 even the issue has been workarounded, when users do
double-clicking on the Login button the issue is still happening, single
click works properly.

Can you check if the situation is similar in you case please?

Wagner

Em ter, 1 de dez de 2020 03:28, Timothée Floure <notifications@github.com>
escreveu:

**Comment by lightapp24** [comment]
I have some problems with 14 at commit e9b5a0522f019adb7ae17164e314206a61c71cc6

**Comment by lightapp24** [comment]
I figured out the bugg.

Problem is in isolation level transaction. We have two cursor and both have ISOLATION_LEVEL_REPEATABLE_READ. First currsor get 'database.secret' from data base and dont do commit. Then second currsor create new user by ldap data with commit.
Second currsor don't see created user.

Solutions: should use ISOLATION_LEVEL_READ_COMMITTED for first cursror.

First currsor is in WebRequest._cr
Second currsor we create in odoo.registry(db)['res.users'] in OpenERPSession.authenticate

On monday I will preparate code and share this.

**Comment by lightapp24** [comment]
https://github.com/lightapp24/odoo/commit/20152bdd653b6491d1e7850a2b4c00236f6f95d3

Whether to create a pull request?

**Comment by lightapp24** [comment]
V2:
https://github.com/lightapp24/odoo/tree/fix_auth_ldap_v2

**Comment by joao-p-marques** [comment]
@odony are you working on a fix for this?

**Comment by Yenthe666** [comment]
There's not a single official PR from Odoo so the answer is no. Neither did anyone from Odoo look at this ticket yet.

**Comment by pedrobaeza** [comment]
As one of the community PRs was closed by @odony (https://github.com/odoo/odoo/pull/66177#issuecomment-779288700), maybe they were thinking about a solution under the hook.

**Comment by odony** [comment]
See the discussion on #66138

**Comment by pedrobaeza** [comment]
Thanks for the pointer, Olivier. So do you see a feasible solution or any roadmap?

**Comment by lightapp24** [comment]
Signature of public methods did not change in the https://github.com/odoo/odoo/pull/66240 PR.
changed only _login method, but this is private method...
> No change in the signature of public methods on model (**methods not starting with an underscore**)

**Comment by odony** [comment]
> Signature of public methods did not change in the #66240 PR.
> changed only _login method, but this is private method...

You're right, let me elaborate a bit. The rule for the signature of public methods is a strict *no*, but there is also a softer rule for private methods: they should also remain stable, unless there is a very good reason to change, one that outweighs all of the risks.

Changing a *public* method signature means that any remote application that was using that API is likely to break. Odoo is deployed in production everywhere in the world, and users often integrate their system with other business critical apps that depend on the API stability and trust us to keep it stable.

But Odoo is also designed to be extensible and modular, and the community produces tons of modules for each version. Those modules are allowed to override any model method, public or private, and then call `super()` to hook their own logic into the system. Each model method acts as an extension point for modules.

Changing a method signature, even a private one, could therefore break the chain of overrides, as the overridden method will not be prepared to handle the change and may misbehave, or plainly crash if the number of arguments changes. This can lead to production downtime too, depending on what community modules are installed on a given system.
For this reason we tend to avoid *any signature change at all* in stable series, and reserve those changes for `master`.

PS: I've updated the CONTRIBUTING page to clarify this :)

**Comment by odony** [comment]
> Thanks for the pointer, Olivier. So do you see a feasible solution or any roadmap?

We need more eyes on the [proposed patch](https://github.com/odoo/odoo/pull/66138#issuecomment-779281278) I think, and then more testing ;-)

**Comment by joao-p-marques** [comment]
> We need more eyes on the proposed patch I think, and then more testing ;-)

I've been testing this patch locally and so far it works as expected. Bug fixed and no side effects that I could see so far.

**Comment by SplashS** [comment]
> We need more eyes on the [proposed patch](https://github.com/odoo/odoo/pull/66138#issuecomment-779281278) I think, and then more testing ;-)

Also works for me. I've patched small production environment and it works.

**Comment by drkpkg** [comment]
I apply the proposed solution applying a monkey patch, problem solved. Also there are many lacks inside the Ldap module.

**Comment by progsmile** [comment]
It also fails on Odoo v16. Moreover patch by @lightapp24 does not work anymore.

> "Since 16.0, 'serialized' parameter is not used anymore."

**Comment by progsmile** [comment]
https://github.com/odoo/odoo/issues/41060#issuecomment-780820920 Fixes issue on Odoo v16

**Comment by eLBati** [comment]
Proposing fix for v16 with https://github.com/odoo/odoo/pull/162456
