### ISSUE TITLE
Read_group on product.product with product_tmpl_id raises an Unable to use a closed cursor exception

### ISSUE THREAD

**Issue by hugosantosred** [odoo/odoo#41202]
Impacted versions: 12.0, 13.0

Steps to reproduce:
If I try to do a read_group over product.product, using the product_tmpl_id field an exception is raised.
(I am connected to Runbot using Erppeek library with the jsonrpc path for test this behaviour)

For example:

```python
model('product.product').read_group([], ['name', 'product_tmpl_id'], ['product_tmpl_id'])
```
Throws the following exception:

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/loglevels.py", line 92, in ustr
    return text_type(value)
  File "/data/build/odoo/odoo/tools/func.py", line 150, in __str__
    def __str__(self): return str(self._value)
  File "/data/build/odoo/odoo/tools/func.py", line 137, in _value
    value = self._func(*self._args, **self._kwargs)
  File "/data/build/odoo/odoo/tools/func.py", line 167, in __getitem__
    def __getitem__(self, key): return self._value[key]
  File "/data/build/odoo/odoo/tools/func.py", line 137, in _value
    value = self._func(*self._args, **self._kwargs)
  File "/data/build/odoo/odoo/models.py", line 6226, in <lambda>
    names = tools.lazy(lambda: dict(self.name_get()))
  File "/data/build/odoo/addons/product/models/product_template.py", line 416, in name_get
    self.browse(self.ids).read(['name', 'default_code'])
  File "/data/build/odoo/odoo/models.py", line 2888, in read
    self._read(stored_fields)
  File "/data/build/odoo/odoo/models.py", line 3001, in _read
    cr.execute(query_str, params)
  File "/data/build/odoo/odoo/sql_db.py", line 162, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.
```

Expected behavior:
Return the results of read_group without any errors.

I've also test that if I change the code for the data_dict line in the _read_group_resolve_many2one_fields of the models.py file (https://github.com/odoo/odoo/blob/12.0/odoo/models.py#L2216) and using the name_get method directly, like in v11 (https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L2026) the read_group for the product.product with the product_tmpl_id field works as expected. So it seems that this error is related with that call to lazy_name_get.

**Comment by pedrobaeza** [comment]
Is this still happening with latest code?

**Comment by hugosantosred** [comment]
Yes, its still happening, I just tried with v12 runbot.

**Comment by pedrobaeza** [comment]
OK, not sure who to ping. @Feyensv is that something of your team?

**Comment by Feyensv** [comment]
Seems a bit related to the python framework, but I'll have a look to see if I'm able to reproduce it locally.

**Comment by C3POdoo** [comment]
Dear @hugosantosred,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
