### ISSUE TITLE
Could we have the @api not eat the stacktrace?

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#4126]
So I added email template validation to our project a while back:

``` python
class ValidateEmailTemplate(models.Model):
    _inherit = 'email.template'

    @api.constrains('body_html', 'subject')
    def validate_templates(self):
        fields = ["body_html", "subject"]
        try:
            res_id = self.res_id
        except AttributeError:
            # Validate against the last record for the model.
            res_id = self.env[self.model].search([], order='id desc')[0].id

        for field in fields:
            template = getattr(self, field)
            if not self.render_template(template, self.model, res_id):
                raise ValidationError("Field '%s' contains errors." % field)
```

Then now I needed to install the calendar module which didn't have a model set. This is the stacktrace I got:

``` bash
Traceback (most recent call last):
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/home/deploy/odoo/build/8.0/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/home/deploy/odoo/build/8.0/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/deploy/odoo/build/8.0/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/deploy/odoo/build/8.0/openerp/modules/registry.py", line 340, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/deploy/odoo/build/8.0/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/home/deploy/odoo/build/8.0/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/deploy/odoo/build/8.0/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/deploy/odoo/build/8.0/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/deploy/odoo/build/8.0/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/deploy/odoo/build/8.0/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/deploy/odoo/build/8.0/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/deploy/odoo/build/8.0/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/addons/base/ir/ir_model.py", line 1063, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/models.py", line 3969, in create
    record = self.browse(self._create(old_vals))
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/models.py", line 4160, in _create
    recs._validate_fields(vals)
  File "/home/deploy/odoo/build/8.0/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/deploy/odoo/build/8.0/openerp/models.py", line 1311, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ParseError: "ValidateError
Error while validating constraint

False" while parsing /home/deploy/odoo/build/8.0/addons/calendar/calendar_data.xml:95, near
<record id="calendar_template_meeting_invitation" model="email.template">
            <field name="name">Meeting Invitation</field>
            <field name="email_from">${object.event_id.user_id.email or ''}</field>
            <field name="subject">${object.event_id.name}</field>
            <field name="model_id" ref="calendar.model_calendar_attendee"/>

            <field name="email_to">${('' if object.partner_id and object.partner_id.email and object.partner_id.email==object.email else object.email|safe)}</field>
            <field name="partner_to">${object.partner_id and object.partner_id.email and object.partner_id.email==object.email and object.partner_id.id or False }</field>
            <field name="auto_delete" eval="True"/>

            <field name="body_html">
                &lt;html&gt;
                    &lt;head&gt;
                        &lt;meta http-equiv="Content-type" content="text/html; charset=utf-8" /&gt;
                        &lt;title&gt;${object.event_id.name}&lt;/title&gt;
                        &lt;style&gt;
                            span.oe_mail_footer_access {
                                display:block;
                                text-align:center;
                                color:grey;
                            }
                        &lt;/style&gt;
                    &lt;/head&gt;
                    &lt;body&gt;
                        &lt;div style="border-radius: 2px; max-width: 1200px; height: auto;margin-left: auto;margin-right: auto;background-color:#f9f9f9;"&gt;
                            &lt;div style="height:auto;text-align: center;font-size : 30px;color: #8A89BA;"&gt;
                                &lt;strong&gt;${object.event_id.name}&lt;/strong&gt;
                            &lt;/div&gt;
                            &lt;div style="height: 50px;text-align: left;font-size : 14px;border-collapse: separate;margin-top:10px"&gt;
                                &lt;strong style="margin-left:12px"&gt;Dear ${object.cn}&lt;/strong&gt; ,&lt;br/&gt;&lt;p style="margin-left:12px"&gt;${object.event_id.user_id.partner_id.name} invited you for the ${object.event_id.name} meeting of ${object.event_id.user_id.company_id.name}.&lt;/p&gt;
                            &lt;/div&gt;
                            &lt;div style="height: auto;margin-left:12px;margin-top:30px;"&gt;
                                &lt;table&gt;
                                    &lt;tr&gt;
                                        &lt;td&gt;
                                            &lt;div style="border-top-left-radius:3px;border-top-right-radius:3px;font-size:12px;border-collapse:separate;text-align:center;font-weight:bold;color:#ffffff;width:130px;min-height: 18px;border-color:#ffffff;background:#8a89ba;padding-top: 4px;"&gt;${object.event_id.get_interval(object.event_id.start, 'dayname')}&lt;/div&gt;
                                            &lt;div style="font-size:48px;min-height:auto;font-weight:bold;text-align:center;color: #5F5F5F;background-color: #E1E2F8;width: 130px;"&gt;
                                                ${object.event_id.get_interval(object.event_id.start,'day')}
                                            &lt;/div&gt;
                                            &lt;div style='font-size:12px;text-align:center;font-weight:bold;color:#ffffff;background-color:#8a89ba'&gt;${object.event_id.get_interval(object.event_id.start, 'month')}&lt;/div&gt;
                                            &lt;div style="border-collapse:separate;color:#8a89ba;text-align:center;width: 128px;font-size:12px;border-bottom-right-radius:3px;font-weight:bold;border:1px solid;border-bottom-left-radius:3px;"&gt;${not object.event_id.allday and object.event_id.get_interval(object.event_id.start, 'time', tz=object.partner_id.tz) or ''}&lt;/div&gt;
                                        &lt;/td&gt;
                                        &lt;td&gt;
                                            &lt;table cellspacing="0" cellpadding="0" border="0" style="margin-top: 15px; margin-left: 10px;font-size: 16px;"&gt;
                                                    &lt;tr&gt;
                                                        &lt;td style="vertical-align:top;"&gt;
                                                            % if object.event_id.location:
                                                                &lt;div style="width: 120px; background : #CCCCCC; font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                                    Where
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                        &lt;td  style="vertical-align:top;"&gt;
                                                            % if object.event_id.location:
                                                                &lt;div style = "font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;   font-size: 14px" &gt;
                                                                    : ${object.event_id.location}
                                                                    &lt;span style= "color:#A9A9A9; "&gt;(&lt;a href="http://maps.google.com/maps?oi=map&amp;q=${object.event_id.location}"&gt;View Map&lt;/a&gt;)
                                                                        &lt;/span&gt;
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                    &lt;/tr&gt;

                                                    &lt;tr&gt;
                                                        &lt;td style="vertical-align:top;"&gt;
                                                            % if object.event_id.description :
                                                                &lt;div style="width: 120px; background : #CCCCCC; font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                                    What
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                        &lt;td style="vertical-align:text-top;"&gt;
                                                            % if object.event_id.description :
                                                                &lt;div style="font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                                    : ${object.event_id.description}
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                    &lt;/tr&gt;

                                                    &lt;tr&gt;
                                                        &lt;td style="vertical-align:top;"&gt;
                                                            % if not object.event_id.allday and object.event_id.duration:
                                                                &lt;div style="height:auto; width: 120px; background : #CCCCCC; font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                                    Duration
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                        &lt;td colspan="3" style="vertical-align:text-top;"&gt;
                                                            % if not object.event_id.allday and object.event_id.duration:
                                                                &lt;div style="font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                                    : ${('%dH%02d' % (object.event_id.duration,(object.event_id.duration*60)%60))}
                                                                &lt;/div&gt;
                                                            % endif
                                                        &lt;/td&gt;
                                                    &lt;/tr&gt;
                                                &lt;tr style=" height: 30px;"&gt;
                                                    &lt;td style="height: 25px;width: 120px; background : # CCCCCC; font-family: Lucica Grande', Ubuntu, Arial, Verdana, sans-serif;"&gt;
                                                        &lt;div&gt;
                                                            Attendees
                                                        &lt;/div&gt;
                                                    &lt;/td&gt;
                                                    &lt;td colspan="3"&gt;
                                                       :
                                                        % for attendee in object.event_id.attendee_ids:
                                                            &lt;div style="display:inline-block; border-radius: 50%; width:10px; height:10px;background:${'color' in ctx and ctx['color'][attendee.state] or 'white'};"&gt;&lt;/div&gt;
                                                            % if attendee.cn != object.cn:
                                                                &lt;span style="margin-left:5px"&gt;${attendee.cn}&lt;/span&gt;
                                                            % else:
                                                                &lt;span style="margin-left:5px"&gt;You&lt;/span&gt;
                                                            % endif
                                                        % endfor
                                                    &lt;/td&gt;
                                                &lt;/tr&gt;
                                            &lt;/table&gt;
                                        &lt;/td&gt;
                                    &lt;/tr&gt;
                                &lt;/table&gt;
                            &lt;/div&gt;
                            &lt;div style="height: auto;width:450px; margin:0 auto;padding-top:20px;padding-bottom:40px;"&gt;
                                    &lt;a style="padding: 8px 30px 8px 30px;border-radius: 6px;border: 1px solid #CCCCCC;background:#8A89BA;margin : 0 15px 0 0;text-decoration: none;color:#FFFFFF;" href="/calendar/meeting/accept?db=${'dbname' in ctx and ctx['dbname'] or ''}&amp;token=${object.access_token}&amp;action=${'action_id' in ctx and ctx['action_id'] or ''}&amp;id=${object.event_id.id}"&gt;Accept&lt;/a&gt;
                                    &lt;a style="padding: 8px 30px 8px 30px;border-radius: 6px;border: 1px solid #CCCCCC;background:#808080;margin : 0 15px 0 0;text-decoration: none;color:#FFFFFF;" href="/calendar/meeting/decline?db=${'dbname' in ctx and ctx['dbname'] or '' }&amp;token=${object.access_token}&amp;action=${'action_id' in ctx and ctx['action_id'] or ''}&amp;id=${object.event_id.id}"&gt;Decline&lt;/a&gt;
                                    &lt;a style="padding: 8px 30px 8px 30px;border-radius: 6px;border: 1px solid #CCCCCC;background:#D8D8D8;text-decoration: none;color:#FFFFFF;" href="/calendar/meeting/view?db=${'dbname' in ctx and ctx['dbname'] or ''}&amp;token=${object.access_token}&amp;action=${'action_id' in ctx and ctx['action_id'] or ''}&amp;id=${object.event_id.id}"&gt;View&lt;/a&gt;
                            &lt;/div&gt;
                        &lt;/div&gt;
                    &lt;/body&gt;
                &lt;/html&gt;

                </field>
        </record>
```

It's impossible to tell where the offending code is from without using a debugger or starting log output from inside of core Odoo because `@api` seem to trash the stack. The offending call was this btw:

``` python
res_id = self.env[self.model].search([], order='id desc')[0].id
```

**Comment by dreispt** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @kitsunde ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
