### ISSUE TITLE
[12.0] Error when uploading supplier invoice 

### ISSUE THREAD

**Issue by 3DOeste** [odoo/odoo#41297]
When trying to upload a supplier invoice a server error occurs because of a missing field which is not present in the wizard.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice_import_wizard.py", line 35, in create_invoices
    invoices += self._create_invoice_from_file(attachment)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice_import_wizard.py", line 20, in _create_invoice_from_file
    invoice = invoice_form.save()
  File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1401, in save
    values = self._values_to_save()
  File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1427, in _values_to_save
    assert v is not False, "{} is a required field".format(f)
AssertionError: document_number is a required field

**Comment by pedrobaeza** [comment]
Which invoice are you trying to upload? The error indicates that what you are uploading doesn't have that information.

**Comment by 3DOeste** [comment]
A suplier invoice, in PDF format. But the wizard doesn't specify any kind of format or file requirement,
I'm also new to odoo and I'm learning the system, but shouldn't it return a warning and not a sever error?

**Comment by pedrobaeza** [comment]
Then that's the problem. It should have a valid Factur-X XML embedded on the PDF for being importable, or have it other kind of complement (like enterprise ones) that are able to be interpreted. Of course a more friendly error would be desirable, but the question is that you are doing something incorrect, so the result is the same: you are not able to import it.

Closing due to no issue as explained above.
