### ISSUE TITLE
[Wishlist] make hr_skills and hr_resume widget global widgets

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#41516]
Impacted versions: 13.0

Steps to reproduce:
1. Open the latest runbot 13.0 and create a new model with Studio (for example `x_test`) with atleast two datetime fields.
2. Add a `Many2one` from this model to `res.partner`
3. Go to contacts and create a `One2many` from `res.partner` to `x_test` and add the widget `hr_skills` or `hr_resume`
4. Save your changes and try to add a record

Current behavior:
Traceback:
TypeError: Cannot read property 'res_id' of undefined
    at http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5779-a775a9b/web.assets_backend.js:8266:1369
    at http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5778-7d1b8b4/web.assets_common.js:122:197
    at Function._.each._.forEach (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5778-7d1b8b4/web.assets_common.js:108:558)
    at Function.groupBy (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5778-7d1b8b4/web.assets_common.js:122:158)
    at Class._renderBody (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5779-a775a9b/web.assets_backend.js:8266:1295)
    at Class._renderView (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5779-a775a9b/web.assets_backend.js:2104:575)
    at Class.prototype.<computed> (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5778-7d1b8b4/web.assets_common.js:3860:488)
    at Class._renderView (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5779-a775a9b/web.assets_backend.js:2014:79)
    at Class._renderView (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5778-7d1b8b4/web.assets_common.js:3863:371)
    at Class._render (http://729939-13-0-8108ef.runbot25.odoo.com/web/content/5779-a775a9b/web.assets_backend.js:1405:222)

Expected behavior:
The widget works on any model. As you can see right now it is only built to use on the hr module itself but it would be such a great addition if the widgets `hr_skills` and `hr_resume` would be renamed and available globally. For example as `chronical_datetime` and `progress_level`.
Right now both widgets are created for just one purpose while they could serve many others such as chronical datetime ordering for customer details, data and much more.

**Comment by pedrobaeza** [comment]
I suppose there are missing steps in your description saying that you assign that widget. The applicable bug then is to restrict the usage of that widgets outside the involved model.

**Comment by Yenthe666** [comment]
Yes and no @pedrobaeza. These kind of widgets should be created with multiple purposes instead of just one model/module. You can use these kind of widgets in a lot of options and it would be a pity if you'd have to reinvent the wheel / create a new one :)

**Comment by pedrobaeza** [comment]
Yes, but they are separated things: you are putting some steps to reproduce a problem with Odoo studio: that's a bug that must be fixed in current version.

For the wishlist, that's something for master and of course desirable, but if you check the problem, it needs a field called res_id for working, so you probably will be able to use it on other models, but with certain data structure.

**Comment by Yenthe666** [comment]
@pedrobaeza the same will happen in Python/XML code ;)
And of course this is an idea for master/desirable. I just like to put out ideas if I think they have some extra value for upcoming versions.

**Comment by Yenthe666** [comment]
Since it's been open for almost two years it's clearly not going to ever make it. Closing..
