### ISSUE TITLE
Too Many Files to open

### ISSUE THREAD

**Issue by killvis** [odoo/odoo#41854]
Impacted versions:11.0

Steps to reproduce:
Extensive use of api  or huge traffic on website
large number of unique requests resulting in creation of too many session files.

Current behavior:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/media/hd1/exotelcalling/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/media/hd1/exotelcalling/odoo/service/wsgi_server.py", line 179, in application
    return application_unproxied(environ, start_response)
  File "/media/hd1/exotelcalling/odoo/service/wsgi_server.py", line 167, in application_unproxied
    result = handler(environ, start_response)
  File "/media/hd1/exotelcalling/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/media/hd1/exotelcalling/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/middleware/shared_data.py", line 227, in __call__
    return self.app(environ, start_response)
  File "/media/hd1/exotelcalling/odoo/http.py", line 1494, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/media/hd1/exotelcalling/odoo/http.py", line 1431, in get_response
    self.session_store.save(httprequest.session)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/contrib/sessions.py", line 256, in save
    fd, tmp = tempfile.mkstemp(suffix=_fs_transaction_suffix, dir=self.path)
  File "/usr/lib/python3.5/tempfile.py", line 481, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 24] Too many open files: '/media/hd1/exotelcalling/Odoo_data/sessions/tmpmssvwisq.__wz_sess'
Expected behavior:
reads session details without error

Video/Screenshot link (optional):

![error_too_many_files_to_open](https://user-images.githubusercontent.com/10908826/70803499-3788a700-1dda-11ea-8eef-335fa0d05dc0.png)

**Comment by pedrobaeza** [comment]
If the number of sessions is correct (because you have a lot of users), the changes limits in your system. If not, then something is not well configure in your part.

Any way, this is not an Odoo problem, but deployment one.

**Comment by killvis** [comment]
@pedrobaeza is it possible and advisable to not allocate sessions until vistors login to system
