### ISSUE TITLE
[13.0] Updating SMS modules causes TransActionRollbackError and destroys sessions

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42296]
Impacted versions: 13.0

Steps to reproduce:
1. Install a new Odoo 13 enterprise instance
2. Install the module `calendar_sms`
3. Stop your Odoo instance and make sure that it updates the `calendar_sms` module from the command line (it is important to do it through the command line as it is not reproducable from the frontend by updating the app!). For example: `./odoo-bin -u calendar_sms -c /etc/your-odoo-service.conf`

Alternatively:
1. Install a new Odoo 13 enterprise instance
2. Create a custom module that depends on `sms` and that adds SMS functionalities on a model
3. Stop your Odoo instance and make sure that it updates the `your_module` module from the command line (it is important to do it through the command line as it is not reproducable from the frontend by updating the app!). For example: `./odoo-bin -u your_module -c /etc/your-odoo-service.conf`

Current behavior: 
Your instance becomes blank and after a refresh you'll see you're logged out and that the session was destroyed. The logfiles will give you more details:
```
2019-12-23 13:11:04,461 4485 INFO sms_test odoo.modules.registry: module calendar_sms: creating or updating database tables 
2019-12-23 13:11:04,500 4487 INFO sms_test odoo.modules.loading: loading calendar_sms/data/sms_data.xml 
2019-12-23 13:11:04,504 4487 INFO sms_test odoo.modules.loading: loading calendar_sms/views/calendar_views.xml 
2019-12-23 13:11:04,534 4486 ERROR sms_test odoo.sql_db: bad query: UPDATE ir_model SET is_mail_thread=true,transient=false,info=' Model for Calendar Event

        Special context keys :
            - `no_mail_to_attendees` : disabled sending email to attendees when creating/editing a meeting
    ',is_mail_activity=false,is_mail_blacklist=false,name='Calendar Event',state='base' WHERE model='calendar.event' RETURNING id
ERROR: could not serialize access due to concurrent update
 
2019-12-23 13:11:04,534 4485 ERROR sms_test odoo.sql_db: bad query: UPDATE ir_model SET is_mail_thread=true,transient=false,info=' Model for Calendar Event

        Special context keys :
            - `no_mail_to_attendees` : disabled sending email to attendees when creating/editing a meeting
    ',is_mail_activity=false,is_mail_blacklist=false,name='Calendar Event',state='base' WHERE model='calendar.event' RETURNING id
ERROR: could not serialize access due to concurrent update
 
2019-12-23 13:11:04,535 4486 WARNING sms_test odoo.modules.loading: Transient module states were reset 
2019-12-23 13:11:04,537 4485 WARNING sms_test odoo.modules.loading: Transient module states were reset 
2019-12-23 13:11:04,535 4486 ERROR sms_test odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/odoo13/odoo13-server/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/odoo13/odoo13-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'sms_test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo13/odoo13-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 416, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo13/odoo13-server/odoo/modules/registry.py", line 324, in init_models
    func()
  File "/odoo13/odoo13-server/odoo/models.py", line 358, in _reflect
    self.env['ir.model']._reflect_model(self)
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_model.py", line 280, in _reflect_model
    ids = query_update(cr, self._table, params, ['model'])
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_model.py", line 68, in query_update
    cr.execute(query, values)
  File "/odoo13/odoo13-server/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update

```

Expected behavior:
You can update SMS modules without any issue, both the default Odoo modules and custom Odoo modules

**Comment by Yenthe666** [comment]
OPW `2161499`

**Comment by rim-odoo** [comment]
> Impacted versions: 13.0
> 
> Steps to reproduce:
> 
> 1. Install a new Odoo 13 enterprise instance
> 2. Install the module `calendar_sms`
> 3. Stop your Odoo instance and make sure that it updates the `calendar_sms` module from the command line (it is important to do it through the command line as it is not reproducable from the frontend by updating the app!). For example: `./odoo-bin -u calendar_sms -c /etc/your-odoo-service.conf`

Hello

I tried to reproduce your issue on a fresh new db but I couldn't.
I've been able to perform

```bash
python3 -B odoo-bin --log-level=debug --logfile=/tmp/1.log --addons-path=addons/,../enterprise/ --max-cron-threads=0 --limit-time-cpu=3600 --limit-time-real=3600 --db-filter='13.0' -d 13.0 -i calendar_sms --without-demo=1 --stop-after-init
```

then

```bash
python3 -B odoo-bin --log-level=debug --logfile=/tmp/2.log --addons-path=addons/,../enterprise/ --max-cron-threads=0 --limit-time-cpu=3600 --limit-time-real=3600 --db-filter='13.0' -d 13.0 -u calendar_sms --without-demo=1 --stop-after-init
```

then I even tried

```bash
python3 -B odoo-bin --log-level=debug --logfile=/tmp/3.log --addons-path=addons/,../enterprise/ --max-cron-threads=0 --limit-time-cpu=3600 --limit-time-real=3600 --db-filter='13.0' -d 13.0 -u sms --without-demo=1 --stop-after-init
```

without facing any issue.

Here are my logs for the record: https://gist.github.com/rim-odoo/52171c97f2660d8346c11de41dd1601d

=> are you sure that nothing else is running on your database? Concurrent errors surface when there are multiple transactions editing the same elements of the db...

By the way, there are multiple pids in your logs.

**Comment by Yenthe666** [comment]
Seems to be some local issue as pointed out by Richard.
