### ISSUE TITLE
[13.0] Tracback on Creating Cutomer from Pipeline's Kanban

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42436]
Impacted versions: 13.0

Steps to reproduce: 
![Screenshot (21)](https://user-images.githubusercontent.com/16624719/71549293-6bbab500-29e1-11ea-9113-2bc067edf987.png)

Current behavior:
![Screenshot (22)](https://user-images.githubusercontent.com/16624719/71549302-9442af00-29e1-11ea-990e-c9daa6a6f1f2.png)
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/res_partner.py", line 679, in name_create
    partner = self.create({self._rec_name: name or email, 'email': email or self.env.context.get('default_email', False)})
  File "<decorator-gen-215>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/base_vat/models/res_partner.py", line 415, in create
    return super(ResPartner, self).create(values)
  File "<decorator-gen-196>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/addons/account/models/partner.py", line 507, in create
    return super().create(vals_list)
  File "<decorator-gen-132>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/partner_autocomplete/models/res_partner.py", line 183, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-79>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/addons/base/models/res_partner.py", line 534, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-108>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-188>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/website/models/mixins.py", line 151, in create
    records = super(WebsitePublishedMixin, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/models.py", line 3722, in create
    records = self._create(data_list)
  File "/data/build/odoo/odoo/models.py", line 3794, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/data/build/odoo/odoo/fields.py", line 2150, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/data/build/odoo/odoo/fields.py", line 2162, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.partner.type: 'opportunity'
```
Expected behavior: No Traceback

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Seems to work just fine?
![image](https://user-images.githubusercontent.com/6352350/71556871-ff21d380-2a3d-11ea-94a8-db537ee9b2f3.png)

**Comment by sswapnesh** [comment]
> Seems to work just fine?

No,

You have to add a column to Create new Customer from there, Not a Lead.

**Comment by Yenthe666** [comment]
Please expand your steps with reproducable ways, there's info missing ;)

**Comment by sswapnesh** [comment]
I think this is Enough

**Creating Customer from Pipeline's Kanban** and also I have Highlighted same on the First screenshots

But still yes, It's better to Add Video on such cases

**Comment by Yenthe666** [comment]
See https://drive.google.com/file/d/1LPaD-LOgLWSpULJP-58CIToQLVCz0nhF/view - confirmed.

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by sswapnesh** [comment]
Yes (http://1718200-13-0-3353b1.runbot20.odoo.com/web#action=627&model=crm.lead&view_type=kanban&cids=1&menu_id=446)
![image](https://user-images.githubusercontent.com/16624719/76452612-69b89d80-63f7-11ea-9604-3ff7893539fe.png)

**Comment by pedrobaeza** [comment]
It seems a bad propagation of a context value maybe?

**Comment by sswapnesh** [comment]
Yep, Seems due to bad context
Working on a Fix

**Comment by sswapnesh** [comment]
Added fix for v12 https://github.com/odoo/odoo/pull/47723

**Comment by Yenthe666** [comment]
Clearly nobody looking at this but I've been bitten by it again a few weeks ago so I finally made an OPW :) OPW `2256905`

**Comment by sswapnesh** [comment]
Should be fixed by https://github.com/odoo/odoo/pull/52265

**Comment by Yenthe666** [comment]
This one did a change for it :) https://github.com/odoo/odoo/pull/51673
