### ISSUE TITLE
[12.0] Error occurred when install Point of Sale

### ISSUE THREAD

**Issue by Fazryan** [odoo/odoo#42452]
Impacted versions: Odoo 12.0

Steps to reproduce: -

Current behavior: error during installation

Expected behavior: Solution

Video/Screenshot link (optional): 
![Error when install](https://user-images.githubusercontent.com/21353841/71567194-bd516580-2aef-11ea-9344-48b284b1ad7c.png)

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 297, in init_models
    model.init()
  File "/opt/odoo12/odoo/addons/sale/report/sale_report.py", line 135, in init
    self.env.cr.execute("""CREATE or REPLACE VIEW %s as (%s)""" % (self._table, self._query()))
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column reference "qty" is ambiguous
LINE 70: ...        CASE WHEN pos.state = 'invoiced' THEN sum(qty) ELSE ...
                                                              ^
```

The app menu items appears but cannot be accessed,

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1096

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo12/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(1096,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 1262, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/opt/odoo12/odoo-custom-addons/odoo_marketplace/models/ir_action.py", line 68, in read
    res = super(IrActionWindow, self).read(fields=fields, load=load)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_actions.py", line 210, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/opt/odoo12/odoo/odoo/models.py", line 2791, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo12/odoo/odoo/models.py", line 5117, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo12/odoo/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_actions.py", line 170, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/opt/odoo12/odoo/odoo/api.py", line 821, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'pos.config'
```

**Comment by pedrobaeza** [comment]
You have a module that is adding a `qty` column somewhere in POS models, provoking an ambiguous reference. Please try on a fresh DB without extra addons.

Closing due to this.
