### ISSUE TITLE
[8.0 7.0] Unusable error when mail message is the element involved.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#4256]
Hello.

For some reason, cancelling a delivery, without put null the reserved inventory, we receive this message below.

The point is that when a recursive object fails the access rules, we should be able at least from logger get the id, and the deep analisis of what is happening in order to set correctly the corresponding ACL.
## What I got:

Error with Access denied.
## Whan I need:

Error with Access Denied, indicating at least the specific record I don't have access to, or the context enviroment variables to validate and set the correct ACL.

Regards. 

```
2014-12-15 17:03:02,178 14118 DEBUG None openerp.http.rpc.request: db.list time:0.007s mem: 880480k -> 880480k (diff: 0k)(True,)
2014-12-15 17:03:02,180 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,247 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,247 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,258 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,276 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,659 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,664 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:02,665 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:03,283 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:03,940 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:04,255 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:03:04,275 14118 ERROR production openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/runbot/instance/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/runbot/instance/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/home/runbot/instance/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/runbot/instance/odoo/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/home/runbot/instance/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/runbot/instance/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/runbot/instance/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 898, in action_cancel
    self.pool.get('stock.move').action_cancel(cr, uid, ids2, context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 2242, in action_cancel
    self.action_cancel(cr, uid, [move.move_dest_id.id], context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 2242, in action_cancel
    self.action_cancel(cr, uid, [move.move_dest_id.id], context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 2252, in action_cancel
    procurement_obj.check(cr, uid, procs_to_check, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/procurement/procurement.py", line 228, in check
    result = self._check(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/purchase_requisition/purchase_requisition.py", line 426, in _check
    return super(procurement_order, self)._check(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/purchase/purchase.py", line 1205, in _check
    return super(procurement_order, self)._check(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mrp/procurement.py", line 58, in _check
    return super(procurement_order, self)._check(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/procurement.py", line 241, in _check
    self.message_post(cr, uid, [procurement.id], body=_('All stock moves have been cancelled for this procurement.'), context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mail/mail_thread.py", line 1655, in message_post
    msg_id = mail_message.create(cr, uid, values, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mail/mail_message.py", line 808, in create
    user_signature=context.get('mail_notify_user_signature', True))
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mail/mail_message.py", line 871, in _notify
    if message.partner_ids:
  File "/home/runbot/instance/odoo/openerp/fields.py", line 774, in __get__
    self.determine_value(record)
  File "/home/runbot/instance/odoo/openerp/fields.py", line 867, in determine_value
    record._prefetch_field(self)
  File "/home/runbot/instance/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/models.py", line 3170, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/runbot/instance/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mail/mail_message.py", line 822, in read
    self.check_access_rule(cr, uid, ids, 'read', context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/portal/mail_message.py", line 63, in check_access_rule
    return super(mail_message, self).check_access_rule(cr, uid, ids=ids, operation=operation, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mail/mail_message.py", line 765, in check_access_rule
    (self._description, operation))
except_orm: (u'Access Denied', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Message, Operation: read)')
```

**Comment by nhomar** [comment]
this behavior is the expected one but a pain, I hope odoo dedicates time to improve this, but for now it does not make sense keep this open.
