### ISSUE TITLE
[8.0] concurrent update of picking in huge transactions.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#4257]
In v8.0 we have transactions that expend something like 30 or 40 minutes to be computed with only 300 lines of Products in a sales order.

After a while, several time it happens that the process is broken with the traceback below.

We have a little complex enviroment:
- Pack, pick and deliver warehouse output strategy.
- Invoice from delivery.
- +10000 product.product elements (1 product - 1 variant).
- Running enviroment with 7 workers.
  blah blah!.

It is almost unusable, but the main issue is the incorrect management of sequences, we need to find a solution for it.

Regards.

```
2014-12-15 17:06:11,740 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,742 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,743 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,786 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,787 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,841 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,843 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,843 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,881 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,884 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,930 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,930 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,932 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,966 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:11,970 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,014 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,022 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,024 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,063 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,066 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,099 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,106 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,306 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:12,357 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:14,191 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:15,732 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:15,742 14118 DEBUG None openerp.http.rpc.request: db.list time:0.006s mem: 880480k -> 880480k (diff: 0k)(True,)
2014-12-15 17:06:18,689 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:18,828 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,019 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,029 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,126 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,136 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,223 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,321 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,349 14118 INFO production openerp.service.common: successful login from 'nhomar@vauxoo.com' using database 'production'
2014-12-15 17:06:19,350 14118 DEBUG production openerp.http.rpc.request: common.login time:0.108s mem: 880480k -> 880480k (diff: 0k)(u'production', u'nhomar@vauxoo.com', '*')
2014-12-15 17:06:19,402 14118 ERROR production openerp.sql_db: bad query: INSERT INTO "stock_move" ("id", "origin", "product_uos_qty", "product_uom", "product_uom_qty", "date", "product_uos", "partner_id", "picking_type_id", "location_id", "company_id", "priority", "state", "weight_uom_id", "date_expected", "procurement_id", "warehouse_id", "propagate", "move_dest_id", "procure_method", "product_id", "name", "partially_available", "invoice_state", "location_dest_id", "group_id", "rule_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('stock_move_id_seq'), 'SO-046904:WH: Packing Zone -> Output', 40.0, 21, 40.0, '2014-12-15 23:04:36', 21, 2226, 5, 1521, 1, '1', 'draft', 3, '2014-12-15 23:04:36', 31988, 1, true, 62181, 'make_to_stock', 18212, 'WH: Packing Zone -> Output', false, 'none', 16, 421, 8, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/runbot/instance/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

2014-12-15 17:06:19,402 14118 ERROR production openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/runbot/instance/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/runbot/instance/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/home/runbot/instance/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/runbot/instance/odoo/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/home/runbot/instance/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/runbot/instance/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/runbot/instance/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/portal_sale/portal_sale.py", line 67, in action_button_confirm
    return super(sale_order, self).action_button_confirm(cr, uid, ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/sale/sale.py", line 598, in action_button_confirm
    self.signal_workflow(cr, uid, ids, 'order_confirm')
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/models.py", line 3483, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/home/runbot/instance/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/runbot/instance/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/runbot/instance/odoo/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/runbot/instance/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/runbot/instance/odoo/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/runbot/instance/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/sale/sale.py", line 720, in action_ship_create
    proc_id = procurement_obj.create(cr, uid, vals, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/procurement_jit/procurement_jit.py", line 30, in create
    self.run(cr, uid, [procurement_id], context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/procurement.py", line 219, in run
    self.pool.get('stock.move').action_confirm(cr, uid, move_to_confirm_ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/delivery/stock.py", line 183, in action_confirm
    res = super(stock_move, self).action_confirm(cr, uid, ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mrp/stock.py", line 151, in action_confirm
    return super(StockMove, self).action_confirm(cr, uid, move_ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 2117, in action_confirm
    self._create_procurement(cr, uid, move, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 1891, in _create_procurement
    return self.pool.get("procurement.order").create(cr, uid, self._prepare_procurement_from_move(cr, uid, move, context=context))
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/procurement_jit/procurement_jit.py", line 30, in create
    self.run(cr, uid, [procurement_id], context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/procurement.py", line 219, in run
    self.pool.get('stock.move').action_confirm(cr, uid, move_to_confirm_ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/delivery/stock.py", line 183, in action_confirm
    res = super(stock_move, self).action_confirm(cr, uid, ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mrp/stock.py", line 151, in action_confirm
    return super(StockMove, self).action_confirm(cr, uid, move_ids, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 2117, in action_confirm
    self._create_procurement(cr, uid, move, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/stock.py", line 1891, in _create_procurement
    return self.pool.get("procurement.order").create(cr, uid, self._prepare_procurement_from_move(cr, uid, move, context=context))
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/procurement_jit/procurement_jit.py", line 30, in create
    self.run(cr, uid, [procurement_id], context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/procurement.py", line 210, in run
    res = super(procurement_order, self).run(cr, uid, new_ids, autocommit=autocommit, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/procurement/procurement.py", line 206, in run
    res = self._run(cr, uid, procurement, context=context or {})
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/purchase_requisition/purchase_requisition.py", line 418, in _run
    return super(procurement_order, self)._run(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/purchase/purchase.py", line 1200, in _run
    return super(procurement_order, self)._run(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/mrp/procurement.py", line 53, in _run
    return super(procurement_order, self)._run(cr, uid, procurement, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/addons/stock/procurement.py", line 204, in _run
    move_obj.create(cr, SUPERUSER_ID, move_dict, context=context)
  File "/home/runbot/instance/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/models.py", line 3999, in create
    record = self.browse(self._create(old_vals))
  File "/home/runbot/instance/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/models.py", line 4137, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/runbot/instance/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/runbot/instance/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
" while evaluating
u'action_ship_create()'
2014-12-15 17:06:19,447 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,456 14118 DEBUG None openerp.http.rpc.request: db.list time:0.006s mem: 880480k -> 880480k (diff: 0k)(True,)
2014-12-15 17:06:19,457 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,526 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,649 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,789 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:19,871 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:20,021 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - old# 285 new# 285]
2014-12-15 17:06:20,367 14118 DEBUG production openerp.modules.registry: Multiprocess signaling check: [Registry - old# 3 new# 3] [Cache - o
```

**Comment by orchidinfosys** [comment]
Account Invoice with 30 to 40 Lines also taking 30 Minutes to get validated.
Its not at acceptable and need a fix ASAP from Odoo

**Comment by jco-odoo** [comment]
I guess it is because they try to access each others fields.  Normally
several sale orders don't touch each other: different moves, different
pickings, different procurement groups.

**Comment by gdgellatly** [comment]
Hmm,

I've had this error before on bulk type operations.  This is not to provide
a solution, but merely how I resolved the issue for myself and my past
experiences with these.  I am not saying it is a good idea, and not for
your average user, you must understand the implications.  Firstly within
this chain there are 3 distinct error logs.  They are related but are
different.

Error 1: Tracking down the exact cause of this is a nightmare and has
occurred since version 6.1.  I must admit I never got to the bottom of it
but it is related to Postgres Transaction Isolation levels and workflow
triggers.  In my batch algorithms to avoid this typically it will have code
like.

from psycopg2.extensions import ISOLATION_LEVEL_READ_COMMITTED
and then in the function that performs the operation
cr._cnx.set_isolation_level(ISOLATION_LEVEL_READ_COMMITTED)

Error 2: Is impossible to provide exact comment on, other than to say that
it is a custom module, it may or may not be related to transaction
isolation levels.

Error 3: I'd advice starting a session with cprof and viewing the resulting
command map.  I definitely do not experience this with invoices of even 100
lines.  There was a fix a long time ago now which stopped the recursive
validation of invoice lines.  If this is still occuring, then it could be a
regression, context passing has seen some changes of late, or it could be a
custom function mangling the context key or context which is passed.  But
that was the original cause of slow invoicing, was the factorial behaviour
of validation of the account_move_lines on invoice validation.

In fact that probably goes for all 3, start Odoo using cprofile, perform
the transaction and check the resulting map, exponentially called functions
should really stick out.

**Comment by orchidinfosys** [comment]
Further investigation, found that
If it set realtime costing method enabled and lot number with minimal transaction , then its fine.
If the volume is more and each invoice having number of lines, its taking too much time and it increases with the database size. Real Time costing and lot number make the issue.

**Comment by hzhenia** [comment]
I faced the same problems as nhomar with V7.0. It takes ~40 min to process SO with above 1200 lines (200 Invoice) so that make the whole system hanged.
My temporary solution is breaking processing-work into small pieces so that transaction could be commited.

**Comment by nhomar** [comment]
as v7 is not supported anymore, closed. (And this was hugely improved on the next versions) IF  you are stuck on v7 with this issue migrate your BD is the best approach I think.
