### ISSUE TITLE
[12.0] Javascript Error : Change the value of One2Many field

### ISSUE THREAD

**Issue by zhumeng459** [odoo/odoo#42760]
The struct of model as below :
  Model A
　┕──fieldB = fields.One2many
　　　　┕──ph:fields.char
 
  I wrote some JS code to modify the value of ph field . Some wrong happened when it modify the first row the second time . 

  Code :
`odoo.define('x_ds.mm_test_js', function (require) {
    "use strict";

    var relational_fields = require('web.relational_fields' )
    var FieldOne2Many = relational_fields.FieldOne2Many
    var ListRenderer = require('web.ListRenderer');
    
    FieldOne2Many.include({
     
        _onFieldChanged: function( event ){
            var self = this 
            var r = this._super( event )
            console.log( event ) 
            console.log( this )
            
            var x 
            var datas               
            var o_changes = event.data.changes
            
            if ( ( 'ph' in o_changes ) && o_changes.ph ){
                
                datas = this.value.data
                for ( x in datas )
                {
                    if ( event.data.dataPointID == datas[ x ].id ) { //
                        break 
                    }
                    
                   if ( 'ph' in datas[ x ].data  ) { // 
                        this._setValue({
                            operation: 'UPDATE',
                            id: datas[ x ].id ,
                            data: o_changes ,
                        }).done(function() {    
                            window.location.reload()   
                        });
                    }
                }
                
            }

            return r
        }
    })`

Error :
`
Uncaught TypeError: Cannot read property '7' of undefined

http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1900
TypeError: Cannot read property '7' of undefined
    at Class.confirmUpdate (http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1900:263)
    at Class.reset (http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1225:526)
    at Class.prototype.(anonymous function) [as reset] (http://127.0.0.1:8012/web/content/495-46e6f55/web.assets_common.js:3538:488)
    at Class.reset (http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1240:1413)
    at Class.prototype.(anonymous function) [as reset] (http://127.0.0.1:8012/web/content/495-46e6f55/web.assets_common.js:3538:488)
    at http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1574:237
    at Function._.each._.forEach (http://127.0.0.1:8012/web/content/495-46e6f55/web.assets_common.js:12:558)
    at Class.confirmChange (http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1574:78)
    at Class.confirmChange (http://127.0.0.1:8012/web/content/507-d415ebc/web.assets_backend.js:1627:1087)
    at Class.prototype.(anonymous function) (http://127.0.0.1:8012/web/content/495-46e6f55/web.assets_common.js:3538:488)`

**Comment by C3POdoo** [comment]
Dear @zhumeng459,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
