### ISSUE TITLE
Odoo 8.0 calendar sync problem

### ISSUE THREAD

**Issue by noamix** [odoo/odoo#4280]
when I Tried  to access the page http://my server:8069/google_account/authentication I have this

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Here is the server log, 

```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 159, in run_wsgi

    execute(app)

  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 146, in execute

    application_iter = app(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/service/server.py", line 281, in app

    return self.app(e, s)

  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 216, in application

    return application_unproxied(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 202, in application_unproxied

    result = handler(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1239, in __call__

    return self.dispatch(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1213, in __call__

    return self.app(environ, start_wrapped)

  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__

    return self.app(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1380, in dispatch

    result = ir_http._dispatch()

application_iter = app(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/service/server.py", line 281, in app

    return self.app(e, s)

  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 216, in application

    return application_unproxied(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 202, in application_unproxied

    result = handler(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1239, in __call__

    return self.dispatch(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1213, in __call__

    return self.app(environ, start_wrapped)

  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__

    return self.app(environ, start_response)

  File "/opt/odoo/odoo-server/openerp/http.py", line 1380, in dispatch

    result = ir_http._dispatch()

  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 130, in _dispatch

    return self._handle_exception(e)

  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception

    return request._handle_exception(exception)

  File "/opt/odoo/odoo-server/openerp/http.py", line 618, in _handle_exception

    return super(HttpRequest, self)._handle_exception(exception)

  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch

    result = request.dispatch()

  File "/opt/odoo/odoo-server/openerp/http.py", line 636, in dispatch

    r = self._call_function(**self.params)

  File "/opt/odoo/odoo-server/openerp/http.py", line 295, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo/odoo-server/openerp/http.py", line 292, in checked_call

    return self.endpoint(*a, **kw)

  File "/opt/odoo/odoo-server/openerp/http.py", line 755, in __call

return self.method(*args, **kw)

  File "/opt/odoo/odoo-server/openerp/http.py", line 388, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo/odoo-server/addons/google_account/controllers/main.py", line 17, in oauth2callback

    state = simplejson.loads(kw['state'])

KeyError: 'state'
```
any clue will be appreciated

**Comment by JKE-be** [comment]
Thank you noamix for your help to fix this bug !

**Comment by garethparker** [comment]
Thanks for fixing this! Just in case anyone else uses this workaround and then doesn't understand why Calendar Sync still doesn't work - you'll need to resave the API details under Settings > Calendar > API Credentials and then run the sync process.
