### ISSUE TITLE
[13.0]  ValueError("Unknown path: %s" % name)

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#43315]
Impacted versions: 13.0

Steps to reproduce:

Take the latest pull and restart the server.

Error :

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1281, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1251, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1450, in dispatch
    result = ir_http._dispatch()
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 172, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/odoo/odoo-server/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/odoo/odoo-server/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 516, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
    return cls._handle_exception(e)
  File "/odoo/odoo-server/addons/http_routing/models/ir_http.py", line 607, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 744, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 803, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 944, in load_locale
    file_open('web/static/lib/moment/locale/%s.js' % code, 'rb')
  File "/odoo/odoo-server/odoo/tools/misc.py", line 197, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/odoo/odoo-server/odoo/tools/misc.py", line 215, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /web/static/lib/moment/locale/en-us.js - - -

**Comment by bhaveshselarka** [comment]
@Yenthe666 @sswapnesh

**Comment by bhaveshselarka** [comment]
Found a solution from: https://github.com/odoo/odoo/issues/22463

**Comment by Kyuubi1** [comment]
Just remove command after addons-path in config file
ex : addons_path = /xxx/addons, -> addons_path = /xxx/addons
