### ISSUE TITLE
[12.0]Enterprise Can't Connect IoT Box with Odoo.

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#43355]
Impacted versions:
12.0 Enterprise

Steps to reproduce:
Install iot module and try to connect the iot box with the url and token.

Current behavior:
can't connect and giving this errors:

Expected behavior:
Should show the iot box connected

Video/Screenshot link (optional):

**TypeError: update_box() got an unexpected keyword argument 'iot_box'
TypeError: download_drivers() got an unexpected keyword argument 'auto' - - -**

`Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
TypeError: update_box() got an unexpected keyword argument 'iot_box'
2020-01-15 14:44:28,189 26617 INFO z_master werkzeug: 109.164.208.26 - - [15/Jan/2020 14:44:28] "POST /iot/setup HTTP/1.1" 200 - 3 0.005 0.015
2020-01-15 14:44:28,271 26617 INFO z_master werkzeug: 109.164.208.26 - - [15/Jan/2020 14:44:28] "POST /iot/get_drivers HTTP/1.1" 500 - 3 0.004 0.017
2020-01-15 14:44:28,279 26617 ERROR z_master werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo12/odoo12-server/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/odoo12/odoo12-server/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/odoo12/odoo12-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo12/odoo12-server/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo12/odoo12-server/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/odoo12/odoo12-server/odoo/http.py", line 1486, in dispatch
    result = ir_http._dispatch()
  File "/odoo12/odoo12-server/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo12/odoo12-server/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/odoo12/odoo12-server/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/odoo12/odoo12-server/addons/http_routing/models/ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/odoo12/odoo12-server/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/odoo12/odoo12-server/addons/website/models/ir_http.py", line 175, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/odoo12/odoo12-server/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 774, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/odoo12/odoo12-server/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
TypeError: download_drivers() got an unexpected keyword argument 'auto' - - -
 `

**Comment by pedrobaeza** [comment]
As this an enterprise module, please report it to odoo.com/help instead of here.

I'm closing this as it seems something local that it's not going to benefit from being shared here.
