### ISSUE TITLE
[7.0] Purchase Receipts. Error on update.

### ISSUE THREAD

**Issue by kingofsevens** [odoo/odoo#4362]
In `Purchase Receipts` you can create a receipt without stating supplier. After you enter some lines and fill the requested fields when you click the `update` button it creates a draft receipt but gives the below error presented at the bottom. This is the first error.

The second error is: Without using the `update` button, when you enter another line it doesn't update the result when the form is open and same error continues when you save the form as well. Clicking `Validate` does not check for the total number it checks for the accounts and confirms it with the wrong total. For the form to be updated correctly you have to edit it select a different tax from the dropdown and change the tax again to a correct one. Or you need to add a supplier and hit update.

Note: This is a multi-company DB, I don't think it is relevant but worth the mention.

```
Client Traceback (most recent call last):
  File "/opt/openerp/server/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/openerp/server/addons/web/controllers/main.py", line 1137, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/server/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/opt/openerp/server/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/server/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/server/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/opt/openerp/server/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/server/addons/account_voucher/account_voucher.py", line 443, in compute_tax
    taxes = position_pool.map_tax(cr, uid, partner and partner.property_account_position or False, tax)
  File "/opt/openerp/server/openerp/osv/orm.py", line 503, in __getattr__
    return self[name]
  File "/opt/openerp/server/openerp/osv/orm.py", line 406, in __getitem__
    field_values = self._table.read(self._cr, self._uid, ids, field_names, context=self._context, load="_classic_write")
  File "/opt/openerp/server/openerp/osv/orm.py", line 3708, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/opt/openerp/server/openerp/osv/orm.py", line 3768, in _read_flat
    self.check_access_rule(cr, user, ids, 'read', context=context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4018, in check_access_rule
    [sub_ids] + where_params)
  File "/opt/openerp/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...artner.id FROM "res_partner" WHERE res_partner.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by Yenthe666** [comment]
Hi @kingofsevens ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
