### ISSUE TITLE
[API8] Many2one field default attribute: no way to set the default to 0 or False

### ISSUE THREAD

**Issue by Sathors** [odoo/odoo#4384]
## Impacted versions:

 - 8.0, maybe master

## Issue description:
In the API v7, we used to have our defaults like this:

```python
_columns = {
    'location_id': fields.many2one('location.location')
}
_defaults = {
    'location_id': lambda self, cr, uid, context=None: context.get('location_id', False)
}
```

So if the key 'location_id' was in the context, its value was passed as the location_id column default, else the field location_id was set to False.

Now while migrating to the new API v8, I write it this way:

```python
location_id = fields.Many2one('location.location', default=lambda self: self._context.get('location_id', False))
```

Everything was working all right in the API 7, now it is not working anymore.
If I write it in the above way, I have the following error:
```
Traceback (most recent call last):
  File "/home/nicolas/odoo/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/nicolas/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/nicolas/odoo/openerp/modules/module.py", line 283, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2574, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2401, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/fields.py", line 363, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/home/nicolas/odoo/openerp/fields.py", line 1490, in convert_to_write
    return value.id
AttributeError: 'bool' object has no attribute 'id'
```

If I write the default in the form:
```python
default=lambda self: self._context.get('location_id', 0)
```
that used to work in the v7, I have the error:
```
Traceback (most recent call last):
  File "/home/nicolas/odoo/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/nicolas/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/nicolas/odoo/openerp/modules/module.py", line 283, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2574, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2401, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/fields.py", line 363, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/home/nicolas/odoo/openerp/fields.py", line 1490, in convert_to_write
    return value.id
AttributeError: 'int' object has no attribute 'id'
```

It is pretty logical, it seems Odoo is trying to read the id attribute of the value given back by the default.
The thing is: how can I tell him that the default is returning a no-value?

If instead of using a lambda for the default, I use a method of the form:
```python
    def _default_location_id(self):
        print "Entered"
        print "context", self._context
        if 'destination_id' in self._context:Impacted versions:

 - 7.0 and above
            self.location_id = self._context['destination_id']
        else:
            self.location_id = False

    location_id = fields.Many2one('location.location', default=_default_location_id)
```
which is setting the field to False it complains with the following error:
```
Traceback (most recent call last):
  File "/home/nicolas/odoo/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/nicolas/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/nicolas/odoo/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/nicolas/odoo/openerp/modules/module.py", line 283, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2574, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/models.py", line 2401, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/home/nicolas/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/nicolas/odoo/openerp/fields.py", line 363, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/home/nicolas/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/nicolas/odoo/olympo_src8/oly_asset_transaction/account_asset.py", line 205, in _default_location_id
    self.location_id = False
  File "/home/nicolas/odoo/openerp/fields.py", line 787, in __set__
    record.ensure_one()
  File "/home/nicolas/odoo/openerp/models.py", line 5196, in ensure_one
    raise except_orm("ValueError", "Expected singleton: %s" % self)
except_orm: ('ValueError', 'Expected singleton: account.asset.asset()')
```

Thanks

**Comment by lepistone** [comment]
I confirm that: in v8 the default method for a many2one field must return a record (possibly an empty one) but not `False`.

@rco-odoo, is that intentional? If so, it's OK by me (with a mention in the doc maybe). 

@Sathors, a way to get an empty record is
`self.env['stock.location']`

**Comment by Sathors** [comment]
@lepistone , thanks for the hint, we will wait for Odoo official confirmation, but I guess it should be the intended way. If so, I will see to update the documentation, because it is not so intuitive.

And thanks about the trick to get an empty record, I didn't know it was working that way neither.

**Comment by clonedagain** [comment]
Have things changed regarding the empty records?

**Comment by gdgellatly** [comment]
Lionel, 

While I don't know the official answer all I do is set to an empty recordset. E.g self.env['product.product']

**Comment by Sathors** [comment]
@clonedagain, I can confirm that returning an empty recordset works.
So in the above example, it would be:
```python
location_id = fields.Many2one('location.location',
                               default=lambda self: self._context.get('location_id', 
                                                                      self.env['location.location']))
```
Still waiting for Odoo to see if they were not thinking in another way.

**Comment by Nowheresly** [comment]
:+1: excellent tips

**Comment by rco-odoo** [comment]
@lepistone I confirm that default values for relational fields must return a recordset.

@Sathors the right definition for your field should be:

    location_id = fields.Many2one('location.location',
                                  default=lambda self: self.env['location.location'].browse(self._context.get('location_id', False)))

**Comment by Sathors** [comment]
@rco-odoo thanks for the correction!
