### ISSUE TITLE
[13] Website: Trackback due to Invalid date format

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44047]
Impacted versions: 13.0
 
Steps to reproduce: Create New Event from Website --> Change Date (with the Same format)
![Screenshot (78)](https://user-images.githubusercontent.com/16624719/73200487-e3087380-415c-11ea-94b6-4a7055bbb121.png)
![Screenshot (79)](https://user-images.githubusercontent.com/16624719/73200504-f1568f80-415c-11ea-8a86-cfbc5ecea860.png)

Current behavior: Traceback 

Error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/website/models/ir_ui_view.py", line 430, in save
    super(View, self).save(value, xpath=xpath)
  File "/data/build/odoo/addons/web_editor/models/ir_ui_view.py", line 178, in save
    self.save_embedded_field(arch_section)
  File "/data/build/odoo/addons/web_editor/models/ir_ui_view.py", line 50, in save_embedded_field
    value = converter.from_html(Model, Model._fields[field], el)
  File "/data/build/odoo/addons/web_editor/models/ir_qweb.py", line 243, in from_html
    dt = datetime.strptime(value, date_format)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'February 08, 2020' does not match format '%m/%d/%Y %H:%M'
```
Expected behavior: Save Event

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
Will be fixed with https://github.com/odoo/odoo/pull/45555
