### ISSUE TITLE
[13] l10n_in: Could not reinstall l10n_in module with demo data

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44137]
Impacted versions: 13.0

Steps to reproduce: Install --> Uninstall --> Install `l10n_in` module

Current behavior: 
**The demonstration data of 0 module(s) failed to install and were disabled**

```
2020-01-28 16:52:36,021 5736 INFO 13_ce odoo.modules.loading: loading l10n_in/data/account_payment_demo.xml 
2020-01-28 16:52:36,055 5736 WARNING 13_ce odoo.modules.loading: Module l10n_in demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 333, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 205, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/addons/payment/models/account_payment.py", line 99, in post
    res = super(AccountPayment, self - payments_need_trans).post()
  File "/home/sswapnesh/WorkSpace/odoo/addons/account/models/account_payment.py", line 661, in post
    raise UserError(_("Only a draft payment can be posted."))
odoo.exceptions.UserError: ('Only a draft payment can be posted.', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/odoo/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 333, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/tools/convert.py", line 205, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/addons/payment/models/account_payment.py", line 99, in post
    res = super(AccountPayment, self - payments_need_trans).post()
  File "/home/sswapnesh/WorkSpace/odoo/addons/account/models/account_payment.py", line 661, in post
    raise UserError(_("Only a draft payment can be posted."))
odoo.tools.convert.ParseError: "Only a draft payment can be posted.
" while parsing /home/sswapnesh/WorkSpace/odoo/addons/l10n_in/data/account_payment_demo.xml:2, near
<odoo noupdate="1">
    <!-- Demo of at(Tax liability on advances). Advance payment need to consideration for which invoices have not been issued in the same month.-->
	<record id="demo_payment_at" model="account.payment">
        <field name="partner_id" ref="l10n_in.res_partner_registered_customer"/>
        
        <field name="partner_type">customer</field>
        <field name="amount">10000</field>
        <field name="payment_type">inbound</field>
        <field name="payment_date" eval="time.strftime('%Y-%m')+'-01'"/>
        <field name="journal_id" model="account.journal" eval="obj().search([                 ('type', '=', 'cash'),                 ('company_id', '=', obj().env.company.id)], limit=1).id"/>
        <field name="payment_method_id" model="account.journal" eval="obj().search([                 ('type', '=', 'cash'),                 ('company_id', '=', obj().env.company.id)], limit=1).inbound_payment_method_ids[0].id"/>
    </record>

    <function model="account.payment" name="post">
        <value eval="[ref('demo_payment_at')]"/>
    </function>
</odoo>

```
Expected behavior: Successful loading of demo data 

Video/Screenshot link (optional):

**Comment by C3POdoo** [comment]
Dear @sswapnesh,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
