### ISSUE TITLE
Odoo 12 - email marketing list export issue

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#44196]
Impacted versions: 12 

Steps to reproduce: email marketing -> email list -> check some positions -> action -> export

Current behavior: Getting error

Expected behavior: Export to excel 

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 80, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 1505, in index
    return self.base(data, token)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 1453, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/odoo/odoo/odoo/models.py", line 819, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/odoo/odoo/odoo/models.py", line 796, in _export_rows
    for record, xid in self.env[model].browse(ids).__ensure_xml_id():
  File "/opt/odoo/odoo/odoo/models.py", line 695, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.
```

**Comment by pedrobaeza** [comment]
I have done it on runbot without problem:

![Peek 29-01-2020 19-14](https://user-images.githubusercontent.com/7165771/73384480-a313ce80-42cb-11ea-9e47-845bb6cf01bc.gif)

so the problem should be in your side or there should be any missing steps to reproduce the problem.

Closing meanwhile.
