### ISSUE TITLE
Unable to import .po file which exported from Odoo

### ISSUE THREAD

**Issue by micksatana** [odoo/odoo#44227]
Odoo unable to import .po file which exported from another Odoo database from the same instance

### Impacted versions: 

[13.0](https://hub.docker.com/layers/odoo/library/odoo/13.0/images/sha256-721a8e0f0bf2ad3dfa0230848f81ddf10471b706d5258af69e3f9f8076321a40)

### Steps to reproduce:

 - Translate `th_TH`
 - Export as `.po` file
 - Import to another database using the `.po` file

### Current behavior:

Got this error

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/wizard/base_import_language.py", line 43, in import_lang
    lang_name=this.name, context=this._context)
  File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1106, in trans_load_data
    irt_cursor.finish()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_translation.py", line 122, in finish
    """ % (self._model_table, self._table))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.CardinalityViolation: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/wizard/base_import_language.py", line 51, in import_lang
    'Technical Details:\n%s') % tools.ustr(e))
TypeError: not enough arguments for format string
```

### Expected behavior:

Able to import

**Comment by pedrobaeza** [comment]
This is logical as you are not providing it inside a module with their POT file, so there can be conflicts of adding the same translations, which is not allowed. POT files serves for discriminating that ones. Note that this is something new since v12 (but not very very new).

Closing as no valid.
