### ISSUE TITLE
[Trunk / 7.0] crash when duplicating a database from the web interface

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#4424]
Issue originally created by @gurneyalex on https://bugs.launchpad.net/openobject-server/+bug/1180000

I got the following crash when trying to duplicate a database from the web interface:

```
Client Traceback (most recent call last):
  File "/srv/openerp/instances/openerp_prod/parts/webclient/addons/web/http.py", line 203, in dispatch
    response["result"] = method(self, **self.params)
  File "/srv/openerp/instances/openerp_prod/parts/webclient/addons/web/controllers/main.py", line 733, in duplicate
    return req.session.proxy("db").duplicate_database(*duplicate_attrs)
  File "/srv/openerp/instances/openerp_prod/parts/webclient/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/srv/openerp/instances/openerp_prod/parts/webclient/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/srv/openerp/instances/openerp_prod/parts/webclient/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/srv/openerp/instances/openerp_prod/parts/server/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/srv/openerp/instances/openerp_prod/parts/server/openerp/service/web_services.py", line 122, in dispatch
    return fn(*params)
  File "/srv/openerp/instances/openerp_prod/parts/server/openerp/service/web_services.py", line 178, in exp_duplicate_database
    cr.execute("""CREATE DATABASE "%s" ENCODING 'unicode' TEMPLATE "%s" """ % (db_name, db_original_name))
  File "/srv/openerp/instances/openerp_prod/parts/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp_prod/parts/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
OperationalError: source database "openerp_prod" is being accessed by other users
DETAIL: There are 8 other session(s) using the database.
```

**Comment by Yenthe666** [comment]
Hi @max3903,

This issue doesn't seem to be present in the latest 7.0 version?
Could you confirm this so I can close this bug report?

Thanks,
Yenthe

**Comment by jholze** [comment]
-- 
Jens Holze
Sent with Airmail

Am 28. Mai 2016 um 11:52:35, Yenthe (notifications@github.com) schrieb:

Hi @max3903 <https://github.com/max3903>,

This issue doesn't seem to be present in the latest 7.0 version?
Could you confirm this so I can close this bug report?

Thanks,
Yenthe

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/4424#issuecomment-222300211>, or mute
the thread
<https://github.com/notifications/unsubscribe/AGiMAjApd9QuUc3EtLA_PocYyMiWT0fIks5qGBBDgaJpZM4DMKsE>
.

**Comment by max3903** [comment]
@Yenthe666 Will do when I get some time. Probably next week.

**Comment by max3903** [comment]
:+1:
