### ISSUE TITLE
[13] crm: Traceback on sending mail from CRM

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44441]
Impacted versions: 13

Steps to reproduce:
![image](https://user-images.githubusercontent.com/16624719/73614106-1e55e700-4622-11ea-9615-651b5cbeb47b.png)
![image](https://user-images.githubusercontent.com/16624719/73614109-29a91280-4622-11ea-9ec6-010f36e1a817.png)

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 204, in action_send_mail
    self.send_mail()
  File "/data/build/odoo/addons/website_sale/models/mail_compose_message.py", line 20, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 263, in send_mail
    all_mail_values = wizard.get_mail_values(res_ids)
  File "/data/build/odoo/addons/mass_mailing/wizard/mail_compose_message.py", line 40, in get_mail_values
    'mailing_domain': self.active_domain,
  File "<decorator-gen-178>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/mass_mailing_sms/models/mailing_mailing.py", line 68, in create
    return super(Mailing, self).create(values)
  File "<decorator-gen-150>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/mass_mailing/models/mailing.py", line 237, in create
    return super(MassMailing, self).create(values)
  File "<decorator-gen-108>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/models.py", line 3689, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'template_id' on model 'mailing.mailing'
```
Expected behavior: Send email

Video/Screenshot link (optional):

**Comment by JPML94** [comment]
Is this still happening to you?

**Comment by sswapnesh** [comment]
Yes, Reproduced at http://1255104-13-0-7c488b.runbot21.odoo.com/

**Comment by DerekFiyo** [comment]
We also do have this problem.

**Comment by DerekFiyo** [comment]
> Yes, Reproduced at http://1255104-13-0-7c488b.runbot21.odoo.com/

I have fixed it for now. But definitely there is something wrong with template id: 18.

**Comment by sviluppo-msa** [comment]
How did you fixed it ?

**Comment by DerekFiyo** [comment]
> How did you fixed it ?

1. You need to enable the debug mode.
2. Create a new standard email template.
3. Then open the ''Send mail'' window.
4. Click on the bug icon in the left top corner
5. Click on "edit action"
6. Edit the "default_template_id" within the "Context Value"
7. My new ID is 45. So my rule is: {'default_composition_mode': 'mass_mail', 'default_email_to': "{($object.email or '')|safe}", 'default_use_template': True, 'default_template_id': 45}

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/48011
