### ISSUE TITLE
[8.0] Setting language inactive while user has it as preffered language results in errors.

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4453]
Hi guys 

Found a problem in Odoo 8 with languages.
<b>How to reproduce?</b>
1. Install a second language (for example Dutch / Nederlands)
2. Set it as the preferred language for any user (for example Administrator)
3. Set the second language (Dutch / Nederlands) from active to inactive.
4. Open your preferrences again and you'll get an error.

# Error
```
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 927, in _call_kw
    records = getattr(request.session.model(model), method)(*args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 835, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/res/res_users.py", line 869, in read
    res = super(users_view, self).read(cr, uid, ids, other_fields, context=context, load=load)
  File "/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/res/res_users.py", line 295, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3102, in read
    result = BaseModel.read(records, fields, load=load)
  File "/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3145, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/odoo/odoo-server/openerp/models.py", line 5448, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/openerp/fields.py", line 711, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/openerp/fields.py", line 815, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/openerp/fields.py", line 771, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/openerp/fields.py", line 763, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/openerp/fields.py", line 430, in _compute_related
    record[self.name] = other[self.related[-1]]
  File "/odoo/odoo-server/openerp/models.py", line 5457, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/odoo/odoo-server/openerp/fields.py", line 727, in __set__
    value = self.convert_to_cache(value, record)
  File "/odoo/odoo-server/openerp/fields.py", line 1244, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.users.lang: u'nl_NL'
```
# Expected behaviour:
Either check if any user has the language set as his preferred language and show a message to the admin that the language cannot be set inactive or a custom notifications to the users. A third option could be to remove the languages that have been set to inactive from the list of choices.

**Comment by Yenthe666** [comment]
@rco-odoo I see you're assigned to this but I believe this was fixed a while ago in a pull request?
Just can't find this directly.

**Comment by rco-odoo** [comment]
@Yenthe666 I could no longer reproduce the bug. Apparently it has been fixed.

**Comment by Yenthe666** [comment]
@rco-odoo correct, has been patched in another pull! Thanks :+1:
