### ISSUE TITLE
[12.0] ChromeOS + Send by e-mail

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#44711]
**Impacted versions:**
12.0 (tested on runbot)

**Steps to reproduce:**
Using a chromebook
Sales > Sales order > Send by email

**Current behavior:**
Error:
```Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.

http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:252
Traceback:
Error: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.
    at getMatchedCSSRules (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:252:168)
    at Object.styleToClass (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:277:127)
    at Class._renderEdit (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:2557:597)
    at Class._render (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:1052:36)
    at http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:1049:1521
    at http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:802:681
    at fire (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:796:299)
    at Object.add [as done] (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:797:467)
    at Array.<anonymous> (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:802:649)
    at Function.each (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:625:767)```

**Expected behavior:**
Being able to send document/message by email from Odoo on  chromeOS

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by gregory-moka** [comment]
Already tested on runbot.

Same issue when trying to add follower on a document :
```Erreur:
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.

https://www.mokatourisme.fr/web/content/10897-281da6f/web_editor.assets_editor.js:252
Retraçage :
Error: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.
    at getMatchedCSSRules (https://www.mokatourisme.fr/web/content/10897-281da6f/web_editor.assets_editor.js:252:168)
    at Object.styleToClass (https://www.mokatourisme.fr/web/content/10897-281da6f/web_editor.assets_editor.js:277:127)
    at Class._renderEdit (https://www.mokatourisme.fr/web/content/10924-043939a/web.assets_backend.js:2434:597)
    at Class._render (https://www.mokatourisme.fr/web/content/10924-043939a/web.assets_backend.js:1054:36)
    at https://www.mokatourisme.fr/web/content/10924-043939a/web.assets_backend.js:1051:1521
    at https://www.mokatourisme.fr/web/content/10877-7523722/web.assets_common.js:802:681
    at fire (https://www.mokatourisme.fr/web/content/10877-7523722/web.assets_common.js:796:299)
    at Object.add [as done] (https://www.mokatourisme.fr/web/content/10877-7523722/web.assets_common.js:797:467)
    at Array.<anonymous> (https://www.mokatourisme.fr/web/content/10877-7523722/web.assets_common.js:802:649)
    at Function.each (https://www.mokatourisme.fr/web/content/10877-7523722/web.assets_common.js:625:767)```

**Comment by gregory-moka** [comment]
Already tested on runbot

Same issue when trying to add follower on a document : 

```Error:
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.

http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:252
Traceback:
Error: Failed to execute 'matches' on 'Element': 'event)"]' is not a valid selector.
    at getMatchedCSSRules (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:252:168)
    at Object.styleToClass (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1048-2d1a653/web_editor.assets_editor.js:277:127)
    at Class._renderEdit (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:2557:597)
    at Class._render (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:1052:36)
    at http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1046-3b60c30/web.assets_backend.js:1049:1521
    at http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:802:681
    at fire (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:796:299)
    at Object.add [as done] (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:797:467)
    at Array.<anonymous> (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:802:649)
    at Function.each (http://1136676-12-0-ed6ac9.runbot26.odoo.com/web/content/1045-2947862/web.assets_common.js:625:767)```

**Comment by pedrobaeza** [comment]
Can you please put Odoo in debug mode with assets for putting here the trace without minification and also indicate the browser and version?

**Comment by gregory-moka** [comment]
Google Chrome OS : Version 80.0.3987.76 (Build officiel) beta (64 bits)

**Comment by pedrobaeza** [comment]
That's not the browser version...

**Comment by Yenthe666** [comment]
`80.0.3987.87` works fine. Your version contains beta for Chrome, thats a bit odd.

**Comment by gregory-moka** [comment]
> `80.0.3987.87` works fine. Your version contains beta for Chrome, thats a bit odd.

Ok, my bad, beta verion is responsible of this issue.

**Comment by Yenthe666** [comment]
Imagined so, happy you've got it solved. :)

**Comment by gregory-moka** [comment]
Bug reproduced today, but, I found why why : 
It's not due to the chrome OS version, or Chrome version, it was due to the [adblock extension](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom).
I disabled it on my Odoo instances, and, it works fine.
