### ISSUE TITLE
Payment transaction cancel in payment provider, it's return cancel URL with pay_id none traceback.

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#4479]
Hello, 
   I try to pay via buckaroo payment provider. But once I come into buckaroo URL, I cancel this gateway (because I want to choose another payment gateway). 
   URL redirect to the <code>domainname.com/payment/buckaroo/cancel</code> with showing <pre>Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</pre>

Following trackback come into back end,

<pre>
2014-12-31 09:22:13,407 10769 INFO 2769d openerp.addons.payment_buckaroo.controllers.main: Buckaroo: entering form_feedback with post data {'ADD_RETURNDATA': u"{'return_url': '/shop/payment/validate'}",
 'BRQ_AMOUNT': u'79.00',
 'BRQ_CURRENCY': u'USD',
 'BRQ_INVOICENUMBER': u'SO009',
 'BRQ_MUTATIONTYPE': u'NotSet',
 'BRQ_SIGNATURE': u'b747744caeb97f86a85e5f86909efc333794456f',
 'BRQ_STATUSCODE': u'890',
 'BRQ_STATUSMESSAGE': u'Cancelled by user',
 'BRQ_TEST': u'true',
 'BRQ_TIMESTAMP': u'2014-12-31 10:22:07',
 'BRQ_TRANSACTIONS': u'B08BAC53683F4BC9B600769D6AB62AB0',
 'BRQ_WEBSITEKEY': u'xxxxxxxxxx'}
2014-12-31 09:22:13,409 10769 ERROR 2769d openerp.addons.payment_buckaroo.models.buckaroo: Buckaroo: received data with missing reference (SO009) or pay_id (None) or shashign (b747744caeb97f86a85e5f86909efc333794456f)
2014-12-31 09:22:13,467 10769 INFO 2769d werkzeug: 127.0.0.1 - - [31/Dec/2014 09:22:13] "POST /payment/buckaroo/cancel HTTP/1.1" 500 -
2014-12-31 09:22:13,590 10769 ERROR 2769d werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 1239, in __call__
    return self.dispatch(environ, start_response)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 1213, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 1380, in dispatch
    result = ir_http._dispatch()
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/website/models/ir_http.py", line 125, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/addons/base/ir/ir_http.py", line 130, in _dispatch
    return self._handle_exception(e)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/website/models/ir_http.py", line 201, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 618, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 636, in dispatch
    r = self._call_function(**self.params)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/payment_buckaroo/controllers/main.py", line 32, in buckaroo_return
    request.registry['payment.transaction'].form_feedback(request.cr, SUPERUSER_ID, post, 'buckaroo', context=request.context)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/website_sale/models/payment.py", line 19, in form_feedback
    res = super(PaymentTransaction, self).form_feedback(cr, uid, data, acquirer_name, context=context)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/payment/models/payment_acquirer.py", line 432, in form_feedback
    tx = getattr(self, tx_find_method_name)(cr, uid, data, context=context)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tiny/workspace/odoo/8.0-buckaroo-hash-issue-jpa/addons/payment_buckaroo/models/buckaroo.py", line 130, in _buckaroo_form_get_tx_from_data
    raise ValidationError(error_msg)
ValidationError: Buckaroo: received data with missing reference (SO009) or pay_id (None) or shashign (b747744caeb97f86a85e5f86909efc333794456f)
</pre>

Effected: 8.0, master
Reason/Solution:  In buckaroo module if reference, pay_id, shashign return none then rise the ValidationError. When rise this error make one cancel controller and redirect to that controller with proper message (payment transaction cancelled), optional give payment alternative method.

**Comment by Yenthe666** [comment]
Hi @imjaypatel,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
