### ISSUE TITLE
AttributeError: 'stock.picking' object has no attribute 'invoice_line'

### ISSUE THREAD

**Issue by aftabnaveed** [odoo/odoo#4493]
Even though I have the updated version of patch mentioned here  https://github.com/odoo/odoo/issues/3170 but I still get that error

Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 517, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 733, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 376, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/stock_account/wizard/stock_invoice_onshipping.py", line 89, in open_invoice
    invoice_ids = self.create_invoice(cr, uid, ids, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/stock_account/wizard/stock_invoice_onshipping.py", line 132, in create_invoice
    context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/stock_account/stock.py", line 250, in action_invoice_create
    invoices += self._invoice_create_line(cr, uid, moves, journal_id, type, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/additionnal_addons/renegade_furniture_shipping/stock.py", line 494, in _invoice_create_line
    res = super(stock_picking_shipping, self)._invoice_create_line(cr, uid, moves, journal_id, inv_type, context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/stock_account/stock.py", line 291, in _invoice_create_line
    invoice_id = self._create_invoice_from_picking(cr, uid, move.picking_id, invoice_vals, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/delivery/stock.py", line 126, in _create_invoice_from_picking
    invoice_line = self._prepare_shipping_invoice_line(cr, uid, picking, invoice, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/addons/delivery/stock.py", line 85, in _prepare_shipping_invoice_line
    for inv_line in invoice.invoice_line):
AttributeError: 'stock.picking' object has no attribute 'invoice_line'

**Comment by aftabnaveed** [comment]
I am closing the issue, sorry my code wasn't really updated, its not relevant any more.

**Comment by sanjaycoder123** [comment]
if self._context.get('taal_project_id'):
            project = self.taal_project_id.id
            vals.update({'project_id': self._context.get('project') })
        rec = super(stock_picking, self).create(vals)
        return rec
you can follow this one(sanjay.bhattacharjee1993@gmail.com)

**Comment by sanjaycoder123** [comment]
if self._context.get('taal_project_id'):
            vals.update({'project_id': self._context.get('taal_project_id')})
        rec = super(stock_picking, self).create(vals)
        return rec
 can follow this , hope it will be work.
