### ISSUE TITLE
PDF invoices do not generate in Romanian but work in English

### ISSUE THREAD

**Issue by calinbule** [odoo/odoo#45099]
Impacted versions: Community 13.0 (Bitnami stack)

Steps to reproduce: 
1) Deployed Odoo 13 Bitnami stack on a Google Compute Engine, from Cloud Marketplace
2) Installed wkhtmltopdf as per Bitnami instructions (https://docs.bitnami.com/aws/apps/odoo/configuration/install-wkhtmltopdf/)
3) Installed invoicing app
4) Added sample data from the settings menu
5) Created a new user with admin privileges
6) Activated Romanian language from settings
7) Chose Romanian as the preferred language from My Profile
8) Went to invoicing and filled in all information for Company Data, Invoice Layout and Payment Method, and then pressed Send Sample

Current behavior:
Instead of generating the invoice and preparing the email I get the following error:

Eroare:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 642, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/template_inheritance.py", line 222, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Elementul '<xpath expr="//span[@name='document_followers_text']">' nu poate fi localizat în vizualizarea părinte 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/models.py", line 1424, in load_views
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/models.py", line 1424, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/web/models/models.py", line 203, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/models.py", line 1504, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/models.py", line 1466, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 713, in read_combined
    arch_tree = self.apply_inheritance_specs(arch_tree, view_arch, parent_view['id'])
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-13.0.post20200115-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 592, in raise_view_error
    raise ValueError(message)
ValueError: Elementul '<xpath expr="//span[@name='document_followers_text']">' nu poate fi localizat în vizualizarea părinte 

Eroare context:
Vizualizare`mail.compose.message.form`
[view_id: 293, xml_id: mail.email_compose_message_wizard_form, model: mail.compose.message, parent_id: indisp.]

Expected behavior:
If I switch to English as the preferred language in My Profile it works fine.

**Comment by pedrobaeza** [comment]
This is a problem in the translation. Please see https://github.com/odoo/odoo/wiki/Translations for knowing how to fix it.

Closing this meanwhile as the solution is to translate it correctly.
