### ISSUE TITLE
[10.0] POS session miss opening date and can't be closed

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#45224]
Impacted versions: 10.0

Steps to reproduce:  (Not sure. This already happened two times after similar steps) I've ended a previous POS session that someone have left open for two days, I've done cash control and validate closing and post entries. Immediately after, I've by mistake opened a new session, done cash control and tried to validate closing and post entries

Current behavior: The POS session doesn't have opening date.  This can't be modified, and I can't validate closing and post entries. Got this error message :

```Python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 246, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 266, in action_pos_session_close
    self.with_context(ctx)._confirm_orders()
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_session.py", line 26, in _confirm_orders
    move = self.env['pos.order'].with_context(force_company=company_id)._create_account_move(session.start_at, session.name, int(journal_id), company_id)
  File "/usr/lib/python2.7/site-packages/odoo/addons/point_of_sale/models/pos_order.py", line 152, in _create_account_move
    date_tz_user = fields.Datetime.context_timestamp(self, fields.Datetime.from_string(dt))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1593, in context_timestamp
    assert isinstance(timestamp, datetime), 'Datetime instance expected'
AssertionError: Datetime instance expected
```

**Comment by Yenthe666** [comment]
@zeroheure sorry but Odoo 10 is no longer an officially supported version.
If I where you I'd run an SQL query to find out which record doesn't have a Datetime instance and update it through SQL before closing the session

**Comment by zeroheure** [comment]
@Yenthe666  thanks for the tip !

**Comment by kimasplund** [comment]
i ran in to the same problem. 

Any tip on how to do that?

**Comment by zeroheure** [comment]
@kimasplund read Yenthe message
