### ISSUE TITLE
[13] HR: Tracback on Opening Related employee record from Discuss page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45425]
Impacted versions: 13.0

http://1255104-13-0-7c488b.runbot21.odoo.com/web

Steps to reproduce: 

Click to Open Record
![image](https://user-images.githubusercontent.com/16624719/74552909-3f9cc880-4f7c-11ea-85e6-376b236c66d7.png)

Current behavior: 
Error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/hr/models/hr_employee.py", line 169, in get_formview_id
    self_sudo = self.with_user(access_uid)
  File "/data/build/odoo/odoo/models.py", line 5038, in with_user
    return self.with_env(self.env(user=user, su=False))
  File "/data/build/odoo/odoo/api.py", line 502, in __call__
    uid = self.uid if user is None else int(user)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

Expected behavior: Open form view of Related record

Video/Screenshot link (optional):

Original Message on Employee

![image](https://user-images.githubusercontent.com/16624719/74553049-87235480-4f7c-11ea-9562-84ecfba9d600.png)

**Comment by mitrasan22** [comment]
Anyone solved this issue?

**Comment by LucasLefevre** [comment]
Hello @mitrasan22 
It should be fixed since https://github.com/odoo/odoo/pull/47205
Do you still experience the bug?

**Comment by mitrasan22** [comment]
Yeahh,still,what can i do

**Comment by LucasLefevre** [comment]
@mitrasan22 
I cannot reproduce the issue on a standard V13 runbot install.
You can open a support ticket here: https://www.odoo.com/help
Please mention this issue in the ticket description to help the support's investiguation

**Comment by mitrasan22** [comment]
Yeah,solved now,thank you
