### ISSUE TITLE
[13] eLearning: Tracback on creating new Category from Content's Kanban view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45452]
Impacted versions: 13.0

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/16624719/74593250-64ae3b80-504f-11ea-876a-5f3f0a3f1a82.png)

Current behavior:
![image](https://user-images.githubusercontent.com/16624719/74593261-87d8eb00-504f-11ea-8a37-8c909a534833.png)

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 1670, in name_create
    record = self.create({self._rec_name: name})
  File "<decorator-gen-376>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/website_slides_survey/models/slide_slide.py", line 57, in create
    rec = super(Slide, self).create(values)
  File "<decorator-gen-363>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 322, in _model_create_single
    return create(self, arg)
  File "/data/build/odoo/addons/website_slides/models/slide_slide.py", line 385, in create
    channel = self.env['slide.channel'].browse(values['channel_id'])
KeyError: 'channel_id'
```
Expected behavior: No Error, Create new category or Block Creation from there

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/pull/45930/commits/2cab0f48264023803211ca14947950b7262cca91
