### ISSUE TITLE
[13.0] hr_expense: Error on Register Payment on Expense Report 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45536]
Impacted versions: 13.0

Steps to reproduce: 
![screenshot-1289328-13-0-18e112 runbot20 odoo com-2020 02 17-17_10_12](https://user-images.githubusercontent.com/16624719/74650764-68a1a100-51a8-11ea-834f-ff413bdf97f9.png)

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/api.py", line 753, in get
    value = self._data[field][record._ids[0]]
KeyError: <NewId 0x7f5010e18978>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/data/build/odoo/odoo/api.py", line 759, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.expense.sheet.register.payment.wizard(<NewId 0x7f5010e18978>,).show_partner_bank_account', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 6041, in onchange
    value = record[name]
  File "/data/build/odoo/odoo/models.py", line 5588, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1020, in __get__
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/odoo/models.py", line 3902, in _compute_field_value
    getattr(self, field.compute)()
  File "/data/build/odoo/addons/hr_expense/wizard/hr_expense_sheet_register_payment.py", line 67, in _compute_show_partner_bank
    payment.require_partner_bank_account = payment.state == 'draft' and payment.payment_method_id.code in self.env['account.payment']._get_method_codes_needing_bank_account()
AttributeError: 'hr.expense.sheet.register.payment.wizard' object has no attribute 'state'
```

Expected behavior: Open wizard to Register Payment
![screenshot-1289328-13-0-18e112 runbot20 odoo com-2020 02 17-17_12_27](https://user-images.githubusercontent.com/16624719/74650907-b4544a80-51a8-11ea-9230-becb9a751890.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/45761 by @oco-odoo

**Comment by elsayedmohamediraky** [comment]
Please , if you find solve this problem , say my how to solve ..

**Comment by sswapnesh** [comment]
> Please , if you find solve this problem , say my how to solve ..

Update your Odoo source code (Or apply this  https://github.com/odoo/odoo/pull/45676/commits/3890bcd7373ffee1a39e1ea7f447ca915833891e patch locally)
