### ISSUE TITLE
Odoo: official certificates broken

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45641]
Impacted versions: Odoo.com

Steps to reproduce:
1. Login to Odoo.com with an account that has passed an exam
2. Try to download the certificate

Current behavior:
Big traceback:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 804, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/13.0/addons/survey/controllers/main.py", line 553, in survey_get_certification
    report = report_sudo.render_qweb_pdf([succeeded_attempt.id], data={'report_type': 'pdf'})[0]
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 718, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 758, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 541, in render_template
    return view_obj.render_template(template, values)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 1154, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/src/odoo/13.0/addons/website/models/ir_ui_view.py", line 337, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/13.0/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 1162, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-53>", line 2, in compile
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 277, in compile
    element, document = self.get_template(template, options)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 363, in get_template
    path = options['last_path_node']
KeyError: 'last_path_node'

Expected behavior:
Certificate is downloaded.

**Comment by Yenthe666** [comment]
OPW `2199165`

**Comment by rrahir** [comment]
@Yenthe666 Could you give it a try ?

**Comment by Yenthe666** [comment]
@rrahir yep fixed! The certificate prints very ugly though. I've already reported that 3 times too but nobody seems to care. Maybe this can be fixed in the meanwhile too? After all it costs 250 euro.

**Comment by aghiles98** [comment]
how you had resolved it?

**Comment by Yenthe666** [comment]
Odoo has fixed it in a commit so you just have to update your local instance. Odoo.com is fixed.
