### ISSUE TITLE
Problem installing on Ubuntu raring

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#4585]
Hi, I already installed all requirements from .txt file, i'm on a virtualenv btw.

But when I run setupy.py it throws me this eror:

Installed /opt/odoo/virtualenv/master/lib/python2.7/site-packages/odoo-8.0-py2.7.egg
Processing dependencies for odoo==8.0
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    **py2exe_options()
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 376, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 600, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 651, in install_item
    self.process_distribution(spec, dist, deps)
  File "/opt/odoo/virtualenv/master/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 710, in process_distribution
    % e.args
TypeError: not enough arguments for format string

Any ideas?

Thanks in advance!

**Comment by mart-e** [comment]
Hello,

You are probably using a too old version setuptools.
By the way ubuntu raring is no longer supported.

**Comment by kkoci** [comment]
Ya I know about the support, Ok, let me upgrade setuptools,. thank you.

**Comment by kkoci** [comment]
Solved, It was the setuptools version, thank you very much!

**Comment by mart-e** [comment]
good to know, thanks for the feedback
