### ISSUE TITLE
Odoo is not compatible with werkzeug >= 1.0

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#45914]
Impacted versions: 11, 12, 13, master

Steps to reproduce:

```console
$ python3 -m venv /tmp/odooenv
$ /tmp/odooenv/bin/python -m pip install -U pip wheel
$ /tmp/odooenv/bin/python -m pip install -e src/odoo
$ /tmp/odooenv/bin/python -m pip list | grep -i werkzeug
Werkzeug          1.0.0
$ /tmp/odooenv/bin/odoo
Traceback (most recent call last):
  File "/tmp/odooenv/bin/odoo", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "src/odoo/setup/odoo", line 5, in <module>
    import odoo
  File "src/odoo/odoo/__init__.py", line 117, in <module>
    from . import service
  File "src/odoo/odoo/service/__init__.py", line 7, in <module>
    from . import wsgi_server
  File "src/odoo/odoo/service/wsgi_server.py", line 25, in <module>
    import werkzeug.contrib.fixers
ModuleNotFoundError: No module named 'werkzeug.contrib'
```

**Comment by Yenthe666** [comment]
@JKE-be I summon you 📦

**Comment by Yenthe666** [comment]
@sbidoul also see https://github.com/odoo/odoo/pull/45931

**Comment by xmo-odoo** [comment]
Various changes have been implemented in master (and possibly 13 for the older ones by @Julien00859). You'll have to ask @odony how open he is to getting these backported to 13 let alone older releases.

However the point is moot because as of today there still isn't an official release of pallets/secure-cookie, which means we can't support Werkzeug 1.0 without vendoring or building our own version of sessions.

That werkzeug.contrib was moved out also generates the issue that we'll need to install secure-cookie (when it eventually gets a release) IFF werkzeug >= 1.0, but we don't want to install it if werkzeug < 1.0, and while I know `requirements.txt` can make dependencies conditional on the Python version I've no idea whether it's possible to make it conditional on the version of an other dependency.

**Comment by sbidoul** [comment]
No problem. I had not found an issue mentioning this before so I thought it was worth opening.

**Comment by xmo-odoo** [comment]
> No problem. I had not found an issue mentioning this before so I thought it was worth opening.

@sbidoul no apology needed or anything, #45931 literally didn't exist when you created this one, I set out check out the few remaining warnings less than an hour ago.

**Comment by Yenthe666** [comment]
@xmo-odoo hey I'm curious.. secure-cookies looks like a pretty dead repository. Has Odoo considered contributing to it to get an official release actually?

**Comment by xmo-odoo** [comment]
> secure-cookies looks like a pretty dead repository.

@Yenthe666 its a straight move of werkzeug.contrib.sessions and [that was a very low-traffic section of werkzeug even before it was moved out](https://github.com/pallets/werkzeug/commits/0f341ea8e5dfb00a6866cf4cbc798c126e063d84/werkzeug/contrib/sessions.py) so I'm not really surprised there would be no activity after it was moved out, especially since it's yet to be usable by third parties at all.

> Has Odoo considered contributing to it to get an official release actually?

See pallets/secure-cookie#1

**Comment by Yenthe666** [comment]
Awesome. Thanks for the extra info and for asking about contributions @xmo-odoo. Great move.

**Comment by davispuh** [comment]
Why this issue was closed? It's still not compatible, not even `master` branch.
On ArchLinux current version of `python-werkzeug` is 1.0 so currently Odoo can't be easily installed.

**Comment by xmo-odoo** [comment]
> Why this issue was closed?

Because as noted in the comments it's redundant with  #45931 and at the time there was literally no way to fix it since `secure-cookie` hadn't had a release yet.

> On ArchLinux

There's your problem.

**Comment by Elkasitu** [comment]
@davispuh Arch is not officially supported by Odoo, it's up to whoever maintains the Odoo AUR package to fix / workaround this.

If you want to run Odoo in Arch you should use pip for dependency management and maybe even a virtualenv

**Comment by davispuh** [comment]
> > On ArchLinux
> 
> There's your problem. [...]

Nope, it's not a problem :P I have Odoo working there fine by downgrading `werkzeug` but wrote here because actual issue is that Odoo doesn't support `1.0`
And I see that PR, great!
