### ISSUE TITLE
[8.0] Crash when using filter in the JS bank statement interface with unaccent=True

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4615]
Here are the steps to reproduce the bug on an up-to-date Odoo 8.0:
1) Create a new DB and install the account module
2) Activate the unaccent feature
sudo apt-get install postgresql-contrib-9.3
psql <database> -c "CREATE EXTENSION "unaccent";
in the config file of the odoo server, set unaccent = True and restart odoo
3) Create a new bank statement with 1 bank statement line (or use the bank statement of the demo data)
4) click on the "Reconcile button"
5) in the special JS interface of the bank statement, put your cursor in the box that has "Filters" written inside it and type a few letters => you get a crash:

2015-01-09 13:43:17,549 17766 ERROR o8_bugunaccent openerp.sql_db: Programming error: function unaccent(date) does not exist
LINE 1: ...e"."id" IS NULL))  AND  (FALSE  OR  (FALSE  OR  ((unaccent("...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
, in query SELECT "account_move_line".id FROM "account_move_line" WHERE ((((("account_move_line"."reconcile_id" IS NULL   AND  ("account_move_line"."state" = %s))  AND  ("account_move_line"."account_id" in (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)))  AND  ("account_move_line"."partner_id" = %s))  AND  (("account_move_line"."id" not in (%s,%s)) OR "account_move_line"."id" IS NULL))  AND  (FALSE  OR  (FALSE  OR  ((unaccent("account_move_line"."date_maturity")::text like unaccent(%s))  OR  (unaccent("account_move_line"."name")::text ilike unaccent(%s)))))) ORDER BY "account_move_line"."date_maturity" asc,"account_move_line"."id" asc  limit 6
2015-01-09 13:43:17,549 17766 ERROR o8_bugunaccent openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 545, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 298, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 761, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 394, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/account/account_bank_statement.py", line 604, in get_move_lines_for_reconciliation_by_statement_line_id
    return self.get_move_lines_for_reconciliation(cr, uid, st_line, excluded_ids, str, offset, limit, count, additional_domain, context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/account/account_bank_statement.py", line 651, in get_move_lines_for_reconciliation
    line_ids = mv_line_pool.search(cr, uid, domain, offset=actual_offset, limit=limit, order="date_maturity asc, id asc", context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/account/account_move_line.py", line 758, in search
    return super(account_move_line, self).search(cr, uid, args, offset, limit, order, context, count)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 1653, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 4587, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/alexis/new_boite/dev/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: function unaccent(date) does not exist
LINE 1: ...e"."id" IS NULL))  AND  (FALSE  OR  (FALSE  OR  ((unaccent("...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

This crash is 100% reproductible.

**Comment by alexis-via** [comment]
I confirm that the patch merged in v8 fixes the bug. Thank you very much @rco-odoo for the fix !
