### ISSUE TITLE
[8.0] TypeError: notify() got an unexpected keyword argument 'ids'

### ISSUE THREAD

**Issue by tl06799** [odoo/odoo#4619]
After update with git pull, appears an error trying to delete a lead or an opportunity:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 545, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 298, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 761, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 394, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 445, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/addons/web_live/abstract.py", line 45, in unlink
    self.notify(ids=[x.id for x in self])
  File "/opt/odoo/odoo-server/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: notify() got an unexpected keyword argument 'ids'

**Comment by xmo-odoo** [comment]
You're not calling `notify` correctly, but I know neither what `web_live` is nor how `notify` is defined. You should check that out.
