### ISSUE TITLE
[13] Survey: Traceback on Datetime type Question

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#46282]
Impacted versions: 13.0

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/16624719/75270946-6df29180-5821-11ea-8c82-429c68f3332f.png)

Current behavior: On Bad Input
```

Error:
Uncaught TypeError: Cannot read property 'format' of undefined

http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:2930
Traceback:
TypeError: Cannot read property 'format' of undefined
    at TempusDominusBootstrap4._setValue (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:2930:288)
    at TempusDominusBootstrap4._change (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:2931:228)
    at Function._jQueryHandleThis (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:3207:73)
    at jQuery.fn.init._jQueryInterface [as datetimepicker] (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:3207:223)
    at HTMLInputElement.<anonymous> (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:3210:42)
    at HTMLDocument.dispatch (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:925:447)
    at HTMLDocument.elemData.handle (http://1499710-13-0-b77d2b.runbot23.odoo.com/web/content/1573-77d4803/1/web.assets_common_lazy.js:911:166)
```
![Screenshot from 2020-02-25 22-59-29](https://user-images.githubusercontent.com/16624719/75271635-857e4a00-5822-11ea-9e46-0a725987c11e.png)

Expected behavior: No traceback / Able to select Datetime

Video/Screenshot link (optional):

**Comment by C3POdoo** [comment]
Dear @sswapnesh,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
