### ISSUE TITLE
12.0: TypeError: _notify_prepare_template_context() got an unexpected keyword argument 'model_description'

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#46713]
Impacted versions:
12.0
Steps to reproduce:
Creating a task with a  diffirent user 

Current behavior:

```
2020-03-03 10:30:26,418 19620 INFO DATABASE werkzeug: 127.0.0.1 - - [03/Mar/2020 10:30:26] "POST /longpolling/poll HTTP/1.1" 200 - 21 0.014 50.084
2020-03-03 10:30:26,642 19620 DEBUG DATABASE odoo.modules.registry: Multiprocess signaling check: [Registry - 351 -> 351] [Cache - 115638 -> 115638] 
> /opt/odoo/odoo12/addons/mail/models/res_partner.py(107)_notify()
-> base_template_ctx = self._notify_prepare_template_context(message, record, model_description=model_description)
(Pdb) c

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.6/bdb.py", line 261, in set_continue
    sys.settrace(None)

2020-03-03 10:30:44,736 19620 ERROR DATABASE odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-521>", line 2, in generate_tasks
  File "/opt/odoo/odoo12/odoo/api.py", line 382, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo12/odoo/api.py", line 382, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/custom/10/tecnibo/tecnibo_project/models/project_phase.py", line 202, in generate_tasks
    created_task = self.env['project.task'].create(task)
  File "<decorator-gen-529>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/custom/10/tecnibo/project_forecast_update/models/project.py", line 34, in create
    res = super(ProjectTask, self).create(vals)
  File "<decorator-gen-519>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/custom/10/tecnibo/tecnibo_project/models/project_task.py", line 114, in create
    res = super(ProjectTask, self).create(vals)
  File "<decorator-gen-425>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/custom/10/tecnibo/tecnibo_hr/models/project_task.py", line 18, in create
    res = super(ProjectTask, self).create(vals)
  File "<decorator-gen-415>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/custom/10/tecnibo/project_update/models/project.py", line 202, in create
    res = super(ProjectTask, self).create(vals)
  File "<decorator-gen-324>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/odoo12/addons/project/models/project.py", line 694, in create
    task = super(Task, self.with_context(context)).create(vals)
  File "<decorator-gen-127>", line 2, in create
  File "/opt/odoo/odoo12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 286, in create
    thread._message_auto_subscribe(create_values)
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 2449, in _message_auto_subscribe
    self.with_context(lang=lang)._message_auto_subscribe_notify(pids, template)
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 2384, in _message_auto_subscribe_notify
    model_description=model_description,
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 2195, in message_notify
    return self.env['mail.thread'].message_post(**msg_values)
  File "/opt/odoo/odoo12/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 2079, in message_post
    self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/odoo12/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
    return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/odoo12/addons/mail/models/mail_thread.py", line 2101, in _message_post_after_hook
    mail_auto_delete=mail_auto_delete,
  File "/opt/odoo/odoo12/addons/mail/models/mail_message.py", line 1070, in _notify
    model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/enterprise/enterprise-12.0/ocn_client/models/mail_message.py", line 18, in _notify_recipients
    super(MailMessage, self)._notify_recipients(rdata, record, msg_vals, **kwargs)
  File "/opt/odoo/odoo12/addons/mail/models/mail_message.py", line 1150, in _notify_recipients
    self.env['res.partner']._notify(self, partner_email_rdata, record, force_send=force_send, send_after_commit=send_after_commit, model_description=model_description, mail_auto_delete=mail_auto_delete)
  File "/opt/odoo/odoo12/addons/mail/models/res_partner.py", line 107, in _notify
    base_template_ctx = self._notify_prepare_template_context(message, record, model_description=model_description)
TypeError: _notify_prepare_template_context() got an unexpected keyword argument 'model_description'
2020-03-03 10:30:44,742 19620 INFO DATABASE werkzeug: 127.0.0.1 - - [03/Mar/2020 10:30:44] "POST /web/dataset/call_button HTTP/1.1" 200 - 421 0.832 167.978
2020-03-03 10:30:48,757 19620 DEBUG ? odoo.service.server: cron0 polling for jobs 
2020-03-03 10:30:51,757 19620 DEBUG ? odoo.service.server: cron1 polling for jobs 
2020-03-03 10:31:16,725 19620 INFO DATABASE werkzeug: 127.0.0.1 - - [03/Mar/2020 10:31:16] "POST /longpolling/poll HTTP/1.1" 200 - 21 0.018 50.067
2020-03-03 10:31:16,753 19620 DEBUG DATABASE odoo.modules.registry: Multiprocess signaling check: [Registry - 351 -> 351] [Cache - 115638 -> 115638] 
2020-03-03 10:31:48,822 19620 DEBUG ? odoo.service.server: cron0 polling for jobs 
2020-03-03 10:31:52,822 19620 DEBUG ? odoo.service.server: cron1 polling for jobs 
2020-03-03 10:32:06,814 19620 INFO DATABASE werkzeug: 127.0.0.1 - - [03/Mar/2020 10:32:06] "POST /longpolling/poll HTTP/1.1" 200 - 21 0.015 50.050
2020-03-03 10:32:06,838 19620 DEBUG DATABASE odoo.modules.registry: Multiprocess signaling check: [Registry - 351 -> 351] [Cache - 115638 -> 115638]  
```

**Comment by Yenthe666** [comment]
Please add more information on how to reproduce this. This seems to work fine on the latest Odoo 12.

**Comment by filwu8** [comment]
can't sent email in helpdesk （ odoo 14）

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
    self._cr.precommit.run()
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1152, in run
    func()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 553, in _finalize_tracking
    record._message_track_post_template(changes)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 587, in _message_track_post_template
    self._fallback_lang().message_post_with_template(template.id, **post_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mass_mailing/models/mail_thread.py", line 37, in message_post_with_template
    return super(MailThread, no_massmail).message_post_with_template(template_id, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1989, in message_post_with_template
    return composer.send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/mail_compose_message.py", line 20, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/coupon/models/mail_compose_message.py", line 15, in send_mail
    return super().send_mail(**kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 264, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1915, in message_post
    self._notify_thread(new_message, values, **notif_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sms/models/mail_thread.py", line 238, in _notify_thread
    recipients_data = super(MailThread, self)._notify_thread(message, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2164, in _notify_thread
    self._notify_record_by_email(message, rdata, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2232, in _notify_record_by_email
    recipients_groups_data = self._notify_classify_recipients(partners_data, model_name, msg_vals=msg_vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2624, in _notify_classify_recipients
    groups = self._notify_get_groups(msg_vals=local_msg_vals)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _notify_get_groups() got an unexpected keyword argument 'msg_vals'
