### ISSUE TITLE
res.partner _compute_email_formatted() fails for special char "ø" (utf-8 problem)

### ISSUE THREAD

**Issue by fractalf** [odoo/odoo#46759]
Impacted versions:
12.0

Steps to reproduce:

```py
import odoorpc
odoo = odoorpc.ODOO(xx, protocol=xx, port=xx])
...
Model = odoo.env['res.partner']
ids = Model.search([
    ('id', '=', 1337)
], limit=1)

recs = Model.browse(ids)
print('recs', recs)

```

Not sure why this function is called in res.partner, but it does using odoorpc browse.

```sh
2020-03-03 14:15:39,653 1 ERROR ff odoo.http: ascii
xøxxxxx@gmail.com
2
3
ordinal not in range(128) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 5628

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(5628,).email_formatted', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 120, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 39, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 153, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 160, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 149, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 967, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_partner.py", line 384, in _compute_email_formatted
    partner.email_formatted = formataddr((partner.name or u"False", partner.email or u"False"))
  File "/usr/lib/python3.5/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 2: ordinal not in range(128)
> /usr/lib/python3.5/email/utils.py(91)formataddr()
-> address.encode('ascii')

```

Overriding this method solves the problem, but this probably should be fixed?

https://github.com/odoo/odoo/blob/163574641f7470f6bdc40e8aeafd055169305fb6/odoo/addons/base/models/res_partner.py#L364

**Comment by pedrobaeza** [comment]
Line references seems different from the line you link. Do you have latest code? Can you do the test against runbot?

**Comment by mah007** [comment]
i have the same problem and it stop the pos from loading

**Comment by fractalf** [comment]
@pedrobaeza I'm not sure which version of 12 I'm running, but one thats around 1 year old. However, I extended the method with the latest code (pasted above) to debug the case, and it still happens. This could be an issue with **odoorpc** however.

**Comment by pedrobaeza** [comment]
Please try odoorpc against a runbot instance.

**Comment by mah007** [comment]
it is on odoo 13 
  File "/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(1,).email_formatted', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/addons/web/controllers/main.py", line 110, in wrap
    return f(*args, **kwargs)
  File "/odoo/addons/web/controllers/main.py", line 1905, in index
    return self.base(data, token)
  File "/odoo/addons/web/controllers/main.py", line 1857, in base
    export_data = records.export_data(field_names).get('datas',[])
  File "/odoo/odoo/models.py", line 898, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/odoo/odoo/models.py", line 835, in _export_rows
    value = record[name]
  File "/odoo/odoo/models.py", line 5588, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo/fields.py", line 1020, in __get__
    self.compute_value(recs)
  File "/odoo/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo/models.py", line 3902, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo/addons/base/models/res_partner.py", line 364, in _compute_email_formatted
    partner.email_formatted = tools.formataddr((partner.name or u"False", partner.email or u"False"))
  File "/odoo/odoo/tools/mail.py", line 550, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-19: ordinal not in range(128)
2020-03-05 12:16:06,763 1613 INFO pos werkzeug: 105.37.163.93 - - [05/Mar/2020 12:16:06] "POST /web/export/xlsx HTTP/1.0" 500 - 7 0.007 0.021
2020-03-05 12:16:07,410 1663 INFO pos werkzeug: 51.36.61.200 - - [05/Mar/2020 12:16:07] "GET /web/image?model=product.product&field=image_128&id=601 HTTP/1.0" 200 - 27 0.024 0.024

**Comment by C3POdoo** [comment]
Dear @fractalf,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._

**Comment by vava-odoo** [comment]
> But the problem still exists!

@bosd in recent versions (>=14)?

**Comment by bosd** [comment]
@vava-odoo Yes, It happens on Odoo.sh version 15.0+e (Enterprise Edition).
An client ran into the problem with the "°" character.
