### ISSUE TITLE
When using the top-right "fa-" icon buttons on the partner form, active_id is not updated

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4689]
Here is the scenario to reproduce the bug:

1) Login to runbot v8 as admin user
2) Go to Sales > Customers and select Agrolait
3) Clic on the "Sales" icon at the top right
4) Clic on "Create" to create a new quotation
5) In the delivery method field, you have the choice between 3 different delivery methods
=> it works well
6) Logout and login as demo user
7) Run the same scenario as above : go to the form view of Agrolait, click on the "Sales" icon and then clic on "Create". On the Delivery method field, clic on the arrow to see the list
 of possible delivery methods and you get this error:

```
AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: sale.order, Operation: read)
```

Here is the full backtrace:
```
2015-01-14 09:26:09,849 8481 ERROR o8_test1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 562, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 299, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 791, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 395, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 1734, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 1747, in _name_search
    res = self.name_get(cr, access_rights_uid, ids, context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/addons/delivery/delivery.py", line 44, in name_get
    currency = order.pricelist_id.currency_id.name or ''
  File "/home/alexis/new_boite/dev/odoo/openerp/fields.py", line 780, in __get__
    return record._cache[self]
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 5834, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/alexis/new_boite/dev/odoo/openerp/fields.py", line 53, in get
    raise self.exception
AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: sale.order, Operation: read)')
```

Rapid code analysis:
It crashes when trying to get the cache of the field "origin" of the object "sale.order"... very strange.

Workaround:
In odoo/addons/delivery/delivery.py line 34, comment out the code of the name_get() method for the object delivery.carrier.

**Comment by alexis-via** [comment]
I found this bug this morning after upgrading from a v8 codebase dated around december 1st 2014 to a v8 codebase dated January 13th 2015 evening. This bug was not present before this update of the code.

**Comment by alexis-via** [comment]
Here is a deeper analysis of the issue:
The error is caused by the ir.rule for the group "See own leads". If you add the demo user to the group "See all leads", the error disappears.

The root of the problem is the following: on step 2, when you select the customer "Agrolait", it has "active_id" = 7, because Agrolait has ID 7 in res.partner. Then, on step 4, when you create a new sale order, it will have in the context "order_id: 7" (that's the caused of the bug !). So it will execute the name_get of delivery.carrier with "order_id: 7" in the context. But, in the demo data, the sale.order that has ID 7 has user_id=1 (= Administrator), so the record rule for the group "see own leads" will prevent the demo user from accessing it.

So, we now need to know why it has order_id = ID of the partner (instead of False) on step 4.

**Comment by alexis-via** [comment]
In odoo/addons/delivery/delivery_view.xml, in the inherit of the sale.order form view, we have:
```
<field name="carrier_id" context="{'order_id':active_id or False}" class="oe_inline"/>
```
That's the piece of code that sets 'order_id' in the context from the active_id.

So the root cause of the problem is that, on step 2, active_id = 7 (ID of Agrolait in res.partner), and, on step 4, we still have active_id = 7 (should be False).

**Comment by alexis-via** [comment]
On step 3, the URL is:
```
http://localhost:8069/web#page=0&limit=80&view_type=list&model=sale.order&action=412&active_id=7
```
it contains active_id = 7, but it shouldn't.
On step 4, the URL is:
```
http://localhost:8069/web#view_type=form&model=sale.order&action=412&active_id=7
```
same issue: it contains active_id = 7, but it shouldn't.

**Comment by alexis-via** [comment]
This bug is also present in the master branch.

**Comment by alexis-via** [comment]
This bug doesn't happend anymore with an up-to-date v8.... but i don't know which commit fixed the issue. I close this bug.
