### ISSUE TITLE
Move odoo12 to another server errors occured when i confirm the sales order

### ISSUE THREAD

**Issue by molandtoxx** [odoo/odoo#47046]
Impacted versions:odoo12 

Steps to reproduce: when i confirm the sales order

Current behavior:psycopg2.ProgrammingError: relation "procurement_group_id_seq" does not exist
LINE 1: ... "name", "partner_id", "sale_id") VALUES (nextval('procureme...
                                                             ^

Expected behavior:

Video/Screenshot link (optional):
![error1](https://user-images.githubusercontent.com/19324917/76045818-22668300-5f99-11ea-8885-5368cd2fecf6.png)
![error2](https://user-images.githubusercontent.com/19324917/76045823-25fa0a00-5f99-11ea-9a4f-110e09c0e7af.png)
### The error code:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/xiangjiangfood/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/xiangjiangfood/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/data/xiangjiangfood/odoo12-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/data/xiangjiangfood/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/data/xiangjiangfood/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/xiangjiangfood/odoo12-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/xiangjiangfood/odoo12-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/xiangjiangfood/odoo12-server/addons/sale_management/models/sale_order.py", line 116, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/data/xiangjiangfood/odoo12-server/addons/sale/models/sale.py", line 746, in action_confirm
    self._action_confirm()
  File "/data/xiangjiangfood/odoo12-server/addons/sale_stock/models/sale_order.py", line 79, in _action_confirm
    order.order_line._action_launch_stock_rule()
  File "/data/xiangjiangfood/odoo12-server/addons/procurement_jit/sale.py", line 12, in _action_launch_stock_rule
    res = super(SaleOrderLine, self)._action_launch_stock_rule()
  File "/data/xiangjiangfood/odoo12-server/addons/sale_stock/models/sale_order.py", line 385, in _action_launch_stock_rule
    'partner_id': line.order_id.partner_shipping_id.id,
  File "<decorator-gen-3>", line 2, in create
  File "/data/xiangjiangfood/odoo12-server/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/data/xiangjiangfood/odoo12-server/odoo/models.py", line 3563, in create
    records = self._create(data_list)
  File "/data/xiangjiangfood/odoo12-server/odoo/models.py", line 3663, in _create
    cr.execute(query, params)
  File "/data/xiangjiangfood/odoo12-server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/data/xiangjiangfood/odoo12-server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "procurement_group_id_seq" does not exist
LINE 1: ... "name", "partner_id", "sale_id") VALUES (nextval('procureme...
                                                             ^
```
### The postgresql dump manifest
```
{
    "odoo_dump": "1",
    "db_name": "odoo12",
    "version": "12.0",
    "version_info": [
        12,
        0,
        0,
        "final",
        0,
        ""
    ],
    "major_version": "12.0",
    "pg_version": "10.0",
    "modules": {
        "vouchers_pos": "12.0.1.0.0",
        "universal_discount": "12.0.1.1.1",
        "resource": "12.0.1.1",
        "pos_discount": "12.0.1.0",
        "disable_odoo_online": "12.0.1.0.0",
        "web_editor": "12.0.1.0",
        "sale_stock": "12.0.1.0",
        "pos_sale": "12.0.1.0",
        "point_of_sale": "12.0.1.0.1",
        "excel_import_export_demo": "12.0.1.0.0",
        "excel_import_export": "12.0.1.0.4",
        "om_mass_confirm_cancel": "12.0.1.0.0",
        "mass_editing": "12.0.1.0.0",
        "web": "12.0.1.0",
        "stock_dropshipping": "12.0.1.0",
        "stock_mts_mto_rule": "12.0.1.0.1",
        "procurement_jit": "12.0.1.0",
        "purchase_stock": "12.0.1.2",
        "stock_account": "12.0.1.1",
        "stock": "12.0.1.1",
        "sale_crm": "12.0.1.0",
        "hr_expense": "12.0.2.0",
        "om_account_accountant": "12.0.1.0.0",
        "account_fiscal_year": "12.0.1.0.0",
        "account_voucher": "12.0.1.0",
        "account_financial_report": "12.0.1.2.2",
        "date_range": "12.0.1.0.0",
        "om_account_budget": "12.0.1.0",
        "om_account_asset": "12.0.1.0",
        "accounting_pdf_reports": "12.0.1.0.0",
        "remove_odoo_enterprise": "12.0.1.0.0",
        "web_tour": "12.0.0.1",
        "portal": "12.0.1.0",
        "analytic": "12.0.1.1",
        "product_template_tags": "12.0.1.1.0",
        "sale_promotion": "12.0.1.0.1",
        "product_price_update_advanced": "12.0.1.0.0",
        "partner_deduplicate_acl": "12.0.1.0.0",
        "membership": "12.0.1.0",
        "report_xlsx": "12.0.1.0.2",
        "hide_cost_price": "12.0.1.0.0",
        "base_vat": "12.0.1.0",
        "base_user_role": "12.0.1.0.1",
        "sale_expense": "12.0.1.0",
        "hr_contract": "12.0.1.0",
        "hr": "12.0.1.1",
        "l10n_cn_standard_latest": "12.0.12.19.11.13",
        "fl_so_po_multi_products": "12.0.1.0.0",
        "app_odoo_customize": "12.0.13.19.09.14",
        "phone_validation": "12.0.1.0",
        "base": "12.0.1.3",
        "bus": "12.0.1.0",
        "calendar_sms": "12.0.1.0",
        "l10n_cn_standard": "12.0.2.0",
        "web_diagram": "12.0.2.0",
        "decimal_precision": "12.0.0.1",
        "http_routing": "12.0.1.0",
        "base_setup": "12.0.1.0",
        "web_kanban_gauge": "12.0.1.0",
        "sale_purchase": "12.0.1.0",
        "utm": "12.0.1.0",
        "contacts": "12.0.1.0",
        "account": "12.0.1.1",
        "enterprise_backend_theme": "12.0.0.1",
        "snailmail": "12.0.0.1",
        "sale": "12.0.1.1",
        "sale_management": "12.0.1.0",
        "mail": "12.0.1.0",
        "fetchmail": "12.0.1.0",
        "purchase": "12.0.1.2",
        "barcodes": "12.0.2.0",
        "uom": "12.0.1.0",
        "web_settings_dashboard": "12.0.1.0",
        "auth_signup": "12.0.1.0",
        "mail_bot": "12.0.1.0",
        "snailmail_account": "12.0.0.1",
        "payment": "12.0.1.0",
        "crm": "12.0.1.0",
        "account_facturx": "12.0.1.0",
        "sales_team": "12.0.1.0",
        "account_bank_statement_import": "12.0.1.0",
        "product": "12.0.1.2",
        "digest": "12.0.1.0",
        "l10n_multilang": "12.0.1.1",
        "web_responsive": "12.0.1.3.4",
        "sms": "12.0.1.0",
        "calendar": "12.0.1.0",
        "payment_transfer": "12.0.1.0",
        "l10n_cn": "12.0.1.8",
        "l10n_cn_small_business": "12.0.1.8",
        "base_import": "12.0.1.0",
        "iap": "12.0.1.0"
    }
}
```

**Comment by pedrobaeza** [comment]
This is a bad move that has not restored correctly the backup, or something different with the code in both sides, but nothing to do with Odoo itself, so closing.
