### ISSUE TITLE
[13.0] incorrect padding error on res.config.settings when translatable field is added

### ISSUE THREAD

**Issue by zachwaite** [odoo/odoo#47132]
Impacted versions:
13.0

Steps to reproduce:

1. Install website
2. Load second language
3. Install a custom module that extends res.config.settings with a translatable field (example below)
4. Navigate to Settings and use the `EN` icon in the translatable field to change the translation
5. Attempt to save

Current behavior:
1. If you just attempt the translation, then save, this user error is produced:
```This file could not be decoded as an image file. Please try with a different file.```

2. If you also change the favicon, a server error is produced, suggesting a binary file does not have correct padding.

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/ASE/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/ASE/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/ASE/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/ASE/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/ASE/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/ASE/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/ASE/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/ASE/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/ASE/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/ASE/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/ASE/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/ASE/odoo/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/odoo/ASE/odoo/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/ASE/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/ASE/odoo/odoo/models.py", line 3762, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/ASE/odoo/odoo/fields.py", line 1116, in determine_inverse
    self.inverse(records)
  File "/home/odoo/ASE/odoo/odoo/fields.py", line 594, in _inverse_related
    target[field.name] = record_value[record]
  File "/home/odoo/ASE/odoo/odoo/models.py", line 5606, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo/ASE/odoo/odoo/fields.py", line 1081, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/ASE/odoo/addons/website/models/website.py", line 165, in write
    result = super(Website, self - public_user_to_change_websites).write(values)
  File "/home/odoo/ASE/odoo/odoo/models.py", line 3529, in write
    field.write(self, vals[fname])
  File "/home/odoo/ASE/odoo/odoo/fields.py", line 1981, in write
    atts.write({'datas': value})
  File "/home/odoo/ASE/odoo/odoo/addons/base/models/ir_attachment.py", line 483, in write
    vals = self._check_contents(vals)
  File "/home/odoo/ASE/odoo/odoo/addons/base/models/ir_attachment.py", line 249, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/home/odoo/ASE/odoo/odoo/addons/base/models/ir_attachment.py", line 245, in _compute_mimetype
    mimetype = guess_mimetype(base64.b64decode(values['datas']))
  File "/home/odoo/ASE/venv/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
Expected behavior:

1. Translation should succeed
2. Settings should save

Video/Screenshot link (optional):

Example extension files:

```python
# models.py
from odoo import models, fields, api, _


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    translateable_field = fields.Char(translate=True)
```

```xml
<!-- views.xml -->
<?xml version="1.0" encoding="utf-8" ?>
<odoo>
  <data>

    <record id="test_configuration" model="ir.ui.view">
      <field name="name">Test Configuration Settings</field>
      <field name="model">res.config.settings</field>
      <field name='inherit_id' ref='base.res_config_settings_view_form'/>
      <field name="arch" type="xml">
        <xpath expr="//div[hasclass('settings')]" position='inside'>
          <div class="app_settings_block" data-string="TEST" string="TEST">
            <h2>Test Options</h2>
            <div class='row mt16 o_settings_container'>
              <div class='col-xs-12 col-md-6 o_setting_box'>
                <div class='o_setting_left_pane'/>
                <div class='o_setting_right_pane'>
                  <label for="translateable_field" string='Translatable Field' />
                  <field name="translateable_field" />
                </div>
              </div>
            </div>
          </div>
        </xpath>
      </field>
    </record>

  </data>
</odoo>
```

**Comment by sswapnesh** [comment]
Seems like it is fixed in https://github.com/odoo/odoo/pull/47297 but not sure

**Comment by jvm-odoo** [comment]
#47297 fix should be live on Monday

**Comment by zachwaite** [comment]
@jvm-odoo Is is correct to say that I should upgrade base_setup to have this fix take effect?

**Comment by jvm-odoo** [comment]
@zachwaite Yes it is!
