### ISSUE TITLE
[13] account: Error on Grouping CoA by Root

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47147]
Impacted versions: 13.0

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/16624719/76165769-bc882000-617f-11ea-8714-f181aed6e905.png)

![image](https://user-images.githubusercontent.com/16624719/76165789-e2152980-617f-11ea-8737-20fe17cca3bd.png)

(Couldn't reproduce on the local instance)
Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 100032

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/data/build/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.root(100032,).name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/loglevels.py", line 92, in ustr
    return text_type(value)
  File "/data/build/odoo/odoo/tools/func.py", line 150, in __str__
    def __str__(self): return str(self._value)
  File "/data/build/odoo/odoo/tools/func.py", line 137, in _value
    value = self._func(*self._args, **self._kwargs)
  File "/data/build/odoo/odoo/tools/func.py", line 167, in __getitem__
    def __getitem__(self, key): return self._value[key]
  File "/data/build/odoo/odoo/tools/func.py", line 137, in _value
    value = self._func(*self._args, **self._kwargs)
  File "/data/build/odoo/odoo/models.py", line 6253, in <lambda>
    names = tools.lazy(lambda: dict(self.name_get()))
  File "/data/build/odoo/odoo/models.py", line 1647, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/data/build/odoo/odoo/models.py", line 5597, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1009, in __get__
    _("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Record does not exist or has been deleted.\n(Record: account.root(100032,), User: 2)', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 678, in dispatch
    return self._json_response(result)
  File "/data/build/odoo/odoo/http.py", line 607, in _json_response
    body = json.dumps(response, default=date_utils.json_default)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/data/build/odoo/odoo/tools/date_utils.py", line 211, in json_default
    return ustr(obj)
  File "/data/build/odoo/odoo/loglevels.py", line 94, in ustr
    raise UnicodeError('unable to convert %r' % (value,))
UnicodeError: unable to convert <odoo.tools.func.lazy object at 0x7f8ece8095a0>
```

Expected behavior: No error

Video/Screenshot link (optional):

**Comment by 0yik** [comment]
maybe deleted account.root data. so cant reproduce on local instance

Record does not exist or has been deleted.\n(Record: account.root(100032,)

**Comment by sswapnesh** [comment]
This is happening when Code has length of One (Which generates root_id with ord(' ') but which is not present in Db)

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/47639
