### ISSUE TITLE
Nested notebooks looses active pages states

### ISSUE THREAD

**Issue by lgarcia11** [odoo/odoo#47145]
Impacted versions:
13.0

Steps to reproduce:
Add a notebook inside another using Studio, go to second page in parent notebook, click edit form.

Current behavior:
Current page is reset to first page in parent notebook.

Expected behavior:
Keep focus on active pages for both notebooks.

**Comment by Lgdev07** [comment]
Version 12 also has the same problem

**Comment by gustotc** [comment]
Version 12 also has the same problem

**Comment by gustotc** [comment]
> Impacted versions:
> 13.0
> 
> Steps to reproduce:
> Add a notebook inside another using Studio, go to second page in parent notebook, click edit form.
> 
> Current behavior:
> Current page is reset to first page in parent notebook.
> 
> Expected behavior:
> Keep focus on active pages for both notebooks.

Version 12 also has the same problem

**Comment by lgarcia11** [comment]
Try adding a return after this line,

https://github.com/odoo/odoo/blob/e38e73978d7131a96da16ba845936b0e77e91ed7/addons/web/static/src/js/views/form/form_renderer.js#L222

**Comment by Lgdev07** [comment]
> Try adding a return after this line,
> 
> https://github.com/odoo/odoo/blob/e38e73978d7131a96da16ba845936b0e77e91ed7/addons/web/static/src/js/views/form/form_renderer.js#L222

It didn't work, maybe it's the notebook index... I'll try some changes

Thanks 👍

**Comment by lgarcia11** [comment]
@Lgdev07 
It did worked for me, see video [https://streamable.com/ippp31](url)

**Comment by Lgdev07** [comment]
> @Lgdev07
> It works for me, see video [https://streamable.com/ippp31](url)

Still doesn't work, I'll look into my code, see if there is anything wrong, 

If I find a solution, I'll comment here

**Comment by midhunmadhuk** [comment]
> > @Lgdev07
> > It works for me, see video [https://streamable.com/ippp31](url)
> 
> Still doesn't work, I'll look into my code, see if there is anything wrong,
> 
> If I find a solution, I'll comment here

Got any solution v12 I also have nested notebook structure autofocus is not working in v12

**Comment by Chauhan07Vivek** [comment]
I am having the same issue i have nested notebook and after 2nd page it loose active state, and after 3rd page i cannot access 4th page on clicking edit button i am getting this error:

Error:


Traceback:
TypeError: Cannot read property 'classList' of undefined
    at Class.setLocalState (http://localhost:8069/web/content/671-e2519ce/web.assets_backend.js:2235:50)
    at http://localhost:8069/web/content/671-e2519ce/web.assets_backend.js:1340:190
    at async Promise.all (index 0)
    at async Class.update (http://localhost:8069/web/content/671-e2519ce/web.assets_backend.js:1340:269)
    at async Class.update (http://localhost:8069/web/content/671-e2519ce/web.assets_backend.js:2289:58)

**Comment by triyudih** [comment]
> > Try adding a return after this line,
> > https://github.com/odoo/odoo/blob/e38e73978d7131a96da16ba845936b0e77e91ed7/addons/web/static/src/js/views/form/form_renderer.js#L222
> 
> It didn't work, maybe it's the notebook index... I'll try some changes
> 
> Thanks 👍

How about this? solved?
for parent's notebook I have finished it, but for child's notebook I haven't

**Comment by Ali-mughal** [comment]
@triyudih  can you explain bit more I have same problem in odoo14. I have same issue when i click on second nested notebook form goes back first active notebook its fine in odoo10 but problem in odoo14

**Comment by mosalahp1** [comment]
> In my case issue is resolved after giving name of every notebook odoo14.

thanks, it worked for me :+1: :100: :
