### ISSUE TITLE
Odoo Cannot Use Etherpad API to Generate Pads with Working Permissions

### ISSUE THREAD

**Issue by sissieadmin** [odoo/odoo#47550]
I have an[ open Github issue for etherpad](https://github.com/ether/etherpad-lite/issues/3695), but this looks like an Odoo bug.

Impacted versions:

Odoo 13, Nightly Community - 13.0.20200227

Steps to reproduce:

Nginx entry for Etherpad reverse proxy:

```
server {
        listen       4443;
        server_name domain.com  

        access_log  /var/log/nginx/etherpadProxy.access.log;
        error_log   /var/log/nginx/etherpadProxy.error.log;

        ssl                  on;
        ssl_certificate      /etc/letsencrypt/live/domain.com/cert.pem;
        ssl_certificate_key  /etc/letsencrypt/live/domain.com/privkey.pem;

        ssl_session_timeout  5m;

        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;
       # ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 \
       # EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 \
       # EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";

        location / {
            proxy_pass             http://localhost:9001/;
            proxy_set_header       Host $host;
            proxy_pass_header Server;
            # be careful, this line doesn't override any proxy_buffering on set in a conf.d/file.conf
            proxy_buffering off;
            proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
            proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
            proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
            proxy_set_header Host $host;  # pass the host header                                                   
            proxy_http_version 1.1;  # recommended with keepalive connections                                                    
            # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
            #proxy_set_header Upgrade $http_upgrade;
            #proxy_set_header Connection $connection_upgrade;
	}

	location /pad {        
        rewrite                /pad/(.*) /$1 break;
        rewrite                ^/pad$ /pad/ permanent; 
        proxy_pass             http://localhost:9001/;
        proxy_pass_header Server;
        proxy_redirect         / /pad/;
        proxy_set_header       Host $host;
        proxy_buffering off;
    }
    
    location /pad/socket.io {
        rewrite /pad/socket.io/(.*) /socket.io/$1 break;
        proxy_pass http://localhost:9001/;
        proxy_redirect         / /pad/;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
        proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
        proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
        proxy_set_header Host $host;  # pass the host header                                                   
        proxy_http_version 1.1;  # recommended with keepalive connections                                                    
        # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection $connection_upgrade;
    }
    
    location /static {
        rewrite /static/(.*) /static/$1 break;
        proxy_pass http://localhost:9001/;
        proxy_set_header Host $host;
        proxy_buffering off;
    }
}
```

My Etherpad settings.json

```
/*
 * This file must be valid JSON. But comments are allowed
 *
 * Please edit settings.json, not settings.json.template
 *
 * Please note that starting from Etherpad 1.6.0 you can store DB credentials in
 * a separate file (credentials.json).
 *
 *
 * ENVIRONMENT VARIABLE SUBSTITUTION
 * =================================
 *
 * All the configuration values can be read from environment variables using the
 * syntax "${ENV_VAR}" or "${ENV_VAR:default_value}".
 *
 * This is useful, for example, when running in a Docker container.
 *
 * EXAMPLE:
 *    "port":     "${PORT:9001}"
 *    "minify":   "${MINIFY}"
 *    "skinName": "${SKIN_NAME:colibris}"
 *
 * Would read the configuration values for those items from the environment
 * variables PORT, MINIFY and SKIN_NAME.
 *
 * If PORT and SKIN_NAME variables were not defined, the default values 9001 and
 * "colibris" would be used.
 * The configuration value "minify", on the other hand, does not have a
 * designated default value. Thus, if the environment variable MINIFY were
 * undefined, "minify" would be null.
 *
 * REMARKS:
 * 1) please note that variable substitution always needs to be quoted.
 *
 *    "port":     9001,            <-- Literal values. When not using
 *    "minify":   false                substitution, only strings must be
 *    "skinName": "colibris"           quoted. Booleans and numbers must not.
 *
 *    "port":     "${PORT:9001}"   <-- CORRECT: if you want to use a variable
 *    "minify":   "${MINIFY:true}"     substitution, put quotes around its name,
 *    "skinName": "${SKIN_NAME}"       even if the required value is a number or
 *                                     a boolean.
 *                                     Etherpad will take care of rewriting it
 *                                     to the proper type if necessary.
 *
 *    "port":     ${PORT:9001}     <-- ERROR: this is not valid json. Quotes
 *    "minify":   ${MINIFY}            around variable names are missing.
 *    "skinName": ${SKIN_NAME}
 *
 * 2) Beware of undefined variables and default values: nulls and empty strings
 *    are different!
 *
 *    This is particularly important for user's passwords (see the relevant
 *    section):
 *
 *    "password": "${PASSW}"  // if PASSW is not defined would result in password === null
 *    "password": "${PASSW:}" // if PASSW is not defined would result in password === ''
 *
 */
{
  /*
   * Name your instance!
   */
  "title": "Etherpad",

  /*
   * favicon default name
   * alternatively, set up a fully specified Url to your own favicon
   */
  "favicon": "favicon.ico",

  /*
   * Skin name.
   *
   * Its value has to be an existing directory under src/static/skins.
   * You can write your own, or use one of the included ones:
   *
   * - "no-skin":  an empty skin (default). This yields the unmodified,
   *               traditional Etherpad theme.
   * - "colibris": the new experimental skin (since Etherpad 1.8), candidate to
   *               become the default in Etherpad 2.0
   */
  "skinName": "colibris",

  /*
   * IP and port which etherpad should bind at
   */
  "ip": "127.0.0.1",
  "port": 9001,

  /*
   * Option to hide/show the settings.json in admin page.
   *
   * Default option is set to true
   */
  "showSettingsInAdminPage": true,

  /*
   * Node native SSL support
   *
   * This is disabled by default.
   * Make sure to have the minimum and correct file access permissions set so
   * that the Etherpad server can access them
   */

  /*
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt",
            "ca": ["/path-to-your/epl-intermediate-cert1.crt", "/path-to-your/epl-intermediate-cert2.crt"]
          },
  */

  /*
   * The type of the database.
   *
   * You can choose between many DB drivers, for example: dirty, postgres,
   * sqlite, mysql.
   *
   * You shouldn't use "dirty" for for anything else than testing or
   * development.
   *
   *
   * Database specific settings are dependent on dbType, and go in dbSettings.
   * Remember that since Etherpad 1.6.0 you can also store these informations in
   * credentials.json.
   *
   * For a complete list of the supported drivers, please refer to:
   * https://www.npmjs.com/package/ueberdb2
   */

   
    "dbType" : "postgres",
    "dbSettings" : {
    "user"    : "etherpadDBUser",
    "host"    : "localhost",
    "password": "xxxxxxx",
    "database": "etherpadDB",
    "charset" : "utf8mb4"
    }, 
   
   
   /*
  "dbType": "dirty",
  "dbSettings": {
    "filename": "var/dirty.db"
  },
   */



  /*
   * An Example of MySQL Configuration (commented out).
   *
   * See: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
   */

  /*
  "dbType" : "mysql",
  "dbSettings" : {
    "user":     "etherpaduser",
    "host":     "localhost",
    "port":     3306,
    "password": "PASSWORD",
    "database": "etherpad_lite_db",
    "charset":  "utf8mb4"
  },
  */

  /*
   * The default text of a pad
   */
  "defaultPadText" : "Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at http:\/\/etherpad.org\n",

  /*
   * Default Pad behavior.
   *
   * Change them if you want to override.
   */
  "padOptions": {
    "noColors":         false,
    "showControls":     true,
    "showChat":         true,
    "showLineNumbers":  true,
    "useMonospaceFont": false,
    "userName":         false,
    "userColor":        false,
    "rtl":              false,
    "alwaysShowChat":   false,
    "chatAndUsers":     false,
    "lang":             "en-gb"
  },

  /*
   * Pad Shortcut Keys
   */
  "padShortcutEnabled" : {
    "altF9":     true, /* focus on the File Menu and/or editbar */
    "altC":      true, /* focus on the Chat window */
    "cmdShift2": true, /* shows a gritter popup showing a line author */
    "delete":    true,
    "return":    true,
    "esc":       true, /* in mozilla versions 14-19 avoid reconnecting pad */
    "cmdS":      true, /* save a revision */
    "tab":       true, /* indent */
    "cmdZ":      true, /* undo/redo */
    "cmdY":      true, /* redo */
    "cmdI":      true, /* italic */
    "cmdB":      true, /* bold */
    "cmdU":      true, /* underline */
    "cmd5":      true, /* strike through */
    "cmdShiftL": true, /* unordered list */
    "cmdShiftN": true, /* ordered list */
    "cmdShift1": true, /* ordered list */
    "cmdShiftC": true, /* clear authorship */
    "cmdH":      true, /* backspace */
    "ctrlHome":  true, /* scroll to top of pad */
    "pageUp":    true,
    "pageDown":  true
  },

  /*
   * Should we suppress errors from being visible in the default Pad Text?
   */
  "suppressErrorsInPadText": false,

  /*
   * If this option is enabled, a user must have a session to access pads.
   * This effectively allows only group pads to be accessed.
   */
  "requireSession": true,

  /*
   * Users may edit pads but not create new ones.
   *
   * Pad creation is only via the API.
   * This applies both to group pads and regular pads.
   */
  "editOnly": true,

  /*
   * If set to true, those users who have a valid session will automatically be
   * granted access to password protected pads.
   */
  "sessionNoPassword": true,

  /*
   * If true, all css & js will be minified before sending to the client.
   *
   * This will improve the loading performance massively, but makes it difficult
   * to debug the javascript/css
   */
  "minify": true,

  /*
   * How long may clients use served javascript code (in seconds)?
   *
   * Not setting this may cause problems during deployment.
   * Set to 0 to disable caching.
   */
  "maxAge": 21600, // 60 * 60 * 6 = 6 hours

  /*
   * Absolute path to the Abiword executable.
   *
   * Abiword is needed to get advanced import/export features of pads. Setting
   * it to null disables Abiword and will only allow plain text and HTML
   * import/exports.
   */
  "abiword": null,

  /*
   * This is the absolute path to the soffice executable.
   *
   * LibreOffice can be used in lieu of Abiword to export pads.
   * Setting it to null disables LibreOffice exporting.
   */
  "soffice": null,

  /*
   * Path to the Tidy executable.
   *
   * Tidy is used to improve the quality of exported pads.
   * Setting it to null disables Tidy.
   */
  "tidyHtml": null,

  /*
   * Allow import of file types other than the supported ones:
   * txt, doc, docx, rtf, odt, html & htm
   */
  "allowUnknownFileEnds": true,

  /*
   * This setting is used if you require authentication of all users.
   *
   * Note: "/admin" always requires authentication.
   */
  "requireAuthentication": false,

  /*
   * Require authorization by a module, or a user with is_admin set, see below.
   */
  "requireAuthorization": false,

  /*
   * When you use NGINX or another proxy/load-balancer set this to true.
   *
   * This is especially necessary when the reverse proxy performs SSL
   * termination, otherwise the cookies will not have the "secure" flag.
   *
   * The other effect will be that the logs will contain the real client's IP,
   * instead of the reverse proxy's IP.
   */
  "trustProxy":true,

  /*
   * Privacy: disable IP logging
   */
  "disableIPlogging": false,

  /*
   * Time (in seconds) to automatically reconnect pad when a "Force reconnect"
   * message is shown to user.
   *
   * Set to 0 to disable automatic reconnection.
   */
  "automaticReconnectionTimeout": 0,

  /*
   * By default, when caret is moved out of viewport, it scrolls the minimum
   * height needed to make this line visible.
   */
  "scrollWhenFocusLineIsOutOfViewport": {

    /*
     * Percentage of viewport height to be additionally scrolled.
     *
     * E.g.: use "percentage.editionAboveViewport": 0.5, to place caret line in
     *       the middle of viewport, when user edits a line above of the
     *       viewport
     *
     * Set to 0 to disable extra scrolling
     */
    "percentage": {
      "editionAboveViewport": 0,
      "editionBelowViewport": 0
    },

    /*
     * Time (in milliseconds) used to animate the scroll transition.
     * Set to 0 to disable animation
     */
    "duration": 0,

    /*
     * Flag to control if it should scroll when user places the caret in the
     * last line of the viewport
     */
    "scrollWhenCaretIsInTheLastLineOfViewport": false,

    /*
     * Percentage of viewport height to be additionally scrolled when user
     * presses arrow up in the line of the top of the viewport.
     *
     * Set to 0 to let the scroll to be handled as default by Etherpad
     */
    "percentageToScrollWhenUserPressesArrowUp": 0
  },

  /*
   * Users for basic authentication.
   *
   * is_admin = true gives access to /admin.
   * If you do not uncomment this, /admin will not be available!
   *
   * WARNING: passwords should not be stored in plaintext in this file.
   *          If you want to mitigate this, please install ep_hash_auth and
   *          follow the section "secure your installation" in README.md
   */

  
  "users": {
    "admin": {
      // 1) "password" can be replaced with "hash" if you install ep_hash_auth
      // 2) please note that if password is null, the user will not be created
      "password": "",
      "is_admin": true
    },
    "user": {
      // 1) "password" can be replaced with "hash" if you install ep_hash_auth
      // 2) please note that if password is null, the user will not be created
      "password": "",
      "is_admin": false
    }
  },
  

  /*
   * Restrict socket.io transport methods
   */
  "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],

  /*
   * Allow Load Testing tools to hit the Etherpad Instance.
   *
   * WARNING: this will disable security on the instance.
   */
  "loadTest": false,

  /*
   * Disable indentation on new line when previous line ends with some special
   * chars (':', '[', '(', '{')
   */

  /*
  "indentationOnNewLine": false,
  */

  /*
   * Toolbar buttons configuration.
   *
   * Uncomment to customize.
   */

  /*
  "toolbar": {
    "left": [
      ["bold", "italic", "underline", "strikethrough"],
      ["orderedlist", "unorderedlist", "indent", "outdent"],
      ["undo", "redo"],
      ["clearauthorship"]
    ],
    "right": [
      ["importexport", "timeslider", "savedrevision"],
      ["settings", "embed"],
      ["showusers"]
    ],
    "timeslider": [
      ["timeslider_export", "timeslider_returnToPad"]
    ]
  },
  */

  /*
   * Expose Etherpad version in the web interface and in the Server http header.
   *
   * Do not enable on production machines.
   */
  "exposeVersion": false,

  /*
   * The log level we are using.
   *
   * Valid values: DEBUG, INFO, WARN, ERROR
   */
  "loglevel": "DEBUG",

  /*
   * Logging configuration. See log4js documentation for further information:
   * https://github.com/nomiddlename/log4js-node
   *
   * You can add as many appenders as you want here.
   */
  "logconfig" :
    { "appenders": [
        { "type": "console"
        //, "category": "access"// only logs pad access
        }

      
      , { "type": "file"
      , "filename": "etherpad-lite.log"
      , "maxLogSize": 1024
      , "backups": 3 // how many log files there're gonna be at max
      //, "category": "test" // only log a specific category
        }
      

      /*
      , { "type": "logLevelFilter"
        , "level": "warn" // filters out all log messages that have a lower level than "error"
        , "appender":
          {  Use whatever appender you want here  }
        }
      */

      /*
      , { "type": "logLevelFilter"
        , "level": "error" // filters out all log messages that have a lower level than "error"
        , "appender":
          { "type": "smtp"
          , "subject": "An error occurred in your EPL instance!"
          , "recipients": "bar@blurdybloop.com, baz@blurdybloop.com"
          , "sendInterval": 300 // 60 * 5 = 5 minutes -- will buffer log messages; set to 0 to send a mail for every message
          , "transport": "SMTP", "SMTP": { // see https://github.com/andris9/Nodemailer#possible-transport-methods
              "host": "smtp.example.com", "port": 465,
              "secureConnection": true,
              "auth": {
                  "user": "foo@example.com",
                  "pass": "bar_foo"
              }
            }
          }
        }
      */

      ]
    } // logconfig
}
```

Current behavior:

When I connect to a page referring to Etherpad, I get an error where etherpad should appear on the page: "You do not have permission to access this pad"

Odoo:

```
`Started Etherpad...
[2020-02-12 20:16:53.691] [DEBUG] console - Running on Node v10.18.1 (minimum required Node version: 8.9.0)
[2020-02-12 20:16:53.787] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad/local/etherpad/etherpad-lite
[2020-02-12 20:16:53.788] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad/local/etherpad/etherpad-lite/settings.json"
[2020-02-12 20:16:53.788] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad/local/etherpad/etherpad-lite/credentials.json"
[2020-02-12 20:16:53.794] [INFO] console - settings loaded from: /opt/etherpad/local/etherpad/etherpad-lite/settings.json
[2020-02-12 20:16:53.794] [INFO] console - No credentials file found in /opt/etherpad/local/etherpad/etherpad-lite/credentials.json. Ignoring.
[2020-02-12 20:16:53.800] [INFO] console - Using skin "colibris" in dir: /opt/etherpad/local/etherpad/etherpad-lite/src/static/skins/colibris
[2020-02-12 20:16:53.800] [DEBUG] AbsolutePaths - Relative path "./SESSIONKEY.txt" can be rewritten to "/opt/etherpad/local/etherpad/etherpad-lite/SESSIONKEY.txt"
[2020-02-12 20:16:53.801] [INFO] console - Session key loaded from: /opt/etherpad/local/etherpad/etherpad-lite/SESSIONKEY.txt


...

[2020-02-12 20:16:54.356] [DEBUG] AbsolutePaths - Relative path "./APIKEY.txt" can be rewritten to "/opt/etherpad/local/etherpad/etherpad-lite/APIKEY.txt"
[2020-02-12 20:16:54.356] [INFO] APIHandler - Api key file read from: "/opt/etherpad/local/etherpad/etherpad-lite/APIKEY.txt"
[2020-02-12 20:16:54.478] [INFO] console - Installed plugins: 
[2020-02-12 20:16:54.478] [DEBUG] console - Installed parts:

...



[2020-02-12 20:17:06.498] [INFO] ueberDB - Flushed 1 values
[2020-02-12 20:17:06.583] [DEBUG] ueberDB - GET    - pad:odoodb1-note.note-AQPFMM9EAP - null - from cache
[2020-02-12 20:17:06.584] [DEBUG] ueberDB - GET    - token2author:t.jNgDKSQidXOGvNr5983T - "a.mLq0ErRbI6RPmy63" - from database 
[2020-02-12 20:17:06.584] [DEBUG] ueberDB - SETSUB - globalAuthor:a.mLq0ErRbI6RPmy63["timestamp"] - 1581567426584
[2020-02-12 20:17:06.585] [DEBUG] ueberDB - GET    - session:null - null - from database 
[2020-02-12 20:17:06.585] [DEBUG] auth - Auth failed: unknown session
[2020-02-12 20:17:06.585] [DEBUG] auth - Auth failed: invalid session & pad does not exist
[2020-02-12 20:17:06.585] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"odoodb1-note.note-AQPFMM9EAP","sessionID":"null","password":null,"token":"t.jNgDKSQidXOGvNr5983T","protocolVersion":2}
[2020-02-12 20:17:06.585] [DEBUG] message - to iSPXj5Y9affKI0lrAAAA: {"accessStatus":"deny"}
[2020-02-12 20:17:06.586] [DEBUG] ueberDB - GET    - globalAuthor:a.mLq0ErRbI6RPmy63 - {"colorId":47,"name":null,"timestamp":1581566958988} - from database 
[2020-02-12 20:17:06.586] [DEBUG] ueberDB - SET    - globalAuthor:a.mLq0ErRbI6RPmy63 - {"colorId":47,"name":null,"timestamp":1581567426584} - to buffer
[2020-02-12 20:17:06.599] [INFO] ueberDB - Flushed 1 values
```
Firefox Console Error:

`Firefox can’t establish a connection to the server at wss://domain.com:44443/socket.io/?EIO=3&transport=websocket&sid=hmql_jbv97j13dpaAAAA. socket.io.js:7:23187
`

Expected behavior:

An Iframe from Etherpad appears, and allows Odoo users to write in a shared pad that is only accessible to users who access the pad through Odoo.

**Comment by pedrobaeza** [comment]
It seems a configuration problem if it puts `wss://domain.com:44443` at the end.

**Comment by sissieadmin** [comment]
> It seems a configuration problem if it puts `wss://domain.com:44443` at the end.

The 4443 is deliberate, since Etherpad is sharing the server with Odoo13 and we used separate ports.

I will have a working Odoo12 install that I can test Etherpad with. This may help clarify if it is a bug or configuration problem.

**Comment by sissieadmin** [comment]
=

> > It seems a configuration problem if it puts `wss://domain.com:44443` at the end.
> 
> The 4443 is deliberate, since Etherpad is sharing the server with Odoo13 and we used separate ports.
> 
> I will have a working Odoo12 install that I can test Etherpad with. This may help clarify if it is a bug or configuration problem.

Ah, so I tried the exact same Etherpad installation but through a separate an Odoo12 installation. It didn't work either, so it appears there is a configuration problem:

`[2020-03-14 16:52:15.355] [ERROR] console - (node:809) UnhandledPromiseRejectionWarning: apierror: sessionID does not exist
    at Object.exports.getSessionInfo (/opt/etherpad-again/etherpad-lite/src/node/db/SessionManager.js:128:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

`[2020-03-14 16:52:15.355] [ERROR] console - (node:809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`


`[2020-03-14 16:52:15.355] [ERROR] console - (node:809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by pedrobaeza** [comment]
OK, then let's close it until further evidences of a bug in code.
