### ISSUE TITLE
[13] website: Error on Setting new Pictogram on Website (Event Home Page)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47642]
Impacted versions: 13.0

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/16624719/76687475-45a0ca80-664a-11ea-83fb-1de93a9c093d.png)

![image](https://user-images.githubusercontent.com/16624719/76687482-55b8aa00-664a-11ea-9b67-6d7b7eb3147c.png)

Add and Save Main Page

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/website/models/ir_ui_view.py", line 440, in save
    super(View, self).save(value, xpath=xpath)
  File "/data/build/odoo/addons/web_editor/models/ir_ui_view.py", line 202, in save
    new_arch = self.replace_arch_section(xpath, arch_section)
  File "/data/build/odoo/addons/web_editor/models/ir_ui_view.py", line 130, in replace_arch_section
    [root] = arch.xpath(section_xpath)
ValueError: not enough values to unpack (expected 1, got 0)
```
Expected behavior: Able to Chage Pictogram

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@JKE-be can you please check this?

**Comment by JKE-be** [comment]
icon is already not replaced before the save :/
![image](https://user-images.githubusercontent.com/4848797/78350888-386e6000-75a6-11ea-8927-d6de5e40dc08.png)

**Comment by JKE-be** [comment]
It is a exception case, and not sure that we want to focus the bug fix on it.
It is due to a specific case where $0 is replaced by the t-caller.

In this case:

Arch is : 
```xml
<data inherit_id="website.website_search_box" primary="True">
    <xpath expr="//div[@role=\'search\']" position="replace">
        <form t-attf-class="o_wevent_event_searchbar_form o_wait_lazy_js my-1 my-lg-0 #{_classes}" t-att-action="action if action else \'/event\'" method="get">
            <t t-set="search" t-value="search or _searches and _searches[\'search\']"/>
            <t>$0</t>
            <t t-foreach="_searches" t-as="search">
                <input t-if="search != \'search\' and search_value != \'all\'" type="hidden" t-att-name="search" t-att-value="search_value"/>
            </t>
            <t t-raw="0"/>
        </form>
    </xpath>
<xpath expr="." position="attributes"><attribute name="t-name">website_event.events_search_box</attribute></xpath></data>
```


but we are looking fot the xpath: 
```xml
/data/xpath[1]/form/t[2]/div[1]/div[1]
```
where `t[2]` is `$0` and so we cannot  match the `div[1]/div[1]` :/


//cc @qsm-odoo
