### ISSUE TITLE
[13] Unable to update modules

### ISSUE THREAD

**Issue by loxK** [odoo/odoo#48388]
**Impacted versions:** 13

**Steps to reproduce:** 
Update all modules connected as a Superadmin user: /web?debug=1#action=39&cids=1&menu_id=5

**Current behavior:**
Update fails with error message: 

![image](https://user-images.githubusercontent.com/136687/77604383-75af6e00-6f66-11ea-9e60-239a556282dc.png)

**Expected behavior:**

Modules should update

**Additional debug information**

Nothing related in odoo.log but the web console has some debug output:

```
Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:
	- User types/Internal User - (Operation: read, User: 4)
None 
 Error data debug:
 Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 60701

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('loempia.module(60701,).image_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f49da3a4950>, 4, False, 'ir.attachment', 'read', True, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1003, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f49da3a4950>, 4, False, 'ir.attachment', 'read', True, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/custom/private/loempia/controllers/embed.py", line 96, in update
    'ico': module.image_ids and '/apps/module_image?image_id=%s' % module.image_ids[0].id or '',
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2246, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1005, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 4)", None)
```

**Comment by Yenthe666** [comment]
Hi @loxK,

Can you reproduce this problem on an official test instance from Odoo at runbot.odoo.com?
It looks like somebody has manually changed some security rights which is causing this issue actually.

Regards,
Yenthe

**Comment by intero-chz** [comment]
Looks like custom code to me:

```
File "/home/odoo/src/custom/private/loempia/controllers/embed.py", line 96, in update
    'ico': module.image_ids and '/apps/module_image?image_id=%s' % module.image_ids[0].id or '',
```

And then there is a `CacheMiss` probably from a computed field which compute method isn't computing every record it gets.

```odoo.exceptions.CacheMiss: ('loempia.module(60701,).image_ids', None)```

**Comment by stupidgoats** [comment]
I am having a similar issue I believe.

When I click on the Updates menu under Apps while in debug I am getting the following error and no apps with updates are displayed. I am able to install apps and update them from the ir.module kanban view or the ir.module form view.

![image](https://user-images.githubusercontent.com/31421058/77676052-26683e00-6f64-11ea-85c1-281988f712b1.png)

This occurs whether I am in as the superuser or my typical internal user account. I am getting this on 3 different instances with fairly similar custom code bases. The one thing I found interesting was all of the userid's for each of the different databases for my instances all show the same user id as the image whether superuser or internal user account.

Additionally, I have checked and there does not seem to be any user with the id 226606.

Any help is greatly appreciated. Thanks!

**Comment by stupidgoats** [comment]
Was just able to find the traceback in the Browser Console. Thanks @loxK 

Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:
	- User types/Internal User - (Operation: read, User: 226606)
None 
 Error data debug:
 Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 50527

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('loempia.module(50527,).image_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f40297857b8>, 226606, False, 'ir.attachment', 'read', True, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1003, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 226606)", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/13.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f40297857b8>, 226606, False, 'ir.attachment', 'read', True, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/custom/private/loempia/controllers/embed.py", line 96, in update
    'ico': module.image_ids and '/apps/module_image?image_id=%s' % module.image_ids[0].id or '',
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2246, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1005, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 2935, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3035, in _read
    field.read(fetched)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2869, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/13.0/addons/calendar/models/ir_attachment.py", line 21, in _search
    return super(Attachment, self)._search(args, offset=offset, limit=limit, order=order, count=count, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_attachment.py", line 410, in _search
    count=False, access_rights_uid=access_rights_uid)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4364, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 3204, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1548, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to access documents of type 'Attachment' (ir.attachment). This operation is allowed for the groups:\n\t- User types/Internal User - (Operation: read, User: 226606)", None)

**Comment by stupidgoats** [comment]
@loxK I was able to find what was causing my issue (not from a coding perspective, I am not too great at actual development) I posted about it in the #47927 issue. 

It seems we had some OCA modules which were causing the error. I was able to find updates for all of the ones throwing me errors. I found out which were causing it by creating a new db and installing the third party modules 1 by 1 and testing for the error after each one.

Good luck, and I hope it helps!

**Comment by loxK** [comment]
It definitely is related to some third party modules.
We contacted the developers.

Thanks.

**Comment by Vartkat** [comment]
I'm facing the same problem and followed a suggestion on another bug report, i.e. brand new database, only two standard apps installed (account and mail), I tried three different times : 

- new database + date_range (required by report_xlsx) --> no error
- new database + report_xlsx --> ERROR
- new database + Muk_utils --> ERROR
- new database + account_financial_report --> ERROR

As you can see, either all these dev has missed a new rule for writing third party modules or the standard code has something wrong.

I'm more inclined to beleive the second option as these three are from really different dev teams.

V.

**Comment by stupidgoats** [comment]
@Vartkat Well on  #47927 linked to earlier, everything started magically working for us late last night without any code updates, so we are thinking our error (which seems to be related) had something to do with the Odoo Apps API which is not an actual part of the Odoo base code.

So I would suggest seeing if the error is still around.

**Comment by Vartkat** [comment]
@stupidgoats Thanks for the info, I just tried with my complete setup (a bunch of third party addons) and it works so I suppose you're right, it doesn't come from the Odoo code or the third party one but from the update server.
