### ISSUE TITLE
malformed VAT# uncaught exception odoo server 8.0 dev latest nightly build available 2014-06-11

### ISSUE THREAD

**Issue by monetschemist** [odoo/odoo#484]
The install script for the accounting / finance app failed on a malformed VAT # and dumped the exception on the screen during installation - which I presume failed from that point onward, but it's hard to tell.

I guess this may have happened because I defined the company before installing the app...? and maybe the validation rule?

here is the traceback...

2014-06-11 21:19:30,835 5052 INFO nueva2014a openerp.addons.base_vat.base_vat: Importing VAT Number [9643303RC0001] is not valid !
2014-06-11 21:19:30,854 5052 ERROR nueva2014a openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/http.py", line 470, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/pymodules/python2.7/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/http.py", line 638, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/http.py", line 337, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1246, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1234, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/module.py", line 428, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/module.py", line 479, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 299, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 243, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 117, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 968, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 1054, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 921, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 850, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py", line 985, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/res/res_partner.py", line 523, in write
    result = super(res_partner,self).write(cr, uid, ids, vals, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/addons/mail/mail_thread.py", line 406, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 3969, in write
    self._validate(cr, user, ids, context)
  File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 1584, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
ParseError: "ValidateError
The VAT number [82964 3303 RC0001] for partner [nueva consulting group inc.] does not seem to be valid.
Note: the expected format is 'CC##' (CC=Country Code, ##=VAT Number)" while parsing /usr/lib/pymodules/python2.7/openerp/addons/stock/stock_data.xml:134, near
<record id="base.main_partner" model="res.partner">
            <field name="property_stock_customer" eval="ref('stock_location_stock')"/>
        </record>
2014-06-11 21:19:30,870 5052 INFO nueva2014a werkzeug: 192.168.2.62 - - [11/Jun/2014 21:19:30] "POST /web/dataset/call_button HTTP/1.1" 200 -

**Comment by Yenthe666** [comment]
Dear @monetschemist,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
