### ISSUE TITLE
[13.0] Impossible to open website app

### ISSUE THREAD

**Issue by tarbib** [odoo/odoo#48549]
Impacted versions: 13

Steps to reproduce:
Click on website

Current behavior:
Error raised:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/website_sale/controllers/backend.py", line 55, in fetch_dashboard_data
    groupby='product_tmpl_id', orderby='product_uom_qty desc', limit=5)
  File "/odoo/odoo-server/odoo/models.py", line 2140, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/odoo/odoo-server/odoo/models.py", line 2265, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column sale_report.website_id does not exist
LINE 4:             WHERE (((("sale_report"."website_id" = 1)  AND  ...
                              ^`
Expected behavior:
Open website app
Video/Screenshot link (optional):
I saw the same issue fixed at Flectra:
https://gitlab.com/flectra-hq/flectra/-/merge_requests/14/diffs

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by kenseii** [comment]
I don't think it is related to the deployment way, sometimes it just happens out of nowhere.
The easiest solution mostly is to **upgrade** the website module

**Comment by bnisevic** [comment]
@pedrobaeza why are you closing the issues which are obviously bugs? I have the same, happened on an installation which we have for a while. There are no changes which we made and which are obviously related to this issue. It is also Odoo 13.

![Firefox_Screenshot_2021-12-20T10-56-32 459Z](https://user-images.githubusercontent.com/1433428/146756899-d7fe8797-d88c-4577-8fd0-73addfeae437.png)
