### ISSUE TITLE
[12.0] Code profile logging output raises an error when you call method with rpc.query via js.

### ISSUE THREAD

**Issue by crtmneric** [odoo/odoo#48559]
Impacted versions:
[12.0] Code profile logging output raises an error.

Steps to reproduce:
add @profile('/tmp/my-module.profile') as shown in [documentation ](https://www.odoo.com/documentation/12.0/howtos/profilecode.html)

Current behavior:
`Traceback (most recent call last):
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/serkan/Documents/Odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serkan/Documents/Odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/serkan/Documents/Odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/serkan/Documents/Odoo12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/serkan/Documents/Odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/serkan/Documents/Odoo12/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/home/serkan/Documents/Odoo12/odoo/api.py", line 725, in _call_kw_model
    context, args, kwargs = split_context(method, args, kwargs)
  File "/home/serkan/Documents/Odoo12/odoo/api.py", line 307, in split_context
    return args[pos], args[:pos], kwargs
IndexError: list index out of range
`
Raises this IndexError

Expected behavior:
Took logs of method than write them into given path.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@crtmneric are you sure you're not importing `from odoo.tools.profiler import profile` instead of `from odoo.tools.misc import profile`? There are two profilers but they both are called differently.

**Comment by crtmneric** [comment]
> @crtmneric are you sure you're not importing `from odoo.tools.profiler import profile` instead of `from odoo.tools.misc import profile`? There are two profilers but they both are called differently.

![image](https://user-images.githubusercontent.com/16175654/77886975-74d25100-7272-11ea-93d5-5374a30afbdb.png)
yep i checked it again but unfortunately nope, i still cannot get what is the problem. I actually used this before :cry:

**Comment by crtmneric** [comment]
i m calling this method from js via rpc.query is it related with error ? @Yenthe666

**Comment by Yenthe666** [comment]
@ged-odoo have you ever seen similar reports like this or know what's up?

**Comment by C3POdoo** [comment]
Dear @crtmneric,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
