### ISSUE TITLE
[12.0] account: Error on onchange in a journal entry with multiple tax_line_id

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#48574]
**Impacted versions:**
12.0

**Steps to reproduce:**

- Create a journal entry with multiple lines with `tax_line_id`. This step can't be reproduced through UI, but can be done with an import. This happens in the usual payroll journal entry that is imported from the external services company that elaborates this payroll.
- Try to modify 

**Current behavior:**
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4741, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5533, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5377, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/auto/addons/account/models/account_move.py", line 256, in _onchange_line_ids
    tax_line.debit = amount > 0 and amount or 0.0
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1025, in __set__
    record.ensure_one()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4744, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move.line(2230592, 2230461, 2230577, 2230514, 2230559, 2230486, 2230569, 2230466, 2230476, 2230549, 2230587, 2230451, 2230554, 2230471, 2230544, 2230564, 2230496, 2230481, 2230524, 2230529, 2230582, 2230519, 2230456, 2230597, 2230491, 2230501, 2230539, 2230607, 2230510, 2230506, 2230534, 2230604, 2230573)
```

**Expected behavior:**
No error.

This is provoked by this piece of code:

https://github.com/odoo/odoo/blob/8722ed96aa62d81819e840b02304489d63025045/addons/account/models/account_move.py#L167-L170

that returns unconditionally all the possible found lines, being 0, 1 or several of them.

I think later in the code:

https://github.com/odoo/odoo/blob/8722ed96aa62d81819e840b02304489d63025045/addons/account/models/account_move.py#L249-L261

a check about the number of lines being 1 should be done and if not, no action should be taken.

**Comment by pedrobaeza** [comment]
@smetl you were the author of that code. Can you please tell what do you think about this? Should I fill a PR with my proposed solution?

**Comment by smetl** [comment]
@pedrobaeza If you already have a solution in mind, feel free to open a PR :)

**Comment by nim-odoo** [comment]
Not sure what you expect in this case, but we could also keep only one line as in https://github.com/odoo/odoo/pull/48721

**Comment by pedrobaeza** [comment]
As the following code lines tries to "synchronize" base and fee tax amounts, for me it doesn't make sense to make the adjustment for the first found line, but make no adjustment at all.

**Comment by nim-odoo** [comment]
ok

**Comment by nim-odoo** [comment]
commit adapted

**Comment by pedrobaeza** [comment]
Closing as the PR is on its way. Thank you both!

**Comment by C3POdoo** [comment]
Dear @pedrobaeza,

Thank you for your report but we are closing it due to inactivity.
We apology if we could not look at your request in time.
If your report still makes sense, don't hesitate to reopen a new one. We will try to check it as soon as possible.

_This is an automated message._
