### ISSUE TITLE
[13] website: Deleting contents of elements in editor leads to errors

### ISSUE THREAD

**Issue by bosskopp** [odoo/odoo#48688]
Impacted versions:

13e, 13ce
(Instance: https://1974466-13-0-276f22.runbot24.odoo.com/ - O13 stable test)

Steps to reproduce:

1. Login as priviledged user, open website and click edit buton
2. Drag snippet on website (e.g. cover)
3. Delete all contents of snippet (backspace-key)
4. Press enter key
5. Play around with pressing Enter and Backspace

![website-editor-err](https://user-images.githubusercontent.com/1733427/78062689-5ada6080-738f-11ea-8b1b-a11d4c9d096a.gif)

Current behavior:

```
Error:
Uncaught TypeError: Cannot read property 'tagName' of null

https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1577-f1c32aa/web_editor.summernote.js:593
Traceback:
TypeError: Cannot read property 'tagName' of null
    at isFormatNode (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1577-f1c32aa/web_editor.summernote.js:593:79)
    at $.summernote.pluginEvents.enter (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1577-f1c32aa/web_editor.summernote.js:539:64)
    at HTMLDivElement.<anonymous> (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1577-f1c32aa/web_editor.summernote.js:399:80)
    at HTMLDivElement.dispatch (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1567-0056db0/1/web.assets_common_lazy.js:925:447)
    at HTMLDivElement.elemData.handle (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1567-0056db0/1/web.assets_common_lazy.js:911:166)
```

```
Error:


Traceback:
TypeError: Cannot read property 'classList' of undefined
    at Class._hasBgvideo (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1581-8c9787d/website.assets_wysiwyg.js:15:96)
    at Class._setActive (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1581-8c9787d/website.assets_wysiwyg.js:13:252)
    at Class._setActive (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1567-0056db0/1/web.assets_common_lazy.js:3764:371)
    at Class.setTarget (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1579-df564e9/web_editor.assets_wysiwyg.js:706:830)
    at Class.setTarget (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1579-df564e9/web_editor.assets_wysiwyg.js:734:163)
    at Class.prototype.<computed> [as setTarget] (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1567-0056db0/1/web.assets_common_lazy.js:3761:488)
    at Class.notify (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1579-df564e9/web_editor.assets_wysiwyg.js:706:757)
    at notifyForEachMatchedOption (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1579-df564e9/web_editor.assets_wysiwyg.js:656:179)
    at https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1579-df564e9/web_editor.assets_wysiwyg.js:654:547
    at Function._.each._.forEach (https://1974466-13-0-276f22.runbot24.odoo.com/web/content/1567-0056db0/1/web.assets_common_lazy.js:9:558)
```

Expected behavior:

Shouldn't lead to errors and simply delete all element contents.

**Comment by sdegueldre** [comment]
Hello @bosskopp , this is a known issue with the library that we are using for editing the content of the page using the mouse and keyboard, there are a lot of things that it doesn't do well and that cause strange problems (in your example, you can see that at some point the section gets split into two for example). Unfortunately, because the bugs it has are in very low level behaviour (like inserting any new node inside the document, or removing content when pressing backspace/delete), any attempt at a fix will have large unforeseen consequences on the entire behaviour of the editor, and this is not a risk that we are willing to take in stable versions.

For the moment, I'm very sorry to say that your best bet is to work around this issue: whenever possible, use the trashcan button to delete blocks of content, and use backspace only when modifying text, not when trying to remove it entirely.

The good news is that we are getting rid of this library for the next version, and are developing our own library instead, which will give us much finer control for future issues of this kind.

Thank you for your understanding. If you need any help working around the issue within the editor feel free to reply on this issue.

**Comment by malkindy** [comment]
hello, I am a new administrator for the odoo 15 onsite hosted. not sure if it the same problem but when we try to delete a google map block by clicking the waste bin we are not able to save the page and it hangs and the only way to continue is to close the page so we are not able to save changes!!!!

**Comment by sdegueldre** [comment]
> hello, I am a new administrator for the odoo 15 onsite hosted. not sure if it the same problem but when we try to delete a google map block by clicking the waste bin we are not able to save the page and it hangs and the only way to continue is to close the page so we are not able to save changes!!!!

Definitely not the same issue. Please open a ticket with Odoo support or create a new issue with a complete description of the problem.
