### ISSUE TITLE
Portal User not able to edit their profile

### ISSUE THREAD

**Issue by t-mohsin** [odoo/odoo#48808]
**Odoo Version**
Version: 13.0+e
Edition: Online
![stacktrace](https://user-images.githubusercontent.com/57789595/78213923-69c72d00-74cd-11ea-94d8-7b54f36f6b29.PNG)

**What are the steps to reproduce your issue?**

Go to courses -> On the right side where your name is appearing click edit -> your profile will be opened click edit button

**What is the current behavior that you observe?**

> Traceback (most recent call last):
> 
> File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
> 
> result = request.dispatch()
> 
> File "/home/odoo/src/odoo/13.0/odoo/http.py", line 809, in dispatch
> 
> r = self._call_function(**self.params)
> 
> File "/home/odoo/src/odoo/13.0/odoo/http.py", line 350, in _call_function
> 
> return checked_call(self.db, *args, **kwargs)
> 
> File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 93, in wrapper
> 
> return f(dbname, *args, **kwargs)
> 
> File "/home/odoo/src/odoo/13.0/odoo/http.py", line 339, in checked_call
> 
> result = self.endpoint(*a, **kw)
> 
> File "/home/odoo/src/odoo/13.0/odoo/http.py", line 915, in __call__
> 
> return self.method(*args, **kw)
> 
> File "/home/odoo/src/odoo/13.0/odoo/http.py", line 515, in response_wrap
> 
> response = f(*args, **kw)
> 
> File "/home/odoo/src/odoo/13.0/addons/website_profile/controllers/main.py", line 120, in view_user_profile_edition
> 
> user_id = int(kwargs.get('user_id'))
> 
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 

**What would be your expected behavior in this case?**

Edit page should be open where user can change their details and make their profile public.

Video/Screenshot link (optional):

**Comment by HirenDangar** [comment]
Yes I'm facing same issue. Getting traceback on the click on **Edit Profile** button.

![Selection_061](https://user-images.githubusercontent.com/38550879/78214269-6edaab00-74d2-11ea-9276-c92192094870.png)
![Selection_060](https://user-images.githubusercontent.com/38550879/78214276-7306c880-74d2-11ea-8edb-dcc180cb650d.png)

**Comment by minhhq09** [comment]
Same issue when I click on Edit profile.

<img width="1241" alt="Screen Shot 2020-04-07 at 9 29 07 PM" src="https://user-images.githubusercontent.com/28040072/78681582-262e5200-7917-11ea-8df0-6669a4249641.png">
