### ISSUE TITLE
Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function

### ISSUE THREAD

**Issue by thkfighter** [odoo/odoo#48923]
Impacted versions: 
odoo 12 community edition

Steps to reproduce:
I have not found the steps to reproduce the error.

Current behavior:
When I add followers under the opportunities of CRM, this error occurs.

Expected behavior:
No error.

Video/Screenshot link (optional):
```
Error:
Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function

http://192.168.10.90:8069/web/content/4558-ea89007/web.assets_backend.js:2427
Traceback:
TypeError: this._summernoteManager.saveCroppedImages is not a function
    at Class.commitChanges (http://192.168.10.90:8069/web/content/4558-ea89007/web.assets_backend.js:2427:74)
    at Class.prototype.<computed> [as commitChanges] (http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:3538:488)
    at http://192.168.10.90:8069/web/content/4558-ea89007/web.assets_backend.js:1574:235
    at Function._.map._.collect (http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:13:270)
    at Class.commitChanges (http://192.168.10.90:8069/web/content/4558-ea89007/web.assets_backend.js:1574:169)
    at http://192.168.10.90:8069/web/content/4558-ea89007/web.assets_backend.js:1561:1093
    at http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:802:681
    at fire (http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.10.90:8069/web/content/3764-384c3af/web.assets_common.js:802:649)
```

**Comment by Yenthe666** [comment]
Well, how do you expect somebody to fix something if there are no steps on how to reproduce it though? ;) Without steps there's not much we can do.

**Comment by pedrobaeza** [comment]
And this has been treated in past issues with same title: regenerate the assets bundles.

Closing as duplicated of #47623 for example.
