### ISSUE TITLE
odoo 12  error : NameError: name 'app' is not defined

### ISSUE THREAD

**Issue by movahhed** [odoo/odoo#48944]
Impacted versions: odoo 12
Hello dear friends please help me:
I've done some importing from an external source related to View database in  odoo12. It caused this error:
It should be noted that in every part of odoo that sets a new record, for example, you are referring to the project in this message, but it works.

error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/user_recent_log/models/user_log.py", line 54, in get_recent_log
    send_log()
  File "/odoo/custom/addons/user_recent_log/models/user_log.py", line 9, in send_log
    with app:
NameError: name 'app' is not defined

**Comment by Yenthe666** [comment]
Hi,

Sorry but this is an issue in the app "user_recent_log" which is not an app from Odoo itself.
Please report this issue to the author of this module.

Regards,
Yenthe

**Comment by movahhed** [comment]
Wow thanks my friends 
Solved uninstall madule and fixed

**Comment by Yenthe666** [comment]
Happy to hear that! Enjoy Odoo :)
