### ISSUE TITLE
[13.0] custom field dependency installation

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#49443]
Impacted versions:
13.0
Steps to reproduce:
- Install "Employee" `hr`
- Activate developer mode
- Go to "Employee"
- From the debug icon, click on "View Fields"
- Create a new one2many field with partners with name "Relative"
- Create a new DateTime field in "Employee" with the name "Last Created Relative" and depend on the "Relative" field with computed method return last created date.
- Install any other app related to "HR"

Current behavior:
appear below error
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 176, in load_module_graph
    registry.setup_models(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 288, in setup_models
    for path in transitive_dependencies(field):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 274, in transitive_dependencies
    for seq2 in transitive_dependencies(seq1[-1], seen + [field]):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 272, in transitive_dependencies
    for seq1 in dependencies[field]:
KeyError: hr.employee.x_last_create_relative
```

**Comment by pedrobaeza** [comment]
I personally don't think that expanding the system this way is the most mantenible one, but if the system allows it, indeed it should be supported.

@rco-odoo not sure if your team should handle this.

**Comment by abdallamhafeez** [comment]
@pedrobaeza I made same customization in version 12.0 and it works fine over a year then when I make an upgrade to 13.0, it appears issue in installation only although functionality is working.
