### ISSUE TITLE
Building Themes

### ISSUE THREAD

**Issue by munruf** [odoo/odoo#4950]
Hi,
I would like to study how to make a theme like it is mentioned at https://www.odoo.com/documentation/8.0/howtos/themes.html
And I have got an error, immediately when I try to install "Dummy Theme" like it is mentioned in the document at the section "Static Page Creating a new template"
My odoo version is 8.0 running on ubuntu 14.04 desktop
here the error log:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 562, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 299, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 791, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 395, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 974, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
XMLSyntaxError: Document is empty, line 1, column 1
Could You please help me?
to pass this stage an to go forward?

**Comment by lukebranch** [comment]
@munruf ,

This is the wrong place to ask this kind of question. The Odoo Issues are for bug/issue reports only, not for general help questions.

Please ask this question on <a href="http://help.odoo.com">help.odoo.com</a> and close this issue and I will provide you with some details to get you started with troubleshooting.

From your error report here, it looks like the first line of one of your XML files in your theme module has been either improperly indented, or it has been pushed down one line.

This is improper XML syntax and therefore the interpreter has stopped the file from being parsed.

Look through all of your XML files in your module and find the one with either an indent or one that has been pushed down one line from the top.

Please only use the github.com/odoo/odoo/issues for reporting actual bugs/issues and provide steps to reproduce the issue.

**Comment by munruf** [comment]
Sorry and thanks.

**Comment by lukebranch** [comment]
@munruf ,

No problem. Feel free to start a question thread in the help forum in Odoo (help.odoo.com) and i'd be glad to offer advice on your issue if it has not been resolved.

**Comment by zeeshangithub** [comment]
hey..my XML is in correct formate but error is still there.
any suggestion ??

**Comment by zeeshangithub** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\openerp\addons\web\controllers\main.py", line 952, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\openerp\addons\web\controllers\main.py", line 940, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\openerp\addons\web\controllers\main.py", line 939, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\openerp\addons\base\module\module.py", line 447, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\modules\loading.py", line 176, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\modules\loading.py", line 118, in _load_data
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\tools\convert.py", line 901, in convert_file
  File "C:\Program Files (x86)\Odoo 8.0-20150929\server\.\openerp\tools\convert.py", line 974, in convert_xml_import
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src\lxml\lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src\lxml\lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src\lxml\lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src\lxml\lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91757)
XMLSyntaxError: Document is empty, line 1, column 1

**Comment by dirtyhandsphp** [comment]
Guys, I am facing the same issue...Any reason?

**Comment by yanndc** [comment]
Same issue here when trying to open a group from the Odoo Chat application
