### ISSUE TITLE
new odoo server after install module signed in error can't signed in

### ISSUE THREAD

**Issue by silversparking** [odoo/odoo#50099]
odoo versions:13.0

![image](https://user-images.githubusercontent.com/18497151/80185071-5297dd00-863e-11ea-9122-70b685126507.png)
2020-04-24 06:55:30,397 17326 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:30] "POST /web/action/load HTTP/1.0" 200 - 19 0.019 5.539
2020-04-24 06:55:30,487 15962 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:30] "GET /web/static/src/xml/crash_manager.xml HTTP/1.0" 200 - - - -
2020-04-24 06:55:34,998 15964 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 170] 
2020-04-24 06:55:35,002 15964 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web HTTP/1.0" 303 - 1 0.000 0.005
2020-04-24 06:55:35,040 15962 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 170] 
2020-04-24 06:55:35,129 15962 ERROR erp-0 odoo.addons.http_routing.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_9
  File "<template>", line 2, in body_call_content_7
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/opt/erp/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/opt/erp/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/erp/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/erp/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/opt/erp/odoo/http.py", line 1236, in flatten
    self.response.append(self.render())
  File "/opt/erp/odoo/http.py", line 1229, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_ui_view.py", line 1174, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/erp/addons/website/models/ir_ui_view.py", line 345, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/erp/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_ui_view.py", line 1182, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_9
  File "<template>", line 2, in body_call_content_7
TypeError: object of type 'NoneType' has no len()

Error to render compiling AST
TypeError: object of type 'NoneType' has no len()
Template: web.login
Path: /t/t/t
Node: <t t-set="form_small" t-value="True" t-if="len(providers) &gt; 2"/>
            
 
2020-04-24 06:55:35,399 15962 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/login HTTP/1.0" 500 - 235 0.142 0.219
2020-04-24 06:55:35,479 15964 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.0" 200 - - - -
2020-04-24 06:55:35,516 17326 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/static/lib/jquery/jquery.js HTTP/1.0" 200 - - - -
2020-04-24 06:55:35,529 15964 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.0" 200 - - - -
2020-04-24 06:55:35,530 17326 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.0" 200 - - - -
2020-04-24 06:55:35,530 15962 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /web/static/lib/bootstrap/js/util.js HTTP/1.0" 200 - - - -
2020-04-24 06:55:35,867 15962 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 170] 
2020-04-24 06:55:35,880 15962 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:35] "GET /favicon.ico HTTP/1.0" 200 - 8 0.004 0.010
2020-04-24 06:55:39,306 15967 DEBUG ? odoo.service.server: WorkerCron (15967) polling for jobs 
2020-04-24 06:55:39,315 15967 WARNING ? odoo.addons.base.models.ir_cron: Skipping database erp-0 because of modules to install/upgrade/remove. 
2020-04-24 06:55:39,315 15967 DEBUG ? odoo.service.server: WorkerCron (15967) erp-0 time:0.002s mem: 395724.0k -> 395724.0k (diff: 0.0k) 
2020-04-24 06:55:45,970 15965 INFO erp-0 longpolling: 220.248.23.58 - - [2020-04-24 06:55:45] "POST /longpolling/poll HTTP/1.0" 200 383 50.016857 
2020-04-24 06:55:51,958 17326 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 170] 
2020-04-24 06:55:52,114 15968 DEBUG ? odoo.service.server: WorkerCron (15968) polling for jobs 
2020-04-24 06:55:52,150 15968 WARNING ? odoo.addons.base.models.ir_cron: Skipping database erp-0 because of modules to install/upgrade/remove. 
2020-04-24 06:55:52,150 15968 DEBUG ? odoo.service.server: WorkerCron (15968) erp-0 time:0.012s mem: 395724.0k -> 395724.0k (diff: 0.0k) 
2020-04-24 06:55:52,615 17326 INFO erp-0 odoo.models.unlink: User #4 deleted ir.attachment records with IDs: [564] 
2020-04-24 06:55:53,607 17326 INFO erp-0 odoo.models.unlink: User #4 deleted ir.attachment records with IDs: [565] 
2020-04-24 06:55:54,476 17326 INFO erp-0 odoo.models.unlink: User #4 deleted ir.attachment records with IDs: [566] 
2020-04-24 06:55:55,017 17326 INFO erp-0 odoo.models.unlink: User #4 deleted ir.attachment records with IDs: [567] 
2020-04-24 06:55:55,171 17326 INFO erp-0 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2020-04-24 06:55:55,172 17326 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:55] "GET / HTTP/1.0" 200 - 981 0.555 2.660
2020-04-24 06:55:55,370 15964 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 171] 
2020-04-24 06:55:55,371 15964 INFO erp-0 odoo.modules.registry: Invalidating all model caches after database signaling. 
2020-04-24 06:55:55,371 15962 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 170 -> 171] 
2020-04-24 06:55:55,371 15962 INFO erp-0 odoo.modules.registry: Invalidating all model caches after database signaling. 
2020-04-24 06:55:55,394 15962 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:55] "GET /web/content/594-4746f2f/1/web.assets_common.css HTTP/1.0" 200 - 9 0.012 0.012
2020-04-24 06:55:55,397 15964 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:55] "GET /web/content/595-7488966/1/web.assets_frontend.css HTTP/1.0" 200 - 9 0.011 0.018
2020-04-24 06:55:55,438 17326 INFO ? werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:55] "GET /web/static/src/img/odoo_logo_tiny.png HTTP/1.0" 200 - - - -
2020-04-24 06:55:55,556 15962 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 171 -> 171] 
2020-04-24 06:55:55,572 15962 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:55] "GET /web/content/596-d7f3217/1/web.assets_common_lazy.js HTTP/1.0" 200 - 6 0.002 0.015
2020-04-24 06:55:56,387 17326 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 171 -> 171] 
2020-04-24 06:55:56,399 17326 INFO erp-0 werkzeug: 220.248.23.58 - - [24/Apr/2020 06:55:56] "GET /web/content/597-c52ca9b/1/web.assets_frontend_lazy.js HTTP/1.0" 200 - 8 0.003 0.010
2020-04-24 06:55:58,470 15962 DEBUG erp-0 odoo.modules.registry: Multiprocess signaling check: [Registry - 3 -> 3] [Cache - 171 -> 171] 
2020-04-24 06:55:58,542 15962 ERROR erp-0 odoo.addons.http_routing.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_37
  File "<template>", line 2, in body_call_content_35
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/opt/erp/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/opt/erp/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/erp/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/erp/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/opt/erp/odoo/http.py", line 1236, in flatten
    self.response.append(self.render())
  File "/opt/erp/odoo/http.py", line 1229, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_ui_view.py", line 1174, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/erp/addons/website/models/ir_ui_view.py", line 345, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/erp/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_ui_view.py", line 1182, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/erp/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/opt/erp/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_37
  File "<template>", line 2, in body_call_content_35
TypeError: object of type 'NoneType' has no len()

Error to render compiling AST
TypeError: object of type 'NoneType' has no len()
Template: web.login
Path: /t/t/t
Node: <t t-set="form_small" t-value="True" t-if="len(providers) &gt; 2"/>

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
