### ISSUE TITLE
[8.0] Server Error while trying to configurate sale. AttributeError: 'res.company' object has no attribute 'project_time_mode_id'

### ISSUE THREAD

**Issue by FlorianO** [odoo/odoo#5010]
I searched for this error message, but didn't found a hint.
Somehow after a bit of configuration we are in a strange situation.
We created several companies and deleted them and this let to this problem:

Impacted versions:
- latest version from git

Steps to reproduce:
1. Go to configuration Menu
2. Click on Sales.
3. Crash.

Current behavior:
- Error  Message:
  Traceback (most recent call last):
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 526, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 563, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/odoo-staging/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 792, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/odoo-staging/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo-staging/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-staging/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/odoo-staging/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-staging/odoo/addons/sale_stock/res_config.py", line 64, in default_get
    res = super(sale_configuration, self).default_get(cr, uid, fields, context)
  File "/home/odoo/odoo-staging/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo-staging/odoo/addons/sale/res_config.py", line 91, in default_get
    res['time_unit'] = user.company_id.project_time_mode_id.id
  AttributeError: 'res.company' object has no attribute 'project_time_mode_id'

Expected behavior:
Show configuration view of sales.

**Comment by Yenthe666** [comment]
Hi @FlorianO,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
