### ISSUE TITLE
Error when trying to insert pictogram in HTML field

### ISSUE THREAD

**Issue by brasta** [odoo/odoo#50314]
Impacted versions: Odoo (enterprise 12) https://runbot.odoo.com/runbot/build/2396173

Steps to reproduce: Go to user preferences and navigate to "pictogram"

Current behavior:
Error:
```
`Error:
Uncaught TypeError: this.fetchPage is not a function

https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1099-c6eb5d1/web_editor.assets_editor.js:303
Traceback:
TypeError: this.fetchPage is not a function
    at Class.goToPage (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1099-c6eb5d1/web_editor.assets_editor.js:303:225)
    at Class._setActive (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1099-c6eb5d1/web_editor.assets_editor.js:361:239)
    at Class._onTabChange (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1099-c6eb5d1/web_editor.assets_editor.js:361:1339)
    at HTMLAnchorElement.<anonymous> (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:3643:11)
    at HTMLDivElement.dispatch (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:865:173)
    at Object.trigger (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:886:211)
    at HTMLAnchorElement.<anonymous> (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:937:147)
    at Function.each (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:625:767)
    at jQuery.fn.init.each (https://2396173-12-0-e1ef37.runbot39.odoo.com/web/content/1195-3d9310d/web.assets_common.js:613:643)`
```
Expected behavior:
Being able to select and insert a pictogram
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
What do you mean with pictogram? Everything seems to work fine at my end?

**Comment by brasta** [comment]
@Yenthe666  Sorry, I should have clarified better. When trying to insert an image in the signature of the user, and you navigate to pictogram in the popup you get the error.

**Comment by Yenthe666** [comment]
I can confirm the bug:
![image](https://user-images.githubusercontent.com/6352350/80489760-96e9ec80-8960-11ea-8834-f59d999e6125.png)

At some point in the past this once also existed actually. @JKE-be for somebody from your team

**Comment by Yenthe666** [comment]
Added an OPW for this. OPW is `2256767`

**Comment by brasta** [comment]
I don't know if this is related or a seperate bug. 

But the pictograms in a signature are not showing in generated emails.

On the same runbot environment (and most recent one same issue):
- insert some icons in user signature.
- Disable auto delete on "sale order: send by email" 
- go to random SO and send by email and confirm
- go over to settings/technical/emails en open email
- pictograms not present in body email

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/687ed32d967390a8602798f60c909aa74495c4f2 🥳
