### ISSUE TITLE
Error creating content in e-learning since /slides/

### ISSUE THREAD

**Issue by sanykTron** [odoo/odoo#50513]
Impacted versions: 13

Steps to reproduce: 

Go to /slides/ select a course,

select add content:
![image](https://user-images.githubusercontent.com/18546916/80746753-02aa9180-8ae8-11ea-9947-8433946b1edb.png)

When you decide what kind of content you want to upload, you get the error.

Current behavior:
![image](https://user-images.githubusercontent.com/18546916/80746962-4ac9b400-8ae8-11ea-9d14-8aa1b711e66f.png)

Expected behavior:

No problems to upload content.

The problem that appears is:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/website_slides/controllers/main.py", line 859, in create_slide
    channel._resequence_slides(slide, category_id)
  File "/opt/odoo13/odoo/addons/website_slides/models/slide_channel.py", line 613, in _resequence_slides
    force_category_id = force_category.id if force_category else slide.category_id.id
AttributeError: 'int' object has no attribute 'id'

**Comment by Yenthe666** [comment]
@jubodoo

**Comment by sswapnesh** [comment]
Has been fixed in https://github.com/odoo/odoo/pull/49641

**Comment by pedrobaeza** [comment]
OK, closing then as fixed.
