### ISSUE TITLE
12.0 Error Export

### ISSUE THREAD

**Issue by hanydaba** [odoo/odoo#50515]
Impacted versions:12

Steps to reproduce: Export Report

Current behavior:Error

Expected behavior: Export Excel sheet

Video/Screenshot link (optional):
![Export error](https://user-images.githubusercontent.com/64616049/80763163-3adcbf00-8b3e-11ea-8f1b-004e6ba1d6af.PNG)

**Comment by Yenthe666** [comment]
Hi there,

Please add reproducible steps.

**Comment by hanydaba** [comment]
Customer> Choose Customer> General leadger> Export xlsx


Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/custom/entreprice-12.0/account_reports/controllers/main.py", line 31, in get_report
    report_obj.get_xlsx(options, response)
  File "/odoo/custom/entreprice-12.0/account_reports/models/account_report.py", line 1163, in get_xlsx
    sheet.write_datetime(y + y_offset, 0, lines[y]['name'], date_default_col1_style)
  File "/usr/local/lib/python3.6/dist-packages/xlsxwriter/worksheet.py", line 64, in cell_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/xlsxwriter/worksheet.py", line 688, in write_datetime
    number = self._convert_date_time(date)
  File "/usr/local/lib/python3.6/dist-packages/xlsxwriter/worksheet.py", line 3526, in _convert_date_time
    return datetime_to_excel_datetime(dt_obj, self.date_1904)
  File "/usr/local/lib/python3.6/dist-packages/xlsxwriter/utility.py", line 637, in datetime_to_excel_datetime
    raise TypeError("Unknown or unsupported datetime type")
TypeError: Unknown or unsupported datetime type

<img width="1243" alt="Screen Shot 2020-05-04 at 12 06 37 PM" src="https://user-images.githubusercontent.com/64616049/80955525-bd47d600-8dff-11ea-84fa-6d7aff0b8e6a.png">

**Comment by Yenthe666** [comment]
Hi,

This works fine on the latest Odoo 12.0 (on runbot.odoo.com).
Can you please try to reproduce the problem there?

**Comment by hanydaba** [comment]
Where can I find the solution?  can see anything help on runbit.oddo.com!

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/wiki/Contributing#reporting-issues for more info. You need to test this behaviour on a default Odoo instance.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
