### ISSUE TITLE
export error odoo 11 ce

### ISSUE THREAD

**Issue by rimedia** [odoo/odoo#50517]
Impacted versions:
odoo 11ce
Steps to reproduce:

Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 77, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 1413, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 1395, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 791, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 715, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 679, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

Your Odoo instance is pretty outdated, you seem to have last updated it on 18/04/2018. In the meanwhile a lot of issues have been fixed.
Can you add reproducible steps and can you test this on the latest Odoo 11 instance please?

Regards,
Yenthe

**Comment by rimedia** [comment]
Hi,

what is reproducible steps..

Regards
Riyaad

**Comment by Yenthe666** [comment]
A clear list of steps to follow that shows how we can reproduce this behaviour. Without this and without testing it on the latest version of 11.0 this will be closed.

**Comment by rimedia** [comment]
if i buy odoo enterprise 13 can i just transfer the odoo 11 database to it?

**Comment by Yenthe666** [comment]
No, you will need a migration but this has nothing to do with this ticket. We still need reproducible steps or this report will be closed.

**Comment by rimedia** [comment]
This error happens when i try to export my inventory items to csv or excel

**Comment by Yenthe666** [comment]
Your Odoo instance is incredible outdated though. So, can you reproduce it on the latest 11.0 or on a runbot.odoo.com test instance? We really need reproducible steps on the latest 11.0

**Comment by rimedia** [comment]
i don't know how to do this ..if i give you a loggin access can you do it?

**Comment by Yenthe666** [comment]
No, because we do not need a login but a reproducible step on the latest Odoo instances.
See https://github.com/odoo/odoo/wiki/Contributing#reporting-issues for extra info.
Please try it on runbot.odoo.com

**Comment by rimedia** [comment]
i have try it on the runbot ..it works fine there

**Comment by rimedia** [comment]
Impacted versions:
 
 - 11.0
 
Steps to reproduce:
 
 1. go to inventory
 2. master data => products
 3. select all products => export to file
 
Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 77, in wrap
    return f(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 1413, in index
    return self.base(data, token)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/addons/web/controllers/main.py", line 1395, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 791, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 715, in _export_rows
    xids = dict(self.__ensure_xml_id(skip=['id'] not in fields))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180418-py3.6.egg/odoo/models.py", line 679, in __ensure_xml_id
    columns=fields,
psycopg2.ProgrammingError: copy_from cannot be used with an asynchronous callback.

**Comment by Yenthe666** [comment]
@rimedia if it works fine on a runbot and not on your instance it means you need to update your own Odoo instance. That's not something we can help you with then.
