### ISSUE TITLE
Werkzeug 0.10

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#5057]
We got an issue using Werkzeug 0.10 when the application is shutting down:

* Impacted versions

 7.0 and above

* Steps to reproduce

Launch unit test using Werkzeug 0.10, the error appear when the server is shutting down

* Current behavior

```
2015-02-03 09:42:28,065 23608 INFO openerp_test openerp.service.server: Initiating shutdown
2015-02-03 09:42:28,065 23608 INFO openerp_test openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp-server", line 5, in <module>
openerp.cli.main()
File "/home/travis/odoo-8.0/openerp/cli/__init__.py", line 71, in main
o.run(args)
File "/home/travis/odoo-8.0/openerp/cli/server.py", line 174, in run
main(args)
File "/home/travis/odoo-8.0/openerp/cli/server.py", line 168, in main
rc = openerp.service.server.start(preload=preload, stop=stop)
File "/home/travis/odoo-8.0/openerp/service/server.py", line 942, in start
rc = server.run(preload, stop)
File "/home/travis/odoo-8.0/openerp/service/server.py", line 352, in run
self.stop()
File "/home/travis/odoo-8.0/openerp/service/server.py", line 320, in stop
self.close_socket(self.httpd.socket)
File "/home/travis/odoo-8.0/openerp/service/server.py", line 213, in close_socket
sock.shutdown(socket.SHUT_RDWR)
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
File "/usr/lib/python2.7/socket.py", line 170, in _dummy
raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

* Expected behavior

no error!

We are going to use 0.9 series until migration would be done as propose [here](https://github.com/OCA/maintainer-quality-tools/pull/161).

**Comment by antwal** [comment]
Hi,

same problem, this is the error:

[root@172.36.12.108 odoo]# /etc/init.d/odoo stop
Interruzione di Odoo Server Daemon (odoo-server):          [  OK  ]
[root@172.36.12.108 odoo]# Traceback (most recent call last):
  File "/opt/odoo/openerp-server", line 5, in <module>
    openerp.cli.main()
  File "/opt/odoo/openerp/cli/__init__.py", line 71, in main
    o.run(args)
  File "/opt/odoo/openerp/cli/server.py", line 180, in run
    main(args)
  File "/opt/odoo/openerp/cli/server.py", line 174, in main
    rc = openerp.service.server.start(preload=preload, stop=stop)
  File "/opt/odoo/openerp/service/server.py", line 948, in start
    rc = server.run(preload, stop)
  File "/opt/odoo/openerp/service/server.py", line 364, in run
    self.stop()
  File "/opt/odoo/openerp/service/server.py", line 321, in stop
    self.close_socket(self.httpd.socket)
  File "/opt/odoo/openerp/service/server.py", line 213, in close_socket
    sock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib64/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

Thanks.

**Comment by moylop260** [comment]
FYI you can use [requirements.txt](https://raw.githubusercontent.com/odoo/odoo/8.0/requirements.txt) file of odoo.
You will see version Werkzeug: 0.9.6

You can fix it using next command:
```
pip install --upgrade Werkzeug==0.9.6
```

**Comment by KangOl** [comment]
Fixed by a091de8 in 7.0 (will be forward-ported to 8.0)

**Comment by akram1** [comment]
Werkzeug  0.10.4 fixed this problem

**Comment by petrus-v** [comment]
@akram1,

Thanks for notification.
