### ISSUE TITLE
8.0 Crash when trying to reconcile 20 invoices with a bank account move

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5063]
Here is the scenario to reproduce the bug with an up-to-date odoo 8.0 from github:

1) Install the module test_crash_reconcile that I available here: http://people.via.ecp.fr/~alexis/test_crash_reconcile.zip
When asked for the accounting package, select "France" (it is required because my YAML test uses the accounts on the French chart of accounts)
When asked for the accounting options, keep the default values and validate.

This module only contains 1 YAML test that create 20 customer invoices, validate them, then it create an account move in the bank journal and eventually it tries the reconcile the 20 invoices with the bank account move.
It is important to have a high number of invoices, because it doesn't crash when the number of invoices is not high enough.

2) Restart Odoo with the following command line:
```
./odoo.py -c <your_config_file> -d <your_db> -u test_crash_reconcile --log-level=test --test-enable
```
It works well, no crash.

3) Install the purchase module

4) Restart Odoo with the following command line:
```
./odoo.py -c <your_config_file> -d <your_db> -u test_crash_reconcile --log-level=test --test-enable
```

You will get a crash with a huge backtrace. I share the full logs here: http://people.via.ecp.fr/~alexis/crash_odoo_80_reconcile.txt

I copy here the server logs with only the end of the backtrace (the backtrace is too big to be posted here):

```
12:25 alexis@wide ~/new_boite/dev/odoo % ./odoo.py -c ../config-80-official-only -d o8_bugrec2 -u test_crash_reconcile --log-level=test --test-enable
2015-02-04 11:25:41,293 31039 INFO ? openerp: OpenERP version 8.0
2015-02-04 11:25:41,293 31039 INFO ? openerp: addons paths: ['/home/alexis/.local/share/OpenERP/addons/8.0', u'/home/alexis/new_boite/dev/odoo/openerp/addons', u'/home/alexis/new_boite/dev/odoo/addons', u'/home/alexis/new_boite/dev/test-80']
2015-02-04 11:25:41,294 31039 INFO ? openerp: database hostname: localhost
2015-02-04 11:25:41,294 31039 INFO ? openerp: database port: 5432
2015-02-04 11:25:41,294 31039 INFO ? openerp: database user: alexis
2015-02-04 11:25:41,487 31039 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-02-04 11:25:41,512 31039 INFO o8_bugrec2 openerp.modules.loading: loading 1 modules...
2015-02-04 11:25:41,723 31039 INFO o8_bugrec2 openerp.modules.loading: 1 modules loaded in 0.21s, 0 queries
2015-02-04 11:25:44,861 31039 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-02-04 11:25:45,405 31039 INFO o8_bugrec2 openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2015-02-04 11:25:45,612 31039 INFO o8_bugrec2 openerp.http: HTTP Configuring static files
2015-02-04 11:25:46,046 31039 INFO o8_bugrec2 openerp.modules.loading: loading 44 modules...
2015-02-04 11:25:46,055 31039 INFO o8_bugrec2 passlib.registry: registered crypt handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2015-02-04 11:25:46,056 31039 INFO o8_bugrec2 passlib.registry: registered crypt handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2015-02-04 11:25:47,704 31039 INFO o8_bugrec2 openerp.modules.module: module test_crash_reconcile: creating or updating database tables
2015-02-04 11:25:47,873 31039 INFO o8_bugrec2 openerp.modules.loading: loading test_crash_reconcile/test/crash_reconcile.yml
2015-02-04 11:26:16,732 31039 ERROR o8_bugrec2 openerp.tools.yaml_import: """""""""""""""""""maximum recursion depth exceeded" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/yaml_import.py", line 894, in process
    self._process_node(node)
[......]
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/__init__.py", line 40, in trg_write
    return WorkflowService.new(cr, uid, res_type, res_id).write()
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/service.py", line 53, in write
    WorkflowInstance(self.session, self.record, {'id': instance_id}).update()
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/instance.py", line 86, in update
    WorkflowItem(self.session, self.record, work_item_values).process(stack=stack)
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/workitem.py", line 229, in _split_test
    if self.wkf_expr_check(transition,signal):
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/workitem.py", line 333, in wkf_expr_check
    return self.wkf_expr_eval_expr(transition['condition'])
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/workitem.py", line 290, in wkf_expr_eval_expr
    env = Environment(self.session, self.record)
  File "/home/alexis/new_boite/dev/odoo/openerp/workflow/workitem.py", line 53, in __init__
    self.obj = openerp.registry(self.cr.dbname)[self.model]
  File "/home/alexis/new_boite/dev/odoo/openerp/__init__.py", line 64, in registry
    return modules.registry.RegistryManager.get(database_name)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/registry.py", line 332, in get
    return cls.registries[db_name]
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/func.py", line 66, in wrapper
    return func(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/lru.py", line 38, in __getitem__
    self[a[0]] = a[1]
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/func.py", line 66, in wrapper
    return func(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/tools/lru.py", line 44, in __setitem__
    del self[obj]
ValueError: """""""""""""""""""maximum recursion depth exceeded" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'" while evaluating
u'confirm_paid()'
2015-02-04 11:26:17,129 31039 INFO o8_bugrec2 openerp.modules.loading: 44 modules loaded in 31.08s, 0 queries
2015-02-04 11:26:18,490 31039 ERROR o8_bugrec2 openerp.modules.loading: At least one test failed when loading the modules.
2015-02-04 11:26:18,516 31039 INFO o8_bugrec2 openerp.modules.module: openerp.addons.report.tests.test_reports running tests.
2015-02-04 11:26:18,517 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: test_reports (openerp.addons.report.tests.test_reports.TestReports)
2015-02-04 11:26:18,557 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_inventory
2015-02-04 11:26:18,898 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report account.report_invoice
2015-02-04 11:26:19,106 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_location_barcode
2015-02-04 11:26:19,127 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_lot_barcode
2015-02-04 11:26:19,153 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_package_barcode_small
2015-02-04 11:26:19,155 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: no record found skipping report stock.report_package_barcode_small
2015-02-04 11:26:19,169 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_package_barcode
2015-02-04 11:26:19,170 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: no record found skipping report stock.report_package_barcode
2015-02-04 11:26:19,187 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report stock.report_picking
2015-02-04 11:26:19,322 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report purchase.report_purchaseorder
2015-02-04 11:26:19,468 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: testing report purchase.report_purchasequotation
2015-02-04 11:26:19,527 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: Ran 1 test in 1.010s
2015-02-04 11:26:19,527 31039 INFO o8_bugrec2 openerp.addons.report.tests.test_reports: OK
2015-02-04 11:26:19,557 31039 INFO o8_bugrec2 openerp.modules.module: openerp.addons.base.tests.test_xmlrpc running tests.
2015-02-04 11:26:19,558 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: test_01_xmlrpc_login (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-02-04 11:26:19,558 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: ` Try to login on the common service.
2015-02-04 11:26:20,088 31039 INFO o8_bugrec2 openerp.service.common: successful login from 'admin' using database 'o8_bugrec2'
2015-02-04 11:26:20,088 31039 INFO o8_bugrec2 werkzeug: 127.0.0.1 - - [04/Feb/2015 11:26:20] "POST /xmlrpc/2/common HTTP/1.1" 200 -
2015-02-04 11:26:20,090 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: test_xmlrpc_ir_model_search (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-02-04 11:26:20,091 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2015-02-04 11:26:20,602 31039 INFO o8_bugrec2 werkzeug: 127.0.0.1 - - [04/Feb/2015 11:26:20] "POST /xmlrpc/2/object HTTP/1.1" 200 -
2015-02-04 11:26:20,617 31039 INFO o8_bugrec2 werkzeug: 127.0.0.1 - - [04/Feb/2015 11:26:20] "POST /xmlrpc/2/object HTTP/1.1" 200 -
2015-02-04 11:26:20,625 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: Ran 2 tests in 1.068s
2015-02-04 11:26:20,626 31039 INFO o8_bugrec2 openerp.addons.base.tests.test_xmlrpc: OK
2015-02-04 11:26:20,626 31039 INFO o8_bugrec2 openerp.modules.loading: All post-tested in 2.13s, 402 queries
2015-02-04 11:26:20,628 31039 INFO o8_bugrec2 openerp.models: Computing parent left and right for table account_account...
2015-02-04 11:26:21,740 31039 INFO o8_bugrec2 openerp.addons.base.ir.ir_http: Generating routing map
2015-02-04 11:27:11,818 31039 INFO o8_bugrec2 werkzeug: 127.0.0.1 - - [04/Feb/2015 11:27:11] "POST /longpolling/poll HTTP/1.1" 200 -
^C2015-02-04 11:27:15,331 31039 INFO o8_bugrec2 openerp.service.server: Initiating shutdown
2015-02-04 11:27:15,331 31039 INFO o8_bugrec2 openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

**Comment by alexis-via** [comment]
You also get the crash with, at step 3 of the above scenario, you install the "sale" module instead of the "purchase" module.

**Comment by alexis-via** [comment]
My latest tests shows that it works up to 18 invoices, and it starts crashing when you use 19 invoices.

**Comment by alexis-via** [comment]
This bug also affects odoo master, with the same module test_crash_reconcile and the same scenario.

**Comment by odony** [comment]
@alexis-via Thanks for the detailed reproduction info! We've been working on a patch that should solve this issue. Could you try PR #4905 and see if it fixes the issue?
It's a sensitive patch so extra reviews/tests would be great before we merge it.
Thanks,

**Comment by alexis-via** [comment]
This bug does NOT affect 7.0 (testing it requires a small change in test_crash_reconcile on the import of the workflow stuff)

**Comment by alexis-via** [comment]
@odony I have applied the patch of the PR you mentioned, and the bug doesn't happen any more when trying to reconcile 20 invoices ! THANKS !

**Comment by beledouxdenis** [comment]
Rev. c9154e08aab9114ce1e269f91c7c6d3972d4b114 closes this issue.
