### ISSUE TITLE
Weird error for view definition..

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5065]
I'm getting this error when trying to install my module. It says that field 'state' does not exist. But there is no such field in view or model at all. So where on earth that field comes from?

There is a problem with this view:

``` xml
        <record id="view_employee_qualification_form" model="ir.ui.view">
            <field name="name">hr.employee.form</field>
            <field name="model">hr.employee</field>
            <field name="inherit_id" ref="hr.view_employee_form"/>
            <field name="arch" type="xml">
                <page string="Personal Information" position="after">
                    <page string="Qualifications">
                        <field name="qualification_ids">
                            <tree editable="bottom">
                                <field name="qualification_id" attrs="{'required': True}"/>
                                <field name="date_from" attrs="{'required': True}"/>
                                <field name="date_to"/>
                                <field name="description"/>
                                <field name="active"/>
                            </tree>
                        </field>
                    </page>
                </page>
            </field>
        </record>
```

But I don't see anything wrong with that view. Even more strange is that module on my local server, installs fine, but on remote, it gives this strange error. If I remove this view (on remote server. On my local server it works even with this view), then it installs module without any errors.

I just don't get it where this 'state' field come from.

The Error:

```
  File "/home/user/odoo/8.0/server/openerp/models.py", line 1282, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `state` does not exist

Error context:
View `hr.employee.form`
[view_id: 1099, xml_id: n/a, model: hr.employee, parent_id: 863]" while parsing /home/user/odoo/8.0/addons/hr_qualification/views/hr_qualification_view.xml:39, near
<record id="view_employee_qualification_form" model="ir.ui.view">
            <field name="name">hr.employee.form</field>
            <field name="model">hr.employee</field>
            <field name="inherit_id" ref="hr.view_employee_form"/>
            <field name="arch" type="xml">
                <page string="Personal Information" position="after">
                    <page string="Qualifications">
                        <field name="qualification_ids">
                            <tree editable="bottom">
                                <field name="qualification_id" attrs="{'required': True}"/>
                                <field name="date_from" attrs="{'required': True}"/>
                                <field name="date_to"/>
                                <field name="description"/>
                                <field name="active"/>
                            </tree>
                        </field>
                    </page>
                </page>
            </field>
        </record>
```

**Comment by pdc-online** [comment]
I got a similar problem, but no solution yet.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by roseragin** [comment]
> Hi @oerp-odoo,
> 
> Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
> At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
> If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
> 
> Regards,
> Yenthe

hi,
i got similar error in odoo12



Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view audit.rule.search definition in custom/addons/smile_audit_new/views/audit_rule_view.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3838, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3752, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3569, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3284, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3430, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view audit.rule.search definition in custom/addons/smile_audit_new/views/audit_rule_view.xml
None" while parsing /opt/odoo12/odoo-custom-addons/custom/addons/smile_audit_new/views/audit_rule_view.xml:25, near
<record id="view_audit_rule_search" model="ir.ui.view">
            <field name="name">audit.rule.search</field>
            <field name="model">audit.rule</field>
            <field name="type">search</field>
            <field name="arch" type="xml">
                <search string="Audit Rules">
                    <filter name="active" string="Active Rules" domain="[('active','=',True)]"/>
                    <separator/>
                    <filter string="Log Creation" domain="[('log_create','=',True)]"/>
                    <filter string="Log Update" domain="[('log_write','=',True)]"/>
                    <filter string="Log Deletion" domain="[('log_unlink','=',True)]"/>
                    <field name="name"/>
                    <field name="model_id"/>
                </search>
            </field>
        </record>
