### ISSUE TITLE
[8.0] Override sale order model got exception KeyError: 'sale.order' on startup

### ISSUE THREAD

**Issue by bcfelix** [odoo/odoo#5077]
I  am trying to override sale.order model with the following code

```python
class sale_order(models.Model):
    _inherit = 'sale.order'
```

When I start the server, I got the following error.

Traceback (most recent call last):
  File "C:\Users\Felix\git\odoo\openerp\service\server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "C:\Users\Felix\git\odoo\openerp\modules\registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\Felix\git\odoo\openerp\modules\loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "C:\Users\Felix\git\odoo\openerp\modules\loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Users\Felix\git\odoo\openerp\modules\loading.py", line 158, in load_module_graph
    models = registry.load(cr, package)
  File "C:\Users\Felix\git\odoo\openerp\modules\registry.py", line 148, in load
    model = cls._build_model(self, cr)
  File "C:\Users\Felix\git\odoo\openerp\models.py", line 595, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "C:\Users\Felix\git\odoo\openerp\modules\registry.py", line 101, in __getitem__
    return self.models[model_name]
KeyError: 'sale.order'

Note, I have override some other models without any problem, just "sale.order" model.

Please help. Thanks.

**Comment by bcfelix** [comment]
Sorry, it solved after I added 'sale' on the depends list in __openerp__.py

**Comment by slimit** [comment]
For me too :)

**Comment by wecole** [comment]
I get this error KeyError: u'search.business.category' in odoo 9.0. but the model exists.what can be the issue?
