### ISSUE TITLE
Odoo 10 server running issue

### ISSUE THREAD

**Issue by Mohamedcmc** [odoo/odoo#50972]
Impacted versions:10.0

Steps to reproduce:
According to some interpreting for this error I tried to create a new user for postgres database
but the user is already added.

Current behaviour:
2020-05-09 12:54:08,620 2892 INFO ? odoo: Odoo version 10.0
2020-05-09 12:54:08,621 2892 INFO ? odoo: addons paths: ['/home/ubuntu/.local/share/Odoo/addons/10.0', u'/opt/odoo/odoo-10.0/odoo/addons', u'/opt/odoo/odoo-10.0/addons', '/usr/local/lib/python2.7/dist-packages/odoo-10.0-py2.7.egg/odoo/addons']
2020-05-09 12:54:08,621 2892 INFO ? odoo: database: default@default:default
2020-05-09 12:54:08,802 2892 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2020-05-09 12:54:32,077 2892 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2020-05-09 12:54:32,191 2892 INFO ? odoo.sql_db: Connection to the database failed
2020-05-09 12:54:32,192 2892 ERROR ? odoo.addons.bus.models.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/addons/bus/models/bus.py", line 170, in run
    self.loop()
  File "/opt/odoo/odoo-10.0/addons/bus/models/bus.py", line 148, in loop
    with odoo.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  role "ubuntu" does not exist

2020-05-09 12:54:32,917 2892 INFO ? odoo.sql_db: Connection to the database failed
2020-05-09 12:54:32,922 2892 INFO ? werkzeug: 127.0.0.1 - - [09/May/2020 12:54:32] "GET / HTTP/1.1" 500 -
2020-05-09 12:54:33,148 2892 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1436, in dispatch
    self.setup_db(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1366, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1514, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1488, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 325, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  role "ubuntu" does not exist
2020-05-09 12:54:34,354 2892 INFO ? odoo.sql_db: Connection to the database failed
2020-05-09 12:54:34,456 2892 INFO ? werkzeug: 127.0.0.1 - - [09/May/2020 12:54:34] "GET /favicon.ico HTTP/1.1" 500 -
2020-05-09 12:54:34,476 2892 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1436, in dispatch
    self.setup_db(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1366, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1514, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1488, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 325, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  role "ubuntu" does not exist
2020-05-09 12:54:39,660 2892 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2020-05-09 12:54:39,669 2892 INFO ? odoo.addons.report.models.report: Upgrade Wkhtmltopdf to (at least) 0.12.0
2020-05-09 12:54:42,416 2892 INFO ? odoo.http: HTTP Configuring static files
2020-05-09 12:54:42,429 2892 INFO ? odoo.sql_db: Connection to the database failed
2020-05-09 12:54:42,438 2892 INFO ? werkzeug: 127.0.0.1 - - [09/May/2020 12:54:42] "GET / HTTP/1.1" 500 -
2020-05-09 12:54:42,486 2892 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1436, in dispatch
    self.setup_db(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1366, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1514, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1488, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/odoo/odoo-10.0/odoo/service/db.py", line 325, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  role "ubuntu" does not exist
2020-05-09 12:55:22,419 2892 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2020-05-09 12:55:22,425 2892 INFO ? odoo.sql_db: Connection to the database failed
2020-05-09 12:55:22,426 2892 ERROR ? odoo.addons.bus.models.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/addons/bus/models/bus.py", line 170, in run
    self.loop()
  File "/opt/odoo/odoo-10.0/addons/bus/models/bus.py", line 148, in loop
    with odoo.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL:  role "ubuntu" does not exist

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
This is actually a deployment issue. You're trying to interact with the database with the role "ubuntu" but it doesn't exist. Follow the deployment guide at https://www.odoo.com/documentation/13.0/setup/deploy.html

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html. Note also that 10.0 is already an out of support version.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups). Little possible tip: Odoo configuration file is not being loaded or it doesn't contain a proper Postgres user.

**Comment by pedrobaeza** [comment]
Hehe, same timing!
