### ISSUE TITLE
File upload >1MB fails

### ISSUE THREAD

**Issue by felipepardo87587** [odoo/odoo#51213]
Impacted versions:
Odoo 13.0-20200428 (Community Edition)

Steps to reproduce:
In the Web editor I try to upload a file (PDF or Image) that's about 1.9Mb in size, error shows. 
Uploading a file smaller than 1MB it works well. 

Current behavior:
Error caught, details below
Traceback:
TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at WrappedRange.insertNode (https://site.co/web/content/350-c2af7d4/1/web_editor.summernote.js:155:313)
    at Class.onSave (https://site.co/web/content/688-b0258dd/1/web_editor.assets_wysiwyg.js:444:403)
    at Class.trigger (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3844:180)
    at Class.trigger (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3850:148)
    at Class.<anonymous> (https://site.co/web/content/688-b0258dd/1/web_editor.assets_wysiwyg.js:574:463)
    at Class.trigger (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3844:180)
    at Class.trigger (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3850:148)
    at Class.destroy (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3783:269)
    at Class.prototype.<computed> [as destroy] (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3762:488)
    at Class.close (https://site.co/web/content/682-ea566fb/1/web.assets_common_lazy.js:3783:188)

Expected behavior:
Upload file on Documents or Image

**Comment by pedrobaeza** [comment]
Are you using a reverse proxy in between? This seems more a limiting configuration in your proxy (Apache/nginX/etc).

**Comment by felipepardo87587** [comment]
I am using nginx, I solved it adding the following line to /etc/nginx/nginx.conf 

client_max_body_size 50M;

Thanks a lot Pedro!
