### ISSUE TITLE
Odoo 8 minimal produces Error on loading SO-Mail-Template

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#5126]
It is a minimal Odoo8 Installation non SSL on Ubuntu 14.04 LTS Server with 1 testproduct, 1 admin and 1 customer.
Company-Data is completed including bank account.

Installed Modules: 
- eCommerce and dependencies
- Website-Chat
- all Payment acquirers

The only Order is 3x Testproduct, confirmed by admin, ordered by testcustomer via eCommerce Module without generating an account (just filled the contact form in order-process).

Now, by opening the Sales order an clicking the "send Message" button, the error occurs when i try to load the template for Invoices (the standard template with paypal-Button).

Error MSG:
````
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 545, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 298, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 761, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 394, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5768, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5702, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/wizard/mail_compose_message.py", line 103, in onchange_template_id
    values = self.generate_email_for_composer_batch(cr, uid, template_id, [res_id], context=context)[res_id]
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/wizard/mail_compose_message.py", line 167, in generate_email_for_composer_batch
    template_values = self.pool.get('email.template').generate_email_batch(cr, uid, template_id, res_ids, fields=fields, context=ctx)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/email_template/email_template.py", line 514, in generate_email_batch
    result, format = self.pool['report'].get_pdf(cr, uid, [res_id], report_service, context=ctx), 'pdf'
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 269, in get_pdf
    paperformat, specific_paperformat_args, save_in_attachment
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 442, in _run_wkhtmltopdf
    wkhtmltopdf = [_get_wkhtmltopdf_bin()] + command_args + local_command_args
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 54, in _get_wkhtmltopdf_bin
    raise IOError
IOError
````

**Comment by explanar** [comment]
Oooops.
The odoo-Installation has been too minimal.
````
sudo apt-get install wkhtmltopdf
````
and configuring the smtp server did their job!

**Comment by bwilmus** [comment]
Be carefull with wkhtmltopdf:
Danger
to print PDF reports, you must install wkhtmltopdf yourself: the version of wkhtmltopdf available in debian repositories does not support headers and footers so it can not be installed automatically. The recommended version is 0.12.1 and is available on the wkhtmltopdf download page, in the archive section. As there is no official release for Debian Jessie, you can find ours on http://nightly.odoo.com/extra/.
