### ISSUE TITLE
[13] payment: Trackback on Payment page due to "False" partner

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51288]
Impacted versions: 13.0

Steps to reproduce: Generate Payment link for the Invoice where Partner is not selected and Open link.

![screenshot-2651086-13-0-dd40fb runbot42 odoo com-2020 05 14-22_33_47](https://user-images.githubusercontent.com/16624719/81963662-046d6c80-9633-11ea-9157-4b4c22d8599e.png)
```

Current behavior: Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/payment/controllers/portal.py", line 156, in pay
    token_ok = request.env['payment.link.wizard'].check_token(access_token, int(partner_id), float(amount), int(currency_id))
ValueError: invalid literal for int() with base 10: 'False'
```

Expected behavior: Open Payment Page

Video/Screenshot link (optional):

This is happening due to `False` passing as a string here 
https://github.com/odoo/odoo/blob/dd40fb63b4ebdd4dd7b44c75d415e99b52d633a1/addons/payment/controllers/portal.py#L155

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/commit/52a315085aaf13d0237845638ceb4535c9429df6 should have fixed this.

**Comment by sswapnesh** [comment]
@Yenthe666  No

**Comment by Yenthe666** [comment]
It was all marked as solved though: https://github.com/odoo/odoo/pull/51526#discussion_r427819708

**Comment by sswapnesh** [comment]
@Yenthe666  Traceback is still there, (The warning of Missing email is for Payment acquirers) but here it is failing due to Missing Partner which should be handled from Odoo itself.

**Comment by Yenthe666** [comment]
@dbo-odoo 😉
