### ISSUE TITLE
Unit tests failing for point of sale: IntegrityError: null value in column "name" violates not-null constraint

### ISSUE THREAD

**Issue by david-saracini** [odoo/odoo#5130]
I have recently downloaded the latest Odoo code (from 2 days ago) and I was trying to run unit tests on the point of sale addon and am getting an error.  I'm very new with Odoo, so maybe I'm doing something wrong, but I can't figure it out. It seems like it's a bug with trying to load some test data.

Here is the command I'm using:

`$ ./openerp-server -d odoo_test --init=point_of_sale --test-file=addons/point_of_sale/test/test_frontend.py`

Here is the output:

```
2015-02-06 18:38:29,777 5557 INFO ? openerp: OpenERP version 8.0
2015-02-06 18:38:29,777 5557 INFO ? openerp: addons paths: ['/home/tony/.local/share/Odoo/addons/8.0', u'/home/tony/.virtualenvs/od/odoo/openerp/addons', u'/home/tony/.virtualenvs/od/odoo/addons']
2015-02-06 18:38:29,777 5557 INFO ? openerp: database hostname: localhost
2015-02-06 18:38:29,778 5557 INFO ? openerp: database port: 5432
2015-02-06 18:38:29,778 5557 INFO ? openerp: database user: tony
2015-02-06 18:38:29,891 5557 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-02-06 18:38:29,897 5557 INFO odoo_test openerp.modules.loading: loading 1 modules...
2015-02-06 18:38:29,976 5557 INFO odoo_test openerp.modules.loading: 1 modules loaded in 0.08s, 0 queries
2015-02-06 18:38:30,052 5557 INFO odoo_test openerp.modules.loading: loading 43 modules...
2015-02-06 18:38:30,079 5557 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-02-06 18:38:30,085 5557 INFO odoo_test openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2015-02-06 18:38:31,027 5557 INFO odoo_test openerp.modules.module: module point_of_sale: creating or updating database tables
2015-02-06 18:38:31,749 5557 INFO odoo_test openerp.addons.auth_crypt.auth_crypt: Hashing passwords, may be slow for databases with many users...
2015-02-06 18:38:31,904 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/data/report_paperformat.xml
2015-02-06 18:38:31,918 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/security/point_of_sale_security.xml
2015-02-06 18:38:32,311 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/security/ir.model.access.csv
2015-02-06 18:38:32,849 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_box.xml
2015-02-06 18:38:32,899 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_confirm.xml
2015-02-06 18:38:32,938 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_details.xml
2015-02-06 18:38:32,985 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_discount.xml
2015-02-06 18:38:33,032 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_open_statement.xml
2015-02-06 18:38:33,099 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_payment.xml
2015-02-06 18:38:33,143 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/wizard/pos_session_opening.xml
2015-02-06 18:38:33,180 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/templates.xml
2015-02-06 18:38:33,216 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_report.xml
2015-02-06 18:38:33,348 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_view.xml
2015-02-06 18:38:34,937 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_sequence.xml
2015-02-06 18:38:34,964 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_data.xml
2015-02-06 18:38:35,021 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/report/pos_order_report_view.xml
2015-02-06 18:38:35,127 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_workflow.xml
2015-02-06 18:38:35,253 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/account_statement_view.xml
2015-02-06 18:38:35,486 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/account_statement_report.xml
2015-02-06 18:38:35,535 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/res_users_view.xml
2015-02-06 18:38:35,734 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/res_partner_view.xml
2015-02-06 18:38:35,844 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_statement.xml
2015-02-06 18:38:35,864 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_usersproduct.xml
2015-02-06 18:38:35,898 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_receipt.xml
2015-02-06 18:38:35,939 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_saleslines.xml
2015-02-06 18:38:35,979 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_detailsofsales.xml
2015-02-06 18:38:36,022 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_payment.xml
2015-02-06 18:38:36,063 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/report_sessionsummary.xml
2015-02-06 18:38:36,105 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/views/point_of_sale.xml
2015-02-06 18:38:36,261 5557 INFO odoo_test openerp.modules.loading: loading point_of_sale/point_of_sale_demo.xml
2015-02-06 18:38:36,328 5557 ERROR odoo_test openerp.sql_db: bad query: INSERT INTO "res_partner" ("id", "ean13", "notify_email", "color", "image", "use_parent_address", "active", "supplier", "tz", "opt_out", "company_id", "type", "is_company", "lang", "vat_subjected", "employee", "customer", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_partner_id_seq'), '0420100000005', 'always', 0, NULL, false, true, false, NULL, false, 1, 'contact', false, NULL, false, false, true, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/tony/.virtualenvs/od/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (22, null, 1, null, 0420100000005, 2015-02-06 18:38:31.901778, 0, null, null, null, null, null, null, null, null, null, null, null, f, null, null, f, null, t, null, null, f, null, 2015-02-06 18:38:31.901778, t, null, 1, null, 1, null, null, null, contact, f, null, null, null, null, null, always, null, f, null, null, null, null, null, f, null).

2015-02-06 18:38:36,329 5557 CRITICAL odoo_test openerp.service.server: Failed to initialize database `odoo_test`.
Traceback (most recent call last):
  File "/home/tony/.virtualenvs/od/odoo/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/tony/.virtualenvs/od/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/tony/.virtualenvs/od/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/tony/.virtualenvs/od/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/tony/.virtualenvs/od/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/tony/.virtualenvs/od/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/tony/.virtualenvs/od/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/tony/.virtualenvs/od/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/tony/.virtualenvs/od/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/tony/.virtualenvs/od/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/addons/base/res/res_partner.py", line 569, in create
    partner = super(res_partner, self).create(vals)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/models.py", line 4025, in create
    record = self.browse(self._create(old_vals))
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/models.py", line 4163, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/tony/.virtualenvs/od/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/tony/.virtualenvs/od/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (22, null, 1, null, 0420100000005, 2015-02-06 18:38:31.901778, 0, null, null, null, null, null, null, null, null, null, null, null, f, null, null, f, null, t, null, null, f, null, 2015-02-06 18:38:31.901778, t, null, 1, null, 1, null, null, null, contact, f, null, null, null, null, null, always, null, f, null, null, null, null, null, f, null).
" while parsing /home/tony/.virtualenvs/od/odoo/addons/point_of_sale/point_of_sale_demo.xml:5, near
<record id="base.res_partner_1" model="res.partner"> <field name="ean13">0420100000005</field> </record>
^C2015-02-06 18:38:38,449 5557 INFO odoo_test openerp.service.server: Initiating shutdown
2015-02-06 18:38:38,449 5557 INFO odoo_test openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

```

**Comment by red15** [comment]
Can you try again with this command line?
Make sure odoo_test database exists but is empty (I assume you already did this before ?)

`$ ./openerp-server -d odoo_test --init=point_of_sale --test-enable`

**Comment by Yenthe666** [comment]
Hi @david-saracini,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by mromdhane** [comment]
Is resoved here:
https://stackoverflow.com/a/39466498
