### ISSUE TITLE
[13.0] survey: Expected singleton issue in survey test

### ISSUE THREAD

**Issue by MojtabaAp** [odoo/odoo#51363]
hi
i got expected singleton issue in survey test

`2020-05-17 03:51:18,124 2124 ERROR odoo13.0 odoo.addons.http_routing.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "\PycharmProjects\odoo\odoo\models.py", line 5000, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\PycharmProjects\odoo\odoo\addons\base\models\ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "\PycharmProjects\odoo\odoo\http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "\PycharmProjects\odoo\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "\PycharmProjects\odoo\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "\PycharmProjects\odoo\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "\PycharmProjects\odoo\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "\PycharmProjects\odoo\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "\PycharmProjects\odoo\odoo\addons\survey\controllers\main.py", line 156, in survey_test
    return request.redirect('/survey/start/%s?%s' % (survey_sudo.access_token, keep_query('*', answer_token=answer_sudo.token)))
  File "\PycharmProjects\odoo\odoo\fields.py", line 984, in __get__
    record.ensure_one()
  File "\PycharmProjects\odoo\odoo\models.py", line 5003, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: survey.survey(2, 3, 4, 5, 9, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30)`

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sswapnesh** [comment]
This should not happen as `access_token` is not copied
https://github.com/odoo/odoo/blob/a8b627bc4a37aedbc741795db83cdf8d52caaecb/addons/survey/models/survey_survey.py#L68
https://github.com/odoo/odoo/blob/a8b627bc4a37aedbc741795db83cdf8d52caaecb/addons/survey/models/survey_survey.py#L24

However, I have added https://github.com/odoo/odoo/pull/51366 to prevent this. (Although not sure If we should handle such behavior)
