### ISSUE TITLE
[12.0] Recipient address rejected: User unknown in virtual mailbox table

### ISSUE THREAD

**Issue by protontrigg3r** [odoo/odoo#51704]
Current settings:

mail.catchall.domain: _**mysubdomain.mydomain.com**_
mail.bounce.alias: _bounce_
​mail.catchall.alias: _catchall_

Sending an email to _**@mydomain.com**_ address (not to _@mysubdomain.mydomain.com_) generates **_User unknown in virtual mailbox table_** error:

```
2020-05-22 13:43:21,173 1555 ERROR test odoo.addons.mail.models.mail_mail: failed sending mail (id: 20) due to Mail Delivery Failed
Mail delivery failed via SMTP server 'None'.
SMTPRecipientsRefused: {'myuser@mydomain.com': (550, b'5.1.1 <myuser@mydomain.com>: Recipient address rejected: User unknown in virtual mailbox table')} 
Traceback (most recent call last):
  File "/myodoopath/odoo/addons/base/models/ir_mail_server.py", line 501, in send_email
    smtp.sendmail(smtp_from, smtp_to_list, message.as_string())
  File "/usr/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'myuser@mydomain.com': (550, b'5.1.1 <myuser@mydomain.com>: Recipient address rejected: User unknown in virtual mailbox table')}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/myodoopath/addons/mail/models/mail_mail.py", line 370, in _send
    msg, mail_server_id=mail.mail_server_id.id, smtp_session=smtp_session)
  File "/myodoopath/odoo/addons/base/models/ir_mail_server.py", line 511, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
odoo.addons.base.models.ir_mail_server.MailDeliveryException: ('Mail Delivery Failed', "Mail delivery failed via SMTP server 'None'.\nSMTPRecipientsRefused: {'myuser@mydomain.com': (550, b'5.1.1 <myuser@mydomain.com>: Recipient address rejected: User unknown in virtual mailbox table')}")

```

**Comment by pedrobaeza** [comment]
That's something expected, as the parameters/mail handling don't include subdomains, You should unify your domains.

Closing as no bug, but misconfiguration.
