### ISSUE TITLE
[13.0] account_saft: Export fails after using POS

### ISSUE THREAD

**Issue by willmakenoise** [odoo/odoo#51724]
**Impacted versions:**
13.0 Enterprise

**Steps to reproduce:**
- DB with Norwegian company
- Install account_saft
- Create a POS order
- Export General Ledger to SAF-T (Norway)

**Current behavior:**
Server Error:
```
Traceback (most recent call last):
  File "/odoo13/enterprise/account_reports/controllers/main.py", line 44, in get_report
    content = report_obj.get_xml(options)
  File "/odoo13/enterprise/account_saft/models/account_saft_report.py", line 410, in get_xml
    report_data = self._prepare_saft_report_data(options)
  File "/odoo13/enterprise/l10n_no_saft/models/account_general_ledger.py", line 26, in _prepare_saft_report_data
    res = super()._prepare_saft_report_data(options)
  File "/odoo13/enterprise/account_saft/models/account_saft_report.py", line 383, in _prepare_saft_report_data
    data = self._prepare_general_ledger_data(move_lines_data)
  File "/odoo13/enterprise/account_saft/models/account_saft_report.py", line 334, in _prepare_general_ledger_data
    move_line['amount_tax'] = move_line['price_total'] - move_line['price_subtotal']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by pedrobaeza** [comment]
`account_saft` is not a core module, so you should ask for support in their source.

Closing as no Odoo bug, but third-party one.

**Comment by willmakenoise** [comment]
It’s an enterprise module. 
Ask who?

**Comment by pedrobaeza** [comment]
Then put a ticket in odoo.com/help
