### ISSUE TITLE
 [odoo9]config file errors in Intellij

### ISSUE THREAD

**Issue by akira32chen** [odoo/odoo#51721]
I add openerp-service.conf in [odoo9]. The content is as below:

`[options]
db_name = odoo
db_host = 10.2.5.111
#db_host = 127.0.0.1
db_port = 5444
db_user = odoo
db_password = odoo
dbfilter = ^odoo$
admin_passwd = abc
addons_path = addons,openerp/addons
data_dir = openerp/filestore
timezone = Asia/Taipei
log_level = info
xmlrpc_port = 8070`

But when I run this project using Intellij , it appear some errors as below:
Does somebody know how to solve those problems?

`C:\Users\user\venv\odoo\Scripts\python.exe C:/Users/user/Downloads/Work/odoo-9.0/odoo-9.0/odoo.py -c openerp-server.conf
2020-05-23 00:14:30,625 40120 INFO ? openerp: OpenERP version 9.0c
2020-05-23 00:14:30,625 40120 INFO ? openerp: addons paths: ['openerp/filestore\\addons\\9.0', u'C:\\Users\\user\\Downloads\\Work\\odoo-9.0\\odoo-9.0\\addons', u'C:\\Users\\user\\Downloads\\Work\\odoo-9.0\\odoo-9.0\\openerp\\addons']
2020-05-23 00:14:30,625 40120 INFO ? openerp: database: odoo@10.2.5.170:5444
2020-05-23 00:14:32,630 40120 INFO ? openerp.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "C:/Users/user/Downloads/Work/odoo-9.0/odoo-9.0/odoo.py", line 160, in <module>
    main()
  File "C:/Users/user/Downloads/Work/odoo-9.0/odoo-9.0/odoo.py", line 157, in main
    openerp.cli.main()
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\cli\command.py", line 64, in main
    o.run(args)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\cli\server.py", line 165, in run
    main(args)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\cli\server.py", line 136, in main
    openerp.service.db._create_empty_database(db_name)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\service\db.py", line 79, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\sql_db.py", line 643, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\sql_db.py", line 526, in _locked
    return fun(self, *args, **kwargs)
  File "C:\Users\user\Downloads\Work\odoo-9.0\odoo-9.0\openerp\sql_db.py", line 594, in borrow
    **connection_info)
  File "C:\Users\user\venv\odoo\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "10.2.5.170" and accepting
	TCP/IP connections on port 5444?`

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/9.0/setup/install.html. The version is also totally out of official support (latest supported version is 11).

I'm closing this issue now. You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
