### ISSUE TITLE
[13] account: Error on adding amount manually on Zero Tax

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51737]
Impacted versions: 13.0

Steps to reproduce: 

- Configure Zero Tax on Vendor Bill
- Create Bill and select tax
- Edit amount
- 

![screenshot-localhost_8069-2020 05 24-00_01_27](https://user-images.githubusercontent.com/16624719/82737916-c28aa780-9d51-11ea-99d1-1f15cbb5660a.png)

Current behavior: Traceback
```
Error:
Uncaught TypeError: Cannot read property 'data' of undefined

http://localhost:8069/account/static/src/js/tax_group.js:39
Traceback:
TypeError: Cannot read property 'data' of undefined
    at Class._changeTaxValueByTaxGroup (http://localhost:8069/account/static/src/js/tax_group.js:39:25)
    at Class._onBlur (http://localhost:8069/account/static/src/js/tax_group.js:130:18)
    at HTMLInputElement.<anonymous> (http://localhost:8069/web/static/src/js/core/mixins.js:277:23)
    at HTMLDivElement.dispatch (http://localhost:8069/web/static/lib/jquery/jquery.js:5183:27)
    at HTMLDivElement.elemData.handle (http://localhost:8069/web/static/lib/jquery/jquery.js:4991:28)
    at Object.trigger (http://localhost:8069/web/static/lib/jquery/jquery.js:8249:12)
    at Object.simulate (http://localhost:8069/web/static/lib/jquery/jquery.js:8318:16)
    at HTMLDocument.handler (http://localhost:8069/web/static/lib/jquery/jquery.js:8352:17)
    at HTMLInputElement.trigger (http://localhost:8069/web/static/lib/jquery/jquery.js:5315:11)
    at Object.trigger (http://localhost:8069/web/static/lib/jquery/jquery.js:8214:60)
```
Expected behavior: Newline should be added with the added amount on the widget 

Video/Screenshot link (optional):

**Comment by KareemAbuzaid** [comment]
@sswapnesh I am unable to reproduce the error. Would you please provide further details on the configuration of the tax.

![1](https://user-images.githubusercontent.com/36644028/82742650-194bad80-9d61-11ea-91c7-3d0c88ccbf05.PNG)
![2](https://user-images.githubusercontent.com/36644028/82742651-1a7cda80-9d61-11ea-9e87-d81cbd10a759.PNG)

**Comment by sswapnesh** [comment]
Tax config seems okay.

Edit draft bill and click on Zero (On the tax group widget) and add some amount.

See pencil Icon in https://user-images.githubusercontent.com/16624719/82737916-c28aa780-9d51-11ea-99d1-1f15cbb5660a.png
