### ISSUE TITLE
Unclear error message when declaring a model without _inherit or _name

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#5196]
In my module, I extended a model but forgot the `_inherit` attribute (and no `_name`). This is the error i got:

```pytb
Traceback (most recent call last):
  File "/srv/openerp/8.0/openerp/http.py", line 524, in _handle_exception
    
  File "/srv/openerp/8.0/openerp/http.py", line 545, in dispatch
    return self._json_response(error=error)
  File "/srv/openerp/8.0/openerp/http.py", line 301, in _call_function
    
  File "/srv/openerp/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/8.0/openerp/http.py", line 298, in checked_call
    if self._cr:
  File "/srv/openerp/8.0/openerp/http.py", line 761, in __call__
    
  File "/srv/openerp/8.0/openerp/http.py", line 394, in response_wrap
    @functools.wraps(f)
  File "/srv/openerp/8.0/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/openerp/8.0/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/8.0/openerp/api.py", line 237, in wrapper
    # avoid hasattr(self, '_ids') because __getattr__() is overridden
  File "/srv/openerp/8.0/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/srv/openerp/8.0/openerp/api.py", line 237, in wrapper
    # avoid hasattr(self, '_ids') because __getattr__() is overridden
  File "/srv/openerp/8.0/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/srv/openerp/8.0/openerp/modules/registry.py", line 346, in new
    The (possibly) previous registry for that database name is discarded.
  File "/srv/openerp/8.0/openerp/modules/loading.py", line 363, in load_modules
    if model in registry and not registry[model].is_transient() and not isinstance(registry[model], openerp.osv.orm.AbstractModel):
  File "/srv/openerp/8.0/openerp/modules/loading.py", line 263, in load_marked_modules
    initialize_sys_path()
  File "/srv/openerp/8.0/openerp/modules/loading.py", line 158, in load_module_graph
    
  File "/srv/openerp/8.0/openerp/modules/registry.py", line 148, in load
    per-registry level. This method populates a registry with the given
  File "/srv/openerp/8.0/openerp/models.py", line 659, in _build_model
    # process store of low-level function fields
TypeError: type() argument 1 must be string, not None
```

Which is generic and confusing, especially considering the last line of code showed is a comment mentioning function fields, so it may redirect your attention with an error with the field definition.
Maybe it could be possible to print a more specific error message when `cls._name` is None, hinting as a missing `_inherit` or `_name` as a probable cause?

**Comment by rco-odoo** [comment]
@LeartS without `_name` and `_inherit`, the name of a model is its Python class name.
I don't understand how you could get `None` there.

Please reopen the issue or create a new one in case the issue is still present.
