### ISSUE TITLE
Errors when connecting to restored Odoo database.

### ISSUE THREAD

**Issue by hieuvts** [odoo/odoo#52202]
I already had an database A (with Web, Sales, Invoices,...) on Odoo.com But now I want to use that database on local computer. So I made a backup of database A, and then restore it on localhost:8069 The restoration was successful however when I can't connect to it.
This is error message from localhost:8069
```Error to render compiling AST
UndefinedTable: relation "ir_attachment_id_seq" does not exist
LINE 1: ...ore_fname", "type", "website_id") VALUES (nextval('ir_attach...
                                                             ^

Template: web.frontend_layout
Path: /t/html/head/t[10]
Node: <t t-call-assets="web.assets_common_minimal_js" t-css="false" defer_load="True"/>
```

And its traceback:
```Traceback (most recent call last):
  File "Q:\odoo-13.0\odoo\tools\cache.py", line 85, in lookup
    r = d[key]
  File "Q:\odoo-13.0\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "Q:\odoo-13.0\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x0586C4F8>, 'web.assets_common_minimal_js', 'vi_VN', False, True, '', False, True, False, (1,))

During handling of the above exception, another exception occurred:
```

and more from terminal:
```
2020-05-30 10:45:47,680 12464 WARNING pep2 odoo.modules.graph: module mail_enterprise: not installable, skipped 
2020-05-30 10:45:47,681 12464 WARNING pep2 odoo.modules.graph: module sale_enterprise: not installable, skipped
2020-05-30 10:45:47,685 12464 WARNING pep2 odoo.modules.graph: module theme_common: not installable, skipped 
2020-05-30 10:45:47,713 12464 WARNING pep2 odoo.modules.graph: module website_sale_dashboard: not installable, skipped 
2020-05-30 10:45:47,719 12464 WARNING pep2 odoo.modules.graph: module web_gantt: not installable, skipped 
2020-05-30 10:45:47,728 12464 WARNING pep2 odoo.modules.graph: module account_bank_statement_import_csv: not installable, skipped 
2020-05-30 10:45:47,736 12464 INFO pep2 odoo.modules.loading: loading 73 modules...
2020-05-30 10:45:50,430 12464 INFO pep2 odoo.modules.loading: 73 modules loaded in 2.69s, 0 queries 
2020-05-30 10:45:50,431 12464 ERROR pep2 odoo.modules.loading: Some modules are not loaded, some dependencies or manifest may be missing: ['account_bank_statement_import_camt', 'account_bank_statement_import_csv', 'account_bank_statement_import_ofx', 'account_invoice_extract', 'account_online_sync', 'account_plaid', 'account_ponto', 'account_yodlee', 'analytic_enterprise', 'barcodes_mobile', 'currency_rate_live', 'im_livechat_enterprise', 'mail_enterprise', 'sale_enterprise', 'stock_account_enterprise', 'stock_enterprise', 'theme_clean', 'theme_common', 'web_cohort', 'web_dashboard', 'web_enterprise', 'web_gantt', 'web_grid', 'web_map', 'web_mobile', 'web_studio', 'website_animate', 'website_enterprise', 'website_sale_dashboard', 'website_studio']
2020-05-30 10:45:51,280 12464 INFO pep2 odoo.modules.loading: Modules loaded. 
2020-05-30 10:45:51,296 12464 INFO pep2 odoo.addons.base.models.ir_http: Generating routing map for key 1 
2020-05-30 10:45:51,906 12464 WARNING pep2 odoo.modules.module: module theme_common: module not found 
2020-05-30 10:45:51,908 12464 WARNING pep2 odoo.modules.module: module web_enterprise: module not found 
2020-05-30 10:45:51,914 12464 WARNING pep2 odoo.modules.module: module theme_common: module not found
2020-05-30 10:45:51,916 12464 WARNING pep2 odoo.modules.module: module theme_clean: module not found 
2020-05-30 10:45:51,928 12464 WARNING pep2 odoo.modules.module: module web_enterprise: module not found
2020-05-30 10:45:51,937 12464 WARNING pep2 odoo.modules.module: module web_enterprise: module not found 
2020-05-30 10:45:51,953 12464 WARNING pep2 odoo.modules.module: module web_enterprise: module not found 
2020-05-30 10:45:52,023 12464 WARNING pep2 odoo.modules.module: module theme_common: module not found 
2020-05-30 10:45:52,026 12464 WARNING pep2 odoo.modules.module: module web_enterprise: module not found 
```

Thanks in advance for any helps!

**Comment by hieuvts** [comment]
btw. "pep2" is database name I just created for restoreation.
I tried both restore by Odoo tool and restore by PostgreSQL command. Facing the same problems.

**Comment by Yenthe666** [comment]
Multiple things there:
- It cannot find the enterprise addons such ad "web_enterprise" etc. Are you sure that you're a partner or have setup the enterprise addons?
- You do know that odoo.com (the saas) is not in sync with major Odoo versions right? They're on 13.3 (or 13.4) right now, while the major release is still 13.
- This is not a bug in Odoo but a custom deployment issue. Not what Github is used for ;)

**Comment by hieuvts** [comment]
> * This is not a bug in Odoo but a custom deployment issue. Not what Github is used for ;)

Sorry, sir. I will double-check those mentioned again. Thank you for your help.

**Comment by Yenthe666** [comment]
No problem and good luck :)

**Comment by hieuvts** [comment]
> No problem and good luck :)

I think I'm using Odoo Monthly plan on Odoo.com 
So there is no way to restore that online database to run it on local, because of missing web_enterprise module?

**Comment by Yenthe666** [comment]
There is if you work with a partner (or download the package which should be available somewhere actually) and if you follow the SaaS releases or migrate to a major version. Otherwise you're pretty stuck. 
It's not the easiest thing to get out off.
