### ISSUE TITLE
TypeError: Cannot read property '_invalid' of undefined     at Class._createStripeToken 

### ISSUE THREAD

**Issue by BlissNomad** [odoo/odoo#52209]
Impacted versions: v13

Steps to reproduce: in store click paynow

Current behavior: error, stops payment process and will not complete payment

Expected behavior: completes payment and processes through stripe. 

Video/Screenshot link (optional):

Error:
Uncaught TypeError: Cannot read property '_invalid' of undefined

http://www.p3permaculture.ca/payment_stripe/static/src/js/payment_form.js:52
Traceback:
TypeError: Cannot read property '_invalid' of undefined
    at Class._createStripeToken (http://www.p3permaculture.ca/payment_stripe/static/src/js/payment_form.js:52:18)
    at Class.payEvent (http://www.p3permaculture.ca/payment_stripe/static/src/js/payment_form.js:167:25)
    at Class.payEvent (http://www.p3permaculture.ca/web/static/src/js/core/class.js:123:38)
    at HTMLButtonElement.<anonymous> (http://www.p3permaculture.ca/web/static/src/js/core/mixins.js:277:23)
    at HTMLFormElement.dispatch (http://www.p3permaculture.ca/web/static/lib/jquery/jquery.js:5183:27)
    at HTMLFormElement.elemData.handle (http://www.p3permaculture.ca/web/static/lib/jquery/jquery.js:4991:28)

**Comment by pedrobaeza** [comment]
Are you using latest source code?

**Comment by BlissNomad** [comment]
Update: I have gotten past this error by setting up the configurations in the template to use the correct email server. 

Now we have another error though. Will create a new thread for it.
