### ISSUE TITLE
 Odoo 12 server error

### ISSUE THREAD

**Issue by Xavihernandez93** [odoo/odoo#52226]
hi all , i tried installing odoo 12 using this link https://www.getopenerp.com/install-odoo-12-on-ubuntu-18-04/ , after installing when i try to start odoo iam getting this error 

*error* :

2020-06-01 13:42:28,369 13926 ERROR odoo odoo.modules.loading: Some modules are not loaded, some dependencies or manifest may be missing: ['account', 'account_bank_statement_import', 'account_facturx', 'account_tax_python', 'analytic', 'attachment_indexation', 'calendar_sms', 'crm_sms', 'guna_lyra', 'gunalan_demo', 'hr_expense', 'hr_fleet', 'hr_holidays_attendance', 'hr_recruitment', 'hr_timesheet', 'iap', 'l10n_in', 'l10n_in_sale', 'l10n_in_sale_stock', 'l10n_in_stock', 'om_hr_payroll', 'partner_autocomplete', 'payment', 'payment_transfer', 'procurement_jit', 'product', 'project_timesheet_holidays', 'sale', 'sale_crm', 'sale_expense', 'sale_management', 'sale_stock', 'sale_timesheet', 'sms', 'snailmail', 'snailmail_account', 'stock', 'stock_account', 'stock_sms', 'transfers', 'website_crm_sms', 'website_hr_recruitment', 'website_sms'] 

2020-06-01 13:42:28,626 13926 INFO odoo odoo.modules.loading: Modules loaded. 

2020-06-01 13:42:28,631 13926 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 

2020-06-01 13:42:28,692 13926 ERROR odoo odoo.sql_db: bad query: SELECT "res_lang"."id" as "id","res_lang"."time_format" as "time_format","res_lang"."name" as "name","res_lang"."decimal_point" as "decimal_point","res_lang"."direction" as "direction","res_lang"."active" as "active","res_lang"."write_date" as "write_date","res_lang"."date_format" as "date_format","res_lang"."thousands_sep" as "thousands_sep","res_lang"."write_uid" as "write_uid","res_lang"."translatable" as "translatable","res_lang"."iso_code" as "iso_code","res_lang"."create_date" as "create_date","res_lang"."create_uid" as "create_uid","res_lang"."grouping" as "grouping","res_lang"."code" as "code","res_lang"."week_start" as "week_start" FROM "res_lang" WHERE "res_lang".id IN (1)

ERROR: column res_lang.translatable does not exist

LINE 1: ...usands_sep","res_lang"."write_uid" as "write_uid","res_lang"...

                                                             ^

 

2020-06-01 13:42:28,694 13926 INFO odoo werkzeug: 127.0.0.1 - - [01/Jun/2020 13:42:28] "GET / HTTP/1.1" 500 - 25 0.014 0.593

2020-06-01 13:42:28,700 13926 ERROR odoo werkzeug: Error on request:

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi

    execute(self.server.app)

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute

    application_iter = app(environ, start_response)

  File "/opt/odoo/odoo/odoo/service/server.py", line 434, in app

    return self.app(e, s)

  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 142, in application

    return application_unproxied(environ, start_response)

  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied

    result = odoo.http.root(environ, start_response)

  File "/opt/odoo/odoo/odoo/http.py", line 1320, in __call__

    return self.dispatch(environ, start_response)

  File "/opt/odoo/odoo/odoo/http.py", line 1293, in __call__

    return self.app(environ, start_wrapped)

whats strange is its loading the modules of odoo13 although i tried to start using  *./odoo-bin --addons-path=/opt/odoo/odoo/addons/*

can someone help me with iam a newbie to odoo development

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
