### ISSUE TITLE
[12.0] Origin ==> bugs after update from the git repository  since yesterday (june 3rd, 2020)

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#52408]
**Impacted versions:**
12.0 origin

Steps to reproduce:
Update the odoo12 server by:
$  cd /opt/odoo12/odoo
$ git fetch origin 12.0
$ git reset -- hard origin/12.0

**Current behavior:**
Many standard modules are not working, showing bugs.
Impacted modules are:
- Contacts
- Sales
- Purchases
- Project
- Manufacturing
...

**Sample error on Purchases:**
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/models.py", line 1394, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo12/odoo/odoo/models.py", line 1394, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo12/odoo/addons/mail/models/mail_thread.py", line 409, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo12/odoo/odoo/models.py", line 1480, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1119, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 944, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 944, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 944, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 1 more time]
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 904, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Le champ `lot_id` n'existe pas

Contexte de l'erreur :
Vue `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Sample of errors on Manufacturing:**
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/addons/note/models/res_users.py", line 57, in systray_get_activities
    activities = super(Users, self).systray_get_activities()
  File "/opt/odoo12/odoo/addons/contacts/models/res_users.py", line 15, in systray_get_activities
    activities = super(Users, self).systray_get_activities()
  File "/opt/odoo12/odoo/addons/calendar/models/res_users.py", line 33, in systray_get_activities
    res = super(Users, self).systray_get_activities()
  File "/opt/odoo12/odoo/addons/mail/models/res_users.py", line 136, in systray_get_activities
    'icon': modules.module.get_module_icon(self.env[activity['model']]._original_module),
  File "/opt/odoo12/odoo/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'purchase.request'

**Expected behavior:**
All previous updates worked properly without any bugs

**Comment by pedrobaeza** [comment]
I don't think there's any bugs. The problem might be that you haven't updated your modules in your DB.

Try that.

Closing meanwhile.

**Comment by pedrobaeza** [comment]
Also showing that the error is in `purchase.request` model, that's something outside of Odoo itself.
