### ISSUE TITLE
[8.0] global name 'args2' is not defined when trying to backup to zip with /web/database/manager

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#5241]
After  recent commit I seem to be having issues with backing up databases.

Steps to reproduce:

1) Install on clean Ubuntu 14.04 with PostgreSQL 9.4 and this install script for Odoo: https://github.com/lukebranch/odoo-install-scripts/blob/master/odoo-saas4/ubuntu-14-04/odoo_install.sh
2) setup a database with new data (not demo data). This could be done by adding a few products, etc.
3) logout of Odoo and go to /web/database/manager
4) try to backup with backup format: zip (includes filestore)
5) I get the following popup window:

<img src="https://cloud.githubusercontent.com/assets/2337666/6164627/dd3846f2-b2db-11e4-93e2-91d1c2bf9af8.png"/>

The traceback is as follows from the logs:
```
2015-02-12 09:18:10,054 7521 DEBUG testing openerp.tools.translate: translation went wrong for "'Backup Database'", skipped
2015-02-12 09:22:16,089 7521 INFO None openerp.service.db: DUMP DB: testing format zip
2015-02-12 09:22:16,208 7521 ERROR testing openerp.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 736, in backup
    dump_stream = openerp.service.db.dump_db(backup_db, None, backup_format)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 196, in dump_db
    openerp.tools.exec_pg_command(*cmd)
  File "/opt/odoo/odoo-server/openerp/tools/misc.py", line 127, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
NameError: global name 'args2' is not defined
2015-02-12 09:22:16,209 7521 DEBUG testing openerp.tools.translate: translation went wrong for "'Backup Database'", skipped
```

I believe the commit might be this one:

https://github.com/odoo/odoo/commit/2c99ddc6127376f55e33d3ba9745226d60e03717

As it is the only commit that references this name.

**Comment by PCatinean** [comment]
I also get this as well

**Comment by lukebranch** [comment]
@PCatinean ,

Would you mind commenting back with a bit more information about your setup, including:

1) Which Modules installed (Odoo SA and Community modules)
2) Multi-database, or single database
3) Operating System
4) Setup Method (eg. installed from .DEB, installed from Github, etc.)

and anything else you think might be relevant?

I'd like to compare notes on the setup and see if there are any similarities in our setups that may be causing the issue.

**Comment by xmo-odoo** [comment]
> I believe the commit might be this one: 2c99ddc

It's ec9a543014a91be17398ba6e443578fe37c3a885

The commit [removed `args2` as the concatenation of the program and its arguments](https://github.com/odoo/odoo/commit/ec9a543014a91be17398ba6e443578fe37c3a885#diff-dce0cdcb177f242e286d454d87c787d7L90) but for some reason added the same `args2` in an error message.

**Comment by lukebranch** [comment]
@xmo-odoo ,

Thanks for the fix! 

I've run into another issue in the same backup process. Here's the traceback:

<strong>[zip (includes filestore)]</strong>
```
2015-02-28 03:02:05,530 21985 ERROR WE-Master openerp.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 736, in backup
    dump_stream = openerp.service.db.dump_db(backup_db, None, backup_format)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 196, in dump_db
    openerp.tools.exec_pg_command(*cmd)
  File "/opt/odoo/odoo-server/openerp/tools/misc.py", line 128, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--username=odoo', '--file=/tmp/tmpsns21A/dump.sql', u'WE-Master') error 1
2015-02-28 03:02:05,531 21985 DEBUG WE-Master openerp.tools.translate: translation went wrong for "'Backup Database'", skipped
```

<strong>[pg_dump custom format (without filestore)]</strong>
```
2015-02-28 03:48:49,285 1810 ERROR WE-Master openerp.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 736, in backup
    dump_stream = openerp.service.db.dump_db(backup_db, None, backup_format)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 196, in dump_db
    openerp.tools.exec_pg_command(*cmd)
  File "/opt/odoo/odoo-server/openerp/tools/misc.py", line 128, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--username=odoo', '--file=/tmp/tmppEt3wi/dump.sql', u'WE-Master') error 1
2015-02-28 03:48:49,286 1810 DEBUG WE-Master openerp.tools.translate: translation went wrong for "'Backup Database'", skipped
2015-02-28 03:58:06,450 1810 INFO None openerp.service.db: DUMP DB: WE-Master format dump
```

Here's a screenshot from /web/database/manager#action=database_manager for backup with [zip (includes filestore)]:

<img src="https://cloud.githubusercontent.com/assets/2337666/6424754/ffc36d58-bf3f-11e4-95c0-93a71fe91926.png"/>

Backing up with [pg_dump custom format (without filestore)] only dumps out an empty .dump file with 0 bytes.

Do you think this is a problem with my setup?

**Comment by lukebranch** [comment]
[UPDATE]
On the off chance that anyone else has this issue, it was due to /usr/bin/pg_dump and /usr/bin/pg_dumpall version mismatch.

I have previously had PosgreSQL 9.3 installed on that server, and had upgraded to 9.4 on it's release.

The fix is detailed by Seth here:

http://stackoverflow.com/questions/12836312/postgresql-9-2-pg-dump-version-mismatch

in my case I did the following:

sudo sudo ln -s /usr/lib/postgresql/9.4/bin/pg_dump /usr/bin/pg_dump --force

Problem solved.

**Comment by maclarensg** [comment]
Hi All,

I've encounter the same problem but I fixed it by commenting out the execptions from line 125
openerp/tools/misc.py

with open(os.devnull) as dn:
         rc = subprocess.call((prog,) + args, env=env, stdout=dn, stderr=subprocess.STDOUT)
         #if rc:
            #raise Exception('Postgres subprocess %s error %s' % (args2, rc))

**Comment by grexe** [comment]
in my case it was simply that /tmp was full. I'd prefer Odoo let me chose the destination and dump/compress right there, as /tmp is often quite tight (e.g. on my fresh Debian 8.3 install)...
