### ISSUE TITLE
Error editing the quantity in purchase orden invoiced

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#52546]
Impacted versions: 13.0

Steps to reproduce:
- Create a purchase order and validate it.
- Invoice the purchase order with total quantity.
- Try to edit the quantity in a line of purchase order change qty to cero and save the document.

Current behavior:
An error is thrown
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/purchase_stock/models/purchase.py", line 72, in write
    res = super(PurchaseOrder, self).write(vals)
  File "/data/build/odoo/addons/purchase_requisition/models/purchase.py", line 103, in write
    result = super(PurchaseOrder, self).write(vals)
  File "/data/build/odoo/addons/purchase/models/purchase.py", line 185, in write
    res = super(PurchaseOrder, self).write(vals)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/data/build/odoo/addons/mail/models/mail_activity.py", line 715, in write
    return super(MailActivityMixin, self).write(vals)
  File "/data/build/odoo/odoo/models.py", line 3542, in write
    field.write(self, vals[fname])
  File "/data/build/odoo/odoo/fields.py", line 2836, in write
    return self.write_batch([(records, value)])
  File "/data/build/odoo/odoo/fields.py", line 2857, in write_batch
    return self.write_real(records_commands_list, create)
  File "/data/build/odoo/odoo/fields.py", line 3000, in write_real
    comodel.browse(command[1]).write(command[2])
  File "/data/build/odoo/addons/purchase_stock/models/purchase.py", line 304, in write
    self.filtered(lambda l: l.order_id.state == 'purchase')._create_or_update_picking()
  File "/data/build/odoo/addons/purchase_stock/models/purchase.py", line 325, in _create_or_update_picking
    'res_id': line.invoice_lines[0].invoice_id.id,
AttributeError: 'account.move.line' object has no attribute 'invoice_id'
```
Expected behavior:
The purchase must be saved without error.

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=HRKyA4zWU-c&feature=youtu.be

**Comment by pedrobaeza** [comment]
Indeed the error is there:

https://github.com/odoo/odoo/blob/8c4439aa7d48ab92827e0031c0a6fda90a9b1dc6/addons/purchase_stock/models/purchase.py#L325

@sle-odoo @amoyaux can you please check this?

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/52551
