### ISSUE TITLE
13.0 load Arabic language "ar_001"

### ISSUE THREAD

**Issue by abdallamohamedcore** [odoo/odoo#52558]
Impacted versions:
13.0
Steps to reproduce:
1. create demo database with name "test_translation_db"
2. activate language [Arabic / الْعَرَبيّة"](https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/data/res.lang.csv#L4)
3. Export translation for module `base`
4. in the terminal run below command
```
`odoo --database test_translation_db --i18n-import=ar_001.po -l base --i18n-overwrite`
```

Current behavior:
appear below issue in log
```
Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 178, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 126, in main
    odoo.tools.config.parse_config(args)
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 355, in parse_config
    self._parse_config(args)
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 515, in _parse_config
    raise Exception('ERROR: The Lang name must take max 5 chars, Eg: -lfr_BE')
```

**Comment by Yenthe666** [comment]
@mart-e I'm pretty sure you know what's up here :)

**Comment by abdallamohamedcore** [comment]
@Yenthe666 
After investigate I found that this [line](https://github.com/odoo/odoo/blob/13.0/odoo/tools/config.py#L514) is count number of character of language
``` python
if len(self.options['language']) > 5:
    raise Exception('ERROR: The Lang name must take max 5 chars, Eg: -lfr_BE')
```

**Comment by Yenthe666** [comment]
Clearly but Martin probably knows the why behind it.

**Comment by mart-e** [comment]
Hi,

No reason, the check was historical and does not make much sense. I have removed it at #52564
Thanks for the report
