### ISSUE TITLE
[8.0] Last 46774-8-0-9ffa3a update

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5270]
when we clic on Sales Team Menu.....

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 844, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5061, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3078, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3274, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/osv/fields.py", line 1356, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/sale/sales_team.py", line 40, in _get_invoices_data
    values = self.__get_bar_values(cr, uid, obj, created_domain, ['price_total', 'date'], 'price_total', 'date', context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/sales_team/sales_team.py", line 58, in __get_bar_values
    group_obj = obj.read_group(cr, uid, domain, read_fields, groupby_field, context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 2140, in read_group
    cr.execute(query, where_clause_params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ERREUR:  la colonne account_invoice_report.section_id n'existe pas
LIGNE 4 :             WHERE (((("account_invoice_report"."section_id" ...
                                ^

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.
