### ISSUE TITLE
[8.0] Voucher validation

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5284]
We receive this message when we want to validate voucher
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 960, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 1045, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 816, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 100, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3478, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 552, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/addons/account_voucher/account_voucher.py", line 922, in proforma_voucher
    self.action_move_line_create(cr, uid, ids, context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account_voucher/account_voucher.py", line 1391, in action_move_line_create
    move_line_id = move_line_pool.create(cr, uid, self.first_move_line_get(cr,uid,voucher.id, move_id, company_currency, current_currency, local_context), local_context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/account_move_line.py", line 1394, in create
    recompute = journal.env.recompute and context.get('recompute', True)
ValueError: "'Environment' object has no attribute 'recompute'" while evaluating
u'proforma_voucher()'

**Comment by Sameer1990** [comment]
Please provide an more details and codes for your issue , or if this issue come in runbot odoo provide the process of this error .

**Comment by malatestay** [comment]
Hi, after updating 46774-8-0-9ffa3a Last update I found several errors including this one.
After entering a customer payment and allocation on invoices, I wanted to validate it that triggered the error.
In this context I had a flashback but I can do other tests if necessary.

**Comment by hhgabelgaard** [comment]
@malatestay I had the same problem. Turns out that I was hitting the wrong (read: old) api.py - Like you, hitting the dist-packages version: /usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py

**Comment by malatestay** [comment]
@hhgabelgaard thanks for this information but i download last version and i done a setup. I expect in this case that last apy.py is taken ....Can you confirm ?

**Comment by hhgabelgaard** [comment]
@malatestay if you ran setyp.py to install/update the Odoo/OpenERP python package, then yes. But it is easy to verify:
def recompute(self) was introduced in [api.py line 894](https://github.com/odoo/odoo/blame/8.0/openerp/api.py#L894) with c9154e0
Just check that line in the version you hit according to the stack trace

**Comment by morrillo** [comment]
I got the error this morning. I updated the source code, installed it and the error disappeared.

**Comment by bigmagic** [comment]
Hello,
I have same error.
I would like to know if you have a fix for this issue.
I tried to reverse the patch c9154e0 given by hhgabelgaard without success.
Thanks,
Nicolas

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.

**Comment by bigmagic** [comment]
I had found where was my problem : I had two copies of the odoo (one from the nightly build (system) and the second done during the migration). So the old API was used. I did an upgrade and the error disappeared.
