### ISSUE TITLE
[13.0] Google Calendar: Odoo allows to edit read-only events

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#52990]
Impacted versions: 13.0, 12.0, 11.0

Steps to reproduce:
You have to be participant in event that was organized by other person.
Event has to be created in Google Calendar first.

When you are not an organizer of event it has `guestsCanModify: false` by default. It means that you can not modify it.

However after such even was synced into Odoo I can modify it which causes update of even back to Google Calendar.
The request will return an error
```
ERROR odoo odoo.addons.google_account.models.google_service: Bad google request : b'{\n "error": {\n  "errors": [\n   {\n    "domain": "calendar",\n    "reason": "forbiddenForNonOrganizer",\n    "message": "Shared properties can only be changed by the organizer of the event."\n   }\n  ],\n  "code": 403,\n  "message": "Shared properties can only be changed by the organizer of the event."\n }\n}\n' ! 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/google_account/models/google_service.py", line 173, in _do_request
    res.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

Current behavior:
Odoo tries to sync read only events

Expected behavior:
Refuse to update event in Odoo if event was created from Google Calendar and current user is not an organizer of event and event has `guestsCanModify: false`.

Video/Screenshot link (optional):

**Comment by lem8r** [comment]
This issue is related to support ticket 2261173

I can fix it myself and do a PR but it requires changes in logic and model. So I believe it wont be accepted. At least without prior discussion.
