### ISSUE TITLE
httplib.py syntax error

### ISSUE THREAD

**Issue by kyronjoves** [odoo/odoo#53169]
Impacted versions: python version 3.6.8

Steps to reproduce:

Current behavior:
$ python odoo-bin -r dbuser -w passw0rd-- addons-path=addons -d mydb
Traceback (most recent call last):
  File "odoo-bin", line 5, in <module>
    import odoo
  File "C:\xampp\htdocs\odoo\odoo\__init__.py", line 113, in <module>
    from . import modules
  File "C:\xampp\htdocs\odoo\odoo\modules\__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "C:\xampp\htdocs\odoo\odoo\modules\graph.py", line 10, in <module>
    import odoo.tools as tools
  File "C:\xampp\htdocs\odoo\odoo\tools\__init__.py", line 9, in <module>
    from .misc import *
  File "C:\xampp\htdocs\odoo\odoo\tools\misc.py", line 29, in <module>
    import werkzeug.utils
  File "C:\Python27\lib\site-packages\werkzeug\__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "C:\Python27\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "C:\Python27\lib\site-packages\werkzeug\wrappers.py", line 37, in <module>
    from werkzeug.formparser import FormDataParser, default_stream_factory
  File "C:\Python27\lib\site-packages\werkzeug\formparser.py", line 28, in <module>
    from werkzeug.wsgi import make_line_iter, \
  File "C:\Python27\lib\site-packages\werkzeug\wsgi.py", line 13, in <module>
    import httplib
  File "C:\Python27\lib\httplib.py", line 408
    print "reply:", repr(line)
                 ^

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have a bad deployment with mix of Python versions, which is clearly stated by the line:
```
File "C:\Python27\lib\httplib.py", line 408
```
Any way, this is not an Odoo issue, but deployment one, so closing.

**Comment by kyronjoves** [comment]
Ohh okay. Its because just used same directory and I updated 2.7 to 3.6.8.
