### ISSUE TITLE
Issue with multi-company reconciliation and complexer record rules for res_partner and res_partner_bank

### ISSUE THREAD

**Issue by gbeuning** [odoo/odoo#53186]
Issue with multi-company reconciliation and complexer record rules for res_partner and res_partner_bank

Issue is related to multi-company reconciliation improvements:
https://github.com/odoo/odoo/commit/3303f871028f7f84539020c12125ee6c3b3dd5e4#diff-34f8ae8a5209bc49b57e881ee41799d7

The problem seems that with more complex record rules for res.partner.bank and res.partner models, 
such as installed by OCA multi-company modules, the string replacement commands may cause undesired replacements (e.g. part of table names are being replaced) in the SQL query. 

Change lines to fix:
Original:
`where_bank = ('AND %s' % where_clause).replace('res_partner_bank', 'bank') `
Replace by:
`where_bank = ('AND %s' % where_clause).replace('"res_partner_bank"', '"bank"') `

Original:
`where_partner = ('AND %s' % where_clause).replace('res_partner', 'p3') ` 
Replace by:
`where_partner = ('AND %s' % where_clause).replace('"res_partner"', '"p3"') `

Note the added double quotes.
This fixes the issue but I'm not sure if this is the best approach...
Tested on Odoo 12.0

**Comment by pedrobaeza** [comment]
Which is the error?

**Comment by gbeuning** [comment]
Traceback:
```
Traceback (most recent call last):

  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception

    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])

  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise

    raise value

  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/opt/odoo12/odoo/odoo/api.py", line 755, in call_kw

    return _call_kw_model(method, model, args, kwargs)

  File "/opt/odoo12/odoo/odoo/api.py", line 728, in _call_kw_model

    result = method(recs, *args, **kwargs)

  File "/opt/odoo12/odoo/addons/account/models/reconciliation_widget.py", line 210, in get_bank_statement_data

    results = self.get_bank_statement_line_data(bank_statement_lines.ids)

  File "/opt/odoo12/odoo/addons/account/models/reconciliation_widget.py", line 147, in get_bank_statement_line_data

    partner_map = self._get_bank_statement_line_partners(bank_statement_lines)

  File "/opt/odoo12/odoo/addons/account/models/reconciliation_widget.py", line 123, in _get_bank_statement_line_partners

    self._cr.execute(query, params)

  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper

    return f(self, *args, **kwargs)

  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute

    res = self._obj.execute(query, params)

psycopg2.ProgrammingError: relation "res_company_assignment_bank_rel" does not exist

LINE 6: ...mber AND ((("bank"."id" in (SELECT "bank_id" FROM "res_compa...
```

Additional info from the log where you can see SQL statement modified by additional record rules:
```
2020-06-17 07:39:22,035 2957 ERROR nxmaintest odoo.sql_db: bad query: 
            SELECT
                st_line.id                          AS id,
                COALESCE(p1.id,p2.id,p3.id)         AS partner_id
            FROM account_bank_statement_line st_line
        LEFT JOIN res_partner_bank bank ON bank.id = st_line.bank_account_id OR bank.acc_number = st_line.account_number AND ((("bank"."id" in (SELECT "bank_id" FROM "res_company_assignment_bank_rel" WHERE "res_company_assignment_id" IN (1)))  OR  ("bank"."id" in (SELECT "bank_id" FROM "res_company_assignment_bank_rel" WHERE "res_company_assignment_id" IN (1))))  OR  (("bank"."id" not in (344,347,341,343,346,342,348,349,340,339)) OR "bank"."id" IS NULL))
LEFT JOIN res_partner p1 ON st_line.partner_id=p1.id 
LEFT JOIN res_partner p2 ON bank.partner_id=p2.id 
LEFT JOIN res_partner p3 ON p3.name ILIKE st_line.partner_name AND ("p3"."active" = true) AND (((("p3"."id" in (SELECT "p3_id" FROM "res_company_assignment_p3_rel" WHERE "res_company_assignment_id" IN (1)))  OR  ("p3"."visible_for_all_companies" = true))  OR  (("p3"."id" not in (4,570,550,561,792,836,800,810,609,543,583,5,2,6,563,813,604)) OR "p3"."id" IS NULL))  AND  ((("p3"."type" != 'private')  OR  "p3"."type" IS NULL )  OR  ("p3"."type" = 'private'))) AND p3.parent_id is NULL 
WHERE st_line.id IN (2212)
ERROR: relation "res_company_assignment_bank_rel" does not exist
LINE 6: ...mber AND ((("bank"."id" in (SELECT "bank_id" FROM "res_compa...
```

**Comment by pedrobaeza** [comment]
But you are talking about a third party module, so the error should be fixed there, not here.

**Comment by gbeuning** [comment]
Hmm... I don't think so because it may occur with any add-on/modification that changes the record rules for res.partner.bank and res.partner models.

If you look here https://github.com/odoo/odoo/blob/db52d97e0902905c638e4b0c3bebc86bd1c7d2e0/addons/account/models/reconciliation_widget.py#L103

Value for `where_clause` in my case is (depending on the record rules that are in-place):
`("res_partner"."active" = %s) AND (((("res_partner"."id" in (SELECT "res_partner_id" FROM "res_company_assignment_res_partner_rel" WHERE "res_company_assignment_id" IN %s))  OR  ("res_partner"."visible_for_all_companies" = %s))  OR  (("res_partner"."id" not in (%s,%s,%s,%s,%s,%s,%s)) OR "res_partner"."id" IS NULL))  AND  ((("res_partner"."type" != %s)  OR  "res_partner"."type" IS NULL )  OR  ("res_partner"."type" = %s)))`

After the string replacement, value assigned to `where_partner` is:
`AND ("p3"."active" = %s) AND (((("p3"."id" in (SELECT "p3_id" FROM "res_company_assignment_p3_rel" WHERE "res_company_assignment_id" IN %s))  OR  ("p3"."visible_for_all_companies" = %s))  OR  (("p3"."id" not in (%s,%s,%s,%s,%s,%s,%s)) OR "p3"."id" IS NULL))  AND  ((("p3"."type" != %s)  OR  "p3"."type" IS NULL )  OR  ("p3"."type" = %s)))`

You see that for example table name `res_company_assignment_res_partner_rel` is erroneously being replaced by `res_company_assignment_p3_rel`

**Comment by pedrobaeza** [comment]
OK, indeed it seems a risky replace.

@qdp-odoo can you please check this?
