### ISSUE TITLE
short dump in vendor invoice payment

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5336]
when pressing the pay button in supplier invoice screen the following dump has occurred:
thanks in advance
Claudio 
Odoo Server Error
Traceback (most recent call last):
  File "C:\Odoo 8.0\server.\openerp\http.py", line 524, in _handle_exception
  File "C:\Odoo 8.0\server.\openerp\http.py", line 545, in dispatch
  File "C:\Odoo 8.0\server.\openerp\http.py", line 301, in _call_function
  File "C:\Odoo 8.0\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0\server.\openerp\http.py", line 298, in checked_call
  File "C:\Odoo 8.0\server.\openerp\http.py", line 761, in __call__
  File "C:\Odoo 8.0\server.\openerp\http.py", line 394, in response_wrap
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 949, in call_kw
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server.\openerp\api.py", line 360, in old_api
  File "C:\Odoo 8.0\server.\openerp\models.py", line 5768, in onchange
  File "C:\Odoo 8.0\server.\openerp\models.py", line 5702, in _onchange_eval
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\account_voucher\account_voucher.py", line 859, in onchange_date
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\account_voucher\account_voucher.py", line 829, in onchange_payment_rate_currency
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\account_voucher\account_voucher.py", line 531, in onchange_rate
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\account_voucher\account_voucher.py", line 273, in _get_currency_help_label
  File "C:\Odoo 8.0\server.\openerp\report\report_sxw.py", line 246, in formatLang
  File "C:\Odoo 8.0\server.\openerp\api.py", line 235, in wrapper
  File "C:\Odoo 8.0\server.\openerp\api.py", line 552, in new_api
  File "C:\Odoo 8.0\server\openerp\addons\base\res\res_lang.py", line 221, in format
  File "C:\Odoo 8.0\server\openerp\addons\base\res\res_lang.py", line 282, in intersperse
  File "C:\Odoo 8.0\server\openerp\addons\base\res\res_lang.py", line 265, in split
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
