### ISSUE TITLE
wkhtmltopdf issue

### ISSUE THREAD

**Issue by ramitalat** [odoo/odoo#5374]
After installing Odoo on Ubuntu 14.04, and installing wkhtmltopdf pkg, I'm still unable to print Odoo reports. so after searching the web, I found that I should run the following command:
$ sudo apt-get -f install
But I'm now -unfortunately- get this error:
 
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/report/controllers/main.py", line 125, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 190, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/report.py", line 165, in get_html
    return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/report/models/abstract_report.py", line 64, in render_html
    return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/report_rtl/models/report.py", line 52, in render
    langs = self.pool.get('res.lang').get_languages_dir(cr, uid, [], context=context)
AttributeError: 'res.lang' object has no attribute 'get_languages_dir'

Can anybody help?

**Comment by sle-odoo** [comment]
Hi,
Seeing the traceback, it seems to me that your issue is not linked to wkhtmltopdf but to the `report_rtl` module, which is not supported by Odoo.

**Comment by Sameer1990** [comment]
Try to uninstall report_rtl module then print your report .

**Comment by ramitalat** [comment]
Yes, it works.
Thanks
