### ISSUE TITLE
Failed to load server-wide module `web` onchange() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by lecciovich** [odoo/odoo#53873]
Impacted versions: Odoo 12

Current behavior: Odoo fails to load server-wide module `web`

Expected behavior: Odoo load server-wide module 'web'

Hi,
while restarting odoo service from pycharm I have got errors starting from loading module 'web'.
postgresql service is running and web module.
the command launched form IDE is odoo-bin -c /home/user/Odoo/odoo-12.0/odoo.conf --dev=reload -u /home/user/Odoo/odoo-12.0/addons.
I'm gonna report  below my conf file and entire error.

`[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /home/odoovm/Odoo/odoo-12.0/addons,/home/odoovm/Odoo/odoo-12.0/master-app
xmlrpc_port = 8099

[logging]
; logfile = /home/odoovm/Odoo/odoo-12.0/logs/openerp-server.log
; logrotate = False
log-level = debug
; log-db = False
; syslog = False`

`/usr/bin/python3.6 /home/odoovm/Odoo/odoo-12.0/odoo-bin -c /home/odoovm/Odoo/odoo-12.0/odoo.conf --dev=reload -u /home/odoovm/Odoo/odoo-12.0/addons
2020-06-30 13:53:03,589 4326 INFO ? odoo: Odoo version 12.0 
2020-06-30 13:53:03,589 4326 INFO ? odoo: Using configuration file at /home/odoovm/Odoo/odoo-12.0/odoo.conf 
2020-06-30 13:53:03,589 4326 INFO ? odoo: addons paths: ['/home/odoovm/.local/share/Odoo/addons/12.0', '/home/odoovm/Odoo/odoo-12.0/addons', '/home/odoovm/Odoo/odoo-12.0/master-app', '/home/odoovm/Odoo/odoo-12.0/odoo/addons'] 
2020-06-30 13:53:03,599 4326 INFO ? odoo: database: odoo@localhost:5432 
2020-06-30 13:53:03,630 4326 CRITICAL ? odoo.modules.module: Couldn't load module base 
2020-06-30 13:53:03,630 4326 CRITICAL ? odoo.modules.module: onchange() takes 1 positional argument but 3 were given 
2020-06-30 13:53:03,630 4326 ERROR ? odoo.service.server: Failed to load server-wide module `base`. 
Traceback (most recent call last):
  File "/home/odoovm/Odoo/odoo-12.0/odoo/service/server.py", line 1098, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/odoovm/Odoo/odoo-12.0/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/odoovm/Odoo/odoo-12.0/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 5, in <module>
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/__init__.py", line 7, in <module>
    from . import ir_model
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 330, in <module>
    class IrModelFields(models.Model):
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 520, in IrModelFields
    @api.onchange('ttype', 'model_id', 'relation')
TypeError: onchange() takes 1 positional argument but 3 were given
2020-06-30 13:53:03,646 4326 WARNING ? odoo.service.server: 'inotify' module not installed. Code autoreload feature is disabled 
2020-06-30 13:53:03,651 4326 INFO ? odoo.service.server: HTTP service (werkzeug) running on odoovm-VirtualBox:8099 
Exception in thread odoo.service.cron.cron0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/odoovm/Odoo/odoo-12.0/odoo/service/server.py", line 425, in target
    self.cron_thread(i)
  File "/home/odoovm/Odoo/odoo-12.0/odoo/service/server.py", line 396, in cron_thread
    from odoo.addons.base.models.ir_cron import ir_cron
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/__init__.py", line 7, in <module>
    from . import ir_model
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 330, in <module>
    class IrModelFields(models.Model):
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 520, in IrModelFields
    @api.onchange('ttype', 'model_id', 'relation')
TypeError: onchange() takes 1 positional argument but 3 were given

Exception in thread odoo.service.cron.cron1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/odoovm/Odoo/odoo-12.0/odoo/service/server.py", line 425, in target
    self.cron_thread(i)
  File "/home/odoovm/Odoo/odoo-12.0/odoo/service/server.py", line 396, in cron_thread
    from odoo.addons.base.models.ir_cron import ir_cron
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/__init__.py", line 7, in <module>
    from . import ir_model
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 330, in <module>
    class IrModelFields(models.Model):
  File "/home/odoovm/Odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 520, in IrModelFields
    @api.onchange('ttype', 'model_id', 'relation')
TypeError: onchange() takes 1 positional argument but 3 were given
`

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
