### ISSUE TITLE
The POS order must have lines when calling this method

### ISSUE THREAD

**Issue by apropsi** [odoo/odoo#53900]
Impacted versions:
12
Steps to reproduce:
Try to close POS
Current behavior:
Can't close POS
Expected behavior:
Should close POS
Video/Screenshot link (optional):
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/aprop/aprop-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/aprop/aprop-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/aprop/aprop-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/aprop/aprop-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/aprop/aprop-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/aprop/aprop-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/aprop/aprop-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/aprop/aprop-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/aprop/aprop-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/aprop/aprop-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/aprop/aprop-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/aprop/aprop-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/aprop/aprop-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/aprop/aprop-server/addons/point_of_sale/models/pos_session.py", line 261, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/aprop/aprop-server/addons/point_of_sale/models/pos_session.py", line 290, in action_pos_session_close
    self.with_context(ctx)._confirm_orders()
  File "/aprop/aprop-server/addons/point_of_sale/models/pos_session.py", line 30, in _confirm_orders
    orders.with_context(force_company=company_id)._create_account_move_line(session, move)
  File "/aprop/aprop-server/addons/point_of_sale/models/pos_order.py", line 351, in _create_account_move_line
    assert order.lines, _('The POS order must have lines when calling this method')
AssertionError: La orden TPV debe tener líneas cuando llama a este método

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by apropsi** [comment]
I found the problem but i dont know how to solve it.
Problem is that POS has an order payed but without any product.
How can i solve that? Cant edit or delete.

**Comment by pedrobaeza** [comment]
If that situation comes using Odoo with its UI, then it's a bug that should be solved.

**Comment by apropsi** [comment]
It is, POS havent any extra module

**Comment by pedrobaeza** [comment]
But the steps to reproduce the problem of not having a product?
