### ISSUE TITLE
filter not work for small float number

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#54038]
Impacted versions: 13.0 or others 

Steps to reproduce:

search view, add Custom filter, select a float field, less than, 0.0000001 

Current behavior:

Error:
Uncaught Error: Expected "]", got "(name)"

Traceback:
Error: Expected "]", got "(name)"
    at advance (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:360:19)
    at F.symbol.nud (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:232:9)
    at expression (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:350:22)
    at F.symbol.nud (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:225:33)
    at expression (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:350:22)
    at Object.py.parse (http://140.207.25.194:6388/web/static/lib/py.js/lib/py.js:1326:16)
    at _getPyJSAST (http://140.207.25.194:6388/web/static/src/js/core/py_utils.js:504:15)
    at Array.map (<anonymous>)
    at Object.assembleDomains (http://140.207.25.194:6388/web/static/src/js/core/py_utils.js:355:24)
    at Class._getGroupDomain

**Comment by GoodERPJeff** [comment]
After research I found when float less then 0.000001, js will convert it to Exponential, like 1e-7, this make the py.js wrog

**Comment by jeffery9** [comment]
为什么要 查这么小的 数值 呢，精确度也不好保证呀。

**Comment by leangjia** [comment]
Good job.

**Comment by Yenthe666** [comment]
@ged-odoo probably for your team to check (and if we even want to support it)

**Comment by jackxusho** [comment]
> @ged-odoo probably for your team to check (and if we even want to support it)Is there any modification  or improvement on the issue? This filter issue could ruin a application somehow.

**Comment by Yenthe666** [comment]
No there is no improvement/change. As long as nobody from Odoo replies there's no update.
