### ISSUE TITLE
[8.0] Error following last port : port b0be8df

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5411]
After update Odoo V8 we have these error

First :

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 932, in _call_kw
    records = getattr(request.session.model(model), method)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 844, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3078, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3274, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/osv/fields.py", line 1356, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/account/partner.py", line 246, in _invoice_total
    result[partner.id] = sum(inv.user_currency_price_total for inv in invoices)
  File "/opt/odoo/addons/account/partner.py", line 246, in <genexpr>
    result[partner.id] = sum(inv.user_currency_price_total for inv in invoices)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 767, in __get__
    self.determine_value(record)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 860, in determine_value
    record._prefetch_field(self)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3165, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3261, in _read_from_database
    res2 = self._columns[fs[0]].get(cr, self._model, ids, fs, user, context=context, values=result)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/osv/fields.py", line 1356, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/account/report/account_invoice_report.py", line 52, in _compute_amounts_in_user_currency
    ctx['date'] = item.date
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 767, in __get__
    self.determine_value(record)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/fields.py", line 860, in determine_value
    record._prefetch_field(self)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3165, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3222, in _read_from_database
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ERREUR:  la colonne account_invoice_report.section_id n'existe pas
LIGNE 1 : ...ccount_line_id",account_invoice_report."residual",account_in...
                                                               ^

when we open a invoce and clic on partner name.

Second in somes views:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5711, in onchange
    if field_name and field_name not in self._fields:
TypeError: unhashable type: 'list'

**Comment by oerp-odoo** [comment]
Got the same problem

**Comment by malatestay** [comment]
@oerp-odoo have news ?

**Comment by oerp-odoo** [comment]
@malatestay  to mee this error happened, because I accidentally ran server using old server source code. When I switched to current source code, this problem disappeared.

**Comment by malatestay** [comment]
@oerp-odoo I just do a new installation with last source. 
I done a setup.py and update all for my database and i have always this error

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5711, in onchange
    if field_name and field_name not in self._fields:
TypeError: unhashable type: 'list'

**Comment by netdrag** [comment]
I get this error using the debian wheezy repository

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.

**Comment by mylbco** [comment]
I also have this error
