### ISSUE TITLE
dump in creating RfQ in call of bids module

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5413]
in pressing the "Request a Quotation! button the following short dump occurred:
thanks in advance
claudio 

Traceback (most recent call last):
  File "C:\Odoo 8.0\server.\openerp\http.py", line 524, in _handle_exception
  File "C:\Odoo 8.0\server.\openerp\http.py", line 545, in dispatch
  File "C:\Odoo 8.0\server.\openerp\http.py", line 301, in _call_function
  File "C:\Odoo 8.0\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0\server.\openerp\http.py", line 298, in checked_call
  File "C:\Odoo 8.0\server.\openerp\http.py", line 761, in __call__
  File "C:\Odoo 8.0\server.\openerp\http.py", line 394, in response_wrap
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 953, in call_button
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\purchase_requisition\wizard\purchase_requisition_partner.py", line 45, in create_order
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\purchase_requisition\purchase_requisition.py", line 195, in make_purchase_order
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\purchase_requisition\purchase_requisition.py", line 168, in _prepare_purchase_order_line
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\warning\warning.py", line 249, in onchange_product_id
  File "C:\Odoo 8.0\server\openerp\addons\purchase\purchase.py", line 1155, in onchange_product_id
  File "C:\Odoo 8.0\server.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\openerp\addons\account\partner.py", line 69, in map_tax
  File "C:\Odoo 8.0\server.\openerp\fields.py", line 774, in __get__
  File "C:\Odoo 8.0\server.\openerp\fields.py", line 867, in determine_value
  File "C:\Odoo 8.0\server.\openerp\api.py", line 235, in wrapper
  File "C:\Odoo 8.0\server.\openerp\models.py", line 3178, in _prefetch_field
  File "C:\Odoo 8.0\server.\openerp\api.py", line 235, in wrapper
  File "C:\Odoo 8.0\server.\openerp\models.py", line 3123, in read
  File "C:\Odoo 8.0\server.\openerp\api.py", line 235, in wrapper
  File "C:\Odoo 8.0\server.\openerp\models.py", line 3235, in _read_from_database
  File "C:\Odoo 8.0\server.\openerp\sql_db.py", line 158, in wrapper
  File "C:\Odoo 8.0\server.\openerp\sql_db.py", line 234, in execute
  File "psycopg2\extensions.pyc", line 129, in getquoted
ProgrammingError: can't adapt type 'account.fiscal.position'

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
