### ISSUE TITLE
[13.0] Removal of TransientModel if it has a Many2many field fails

### ISSUE THREAD

**Issue by kkarolis** [odoo/odoo#54178]
I encountered this issue while I was trying to remove a wizard with Many2many fields related to a normal model.

Impacted versions: **13.0**, commits checked,- [**fb377a8**](https://github.com/odoo/odoo/tree/fb377a8f1bf2bea020c14ea57997ea9078a54e5f) and [**0b27dc7**](https://github.com/odoo/odoo/tree/0b27dc797c35704c3c46965077dde4d369dc4efb) (current latest)

Steps to reproduce:

I have produced a minimal addon [problematic_addon.zip](https://github.com/odoo/odoo/files/4883997/problematic_addon.zip) demonstrating the problematic case. It demonstrates a simple wizard `problematic.wizard` with a `Many2many` relation to `res.partner` field

1. Install `problematic_addon` into a new database: `-i problematic_addon`
2. Apply the patch to remove the wizard model `patch < disable_wizard.patch`
3. Update the module `-u problematic_addon`

Current behavior: Traceback below followed by endless update loop.

Traceback:
```
2020-07-07 09:21:54,991 27 INFO relation-bug odoo.addons.base.models.ir_model: Deleting 105@ir.model (problematic_addon.model_problematic_wizard)
2020-07-07 09:21:54,993 27 WARNING relation-bug odoo.addons.base.models.ir_model: The model problematic.wizard could not be dropped because it did not exist in the registry.
2020-07-07 09:21:54,996 27 ERROR relation-bug odoo.sql_db: bad query: DELETE FROM ir_model WHERE id IN (105)
ERROR: update or delete on table "ir_model" violates foreign key constraint "ir_model_relation_model_fkey" on table "ir_model_relation"
DETAIL:  Key (id)=(105) is still referenced from table "ir_model_relation".

2020-07-07 09:21:54,997 27 WARNING relation-bug odoo.modules.loading: Transient module states were reset
2020-07-07 09:21:55,011 27 ERROR relation-bug odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/modules/loading.py", line 472, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/addons/base/models/ir_model.py", line 1990, in _process_end
    record.unlink()
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/addons/base/models/ir_model.py", line 218, in unlink
    res = super(IrModel, self).unlink()
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/models.py", line 3348, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: update or delete on table "ir_model" violates foreign key constraint "ir_model_relation_model_fkey" on table "ir_model_relation"
DETAIL:  Key (id)=(105) is still referenced from table "ir_model_relation".

2020-07-07 09:21:55,013 27 CRITICAL relation-bug odoo.service.server: Failed to initialize database `relation-bug`.
Traceback (most recent call last):
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/modules/loading.py", line 472, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/addons/base/models/ir_model.py", line 1990, in _process_end
    record.unlink()
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/addons/base/models/ir_model.py", line 218, in unlink
    res = super(IrModel, self).unlink()
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/models.py", line 3348, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/venvs/odoo/lib/python3.6/site-packages/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: update or delete on table "ir_model" violates foreign key constraint "ir_model_relation_model_fkey" on table "ir_model_relation"
DETAIL:  Key (id)=(105) is still referenced from table "ir_model_relation".
```

Expected behavior: Clean removal of the wizard model.

Am I missing something? I've checked other wizard definitions in the Odoo codebase and they don't seem to handle Many2many in any special way.

**Comment by pedrobaeza** [comment]
@sswapnesh I remember you faced this. Can it be?

**Comment by sswapnesh** [comment]
Not this one, But I remember @Elkasitu has said 

> Deleting a model is considered an "unstable change" 

https://github.com/odoo/odoo/issues/44767#issuecomment-584023362

**Comment by Yenthe666** [comment]
Yep, @Elkasitu labeled this as unsupported so let's close it.
