### ISSUE TITLE
Customer Import on GUI fails with error message

### ISSUE THREAD

**Issue by larrym** [odoo/odoo#5418]
I created a test CSV file and tried to Validate it before the actual import. After hitting the Validate button a red line across the total width of the mapped data and below the "The first row of the file contains the label of the column" checkbox appeared. When I checked the /var/log/odoo/odoo-server.log, it showed the following:

```
50785 2015-02-21 21:17:51,201 1019 INFO acedemo werkzeug: 192.168.10.12 - - [21/Feb/2015 21:17:51] "POST /longpolling/poll HT      TP/1.1" 200 -
50786 2015-02-21 21:18:08,271 1019 INFO acedemo openerp.addons.base_import.models: importing 5 rows...
50787 2015-02-21 21:18:08,290 1019 ERROR acedemo openerp.http: Exception during JSON request handling.
50788 Traceback (most recent call last):
50789   File "/mnt/data/odoo/openerp/http.py", line 524, in _handle_exception
50790     return super(JsonRequest, self)._handle_exception(exception)
50791   File "/mnt/data/odoo/openerp/http.py", line 545, in dispatch
50792     result = self._call_function(**self.params)
50793   File "/mnt/data/odoo/openerp/http.py", line 301, in _call_function
50794     return checked_call(self.db, *args, **kwargs)
50795   File "/mnt/data/odoo/openerp/service/model.py", line 113, in wrapper
50796     return f(dbname, *args, **kwargs)
50797   File "/mnt/data/odoo/openerp/http.py", line 298, in checked_call
50798     return self.endpoint(*a, **kw)
50799   File "/mnt/data/odoo/openerp/http.py", line 761, in __call__
50800     return self.method(*args, **kw)
50801   File "/mnt/data/odoo/openerp/http.py", line 394, in response_wrap
50802     response = f(*args, **kw)
50803   File "/mnt/data/odoo/addons/web/controllers/main.py", line 949, in call_kw
50804     return self._call_kw(model, method, args, kwargs)
50805   File "/mnt/data/odoo/addons/web/controllers/main.py", line 941, in _call_kw
50806     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
50807   File "/mnt/data/odoo/openerp/api.py", line 237, in wrapper
50808     return old_api(self, *args, **kwargs)
50809   File "/mnt/data/odoo/addons/base_import/models.py", line 327, in do
50810     cr, uid, import_fields, data, context=context)
50811   File "/mnt/data/odoo/openerp/api.py", line 237, in wrapper
50812     return old_api(self, *args, **kwargs)
50813   File "/mnt/data/odoo/openerp/models.py", line 1071, in load
50814     context=context, log=messages.append):
50815   File "/mnt/data/odoo/openerp/models.py", line 1244, in _convert_records
50816     converted = convert(record, lambda field, err:\
50817   File "/mnt/data/odoo/openerp/addons/base/ir/ir_fields.py", line 68, in fn
50818     converted[field], ws = converters[field](value)
50819   File "/mnt/data/odoo/openerp/api.py", line 235, in wrapper
50820     return new_api(self, *args, **kwargs)
50821   File "/mnt/data/odoo/openerp/addons/base/ir/ir_fields.py", line 364, in _str_to_many2one
50822     id, _, w2 = self.db_id_for(model, field, subfield, reference)
50823   File "/mnt/data/odoo/openerp/api.py", line 235, in wrapper
50824     return new_api(self, *args, **kwargs)
50825   File "/mnt/data/odoo/openerp/addons/base/ir/ir_fields.py", line 316, in db_id_for
50826     ids = RelatedModel.name_search(name=value, operator='=')
50827 TypeError: location_name_search() takes at least 3 arguments (3 given)
50828 2015-02-21 21:18:08,292 1019 INFO acedemo werkzeug: 192.168.10.12 - - [21/Feb/2015 21:18:08] "POST /web/dataset/call_kw      /base_import.import/do HTTP/1.1" 200 -
```

**Comment by larrym** [comment]
I think this must have been an error on my part, beginner as I am. I think that I did not include the required fields highlighted in blue.
