### ISSUE TITLE
[8.0] Inherit 'account.journal' model: KeyError

### ISSUE THREAD

**Issue by georgetsag** [odoo/odoo#5419]
I wrote a custom module and I try to inherit account.journal model. When I install the first time my module there is no error. When I restarted the server with my module installed I get:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo_test/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/opt/odoo_test/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo_test/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo_test/openerp/http.py", line 1245, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo_test/openerp/http.py", line 1219, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo_test/openerp/http.py", line 1377, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/odoo_test/openerp/http.py", line 337, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/odoo_test/openerp/modules/registry.py", line 315, in get
    update_module)
  File "/opt/odoo_test/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo_test/openerp/modules/loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo_test/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo_test/openerp/modules/loading.py", line 158, in load_module_graph
    models = registry.load(cr, package)
  File "/opt/odoo_test/openerp/modules/registry.py", line 148, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo_test/openerp/models.py", line 595, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "/opt/odoo_test/openerp/modules/registry.py", line 101, in __getitem__
    return self.models[model_name]
KeyError: 'account.journal'

The code from my module that causes the error is:

class account_journal_add(models.Model):
	_inherit='account.journal'
	is_cheque=fields.Boolean(string="Cheque")

**Comment by georgetsag** [comment]
I had forgotten to add the account module at depends  at  __openerp__.py
