### ISSUE TITLE
[8.0] Validate invoice results..object has no attribute 'recompute'

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5434]
OpenERP Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 526, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 282, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 742, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 378, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 960, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 1045, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 816, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 100, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 183, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 177, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3478, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/account_invoice.py", line 916, in action_move_create
    move = account_move.with_context(ctx).create(move_vals)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/addons/account/account.py", line 1394, in create
    result = super(account_move, self).create(cr, uid, vals, c)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 3994, in create
    record = self.browse(self._create(old_vals))
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 4179, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/osv/fields.py", line 742, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/account/account_move_line.py", line 1399, in create
    recompute = journal.env.recompute and context.get('recompute', True)
ValueError: "'Environment' object has no attribute 'recompute'" while evaluating
u'action_move_create()'

**Comment by Sameer1990** [comment]
Please provide `How to reproduce` and `Impacted versions` , to make others help you correctly .

**Comment by malatestay** [comment]
@Sameer1990 I do that after upgrade yesterday evening (French time), i stat from timesheet to invoice, that is ok but when we want to validate draft invoice i have error previouly done.i propose to upgrade with last version this afternoon and go back when we reproduce same.

**Comment by malatestay** [comment]
@Sameer1990 see video io have reproduce error.
http://youtu.be/ObzMdh--utA

**Comment by lapagept** [comment]
I get this error too. Analyzing this.

**Comment by llacroix** [comment]
This seems to be an error related to this.

https://github.com/odoo/odoo/pull/5703

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.
