### ISSUE TITLE
Can not edit users

### ISSUE THREAD

**Issue by tanmaysathe** [odoo/odoo#5437]
Odoo Server Error

Traceback (most recent call last):

File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 530, in _handle_exception File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 567, in dispatch File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 303, in _call_function File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\service\model.py", line 113, in wrapper File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 300, in checked_call File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 796, in __call__ File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\http.py", line 396, in response_wrap File "C:\Program Files\Odoo 8.0-20150223\server\openerp\addons\web\controllers\main.py", line 949, in call_kw File "C:\Program Files\Odoo 8.0-20150223\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\api.py", line 241, in wrapper File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\models.py", line 1552, in fields_view_get File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\api.py", line 241, in wrapper File "C:\Program Files\Odoo 8.0-20150223\server\openerp\addons\base\ir\ir_ui_view.py", line 843, in postprocess_and_fields File "C:\Program Files\Odoo 8.0-20150223\server.\openerp\api.py", line 241, in wrapper File "C:\Program Files\Odoo 8.0-20150223\server\openerp\addons\base\ir\ir_ui_view.py", line 367, in raise_view_error AttributeError: Field `in_group_15` does not exist

Error context: View `res.users.form`

[view_id: 153, xml_id: base.view_users_form, model: res.users, parent_id: n/a]

**Comment by Sameer1990** [comment]
Please provide `How to reproduce` and `Impacted versions` , to set issue or not .

**Comment by Yenthe666** [comment]
Hi @tanmaysathe ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Please do add more information on future bug reports.

Regards,
Yenthe
