### ISSUE TITLE
Update model fails for hr.employee object

### ISSUE THREAD

**Issue by peterchibunna** [odoo/odoo#5460]
I tried to update an employee details from the xmlrpc. It fails with the error message

```
openerp.netsvc: write() takes exactly 6 arguments (5 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/addons/audittrail/audittrail.py", line 532, in execute_cr
    return fct_src(cr, uid, model, method, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp-7.0_20150225-py2.7.egg/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
TypeError: write() takes exactly 6 arguments (5 given)
```

Meanwhile, I have audit rules monitoring the `hr.employee` object. I unsubscribed the rule, It still fails. I delete the rule, It still fails.

**Comment by peterchibunna** [comment]
Actually I tried to isolate issues. It still fails when I remove the audittrail module. I'm still investigating.

**Comment by peterchibunna** [comment]
Did anyone else experience this? I have been able to isolate it to the `hr.employee` object. I tried the `res.partner` object. IT works; but fails for the Employee object.
