### ISSUE TITLE
Add support for werkzeug 1.x

### ISSUE THREAD

**Issue by sdelafond** [odoo/odoo#54980]
Impacted versions: 13.0

Steps to reproduce: Install on Debian sid with werkzeug 1.0.1

Current behavior: exception thrown at startup

Expected behavior: service runs correctly

Here is the stracktrace:

```
  Started Odoo Open Source ERP and CRM.
  Traceback (most recent call last):
  File "/usr/bin/odoo", line 5, in <module>
     import odoo
   File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 117, in <module>
     from . import service
   File "/usr/lib/python3/dist-packages/odoo/service/__init__.py", line 7, in <module>
     from . import wsgi_server
   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 25, in <module>
     import werkzeug.contrib.fixers
```

In the meantime, setup.py could probably be amended to explicitely list `werkzeug < 1.0`.

**Comment by Yenthe666** [comment]
@d-fence probably for you :)

**Comment by xnox** [comment]
As per https://werkzeug.palletsprojects.com/en/1.0.x/changes/

ProxyFix moved to middleware.proxy_fix

**Comment by xnox** [comment]
securecookie and sessions have been extracted into a separate project, secure-cookie. The version in Werkzeug is deprecated.

**Comment by xnox** [comment]
class secure_cookie.session.Session(data, sid, new=False) needs to be used, but like not packaged in debian it seems

**Comment by d-fence** [comment]
This PR #54785  in preparation should fix this issue

**Comment by gustavovalverde** [comment]
Are we still holding onto Werkzeug <= 0.x?

**Comment by Yenthe666** [comment]
Oh yes:
https://github.com/odoo/odoo/blob/4d9245f3b31483f5b92d07f0b5d740c5a8bf6f6d/requirements.txt#L43
