### ISSUE TITLE
[All versions] Unable to run odoo with newest Arch Linux packages

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#55032]
**Impacted versions:**

13.0, 11.0
Probably other versions

**Steps to reproduce:**

Try to run or update odoo, using updated arch linux

**Current behavior:**

```
2020-07-28 09:19:30,641 19612 INFO odoo13 odoo.modules.loading: loading web/data/report_layout.xml 
2020-07-28 09:19:30,694 19612 ERROR odoo13 odoo.tools.convert.init: Could not eval(obj()._get_asset_style_b64()) for datas in {} 
2020-07-28 09:19:30,699 19612 WARNING odoo13 odoo.modules.loading: Transient module states were reset 
2020-07-28 09:19:30,700 19612 ERROR odoo13 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/gk/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gk/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f7cc35e3d30>, 219, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 315, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Name node can't be used with 'None' constant
Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/gk/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gk/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f7cc35e3d30>, 219, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 315, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: web.styles_company_report
Path: /t/t/t[10]
Node: <t t-elif="layout == 'web.external_layout_standard'">
                &amp;.o_report_layout_standard {
                    h2 {
                        color: <t t-esc="primary"/>;
                    }
                    #informations strong {
                        color: <t t-esc="secondary"/>;
                    }
                    #total strong{
                        color: <t t-esc="primary"/>;
                    }
                    table {
                        thead {
                            color: <t t-esc="secondary"/>;
                        }
                    }
                }
            </t>
            }
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 374, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
ValueError: <class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating
'obj()._get_asset_style_b64()'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gk/odoo13/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/gk/odoo13/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/gk/odoo13/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/gk/odoo13/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/gk/odoo13/odoo/tools/convert.py", line 715, in parse
    pycompat.reraise(
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 374, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.tools.convert.ParseError: "<class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating
'obj()._get_asset_style_b64()'" while parsing /home/gk/odoo13/addons/web/data/report_layout.xml:2, near
<odoo>
    <data>
        <record id="report_layout_standard" model="report.layout">
            <field name="name">Standard</field>
            <field name="view_id" ref="web.external_layout_standard"/>
            <field name="image">/web/static/img/preview_standard.png</field>
            <field name="pdf">/web/static/pdf/preview_standard.pdf</field>
        </record>
        <record id="report_layout_background" model="report.layout">
            <field name="name">Background</field>
            <field name="view_id" ref="web.external_layout_background"/>
            <field name="image">/web/static/img/preview_background.png</field>
            <field name="pdf">/web/static/pdf/preview_background.pdf</field>
        </record>
        <record id="report_layout_boxed" model="report.layout">
            <field name="name">Boxed</field>
            <field name="view_id" ref="web.external_layout_boxed"/>
            <field name="image">/web/static/img/preview_boxed.png</field>
            <field name="pdf">/web/static/pdf/preview_boxed.pdf</field>
        </record>
        <record id="report_layout_clean" model="report.layout">
            <field name="name">Clean</field>
            <field name="view_id" ref="web.external_layout_clean"/>
            <field name="image">/web/static/img/preview_clean.png</field>
            <field name="pdf">/web/static/pdf/preview_clean.pdf</field>
        </record>
        <record id="asset_styles_company_report" model="ir.attachment">
            <field name="datas" model="res.company" eval="obj()._get_asset_style_b64()"/>
            <field name="mimetype">text/scss</field>
            <field name="name">res.company.scss</field>
            <field name="type">binary</field>
            <field name="url">/web/static/src/scss/asset_styles_company_report.scss</field>
        </record>
    </data>
</odoo>
2020-07-28 09:19:30,704 19612 ERROR odoo13 odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/gk/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gk/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f7cc35e3d30>, 219, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 315, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Name node can't be used with 'None' constant
Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/gk/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gk/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f7cc35e3d30>, 219, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 315, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: web.styles_company_report
Path: /t/t/t[10]
Node: <t t-elif="layout == 'web.external_layout_standard'">
                &amp;.o_report_layout_standard {
                    h2 {
                        color: <t t-esc="primary"/>;
                    }
                    #informations strong {
                        color: <t t-esc="secondary"/>;
                    }
                    #total strong{
                        color: <t t-esc="primary"/>;
                    }
                    table {
                        thead {
                            color: <t t-esc="secondary"/>;
                        }
                    }
                }
            </t>
            }
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 374, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
ValueError: <class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating
'obj()._get_asset_style_b64()'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gk/odoo13/odoo/service/db.py", line 62, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/home/gk/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gk/odoo13/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/gk/odoo13/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/gk/odoo13/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/gk/odoo13/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/gk/odoo13/odoo/tools/convert.py", line 715, in parse
    pycompat.reraise(
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 563, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/gk/odoo13/odoo/tools/convert.py", line 32, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 374, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/gk/odoo13/odoo/tools/safe_eval.py", line 351, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/gk/odoo13/addons/web/models/models.py", line 390, in _get_asset_style_b64
    company_styles = template_style.render({
  File "/home/gk/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
  File "/home/gk/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/gk/odoo13/odoo/addons/base/models/qweb.py", line 323, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.tools.convert.ParseError: "<class 'odoo.addons.base.models.qweb.QWebException'>: "Error when compiling AST" while evaluating
'obj()._get_asset_style_b64()'" while parsing /home/gk/odoo13/addons/web/data/report_layout.xml:2, near
<odoo>
    <data>
        <record id="report_layout_standard" model="report.layout">
            <field name="name">Standard</field>
            <field name="view_id" ref="web.external_layout_standard"/>
            <field name="image">/web/static/img/preview_standard.png</field>
            <field name="pdf">/web/static/pdf/preview_standard.pdf</field>
        </record>
        <record id="report_layout_background" model="report.layout">
            <field name="name">Background</field>
            <field name="view_id" ref="web.external_layout_background"/>
            <field name="image">/web/static/img/preview_background.png</field>
            <field name="pdf">/web/static/pdf/preview_background.pdf</field>
        </record>
        <record id="report_layout_boxed" model="report.layout">
            <field name="name">Boxed</field>
            <field name="view_id" ref="web.external_layout_boxed"/>
            <field name="image">/web/static/img/preview_boxed.png</field>
            <field name="pdf">/web/static/pdf/preview_boxed.pdf</field>
        </record>
        <record id="report_layout_clean" model="report.layout">
            <field name="name">Clean</field>
            <field name="view_id" ref="web.external_layout_clean"/>
            <field name="image">/web/static/img/preview_clean.png</field>
            <field name="pdf">/web/static/pdf/preview_clean.pdf</field>
        </record>
        <record id="asset_styles_company_report" model="ir.attachment">
            <field name="datas" model="res.company" eval="obj()._get_asset_style_b64()"/>
            <field name="mimetype">text/scss</field>
            <field name="name">res.company.scss</field>
            <field name="type">binary</field>
            <field name="url">/web/static/src/scss/asset_styles_company_report.scss</field>
        </record>
    </data>
</odoo>
2020-07-28 09:19:30,711 19612 INFO odoo13 odoo.modules.loading: loading 1 modules... 
2020-07-28 09:19:30,725 19612 INFO odoo13 odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries 
2020-07-28 09:19:30,881 19612 INFO odoo13 odoo.modules.loading: Modules loaded. 
2020-07-28 09:19:30,941 19612 INFO odoo13 odoo.addons.base.models.res_users: Login successful for db:odoo13 login:admin from 95.108.16.209 
2020-07-28 09:19:30,955 19612 INFO odoo13 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2020-07-28 09:19:30,962 19612 INFO odoo13 werkzeug: 95.108.16.209 - - [28/Jul/2020 09:19:30] "POST /web/database/create HTTP/1.1" 303 - 19453 7.533 7.620
2020-07-28 09:19:31,040 19612 INFO odoo13 odoo.addons.base.models.ir_http: Generating routing map for key None 
2020-07-28 09:19:31,068 19612 INFO odoo13 werkzeug: 95.108.16.209 - - [28/Jul/2020 09:19:31] "GET /web/ HTTP/1.1" 500 - 1 0.001 0.030
2020-07-28 09:19:31,074 19612 ERROR odoo13 werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/gk/odoo13/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/gk/odoo13/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/gk/odoo13/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/home/gk/odoo13/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/home/gk/odoo13/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/gk/odoo13/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/home/gk/odoo13/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/home/gk/odoo13/venv/lib/python3.8/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/home/gk/odoo13/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/home/gk/odoo13/odoo/addons/base/models/ir_http.py", line 238, in _dispatch
    return cls._handle_exception(e)
  File "/home/gk/odoo13/odoo/addons/base/models/ir_http.py", line 206, in _handle_exception
    return request._handle_exception(exception)
  File "/home/gk/odoo13/odoo/http.py", line 750, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/gk/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/gk/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/gk/odoo13/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/home/gk/odoo13/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/gk/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/gk/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/gk/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/gk/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/gk/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/gk/odoo13/addons/web/controllers/main.py", line 844, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context' - - -
```

**Expected behavior:**

No errors

**Comment by grzekru** [comment]
Probably caused by this update
```
[2020-07-27T14:29:09+0200] [ALPM] upgraded python (3.8.3-1 -> 3.8.4-1)
[2020-07-27T14:29:09+0200] [ALPM] upgraded python-ordered-set (3.1.1-2 -> 4.0.2-1)
```

**Comment by Cicciodev** [comment]
Same issue with 12.0 too! 
I'm trying a downgrade as @grzekru suggested

**Comment by xmo-odoo** [comment]
See #54785

**Comment by mk298** [comment]
I am having the same issue. Can any one suggest how to fix it?

**Comment by grzekru** [comment]
> I am having the same issue. Can any one suggest how to fix it?

I've installed older python version using pyenv.

**Comment by mk298** [comment]
> > I am having the same issue. Can any one suggest how to fix it?
> 
> I've installed older python version using pyenv.

Thank you @grzekru

**Comment by REDYTEC** [comment]
Im trying to run this command: sudo pacman -U /var/cache/pacman/pkg/python-3.8.3-1-x86_64.pkg.tar.zst I´ve already install "pacman" but it showns: Pacman command not found

**Comment by AngelesG2020** [comment]
> Im trying to run this command: sudo pacman -U /var/cache/pacman/pkg/python-3.8.3-1-x86_64.pkg.tar.zst I´ve already install "pacman" but it showns: Pacman command not found

Same

**Comment by thetrebelcc** [comment]
> > I am having the same issue. Can any one suggest how to fix it?
> 
> I've installed older python version using pyenv.

I did the same, but even after restarting the service I have the same issues, are there any other steps I should take?

**Comment by grzekru** [comment]
> > > I am having the same issue. Can any one suggest how to fix it?
> > 
> > 
> > I've installed older python version using pyenv.
> 
> I did the same, but even after restarting the service I have the same issues, are there any other steps I should take?

1. Install pyenv
2. pyenv install 3.8.0
3. pyenv virtualenv 3.8.0 <new_venv_name>
4. pyenv shell <venv name from point 3>

**Comment by thetrebelcc** [comment]
> 1. Install pyenv
> 2. pyenv install 3.8.0
> 3. pyenv virtualenv 3.8.0 <new_venv_name>
> 4. pyenv shell <venv name from point 3>
> 5. Install requirements with pip and run odoo

Thank you for your reply. I had installed python3.6 globally with pyenv, should I run it with virtualenv? The original version of Odoo was installed using the package install from Odoo on Ubuntu. Is there a way to specify the service starts with a specific version of python?

**Comment by grzekru** [comment]
@thetrebelcc You can modify the service file.
sudo systemctl status odoo - for service file location.
