### ISSUE TITLE
[13.0] eLearning video lesson javascript error

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#55142]
Impacted versions: 13.0 in Odoo.sh

After commit 6da17c3ee1e0c63b0cace60da2f98cfc4fe8ac57 i got this error:
```
TypeError: Cannot read property 'indexOf' of undefined
    at https://www.online-erp.hu/website_slides/static/src/js/slides_course_fullscreen_player.js:514:57
    at Array.forEach (<anonymous>)
    at Class._preprocessSlideData (https://www.online-erp.hu/website_slides/static/src/js/slides_course_fullscreen_player.js:508:28)
    at Class.init (https://www.online-erp.hu/website_slides/static/src/js/slides_course_fullscreen_player.js:421:32)
    at Class.prototype.<computed> [as init] (https://www.online-erp.hu/web/static/src/js/core/class.js:90:38)
    at new Class (https://www.online-erp.hu/web/static/src/js/core/class.js:107:33)
    at Class.start (https://www.online-erp.hu/website_slides/static/src/js/slides_course_fullscreen_player.js:703:30)
    at Class.prototype.<computed> [as start] (https://www.online-erp.hu/web/static/src/js/core/class.js:90:38)
    at https://www.online-erp.hu/web/static/src/js/core/widget.js:207:25
    at async Promise.all (index 0)
```

At line:
https://github.com/odoo/odoo/blob/13.0/addons/website_slides/static/src/js/slides_course_fullscreen_player.js#L514
```javascript
var separator = slideData.embedCode.indexOf("?") !== -1 ? "&" : "?";
```

Steps to reproduce:
* Install elearning
* create a lesson with a youtube video link, like: https://youtu.be/YjAVVbfZNWQ
* view it on the website

**Comment by tsabi** [comment]
@nle-odoo I think this is yours.

**Comment by nle-odoo** [comment]
Sorry for the issue, this should be solved with this fix:

https://github.com/odoo/odoo/pull/55079

Odoo.sh team suggested using the feature to use "Last week" revision to avoid the bug temporarily until update (usually at the latest on Monday), it should be in the branch settings.
