### ISSUE TITLE
[13.0] Some Plugin make Assert when enter to user setting view, if select Koran and some language 

### ISSUE THREAD

**Issue by jisueo** [odoo/odoo#55188]
Impacted versions:
13.0

Steps to reproduce:
1. start odoo
2. install plugin, https://apps.odoo.com/apps/modules/13.0/employee_vehicle_request/
3. load korean language translate
4. go settings
5. click user setting

Current behavior:
occur assert error
```
Odoo Server Error
Traceback (most recent call last):
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/Users/jisueo/Devs/gits/sandbox/odoo/addons/hr/models/res_users.py", line 151, in fields_view_get
    return super(User, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/Users/jisueo/Devs/gits/sandbox/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: `sel_groups_54_55`
```

Expected behavior:
enter user setting view

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You should notify the problem to the addons owner, as it's not a problem of Odoo itself, but third-party one. Closing due to this reason.

**Comment by jisueo** [comment]
first of all thanks for your comments

I tried found problem. so I found problem in addon/base/models/res_user.py. to find or generate translated fields, this module make some group like {sel_groups_xxxxx). in get_groups_by_application generate some fields selection or boolean. but in some case, this function make boolean type fields even though translated things is exist. linearize function check 2 condition

```
            if len(set(order.values())) == len(gs):
                return (app, 'selection', gs.sorted(key=order.get), category_name)
            else:
                return (app, 'boolean', gs, (100, 'Other'))
```

this condition make boolean fields  even though translated things is exist. according to your comment, this issue could be addons problem. however I think, even if addon has some problem, odoo main operation should be working.
so I add some logic in linearize function 

```
           transValue  = numpy.sum(list(order.values()))
            if len(set(order.values())) == len(gs):
                return (app, 'selection', gs.sorted(key=order.get), category_name)
            elif transValue > 0 and category_name[0] != 100:
                return (app, 'selection', gs.sorted('id'), category_name)
            else:
                return (app, 'boolean', gs, (100, 'Other'))
```

if trans_implied_ids is exist in gs and category is not (100, other), this function make ` (app, 'selection', gs.sorted('id'), category_name)`. it is works.

**Comment by pedrobaeza** [comment]
Sorry, I don't get your explanation, but that code is working for a lot of time and with thousands of addons, so what you are trying to fix in core should be fixed on the third-party addon.
