### ISSUE TITLE
[13.0] Cannot upgrade if mixin with selection field was removed

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#55183]
Impacted versions:
13.0-20200417, official docker image. Did not check on others.

Steps to reproduce:
1. `git clone https://github.com/em230418/odoo-mixin-bug -b master`
2. Install mixin-test
3. In cloned odoo-mixin-bug switch branch to `downgraded` (`git checkout downgraded # branch with removed mixin`)
4. Difference between master branch and downgraded branch is:
```diff
diff --git a/mixin_test/__init__.py b/mixin_test/__init__.py
index 4637fa9..961b9cc 100644
--- a/mixin_test/__init__.py
+++ b/mixin_test/__init__.py
@@ -1,17 +1,5 @@
 from odoo import models, fields
 
 
-class TestMixin(models.AbstractModel):
-    _name = 'test.mixin'
-
-    test_field = fields.Boolean("Test field")
-    test_field_selection = fields.Selection([
-        ("yes", "Da"),
-        ("no", "Net"),
-    ])
-
-
 class TestModel(models.Model):
     _name = "test.model"
-
-    _inherit = 'test.mixin'
```
4. Upgrade mixin-test

Current behavior:
Does not upgrade and throws error:
```
test_1      | Traceback (most recent call last):
test_1      |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1179, in preload_registries
test_1      |     registry = Registry.new(dbname, update_module=update_module)
test_1      |   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
test_1      |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
test_1      |   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 472, in load_modules
test_1      |     env['ir.model.data']._process_end(processed_modules)
test_1      |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1976, in _process_end
test_1      |     record.unlink()
test_1      |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 1192, in unlink
test_1      |     not self.env[selection.field_id.model]._abstract:
test_1      |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 463, in __getitem__
test_1      |     return self.registry[model_name]._browse(self, (), ())
test_1      |   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
test_1      |     return self.models[model_name]
test_1      | KeyError: 'test.mixin'
```

Expected behavior:
Successfully upgraded

**Comment by sswapnesh** [comment]
This has been also discussed earlier and you should never remove model from production module.( Maybe @Elkasitu knows more about this)

**Comment by em230418** [comment]
> This has been also discussed earlier and you should never remove model from production module.

My case was downgrading module, which didn't have mixin before.
