### ISSUE TITLE
[BUG][12.0] account: You cannot use anything else than unaccented latin characters in the alias address

### ISSUE THREAD

**Issue by leotranviindoo** [odoo/odoo#55492]
## Impacted versions:
- Odoo 12.0
- Python 3.7+
## Steps to reproduce:
- Run odoo 12 with **python 3.7+**
- Create new database with `language` is **Vietnamese** and `country` is **Vietnam**
- Install module **Invoices & Payments** (technical name is `account`)
## Current behavior:
an occurred error:
```python
Traceback (most recent call last):
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 343, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-184>", line 2, in try_loading_for_current_company
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 382, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 382, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 178, in try_loading_for_current_company
    self.load_for_current_company(15.0, 15.0)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 249, in load_for_current_company
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 520, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 568, in _load_template
    self.generate_journals(account_ref, company)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 398, in generate_journals
    journal = JournalObj.create(vals_journal)
  File "<decorator-gen-154>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/account.py", line 791, in create
    journal._update_mail_alias(vals)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/account.py", line 624, in _update_mail_alias
    alias_parent_model_name='account.journal').create(alias_values)
  File "<decorator-gen-104>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/leotran/git/odoo/odoo12/addons/mail/models/mail_alias.py", line 123, in create
    return super(Alias, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 3588, in create
    records = self._create(data_list)
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 3720, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/home/leotran/git/odoo/odoo12/addons/mail/models/mail_alias.py", line 89, in _alias_is_ascii
    raise ValidationError(_("You cannot use anything else than unaccented latin characters in the alias address."))
odoo.exceptions.ValidationError: ('You cannot use anything else than unaccented latin characters in the alias address.', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/leotran/git/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/leotran/git/odoo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/leotran/git/odoo/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/leotran/git/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/leotran/git/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/leotran/git/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/leotran/git/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/leotran/git/odoo/odoo12/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/leotran/git/odoo/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/leotran/git/odoo/odoo12/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/leotran/git/odoo/odoo12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/home/leotran/git/odoo/odoo12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 343, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/leotran/git/odoo/odoo12/odoo/tools/convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-184>", line 2, in try_loading_for_current_company
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 382, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 382, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 178, in try_loading_for_current_company
    self.load_for_current_company(15.0, 15.0)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 249, in load_for_current_company
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 520, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 568, in _load_template
    self.generate_journals(account_ref, company)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/chart_template.py", line 398, in generate_journals
    journal = JournalObj.create(vals_journal)
  File "<decorator-gen-154>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/account.py", line 791, in create
    journal._update_mail_alias(vals)
  File "/home/leotran/git/odoo/odoo12/addons/account/models/account.py", line 624, in _update_mail_alias
    alias_parent_model_name='account.journal').create(alias_values)
  File "<decorator-gen-104>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/leotran/git/odoo/odoo12/addons/mail/models/mail_alias.py", line 123, in create
    return super(Alias, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/home/leotran/git/odoo/odoo12/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 3588, in create
    records = self._create(data_list)
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 3720, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/leotran/git/odoo/odoo12/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/home/leotran/git/odoo/odoo12/addons/mail/models/mail_alias.py", line 89, in _alias_is_ascii
    raise ValidationError(_("You cannot use anything else than unaccented latin characters in the alias address."))
odoo.tools.convert.ParseError: "You cannot use anything else than unaccented latin characters in the alias address.
None" while parsing /home/leotran/git/odoo/odoo12/addons/l10n_vn/data/account_chart_template_data.xml:4, near
<function model="account.chart.template" name="try_loading_for_current_company">
            <value eval="[ref('l10n_vn.vn_template')]"/>
        </function>
```
## Expected behavior:
Completed installation
## Screenshot:
Create new database

![image](https://user-images.githubusercontent.com/63898164/89487874-c9fa1280-d7d0-11ea-997e-abca10669fd2.png)

Install module

![image](https://user-images.githubusercontent.com/63898164/89487905-d8482e80-d7d0-11ea-883b-30a0a5ebc9ee.png)

**Comment by pedrobaeza** [comment]
Please indicate which is the data file that is loading.

**Comment by pedrobaeza** [comment]
I see that PR #55493 tries to solve this. I think a generic slugification should be done instead.

@Julien00859 you were the original author of the limitation. What do you think about this?

**Comment by thongthele** [comment]
> I see that PR #55493 tries to solve this. I think a generic slugification should be done instead.
> 
> @Julien00859 you were the original author of the limitation. What do you think about this?

@pedrobaeza  for this case I think no need to use generic slugification, because `unicodedata` already works quite well

**Comment by Julien00859** [comment]
Well it works on my machine... it creates a `cong-no-nha-cung-cap@` alias...

Using python 3.6 and the latest standard community v12

    createdb odoo-gh55492
    python3 odoo-bin -d odoo-gh55492 --db-filter=^odoo-gh55492$ -l vi_VN --load-language=vi_VN -i base,account

**Comment by Julien00859** [comment]
But I have the unaccent extension on my database, I don't use our `remove_accents` function, let me see...

**Comment by thongthele** [comment]
> Well it works on my machine... it creates a `cong-no-nha-cung-cap@` alias...
> 
> Using python 3.6 and the latest standard community v12
> 
> ```
> createdb odoo-gh55492
> python3 odoo-bin -d odoo-gh55492 --db-filter=^odoo-gh55492$ -l vi_VN --load-language=vi_VN -i base,account
> ```
@Julien00859 please ussing python >= 3.7, using python 3.6 will not cause an error

**Comment by Julien00859** [comment]
Without unaccent, using py3.7.7, not able to reproduce locally. What OS are you using ? I'm on Linux Mint 19 Tara

**Comment by thongthele** [comment]
> Without unaccent, using py3.7.7, not able to reproduce locally. What OS are you using ? I'm on Linux Mint 19 Tara

@Julien00859 I'm on Ubuntu 20.04 LTS, using python 3.8. You can use journals with Vietnamese names, which contain accented character (`đ`), such as `Hóa đơn Nhà cung cấp`.

`cong-no-nha-cung-cap` does not contain the character `đ`
