### ISSUE TITLE
Odoo Server: auto-reload and workers parameter

### ISSUE THREAD

**Issue by maljac** [odoo/odoo#5557]
Hi, 

Impacted versions:
- 8.0 (20150302)

Steps to reproduce:
- when starting the odoo server with the options `auto-reload` and `workers` I get the following error:

``` python

> odoo.py -c /etc/odoo/openerp-server.conf --workers=4 --auto-reload

Traceback (most recent call last):
  File "/usr/bin/openerp-gevent", line 11, in <module>
    openerp.cli.main()
  File "/usr/lib/python2.7/dist-packages/openerp/cli/__init__.py", line 71, in main
    o.run(args)
  File "/usr/lib/python2.7/dist-packages/openerp/cli/server.py", line 180, in run
    main(args)
  File "/usr/lib/python2.7/dist-packages/openerp/cli/server.py", line 174, in main
    rc = openerp.service.server.start(preload=preload, stop=stop)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 939, in start
    autoreload = AutoReload(server)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 132, in __init__
    self.notifier = pyinotify.Notifier(self.wm, self.handler, timeout=0)
  File "/usr/local/lib/python2.7/dist-packages/pyinotify.py", line 1173, in __init__
    self._pollobj = select.poll()
AttributeError: 'module' object has no attribute 'poll'
```

My environment:
- Ubuntu14.04
- Odoo from debian packackes (20150302)

Cheers

**Comment by onlyjob** [comment]
I'm having the same issue with `auto-reload` on Debian Jessie with Odoo nightly 20150416...

**Comment by Labna** [comment]
I'm not sure but the `--auto-reload` option is a setting in `server/openerp-server.conf`

**Comment by onlyjob** [comment]
spelled `auto_reload` actually...

**Comment by Yenthe666** [comment]
Hi @maljac,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
