### ISSUE TITLE
Getting crash on enabling the oauth in settings

### ISSUE THREAD

**Issue by sivabalan2088** [odoo/odoo#55674]
Impacted versions:
Odoo-13.0

Steps to reproduce:
    Login as superuser
    Go to settings-> General
    Enable OAuth Authentication
    Click Save button

Current behavior:
    Got crashed and showing 
    An error occurred
    Please use the copy button to report the error to your support service.

Expected behavior:
    It should allow a user to configure OAuth information.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/16461423/89769282-7d893c80-db1a-11ea-9b8e-7d8584bcbbb1.png)

**Error Log**

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 1000, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field 'company_id' used in attributes must be present in view but is missing:
 - 'company_id' in context="{'default_company_id': company_id}"
 - 'company_id' in domain="[('company_id', '=', company_id), ('type', '=', 'general')]"
 - 'company_id' in domain="[('company_id', '=', company_id)]"
 - 'company_id' in domain="[('type_tax_use', 'in', ('purchase', 'all')), ('company_id', '=', company_id)]"
 - 'company_id' in domain="[('type_tax_use', 'in', ('sale', 'all')), ('company_id', '=', company_id)]"

Error context:
View `res.config.settings.view.form.inherit.auth.oauth`
[view_id: 2005, xml_id: n/a, model: res.config.settings, parent_id: 251]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\website_theme_install\models\theme_models.py", line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\website\models\ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 1176, in _validate_fields
    check(self)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating view\n\nField \'company_id\' used in attributes must be present in view but is missing:\n - \'company_id\' in context="{\'default_company_id\': company_id}"\n - \'company_id\' in domain="[(\'company_id\', \'=\', company_id), (\'type\', \'=\', \'general\')]"\n - \'company_id\' in domain="[(\'company_id\', \'=\', company_id)]"\n - \'company_id\' in domain="[(\'type_tax_use\', \'in\', (\'purchase\', \'all\')), (\'company_id\', \'=\', company_id)]"\n - \'company_id\' in domain="[(\'type_tax_use\', \'in\', (\'sale\', \'all\')), (\'company_id\', \'=\', company_id)]"\n\nError context:\nView `res.config.settings.view.form.inherit.auth.oauth`\n[view_id: 2005, xml_id: n/a, model: res.config.settings, parent_id: 251]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\web\controllers\main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\res_config.py", line 630, in execute
    result = self._install_modules(to_install)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\res_config.py", line 34, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\modules\loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\modules\loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\modules\loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 721, in parse
    exc_info[2]
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\website_theme_install\models\theme_models.py", line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "d:\odoo\odoo\workspace\odoo-13.0\addons\website\models\ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\models.py", line 1176, in _validate_fields
    check(self)
  File "D:\odoo\odoo\workspace\odoo-13.0\odoo\addons\base\models\ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

Field 'company_id' used in attributes must be present in view but is missing:
 - 'company_id' in context="{'default_company_id': company_id}"
 - 'company_id' in domain="[('company_id', '=', company_id), ('type', '=', 'general')]"
 - 'company_id' in domain="[('company_id', '=', company_id)]"
 - 'company_id' in domain="[('type_tax_use', 'in', ('purchase', 'all')), ('company_id', '=', company_id)]"
 - 'company_id' in domain="[('type_tax_use', 'in', ('sale', 'all')), ('company_id', '=', company_id)]"

Error context:
View `res.config.settings.view.form.inherit.auth.oauth`
[view_id: 2005, xml_id: n/a, model: res.config.settings, parent_id: 251]
None" while parsing file:/d:/odoo/odoo/workspace/odoo-13.0/addons/auth_oauth/views/res_config_settings_views.xml:2, near
<odoo>
        <record id="res_config_settings_view_form" model="ir.ui.view">
            <field name="name">res.config.settings.view.form.inherit.auth.oauth</field>
            <field name="model">res.config.settings</field>
</odoo>

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by sivabalan2088** [comment]
Hi, Thanks for your timely reply. Not sure about the issue but it got fixed once moved to a new database.
