### ISSUE TITLE
Resubmission of  #16398,  Domain on one2many field on the xml view not working

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#55712]
Impacted versions: 11

Steps to reproduce: Try to set a domain on a field in an XML view per the documentation. Examples are in the original issue from 2017 at https://github.com/odoo/odoo/issues/16398

Current behavior: Same as in Odoo 9.0 in 2017

Expected behavior: Work as the documentation describes, domain constrains items displayed in the field.

Video/Screenshot link (optional):

**Comment by elgow** [comment]
Here is example code.  I can't easily try this out on runbot, but it captures the basic issue. What I see is that the domain on the `attrs` which should filter for only those `attrs` linked to the current `main` record does not work, so all `attrs` are shown. 

The reason you should pay attention to this issue is that it could be a very powerful feature. In Odoo there is no way to have a Many2many relationship where the link between related records has attributes. This is a limitation of the Odoo ORM. In my application I have associations where the associated records play different roles in different main records at the same time. Odoo does not provide a way to represent this w/o wrapping the associated records in another class - a very inconvenient way to do it. It would be far better to have the domain feature work as documented so that the attrs could be broken out as shown. Think about most normal graph structures, they have edges between nodes that carry attributes, and the attribute data is stored in the records representing the edges - it is CS 101 stuff.

This issue was first raised three years ago with the relevant example code. Please do not dismiss it w/o considering the merits again.

```
# models
class MainRecord(models.Model):
    _name = 'main_record'
    _description = 'main record'

    associated_ids = fields.Many2many('associated_record')

class AssociatedRecord(models.Model):
    _name = 'associated_record'
    _description = 'associated record'

    attr_ids = fields.One2many('association_attrs', 'assoc_id')


class AssociationAttrs(models.Model):
    _name = 'association_attrs'
    _description = 'association attrs'

	attr_data = fields.Char()
    main_id = fields.Many2one('main_record')
    assoc_id = fields.Many2one('associated_record')

```

```
#views



  <record id="main_form_view" model="ir.ui.view">
    <field name="name">main_form</field>
    <field name="model">main_record</field>
    <field name="arch" type="xml">
        <form>
          <field name="associated_ids">
	           <field name="run_attrs" domain="[('main_id', '=', active_id)]">
	              <tree>
	                   <field name="attr_data"/>
	              </tree>
	           </field>
	        </field>
	      </form>
    </field>
 </record>

```

**Comment by pedrobaeza** [comment]
The problem is not with the domain, but with `active_id` variable, that is not set in a regular view, but only through actions/buttons.

**Comment by elgow** [comment]
The active_id would be the desired value, but I tried it with explicitly specified integer values and that does not work either.
________________________________

**Comment by Yenthe666** [comment]
Either way it does look like something that should qualify. @mart-e who can have a look?

**Comment by etechsam** [comment]
I have the same issue with Odoo 13
The only workaround is to set the domain in the field declaration in python.

**Comment by vva-odoo** [comment]
Any solution for it?

**Comment by c-amara** [comment]
Same Issue with Odoo 12

**Comment by KarstenK77** [comment]
Same Issue Odoo12
XML Domain does not filter and when set in field param, then there is an exception:

```
class ResCompany(models.Model):
    _inherit = 'res.company'

    bank_ids = fields.One2many('res.partner.bank', 'company_id', domain="[('partner_id', '=', partner_id)]", string='Bank Accounts', help='Bank accounts related to this company')
```


```
2023-05-16 06:54:40,252 655010 ERROR mariew odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/models.py", line 2820, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo12/odoo/models.py", line 2981, in _read_from_database
    field.read(fetched)
  File "/opt/odoo12/odoo/fields.py", line 2520, in read
    domain = domain + [(inverse, 'in', records.ids)]
TypeError: can only concatenate str (not "list") to str
```

**Comment by FherStk** [comment]
Same with Odoo 16 :(
