### ISSUE TITLE
Odoo12 Server Error

### ISSUE THREAD

**Issue by Adelmaster** [odoo/odoo#55804]
Odoo Server Error

Traceback (most recent call last):
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\bitnami\odoo-12.0.20190618-0\apps\odoo\lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\bitnami\odoo-12.0.20190618-0\apps\odoo\lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "c:\bitnami\odoo-12.0.20190618-0\apps\odoo\lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\addons\mail\models\mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "C:\Bitnami\odoo-12.0.20190618-0\apps\odoo\Lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "c:\bitnami\odoo-12.0.20190618-0\apps\odoo\lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\addons\base\models\ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "c:\bitnami\odoo-12.0.20190618-0\apps\odoo\lib\site-packages\odoo-12.0.post20190618-py3.7.egg\odoo\addons\base\models\ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `hs_code` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
