### ISSUE TITLE
l10n_in installation gives error

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#56025]
Impacted versions: master branch

Steps to reproduce: Install l10n_in on runbot.

Current behavior: Gives error on runbot https://3892382-master.runbot45.odoo.com/

Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 676, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 355, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 343, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 902, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 524, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1364, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1352, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-70>", line 2, in button_immediate_install
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 472, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/data/build/odoo/odoo/addons/base/models/ir_module.py", line 589, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/data/build/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/build/odoo/odoo/modules/loading.py", line 447, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/data/build/odoo/odoo/modules/loading.py", line 340, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/data/build/odoo/odoo/modules/loading.py", line 237, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/data/build/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/data/build/odoo/odoo/tools/convert.py", line 732, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/data/build/odoo/odoo/tools/convert.py", line 798, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/build/odoo/odoo/tools/convert.py", line 718, in parse
    self._tag_root(de)
  File "/data/build/odoo/odoo/tools/convert.py", line 680, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 632, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /data/build/odoo/addons/l10n_in/views/account_journal_views.xml:3, near
<record id="view_account_journal_form_inherit_l10n_in" model="ir.ui.view">
        <field name="name">account.journal.form.inherit.l10n.in</field>
        <field name="model">account.journal</field>
        <field name="inherit_id" ref="account.view_account_journal_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//group[@name='column_posting']" position="attributes">
                <attribute name="attrs">{'invisible': [('type', 'not in', ['bank', 'cash', 'sale', 'purchase'])]}</attribute>
            </xpath>
            <field name="company_id" position="after">
                <field name="l10n_in_gstin_partner_id" context="{'show_vat':True}" options="{&quot;no_create&quot;: True,&quot;always_reload&quot;: True}"/>
            </field>
        </data></field>
    </record>

Expected behavior: Must install successfully.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/33711872/90482856-7df48980-e151-11ea-90cc-5bfa5e39730f.png)

**Comment by pedrobaeza** [comment]
Master branch is a branch in development, so it is expected to fail. Please use a stable one.

Closing as no issues should be reported in master branch.
