### ISSUE TITLE
Mass Mailing test sending - silently ignores error

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5650]
I wanted to test mass mailing, i Pressed 'Test Mailing' and nothing happened, mail was not delivered, but I didn't get any warning too. So I checked the log and saw this:

```
2015-03-09 08:40:20,394 16471 ERROR test openerp.addons.mail.mail_mail: failed sending mail.mail 25
Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/addons/mail/mail_mail.py", line 259, in send
    email_list.append(self.send_get_email_dict(cr, uid, mail, context=context))
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/addons/mass_mailing/models/mail_mail.py", line 90, in send_get_email_dict
    res = super(MailMail, self).send_get_email_dict(cr, uid, mail, partner, context=context)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/addons/mail/mail_mail.py", line 209, in send_get_email_dict
    body = self.send_get_mail_body(cr, uid, mail, partner=partner, context=context)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/addons/mass_mailing/models/mail_mail.py", line 80, in send_get_mail_body
    body = tools.append_content_to_html(base, body, plaintext=False, container_tag='div')
  File "/home/oerp/openerp80/odoo/openerp/tools/mail.py", line 582, in append_content_to_html
    content = re.sub(r'(?i)(</?(?:html|body|head|!\s*DOCTYPE)[^>]*>)', '', content)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

And it happened because there was no mail template defined. It would be fine, but I think system should warn the user that no template is defined if you try to test you mail. Because that should be the point of test, to see if everything is correct.

What it does now, it silently ignores error that can only see in log.

**Comment by noamix** [comment]
any workaround ?

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
