### ISSUE TITLE
[8.0] Cannot Update Module 'product' - Tries to Delete Imported UoM

### ISSUE THREAD

**Issue by michaeljohn32** [odoo/odoo#5691]
I cannot update my product module.  I get the following error and traceback.
```
2015-03-10 18:53:10,585 1932 INFO db-test openerp.addons.base.ir.ir_model: Deleting 23@product.uom
2015-03-10 18:53:10,724 1932 ERROR db-test werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/mnt/sdb1/odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/http.py", line 1239, in __call__
    return self.dispatch(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/http.py", line 1213, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/http.py", line 1213, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/mnt/sdb1/odoo/odoo/openerp/http.py", line 1371, in dispatch
    ir_http = request.registry['ir.http']
  File "/mnt/sdb1/odoo/odoo/openerp/http.py", line 331, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/mnt/sdb1/odoo/odoo/openerp/modules/registry.py", line 310, in get
    update_module)
  File "/mnt/sdb1/odoo/odoo/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/sdb1/odoo/odoo/openerp/modules/loading.py", line 392, in load_modules
    registry['ir.model.data']._process_end(cr, SUPERUSER_ID, processed_modules)
  File "/mnt/sdb1/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mnt/sdb1/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1243, in _process_end
    self.pool[model].unlink(cr, uid, [res_id])
  File "/mnt/sdb1/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/mnt/sdb1/odoo/odoo/openerp/models.py", line 3543, in unlink
    'where id IN %s', (sub_ids,))
  File "/mnt/sdb1/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/sdb1/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "product_uom" violates not-null constraint
DETAIL:  Failing row contains (1823, null, null, 2015-01-03 22:33:05.227439, null, 1, 1, 499, 2015-01-03 22:33:05.227439, 4.0, null, 1, 0, 1, 20267, null, null, normal).
CONTEXT:  SQL statement "UPDATE ONLY "public"."mrp_bom_line" SET "product_uom" = NULL WHERE $1 OPERATOR(pg_catalog.=) "product_uom""
```
In my database, product_uom, id=23 is a unit of measure that was added via an import.  I use this unit of measure extensively across the database, so it cannot be deleted.

Steps to reproduce:
1. Create a new database
2. Install 'stock' / Warehouse
3. In Settings -> Warehouse, check "Manage different units of measure for products"
4. Import a Unit of Measure Category (eg 'Area')
```
"External ID","name"
"UoMCat – Area","Area"
```
5. Import a new unit of measure (eg 'sq in')
```
"id","active","factor_inv","category_id/id","factor","rounding","uom_type","name"
"product.product_uom_sqin","True",1,"UoMCat – Area",1,0.01,"Reference Unit of Measure for this category","sq in"
```
6. Update 'product'
```
~/odoo/odoo.py -u product -d testproduct
```
Result:
```
2015-03-10 19:33:06,557 3831 INFO testproduct openerp.addons.base.ir.ir_model: Deleting 23@product.uom
```

Expected behavior:
Imported product.uom should not be deleted and I can update 'product' or its dependents/dependencies without error

**Comment by michaeljohn32** [comment]
In the example above, I chose an external id of 'product.product_uom_sqin'  It appears that if a user chooses an external id that is part of another model by using the period (e.g. 'product.external_id'), this can happen.  To solve this issue, I found the external id in the postgres table ir_model_data and deleted it.
