### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg-info/entry_points.txt'

### ISSUE THREAD

**Issue by ericntd-legacy** [odoo/odoo#5693]
On Centos 7 with Python 2.7 installed, I tried to run the following:
[odoo@odoo ~]$ pip install -r /opt/odoo/requirements.txt
Note that I didn't run the command as root but as a user name 'odoo'.

Full stacktrace:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 307, in run
    strip_file_prefix=options.strip_file_prefix)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1841, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 296, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 299, in move
    rmtree(src)
  File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg-info/entry_points.txt'

**Comment by Yenthe666** [comment]
Hi @ericntd-legacy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
