### ISSUE TITLE
Website Module Installation Error

### ISSUE THREAD

**Issue by thiago95macedo** [odoo/odoo#57137]
**Impacted versions:** 12

**Steps to reproduce:** 
Ubuntu 18.04
Python 3.6
Error installing the WEBSITE module

_______________________________________________________________________________

Ops...

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 794, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 737, in apply_view_inheritance
    sql_inherit = self.get_inheriting_views_arch(source_id, model)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 255, in get_inheriting_views_arch
    original_keys = self.with_context(website_id=False)._get_inheriting_views(original_view.id, model).mapped('key')
AttributeError: 'ir.ui.view' object has no attribute '_get_inheriting_views'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/models.py", line 3870, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/models.py", line 3784, in _load_records_create
    return self.create(values)
  File "<decorator-gen-180>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 442, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/api.py", line 442, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/addons/website/models/website.py", line 131, in create
    res._bootstrap_homepage()
  File "/opt/odoo/addons/website/models/website.py", line 184, in _bootstrap_homepage
    standard_homepage.with_context(website_id=self.id).arch_db = new_homepage_view
  File "/opt/odoo/odoo/fields.py", line 1046, in __set__
    record.write({self.name: write_value})
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 72, in write
    website_specific_view = view.copy(copy_vals)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 459, in copy
    return super(View, self).copy(default)
  File "/opt/odoo/odoo/models.py", line 4298, in copy
    new = self.with_context(lang=None).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 460, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 3565, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 3697, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Erro ao validar restrição"), tools.ustr(e)))
weth.exceptions.ValidationError: ("Erro ao validar restrição\n\n'ir.ui.view' object has no attribute '_get_inheriting_views'", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/weth/weth/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 965, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 758, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 745, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 435, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 551, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    weth.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo/modules/loading.py", line 67, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/opt/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/models.py", line 3870, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/models.py", line 3784, in _load_records_create
    return self.create(values)
  File "<decorator-gen-180>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 442, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/api.py", line 442, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/addons/website/models/website.py", line 131, in create
    res._bootstrap_homepage()
  File "/opt/odoo/addons/website/models/website.py", line 184, in _bootstrap_homepage
    standard_homepage.with_context(website_id=self.id).arch_db = new_homepage_view
  File "/opt/odoo/odoo/fields.py", line 1046, in __set__
    record.write({self.name: write_value})
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 72, in write
    website_specific_view = view.copy(copy_vals)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 459, in copy
    return super(View, self).copy(default)
  File "/opt/odoo/odoo/models.py", line 4298, in copy
    new = self.with_context(lang=None).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 460, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 3565, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 3697, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Erro ao validar restrição"), tools.ustr(e)))
weth.tools.convert.ParseError: "Erro ao validar restrição

'ir.ui.view' object has no attribute '_get_inheriting_views'
None" while parsing /opt/odoo/addons/website/data/website_data.xml:153, near
<record id="default_website" model="website">
            <field name="name">My Website</field>
            <field name="domain"/>
            <field name="company_id" ref="base.main_company"/>
            <field name="user_id" ref="base.public_user"/>
            <field name="favicon" type="base64" file="web/static/src/img/favicon.ico"/>
            <field name="homepage_id" ref="homepage_page"/>
        </record>

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
