### ISSUE TITLE
Can not install l10n_cn in master \ 14.0 version.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#57132]
Impacted versions:
master or 14.0

Steps to reproduce:
install l10n_cn.

Current behavior:
```
Traceback (most recent call last):
  File "/Users/tingwang/odoo-dev/src/odoo/odoo/http.py", line 635, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/tingwang/odoo-dev/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /Users/tingwang/odoo-dev/src/odoo/addons/l10n_cn/data/account_chart_template_data.xml:4, near
<function model="account.chart.template" name="try_loading">
            <value eval="[ref('l10n_cn.l10n_chart_china_small_business')]"/>
        </function>
```

Expected behavior:
l10n_cn can be correctly installed.

**Comment by pedrobaeza** [comment]
master branch is no longer v14, but future v15. saas-13.5 will be v14. And bug reports in master branch are not allowed. If you want to try saas-13.5 now that is frozen, bug reports over that branch are allowed due to the close of the release date.

**Comment by tanghulu0608** [comment]
@pedrobaeza  Thank you very much.
