### ISSUE TITLE
I can't install any apps/modules - something must have broke

### ISSUE THREAD

**Issue by penguindave** [odoo/odoo#5759]
Now when I go to install any apps/modules i get the following:

Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 729, in install_from_urls
    post_install_action = self.button_immediate_install(cr, uid, to_install_ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/db_tools/__init__.py", line 27, in <module>
    from . import wizard
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/db_tools/wizard/__init__.py", line 27, in <module>
    from . import db_tools
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/db_tools/wizard/db_tools.py", line 32, in <module>
    import service
ImportError: No module named service

**Comment by nhomar** [comment]
2015-03-14 22:08 GMT-06:00 penguindave <notifications@github.com>:

> Now when I go to install any apps/modules i get the following:
>
> Odoo
>
> Odoo Server Error
>

Please verify your installation, maybe yoy have a broken developments which
represent an unloading process.

http://runbot.odoo.com/runbot

You can check that the last commit is completely installable.

Regards.


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by penguindave** [comment]
I tried an "apt-get --reinstall install odoo"

That did not work, do you suggest something else?

**Comment by nhomar** [comment]
2015-03-14 22:46 GMT-06:00 penguindave <notifications@github.com>:

> I tried an "apt-get --reinstall install odoo"


I didn't test the .deb package, I always use the source code, try to run
the server manually with a -u all on your db.

Which version are you using?, are you re-installing from what version?, How
did you get the link to repository? I need more information dude to help
you.

BUt such command and such error looks like you are trying to reinstall a
V8.0 where there were a V7.0 running.

BTW, I am sure it is not a bug, you should use the community list to help
you better or the forum.

Regards.


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by penguindave** [comment]
I appreciate any help.  I am using version V8 

I added http://nightly.odoo.com/8.0/nightly/deb/ as a repo.

It installed fine, as I was going through adding more modules, all of a sudden I got that error.

**Comment by penguindave** [comment]
I figured it out, it was a broken module, I just had to rename the directory it was in. Now I'm good.

\o/

**Comment by greanie** [comment]
I am having the same issue on an unmodified install.  Can you tell me which directory you had to rename and why?

**Comment by gvalbert05** [comment]
Hello friends,

I am  getting an **odoo server Error** while i was installing new modules from odoo 10 version App menu. I downloaded from net and copied that dowloaded files and paste it into addons folder. After that i encountered this error below i have pasted that error.

Hope i will get response from any one of our friends..

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/odoo/odoo-10.0/odoo/modules/loHope i will get response from any one of our friends..ading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3823, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 3918, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(105, GJ) already exists.
" while parsing /opt/odoo/odoo-10.0/addons/openeducat_core/demo/base_demo.xml:4, near
<record id="state_in_01" model="res.country.state">
            <field name="name">Gujarat</field>
            <field name="code">GJ</field>
            <field name="country_id" ref="base.in"/>
        </record>

**Comment by mady143** [comment]
I was unable to get the installed app in the menu bar i had created a new module called school and i created all requirements needed such as 
__init__.py,
__manifest__.py
student.py
student_view.xml and 
ir.model.access.csv 

and later i open the developer mode in odoo environment and upadated the apps list and upgraded the school app but i was unable to find that app in the main menu in the odoo environment
