### ISSUE TITLE
Fresh Install Master Branch Module Import Error 21/03/15 GMT

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#5871]
Hey all just done a fresh install 3 times the same way i always have done never a problem before. Today the server won't launch it errors out and shutsdown immediatley. Please see below for error log.

odoo@mx-1:~$ ./openerp-server
Traceback (most recent call last):
  File "./openerp-server", line 2, in <module>
    import openerp
  File "/opt/odoo/openerp/__init__.py", line 72, in <module>
    import modules
  File "/opt/odoo/openerp/modules/__init__.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/opt/odoo/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/opt/odoo/openerp/osv/__init__.py", line 22, in <module>
    import osv
  File "/opt/odoo/openerp/osv/osv.py", line 22, in <module>
    from ..exceptions import except_orm
  File "/opt/odoo/openerp/exceptions.py", line 33, in <module>
    from tools.func import frame_codeinfo
  File "/opt/odoo/openerp/tools/__init__.py", line 26, in <module>
    from misc import *
  File "/opt/odoo/openerp/tools/misc.py", line 38, in <module>
    import werkzeug.utils
ImportError: No module named werkzeug.utils

**Comment by AidenAndrews** [comment]
Fixed by commit 137305d1497a7c6f82456909065dddaca4538467

**Comment by jl2035** [comment]
I fixed it with: sudo apt-get install python-werkzeug
