### ISSUE TITLE
[14] purcahse: Traceback on sending Preview email

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#58744]
Impacted versions: 14.0

Steps to reproduce: Create PO (Do not save)

Send Confirmation Preview Email

![14e](https://user-images.githubusercontent.com/16624719/94473486-dd7e9400-01e9-11eb-92aa-eca7a9c48b00.gif)

Current behavior: Traceback 
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/addons/purchase/models/purchase.py", line 672, in send_reminder_preview
    notif_layout="mail.mail_notification_paynow")
  File "/home/sswapnesh/WorkSpace/14.0/addons/mail/models/mail_template.py", line 247, in send_mail
    values = self.generate_email(res_id, ['subject', 'body_html', 'email_from', 'email_to', 'partner_to', 'email_cc', 'reply_to', 'scheduled_date'])
  File "/home/sswapnesh/WorkSpace/14.0/addons/account_edi/models/mail_template.py", line 10, in generate_email
    res = super().generate_email(res_ids, fields)
  File "/home/sswapnesh/WorkSpace/14.0/addons/mail/models/mail_template.py", line 164, in generate_email
    for lang, (template, template_res_ids) in self._classify_per_lang(res_ids).items():
  File "/home/sswapnesh/WorkSpace/14.0/addons/mail/models/mail_render_mixin.py", line 425, in _classify_per_lang
    for res_id, lang in self._render_lang(res_ids).items():
  File "/home/sswapnesh/WorkSpace/14.0/addons/mail/models/mail_render_mixin.py", line 403, in _render_lang
    raise ValueError(_('Template rendering for language should be called with a list of IDs.'))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Template rendering for language should be called with a list of IDs.
```

Expected behavior: No Traceback and send email
(Not sure but we should hide button If record is not saved)

Video/Screenshot link (optional):

**Comment by Whenrow** [comment]
@sswapnesh we could indeed. If you want to make the PR I will review it

**Comment by Yenthe666** [comment]
let's close this one in the meanwhile as the main bug is solved & a PR is welcomed.
