### ISSUE TITLE
werkzeug: Error on request: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Ecetinkaya0** [odoo/odoo#59062]
Hi everyone, I am facing this type of error when I am trying to run odoo-bin in my community directory. Is there any way to fix this error. Thank you very much!

2020-10-05 05:49:04,488 8256 INFO ? odoo: Odoo version 14.0
2020-10-05 05:49:04,489 8256 INFO ? odoo: addons paths: ['D:\\Odoo BE\\community\\odoo\\odoo\\addons', 'c:\\users\\ataka\\appdata\\local\\openerp s.a\\odoo\\addons\\14.0', 'd:\\odoo be\\community\\odoo\\odoo\\addons', 'd:\\odoo be\\community\\odoo\\addons']
2020-10-05 05:49:04,489 8256 INFO ? odoo: database: odoo@default:default
2020-10-05 05:49:04,696 8256 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf version of the reports.
2020-10-05 05:49:04,824 8256 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-URKE3LP3:8069
2020-10-05 05:49:22,861 8256 INFO ? odoo.http: HTTP Configuring static files
2020-10-05 05:49:22,937 8256 INFO ? odoo.sql_db: Connection to the database failed
2020-10-05 05:49:22,940 8256 INFO ? werkzeug: 127.0.0.1 - - [05/Oct/2020 05:49:22] "GET / HTTP/1.1" 500 - 0 0.000 0.059
2020-10-05 05:49:22,950 8256 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\service\server.py", line 440, in app
    return self.app(e, s)
  File "D:\Odoo BE\community\odoo\odoo\service\wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\service\wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1428, in dispatch
    self.setup_db(httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1351, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1513, in db_monodb
    dbs = db_list(True, httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1480, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "D:\Odoo BE\community\odoo\odoo\service\db.py", line 384, in list_dbs
    with closing(db.cursor()) as cr:
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 660, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 241, in __init__
    self._cnx = pool.borrow(dsn)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 543, in _locked
    return fun(self, *args, **kwargs)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 611, in borrow
    **connection_info)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError - - -
2020-10-05 05:49:23,037 8256 INFO ? odoo.sql_db: Connection to the database failed
2020-10-05 05:49:23,043 8256 INFO ? werkzeug: 127.0.0.1 - - [05/Oct/2020 05:49:23] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.063
2020-10-05 05:49:23,053 8256 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\service\server.py", line 440, in app
    return self.app(e, s)
  File "D:\Odoo BE\community\odoo\odoo\service\wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\service\wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1428, in dispatch
    self.setup_db(httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1351, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1513, in db_monodb
    dbs = db_list(True, httprequest)
  File "D:\Odoo BE\community\odoo\odoo\http.py", line 1480, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "D:\Odoo BE\community\odoo\odoo\service\db.py", line 384, in list_dbs
    with closing(db.cursor()) as cr:
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 660, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 241, in __init__
    self._cnx = pool.borrow(dsn)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 543, in _locked
    return fun(self, *args, **kwargs)
  File "D:\Odoo BE\community\odoo\odoo\sql_db.py", line 611, in borrow
    **connection_info)
  File "C:\Users\ataka\anaconda\envs\odoo\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError - - -
2020-10-05 05:50:01,683 8256 INFO ? odoo.service.server: Initiating shutdown
2020-10-05 05:50:01,683 8256 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

(odoo) D:\Odoo BE\community\odoo>

**Comment by itskhurram** [comment]
check error is self explanatory "2020-10-05 05:49:22,937 8256 INFO ? odoo.sql_db: Connection to the database failed" 

Please check your db connection.

**Comment by Yenthe666** [comment]
Yep, not a bug but a deployment issue.
