### ISSUE TITLE
Demo data of parent modules should be loaded when running tests

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#5908]
Before running tests in a database that is not demo-enabled, demo data is temporarily loaded to use it in the tests.

This is very useful, but demo data of dependencies should be loaded too, because sometimes a child module modifies the demo data of the parent one.

Here I created an empty database called "demo" (but with demo data disabled) and I try to run there the tests of the official module `website_event`:

```
$ odoo.py --database demo --init website_event --log-level test --test-enable --update website_event --config /etc/odoo/openerp-server.conf

[...]

2015-03-24 09:32:32,771 16 INFO demo openerp.modules.module: module website_event: creating or updating database tables
2015-03-24 09:32:33,090 16 INFO demo openerp.modules.loading: loading website_event/data/event_data.xml
2015-03-24 09:32:33,156 16 INFO demo openerp.modules.loading: loading website_event/views/website_event.xml
2015-03-24 09:32:33,714 16 INFO demo openerp.modules.loading: loading website_event/views/website_event_sale_backend.xml
2015-03-24 09:32:33,778 16 INFO demo openerp.modules.loading: loading website_event/security/ir.model.access.csv
2015-03-24 09:32:33,816 16 INFO demo openerp.modules.loading: loading website_event/security/website_event.xml
2015-03-24 09:32:33,830 16 INFO demo openerp.modules.loading: loading website_event/data/event_demo.xml
2015-03-24 09:32:33,857 16 ERROR demo openerp.sql_db: bad query: INSERT INTO "res_partner" ("id", "notify_email", "color", "image", "use_parent_address", "tz", "opt_out", "company_id", "speaker", "supplier", "type", "website_published", "is_company", "customer", "employee", "active", "lang", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_partner_id_seq'), 'always', 0, NULL, false, NULL, false, 1, false, false, 'contact', true, false, true, false, true, 'es_ES', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (6, null, 1, null, null, 2015-03-24 09:32:33.054092, 0, null, null, null, null, null, null, null, null, null, null, null, f, null, null, f, null, t, null, null, f, null, 2015-03-24 09:32:33.054092, t, null, 1, es_ES, 1, null, null, null, contact, f, null, null, null, null, null, always, null, f, null, null, null, f, null, null, null, t, null, null).

2015-03-24 09:32:33,858 16 CRITICAL demo openerp.service.server: Failed to initialize database `demo`.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/service/server.py", line 909, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_partner.py", line 573, in create
    partner = super(res_partner, self).create(vals)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4041, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4179, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (6, null, 1, null, null, 2015-03-24 09:32:33.054092, 0, null, null, null, null, null, null, null, null, null, null, null, f, null, null, f, null, t, null, null, f, null, 2015-03-24 09:32:33.054092, t, null, 1, es_ES, 1, null, null, null, contact, f, null, null, null, null, null, always, null, f, null, null, null, f, null, null, null, t, null, null).
" while parsing /usr/lib/python2.7/site-packages/openerp/addons/website_event/data/event_demo.xml:5, near
<record id="base.res_partner_6" model="res.partner">
            <field name="website_published">True</field>
        </record>
```

This would be very useful for us module developers.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
