### ISSUE TITLE
[14] mrp: Traceback on closing manufacturing order

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#59160]
Impacted versions: 14.0

Steps to reproduce: 

- Create and Process MO
- Duplicate it
- Confirm
- Mark as Done

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/sswapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/14.0/addons/mrp_account/models/mrp_production.py", line 74, in button_mark_done
    res = super(MrpProduction, self).button_mark_done()
  File "/home/sswapnesh/WorkSpace/14.0/addons/mrp/models/mrp_production.py", line 1460, in button_mark_done
    productions_not_to_backorder._post_inventory(cancel_backorder=True)
  File "/home/sswapnesh/WorkSpace/14.0/addons/mrp/models/mrp_production.py", line 1346, in _post_inventory
    if not finish_moves.quantity_done:
  File "/home/sswapnesh/WorkSpace/14.0/odoo/fields.py", line 927, in __get__
    record.ensure_one()
  File "/home/sswapnesh/WorkSpace/14.0/odoo/models.py", line 4946, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sswapnesh/WorkSpace/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: stock.move(87, 88)
```
Expected behavior:

Video/Screenshot link (optional):
![14c](https://user-images.githubusercontent.com/16624719/95113877-bcc1bb80-0760-11eb-9dfe-65cb071dc496.gif)

**Comment by ryv-odoo** [comment]
I Can't reproduce the issue today. I think it has be solved by https://github.com/odoo/odoo/commit/6c087f2043f8757117061c1ef32b1842616c79eb

**Comment by edlwise** [comment]
Hello, I face the issue now 
Any solution please
