### ISSUE TITLE
Fallas al Instalar Modulos

### ISSUE THREAD

**Issue by solintics** [odoo/odoo#5922]
Al ejecutar la instalación de algunos de los modulos en la version 8.0, con una base de datos populada con datos de ejemplo para evaluación, se presenta al final del proceso de instalación, una pantalla de error, posiblemente por algún campo inexistente (date_stop) o con formato inadecuado.
Creo que el error está en el script que se ejecuta para rellenar las tablas, o en el archivo que contiene los datos que se cargan, cuando se selecciona la opción de crear la BD con datos de ejemplo.

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 530, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 567, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 303, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 300, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 796, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\http.py", line 396, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\web\controllers\main.py", line 939, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\web\controllers\main.py", line 927, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\base\res\res_config.py", line 586, in execute
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\base\res\res_config.py", line 55, in _install_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\modules\registry.py", line 366, in new
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\modules\loading.py", line 179, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\modules\loading.py", line 118, in _load_data
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\tools\convert.py", line 901, in convert_file
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\tools\convert.py", line 987, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\tools\convert.py", line 853, in parse
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\tools\convert.py", line 763, in _tag_record
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server\openerp\addons\base\ir\ir_model.py", line 1073, in _update
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 336, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\models.py", line 4068, in create
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 462, in new_api
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\models.py", line 4259, in _create
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150323\server.\openerp\models.py", line 1280, in _validate_fields
ParseError: "ValidateError
Field(s) `date_stop` failed against a constraint: Error!
The period is invalid. Either some periods are overlapping or the period's dates are not matching the scope of the fiscal year." while parsing file:///C:/Program%20Files%20(x86)/Odoo%208.0-20150323/server/openerp/addons/account/demo/account_demo.xml:30, near
<record id="period_1" model="account.period">
            <field eval="'01/'+time.strftime('%Y')" name="code"/>
            <field eval="'X 01/'+time.strftime('%Y')" name="name"/>
            <field name="fiscalyear_id" ref="data_fiscalyear"/>
            <field eval="time.strftime('%Y')+'-01-01'" name="date_start"/>
            <field eval="time.strftime('%Y')+'-01-31'" name="date_stop"/>
            <field name="company_id" ref="base.main_company"/>
        </record>

**Comment by Yenthe666** [comment]
Hi @solintics ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. 
Please do create bug reports in English if you can though.
We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
