### ISSUE TITLE
[14] Database Creation Issue

### ISSUE THREAD

**Issue by vsdevelopers** [odoo/odoo#59335]
Impacted versions: 14
**While Creating New Database Face this issue.**
**Database Name I use for create is v14_demo**

**Below Are the logs**

2020-10-07 06:58:21,250 8032 ERROR v14_demo odoo.modules.registry: Failed to load registry 
2020-10-07 06:58:21,251 8032 ERROR v14_demo odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/home/odoo/odoo/v14/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/odoo/v14/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f182166eae8>, 'base.module_category_services_timesheets')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 564, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/odoo/v14/odoo/odoo/addons/base/models/ir_model.py", line 1882, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-36>", line 2, in xmlid_lookup
  File "/home/odoo/odoo/v14/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo/v14/odoo/odoo/addons/base/models/ir_model.py", line 1875, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.module_category_services_timesheets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/v14/odoo/odoo/service/db.py", line 63, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/loading.py", line 396, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/odoo/v14/odoo/odoo/tools/convert.py", line 684, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
odoo.tools.convert.ParseError: while parsing /home/odoo/odoo/v14/odoo/odoo/addons/base/data/ir_module_module.xml:19, near
<record model="ir.module.module" id="base.module_timesheet_grid">
            <field name="name">timesheet_grid</field>
            <field name="shortdesc">Timesheets</field>
            <field name="sequence">65</field>
            <field name="category_id" ref="base.module_category_services_timesheets"/>
            <field name="application" eval="True"/>
            <field name="summary">Track time &amp; costs</field>
            <field name="license">OEEL-1</field>
            <field name="author">Odoo S.A.</field>
            <field name="to_buy" eval="True"/>
            <field name="icon">/base/static/img/icons/timesheet_grid.png</field>
            <field name="website">https://www.odoo.com/page/timesheet-mobile-app?utm_source=db&amp;utm_medium=module</field>
        </record>
2020-10-07 06:58:21,257 8032 INFO v14_demo odoo.modules.loading: loading 1 modules... 
2020-10-07 06:58:21,278 8032 INFO v14_demo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries (+0 extra) 
2020-10-07 06:58:21,279 8032 ERROR v14_demo odoo.modules.registry: Remaining fields to compute before setting up registry: defaultdict(<class 'set'>, {ir.module.module.menus_by_module: {352}, ir.module.module.views_by_module: {352}, ir.module.module.reports_by_module: {352}}) 
Stack (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 329, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 364, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/odoo/v14/odoo/odoo/service/server.py", line 440, in app
    return self.app(e, s)
  File "/home/odoo/odoo/v14/odoo/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/odoo/v14/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 1466, in dispatch
    result = _dispatch_nodb()
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 1439, in _dispatch_nodb
    result = request.dispatch()
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 805, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 359, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/v13/odoo-13.0/addons/web/controllers/main.py", line 1094, in create
    request.session.authenticate(name, post['login'], password)
  File "/home/odoo/odoo/v14/odoo/odoo/http.py", line 1001, in authenticate
    uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
  File "/home/odoo/odoo/v14/odoo/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.new(db_name)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/loading.py", line 401, in load_modules
    registry.setup_models(cr)
  File "/home/odoo/odoo/v14/odoo/odoo/modules/registry.py", line 247, in setup_models
    env.all.tocompute, stack_info=True,
2020-10-07 06:58:21,281 8032 ERROR v14_demo odoo.sql_db: bad query: SELECT * FROM ir_model WHERE state='manual'
ERROR: relation "ir_model" does not exist
LINE 1: SELECT * FROM ir_model WHERE state='manual'
                      ^
 
2020-10-07 06:58:21,286 8032 WARNING v14_demo odoo.modules.loading: Transient module states were reset 
2020-10-07 06:58:21,286 8032 ERROR v14_demo odoo.modules.registry: Failed to load registry

**Comment by pedrobaeza** [comment]
I see that the module category is declared in `hr_timesheet` module:

https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/addons/hr_timesheet/security/hr_timesheet_security.xml#L4

but trying to be used in `base` module:

https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/odoo/addons/base/data/ir_module_module.xml#L23

@tivisse can you please check?

**Comment by sswapnesh** [comment]
> File "/home/odoo/odoo/v13/odoo-13.0/addons/web/controllers/main.py", line 1094, in create
> request.session.authenticate(name, post['login'], password)

🤔

**Comment by sswapnesh** [comment]
@pedrobaeza 
It is creating module category during initialization of db 

https://github.com/odoo/odoo/blob/9f5343749c3197f38eb6e612c85dd6a21870576c/odoo/addons/base/models/ir_module.py#L897

https://github.com/odoo/odoo/blob/9f5343749c3197f38eb6e612c85dd6a21870576c/odoo/modules/db.py#L121




I was wondering why No one faced issue like this at first point. (Now I can die in peace 😉 )

**Comment by pedrobaeza** [comment]
I wonder the same. Maybe it's on the initial SQL DB...

**Comment by sswapnesh** [comment]
Yes, It is.

https://github.com/odoo/odoo/blob/9f5343749c3197f38eb6e612c85dd6a21870576c/odoo/modules/db.py#L20-L22

**Comment by pedrobaeza** [comment]
Then why this guy is having the problem?

**Comment by pedrobaeza** [comment]
@vsdevelopers are you restricting existing addons?

**Comment by sswapnesh** [comment]
Maybe he needs to initialize base again (He should try `-d v14_demo-i base`)

and this is also strange in the log 

```
File "/home/odoo/odoo/v13/odoo-13.0/addons/web/controllers/main.py", line 1094, in create
request.session.authenticate(name, post['login'], password)
```

**Comment by vsdevelopers** [comment]
> Maybe he needs to initialize base again (He should try `-d v14_demo-i base`)
> 
> and this is also strange in the log
> 
> ```
> File "/home/odoo/odoo/v13/odoo-13.0/addons/web/controllers/main.py", line 1094, in create
> request.session.authenticate(name, post['login'], password)
> ```

This Log is shows because of the last time I use 8069 for v13 and I dont close that window so it's shows.

**Comment by pedrobaeza** [comment]
Well, it seems clearly a deployment issue, and no reproducible in normal conditions. @vsdevelopers please check your deployment method and try in Linux for better environment. Closing meanwhile no other hints are given proving an Odoo error itself.
