### ISSUE TITLE
[14] account: won't open after fresh installation

### ISSUE THREAD

**Issue by kinafu** [odoo/odoo#59568]
Impacted versions: Odoo 14 (5d10f1367e647d4920bd767a8e1e970eb6a459e9)

Steps to reproduce: 

- Install Odoo 14
- create fresh database (Iin my case country & language German DE)
- install accounting app

Current behavior:
<details>
<summary>Show traceback 🔧 </summary>

```
Odoo Server ErrorTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1516, in load_views
    result['fields_views'] = {
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1517, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 220, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1607, in fields_view_get
    xarch, xfields = view.postprocess_and_fields(etree.fromstring(result['arch']), model=self._name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 844, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 856, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 956, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 951, in postprocess
    transfer_node_to_modifiers(node, node_info['modifiers'], self._context, current_node_path)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 66, in transfer_node_to_modifiers
    modifiers.update(ast.literal_eval(attrs))
  File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
ExceptionThe above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "<unknown>", line 1
    {'invisible'\: ['|', ('state', '!=', 'draft'), ('name', '!=', '/')]}
                                                                       ^
SyntaxError: unexpected character after line continuation character
```
</details>

Expected behavior:
Accounting app opens

Workaround: 
Comment out the line, which seems to finally raise the exception:
`account/views/account_move_views.xml`:`628`

**Comment by Yenthe666** [comment]
Hmm I saw another ticket exactly like this before. The conclusion was that it is no longer reproducible on the latest runbot 13.0 instances & seems to work fine.
CC @pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, I would say that this is because of bad translations

**Comment by pedrobaeza** [comment]
Please fix it in Transifex: https://github.com/odoo/odoo/wiki/Translations
