### ISSUE TITLE
[14.0] General Settings , unexpected error when clicking `manage users`

### ISSUE THREAD

**Issue by kirega** [odoo/odoo#60208]
Impacted versions:
14

Steps to reproduce:
1. On a clean database install inventory
2. Activate debug mode
3. Go to general settings and click on `manage users`

Current behavior:
Currently, I get an error, this error 
 ```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/kirega/Desktop/odoo-14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/kirega/Desktop/odoo-14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/kirega/Desktop/odoo-14.0/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/kirega/Desktop/odoo-14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 394, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 374, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-178>", line 2, in create
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/kirega/Desktop/odoo-14.0/enterprise/account_accountant/models/res_config_settings.py", line 55, in create
    return super().create(vals)
  File "<decorator-gen-167>", line 2, in create
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/kirega/Desktop/odoo-14.0/addons/account/models/res_config_settings.py", line 176, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-65>", line 2, in create
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/kirega/Desktop/odoo-14.0/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/kirega/Desktop/odoo-14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/kirega/Desktop/odoo-14.0/odoo/models.py", line 3784, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kirega/Desktop/odoo-14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'stock_move_sms_validation' on model 'res.config.settings'
 ```
Expected behavior:

Clicking on `manage users` should take me to the manage users view

Video/Screenshot link (optional):

![Screencast-from-17-10-20-01_17_36](https://user-images.githubusercontent.com/12595401/96316699-5158d300-1017-11eb-859a-ac753ebeb29d.gif)

**Comment by kirega** [comment]
The solution was to install `stock_sms`
