### ISSUE TITLE
[14.0]Singleton Error on Optional Product

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#60205]
**Impacted versions:**

14.0, 13.0

**Steps to reproduce:**

1. Create a Quotation
2. Add an optional without selecting a Customer

**Current behavior:**
![image](https://user-images.githubusercontent.com/62367855/96296257-9a575a00-100c-11eb-9f9e-0e1b0d188b66.png)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5060, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/data/build/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 6183, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/build/odoo/odoo/models.py", line 5962, in _onchange_eval
    method_res = method(self)
  File "/data/build/odoo/addons/sale_quotation_builder/models/sale_order.py", line 69, in _onchange_product_id
    ret = super(SaleOrderOption, self)._onchange_product_id()
  File "/data/build/odoo/addons/sale_management/models/sale_order.py", line 208, in _onchange_product_id
    self.price_unit = new_sol._get_display_price(product)
  File "/data/build/odoo/addons/event_sale/models/sale_order.py", line 107, in _get_display_price
    return super()._get_display_price(product)
  File "/data/build/enterprise/sale_renting/models/sale.py", line 208, in _get_display_price
    return super(RentalOrderLine, self)._get_display_price(product)
  File "/data/build/odoo/addons/sale/models/sale.py", line 1487, in _get_display_price
    final_price, rule_id = self.order_id.pricelist_id.with_context(product_context).get_product_price_rule(product or self.product_id, self.product_uom_qty or 1.0, self.order_id.partner_id)
  File "/data/build/odoo/addons/product/models/product_pricelist.py", line 288, in get_product_price_rule
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5063, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.pricelist()

**Expected behavior:**

Normally we add the customer first and it will fill the pricelist. So this case is very rarest.
But anyway it should handle.

**Comment by Vanneri** [comment]
Already Applied a PR for it #59576

**Comment by pedrobaeza** [comment]
Closing as there's already a PR for this.
