### ISSUE TITLE
setup.py --help-commands requires a library

### ISSUE THREAD

**Issue by kingofsevens** [odoo/odoo#603]
Trying to install fresh from master to a Centos server. I was just checking the commads and tools. Shouldn't this work right away without install since this is help on commands? 

    $ python setup.py --help-commands
    Traceback (most recent call last):
      File "setup.py", line 192, in <module>
        **py2exe_options()
      File "/usr/lib64/python2.6/distutils/core.py", line 138, in setup
        ok = dist.parse_command_line()
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 271, in parse_command_line
      File "/usr/lib64/python2.6/distutils/dist.py", line 456, in parse_command_line
        if self.handle_display_options(option_order):
      File "/usr/lib64/python2.6/distutils/dist.py", line 681, in handle_display_options
        self.print_commands()
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 403, in print_commands
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1954, in load
        return entry
    ImportError: No module named upload_docs

**Comment by Yenthe666** [comment]
Dear @kingofsevens,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
