### ISSUE TITLE
Error concurrency javascript

### ISSUE THREAD

**Issue by MiguelJ1** [odoo/odoo#60480]
Impacted versions:
14
Steps to reproduce:
open a record from one2many field as form view and change any field of the record, no press click or enter, press save and save, the system will launch error
Current behavior:
Lock error

Expected behavior:
No lock error

Video/Screenshot link (optional):
Seguimiento:
TypeError: list._changes.push is not a function
    at Class._applyX2ManyChange (http://181.143.148.61:8890/web/content/1138-e9c62b5/web.assets_backend.js:1434:115)
    at Class._applyChange (http://181.143.148.61:8890/web/content/1138-e9c62b5/web.assets_backend.js:1410:274)
    at http://181.143.148.61:8890/web/content/1125-ee6ba1f/web.assets_common.js:4617:607

In 14.0 branch, file addons/web/static/src/js/core/concurrency.js line 195. 

Thanks you !!!

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by odoo-basecare-cn** [comment]
I also encountered this problem

**Comment by odoo-basecare-cn** [comment]
![图片](https://user-images.githubusercontent.com/62583623/103115776-e246cd00-469e-11eb-906c-8c34fa6f1300.png)

**Comment by jeroen7s** [comment]
same here
Scenario is:
We have a form with a Tree view inside it, clicking an item the tree view opens another form in a popup.
in that popup form, is another tree view, if we add an item there (add an item opens another form, with only regular fields) it returns an error on clicking save.

It's reproducible pretty consistently on the latest chrome version. 
It's probably related to the fact that there's another tree view inside the popup.

**Comment by pedrobaeza** [comment]
Can you please specify steps to reproduce in runbot?

**Comment by jeroen7s** [comment]
I've never used runbot, so I don't know how to reproduce it there.

**Comment by kennu** [comment]
I am also seeing this error randomly when trying to edit a Many2many field. My relationship structure is Sales Order => One2many (mymodel1)  => Many2many (mymodel2). Reloading the page and starting to edit the Sales Order again seems to always fix the problem. So far I have not figured out how to reproduce it reliably.

**Comment by ossimantylahti** [comment]
I confirm that this Javascript error pops up during the development frequently (at least ten times a day). Can't figure steps to reproduce it reliably. But it happesn on v.13 as well.

**Comment by ShavaShav** [comment]
We're also seeing this error on Odoo 13. This line is throwing the "list._changes.push is not a function" error: https://github.com/odoo/odoo/blob/3f54ca3e29d1537f66c6a3b56494dc065d9230e9/addons/web/static/src/js/views/basic/basic_model.js#L1455

In the Chrome debugger, it shows that `list._changes` is defined, but is an object:
![image](https://user-images.githubusercontent.com/17697598/120510320-4f216a00-c397-11eb-88b4-f318268e66c9.png)

When it's working properly, list._changes is an array, not an object:
![image](https://user-images.githubusercontent.com/17697598/120510826-cce57580-c397-11eb-88de-b2e8ef19276b.png)


After this error is encountered, the UI is unusable until the browser is refreshed.

**Comment by m-khider** [comment]
I confirm the issue on v13,0, the error is randomly raised..

**Comment by ray75013** [comment]
I confirm the issue on V14
