### ISSUE TITLE
Analytic : TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by yk2kus** [odoo/odoo#6051]
Version 8.0-20150322

When creating analytic_account at on_change(), Error can be experienced only when on_change() is run for first time, from next time is okay but if you reload page and run on_change for first time, you experience error again.

def on_change_partner_id(self, cr, uid, ids,partner_id, name, context=None):
        res={}
        if not context:
            context ={}

```
    company_id = self.pool.get('res.users').browse(cr, uid, uid).company_id.id
    res = super(account_analytic_account, self).on_change_partner_id(cr, uid, ids, partner_id, name, context = context)
    if partner_id:
        part_pool = self.pool.get('res.partner')
        part_obj = part_pool.browse(cr, uid, partner_id)
        if not part_obj.parent_project_id:
            analytic_account = self.create(cr, uid, {'name': part_obj.name, 'partner_id' : partner_id})
            res['value'].update({'parent_id' : analytic_account, 'company_id' : company_id})

    return res
```

2014-08-27 19:58:25,955 1719 ERROR testbase openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 479, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 498, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 314, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 311, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 688, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 363, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 941, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 933, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 234, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mail/mail_message.py", line 544, in message_read
    for message in self.browse(cr, uid, ids, context=context):
  File "/opt/odoo/odoo/openerp/api.py", line 234, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 5072, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/opt/odoo/odoo/openerp/models.py", line 5065, in _browse
    env.prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'

**Comment by Yenthe666** [comment]
Hi @yk2kus,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
