### ISSUE TITLE
[14.0 CE] restored db showing errors

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#60539]
Impacted versions:14.0 CE

I had set up an google cloud instance`(OS: Ubuntu 20.04.1, postgres version:  PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit and Python version:3.8.5).` 
Installed odoo 14.0 CE and created a database and installed accounting module and configured it. 
Then took a database backup using pg_dump and also copied the filestore. 
Compressed both and copied to my local system`(OS: Ubuntu 20.04.1, postgres version: PostgreSQL 9.5.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit, python version: 3.8.5)`
Uncompressed and restored the database. 
Started the odoo 14 server and it is getting following errors

```
2020-10-22 12:41:29,629 160389 INFO odoo14_test odoo.modules.loading: loading 1 modules... 
2020-10-22 12:41:29,670 160389 INFO odoo14_test odoo.modules.loading: 1 modules loaded in 0.04s, 0 queries (+0 extra) 
2020-10-22 12:41:29,829 160389 INFO odoo14_test odoo.modules.loading: loading 47 modules... 
2020-10-22 12:41:30,625 160389 WARNING odoo14_test py.warnings: /usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py:82: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import MutableSet, MutableMapping, MutableSequence
 
2020-10-22 12:41:33,069 160389 INFO odoo14_test odoo.modules.loading: 47 modules loaded in 3.24s, 0 queries (+0 extra) 
2020-10-22 12:41:33,839 160389 INFO odoo14_test odoo.modules.loading: Modules loaded. 
2020-10-22 12:41:34,115 160389 INFO odoo14_test odoo.addons.base.models.ir_http: Generating routing map for key None 
2020-10-22 12:41:34,266 160389 INFO odoo14_test werkzeug: 127.0.0.1 - - [22/Oct/2020 12:41:34] "GET /web?db=odoo14_test HTTP/1.1" 303 - 13 1.018 3.962
2020-10-22 12:41:36,192 160389 ERROR odoo14_test odoo.sql_db: bad query: INSERT INTO "ir_attachment" ("id", "create_uid", "create_date", "write_uid", "write_date", "company_id", "mimetype", "name", "public", "res_id", "res_model", "type") VALUES (nextval('ir_attachment_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 1, 'text/css', 'web.assets_common.css', true, 0, 'ir.ui.view', 'binary') RETURNING id
ERROR: relation "ir_attachment_id_seq" does not exist
LINE 1: ...", "res_id", "res_model", "type") VALUES (nextval('ir_attach...
                                                             ^
 
2020-10-22 12:41:36,195 160389 ERROR odoo14_test odoo.sql_db: bad query: SELECT "ir_ui_view".id FROM "ir_ui_view" WHERE (("ir_ui_view"."active" = true) AND ("ir_ui_view"."key" = 'web.frontend_layout')) ORDER BY  "ir_ui_view"."priority" ,"ir_ui_view"."name" ,"ir_ui_view"."id"   LIMIT 1
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2020-10-22 12:41:36,408 160389 INFO odoo14_test werkzeug: 127.0.0.1 - - [22/Oct/2020 12:41:36] "GET /web/login HTTP/1.1" 500 - 103 1.119 1.020
2020-10-22 12:41:36,592 160389 ERROR odoo14_test werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/ob/git/odoo13/odoo/http.py", line 805, in dispatch
    r = self._call_function(**self.params)
  File "/home/ob/git/odoo13/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ob/git/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ob/git/odoo13/odoo/http.py", line 349, in checked_call
    result.flatten()
  File "/home/ob/git/odoo13/odoo/http.py", line 1241, in flatten
    self.response.append(self.render())
  File "/home/ob/git/odoo13/odoo/http.py", line 1234, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1694, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/home/ob/git/odoo13/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1702, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_6
    
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_layout_12
    
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 336, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 363, in get_template
    raise QWebException("load could not load template", e, path, name=template)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/home/ob/git/odoo13/odoo/service/server.py", line 440, in app
    return self.app(e, s)
  File "/home/ob/git/odoo13/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/home/ob/git/odoo13/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/ob/git/odoo13/odoo/http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "/home/ob/git/odoo13/odoo/http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/ob/git/odoo13/odoo/http.py", line 1464, in dispatch
    result = ir_http._dispatch()
  File "/home/ob/git/odoo13/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/ob/git/odoo13/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/ob/git/odoo13/addons/http_routing/models/ir_http.py", line 512, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/home/ob/git/odoo13/addons/http_routing/models/ir_http.py", line 602, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/home/ob/git/odoo13/odoo/http.py", line 743, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/ob/git/odoo13/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: current transaction is aborted, commands ignored until end of transaction block

Traceback (most recent call last):
  File "/home/ob/git/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/ob/git/odoo13/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ob/git/odoo13/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7f12a7e72f70>, 'web.assets_common', 'en_US', True, False, '', False, False, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_41
  File "<decorator-gen-66>", line 2, in _get_asset_nodes
  File "/home/ob/git/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_qweb.py", line 297, in _get_asset_nodes
    return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load, defer_load=defer_load, lazy_load=lazy_load)
  File "/home/ob/git/odoo13/odoo/addons/base/models/assetsbundle.py", line 153, in to_node
    css_attachments = self.css() or []
  File "/home/ob/git/odoo13/odoo/addons/base/models/assetsbundle.py", line 346, in css
    self.save_attachment("css", css)
  File "/home/ob/git/odoo13/odoo/addons/base/models/assetsbundle.py", line 295, in save_attachment
    attachment = ira.with_user(SUPERUSER_ID).create(values)
  File "<decorator-gen-50>", line 2, in create
  File "/home/ob/git/odoo13/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_attachment.py", line 554, in create
    return super(IrAttachment, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/home/ob/git/odoo13/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/ob/git/odoo13/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/ob/git/odoo13/odoo/models.py", line 3827, in create
    records = self._create(data_list)
  File "/home/ob/git/odoo13/odoo/models.py", line 3933, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/ob/git/odoo13/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/ob/git/odoo13/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "ir_attachment_id_seq" does not exist
LINE 1: ...", "res_id", "res_model", "type") VALUES (nextval('ir_attach...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ob/git/odoo13/odoo/addons/base/models/qweb.py", line 357, in get_template
    document = options.get('load', self._load)(template, options)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_qweb.py", line 118, in _load
    view_id = self.env['ir.ui.view'].get_view_id(name)
  File "/home/ob/git/odoo13/odoo/addons/base/models/ir_ui_view.py", line 1595, in get_view_id
    view = self.sudo().search([('key', '=', template)], limit=1)
  File "/home/ob/git/odoo13/odoo/models.py", line 1698, in search
    return res if count else self.browse(res)
  File "/home/ob/git/odoo13/odoo/models.py", line 4909, in browse
    if not ids:
  File "/home/ob/git/odoo13/odoo/osv/query.py", line 156, in __bool__
    return bool(self._result)
  File "/home/ob/git/odoo13/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/home/ob/git/odoo13/odoo/osv/query.py", line 149, in _result
    self._cr.execute(query_str, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/ob/git/odoo13/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/ob/git/odoo13/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


load could not load template
InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

Template: web.login_layout
Path: /t/t - - -
```

**Comment by pedrobaeza** [comment]
Sorry, but this is not a problem of Odoo itself, but on your deployment/restore procedure.

Try to update modules in DB, or for further help, use Odoo forums.

Closing as no bug.
