### ISSUE TITLE
Install base module require extra modules

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#60685]
Thanks for the great odoo module flexibility.

I was trying to get light and secure docker image bringing only required modules, however there are implicit dependencies that makes hard to avoid some extra code.

## Impacted versions:

14.0

## Steps to reproduce:

* install odoo as you usually do
* remove all addons/ expected some useful likes
  * auth_totp
  * base_import
  * odoo_referral
  * web_editor
  * web
  * web_kanban_gauge
  * web_tour
* run odoo to install `base` module

## Current behavior:

you can't install base module unless you have put following module in addons path
        hr_timesheet \
        mass_mailing \
        mrp \
        project \
        stock \
        website \

## Expected behavior:

install base module without exception

I'm wondering if resolving this kind of dependency would be considered ?

---

There is same kind of implicit dependency, to install **payment** module that required **payment_*** modules to be present in addons the path (I supposed in configuration to get a reference to those modules and logo). I can create a separate issue if you care about.

**Comment by pedrobaeza** [comment]
That's true, and it's due to the module category population, that is done dynamically based on the existing addons. This annoys me, as I also restrict core addons in my instance, but not sure if Odoo wants to populate them other way.

@Elkasitu it was you the one to add such method in base?

**Comment by petrus-v** [comment]
a new dependency appear `account_edi` python code require `account_edi_extended` to be present in `account_edi_document`

```python
from odoo.addons.account_edi_extended.models.account_edi_document import DEFAULT_BLOCKING_LEVEL
```

**Comment by Elkasitu** [comment]
> @Elkasitu it was you the one to add such method in base?

What method?

@petrus-v can you share the traceback you get from this? We don't really test this scenario but I'll check with the higher ups if it's something we want to look for since it's generally bad practice (like in your example, importing stuff from modules that are not dependencies)

**Comment by petrus-v** [comment]
@Elkasitu here you are for the `account_edi_document` case.

I've removed `account_edi_document` from the repo and install account_edi on new database this would produce following traceback:

```log
odoo -c /etc/odoo.cfg --stop-after-init --load-language fr_FR -i account_edi -d odoo60685 --without-demo all
...
2021-03-24 14:19:43,228 6 INFO odoo60685 odoo.modules.loading: Loading module account_edi (24/28) 
2021-03-24 14:19:43,300 6 CRITICAL odoo60685 odoo.modules.module: Couldn't load module account_edi 
2021-03-24 14:19:43,300 6 CRITICAL odoo60685 odoo.modules.module: No module named 'odoo.addons.account_edi_extended' 
2021-03-24 14:19:43,302 6 WARNING odoo60685 odoo.modules.loading: Transient module states were reset 
2021-03-24 14:19:43,303 6 ERROR odoo60685 odoo.modules.registry: Failed to load registry 
2021-03-24 14:19:43,304 6 CRITICAL odoo60685 odoo.service.server: Failed to initialize database `odoo60685`. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/module.py", line 358, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/var/lib/odoo/addons-contrib/account_edi/__init__.py", line 3, in <module>
    from . import models
  File "/var/lib/odoo/addons-contrib/account_edi/models/__init__.py", line 6, in <module>
    from . import account_edi_document
  File "/var/lib/odoo/addons-contrib/account_edi/models/account_edi_document.py", line 5, in <module>
    from odoo.addons.account_edi_extended.models.account_edi_document import DEFAULT_BLOCKING_LEVEL
ModuleNotFoundError: No module named 'odoo.addons.account_edi_extended'
2021-03-24 14:19:43,305 6 INFO odoo60685 odoo.service.server: Initiating shutdown 
2021-03-24 14:19:43,305 6 INFO odoo60685 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
```

**Comment by Ahmedouu** [comment]
I guess I will follow up here instead of opening a new issue.
I am trying to do something similar by having a minimal odoo installation.
   
I have 46 modules in my addons, mass_mailing is not one of them.


**18.0**
**Steps to reproduce:**

    install odoo as you usually do
    remove all addons/ except the ones I need.
    drop DB from previous run.
    restart server.
    create a new DB

**Current behavior:**

you can't create a new database unless you have the following module in addons:

mass_mailing_themes 

**Expected behavior:**
since mass_mailing_themes is not referenced anywhere outside of the module itself why does it throw a critical database creation error, it just themes for mailing which I don't need,  and I don't have mass_mailing so this is confusing.

Currently mass_mailing_themes is not referenced anywhere else, moreover the __init__.py is just empty.



**Log output**:
`2025-07-02 03:41:45,088 66825 ERROR None odoo.modules.registry: Failed to load registry
2025-07-02 03:41:45,088 66825 ERROR None odoo.addons.web.controllers.database: Database creation error.
Traceback (most recent call last):
  File "/<WORKSPACE>/odoo/modules/registry.py", line 104, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/<WORKSPACE>/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<WORKSPACE>/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'odoo-pg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<WORKSPACE>/addons/web/controllers/database.py", line 83, in create
    request.session.authenticate(name, credential)
  File "/<WORKSPACE>/odoo/http.py", line 1056, in authenticate
    registry = Registry(dbname)
               ^^^^^^^^^^^^^^^^
  File "/<WORKSPACE>/odoo/modules/registry.py", line 106, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "<decorator-gen-13>", line 2, in new
  File "/<WORKSPACE>/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<WORKSPACE>/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/<WORKSPACE>/odoo/modules/loading.py", line 433, in load_modules
    registry.setup_models(cr)
  File "<decorator-gen-16>", line 2, in setup_models
  File "/<WORKSPACE>/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<WORKSPACE>/odoo/modules/registry.py", line 333, in setup_models
    env['ir.model']._add_manual_models()
  File "/<WORKSPACE>/addons/base/models/ir_model.py", line 502, in _add_manual_models
    cr.execute("SELECT *, name->>'en_US' AS name FROM ir_model WHERE state = 'manual'")
  File "/<WORKSPACE>/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
LINE 1: SELECT *, name->>'en_US' AS name FROM ir_model WHERE state =...
`

![Image](https://github.com/user-attachments/assets/636fda67-0b09-4201-83b4-abaea410f17c)

it shows the database was created however it's incompatible, I assume this is a very low level server start function.
