### ISSUE TITLE
[14.0] ParseError hr_expense_data.xml

### ISSUE THREAD

**Issue by KRONOMX** [odoo/odoo#60774]
Impacted versions:
14

Steps to reproduce: 
install employees after install hr_expenses , i cant reproduce the problem in runbot, think the failure start when i tried install employee because i didnt have it

Current behavior: 
i cant install hr_expense from apps after install employee

Expected behavior:
install hr_expense and employees 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/custom/trial/saas_trial/models/module.py", line 112, in button_immediate_install
    return super(IrModuleModule, self).button_immediate_install()
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/custom/trial/saas_trial/models/module.py", line 99, in _button_immediate_function
    res = super(IrModuleModule, self)._button_immediate_function(function)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/14.0/addons/hr_expense/data/hr_expense_data.xml:4, near
<record id="product_product_fixed_cost" model="product.product">
            <field name="name">Expenses</field>
            <field name="list_price">0.0</field>
            <field name="standard_price">1.0</field>
            <field name="type">service</field>
            <field name="default_code">EXP_GEN</field>
            <field name="categ_id" ref="product.cat_expense"/>
            <field name="can_be_expensed" eval="True"/>
        </record>

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by matiasonmi** [comment]
Hi have this issue installing data_range and i cant solved it

odoo.tools.convert.ParseError: while parsing None:7, somewhere inside
<data inherit_id="web.assets_backend" name="Module name backend assets">
        <xpath expr="." position="inside">
            <script src="/date_range/static/src/js/date_range.js" type="text/javascript"/>
        </xpath>
    </data>
