### ISSUE TITLE
Error Development Enviroment with Visual Studio 2019

### ISSUE THREAD

**Issue by itskhurram** [odoo/odoo#60802]
Impacted versions: 13.0

Steps to reproduce: Just setting up development Environment.

getting following error when RUN.

2020-10-27 05:53:31,058 10936 INFO ? odoo: Odoo version 13.0
2020-10-27 05:53:31,060 10936 INFO ? odoo: Using configuration file at D:\Personal\Data\ODOO\odoo13\debian\odoo.conf
2020-10-27 05:53:31,060 10936 INFO ? odoo: addons paths: ['D:\\Personal\\Data\\ODOO\\odoo13\\odoo\\addons', 'c:\\users\\kshahzad\\appdata\\local\\openerp s.a\\odoo\\addons\\13.0', 'd:\\personal\\data\\odoo\\odoo13\\addons', 'd:\\personal\\data\\odoo\\odoo13\\odoo\\addons']
2020-10-27 05:53:31,060 10936 INFO ? odoo: database: odoo@localhost:5432
2020-10-27 05:53:32,008 10936 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf version of the reports.
2020-10-27 05:53:33,443 10936 INFO ? odoo.service.server: HTTP service (werkzeug) running on KHURRAMPC:8069
2020-10-27 05:53:49,253 10936 INFO ? odoo.http: HTTP Configuring static files
2020-10-27 05:53:49,319 10936 INFO ? odoo.http: Generating nondb routing
2020-10-27 05:53:49,383 10936 INFO ? werkzeug: 127.0.0.1 - - [27/Oct/2020 05:53:49] "GET / HTTP/1.1" 303 - 1 0.005 0.113
2020-10-27 05:53:49,713 10936 INFO ? werkzeug: 127.0.0.1 - - [27/Oct/2020 05:53:49] "GET /web HTTP/1.1" 500 - 2 0.011 0.312
2020-10-27 05:53:49,719 10936 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "D:\Personal\Data\ODOO\odoo13\odoo\service\server.py", line 439, in app
    return self.app(e, s)
  File "D:\Personal\Data\ODOO\odoo13\odoo\service\wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "D:\Personal\Data\ODOO\odoo13\odoo\service\wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Personal\Data\ODOO\odoo13\odoo\http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Personal\Data\ODOO\odoo13\odoo\http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\werkzeug\wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "D:\Personal\Data\ODOO\odoo13\odoo\http.py", line 1465, in dispatch
    return e(environ, start_response)
  File "_pydevd_bundle/pydevd_cython.pyx", line 1216, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__

  File "_pydevd_bundle/pydevd_cython.pyx", line 300, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_exception

  File "_pydevd_bundle/pydevd_cython.pyx", line 187, in _pydevd_bundle.pydevd_cython.is_unhandled_exception

  File "c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_collect_bytecode_info.py", line 167, in collect_try_except_info
    def collect_try_except_info(co, use_func_first_line=False):
IndexError: list index out of range - - -

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but an specific question about how to deploy for your development environment. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
