### ISSUE TITLE
Odoo 14. Helpdesk module install bug.

### ISSUE THREAD

**Issue by JustRibokas** [odoo/odoo#60944]
Impacted versions: 14

Steps to reproduce: Create a new database, install CRM,  install Helpdesk.

Current behavior: Odoo error occurs

Expected behavior: Helpdesk installed.

Video/Screenshot link (optional):

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/justas/Odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/justas/Odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/justas/Odoo14/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/justas/Odoo14/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/justas/Odoo14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/justas/Odoo14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/home/justas/Odoo14/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/justas/Odoo14/odoo/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/justas/Odoo14/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/justas/Odoo14/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/justas/Odoo14/odoo/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/justas/Odoo14/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/justas/Odoo14/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/justas/Odoo14/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/justas/Odoo14/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/justas/Odoo14/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/justas/Odoo14/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/justas/Odoo14/odoo/odoo/tools/convert.py", line 684, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/justas/Odoo14/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/justas/Odoo14/enterprise/helpdesk/views/helpdesk_views.xml:292, near
<record id="helpdesk_ticket_view_cohort" model="ir.ui.view">
        <field name="name">helpdesk.ticket.view.cohort</field>
        <field name="model">helpdesk.ticket</field>
        <field name="arch" type="xml">
            <cohort string="Tickets" date_start="create_date" date_stop="close_date" interval="week" sample="1"/>
        </field>
    </record>`

**Comment by pedrobaeza** [comment]
As this is something enterprise, please report it through odoo.com/enterprise. Anyway, it seems a deployment problem, as the enterprise runbot instances are working well.

Closing due to this.
