### ISSUE TITLE
Switching database in login screen gives AttributeError ('NoneType' object has no attribute 'cursor')

### ISSUE THREAD

**Issue by npiganeau** [odoo/odoo#6100]
Impacted versions:

 - 8.0 at least

Steps to reproduce:

 1. Open a runbot
 2. Before login change database to uuid-whatsoever-base
 3. Change back database to uuid-whatsoever-all

Current behavior:

 - HTTP 500 Internal server error
 - Reloading the page fixes the problem
 - Seems to happen only on the login page when website module is not installed
 - Logs give 

 Traceback (most recent call last):
  File "C:\Program Files (x86)\Python27\lib\site-packages\werkzeug\serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\Python27\lib\site-packages\werkzeug\serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\service\server.py", line 281, in app
    return self.app(e, s)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\service\wsgi_server.py", line 216, 
   in application
    return application_unproxied(environ, start_response)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\service\wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\http.py", line 1280, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\http.py", line 1254, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Program Files (x86)\Python27\lib\site-packages\werkzeug\wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\http.py", line 1421, in dispatch
    result = ir_http._dispatch()
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\addons\base\ir\ir_http.py", line 168, in _dispatch
    return self._handle_exception(e)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\addons\base\ir\ir_http.py", line 132, in _handle_exception
    attach = self._serve_attachment()
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\addons\base\ir\ir_http.py", line 104, in _serve_attachment
    request.cr, openerp.SUPERUSER_ID, domain,
  File "C:\Program Files (x86)\Python27\lib\site-packages\werkzeug\local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\nicolas\Documents\Progs\GitHub\odoo\openerp\http.py", line 240, in cr
    self._cr = self.registry.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

Expected behavior:

 - Flawless switch between databases

**Comment by sm2x** [comment]
any luck with this one please

**Comment by Gabriel42000** [comment]
I have exactly the same error with the same npiganeau context.

**Comment by miltondp** [comment]
I also found this bug.

**Comment by mnoukrati** [comment]
Have the same problem, any solution ?

**Comment by Bartiff** [comment]
So do I ! I have exactly the same error. :-1:

**Comment by sm2x** [comment]
are we the only ones affected by this?  17 days no fix, no one else?  very frustrating, the very first click on your erp, error!  Internal Server Error, sorry SAP or sorry me ;(

**Comment by saad007** [comment]
We still have the same bug !!

**Comment by lmignon** [comment]
I'm also impacted.

**Comment by Bartiff** [comment]
Still no solution? I can't fix the problem ...

**Comment by moylop260** [comment]
We still have the same issue !

**Comment by moylop260** [comment]
video with test case of @npiganeau
http://youtu.be/nocblub81o4

**Comment by dhongu** [comment]
I have exactly the same error.

**Comment by siouf** [comment]
Same error here.

**Comment by albertoluengo** [comment]
In this topic, it points to a browser cache issue -> https://www.odoo.com/es_ES/forum/help-1/question/switching-database-in-login-screen-gives-internal-server-error-85059

**Comment by moylop260** [comment]
If you use a webpage refresh work too.
But you will need refresh page as many times as you need to change of database.

**Comment by sylvainvanhoof** [comment]
Hi, I've the same error.
This is not serious for ours clients.

**Comment by karen-morales** [comment]
I have the same error when changing database Odoo, and clear history and cookies but still the same. Anyone can support me with a solution.

**Comment by moylop260** [comment]
FYI fix https://github.com/odoo/odoo/pull/6705

**Comment by npiganeau** [comment]
This issue has been fixed somehow now. So I close the issue
