### ISSUE TITLE
Unable to send quotations by email

### ISSUE THREAD

**Issue by lmurta** [odoo/odoo#6104]
I can send test emails but no quotations by email.
I always get the error
```
2015-04-01 15:46:17,034 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:a710f9cc> using values {'format_tz': <function <lambda> at 0xa6dd0ae4>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'tpl_partners_only': True, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'default_res_id': 5, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'partner_id'
2015-04-01 15:46:17,047 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:a71a110c> using values {'format_tz': <function <lambda> at 0xa6e248b4>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'default_res_id': 5, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'tpl_partners_only': True, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'user_id'
2015-04-01 15:46:17,052 22885 ERROR pht openerp.addons.email_template.email_template: Failed to render template <Template memory:b4fa3e0c> using values {'format_tz': <function <lambda> at 0xa6e8e95c>, 'ctx': {'lang': 'pt_BR', 'default_template_id': 7, 'tz': 'America/Sao_Paulo', 'uid': 1, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'params': {'action': 409}, 'default_res_id': 5, 'search_disable_custom_filters': True, 'active_ids': [5], 'default_model': 'sale.order', 'tpl_partners_only': True, 'active_id': 5}, 'user': res.users(1,), 'object': account.account.template(5,)}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/email_template/email_template.py", line 201, in render_template_batch
    render_result = template.render(variables)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py", line 330, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.account.account.template object' has no attribute 'partner_invoice_id'

```

**Comment by lmurta** [comment]
my bad... the user had changed the quotation template...
