### ISSUE TITLE
[14.0] framework: missing XML templates in JS core

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#61330]
Impacted versions: 14.0 At least

Steps to reproduce:
1. Create a custom module with a dependency to `portal_rating`
2. Create a new XML file in a directory `static/src/xml` named `rating_card.xml` and add the following XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="custom_sample.CustomRating" t-extend="portal_rating.PopupComposer" priority="99">
        <t t-jquery=".flex-wrap" t-operation="replace">
        </t>
    </t>
</templates>
```
3. Add this file in the manifest of your module in a `qweb` key:
```
 'qweb': ['static/src/xml/rating_card.xml'],
```
4. Install this module. 

Current behavior:
You will now get an error on the homescreen saying:
```
Traceback:
Error: QWeb2: Can't clone undefined template portal_rating.PopupComposer
    at Object.exception (http://192.168.213.129:14000/web/static/lib/qweb/qweb2.js:48:19)
    at Engine.add_template (http://192.168.213.129:14000/web/static/lib/qweb/qweb2.js:269:47)
    at Object.<anonymous> (http://192.168.213.129:14000/web/static/src/js/core/session.js:255:22)
    at mightThrow (http://192.168.213.129:14000/web/static/lib/jquery/jquery.js:3534:29)
    at process (http://192.168.213.129:14000/web/static/lib/jquery/jquery.js:3602:12)
```
This comes back from the Qweb2 core where this is defined:
https://github.com/odoo/odoo/blob/5064bfa85dcf35410ed0e0053b675debf6883484/addons/web/static/lib/qweb/qweb2.js#L267-L269

If you add a log statement above this if to print the objects you can see which are added to `this.templates`:
```
console.log('this.templates: ' + JSON.stringify(this.templates, null, 4));
 // Clone template and extend it
if (!this.templates[extend]) {
  return this.tools.exception("Can't clone undefined template " + extend);
 }
```
After a reload you will now see the following templates showing up in the console (it depends a bit on the installed apps in your database ofcourse):
```
this.templates: {
    "EmptyComponent": {},
    "Loading": {},
    "WidgetLabel.tooltip": {},
    "WidgetButton.tooltip": {},
    "ChangePassword": {},
    "Action": {},
    "ListView.buttons": {},
    "ListView.selection": {},
    "ListView.confirmModal": {},
    "FormView.buttons": {},
    "SaveCancelButton.tooltip": {},
    "CreateButton.tooltip": {},
    "FormButton.tooltip": {},
    "FormView.set_default": {},
    "GraphView.buttons": {},
    "GraphView.CustomTooltip": {},
    "PivotView.buttons": {},
    "FormSelection": {},
    "FormSelection.items": {},
    "FieldDomain.content": {},
    "DomainNode.ControlPanel": {},
    "DomainTree.OperatorSelector": {},
    "DomainSelector": {},
    "DomainTree": {},
    "DomainLeaf": {},
    "ModelFieldSelector": {},
    "ModelFieldSelector.value": {},
    "ModelFieldSelector.page": {},
    "web.datepicker": {},
    "FieldSelection": {},
    "FieldRadio.button": {},
    "FieldSelectionBadge": {},
    "FieldMany2One": {},
    "web.Many2OneAvatar": {},
    "FieldReference": {},
    "FieldMany2ManyTag": {},
    "FieldMany2ManyTagAvatar": {},
    "FieldMany2ManyTag.colorpicker": {},
    "ProgressBar": {},
    "FieldPercentPie": {},
    "FieldStatus.content": {},
    "FieldStatus.content.button": {},
    "FieldBinaryImage": {},
    "FieldBinaryImage-img": {},
    "CopyClipboardText": {},
    "CopyClipboardChar": {},
    "FieldBinaryFile": {},
    "HiddenInputFile": {},
    "FieldBinarySignature-img": {},
    "FieldBinarySignature": {},
    "SignatureSvgText": {},
    "FieldPdfViewer": {},
    "FieldBinaryFileUploader": {},
    "FieldBinaryFileUploader.attachment_preview": {},
    "FieldBinaryFileUploader.files": {},
    "ExportDialog": {},
    "Export.TreeItems": {},
    "Export.SaveList": {},
    "Export.SavedList": {},
    "Throbber": {},
    "Spinner": {},
    "M2ODialog": {},
    "FieldMany2ManyCheckBoxes": {},
    "StatInfo": {},
    "toggle_button": {},
    "AceEditor": {},
    "notification-box": {},
    "translation-alert": {},
    "UserMenu": {},
    "UserMenu.Actions": {},
    "SwitchCompanyMenu": {},
    "EnterpriseUpgrade": {},
    "BaseSetting.Tabs": {},
    "BaseSetting.SearchHeader": {},
    "AttachDocument": {},
    "FieldColor": {},
    "ColorPicker": {},
    "ColorPickerReadonly": {},
    "SignButton": {},
    "web.IframeWrapper": {},
    "web.PieChart": {},
    "web.FileUploadProgressBar": {},
    "web.ProgressCard": {},
    "KanbanView.buttons": {},
    "KanbanView.Group": {},
    "KanbanView.LoadMore": {},
    "KanbanView.ColumnQuickCreate": {},
    "KanbanView.RecordQuickCreate.buttons": {},
    "KanbanColorPicker": {},
    "GraphCustomTooltip": {},
    "KanbanView.ColumnProgressBar": {},
    "KanbanView.SetCoverModal": {},
    "KanbanView.ExamplesDialog": {},
    "KanbanView.ExamplesDialog.RecordGhost": {},
    "KanbanView.ExamplesBackground": {},
    "KanbanView.ExamplesBackground.RecordGhost": {},
    "KanbanView.MobileTabs": {},
    "Menu": {},
    "AppsMenu": {},
    "Menu.link": {},
    "Menu.sections": {},
    "UserMenu.shortcuts": {},
    "Notification": {},
    "rainbow_man.notification": {},
    "rainbow_man.star": {},
    "report.client_action": {},
    "report.client_action.ControlButtons": {},
    "CalendarView": {},
    "calendar-box": {},
    "CalendarView.event.popover.placeholder": {},
    "CalendarView.event.popover": {},
    "CalendarView.sidebar.filter": {},
    "CalendarView.buttons": {},
    "CalendarView.navigation_buttons": {},
    "CalendarView.scale_buttons": {},
    "CalendarView.quick_create": {},
    "CalendarView.yearEvent.popover": {},
    "CalendarView.yearEvent.popover.placeholder": {},
    "res_config_dev_tool": {},
    "res_config_edition": {},
    "res_config_invite_users": {},
    "web_tour.ToursDialog": {},
    "web_tour.ToursDialog.Table": {},
    "mail.activity_items": {},
    "mail.activity_thread_message_tools": {},
    "mail.activity_feedback_form": {},
    "mail.legacy.Composer.emojis": {},
    "FieldMany2ManyTagsEmail": {},
    "mail.KanbanMany2OneAvatarUser": {},
    "mail.systray.ActivityMenu.Previews": {},
    "mail.systray.ActivityMenu": {},
    "DocumentViewer.Content": {},
    "DocumentViewer": {},
    "PrintImage": {},
    "mail.KanbanActivity": {},
    "mail.ListActivity": {},
    "mail.KanbanActivityLoading": {},
    "mail.KanbanActivityDropdown": {},
    "mail.activities-list-group-item": {},
    "mail.EmojisDropdown": {},
    "mail.widgets.UserStatus": {},
    "mail.widgets.Discuss": {},
    "mail.widgets.Discuss.DiscussControlButtons": {},
    "mail.widgets.DiscussInvitePartnerDialog": {},
    "mail.widgets.MessagingMenu": {},
    "product.report_pricelist_qty": {},
    "product.report_pricelist_search": {},
    "product.report_pricelist_qty_badges": {},
    "web_editor.ace_view_editor": {},
    "web_editor.FieldTextHtml.button.translate": {},
    "web_editor.FieldTextHtml.fullscreen": {},
    "web_editor.snippet_overlay": {},
    "web_editor.customize_block_options_section": {},
    "web_editor.outdated_block_message": {},
    "web_editor.snippet.option.colorpicker": {},
    "web_editor.colorpalette.combination.btn": {},
    "web_editor.color.combination.preview": {},
    "web_editor.many2one.button": {},
    "web_editor.many2one.search": {},
    "wysiwyg.iframeContent": {},
    "wysiwyg.widgets.alt": {},
    "wysiwyg.widgets.media": {},
    "wysiwyg.widgets.media.search": {},
    "wysiwyg.widgets.file": {},
    "wysiwyg.widgets.files.submenu": {},
    "wysiwyg.widgets.image": {},
    "wysiwyg.widgets.document": {},
    "wysiwyg.widgets.image.optimize": {},
    "wysiwyg.widgets.image.existing.attachments": {},
    "wysiwyg.widgets.image.existing.attachment": {},
    "wysiwyg.widgets.image.library_media": {},
    "wysiwyg.widgets.document.existing.attachments": {},
    "wysiwyg.widgets.file.existing.remove": {},
    "wysiwyg.widgets.image.existing.error": {},
    "wysiwyg.widgets.font-icons": {},
    "wysiwyg.widgets.font-icons.icons": {},
    "wysiwyg.widgets.video": {},
    "wysiwyg.widgets.link": {},
    "wysiwyg.widgets.crop": {},
    "web_editor.editorbar": {},
    "web_editor.background_position_overlay": {},
    "web_editor.dialog.save_snippet": {},
    "wysiwyg.plugin.font.paletteButton": {},
    "wysiwyg.plugin.font.colorPalette": {},
    "portal.chatter_message_count": {},
    "portal.Composer": {},
    "portal.Chatter.Attachments": {},
    "portal.chatter_messages": {},
    "portal.chatter_internal_toggle": {},
    "portal.pager": {},
    "portal.Chatter": {},
    "portal.portal_signature": {},
    "portal.portal_signature_success": {},
    "portal.portal_signature_error": {},
    "ShowPaymentInfo": {},
    "PaymentPopOver": {},
    "account.BillsHiddenUploadForm": {},
    "BillsListView.buttons": {},
    "accountJournalDashboardActivity": {},
    "AccountTaxGroupTemplate": {},
    "WidgetWebsiteButton": {},
    "WidgetWebsiteButtonIcon": {},
    "website.WebsiteDashboardMain": {},
    "website.dashboard_header": {},
    "website.dashboard_content": {},
    "website.google_analytics_content": {},
    "website.unauthorized_analytics": {},
    "website.ga_dialog_content": {},
    "website.DateRangeButtons": {},
    "website.GoToButtons": {},
    "website.iframeWidget": {},
    "website.ThemePreview.Buttons": {},
    "website.ThemePreview.SwitchModeButton": {},
    "website.ThemePreview.Loader": {},
    "purchase.PurchaseDashboard": {},
    "purchase.ToasterButton": {},
    "website_sale.productsSearchBar.autocomplete": {},
    "website_sale.ribbonSelectItem": {},
    "website_sale.products_table": {},
    "website_sale.LinkTrackersDropDown": {},
    "website_sale.productsRecentlyViewed": {},
    "productVideo": {},
    "StatusbarButtonsDropdown": {},
    "FieldStatus.content.mobile": {},
    "BurgerMenu": {},
    "MobileCompanySwitcher": {},
    "Menu.sections.mobile": {},
    "SnackBar": {},
    "CalendarView.OtherCalendarMobile": {},
    "MapView.buttons": {},
    "GanttView.buttons": {},
    "GanttView": {},
    "GanttView.Row": {},
    "GanttView.ResizeBadge": {},
    "gantt-popover": {},
    "web_studio.ReportEditor": {},
    "web_studio.X2ManyEdit": {},
    "web_studio.FieldOne2manyWarning": {},
    "web_studio.SystrayItem": {},
    "web_studio.EditMenu.MenuItem": {},
    "studio.contentMenu.dialog.submenu": {},
    "web_studio.EditMenu.Dialog": {},
    "web_studio.EditMenu.Dialog.New": {},
    "web_studio.searchRenderer": {},
    "web_studio.NewButtonBoxDialog": {},
    "web_studio.ViewEditorSidebar": {},
    "web_studio.ViewEditorSidebar.InvisibleCheckbox": {},
    "web_studio.ViewEditorSidebar.field": {},
    "web_studio.ViewEditorSidebar.autocompletion_field": {},
    "web_studio.ViewEditorSidebar.page": {},
    "web_studio.ViewEditorSidebar.group": {},
    "web_studio.ViewEditorSidebar.filter": {},
    "web_studio.ViewEditorSidebar.chatter": {},
    "web_studio.ViewEditorSidebar.approval": {},
    "web_studio.ViewEditorSidebar.button": {},
    "web_studio.ViewEditorSidebar.label": {},
    "web_studio.ViewEditorSidebar.div": {},
    "web_studio.ViewEditorSidebar.img": {},
    "web_studio.ViewEditorSidebar.group_by": {},
    "web_studio.ShowInvisibleElements": {},
    "web_studio.ViewEditorSidebar.ApprovalRule": {},
    "web_studio.ExistingFieldsInputSearch": {},
    "web_studio.ReportEditorSidebar": {},
    "web_studio.AccordionSection": {},
    "web_studio.ReportDirectiveTField": {},
    "web_studio.ReportDirectiveTIf": {},
    "web_studio.ReportDirectiveTElse": {},
    "web_studio.ReportDirectiveTEsc": {},
    "web_studio.ReportDirectiveTSet": {},
    "web_studio.ReportDirectiveTForeach": {},
    "web_studio.ReportDirectiveTOptions": {},
    "web_studio.BlockTotal": {},
    "web_studio.ReportColumn": {},
    "web_studio.ReportImage": {},
    "web_studio.ReportGroups": {},
    "web_studio.ReportText": {},
    "web_studio.ReportLayoutEditable": {},
    "web_studio.ReportDirectiveTOptions.options": {},
    "web_studio.PrintSection": {},
    "web_studio.NewViewDialog": {},
    "web_studio.MapViewDialog": {},
    "web_studio.Sidebar.Toolbox": {},
    "web_studio.Sidebar.Parameters": {},
    "web_studio.Sidebar.Remove": {},
    "web_studio.Sidebar.XMLEditor": {},
    "web_studio.Sidebar.Warning.Groups": {},
    "web_studio.Sidebar.Groups": {},
    "web_studio.FieldSelectorDialog": {},
    "web_studio.ActionEditor": {},
    "web_studio.ActionEditorView": {},
    "web_studio.NewModel": {},
    "web_studio.NewModel.Dialog": {},
    "web_studio.NewKanbanHelperDialog": {},
    "web_studio.AvatarPlaceholder": {},
    "web_studio.NewFieldDialog": {},
    "web_studio.SelectionValues": {},
    "web_studio.SelectionValues.edit": {},
    "web_studio.NewReportDialog": {},
    "web_studio.HomeStudioMenu": {},
    "web_studio.Menu": {},
    "web_studio.ActionEditorSidebar": {},
    "Many2ManyAttendeeTag": {},
    "calendar.RecurrentEventUpdate": {},
    "Calendar.attendee.status.popover": {},
    "web_dashboard.StatisticTooltip": {},
    "iap.redirect_to_odoo_credit": {},
    "iap.buy_more_credits": {},
    "FieldMany2OneBarcode": {},
    "ContactSync": {},
    "mail_enterprise.AttachmentPreview": {},
    "account_invoice_extract.Box": {},
    "account_invoice_extract.Button": {},
    "OnlineSyncSearchBankTable": {},
    "OnlineSyncErrorMessage": {},
    "OnlineSyncSearchBankFooter": {},
    "OnlineSyncSearchBank": {},
    "PlaidLogin": {},
    "PontoTemplateFooter": {},
    "PontoTemplate": {},
    "YodleeTemplateFooter": {},
    "YodleeTemplate": {},
    "ImportView": {},
    "ImportView.buttons": {},
    "ImportView.create_record_option": {},
    "ImportView.preview": {},
    "ImportView.preview.error": {},
    "ImportView.error": {},
    "ImportView.error.multi.header": {},
    "ImportView.error.multi.body": {},
    "ImportView.error.single": {},
    "HrGanttView.Row": {},
    "hr_org_chart_employee": {},
    "hr_org_chart": {},
    "hr_orgchart_emp_popover": {},
    "hr_orgchart_emp_popover_content": {},
    "hr_orgchart_emp_popover_title": {},
    "systray_odoo_referral.gift_icon": {}
}
```

However, the XML template for `portal_rating.PopupComposer` is not in there, which causes this error.
If you'd add the XML file for the module `portal_templates` in the `__manifest__.py` file the template would be added though:
```
'qweb': ['static/src/xml/portal_rating_composer.xml'],
```

Expected behavior:
All XML templates are added in `this.templates`, both when they're defined through JS and through XML and are accessible to inherit

**Comment by Yenthe666** [comment]
OPW `2376412`

**Comment by msh-odoo** [comment]
@Yenthe666 portal_templates are lazy loaded by widgets that's why you are not able to find it in loaded qweb list, if you want to fix then you can do ```include```  ```RatingPopupComposer``` widget from ```portal_rating_composer.js``` and instead of adding your xml file in ```__manifest__.py``` you can lazy load your xml file as well, this should fix your issue.

Something like in your JS file:
```
const PortalRatingComposer = require("portal.rating.composer");

PortalRatingComposer.include({
    xmlDependencies: (PortalRatingComposer.prototype.xmlDependencies || []).concat(["yourfile.xml"]),
});
```

**Comment by Yenthe666** [comment]
@msh-odoo thanks a lot for your feedback, I really appreciate it! I guess you mean to do this in JS?
```
odoo.define('my_app.rating_widget_details', function (require) {
'use strict';
var core = require('web.core');
var PortalRatingComposer = require("portal_rating.portal.rating.composer");
PortalRatingComposer.include({
    xmlDependencies: (PortalRatingComposer.prototype.xmlDependencies || []).concat(["/my_app/static/src/xml/rating_card.xml"]),
})
});
```

And then an XML that does this for example?
```
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="my_app.CustomRating" t-extend="portal_rating.PopupComposer" priority="99">
        <t t-jquery=".flex-wrap" t-operation="replace">
        </t>
    </t>
</templates>
```

This still doesn't seem to work at my end and I can't really figure out what I did wrong. Do you think I still have a mistake and it is my fault instead of something from the framework?

**Comment by msh-odoo** [comment]
@Yenthe666 It may not work because ```portal_rating.portal.rating.composer``` don't return class which you want use in your file, maybe simple PR can be done where ```portal_rating.portal.rating.composer``` returns ```RatingPopupComposer``` BTW you have to require somehing like ```require('portal.rating.composer')``` don't add module name before ```portal.rating.composer```

**Comment by Yenthe666** [comment]
@msh-odoo if I just require `portal.rating.composer` I will get a warning saying `TypeError: Cannot read property 'include' of undefined` which I assume is why you talk about returning `RatingPopupComposer `? I'm not exactly sure what you expect here though as the `start` from `RatingPopupComposer` seems to return a `Promise`?
Could you maybe give me another little helping hand? :)

**Comment by msh-odoo** [comment]
@Yenthe666 With PR #61940 you can use RatingPopupComposer in your file once it is merged and forward ported to 14.0, once it is merged and forward ported you can  do something like:

```
const RatingPopupComposer = require("portal.rating.composer");
RatingPopupComposer.include({
    xmlDependencies: (RatingPopupComposer.prototype.xmlDependencies || []).concat(["/portal_extended/static/src/xml/portal_extended.xml"]),
});
```

**Comment by msh-odoo** [comment]
@Yenthe666 #61940 is mereged and forward ported, would you please check now above example, I guess it should fix now.

**Comment by Yenthe666** [comment]
I'll get back to you ASAP, will probably test this tommorow :) ty

**Comment by Yenthe666** [comment]
Hmm, it still doesn't seem to work though. Let me show all my code to be transparant. I really don't see an issue from my side?
The JS `console.log` goes off. See the code:

Assets:
```
<template id="assets_frontend_scss" name="custom scss assets" inherit_id="web.assets_frontend">
    <script type="text/javascript" src="/my_app/static/src/js/rating.js"></script>
</template>
```

JS:
```
odoo.define('my_app.rating_widget_details', function (require) {
  'use strict';
  var core = require('web.core');
  const RatingPopupComposer = require("portal.rating.composer");
  console.log('----------------');
  RatingPopupComposer.include({
    xmlDependencies: (RatingPopupComposer.prototype.xmlDependencies || []).concat(["/my_app/static/src/xml/rating_card.xml"]),
  });
});
```

XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="my_app.CustomRating" t-extend="portal_rating.PopupComposer" priority="99">
        <t t-jquery=".flex-wrap" t-operation="replace">
        </t>
        <p>TESTTTTT</p>
    </t>
</templates>
```
I don't have any console errors in chrome.

**Comment by Yenthe666** [comment]
@msh-odoo sorry to bother you again but did you get around to checking this?

**Comment by msh-odoo** [comment]
@Yenthe666 Didn't get time to check it, would you please let me know where can I see this ```portal.rating.composer``` in website?

**Comment by msh-odoo** [comment]
@Yenthe666 Here  you should improve two things, use ```web_editor.assets_frontend``` while registering assets and you should not give name to template which you extending(if you want to update existing template), if you give name to template then new template will be registerd in core.qweb, I tried at my end and everything is working fine.

**Comment by Yenthe666** [comment]
Aha, you're right :) After the commit you made to fix the return and modifying it to `web_editor` it works. Thanks a lot!
