### ISSUE TITLE
[14.0] crm: Traceback on sending Email from Lead

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#61360]
Impacted versions: 14.0

Steps to reproduce:
![Screenshot](https://user-images.githubusercontent.com/16624719/98160706-8ebccc00-1f04-11eb-8887-0a4eec63c9c8.png)
![Screenshot (1)](https://user-images.githubusercontent.com/16624719/98160711-911f2600-1f04-11eb-929d-1c3b4f868c28.png)

Current behavior:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 180, in action_send_mail
    self.send_mail()
  File "/data/build/odoo/addons/website_sale/models/mail_compose_message.py", line 20, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/data/build/odoo/addons/sale/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/data/build/odoo/addons/purchase/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/data/build/odoo/addons/coupon/models/mail_compose_message.py", line 15, in send_mail
    return super().send_mail(**kwargs)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 241, in send_mail
    all_mail_values = wizard.get_mail_values(res_ids)
  File "/data/build/odoo/addons/mass_mailing/wizard/mail_compose_message.py", line 21, in get_mail_values
    res = super(MailComposeMessage, self).get_mail_values(res_ids)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 277, in get_mail_values
    rendered_values = self.render_message(res_ids)
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 483, in render_message
    ['email_to', 'partner_to', 'email_cc', 'attachment_ids', 'mail_server_id'])
  File "/data/build/odoo/addons/mail/wizard/mail_compose_message.py", line 514, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields)
  File "/data/build/odoo/addons/account_edi/models/mail_template.py", line 10, in generate_email
    res = super().generate_email(res_ids, fields)
  File "/data/build/odoo/addons/mail/models/mail_template.py", line 175, in generate_email
    results = template.generate_recipients(results, template_res_ids)
  File "/data/build/odoo/addons/mail/models/mail_template.py", line 137, in generate_recipients
    partner = Partner.find_or_create(mail)
  File "/data/build/odoo/addons/mail/models/res_partner.py", line 63, in find_or_create
    return super(Partner, self).find_or_create(email, assert_valid_email=assert_valid_email)
  File "/data/build/odoo/odoo/addons/base/models/res_partner.py", line 830, in find_or_create
    return self.create(create_values)
  File "<decorator-gen-255>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/data/build/odoo/addons/base_vat/models/res_partner.py", line 500, in create
    return super(ResPartner, self).create(vals_list)
  File "<decorator-gen-205>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/account/models/partner.py", line 493, in create
    return super().create(vals_list)
  File "<decorator-gen-193>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/partner_autocomplete/models/res_partner.py", line 183, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-94>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/addons/base/models/res_partner.py", line 561, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-131>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 262, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-240>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/addons/website/models/mixins.py", line 169, in create
    records = super(WebsitePublishedMixin, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/data/build/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/data/build/odoo/odoo/models.py", line 3842, in create
    records = self._create(data_list)
  File "/data/build/odoo/odoo/models.py", line 3914, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/data/build/odoo/odoo/fields.py", line 2337, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/data/build/odoo/odoo/fields.py", line 2349, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for res.partner.type: 'opportunity'
```
Expected behavior: Send Email

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Another default in the context...
