### ISSUE TITLE
"RuntimeError: maximum recursion depth exceeded" with related field to same model

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#6141]
I have a model `product.customfield` with a one2many to `product.customfield.option`
In  `product.customfield.option` I defined a field to see the other options of the custom field.
Here's the relevan parrt of the code

Models:
```python
class CustomField(models.Model):
    _name = 'product.customfield'

    name = fields.Char(required=True, translate=True)
    category_id = fields.Many2one('product.category', 'Category')
    fieldtype = fields.Selection([
        ('selection', 'Selection'),
        ('numerical', 'Numerical'),
    ], string='Field type', required=True)
    option_ids = fields.One2many('product.customfield.option', 'custom_field_id',
                              string='Possible values')


class CustomFieldValueOptions(models.Model):
    """
    Model for storing the options for custom fields of type select
    """
    _name = 'product.customfield.option'

    custom_field_id = fields.Many2one('product.customfield', 'Field',
                                      ondelete='cascade')
    name = fields.Char(required=True)
    other_option_ids = fields.One2many(
        'product.customfield.option',
        string='Other options of this custom field',
        related='custom_field_id.option_ids'
    )
```

View:
```xml
    <record id="view_custom_fields_option_form" model="ir.ui.view">
      <field name="name">Product custom field option form view</field>
      <field name="model">product.customfield.option</field>
      <field name="arch" type="xml">
        <form>
          <group>
            <field name="name"/>
            <field name="custom_field_id"
                   readonly="context.get('opened_by_product_form', False)"/>
            <field name="other_option_ids"/>
          </group>
        </form>
      </field>
    </record>
```

When I open this view with `'opened_by_product_form': True, 'default_custom_field_id': 3` in the context I get a server error: `RuntimeError: maximum recursion depth exceeded`

Here's the traceback:

```python-tb
Traceback (most recent call last):
  File "/opt/odoo/8.0/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/8.0/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/8.0/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/8.0/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/8.0/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/8.0/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/8.0/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/8.0/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/8.0/openerp/models.py", line 5821, in onchange
    newval, record._origin, subfields.get(name),
  File "/opt/odoo/8.0/openerp/fields.py", line 1594, in convert_to_write
    values = record._convert_to_write(values)
  File "/opt/odoo/8.0/openerp/models.py", line 5277, in _convert_to_write
    value = fields[name].convert_to_write(value)
  File "/opt/odoo/8.0/openerp/fields.py", line 1594, in convert_to_write
    values = record._convert_to_write(values)
  File "/opt/odoo/8.0/openerp/models.py", line 5277, in _convert_to_write
    value = fields[name].convert_to_write(value)
[...]
  File "/opt/odoo/8.0/openerp/fields.py", line 1594, in convert_to_write
    values = record._convert_to_write(values)
  File "/opt/odoo/8.0/openerp/models.py", line 5277, in _convert_to_write
    value = fields[name].convert_to_write(value)
  File "/opt/odoo/8.0/openerp/fields.py", line 1594, in convert_to_write
    values = record._convert_to_write(values)
  File "/opt/odoo/8.0/openerp/models.py", line 5277, in _convert_to_write
    value = fields[name].convert_to_write(value)
  File "/opt/odoo/8.0/openerp/fields.py", line 1593, in convert_to_write
    values = {k: v for k, v in record._cache.iteritems() if k in fnames}
  File "/opt/odoo/8.0/openerp/fields.py", line 1593, in <dictcomp>
    values = {k: v for k, v in record._cache.iteritems() if k in fnames}
  File "/usr/lib/python2.7/_abcoll.py", line 406, in iteritems
    yield (key, self[key])
  File "/opt/odoo/8.0/openerp/models.py", line 5873, in __getitem__
    value = self._recs.env.cache[field][self._recs.id]
  File "/opt/odoo/8.0/openerp/fields.py", line 1778, in __get__
    if not record:
RuntimeError: maximum recursion depth exceeded
```

**Comment by rco-odoo** [comment]
@LeartS this is because the method `onchange` uses `convert_to_write` to serialize the values in cache after executing onchange methods, and the cache contains cycles!

I am afraid there is no simple way to get around this...

**Comment by a0c** [comment]
I solved a similar problem by eliminating the cycle in the aggregating field (`other_option_ids` in your case).

I didn't use the `related=...` field, but a computed one (`compute=...`) and just explicitly skipped `self` from the aggregated values.

As for your case, does it solve the issue if you add this domain to `other_option_ids` field declaration?
```python
domain="[('id','!=',id)]"
```
and add this to the form view:
```xml
<field name="id" invisible="1"/>
```

**Comment by a0c** [comment]
Here is [another workaround](https://github.com/odoo/odoo/issues/6037#issuecomment-642603066). In the context of your case, that would mean changing your field `other_option_ids` from related field to a computed field and using `no_prefetch()` in the compute method like this:
```python
x.no_prefetch().custom_field_id.option_ids
```
or 
```python
x.custom_field_id.no_prefetch().option_ids
```
Haven't tried, but should work.
