### ISSUE TITLE
Emails are not sent correctly from crm

### ISSUE THREAD

**Issue by azacchino** [odoo/odoo#61506]
Impacted versions: 12 and 13

Steps to reproduce:

1. CRM (List view)
2. Select one or more rows
3. Actions -> Send Email

Current behavior:

Frontend: Silent failure (message marked as not sent)
In logs you can see:

```
SMTPRecipientsRefused: {}
6/11/2020 14:26:062020-11-06 17:26:06,425 983 ERROR primicia odoo.addons.mail.models.mail_mail: failed sending mail (id: 2536) due to Fallo de entrega de correo
6/11/2020 14:26:06La entrega de correo falló vía el servidor SMTP 'None'.
6/11/2020 14:26:06SMTPRecipientsRefused: {}
6/11/2020 14:26:06Traceback (most recent call last):
6/11/2020 14:26:06  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 501, in send_email
6/11/2020 14:26:06    smtp.sendmail(smtp_from, smtp_to_list, message.as_string())
6/11/2020 14:26:06  File "/usr/local/lib/python3.5/smtplib.py", line 877, in sendmail
6/11/2020 14:26:06    raise SMTPRecipientsRefused(senderrs)
6/11/2020 14:26:06smtplib.SMTPRecipientsRefused: {}
6/11/2020 14:26:06
6/11/2020 14:26:06During handling of the above exception, another exception occurred:
6/11/2020 14:26:06
6/11/2020 14:26:06Traceback (most recent call last):
6/11/2020 14:26:06  File "/home/odoo/src/odoo/addons/mail/models/mail_mail.py", line 370, in _send
6/11/2020 14:26:06    msg, mail_server_id=mail.mail_server_id.id, smtp_session=smtp_session)
6/11/2020 14:26:06  File "/home/odoo/src/repositories/ingadhoc-odoo-support/server_mode/models/ir_mail_server.py", line 30, in send_email
6/11/2020 14:26:06    smtp_session=smtp_session)
6/11/2020 14:26:06  File "/home/odoo/src/repositories/oca-social/mail_tracking/models/ir_mail_server.py", line 79, in send_email
6/11/2020 14:26:06    smtp_session=smtp_session)
6/11/2020 14:26:06  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 511, in send_email
6/11/2020 14:26:06    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
```

Expected behavior: 

Mails sent correctly

Video/Screenshot link (optional):

**Comment by azacchino** [comment]
this can by fixed be removing this line on V13 
https://github.com/odoo/odoo/blob/7ff3e9abf08f7f896f31119247157cce5764b431/addons/crm/views/crm_lead_views.xml#L786
and this on V12
https://github.com/odoo/odoo/blob/e62988b5b9314daf3132450c2eb90dc8e81e8b6a/addons/crm/views/crm_lead_views.xml#L809

@nicomacr

**Comment by pedrobaeza** [comment]
I don't get why removing that line is a problem. This is working properly in all my installations.

**Comment by azacchino** [comment]
I attach some screenshots to illustrate.

![1](https://user-images.githubusercontent.com/10451904/98405622-4fe55e00-204b-11eb-9d74-80ad1550b35d.png)
![2](https://user-images.githubusercontent.com/10451904/98405624-51168b00-204b-11eb-92ee-537fdbb9cfd7.png)
![3](https://user-images.githubusercontent.com/10451904/98405625-5247b800-204b-11eb-8c01-842df97fe16d.png)
![4](https://user-images.githubusercontent.com/10451904/98405627-52e04e80-204b-11eb-8d7f-9554adfa846c.png)

But if I send an email from the message it works fine.

![5](https://user-images.githubusercontent.com/10451904/98406024-fe899e80-204b-11eb-907e-a8e110193f21.png)
![6](https://user-images.githubusercontent.com/10451904/98406030-00536200-204c-11eb-84a2-d7c64c89034a.png)

This works fine in V14 because it is fixed in
https://github.com/odoo/odoo/commit/ad7d28ab1abe484102cd3ec18ee6ce9c9ac7b5bb

**Comment by pedrobaeza** [comment]
OK, tagged
