### ISSUE TITLE
Create_company is not a valid action on my module

### ISSUE THREAD

**Issue by cicciob95** [odoo/odoo#61644]
**I have encountered this problem in Odoo v14:**

2020-11-12 10:18:57,011 145 INFO mydb odoo.addons.base.models.ir_ui_view: create_company is not a valid action on res.partner.conversation
View name: res.partner.conversation.form
Error context:
 view: ir.ui.view(634,)
 xmlid: res_partner_conversation_form
 view.model: res.partner.conversation
 view.parent: ir.ui.view(118,)
 file: /odoo/local-addons/social_crm/views/converations_view.xml
2020-11-12 10:18:57,014 145 WARNING mydb odoo.modules.loading: Transient module states were reset
2020-11-12 10:18:57,014 145 ERROR mydb odoo.modules.registry: Failed to load registry
2020-11-12 10:18:57,015 145 CRITICAL mydb odoo.service.server: Failed to initialize database `mydb`.
Traceback (most recent call last):
  File "/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo/models.py", line 4185, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo/models.py", line 4114, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/models.py", line 3875, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo/fields.py", line 1124, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo/models.py", line 3664, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/odoo/odoo/models.py", line 1249, in _validate_fields
    check(self)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 1 more time]
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 1128, in _validate_tag_button
    self.handle_view_error(msg)
  File "/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:
create_company is not a valid action on res.partner.conversation
View name: res.partner.conversation.form
Error context:
 view: ir.ui.view(634,)
 xmlid: res_partner_conversation_form
 view.model: res.partner.conversation
 view.parent: ir.ui.view(118,)
 file: /odoo/local-addons/social_crm/views/converations_view.xml
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/odoo/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo/modules/loading.py", line 449, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /odoo/local-addons/social_crm/views/converations_view.xml:3, near
record id="res_partner_conversation_form" model="ir.ui.view"
            field name="name"res.partner.conversation.form/field
            field name="model"res.partner.conversation/field
            field name="inherit_id" ref="base.view_partner_form"/
            field name="arch" type="xml"
                xpath expr="//form[1]/sheet[1]/notebook[1]" position="inside"
                    page string="Conversation" name="studio_page_kMLL3" groups="sales_team.group_sale_manager,base.group_system"
                        group name="studio_group_kMLL3"
                            group name="studio_group_kMLL3_left"
                                field name="content"/
                            /group
                            group name="studio_group_kMLL3_right"
                                field name="conversation_id" force_save="True" attrs="{}" readonly="1" required="1" widget="label_selection"/
                                field name="date"/
                                field name="channel"/
                            /group
                        /group
                    /page
                /xpath
            /field
        /record

**The class of the module it refers to is:**

class Conversation(models.Model):
    _name = 'res.partner.conversation'
    _description = 'Inbound and Outbound Conversation'

    conversation_id = fields.Char(required=True, string='Conversation ID')
    channel = fields.Char(string='Channel')
    date = fields.Char(string='Date')
    content = fields.Text(string='Content')
    client = fields.Many2one('res.partner', required=True, readonly=True, ondelete='cascade', string='Client')

    _inherits = {'res.partner': 'client'}

    @api.depends('channel_id')
    def get_channel(self):
        result = []
        for conv in self:
            result.append((conv.conversation_id, conv.channel))
        return result

    @api.depends('client')
    def get_client(self):
        result = []
        for conv in self:
            result.append((conv.conversation_id, conv.client))
        return result

    @api.depends('content')
    def get_content(self):
        result = []
        for conv in self:
            result.append((conv.conversation_id, conv.content))
        return result

**How can I fix it?**

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a custom module development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by cicciob95** [comment]
> Sorry, this is not an Odoo issue, but a custom module development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
> 
> Closing this by the reason above.

On the forum I tried to post it but it was probably not accepted. Are you sure it's not an inherits problem?
