### ISSUE TITLE
[14.0] Fail to open mrp production order after 10 thousands of stock locations imported.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#61666]
Impacted versions:
14.0

Steps to reproduce:
1. Before 10 thousands of stock locations imported, It is ok to open a mrp production order.
2. Import 10 thousands of stock locations.
3. Try to open a mrp production order.
`
Odoo Server Error
Traceback (most recent call last):
  File "/home/ruifeng/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/ruifeng/odoo/src/odoo/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ruifeng/odoo/src/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/ruifeng/odoo/src/odoo/odoo/fields.py", line 976, in __get__
    self.compute_value(recs)
  File "/home/ruifeng/odoo/src/odoo/odoo/fields.py", line 1115, in compute_value
    records._compute_field_value(self)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 4035, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/ruifeng/odoo/src/odoo/addons/stock/models/stock_move.py", line 440, in _compute_forecast_information
    ._get_report_lines(None, product_variant_ids, wh_location_ids)
  File "/home/ruifeng/odoo/src/odoo/addons/stock/report/report_stock_forecasted.py", line 146, in _get_report_lines
    currents = {c['id']: c['qty_available'] for c in outs.product_id.with_context(location=wh_location_ids).read(['qty_available'])}
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/ruifeng/odoo/src/odoo/odoo/fields.py", line 976, in __get__
    self.compute_value(recs)
  File "/home/ruifeng/odoo/src/odoo/odoo/fields.py", line 1115, in compute_value
    records._compute_field_value(self)
  File "/home/ruifeng/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 4035, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/ruifeng/odoo/src/odoo/addons/mrp/models/product.py", line 164, in _compute_quantities
    super(ProductProduct, self.filtered(lambda p: p not in bom_kits))._compute_quantities()
  File "/home/ruifeng/odoo/src/odoo/addons/stock/models/product.py", line 104, in _compute_quantities
    res = products._compute_quantities_dict(self._context.get('lot_id'), self._context.get('owner_id'), self._context.get('package_id'), self._context.get('from_date'), self._context.get('to_date'))
  File "/home/ruifeng/odoo/src/odoo/addons/stock/models/product.py", line 158, in _compute_quantities_dict
    moves_in_res = dict((item['product_id'][0], item['product_qty']) for item in Move.read_group(domain_move_in_todo, ['product_id', 'product_qty'], ['product_id'], orderby='id'))
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 2243, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/ruifeng/odoo/src/odoo/odoo/models.py", line 2368, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/ruifeng/odoo/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/ruifeng/odoo/src/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ruifeng/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: memory exhausted at or near "("
LINE 4: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((...
`

**Comment by pedrobaeza** [comment]
Are you sure you don't have hierarchy bad imported with circular hierarchy?

**Comment by tanghulu0608** [comment]
If circular hierarchy happened, odoo will raise:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/5561864/98942507-0c965e00-2529-11eb-9972-be3254a76ed5.png">

**Comment by pedrobaeza** [comment]
It depends if you have imported them by SQL (I have seen such things...).

**Comment by tanghulu0608** [comment]
I import by odoo，not by SQL
