### ISSUE TITLE
[14.0] Error in analytic account ir.rule when uninstalling sale_timesheet module

### ISSUE THREAD

**Issue by ivantodorovich** [odoo/odoo#61722]
**Impacted versions:**
14.0

**Steps to reproduce:**
1. Install sale_timesheet module
2. Create some analytic accounts and analytic lines
3. Uninstall sale_timesheet
4. Go to Invoicing > Configuration > Analytic Accounts

**Current behavior:**

```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1317, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1336, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/home/odoo/src/odoo/addons/web/models/models.py", line 53, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/home/odoo/src/odoo/odoo/models.py", line 4813, in search_read
    result = records.read(fields)
  File "/home/odoo/src/odoo/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/odoo/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 976, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1115, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4035, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/addons/analytic/models/analytic_account.py", line 99, in _compute_debit_credit_balance
    credit_groups = analytic_line_obj.read_group(
  File "/home/odoo/src/odoo/odoo/models.py", line 2243, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/src/odoo/odoo/models.py", line 2276, in _read_group_raw
    self._apply_ir_rules(query, 'read')
  File "/home/odoo/src/odoo/odoo/models.py", line 4250, in _apply_ir_rules
    expression.expression(domain, self.sudo(), self._table, query)
  File "/home/odoo/src/odoo/odoo/osv/expression.py", line 438, in __init__
    self.parse()
  File "/home/odoo/src/odoo/odoo/osv/expression.py", line 640, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field account.analytic.line.project_id in leaf ('project_id', '=', False)
```

**Expected behavior:**
No error

**Analysis:**

`sale_timesheet` modules makes this modification in `account.account_analytic_line_rule_billing_user` `ir.rule`:
https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/addons/sale_timesheet/security/sale_timesheet_security.xml#L12

When uninstalling the module, this is not reverted to the original:
https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/addons/account/security/account_security.xml#L80

Moreover, this `ir.rule` is set to `noupdate=True`, so not even a module update will fix it.

**Comment by pedrobaeza** [comment]
@Elkasitu as you are the usual one for uninstallation stuff, I ping you.

**Comment by fghaiati** [comment]
I have the same issue, is there any resolution

**Comment by Elkasitu** [comment]
Fixed as of https://github.com/odoo/odoo/pull/63687
