### ISSUE TITLE
Version 14 Inheritance of multiple classes

### ISSUE THREAD

**Issue by Jack-Dane** [odoo/odoo#61740]
Impacted versions: V14 Odoo.sh Enterprise 

Steps to reproduce: 
Have a class in the format:
class APIBase(models.Model):
    _name = "api_base"
    _inherit = ["crm.lead", "res.partner"]

or 

* base class *
class APIBase ():

* model class *
class cpq_quotes (models.Model, APIBase):
    _inherit = "crm.lead"

Current behavior:
First one raises: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/server.py", line 440, in app
    return self.app(e, s)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 122, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1294, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1262, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1446, in dispatch
    odoo.registry(db).check_signaling()
  File "/home/odoo/src/odoo/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.new(db_name)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 449, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 187, in load_module_graph
    model_names = registry.load(cr, package)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 230, in load
    model = cls._build_model(self, cr)
  File "/home/odoo/src/odoo/odoo/models.py", line 579, in _build_model
    ModelClass.__bases__ = tuple(bases)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BaseModel, mail.thread.blacklist, format.address.mixin, base - - -

Second one raises:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute (self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app (approximately, start_response)
  File "/home/odoo/src/odoo/odoo/service/server.py", line 440, in app
    return self.app (e, s)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 122, in application
    return ProxyFix (application_unproxied) (environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app (environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root (approximately, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1294, in __call__
    return self.dispatch (approximately, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1262, in __call__
    return self.app (approximately, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app (environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1446, in dispatch
    odoo.registry (db) .check_signaling ()
  File "/home/odoo/src/odoo/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry (database_name)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.new (db_name)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules (registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 449, in load_modules
    processed_modules + = load_marked_modules (cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph (
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 187, in load_module_graph
    model_names = registry.load (cr, package)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 230, in load
    model = cls._build_model (self, cr)
  File "/home/odoo/src/odoo/odoo/models.py", line 579, in _build_model
    ModelClass .__ bases__ = tuple (bases)
TypeError: __bases__ assignment: 'cpq_quotes' object layout differs from 'Lead' - - -

I have also asked a question here: https://www.odoo.com/forum/help-1/question/how-to-inherit-from-a-python-class-that-isn-t-a-model-and-also-inherit-a-model-179369 but without any help.

Thanks,

**Comment by pedrobaeza** [comment]
The problem comes from trying to mix models that have a multi inheritance each one, with overlapping classes on both. You can't do such things without expressing whole inheritance chain.

Closing as no bug, but development question. For further ones, please go to forums or mailing lists.
