### ISSUE TITLE
[8.0] Error 500 after "Account" module update

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#6187]
Hello,

After trying to update the latest "Account" module, Odoo is blocked with a 500 internal server error.
Even after restoring a backup of the module, Odoo is not starting anymore.
Any help would be greatly appreciated as the issue affects a production server.
I have a database backup if needed.

Here is the traceback:

2015-04-07 16:15:03,069 5132 INFO avandco openerp.modules.loading: loading 1 modules...
2015-04-07 16:15:03,417 5132 INFO avandco openerp.modules.loading: 1 modules loaded in 0.35s, 0 queries
2015-04-07 16:15:04,444 5132 INFO avandco openerp.modules.loading: loading 124 modules...
2015-04-07 16:15:06,374 5132 INFO avandco openerp.modules.module: module mrp: creating or updating database tables
2015-04-07 16:15:07,477 5132 INFO avandco openerp.modules.loading: loading mrp/security/mrp_security.xml
2015-04-07 16:15:08,681 5132 INFO avandco openerp.modules.loading: loading mrp/security/ir.model.access.csv
2015-04-07 16:15:09,296 5132 INFO avandco openerp.modules.loading: loading mrp/mrp_workflow.xml
2015-04-07 16:15:09,365 5132 INFO avandco openerp.modules.loading: loading mrp/mrp_data.xml
2015-04-07 16:15:09,417 5132 INFO avandco werkzeug: 94.23.205.107 - - [07/Apr/2015 16:15:09] "GET / HTTP/1.1" 500 -
2015-04-07 16:15:09,446 5132 ERROR avandco werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi
    
  File "werkzeug\serving.py", line 165, in execute
    
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\server.py", line 280, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1214, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1188, in __call__
    return self.app(environ, start_wrapped)
  File "werkzeug\wsgi.py", line 579, in __call__
    
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1346, in dispatch
    ir_http = request.registry['ir.http']
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 318, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\registry.py", line 293, in get
    update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\base\ir\ir_model.py", line 1047, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 3267, in create
    wh_loc_id = location_obj.create(cr, uid, loc_vals, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 160, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\models.py", line 3972, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\models.py", line 4110, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xab name \xbb
DETAIL:  La ligne en \xe9chec contient (129, null, null, null, null, null, 2015-04-07 16:15:07.405, 2015-04-07 16:15:07.405, 1, 1, 0, 0, 0, t, null, null, f, null, 1, 1, null, view, null, null)
" while parsing file:///C:/Program%20Files%20(x86)/Odoo%208.0-20140920-000204/server/openerp/addons/mrp/mrp_data.xml:40, near
<record id="stock.warehouse0" model="stock.warehouse">
            <field name="manufacture_to_resupply" eval="True"/>
        </record>
2015-04-07 16:15:09,460 5132 INFO avandco openerp.modules.loading: loading 1 modules...
2015-04-07 16:15:09,757 5132 INFO avandco openerp.modules.loading: 1 modules loaded in 0.28s, 0 queries
2015-04-07 16:15:10,865 5132 INFO avandco openerp.modules.loading: loading 124 modules...
2015-04-07 16:15:13,549 5132 INFO avandco openerp.modules.module: module mrp: creating or updating database tables
2015-04-07 16:15:14,158 5132 INFO avandco openerp.modules.loading: loading mrp/security/mrp_security.xml
2015-04-07 16:15:15,344 5132 INFO avandco openerp.modules.loading: loading mrp/security/ir.model.access.csv
2015-04-07 16:15:15,983 5132 INFO avandco openerp.modules.loading: loading mrp/mrp_workflow.xml
2015-04-07 16:15:16,062 5132 INFO avandco openerp.modules.loading: loading mrp/mrp_data.xml
2015-04-07 16:15:16,124 5132 INFO avandco werkzeug: 94.23.205.107 - - [07/Apr/2015 16:15:16] "GET /favicon.ico HTTP/1.1" 500 -
2015-04-07 16:15:16,140 5132 ERROR avandco werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi
    
  File "werkzeug\serving.py", line 165, in execute
    
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\server.py", line 280, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\service\wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1214, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1188, in __call__
    return self.app(environ, start_wrapped)
  File "werkzeug\wsgi.py", line 579, in __call__
    
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 1346, in dispatch
    ir_http = request.registry['ir.http']
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\http.py", line 318, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\registry.py", line 293, in get
    update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 354, in load_modules
    force, status, report, loaded_modules, update_module)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\modules\loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\tools\convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\base\ir\ir_model.py", line 1047, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 3267, in create
    wh_loc_id = location_obj.create(cr, uid, loc_vals, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 160, in create
    return super(stock_location, self).create(cr, uid, default, context=context)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\models.py", line 3972, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\models.py", line 4110, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xab name \xbb
DETAIL:  La ligne en \xe9chec contient (130, null, null, null, null, null, 2015-04-07 16:15:14.112, 2015-04-07 16:15:14.112, 1, 1, 0, 0, 0, t, null, null, f, null, 1, 1, null, view, null, null)
" while parsing file:///C:/Program%20Files%20(x86)/Odoo%208.0-20140920-000204/server/openerp/addons/mrp/mrp_data.xml:40, near
<record id="stock.warehouse0" model="stock.warehouse">
            <field name="manufacture_to_resupply" eval="True"/>
        </record>

Best regards,
Alain

**Comment by avanzella** [comment]
Issue has been solved by a database update.
