### ISSUE TITLE
[12] Error while app installing

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#61978]
Impacted versions: 12

Steps to reproduce: Uninstall modules, then install it again

Current behavior: Error

Expected behavior: Install modules

Hello, I uninstalled three of my apps to debug purposes. When I located an error in one of them I wanted to install back two of them. Unfortunately during install Im getting error. But when I tried to install this module where there was a bug it installed properly. 

On both modules errors are similar and it says about (group_id)=(239046)

No one of groups was deleted...

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading advance_signup failed: file advance_signup/security/ir.model.access.csv could not be processed:
 insert or update on table "ir_model_access" violates foreign key constraint "ir_model_access_group_id_fkey"
DETAIL:  Key (group_id)=(239046) is not present in table "res_groups".
insert or update on table "ir_model_access" violates foreign key constraint "ir_model_access_group_id_fkey"
DETAIL:  Key (group_id)=(239046) is not present in table "res_groups".

**Comment by Yenthe666** [comment]
Please add detailed steps on how to reproduce this. Can you reproduce this on runbot.odoo.com?

**Comment by zozolpl** [comment]
Unfortunately, I am not able to provide more information - modules that are not installable now worked earlier for over half a year. During this time, updates to odoo and linux were made.
I am not able to reproduce this on the runbot because they are third part modules. And I don't know under what circumstances this error occurred

**Comment by pedrobaeza** [comment]
I'm pretty sure this is not a fault of Odoo, but changes on your code that leads that when you uninstall the module, an XML-ID was not present in the code and then the record was not purged during such uninstallation.

Closing until further evidence is presented.
