### ISSUE TITLE
[14.0] Cannot install module with valid view

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#62072]
Impacted versions:
14.0

Steps to reproduce:
Install arch_test module (See attachments)

Current behavior:
Module is not installed, because of exception

```
2020-11-20 09:28:05,912 1 INFO test odoo.modules.loading: loading arch_test/data.xml 
2020-11-20 09:28:05,942 1 INFO test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [2] 
2020-11-20 09:28:05,983 1 INFO test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [15] 
2020-11-20 09:28:05,989 1 INFO test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [6] 
2020-11-20 09:28:05,995 1 INFO test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [12] 
2020-11-20 09:28:06,001 1 INFO test odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [9] 
2020-11-20 09:28:06,425 wdb You can now launch your browser at http://[wdb.server]/debug/session/00e34fb9-2b6d-423d-b9d3-0e696a48e392 at open_browser:881
2020-11-20 09:28:12,425 wdb Connection lost at receive:859
2020-11-20 09:28:12,453 1 WARNING test odoo.modules.loading: Transient module states were reset 
2020-11-20 09:28:12,476 1 ERROR test odoo.modules.registry: Failed to load registry 
2020-11-20 09:28:12,476 1 CRITICAL test odoo.service.server: Failed to initialize database `test`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 655, in _tag_template
    return self._tag_record(record)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4185, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4114, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 484, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-62>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3875, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1128, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 502, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3664, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1249, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 385, in _check_xml
    view_arch = etree.fromstring(view.arch.encode('utf-8'))
AttributeError: 'bool' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 684, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
odoo.tools.convert.ParseError: while parsing None:7, near
<data inherit_id="web.login_layout" priority="8">
        <xpath expr="//div[@t-if='not disable_footer']" position="replace">
            <div>Hello</div>
        </xpath>
    </data>
```

Expected behavior:
Module is installed successfully

If in data.xml we define template with login_layout first and record with main_partner as second, module is installed successfully.

[arch_test.tar.gz](https://github.com/odoo/odoo/files/5572740/arch_test.tar.gz)

**Comment by pedrobaeza** [comment]
The problem is the `position='replace'` clause, that is removing elements from the DOM, and this affects to the rest of the chain. You should avoid or restrict such type of changes.

Closing as no apparent Odoo bug.

**Comment by em230418** [comment]
> The problem is the position='replace' clause
No, it is not @pedrobaeza. Instead of replace you can write after. Same will happen.

Uploading the other file. Using position=after instead
[arch_test.tar.gz](https://github.com/odoo/odoo/files/5572789/arch_test.tar.gz)

**Comment by pedrobaeza** [comment]
And why are you emptying the image in the partner?

**Comment by em230418** [comment]
> And why are you emptying the image in the partner?

Because it is one of the module's feature.

**Comment by pedrobaeza** [comment]
But have you confirmed that is not that one the one that is failing?

**Comment by em230418** [comment]
> But have you confirmed that is not that one the one that is failing?

If we swap elements in data.xml as I mentioned in first message, emptying partner image is working fine.

> If in data.xml we define template with login_layout first and record with main_partner as second, module is installed successfully.

Screentshot from my local instance. No logo in right side
![without_logo](https://user-images.githubusercontent.com/52414052/99789855-0dd91380-2b45-11eb-8f66-f1b0f82197e1.png)

Screenshot from https://5099428-14-0.runbot47.odoo.com/web#id=1&action=52&model=res.company&view_type=form&cids=&menu_id=4. There is logo on right side

![with_logo](https://user-images.githubusercontent.com/52414052/99789845-09acf600-2b45-11eb-9b53-c146d9d68e59.png)

**Comment by pedrobaeza** [comment]
The problem is mixing <record> tags with <template> then. You can't mix both.

**Comment by em230418** [comment]
> The problem is mixing tags with then

Wrong. See attachment.
[arch_test.tar.gz](https://github.com/odoo/odoo/files/5573222/arch_test.tar.gz)

> You can't mix both.

Why?

**Comment by em230418** [comment]
> Wrong. See attachment.

I meant, that the problem is NOT mixing tags. I split record with emptying partner to record.xml and template modification to template.xml, then defined them in manifest.
If you define record.xml first in manifest (like in recent attachment), then you will have exception from my first message.
If you define template.xml first in manifest, everything will be fine.

**Comment by AnnabelleGe** [comment]
may be missing utf-8 declaration
<?xml version="1.0" encoding='UTF-8'?>
