### ISSUE TITLE
odoo 14: error while installing "hr_expense" app

### ISSUE THREAD

**Issue by Oktay96** [odoo/odoo#62226]
> This error only occurs during installation of "expenses" and its dependency "hr_contract".
> On the last lines you can see a record entry which does not exist / should not exist.

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo-dev/odoo-source/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo-dev/odoo-source/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo-dev/odoo-source/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo-dev/odoo-source/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo-dev/odoo-source/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo-dev/odoo-source/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/odoo-dev/odoo-source/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo-dev/odoo-source/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo-dev/odoo-source/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo-dev/odoo-source/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo-dev/odoo-source/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo-dev/odoo-source/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo-dev/odoo-source/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo-dev/odoo-source/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo-dev/odoo-source/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo-dev/odoo-source/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo-dev/odoo-source/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo-dev/odoo-source/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo-dev/odoo-source/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-dev/odoo-source/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo-dev/odoo-source/addons/hr_contract/data/hr_contract_data.xml:13, near
<record id="structure_type_employee_cp200_pfi" model="hr.payroll.structure.type">
            <field name="name">CP200 PFI: Belgian Employee</field>
            <field name="default_resource_calendar_id" ref="resource.resource_calendar_std_38h"/>
            <field name="country_id" ref="base.be"/>
        </record>

**Comment by pedrobaeza** [comment]
Modules are being installed on runbot without problems, so this seems something specific of your deployment (outdated code, third-party modules or other thing).

**Comment by Oktay96** [comment]
all apps are up to date and even if i uninstall third-party modules doesnt fix this

**Comment by Yenthe666** [comment]
Please provide us with steps to reproduce it on runbot.odoo.com

**Comment by Oktay96** [comment]
think that it is not reproducible

**Comment by Yenthe666** [comment]
Closing until you provide steps :)

**Comment by Oktay96** [comment]
upgrading the "base" module solved my issue
