### ISSUE TITLE
odoo_8.0.20150409  odoo win32_service.exe can not start

### ISSUE THREAD

**Issue by coolsoloist** [odoo/odoo#6230]
The windows log writes:
Traceback (most recent call last): File "win32serviceutil.pyo", line 835, in SvcRun File "win32_service.pyo", line 42, in SvcDoRun SystemExit: 255

**Comment by sle-odoo** [comment]
It's working fine on the last version on [nightly](http://nightly.odoo.com/).
Please reinstall
