### ISSUE TITLE
BUG  about MRP  not exist field 'date_deadline'

### ISSUE THREAD

**Issue by dengshuaix** [odoo/odoo#62363]
Odoo Server Error
Traceback (most recent call last):
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/models.py", line 1424, in load_views
    for [v_id, v_type] in views
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/models.py", line 1424, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/addons/web/models/models.py", line 203, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/models.py", line 1511, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 964, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/ds/桌面/ds_file/Z_QYB/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 592, in raise_view_error
    raise ValueError(message)
ValueError: 字段`date_deadline`不存在

错误的上下文:
视图 `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.
