### ISSUE TITLE
Why button_cancel is not returning result?

### ISSUE THREAD

**Issue by tom10271** [odoo/odoo#62364]
https://github.com/odoo/odoo/blob/4c2768846809f6687d03eb0d7f501e57c2c93a90/addons/purchase/models/purchase.py#L405

I am writing a set of XMLRPC call and I need to cancel PO and the XMLRPC call fails as button_cancel is not returning anything.

```
{ err:
   { Error: XML-RPC fault: Traceback (most recent call last):
     File "/me/Sites/odoo-14.0/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
       response = self._xmlrpc(service)
     File "/me/Sites/odoo-14.0/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc
       return dumps((result,), methodresponse=1, allow_none=False)
     File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 971, in dumps
       data = m.dumps(params)
     File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 502, in dumps
       dump(v, write)
     File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 524, in __dump
       f(self, value, write)
     File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 528, in dump_nil
       raise TypeError("cannot marshal None unless allow_none is enabled")
   TypeError: cannot marshal None unless allow_none is enabled
   
       at createFault (/me/Sites/odoo-addons/node_modules/xmlrpc/lib/deserializer.js:83:21)
       at Deserializer.onDone (/me/Sites/odoo-addons/node_modules/xmlrpc/lib/deserializer.js:89:21)
       at SAXStream.emit (events.js:198:13)
       at SAXStream.EventEmitter.emit (domain.js:448:20)
       at SAXParser.SAXStream._parser.onend (/me/Sites/odoo-addons/node_modules/sax/lib/sax.js:190:10)
       at emit (/me/Sites/odoo-addons/node_modules/sax/lib/sax.js:624:35)
       at end (/me/Sites/odoo-addons/node_modules/sax/lib/sax.js:667:5)
       at SAXParser.end (/me/Sites/odoo-addons/node_modules/sax/lib/sax.js:154:24)
       at SAXStream.end (/me/Sites/odoo-addons/node_modules/sax/lib/sax.js:248:18)
       at IncomingMessage.onend (_stream_readable.js:671:10)
     code: 1,
     faultCode: 1,
     faultString:
      'Traceback (most recent call last):\n  File "/me/Sites/odoo-14.0/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2\n    response = self._xmlrpc(service)\n  File "/me/Sites/odoo-14.0/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc\n    return dumps((result,), methodresponse=1, allow_none=False)\n  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 971, in dumps\n    data = m.dumps(params)\n  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 502, in dumps\n    dump(v, write)\n  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 524, in __dump\n    f(self, value, write)\n  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 528, in dump_nil\n    raise TypeError("cannot marshal None unless allow_none is enabled")\nTypeError: cannot marshal None unless allow_none is enabled\n' },
  method: 'execute_kw',
  params:
   [ 'odoo_dev',
     2,
     'admin',
     'purchase.order',
     'button_cancel',
     [ 17 ] ] }
```

**Comment by pedrobaeza** [comment]
Please do the PR adding the returned value.

**Comment by tom10271** [comment]
I found a lot of methods are not returning anything. Maybe fixing it from response serialization side is better
