### ISSUE TITLE
[master] [purchase] [raise new PO does not work]

### ISSUE THREAD

**Issue by vamsiy** [odoo/odoo#6249]
[master branch] [purchases] [Purchase order] [create] 

Add some item and save

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 532, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 569, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 305, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 302, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 807, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 398, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 955, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 947, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/account/account.py", line 1955, in name_get
    for record in self.read(cr, uid, ids, ['description','name'], context=context):
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3130, in read
    records = self.browse(cr, user, ids, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5210, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/opt/odoo/odoo-server/openerp/models.py", line 5203, in _browse
    env.prefetch[cls._name].update(ids)
TypeError: unhashable type: 'dict'

**Comment by jsh-odoo** [comment]
Unable to reproduc the bug in master.

**Comment by vamsiy** [comment]
Reproducible on this commit ID: 9d87d15db6dd40a5a0162fb126c725a2f0a40414

Can you confirm your version once.

**Comment by Yenthe666** [comment]
Hi @vamsiy,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
