### ISSUE TITLE
Odoo 14.0 fresh instalation - 500 internal error

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#62595]
Impacted versions: 14

Steps to reproduce: Fresh instalation (pulled from git)

Current behavior: 500 Internal error

Expected behavior: Open database creator/selector 

Hello, I instaled odoo v14 for tests (using v12 so far)
Created a simple config file to connect to new (clear) database and new user:
```
logfile = /var/log/odoo_14/odoo-server.log
addons_path=/opt/odoo_14/odoo-server/addons

longpolling_port = 8470
http_port = 8472

db_maxconn = 64

db_user = user
db_password = pwd
db_host = localhost
db_port = 5432
```

When I acces to localhost:8472 Im getting 500 internal... and this error is present in log:

```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo_14/odoo-server/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo_14/odoo-server/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo_14/odoo-server/odoo/http.py", line 1295, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo_14/odoo-server/odoo/http.py", line 1263, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/shared_data.py", line 227, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo_14/odoo-server/odoo/http.py", line 1449, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/odoo_14/odoo-server/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
```
Is it related to database config etc. or else problem? 
In log I see that it is connecting to the right database 

//EDIT
Found this error also 
Database db not initialized, you can force it with `-i base`

//EDIT 2
run odoo-bin with -i INIT fixed it :)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
