### ISSUE TITLE
ERROR when testing SMTP settings (but "Connection Test Succeeded!")

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#6268]
When testing the outgoing SMTP server settings, the UI reports success, but there is an ERRPR/exception raised in the output log.

```
2015-04-10 18:31:11,309 3678 ERROR scg_demo1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/share/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/share/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/share/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/share/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/share/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/share/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/share/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/share/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/share/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/share/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/share/odoo/openerp/addons/base/ir/ir_mail_server.py", line 215, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Succeeded!"), _("Everything seems properly set up!"))
except_orm: (u'Connection Test Succeeded!', u'Everything seems properly set up!')
```

**Comment by JayVora-SerpentCS** [comment]
This is probably for log, this is not an issue:)

**Comment by jaredkipe** [comment]
I think it may be the only 'error' I've seen in the log that wasn't a real error.
Seems like there should be a more elegant way of displaying the success case other than throwing an exception with 'success'

**Comment by Yenthe666** [comment]
Indeed - not a bug but it could have been handled cleaner. It was slightly confusing.
