### ISSUE TITLE
[8.0] Error updating stock quantity: float division by zero

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#6271]
Hello,

After updating some modules (stock and product) I get an error message when  updating the stock quantity from the product form. "Error: float division by zero".
Products that have been created before the update don't show the error...
If I try from "warehouse/inventory adjustments" I get the following error message:
AttributeError: 'collections.defaultdict' object has no attribute 'add'.
Any idea?

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 499, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 516, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 282, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 279, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 732, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 375, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\wizard\stock_change_product_qty.py", line 113, in change_product_qty
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 2648, in action_done
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 2672, in action_check
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 2857, in _resolve_inventory_line
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 336, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 3954, in create
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 462, in new_api
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 1836, in _add_missing_default_values
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 1331, in default_get
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 5443, in __getitem__
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\fields.py", line 714, in __get__
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 1376, in add_default_value
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\fields.py", line 824, in determine_default
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\fields.py", line 763, in _compute_value
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock\stock.py", line 1619, in _quantity_normalize
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\product\product.py", line 185, in _compute_qty_obj
ZeroDivisionError: float division by zero

**Comment by avanzella** [comment]
Solved after code update
