### ISSUE TITLE
Model does not accept document creation. 

### ISSUE THREAD

**Issue by jwiley5** [odoo/odoo#62918]
Impacted versions: Odoo14

Steps to reproduce: Model creation in email routing. 

Current behavior: Gives error model does not accept document creation. 

2020-12-04 20:53:46,317 16506 INFO odoo14dbv3 odoo.addons.mail.models.mail_thread: Routing mail with Message-Id <C#############@mail.######.com>: route ('coupon.generate.wizard', None, None, 6, None): model coupon.generate.wizard does not accept document creation 
2020-12-04 20:53:46,317 16506 INFO odoo14dbv3 odoo.addons.fetchmail.models.fetchmail: Failed to process mail from imap server ########## Email Inbound. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo14_v2/odoo/addons/fetchmail/models/fetchmail.py", line 179, in fetch_mail
    res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
  File "/home/ubuntu/odoo14_v2/odoo/addons/mail/models/mail_thread.py", line 1136, in message_process
    routes = self.message_route(message, msg_dict, model, thread_id, custom_values)
  File "/home/ubuntu/odoo14_v2/odoo/addons/mail/models/mail_thread.py", line 1009, in message_route
    raise_exception=True)
  File "/home/ubuntu/odoo14_v2/odoo/addons/mail/models/mail_thread.py", line 800, in _routing_check_route
    self._routing_warn(_('model %s does not accept document creation', model), message_id, route, raise_exception)
  File "/home/ubuntu/odoo14_v2/odoo/addons/mail/models/mail_thread.py", line 666, in _routing_warn
    raise ValueError(short_message)
ValueError: Mailbox unavailable - model coupon.generate.wizard does not accept document creation

Expected behavior: Successful model creation using email.

**Comment by pedrobaeza** [comment]
Not all models can be created this way. Please check the models that accept this way how they handle it.

Closing as no bug, but model not supporting that.
