### ISSUE TITLE
[14.0] website,web_editor: Error when trying to delete saved snippet

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#62923]
Not able to delete saved snippets see: https://drive.google.com/file/d/1wJUmLaS-WSMhQEW7lBG4iYW4-eCr1Xjv/view?usp=sharing

Thanks

**Comment by rk-aix** [comment]
Same issue here, trying to delete e.g. Custom Snippet 1

Temporary (manual) solution:
Goto Settings in Developer Mode -> Technical/User Interface -> Views
Search for your desired Custom Snippet 1 and delete both hits "Custom Snippet 1" and "Custom Snippet 1 Block"...


`Error: Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1364, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1356, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo/addons/web_editor/models/ir_ui_view.py", line 354, in delete_snippet
    key = snippet_view.key.split('.')[1]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'bool' object has no attribute 'split'`

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by JKE-be** [comment]
Hey, @kig-odoo 
A PR already exists for this bug

Can you confirm that it is fixed with https://github.com/odoo/odoo/pull/62555/files ? 

Thank you

**Comment by rk-aix** [comment]
@JKE-be,

Perfect! - Can confirm it is fixed with 62555...

Thank you!

**Comment by kig-odoo** [comment]
@JKE-be Yes i've just tested in development branch and it's working well.
You can close this issue once you merged PR #62555.

Thanks

**Comment by kig-odoo** [comment]
Fixed at: https://github.com/odoo/odoo/pull/62555
