### ISSUE TITLE
ir_module_module not exist on db init

### ISSUE THREAD

**Issue by Walk4Muscle** [odoo/odoo#62975]
Impacted versions:
odoo 14

I was following the document https://www.odoo.com/documentation/10.0/reference/cmdline.html exactly step by steo to build the odoo environment locally, but when I tried to run the command to start odoo server with the command: 
`python odoo-bin  -d mydb -r odoo -w odoo -i base`, 
I got the following error message:
```
2020-12-07 16:03:49,462 31824 ERROR odoo odoo.sql_db: bad query: UPDATE ir_module_module SET state='installed' WHERE state IN ('to remove', 'to upgrade')
ERROR: 错误:  关系 "ir_module_module" 不存在
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
               ^

2020-12-07 16:03:49,463 31824 ERROR odoo odoo.modules.registry: Failed to load registry 
2020-12-07 16:03:49,463 31824 CRITICAL odoo odoo.service.server: Failed to initialize database `odoo`.
Traceback (most recent call last):
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\workspace\odoo-14.0\odoo\models.py", line 4185, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\workspace\odoo-14.0\odoo\models.py", line 4114, in _load_records_create
    return self.create(values)
  File "<decorator-gen-45>", line 2, in create
  File "C:\workspace\odoo-14.0\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\workspace\odoo-14.0\odoo\addons\base\models\ir_actions.py", line 46, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "C:\workspace\odoo-14.0\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\workspace\odoo-14.0\odoo\addons\base\models\ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\workspace\odoo-14.0\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\workspace\odoo-14.0\odoo\models.py", line 3842, in create
    records = self._create(data_list)
  File "C:\workspace\odoo-14.0\odoo\models.py", line 4015, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "C:\workspace\odoo-14.0\odoo\models.py", line 1249, in _validate_fields
    check(self)
  File "C:\workspace\odoo-14.0\odoo\addons\base\models\ir_actions.py", line 437, in _check_python_code
    raise ValidationError(msg)
odoo.exceptions.ValidationError: forbidden opcode(s) in "config = model.next() or {}\nif config.get('type') not in ('ir.actions.act_window_close',):\n    action = config": CONTAINS_OP

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\workspace\odoo-14.0\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\workspace\odoo-14.0\odoo\modules\loading.py", line 394, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "C:\workspace\odoo-14.0\odoo\modules\loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\workspace\odoo-14.0\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 719, in parse
    self._tag_root(de)
  File "C:\workspace\odoo-14.0\odoo\tools\convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/c:/workspace/odoo-14.0/odoo/addons/base/views/ir_actions_views.xml:457, near
<record id="action_run_ir_action_todo" model="ir.actions.server">
            <field name="name">Config: Run Remaining Action Todo</field>
            <field name="type">ir.actions.server</field>
            <field name="model_id" ref="model_res_config"/>
            <field name="state">code</field>
            <field name="code">
config = model.next() or {}
if config.get('type') not in ('ir.actions.act_window_close',):
    action = config
</field>
        </record>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workspace\odoo-14.0\odoo\service\server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "C:\workspace\odoo-14.0\odoo\modules\registry.py", line 91, in new
    odoo.modules.reset_modules_state(db_name)
  File "C:\workspace\odoo-14.0\odoo\modules\loading.py", line 583, in reset_modules_state
    cr.execute(
  File "<decorator-gen-3>", line 2, in execute
  File "C:\workspace\odoo-14.0\odoo\sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "C:\workspace\odoo-14.0\odoo\sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: 错误:  关系 "ir_module_module" not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
```

Dose anyone how to fix it.

**Comment by pedrobaeza** [comment]
Shouldn't you follow https://www.odoo.com/documentation/14.0/reference/cmdline.html instead? Anyway, what do you want to do? Please follow https://www.odoo.com/documentation/14.0/setup/install.html for installation instructions.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by Walk4Muscle** [comment]
It's typo issue for the link, i was exacatly following https://www.odoo.com/documentation/14.0/setup/install.html for the installation. I just want to run the odoo server locally, but cannot fix the issue. 
When i run the command: `python odoo-bin -r odoo -w odoo --addons-path=addons -d mydb -i base` , it always throws the error 
```
ERROR mydb odoo.sql_db: bad query: UPDATE ir_module_module SET state='installed' WHERE state IN ('to remove', 'to upgrade')
ERROR: relation "ir_module_module" does not exist
``` 

the depedencies should be ready, I need help.

**Comment by pedrobaeza** [comment]
Please ask for help in the forums.

**Comment by sim6** [comment]
I run in this issue when I have another odoo is running. So, make sure that not another odoo is running.

**Comment by mpingo** [comment]
I run to this problem on self hosted instances where wkhtmltopdf is not present.
