### ISSUE TITLE
Fetchmail : Microsoft Exchange 10 SSL error

### ISSUE THREAD

**Issue by vrenaville** [odoo/odoo#6300]
**Retrieve mail from an Exchange 2010 with SSL failed**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. configure an account on a Exchange server, specified the security with SSL
 2. Try to fetchmail from this server

Current behavior:

Got this stace back 

```

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp_prod_XXXX/parts/server-tools/fetchmail_attach_from_folder/model/fetchmail_server.py", line 72, in fetch_mail
    connection.close()
  File "/usr/lib/python2.7/imaplib.py", line 382, in close
    typ, dat = self._simple_command('CLOSE')
  File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 825, in _command
    ', '.join(Commands[name])))
error: command CLOSE illegal in state AUTH, only allowed in states SELECTED
```

This issue was discused here also : https://www.odoo.com/fr_FR/forum/help-1/question/incoming-email-imap-ssl-fetch-mail-error-67956

Thanks for your help,

Vincent

**Comment by beledouxdenis** [comment]
Hello Vincent, 

From the traceback:

`command CLOSE illegal in state AUTH, only allowed in states SELECTED`

Which means that the method `close` cannot be applied when in state `AUTH`.

But, the method `close` is called from:
File "/srv/openerp/instances/openerp_prod_XXXX/parts/server-tools/fetchmail_attach_from_folder/model/fetchmail_server.py", line 72, in fetch_mail
    connection.close()

The module fetchmail_attach_from_folder is not a standard module, and is therefore not under our responsibility.
https://www.odoo.com/apps/modules/8.0/fetchmail_attach_from_folder/

Regards,
