### ISSUE TITLE
8.0  account demo conflict with l10n_ca

### ISSUE THREAD

**Issue by bjoliveau** [odoo/odoo#6304]
Actually, when you try to install l10n_ca on a new DB with demo data, you get back an error

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo8/git/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo8/git/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo8/git/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo8/git/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo8/git/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo8/git/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo8/git/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo8/git/odoo/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo8/git/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo8/git/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo8/git/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/odoo8/git/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo8/git/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo8/git/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo8/git/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo8/git/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo8/git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo8/git/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/models.py", line 4250, in _create
    recs._validate_fields(vals)
  File "/opt/odoo8/git/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo8/git/odoo/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `date_stop` failed against a constraint: Error!
The period is invalid. Either some periods are overlapping or the period's dates are not matching the scope of the fiscal year." while parsing /opt/odoo8/git/odoo/addons/account/demo/account_demo.xml:30, near
<record id="period_1" model="account.period">
            <field eval="'01/'+time.strftime('%Y')" name="code"/>
            <field eval="'X 01/'+time.strftime('%Y')" name="name"/>
            <field name="fiscalyear_id" ref="data_fiscalyear"/>
            <field eval="time.strftime('%Y')+'-01-01'" name="date_start"/>
            <field eval="time.strftime('%Y')+'-01-31'" name="date_stop"/>
            <field name="company_id" ref="base.main_company"/>
        </record>

**Comment by foutoucour** [comment]
Hey @bjoliveau  did you find any work around or fix for this issue? I got the same and seem the guys at odoo don't really did anything...

**Comment by ronnynations21** [comment]
HELLO MY GOOD FRIENDS, I HAVE THE SAME PROBLEM AND I CAN´T TO FIND ANY BODY WHO EXPLAINE TO ME HOW CAN TO FIX THIS SERIOUS PROBLEM IN MY ODOO SERVER. PLEASE IF ANY BODY CAN TO HELP US, CONTACT US URGENTLY. THANKS FOR ALL

**Comment by Yenthe666** [comment]
Hi @bjoliveau,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
