### ISSUE TITLE
error attachment_ids when sending invoice V13

### ISSUE THREAD

**Issue by zackleeuk** [odoo/odoo#63060]
Impacted versions: v13 COMMUNITY 18122020

Install Invoicing
Create an invoice
Post invoice and send it
An AttributeError is raised:
"AttributeError: 'account.move' object has no attribute 'attachment_ids'"

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/wizard/account_invoice_send.py", line 123, in send_and_print_action
    self._send_email()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/wizard/account_invoice_send.py", line 96, in _send_email
    if inv.attachment_ids:
AttributeError: 'account.move' object has no attribute 'attachment_ids'

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoo/odoo/commit/685fbbb621ee3d93c66d92398916a6366c47b824. Please update your source code.
