### ISSUE TITLE
Exception during request Authentication

### ISSUE THREAD

**Issue by nataliarosa9** [odoo/odoo#63206]
Impacted versions: 10

Hi, I tried restoring my database on localhost. I got an error during login. Any idea?

INFO teste_10 odoo.addons.base.ir.ir_http: Exception during request Authentication.
Traceback (most recent call last):
  File "/home/naty/PycharmProjects/smartodoo/smartcrm/odoo/addons/base/ir/ir_http.py", line 103, in _authenticate
    request.session.check_security()
  File "/home/naty/PycharmProjects/smartodoo/smartcrm/odoo/odoo/http.py", line 1075, in check_security
    if not security.check_session(self, env):
  File "/home/naty/PycharmProjects/smartodoo/smartcrm/odoo/odoo/service/security.py", line 21, in check_session
    expected = self._compute_session_token(session.sid)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a deployment question, and over an out of official support version. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
