### ISSUE TITLE
8.0 Crash if you inherit the view 'base.view_users_form' in a module that doesn't depend on 'share'

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#6324]
Here is the scenario to reproduce the bug on an up-to-date odoo v8 from github:
1) create a new DB with demo data
2) install my special module "bug_base_phone" available on http://people.via.ecp.fr/~alexis/bug_base_phone.zip
3) restart odoo with "-u bug_base_phone": it works
4) install the "share" module
5) restart odoo with "-u bug_base_phone" -> it breaks with this error:

```
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 3940, in _write
    recs._validate_fields(vals)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 1274, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `sel_groups_7` does not exist

Error context:
View `base_phone_bug.res.users.telephony_tab`
[view_id: 201, xml_id: bug_base_phone.view_users_form, model: res.users, parent_id: 153]" while parsing /home/alexis/new_boite/dev/test-80/bug_base_phone/res_users_view.xml:11, near
<record id="view_users_form" model="ir.ui.view">
    <field name="name">base_phone_bug.res.users.telephony_tab</field>
    <field name="model">res.users</field>
    <field name="inherit_id" ref="base.view_users_form"/>
    <field name="arch" type="xml">
        <field name="tz" position="attributes">
            <attribute name="readonly">1</attribute>
        </field>
    </field>
</record>
```

We are affected by this bug with the OCA module base_phone, see the bug report on the connector-telephony project: https://github.com/OCA/connector-telephony/issues/35

I found a workaround : edit bug_base_phone/__openerp__.py and add a dependancy on the "share" module. Then restart odoo with "-u bug_base_phone", and it works !!!

**Comment by alexis-via** [comment]
One thing to investigate: it seems that all the module categories are defined in the base module (cf odoo/openerp/addons/base/module/module_data.xml), except the module category "Sharing", which is defined in the share module (cf odoo/addons/share/security/share_security.xml)...

**Comment by ah-taktik** [comment]
Hello,
Same problem occurred on travis today :

```javascript
2015-04-14 13:53:38,724 23700 ERROR openerp_test openerp.addons.base.ir.ir_ui_view: Field `sel_groups_7` does not exist
Error context:
View `inherited.res.users.form`
[view_id: 213, xml_id: web_widget_digital_signature.inherited_res_users_form, model: res.users, parent_id: 153]
2015-04-14 13:53:38,726 23700 CRITICAL openerp_test openerp.service.server: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/service/server.py", line 915, in preload_registries
registry = RegistryManager.new(dbname, update_module=update_module)
File "/home/travis/odoo-8.0/openerp/modules/registry.py", line 368, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 351, in load_modules
force, status, report, loaded_modules, update_module)
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 255, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 176, in load_module_graph
_load_data(cr, module_name, idref, mode, kind='data')
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 118, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 901, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 987, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 853, in parse
self._tags[rec.tag](self.cr, rec, n, mode=mode)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 763, in _tag_record
id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_model.py", line 1050, in _update
model_obj.write(cr, uid, [res_id], values, context=context)
File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/addons/base/ir/ir_ui_view.py", line 282, in write
context)
File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/api.py", line 363, in old_api
result = method(recs, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/models.py", line 3760, in write
self._write(old_vals)
File "/home/travis/odoo-8.0/openerp/api.py", line 239, in wrapper
return new_api(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/api.py", line 546, in new_api
result = method(self._model, cr, uid, self.ids, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/models.py", line 3931, in _write
recs._validate_fields(vals)
File "/home/travis/odoo-8.0/openerp/api.py", line 239, in wrapper
return new_api(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/models.py", line 1267, in _validate_fields
raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition
Error details:
Field `sel_groups_7` does not exist
Error context:
View `inherited.res.users.form`
[view_id: 213, xml_id: web_widget_digital_signature.inherited_res_users_form, model: res.users, parent_id: 153]" while parsing /home/travis/build/OCA/web/web_widget_digital_signature/users_view.xml:22, near
<record id="inherited_res_users_form" model="ir.ui.view">
<field name="name">inherited.res.users.form</field>
<field name="model">res.users</field>
<field name="inherit_id" ref="base.view_users_form"/>
<field name="arch" type="xml">
<xpath expr="//group[@name='messaging']" position="after">
<group string="Digital Signature">
<label for="signature_image" class="oe_edit_only"/>
<h2>
<field name="signature_image" widget="signature"/>
</h2>
</group>
</xpath>
</field>
</record>
2015-04-14 13:53:38,732 23700 INFO openerp_test openerp.service.server: Initiating shutdown
2015-04-14 13:53:38,732 23700 INFO openerp_test openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

**Comment by KangOl** [comment]
It's a known bug I already fixed last month: https://github.com/odoo/odoo/commit/98c1a82e681e9152bc68ee76b89e7cf029a7371c

You can use the same workaround of re-generating the groups view.

**Comment by alexis-via** [comment]
@KangOl 
I see that your patch has been merged in v8
I updated the code of the module bug_base_phone and added
```
<function model="res.groups" name="update_user_groups_view" />
```
Then I replayed the scenario described in this bug report, but it still fails with the same error message. So the problem remains, and the workaround you propose doesn't seem to work.

**Comment by b310mml** [comment]
HI,
I manage to resolve by changing the category_id for group 7-multi currency.
This group is defined in base as:
<record model="res.groups" id="group_multi_currency">
            <field name="category_id" ref="module_category_hidden"/>
</record>
Changing it to anything else will work ok.

Thanks,

**Comment by namirister** [comment]
i have the same probeme on oddo 8.0 by inheriting the res.users class. can you explane more solution ? thanks

**Comment by b310mml** [comment]
hi,

It is because of the category_id which is set initially in
base/module/module_data.xml-start line 126 in odoo8 latest today!
One of the category it referencing in res.users it doesn't exists so it
crashes.
Hope this helps.
Also if you need more details, please send me a link from where i have
posted so i can see first my answer than search for the solution i applied
on my side.

Thanks,
Marius

**Comment by b310mml** [comment]
HI,
This record:
  <record model="res.groups" id="group_multi_currency">
            <field name="category_id" ref="module_category_hidden"/>
  </record>

Category_id=module_category_hidden
Change it to anything else and will work.
Don't have time to dig about why is that, and why it works if share is
installed. Probably this category id is defined in share module and
referenced in base...which is not good.

Thanks,

**Comment by ayyan1** [comment]
hello,i try o add custom fields in account.analytic.account.ields are added but now i can not access contract form,please help me to fix this error

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/odoodev/Odoo/Odoo9/addons/web/controllers/main.py", line 1148, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/home/odoodev/Odoo/Odoo9/openerp/http.py", line 1069, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/addons/base/ir/ir_actions.py", line 370, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/models.py", line 3208, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/models.py", line 3243, in read
    self._read_from_database(stored, inherited)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/models.py", line 3434, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/odoodev/Odoo/Odoo9/openerp/osv/fields.py", line 1501, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/odoodev/Odoo/Odoo9/openerp/addons/base/ir/ir_actions.py", line 312, in _search_view
    'search', context=context)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/addons/mail/models/mail_thread.py", line 369, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/models.py", line 1567, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/addons/base/ir/ir_ui_view.py", line 933, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/home/odoodev/Odoo/Odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoodev/Odoo/Odoo9/openerp/addons/base/ir/ir_ui_view.py", line 476, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `pricelist_id` does not exist

Error context:
View `account.analytic.account.search`
[view_id: 263, xml_id: analytic.view_account_analytic_account_search, model: account.analytic.account, parent_id: n/a]

**Comment by mart-e** [comment]
@ayyan1 please open a new issue for a different problem.
Please also remember that github is for bug reporting, not to ask help on your customizations.
