### ISSUE TITLE
Unable to find Wkhtmltopdf on this system. The PDF can not be created.

### ISSUE THREAD

**Issue by mrcodekiddie** [odoo/odoo#63280]
Impacted versions:
14.0 Git 429febb30bb3f5442cf310e836a5e0e6c4bc3e65

Steps to reproduce:
1. Create an Invoice
2. Try to download it

Current behavior:
**Error message:**
    Unable to find Wkhtmltopdf on this system. The PDF can not be created.

Expected behavior:
   PDF should be downloaded

Screenshot:
 
![image](https://user-images.githubusercontent.com/24442168/101994790-3939c300-3ceb-11eb-961d-cef19b08ded9.png)

Traceback:

 ```
 
Traceback (most recent call last):
  File "/home/illuminati/sites/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/illuminati/sites/odoo/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/illuminati/sites/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/illuminati/sites/odoo/addons/account/controllers/portal.py", line 99, in portal_my_invoice_detail
    return self._show_report(model=invoice_sudo, report_type=report_type, report_ref='account.account_invoices', download=download)
  File "/home/illuminati/sites/odoo/addons/portal/controllers/portal.py", line 414, in _show_report
    report = getattr(report_sudo, method_name)([model.id], data={'report_type': report_type})[0]
  File "/home/illuminati/sites/odoo/odoo/addons/base/models/ir_actions_report.py", line 767, in _render_qweb_pdf
    raise UserError(_("Unable to find Wkhtmltopdf on this system. The PDF can not be created."))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/illuminati/sites/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/illuminati/sites/odoo/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/illuminati/sites/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/illuminati/sites/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/illuminati/sites/odoo/addons/account/controllers/portal.py", line 99, in portal_my_invoice_detail
    return self._show_report(model=invoice_sudo, report_type=report_type, report_ref='account.account_invoices', download=download)
  File "/home/illuminati/sites/odoo/addons/portal/controllers/portal.py", line 414, in _show_report
    report = getattr(report_sudo, method_name)([model.id], data={'report_type': report_type})[0]
  File "/home/illuminati/sites/odoo/odoo/addons/base/models/ir_actions_report.py", line 767, in _render_qweb_pdf
    raise UserError(_("Unable to find Wkhtmltopdf on this system. The PDF can not be created."))
odoo.exceptions.UserError: Unable to find Wkhtmltopdf on this system. The PDF can not be created.   

```

wkhtmltopdf:
  **Version**:  wkhtmltopdf 0.12.6 (with patched qt)
  **Path**: /usr/bin/wkhtmltopdf

OS: 
  Debian Buster (10)

**Comment by mage1k99** [comment]
Yep same issue here too.

**Comment by NICO-SOLUTIONS** [comment]
For Debain Buster 10 you should be fine by using wkhtmltox_0.12.6-1.buster

_"wkhtmltopdf:
Version: wkhtmltopdf 0.12.6 (with patched qt)
Path: /usr/bin/wkhtmltopdf"_

Is this your result for checking installed version of wkhtmltopdf by entering "wkhtmltopdf --version"? So does it mean wkhtmltopdf is installed but odoo doesnt find it?

**Comment by mart-e** [comment]
Hello,

Could you run the following commands and give use the result ?
```
$ /usr/bin/wkhtmltopdf --version
$ python odoo-bin shell -d YOURDATABASENAME
...
>>> import os; os.environ.get('PATH', os.defpath).split(os.pathsep)
>>> from odoo.tools.misc import find_in_path; find_in_path('wkhtmltopdf')
'/usr/bin/wkhtmltopdf'
```
