### ISSUE TITLE
Home Action not working

### ISSUE THREAD

**Issue by HendryLeo** [odoo/odoo#63561]
Impacted versions: 14

Steps to reproduce:
1. Login as administrator
2. Activate developer mode
2. Change user Preferences, set Home Action
3. Logout
4. Login again as user

Current behavior:
1. If developer mode is on, user will open to the Home Action set before
2. If developer mode is off, user will see Discuss Menu

Expected behavior:
User will open to the Home Action set, regardless of developer mode

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/10069724/102576291-c172fa80-4127-11eb-803c-b5339ab23249.png)

Home page with developer mode on
![image](https://user-images.githubusercontent.com/10069724/102576353-e5ced700-4127-11eb-972c-3f5a0db204b0.png)

Home page with developer mode off
![image](https://user-images.githubusercontent.com/10069724/102576420-0e56d100-4128-11eb-8808-9f4ba9d11315.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by shurshilov** [comment]
Yes, confirm the same behavior. please fix it)

**Comment by ctac1412** [comment]
Yes, confirm the same behavior. please fix it)

**Comment by Pilgrim26** [comment]
Hi, the problem is current, please fix it )

**Comment by SergePogorelov** [comment]
Hello. the problem really exists, please fix it.

**Comment by quick-sort** [comment]
adding line `self._ignore_hashchange = true;` in `odoo/addons/web/static/src/js/chrome/web_client.js` right after line 82  could fix this problem.
in odoo/addons/web/static/src/js/chrome/web_client.js
```
line 82: $(window).bind('hashchange', self.on_hashchange);
line 83: self._ignore_hashchange = true;
```
I guess it's the do_action call triggers hashchange event and somehow hashchange call triggers openFirstApp(). The added line could ignore hashchange event once.

**Comment by HendryLeo** [comment]
confirmed that modifying odoo/addons/web/static/src/js/chrome/web_client.js
```
line 82: $(window).bind('hashchange', self.on_hashchange);
line 83: self._ignore_hashchange = true;
```
works for me.

I am trying to override the show_application function, but still not successful
this is my code so far

web_client.js
```
odoo.define('pos_custom_layout.WebClient', function (require) {
    "use strict";

    var webclient = require('web.WebClient');

    webclient.extend({
        show_application: function () {
            var self = this;
            this.set_title();
    
            return this.menu_dp.add(this.instanciate_menu_widgets()).then(function () {
                $(window).bind('hashchange', self.on_hashchange);
                self._ignore_hashchange = true; // change is proposed by https://github.com/odoo/odoo/issues/63561#issuecomment-798624146

                // If the url's state is empty, we execute the user's home action if there is one (we
                // show the first app if not)
                var state = $.bbq.getState(true);
                if (_.keys(state).length === 1 && _.keys(state)[0] === "cids") {
                    return self.menu_dp.add(self._rpc({
                            model: 'res.users',
                            method: 'read',
                            args: [session.uid, ["action_id"]],
                        }))
                        .then(function (result) {
                            var data = result[0];
                            if (data.action_id) {
                                return self.do_action(data.action_id[0]).then(function () {
                                    self.menu.change_menu_section(self.menu.action_id_to_primary_menu_id(data.action_id[0]));
                                });
                            } else {
                                self.menu.openFirstApp();
                            }
                        });
                } else {
                    return self.on_hashchange();
                }
            });
        },
    });
});

```

webclient.xml
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
	<template id="pos_custom_layout.assets_backend" inherit_id="web.assets_backend">
		<xpath expr="." position="inside">
			<script type="text/javascript" src="/pos_custom_layout/static/src/js/web_client.js" ></script>
		</xpath>
	</template>
</odoo>

```
web_client.js is already loaded
![image](https://user-images.githubusercontent.com/10069724/111729825-8a38f480-88a2-11eb-86a5-5ab094cdc9d5.png)

but the same behavior can not be achieved

**Comment by sicay1** [comment]
> adding line `self._ignore_hashchange = true;` in `odoo/addons/web/static/src/js/chrome/web_client.js` right after line 82 could fix this problem.
> in odoo/addons/web/static/src/js/chrome/web_client.js
> 
> ```
> line 82: $(window).bind('hashchange', self.on_hashchange);
> line 83: self._ignore_hashchange = true;
> ```
> 
> I guess it's the do_action call triggers hashchange event and somehow hashchange call triggers openFirstApp(). The added line could ignore hashchange event once.

it not works for me. I got this error after login

```
Traceback:
Error: NameError: name 'active_id' is not defined
    at PY_ensurepy (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:87:65)
    at Object.py.evaluate (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:204:8)
    at Object.py.evaluate (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:214:194)
    at Object.py.eval (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:218:284)
    at https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:355:110
    at iterator (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:110:183)
    at Function.<anonymous> (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:113:8)
    at _.<computed> [as reduce] (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:165:526)
    at eval_contexts (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:353:136)
    at https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:355:253
```

please help

**Comment by borisduin** [comment]
> > adding line `self._ignore_hashchange = true;` in `odoo/addons/web/static/src/js/chrome/web_client.js` right after line 82 could fix this problem.
> > in odoo/addons/web/static/src/js/chrome/web_client.js
> > ```
> > line 82: $(window).bind('hashchange', self.on_hashchange);
> > line 83: self._ignore_hashchange = true;
> > ```
> > 
> > 
> > I guess it's the do_action call triggers hashchange event and somehow hashchange call triggers openFirstApp(). The added line could ignore hashchange event once.
> 
> it not works for me. I got this error after login
> 
> ```
> Traceback:
> Error: NameError: name 'active_id' is not defined
>     at PY_ensurepy (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:87:65)
>     at Object.py.evaluate (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:204:8)
>     at Object.py.evaluate (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:214:194)
>     at Object.py.eval (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:218:284)
>     at https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:355:110
>     at iterator (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:110:183)
>     at Function.<anonymous> (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:113:8)
>     at _.<computed> [as reduce] (https://erp.hagi.com.vn/web/content/239-49bf0a2/web.assets_common.js:165:526)
>     at eval_contexts (https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:353:136)
>     at https://erp.hagi.com.vn/web/content/266-8bead91/web.assets_backend.js:355:253
> ```
> 
> please help

Hi Sicay, It is another kind of error. Check if your selected action has domain options defined.

**Comment by vito-dev** [comment]
Hello, this issue is old but still not fixed. This feature is very important to us.
I see Xavier Morel did some modifications last month in web_client.js but it's still not working without Developer mode active!
Any plans to get this fixed? Thank you.

**Comment by a87b01c14** [comment]
start: function () {
        ****this._ignore_hashchange** = true;//Fix bug:user's home action works only in debug mode**
        core.bus.on('change_menu_section', this, function (menuID) {
            this.do_push_state(_.extend($.bbq.getState(), {
                menu_id: menuID,
            }));
        });
        return this._super.apply(this, arguments);
    },

add this line "this._ignore_hashchange= true;"
in odoo/addons/web/static/src/js/chrome/web_client.js

@quick-sort  you are right!

**Comment by MichalNemec** [comment]
> start: function () { ****this._ignore_hashchange** = true;//Fix bug:user's home action works only in debug mode** core.bus.on('change_menu_section', this, function (menuID) { this.do_push_state(_.extend($.bbq.getState(), { menu_id: menuID, })); }); return this._super.apply(this, arguments); },
> 
> add this line "this._ignore_hashchange= true;" in odoo/addons/web/static/src/js/chrome/web_client.js
> 
> @quick-sort you are right!

this and even the change from `show_application: function ()` is showing discuss app as blank page. its not loaded at all. Any solutions for that?

**Comment by dariojr** [comment]
> start: function () { ****this._ignore_hashchange** = true;//Fix bug:user's home action works only in debug mode** core.bus.on('change_menu_section', this, function (menuID) { this.do_push_state(_.extend($.bbq.getState(), { menu_id: menuID, })); }); return this._super.apply(this, arguments); },
> 
> add this line "this._ignore_hashchange= true;" in odoo/addons/web/static/src/js/chrome/web_client.js
> 
> @quick-sort you are right!

Hello! it's work form me. Odoo 14 (Version Community)

**Comment by wahono77** [comment]
If only add this._ignore_hashchange = true;, if we reload browser, it will display blank. I add this._ignore_hashchange = false; after if (!_.isEqual(_.keys(state), ["cids"])) { like this :
``    async show_application() {
        this.set_title();

        await this.menu_dp.add(this.instanciate_menu_widgets());
        $(window).bind('hashchange', this.on_hashchange);
        this._ignore_hashchange = true; //===============> add this

        const state = $.bbq.getState(true);
        if (!_.isEqual(_.keys(state), ["cids"])) {
            this._ignore_hashchange = false; //===============> add this
            return this.on_hashchange();
        }

**Comment by incoluz** [comment]
> this._ignore_hashchange = false;_

this works for us.  Thanks!

**Comment by incoluz** [comment]
> If only add this._ignore_hashchange = true;, if we reload browser, it will display blank. I add this._ignore_hashchange = false; after if (!_.isEqual(_.keys(state), ["cids"])) { like this : `` async show_application() { this.set_title();
> 
> ```
>     await this.menu_dp.add(this.instanciate_menu_widgets());
>     $(window).bind('hashchange', this.on_hashchange);
>     this._ignore_hashchange = true; //===============> add this
> 
>     const state = $.bbq.getState(true);
>     if (!_.isEqual(_.keys(state), ["cids"])) {
>         this._ignore_hashchange = false; //===============> add this
>         return this.on_hashchange();
>     }
> ```

this works for us. Thanks @wahono77 !!!

**Comment by E4eqRL0yw0yajQJ433QL** [comment]
thx @wahono77. Solution confirmed. For those who do this in a docker container and do not do this every day, see sample instruction below:

**Find Odoo CONTAINER_ID**
sudo docker container ls

**Run container as root**
sudo docker exec -it -u root CONTAINER_ID bash

**Install VI**
apt-get update
apt-get install vim

**Edit web_client.js according to the instructions of @wahono77** 
cd /usr/lib/python3/dist-packages/odoo/addons
cd web/static/src/js/chrome/
vi web_client.js

**Restart container**

**Comment by incoluz** [comment]
BTW this https://github.com/odoo/odoo/issues/63561#issuecomment-1084552448 is a temporary workaround... any way to make this fix persistent over Odoo source code updates?
