### ISSUE TITLE
error: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6390]
I have test server that is run directly from Odoo source (no apache or nginx). And it started giving this error:

``` python
2015-04-20 10:55:09,364 1167 ERROR db_name openerp.addons.fetchmail.fetchmail: General failure when trying to fetch mail from imap server example@example.com.
Traceback (most recent call last):
  File "/home/andrius/odoo/8.0/odoo/addons/fetchmail/fetchmail.py", line 196, in fetch_mail
    imap_server = server.connect()
  File "/home/andrius/odoo/8.0/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/andrius/odoo/8.0/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/andrius/odoo/8.0/odoo/addons/fetchmail/fetchmail.py", line 140, in connect
    connection = IMAP4_SSL(server.server, int(server.port))
  File "/usr/lib/python2.7/imaplib.py", line 1165, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python2.7/imaplib.py", line 172, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/imaplib.py", line 1176, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
error: [Errno 24] Too many open files
```

running 'lsof -n -p 1167' (1167 python PID)

```
python  1167 odoo  460u  IPv4             417593      0t0     TCP 192.168.1.119:8079->77.77.77.77:61267 (ESTABLISHED)
python  1167 odoo  461u  IPv4             428448      0t0     TCP 192.168.1.119:8079->77.77.77.77:62944 (ESTABLISHED)
python  1167 odoo  462u  IPv4             422988      0t0     TCP 192.168.1.119:8079->77.77.77.77:62205 (ESTABLISHED)
python  1167 odoo  463u  IPv4             424936      0t0     TCP 192.168.1.119:8079->77.77.77.77:62271 (ESTABLISHED)
python  1167 odoo  464u  IPv4             438781      0t0     TCP 192.168.1.119:8079->77.77.77.77:64474 (ESTABLISHED)
python  1167 odoo  465u  IPv4             425231      0t0     TCP 192.168.1.119:8079->77.77.77.77:62458 (ESTABLISHED)
```

It shows a lot of connections that are established on same IP (I pasted only the part, but the are many more such connections with few IPs).

Does anyone know what could cause this?

**Comment by guilro** [comment]
Same is happening to me. The system file limit is reached and causing instability on the entire sever.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
