### ISSUE TITLE
Error Sync Google Calendar Odoo v14

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#64120]
Impacted versions:
Odoo 14

Current behavior:

I configure Google Calendar API. When I schedule a meeting in Odoo it does sync in Google Calendar, but when I schedule a meeting in Google Calendar it doesn't sync in Odoo.

Also an error appears in Odoo. This is:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/controllers/main.py", line 44, in sync_data
    need_refresh = request.env.user.sudo()._sync_google_calendar(GoogleCal)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/res_users.py", line 94, in _sync_google_calendar
    synced_events = self.env['calendar.event']._sync_google2odoo(events - recurrences, default_reminders=default_reminders)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/google_sync.py", line 168, in _sync_google2odoo
    vals = dict(self._odoo_values(gevent, default_reminders), need_sync=False)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/calendar.py", line 58, in _odoo_values
    attendee_commands, partner_commands = self._odoo_attendee_commands(google_event)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/models/calendar.py", line 92, in _odoo_attendee_commands
    user = google_event.owner(self.env)
  File "/usr/lib/python3/dist-packages/odoo/addons/google_calendar/utils/google_event.py", line 132, in owner
    real_owner = real_owner_id and env['res.users'].browse(int(real_owner_id))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: invalid literal for int() with base 10: 'false'

Thank you very much for the help!

**Comment by rb3606** [comment]
I have same problem When create meeting in odoo its sync with google calendar but in background its giving same error. 

`2021-03-18 13:19:23,307 373972 ERROR vesta odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/addons/google_calendar/controllers/main.py", line 44, in sync_data
    need_refresh = request.env.user.sudo()._sync_google_calendar(GoogleCal)
  File "/opt/odoo14/addons/google_calendar/models/res_users.py", line 94, in _sync_google_calendar
    synced_events = self.env['calendar.event']._sync_google2odoo(events - recurrences, default_reminders=default_reminders)
  File "/opt/odoo14/addons/google_calendar/models/google_sync.py", line 172, in _sync_google2odoo
    vals = dict(self._odoo_values(gevent, default_reminders), need_sync=False)
  File "/opt/odoo14/addons/google_calendar/models/calendar.py", line 63, in _odoo_values
    'user_id': google_event.owner(self.env).id,
  File "/opt/odoo14/addons/google_calendar/utils/google_event.py", line 132, in owner
    real_owner = real_owner_id and env['res.users'].browse(int(real_owner_id))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: invalid literal for int() with base 10: 'false'`

**Comment by wai** [comment]
#67746 fixed this error

**Comment by pedrobaeza** [comment]
Closing then.
