### ISSUE TITLE
[8.0] Impossible to attach Email template to a Mass Mailing in Marketing>Mass Mailings

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#6433]
**[8.0] Impossible to attach Email template to a Mass Mailing in Marketing>Mass Mailings**

Impacted versions:

 - 8.0 (Nightly build odoo-8.0_20150422) on Ubuntu 14.04

Steps to reproduce:

 1. Create a new Mass Mailing 
 2. select Recipients : Leads/Opportunities
 3. in Mail Body of this new Mass Mailing click on "Design Email"
 4. On the page with list of all Email Templates : Click Select under needed template, then Click Save, then Click Back
 5. When you are back on the page of Mass Mailing creation click again on "Design Email" and you will see Odoo Server Error

Current behavior:

 - After selecting an template on the page where are listed all Email Templates Mass Mailing mail body  is empty, there is no Email template attached to the Mass Mailing!  If you click one more time on the button "Design Email" you will see this Odoo Server Error:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150422-py2.7.egg/openerp/addons/mass_mailing/models/mass_mailing.py", line 553, in action_edit_html
    url = '/website_mail/email_designer?model=mail.mass_mailing&res_id=%d&template_model=%s&return_action=%d&enable_editor=1' % (ids[0], mail.mailing_model, context['params']['action'])
KeyError: 'action'

Expected behavior:

 - You mast have an Email template attached to the Mass Mailing

Best regards.

**Comment by mianos** [comment]
Did you find a workaround for this? I can't seem to find any way to save a template into the outgoing mail and, of course, it gives the python error and fails.

**Comment by sergueikp** [comment]
Hi, I just use an earlier nigtly build version, in my case I've tested and found that nightly build odoo_8.0.20150407.tar.gz has no issue with Marketing mass mailing.

**Comment by jbcrouigneau** [comment]
About the same issue with 8.0-20150614.
I have KeyError: 'params' instead, but same result.
A blocker !

**Comment by sergueikp** [comment]
Hi, everybody, I found a workaround for the problem of mass mailing template, 
In order to be able to attach an email template to your mass mailing you have to enable English as default language in Website settings !!!! 
![website_settings](https://cloud.githubusercontent.com/assets/9844780/8195250/9e0fda82-1481-11e5-8190-370fb78a97d7.JPG)
Then restart your server or/and purge the cashe of your browser. 
That's all.
