### ISSUE TITLE
Error While Searching by Date / Datetime fields if user language is Arabic

### ISSUE THREAD

**Issue by IAY-DGTERA** [odoo/odoo#64392]
Impacted versions:
14.0

Steps to reproduce:
1. Change User Language to Arabic
2. Open order list view in point of sale 
3. press Filters --> add custom filter
4. choose date equals to 
5. from the date picker widget select a date then press outside of it
6. error would appear

note: can be reproduced on runbot https://5710815-14-0.runbot44.odoo.com/

Current behavior:
خطأ:
Uncaught TypeError: date.format is not a function

https://5710815-14-0.runbot44.odoo.com/web/content/1504-7bf575e/web.assets_backend.js:855
تتبع الأثر:
TypeError: date.format is not a function
    at DateTimePicker._onDateTimePickerHide (https://5710815-14-0.runbot44.odoo.com/web/content/1504-7bf575e/web.assets_backend.js:855:101)
    at HTMLDivElement.dispatch (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1719:447)
    at HTMLDivElement.elemData.handle (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1705:166)
    at Object.trigger (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1936:227)
    at HTMLDivElement.<anonymous> (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1942:258)
    at Function.each (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1418:170)
    at jQuery.fn.init.each (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1409:192)
    at jQuery.fn.init.trigger (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:1942:229)
    at TempusDominusBootstrap4._notifyEvent (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:3729:15)
    at TempusDominusBootstrap4.hide (https://5710815-14-0.runbot44.odoo.com/web/content/1503-891d5b4/web.assets_common.js:3975:178)

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/74735567/104303522-db0f2400-54d2-11eb-83df-e1fed64da697.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by IAY-DGTERA** [comment]
Hello guys is there any chance this is going to be fixed soon

**Comment by Yenthe666** [comment]
As long as there is no feedback there is basically nobody from Odoo looking at it.

**Comment by msh-odoo** [comment]
@IAY-DGTERA @Yenthe666 This should be fixed with #63091
