### ISSUE TITLE
[8.0] Computed fields in multicompany environment produce "Access Error"

### ISSUE THREAD

**Issue by matthieuchoplin** [odoo/odoo#6447]
**When a user access a record that has been created by an other user logged in under an other company, then we always get an access error if one of the fields of the object is a computed fields.**
## Impacted versions:
- 8.0
## Steps to reproduce:
1. Enable the multicompany environment for the user admin and demo by ticking the box "Multicompany" on the user object and authorize both companies "Your Company" and "Your Company, Chicago" for the 2 users.
2. Log in with the user  "admin" and make sure that he is logged in under the company "Your Company, Chicago".
   Check that he has created an supplier invoice that is in the state "open" (if it is triggered by the tests, you can take the supplier invoice for the supplier "Nebula Business"). If no supplier invoice has been created by admin under this company, please do it.
3. Log in with the user "demo", and make sure that the is logged in under the company "Your Company". Go on the supplier invoice that was created by the user "admin" and validate it.
   You will not have an error in the user interface because the code is written with the old API. It is more serious if the computed field is using the new api because the error prevent from editing the document.
   The error will be seen in the logs:

```
2015-04-23 11:25:40,786 15158 INFO account werkzeug: 127.0.0.1 - - [23/Apr/2015 11:25:40] "POST /web/dataset/call_kw/res.company/name_search HTTP/1.1" 200 -
2015-04-23 11:25:40,800 15158 ERROR account openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/addons/mail/mail_thread.py", line 188, in read_followers_data
    is_uid = uid in map(lambda x: x.id, follower.user_ids)
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/models.py", line 5910, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/home/matt/work/odoo/odoo-custom/community-apps/odoo/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)')

```

I provide a video here that illustrates this case: https://youtu.be/Nz2I6RFM0Io

The error I am getting here is for the specific case of an invoice but it is actually a **generic error** that can be reproduced on any object that has computed fields (taking into account that we are in a multicompany environment use case where one record was created by a user logged in an other company).

This error can be related to other errors that were reported before:
https://github.com/odoo/odoo/issues/3178 and https://github.com/odoo/odoo/issues/4824
Several fixes were proposed, but I think that we still have an issue with the computed fields in a multicompany environment.
Fixes proposed: https://github.com/odoo/odoo/pull/4847 replaced by https://github.com/odoo/odoo/pull/5087#issuecomment-73206300

Maybe the compute_sudo attribute could help, but I tried with this as well and it did not work at this point.

**Comment by jcdrubay** [comment]
This is probably related to #13932

**Comment by thomaspaulb** [comment]
I experienced a similar problem with computed fields in multi-company mode, although my issue did not pop up by accessing records created by another user, but by accessing Form Views that reference a non-accessible user (eg. as a follower, eg. Administrator) as well as the newly computed field. See [this issue](https://github.com/OCA/geospatial/issues/139) for a more detailed explanation.

I haven't been able to tackle the bug, but my workaround has been to define my computed field in v7-style instead of v8-style.

**Comment by Yenthe666** [comment]
Hi @matthieuchoplin ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
