### ISSUE TITLE
purchase_stock failed to install/update in a multi company instance

### ISSUE THREAD

**Issue by StephaneMangin** [odoo/odoo#64480]
Impacted versions: 14.0

Steps to reproduce:
Update the module purchase_stock in a multi-company configured database. (in this case a migrated database from odoo)

Current behavior:
Fail to insert `odoo/src/addons/purchase_stock/data/purchase_stock_data.xml`

Expected behavior:
A functional insertion of the data

Video/Screenshot link (optional):
```
2021-01-13 13:20:41,797 241 INFO odoodb odoo.modules.loading: Loading module purchase_stock (130/161) 
2021-01-13 13:20:42,232 241 INFO odoodb odoo.modules.registry: module purchase_stock: creating or updating database tables 
2021-01-13 13:20:42,539 241 INFO odoodb odoo.modules.loading: loading purchase_stock/security/ir.model.access.csv 
2021-01-13 13:20:42,580 241 INFO odoodb odoo.modules.loading: loading purchase_stock/data/purchase_stock_data.xml 
2021-01-13 13:20:42,605 241 WARNING odoodb odoo.modules.loading: Transient module states were reset 
2021-01-13 13:20:42,606 241 ERROR odoodb odoo.modules.registry: Failed to load registry 
2021-01-13 13:20:42,606 241 CRITICAL odoodb odoo.service.server: Failed to initialize database `odoodb`. 
Traceback (most recent call last):
  File "/odoo/src/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo/src/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/src/odoo/models.py", line 4198, in _load_records
    data['record']._load_records_write(data['values'])
  File "/odoo/src/odoo/models.py", line 4135, in _load_records_write
    self.write(values)
  File "/odoo/src/odoo/models.py", line 3710, in write
    self._check_company()
  File "/odoo/src/odoo/models.py", line 3327, in _check_company
    raise UserError("\n".join(lines))
odoo.exceptions.UserError: Incompatible companies on records:
- 'Buy' belongs to company False and 'Products' (product_ids: (...) ) belongs to another company.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/src/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/src/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/src/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/src/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/src/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/src/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/src/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/src/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/odoo/src/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo/src/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /odoo/src/addons/purchase_stock/data/purchase_stock_data.xml:10, near
<record id="route_warehouse0_buy" model="stock.location.route">
            <field name="name">Buy</field>
            <field name="company_id"/>
            <field name="sequence">5</field>
        </record>
2021-01-13 13:20:42,608 241 INFO odoodb odoo.service.server: Initiating shutdown 
2021-01-13 13:20:42,608 241 INFO odoodb odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
```

Temporary solution : 
Remove `<field name="company_id"></field>` from the `route_warehouse0_buy` record.

Support ticket number submitted via odoo.com/help (optional):
None

**Comment by vava-odoo** [comment]
Fixed in https://github.com/odoo/odoo/pull/74024
