### ISSUE TITLE
SyntaxError App Fleet Reports/Costs Odoo Community v14 Ubuntu server

### ISSUE THREAD

**Issue by marcosmonauta** [odoo/odoo#64513]
Impacted versions: V14 Community

Steps to reproduce: Install Fleet, select Reports and click on costs

Current behavior:   SyntaxError: Unexpected token T in JSON at position 0

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/75961027/104557996-bec0d380-5607-11eb-94a4-340a2fdc0117.png)

I installed Community v14 and the app Fleet. When clicking on reports/costs I get his error

Error:

Traceback:
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Class.init (https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:2400:235)
    at Class.prototype.<computed> [as init] (https://donau.com.mx/web/content/7977-e9c59c3/web.assets_common.js:4614:488)
    at new Class (https://donau.com.mx/web/content/7977-e9c59c3/web.assets_common.js:4615:65)
    at Class._createViewController (https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:448:658)
    at https://donau.com.mx/web/content/9039-1316d81/web.assets_backend.js:453:169

I installed python, checking all dependencies and so on , but I cannot do it work. This happens to me in 2 differente servers

Anybody that could please help me?

**Comment by pedrobaeza** [comment]
Duplicated of #64512
