### ISSUE TITLE
Upgrade underscore.string?

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#64609]
This is a suggestion for master branch.

Currently using version throws not informative errrors:

https://github.com/odoo/odoo/blob/28b748a559e1ffb5fb7c3631bf77adba121b2ebf/addons/web/static/lib/underscore.string/lib/underscore.string.js#L158-L176

Compare with latest version:

https://github.com/esamattis/underscore.string/blob/df8dc9ea7e84ef3313d7c61d47da9d7bcc353ef8/dist/underscore.string.js#L754-L772

More precisely, I'd like to have a better error message when format is broken in translations (see https://github.com/odoo/odoo/pull/64557 )

```

Ошибка:
Uncaught Error: [_.sprintf] huh?

https://5762317-14-0.runbot35.odoo.com/web/static/lib/underscore.string/lib/underscore.string.js:176
Отслеживающий:
Error: [_.sprintf] huh?
    at Function.str_format.parse (https://5762317-14-0.runbot35.odoo.com/web/static/lib/underscore.string/lib/underscore.string.js:176:17)
    at Object.str_format [as sprintf] (https://5762317-14-0.runbot35.odoo.com/web/static/lib/underscore.string/lib/underscore.string.js:79:53)
    at Class._onElementRemoved (https://5762317-14-0.runbot35.odoo.com/web_studio/static/src/js/views/view_editor_sidebar.js:948:29)
    at HTMLButtonElement.<anonymous> (https://5762317-14-0.runbot35.odoo.com/web/static/src/js/core/mixins.js:277:23)
    at HTMLDivElement.dispatch (https://5762317-14-0.runbot35.odoo.com/web/static/lib/jquery/jquery.js:5183:27)
    at HTMLDivElement.elemData.handle (https://5762317-14-0.runbot35.odoo.com/web/static/lib/jquery/jquery.js:4991:28)
```

**Comment by yelizariev** [comment]
I also made a PR to the lib to provide more context in error message 
https://github.com/esamattis/underscore.string/pull/526
