### ISSUE TITLE
Odoo cli database option

### ISSUE THREAD

**Issue by general03** [odoo/odoo#64611]
Hi,

I can't connect to my SAAS database with database specified on cli parameter

Impacted versions: 14.0-20210111

Steps to reproduce:
Launch `odoo --database mydb`

Current behavior:
The odoo try to connect on 'postgres' db insted of 'mydb'
```
INFO ? odoo.sql_db: Connection to the database failed 
Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 61, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 178, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 142, in main
    odoo.service.db._create_empty_database(db_name)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 99, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 675, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 248, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 558, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 626, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
```

I also try to put `db_name=mydb` on odoo.conf without change

Expected behavior:
Odoo must to connect on 'mydb' database

**Comment by pedrobaeza** [comment]
This is a specific deployment question that has nothing to do with Odoo itself. The user from which you are invoking the command is not allowed for PG access.

Closing thus.

**Comment by general03** [comment]
@pedrobaeza thanks for you speed answer but my user have access to 'mydb' database and the 'postgres' database does not exist so the error is understanding
But when I say to Odoo to use 'mydb' database on cli parameter it is not taken

**Comment by general03** [comment]
I found my problem, the 'postgres' databse is set here https://github.com/odoo/odoo/blob/14.0/odoo/service/db.py#L98
 But why it is necessary to connect on this database ?
