### ISSUE TITLE
[BUG] Multi-company COA configuration. ProgrammingError: column "module_payment_authorize" of relation "account_config_settings" does not exist

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6475]
Getting issue 

ProgrammingError: column "module_payment_authorize" of relation "account_config_settings" does not exist

… Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in call
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/odoo/odoo-server/addons/account/res_config.py", line 206, in create
    id = super(account_config_settings, self).create(cr, uid, values, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4197, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, args, *kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "module_payment_authorize" of relation "account_config_settings" does not exist
LINE 1: ...oices", "module_payment_paypal", "sale_tax_rate", "module_pa...

its the error I get when I try configure the chart of accounts for child company R2

**Comment by pcady** [comment]
We are seeing this exact issue.

**Comment by mattsarz** [comment]
I fixed this error by adding a column "module_payment_authorize" to account_config_settings and set it to 'false' manually. I used pgAdmin for this purpose.
For me it worked and I did not see any longterm problems so far...

**Comment by tejastank** [comment]
Till not fixed on code ? looking for update ?

**Comment by mart-e** [comment]
Closing as V8 is no longer supported
