### ISSUE TITLE
[8.0] Error in create partner and/or sale

### ISSUE THREAD

**Issue by ccarly** [odoo/odoo#6501]
```
Traceback (most recent call last):
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/data/home/openerp/tmp/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/tmp/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/openerp/tmp/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/tmp/odoo/addons/base_action_rule/base_action_rule.py", line 177, in create
    new_id = create.origin(self, cr, uid, vals, context=context, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/addons/base/res/res_partner.py", line 573, in create
    partner = super(res_partner, self).create(vals)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/openerp/tmp/odoo/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 4231, in _create
    recs.modified(self._fields)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 5627, in modified
    spec += self._fields[fname].modified(self)
  File "/data/home/openerp/tmp/odoo/openerp/fields.py", line 1479, in modified
    spec = super(_Relational, self).modified(records)
  File "/data/home/openerp/tmp/odoo/openerp/fields.py", line 960, in modified
    target = env[field.model_name].search([(path, 'in', records.ids)])
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 4621, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/data/home/openerp/tmp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/data/home/openerp/tmp/odoo/openerp/models.py", line 4444, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/data/home/openerp/tmp/odoo/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/data/home/openerp/tmp/odoo/openerp/osv/expression.py", line 827, in parse
    elif len(path) > 1 and column._type == 'many2one' and column._auto_join:
AttributeError: 'NoneType' object has no attribute '_type'

```

**Comment by Yenthe666** [comment]
Hi @ccarly,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
