### ISSUE TITLE
[8.0] Changing from DB to another raises an Error

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#6531]
Steps to reproduce:
1. On a brand new instance of Odoo.  Create two DB.  First create "o8".  
2. Then logout and create db "o8-1".
3. Logout.
4. Try to switch to DB "o8".

At this point you get a HTTP 500 error.  The console shows the following:

```
2015-04-30 15:16:47,532 12909 ERROR o8 werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/manu/.buildout/eggs/Werkzeug-0.10-py2.7.egg/werkzeug/serving.py", line 180, in run_wsgi
execute(self.server.app)
  File "/home/manu/.buildout/eggs/Werkzeug-0.10-py2.7.egg/werkzeug/serving.py", line 168, in execute
application_iter = app(environ, start_response)
  File "/home/manu/src/merchise/pgi/openerp/openerp/service/server.py", line 285, in app
return self.app(e, s)
  File "/home/manu/src/merchise/pgi/openerp/openerp/service/wsgi_server.py", line 216, in application
return application_unproxied(environ, start_response)
  File "/home/manu/src/merchise/pgi/openerp/openerp/service/wsgi_server.py", line 202, in application_unproxied
result = handler(environ, start_response)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 1280, in __call__
return self.dispatch(environ, start_response)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 1254, in __call__
return self.app(environ, start_wrapped)
  File "/home/manu/.buildout/eggs/Werkzeug-0.10-py2.7.egg/werkzeug/wsgi.py", line 591, in __call__
return self.app(environ, start_response)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 1421, in dispatch
result = ir_http._dispatch()
  File "/home/manu/src/merchise/pgi/openerp/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
return self._handle_exception(e)
  File "/home/manu/src/merchise/pgi/openerp/openerp/addons/base/ir/ir_http.py", line 140, in _handle_exception
attach = self._serve_attachment()
  File "/home/manu/src/merchise/pgi/openerp/openerp/addons/base/ir/ir_http.py", line 104, in _serve_attachment
request.cr, openerp.SUPERUSER_ID, domain,
  File "/home/manu/.buildout/eggs/Werkzeug-0.10-py2.7.egg/werkzeug/local.py", line 338, in __getattr__
return getattr(self._get_current_object(), name)
  File "/home/manu/src/merchise/pgi/openerp/openerp/http.py", line 240, in cr
self._cr = self.registry.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by mvaled** [comment]
At this point, `self.registry` is None cause the session has lost its "db" attribute.  Tracing the server we reach the self.registry twice, one with the "current" db name, and then with None as the db.

**Comment by JuanjoA** [comment]
Same problem.
Change database, cause a internal error.

**Comment by Yenthe666** [comment]
Hi @mvaled ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
