### ISSUE TITLE
when confirm Quotation as Sale Order, erro: QWebTemplateNotFound: Invalid template id: u''

### ISSUE THREAD

**Issue by alanljj** [odoo/odoo#6582]
when I wan to confirm the Quotation, then I can open it in Sale Order. How to solve this problem?

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 5135, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3133, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3168, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3346, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 1452, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 31, in <lambda>
    _payment_block_proxy = lambda self, _a, *_kw: self._portal_payment_block(_a, *_kw)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 44, in _portal_payment_block
    partner_id=this.partner_id.id, company_id=this.company_id.id, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 299, in render_payment_block
    context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 271, in render
    return self.pool['ir.ui.view'].render(cr, uid, acquirer.view_template_id.xml_id, qweb_context, engine='ir.qweb', context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1029, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 261, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 192, in get_template
    raise_qweb_exception(QWebTemplateNotFound, message="Loader could not find template %r" % name, template=origin_template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 190, in get_template
    xml_doc = qwebcontext.loader(name)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1027, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in read_template
  File "/opt/odoo/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 856, in read_template
    raise ValueError('Invalid template id: %r' % (xml_id,))
QWebTemplateNotFound: Invalid template id: u''

**Comment by alanljj** [comment]
if I change the state of sale order and account invoice to "draft", all of theme can be opened.

**Comment by magneticlab-ch** [comment]
I get the same issue. Did you solve this ?

**Comment by dirtyhandsphp** [comment]
Same issue here..any update?

**Comment by Yenthe666** [comment]
Hi @alanljj,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
