### ISSUE TITLE
[8.0] error, when set up fresh db with demo data in base_demo.xml  PIL

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#6602]
015-05-07 10:06:12,135 29591 INFO develop openerp.modules.loading: loading base/base_demo.xml
2015-05-07 10:06:12,382 29591 ERROR develop openerp.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/service/db.py", line 42, in _initialize_db
    db_name, demo, None, update_module=True)
  File "/opt/workspace/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/workspace/odoo/openerp/modules/loading.py", line 297, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/workspace/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/workspace/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/workspace/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/workspace/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/workspace/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/workspace/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_users.py", line 820, in create
    return super(users_view, self).create(cr, uid, values, context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_users.py", line 633, in create
    user_id = super(users_implied, self).create(cr, uid, values, context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_users.py", line 311, in create
    user_id = super(res_users, self).create(cr, uid, vals, context=context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/models.py", line 4068, in create
    record = self.browse(self._create(old_vals))
  File "/opt/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/models.py", line 4126, in _create
    self.pool[table].write(cr, user, [record_id], tocreate[table], context=context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_partner.py", line 564, in write
    result = super(res_partner, self).write(vals)
  File "/opt/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/models.py", line 3768, in write
    self._write(old_vals)
  File "/opt/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/models.py", line 4010, in _write
    self.pool[model_name]._store_set_values(cr, user, todo, fields_to_recompute, context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/models.py", line 4380, in _store_set_values
    result = self._columns[val[0]].get(cr, self, ids, val, SUPERUSER_ID, context=context)
  File "/opt/workspace/odoo/openerp/osv/fields.py", line 1452, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_partner.py", line 191, in _get_image
    return dict((p.id, tools.image_get_resized_images(p.image)) for p in self)
  File "/opt/workspace/odoo/openerp/addons/base/res/res_partner.py", line 191, in <genexpr>
    return dict((p.id, tools.image_get_resized_images(p.image)) for p in self)
  File "/opt/workspace/odoo/openerp/tools/image.py", line 218, in image_get_resized_images
    return_dict[medium_name] = image_resize_image_medium(base64_source, avoid_if_small=avoid_resize_medium)
  File "/opt/workspace/odoo/openerp/tools/image.py", line 156, in image_resize_image_medium
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/opt/workspace/odoo/openerp/tools/image.py", line 91, in image_resize_image
    image = image_resize_and_sharpen(image, size)
  File "/opt/workspace/odoo/openerp/tools/image.py", line 110, in image_resize_and_sharpen
    image = image.convert('RGBA')
  File "/opt/workspace/Odoo8env/lib/python2.7/site-packages/PIL/Image.py", line 844, in convert
    self.load()
  File "/opt/workspace/Odoo8env/lib/python2.7/site-packages/PIL/ImageFile.py", line 203, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/opt/workspace/Odoo8env/lib/python2.7/site-packages/PIL/Image.py", line 419, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
ParseError: "decoder jpeg not available" while parsing /opt/workspace/odoo/openerp/addons/base/base_demo.xml:32, near
<record id="user_demo" model="res.users">
            <field name="partner_id" ref="base.partner_demo"/>
            <field name="login">demo</field>
            <field name="password">demo</field>
            <field name="signature">--
Mr Demo</field>
            <field name="company_id" ref="main_company"/>
            <field name="groups_id" eval="[(6,0,[ref('base.group_user'), ref('base.group_partner_manager')])]"/>
            <field name="image" type="base64" file="base/static/img/user_demo-image.jpg"/>
        </record>
###### 

Python Imaging Library (Fork) 
Version
2.8.1

**Comment by Yenthe666** [comment]
Hi @Karsten-77,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
