### ISSUE TITLE
Not being able to debug qweb with t-debug pdb

### ISSUE THREAD

**Issue by hugoromo** [odoo/odoo#66236]
Impacted versions:
13
Steps to reproduce:
Enable --dev=qweb on console
Insert: 
          <t t-debug="pdb"/>
On a web page.
Current behavior:
Displaying the following error when --dev=qweb is enabled:

`odoo.addons.base.models.qweb.QWebException: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_pack-purchase_1713
  File "<template>", line 2, in body_call_content_1711
  File "<template>", line 2, in body_call_content_1711
  File "/usr/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

Error to render compiling AST
BdbQuit: 
Template: website.pack-purchase
Path: /t/t/t
Node: <t t-debug="pdb"/>`

Expected behavior:
Display list of variables
Video/Screenshot link (optional):

Complete traceback:

`File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 142, in application
return application_unproxied(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1287, in __call__
return self.dispatch(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1257, in __call__
return self.app(environ, start_wrapped)
File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__
return self.app(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1461, in dispatch
response = self.get_response(httprequest, result, explicit_session)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1369, in get_response
result.flatten()
File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
response = super(IrHttp, cls)._handle_exception(exc)
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 621, in _handle_exception
raise e
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 612, in _handle_exception
response = super(IrHttp, cls)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _handle_exception
raise exception
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1369, in get_response
result.flatten()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1236, in flatten
self.response.append(self.render())
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1229, in render
return env["ir.ui.view"].render_template(self.template, self.qcontext)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
return self.browse(self.get_view_id(template)).render(values, engine)
File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 336, in render
return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
return self.env[engine].render(self.id, qcontext)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 58, in render
result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 260, in render
self.compile(template, options)(self, body.append, values or {})
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
return compiled(self, append, new, options, log)
`

Support ticket number submitted via odoo.com/help (optional):

**Comment by hugoromo** [comment]
I forgot to add that I'm using the Docker version, so requirements are completely fulfilled
