### ISSUE TITLE
Odoo Server Error on invoicing lines from a timesheet in hr_timesheet_invoice

### ISSUE THREAD

**Issue by awpeters** [odoo/odoo#6628]
When trying to invoice lines from a timesheet I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_timesheet_invoice/wizard/hr_timesheet_invoice_create.py", line 61, in do_create
    invs = self.pool.get('account.analytic.line').invoice_cost_create(cr, uid, context['active_ids'], data, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_timesheet_invoice/hr_timesheet_invoice.py", line 308, in invoice_cost_create
    journal_type, data, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_timesheet_invoice/hr_timesheet_invoice.py", line 248, in _prepare_cost_invoice_line
    curr_invoice_line['name'] += "\n" + ("\n".join(map(lambda x: unicode(x) or '', note)))
TypeError: unsupported operand type(s) for +=: 'bool' and 'unicode'

**Comment by awpeters** [comment]
The error is caused by having an empty customer_name in hr_timesheet_invoice.factor by adding a space the error goes away.

**Comment by awpeters** [comment]
Accidentally closed this issue.

**Comment by Yenthe666** [comment]
Hi @awpeters,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
