### ISSUE TITLE
[8.0] Neither run scheduler, nor check procurement are working

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#6634]
When I use the Run Schedulers wizard, of the 'Check Procurement'  button in a procurement the call to run_scheduler fails with a message about an unexpected keyword argument 'company_id'. Strange as this keyword argument is defined in the method, and inheriting models use the same parameters.

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/openeyedev/var/projects/oe_intervlag_80/buildout/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/oe_intervlag_80/buildout/parts/odoo/addons/procurement/wizard/schedulers_all.py", line 61, in _procure_calculation_all
    proc_obj.run_scheduler(new_cr, uid, use_new_cursor=True, company_id=comp, context=context)
  File "/home/openeyedev/var/projects/oe_intervlag_80/buildout/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: run_scheduler() got an unexpected keyword argument 'company_id'

**Comment by NL66278** [comment]
By the way, the error is only shown when running odoo from the terminal. Because the code is running in a thread, it seems the normal logging is not used and the error trace is going to stdout or stderr. So when running in daemon mode, the error is going into a black hole.

**Comment by NL66278** [comment]
It seems the error was caused by an override that did not have the company_id keyword argument. I was lead on the wrong track by the error-messages and the return_old_api call at the end of the stack trace.
