### ISSUE TITLE
[V8] Error when you create a Purchase Order from Product

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6644]
**Error when you create a Purchase Order from Product**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. enter in a Product
 2. click on "Purchases" button
 3. enter in a Purchase Order
 4. click on "Create" button
![image](https://cloud.githubusercontent.com/assets/8233008/7560770/61407954-f7c6-11e4-80bc-9305c1704c6f.png)

Current behavior:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/master/openerp/http.py", line 532, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/master/openerp/http.py", line 569, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/master/openerp/http.py", line 305, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/master/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/master/openerp/http.py", line 302, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/master/openerp/http.py", line 807, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/master/openerp/http.py", line 398, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/master/addons/web/controllers/main.py", line 969, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/master/addons/web/controllers/main.py", line 961, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/src/odoo/master/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/master/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/master/openerp/models.py", line 5823, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/master/openerp/models.py", line 5739, in _onchange_eval
    params = eval("[%s]" % params, global_vars, field_vars)
  File "/home/odoo/src/odoo/master/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: "name 'parent' is not defined" while evaluating
"[parent.pricelist_id, product_id, 0, False,                                             parent.partner_id, parent.date_order, parent.fiscal_position, date_planned,                                             name, False, 'draft', True, context]"
```

Expected behavior:

 - Don't allow to create a new Purchase Order. This behaviour is correct in "Sales" button

**Comment by alejandrosantana** [comment]
+1 Tested in demo1.odoo.com
