### ISSUE TITLE
Authentification_ldap installation error

### ISSUE THREAD

**Issue by Noirvent** [odoo/odoo#667]
I just installed the authentificationldap module (users_ldap) (the official one), and the page started to loop-refresh. After a while I got the following error and cannot login anymore

	Client Traceback (most recent call last):
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
		response["result"] = method(self, **self.params)
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 864, in authenticate
		req.session.authenticate(db, login, password, env)
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 115, in authenticate
		uid = self.proxy('common').authenticate(db, login, password, env)
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
		result = self.session.send(self.service_name, method, *args)
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
		raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

	Server Traceback (most recent call last):
	  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
		return openerp.netsvc.dispatch_rpc(service_name, method, args)
	  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 296, in dispatch_rpc
		result = ExportService.getService(service_name).dispatch(method, params)
	  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 433, in dispatch
		return fn(*params)
	  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 444, in exp_authenticate
		res_users = pooler.get_pool(db).get('res.users')
	  File "/usr/lib/pymodules/python2.7/openerp/pooler.py", line 49, in get_pool
		return get_db_and_pool(db_name, force_demo, status, update_module)[1]
	  File "/usr/lib/pymodules/python2.7/openerp/pooler.py", line 33, in get_db_and_pool
		registry = RegistryManager.get(db_name, force_demo, status, update_module)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 203, in get
		update_module)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/registry.py", line 233, in new
		openerp.modules.load_modules(registry.db, force_demo, status, update_module)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 350, in load_modules
		force, status, report, loaded_modules, update_module)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 256, in load_marked_modules
		loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 188, in load_module_graph
		load_data(module_name, idref, mode)
	  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 76, in <lambda>
		load_data = lambda *args: _load_data(cr, *args, kind='data')
	  File "/usr/lib/pymodules/python2.7/openerp/modules/loading.py", line 124, in _load_data
		tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
	  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 959, in convert_xml_import
		obj.parse(doc.getroot())
	  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 852, in parse
		self._tags[rec.tag](self.cr, rec, n)
	  File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 819, in _tag_record
		id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
	  File "/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py", line 971, in _update
		res_id = model_obj.create(cr, uid, values, context=context)
	  File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 4515, in create
		cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
	  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 161, in wrapper
		return f(self, *args, **kwargs)
	  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 226, in execute
		res = self._obj.execute(query, params)
	IntegrityError: insert or update on table "account_chart_template" violates foreign key constraint "account_chart_template_property_account_income_categ_fkey"
	DETAIL:  Key (property_account_income_categ)=(19) is not present in table "account_account_template".

**Comment by Yenthe666** [comment]
Dear @Noirvent,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
