### ISSUE TITLE
Template u'account.view_bank_statement_form' not found

### ISSUE THREAD

**Issue by ChristianPasten** [odoo/odoo#6693]
Dear Team,

I´m having troubles when I try pay an sales envoice, 
When I click on edit boton to pay, the system showme the error showed in follow image; could you help me to solve it. thank a lot!!!

This is the all masage:

OpenERP Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 508, in _handle_exception
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 526, in dispatch
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 285, in _call_function
  File "C:\Program Files (x86)\Odoo8\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 282, in checked_call
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 742, in __call__
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 378, in response_wrap
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\web\controllers\main.py", line 948, in call_kw
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\web\controllers\main.py", line 931, in _call_kw
  File "C:\Program Files (x86)\Odoo8\server.\openerp\http.py", line 844, in proxy
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server.\openerp\models.py", line 3078, in read
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 235, in wrapper
  File "C:\Program Files (x86)\Odoo8\server.\openerp\models.py", line 3110, in read
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 235, in wrapper
  File "C:\Program Files (x86)\Odoo8\server.\openerp\models.py", line 3274, in _read_from_database
  File "C:\Program Files (x86)\Odoo8\server.\openerp\osv\fields.py", line 1356, in get
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\portal_sale\portal_sale.py", line 91, in <lambda>
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\portal_sale\portal_sale.py", line 104, in _portal_payment_block
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\payment\models\payment_acquirer.py", line 298, in render_payment_block
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\payment\models\payment_acquirer.py", line 270, in render
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\base\ir\ir_ui_view.py", line 1007, in render
  File "C:\Program Files (x86)\Odoo8\server.\openerp\api.py", line 237, in wrapper
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\base\ir\ir_qweb.py", line 253, in render
  File "C:\Program Files (x86)\Odoo8\server\openerp\addons\base\ir\ir_qweb.py", line 190, in get_template
QWebTemplateNotFound: Template u'account.view_bank_statement_form' not found

**Comment by Yenthe666** [comment]
Hi @ChristianPasten,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
