### ISSUE TITLE
[14.0 CE] Error on opening a meeting in calender view

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [odoo/odoo#66975]
Impacted versions: 14.0 CE

Steps to reproduce:
- Configure Google Calender properly
- Go to Calender view
- When trying to open a meeting in calender view it throws the error described in "Current Behavious"
- When trying to open a meeting in list view everything works well.

Current behavior:
- When trying to open a meeting in calender view it throws the following error:

Error: QWeb2 - template['CalendarView.event.popover']: Runtime Error: TypeError: dict.widget.isGEventSyncedAndArchivable is not a function
    at Object.exception (https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4384:7)
    at Engine.eval (eval at _render (https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4426:73), <anonymous>:77:29)
    at Engine._render (https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4425:296)
    at Engine.render (https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4425:151)
    at Class.renderElement (https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4940:775)
    at https://mydomain.de/web/content/5369-463f175/web.assets_common.js:4950:6

Expected behavior:
- Opening a meeting in calender view shouldnt give an error and should open it.

Best Regards
Nils

**Comment by NICO-SOLUTIONS** [comment]
Update...
sorry for the early shot.
could not follow the problem in detail but updating the cal-module fixed the problem.
