### ISSUE TITLE
[10.0] Crash in action_assign() of stock.move

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#67251]
Here is the scenario to reproduce the bug on odoo v10.0:

Create a new stockable product X tracked by lot.
Create an inventory for product X lot A quantity 10.
Create a quotation with 2 lines:
1) product X quantity 9
2) product X quantity 15
(in real life, you create 2 lines because these lines have a different discount for example)
Confirm the quotation.
On the related picking: 
1) the stock move with quantity 9 is "Available" 
2) the stock move with quantity 15 is "Waiting availability".
Then, run the procurement scheduler. During the execution of the scheduler, you get this crash:

```
2021-03-04 13:58:52,252 23090 INFO o0_test2 werkzeug: 127.0.0.1 - - [04/Mar/2021 13:58:52] "POST /web/dataset/call_button HTTP/1.1" 200 -
2021-03-04 13:58:52,286 23090 INFO o0_test2 werkzeug: 127.0.0.1 - - [04/Mar/2021 13:58:52] "POST /web/menu/load_needaction HTTP/1.1" 200 -
Exception in thread Thread-255:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alexis/new_boite/dev/odoo0/addons/procurement/wizard/procurement_order_compute_all.py", line 35, in _procure_calculation_all
    Procurement.run_scheduler(use_new_cursor=self._cr.dbname, company_id=company.id)
  File "/home/alexis/new_boite/dev/usability0/stock_usability/procurement.py", line 45, in run_scheduler
    use_new_cursor=use_new_cursor, company_id=company_id)
  File "/home/alexis/new_boite/dev/odoo0/addons/stock/models/procurement.py", line 255, in run_scheduler
    self.env['stock.move'].browse(confirmed_moves.ids[x:x + 100]).action_assign()
  File "/home/alexis/new_boite/dev/odoo0/addons/mrp/models/stock_move.py", line 139, in action_assign
    res = super(StockMove, self).action_assign(no_prepare=no_prepare)
  File "/home/alexis/new_boite/dev/odoo0/addons/stock/models/stock_move.py", line 643, in action_assign
    domain = main_domain[move.id]
KeyError: 50
``` 

Code analysis:
In the picking created by the scenario, there is 1 stock.pack.operation linked to the 2 stock moves via stock_move_operation_link.
In action_assign() of stock.move, there is a loop on stock.pack.operations that contain a loop on the moves linked to that pack operation 

https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_move.py#L623

In this second loop (line 640), it will process not only the confirmed move, but also the move that is already assigned... which trigger the crash. It seems to me that, in this second loop, we should filter out the assigned moves.

I know odoo v10.0 is end of life, but I wanted to create this issue so that it can be found in Google, with the solution.

**Comment by Yenthe666** [comment]
Yeah so as you said V10 is EOL. I propose we close it and Google will index it anyways :) Thnx for documenting it.
