### ISSUE TITLE
Unable to upgrade or use any modules in odoo 13

### ISSUE THREAD

**Issue by GunalanD95** [odoo/odoo#67305]
hi , all i have installed odoo 13 in my system (linux 18.04) with all the core modules , after installation when i try to update module  or upgrade any modules , 
Impacted versions: Odoo 12 
                   

Current behavior:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/fields.py", line 1004, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo_13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.employee(1,).department_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo_13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo_13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo_13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo_13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo_13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo_13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo_13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo_13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo_13/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo_13/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo_13/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo_13/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo_13/addons/hrms_dashboard/models/hrms_dashboard.py", line 135, in get_upcoming
    department = employee.department_id
  File "/odoo/odoo_13/odoo/fields.py", line 2333, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo_13/odoo/fields.py", line 1011, in __get__
    recs._fetch_field(self)
  File "/odoo/odoo_13/odoo/models.py", line 2994, in _fetch_field
    self._read(fnames)
  File "/odoo/odoo_13/addons/hr/models/hr_employee.py", line 131, in _read
    return super(HrEmployeePrivate, self)._read(fields)
  File "/odoo/odoo_13/odoo/models.py", line 3066, in _read
    cr.execute(query_str, params)
  File "/odoo/odoo_13/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo_13/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column hr_employee.blood_grp does not exist
LINE 1: ...oyee"."pan" as "pan","hr_employee"."uan" as "uan","hr_employ...

when i try to select some module menu its showing like below:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/fields.py", line 1004, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo_13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).employee_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/fields.py", line 1004, in __get__
    value = env.cache.get(record, self)
  File "/odoo/odoo_13/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.employee(1,).active', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo_13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo_13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo_13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo_13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo_13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo_13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo_13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo_13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo_13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo_13/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo_13/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo_13/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo_13/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo_13/addons/hr_holidays/models/hr_leave_type.py", line 244, in get_days_all_request
    leave_types = sorted(self.search([]).filtered(lambda x: x.virtual_remaining_leaves or x.max_leaves), key=self._model_sorting_key, reverse=True)
  File "/odoo/odoo_13/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo_13/addons/hr_holidays/models/hr_leave_type.py", line 339, in _search
    employee_id = self._get_contextual_employee_id()
  File "/odoo/odoo_13/addons/hr_holidays/models/hr_leave_type.py", line 260, in _get_contextual_employee_id
    employee_id = self.env.user.employee_id.id
  File "/odoo/odoo_13/odoo/fields.py", line 2333, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo_13/odoo/fields.py", line 1028, in __get__
    self.compute_value(recs)
  File "/odoo/odoo_13/odoo/fields.py", line 1113, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo_13/odoo/models.py", line 4003, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo_13/addons/hr/models/res_users.py", line 198, in _compute_company_employee
    user.employee_id = self.env['hr.employee'].search([('id', 'in', user.employee_ids.ids), ('company_id', '=', self.env.company.id)], limit=1)
  File "/odoo/odoo_13/odoo/fields.py", line 2968, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo_13/odoo/fields.py", line 2333, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo_13/odoo/fields.py", line 1056, in __get__
    return self.convert_to_record(value, record)
  File "/odoo/odoo_13/odoo/fields.py", line 2795, in convert_to_record
    corecords = corecords.filtered('active').with_prefetch(prefetch_ids)
  File "/odoo/odoo_13/odoo/models.py", line 5344, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/odoo/odoo_13/odoo/models.py", line 5344, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/odoo/odoo_13/odoo/models.py", line 5343, in <lambda>
    func = lambda rec: any(rec.mapped(name))
  File "/odoo/odoo_13/odoo/models.py", line 5307, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/odoo/odoo_13/odoo/models.py", line 5266, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/odoo/odoo_13/odoo/models.py", line 5266, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/odoo/odoo_13/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo_13/odoo/fields.py", line 1011, in __get__
    recs._fetch_field(self)
  File "/odoo/odoo_13/odoo/models.py", line 2994, in _fetch_field
    self._read(fnames)
  File "/odoo/odoo_13/addons/hr/models/hr_employee.py", line 131, in _read
    return super(HrEmployeePrivate, self)._read(fields)
  File "/odoo/odoo_13/odoo/models.py", line 3066, in _read
    cr.execute(query_str, params)
  File "/odoo/odoo_13/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo_13/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column hr_employee.blood_grp does not exist
LINE 1: ...oyee"."pan" as "pan","hr_employee"."uan" as "uan","hr_employ...
                                                             ^
                                                             ^

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
