### ISSUE TITLE
Unittests fail if admin password changed

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6766]
When I tried running unittests with option `--test-enable`, I got this error (below). It shows that bad login or password was used. And it seems that Odoo tries to use default password, which is `admin`. But I actually changed that password. 

So can you only run unittests, when `admin` user password is `admin`? Or do I need to specify somewhere that its password is changed? Or is it a bug and this should not happen at all?

P.S. When I changed password back to `admin`, it passed without these errors.

```
2015-05-19 11:30:50,602 2238 INFO db_name openerp.addons.base.res.res_users: Login failed for db:db_name login:admin
2015-05-19 11:30:50,603 2238 INFO db_name openerp.service.common: bad login or password from 'admin' using database 'db_name'
2015-05-19 11:30:50,603 2238 INFO db_name werkzeug: 127.0.0.1 - - [19/May/2015 11:30:50] "POST /xmlrpc/2/common HTTP/1.1" 200 -
2015-05-19 11:30:50,605 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: FAIL
2015-05-19 11:30:50,606 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc: test_xmlrpc_ir_model_search (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-05-19 11:30:50,606 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2015-05-19 11:30:50,824 2238 INFO db_name werkzeug: 127.0.0.1 - - [19/May/2015 11:30:50] "POST /xmlrpc/2/object HTTP/1.1" 200 -
2015-05-19 11:30:50,827 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ERROR
2015-05-19 11:30:50,828 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc: ======================================================================
2015-05-19 11:30:50,828 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ERROR: test_xmlrpc_ir_model_search (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: Traceback (most recent call last):
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/home/oerp/openerp80/odoo/openerp/addons/base/tests/test_xmlrpc.py", line 18, in test_xmlrpc_ir_model_search
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     ids = o.execute(DB, 1, 'admin', 'ir.model', 'search', [])
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 1225, in __call__
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     return self.__send(self.__name, args)
2015-05-19 11:30:50,829 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 1579, in __request
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     verbose=self.__verbose
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 1265, in request
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     return self.single_request(host, handler, request_body, verbose)
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 1298, in single_request
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     return self.parse_response(response)
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 1474, in parse_response
2015-05-19 11:30:50,830 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     return u.close()
2015-05-19 11:30:50,831 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
2015-05-19 11:30:50,831 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     raise Fault(**self._stack[0])
2015-05-19 11:30:50,831 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ` Fault: <Fault 3: 'Access denied.'>
2015-05-19 11:30:50,831 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc: ======================================================================
2015-05-19 11:30:50,831 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: FAIL: test_01_xmlrpc_login (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-05-19 11:30:50,831 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ` Try to login on the common service.
2015-05-19 11:30:50,832 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: Traceback (most recent call last):
2015-05-19 11:30:50,832 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `   File "/home/oerp/openerp80/odoo/openerp/addons/base/tests/test_xmlrpc.py", line 13, in test_01_xmlrpc_login
2015-05-19 11:30:50,832 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: `     self.assertEqual(uid, 1)
2015-05-19 11:30:50,832 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: ` AssertionError: False != 1
2015-05-19 11:30:50,832 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc: Ran 2 tests in 0.481s
2015-05-19 11:30:50,833 2238 ERROR db_name openerp.addons.base.tests.test_xmlrpc: FAILED
2015-05-19 11:30:50,833 2238 INFO db_name openerp.addons.base.tests.test_xmlrpc:  (failures=1, errors=1)
2015-05-19 11:30:50,833 2238 ERROR db_name openerp.modules.module: Module base: 1 failures, 1 errors
2015-05-19 11:30:50,844 2238 INFO db_name openerp.modules.module: openerp.addons.report.tests.test_reports running tests.
```

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
