### ISSUE TITLE
[8.0] [BUG] ProgrammingError on read for forum.tag

### ISSUE THREAD

**Issue by isabellerichard** [odoo/odoo#6770]
I installed module _website_forum_ with the last version of Odoo 8.0.
When I try to read on model `forum.tag`, I have an error.

Here are the methods I call:

```
tag_ids = sock.execute('demo', uid, pwd, 'forum.tag', 'search', [])
sock.execute('demo', uid, pwd, 'forum.tag', 'read', tag_ids, [])
```

Here are the logs of Odoo:

```
2015-05-19 13:51:10,557 32436 ERROR demo openerp.sql_db: Programming error: column forum_tag_rel.post_id does not exist
LINE 1: SELECT forum_tag_rel.post_id, forum_tag_rel.tag_id          ...
               ^
, in query SELECT forum_tag_rel.post_id, forum_tag_rel.tag_id                    FROM forum_tag_rel, "forum_post"                   WHERE forum_tag_rel.tag_id IN %s                     AND forum_tag_rel.post_id = forum_post.id                   AND ("forum_post"."active" = %s)                    ORDER BY "forum_post".is_correct DESC                                    OFFSET 0
2015-05-19 13:51:10,558 32436 ERROR demo openerp.http: column forum_tag_rel.post_id does not exist
LINE 1: SELECT forum_tag_rel.post_id, forum_tag_rel.tag_id          ...
               ^
Traceback (most recent call last):
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/isabelle/workspace/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, *params)
  File "/home/isabelle/workspace/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/service/model.py", line 170, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/isabelle/workspace/odoo/openerp/service/model.py", line 159, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 3352, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/isabelle/workspace/odoo/openerp/osv/fields.py", line 1001, in get
    cr.execute(query, [tuple(ids),] + where_params)
  File "/home/isabelle/workspace/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column forum_tag_rel.post_id does not exist
LINE 1: SELECT forum_tag_rel.post_id, forum_tag_rel.tag_id          ...
               ^
```

**Comment by Yenthe666** [comment]
Hi @isabellerichard,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
