### ISSUE TITLE
TypeError: scope.sprintf is not a function

### ISSUE THREAD

**Issue by l9-fstaske** [odoo/odoo#67801]
I just made an update about the Odoo nightly Debian repo.
After that I get the following error with almost all apps:
TypeError: scope.sprintf is not a function
    at QWeb.eval (eval at _compile (http://192.168.200.222:8069/web/content/114-b084f22/web.assets_common.js:970:178), <anonymous>:16:32)
    at QWeb.eval (eval at _compile (http://192.168.200.222:8069/web/content/114-b084f22/web.assets_common.js:970:178), <anonymous>:396:48)
    at QWeb.render (http://192.168.200.222:8069/web/content/114-b084f22/web.assets_common.js:959:20)
    at Object.__owl__.renderFn (http://192.168.200.222:8069/web/content/122-fdabd09/web.assets_backend.js:1326:147)
    at PatchableClass.__render (http://192.168.200.222:8069/web/content/114-b084f22/web.assets_common.js:1276:33)
    at PatchableClass.__prepareAndRender (http://192.168.200.222:8069/web/content/114-b084f22/web.assets_common.js:1274:29)

**Comment by adriantonatiu** [comment]
Hi rrakso, same here :(

**Comment by Yenthe666** [comment]
@d-fence maybe something you missed?

**Comment by d-fence** [comment]
I cannot reproduce. Can you give detailed steps on how to reproduce ?

**Comment by adriantonatiu** [comment]
Hi @d-fence for me this was the steps:

1. sudo apt-get update
2. sudo apt-get upgrade -y
3. login on odoo and navigate to any module

Now I can solve the problem by:

1. sudo service odoo stop
2. sudo su odoo -s /bin/bash
3. odoo -c /etc/odoo/odoo.conf -d "Here_database_name_with_out_quotation_marks" -u base
4. wait until the log shows the update is finished
5. CTRL+C
6. exit
7. sudo service odoo start

Best regards

**Comment by reyesruiz** [comment]
Would this be related? I was able to reproduce the same issue in an Ubuntu 20.04 installation.

https://github.com/odoo/odoo/issues/68040#issuecomment-804426532

After I changed the two lines that has sprintf back to previous commit, error went away.

**Comment by GregaVavtar** [comment]
I also have this issue with the new update of odoo v14.

**Comment by adriantonatiu** [comment]
Hi @GregaVavtar did you try this?
https://github.com/odoo/odoo/issues/67801#issuecomment-804139971

**Comment by reyesruiz** [comment]
Try editing the following file:
`sudo vi /usr/lib/python3/dist-packages/odoo/addons/web/static/src/xml/base.xml`

Search for _sprintf_

Replace 
```
t-att-aria-label="sprintf(buttonLabel.toString(), view.type)"
t-att-title="sprintf(buttonLabel.toString(), view.type)"
```
with
```
t-attf-aria-label="View {{ view.type }}"
t-attf-title="View {{ view.type }}"
```
restart odoo if using systemctl
`sudo systemctl restart odoo`

or using service
`sudo service odoo restart`

Refresh or open a new odoo webpage.

You have to do this every time you update to a newer odoo version, until a permanent fix if found.

**Comment by GregaVavtar** [comment]
> Hi @d-fence for me this was the steps:
> 
> 1. sudo apt-get update
> 2. sudo apt-get upgrade -y
> 3. login on odoo and navigate to any module
> 
> Now I can solve the problem by:
> 
> 1. sudo service odoo stop
> 2. sudo su odoo -s /bin/bash
> 3. odoo -c /etc/odoo/odoo.conf -d "Here_database_name_with_out_quotation_marks" -u base
> 4. wait until the log shows the update is finished
> 5. CTRL+C
> 6. exit
> 7. sudo service odoo start
> 
> Best regards

No, this one is not working

**Comment by GregaVavtar** [comment]
> Try editing the following file:
> `sudo vi /usr/lib/python3/dist-packages/odoo/addons/web/static/src/xml/base.xml`
> 
> Search for _sprintf_
> 
> Replace
> 
> ```
> t-att-aria-label="sprintf(buttonLabel.toString(), view.type)"
> t-att-title="sprintf(buttonLabel.toString(), view.type)"
> ```
> 
> with
> 
> ```
> t-attf-aria-label="View {{ view.type }}"
> t-attf-title="View {{ view.type }}"
> ```
> 
> restart odoo if using systemctl
> `sudo systemctl restart odoo`
> 
> or using service
> `sudo service odoo restart`
> 
> Refresh or open a new odoo webpage.
> 
> You have to do this every time you update to a newer odoo version, until a permanent fix if found.

This one is working!

Tnx.

**Comment by mhabboush97** [comment]
I also faced this issue with docker deployment, any idea what is happening??

**Comment by eguane** [comment]
Same problem, with debian package upgrade.
67801# solve the problem only with linux os,  with Windows 10  OS and multiple browser (firefox, chrome, edge), impossible to navigate with list view  1 - 80 < >  , and impossible to remove filter  X .

**Comment by eguane** [comment]
update web module in application seems ok for myself.

**Comment by dacopan** [comment]
same error in docker

**Comment by Kilhog** [comment]
same error ...

**Comment by awgrass** [comment]
Same error here, I am running the newest odoo 14 version (Odoo 14.0-20220520)
I would love to see a fix!

**Comment by Vampouille** [comment]
Each time my odoo package is updated I have to patch the `base.xml. Is there a way to include this patch in next updates ?

**Comment by serranomorante** [comment]
This [comment](https://github.com/odoo/odoo/issues/67801#issuecomment-805389867) was helpful but I still experienced some issues.
I would add [this link](https://www.odoo.com/forum/help-1/an-error-occured-197541) that apparently completely fixes the issue. I think in the end the solution for me was to click "Regenerate Asset Bundles".
