### ISSUE TITLE
Key Error : u 'pin' 

### ISSUE THREAD

**Issue by SavanTripathi** [odoo/odoo#6786]
Hello,
      Currently I am dealing with Accounting module in odoo 8.0. I made few customers and now i want to make customer invoice. While I am clicking on Create Customer invoice, form view is there and when I am clicking on selection box (many 2 one field) for selecting particular customer, traceback is provided by server, which is displayed below.
![invoice](https://cloud.githubusercontent.com/assets/9957916/7726195/f257a7ce-ff1d-11e4-9645-cf5d4eab3be0.png)

Odoo Server Error

Traceback (most recent call last):
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/addons/base/res/res_partner.py", line 699, in name_search
    return super(res_partner,self).name_search(cr, uid, name, args, operator=operator, context=context, limit=limit)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/models.py", line 1732, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/models.py", line 1745, in _name_search
    res = self.name_get(cr, access_rights_uid, ids, context)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/addons/base/res/res_partner.py", line 611, in name_get
    name = name + "\n" + self._display_address(cr, uid, record, without_company=True, context=context)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/ec2-user/odoo/odoo-8.0/openerp/addons/base/res/res_partner.py", line 815, in _display_address
    return address_format % args
KeyError: u'pin'

So provide me some solution or guidelines for this issue

**Comment by Yenthe666** [comment]
Hi @SavanTripathi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
