### ISSUE TITLE
Web page is not available in odoo 8

### ISSUE THREAD

**Issue by gemchand** [odoo/odoo#6809]
Log file /var/log/odoo/odoo-server.log shows

 return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 298, in close
    return self._close(False)
  File "/opt/odoo/openerp/sql_db.py", line 328, in _close
    self._cnx.rollback()
InterfaceError: connection already closed
2015-05-22 03:53:53,116 1121 INFO ? openerp.service.server: Initiating shutdown
2015-05-22 03:53:53,117 1121 INFO ? openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2015-05-22 03:54:04,858 24909 ERROR odoo openerp.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

2015-05-22 03:54:33,647 24909 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-05-22 03:54:33,648 24909 ERROR ? openerp.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

2015-05-22 03:54:33,648 24909 ERROR ? openerp.addons.bus.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/addons/bus/bus.py", line 136, in run
    self.loop()
  File "/opt/odoo/addons/bus/bus.py", line 114, in loop
    with openerp.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/openerp/sql_db.py", line 575, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/openerp/sql_db.py", line 181, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/openerp/sql_db.py", line 464, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

2015-05-22 03:55:23,698 24909 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres

how to fix this error

Thank you

**Comment by sle-odoo** [comment]
Closing as it is a deployment issue, Odoo cannot contact your postgres server.
Regards
