### ISSUE TITLE
Module README.rst file title problem

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6811]
## Summary

Trying to load a pair of modules which have README.rst files, they raised an error related to an unexpected title section in it.
Basically

## Steps to reproduce:

- Add a module with README.rst with at least two "="-underlined titles.
- Try to install or update it.

## Current behaviour:

- It looks Odoo only accepts only 1 title underlined with "=", but several with "-".
- When trying to install or update, it raises the error below.
- If error happens anytime, even if you modify the README.rst file to have only one "="-underlined title, it keeps failing in updated attempts.
- To be able to update, you have to uninstall and install again (which may have undesired effects).
- And even then, you cannot update any more, but uninstall+install.

```
Traceback (most recent call last):
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 537, in button_immediate_upgrade
    return self._button_immediate_function(cr, uid, ids, self.button_upgrade, context=context)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 494, in _button_immediate_function
    function(cr, uid, ids, context=context)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 542, in button_upgrade
    self.update_list(cr, uid)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 647, in update_list
    self._update_category(cr, uid, mod, terp.get('category', 'Uncategorized'))
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 768, in _update_category
    mod_browse.write({'category_id': cat_id})
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/auditlog/models/rule.py", line 262, in write
    (d['id'], d) for d in self.sudo().read(list(self._columns)))
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/models.py", line 3352, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/mnt/workZone/odoo/odoo_8_devel_mountain/src/odoo/openerp/osv/fields.py", line 1466, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/odoo_8_devel_mountain/src/linked-addons/base/module/module.py", line 186, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 1136, in indent
    elements = self.block_quote(indented, line_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 1151, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2721, in underline
    source=src, line=srcline)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
SystemMessage: <string>:19: (SEVERE/4) Unexpected section title.

Usage
=====
```

## Expected behaviour:

- Allow any title hierarchy.
- Even better, allow also Markdown, so it could be a README.md, like usual in Github.

**Comment by xmo-odoo** [comment]
> It looks Odoo only accepts only 1 title underlined with "=", but several with "-".

It has nothing to do with Odoo, or the specific underlining character. Docutils/ReStructuredText only allows a single primary title for a given document.

> Allow any title hierarchy.

http://docutils.sourceforge.net/BUGS.html

**Comment by xmo-odoo** [comment]
> As far as I know, it has nothing to do with Odoo, or the specific underlining character. Docutils/ReStructuredText only allows a single primary title for a given document.

After further research, this looks to be a mistake, rst2html is able to build documents with multiple "top-level" titles, so this should be possible somehow.

**Comment by pedrobaeza** [comment]
We are using multiple top-level titles without problems in all OCA modules (for example, https://raw.githubusercontent.com/OCA/l10n-spain/8.0/l10n_es/README.rst) and we haven't seen this problem. Are you sure you have ended correctly previous sections?

**Comment by alejandrosantana** [comment]
@pedrobaeza You were right (as usual). I have tested it, deleted and rewritten the problematic part and problem is solved. It should have been some non-visible character I missed (these are hard to catch if you do not count on them).

@xmo-odoo I close this, sorry for the noise.
