### ISSUE TITLE
[13.0][14.0][MRP] Issue in BOM structure when Component product has a BOM and the component quantity is zero

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#68125]
**Impacted versions:**
V13 and V14 

**Steps to reproduce:**

- Add a component **product B** to the Bom of **Product A**.  Product B has already have a bom. 
- Quantity of Product B is zero in the BOM of product A.
- Then take the BOM Structure of product A and unfold product B

**Current behavior:**

![bom_error_qty_1](https://user-images.githubusercontent.com/62367855/111740762-50b8b700-88ab-11eb-8c5e-6baa7eaa82d0.gif)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/addons/mrp/report/mrp_report_bom_structure.py", line 52, in get_bom
    lines = self._get_bom(bom_id=bom_id, product_id=product_id, line_qty=line_qty, line_id=line_id, level=level)
  File "/home/odoo/src/odoo/14.0/addons/mrp/report/mrp_report_bom_structure.py", line 97, in _get_bom
    bom_quantity = current_line.product_uom_id._compute_quantity(line_qty, bom.product_uom_id)
  File "/home/odoo/src/odoo/14.0/addons/uom/models/uom_uom.py", line 152, in _compute_quantity
    amount = qty / self.factor
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by hajajroshan** [comment]
@pedrobaeza Can you mention related people to check the PR  #68132 against this issue.

**Comment by pedrobaeza** [comment]
Closing as there's a PR. If this happens in 13 as well, you should do the CLA and PR to 13, not 14.
