### ISSUE TITLE
web page is not open in odoo

### ISSUE THREAD

**Issue by gemchand** [odoo/odoo#6814]
when we closed the browser and then hit url for odoo..odoo server is down that means odoo connection refused by postgresql
 Log file:  /var/log/odoo/odoo-server.log

```
self._cnx = pool.borrow(dsn)
```

  File "/opt/odoo/openerp/sql_db.py", line 464, in _locked
    return fun(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

2015-05-22 09:35:46,491 23109 ERROR ? openerp.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/**init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

2015-05-22 09:35:46,491 23109 ERROR ? openerp.addons.bus.bus: Bus.loop error, sleep and retry
Traceback (most recent call last):
  File "/opt/odoo/addons/bus/bus.py", line 136, in run
    self.loop()
  File "/opt/odoo/addons/bus/bus.py", line 114, in loop
    with openerp.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo/openerp/sql_db.py", line 575, in cursor
    return Cursor(self.**pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/openerp/sql_db.py", line 181, in __init**
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/openerp/sql_db.py", line 464, in _locked
    return fun(self, _args, *_kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 526, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/home/odoo/odoo/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

How to fix this error
Thank you

**Comment by gemchand** [comment]
How to fix this error

thank you

**Comment by Yenthe666** [comment]
Hi @gemchand,

This issue was with the `postgreSQL` not being available / up and running. This is an installation issue.
This is now explained in the documentation at https://www.odoo.com/documentation/11.0/setup/install.html
