### ISSUE TITLE
[8.0] Context is not defined in attrs

### ISSUE THREAD

**Issue by isabellerichard** [odoo/odoo#6830]
**Context is not defined in attrs**

Impacted versions:
- 8.0

With server version of May 18, I could check values from context inside attrs. 
With server version of May 23, I can't do it anymore, I have the following error:

```
2015-05-23 19:10:25,195 18144 ERROR demo80 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/home/isabelle/workspace/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/home/isabelle/workspace/odoo/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/isabelle/workspace/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/isabelle/workspace/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/isabelle/workspace/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/isabelle/workspace/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/isabelle/workspace/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/isabelle/workspace/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/isabelle/workspace/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/isabelle/workspace/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/isabelle/workspace/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/isabelle/workspace/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 4265, in _create
    recs._validate_fields(vals)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/isabelle/workspace/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
"name 'context' is not defined" while evaluating
"{'invisible': ['|', ('id', '=', context.get('SUPERUSER_ID')), ('user_profile', '=', True)], 'required': [('user_profile', '!=', True)]}"" while parsing /home/isabelle/workspace/custom_addons/my_module/views/res_users_view.xml:7, near
```

**Comment by soygabriel** [comment]
Have you being able to solve it I have same problem.

**Comment by isabellerichard** [comment]
Hello, 

No, I had to completely rewrite my view to bypass the usage of context in attrs.

**Comment by nono6677** [comment]
Hi,
After a git pull i have the same problem.
I think this problem need fixed.

**Comment by vish-sk** [comment]
Hi,

I have the same issue.

Any updates on this ? got fixed ?

**Comment by dcorio** [comment]
looks like context has been removed from the variables that attrs has access to. this was working with an early release of odoo 8.0

**Comment by flotho** [comment]
@dcorio , sad news

**Comment by Yenthe666** [comment]
Hi @isabellerichard,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
