### ISSUE TITLE
[14.0][14.3]Python 3.8.5 : Error to render compiling AST

### ISSUE THREAD

**Issue by kamarya** [odoo/odoo#68608]
This issue seems to be a regression of  #55305 and/or #59630 or another Python 3.8 compatibility issue that is happening in a different place. 
Impacted versions:
 - 14.0
 - master branch 14.3 (commit 5dee24c670f3729db72a9fa8f18c2c5e7938a29f)

Steps to reproduce:
start a fresh Odoo installation and go to `/web/database/selector` to initialize a demo or empty database.
Current behavior:
"500 Internal Server Error" right after filling the initialization form (regardless of what has been filled in) and pressing "Create database"
Expected behavior:
initialize the database and pop up the Odoo web interface on the browser 
Video/Screenshot link (optional):
```
[  978.070918] odoo[495]: 2021-03-31 14:02:10,254 495 ERROR odoo_db werkzeug: Error on request:
[  978.071324] odoo[495]: Traceback (most recent call last):
[  978.071587] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 238, in _dispatch
[  978.071841] odoo[495]:     result = request.dispatch()
[  978.072145] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 806, in dispatch
[  978.072413] odoo[495]:     r = self._call_function(**self.params)
[  978.072674] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 359, in _call_function
[  978.072972] odoo[495]:     return checked_call(self.db, *args, **kwargs)
[  978.073225] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/service/model.py", line 94, in wrapper
[  978.073483] odoo[495]:     return f(dbname, *args, **kwargs)
[  978.073729] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 350, in checked_call
[  978.073974] odoo[495]:     result.flatten()
[  978.074218] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 1242, in flatten
[  978.074461] odoo[495]:     self.response.append(self.render())
[  978.074703] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 1235, in render
[  978.074967] odoo[495]:     return env["ir.ui.view"]._render_template(self.template, self.qcontext)
[  978.075212] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 1708, in _render_template
[  978.075457] odoo[495]:     return self.browse(self.get_view_id(template))._render(values, engine)
[  978.075699] odoo[495]:   File "/home/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
[  978.075941] odoo[495]:     return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
[  978.076222] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 1716, in _render
[  978.076466] odoo[495]:     return self.env[engine]._render(self.id, qcontext)
[  978.076708] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_qweb.py", line 55, in _render
[  978.076970] odoo[495]:     result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
[  978.077214] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/qweb.py", line 260, in _render
[  978.077461] odoo[495]:     self.compile(template, options)(self, body.append, values)
[  978.077703] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/qweb.py", line 343, in _compiled_fn
[  978.078008] odoo[495]:     raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
[  978.078253] odoo[495]: Exception
[  978.078493] odoo[495]: The above exception was the direct cause of the following exception:
[  978.078760] odoo[495]: Traceback (most recent call last):
[  978.079003] odoo[495]:   File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
[  978.079243] odoo[495]:     execute(self.server.app)
[  978.079483] odoo[495]:   File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
[  978.079729] odoo[495]:     application_iter = app(environ, start_response)
[  978.079971] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/service/server.py", line 475, in app
[  978.080269] odoo[495]:     return self.app(e, s)
[  978.080514] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/service/wsgi_server.py", line 124, in application
[  978.080774] odoo[495]:     return application_unproxied(environ, start_response)
[  978.081022] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/service/wsgi_server.py", line 99, in application_unproxied
[  978.081265] odoo[495]:     result = odoo.http.root(environ, start_response)
[  978.081507] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 1299, in __call__
[  978.081748] odoo[495]:     return self.dispatch(environ, start_response)
[  978.081987] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 1267, in __call__
[  978.420388] odoo[495]:     return self.app(environ, start_wrapped)
[  978.420697] odoo[495]:   File "/usr/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
[  978.420982] odoo[495]:     return self.app(environ, start_response)
[  978.421232] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 1472, in dispatch
[  978.421489] odoo[495]:     result = ir_http._dispatch()
[  978.421735] odoo[495]:   File "/home/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
[  978.421979] odoo[495]:     return super(IrHttp, cls)._dispatch()
[  978.422240] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 242, in _dispatch
[  978.422491] odoo[495]:     return cls._handle_exception(e)
[  978.422734] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 210, in _handle_exception
[  978.423005] odoo[495]:     return request._handle_exception(exception)
[  978.423250] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 744, in _handle_exception
[  978.423506] odoo[495]:     return super(HttpRequest, self)._handle_exception(exception)
[  978.423897] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/http.py", line 315, in _handle_exception
[  978.424209] odoo[495]:     raise exception.with_traceback(None) from new_cause
[  978.424458] odoo[495]: odoo.addons.base.models.qweb.QWebException: Document is empty
[  978.424707] odoo[495]: Traceback (most recent call last):
[  978.424963] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/cache.py", line 85, in lookup
[  978.425227] odoo[495]:     r = d[key]
[  978.425472] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/func.py", line 71, in wrapper
[  978.425723] odoo[495]:     return func(self, *args, **kwargs)
[  978.425964] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/lru.py", line 34, in __getitem__
[  978.426210] odoo[495]:     a = self.d[obj]
[  978.426468] odoo[495]: KeyError: ('ir.qweb', <function IrQWeb._generate_asset_nodes_cache at 0x7f955863a0>, 'web.assets_common', 'en_US', True, False, '', False, False, False, (None,))
[  978.426719] odoo[495]: During handling of the above exception, another exception occurred:
[  978.426964] odoo[495]: Traceback (most recent call last):
[  978.427231] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/cache.py", line 85, in lookup
[  978.427470] odoo[495]:     r = d[key]
[  978.427748] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/func.py", line 71, in wrapper
[  978.427987] odoo[495]:     return func(self, *args, **kwargs)
[  978.428265] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/lru.py", line 34, in __getitem__
[  978.428515] odoo[495]:     a = self.d[obj]
[  978.428755] odoo[495]: KeyError: ('ir.qweb', <function IrQWeb._get_asset_content at 0x7f95586670>, 'web.assets_common', 'en_US', (None,))
[  978.429003] odoo[495]: During handling of the above exception, another exception occurred:
[  978.429254] odoo[495]: Traceback (most recent call last):
[  978.429510] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/qweb.py", line 336, in _compiled_fn
[  978.429752] odoo[495]:     return compiled(self, append, new, options, log)
[  978.430006] odoo[495]:   File "<template>", line 1, in template_web_webclient_bootstrap_41
[  978.430247] odoo[495]:   File "<template>", line 2, in body_call_content_39
[  978.430486] odoo[495]:   File "<template>", line 3, in set_38
[  978.430737] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_qweb.py", line 295, in _get_asset_nodes
[  978.430980] odoo[495]:     return self._generate_asset_nodes_cache(xmlid, options, css, js, debug, async_load, defer_load, lazy_load, values)
[  978.431245] odoo[495]:   File "<decorator-gen-66>", line 2, in _generate_asset_nodes_cache
[  978.770004] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/cache.py", line 90, in lookup
[  978.770263] odoo[495]:     value = d[key] = self.method(*args, **kwargs)
[  978.770521] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_qweb.py", line 304, in _generate_asset_nodes_cache
[  978.770768] odoo[495]:     return self._generate_asset_nodes(xmlid, options, css, js, debug, async_load, defer_load, lazy_load, values)
[  978.771013] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_qweb.py", line 307, in _generate_asset_nodes
[  978.771267] odoo[495]:     files, remains = self._get_asset_content(xmlid, options)
[  978.771510] odoo[495]:   File "<decorator-gen-67>", line 2, in _get_asset_content
[  978.771781] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/tools/cache.py", line 90, in lookup
[  978.772078] odoo[495]:     value = d[key] = self.method(*args, **kwargs)
[  978.772327] odoo[495]:   File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_qweb.py", line 341, in _get_asset_content
[  978.772582] odoo[495]:     for el in html.fragments_fromstring(template):
[  978.772824] odoo[495]:   File "/usr/lib/python3.8/site-packages/lxml/html/__init__.py", line 794, in fragments_fromstring
[  978.773066] odoo[495]:     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
[  978.773318] odoo[495]:   File "/usr/lib/python3.8/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
[  978.773560] odoo[495]:     raise etree.ParserError(
[  978.773814] odoo[495]: lxml.etree.ParserError: Document is empty
[  978.774066] odoo[495]: Error to render compiling AST
[  978.774341] odoo[495]: ParserError: Document is empty
[  978.774609] odoo[495]: Template: web.webclient_bootstrap
[  978.774861] odoo[495]: Path: /t/t/t[1]/t[1]
[  978.775102] odoo[495]: Node: <t t-call-assets="web.assets_common" t-js="false"/> - - -
[  978.775360] odoo[495]: 2021-03-31 14:02:10,369 495 INFO odoo_db werkzeug: 192.168.10.1 - - [31/Mar/2021 14:02:10] "GET /favicon.ico HTTP/1.1" 404 - 2 0.002 0.012
[  986.652980] odoo[495]: 2021-03-31 14:02:18,834 495 INFO odoo_db odoo.addons.base.models.ir_attachment: filestore gc 56 checked, 2 removed
[  986.905330] odoo[495]: 2021-03-31 14:02:19,088 495 INFO odoo_db odoo.addons.base.models.res_users: GC'd 0 user log entries

```
Support ticket number submitted via odoo.com/help (optional):

**Comment by kamarya** [comment]
@d-fence this might interest you.

**Comment by kamarya** [comment]
can you give me some info about this  @xmo-odoo @d-fence @odony @nla-odoo ? the cause and how to fix it?

**Comment by Yenthe666** [comment]
I setup a new Odoo 14 yesterday on P3.8 without any issues 🤔

**Comment by kamarya** [comment]
@Yenthe666 I wonder why this could happen...it requires an Odoo developer insight cause it is heavily bound to the techniques that are used in Odoo.

**Comment by d-fence** [comment]
I cannot reproduce the bug. Can you give more information on your setup ?
I tested with python 3.8.5 and `requirements.txt` properly installed.

**Comment by xmo-odoo** [comment]
Likewise tried reproducing in a 3.8.5, using the latest 14.0 code, with a fresh install of all dependencies. No error when creating a database through the database selector, whether creating the new database with or without demo data.

Not sure what to even ask about, except checking that your dependency versions match the requirements maybe if you're using that, otherwise what your distro is: for distro-installed package, technically speaking we only ensure things work properly for Debian and Ubuntu, and maybe redhat as well (@d-fence do you confirm?)

**Comment by d-fence** [comment]
I confirm that a simple installation of distro packages are automatically tested nightly for Debian and Fedora.
14.0 is tested against [Fedora 32](https://github.com/odoo/odoo/blob/0b8d79f65dc96d30fc4737362d3e05e103b281bb/setup/package.dffedora#L3) and [Debian Buster](https://github.com/odoo/odoo/blob/0b8d79f65dc96d30fc4737362d3e05e103b281bb/setup/package.dfdebian#L3)

**Comment by kamarya** [comment]
Here is my dependencies (more recent version w.r.t. requirements.txt) however the exception does not seem to be related to the auxiliary libraries except `lxml`

```
python3-ebaysdk_2.1.5
python3-mako_1.0.7
python3-pyparsing_2.4.7
python3-six_1.15.0
python3-feedparser_6.0.2
python3-markupsafe_1.1.0
python3-pypdf2_1.26.0
python3-stdnum_1.8
python3-appdirs_1.4.4
python3-freezegun_1.1.0
python3-markupsafe_1.1.1
python3-pyserial_3.4
python3-urllib3_1.26.4
python3-attrs_20.3.0
python3-num2words_0.5.6
python3-babel_2.6.0
python3-gevent_21.1.2
python3-ofxparse_0.19
python3-pytz_2021.1
python3-vobject_0.9.6.1
python3-cached-property_1.5.2
python3-greenlet_1.0.0
python3-passlib_1.7.1
python3-pyusb_1.0.2
python3-werkzeug_0.16.1
python3-certifi_2020.12.5
python3-html2text_2018.1.9
python3-passlib_1.7.4
python3-qrcode_6.1
python3-werkzeug_1.0.1
python3-chardet_3.0.4
python3-xlrd_2.0.1
python3-chardet_4.0.0
python3-idna_3.1
python3-pillow_8.1.2
python3-reportlab_3.5.66
python3-dateutil_2.7.3
python3-isodate_0.6.0
python3-polib_1.1.0
python3-requests_2.21.0
python3-xlsxwriter_1.3.8
python3-dateutil_2.8.1
python3-jinja2_2.11.3
python3-psutil_5.6.6
python3-requests_2.25.1
python3-xlwt_1.3.0
python3-decorator_4.3.0
python3-ldap_3.3.1
python3-requests-toolbelt_0.9.1
python3-zeep_3.2.0
python3-defusedxml_0.7.1
python3-libsass_0.17.0
python3-psycopg2_2.8.6
python3-setuptools_54.2.0
python3-zope-event_4.5.0
python3-docutils_0.14
python3-lxml_4.6.3
python3-pydot_1.4.1
python3-sgmllib3k_1.0.0
python3-zope-interface_5.3.0
```
