### ISSUE TITLE
[14] hr holidays: can not delete time off without start/end date

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#68671]
Impacted versions: 14

Steps to reproduce: Create time off without any date and try to Delete it

https://6989329-14-0-all.runbot51.odoo.com/web?debug=1#id=15&action=299&model=hr.leave&view_type=form&cids=&menu_id=234

Current behavior: 
![Screenshot (3)](https://user-images.githubusercontent.com/16624719/113345743-813f2d00-9350-11eb-8c77-5cb83f3cbc91.png)

Expected behavior: Able to delete

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by khalidelhaji** [comment]
You can solve this issue by making sure that the `data_from` attribute in the database doesn't have to be "Not Null". Will this solves the issue you mentioned, I have no idea as to how this can actually be solved in the Odoo codebase as I couldn't find where/how the database is set up with all its tables and associated attributes.

**Comment by sswapnesh** [comment]
@khalidelhaji  It is trying to set `data_from` false in compute method

**Comment by khalidelhaji** [comment]
@sswapnesh I am not sure which method you are referring to. Could you provide an explicit reference?

**Comment by sswapnesh** [comment]
https://github.com/odoo/odoo/blob/393ce31fbdd9c424037dc159e1ec8ac1bfbbf0b0/addons/hr_holidays/models/hr_leave.py#L319

**Comment by khalidelhaji** [comment]
Hmm, I don't think that function is the culprit. I am not sure if that function is called when deleting.

**Comment by sswapnesh** [comment]
```
2021-04-06 16:54:15,243 8772 ERROR v14 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/swapnesh/WorkSpace/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/swapnesh/WorkSpace/14.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/swapnesh/WorkSpace/14.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/swapnesh/WorkSpace/14.0/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/swapnesh/WorkSpace/14.0/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/swapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/swapnesh/WorkSpace/14.0/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave.py", line 832, in unlink
    return super(HolidaysRequest, self.with_context(leave_skip_date_check=True, unlink=True)).unlink()
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_thread.py", line 337, in unlink
    res = super(MailThread, self).unlink()
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_activity.py", line 771, in unlink
    result = super(MailActivityMixin, self).unlink()
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 3425, in unlink
    self.check_access_rule('unlink')
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 3346, in check_access_rule
    invalid = self - self._filter_access_rules_python(operation)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 3401, in _filter_access_rules_python
    return self.sudo().filtered_domain(dom or [])
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 5314, in filtered_domain
    data = rec.mapped(key)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 5242, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1075, in mapped
    self.recompute(records)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4061, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave.py", line 439, in _compute_from_employee_id
    holiday.manager_id = holiday.employee_id.parent_id.id
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 967, in __get__
    self.recompute(record)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4068, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave.py", line 592, in _check_date_state
    if holiday.state in ['cancel', 'refuse', 'validate1', 'validate']:
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 967, in __get__
    self.recompute(record)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4068, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave.py", line 578, in _check_holidays
    mapped_days = self.mapped('holiday_status_id').get_employees_days(self.mapped('employee_id').ids)
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave_type.py", line 208, in get_employees_days
    requests = self.env['hr.leave'].search([
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4492, in _search
    self._flush_search(args, order=order)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4470, in _flush_search
    self.env[model_name].flush(field_names)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 5442, in flush
    self.recompute(fnames, records=records)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 5908, in recompute
    process(field)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 5879, in process
    field.recompute(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/swapnesh/WorkSpace/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/swapnesh/WorkSpace/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/swapnesh/WorkSpace/14.0/odoo/models.py", line 4061, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/swapnesh/WorkSpace/14.0/addons/hr_holidays/models/hr_leave.py", line 326, in _compute_date_from_to

```
