### ISSUE TITLE
TypeError: Cannot read property 'focusableElement' of null

### ISSUE THREAD

**Issue by slakk** [odoo/odoo#69938]
Impacted versions:14

Steps to reproduce: add Boolean field to sale.order.line. then add Optional Products to order line

Current behavior:error

Expected behavior:

Video/Screenshot link (optional):https://www.loom.com/share/1758de75d9834d82a0d5b30290b8d322

Support ticket number submitted via odoo.com/help (optional):

on http://runbot.odoo.com/runbot cant check because sale.order.line have not checkbox fields
I managed to reproduce bug locally on laters version Odoo

```
class SaleOrderLine(models.Model):
_inherit = 'sale.order.line'
approved = fields.Boolean(string="Approved", default=False)

    <record id="sale_order_form_view" model="ir.ui.view">
        <field name="name">sale.order.form.inherit</field>
        <field name="model">sale.order</field>
        <field name="inherit_id" ref="sale.view_order_form" />
        <field name="mode">primary</field>
        <field name="priority" eval="15"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='order_line']/tree/field[@name='product_id']" position="before">
                <field name="approved"  />
            </xpath>
        </field>
    </record>
```

if add boolean field to sale.order.line and show this field on order tree
after need add to new order some optional products 
on popup need  click on add to cart some optional products
after confirm Configure optional products we have error

```
Traceback:
TypeError: Cannot read property 'focusableElement' of null
    at FieldWrapper.getFocusableElement (http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:1175:55)
    at http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:2580:184
    at Function._.each._.forEach (http://localhost:8081/web/content/1841-83a233f/web.assets_common.js:108:558)
    at toggleWidgets (http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:2580:133)
    at Class.unselectRow (http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:2581:1)
    at Object.onSuccess (http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:6419:922)
    at http://localhost:8081/web/content/1842-69a2c77/web.assets_backend.js:1127:1086
```

**Comment by pedrobaeza** [comment]
Why are you adding the field in the view as primary?

**Comment by slakk** [comment]
don't matter. for optional fields problem still have. if new field shown

**Comment by pedrobaeza** [comment]
This sounds me very weird to me. @Yenthe666 what do you think?

**Comment by slakk** [comment]
i found decision for me not use checkbox on lines but maybe it's bug

**Comment by Yenthe666** [comment]
Have you tried reproducing it on a runbot with studio or a custom field on the order line though? We have custom modules with booleans on the lines that work just fine 🤔

**Comment by sswapnesh** [comment]
@pedrobaeza  @Yenthe666 I can confirm this Bug on Runbot. 
![Screenshot from 2021-04-30 01-29-19](https://user-images.githubusercontent.com/16624719/116611136-a6c15580-a953-11eb-8153-90b36478cd5f.png)

Add boolean field on order line at first position.
Add option products https://prnt.sc/129o5b7

**Comment by pedrobaeza** [comment]
But that's because the widget expects at the first place other field. Have you tried in another position after the sequence one?

**Comment by sswapnesh** [comment]
Still same Issue
![Screenshot from 2021-04-30 01-39-26](https://user-images.githubusercontent.com/16624719/116612219-ea688f00-a954-11eb-8a1a-6e2060257750.png)

**Comment by Yenthe666** [comment]
@ged-odoo can somebody from your team look at it?

**Comment by msh-odoo** [comment]
Yes, I can produce it, will have a look

**Comment by msh-odoo** [comment]
@slakk @Yenthe666 @Yenthe666 Should be fixed with #72399

**Comment by Yenthe666** [comment]
If now some of all those PR's you make get merged.. :)
