### ISSUE TITLE
xmlrpc api error while fetch all tables / models with search_read over ir.model 

### ISSUE THREAD

**Issue by s0me0ther** [odoo/odoo#70096]
Impacted versions: 14

Steps to reproduce: xmlrpc api search_read ir.model

Current behavior: relation "account_invoice_report" does not exist

Expected behavior: list of all tables / models

Full error:
```
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 790, in get
    return field_cache[record._ids[0]]
KeyError: 331

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.model(331,).count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 49, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 140, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 41, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 168, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 175, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 159, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4832, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3018, in read
    return self._read_format(fnames=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3038, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 986, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1142, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4054, in _compute_field_value
    getattr(self, field.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_model.py", line 204, in _compute_count
    cr.execute(sql.SQL('SELECT COUNT(*) FROM {}').format(sql.Identifier(records._table)))
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "account_invoice_report" does not exist
LINE 1: SELECT COUNT(*) FROM "account_invoice_report"

```

**Comment by s0me0ther** [comment]
It's possible to get a result by omitting the table count

**Comment by Sirfanas** [comment]
Hi,

Did you try to upgrade the `base` module ?
It look like there's a problem with the module account

**Comment by pedrobaeza** [comment]
Yes, this has nothing to do with the XML-RPC protocol itself, so closing unless further evidences are presented.

**Comment by tw-maustin** [comment]
I don't think it's related to xml-rpc, but I do think it might be a bug here?
https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_model.py#L203
because it's valid for a model to not be _abstract,  but also if  _auto = False it will not have a table. 

The same is true for another example 
`psycopg2.ProgrammingError: relation "account_aged_payable" does not exist
LINE 1: SELECT COUNT(*) FROM "account_aged_payable"`
This model is also _auto=False but it is not an _abstract=False thereby triggering a SELECT COUNT on a table that doesn't exist.
