### ISSUE TITLE
Getting issue on claims

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7019]
Hello,

Odoo v8 stable.

Clicked on sales -> after sale servers -> claims,

Clicked on calendar view, getting below bug.

```
Traceback (most recent call last):
  File "/home/odoohell/v8/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/odoohell/v8/odoo/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoohell/v8/odoo/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/home/odoohell/v8/odoo/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoohell/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/models.py", line 5108, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/home/odoohell/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoohell/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/models.py", line 4635, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/odoohell/v8/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoohell/v8/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type timestamp: "0NaN-NaN-NaN"
LINE 1: ...d" = 1))  AND  ("crm_claim"."date_action_next" >= '0NaN-NaN-...
                                                             ^
```

**Comment by sergueikp** [comment]
Hi, I have the same issue, form time to time there is the server error popping up:
Odoo 8.0-20150528

To reproduce:
Open the calendar view in any module

Then you get this error:
Odoo Server Error
________________________________________
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 897, in do_search_read
    request.context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 5112, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4639, in _search
    cr.execute(query_str, where_clause_params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type timestamp: "0NaN-NaN-NaN"
LINE 1: ...one')))  AND  ("sale_order_line"."date_depart" >= '0NaN-NaN-...

**Comment by tejastank** [comment]
How fpodoo dealing with stable version of bugs? Does it takes 6 days to fix for stable version !!!

Users of odoo had to suffer always with newly stable version use, not estimate how long take a fix

**Comment by shingonoide** [comment]
:+1:  When try to open calendar view of project/tasks.

**Comment by Yenthe666** [comment]
Hi @tejastank,

This bug can no longer be reproduced in the latest Odoo 8 build.
If you still face this issue please update your Odoo and this issue will be fixed!

Regards,
Yenthe

**Comment by tejastank** [comment]
@Yenthe666 Ohh, Awesome for quick actions, after a year!!!, thanks for slow perfect fixes.  



Thanks from:
me, @shingonoide @sergueikp

**Comment by Yenthe666** [comment]
@tejastank,

Odoo has had way too many issues in the past and not enough people to handle all of them. 
You're welcome though!

Regards,
Yenthe

**Comment by ljsalvatierra** [comment]
I've encountered this error following the app todo-task tutorial in the book "Odoo Development Essentials" (chapter 6). Also when clicking some times in the calendar view, a bit random...

Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 915, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 5183, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 1646, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4704, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type date: "0NaN-NaN-NaN"
LINE 1: ...ve" = true)  AND  ("todo_task"."date_deadline" >= '0NaN-NaN-...

**Comment by tejastank** [comment]
@Yenthe666, Thanks for hiding bugs in community edition, big thanks for Nagative graded support on community edition.
 
People soon start to pay big amount for enterprise edition like #NetsuiteERP.
You really making good job for Enterprise edition,
