### ISSUE TITLE
Using delete tag - Warning for not found external ID 

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#7043]
I specified these records to be deleted as they are not needed in my module.

``` xml
        <delete id="crm.ir_mark_as_lost" model="ir.values"/>
        <delete id="crm.action_mark_as_lost" model="ir.actions.server"/>
```

First time I did upgrade of my module, everything went fine. But now everytime I ugprade my module, I get this warning (below). Is it intended to warn you that record was not found? Because it actually clear it should not find it, because it was deleted, so why warn every time?

Or maybe it is possible to suppress that specific warning? Cause at least for me that warning is not necessary at all. Or even better to delete record only when it exists? So then it should not give this error.

```
2015-06-12 08:30:13,153 384 WARNING test openerp.tools.convert: Skipping deletion for missing XML ID `'crm.ir_mark_as_lost'`
Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 309, in _tag_delete
    ids.append(self.id_get(cr, d_id))
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/oerp/openerp80/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: crm.ir_mark_as_lost
2015-06-12 08:30:13,156 384 WARNING test openerp.tools.convert: Skipping deletion for missing XML ID `'crm.action_mark_as_lost'`
Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 309, in _tag_delete
    ids.append(self.id_get(cr, d_id))
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/oerp/openerp80/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: crm.action_mark_as_lost
```

P.S. Module does not stop from working though, but just wondering if that error is intended or not.

**Comment by samuellefever** [comment]
Same here.
Any solution to avoid this?

**Comment by SirEdvin** [comment]
Try to use `search` tag instead of `id` tag

**Comment by ParokshaX** [comment]
@SirEdvin that doesn't seem to be the way.
 By using `search` instead of `id` still one have to use `ref()`  in search domain which returns the same "External ID not found Error"
 also `noupdate=1` doesn't seem to work at all!. are there any viable solutions at all?

**Comment by LeartS** [comment]
For models **with an `active` field**, the best solution is probably to set override the record using the same id and setting `<field name="active" eval="False"/>`.

For models **without an active field**, I think only the warning should be printed, and no stacktrace!

**Comment by rockcesar** [comment]
Good afternoon, how are you people?. I found a tag in odoo/l10n_fr/data/account_fiscal_position_template_data.xml, referencing to the solution:

<delete model="account.fiscal.position.template" search="[('chart_template_id','=',ref('l10n_fr_pcg_chart_template'))]"/>

Using the search attributem, you can refer the value with ref('l10n_fr_pcg_chart_template').

Being l10n_fr_pcg_chart_template the XML ID.

**Comment by pedrobaeza** [comment]
This is something inherent in how it works that command, so better to not use it in XML, or you won't be able to avoid the warning message. In recent versions, you can use hooks for doing the job of removing things.
