### ISSUE TITLE
Database "postgres" does not exist

### ISSUE THREAD

**Issue by Prasoon6667** [odoo/odoo#70532]
I was trying to deploy odoo 14 on digital ocean with managed database and encountered this error

`Traceback (most recent call last):
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 61, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 178, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 142, in main
    odoo.service.db._create_empty_database(db_name)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 99, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 675, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 248, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 558, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 626, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "postgres" does not exist`

DigitalOcean's database cluster comes with a DB called defaultdb

https://github.com/odoo/odoo/blob/c449fcb6274c9e68d4470423b5e2d91df3566615/odoo/service/db.py#L97

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by Prasoon6667** [comment]
The issue appears with digital ocean managed databases which doesnt have 'postgres' database and the 'postgres' database is used in here: https://github.com/odoo/odoo/blob/c449fcb6274c9e68d4470423b5e2d91df3566615/odoo/service/db.py#L97

**Comment by Prasoon6667** [comment]
> Then you can't use such thing.

Wow, thats a great answer from a great community, thats how we should tackle the issues. :)

**Comment by pedrobaeza** [comment]
It's not an issue, but a limitation.
