### ISSUE TITLE
[8.0] ERROR database_test openerp.sql_db: bad query: SELECT

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#7060]
Hi, I've got this error when clicking on calendar view of sale.order.line object.
Impacted version Odoo 8.0 20150528

How to reproduce:
Select filter Today, then Click on the menu item on the left side than click on the calendar view, or click several times back and forth on side menu with tree view and calendar view, error occurs randomly. 

Current Behaviour : 
Error occuring randomly:

2015-06-13 19:31:01,313 484 ERROR aramis_prod2_test openerp.sql_db: bad query: SELECT "sale_order_line".id FROM "sale_order_line" WHERE (((("sale_order_line"."state" in ('draft','sent','invoice_except','waiting_date','progress','manual','done'))  AND  ("sale_order_line"."state" in ('draft','sent','invoice_except','waiting_date','progress','manual','done')))  AND  ("sale_order_line"."date_depart" >= '0NaN-NaN-NaN'))  AND  ("sale_order_line"."date_depart" <= '0NaN-NaN-NaN')) ORDER BY "sale_order_line"."date_depart" asc,"sale_order_line"."id" asc 
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 897, in do_search_read
    request.context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 5112, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4639, in _search
    cr.execute(query_str, where_clause_params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type timestamp: "0NaN-NaN-NaN"
LINE 1: ...one')))  AND  ("sale_order_line"."date_depart" >= '0NaN-NaN-...
                                                             ^

**Comment by witoszek** [comment]
Hi How do you solvede?
