### ISSUE TITLE
[8.0] Project Module & Calendar view - ERROR openerp.sql_db: bad query: SELECT...

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#7061]
Hi, there is an error when accessing Calendar view in any module.
![error_projet_task_view_calendar](https://cloud.githubusercontent.com/assets/9844780/8147956/d8ea2f9e-1284-11e5-9e71-2f26c06d82fd.JPG)

![error_projet_task_view_calendar](https://cloud.githubusercontent.com/assets/9844780/8146302/bbb7d1d6-1231-11e5-9a39-38d70e29f7eb.JPG)
.
Impacted version : 8.0-20150528 (Windows and Ubuntu)

How to reproduce:
Crate a Project
Crate some tasks
Switch back and forth beetween Canban view and calendar view of tasks, Attention!! you have to click on the side menubar "Tasks" (not on canban view selector)  then  on the Calendar view selector.
The error will occur randomly after ten to twenty back and forth.  
You will get this error message:

2015-06-13 22:51:37,865 3164 ERROR aramis_prod2_test openerp.sql_db: bad query: SELECT "project_task".id FROM "project_task" WHERE ((("project_task"."active" = true)  AND  ("project_task"."date_deadline" >= '0NaN-NaN-NaN'))  AND  ("project_task"."date_deadline" <= '0NaN-NaN-NaN')) ORDER BY "project_task"."priority" desc,"project_task"."sequence" ,"project_task"."date_start" ,"project_task"."name" ,"project_task"."id"  
Traceback (most recent call last):
  File "C:\Odoo 8.0-20150528\server\.\openerp\sql_db.py", line 234, in execute
DataError: ERREUR:  syntaxe en entrÃ©e invalide pour le type date : Â« 0NaN-NaN-NaN Â»
LINE 1: ... = true)  AND  ("project_task"."date_deadline" >= '0NaN-NaN-...
                                                             ^

2015-06-13 22:51:37,865 3164 ERROR aramis_prod2_test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 536, in _handle_exception
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 573, in dispatch
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 309, in _call_function
  File "C:\Odoo 8.0-20150528\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 306, in checked_call
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 802, in __call__
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 402, in response_wrap
  File "C:\Odoo 8.0-20150528\server\openerp\addons\web\controllers\main.py", line 877, in search_read
  File "C:\Odoo 8.0-20150528\server\openerp\addons\web\controllers\main.py", line 898, in do_search_read
  File "C:\Odoo 8.0-20150528\server\.\openerp\http.py", line 907, in proxy
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 5129, in search_read
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 1642, in search
  File "C:\Odoo 8.0-20150528\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\models.py", line 4656, in _search
  File "C:\Odoo 8.0-20150528\server\.\openerp\sql_db.py", line 158, in wrapper
  File "C:\Odoo 8.0-20150528\server\.\openerp\sql_db.py", line 234, in execute
DataError: ERREUR:  syntaxe en entrÃ©e invalide pour le type date : Â« 0NaN-NaN-NaN Â»
LINE 1: ... = true)  AND  ("project_task"."date_deadline" >= '0NaN-NaN-...

**Comment by Yenthe666** [comment]
Hi @sergueikp,

I can no longer reproduce this issue on the last Odoo 8 code.
If you still face this issue please update your local Odoo and it should be fixed!

Regards,
Yenthe
