### ISSUE TITLE
[8.0] Database restore error

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#7063]
Hi, it's me again,
I'm sorry but I'm setting up a production server and I would like to be sure that everything will work fine.
Impacted version:
8.0 20150423 (Ubuntu and Windows) with Document module installed

Steps to reproduce the error:
Create a new database with de
![error_impossible_to_restore_database](https://cloud.githubusercontent.com/assets/9844780/8148209/5b764d06-1291-11e5-909e-51dff2ff4b3b.JPG)
mo information
Backup database, in *.dump format (not *.zip)  then try to restore it on same or different server,

Current behavior:
When I restore the database I got contradictory informations :
1. In the web interface two popup windows, first says "Impossible to restore the database", second in the right top corner (which stays 2 seconds on the screen) says "Database restored successfully", and in fact the database is restored and works apparently good,

2. In the openerp-server.log file I see the error message:
2015-06-14 09:50:54,864 18799 ERROR None openerp.http: Postgres subprocess ('/opt/bitnami/postgresql/bin/pg_restore', '--username=bn_openerp', '--host=127.0.0.1', '--port=5432', u'--dbname=aramis_prod1_v1_2015-06-13_ubu_aws_4000leads', '--no-owner', '/tmp/tmpTFPg_C') error 1
Traceback (most recent call last):
File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 114, in dispatch_rpc
result = dispatch(method, params)
File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/db.py", line 73, in dispatch
return fn(*params)
File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/db.py", line 217, in exp_restore
restore_db(db_name, data_file.name, copy=copy)
File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/db.py", line 260, in restore_db
if openerp.tools.exec_pg_command(pg_cmd, *pg_args):
File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/misc.py", line 128, in exec_pg_command
raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/opt/bitnami/postgresql/bin/pg_restore', '--username=bn_openerp', '--host=127.0.0.1', '--port=5432', u'--dbname=aramis_prod1_v1_2015-06-13_ubu_aws_4000leads', '--no-owner', '/tmp/tmpTFPg_C') error 1

Can you help me please with this.
Thank you very much.

**Comment by andreparames** [comment]
Most likely, you have some kind of problem in the template1 database (that comes with Postgres), so pg_restore gives an error before finishing. I see you're running Odoo using bitnami; does it have an error_log? It'd be useful to get the error from the postgres command that was run by Odoo.

**Comment by sergueikp** [comment]
The error was related to Bitnami Postgresql configuration.
The issue is that the generated user for the application doesn't have enough permissions to create a new user. You can allow it executing the following:
psql -U postgres -c "ALTER USER bn_openerp WITH CREATEUSER;"

And I used this command for stack installation: 
/opt/odoo-8.0-9/postgresql/bin/psql -U postgres -c "ALTER USER bn_openerp WITH CREATEUSER;"

**Comment by BrayhanJC** [comment]
Yo tengo este error .

2017-02-10 23:10:48,270 6896 INFO None werkzeug: 127.0.0.1 - - [10/Feb/2017 23:10:48] "POST /web/database/restore HTTP/1.1" 200 -
2017-02-10 23:18:30,727 6896 ERROR None openerp.http: Command `pg_restore` not found.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\http.py", line 115, in dispatch_rpc
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\service\db.py", line 379, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\service\db.py", line 217, in exp_restore
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\service\db.py", line 254, in restore_db
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\tools\misc.py", line 116, in exec_pg_command
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\.\openerp\tools\misc.py", line 90, in find_pg_tool
Exception: Command `pg_restore` not found.
2017-02-10 23:18:30,997 6896 INFO None werkzeug: 127.0.0.1 - - [10/Feb/2017 23:18:30] "POST /web/database/restore HTTP/1.1" 200 -

**Comment by andreparames** [comment]
@BrayhanJC seems like you're missing the Postgres tools. The easiest fix is just to install Postgres on your machine: https://get.enterprisedb.com/postgresql/postgresql-9.6.2-1-windows-x64.exe

**Comment by BrayhanJC** [comment]
Hola ahora me sale es este error, 
    if not self._execute(activity, stack):
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\openerp\workflow\workitem.py", line 144, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\openerp\workflow\workitem.py", line 295, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\openerp\workflow\workitem.py", line 272, in wkf_expr_eval_expr
    env = Environment(self.session, self.record)
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\openerp\workflow\workitem.py", line 35, in __init__
    self.obj = openerp.registry(self.cr.dbname)[self.model]
  File "C:\Program Files (x86)\Odoo 9.0-20170131\server\openerp\modules\registry.py", line 84, in __getitem__
    return self.models[model_name]
**KeyError: u'sale.order'**


Lo que hice fue hacer una copia de seguridad desde la versión de odoo 8 para restaurarla en odoo 9. Claro esta ejecute primeramente este código.

wget https://raw.githubusercontent.com/OCA/OpenUpgrade/HEAD/scripts/migrate.py
python migrate.py --config=/etc/odoo-server.conf --database=entrenamiento --run-migrations=8.0,9.0

Pero no logro restaurarla. Muchas gracias por su ayuda
