### ISSUE TITLE
Can't use xml data for default values?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#7067]
I created this xml data:
```xml
<record id="commission_repayment_1" model="insurance.commission.repayment">
    <field name="name">Repayment Plan</field>
</record>
```
And I tried to use it as default value for a record, like this:
```python
    repayment_id = fields.Many2one('insurance.commission.repayment', 'Commission Repayment', required=True, 
        default=lambda s: s._get_default_repayment(),
        help="It is used when contract is cancelled and need to return paid commissions")

    @api.model
    def _get_default_repayment(self):
        return self.env.ref('insurance_commission_invoice.commission_repayment_1')
```
But there is a problem. It seems odoo first tries to get default value without loading xml data. When I try to install my module, it gives error, that external ID was not found:

```
Traceback (most recent call last):
  File "/home/oerp/openerp80/odoo/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/oerp/openerp80/odoo/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/oerp/openerp80/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/oerp/openerp80/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/oerp/openerp80/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/oerp/openerp80/odoo/openerp/modules/module.py", line 286, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/models.py", line 2623, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/models.py", line 2390, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/fields.py", line 417, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/home/oerp/openerp80/addons/insurance_commission_invoice/models/insurance_commission.py", line 78, in <lambda>
    default=lambda s: s._get_default_repayment(),
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/addons/insurance_commission_invoice/models/insurance_commission.py", line 83, in _get_default_repayment
    repayment = self.env.ref('insurance_commission_invoice.commission_repayment_1')
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 737, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 950, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/oerp/openerp80/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/oerp/openerp80/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/oerp/openerp80/odoo/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: insurance_commission_invoice.commission_repayment_1
```

But if I install my module without default value for that field and then after installation I change code to have such default value again, then it finds that xml and gives default value.

So is it bugged, that xml data is loaded later? Or I have to somehow specify to load it first?

Data files priority in `__openerp__.py` is set just after security csv file.

**Comment by oerp-odoo** [comment]
Changing default method to this:
```python
    @api.model
    def _get_default_repayment(self):
        return self.env['insurance.commission.repayment'].search([], limit=1, order='id')
```
let me installed. But still it does not answer why xml data is not loaded first? But when I search for record then it finds, but skips default values for records that were already present in before installing module.

**Comment by michaelkarrer81** [comment]
I do have the exact same problem! 
How can one make sure the Data XML is loaded before?

**Comment by fevxie** [comment]
you can use following codes to fix your problem:
```
@api.model
    def _get_default_repayment(self):
        return self.env.ref('insurance_commission_invoice.commission_repayment_1', False) and self.env.ref('insurance_commission_invoice.commission_repayment_1') or self
```

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

I'm closing this issue since it is not about the default Odoo code, but custom development. @fevxie gives a nice example too, so you should be fine.
I'd suggest you to create a topic on the official Odoo help forum (help.odoo.com) when you're facing custom development issues, this forum is dedicated to these kind of questions.

Regards,
Yenthe
