### ISSUE TITLE
invoice problem

### ISSUE THREAD

**Issue by tarekihya** [odoo/odoo#7084]
When I try to create an invoice I get this error 
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 573, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 306, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 802, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 402, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/src/odoo/8.0/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/8.0/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/sale/wizard/sale_make_invoice_advance.py", line 175, in create_invoices
    res = sale_obj.manual_invoice(cr, uid, sale_ids, context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/sale/sale.py", line 458, in manual_invoice
    self.signal_workflow(cr, uid, ids, 'manual_invoice')
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3557, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/instance.py", line 75, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 187, in _execute
    id_new = self.wkf_expr_execute(activity)
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/odoo/src/odoo/8.0/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/odoo/src/odoo/8.0/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/sale_stock/sale_stock.py", line 143, in action_invoice_create
    res = super(sale_order,self).action_invoice_create(cr, uid, ids, grouped=grouped, states=states, date_invoice = date_invoice, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/sale/sale.py", line 564, in action_invoice_create
    res = self._make_invoice(cr, uid, order, il, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/sale/sale.py", line 435, in _make_invoice
    inv_id = inv_obj.create(cr, uid, inv, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 4212, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "account_id" violates not-null constraint
DETAIL:  Failing row contains (41, null, null, 0.00, SO006, 1, null, null, 1, 113, 2015-06-16 01:08:29.075049, 5, null, null, null, 33, null, none, 4, null, draft, null, out_invoice, null, null, f, null, null, null, null, 2015-06-16 01:08:29.075049, 6, 5, SO006, null, , f, null, 3).
" while evaluating
u'action_invoice_create()'

**Comment by flotho** [comment]
Hy @tarekihya, the latest message seems explicit :
```
null value in column "account_id" violates not-null constraint
```
It looks like some fields of your invoice are not set or maybe you're un multi company env an you choose one of the wrong company

**Comment by Yenthe666** [comment]
Hi @tarekihya,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
