### ISSUE TITLE
[14.0] stock_account: unsupported operand in _action_done

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#70967]
Impacted versions: 14.0

Steps to reproduce:
Create and confirm a stock move.

Current behavior:
```Error:
Odoo Server Error

Traceback (most recent call last):
  File "/path/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/path/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/path/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/path/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/path/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/path/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/path/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/path/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/path/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/path/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/path/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/path/addons/stock/wizard/stock_track_confirmation.py", line 16, in action_confirm
    confirmation.inventory_id._action_done()
  File "/path/addons/stock/models/stock_inventory.py", line 127, in _action_done
    self.post_inventory()
  File "/path/addons/stock_account/models/stock_inventory.py", line 38, in post_inventory
    res = super(StockInventory, inventory.with_context(force_period_date=inventory.accounting_date)).post_inventory()
  File "/path/addons/stock/models/stock_inventory.py", line 134, in post_inventory
    self.mapped('move_ids').filtered(lambda move: move.state != 'done')._action_done()
  File "/path/addons/stock_account/models/stock_move.py", line 250, in _action_done
    for move in res - self:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/path/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for -: 'NoneType' and 'stock.move'
```

Expected behavior:
Confirm stock move

**Comment by mrawi** [comment]
Could not replicate on different instance using the same database.
