### ISSUE TITLE
Error Design Layout document - Odoo 14

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#71073]
Hello, after restoring a backup of the same version, the logos do not appear in the document.

When I try to edit the document I get the following error:

Odoo Server Error
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 683, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 359, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3.8/site-packages/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 347, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 912, in __call__
return self.method(*args, **kw)
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 531, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3.8/site-packages/odoo/api.py", line 396, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python3.8/site-packages/odoo/api.py", line 383, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/usr/lib/python3.8/site-packages/odoo/models.py", line 6244, in onchange
snapshot1 = Snapshot(record, nametree)
File "/usr/lib/python3.8/site-packages/odoo/models.py", line 6049, in __init__
self.fetch(name)
File "/usr/lib/python3.8/site-packages/odoo/models.py", line 6059, in fetch
self[name] = record[name]
File "/usr/lib/python3.8/site-packages/odoo/models.py", line 5666, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/usr/lib/python3.8/site-packages/odoo/fields.py", line 1019, in __get__
self.compute_value(recs)
File "/usr/lib/python3.8/site-packages/odoo/fields.py", line 1175, in compute_value
records._compute_field_value(self)
File "/usr/lib/python3.8/site-packages/odoo/models.py", line 4061, in _compute_field_value
getattr(self, field.compute)()
File "/usr/lib/python3.8/site-packages/odoo/addons/web/models/base_document_layout.py", line 100, in _compute_preview
preview_css = self._get_css_for_preview(styles, wizard.id)
File "/usr/lib/python3.8/site-packages/odoo/addons/web/models/base_document_layout.py", line 249, in _get_css_for_preview
css_code = self._compile_scss(scss)
File "/usr/lib/python3.8/site-packages/odoo/addons/web/models/base_document_layout.py", line 277, in _compile_scss
except libsass.CompileError as e:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 639, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3.8/site-packages/odoo/http.py", line 315, in _handle_exception
raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'CompileError'

Thanks for the help

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps trying on runbot, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
