### ISSUE TITLE
Bug in filestore

### ISSUE THREAD

**Issue by Said113** [odoo/odoo#71081]
2021-05-20 09:13:26,940 21356 INFO archi odoo.addons.base.models.ir_attachment: _read_file reading /home/odoo1/.local/share/Odoo/filestore/archi/16/16adc9bbd80e077b71728c4a175e08f3472f60b1 
Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 761

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
  File "/opt/rgs/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(761,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/addons/base/models/ir_attachment.py", line 103, in _file_read
    with open(full_path,'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo1/.local/share/Odoo/filestore/archi/16/16adc9bbd80e077b71728c4a175e08f3472f60b1'
2021-05-20 09:13:26,942 21356 INFO archi werkzeug: 41.107.49.71 - - [20/May/2021 09:13:26] "GET /web/content/761-bd5fc0f/web.assets_backend.js HTTP/1.1" 404 - 4 0.001 0.006
2021-05-20 09:13:26,947 21356 INFO archi werkzeug: 41.107.49.71 - - [20/May/2021 09:13:26] "GET /web/webclient/load_menus/c818157a373a332a275ba9a8920690fbe08655ac HTTP/1.1" 200 - 1 0.000 0.003
2021-05-20 09:13:29,721 21355 INFO archi odoo.addons.base.models.ir_attachment: _read_file reading /home/odoo1/.local/share/Odoo/filestore/archi/16/16adc9bbd80e077b71728c4a175e08f3472f60b1 
Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 761

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
  File "/opt/rgs/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(761,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rgs/odoo/odoo/addons/base/models/ir_attachment.py", line 103, in _file_read
    with open(full_path,'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo1/.local/share/Odoo/filestore/archi/16/16adc9bbd80e077b71728c4a175e08f3472f60b1'
2021-05-20 09:13:29,724 21355 INFO archi werkzeug: 41.107.49.71 - - [20/May/2021 09:13:29] "GET /web/content/761-bd5fc0f/web.assets_backend.js HTTP/1.1" 404 - 4 0.001 0.007

--------------------------------------------------------------------------------------------------
and when i run 
 - sudo -u postgres psql
 - postgres=# DELETE FROM ir_attachment WHERE store_fname LIKE'%16adc9bbd80e077b71728c4a175e08f3472f60b1%';
ERROR:  relation "ir_attachment" does not exist
LINE 1: DELETE FROM ir_attachment WHERE store_fname LIKE'%16adc9bbd8...

**Comment by pedrobaeza** [comment]
This is something of your deployment, that has a missing file in your filestore, and the postgres operation is not being done on the proper DB.

Closing as no Odoo issue.
