### ISSUE TITLE
Get a trace back when trying to print an empty delivery order

### ISSUE THREAD

**Issue by duanyp1991** [odoo/odoo#7113]
Create an empty delivery order, print the 'picking' report, getting the following error:

Traceback (most recent call last):
  File "/home/alex/elico/v8/odoo/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/alex/elico/v8/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/alex/elico/v8/odoo/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/addons/report/models/report.py", line 186, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/addons/report/models/report.py", line 171, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/addons/report/models/report.py", line 147, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1015, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/alex/elico/v8/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 430, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 416, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 430, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 424, in render_tag_if
    if self.eval_bool(template_attributes["if"], qwebcontext):
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 228, in eval_bool
    return int(bool(self.eval(expr, qwebcontext)))
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 197, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    return qwebcontext.safe_eval(expr)
  File "/home/alex/elico/v8/odoo/openerp/addons/base/ir/ir_qweb.py", line 80, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/home/alex/elico/v8/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/alex/elico/v8/odoo/openerp/models.py", line 5527, in __getitem__
    return self._browse(self.env, (self._ids[key],))
QWebException: "tuple index out of range" while evaluating
'o.move_lines[0].partner_id and o.move_lines[0].partner_id.id != o.partner_id.id'

**Comment by Yenthe666** [comment]
Hi @duanyp1991 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
I've tried to reproduce it on 9.0 & 10.0 and it seems to work fine there now too.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
