### ISSUE TITLE
 AttributeError: 'report.bi_account_tax_report.bi_report_account_tax' object has no attribute '_get_report_values'

### ISSUE THREAD

**Issue by AsmaAl-Haddar** [odoo/odoo#71366]
Impacted versions: 13.0
Hello all,

I faced an error while printing my report that I'd created it, but I couldn't know where the error placed and why it caused that error.

Here is the ERROR that I faced:.

Error:
Odoo Server Error

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 2032, in report_download
response = self.report_routes(reportname, converter=converter, context=context, **data)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
response = f(*args, **kw)
File "/home/ubuntu/custom_modules/report_xlsx_helper/controllers/main.py", line 56, in report_routes
reportname, docids, converter, **data
File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
response = f(*args, **kw)
File "/home/ubuntu/custom_modules/report_xlsx/controllers/main.py", line 49, in report_routes
reportname, docids, converter, **data
File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1963, in report_routes
pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 734, in render_qweb_pdf
html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 773, in render_qweb_html
data = self._get_rendering_context(docids, data)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 790, in _get_rendering_context
data.update(report_model._get_report_values(docids, data=data))
AttributeError: 'report.bi_account_tax_report.bi_report_account_tax' object has no attribute '_get_report_values'

May anyone guide me solving this ERROR.

Waiting an reply,

Thanks in advance,

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot). Maybe a third-party module is breaking the behavior.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
