### ISSUE TITLE
[8.0] ascii can't decode

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#7136]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/opt/odoo/openerp/netsvc.py", line 120, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa1 in position 38: ordinal not in range(128)
Logged from file _internal.py, line 87
```

**Comment by ilexius** [comment]
This happens when you feed unicode to the logger. I have the same problem, as some library is logging a string with UTF-8 characters in it.

**Comment by MuhammedMiiRanna** [comment]
@ilexius I am facing a similar issue when trying to run odoo16 on my PC, here's the error: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 103: invalid continuation byte


can you guide me ?
