### ISSUE TITLE
FIrst time login error

### ISSUE THREAD

**Issue by JDuque99** [odoo/odoo#71738]
Hello.

Whenever a new user logs in for the first time, the page gives an Internal Error. However when the new user refreshes the page and tries to log in a second time, he's allowed to do it.

Why is that? Why the internal error in the first time?

This is the log error when the new user sees the Internal Error page:

2021-06-04 08:29:59,260 17216 ERROR OneSource werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/openhrms/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/opt/openhrms/odoo/http.py", line 806, in dispatch
r = self._call_function(**self.params)
File "/opt/openhrms/odoo/http.py", line 359, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/openhrms/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/openhrms/odoo/http.py", line 347, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/openhrms/odoo/http.py", line 912, in call
return self.method(*args, **kw)
File "/opt/openhrms/odoo/http.py", line 531, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
response = super(AuthSignupHome, self).web_login(*args, **kw)
File "/opt/openhrms/odoo/http.py", line 531, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 946, in web_login
uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
File "/opt/openhrms/odoo/http.py", line 1011, in authenticate
if not user._mfa_url():
File "/usr/lib/python3/dist-packages/odoo/addons/auth_totp/models/res_users.py", line 37, in _mfa_url
if self.totp_enabled:
File "/opt/openhrms/odoo/fields.py", line 1021, in get
self.compute_value(record)
File "/opt/openhrms/odoo/fields.py", line 1175, in compute_value
records._compute_field_value(self)
File "/opt/openhrms/odoo/models.py", line 4061, in _compute_field_value
getattr(self, field.compute)()
File "/usr/lib/python3/dist-packages/odoo/addons/auth_totp/models/res_users.py", line 43, in _compute_totp_enabled
r.totp_enabled = bool(v.totp_secret)
File "/opt/openhrms/odoo/fields.py", line 1002, in get
_("(Record: %s, User: %s)") % (record, env.uid),
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 294, in execute
application_iter = app(environ, start_response)
File "/opt/openhrms/odoo/service/server.py", line 440, in app
return self.app(e, s)
File "/opt/openhrms/odoo/service/wsgi_server.py", line 124, in application
return application_unproxied(environ, start_response)
File "/opt/openhrms/odoo/service/wsgi_server.py", line 99, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/opt/openhrms/odoo/http.py", line 1295, in call
return self.dispatch(environ, start_response)
File "/opt/openhrms/odoo/http.py", line 1263, in call
return self.app(environ, start_wrapped)
File "/usr/local/lib/python3.7/dist-packages/werkzeug/middleware/shared_data.py", line 220, in call
return self.app(environ, start_response)
File "/opt/openhrms/odoo/http.py", line 1468, in dispatch
result = ir_http._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch return super(Http, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
return super(IrHttp, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
response = super(IrHttp, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 508, in _dispatch
result = super(IrHttp, cls)._dispatch()
File "/opt/openhrms/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
return cls._handle_exception(e)
File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception response = super(IrHttp, cls)._handle_exception(exc)
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 598, in _handle_exception
return super(IrHttp, cls)._handle_exception(exception)
File "/opt/openhrms/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
return request._handle_exception(exception)
File "/opt/openhrms/odoo/http.py", line 744, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/opt/openhrms/odoo/http.py", line 315, in _handle_exception
raise exception.with_traceback(None) from new_cause
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: res.users(28,), User: 28) - - -

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
