### ISSUE TITLE
Odoo Enterprise on OpenShift Cluster

### ISSUE THREAD

**Issue by C-tof** [odoo/odoo#71848]
Impacted versions: 13 Enterprise version

Steps to reproduce: Deploying Odoo On OC

- Build an image of Odoo with this Dockerfile : 
FROM odoo:13
COPY {addons local directory} /mnt/extra-addons/
COPY {filestore file name} /var/lib/odoo/filestore/

- When access the URL and logon we have this error : 
Retraçage :
Error: QWeb2: Template 'HomeMenu' not found
    at Object.exception ({url}/web/content/127885-faa7430/web.assets_common.js:3692:7)
    at Engine._render ({url}/web/content/127885-faa7430/web.assets_common.js:3737:103)
    at Engine.render ({url}/web/content/127885-faa7430/web.assets_common.js:3733:151)
    at Class.renderElement ({url}/web/content/127885-faa7430/web.assets_common.js:4097:1178)
    at {url}/web/content/127885-faa7430/web.assets_common.js:4107:6
    at async Promise.all (index 0)

**Comment by pedrobaeza** [comment]
Hi, this issue is related to your deployment method, so unless you find something that is impacting in the code for that, this can't be considered an issue for this tracker, so closing meanwhile.

**Comment by C-tof** [comment]
Thanks for your reply
