### ISSUE TITLE
[14.0] Server Error while creating the Invoiving

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#72226]
Impacted versions:
14.0

Steps to reproduce:
1. Log in as Admin
2. Navigate to Invoicing
3. Click to Create

Current behavior:
It throws the Server Error.

Expected behavior:
It'll not be thrown any errors.

Error Info:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/addons/account/models/account_move.py", line 1059, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/models.py", line 6230, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/models.py", line 5986, in _onchange_eval
    method_res = method(self)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/addons/account/models/account_move.py", line 384, in _onchange_journal
    if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/addons/account/models/sequence_mixin.py", line 176, in _get_last_sequence
    self.env.cr.execute(query, param)
  File "<decorator-gen-3>", line 2, in execute
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/trail/Windows/Web14/dev/trail-web/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.InvalidRegularExpression: invalid regular expression: quantifier operand invalid
```

Actual Query:
```
UPDATE account_move SET write_date = write_date WHERE id = (
                SELECT id FROM account_move
                WHERE journal_id = 1 AND name != '/' AND sequence_prefix !~ '^(?:.*?)(?:((?<=\D)|(?<=^))((20|21)?\d{2}))(?:\D+?)$'  AND move_type NOT IN ('out_refund', 'in_refund') 
                AND sequence_prefix = (SELECT sequence_prefix FROM account_move WHERE journal_id = 1 AND name != '/' AND sequence_prefix !~ '^(?:.*?)(?:((?<=\D)|(?<=^))((20|21)?\d{2}))(?:\D+?)$'  AND move_type NOT IN ('out_refund', 'in_refund')  ORDER BY id DESC LIMIT 1)
                ORDER BY sequence_number DESC
                LIMIT 1
            )
            RETURNING name;
```

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Gokulakannanaj** [comment]
Thanks, @pedrobaeza ! After pulling the latest code it's working fine.
