### ISSUE TITLE
Could not uninstall crm : Record does not exist or has been deleted (Record: ir.model.fields(9311,), User: 1)

### ISSUE THREAD

**Issue by Samadeva** [odoo/odoo#72378]
version : odoo 13.0.20210614
Repproduce : in Application, CRM App. > uninstall

Behavior :
image 1 in attach
Can t Unsintall : ERROR (image 1 in attach):
French : ('Enregistrement inexistant ou détruit.\n(Enregistrement: ir.model.fields(9311,), Utilisateur: 1)', None) 
English : Record does not exist or has been deleted (Record: ir.model.fields(9311,), User: 1)', None) 

Same Bug was reported several times but still not fixed : 
* image 2 in attach : https://github.com/odoo/odoo/issues/38008
* image 3 in attach

The Bug fix seems to be applied on v14 but not on v13 ? : https://github.com/odoo/odoo/commit/85c2a18dae3f31daad05f16053277d1b30a4bedb

Expected behavior :
Since there is no dependance in other modules, we should have the possibility and right to remove it (we don t need this App).
![CE_ 2021-06-18 à 18 22 52](https://user-images.githubusercontent.com/62155459/122594348-325b8680-d067-11eb-94b0-46925224d721.jpg)
![CE_ 2021-06-18 à 18 35 43](https://user-images.githubusercontent.com/62155459/122594365-3687a400-d067-11eb-90b9-55a996bf4542.jpg)
![CE_ 2021-06-18 à 18 33 07](https://user-images.githubusercontent.com/62155459/122594369-37b8d100-d067-11eb-91ef-12d1a1ae2bea.jpg)

****************          TRACEBACK             **************
2021-06-18 14:21:52,779 6 INFO samadeva-oerp-brstaging-2702918 odoo.addons.base.models.ir_module: ALLOW access to module.module_uninstall on ['sale_crm', 'crm_enterprise', 'crm_sms', 'website_crm', 'website_crm_sms', 'mass_mailing_crm', 'crm'] to user __system__ #1 via 86.243.106.83 
2021-06-18 14:21:52,800 6 WARNING samadeva-oerp-brstaging-2702918 odoo.modules.loading: Transient module states were reset 
2021-06-18 14:21:52,801 6 ERROR samadeva-oerp-brstaging-2702918 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/api.py", line 745, in get
def get(self, record, field, default=NOTHING):
value = self._data[field][record._ids[0]]
KeyError: 9311

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/fields.py", line 1037, in __get__
value = env.cache.get(record, self)
File "/home/odoo/src/odoo/odoo/api.py", line 751, in get
raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(9311,).model', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 494, in load_modules
Module.browse(modules_to_remove.values()).module_uninstall()
File "<decorator-gen-61>", line 2, in module_uninstall
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
return method(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 478, in module_uninstall
self.env['ir.model.data']._module_data_uninstall(modules_to_remove)
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 1898, in _module_data_uninstall
model = self.pool.get(ir_field.model)
File "/home/odoo/src/odoo/odoo/fields.py", line 1050, in __get__
_("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Enregistrement inexistant ou détruit.\n(Enregistrement: ir.model.fields(9311,), Utilisateur: 1)', None)
2021-06-18 14:21:52,803 6 WARNING samadeva-oerp-brstaging-2702918 odoo.http: ('Enregistrement inexistant ou détruit.\n(Enregistrement: ir.model.fields(9311,), Utilisateur: 1)', None) 
ENGLISH : Record does not exist or has been deleted (Record: ir.model.fields(9311,), User: 1)', None)

**Comment by Garibaldy** [comment]
i found this response [somewhere](https://stackoverflow.com/questions/68039070/odoo-v13-could-not-uninstall-crm-app-record-does-not-exist-or-has-been-delet) and was usefull  , `i have same problem and solved it witout code. Enable develop mode. Go to Settings->External Identifiers and find model = 'ir.model.fields' and res_id = and delete it`
