### ISSUE TITLE
[8.0] stock valuation history error if cost method is real

### ISSUE THREAD

**Issue by dhongu** [odoo/odoo#7239]
If cost method for all product are 'real' value  then we have the next error at stock report:
```
ProgrammingError: syntax error at or near ")"
LINE 1: ...oduct_price_history WHERE product_template_id in () AND date...
 ```
The error was introduced by this commit  (https://github.com/odoo/odoo/commit/55b7f15ee2427e4c99edf05a5a61b069a5395bab)

I find issue at line 66 
https://github.com/odoo/odoo/blob/8.0/addons/stock_account/wizard/stock_valuation_history.py#L66

I think the correct code is:
```python
            histories_dict = {}
            if cost_method_product_tmpl_ids:
                cr.execute("""SELECT DISTINCT ON (product_template_id, company_id) product_template_id, company_id, cost
                                 FROM product_price_history 
                                 WHERE product_template_id in %s AND datetime <= %s 
                                 ORDER BY product_template_id, company_id, datetime DESC""", 
                                 (tuple(cost_method_product_tmpl_ids), date))
                histories = cr.dictfetchall()           
                for history in histories:
                    histories_dict[(history['product_template_id'], history['company_id'])] = history['cost']
```

**Comment by felixlim10** [comment]
I'm also facing this problem.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/stock_account/wizard/stock_valuation_history.py", line 66, in read_group
    cr.execute('SELECT DISTINCT ON (product_template_id, company_id) product_template_id, company_id, cost FROM product_price_history WHERE product_template_id in %s AND datetime <= %s ORDER BY product_template_id, company_id, datetime DESC', (tuple(cost_method_product_tmpl_ids), date))
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 1: ...oduct_price_history WHERE product_template_id in () AND date...
                                                             ^
```

**Comment by dhongu** [comment]
fix by commit https://github.com/odoo/odoo/commit/ce0027a6d0e3ef9ac549c165bd3870a8e9dd1569
