### ISSUE TITLE
[8.0] hr_expense is not installable due to missing uom_id's in demo xml

### ISSUE THREAD

**Issue by mrgoetz** [odoo/odoo#7296]
The following steps led to the error message, see the error message at the bottom.
1. Checkout odoo 8 (head) on your server, start with an empty database, install Sales Management, 8.0.1.0
2. Try to install hr_expense and we see the error message, see below
3. Add uom_ids as indicated in the error message, example hr_expense_demo.xml

hr_expense_demo.xml:
...
        <record id="air_ticket" model="product.product">
            <field name="list_price">700.0</field>
            <field name="standard_price">700.0</field>
            <field name="type">service</field>
            <field name="name">Air Ticket</field>
            <field name="default_code">AT</field>
            <field name="uom_id" ref="product.product_uom_unit"/>
            <field name="categ_id" ref="hr_expense.cat_expense"/>
            <field name="hr_expense_ok" eval="True" />
            <field name="image" type="base64" file="hr_expense/static/img/air_ticket-image.jpg"/>
        </record>

```
    <record id="hotel_rent" model="product.product">
        <field name="list_price">400.0</field>
        <field name="type">service</field>
        <field name="name">Hotel Accommodation</field>
        <field name="default_code">HA0</field>
        <field name="uom_id" ref="product.product_uom_unit"/>
        <field name="categ_id" ref="hr_expense.cat_expense"/>
        <field name="hr_expense_ok" eval="True" />
        <field name="image" type="base64" file="hr_expense/static/img/hotel_rent-image.jpg"/>
    </record>
```

...
End of changes in hr_expense_demo.xml

Error message (part):
loading hr_expense/hr_expense_demo.xml
2015-06-25 13:14:05,022 7789 ERROR ini88 openerp.sql_db: bad query: INSERT INTO "product_template" ("id", "track_all", "list_price", "color", "mes_type", "uom_id", "uos_coeff", "sale_ok", "categ_id", "track_outgoing", "company_id", "uom_po_id", "type", "track_incoming", "active", "rental", "sale_delay", "name", "produce_delay", "sale_basis_qty", "track_production", "purchase_ok", "hr_expense_ok", "own_manufacturing", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('product_template_id_seq'), false, '700.00', 0, 'fixed', NULL, '1.000', true, 18, false, 1, 1, 'service', false, true, false, 7.0, 'Air Ticket', 1.0, '1.000', false, false, true, false, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/vagrant/work_actual4/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "uom_id" violates not-null constraint

2015-06-25 13:14:05,025 7789 CRITICAL ini88 openerp.service.server: Failed to initialize database `ini88`.
... 
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/vagrant/work_actual4/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/vagrant/work_actual4/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "uom_id" violates not-null constraint
" while parsing /home/vagrant/work_actual4/odoo/addons/hr_expense/hr_expense_demo.xml:21, near
<record id="air_ticket" model="product.product">
            <field name="list_price">700.0</field>
            <field name="standard_price">700.0</field>
            <field name="type">service</field>
            <field name="name">Air Ticket</field>
            <field name="default_code">AT</field>
            <field name="categ_id" ref="hr_expense.cat_expense"/>
            <field name="hr_expense_ok" eval="True"/>
            <field name="image" type="base64" file="hr_expense/static/img/air_ticket-image.jpg"/>
        </record>

**Comment by Yenthe666** [comment]
Hi @mrgoetz ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
