### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by Puhlik77** [odoo/odoo#73110]
Impacted versions:    14  community.
Windows  version.     

Steps to reproduce:    Tried to add custom field to the sale.order  view.  Field was created  properly in the  database,    but couldn't save     sale.order.tree     view.    Error:     website_id   is not a proper filed  in sale.order    Tried  to reinstall   website   module ,    but  now  cannot  even  start the Odoo    insatnce. I'm not a  developer, but   have   Pycharm and   PGadmin installed    and can  perform some changes  write  some  basic  code.  Any help would be  appreciated
Regards,   Alex B.           

Error to render compiling AST
AttributeError: 'website' object has no attribute 'sale_get_order'
Template: website_sale.header_cart_link
Path: /t/t[1]
Node: <t t-set="website_sale_order" t-value="website.sale_get_order()"/>
        
The error occured while rendering the template website_sale.header_cart_link and evaluating the following expression: <t t-set="website_sale_order" t-value="website.sale_get_order()"/>  

Traceback (most recent call last):
  File "C:\Program Files\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\server\odoo\http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\server\odoo\addons\website\controllers\main.py", line 79, in index
    website_page = request.env['ir.http']._serve_page()
  File "C:\Program Files\server\odoo\addons\website\models\ir_http.py", line 293, in _serve_page
    r = response.render()
  File "C:\Program Files\server\odoo\http.py", line 1235, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_ui_view.py", line 1709, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "C:\Program Files\server\odoo\addons\website\models\ir_ui_view.py", line 411, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "C:\Program Files\server\odoo\addons\web_editor\models\ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 333, in _compiled_fn
    raise e
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_homepage1_1136
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 333, in _compiled_fn
    raise e
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_1221
  File "<template>", line 291, in body_call_content_1201
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\server\odoo\http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\server\odoo\addons\website\controllers\main.py", line 79, in index
    website_page = request.env['ir.http']._serve_page()
  File "C:\Program Files\server\odoo\addons\website\models\ir_http.py", line 293, in _serve_page
    r = response.render()
  File "C:\Program Files\server\odoo\http.py", line 1235, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_ui_view.py", line 1709, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "C:\Program Files\server\odoo\addons\website\models\ir_ui_view.py", line 411, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "C:\Program Files\server\odoo\addons\web_editor\models\ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "C:\Program Files\server\odoo\addons\base\models\ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 333, in _compiled_fn
    raise e
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_homepage1_1136
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 333, in _compiled_fn
    raise e
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_1221
  File "<template>", line 291, in body_call_content_1201
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'website' object has no attribute 'sale_get_order'
Traceback (most recent call last):
  File "C:\Program Files\server\odoo\addons\base\models\qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_sale_header_cart_link_1333
AttributeError: 'website' object has no attribute 'sale_get_order'

Error to render compiling AST
AttributeError: 'website' object has no attribute 'sale_get_order'
Template: website_sale.header_cart_link
Path: /t/t[1]
Node: <t t-set="website_sale_order" t-value="website.sale_get_order()"/>

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue in existing code, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
