### ISSUE TITLE
14.0 - [BUG] base: Related-Stored-Translated field raises translation error

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#73192]
# Impacted versions:
 - Reproduced in 14.0 

# Steps to reproduce

1. Install `product` module:
    -  `odoo-bin -d product -i product`
2. Create a new product template using a lang not installed in the context set values for required columns and set an `uom_id`
   - **Notice that `uom_id` it is an related field to translated field.**
   - I just ran the following line of code in `odoo-bin shell`
```python
env['product.template'].with_context(lang='es_MX').create({'name': 'hi', 'uom_id': 1})
```

# Current behavior:

```txt
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<decorator-gen-145>", line 2, in create
  File "odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "addons/product/models/product_template.py", line 396, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-132>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-174>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "addons/website/models/mixins.py", line 169, in create
    records = super(WebsitePublishedMixin, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "odoo/models.py", line 4053, in _create
    Translations._set_ids(tname, 'model', self.env.lang, record.ids, val, val)
  File "odoo/addons/base/models/ir_translation.py", line 279, in _set_ids
    for res_id in set(ids) - set(existing_ids)
  File "<decorator-gen-58>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "odoo/addons/base/models/ir_translation.py", line 554, in create
    records = super(IrTranslation, self.sudo()).create(vals_list).with_env(self.env)
  File "<decorator-gen-64>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "odoo/models.py", line 4005, in _create
    cache_value = field.convert_to_cache(value, record)
  File "odoo/fields.py", line 2414, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.translation.lang: 'es_MX'
```

https://github.com/odoo/odoo/blob/878bf768f8542bdd4e3adcff03e51069f6630f5f/odoo/fields.py#L2414

You could think.
Are you crazy, Why are you using a non-installed lang in the context?
And I'm agree

But the website is set the lang of the browser (tested using firefox)

I print the `request.env.context` in the following line of code:
 - https://github.com/odoo/odoo/blob/878bf768f8542bdd4e3adcff03e51069f6630f5f/addons/payment/controllers/portal.py#L63

And it has `{'lang': 'es_MX'}`

So, if there is an "Related-Stored-Translated" field it will raise this error

# Expected behavior:

No error for "Related-Stored-Translated" field
Maybe, use the original value if the lang doesn't exists.

**Comment by moylop260** [comment]
@mart-e 

May I ask you to check this issue?

**Comment by mart-e** [comment]
> But the website is set the lang of the browser (tested using firefox)

This is the interesting part, you shouldn't have a lang that isn't installed in the context. To indentify where it's set and filter it with the `tools.misc.get_lang` method.

**Comment by moylop260** [comment]
@mart-e 

Thank you for quick reply

I just put a `print` in `tools.misc.get_lang` and it is using showing `en_US` for all cases

but is not the same for `models...with_context` method:
 - https://github.com/odoo/odoo/blob/5121506a0f05eb93df10caf860f12cf759aae201/odoo/models.py#L5084

It is showing `es_MX` only opening `/shop` URL for firefox
and `es_419` for chrome browser

We had a issue using lang from the browser even if they are not installed in v10.0:
 - https://github.com/odoo/odoo/issues/18363

@nim-odoo
Do you remember this weird case?
Is it a regression issue of:
 - https://github.com/odoo/odoo/commit/6879409723184ed360043b7a2da11fcd725e5c4f#commitcomment-24156078

**Comment by moylop260** [comment]
For record,

`OPW#2590687`
