### ISSUE TITLE
[14.0] Can't create products

### ISSUE THREAD

**Issue by MBadberg** [odoo/odoo#73228]
Impacted versions: Odoo 14

Steps to reproduce: Go to products, New Product, Fill in Name and click save.

Current behavior:
Error occurs:
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/models.py", line 6197, in onchange
    record = self.new(initial_values, origin=self)
  File "/opt/odoo14/odoo/odoo/models.py", line 5506, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo14/odoo/odoo/models.py", line 5148, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'brand_id' on model 'product.template'

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your installation, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot). Specifically, it seems you have tried to add something about brands.

I'm closing this issue now, but if you feel this can be something reproducible in standard setup., please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
