### ISSUE TITLE
bad database creation in the last Odoo pull

### ISSUE THREAD

**Issue by jcarlosmontoya** [odoo/odoo#7323]
i've done a git pull right now, i've tried do this command:
1: python openerp-server --config=/etc/odoo-server.conf (use other config file)
2: localhost:8069
3: from database manager: create a new database (with password) without demo data
4: and appear this: Unable to login on database "demo"
5 using pgadmin i see that there only "20"  tables help me please, ¿what happen?
if i try execute this command:
python openerp-server, the creation database  successfully.

regards.

log:

2015-06-26 17:36:58,546 5292 INFO None openerp.service.db: Create database `demo_db`.
#2015-06-26 17:36:59,336 5292 ERROR None openerp.sql_db: bad query: INSERT INTO ir_module_module                 (author, website, name, shortdesc, description,                     category_id, auto_install, state, web, license, application, icon, sequence, summary)                 VALUES ('Spanish Localization Team,AvanzOSC,Serv. Tecnol. Avanzados - Pedro M. Baeza,MálagaTIC,Grupo Vermon,Odoo Community Association (OCA)', 'https://github.com/OCA/l10n-spain', 'l10n_es_aeat_mod111', 'AEAT modelo 111', 'Presentación del Modelo AEAT 111

Modelo 111 de la AEAT. Retenciones e ingresos a cuenta. Rendimientos del
trabajo y de actividades económicas, premios y determinadas ganancias
patrimoniales e imputaciones de Renta. Autoliquidación.
# Problemas conocidos / Hoja de ruta
- Permitir periodos trimestrales.
# Créditos
## Contribuidores
- MálagaTIC (http://www.malagatic.com)
- Carlos Sánchez Cifuentes csanchez@grupovermon.com
- Pedro M. Baeza pedro.baeza@serviciosbaeza.com
- AvanzOSC (http://www.avanzosc.es)
## Maintainer

.. image:: http://odoo-community.org/logo.png
   :alt: Odoo Community Association
   :target: http://odoo-community.org

This module is maintained by the OCA.

OCA, or the Odoo Community Association, is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

To contribute to this module, please visit http://odoo-community.org.
', 34, false, 'uninstalled', false, 'AGPL-3', false, '/l10n_es_aeat_mod111/static/description/icon.png', 100, '') RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: value too long for type character varying(128)

2015-06-26 17:36:59,337 5292 ERROR None openerp.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/service/db.py", line 37, in _initialize_db
    openerp.modules.db.initialize(cr)
  File "/opt/odoo/odoo/openerp/modules/db.py", line 86, in initialize
    info['sequence'], info['summary']))
  File "/opt/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: value too long for type character varying(128)

2015-06-26 17:36:59,340 5292 INFO demo_db openerp.modules.loading: loading 1 modules...
2015-06-26 17:36:59,349 5292 INFO demo_db openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2015-06-26 17:36:59,509 5292 INFO demo_db openerp.modules.loading: Modules loaded.
2015-06-26 17:36:59,511 5292 INFO demo_db openerp.addons.base.res.res_users: Login failed for db:demo_db login:admin
2015-06-26 17:36:59,512 5292 INFO demo_db werkzeug: 127.0.0.1 - - [26/Jun/2015 17:36:59] "POST /web/database/create HTTP/1.1" 200 -
2015-06-26 17:36:59,525 5292 INFO demo_db openerp.addons.base.ir.ir_http: Generating routing map
2015-06-26 17:36:59,557 5292 INFO demo_db werkzeug: 127.0.0.1 - - [26/Jun/2015 17:36:59] "GET /web HTTP/1.1" 200 -
2015-06-26 17:36:59,606 5292 INFO demo_db werkzeug: 127.0.0.1 - - [26/Jun/2015 17:36:59] "GET /web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fweb%3F HTTP/1.1" 303 -
2015-06-26 17:36:59,625 5292 INFO None werkzeug: 127.0.0.1 - - [26/Jun/2015 17:36:59] "GET /web/database/selector?error=Unable%20to%20login%20on%20database%20demo_db HTTP/1.1" 200 -
2015-06-26 17:37:53,281 5292 WARNING demo_db openerp.addons.base.ir.ir_cron: Skipping database demo_db as its base version is not 8.0.1.3.
2015-06-26 17:37:53,283 5292 WARNING demo_db openerp.addons.base.ir.ir_cron: Skipping database demo_db as its base version is not 8.0.1.3.

config file:

[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = demo
addons_path = /opt/odoo/odoo/addons
logfile = /var/log/odoo/odoo-server.log

**Comment by Doopin** [comment]
Having the same issue as @cellsnake .
Anyone help :/

**Comment by yustas147** [comment]
This problem possibly due to wrong\corrupted module in your addons path. Try to start odoo server with original modules, try to create database and watch if problem persists.

**Comment by Yenthe666** [comment]
Hi @jcarlosmontoya,

Thanks a lot for your bug report.
I was no longer able to reproduce this though, I'm assuming something in the configuration was wrong.

Regards,
Yenthe
