### ISSUE TITLE
[8.0][API/Cache] - api.depends fails due to KeyError

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#7326]
## Impacted versions:

8.0 and above
## Steps to reproduce:
- Create a binary field on an inherited model with the attributes `store=True` `compute='_computation'` and `readonly=True` (model is inherited based on the new API)
- Computation should simply provide the value which will be stored (for example a barcode image to the current ean13)
- Use the snippet given below, namely to assign a method with a return value to self.attribute (finding as triggering issue).
- Update or install the module and wait for the exception when Odoo tries to initially store the computed values
## Current behavior:
- Exception
- It does work later when I do trigger the api.depends('ean13') via form view.

``` python

2015-06-27 16:40:23,870 31720 INFO odoo openerp.modules.module: module dummy_module: creating or updating database tables
2015-06-27 16:40:24,178 31720 INFO odoo openerp.models: Storing computed values of product.product fields ean_image, qr_image
Traceback (most recent call last):
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/deploy/odoo-stable/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/deploy/odoo-stable/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/deploy/odoo-stable/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/addons/base/module/module.py", line 537, in button_immediate_upgrade
    return self._button_immediate_function(cr, uid, ids, self.button_upgrade, context=context)
  File "/home/odoo/deploy/odoo-stable/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/deploy/odoo-stable/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/deploy/odoo-stable/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/deploy/odoo-stable/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/deploy/odoo-stable/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/odoo/deploy/odoo-stable/openerp/modules/module.py", line 297, in init_module_models
    t[1](cr, *t[2])
  File "/home/odoo/deploy/odoo-stable/openerp/models.py", line 2697, in func
    recs.recompute()
  File "/home/odoo/deploy/odoo-stable/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/deploy/odoo-stable/openerp/models.py", line 5687, in recompute
    name: rec[name] for name in names
  File "/home/odoo/deploy/odoo-stable/openerp/models.py", line 5687, in <dictcomp>
    name: rec[name] for name in names
  File "/home/odoo/deploy/odoo-stable/openerp/models.py", line 5571, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/deploy/odoo-stable/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/home/odoo/deploy/odoo-stable/openerp/models.py", line 5932, in __getitem__
    value = self._recs.env.cache[field][self._recs.id]
KeyError: 915

```
## Expected behavior:
- Proper initialization of the images based on the ean13 or an empty binary field in case there is no ean13

@rco-odoo 
I guess this is something for you...I hope you can reproduce easily...

Here the code of the use case which fails

``` python
class product_product(models.Model):
    _inherit = 'product.product'

    ean_image = fields.Binary(
        string="EAN13 Image",
        compute="_compute_barcode_image",
        store=True, readonly=True,
        copy=False,
    )
    qr_image = fields.Binary(
        string="QR Image",
        compute="_compute_barcode_image",
        store=True, readonly=True,
        copy=False,
    )

    @api.one
    @api.depends('ean13', 'name', 'product_tmpl_id.name', 'description_sale')
    def _compute_barcode_image(self):

        def create_barcode(barcode_type, value, width, height, humanreadable):
            return createBarcodeDrawing(
                barcode_type, value=value, format='png', width=width, height=height,
                humanReadable=humanreadable
            ).asString('png').encode('base64')

        if self.ean13 and check_ean(self.ean13):
            self.ean_image = create_barcode('EAN13', self.ean13, 500, 200, 1) <------- ISSUE TRIGGER

        qr_content = '%s\n%s\n%s\n\n%s' % (self.with_context(lang=self.env.user.lang).name, self.company_id.website, self.with_context(lang=self.env.user.lang).uom_id.name, self.description_sale or '')
        self.qr_image = create_barcode('QR', qr_content, 300, 300, 1) <------- ISSUE TRIGGER
```

OPW-643532

**Comment by wtaferner** [comment]
@rco-odoo 
Seems I found out myself what the issue was, although I am not sure if it is glass clear to avoid such an implementation or not, but maybe you can improve the magic that this kind of pitfall might not happen to others. Anyway, I blame myself ;-)

The code below does work smoothly...so first retrieve the value and assign it via a variable but not assigning the method itself and expecting the return value is applied.

```python
        ean_image = False
        if self.ean13 and check_ean(self.ean13):
            ean_image = create_barcode('EAN13', self.ean13, 500, 200, 1)

        qr_content = '%s\n%s\n%s\n\n%s' % (self.with_context(lang=self.env.user.lang).name, self.company_id.website, self.with_context(lang=self.env.user.lang).uom_id.name, self.description_sale or '')
        qr_image = create_barcode('QR', qr_content, 300, 300, 1)

        self.ean_image = ean_image
        self.qr_image = qr_image
```

**Comment by beledouxdenis** [comment]
I am not sure why assigning the method result to a variable would solve the issue.

Could you share the entire code that works ?

Anyway, this is a cache problem, that's for sure :).

**Comment by wtaferner** [comment]
Thank you for confirmation on your side. the lower code is fully working (so all code shared I would say - put it together underneath).

I guess it is working b/c the local function result is evaluated and assigned to the variable and therefore the pure value is being passed to self.attribute instead of the function itself which is not evaluated before the magic happens - direct write although is it really intended here? b/c based on this I should say ```self.write({'ean_image': ean_image, 'qr_image': qr_image})``` instead of doing two queries...not finding out yet...I guess Raphael can explain it better and will fix what needs to be fixed if so :-)

```python
class product_product(models.Model):
    _inherit = 'product.product'

    ean_image = fields.Binary(
        string="EAN13 Image",
        compute="_compute_barcode_image",
        store=True, readonly=True,
        copy=False,
    )
    qr_image = fields.Binary(
        string="QR Image",
        compute="_compute_barcode_image",
        store=True, readonly=True,
        copy=False,
    )

    @api.one
    @api.depends('ean13', 'name', 'product_tmpl_id.name', 'description_sale')
    def _compute_barcode_image(self):

        def create_barcode(barcode_type, value, width, height, humanreadable):
            return createBarcodeDrawing(
                barcode_type, value=value, format='png', width=width, height=height,
                humanReadable=humanreadable
            ).asString('png').encode('base64')

        ean_image = False
        if self.ean13 and check_ean(self.ean13):
            ean_image = create_barcode('EAN13', self.ean13, 500, 200, 1)

        qr_content = '%s\n%s\n%s\n\n%s' % (self.with_context(lang=self.env.user.lang).name, self.company_id.website, self.with_context(lang=self.env.user.lang).uom_id.name, self.description_sale or '')
        qr_image = create_barcode('QR', qr_content, 300, 300, 1)

        self.ean_image = ean_image
        self.qr_image = qr_image
```

**Comment by wtaferner** [comment]
@rco-odoo 
Hi Raphael,
just stumbled across another key error...may I ask you to take a look and try to find a solution together...as it is already a trial and error approach [here](https://github.com/odoo/odoo/blob/8.0/openerp/fields.py#L809) I hope that you can just improve the coverage as it is horrible to debug?

The upper use case is one scenario and now I have a scenario where obviously a dependency computation triggers the key error in a certain situation whereas normally there is no issue.

**Comment by michaelkarrer81** [comment]
I may stumbled across the same error but for a different scenario: At Issue #8773

**Comment by flotho** [comment]
Same problem for me, executing signal_workflow in a @api.depends method causes keyerror

**Comment by bringsvor** [comment]
Got the same error here. After reading the investigations in this issue I found that I had a computed field (not stored) that depended upon another computed field (not stored either). The field that was depended upon was a m2o field. Anyway, things worked fine when I was logged in as admin, but when I was my own user I got the KeyError. Removing the depends decorator solved the problem for me.
