### ISSUE TITLE
[Bug/8.0] Website Email Designer - Language change error

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#7395]
Steps to reproduce:
1. Install modules: email_template, website
2. Translations -> Load a Translation - Load additional lanuage
3. Technical -> Email -> Templates -> Choose any email template
4. Click on 'Edit Template' button
5. Try to change language
6. Error message: index() takes at least 3 arguments (2 given)

Traceback (most recent call last):
  File "/home/grzegorz/Pulpit/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/grzegorz/Pulpit/odoo/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/grzegorz/Pulpit/odoo/openerp/addons/base/ir/ir_http.py", line 173, in _dispatch
    result = request.dispatch()
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 684, in dispatch
    r = self._call_function(*_self.params)
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/grzegorz/Pulpit/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/grzegorz/Pulpit/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
TypeError: index() takes at least 3 arguments (2 given)

**Comment by Yenthe666** [comment]
Hi @grzekru,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
