### ISSUE TITLE
AssertionError: The report "report.sale.shipping" already exists!

### ISSUE THREAD

**Issue by fleurykoyo** [odoo/odoo#7424]
I have reinstall the "delivery" addons to OpenErp  and l have this error. Can you help me with that?

Client Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\http.py", line 204, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\controllers\main.py", line 864, in authenticate
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\session.py", line 115, in authenticate
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\session.py", line 30, in proxy_method
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\session.py", line 103, in send

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\netsvc.py", line 296, in dispatch_rpc
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\service\web_services.py", line 433, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\service\web_services.py", line 444, in exp_authenticate
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\pooler.py", line 49, in get_pool
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\pooler.py", line 33, in get_db_and_pool
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\registry.py", line 203, in get
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\registry.py", line 233, in new
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\loading.py", line 350, in load_modules
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\loading.py", line 256, in load_marked_modules
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\loading.py", line 159, in load_module_graph
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\module.py", line 405, in load_openerp_module
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\delivery__init__.py", line 24, in <module>
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\delivery\report__init__.py", line 22, in <module>
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server\openerp\addons\delivery\report\shipping.py", line 33, in <module>
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\report\report_sxw.py", line 390, in **init**
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\report\interface.py", line 65, in **init**
  File "C:\Program Files\OpenERP 7.0-20140622-231040\Server\server.\openerp\report\interface.py", line 45, in **init**
AssertionError: The report "report.sale.shipping" already exists!

**Comment by Yenthe666** [comment]
Hi @fleurykoyo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
