### ISSUE TITLE
newly created users gets "Internal Server Error"

### ISSUE THREAD

**Issue by netdur** [odoo/odoo#7475]
Hello,

Odoo works fine for old users, the newly created users can successfully log in but always face

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

the command "tail -f /var/log/odoo/odoo-server.log" says

```
2015-07-06 11:32:49,621 719 ERROR a-t werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 285, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1435, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 177, in _dispatch
    return self._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 665, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 173, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 683, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 477, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, context=request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in load_menus

  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_menu.py", line 381, in load_menus
    menu_root_ids = self.get_user_roots(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_menu.py", line 355, in get_user_roots
    return self.search(cr, uid, menu_domain, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mail/mail_group_menu.py", line 42, in search
    context=context, count=False)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_menu.py", line 128, in search
    result = self._filter_visible_menus(cr, uid, ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_menu.py", line 85, in _filter_visible_menus
    action_menus = menus.filtered('action')
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5378, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5377, in <lambda>
    func = lambda rec: filter(None, rec.mapped(name))
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5353, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5337, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5571, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5931, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for ir.ui.menu(2,).action')

```

**Comment by eovolkov** [comment]
Hi, I have the same issue

2015-07-29 11:18:50,994 30711 DEBUG db_sphereinc openerp.addons.auth_ldap.users_ldap: Creating new Odoo user "exampleuser" from LDAP
2015-07-29 11:18:51,330 30711 ERROR db_sphereinc openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/addons/website/models/ir_http.py", line 198, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 677, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/auth_oauth/controllers/main.py", line 94, in web_login
    response = super(OAuthLogin, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/auth_signup/controllers/main.py", line 38, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/website/controllers/main.py", line 52, in web_login
    return super(Website, self).web_login(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 509, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 960, in authenticate
    if uid: self.get_context()
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 995, in get_context
    self.context = request.registry.get('res.users').context_get(request.cr, request.uid) or {}
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py", line 402, in context_get
    return self._context_get(cr, uid)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in _context_get
  File "/usr/lib/python2.7/site-packages/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py", line 395, in _context_get
    res = getattr(user, k) or False
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5931, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')

2015-07-29 11:18:51,359 30711 INFO db_sphereinc werkzeug: 127.0.0.1 - - [29/Jul/2015 11:18:51] "POST /web/login HTTP/1.0" 500 -

**Comment by Yenthe666** [comment]
Hi @netdur,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
