### ISSUE TITLE
osv/expression.py line 827 uses column before check for null in 858

### ISSUE THREAD

**Issue by DavidGoodenough** [odoo/odoo#7480]
line 827 uses column._type and of course if column is null then NullType does not have an _type attribute and fails.  Either the if at 827 (and 832 and 843 and 846 and 852) need to check for column being null or the test at 858 needs to be moved before 827.

This keeps hitting people using slmoebius's builder slmoebius/builder#13.  Quite why it should trigger this bug while normal Odoo operations do not I do not know, but this needs fixing as it is obviously wrong.

**Comment by xmo-odoo** [comment]
> Quite why it should trigger this bug while normal Odoo operations do not I do not know

From the conditions, it looks like this would require a search on a sub-field (so the "field path" has a length of 2+) of a new-API computed non-stored field (so there is no column). Which I'm not sure makes any sense given it is not handled at all by computed fields (both new API and old API versions ignore the field path entirely, so they don't tell the search function that there is any "subfield" involved).

The conditions could be shuffled around to make the error disappear, but it really looks like the domain is broken/unsupported and the actual fix would be to raise a clearer error /cc @mart-e

**Comment by matheo** [comment]
I'm trying to search a computed non-stored field and I'm getting an error.
It seems to me that some logic is wrong, because querying the list and showing the computed field value works fine and fast, but searching the computed field gives this kind of "infinite loop":
```
2016-12-26 04:30:44,867 2521 INFO odoo odoo.service.server: Worker (2521) CPU time limit (60) reached.
2016-12-26 04:30:44,880 2521 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "addons/web/controllers/main.py", line 804, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "addons/web/controllers/main.py", line 826, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "odoo/models.py", line 4645, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "odoo/models.py", line 1504, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "odoo/models.py", line 4191, in _search
    query = self._where_calc(args)
  File "odoo/models.py", line 3990, in _where_calc
    e = expression.expression(domain, self)
  File "odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "odoo/osv/expression.py", line 823, in parse
    elif field.inherited:
  File "odoo/service/server.py", line 686, in time_expired
    raise Exception('CPU time limit exceeded.')
Exception: CPU time limit exceeded.
```

**Comment by pedrobaeza** [comment]
As the API has changed and the compatibility layer with old one has been removed in latest versions, this doesn't apply anymore. If the problem is still present in new version, please open a new issue.
