### ISSUE TITLE
ProgrammingError: no existe la columna mail_message.same_thread

### ISSUE THREAD

**Issue by jhg** [odoo/odoo#749]
When I login I have it error:
OpenERP Server Error
Traceback (most recent call last):
  File "./openerp/http.py", line 462, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "./openerp/http.py", line 481, in dispatch
    result = self._call_function(**self.params)
  File "./openerp/http.py", line 297, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "./openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "./openerp/http.py", line 294, in checked_call
    return self.endpoint(*a, **kw)
  File "./openerp/http.py", line 671, in __call__
    return self.method(*args, **kw)
  File "./openerp/http.py", line 346, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/openerp/addons/web/controllers/main.py", line 1046, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/openerp/openerp/addons/web/controllers/main.py", line 1038, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/openerp/openerp/addons/mail/mail_message.py", line 557, in message_read
    while parent.parent_id and parent.parent_id.id != parent_id:
  File "./openerp/osv/orm.py", line 505, in __getattr__
    return self[name]
  File "./openerp/osv/orm.py", line 408, in __getitem__
    field_values = self._table.read(self._cr, self._uid, ids, field_names, context=self._context, load="_classic_write")
  File "/home/openerp/openerp/addons/mail/mail_message.py", line 817, in read
    res = super(mail_message, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "./openerp/osv/orm.py", line 3355, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "./openerp/osv/orm.py", line 3404, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "./openerp/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "./openerp/sql_db.py", line 230, in execute
    res = self._obj.execute(query, params)
ProgrammingError: no existe la columna mail_message.same_thread
LINE 1: SELECT mail_message."body",mail_message."model",mail_message...

**Comment by Yenthe666** [comment]
Dear @jhg,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
