### ISSUE TITLE
[8.0] UnicodeDecodeError: Named of archives with special characters

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#7509]
Steps to reproduce:
1. Add a special character to one file of some module of `addons-path`
   e.g. mkdir "sale/doc/special_char_ñ"
2. Start services and try install this module.
   e.g. odoo.py -d odoo -i sale

Current behavior:

``` python
2015-07-07 18:43:54,369 139 CRITICAL openerp_template openerp.service.server: Failed to initialize database `openerp_template`.
Traceback (most recent call last):
  File "/root/odoo-8.0/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/root/odoo-8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/odoo-8.0/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/root/odoo-8.0/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/root/odoo-8.0/openerp/modules/loading.py", line 126, in load_module_graph
    migrations = openerp.modules.migration.MigrationManager(cr, graph)
  File "/root/odoo-8.0/openerp/modules/migration.py", line 68, in __init__
    self._get_files()
  File "/root/odoo-8.0/openerp/modules/migration.py", line 83, in _get_files
    self.migrations[pkg.name]['module'] = get_module_filetree(pkg.name, 'migrations') or {}
  File "/root/odoo-8.0/openerp/modules/module.py", line 144, in get_module_filetree
    files = openerp.tools.osutil.listdir(path, True)
  File "/root/odoo-8.0/openerp/tools/osutil.py", line 46, in listdir
    for root, dirs, files in walksymlinks(dir):
  File "/root/odoo-8.0/openerp/tools/osutil.py", line 56, in walksymlinks
    for dirpath, dirnames, filenames in os.walk(top, topdown, onerror):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

Expected behavior:
- modules loaded

[video](https://asciinema.org/a/22749)

NOTE: You can reproduce it in a cleaned environment e.g. docker of odoo (docker pull odoo)

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
