### ISSUE TITLE
[V14]XMLRPC cannot unmarshal frozendict

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#75412]
### Impacted  versions:
v14
tested with demo 

### Steps to reproduce:

call the context_get method on res.users

### Current behavior:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/controllers/rpc.py", line 69, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/controllers/rpc.py", line 50, in _xmlrpc
    return dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 968, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 519, in __dump
    raise TypeError("cannot marshal %s objects" % type(value))
TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects
```

this is mainly caused by this part https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/res_users.py#L649

### Expected behavior:

As for v12 and v13, the context values has to be returned.

**Comment by flotho** [comment]
jsonrpc don't seems to be impacted

**Comment by flotho** [comment]
Here is a simple script based on the officla documentation for executing method throught XMLRPC :

```
import xmlrpc.client
info = xmlrpc.client.ServerProxy('https://demo.odoo.com/start').start()
url, db, username, password = \
    info['host'], info['database'], info['user'], info['password']
     
common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(url))
uid = common.authenticate(db, username, password, {})

models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))
# This one throw the error
# context_get = models.execute_kw(db, uid, password,
#     'res.users', 'context_get', [])

# This one also throw the error
context_get = models.execute(db, uid, password,
     'res.users', 'context_get')
```
