### ISSUE TITLE
[9.0Alpha] Fresh Install Database Creation Fail's when setting language as English (UK)

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#7587]
Tried installing in English UK it show's the following error (INSTALLING IN ENGLISH US WORKS NORMALLY).

2015-07-13 14:56:46,108 17964 ERROR holdings openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 313, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 814, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 725, in create
    request.session.authenticate(params['db_name'], 'admin', params['create_admin_pwd'])
  File "/opt/odoo/openerp/http.py", line 967, in authenticate
    uid = dispatch_rpc('common', 'authenticate', [db, login, password, env])
  File "/opt/odoo/openerp/http.py", line 117, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/common.py", line 26, in dispatch
    return fn(*params)
  File "/opt/odoo/openerp/service/common.py", line 37, in exp_authenticate
    res_users = openerp.registry(db)['res.users']
  File "/opt/odoo/openerp/__init__.py", line 50, in registry
    return modules.registry.RegistryManager.get(database_name)
  File "/opt/odoo/openerp/modules/registry.py", line 318, in get
    update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 349, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 277, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 865, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 952, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 815, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 818, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 722, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1046, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_users.py", line 728, in create
    self.update_user_groups_view(cr, uid, context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_users.py", line 780, in update_user_groups_view
    view.write({'arch': xml_content})
  File "/opt/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 528, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 363, in write
    context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3729, in write
    self._write(old_vals)
  File "/opt/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 528, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3885, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/openerp/osv/fields.py", line 1480, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 179, in _arch_set
    self.write(cr, uid, ids, data, context=context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 363, in write
    context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3729, in write
    self._write(old_vals)
  File "/opt/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 528, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3823, in _write
    raise UserError(_("You cannot update the translated value of field '%s'") % flabel)
ParseError: "You cannot update the translated value of field 'Arch Blob'
None" while parsing /opt/odoo/openerp/addons/base/res/res_security.xml:5, near
<record model="res.groups" id="group_partner_manager">
            <field name="name">Contact Creation</field>
        </record>
2015-07-13 14:56:46,112 17964 INFO holdings werkzeug: 127.0.0.1 - - [13/Jul/2015 14:56:46] "POST /web/database/create HTTP/1.0" 200 -

**Comment by AidenAndrews** [comment]
Similar Issue Found issue reference is https://github.com/odoo/odoo/issues/7573

**Comment by zchking** [comment]
same issue

**Comment by katyukha** [comment]
Seems to be same problem #7702

**Comment by Vassy** [comment]
same issue

**Comment by rco-odoo** [comment]
Fixed by revision f84c375c.
