### ISSUE TITLE
Cannot open website since install website_report module

### ISSUE THREAD

**Issue by dalejsa** [odoo/odoo#7611]
Hi

I installed the website_report module today then restarted the server and now I cannot access anything from the browser at all. I am getting lots of errors. Now I can only use the command line as I can't log in to uninstall the module or update it. What can I do? I have tried to update that module but it has had no effect. Below are my errors:

Really appreciate any help. Thanks

Terminal errors when starting the server are below and the website errors beneath that:

2015-07-14 13:10:53,848 1254 INFO ? openerp: OpenERP version 8.0
2015-07-14 13:10:53,848 1254 INFO ? openerp: addons paths: ['/opt/odoo/.local/sh                                                                                        are/Odoo/addons/8.0', u'/opt/odoo/addons', '/opt/odoo/openerp/addons']
2015-07-14 13:10:53,849 1254 INFO ? openerp: database hostname: localhost
2015-07-14 13:10:53,849 1254 INFO ? openerp: database port: 5432
2015-07-14 13:10:53,850 1254 INFO ? openerp: database user: odoo
2015-07-14 13:10:54,031 1254 INFO ? openerp.service.server: HTTP service (werkze                                                                                        ug) running on 0.0.0.0:8069
2015-07-14 13:10:54,045 1254 INFO Sales_Hire openerp.modules.loading: loading 1                                                                                         modules...
2015-07-14 13:10:54,225 1254 INFO Sales_Hire openerp.modules.loading: 1 modules                                                                                         loaded in 0.18s, 0 queries
2015-07-14 13:10:54,400 1254 INFO Sales_Hire openerp.modules.loading: loading 44                                                                                         modules...
2015-07-14 13:10:54,406 1254 INFO Sales_Hire passlib.registry: registered crypt                                                                                         handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2015-07-14 13:10:54,407 1254 INFO Sales_Hire passlib.registry: registered crypt                                                                                         handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2015-07-14 13:10:54,470 1254 INFO ? openerp.addons.bus.bus: Bus.loop listen imbu                                                                                        s on db postgres
2015-07-14 13:10:54,478 1254 INFO Sales_Hire openerp.addons.report.models.report                                                                                        : Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2015-07-14 13:10:55,384 1254 INFO Sales_Hire openerp.modules.loading: 44 modules                                                                                         loaded in 0.98s, 0 queries
2015-07-14 13:10:56,023 1254 INFO Sales_Hire openerp.modules.loading: Modules lo                                                                                        aded.
2015-07-14 13:11:06,515 1254 INFO ? werkzeug: 105.237.210.67 - - [14/Jul/2015 13:11:06] "GET / HTTP/1.1" 500 -
2015-07-14 13:11:06,524 1254 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1279, in __call__
    self.load_addons()
  File "/opt/odoo/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/auto_backup/__init__.py", line 23, in <module>
    import backup_scheduler
  File "/opt/odoo/.local/share/Odoo/addons/8.0/auto_backup/backup_scheduler.py", line 33, in <module>
    raise ImportError('This module needs pysftp to automaticly write backups to the FTP through SFTP. Please install pysftp on your system. (sudo pip install pysftp)')
ImportError: This module needs pysftp to automaticly write backups to the FTP through SFTP. Please install pysftp on your system. (sudo pip install pysftp)

Website errors:
Could not get content for /web/static/lib/boostrap/css/bootstrap.css defined in bundle 'website.assets_frontend'

Could not get content for /website/static/src/css/website.css defined in bundle 'website.assets_frontend'

Could not get content for /website_mail/static/src/css/website_mail.css defined in bundle 'website.assets_frontend'

Could not get content for /web_graph_static/src/css/nv.d3.css defined in bundle 'website.assets_frontend'

Could not get content for /survey/static/src/css/survey_results.css defined in bundle 'website.assets_frontend'

**Comment by dalejsa** [comment]
Hi All

I found the problem. It seems that another user installed an autobackup module which needed more work. I hadn't restarted the server in a very long time so when i  installed the new module and restarted i assumed the problem was with the new module. Thanks for all the input!

**Comment by Yenthe666** [comment]
@dalejsa can you close this issue if its fixed by yourself and not related to Odoo itself?

**Comment by rim-odoo** [comment]
Assuming problem is solved and thus closing this issue. Feel free to reopen one if there are new problems :)
