### ISSUE TITLE
[POS] Runtime error when using Advance Pricelist and Employee log in

### ISSUE THREAD

**Issue by andrp92** [odoo/odoo#76783]
Impacted versions:
13.0
Steps to reproduce:
Use Bar POS on runbot (https://10015412-13-0-all.runbot55.odoo.com/pos/web?config_id=2#action=pos.ui&cids=1)
Configure log in with employees
Configure advance pricelist and choose a couple of them
Sale a product and choose a pricelist different from default one
Lock de POS (top right corner)
Try to access with any employee

Current behavior:
Traceback:
TypeError: Cannot read properties of null (reading 'pricelist')
    at Class.is_selected (https://10015412-13-0-all.runbot55.odoo.com/point_of_sale/static/src/js/screens.js:2562:61)
    at eval (eval at _render (https://10015412-13-0-all.runbot55.odoo.com/web/static/lib/qweb/qweb2.js:469:33), <anonymous>:20:105)
    at Object.foreach (https://10015412-13-0-all.runbot55.odoo.com/web/static/lib/qweb/qweb2.js:180:25)
    at Engine.eval (eval at _render (https://10015412-13-0-all.runbot55.odoo.com/web/static/lib/qweb/qweb2.js:469:33), <anonymous>:18:23)
    at Engine._render (https://10015412-13-0-all.runbot55.odoo.com/web/static/lib/qweb/qweb2.js:458:58)
    at Engine.render (https://10015412-13-0-all.runbot55.odoo.com/web/static/lib/qweb/qweb2.js:450:26)
    at Class.renderElement (https://10015412-13-0-all.runbot55.odoo.com/web/static/src/js/core/widget.js:283:31)
    at Class.show (https://10015412-13-0-all.runbot55.odoo.com/point_of_sale/static/src/js/popups.js:40:14)
    at Class.show (https://10015412-13-0-all.runbot55.odoo.com/point_of_sale/static/src/js/popups.js:177:14)
    at Class.prototype.<computed> [as show] (https://10015412-13-0-all.runbot55.odoo.com/web/static/src/js/core/class.js:90:38)

Expected behavior:
It should log in normally.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1RB5QkR46ZskhFAMPUhSR97ULirSMEe-D/view

Support ticket number submitted via odoo.com/help (optional):
2649351

**Comment by andrp92** [comment]
¿Any updates on this one?

**Comment by andrp92** [comment]
Hey, ¿is anyone going to check on this one?

**Comment by Yenthe666** [comment]
Hey Andrés,

Since all people in the Odoo community bug management team have left nobody is actively looking at the public issues anymore I'm afraid.
If you have an enterprise version your best bet is to make a ticket through the official channel. I'm afraid that outside of the contributors team that used to be here nobody really cares about issues at Odoo.

Regards,
Yenthe

**Comment by andrp92** [comment]
Thanks for your response @Yenthe666. As always, helping out community. I appreciate it. 

I will be following up with the enterprise ticket that has 3 months opened already 💔.

Have a good one.

Regards,
