### ISSUE TITLE
Oddo app installing error

### ISSUE THREAD

**Issue by Solgitab** [odoo/odoo#77103]
Impacted versions: Odoo 14

Steps to reproduce:

Current behavior: Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo14/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo14/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f2e40ffd310>, 'base.module_category_localization')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo14/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/odoo14/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/odoo14/odoo/addons/base/models/ir_model.py", line 1928, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in xmlid_lookup
  File "/opt/odoo14/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo14/odoo/addons/base/models/ir_model.py", line 1921, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.module_category_localization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo14/odoo/tools/convert.py", line 566, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/opt/odoo14/odoo/tools/convert.py", line 114, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/opt/odoo14/odoo/tools/convert.py", line 37, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/opt/odoo14/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'ValueError'>: "External ID not found in the system: base.module_category_localization" while evaluating
"{'search_default_category_id': ref('base.module_category_localization'), 'search_default_name': 'Payroll'}"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/odoo14/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo14/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo14/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo14/odoo/modules/loading.py", line 458, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo14/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo14/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo14/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo14/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo14/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo14/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/odoo14/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/odoo14/odoo/addons/hr_payroll_community/views/res_config_settings_views.xml:3, near
<record id="open_payroll_modules" model="ir.actions.act_window">
            <field name="name">Payroll</field>
            <field name="res_model">ir.module.module</field>
            <field name="view_mode">kanban,tree,form</field>
            <field name="context" eval="{'search_default_category_id': ref('base.module_category_localization'), 'search_default_name': 'Payroll'}"/>
            <field name="search_view_id" ref="base.view_module_filter"/>
        </record>

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment]
>  odoo.tools.convert.ParseError: while parsing /opt/odoo14/odoo/addons/hr_payroll_community/views/res_config_settings_views.xml:3, near

hr_payroll_community is custom module.
