### ISSUE TITLE
Calendar Event not read by odoo.shell with .read()

### ISSUE THREAD

**Issue by isdabenx** [odoo/odoo#77356]
Impacted versions:
14

Steps to reproduce: 
Enter shell odoo and try:
self.env['calendar.event'].search([])[0].read()

Current behavior:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/benx/odoo/14.0/odoo/addons/calendar/models/calendar_event.py", line 781, in read
    events = super().read(fields=fields + ['privacy', 'user_id'], load=load)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

Expected behavior:
print all fields for this record.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by intero-chz** [comment]
Should help to just use `self.env['calendar.event'].search([])[0].read([])` as workaround. But yes the following code should be changed

https://github.com/odoo/odoo/blob/b36809315f12142ca9589b34b38c725100528909/addons/calendar/models/calendar_event.py#L741-L785

The `fields` parameter should be checked and filled with an empty list, before calling the super.
