### ISSUE TITLE
web: can't implement custom HTTP controller if request has application/json mime-type

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#7766]
1. Steps to reproduce error.
   1. Create a new json http controller and check value of `request.httprequest.data`
      1. Example: https://github.com/moylop260/odoo-json-test/blob/8.0/json_data_test/controllers/main.py#L20-L30
   2. Create a test of post json
      1. Example: https://github.com/moylop260/odoo-json-test/blob/8.0/json_data_test/tests/test_post.py#L65-L74
2. Saw:
   1. Variable ever is empty and generate next traceback
   
   ``` python
   2015-07-27 23:48:28,399 129 ERROR openerp_test openerp.http: Exception during JSON request handling.
   Traceback (most recent call last):
   File "/.repo_requirements/odoo/openerp/http.py", line 537, in _handle_exception
     return super(JsonRequest, self)._handle_exception(exception)
   File "/.repo_requirements/odoo/openerp/http.py", line 574, in dispatch
     result = self._call_function(**self.params)
   File "/.repo_requirements/odoo/openerp/http.py", line 310, in _call_function
     return checked_call(self.db, *args, **kwargs)
   File "/.repo_requirements/odoo/openerp/service/model.py", line 113, in wrapper
     return f(dbname, *args, **kwargs)
   File "/.repo_requirements/odoo/openerp/http.py", line 307, in checked_call
     return self.endpoint(*a, **kw)
   File "/.repo_requirements/odoo/openerp/http.py", line 803, in __call__
     return self.method(*args, **kw)
   File "/.repo_requirements/odoo/openerp/http.py", line 403, in response_wrap
     response = f(*args, **kw)
   File "/home/shippable/json_data_test/json_data_test/controllers/main.py", line 28, in json_provider_test
     'http request data is empty :('
   ValidationError: ('ValidateError', 'http request data is empty :(')
   2015-07-27 23:48:28,406 129 INFO openerp_test werkzeug: 127.0.0.1 - - [27/Jul/2015 23:48:28] "POST /json_provider_test?session_id=e104476f8119d1d21a58b5ab6919cb9fd67aabe4 HTTP/1.1" 200 -
   2015-07-27 23:48:28,410 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: FAIL
   2015-07-27 23:48:28,413 129 INFO openerp_test openerp.addons.json_data_test.tests.test_post: ======================================================================
   2015-07-27 23:48:28,414 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: FAIL: test_post_json_data (openerp.addons.json_data_test.tests.test_post.TestJsonPost)
   2015-07-27 23:48:28,414 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: Traceback (most recent call last):
   2015-07-27 23:48:28,414 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: `   File "/home/shippable/json_data_test/json_data_test/tests/test_post.py", line 73, in test_post_json_data
   2015-07-27 23:48:28,414 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: `     'Error in json post data!.')
   2015-07-27 23:48:28,415 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: ` AssertionError: {u'message': u'Odoo Server Error', u'code': 200, u'data': {u'debug': u'Traceback (most recent call last):\n  File "/.repo_requirements/odoo/openerp/http.py", line 537, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File "/.repo_requirements/odoo/openerp/http.py", line 574, in dispatch\n    result = self._call_function(**self.params)\n  File "/.repo_requirements/odoo/openerp/http.py", line 310, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File "/.repo_requirements/odoo/openerp/service/model.py", line 113, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/.repo_requirements/odoo/openerp/http.py", line 307, in checked_call\n    return self.endpoint(*a, **kw)\n  File "/.repo_requirements/odoo/openerp/http.py", line 803, in __call__\n    return self.method(*args, **kw)\n  File "/.repo_requirements/odoo/openerp/http.py", line 403, in response_wrap\n    response = f(*args, **kw)\n  File "/home/shippable/json_data_test/json_data_test/controllers/main.py", line 28, in json_provider_test\n    \'http request data is empty :(\'\nValidationError: (\'ValidateError\', \'http request data is empty :(\')\n', u'exception_type': u'except_osv', u'message': u'ValidateError\nhttp request data is empty :(', u'name': u'openerp.exceptions.ValidationError', u'arguments': [u'ValidateError', u'http request data is empty :(']}} != False : Error in json post data!.
   2015-07-27 23:48:28,415 129 INFO openerp_test openerp.addons.json_data_test.tests.test_post: Ran 1 test in 1.550s
   2015-07-27 23:48:28,415 129 ERROR openerp_test openerp.addons.json_data_test.tests.test_post: FAILED
   2015-07-27 23:48:28,415 129 INFO openerp_test openerp.addons.json_data_test.tests.test_post:  (failures=1)
   2015-07-27 23:48:28,415 129 ERROR openerp_test openerp.modules.module: Module json_data_test: 1 failures, 0 errors
   ```
3. Expected:
   1. Show string "data" similar to "flask": https://github.com/carlos-jenkins/python-github-webhooks/blob/master/webhooks.py#L77
      Because we need this string to generate a signature.
      By example github json webhook. https://developer.github.com/webhooks/securing/#securing-your-webhooks

Where is stored original string value of json `request`?
NOTE: I printed `request.httprequest.content_length` and is different to zero then had data.

**Comment by moylop260** [comment]
FYI if you apply this patch to odoo now you can access to original string request:
```diff
diff --git a/openerp/http.py b/openerp/http.py
index 5053d79..ce47b6d 100644
--- a/openerp/http.py
+++ b/openerp/http.py
@@ -496,6 +496,7 @@ class JsonRequest(WebRequest):
         # Read POST content or POST Form Data named "request"
         try:
             self.jsonrequest = simplejson.loads(request)
+            self.realrequest = request
         except simplejson.JSONDecodeError:
             msg = 'Invalid JSON data: %r' % (request,)
             _logger.error('%s: %s', self.httprequest.path, msg)
```

I don't know if this change is a good idea of we can get this value by other way

**Comment by odony** [comment]
Both Flask and Odoo use werkzeug, so you have access to the same underlying request object (in Odoo: `request.httprequest`). However the ways to access the request body in werkzeug depend a lot on [how and when the data was previously parsed](http://werkzeug.pocoo.org/docs/0.10/request_data/#when-does-werkzeug-parse), and this is different in Flask and Odoo.
This is not a bug but a consequence of the way werkzeug works.

Odoo controllers with `type=json` are meant for JSON-RPC and your example (github webhook) is not JSON-RPC, just a simple POST with JSON data. The appropriate way to handle this should be to use a normal HTTP route and to parse the request body yourself as JSON, using `request.httprequest.get_data()`.
Maybe you have tried that and you noticed that Odoo prevents it because it will automatically detect the mime type of the request (`application/json`) and force you to use a JSON-RPC route. You don't get the same result in flask because it does not do anything special for JSON mime-type.

One solution with Odoo is to use a different mime-type for the request (not `application/json` like [in your code](https://github.com/moylop260/odoo-json-test/blob/8.0/json_data_test/tests/test_post.py#L58)) + an HTTP controller and do your JSON parsing manually. If you can't change the mime-type of the request, then you have to patch Odoo somehow, but manually storing the `data` on `httprequest` would be like monkey-patching werkzeug, it's not really clean, because this is standard behavior. The only difference here is because Odoo parses the `request.stream` directly when the mime-type `application/json` is detected, so the stream is emptied, and in that case werkzeug makes `request.data` [unavailable](http://werkzeug.pocoo.org/docs/0.10/request_data/#when-does-werkzeug-parse).

An alternative (for a future Odoo version) would be to switch the request type (HTTP/JSON) automatically depending on the route, not [depending on the mime-type](https://github.com/odoo/odoo/blob/3940a096/openerp/http.py#L1356-L1363), so you would have more control over this by choosing the kind of controller.

**Comment by maljac** [comment]
For further reference: If you use the JSON-RPC2.0 data structure ([link](http://www.jsonrpc.org/specification)), you are able to get the data from the json request:

```python
# your_controller.py
@http.route('/your/callback', type='json', auth='public', methods=['POST'], website=True)
    def callback(self, **post):
        print post
        x = post.get('data')
        print x

# make a request
import requests as r

url = 'http://localhost:8069/your/callback'
data = {"params": {"data":"123"}}
r.post(url, json=data)
```

**Comment by tortabevonas** [comment]
I ended up creating a small Flask proxy server that encapsulates JSON requests as JSON-RPC ones and forwards them to the Odoo server:
```
# -*- coding: utf-8 -*-

import flask
from flask import Flask
from flask import request
import json
import requests

app = Flask(__name__)

DISPATCH_URL = "http://localhost:8069/"


@app.route('/', defaults={'path': ''}, methods=['POST'])
@app.route('/<path:path>', methods=['POST'])
def hello(path=""):
    payload = request.get_json()
    json_rpc_payload = {
        "jsonrpc": "2.0",
        "params": payload,
    }
    response = requests.post(DISPATCH_URL + path, json=json_rpc_payload)
    return flask.jsonify(response.json())


if __name__ == "__main__":
    app.run(port=1515)

```

**Comment by ikzent** [comment]
We have changed the wsgi-server.py in order to have an additional handler consuming urls before the Odoo stuff comes in. By doing so we avoided the basic jsonrpc mix up as described in the previous loggings.

Changes to wsgi-server.py

`index 7838350..fcd7b6f 100644 (file)
--- a/openerp/service/wsgi_server.py
+++ b/openerp/service/wsgi_server.py
@@ -164,11 +164,22 @@ def wsgi_xmlrpc(environ, start_response):
         params, method = xmlrpclib.loads(data)
         return xmlrpc_return(start_response, service, method, params, string_faultcode)
 
+# WSGI handlers registered through the register_override_handler() function below.
+override_handlers = []
 # WSGI handlers registered through the register_wsgi_handler() function below.
 module_handlers = []
 # RPC endpoints registered through the register_rpc_endpoint() function below.
 rpc_handlers = {}
 
+def register_override_handler(handler):
+    """ Register a WSGI override handler.
+
+    Override handlers are tried before regular wsgi handlers.
+
+    Handlers are tried in the order they are added. We might provide a way to
+    register a handler for specific routes later.
+    """
+    override_handlers.append(handler)
 def register_wsgi_handler(handler):
     """ Register a WSGI handler.`

Add the handler in the code
--- a/openerp/service/wsgi_server.py
+++ b/openerp/service/wsgi_server.py
@@ -180,6 +180,7 @@ def register_override_handler(handler):
     register a handler for specific routes later.
     """
     override_handlers.append(handler)
+
 def register_wsgi_handler(handler):
     """ Register a WSGI handler.
 
@@ -208,8 +209,8 @@ def application_unproxied(environ, start_response):
     with openerp.api.Environment.manage():
         # Try all handlers until one returns some result (i.e. not None).
         wsgi_handlers = [wsgi_xmlrpc]
-        wsgi_handlers += module_handlers
         wsgi_handlers += override_handlers
+        wsgi_handlers += module_handlers
         for handler in wsgi_handlers:
             result = handler(environ, start_response)
             if result is None:

Add in your module the additional handler and use this

**Comment by lasley** [comment]
I'm still playing with a final solution, but I solved this when creating the REST API in `[oauth_provider](https://github.com/OCA/server-tools/pull/889)` by doing somewhat of a ghetto monkey patch in the `JsonRequest.__init__` that will [setup the request properly when the unpacking of the JSON-RPC request fails](https://github.com/LasLabs/server-tools/blob/fcf8b7e877bc687e7061f462c50b9957f3a25c74/oauth_provider/http.py#L17). 

So far this works well and I haven't run into any issues using RPC. This has been deployed on a few heavily used production systems for a few months now with no issues.

I just ran across this same issues with web hooks, so I may make this more elegant and break it out into a base module here in the next few days.

**Comment by lasley** [comment]
[`base_json_request`](https://github.com/OCA/webhook/pull/3) solves this

**Comment by moylop260** [comment]
If something can reproduce it feel free of request re-open it

**Comment by andrewdhastings** [comment]
Has there ever been a long term fix for this issue? Running into this still.

**Comment by theangryangel** [comment]
I'm also running into this, so I guess not @andrewdhastings. I'm working with the Xero webhooks - which send `application/json` content-type (which I have no control over), so type='http' results in bad request. The killer is that I need to send back blank responses with specific status codes. Which I can't do because they're always wrapped by _json_response by default.

What I am slightly confused by is how the mail_github webhooks function in Enterprise as the docs suggest that github sends a content-type of application/json.

**Comment by andrewdhastings** [comment]
I was able to solve my issue using the following:

Add `from odoo.http import request` to the head

Then call `request.jsonrequest` to get the json body. 

This solved my issue in v13 with a json-rpc webhook.
