### ISSUE TITLE
Internal Server Error after creating new Odoo user "exampleuser" from LDAP

### ISSUE THREAD

**Issue by eovolkov** [odoo/odoo#7785]
2015-07-29 11:08:17,926 30711 DEBUG db_sphereinc openerp.addons.auth_ldap.users_ldap: Creating new Odoo user "exampleuser" from LDAP
2015-07-29 11:08:18,247 30711 ERROR db_sphereinc openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/addons/website/models/ir_http.py", line 198, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 677, in dispatch
    r = self._call_function(*_self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/auth_oauth/controllers/main.py", line 94, in web_login
    response = super(OAuthLogin, self).web_login(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/auth_signup/controllers/main.py", line 38, in web_login
    response = super(AuthSignupHome, self).web_login(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/website/controllers/main.py", line 52, in web_login
    return super(Website, self).web_login(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 509, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 960, in authenticate
    if uid: self.get_context()
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 995, in get_context
    self.context = request.registry.get('res.users').context_get(request.cr, request.uid) or {}
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py", line 402, in context_get
    return self._context_get(cr, uid)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in _context_get
  File "/usr/lib/python2.7/site-packages/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py", line 395, in _context_get
    res = getattr(user, k) or False
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 5931, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 55, in get
    raise self.exception
MissingError: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')

2015-07-29 11:08:18,273 30711 INFO db_sphereinc werkzeug: 127.0.0.1 - - [29/Jul/2015 11:08:18] "POST /web/login HTTP/1.0" 500 -

**Comment by grv333** [comment]
try edit _context_get function in /openerp/addons/base/res/res_users.py
In my case error was in string.
res = getattr(user, k) or False

I add try - except and it's work fine for my. My function after edit:
```
@tools.ormcache(skiparg=2)
def _context_get(self, cr, uid):
    user = self.browse(cr, SUPERUSER_ID, uid)
    result = {}
    for k in self._fields:
        if k.startswith('context_'):
                context_key = k[8:]
        elif k in ['lang', 'tz']:
                context_key = k
        else:
                context_key = False
    if context_key:
         try:
                res = getattr(user, k) or False
         except Exception as e:
                res = False
    if isinstance(res, models.BaseModel):
                res = res.id
    result[context_key] = res or False
    if res == False:
                result = {'lang': u'ru_RU', 'tz': False}
return result
```

**Comment by Yenthe666** [comment]
Hi @grv333,

It is really **not** a good idea to edit the source code from Odoo. You'll get into troubles if you later on want to update your Odoo its codebase.
Using a try/catch is also not a good, you're just putting an 'if all else fails' around it to wrap and hide all errors, without solving the underlying problem. 
@eovolkov could you update your Odoo codebase and try again please? We had some fixes on the LDAP module a while ago.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on my response.

**Comment by mmonteusa** [comment]
I'm getting this on lldp auth using Univention as backend... the page errors, but if I refresh it works. Not acceptable, but that just more feedback. Can we reopen?

**Comment by Yenthe666** [comment]
@mmonteusa sorry but we still have no reproducable case or clear information. Can you reproduce it on a runbot instance?
