### ISSUE TITLE
[15] sale: traceback on changing delivered quantity

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#77910]
Impacted versions: 15.0

https://10373579-15-0-all.runbot65.odoo.com/web?debug=1#id=45&cids=1&action=899&model=sale.order&view_type=form&menu_id=621

Steps to reproduce: Edit Delivered Qty on Sale order line
![Screenshot](https://user-images.githubusercontent.com/16624719/136063994-26d636b2-af20-4720-881a-e620351ae2cc.png)

Current behavior:
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1332, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1324, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 6458, in onchange
    todo = [
  File "/data/build/odoo/odoo/models.py", line 6461, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/data/build/odoo/odoo/models.py", line 6269, in has_changed
    return self[name] != record[name]
  File "/data/build/odoo/odoo/models.py", line 5867, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1054, in __get__
    self.recompute(record)
  File "/data/build/odoo/odoo/fields.py", line 1243, in recompute
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/addons/sale_timesheet/models/sale_order.py", line 71, in _compute_field_value
    order._create_upsell_activity()
  File "/data/build/odoo/addons/sale/models/sale_order.py", line 578, in _create_upsell_activity
    order_ref = ref % (order._name, order.id, order.name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: %d format: a number is required, not NewId

```
Expected behavior: Able to Change Delivered Qty

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Fixed
