### ISSUE TITLE
openerp.http: Exception during JSON request handling.

### ISSUE THREAD

**Issue by Mediadom** [odoo/odoo#77963]
Hello Guys, 

I have this error when i load the mail in the odoo dashboard

Do you have an idea ? 

Odoo V9

Ubuntu 16.04

Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 659, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 696, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/openerp/http.py", line 332, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/openerp/http.py", line 325, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo/openerp/http.py", line 975, in __call__
return self.method(*args, **kw)
File "/opt/odoo/openerp/http.py", line 525, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/addons/web/controllers/main.py", line 895, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/addons/mail/models/mail_message.py", line 521, in message_fetch
return self.search(domain, limit=limit).message_format()
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/addons/mail/models/mail_message.py", line 572, in message_format
self._message_read_dict_postprocess(message_values, message_tree)
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/addons/mail/models/mail_message.py", line 339, in _message_read_dict_postprocess
body_short = tools.html_email_clean(message_dict['body'], shorten=True, remove=True)
File "/opt/odoo/openerp/tools/mail.py", line 321, in html_email_clean
root = lxml.html.fromstring(inner_html)
File "/usr/local/lib/python2.7/dist-packages/lxml/html/__init__.py", line 723, in fromstring
doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
File "/usr/local/lib/python2.7/dist-packages/lxml/html/__init__.py", line 616, in document_fromstring
"Document is empty")
ParserError: Document is empty

Thx a lot

**Comment by Yenthe666** [comment]
Sorry but V9 is long out of support.
