### ISSUE TITLE
MAC install odoo 15 error during initialize database

### ISSUE THREAD

**Issue by silversparking** [odoo/odoo#77986]
```
Traceback (most recent call last):
  File "/Users/zijin/03_Github/odoo/odoo/service/db.py", line 66, in _initialize_db
    env = odoo.api.Environment(cr, SUPERUSER_ID, {})
  File "/Users/zijin/03_Github/odoo/odoo/api.py", line 506, in __new__
    for env in transaction.envs:
AttributeError: 'NoneType' object has no attribute 'envs'
```

Error as posted. program could't finish database initialize. I have reinstall postgres the same.

**Comment by Yenthe666** [comment]
Yep, closing as duplicate.
