### ISSUE TITLE
Wrong value for res.partner.lang: 'en_UK'

### ISSUE THREAD

**Issue by killday** [odoo/odoo#78003]
Impacted versions: 12

Steps to reproduce:
Load English UK translation, set as default language.
Open Invoicing and create new customer

Current behavior:
When click on create button for new customer getting an error report.
Error:
Odoo Server Error

Traceback (most recent call last):
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "E:\web\Odoo\v12_local\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\web\Odoo\v12_local\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "E:\web\Odoo\v12_local\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "e:\web\odoo\v12_local\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "e:\web\odoo\v12_local\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\web\Odoo\v12_local\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "E:\web\Odoo\v12_local\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "E:\web\Odoo\v12_local\server\odoo\models.py", line 5481, in onchange
    record = self.new(values)
  File "E:\web\Odoo\v12_local\server\odoo\models.py", line 4943, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "E:\web\Odoo\v12_local\server\odoo\models.py", line 4816, in _convert_to_cache
    for name, value in values.items()
  File "E:\web\Odoo\v12_local\server\odoo\models.py", line 4817, in <dictcomp>
    if name in fields
  File "E:\web\Odoo\v12_local\server\odoo\fields.py", line 1966, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.partner.lang: 'en_UK'
Expected behavior:
No error report, create customer

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Sorry but V12 is no longer supported. I presume that you have set a key on a language which is no longer active which causes this.
