### ISSUE TITLE
Community 15 updated to the Enterprise 15 is error

### ISSUE THREAD

**Issue by Etren** [odoo/odoo#78294]
Impacted versions: odoo 15.0 in debian 10

Steps to reproduce: the community is updated to the enterprise, and the "web enterprise" is installed.

Current behavior: Click the home menu to display the error report.

Expected behavior: Clicking the main menu is normal.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

error report is
`UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at HomeMenuAction.mounted (https://erp.test.com/web/assets/26-bff28a9/web.assets_backend.min.js:6050:77)
    at HomeMenuAction.__callMounted (https://erp.test.com/web/assets/25-c5f783f/web.assets_common.min.js:1312:66)
    at Fiber.complete (https://erp.test.com/web/assets/25-c5f783f/web.assets_common.min.js:1234:16)
    at https://erp.test.com/web/assets/25-c5f783f/web.assets_common.min.js:1202:65
    at Array.filter (<anonymous>)
    at Scheduler.flush (https://erp.test.com/web/assets/25-c5f783f/web.assets_common.min.js:1201:56)
    at https://erp.test.com/web/assets/25-c5f783f/web.assets_common.min.js:1206:54`

**Comment by Etren** [comment]
> Hey,
> 
> You can define the number of workers in your Odoo's conf file (/etc/odoo/odoo.conf).
> 
> Are you using firefox ? If yes, can you check with Chrome and see if you get the same error ?

I changed the workers parameter to 4, and this error report still appears.
I have been using chrome browser.

**Comment by Etren** [comment]
The reason has been determined: the enterprise version component compression package file sent to me by my service provider is damaged!
After updating the Enterprise Edition component package, it returns to normal.
