### ISSUE TITLE
[15] Can't change settings after installation

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#78508]
Impacted versions: 15 in ubuntu 18.04

Steps to reproduce: install 15CE edition. install sales and invoicing addon and try change some settings ( like price list enable )

Current behavior: error out

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1332, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1324, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 459, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 439, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-98>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 388, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_config.py", line 782, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/odoo/models.py", line 4064, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/odoo/models.py", line 4216, in _create
    for other, data in zip(others, data_list)
  File "/opt/odoo/odoo/odoo/fields.py", line 2195, in create
    for record, value in record_values
  File "<decorator-gen-53>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 561, in create
    values = self._check_contents(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 298, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_attachment.py", line 292, in _compute_mimetype
    raw = base64.b64decode(values['datas'])
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
binascii.Error: Incorrect padding
```

**Comment by esakarya** [comment]
problem reason is 
Odoo 15 Accounting by Odoo Mates
dont use this addon
