### ISSUE TITLE
[calendar] Fail test: disableQuickCreate 

### ISSUE THREAD

**Issue by odoosa** [odoo/odoo#78509]
Impacted versions:
V15.0
Steps to reproduce:
Run new install with testing
Current behavior:

2021-10-16 11:24:17,359 24529 ERROR odoodb odoo.addons.web.tests.test_js: FAIL: WebSuite.test_js
Traceback (most recent call last):
  File "/home/odoo/odoo/addons/web/tests/test_js.py", line 15, in test_js
    self.browser_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800)
  File "/home/odoo/odoo/odoo/tests/common.py", line 1586, in browser_js
    self.fail('%s\n%s' % (message, error))
AssertionError: Some js test failed
QUnit test failed: Views > CalendarView > calendar: disableQuickCreate in data event [message: "undefined", actual: "", expected: "do_action"]
QUnit test failed: Views > CalendarView > calendar: disableQuickCreate in data event [message: "Expected 3 assertions, but 1 were run", expected: "undefined"]
2 / 13397 tests failed.

Expected behavior:

Pass the test

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by duong77476** [comment]
Have you found the solution and reason sir?
