### ISSUE TITLE
Traceback when deleting message in Discuss module

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#78691]
Impacted versions: V15C and V15E.

Steps to reproduce: 

1. Goto Discuss module.
2. Goto History and try to delete the message.

Current behavior: 

Traceback :- RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, args, *kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, args, *kwargs)
  File "/data/build/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 916, in _call_
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/mail/controllers/discuss.py", line 213, in mail_message_update_content
    message_sudo._update_content(body=body, attachment_ids=attachment_ids)
  File "/data/build/odoo/addons/mail/models/mail_message.py", line 680, in _update_content
    thread._check_can_update_message_content(self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'mail.group' object has no attribute '_check_can_update_message_content'

Expected behavior: 

It should delete the message.

Video/Screenshot link (optional): 

https://www.awesomescreenshot.com/video/5700239?key=6725d6de14d20075d59028cda2a92307

Support ticket number submitted via odoo.com/help (optional):

**Comment by seb-odoo** [comment]
Hello @odooaktiv,

I think we already resolved the issue but forgot to close the issue, and I can't access the video you posted, could you please confirm if it's ok?
