### ISSUE TITLE
Traceback when changing UOM on product form.

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#78693]
Impacted versions: V15C and V15E

Steps to reproduce: 
1. Goto Inventory module
2. Open Product Form.
3. Try to change UOM.

Current behavior: 

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/api.py", line 879, in get
    return field_cache[record._ids[0]]
KeyError: <NewId origin=31>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/data/build/odoo/odoo/api.py", line 882, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(<NewId origin=31>,).virtual_available'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1332, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1324, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 6415, in onchange
    snapshot0 = Snapshot(record, nametree, fetch=(not first_call))
  File "/data/build/odoo/odoo/models.py", line 6250, in __init__
    self.fetch(name)
  File "/data/build/odoo/odoo/models.py", line 6258, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/data/build/odoo/odoo/models.py", line 6258, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/data/build/odoo/odoo/models.py", line 6250, in __init__
    self.fetch(name)
  File "/data/build/odoo/odoo/models.py", line 6260, in fetch
    self[name] = record[name]
  File "/data/build/odoo/odoo/models.py", line 5867, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/data/build/odoo/odoo/models.py", line 4249, in _compute_field_value
    getattr(self, field.compute)()
  File "/data/build/odoo/addons/stock/models/product.py", line 116, in _compute_quantities
    res = products._compute_quantities_dict(self._context.get('lot_id'), self._context.get('owner_id'), self._context.get('package_id'), self._context.get('from_date'), self._context.get('to_date'))
  File "/data/build/odoo/addons/mrp/models/product.py", line 170, in _compute_quantities_dict
    res = super(ProductProduct, self - kits)._compute_quantities_dict(lot_id, owner_id, package_id, from_date=from_date, to_date=to_date)
  File "/data/build/odoo/addons/stock/models/product.py", line 193, in _compute_quantities_dict
    res[product_id]['qty_available'] = float_round(qty_available, precision_rounding=rounding)
  File "/data/build/odoo/odoo/tools/float_utils.py", line 54, in float_round
    rounding_factor = _float_check_precision(precision_digits=precision_digits,
  File "/data/build/odoo/odoo/tools/float_utils.py", line 29, in _float_check_precision
    assert precision_rounding is None or precision_rounding > 0,\
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: precision_rounding must be positive, got 0.0

Expected behavior: 

Allow change of UOM or raise a warning i.e You're not allowed to change UOM as product has been consumed or utilised.

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

**Comment by DjamelTouati** [comment]
Thank you for the feedback!
The issue has been fixed: https://github.com/odoo/enterprise/pull/22090
The fix should be deployed at the beginning of next week.
Have a nice day!
