### ISSUE TITLE
[8.0] When i edit email template and try change the language "500: Internal Server Error"

### ISSUE THREAD

**Issue by Endika** [odoo/odoo#7898]
I tested in Runbot (http://3112434-8-0-45b4b9.runbot2.odoo-community.org/)
When i edit email template and try change the language "500: Internal Server Error"

My steps:

* 1- I enter in "Partner Mass Mailing" and press button "Edit Template":
![screenshot from 2015-08-05 15 51 36](https://cloud.githubusercontent.com/assets/568585/9087306/1f494f5a-3b8a-11e5-9b24-3f1e872e0ccb.png)

* 2- In template editor, press Spanish language
![screenshot from 2015-08-05 15 55 01](https://cloud.githubusercontent.com/assets/568585/9087376/8de114c0-3b8a-11e5-8396-0cc43ef3ff1a.png)

* 3- And execute this error
![screenshot from 2015-08-05 15 55 28](https://cloud.githubusercontent.com/assets/568585/9087390/9b7923de-3b8a-11e5-911d-a5c7e11f0af4.png)

```
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/addons/base/ir/ir_http.py", line 173, in _dispatch
    result = request.dispatch()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112434-8-0-45b4b9/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
TypeError: index() takes at least 3 arguments (2 given)
```

**Comment by rafaelbn** [comment]
This issues has been solved by @beledouxdenis .

---
This issue has been solved in Odoo 8.0 from the below revision:
https://github.com/odoo/odoo/commit/a1328c9054c1907ce4996811bb7befc6ca031a7f
---

Who can close it?
Thanks
