### ISSUE TITLE
[14.0][ENTERPRISE][l10n_cl_edi_boletas] Cannot validate 8 characters 'rutSender' in digital signature

### ISSUE THREAD

**Issue by MaxwellJake** [odoo/odoo#79162]
Impacted versions: 14.0 ENTERPRISE

Steps to reproduce:

Create a valid invoice with document type (l10n_latam.document.type) "(39) Boleta Electrónica".
Attempt to send the DTE to SII with "=> Enviar ahora al SII" (l10n_cl_dte_to_sii).

Current behavior:

Fails because the sender RUT (VAT) cannot be validated.
I believe this happens because the digital signature subject serial number is "9.999.999-9" and it's expecting a RUT (VAT) in the "99.999.999-9" format, but both are valid! 

Expected behavior:

Validate the RUT (VAT) of the sender digital signature correctly.

Video/Screenshot link (optional):

RUT (VAT) of digital signature censored for privacy but it has the same length as the example.

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/14.0/l10n_cl_edi_boletas/models/account_move.py", line 31, in l10n_cl_send_dte_to_sii
    response = self._send_xml_to_sii_rest(
  File "/home/odoo/src/enterprise/14.0/l10n_cl_edi_boletas/models/l10n_cl_edi_util.py", line 76, in _send_xml_to_sii_rest
    data['rutSender'] = int(digital_signature['subject_serial_number'][:8])
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: invalid literal for int() with base 10: '9999999-'
```

Support ticket number submitted via odoo.com/help (optional): 2680095

@Danisan

**Comment by MaxwellJake** [comment]
Ticket answer:

> The bug has indeed been confirmed by the team who developed the Chilean localization module. They have prepared a fix to solve this issue, which should be implemented in the coming days.

**Comment by MaxwellJake** [comment]
Ticket answer:

> The bug has indeed been confirmed by the team who developed the Chilean localization module. They have prepared a fix to solve this issue, which should be implemented in the coming days.
