### ISSUE TITLE
[BUG][14.0]  Cannot read properties of undefined (reading 'onChange') 

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#79299]
Impacted versions:
14.0
Steps to reproduce:
I created a Mdel, detail Model, detail's detail Model.
  detail's detail model has a compute field. When I modify the compute field and save it, an error is reported.
Current behavior:

`TypeError: Cannot read properties of undefined (reading 'onChange')
    at http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2245:44
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at generateSpecs (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2241:15)
    at http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2251:25
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:150:9)
    at http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2250:23
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at generateSpecs (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2241:15)
    at Class._buildOnchangeSpecs (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:2235:9)
    at Class._performOnChange (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:4171:50)`

I checked the code, the problem mainly appeared in:
https://github.com/odoo/odoo/blob/952e70bf7f446c38f51b253ba890f12ca814ef60/addons/web/static/src/js/views/basic/basic_model.js#L2239-L2255

I found that fieldsInfo contains the display_name field, but fields does not, which leads to an error.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/5398273/140013930-c03ffcc9-4eb9-455e-80a5-120694206b96.png">

I see that there is a piece of code here that will delete display_name. I don't know if it is caused by this?
https://github.com/odoo/odoo/blob/952e70bf7f446c38f51b253ba890f12ca814ef60/addons/web/static/src/js/views/basic/basic_model.js#L3240-L3256

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by zolzaya** [comment]
Hello, I have a same issue. Any updates or solutions?

**Comment by danaelshrbiny10** [comment]
hi there, this a problem appear when i need to upgrade my module any solution please !!

![odoo](https://user-images.githubusercontent.com/54659424/151662946-f67e8396-2184-47c2-840b-1f56d842a8b3.jpg)

**Comment by AyoubZahid** [comment]
i have the same issue on odoo version Odoo 15.0-20230329 (Community Edition).
any update?

**Comment by forvas** [comment]
I'm having the same error on 15.0.

I have created a new model X, which contains several fields and an onchange method. Then I created an One2many field which points to this new model X. When I add a new record to X from the One2many list, the onchange works OK.

However, if I edit an existing record from this One2many field, I get the error. If I comment the onchange method, I get no error. The onchange method only prints a log message, and when the error is raised I cannot see the message in the log. It happens to any field of the model X, if I create an onchange method for other field, same error.

Did anyone find a solution for this??
