### ISSUE TITLE
Sales Teams add new member 

### ISSUE THREAD

**Issue by mesmatm** [odoo/odoo#79343]
Impacted versions: 14

Steps to reproduce: Sales Teams

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

error as below  i am not able to add new user member to the Sales Teams can you please help me 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/crm/models/crm_team.py", line 96, in write
    result = super(Team, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_alias_mixin.py", line 54, in write
    super(AliasMixin, self).write(record_vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/sales_team/models/crm_team.py", line 96, in write
    res = super(CrmTeam, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3664, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3048, in write
    return self.write_batch([(records, value)])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3069, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3243, in write_real
    lines[inverse] = recs[-1]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5676, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1129, in __set__
    records.write({self.name: write_value})
  File "/usr/lib/python3/dist-packages/odoo/addons/hr/models/res_users.py", line 169, in write
    result = super(User, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/gamification/models/res_users.py", line 63, in write
    result = super(Users, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/res_users.py", line 88, in write
    write_res = super(Users, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/hide_menu_user/models/res_user.py", line 44, in write
    'restrict_user_ids': [(4, self.id)]
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3821, in __get__
    raise ValueError("Expected singleton: %s" % record)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: res.users(107, 108, 130)

Thanks for help

**Comment by whotopia** [comment]
The hide_menu_user addon seems to interact negatively with Operating Units.    If you try to add users to a Sales Team within a specific operating Unit, and you are also trying to restrict that user's list of menu options, you will get the above error.   Seems to be an issue with the hide_menu_user addon.

**Comment by niyasraphy** [comment]
hi @mesmatm ,
feel free to close the issue as it is not an issue inside odoo code, but with third party app as specified by @whotopia 

thanks
