### ISSUE TITLE
http:Exception during JSON request

### ISSUE THREAD

**Issue by anoureldin** [odoo/odoo#79536]
Impacted versions: 13

Steps to reproduce: 
this issue showing on log file 
i don't know what the reason for it 

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Nov 09 06:29:42 OdooEnterPrise python3[1476]: Odoo Server 13.0:test:ERROR:odoo.http:Exception during JSON request handling.
                                              Traceback (most recent call last):
                                                File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
                                                  return super(JsonRequest, self)._handle_exception(exception)
                                                File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
                                                  raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
                                                File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
                                                  raise value
                                                File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
                                                  result = self._call_function(**self.params)
                                                File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
                                                  return checked_call(self.db, *args, **kwargs)
                                                File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
                                                  return f(dbname, *args, **kwargs)
                                                File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
                                                  result = self.endpoint(*a, **kw)
                                                File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
                                                  return self.method(*args, **kw)
                                                File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
                                                  response = f(*args, **kw)
                                                File "/opt/odoo13/odoo/addons/bus/controllers/main.py", line 35, in poll
                                                  raise Exception("bus.Bus unavailable")
                                              Exception: bus.Bus unavailable

**Comment by anoureldin** [comment]
it's was from odoo.conf 
i edit it and every thing is ok
