### ISSUE TITLE
CRITICAL ? odoo.modules.module: Couldn't load module web

### ISSUE THREAD

**Issue by luna9722** [odoo/odoo#79603]
Hello, I am facing this issue with odoo 13, I deleted it and clone it again and reinstalled the dependencies but this couldn't solve the problem, I will be grateful if you can help me with this problem. Thank you.
Here is the displayed error:
/usr/bin/python3.8 /home/user/odoo/odoo-bin -c odoo.conf
2021-11-10 09:04:43,455 7618 INFO ? odoo: Odoo version 13.0 
2021-11-10 09:04:43,455 7618 INFO ? odoo: Using configuration file at /home/user/odoo/odoo.conf 
2021-11-10 09:04:43,455 7618 INFO ? odoo: addons paths: ['/home/user/odoo/odoo/addons', '/home/user/.local/lib/python3.8/site-packages/odoo/addons', '/home/user/.local/share/Odoo/addons/13.0', '/home/user/odoo/addons', '/home/user/odoo/custom_addons'] 
2021-11-10 09:04:43,455 7618 INFO ? odoo: database: odoo13@default:default 
2021-11-10 09:04:43,649 7618 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2021-11-10 09:04:43,859 7618 CRITICAL ? odoo.modules.module: Couldn't load module web 
2021-11-10 09:04:43,859 7618 CRITICAL ? odoo.modules.module: cannot import name 'crop_image' from 'odoo.tools' (/home/user/odoo/odoo/tools/__init__.py) 
2021-11-10 09:04:43,859 7618 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration. 
Traceback (most recent call last):
  File "/home/user/odoo/odoo/service/server.py", line 1140, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/user/odoo/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/user/.local/lib/python3.8/site-packages/odoo/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/home/user/.local/lib/python3.8/site-packages/odoo/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main, pivot
  File "/home/user/.local/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 38, in <module>
    from odoo.tools import crop_image, topological_sort, html_escape, pycompat
ImportError: cannot import name 'crop_image' from 'odoo.tools' (/home/user/odoo/odoo/tools/__init__.py)
2021-11-10 09:04:43,864 7618 INFO ? odoo.service.server: HTTP service (werkzeug) running on user-Lenovo-IdeaPad-S145-15IKB:8013

**Comment by GunalanD95** [comment]
hi which python and passlib version are you using ?

**Comment by luna9722** [comment]
python 3.8 and passlib 1.7.4

**Comment by GunalanD95** [comment]
try upgrading your packages sudo -H pip3 install --upgrade pip

**Comment by luna9722** [comment]
@GunalanD95 are you sure if I upgrade pip, everything will be fine, I tried installing odoo on windows but I faced too many problems, I followed this tuto when I installed odoo for the first time on ubuntu, and it worked pretty fine for me for a month, but I don't know why, one day without changing anything from the day before, it gave me that error about the web module.

**Comment by GunalanD95** [comment]
iam also not sure exactly did u tried to pull the latest code for core modules once ?

**Comment by luna9722** [comment]
Solved by deleting and reinstalling odoo and postgres

**Comment by hashshift** [comment]
I face same issue with odoo 14 version, when I removed some modules. and reinstall all libs from requirements.txt, all worked for me.

**Comment by StraubCreative** [comment]
Downgrading the pip module `cryptography` to 37.0.4 worked for me 👍
