### ISSUE TITLE
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "odoo13"

### ISSUE THREAD

**Issue by luna9722** [odoo/odoo#79657]
Hello everybody,

I installed postgres and created a user odoo13 following these steps:

sudo apt-get install postgresql

sudo su - postgres

createuser --createdb --username postgres --no-createrole --no-superuser --pwprompt odoo13

psql

ALTER USER odoo13 WITH SUPERUSER;

cloned the the odoo 13 repo https://www.github.com/odoo/odoo --depth 1 --branch 13.0

and installed the dependencies from the requirements.txt and changed the odoo.conf file like this:

[options]
   ; This is the password that allows database operations:
   ; admin_passwd = admin
   db_host = False
   db_port = False
   db_user = odoo13
   db_password = asma
   addons_path = /home/asma/odoo/addons, /home/asma/odoo/custom_addons
   xmlrpc_port = 8069
But I don't know why I can't connect to the database when running the project, I get this error:

/home/asma/odoo/venv/bin/python /home/asma/odoo/odoo-bin -c odoo.conf
2021-11-10 18:54:19,179 54347 INFO ? odoo: Odoo version 13.0
2021-11-10 18:54:19,179 54347 INFO ? odoo: Using configuration file at /home/asma/odoo/odoo.conf
2021-11-10 18:54:19,180 54347 INFO ? odoo: addons paths: ['/home/asma/odoo/odoo/addons', '/home/asma/.local/share/Odoo/addons/13.0', '/home/asma/odoo/addons', '/home/asma/odoo/custom_addons']
2021-11-10 18:54:19,180 54347 INFO ? odoo: database: odoo13@default:default
2021-11-10 18:54:19,327 54347 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2021-11-10 18:54:19,448 54347 INFO ? odoo.service.server: HTTP service (werkzeug) running on asma-Lenovo-IdeaPad-S145-15IKB:8069
2021-11-10 18:54:37,078 54347 INFO ? odoo.http: HTTP Configuring static files
2021-11-10 18:54:37,083 54347 INFO ? odoo.sql_db: Connection to the database failed
2021-11-10 18:54:37,085 54347 INFO ? werkzeug: 127.0.0.1 - - [10/Nov/2021 18:54:37] "GET / HTTP/1.1" 500 - 0 0.000 0.005
2021-11-10 18:54:37,092 54347 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
File "/home/asma/odoo/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/home/asma/odoo/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/home/asma/odoo/odoo/service/server.py", line 441, in app
return self.app(e, s)
File "/home/asma/odoo/odoo/service/wsgi_server.py", line 142, in application
return application_unproxied(environ, start_response)
File "/home/asma/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/home/asma/odoo/odoo/http.py", line 1287, in __call__
return self.dispatch(environ, start_response)
File "/home/asma/odoo/odoo/http.py", line 1257, in __call__
return self.app(environ, start_wrapped)
File "/home/asma/odoo/venv/lib/python3.8/site-packages/werkzeug/wsgi.py", line 766, in __call__
return self.app(environ, start_response)
File "/home/asma/odoo/odoo/http.py", line 1421, in dispatch
self.setup_db(httprequest)
File "/home/asma/odoo/odoo/http.py", line 1344, in setup_db
httprequest.session.db = db_monodb(httprequest)
File "/home/asma/odoo/odoo/http.py", line 1506, in db_monodb
dbs = db_list(True, httprequest)
File "/home/asma/odoo/odoo/http.py", line 1473, in db_list
dbs = odoo.service.db.list_dbs(force)
File "/home/asma/odoo/odoo/service/db.py", line 378, in list_dbs
with closing(db.cursor()) as cr:
File "/home/asma/odoo/odoo/sql_db.py", line 664, in cursor
return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
File "/home/asma/odoo/odoo/sql_db.py", line 196, in __init__
self._cnx = pool.borrow(dsn)
File "/home/asma/odoo/odoo/sql_db.py", line 547, in _locked
return fun(self, *args, **kwargs)
File "/home/asma/odoo/odoo/sql_db.py", line 613, in borrow
result = psycopg2.connect(
File "/home/asma/odoo/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL: Peer authentication failed for user "odoo13" - - -
ALso when I try to connect to the PostgreSQL database server using the odoo13 user:
it gives me the same error: psql: error: FATAL:  Peer authentication failed for user "odoo13"
without asking for a password.
I would be grateful if you can help me with this matter.

Thank you

**Comment by luna9722** [comment]
Solved by modifying pg_hba.conf file*.

This line:

local   all             postgres                                trust
