### ISSUE TITLE
Exception: Couldn't find pg_dump

### ISSUE THREAD

**Issue by odooopen** [odoo/odoo#8005]
getting traceback while getting backup of odoo database from database manager.
postgres server is on another server, I have configured pg_path accordingly.
while taking backup it is giving me error like 

pg_path is /usr/lib/postgresql/9.1/bin/

> Traceback (most recent call last):
  File "/home/software/ws/odoo/openerp/http.py", line 108, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/software/ws/odoo/openerp/service/db.py", line 70, in dispatch
    return fn(*params)
  File "/home/software/ws/odoo/openerp/service/db.py", line 176, in exp_dump
    dump_db(db_name, t)
  File "/home/software/ws/odoo/openerp/service/db.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/home/software/ws/odoo/openerp/service/db.py", line 200, in dump_db
    if openerp.tools.exec_pg_command(*cmd):
  File "/home/software/ws/odoo/openerp/tools/misc.py", line 90, in exec_pg_command
    raise Exception('Couldn\'t find %s' % name)
Exception: Couldn't find pg_dump

**Comment by odooopen** [comment]
To reproduce the issue use the postgres server of another machine.

**Comment by lem8r** [comment]
postgresql-client-common is installed on a pg server?

**Comment by Yenthe666** [comment]
Hi @odooopen,

This looks like an issue in the configuration / settings of your pg_path or pg server settings.
Issues are however only for the default code, not for questions and / or configurations.
If you still face this problem you can create a topic on the official Odoo help forums (help.odoo.com), where I'm sure somebody can help you!

Regards,
Yenthe
