### ISSUE TITLE
IoTBox: Connected CashBox Trying to pay a ticket on Pint of Sale gets error and cannot open the cashbox TypeError: open_cashbox() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by carlosecv** [odoo/odoo#80339]
TypeError: open_cashbox() takes 1 positional argument but 2 were given

Impacted versions: 
IoT Box 21.1 
Odoo 14 and Odoo 15

Iot Box Raspberri PI 3 Model B
Printer EPSON TM-T20 II
Cash box connected to Printer

Steps to reproduce:
Do a sale on POS then try to pay on Cash to get Change

Current behavior:
Then error trying to open Cashbox:

Odoo Server Error

Traceback (most recent call last):

  File "/home/pi/odoo/odoo/http.py", line 1459, in _dispatch_nodb

    result = request.dispatch()

  File "/home/pi/odoo/odoo/http.py", line 687, in dispatch

    result = self._call_function(**self.params)

  File "/home/pi/odoo/odoo/http.py", line 360, in _call_function

    return self.endpoint(*args, **kwargs)

  File "/home/pi/odoo/odoo/http.py", line 916, in __call__

    return self.method(*args, **kw)

  File "/home/pi/odoo/odoo/http.py", line 535, in response_wrap

    response = f(*args, **kw)

  File "/home/pi/odoo/addons/hw_drivers/iot_handlers/drivers/PrinterDriver.py", line 269, in default_printer_action

    iot_devices[printer].action(data)

  File "/home/pi/odoo/addons/hw_drivers/driver.py", line 52, in action

    self._actions[data.get('action', '')](data)

Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/pi/odoo/odoo/http.py", line 643, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/home/pi/odoo/odoo/http.py", line 301, in _handle_exception

    raise exception.with_traceback(None) from new_cause

TypeError: open_cashbox() takes 1 positional argument but 2 were given

Expected behavior:

Open the cashbox without error

If i execute on my linux box this command:
echo -e -n "\x1b\x70\x00\x19\xfa" | lpr -o raw -P TM-T20II
The cashbox is opened without problem

TM-T20II is the exact name as listed by the command: lpstat -p

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/7633676/143268694-0186c664-5418-4643-9cd4-6686f8b8cf4d.mp4

![2021-11-24_09-35](https://user-images.githubusercontent.com/7633676/143268632-fbfba263-e9a4-4c02-a833-cb0b0c7e1fa6.png)
Support ticket number submitted via odoo.com/help (optional)
![2021-11-24_09-36](https://user-images.githubusercontent.com/7633676/143268646-5b41b4d3-c26a-4f28-bcce-95672741d8dc.png)
:

**Comment by Batista10-G** [comment]
We are experiencing the same issue.
As a workaround you can disable the automatic opening of the cash-box. This lets the users work with no errors.

**Comment by carlosecv** [comment]
On old versions this cashbox it worked ok, something has changed so I will try to checkold versions of this to check the differences
