### ISSUE TITLE
[v8] Can't view or edit Models in Database Structure > Models

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#8038]
I get this error when trying to open a Model in  Database Structure > Models:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 944, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\calendar\calendar.py", line 649, in read
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 3141, in read
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 3176, in read
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\models.py", line 3355, in _read_from_database
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\osv\fields.py", line 788, in get
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 239, in wrapper
TypeError: 'NoneType' object is not callable

Any help on where to look for a solution would be greatly appreciated.
Thank you.

**Comment by avanzella** [comment]
Found the problem: it was caused by mass editing module. After updating the module with latest version it works again.
