### ISSUE TITLE
IOError: encoder error -2 when writing image file

### ISSUE THREAD

**Issue by guggenbergerl** [odoo/odoo#8056]
If I whant to upload a picture in the website with using the button "Upload an image from your computer" I get the error message "IOError: encoder error -2 when writing image file".

The full log looks like follows:
2015-08-13 12:08:05,549 3867 ERROR feuerwehr openerp.addons.website.controllers.main: Failed to upload image to attachment
Traceback (most recent call last):
  File "/usr/local/openerp/server/openerp/addons/website/controllers/main.py", line 342, in attach
    image_data = image_save_for_web(image)
  File "/usr/local/openerp/server/openerp/tools/image.py", line 141, in image_save_for_web
    image.save(img, **opt)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1439, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 491, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file

The python pillow version 2.9.0 is installed.

What do I have to do to solve this issue?

Thanks a lot!

**Comment by JKE-be** [comment]
Cannot reproduce.
Probably fixed meanwhile
