### ISSUE TITLE
odoo 15 install new database error

### ISSUE THREAD

**Issue by hashshift** [odoo/odoo#80568]
Impacted versions: 15 community

Steps to reproduce: create new database with latest pull

Current behavior:
2021-11-30 05:53:44,691 25920 INFO o15testing odoo.modules.loading: loading base/data/res_company_data.xml 
2021-11-30 05:53:44,694 25920 ERROR o15testing odoo.tools.convert.init: Could not eval(obj()._get_default_favicon(original=True)) for favicon in {} 
2021-11-30 05:53:44,696 25920 WARNING o15testing odoo.modules.loading: Transient module states were reset 
2021-11-30 05:53:44,697 25920 ERROR o15testing odoo.modules.registry: Failed to load registry 
2021-11-30 05:53:44,697 25920 CRITICAL o15testing odoo.service.server: Failed to initialize database `o15testing`. 
Traceback (most recent call last):
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/addons/base/models/res_company.py", line 35, in _get_default_favicon
    with tools.file_open(img_path, 'rb') as f:
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/misc.py", line 196, in file_open
    path = file_path(name, filter_ext=filter_ext)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/misc.py", line 158, in file_path
    is_abs = os.path.isabs(file_path)
  File "/usr/lib/python3.8/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 569, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 39, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'TypeError'>: "expected str, bytes or os.PathLike object, not bool" while evaluating
'obj()._get_default_favicon(original=True)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/modules/loading.py", line 415, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/snippetbucket/source/odoo/branches/15-odoo/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/snippetbucket/source/odoo/branches/15-odoo/odoo/addons/base/data/res_company_data.xml:4, somewhere inside
<record id="main_company" model="res.company">
            <field name="name">My Company</field>
            <field name="partner_id" ref="main_partner"/>
            <field name="currency_id" ref="base.EUR"/>
            <field name="favicon" model="res.company" eval="obj()._get_default_favicon(original=True)"/>
        </record>

Expected behavior: no bugs to create new database

Video/Screenshot link (optional):
![Screenshot from 2021-11-30 11-25-28](https://user-images.githubusercontent.com/95270597/143993432-b58bd1a2-8e26-443e-8b8c-80f12e21ae03.png)

**Comment by angel-ramirez-isea** [comment]
Make sure you're using the Python version recommended for 15.0.

I ran into the same problem, installed the requirements using:

python3.9 -m pip -r rquirements.txt

and changed the first line in odoo-bin, and everything is fine now.

**Comment by manh-nguyen160823** [comment]
![odoo-15](https://github.com/odoo/odoo/assets/40142118/560e465c-0196-4766-8264-223eec55d5e3)
check your _get_default_favicon() func, seem like below line return False result to img_path variable
img_path = get_resource_path('web', 'static/img/favicon.ico')
