### ISSUE TITLE
ParseError: "module 'base64' has no attribute 'encodestring'"

### ISSUE THREAD

**Issue by primeKal** [odoo/odoo#80652]
Impacted versions:13

Steps to reproduce: installed postgres 10 on windows and python 3.9 and odoo13 
The base64.encodestrings method has been depreciated and in 3.9 removed thus causing it to crush, I tried replacing it with base64.encodebytes but it gives forbidden opcode error

Current behaviour: Server is up and running but creating a database fails and continues but retrieving it giving a failure , UndefinedTable: relation "ir_model" does not exist

A copy of the stacktrace 

  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 712, in parse
      self._tag_root(de)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
      f(rec)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 483, in _tag_menuitem
      self.env['ir.ui.menu']._load_records([data], self.mode == 'update')
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4176, in _load_records
      records = self._load_records_create([data['values'] for data in to_create])
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4090, in _load_records_create
      return self.create(values)
    File "<decorator-gen-29>", line 2, in create
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
      return create(self, arg)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 149, in create
      values['web_icon_data'] = self._compute_web_icon_data(values.get('web_icon'))
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 166, in _compute_web_icon_data
      return self.read_image(web_icon)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 70, in read_image
      icon_image = base64.encodestring(icon_file.read())
  AttributeError: module 'base64' has no attribute 'encodestring'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\registry.py", line 86, in new
      odoo.modules.load_modules(registry._db, force_demo, status, update_module)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 367, in load_modules
      loaded_modules, processed_modules = load_module_graph(
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 225, in load_module_graph
      load_data(cr, idref, mode, kind='data', package=package, report=report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 68, in load_data
      tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 736, in convert_file
      convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 803, in convert_xml_import
      obj.parse(doc.getroot())
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 715, in parse
      pycompat.reraise(
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise
      raise value.with_traceback(tb)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 712, in parse
      self._tag_root(de)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
      f(rec)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 483, in _tag_menuitem
      self.env['ir.ui.menu']._load_records([data], self.mode == 'update')
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4176, in _load_records
      records = self._load_records_create([data['values'] for data in to_create])
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4090, in _load_records_create
      return self.create(values)
    File "<decorator-gen-29>", line 2, in create
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
      return create(self, arg)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 149, in create
      values['web_icon_data'] = self._compute_web_icon_data(values.get('web_icon'))
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 166, in _compute_web_icon_data
      return self.read_image(web_icon)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 70, in read_image
      icon_image = base64.encodestring(icon_file.read())
  odoo.tools.convert.ParseError: "module 'base64' has no attribute 'encodestring'" while parsing file:/c:/users/kaleb/pycharmprojects/odoo13/odoo-13.0/odoo/addons/base/views/base_menus.xml:2, near
  <odoo>
        
            <menuitem id="menu_board_root" name="Dashboards" sequence="305" web_icon="base,static/description/board.png" groups="base.group_user"/>
            <menuitem id="menu_reporting_dashboard" name="Dashboards" parent="menu_board_root" sequence="0"/>
            <menuitem id="menu_reporting_config" name="Configuration" parent="menu_board_root" sequence="100" groups="base.group_system"/>
  
        
        <menuitem name="Settings" id="menu_administration" web_icon="base,static/description/settings.png" sequence="500" groups="base.group_erp_manager"/>
            <menuitem id="menu_management" name="Apps" sequence="310" web_icon="base,static/description/modules.png" groups="base.group_system"/>
            <menuitem id="menu_administration_shortcut" parent="menu_administration" name="Custom Shortcuts" sequence="50"/>
            
            <menuitem id="menu_users" name="Users &amp; Companies" parent="menu_administration" sequence="1"/>
            <menuitem id="menu_translation" name="Translations" parent="menu_administration" sequence="2" groups="base.group_no_one"/>
                <menuitem id="menu_translation_app" name="Application Terms" parent="menu_translation" sequence="4" groups="base.group_no_one"/>
                <menuitem id="menu_translation_export" name="Import / Export" parent="menu_translation" sequence="3" groups="base.group_no_one"/>
            <menuitem id="menu_config" name="General Settings" parent="menu_administration" sequence="3"/>
  
            <menuitem id="menu_custom" name="Technical" parent="menu_administration" sequence="110" groups="base.group_no_one"/>
                <menuitem id="next_id_2" name="User Interface" parent="menu_custom"/>
                <menuitem id="menu_email" name="Email" parent="menu_custom" sequence="1"/>
                <menuitem id="next_id_9" name="Database Structure" parent="base.menu_custom"/>
                <menuitem id="menu_automation" name="Automation" parent="base.menu_custom"/>
                <menuitem id="menu_security" name="Security" parent="menu_custom" sequence="25"/>
                <menuitem id="menu_ir_property" name="Parameters" parent="menu_custom" sequence="24"/>
  
            <menuitem id="base.menu_tests" name="Tests" sequence="1000000" web_icon="test_exceptions,static/description/icon.png"/>
  
        <record model="ir.ui.menu" id="base.menu_administration">
            <field name="groups_id" eval="[(6,0, [ref('group_system'), ref('group_erp_manager')])]"/>
        </record>
  
        <record id="action_client_base_menu" model="ir.actions.client">
            <field name="name">Open Settings Menu</field>
            <field name="tag">reload</field>
            <field name="params" eval="{'menu_id': ref('base.menu_administration')}"/>
        </record>
        <record id="open_menu" model="ir.actions.todo">
            <field name="action_id" ref="action_client_base_menu"/>
            <field name="sequence">100</field>
            <field name="state">done</field>
        </record>
        <record id="action_open_website" model="ir.actions.act_url">
            <field name="name">Home Menu</field>
            <field name="target">self</field>
            <field name="url">/web</field>
        </record>
  </odoo>
  2021-11-30 20:30:02,780 9092 ERROR gg odoo.service.db: CREATE DATABASE failed: 
  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 712, in parse
      self._tag_root(de)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
      f(rec)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 483, in _tag_menuitem
      self.env['ir.ui.menu']._load_records([data], self.mode == 'update')
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4176, in _load_records
      records = self._load_records_create([data['values'] for data in to_create])
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4090, in _load_records_create
      return self.create(values)
    File "<decorator-gen-29>", line 2, in create
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
      return create(self, arg)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 149, in create
      values['web_icon_data'] = self._compute_web_icon_data(values.get('web_icon'))
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 166, in _compute_web_icon_data
      return self.read_image(web_icon)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 70, in read_image
      icon_image = base64.encodestring(icon_file.read())
  AttributeError: module 'base64' has no attribute 'encodestring'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\service\db.py", line 62, in _initialize_db
      registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\registry.py", line 86, in new
      odoo.modules.load_modules(registry._db, force_demo, status, update_module)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 367, in load_modules
      loaded_modules, processed_modules = load_module_graph(
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 225, in load_module_graph
      load_data(cr, idref, mode, kind='data', package=package, report=report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 68, in load_data
      tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 736, in convert_file
      convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 803, in convert_xml_import
      obj.parse(doc.getroot())
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 715, in parse
      pycompat.reraise(
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\pycompat.py", line 13, in reraise
      raise value.with_traceback(tb)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 712, in parse
      self._tag_root(de)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 674, in _tag_root
      f(rec)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\convert.py", line 483, in _tag_menuitem
      self.env['ir.ui.menu']._load_records([data], self.mode == 'update')
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4176, in _load_records
      records = self._load_records_create([data['values'] for data in to_create])
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\models.py", line 4090, in _load_records_create
      return self.create(values)
    File "<decorator-gen-29>", line 2, in create
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\api.py", line 336, in _model_create_multi
      return create(self, arg)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 149, in create
      values['web_icon_data'] = self._compute_web_icon_data(values.get('web_icon'))
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 166, in _compute_web_icon_data
      return self.read_image(web_icon)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_ui_menu.py", line 70, in read_image
      icon_image = base64.encodestring(icon_file.read())
  odoo.tools.convert.ParseError: "module 'base64' has no attribute 'encodestring'" while parsing file:/c:/users/kaleb/pycharmprojects/odoo13/odoo-13.0/odoo/addons/base/views/base_menus.xml:2, near
  <odoo>
        
            <menuitem id="menu_board_root" name="Dashboards" sequence="305" web_icon="base,static/description/board.png" groups="base.group_user"/>
            <menuitem id="menu_reporting_dashboard" name="Dashboards" parent="menu_board_root" sequence="0"/>
            <menuitem id="menu_reporting_config" name="Configuration" parent="menu_board_root" sequence="100" groups="base.group_system"/>
  
        
        <menuitem name="Settings" id="menu_administration" web_icon="base,static/description/settings.png" sequence="500" groups="base.group_erp_manager"/>
            <menuitem id="menu_management" name="Apps" sequence="310" web_icon="base,static/description/modules.png" groups="base.group_system"/>
            <menuitem id="menu_administration_shortcut" parent="menu_administration" name="Custom Shortcuts" sequence="50"/>
            
            <menuitem id="menu_users" name="Users &amp; Companies" parent="menu_administration" sequence="1"/>
            <menuitem id="menu_translation" name="Translations" parent="menu_administration" sequence="2" groups="base.group_no_one"/>
                <menuitem id="menu_translation_app" name="Application Terms" parent="menu_translation" sequence="4" groups="base.group_no_one"/>
                <menuitem id="menu_translation_export" name="Import / Export" parent="menu_translation" sequence="3" groups="base.group_no_one"/>
            <menuitem id="menu_config" name="General Settings" parent="menu_administration" sequence="3"/>
  
            <menuitem id="menu_custom" name="Technical" parent="menu_administration" sequence="110" groups="base.group_no_one"/>
                <menuitem id="next_id_2" name="User Interface" parent="menu_custom"/>
                <menuitem id="menu_email" name="Email" parent="menu_custom" sequence="1"/>
                <menuitem id="next_id_9" name="Database Structure" parent="base.menu_custom"/>
                <menuitem id="menu_automation" name="Automation" parent="base.menu_custom"/>
                <menuitem id="menu_security" name="Security" parent="menu_custom" sequence="25"/>
                <menuitem id="menu_ir_property" name="Parameters" parent="menu_custom" sequence="24"/>
  
            <menuitem id="base.menu_tests" name="Tests" sequence="1000000" web_icon="test_exceptions,static/description/icon.png"/>
  
        <record model="ir.ui.menu" id="base.menu_administration">
            <field name="groups_id" eval="[(6,0, [ref('group_system'), ref('group_erp_manager')])]"/>
        </record>
  
        <record id="action_client_base_menu" model="ir.actions.client">
            <field name="name">Open Settings Menu</field>
            <field name="tag">reload</field>
            <field name="params" eval="{'menu_id': ref('base.menu_administration')}"/>
        </record>
        <record id="open_menu" model="ir.actions.todo">
            <field name="action_id" ref="action_client_base_menu"/>
            <field name="sequence">100</field>
            <field name="state">done</field>
        </record>
        <record id="action_open_website" model="ir.actions.act_url">
            <field name="name">Home Menu</field>
            <field name="target">self</field>
            <field name="url">/web</field>
        </record>
  </odoo>
  2021-11-30 20:30:02,805 9092 INFO gg odoo.modules.loading: loading 1 modules... 
  2021-11-30 20:30:02,819 9092 INFO gg odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries 
  2021-11-30 20:30:02,820 9092 ERROR gg odoo.sql_db: bad query: SELECT * FROM ir_model WHERE state='manual'
  ERROR: relation "ir_model" does not exist
  LINE 1: SELECT * FROM ir_model WHERE state='manual'
                        ^
   
  2021-11-30 20:30:02,822 9092 WARNING gg odoo.modules.loading: Transient module states were reset 
  2021-11-30 20:30:02,823 9092 ERROR gg odoo.modules.registry: Failed to load registry 
  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\registry.py", line 60, in __new__
      return cls.registries[db_name]
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\func.py", line 69, in wrapper
      return func(self, *args, **kwargs)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\tools\lru.py", line 44, in __getitem__
      a = self.d[obj].me
  KeyError: 'gg'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\registry.py", line 86, in new
      odoo.modules.load_modules(registry._db, force_demo, status, update_module)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\loading.py", line 374, in load_modules
      registry.setup_models(cr)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\modules\registry.py", line 248, in setup_models
      env['ir.model']._add_manual_models()
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\addons\base\models\ir_model.py", line 321, in _add_manual_models
      cr.execute('SELECT * FROM ir_model WHERE state=%s', ['manual'])
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\sql_db.py", line 173, in wrapper
      return f(self, *args, **kwargs)
    File "C:\Users\kaleb\PycharmProjects\odoo13\odoo-13.0\odoo\sql_db.py", line 250, in execute
      res = self._obj.execute(query, params)
  psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
  LINE 1: SELECT * FROM ir_model WHERE state='manual'
                        ^
  
  2021-11-30 20:30:02,932 9092 INFO gg odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=gg port=5433 sslmode=prefer' 
  2021-11-30 20:30:03,233 9092 INFO gg werkzeug: 127.0.0.1 - - [30/Nov/2021 20:30:03] "POST /web/database/create HTTP/1.1" 200 - 9942 36.721 7.910

**Comment by nilshamerlinck** [comment]
Hi @primeKal
- odoo 13.0 is not compatible with python 3.9 and this won't be fixed as per Odoo policy, see https://github.com/odoo/odoo/pull/71437#issuecomment-853865869
- ...but you can apply the following changes, it should work: https://github.com/OCA/OCB/pull/1037

**Comment by primeKal** [comment]
okay thank you very much, @nilshamerlinck

**Comment by nilshamerlinck** [comment]
You're welcome @primeKal :)

Would you mind closing your issue as a consequence?

**Comment by hema-28** [comment]
Maybe you forgot to add those addons in your addons_path configuration. 
Traceback (most recent call last):
  File "/home/hema/Documents/odoo-15.0/odoo/service/server.py", line 1210, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/home/hema/Documents/odoo-15.0/odoo/modules/module.py", line 407, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/hema/Documents/odoo-15.0/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/home/hema/Documents/odoo-15.0/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/home/hema/Documents/odoo-15.0/addons/web/controllers/main.py", line 29, in <module>
    from werkzeug.urls import url_encode, url_decode, iri_to_uri
ImportError: cannot import name 'url_encode' from 'werkzeug.urls' (/home/hema/Documents/odoo-15.0/venv/lib/python3.8/site-packages/werkzeug/urls.py)
2023-11-23 05:43:09,678 6470 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2023-11-23 05:43:09,943 6470 INFO ? odoo.service.server: HTTP service (werkzeug) running on Aspire-A515-56:1551 
2023-11-23 05:43:24,117 6470 INFO ? odoo.http: HTTP Configuring static files 
2023-11-23 05:43:24,130 6470 INFO demo odoo.modules.loading: loading 1 modules... 
2023-11-23 05:43:24,135 6470 INFO demo odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2023-11-23 05:43:24,229 6470 ERROR demo odoo.sql_db: bad query: SELECT * FROM ir_model WHERE state='manual'
ERROR: relation "ir_model" does not exist
LINE 1: SELECT * FROM ir_model WHERE state='manual'
                      ^
 
2023-11-23 05:43:24,230 6470 WARNING demo odoo.modules.loading: Transient module states were reset 
2023-11-23 05:43:24,230 6470 ERROR demo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/hema/Documents/odoo-15.0/odoo/modules/registry.py", line 61, in __new__
    return cls.registries[db_name]
  File "/home/hema/Documents/odoo-15.0/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hema/Documents/odoo-15.0/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hema/Documents/odoo-15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/hema/Documents/odoo-15.0/odoo/modules/loading.py", line 479, in load_modules
    registry.setup_models(cr)
  File "/home/hema/Documents/odoo-15.0/odoo/modules/registry.py", line 274, in setup_models
    env['ir.model']._add_manual_models()
  File "/home/hema/Documents/odoo-15.0/odoo/addons/base/models/ir_model.py", line 431, in _add_manual_models
    cr.execute('SELECT * FROM ir_model WHERE state=%s', ['manual'])
  File "<decorator-gen-5>", line 2, in execute
  File "/home/hema/Documents/odoo-15.0/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/home/hema/Documents/odoo-15.0/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "ir_model" does not exist
LINE 1: SELECT * FROM ir_model WHERE state='manual'
                      ^
                      here i'm using odoo-15 version and python version is 3.8.10 How to resolve the above error

**Comment by vava-odoo** [comment]
Fixed by https://github.com/odoo/odoo/pull/80999
