### ISSUE TITLE
[15] New Odoo Install - AttributeError: 'QWeb' object has no attribute 'env'

### ISSUE THREAD

**Issue by renshed** [odoo/odoo#80650]
Ubuntu Server 20.04

Odoo 15 Community

Steps to reproduce: 

Odoo Installation, Installation script and Manual installation

Current behavior: 

2021-11-30 19:14:10,930 7892 INFO ? werkzeug: 46.153.89.37 - - [30/Nov/2021 19:14:10] "GET /web/database/selector HTTP/1.0" 500 - 2 0.004 0.019
2021-11-30 19:14:10,938 7892 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 955, in _compile_directive_content
    if self.env.context.get('preserve_comments'):
AttributeError: 'QWeb' object has no attribute 'env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo15c/odoo15c-server/odoo/http.py", line 1458, in _dispatch_nodb
    result = request.dispatch()
  File "/odoo15c/odoo15c-server/odoo/http.py", line 810, in dispatch
    r = self._call_function(**self.params)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 360, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/odoo15c/odoo15c-server/addons/web/controllers/main.py", line 1079, in selector
    return self._render_template(manage=False)
  File "/odoo15c/odoo15c-server/addons/web/controllers/main.py", line 1074, in _render_template
    return QWeb()._render(html.document_fromstring(template), d, load=load)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 132, in _render
    render_template = self._compile(template, options)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 187, in _compile
    raise QWebException("Error when compiling xml template", self, options,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/odoo15c/odoo15c-server/odoo/service/wsgi_server.py", line 110, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/odoo15c/odoo15c-server/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 1313, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 1279, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 1491, in dispatch
    result = _dispatch_nodb()
  File "/odoo15c/odoo15c-server/odoo/http.py", line 1460, in _dispatch_nodb
    return request._handle_exception(e)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 748, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo15c/odoo15c-server/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: 'QWeb' object has no attribute 'env'
Traceback (most recent call last):
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/odoo15c/odoo15c-server/odoo/addons/base/models/qweb.py", line 955, in _compile_directive_content
    if self.env.context.get('preserve_comments'):
AttributeError: 'QWeb' object has no attribute 'env'

Error when compiling xml template
AttributeError: 'QWeb' object has no attribute 'env'
Template: <Element html at 0x7f9bd9df7f90> - - -

**Comment by renshed** [comment]
Before i was able to install odoo 15 CE in ubuntu 20.04 using odoo standard install, using odoo script install (by Yenthe666/InstallScript), and even odoo manual installation but now it's not working anymore due to the error related to QWeb.

Details:

Digital Ocean
Ubuntu 18.04 and ubuntu 20.04
Updated and Upgraded

Tried to install 5 times, its the same error

**Comment by imeshal88** [comment]
Same issue as well, last week i installed 2 servers with same steps but yesterday it shows same error that you faced.

**Comment by yaodongshi** [comment]
After the old development environment pulls the new code, it is impossible to create a new database, and the management data list prompts the same error as yours

**Comment by obayit** [comment]
Same here, https://github.com/odoo/odoo/issues/80655#issue-1068105177
It happened in the server after they did git pull to install the new saudi QR module.

**Comment by obayit** [comment]
BTW, `/web/login` works normally, you can configure the database in the config file as a workaround until we find a fix

**Comment by odony** [comment]
Fixed by #80666, thanks for reporting

**Comment by renshed** [comment]
It's Fixed. Thank you.

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/commit/a82c23aeb64669d58f8a47cfe01e81cfe33ef99e, I'll close it since nobody did.
