### ISSUE TITLE
[14.0 CE] Issue installing sale_management.

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#80662]
Impacted versions: 14.0

Steps to reproduce: 
Install `sale_management`

Current behavior:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f7446d3bbf8>, 'base.module_payment_sepa_direct_debit')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 564, in _tag_record
    f_val = self.id_get(f_ref)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 1928, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in xmlid_lookup
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 1921, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.module_payment_sepa_direct_debit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /.repo_requirements/odoo/addons/payment/data/payment_acquirer_data.xml:312, near
<record id="payment.payment_acquirer_sepa_direct_debit" model="payment.acquirer">
        <field name="name">SEPA Direct Debit</field>
        <field name="view_template_id" ref="default_acquirer_button"/>
        <field name="image_128" type="base64" file="base/static/img/icons/payment_sepa_direct_debit.png"/>
        <field name="module_id" ref="base.module_payment_sepa_direct_debit"/>
        <field name="description" type="html">
            <p>
                SEPA Direct Debit is a Europe-wide Direct Debit system that allows merchants to collect Euro-denominated payments from accounts in the 34 SEPA countries and associated territories.
            </p>
        </field>
    </record>
```

Expected behavior:

Module `payment_sepa_direct_debit` should be open sourced. If not the case, do not try load module on CE version.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
No need to opensource it, a record exists to fix this problem.  You probably do not have it because of local modifications or incorrect update/upgrade.

**Comment by GSLabIt** [comment]
@Feyensv not sure why i'm getting this issue. it seems we've last version from 14.0 branch:

```
Using Odoo from cache /.repo_requirements
[91mFrom https://github.com/odoo/odoo
* branch                14.0       -> FETCH_HEAD
355056e8f...3ae0b21f4 14.0       -> odoo/14.0  (forced update)
```
and we have the record u pointed out:

<img width="1023" alt="Schermata 2021-12-01 alle 11 43 32" src="https://user-images.githubusercontent.com/11652845/144220453-45c713d1-1ae0-4d52-a2b2-a346a149cb9b.png">

But, when installing sale management we're facing the issue

<img width="1272" alt="Schermata 2021-12-01 alle 11 35 55" src="https://user-images.githubusercontent.com/11652845/144219693-2ca8e071-e601-403f-b788-2d4b99770036.png">


Any hint?

**Comment by Feyensv** [comment]
I'm not knowledgeable enough on the upgrade/update inner code but I suppose your instance didn't start in v14, but in an earlier version, and the needed `ir.module.module` record wasn't successfully created during your upgrade.

You have to find a way to create this record (and reference) in your database, either through SQL/Python/... (I cannot ascertain that updating `base` won't modify existing data in your instance, but I believe it should also (re)create the missing record).

**Comment by pedrobaeza** [comment]
I think the problem is that you haven't upgrade `base` module before installing `sale_management`.

**Comment by GSLabIt** [comment]
@pedrobaeza it works, thx. Will investigate why it's not loading last version at initial setup.
