### ISSUE TITLE
Odoo 15 release 20211202 (odoo-15.0.post20211202) : Database creation error: module 'odoo.tests.runner' has no attribute 'OdooTestResult'

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#80710]
Impacted versions: 
- Odoo 15.0
- PostgreSQL 10
- Python 3.8.10

Steps to reproduce:
1. Start odoo from fresh source
2. Create a database from web/database/selector

Current behavior:
Shows "Database creation error: module 'odoo.tests.runner' has no attribute 'OdooTestResult' " on the screen after creating a new database from the web/database/selector

Expected behavior:
Should create database successfully

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![Screenshot 2021-12-02 172543](https://user-images.githubusercontent.com/7699250/144394414-4d02a6b2-edd7-43ab-8ce4-01cb31f1c2a3.png)

Logging
--------------------------------------
2021-12-02 09:15:21,714 17356 INFO ? werkzeug: 127.0.0.1 - - [02/Dec/2021 09:15:21] "GET /web/database/manager HTTP/1.1" 200 - 14 0.058 0.281
2021-12-02 09:15:59,633 17356 DEBUG ? odoo.service.server: cron0 polling for jobs
2021-12-02 09:16:00,662 17356 DEBUG ? odoo.service.server: cron1 polling for jobs
2021-12-02 09:16:09,506 17356 INFO None odoo.service.db: Create database `testdb15`.
2021-12-02 09:16:11,693 17356 ERROR None odoo.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "C:\Users\peter\Work\mywork\Python\odoo\odoo-15.0\odoo\odoo\service\db.py", line 63, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "C:\Users\peter\Work\mywork\Python\odoo\odoo-15.0\odoo\odoo\modules\registry.py", line 75, in new
    registry.init(db_name)
  File "C:\Users\peter\Work\mywork\Python\odoo\odoo-15.0\odoo\odoo\modules\registry.py", line 113, in init
    self._assertion_report = odoo.tests.runner.OdooTestResult()
AttributeError: module 'odoo.tests.runner' has no attribute 'OdooTestResult'

**Comment by peterhoth** [comment]
Found some corrupted files. Seems ok after redownload source again.
