### ISSUE TITLE
Cache problem on compose mail message wizard

### ISSUE THREAD

**Issue by doganaltunbay** [odoo/odoo#8088]
Compose mail message wizard causes exception when an e-mail template is selected which has a report attachment(i.e. Sale Order report). This happens during the on_change event of template_id field. This does not happen when I debug, where I wait a couple of seconds on one line. I think this is because of the cache update latency. The field resulting key error is file_type_icon, which is computed field.

Branch: master

Error message:

Odoo Server Error

Traceback (most recent call last):
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 819, in __call__
    return self.method(_args, *_kw)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/dogan/workspace/isg-erp/odoo/addons/web/controllers/main.py", line 937, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/dogan/workspace/isg-erp/odoo/openerp/models.py", line 5875, in onchange
    newval, record._origin, subfields.get(name),
  File "/home/dogan/workspace/isg-erp/odoo/openerp/fields.py", line 1738, in convert_to_write
    values = {k: record._cache[k] for k in record._get_dirty() if k in fnames}
  File "/home/dogan/workspace/isg-erp/odoo/openerp/fields.py", line 1738, in <dictcomp>
    values = {k: record._cache[k] for k in record._get_dirty() if k in fnames}
  File "/home/dogan/workspace/isg-erp/odoo/openerp/models.py", line 5927, in __getitem__
    value = self._recs.env.cache[field][self._recs.id]
KeyError: 558

**Comment by pedrobaeza** [comment]
That is not happening anymore, but master is expected to fail sometimes.
