### ISSUE TITLE
[8.0] stock valuation crashes for "Real Price"

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#8097]
When an item has "Real Price" inventory turned on.

Ensure some are on hand at the stock location.

Go to Reporting > Warehouse > Stock Valuation

Run for current date/time.

2015-08-17 00:13:08,207 5569 ERROR testdb openerp.sql_db: Programming error: syntax error at or near ")"
LINE 1: ...oduct_price_history WHERE product_template_id in () AND date...
                                                             ^
, in query SELECT DISTINCT ON (product_template_id, company_id) product_template_id, company_id, cost FROM product_price_history WHERE product_template_id in %s AND datetime <= %s ORDER BY product_template_id, company_id, datetime DESC
2015-08-17 00:13:08,207 5569 ERROR testdb openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/richard/src/odoo-8.0/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/richard/src/odoo-8.0/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/richard/src/odoo-8.0/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/richard/src/odoo-8.0/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/richard/src/odoo-8.0/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/richard/src/odoo-8.0/odoo/addons/stock_account/wizard/stock_valuation_history.py", line 66, in read_group
    cr.execute('SELECT DISTINCT ON (product_template_id, company_id) product_template_id, company_id, cost FROM product_price_history WHERE product_template_id in %s AND datetime <= %s ORDER BY product_template_id, company_id, datetime DESC', (tuple(cost_method_product_tmpl_ids), date))
  File "/home/richard/src/odoo-8.0/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/richard/src/odoo-8.0/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 1: ...oduct_price_history WHERE product_template_id in () AND date...

**Comment by jco-odoo** [comment]
I thought we put an if statement there.  Is it with the latest 8.0?  With at least one product non real price it should work.

**Comment by richard-willowit** [comment]
I have been directed by Odoo support to the latest code and yes, I noticed when I checked yesterday that new code had been inserted in June.

The client has extensive mods, so I will be treading carefully, but I will pull the latest base and test early next week, but on the surface, it appears to address the issue raised.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
