### ISSUE TITLE
Odoo_realestate_installation_problem

### ISSUE THREAD

**Issue by gemchand** [odoo/odoo#8116]
the following error apears when i trying to install  real estate module in odoo 8

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\base\module\module.py", line 725, in install_from_urls
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\base\module\module.py", line 446, in button_immediate_install
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\base\module\module.py", line 494, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\modules\loading.py", line 176, in load_module_graph
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\modules\loading.py", line 118, in _load_data
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\tools\convert.py", line 901, in convert_file
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\tools\convert.py", line 987, in convert_xml_import
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\tools\convert.py", line 853, in parse
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\tools\convert.py", line 763, in _tag_record
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\base\ir\ir_model.py", line 1077, in _update
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\openerp\addons\base\ir\ir_ui_view.py", line 264, in create
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 336, in old_api
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\models.py", line 4076, in create
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 463, in new_api
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\models.py", line 4267, in _create
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo_7\server\.\openerp\models.py", line 1271, in _validate_fields
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `country` does not exist

Error context:
View `res.partner.owner.select`
[view_id: 223, xml_id: n/a, model: res.partner, parent_id: n/a]" while parsing file:///C:/Users/ServerAdmin/AppData/Local/OpenERP%20S.A/Odoo7/addons/8.0/chricar_partner_parent_companies/partner_parent_companies_view.xml:331, near
<record id="view_res_partner_owner_filter" model="ir.ui.view">
            <field name="name">res.partner.owner.select</field>
            <field name="model">res.partner</field>
            <field name="type">search</field>
            <field name="arch" type="xml">
                <search string="Search Partner">
                   <group col="10" colspan="4">
                        <filter string="Customers" name="customer" icon="terp-personal" domain="[('customer','=',1)]" help="Customer Partners"/>
                        <filter string="Suppliers" name="supplier" icon="terp-personal" domain="[('supplier','=',1)]" help="Supplier Partners"/>
                        <separator orientation="vertical"/>
                        <field name="name"/>
                        <field name="country"/>
                   </group>
               </search>
            </field>
        </record>

Can everybody help regarding this issues?
Thank You

**Comment by purnendu03** [comment]
Hello gemchand,

It's because "country" is not defined in "res.partner" model.

Either you define country field on res.partner or just comment the field on view.

That will allow you to install the module.

Apply this patch in chricar_partner_parent_companies/partner_parent_companies_view.xml

       <record id="view_res_partner_owner_filter" model="ir.ui.view">
            <field name="name">res.partner.owner.select</field>
            <field name="model">res.partner</field>
            <field name="type">search</field>
            <field name="arch" type="xml">
                <search string="Search Partner">
                   <group col='10' colspan='4'>
                        <filter string="Customers" name="customer" icon="terp-personal" domain="[('customer','=',1)]" help="Customer Partners"/>
                        <filter string="Suppliers" name="supplier" icon="terp-personal" domain="[('supplier','=',1)]" help="Supplier Partners"/>
                        <separator orientation="vertical"/>
                        <field name="name" />
                        
                   </group>
               </search>
            </field>
        </record>

Hope this will help you.

Regards,
Purnendu Singh
Synconics Technologies Pvt. Ltd

**Comment by gemchand** [comment]
Hello purnendu03

   Thank you for your support . it really work for me and i successfully installed real estate module but in menu bar i was unable found any real estate related menu.

can you help me regarding this?

Thank You

**Comment by sohaibrafiq** [comment]
Maybe you can find menu by activating options from user settings

**Comment by gemchand** [comment]
When I am trying to install real estate addon(camptocamp/c2c-rd-addons) from github and then put in to addon folder of odoo and update module list and search real estate addon from local module . it does not  show any thing related to real estate.


can anybody help me regarding this issues?

Thank You

**Comment by purnendu03** [comment]
Hello,

camptocamp/c2c-rd-addons contains multiple modules in it.
Instead of adding these module to main addons source I would suggest to put it on a separate directory, and pass this directory path to --addons-path while starting odoo server. 
Note: You can also update the addons path from openerp-server.conf file.

Once you restart the odoo server update the module list and search for "c2c_real_estate".

Hope this will help you,

Regards,
Purnendu Singh
Synconics Technologies Pvt. Ltd

**Comment by khaledbenjannet** [comment]
After resolving the problem of the 'country' field I had another issue : 

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/odoo/.local/share/Odoo/addons/8.0/chricar_top/__init__.py", line 7, in <module>
    import location_income_tax
  File "/home/odoo/.local/share/Odoo/addons/8.0/chricar_top/location_income_tax.py", line 48, in <module>
    class stock_location(osv.osv):
  File "/opt/odoo/openerp/models.py", line 255, in __init__
    setattr(self, name, column.to_field())
  File "/opt/odoo/openerp/osv/fields.py", line 197, in to_field
    return Field.by_type[self._type](column=self, **self.to_field_args())
KeyError: 'dict'


Please I need help regarding this issue.

**Comment by Yenthe666** [comment]
Hi @gemchand,

Thank you for your report but we only handle bug reports that are about the official Odoo code.
I'm closing this issue since it is an external module, not a default Odoo module. If you still face this issue you can ask help on the official forums (help.odoo.com).

Regards,
Yenthe
