### ISSUE TITLE
[BUG] accounting reports: Memory errors because of shows a lot of records opening them

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#81266]
# Impacted versions:

Tested in 14.0

# Steps to reproduce:

1. Create 100k partners with invoices
2. Open the menu Accounting -> Reporting -> Partner Ledger (From [enterprise/account_reports](https://github.com/odoo/enterprise/tree/14.0/account_reports) module)

# Current behavior:

The following traceback is raised

```txt
  File "odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)                                                                                                                                             File "enterprise/account_reports/models/account_report.py", line 1167, in get_report_informations
    'main_html': self.get_html(options),
  File "enterprise/account_reports/models/account_report.py", line 1229, in get_html
    html = self.env.ref(template)._render(render_values)
  File "addons/website/models/ir_ui_view.py", line 411, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "odoo/addons/base/models/ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "odoo/addons/base/models/qweb.py", line 259, in _render
    return u''.join(body).encode('utf8')
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
MemoryError
```

# Expected behavior:

What about using a limit and pages similar to tree views?
In order to be able to filter the records or increase the quantity of records to see

**Comment by fmdl** [comment]
same as : https://github.com/odoo/odoo/issues/77529

**Comment by moylop260** [comment]
Thank you @fmdl 

I was worried that the ticket support team says me again: "I can not reproduced in runbot"

Similar to MemoryError with messages:
 - https://github.com/odoo/odoo/issues/79905

**Comment by fmdl** [comment]
@qdp-odoo can you check this ?
