### ISSUE TITLE
 psycopg2.DataError: division by zero

### ISSUE THREAD

**Issue by rishalchand94** [odoo/odoo#81354]
Hi, i am getting this error. Can someone help me here how to solve this.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo/addons/crm_dashboard/models/crm_dashboard.py", line 846, in lead_details_user
    ''' % (session_user_id, session_user_id))
  File "/opt/odoo13/odoo/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: division by zero

Rishal

**Comment by odooaktiv** [comment]
@rishalchand94 Can you please mention the steps to reproduce this error?

**Comment by rishalchand94** [comment]
Hi.

l have installed a v14 module on my Odoo 13. I am able to install it
successfully on Odoo 13.

However, now when I try to click on the module, it gives this error.

Unfortunately I am unable to get the log file, its giving permission error.

I have installed the CRM Dashboard 3rd party module.

[image: image.png]

Rishal

**Comment by odooaktiv** [comment]
@rishalchand94 Thanks for the information.

For custom module and technical help you can post your question on the Odoo Forum(https://www.odoo.com/forum/help-1) where you can get the help from the community.

Thanks.
