### ISSUE TITLE
ValueError: External ID not found in the system: base.module_category_services_timesheets

### ISSUE THREAD

**Issue by StarV5s** [odoo/odoo#81496]
Impacted versions:
14.0

Steps to reproduce:
create new database with only base web module

Current behavior:
In base/data/ir_module_module.xml, there is a base.module_category_services_timesheets reference at line 23, but there is no defination in base/data/ir_module_category_data.xml.

I found it at module hr_timesheet, but base module also not depends on it. 

log error:
```
2021-12-16 03:29:35,837 3125 INFO odoo_base odoo.modules.loading: loading base/data/ir_module_module.xml 
2021-12-16 03:29:35,864 3125 WARNING odoo_base odoo.modules.loading: Transient module states were reset 
2021-12-16 03:29:35,865 3125 ERROR odoo_base odoo.modules.registry: Failed to load registry 
2021-12-16 03:29:35,865 3125 ERROR odoo_base odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f14ded35158>, 'base.module_category_services_timesheets')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 564, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 660, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 666, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1881, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-36>", line 2, in xmlid_lookup
  File "/home/odoo/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo/odoo/addons/base/models/ir_model.py", line 1874, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.module_category_services_timesheets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/service/db.py", line 63, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/home/odoo/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/odoo/modules/loading.py", line 396, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/odoo/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/odoo/odoo/tools/convert.py", line 684, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
odoo.tools.convert.ParseError: while parsing /home/odoo/odoo/odoo/addons/base/data/ir_module_module.xml:19, near
<record model="ir.module.module" id="base.module_timesheet_grid">
            <field name="name">timesheet_grid</field>
            <field name="shortdesc">Timesheets</field>
            <field name="sequence">65</field>
            <field name="category_id" ref="base.module_category_services_timesheets"/>
            <field name="application" eval="True"/>
            <field name="summary">Track time &amp; costs</field>
            <field name="license">OEEL-1</field>
            <field name="author">Odoo S.A.</field>
            <field name="to_buy" eval="True"/>
            <field name="icon">/base/static/img/icons/timesheet_grid.png</field>
            <field name="website">https://www.odoo.com/page/timesheet-mobile-app?utm_source=db&amp;utm_medium=module</field>
        </record>
```
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/46417244/146304785-a0ad1dae-400d-4f2e-9c5f-49d73df38fb0.png)

**Comment by odooaktiv** [comment]
@StarV5s I am not able to regenerate this issue in V14. 
I am using latest build of Odoo v14 and created a new DB with base&web module.

**Comment by StarV5s** [comment]
> @StarV5s I am not able to regenerate this issue in V14. I am using latest build of Odoo v14 and created a new DB with base&web module.

Sry didn't mention it, I delete other modules except base and web first.

And m so confused about when my local files have other modules, there is no error when create a new database, when I delete them, the error occured.

But I see the log, before the error occured, other modules hasn't been loaded yet, and some of them are not suppose be loaded at all.

**Comment by ebirbe** [comment]
I confirm this error still exists in Odoo 17.0.

I'm trying to install the most basic Odoo framework, just leaving available `web` and `base` modules in the addons path.

In the middle of the installation of `base` module it returns this error in this exact same file as reported here.

**Comment by ebirbe** [comment]
I just found it is an issue that won't be fixed 😢 

**Desicion Statement:**

https://github.com/odoo/odoo/issues/71680#issuecomment-853887320

**Technical Cause:**

https://github.com/odoo/odoo/issues/59335#issuecomment-704742156

https://github.com/odoo/odoo/issues/59335#issuecomment-705109826
