### ISSUE TITLE
Create invoice move : invalid regular expression: quantifier operand invalid

### ISSUE THREAD

**Issue by rootkit7628** [odoo/odoo#81528]
Impacted versions: V14 EE enterprise

Steps to reproduce: Create Database >> Install Invoices Addons >> Create Invoice >> Bug
```
Odoo Server Error
Traceback (most recent call last):
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/account/models/account_move.py", line 1094, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/data/rfg.qualif.arkeup.com/server/odoo/models.py", line 6246, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/data/rfg.qualif.arkeup.com/server/odoo/models.py", line 5988, in _onchange_eval
    method_res = method(self)
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/account/models/account_move.py", line 418, in _onchange_journal
    if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
  File "/data/rfg.qualif.arkeup.com/server/odoo/addons/account/models/sequence_mixin.py", line 179, in _get_last_sequence
    self.env.cr.execute(query, param)
  File "<decorator-gen-3>", line 2, in execute
  File "/data/rfg.qualif.arkeup.com/server/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/data/rfg.qualif.arkeup.com/server/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/rfg.qualif.arkeup.com/server/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.DataError: invalid regular expression: quantifier operand invalid
```
![image](https://user-images.githubusercontent.com/60097202/146386346-4c145298-7173-43e5-b871-886a54853ee5.png)

**Comment by gaetan1903** [comment]
you guys mainty
