### ISSUE TITLE
Survey User Default Access Rights

### ISSUE THREAD

**Issue by amonang** [odoo/odoo#8153]
I'm using Odoo 8.

In the record rules for survey (*survey_users_access*), the domain is *[('stage_id.closed', '=', False)]*

This is causing the page to get a 403 error for regular users and thus not redirected to the survey.notopen page as intended.

I changed the rule to [(1, '=', 1)] and it successfully redirected to survey.notopen for survey users but I don't know yet how this will affect the other views.

```
Error log:
WARNING odoo openerp.addons.website.models.ir_http: 403 Forbidden:
Traceback (most recent call last):
  File "/opt/odoo/openerp/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/website/models/ir_http.py", line 177, in _postprocess_args
    _, path = rule.build(arguments)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 713, in build
    add(self._converters[data].to_url(values[data]))
  File "/opt/odoo/openerp/addons/website/models/ir_http.py", line 258, in to_url
    return slug(value)
  File "/opt/odoo/openerp/addons/website/models/website.py", line 115, in slug
    id, name = value.id, value.display_name
  File "/opt/odoo/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/opt/odoo/openerp/models.py", line 5934, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', u'The requested operation cannot be completed due to security \
restrictions. Please contact your system administrator.\n\n(Document type: survey.survey, \
Operation: read)')
```

**Comment by rim-odoo** [comment]
This record rule also prevent access from backend or XMLRPC
