### ISSUE TITLE
Start a Meeting> More> Settings It will lead to crash,

### ISSUE THREAD

**Issue by yaoyingkeji** [odoo/odoo#81539]
**Start a Meeting> More> Settings
It will lead to crash,
Rehaps 100% version: ODOO15.0**

UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of undefined (reading 'writeText')

TypeError: Cannot read properties of undefined (reading 'writeText')
    at ClientErrorDialog.onClickClipboard (http://192.168.1.5:8069/web/assets/117-08c87e8/web.assets_backend.min.js:371:48)
    at Object.extra.handlers.<computed> (eval at _compile (http://192.168.1.5:8069/web/assets/116-19e9020/web.assets_common.min.js:1016:178), <anonymous>:24:156)
    at invokeHandler (http://192.168.1.5:8069/web/assets/116-19e9020/web.assets_common.min.js:838:144)
    at handleEvent (http://192.168.1.5:8069/web/assets/116-19e9020/web.assets_common.min.js:842:92)
    at HTMLButtonElement.handler (http://192.168.1.5:8069/web/assets/116-19e9020/web.assets_common.min.js:844:58)

![录屏_选择区域_20211216230344](https://user-images.githubusercontent.com/93997433/146396690-738ef8e3-7cd1-4a4f-a9a6-423eaab7a3aa.gif)

**Comment by zashj** [comment]
I have a similar error, and this one comes up after installing a third-party module. How did you resolve this error?
