### ISSUE TITLE
Odoo 14.0 on FreeBSD: login throws exception

### ISSUE THREAD

**Issue by th3penguinwhisperer** [odoo/odoo#81706]
Impacted versions:
14.0

Steps to reproduce:
Login on /web/login

Current behavior:
Exception thrown:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/website/controllers/main.py", line 140, in web_login
    return super().web_login(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 948, in web_login
    return http.redirect_with_hash(self._login_redirect(uid, redirect=redirect))
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 176, in redirect_with_hash
    return werkzeug.utils.redirect(url, code)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/local/lib/python3.8/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/website/controllers/main.py", line 140, in web_login
    return super().web_login(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 948, in web_login
    return http.redirect_with_hash(self._login_redirect(uid, redirect=redirect))
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 176, in redirect_with_hash
    return werkzeug.utils.redirect(url, code)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/local/lib/python3.8/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
TypeError: a bytes-like object is required, not 'str'
`

Expected behavior:
No errors.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by th3penguinwhisperer** [comment]
If it would help anyone: Install using python3.7 through a VirtualEnv using the pip requirements file.
This got it working properly for me instead of the Odoo version supplied with FreeBSD.
