### ISSUE TITLE
[8.0] sql_db borrow does not handle DatabaseError

### ISSUE THREAD

**Issue by lefeverd** [odoo/odoo#8175]
Hello,
I have some Odoo instances connecting to a remote PostgreSQL through HAProxy.
In some circumstances, the connections are killed (if the HAProxy is restarted for instance).
This leads to an error when refreshing Odoo:
<pre><code>
5-08-20 18:25:16,704 22532 ERROR mydatabase openerp.service.server: Worker (22532) Exception occured, exiting...
Traceback (most recent call last):
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/service/server.py", line 767, in run
    self.process_work()
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/service/server.py", line 845, in process_work
    base.ir.ir_cron.ir_cron._acquire_job(db_name)
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/addons/base/ir/ir_cron.py", line 200, in _acquire_job
    cr = db.cursor()
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/sql_db.py", line 575, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/sql_db.py", line 181, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/sql_db.py", line 464, in _locked
    return fun(self, _args, *_kwargs)
  File "/usr/local/openerp/openerp-buildout/parts/addons/openerp/sql_db.py", line 499, in borrow
    cnx.reset()
DatabaseError: SSL SYSCALL error: EOF detected
</pre></code>

This could be avoided if catching the psycopg2.DatabaseError.

**Steps to reproduce**
As I said this happens to us when connecting to the database through a proxy (HAProxy), then killing the sessions or restarting the proxy.

**Current behaviour**
Odoo crashes when the user clicks anywhere, showing a blank page indicating an "Internal Server Error".

**Expected behaviour**
Odoo should continue to run normally, discarding the bad connections if needed.

**Comment by lefeverd** [comment]
Any thoughts on this issue?

**Comment by Yenthe666** [comment]
Hi @lefeverd,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
