### ISSUE TITLE
[14.0] TypeError: Many2many fields ir.actions.server.partner_ids and ir.actions.server.partner_ids use the same table and columns

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#81760]
Impacted versions: 14.0

Anyone is getting the same issue? 

```
Traceback (most recent call last):
2021-12-21 16:45:04,666 153 [1;32m[1;49mINFO[0m openerp_template odoo.modules.loading: Loading module website_mail (42/43) 
2021-12-21 16:45:04,724 153 [1;33m[1;49mWARNING[0m openerp_template odoo.modules.loading: Transient module states were reset 
2021-12-21 16:45:04,724 153 [1;31m[1;49mERROR[0m openerp_template odoo.modules.registry: Failed to load registry 
2021-12-21 16:45:04,724 153 [1;37m[1;41mCRITICAL[0m openerp_template odoo.service.server: Failed to initialize database `openerp_template`. 
  File "/.repo_requirements/odoo/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 173, in load_module_graph
    registry.setup_models(cr)
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 276, in setup_models
    model._setup_fields()
  File "/.repo_requirements/odoo/odoo/models.py", line 2845, in _setup_fields
    field.setup_full(self)
  File "/.repo_requirements/odoo/odoo/fields.py", line 399, in setup_full
    self._setup_regular_full(model)
  File "/.repo_requirements/odoo/odoo/fields.py", line 3473, in _setup_regular_full
    raise TypeError(msg % (self, field))
TypeError: Many2many fields ir.actions.server.partner_ids and ir.actions.server.partner_ids use the same table and columns

```

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ViktorFedoriv** [comment]
I get the same in essence and similar tracebackwise error in Odoo 14 during (or maybe slightly after) a post-init hook execution where I wrote following lines:
```python
module = env['ir.module.module'].search(some_domain)
if module.state == 'installed':
        module.button_immediate_uninstall()
```
The hook executes successfully and even the module gets deleted, but the error get throw afterwards.
My traceback:

```bash
2022-10-17 17:02:51,298 87377 INFO stage_2 odoo.modules.loading: Reloading registry once more after uninstalling modules 
2022-10-17 17:02:51,304 87377 INFO stage_2 odoo.modules.loading: loading 1 modules... 
2022-10-17 17:02:51,318 87377 INFO stage_2 odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2022-10-17 17:02:51,385 87377 INFO stage_2 odoo.modules.loading: updating modules list 
2022-10-17 17:02:51,386 87377 INFO stage_2 odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 127.0.0.1 
2022-10-17 17:02:51,825 87377 INFO stage_2 odoo.modules.loading: loading 177 modules... 
2022-10-17 17:02:52,057 87377 INFO stage_2 odoo.modules.loading: 177 modules loaded in 0.23s, 0 queries (+0 extra)
2022-10-17 17:02:53,309 87377 INFO stage_2 odoo.modules.loading: Modules loaded. 
2022-10-17 17:02:53,322 87377 INFO stage_2 odoo.addons.base.models.ir_module: getting next ir.actions.todo() 
2022-10-17 17:02:53,333 87377 INFO stage_2 odoo.modules.loading: Module module loaded in 9.42s, 649 queries (+6223 other) 
2022-10-17 17:02:53,334 87377 INFO stage_2 odoo.modules.loading: 180 modules loaded in 9.42s, 649 queries (+6223 extra) 
2022-10-17 17:02:53,387 87377 WARNING stage_2 odoo.modules.loading: Transient module states were reset 
2022-10-17 17:02:53,388 87377 ERROR stage_2 odoo.modules.registry: Failed to load registry 
2022-10-17 17:02:53,388 87377 ERROR stage_2 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/user_folder/odoo/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user_folder/odoo/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/user_folder/odoo/odoo14/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/user_folder/odoo/odoo14/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/user_folder/odoo/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/user_folder/odoo/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/user_folder/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/user_folder/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/user_folder/odoo/odoo14/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/user_folder/odoo/odoo14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user_folder/odoo/odoo14/odoo/modules/loading.py", line 470, in load_modules
    registry.setup_models(cr)
  File "/home/user_folder/odoo/odoo14/odoo/modules/registry.py", line 276, in setup_models
    model._setup_fields()
  File "/home/user_folder/odoo/odoo14/odoo/models.py", line 2845, in _setup_fields
    field.setup_full(self)
  File "/home/user_folder/odoo/odoo14/odoo/fields.py", line 399, in setup_full
    self._setup_regular_full(model)
  File "/home/user_folder/odoo/odoo14/odoo/fields.py", line 3471, in _setup_regular_full
    raise TypeError(msg % (self, field))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user_folder/odoo/odoo14/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Many2many fields ir.actions.server.partner_ids and ir.actions.server.partner_ids use the same table and columns
```
