### ISSUE TITLE
ir_attachment issue in odoo pod while deploying on IBM cloud

### ISSUE THREAD

**Issue by truthfool** [odoo/odoo#81839]
Impacted versions: 12.0

Steps to reproduce:

1. Go to 'charts/bitnami/odoo/'
2. Run using helm install ''helm install openg2p-erp12 -f values.yaml bitnami/odoo".(I have volume mounts on path '/mnt/extra-addons')
3. After the pod initializes see the logs.

Volume Mounts : 
```
extraVolumes:
  - name: odoo-addons
    emptyDir: {}
  - name: odoo-data-master
    emptyDir: {}
extraVolumeMounts:
  - name: odoo-addons  
    mountPath: "/mnt/extra-addons"
  - name: odoo-data-master
    mountPath: "/var/lib/odoo"
```

Current behavior:
The UI of the odoo v12 does not appear on port forward.
I'm facing attachment issue while deploying odoo 12 on the IBM cloud. I'm using bitnami helm charts for the deployment of odoo pod on the IBM cloud. I cannot delete tables as "ir_attachment" has media files and has foreign key in another table.There is nothing in network logs too.

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Logs of the odoo pod :
```
openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/api.py", line 1049, in get                                          │
│ openg2p-erp12-odoo     value = self._data[key][field][record._ids[0]]                                                                                      │
│ openg2p-erp12-odoo KeyError: 673                                                                                                                           │
│ openg2p-erp12-odoo During handling of the above exception, another exception occurred:                                                                     │
│ openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/fields.py", line 1064, in __get__                                   │
│ openg2p-erp12-odoo     value = record.env.cache.get(record, self)                                                                                          │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/api.py", line 1051, in get                                          │
│ openg2p-erp12-odoo     raise CacheMiss(record, field)                                                                                                      │
│ openg2p-erp12-odoo odoo.exceptions.CacheMiss: ('ir.attachment(673,).datas', None)                                                                          │
│ openg2p-erp12-odoo During handling of the above exception, another exception occurred:                                                                     │
│ openg2p-erp12-odoo Traceback (most recent call last):                                                                                                      │
│ openg2p-erp12-odoo   File "/opt/bitnami/odoo/lib/odoo-12.0.post20210815-py3.8.egg/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read       │
│ openg2p-erp12-odoo     r = base64.b64encode(open(full_path,'rb').read())                                                                                   │
│ openg2p-erp12-odoo FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/odoo/data/filestore/openg2p/ba/ba534fd56e5dde52f5a9fe9a8c7451c4cb │
│ 2ba3b3'

```

Expected behavior:
Odoo UI should come up successfully.

**Comment by truthfool** [comment]
@xrg can you help me with this?

**Comment by odony** [comment]
I'm afraid we can't help much for supporting bitnami charts, so I'll close this issue. You'll want to contact their bitnami maintainers instead. The error you quoted indicates that the filestore data is missing, which makes all binary fields unavailable too.

You could try to delete the assets from ir_attachment, and let the system attempt to regenerate them, but it unlikely to work if the filestore directory does not exist at all:
`DELETE FROM ir_attachment WHERE type = 'binary' AND url like '/web/%' AND res_field IS NULL`


BTW, Odoo 12 is out of support now, the only supported versions are 13, 14 and 15, so it's really recommended to start with a more recent version.

**Comment by truthfool** [comment]
okay thanks for the feedback.
