### ISSUE TITLE
[15.0] "scope.messageView.message.originThread.getMemberName is not a function" error after upgrade

### ISSUE THREAD

**Issue by geoextra** [odoo/odoo#82424]
Impacted versions: 15.0 (issue got introduced in nightly between 12/17/2021 and 12/31/2021)

Steps to reproduce: Upgrade Odoo through as a Debian package instance from 15.0.20211217 to 15.0.20220108. The error will immediately be thrown after logging in to the backend.

Current behavior:
The following client-side error gets displayed on nearly every page multiple times (stacked):
```
UncaughtPromiseError > TypeError
Uncaught Promise > scope.messageView.message.originThread.getMemberName is not a function
TypeError: scope.messageView.message.originThread.getMemberName is not a function
    at QWeb.eval (eval at _compile (https://[...]/web/assets/818-c1bdc82/web.assets_common.min.js:1026:178), <anonymous>:195:75)
    at QWeb.fn (https://[...]/web/assets/818-c1bdc82/web.assets_common.min.js:1008:173)
    at QWeb.render (https://[...]/web/assets/818-c1bdc82/web.assets_common.min.js:1015:20)
    at MessagingClass.__render (https://[...]/web/assets/818-c1bdc82/web.assets_common.min.js:1344:33)
    at MessagingClass.component.__render (https://[...]/web/assets/834-2b196c7/web.assets_backend.min.js:6204:10)
    at MessagingClass.__prepareAndRender (https://[...]/web/assets/818-c1bdc82/web.assets_common.min.js:1342:29)
```
The error reporting can be closed. Although, this widely limits functionality like for instance editing tasks in the Project view and makes the Odoo instance essentially unusable. 
I suspect the little message window on the bottom of the page to be the root cause since it needs to get rendered on every page. It is not visible on my broken instance.

This behaviour was also already described [here](https://www.odoo.com/forum/help-1/uncaught-promise-scope-messageview-message-originthread-getmembername-is-not-a-function-197343).

Expected behavior: No errors.

**Comment by moteuchi** [comment]
Upgrade to nightly 15.0.20220111 (Ubutut 20.04) and the same error:

TypeError: scope.messageView.message.originThread.getMemberName is not a function
    at QWeb.eval (eval at _compile (https://erp.consnaval.com/web/assets/173-efea723/web.assets_common.min.js:1026:178), <anonymous>:195:75)
    at QWeb.render (https://erp.consnaval.com/web/assets/173-efea723/web.assets_common.min.js:1015:20)
    at MessagingClass.__render (https://erp.consnaval.com/web/assets/173-efea723/web.assets_common.min.js:1344:33)
    at MessagingClass.component.__render (https://erp.consnaval.com/web/assets/233-1c61cee/web.assets_backend.min.js:6202:10)
    at MessagingClass.__prepareAndRender (https://erp.consnaval.com/web/assets/173-efea723/web.assets_common.min.js:1342:29)

**Comment by geoextra** [comment]
Thanks for the confirmation!
The error doesn't occur in debug mode with assets, which is currently a solid workaround. The minified production front-end bundle files do not seem to match the debug scripts. 
Maybe there has been a problem with rebuilding them after the package upgrade?

**Comment by sandstumpen** [comment]
Upgrade to 14.0 on 10.01.2022 with same error:

TypeError: scope.threadView.thread.getMemberName is not a function
    at QWeb.eval (eval at _compile (https://domain.de/web/content/381-3adccb5/web.assets_common.js:979:178), <anonymous>:141:59)
    at QWeb.fn (https://domain.de/web/content/381-3adccb5/web.assets_common.js:961:173)
    at QWeb.render (https://domain.de/web/content/381-3adccb5/web.assets_common.js:968:20)
    at Object.__owl__.renderFn (https://domain.de/web/content/381-3adccb5/web.assets_common.js:1318:113)
    at Message.__render (https://domain.de/web/content/381-3adccb5/web.assets_common.js:1298:33)
    at Message.__prepareAndRender (https://domain.de/web/content/381-3adccb5/web.assets_common.js:1296:29)

**Comment by JavierB7** [comment]
Upgrade to the latest version of Odoo 14 (Enterprise Edition) on 13/01/2022 with the same error:

![telegram-cloud-photo-size-1-5116579834213018154-y](https://user-images.githubusercontent.com/13892910/149343024-80c763c8-d2df-43c0-92ff-7d76d8bc099d.jpg)

**Comment by moteuchi** [comment]
Upgrade to 15.0.20220113 (CE) and the same error persists.
In debug mode doesn't occur in debug mode with assets.

**Comment by leimantas** [comment]
All files from nightly are from 2021 DECEMBER 15. *.deb *.tar.gz
No matter what day you choose. All files from this day. 

![image](https://user-images.githubusercontent.com/46538777/149399469-4694f959-e3a9-4cf4-aada-1a52e98dd0ae.png)

**Comment by PRTBELL** [comment]
Same problem. How do we fix this other than using it in debug mode?


Error:
--
 
Traceback:
TypeError: scope.threadView.thread.getMemberName is not a function
at QWeb.eval (eval at _compile (https://odoo.bellsaffron.com/web/content/131-e6e033c/web.assets_common.js:979:178), <anonymous>:141:59)
at QWeb.render (https://odoo.bellsaffron.com/web/content/131-e6e033c/web.assets_common.js:968:20)
at Object.__owl__.renderFn (https://odoo.bellsaffron.com/web/content/131-e6e033c/web.assets_common.js:1318:113)
at Message.__render (https://odoo.bellsaffron.com/web/content/131-e6e033c/web.assets_common.js:1298:33)
at Message.__prepareAndRender (https://odoo.bellsaffron.com/web/content/131-e6e033c/web.assets_common.js:1296:29)

**Comment by TheMatzy** [comment]
Same Problem at Odoo 14 Community Edition. Is there already a fix for it?

![grafik](https://user-images.githubusercontent.com/41703752/162942037-18b6217a-a332-441c-b9fa-14abc368c55c.png)

**Comment by PRTBELL** [comment]
Regenerating Asset Bundle Fixed the issue for me

Settings -> Developer mode -> Debug Icon -> Regenerate Asset Bundle


> Same Problem at Odoo 14 Community Edition. Is there already a fix for it?
> 
> ![grafik](https://user-images.githubusercontent.com/41703752/162942037-18b6217a-a332-441c-b9fa-14abc368c55c.png)

**Comment by aegirops** [comment]
Any update on this issue ?

We are still impacted in `Odoo 14.0-20220503 (Community Edition)`.

For our case, it appears that the 'Settings -> Developer mode -> Debug Icon -> Regenerate Asset Bundle' process doesn't fix the issue.

**Comment by Sum4196** [comment]
Bump. Still affected in version `Odoo 14.0-20220727 (Community Edition)`.
Like the above response from @aegirops -- Regenerate Asset Bundle did not fix the issue.

**Comment by Sum4196** [comment]
I had the issue with another site and it seems that the `Activate Assets Debugging` fixes the issue. I recommend trying the `Regenerate Assets Bundles` first and then open two instances of the site with debug mode on (**one instance in a separate browser or private window where the cookies/site data is not shared**) so you have control when the first one goes blank. After selecting `Activate Assets Debugging` your site will most likely go blank. This is fixed after refreshing a few times, but if not, you can try clicking the `Regenerate Assets Bundles` again on the second instance. If that still doesn't work, go back to the first instance and clear the cache; this usually fixes the issue.

Leaving this here to help others and possibly for myself in the future.

**Comment by deyanira87** [comment]
> I had the issue with another site and it seems that the `Activate Assets Debugging` fixes the issue. I recommend trying the `Regenerate Assets Bundles` first and then open two instances of the site with debug mode on (**one instance in a separate browser or private window where the cookies/site data is not shared**) so you have control when the first one goes blank. After selecting `Activate Assets Debugging` your site will most likely go blank. This is fixed after refreshing a few times, but if not, you can try clicking the `Regenerate Assets Bundles` again on the second instance. If that still doesn't work, go back to the first instance and clear the cache; this usually fixes the issue.
> 
> Leaving this here to help others and possibly for myself in the future.

Thanks a lot. This solved the problem to me

**Comment by bonarn** [comment]
You have to configure your odoo in "debug mode" and the problem will be solved.
