### ISSUE TITLE
[8.0] TypeError: _get_moves_taxes() got multiple values for keyword argument 'context'

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#8266]
When trying to generate an invoice after a delivery order is completed (from the warehouse menu) I get this error :

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock_account\wizard\stock_invoice_onshipping.py", line 105, in open_invoice
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock_account\wizard\stock_invoice_onshipping.py", line 148, in create_invoice
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock_account\stock.py", line 267, in action_invoice_create
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\stock_account\stock.py", line 298, in _invoice_create_line
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\openerp\addons\sale_stock\sale_stock.py", line 417, in _get_moves_taxes
  File "C:\Program Files (x86)\Odoo 8.0-20140920-000204\server\.\openerp\api.py", line 241, in wrapper
TypeError: _get_moves_taxes() got multiple values for keyword argument 'context'

If somebody can help...

**Comment by avanzella** [comment]
Found the problem: it was caused by mass editing module. After updating the module with latest version it works again.

**Comment by avanzella** [comment]
Problem solved. It was due to outdated code.
