### ISSUE TITLE
[15] Database creation error

### ISSUE THREAD

**Issue by ark-sparkprompt** [odoo/odoo#82843]
Impacted versions:15.0

Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

**Comment by jjackofall** [comment]
Facing the same issue.

**Comment by odony** [comment]
Thanks for reporting, and sorry for this problem, it's been introduced by my patch in #82838
The root cause for your problem is the following crash (you will see it in the server log before the SQL error you quoted):

```
Traceback (most recent call last):
  File "/home/odo/repositories/o/15.0/odoo/service/db.py", line 63, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/home/odo/repositories/o/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odo/repositories/o/15.0/odoo/modules/loading.py", line 415, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/odo/repositories/o/15.0/odoo/modules/loading.py", line 199, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/odo/repositories/o/15.0/odoo/modules/registry.py", line 427, in init_models
    model._auto_init()
  File "/home/odo/repositories/o/15.0/odoo/models.py", line 2795, in _auto_init
    raise_on_invalid_object_name(self._name)
  File "/home/odo/repositories/o/15.0/odoo/models.py", line 104, in raise_on_invalid_object_name
    raise ValueError(msg)
ValueError: The _name attribute MockIrQWeb is not valid.
```

I'm preparing a PR to fix this problem.

A workaround for now is to use the command-line to create the database, e.g. with `odoo-bin -d <dbname> -i base`

**Comment by ark-sparkprompt** [comment]
Appreciate your prompt response.

**Comment by odony** [comment]
You can try the patch in #82844, it should fix the issue :)
