### ISSUE TITLE
Cannot download or print confirmed invoices AttributeError: 'OdooPdfFileWriter' object has no attribute 'embed_odoo_attachment'

### ISSUE THREAD

**Issue by soomro30** [odoo/odoo#83013]
Impacted versions: 15

Steps to reproduce: Download Invoice or print confirmed invoice from website or admin

Current behavior:

Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 2001, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/odoo/odoo-server/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1934, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/odoo/odoo-server/addons/account/models/ir_actions_report.py", line 47, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 838, in _render_qweb_pdf
    return self_sudo._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/odoo/odoo-server/addons/account_edi/models/ir_actions_report.py", line 14, in _post_pdf
    pdf_content = invoice.journal_id.edi_format_ids._embed_edis_to_pdf(pdf_content, invoice)
  File "/odoo/odoo-server/addons/account_edi/models/account_edi_format.py", line 331, in _embed_edis_to_pdf
    edi_document.edi_format_id._prepare_invoice_report(writer, edi_document)
  File "/odoo/odoo-server/addons/account_edi_facturx/models/account_edi_format.py", line 55, in _prepare_invoice_report
    pdf_writer.embed_odoo_attachment(edi_document.attachment_id, subtype='application/xml')
AttributeError: 'OdooPdfFileWriter' object has no attribute 'embed_odoo_attachment'

Expected behavior:

Should Download the invoice pdf.

Video/Screenshot link (optional):
![Screen Shot 2022-01-18 at 11 24 40 PM](https://user-images.githubusercontent.com/1238737/150004818-a42d80d4-2507-46bf-acd9-3345ee5ee537.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by MihranThalhath** [comment]
Hi,

Have you tried replicating the issue on runbot? Also have you tried pulling in the latest changes from the v15 branch?

**Comment by crane134a** [comment]
to solve this problem try to uninstall the account_edi_facturx module, it's work for me
