### ISSUE TITLE
First time authenticating using LDAP raises Internal Server Error 

### ISSUE THREAD

**Issue by mohameddagher** [odoo/odoo#83038]
Impacted versions: 15

Steps to reproduce: 
1- install "Authentication via LDAP "
2- Configure LDAP and check "Create User"
3- Login with LDAP user

Current behavior:
. User is created in database 
. logs show odoo.exceptions.CacheMiss: 'res.users(10,).totp_secret'
. Internal Server Error is raised with first user login trial only (Not all users have this issue).
Expected behavior:
. No errors raised
Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/api.py", line 879, in get
    return field_cache[record._ids[0]]
KeyError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/home/odoodev/odoo/env/odoo/api.py", line 882, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.users(10,).totp_enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/api.py", line 879, in get
    return field_cache[record._ids[0]]
KeyError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/home/odoodev/odoo/env/odoo/api.py", line 882, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.users(10,).totp_secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
  File "/home/odoodev/odoo/env/odoo/models.py", line 4248, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoodev/odoo/env/addons/auth_totp/models/res_users.py", line 42, in _compute_totp_enabled
    r.totp_enabled = bool(v.totp_secret)
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1087, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: res.users(10,), User: 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/api.py", line 879, in get
    return field_cache[record._ids[0]]
KeyError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoodev/odoo/env/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/home/odoodev/odoo/env/odoo/api.py", line 882, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.users(10,).totp_secret'

Support ticket number submitted via odoo.com/help (optional):

**Comment by mohameddagher** [comment]
[https://github.com/odoo/odoo/issues/41060#issue-529963633](url)

**Comment by nrome-n** [comment]
Not sure if this is related but:
when ldap is enabled Login takes long time without any logs
then fails with LDAP exception without any info 
If I choose create it simply sends login failed without creating the user.

**Comment by bendem** [comment]
Hitting the same problem, I removed the totp module to check and the problem persists (albeit with a different stack):

```
2023-02-22 12:55:29,033 34 INFO aaaaaaaaa werkzeug: 192.168.83.60 - - [22/Feb/2023 12:55:29] "POST /web/login HTTP/1.1" 500 - 125 0.315 0.941
2023-02-22 12:55:29,044 34 ERROR aaaaaaaaa werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('res.users', <function Users.context_get at 0x7fa7771f8160>, 9)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 810, in dispatch
    r = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 872, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1039, in authenticate
    self.finalize()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1051, in finalize
    self.get_context()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1091, in get_context
    self.context = dict(request.env['res.users'].context_get() or {})
File "<decorator-gen-105>", line 2, in context_get

File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 667, in context_get
    values = user.read(list(name_to_key), load=False)[0]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 110, in application
    return ProxyFix(application_unproxied)(environ, start_response)
File "/usr/lib/python3/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1341, in __call__
    return self.dispatch(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1307, in __call__
    return self.app(environ, start_wrapped)
File "/usr/lib/python3/dist-packages/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1536, in dispatch
    result = ir_http._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 620, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 748, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
IndexError: list index out of range - - -
