### ISSUE TITLE
QWebTemplateNotFound: Template 'web.menu' not found

### ISSUE THREAD

**Issue by ObieBent** [odoo/odoo#8309]
Hi all, I'm facing to a Internal Server Error on my server Ubuntu 14.04LTS where I've installed Odoo 8. It runs well before I created a new module to modify the default layout. Here is the output of this error 
###### #####################################################################

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1290, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1264, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1440, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo/openerp/http.py", line 1371, in get_response
    result = request.registry['ir.http']._handle_exception(e)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 1368, in get_response
    result.flatten()
  File "/opt/odoo/odoo/openerp/http.py", line 1241, in flatten
    self.response.append(self.render())
  File "/opt/odoo/odoo/openerp/http.py", line 1235, in render
    context=request.context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1026, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 262, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 437, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 446, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 262, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_qweb.py", line 199, in get_template
    raise QWebTemplateNotFound("Template %r not found" % name, template=origin_template)
QWebTemplateNotFound: Template 'web.menu' not found
###### ###################################################################

I made some research on Google and I found there was a problem for referrencing the 'web.menu' in the postgres database.  It is possible or I must be wrong ? Please help to solve this problem. 

Regards 
Obie Bentley

**Comment by Yenthe666** [comment]
Hi there,

Sorry for the late reply on this issue.
At this point Odoo 8 is no longer supported and end of life, because of this I'm closing this issue.

Regards,
Yenthe
