### ISSUE TITLE
Error <span t-esc="o.l10n_mx_edi_amount_to_text()"/>

### ISSUE THREAD

**Issue by IsisAth** [odoo/odoo#83157]
Al querer imprimir una factura me muestra este error.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_7400
  File "<template>", line 2, in body_call_content_7398
  File "/home/odoo/src/enterprise/13.0/l10n_mx_edi/models/account_invoice.py", line 318, in l10n_mx_edi_amount_to_text
    words = self.currency_id.with_context(lang=self.partner_id.lang or 'es_ES').amount_to_text(amount_i).upper()
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_currency.py", line 117, in amount_to_text
    amt_value=_num2words(integer_value, lang=lang.iso_code),
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_currency.py", line 101, in _num2words
    return num2words(number, lang=lang).title()
  File "/usr/local/lib/python3.6/dist-packages/num2words/__init__.py", line 73, in num2words
    lang = lang[:2]
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/13.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/13.0/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/13.0/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 6264, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 6043, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/odoo/13.0/addons/account/wizard/account_invoice_send.py", line 68, in onchange_is_email
    self.composer_id.onchange_template_id_wrapper()
  File "/home/odoo/src/odoo/13.0/addons/mail/wizard/mail_compose_message.py", line 384, in onchange_template_id_wrapper
    values = self.onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/home/odoo/src/odoo/13.0/addons/mail/wizard/mail_compose_message.py", line 405, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/home/odoo/src/odoo/13.0/addons/mail/wizard/mail_compose_message.py", line 546, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/home/odoo/src/enterprise/13.0/l10n_mx_edi/models/mail_template.py", line 11, in generate_email
    res = super(MailTemplate, self).generate_email(res_ids, fields=fields)
  File "/home/odoo/src/odoo/13.0/addons/mail/models/mail_template.py", line 447, in generate_email
    result, format = report.render_qweb_pdf([res_id])
  File "/home/odoo/src/odoo/13.0/addons/account/models/ir_actions_report.py", line 50, in render_qweb_pdf
    return super().render_qweb_pdf(res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 771, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 812, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions_report.py", line 551, in render_template
    return view_obj.render_template(template, values)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/src/odoo/13.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_with_payments_7309
  File "<template>", line 2, in body_call_content_7307
  File "<template>", line 3, in foreach_7306
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 340, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_7400
  File "<template>", line 2, in body_call_content_7398
  File "/home/odoo/src/enterprise/13.0/l10n_mx_edi/models/account_invoice.py", line 318, in l10n_mx_edi_amount_to_text
    words = self.currency_id.with_context(lang=self.partner_id.lang or 'es_ES').amount_to_text(amount_i).upper()
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_currency.py", line 117, in amount_to_text
    amt_value=_num2words(integer_value, lang=lang.iso_code),
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_currency.py", line 101, in _num2words
    return num2words(number, lang=lang).title()
  File "/usr/local/lib/python3.6/dist-packages/num2words/__init__.py", line 73, in num2words
    lang = lang[:2]
TypeError: 'bool' object is not subscriptable

Error to render compiling AST
TypeError: 'bool' object is not subscriptable
Template: account.report_invoice_document
Path: /t/t/div/t[4]/p/span
Node: <span t-esc="o.l10n_mx_edi_amount_to_text()"/>

No he logrado dar con el error...

**Comment by odoochina-dev** [comment]
```
File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/res_currency.py", line 101, in _num2words
return num2words(number, lang=lang).title()
File "/usr/local/lib/python3.6/dist-packages/num2words/init.py", line 73, in num2words
lang = lang[:2]
TypeError: 'bool' object is not subscriptable
```

It looks like a configure issue. 
The partner_id (for who you print the account_invoice) has been setup to a lang which does not installed in odoo?  (and cause the `lang = tools.get_lang(self.env)` in res_currency.py amount_to_text() func, returns a boolean value(False) instead of the expected string value (e.g. 'es_ES') and thus cause `lang = lang[:2]` raise the exception.

Set the partner_id's lang to a lang installed in the odoo (or unset lang for the partner) would resolve the issue.
