### ISSUE TITLE
ERP BUG Odoo with stable version

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#8317]
Getting issues, we found below issue raises, but not show in front end.

Look at this issue please.

2015-09-01 11:56:45,149 12984 INFO sanjorg openerp.addons.base.ir.ir_http: Generating routing map
2015-09-01 11:56:45,157 12984 INFO fornhork openerp.addons.base.ir.ir_http: Generating routing map
2015-09-01 11:56:45,158 12984 INFO demo openerp.addons.base.ir.ir_http: Generating routing map
2015-09-01 11:56:45,160 12984 INFO demo openerp.addons.base.ir.ir_http: Generating routing map
2015-09-01 11:56:49,619 12984 INFO flxex openerp.addons.base.ir.ir_http: Generating routing map
2015-09-01 11:56:51,386 12984 ERROR flxex openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/bugerp/v8/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bugerp/v8/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/home/bugerp/v8/odoo/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by rim-odoo** [comment]
It looks like that some JSON request has triggered a 404 HTTP error, but with no more information on what you're trying to achieve, it is impossible to help you more.
