### ISSUE TITLE
[14.0] discuss bug missed object

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#83200]
Impacted versions:

- [ ] 14.0

Steps to reproduce:
create a ticket on helpdesk app, assign to user, delete ticket 

Current behavior:
Actually on Odoo the notify is kept when the object is delete and we have this message for istance 
![image](https://user-images.githubusercontent.com/43987335/150553531-7367eea9-183e-4583-b5fd-92e953dad776.png)

Expected behavior:
When the ticket is canceled the linked notify should disappear

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/43987335/150553912-a11ae2aa-af6d-44a0-8358-1fe92d6e8ee0.png)

Support ticket number submitted via odoo.com/help (optional):
2753528

**Comment by matteoopenf** [comment]
I also se in the console:

 Error message: Odoo Server Error 
 Error data message:
 Record does not exist or has been deleted.
(Record: helpdesk.ticket(153,), User: 6) 
 Error data debug:
 Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1392, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/user/printnode_base/controllers/main.py", line 50, in _call_kw
    return super(DataSetProxy, self)._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/mail/models/mail_message.py", line 1071, in message_fetch
    return messages.message_format()
  File "/home/odoo/src/odoo/addons/sms/models/mail_message.py", line 43, in message_format
    message_values = super(MailMessage, self).message_format()
  File "/home/odoo/src/odoo/addons/mail/models/mail_message.py", line 1115, in message_format
    vals_list = self._message_format(self._get_message_format_fields())
  File "/home/odoo/src/odoo/addons/portal_rating/models/mail_message.py", line 20, in _message_format
    vals_list = super(MailMessage, self)._message_format(fnames)
  File "/home/odoo/src/odoo/addons/mail/models/mail_message.py", line 1015, in _message_format
    record_name = self.env[message_sudo.model] \
  File "/home/odoo/src/odoo/odoo/fields.py", line 1023, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4070, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/odoo/models.py", line 1728, in _compute_display_name
    names = dict(self.name_get())
  File "/home/odoo/src/enterprise/helpdesk/models/helpdesk_ticket.py", line 467, in name_get
    result.append((ticket.id, "%s (#%d)" % (ticket.name, ticket._origin.id)))
  File "/home/odoo/src/odoo/odoo/fields.py", line 1002, in __get__
    raise MissingError("\n".join([
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: helpdesk.ticket(153,), User: 6)

**Comment by matteoopenf** [comment]
> Hi Matteo, thanks for the feedback regarding this. There's a fix in progress to address this you can follow - #84863
> 
> > Impacted versions:
> > 
> > * [ ]   14.0
> > 
> > Steps to reproduce: create a ticket on helpdesk app, assign to user, delete ticket
> > Current behavior: Actually on Odoo the notify is kept when the object is delete and we have this message for istance ![image](https://user-images.githubusercontent.com/43987335/150553531-7367eea9-183e-4583-b5fd-92e953dad776.png)
> > Expected behavior: When the ticket is canceled the linked notify should disappear
> > Video/Screenshot link (optional): ![image](https://user-images.githubusercontent.com/43987335/150553912-a11ae2aa-af6d-44a0-8358-1fe92d6e8ee0.png)
> > Support ticket number submitted via odoo.com/help (optional): 2753528

Hi, I don't understand if is merged or not, because a customer yesterday open a new ticket with similar message

**Comment by seb-odoo** [comment]
1. the fix is merged but it was not necessarily deployed (at the time)
2. the fix is only to prevent "new dead messages" from appearing, but existing dead messages have to be cleaned manually to resolve the issue

This last point was mentioned on the related PR but apparently nothing has been done?

**Comment by matteoopenf** [comment]
> This last point was mentioned on the related PR but apparently nothing has been done?

Hi @seb-odoo , thanks for reply.

Ok for old messages is not fix, and only the new messages.

But yesterday my customer have again the problem with an assigned purchase order, in this case is deleted the PO and not the ticket of helpdesk.

In this case case the app Discuss is blocked until, in manual mode I delete the notification.
My customer is an e-commerce and use a lot the the app discuss, is also an enterprise User and it is hosted on odoo.sh.

I also open a ticket and number is 2753528

The answer is, when will you deploy the fix?

**Comment by matteoopenf** [comment]
> It depends where is the database hosted? I believe the update is done every week on the saas, I'm not sure about .sh but I assume you might have to do it yourself (for example if a commit has a conflict with custom code I assume you would have to resolve it first), and on premise you would have to do it yourself for sure.

I know on odoo.sh the last release is apply by odoo and not by me.
How can I know if there is a conflict, and the deploy is not will be done?
Thanks

**Comment by seb-odoo** [comment]
I have no idea actually, I'm from dev team not support, your best bet would be to check the doc or contact the support to get help on that.

**Comment by matteoopenf** [comment]
> I have no idea actually, I'm from dev team not support, your best bet would be to check the doc or contact the support to get help on that.

ok i reply to the support and when confirm the fix is deployed I will close the issue

**Comment by matteoopenf** [comment]
the support confirm me is deployer I close the Issue.
Thanks for support
