### ISSUE TITLE
Payslip printing has an error

### ISSUE THREAD

**Issue by repany** [odoo/odoo#83458]
Impacted versions: odoo 15

Steps to reproduce: Payroll --> Payslips --> All Payslips --> Select an Employee --> Print

Current behavior: Return error
```
2022-01-27 02:13:55,583 2717458 INFO odoo werkzeug: 127.0.0.1 - - [27/Jan/2022 02:13:55] "GET /web/assets/267-c6b0450/web.report_assets_common.min.css HTTP/1.0" 200 - 2 0.001 0.007
2022-01-27 02:13:55,923 2717462 INFO ? werkzeug: 127.0.0.1 - - [27/Jan/2022 02:13:55] "GET /web/static/fonts/lato/Lato-LigIta-webfont.woff HTTP/1.0" 200 - - - -
2022-01-27 02:13:56,735 2717466 INFO odoo longpolling: 127.0.0.1 - - [2022-01-27 02:13:56] "POST /longpolling/im_status HTTP/1.0" 200 444 0.007759 
2022-01-27 02:13:56,958 2717448 INFO odoo odoo.addons.base.models.ir_actions_report: The PDF report has been generated for model: hr.payslip, records [18]. 
2022-01-27 02:13:56,974 2717448 INFO odoo werkzeug: 127.0.0.1 - - [27/Jan/2022 02:13:56] "GET /print/payslips?list_ids=18 HTTP/1.0" 200 - 120 0.041 1.950
2022-01-27 02:13:56,976 2717448 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo15/odoo15-venv/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo15/odoo15-venv/lib/python3.8/site-packages/werkzeug/serving.py", line 297, in execute
    write(data)
  File "/opt/odoo15/odoo15-venv/lib/python3.8/site-packages/werkzeug/serving.py", line 258, in write
    self.send_header(key, value)
  File "/usr/lib/python3.8/http/server.py", line 517, in send_header
    ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 65-66: ordinal not in range(256) - - -
```
Expected behavior: Print Payslip

**Comment by odoochina-dev** [comment]
the pdf has ben generated(`The PDF report has been generated for model: hr.payslip, records [18]. `, and `"GET /print/payslips?list_ids=18 HTTP/1.0" 200 ` also response correctly.), issue occur when werkzeug sendback the pdf filename in http response header, some character in the pdf filename cannot be decoded by 'latin-1' codec.
```
hr_payroll\controllers\main.py
        pdfhttpheaders = [
            ('Content-Type', 'application/pdf'),
            ('Content-Length', len(merged_pdf)),
            ('Content-Disposition', 'attachment; filename=' + report_name + '.pdf;')
        ]

        return request.make_response(merged_pdf, headers=pdfhttpheaders)  # <--------- here when werkzeug compose the response header, for report_name
```

Did you customize the report file name?  If yes, check the template's `print_report_name` ; or fallback this odoo user's lang to default english, does it works?,  to narrow the issue.
(or you can change this line `report_name` to fixed value "testing", and restart odoo, to quick verify the issue.)

**Comment by repany** [comment]
Thanks for your feedback
I found the problem because the payroll name (`report_name`) contains unicode character so the error occurs.
