### ISSUE TITLE
[15] Generating new website fails at configurator/5

### ISSUE THREAD

**Issue by pongraczi** [odoo/odoo#83871]
### Impacted versions: 
15.0.20220201 community

### OS
Debian 10.11

### Steps to reproduce: 
Creating new website using the configurator

### Current behavior: 
Exception happens, configurator stuck in phase 5, exceptions in the log, the UI become inaccessible, have to restart the odoo service and and clear cookies from browser (probably restarting odoo service is not neccessary, I didn't try yet)

### Expected behavior: 
After some magic the generated page should appear

### Video/Screenshot link (optional):
https://youtu.be/IFnas-C7o6g

### Relevant part from the odoo-server.log

```
022-02-02 18:44:53,775 1891 INFO evaldb01 odoo.addons.iap.tools.iap_tools: iap jsonrpc https://website.api.odoo.com/api/website/2/configurator/custom_resources/791 
2022-02-02 18:44:54,277 1891 ERROR evaldb01 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5193, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1348, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 585, in configurator_apply
    configure_page(page_code, snippet_lists.get(page_code, []), pages_views, cta_data)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 452, in configure_page
    page_view_id.save(value=''.join(rendered_snippets), xpath="(//div[hasclass('oe_structure')])[last()]")
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 509, in save
    self.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5196, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: ir.ui.view()
2022-02-02 18:44:54,370 1891 WARNING evaldb01 odoo.fields: product.dynamic.fields.ttype: selection attribute will be ignored as the field is related 
2022-02-02 18:44:54,371 1891 WARNING evaldb01 odoo.fields: product.dynamic.fields.ttype: selection_add attribute will be ignored as the field is related 
2022-02-02 18:44:54,445 1891 WARNING evaldb01 odoo.fields: recurring.payment.recurring_period: selection attribute will be ignored as the field is related 
2022-02-02 18:44:54,446 1891 WARNING evaldb01 odoo.fields: recurring.payment.journal_state: selection attribute will be ignored as the field is related 
2022-02-02 18:44:54,525 1891 WARNING evaldb01 odoo.fields: Field budget.budget.state: unknown parameter 'track_visibility', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2022-02-02 18:44:54,530 1891 WARNING evaldb01 odoo.fields: Redundant default on recurring.payment.recurring_interval 
2022-02-02 18:44:54,530 1891 WARNING evaldb01 odoo.fields: Redundant default on recurring.payment.journal_state 
2022-02-02 18:44:54,884 1891 INFO evaldb01 werkzeug: 10.0.2.65 - - [02/Feb/2022 18:44:54] "POST /web/dataset/call_kw/website/configurator_apply HTTP/1.1" 200 - 7414 4.218 13.
```

### Other information
* It doesn't matter the domain is different than the fqdn used to access the odoo (for example blahblah.startit.hu), the result is the same
* To get odoo at least work I have to cry, yell, threaten, curse etc. besides of restarting odoo service, deleting cookies, trying to find an url which actually works somehow etc. (sorry, I can't reproduce, how, even after I tried about 20 times today).
* I tried to choose different color schema, theme, descriptions, doesn't matter, same results.

### Addons
```
barcode_scanning_sale_purchase
base_account_budget
base_accounting_kit
bi_convert_purchase_from_sales
bi_project_issue_sequence
deltatech_product_dimension
dynamic_product_fields
elearning_download_pdf
fl_so_po_multi_products
hspl_attachment_size
jt_amount_in_words
ob_login_language
om_account_asset
om_recurring_payments
product_images_olbs
website_customer_order_comment
website_customer_order_delivery_date
website_product_publish
```

**Comment by pongraczi** [comment]
Sorry, the video was private by default, I fixed it, now it is visible.

**Comment by pongraczi** [comment]
Ooooops, it seems I am on the nightly build channel.........   
Hmmm, I guess in this case that would be interesting if everything works as expected.

**Comment by icoco** [comment]
looks same question question:
while I setup a website, it show this log message :

`  odoo.addons.iap.tools.iap_tools: iap jsonrpc https://website.api.odoo.com/api/website/1/configurator/industries `

  so it is meaning if we use odoo as platform, we   should always be online ( keep connection to odoo.com) ?

**Comment by bnisevic** [comment]
I get the same on a server. I am not sure why. UFW allows 443/tcp connections.
