### ISSUE TITLE
[15.0] ir_actions_report: assert len(outlines_pages) == len(res_ids)

### ISSUE THREAD

**Issue by hedshefer** [odoo/odoo#84221]
Impacted versions:
15.0
Steps to reproduce:
create some invoices with html content including <h> tags in the narration (terms and condition) standard field.
Go to invoices, select more than one, and print.

Current behavior:
The narration html field brakes the standard ir_actions_report logic because of the following logic:
odoo/addons/base/models/ir_actions_report.py:
# In case of multiple docs, we need to split the pdf according the records.
# To do so, we split the pdf based on top outlines computed by wkhtmltopdf.
# An outline is a <h?> html tag found on the document. To retrieve this table,
# we look on the pdf structure using pypdf to compute the outlines_pages from
# the top level heading in /Outlines.
The current output is assertion error and blank pages

**Comment by a-willem** [comment]
Seconded, been running into this issue today : printing (generating a PDF) individually is working perfectly, but "batch" printing (an edited invoice_document having more than one <hX> header, for instance) results in this assertion failure.

**Comment by hedshefer** [comment]
@mart-e

**Comment by mart-e** [comment]
Hello,

Please copy the traceback you have. If you modify the report with some specific html, it's also a good idea to post it in the issue, it will help debugging.
Thanks

**Comment by hedshefer** [comment]
Currently, we facing the issue while using some values in the html field called narration and the html in the layout.

**Comment by mart-e** [comment]
> we facing the issue while using **some values**

This is what we need to know to repoduce. I tried to print several invoices with html content in the terms but got no problem. Please share more details on your issue or contact the support with your database so they can investigate but here, sorry, I don't have enough information to help you.

**Comment by hedshefer** [comment]
@mart-e 
I was able to reproduce it today again in the odoo runbot V 15.0:

Steps:
1) user set to hebrew
2)Create 3 invoices with multiple lines,  and set the Terms and conditions(narration) to "ddsf sdaגדכבגדgh" as h1 element.
3) print the 3 invoices in one merged PDF
Video:
https://watch.screencastify.com/v/25cSesdZPuwYUWI86yBv
Then I get the following traceback:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/addons/web/controllers/main.py", line 2020, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/data/build/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1949, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/data/build/odoo/addons/account/models/ir_actions_report.py", line 49, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/data/build/odoo/odoo/addons/base/models/ir_actions_report.py", line 858, in _render_qweb_pdf
    return self_sudo._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/data/build/odoo/addons/account_edi/models/ir_actions_report.py", line 16, in _post_pdf
    return super(IrActionsReport, self)._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=res_ids)
  File "/data/build/odoo/addons/account/models/ir_actions_report.py", line 26, in _post_pdf
    return super(IrActionsReport, self)._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=res_ids)
  File "/data/build/odoo/odoo/addons/base/models/ir_actions_report.py", line 688, in _post_pdf
    assert len(outlines_pages) == len(res_ids)
AssertionError

* sometimes it works with no traceback but the split not working properly (the header is not complete and there is missing information in the PDF of some records)
