### ISSUE TITLE
key error 

### ISSUE THREAD

**Issue by sokalo** [odoo/odoo#8424]
Traceback (most recent call last):
  File "/home/bod/server/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bod/server/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/home/bod/server/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/bod/server/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/home/bod/server/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/home/bod/server/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/bod/server/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/bod/server/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/bod/server/odoo/openerp/modules/loading.py", line 423, in load_modules
    registry['ir.module.module'].module_uninstall(cr, SUPERUSER_ID, modules_to_remove.values())
  File "/home/bod/server/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/addons/base/module/module.py", line 462, in module_uninstall
    ir_model_data._module_data_uninstall(cr, uid, modules_to_remove, context)
  File "/home/bod/server/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/addons/base/ir/ir_model.py", line 1217, in _module_data_uninstall
    ir_model_constraint._module_data_uninstall(cr, uid, constraint_ids, context)
  File "/home/bod/server/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/bod/server/odoo/openerp/addons/base/ir/ir_model.py", line 575, in _module_data_uninstall
    model_obj = self.pool[model]
  File "/home/bod/server/odoo/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'hotel.guest.line'

**Comment by sokalo** [comment]
please help me for that issue

**Comment by mart-e** [comment]
The model `hotel.guest.line` does not exists in standard Odoo so it's most likely due to the use of a custom module. You should look in that direction (no idea what module you are using)
