### ISSUE TITLE
[8.0]install Purchase Management error

### ISSUE THREAD

**Issue by seanmars** [odoo/odoo#8442]
When i install, i got this message:

```
Traceback (most recent call last):
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/mars/projects/odoo-dev/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/mars/projects/odoo-dev/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mars/projects/odoo-dev/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/addons/base/module/module.py", line 490, in _button_immediate_function
    function(cr, uid, ids, context=context)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/addons/base/module/module.py", line 413, in button_install
    self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context=context)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/addons/base/module/module.py", line 390, in state_update
    for dep in module.dependencies_id:
  File "/home/mars/projects/odoo-dev/odoo/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/home/mars/projects/odoo-dev/odoo/openerp/fields.py", line 910, in determine_value
    record._prefetch_field(self)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/models.py", line 3233, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/models.py", line 3178, in read
    self._read_from_database(stored, inherited)
  File "/home/mars/projects/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/models.py", line 3302, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/home/mars/projects/odoo-dev/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mars/projects/odoo-dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by Yenthe666** [comment]
Hi @seanmars,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
