### ISSUE TITLE
[8.0] Issue with @api.depends() and store and inherits

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#8461]
### Impacted versions:

8.0
### Steps to reproduce:

Having a One2many field to an inherits object like `hr.analytic.timesheet` using field defined on inherited object `account.analytic.line`.

```
# -*- coding: utf-8 -*-
from openerp import models, fields, api


class ProjectTask(models.Model):
    _inherit = 'project.task'

    ts_line_ids = fields.One2many('hr.analytic.timesheet', 'task_id')

    failing_field = fields.Float(compute='_get_invoiced_hours', store=True)

    @api.one
    # This would pervent creation of timesheet lines
    # as task_id (counter part of ts_line_ids) is defined on the analytic line
    # whereas the ts_line_ids is defined on hr.analytic.timesheet
    @api.depends('ts_line_ids')
    def _get_invoiced_hours(self):
        """ Sum timesheet line invoiced hours """
        self.failing_field = len(self.work_ids)


class AnalyticAccountLine(models.Model):
    _inherit = 'account.analytic.line'

    task_id = fields.Many2one('project.task')
```

Here is the dummy module with the same code to test it:
https://github.com/yvaucher/project-service/tree/8.0-inherits-depends/test_inherits_depends

With this installed, let's try to create an hr.analytic.timesheet.line in timesheet sheet
### Current behavior:

It will try to read the field `task_id` from the wrong table. (in fact tracing it shows it read it in both table)

BLAM:

```
Traceback (most recent call last):
  File ".../openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File ".../openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File ".../openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File ".../openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File ".../openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File ".../openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File ".../openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File ".../addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File ".../addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File ".../openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File ".../addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../addons/hr_timesheet_sheet/hr_timesheet_sheet.py", line 79, in create
    return super(hr_timesheet_sheet, self).create(cr, uid, vals, context=context)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File ".../openerp/models.py", line 4083, in create
    record = self.browse(self._create(old_vals))
  File ".../openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File ".../openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File ".../openerp/models.py", line 4268, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File ".../openerp/osv/fields.py", line 811, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../addons/hr_timesheet/hr_timesheet.py", line 192, in create
    return super(hr_analytic_timesheet, self).create(cr, uid, vals, context=context)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File ".../openerp/models.py", line 4083, in create
    record = self.browse(self._create(old_vals))
  File ".../openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File ".../openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File ".../openerp/models.py", line 4255, in _create
    recs.modified(self._fields)
  File ".../openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File ".../openerp/models.py", line 5677, in modified
    spec += self._fields[fname].modified(self)
  File ".../openerp/fields.py", line 1493, in modified
    spec = super(_Relational, self).modified(records)
  File ".../openerp/fields.py", line 960, in modified
    target = env[field.model_name].search([(path, 'in', records.ids)])
  File ".../openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File ".../openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File ".../openerp/models.py", line 1645, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../openerp/models.py", line 4663, in _search
    query = self._where_calc(cr, user, args, context=context)
  File ".../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File ".../openerp/models.py", line 4474, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File ".../openerp/osv/expression.py", line 647, in __init__
    self.parse(cr, uid, context=context)
  File ".../openerp/osv/expression.py", line 958, in parse
    push(create_substitution_leaf(leaf, ('id', o2m_op, select_distinct_from_where_not_null(cr, column._fields_id, comodel._table)), model))
  File ".../openerp/osv/expression.py", line 431, in select_distinct_from_where_not_null
    cr.execute('SELECT distinct("%s") FROM "%s" where "%s" is not null' % (select_field, from_table, select_field))
  File ".../openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File ".../openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "task_id" does not exist
LINE 1: SELECT distinct("task_id") FROM "hr_analytic_timesheet" wher...
```
### Expected behavior:

I can create my timesheet line and it update the computed store field

This might be quite similar to https://bugs.launchpad.net/openobject-server/+bug/704922
but in a API 8.0 way.

**Comment by Yenthe666** [comment]
Hi @yvaucher,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
