### ISSUE TITLE
[14] can't add attachment,  FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SamuelLHuber** [odoo/odoo#84783]
Impacted versions: 14.0 on Ubuntu 20.04. LTS

Steps to reproduce: Add attachment to message/log in crm, project or discuss

Current behavior: Infinite loading circle and no attachment being added (file not uploaded)

Expected behavior: Adding attachment uploads selected file(s) to message/log

```
2022-02-17 02:48:49,973 1330794 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/odoo/2f/2f7028932480cdcb927f83b0165d577669e620fa  Traceback (most recent call last):  File "/home/odoo/git/odoo/odoo/api.py", line 789, in get  field_cache = field_cache[record.env.cache_key(field)]  KeyError: (None, None)   

During handling of the above exception, another exception occurred:   Traceback (most recent call last):  File "/home/odoo/git/odoo/odoo/fields.py", line 970, in __get__  value = env.cache.get(record, self)  File "/home/odoo/git/odoo/odoo/api.py", line 793, in get  raise CacheMiss(record, field)  odoo.exceptions.CacheMiss: 'ir.attachment(4,).datas'   

During handling of the above exception, another exception occurred:   Traceback (most recent call last):  File "/home/odoo/git/odoo/odoo/api.py", line 789, in get  field_cache = field_cache[record.env.cache_key(field)]  KeyError: (None,)   

During handling of the above exception, another exception occurred:   Traceback (most recent call last):  File "/home/odoo/git/odoo/odoo/fields.py", line 970, in __get__  value = env.cache.get(record, self)  File "/home/odoo/git/odoo/odoo/api.py", line 793, in get  raise CacheMiss(record, field)  odoo.exceptions.CacheMiss: 'ir.attachment(4,).raw' 

  During handling of the above exception, another exception occurred:   Traceback (most recent call last):  File "/home/odoo/git/odoo/odoo/addons/base/models/ir_attachment.py", line 102, in _file_read  with open(full_path, 'rb') as f:  FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/.local/share/Odoo/filestore/odoo/2f/2f7028932480cdcb927f83b0165d577669e620fa'

```

**Comment by sennhvi** [comment]
Hello, I got same issue, have this problem been solved? I'd like to know how to fix this error, Thank you.

**Comment by wm-cortex** [comment]
Hello, I'm getting the same error in Odoo 16.0

**Comment by SamuelLHuber** [comment]
> Hello, I got same issue, have this problem been solved? I'd like to know how to fix this error, Thank you.

Haven't found a solution yet. Just switched away from Odoo. Seemed like you'd need the enterprise version to get it to work by using the Documents extension.
