### ISSUE TITLE
[8.0] raise NotFound()  404: Not Found

### ISSUE THREAD

**Issue by Dayssam** [odoo/odoo#8479]
Hi everyone,

I got this unkonwn error periodically

2015-09-10 11:42:02,220 26677 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 1413, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by florca1979** [comment]
Dayssam hello has been able to solve the problem
to me the same thing is happening to me

**Comment by Little-Jerry** [comment]
Can you describe the flow ? when you get this error ? Thanks

**Comment by click2prasanth** [comment]
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 1413, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found


this was happens when i created the portal user from login page , after that i log-in by admin, in that time it shows this error

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
On a sidenote: refreshing the page shouldwork just fine.

Regards,
Yenthe
