### ISSUE TITLE
[8.0] TypeError: <generator object <genexpr> at 0x7f4ce17ac050> is not JSON serializable

### ISSUE THREAD

**Issue by Dayssam** [odoo/odoo#8480]
Hi 

i got this error when i click in a tree element

Traceback (most recent call last):
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 354, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <generator object <genexpr> at 0x7f4ce17ac050> is not JSON serializable

**Comment by Yenthe666** [comment]
Hi @Dayssam,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
