### ISSUE TITLE
[Saas-6] [enterprise] crm VoIP. Error in Phone Calls analysis Pivot

### ISSUE THREAD

**Issue by ygol** [odoo/odoo#8502]
Replicate:
-------------
runbot http://100980-saas-6-b9517e.runbot8.odoo.com/web#view_type=kanban&model=ir.module.module&menu_id=52&action=36

install CRM
install Odoo VOIP

visit reporting / Phone Calls analysis

you get following error:

```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 814, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/addons/web/controllers/main.py", line 968, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/addons/web/controllers/main.py", line 960, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/addons/web/controllers/main.py", line 959, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/models.py", line 2136, in read_group
    cr.execute(query, where_clause_params)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/100980-saas-6-b9517e/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column crm_phonecall_report.create_date does not exist
LINE 2: ...onth', timezone('Europe/Brussels', timezone('UTC',"crm_phone...
                                                             ^
```

**Comment by sle-odoo** [comment]
Closing as this seems to be fixed now.
Regards!
