### ISSUE TITLE
9.0 hr_expense: cash when using "Generate single accounting entry" on several hr.expense entries

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#8540]
Here are the steps to reproduce the crash:
1) Connect to runbot 9.0 as admin
2) Go to the "Expenses" menu
3) In the tree view, select the 2 demo entries in "To submit" mode and do "Action > Submit expenses"
4) Approve each of the 2 demo entries
5) Select again the 2 demo entries and do "Action > Generate Single Accounting Entry": you get the crash

```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 828, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/addons/web/controllers/main.py", line 1222, in run
    [action_id], request.context)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/http.py", line 933, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/addons/base/ir/ir_actions.py", line 1074, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/addons/base/ir/ir_actions.py", line 900, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/addons/hr_expense/models/hr_expense.py", line 213, in action_move_create
    'journal_id': self.journal_id.id,
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/fields.py", line 806, in __get__
    record.ensure_one()
  File "/home/odoo/runbot/extra/runbot/static/build/101778-9-0-f29d81/openerp/models.py", line 5352, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: "Expected singleton: hr.expense(1, 2)" while evaluating
u"self.action_move_create(cr, uid, context.get('active_ids', []), context=context)"
```

**Comment by alexis-via** [comment]
You can fix the technical issue by changing "self" by "self[0]" in hr_expense.py line 213 and 214. Once this is fixed, it won't crash anymore, but the generated account move is not appropriate because it has 2 lines for the supplier account, instead of just once... and this requires deeper changes in the method "action_move_create".

**Comment by alexis-via** [comment]
The bug is still present in the final version of Odoo 9.0.

**Comment by Yenthe666** [comment]
Hi @alexis-via,

I've just tested it on the latest Odoo 9.0 and it works fine:
![image](https://user-images.githubusercontent.com/6352350/36089791-e169b3ca-0fdd-11e8-8845-de2dfcee5c36.png)

Please update your local Odoo instance if you still face it.

Regards,
Yenthe
