### ISSUE TITLE
FAIL: TestUi.test_04_product_configurator

### ISSUE THREAD

**Issue by vannyong** [odoo/odoo#85466]
ERROR | server | FAIL: TestUi.test_04_product_configurator Traceback (most recent call last):   File "/home/odoo/src/odoo/addons/point_of_sale/tests/test_frontend.py", line 525, in test_04_product_configurator     self.start_tour("/pos/ui?config_id=%d" % self.main_pos_config, 'ProductConfiguratorTour', login="accountman")   File "/home/odoo/src/odoo/odoo/tests/common.py", line 1616, in start_tour     return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)   File "/home/odoo/src/odoo/odoo/tests/common.py", line 1596, in browser_js     self.fail('%s\n%s' % (message, error)) AssertionError: The test code "odoo.startTour('ProductConfiguratorTour')" failed Tour ProductConfiguratorTour failed at step product configurator is shown (trigger: .product-configurator-popup:not(:has(.oe_hidden)))
-- | -- | --

I got this error, Can anyone guide me through this?

**Comment by duong77476** [comment]
Have you found the solution and why?
