### ISSUE TITLE
[14.0] repair: error when deleting Pricelist default value on form view

### ISSUE THREAD

**Issue by SimoneVagile** [odoo/odoo#85518]
Impacted versions:
14.0

Steps to reproduce:
- Enable "Basic pricelist" on User settings;
- Go to Repairs and create a new order;
- Choose an Invoice Method different from "No Invoice";
- Delete default value of Pricelist field, leaving it empty.

Current behavior:
It raises:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/odoo/models.py", line 6269, in onchange
    todo = [
  File "/data/build/odoo/odoo/models.py", line 6272, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/data/build/odoo/odoo/models.py", line 6089, in has_changed
    return self[name] != record[name]
  File "/data/build/odoo/odoo/models.py", line 5687, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/data/build/odoo/odoo/fields.py", line 969, in __get__
    self.recompute(record)
  File "/data/build/odoo/odoo/fields.py", line 1155, in recompute
    self.compute_value(recs)
  File "/data/build/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/data/build/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/data/build/odoo/odoo/models.py", line 4070, in _compute_field_value
    getattr(self, field.compute)()
  File "/data/build/odoo/addons/repair/models/repair.py", line 129, in _amount_untaxed
    order.amount_untaxed = order.pricelist_id.currency_id.round(total)
  File "/data/build/odoo/odoo/addons/base/models/res_currency.py", line 133, in round
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5012, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: res.currency()
```
Expected behavior:
No errors when deleting field value.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/5ef00fcdccf788ab33789d505f88ec1bc0750d4d https://github.com/odoo/odoo/pull/85519
