### ISSUE TITLE
[9.0] AttributeError: 'NoneType' object has no attribute 'product_variant_ids' - Sales > Settings

### ISSUE THREAD

**Issue by Cafeinoman** [odoo/odoo#8558]
Context : installation on-site on a Debian 8 VM for test purpose; Creation of 1 product with 2 variants (2 attribute, 1 with same value, 1 with 2 different values, different prices); Only 1 admin user;

On click on Sales > Settings, got this error : 
```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 542, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 579, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 824, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 408, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 973, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 965, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/res/res_config.py", line 541, in default_get
    res.update(getattr(self, method)(cr, uid, fields, context))
  File "/opt/odoo/odoo-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/sale/res_config.py", line 98, in get_default_deposit_values
    'deposit_property_account_income_id': deposit_product_template.product_variant_ids.property_account_income_id.id,
AttributeError: 'NoneType' object has no attribute 'product_variant_ids'
```

After error, half of the interface freeze on page change (noted after all errors) :

![capture d ecran de 2015-09-17 10 27 31](https://cloud.githubusercontent.com/assets/8056970/9928578/766a7034-5d27-11e5-9841-c3dbffc3cfc8.png)

**Comment by mart-e** [comment]
Should be fixed at 3e59febb1660c5c27fc83bc78240a707d5539722, the field `deposit_property_account_income_id` no longer exists in v9
