### ISSUE TITLE
Qrcode l10n_ch not print

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#85614]
Impacted versions:

- [ ] 14.0

Steps to reproduce:
try to print qr code 

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 547, in barcode
    return barcode.asString('png')
  File "/usr/lib/python3/dist-packages/reportlab/graphics/shapes.py", line 854, in asString
    return renderPM.drawToString(self, fmt=format,showBoundary=getattr(self,'showBorder',
  File "/usr/lib/python3/dist-packages/reportlab/graphics/renderPM.py", line 685, in drawToString
    drawToFile(d,s,fmt=fmt, dpi=dpi, bg=bg, configPIL=configPIL)
  File "/usr/lib/python3/dist-packages/reportlab/graphics/renderPM.py", line 681, in drawToFile
    c.saveToFile(fn,fmt)
  File "/usr/lib/python3/dist-packages/reportlab/graphics/renderPM.py", line 313, in saveToFile
    im = self.toPIL()
  File "/usr/lib/python3/dist-packages/reportlab/graphics/renderPM.py", line 309, in toPIL
    getattr(im,'frombytes',getattr(im,'fromstring'))(self._gs.pixBuf)
  File "/home/odoo/.local/lib/python3.8/site-packages/PIL/Image.py", line 519, in __getattr__
    raise AttributeError(name)
AttributeError: fromstring

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/account/models/res_bank.py", line 125, in _get_qr_code_base64
    barcode = self.env['ir.actions.report'].barcode(**params)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 552, in barcode
    raise ValueError("Cannot convert into QR code.")
ValueError: Cannot convert into QR code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 2130, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 2061, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/home/odoo/src/odoo/addons/account/models/ir_actions_report.py", line 50, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 820, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 860, in _render_qweb_html
    data = self._get_rendering_context(docids, data)
  File "/home/odoo/src/odoo/addons/account/models/ir_actions_report.py", line 55, in _get_rendering_context
    return super()._get_rendering_context(docids=docids, data=data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 877, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
  File "/home/odoo/src/odoo/addons/l10n_ch/report/swissqr_report.py", line 15, in _get_report_values
    qr_code_urls[invoice.id] = invoice.partner_bank_id.build_qr_code_base64(invoice.amount_residual, invoice.ref or invoice.name, invoice.payment_reference, invoice.currency_id, invoice.partner_id, qr_method='ch_qr', silent_errors=False)
  File "/home/odoo/src/odoo/addons/account/models/res_bank.py", line 72, in build_qr_code_base64
    return self._get_qr_code_base64(
  File "/home/odoo/src/odoo/addons/account/models/res_bank.py", line 130, in _get_qr_code_base64
    raise werkzeug.exceptions.HTTPException(description='Cannot convert into barcode.')
werkzeug.exceptions.HTTPException: ??? Unknown Error: Cannot convert into barcode.

Expected behavior:
print pdf 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
2782484

**Comment by niyasraphy** [comment]
Hi,
I hope this is the reason for it: https://groups.google.com/g/reportlab-users/c/ZDcJqmYv9Oo

**Comment by matteoopenf** [comment]
I check
