### ISSUE TITLE
InternalError: current transaction is aborted, while checking stock picking availability

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#8590]
maybe related to #8585 

versions affected: 8.0 at least

steps to reproduce:
- connect to runbot.odoo.com
- import a stock picking with 500 stock moves, each with 1 Printer All in One, from WH/Stock to Customers
- confirm the stock picking
- open a second browser tab. In that tab:
  - go to the Printer all in One product, and make an inventory adjustment to have 600 units in stock
- in the first browser tab, click on check availability for the picking
- switch back to the second tab and refresh (using Ctrl-F or F5)

Expected: the picking is availabe

```
Actual: I get a stack trace:
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/stock/stock.py", line 1392, in rereserve_pick
    self.rereserve_quants(cr, uid, pick, move_ids = [x.id for x in pick.move_lines], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/stock/stock.py", line 1401, in rereserve_quants
    stock_move_obj.do_unreserve(cr, uid, move_ids, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/stock/stock.py", line 1904, in do_unreserve
    self.write(cr, uid, [move.id], {'state': 'confirmed'}, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/purchase/stock.py", line 44, in write
    res = super(stock_move, self).write(cr, uid, ids, vals, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/mrp/stock.py", line 236, in write
    res = super(StockMove, self).write(cr, uid, ids, vals, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/stock/stock.py", line 2015, in write
    return super(stock_move, self).write(cr, uid, ids, vals, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 3779, in write
    self._write(old_vals)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 556, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 3827, in _write
    result = self._store_get_values(cr, user, ids, vals.keys(), context) or []
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 4334, in _store_get_values
    target_id_results[target_func_id_] = [i for i in store_trigger[target_ids_func_](self, cr, SUPERUSER_ID, ids, context) if i]
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/addons/mrp/mrp.py", line 548, in _mrp_from_move
    res += self.pool.get("mrp.production").search(cr, uid, [('move_lines', 'in', move.id)], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 1645, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 4664, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/models.py", line 4475, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/osv/expression.py", line 657, in __init__
    self.parse(cr, uid, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/osv/expression.py", line 957, in parse
    ids1 = select_from_where(cr, column._fields_id, comodel._table, 'id', ids2, operator)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/osv/expression.py", line 435, in select_from_where
    (select_field, from_table, where_field), (tuple(subids),))
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/102248-8-0-e11636/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by gurneyalex** [comment]
ping @odony

**Comment by alexis-via** [comment]
I am also affected by this issue on an up-to-date Odoo 8. Here is the scenario I use to reproduce the bug:
0) Create a new DB with demo data
1) Login as admin in this new DB
2) Install the module "base_location_geonames_import" from https://github.com/OCA/partner-contact
3) Add yourself to the Sales Manager and Technical Features group
4) Go to Sales > Configuration > Address book > Localization > Import from Geonames
5) In the wizard, select "France" as country and click on "Import"
6) When you see in the Odoo server logs "Starting to create the better zip entries", start another web browser and login as "admin" ; when logs the new user, it creates this crash:

```
2015-09-28 07:26:44,856 2511 INFO o8_bugtrans1 openerp.addons.base_location_geonames_import.wizard.geonames_import: Starting to download http://download.geonames.org/export/zip/FR.zip
2015-09-28 07:26:44,869 2511 INFO o8_bugtrans1 urllib3.connectionpool: Starting new HTTP connection (1): download.geonames.org
2015-09-28 07:26:46,067 2511 INFO o8_bugtrans1 openerp.addons.base_location_geonames_import.wizard.geonames_import: The geonames zipfile has been decompressed
2015-09-28 07:26:46,067 2511 INFO o8_bugtrans1 openerp.addons.base_location_geonames_import.wizard.geonames_import: Starting to create the better zip entries
[...]
2015-09-28 07:26:59,178 2511 INFO o8_bugtrans1 werkzeug: 127.0.0.1 - - [28/Sep/2015 07:26:59] "GET /web/binary/company_logo HTTP/1.1" 200 -
2015-09-28 07:27:04,670 2511 ERROR o8_bugtrans1 openerp.sql_db: bad query: INSERT INTO "res_better_zip" ("id", "city", "country_id", "name", "state_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_better_zip_id_seq'), 'Saint-Vincent-de-Tyrosse', 76, '40235 CEDEX', 60, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

2015-09-28 07:27:04,681 2511 INFO o8_bugtrans1 openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7569 sec...
2015-09-28 07:27:04,686 2511 INFO o8_bugtrans1 werkzeug: 127.0.0.1 - - [28/Sep/2015 07:27:04] "POST /web/login HTTP/1.1" 200 -
2015-09-28 07:27:04,886 2511 INFO o8_bugtrans1 werkzeug: 127.0.0.1 - - [28/Sep/2015 07:27:04] "GET /web?db=o8_bugtrans1 HTTP/1.1" 200 -
2015-09-28 07:27:05,152 2511 INFO o8_bugtrans1 werkzeug: 127.0.0.1 - - [28/Sep/2015 07:27:05] "GET /web/css/web.assets_common/35cab2c HTTP/1.1" 200 -
2015-09-28 07:27:05,443 2511 ERROR o8_bugtrans1 openerp.sql_db: bad query: SELECT "ir_config_parameter".id FROM "ir_config_parameter" WHERE ("ir_config_parameter"."key" = 'geonames.url') ORDER BY "ir_config_parameter"."id"  
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

> /home/alexis/new_boite/dev/odoo/openerp/sql_db.py(234)execute()
-> res = self._obj.execute(query, params)
```

If, on step 6, you login as demo user, you don't get the crash. If you execute the scenario as demo user and you login as demo user on step 6, you get the crash. So, you get the crash when you run the wizard as user X and, while the wizard is creating thousand of entries in the database, you login as user X from another web browser.

**Comment by moylop260** [comment]
@gurneyalex 
FYI Maybe fixed here:
https://github.com/odoo/odoo/commit/94a0bbed0a94e4bd34965c1466615d225ac8e509

**Comment by spadae22** [comment]
How about v8, we are getting : InternalError: current transaction is aborted, commands ignored until end of transaction block - everyday, when picking and creating invvoices.

**Comment by gurneyalex** [comment]
@spadae22 use base_concurrency (OCA module)

**Comment by spadae22** [comment]
Ok

**Comment by spadae22** [comment]
@gurneyalex Still had the issue again. I ran the cron a few hours before. But do they need all to log out, then log in? 7 out of 10 worked.

**Comment by gurneyalex** [comment]
@spadae22 if you're having issues with base_concurrency, please report an issue against OCA/server-tools. Otherwise there's nothing I can do for you and you'll have to discuss this with the odoo staff.

**Comment by Yenthe666** [comment]
Hi @gurneyalex ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
