### ISSUE TITLE
Error in test for decimal_precision

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#8611]
Impacted versions:

 - 8.0

Steps to reproduce:

 1. Add as data in the US lang, grouping = [1,1,1,1,1,1,1,1,1,1,-2]
 2. Create a new data base, and run all the test (As runbot)

Current behavior:

 - The test of decimal_precision generated the next error:
```
2015-09-18 17:33:42,036 1459 INFO odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: ======================================================================
2015-09-18 17:33:42,036 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: FAIL: test_basic_float (openerp.addons.decimal_precision.tests.test_qweb_float.TestFloatExport)
2015-09-18 17:33:42,036 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: Traceback (most recent call last):
2015-09-18 17:33:42,036 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: `   File "/Users/luistorres/odoo/mod_odoo/decimal_precision/tests/test_qweb_float.py", line 20, in test_basic_float
2015-09-18 17:33:42,036 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: `     "42.0")
2015-09-18 17:33:42,036 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: ` AssertionError: u'4,2.0' != '42.0'
2015-09-18 17:33:42,037 1459 INFO odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: ======================================================================
2015-09-18 17:33:42,037 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: FAIL: test_precision_domain (openerp.addons.decimal_precision.tests.test_qweb_float.TestFloatExport)
2015-09-18 17:33:42,037 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: Traceback (most recent call last):
2015-09-18 17:33:42,037 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: `   File "/Users/luistorres/odoo/mod_odoo/decimal_precision/tests/test_qweb_float.py", line 55, in test_precision_domain
2015-09-18 17:33:42,037 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: `     '42.00')
2015-09-18 17:33:42,037 1459 ERROR odoo_data openerp.addons.decimal_precision.tests.test_qweb_float: ` AssertionError: u'4,2.00' != '42.00'
```

Expected behavior:

 - I hope that all test pass.

I was generated the next PR to can show the error https://github.com/odoo/odoo/pull/8610/

**Comment by beledouxdenis** [comment]
Dear Luis, 

Tests are supposed to be ran on new databases only.
Changing the grouping of the `en_US` language is not supposed to happen in a new database.

If you do this in a custom module, changing the grouping format, you should adapt the test in your custom module.

Regards,
