### ISSUE TITLE
[9.0] Tuple index out of range

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#8659]
After doing some settings on accounting, installing a few new modules i ot this when click Accounting
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 828, in __call__
    return self.method(*args, **kw)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/aeroclub/odoo/90/sources/server/addons/web/controllers/main.py", line 913, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/aeroclub/odoo/90/sources/server/addons/web/controllers/main.py", line 934, in do_search_read
    request.context)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/http.py", line 933, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/models.py", line 5225, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/models.py", line 3166, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/models.py", line 3212, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/models.py", line 5658, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/fields.py", line 816, in __get__
    self.determine_value(record)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/fields.py", line 920, in determine_value
    self.compute_value(recs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/fields.py", line 875, in compute_value
    self._compute_value(records)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/fields.py", line 491, in <lambda>
    return lambda recs, *args, **kwargs: getattr(recs, name)(*args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 380, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/aeroclub/odoo/90/sources/server/addons/account/models/account_journal_dashboard.py", line 15, in _kanban_dashboard
    self.kanban_dashboard = json.dumps(self.get_journal_dashboard_datas())
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/aeroclub/odoo/90/sources/server/addons/account/models/account_journal_dashboard.py", line 181, in get_journal_dashboard_datas
    'account_balance': formatLang(self.env, account_sum, currency_obj=self.currency_id or self.company_id.currency_id),
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/tools/misc.py", line 1149, in formatLang
    lang_obj = lang_objs[0]
  File "/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/models.py", line 5662, in __getitem__
    return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range
```

**Comment by qtheuret** [comment]
Which modules did you install ?

**Comment by SBollatti** [comment]
Almost all instead of Website Live chat, Lunch, Admin accounting, MRP.
Argentinian localization and 0% tax on buy and sales, a few account for
accounting.
2 new users, and problems changing pswd and login in on every user.

I runned in virtualenv a cloned v9rc1 with postgresql 9.4

**Comment by mart-e** [comment]
Have you disabled `en_US` language ? Looks like the issue is rendering in a language not installed.

**Comment by SBollatti** [comment]
Yes, i tryed but coulndt.

**Comment by mart-e** [comment]
Well looks like you have succeeded to desactivate it and it wasn't a good idea :)
en_US is the master language of Odoo so removing it breaks in lot's of places.
I have prevented to deactivate it at 60fad17c0c253eea6b390c13f4e1752a29ee3769

**Comment by SBollatti** [comment]
Yes, i droped db
