### ISSUE TITLE
[9.0] Changing Password

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#8661]
Change password from user Preferences window, using "Change Password" link... then:

```
Uncaught Error: QWeb2: Template 'ChangePassword' not found
http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2444
Traceback:
Error: QWeb2: Template 'ChangePassword' not found
    at Object.QWeb2.tools.exception (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2444:7)
    at Engine.QWeb2.Engine.QWeb2.tools.extend._render (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2481:103)
    at Engine.QWeb2.Engine.QWeb2.tools.extend.render (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2477:151)
    at OdooClass.core.Class.extend.renderElement (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2622:1073)
    at http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:2622:917
    at http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:650:681
    at fire (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:644:299)
    at Object.self.add [as done] (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:645:467)
    at Array.<anonymous> (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:650:649)
    at Function.jQuery.extend.each (http://93.188.163.142:8069/web/content/2-eb23b7e/web.assets_common.js:473:767)
```

**Comment by rsi-odoo** [comment]
hello @mart-e,
```ChangePassword``` template is removed in this commit 3cba55d7a7e1f01150f87f806546e10526b10219 by al
restore this template with new design will solve this issue.

Thanks

**Comment by mart-e** [comment]
@rsi-odoo best would be that this button executes the same action as the "Change password" wizard from the `res.users` form.

**Comment by SBollatti** [comment]
Solved and closing
