### ISSUE TITLE
Calendar: Internal server error when viewing event with an invalid token

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#86715]
Impacted versions:
- 15.0
- 14.0

Steps to reproduce:
- Visit URL `/calendar/meeting/view?token=invalid_token`

Current behavior:

An internal server error page is displayed.

Expected behavior:

The message "Invalid Invitation Token." should be displayed, as occurs when trying to accept the event, using:
`/calendar/meeting/accept?token=invalid_token`

This is the full traceback:

```
Traceback (most recent call last):
  File "/.repo_requirements/odoo/addons/http_routing/models/ir_http.py", line 446, in _dispatch
    cls._authenticate(func)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 127, in _authenticate
    getattr(cls, "_auth_method_%s" % auth_method)()
  File "/.repo_requirements/odoo/addons/calendar/models/ir_http.py", line 28, in _auth_method_calendar
    raise BadRequest(error_message)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 746, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
werkzeug.exceptions.BadRequest: 400 Bad Request: Invalid Invitation Token.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/addons/http_routing/models/ir_http.py", line 646, in _handle_exception
    code, html = cls._get_error_html(env, code, values)
  File "/.repo_requirements/odoo/addons/website/models/ir_http.py", line 377, in _get_error_html
    return super(Http, cls)._get_error_html(env, code, values)
  File "/.repo_requirements/odoo/addons/http_routing/models/ir_http.py", line 591, in _get_error_html
    return code, env['ir.ui.view']._render_template('http_routing.%s' % code, values)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1708, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/.repo_requirements/odoo/addons/website/models/ir_ui_view.py", line 403, in _render
    editable = request.website.is_publisher()
  File "/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'HttpRequest' object has no attribute 'website'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/.repo_requirements/odoo/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/.repo_requirements/odoo/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/.repo_requirements/odoo/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/.repo_requirements/odoo/odoo/http.py", line 1307, in __call__
    return self.dispatch(environ, start_response)
  File "/.repo_requirements/odoo/odoo/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/.repo_requirements/odoo/odoo/http.py", line 1497, in dispatch
    result = ir_http._dispatch()
  File "/.repo_requirements/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/.repo_requirements/odoo/addons/website/models/ir_http.py", line 183, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/.repo_requirements/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/.repo_requirements/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/.repo_requirements/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/.repo_requirements/odoo/addons/http_routing/models/ir_http.py", line 450, in _dispatch
    return cls._handle_exception(e)
  File "/.repo_requirements/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/.repo_requirements/odoo/addons/http_routing/models/ir_http.py", line 648, in _handle_exception
    code, html = 418, env['ir.ui.view']._render_template('http_routing.http_error', values)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1708, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/.repo_requirements/odoo/addons/website/models/ir_ui_view.py", line 403, in _render
    editable = request.website.is_publisher()
  File "/.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'HttpRequest' object has no attribute 'website' - - -
```

Support ticket number submitted via odoo.com/help (optional):

**Comment by luisg123v** [comment]
FYI @imanie383, @ajqn9094, @hugho-ad
