### ISSUE TITLE
[9.0] Active_id is not defined

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#8689]
VPS: Ubuntu 64 bits netinstall using virtualenv and clone 9.0 branch from github
Create db, add some apps, create New user, logout admin, login "new user" then...

```
Uncaught Error: NameError: name 'active_id' is not defined
http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:2738
Traceback:
Error: NameError: name 'active_id' is not defined
    at PY_ensurepy (http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:2738:65)
    at Object.py.evaluate (http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:2853:8)
    at Object.py.evaluate (http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:2862:194)
    at Object.py.eval (http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:2866:284)
    at http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:3002:110
    at iterator (http://93.188.163.142:8069/web/content/223-0151880/web.assets_common.js:14:183)
    at Function.<anonymous> (http://93.188.163.142:8069/web/content/223-0151880/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (http://93.188.163.142:8069/web/content/223-0151880/web.assets_common.js:69:526)
    at eval_contexts (http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:3000:136)
    at http://93.188.163.142:8069/web/content/226-33889c1/web.assets_backend.js:3002:253
```

**Comment by lem8r** [comment]
node-less, node-clean-css were installed before first run?

**Comment by SBollatti** [comment]
Yes

2015-09-23 16:21 GMT-03:00 Bogdan Lisnenko <notifications@github.com>:

**Comment by SBollatti** [comment]
Despite last pulls still having this issue at every user login in other language than english

**Comment by SBollatti** [comment]
Log

(90)aeroclub@aeroclubmjz:~/odoo/90$ odoo.py -c odoo.conf
2015-09-29 18:27:23,021 19076 INFO ? openerp: OpenERP version 9.0rc1
2015-09-29 18:27:23,021 19076 INFO ? openerp: addons paths: ['/home/aeroclub/.local/share/Odoo/addons/9.0', u'/home/aeroclub/odoo/90/sources/server/openerp/addons', u'/home/aeroclub/odoo/90/sources/server/addons', '/home/aeroclub/odoo/90/local/lib/python2.7/site-packages/odoo-9.0rc1-py2.7.egg/openerp/addons']
2015-09-29 18:27:23,021 19076 INFO ? openerp: database: default@default:default
2015-09-29 18:27:23,648 19076 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-09-29 18:27:36,025 19076 INFO produccion openerp.modules.loading: loading 1 modules...
2015-09-29 18:27:36,053 19076 INFO produccion openerp.modules.loading: 1 modules loaded in 0.03s, 0 queries
2015-09-29 18:27:36,060 19076 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2015-09-29 18:27:36,409 19076 INFO produccion openerp.modules.loading: loading 75 modules...
2015-09-29 18:27:36,609 19076 INFO produccion openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2015-09-29 18:27:39,252 19076 INFO produccion openerp.modules.loading: 75 modules loaded in 2.84s, 0 queries
2015-09-29 18:27:39,593 19076 INFO ? openerp.http: HTTP Configuring static files
2015-09-29 18:27:40,780 19076 INFO produccion openerp.modules.loading: Modules loaded.
2015-09-29 18:27:40,789 19076 INFO produccion openerp.addons.base.ir.ir_http: Generating routing map
2015-09-29 18:27:40,877 19076 INFO produccion openerp.addons.base.ir.ir_http: Generating routing map
2015-09-29 18:27:41,986 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:41] "GET / HTTP/1.1" 200 -
2015-09-29 18:27:41,986 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:41] "GET / HTTP/1.1" 200 -
2015-09-29 18:27:42,804 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:42] "POST /website/translations HTTP/1.1" 200 -
2015-09-29 18:27:43,048 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:43] "GET /favicon.ico HTTP/1.1" 404 -
2015-09-29 18:27:46,176 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:46] "GET /web/login HTTP/1.1" 200 -
2015-09-29 18:27:46,905 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:46] "POST /website/translations HTTP/1.1" 200 -
2015-09-29 18:27:53,650 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:27:53] "POST /web/login HTTP/1.1" 200 -
2015-09-29 18:28:09,046 19076 INFO produccion openerp.models.unlink: User #1 deleted ir.attachment records with IDs: [607]
2015-09-29 18:28:09,810 19076 INFO produccion openerp.models.unlink: User #1 deleted ir.attachment records with IDs: [608]
2015-09-29 18:28:11,871 19076 INFO produccion openerp.models.unlink: User #1 deleted ir.attachment records with IDs: [605, 604]
2015-09-29 18:28:13,340 19076 INFO produccion openerp.models.unlink: User #1 deleted ir.attachment records with IDs: [606]
2015-09-29 18:28:13,855 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:13] "GET /web? HTTP/1.1" 200 -
2015-09-29 18:28:14,509 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:14] "GET /web/content/609-ebe98c9/web.assets_common.0.css HTTP/1.1" 200 -
2015-09-29 18:28:14,551 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:14] "GET /web/content/611-3a29ff3/web.assets_backend.0.css HTTP/1.1" 200 -
2015-09-29 18:28:14,566 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:14] "GET /web/content/612-3a29ff3/web.assets_backend.1.css HTTP/1.1" 200 -
2015-09-29 18:28:14,665 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:14] "GET /web/content/610-ebe98c9/web.assets_common.js HTTP/1.1" 200 -
2015-09-29 18:28:14,761 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:14] "GET /web/content/613-3a29ff3/web.assets_backend.js HTTP/1.1" 200 -
2015-09-29 18:28:35,514 19076 INFO produccion openerp.service.common: successful login from '-------------@----------.com' using database 'produccion'
2015-09-29 18:28:35,525 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:35] "POST /web/session/get_session_info HTTP/1.1" 200 -
2015-09-29 18:28:36,127 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:36] "POST /web/proxy/load HTTP/1.1" 200 -
2015-09-29 18:28:38,173 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:38] "POST /web/session/modules HTTP/1.1" 200 -
2015-09-29 18:28:38,621 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:38] "POST /web/dataset/search_read HTTP/1.1" 200 -
2015-09-29 18:28:38,750 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:38] "POST /web/webclient/translations HTTP/1.1" 200 -
2015-09-29 18:28:39,785 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:39] "GET /web/webclient/locale/es_AR HTTP/1.1" 200 -
2015-09-29 18:28:40,438 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:40] "POST /mail/chat_init HTTP/1.1" 200 -
2015-09-29 18:28:40,913 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:40] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2015-09-29 18:28:40,922 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:40] "POST /mail/needaction HTTP/1.1" 200 -
2015-09-29 18:28:40,930 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:40] "POST /web/dataset/call_kw/ir.config_parameter/get_param HTTP/1.1" 200 -
2015-09-29 18:28:41,016 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "POST /calendar/notify HTTP/1.1" 200 -
2015-09-29 18:28:41,040 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "POST /web/dataset/search_read HTTP/1.1" 200 -
2015-09-29 18:28:41,161 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "POST /web/dataset/search_read HTTP/1.1" 200 -
2015-09-29 18:28:41,366 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "GET /web/image?model=res.users&field=image_small&id=5 HTTP/1.1" 200 -
2015-09-29 18:28:41,626 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2015-09-29 18:28:41,964 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:41] "POST /web/menu/load_needaction HTTP/1.1" 200 -
2015-09-29 18:28:42,111 19076 INFO produccion werkzeug: 186.64.73.132 - - [29/Sep/2015 18:28:42] "POST /web/action/load HTTP/1.1" 200 -

In the frontend shows "Uncaught Error: NameError: name 'active_id' is not defined"

**Comment by SBollatti** [comment]
Despite to follow this:
https://www.odoo.com/es_ES/forum/help-1/question/active-id-is-not-defined-error-occured-for-portal-user-90812
And removing access rights to Sales and Accountancy, still get this error.

**Comment by SBollatti** [comment]
Deleted odoo folder (in the enviroment) and cloned again and no problem

**Comment by sonmars** [comment]
@SBollatti I am newbie, so could you detail step by step your solution?
