### ISSUE TITLE
(mrp,stock)_account: product views new permissions

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#87647]
Impacted versions: `13.0` (AFAIC) opw-2811301

This change https://github.com/odoo/odoo/commit/4289887496a155bc863f1e26bbec5c2cbb8c451c has two issues:

- It restricts the permissions to several views, but it DOESN'T remove the old ones.
- It assumes that MRP Managers are Inventory Managers and that isn't implied in the group declaration.

Issues:

1. An MRP User which is only Inventory User will get a crash when trying to access a product form.
    - It can be solved removing manually the permission from the affected views.

2. An MRP MANAGER who is just Inventory user will get a crash as well as MRP Manager doesn't imply being Inventory Manager!
   - This has no obvious fix aside from raising those users permissions. Anyway, the fix is broken by design.

<details>
<summary>Traceback</summary>
Odoo Server Error
Traceback (most recent call last):
File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 671, in apply_inheritance_specs
pre_locate=pre_locate)
File "/data/build/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
_("Element '%s' cannot be located in parent view") % tag
ValueError: Element '<xpath expr="//span[@name='update_cost_price']">' cannot be located in parent view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/build/odoo/odoo/http.py", line 625, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/data/build/odoo/odoo/http.py", line 311, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/data/build/odoo/odoo/tools/pycompat.py", line 14, in reraise
raise value
File "/data/build/odoo/odoo/http.py", line 670, in dispatch
result = self._call_function(**self.params)
File "/data/build/odoo/odoo/http.py", line 351, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/data/build/odoo/odoo/http.py", line 340, in checked_call
result = self.endpoint(*a, **kw)
File "/data/build/odoo/odoo/http.py", line 916, in __call__
return self.method(*args, **kw)
File "/data/build/odoo/odoo/http.py", line 516, in response_wrap
response = f(*args, **kw)
File "/data/build/odoo/addons/web/controllers/main.py", line 1342, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/data/build/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/data/build/odoo/odoo/api.py", line 386, in call_kw
result = _call_kw_model(method, model, args, kwargs)
File "/data/build/odoo/odoo/api.py", line 359, in _call_kw_model
result = method(recs, *args, **kwargs)
File "/data/build/odoo/odoo/models.py", line 1478, in load_views
for [v_id, v_type] in views
File "/data/build/odoo/odoo/models.py", line 1478, in <dictcomp>
for [v_id, v_type] in views
File "/data/build/odoo/addons/membership/models/product.py", line 27, in fields_view_get
return super(Product, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
File "/da
<ta/build/odoo/addons/mail/models/mail_thread.py", line 411, in fields_view_get
res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
File "/data/build/odoo/addons/web/models/models.py", line 232, in fields_view_get
r = super().fields_view_get(view_id, view_type, toolbar, submenu)
File "/data/build/odoo/odoo/models.py", line 1558, in fields_view_get
result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
File "/data/build/odoo/odoo/models.py", line 1520, in _fields_view_get
root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 745, in read_combined
arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 694, in apply_view_inheritance
source = self.apply_inheritance_specs(source, specs_tree, view_id)
File "/data/build/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
pre_locate=pre_locate)
File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in apply_inheritance_specs
self.raise_view_error(str(e), inherit_id)
File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
raise ValueError(message)
ValueError: Element '<xpath expr="//span[@name='update_cost_price']">' cannot be located in parent view

Error context:
View `product_extended.product.form.view`
[view_id: 3208, xml_id: mrp_account.product_product_ext_form_view2, model: product.template, parent_id: 737]

</details>

cc @Tecnativa TT35466

**Comment by pedrobaeza** [comment]
@amoyaux can you please check?

**Comment by amoyaux** [comment]
We will revert it. All our apologize

**Comment by chienandalu** [comment]
Thanks :slightly_smiling_face: :+1:
