### ISSUE TITLE
[9.0] recurrent error "ValueError: need more than 1 value to unpack"

### ISSUE THREAD

**Issue by ddrapeau** [odoo/odoo#8768]
In the terminal, this error appears very often, it does not matter what I do.

2015-09-29 11:41:00,465 8026 ERROR odoo9_02 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 149, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 113, in write
    code, msg = status.split(None, 1)
ValueError: need more than 1 value to unpack

**Comment by apr-odoo** [comment]
You forgot to provide library version information (distribution, libaries)

https://github.com/odoo/odoo/wiki/Contributing

Can you try on a pristine ubuntu 15.04 ?

**Comment by antonylesuisse** [comment]
Upgrade werkzeug.
