### ISSUE TITLE
Exporting time sheet als xlsx results with error

### ISSUE THREAD

**Issue by vmario89** [odoo/odoo#87737]
Impacted versions: 15

Steps to reproduce:
create some entries for work and click export
![grafik](https://user-images.githubusercontent.com/5631071/161248175-ca73dd5b-7674-4021-be26-d53d58595e19.png)

Current behavior:
Export fails with error:
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/odoo/addons/web/controllers/main.py", line 98, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/odoo/addons/web/controllers/main.py", line 1894, in index
    return self.base(data)
  File "/usr/lib/python3.9/site-packages/odoo/addons/web/controllers/main.py", line 1843, in base
    response_data = self.from_data(columns_headers, export_data)
  File "/usr/lib/python3.9/site-packages/odoo/addons/web/controllers/main.py", line 1913, in from_data
    with ExportXlsxWriter(fields, len(rows)) as xlsx_writer:
  File "/usr/lib/python3.9/site-packages/odoo/addons/web/controllers/main.py", line 700, in __init__
    self.workbook = xlsxwriter.Workbook(self.output, {'in_memory': True})
AttributeError: 'NoneType' object has no attribute 'Workbook'

```

Expected behavior:
A downloadable xlsx file is generated. I checked python modules. xlsxwriter is present

**Comment by vmario89** [comment]
same happens when exporting contacts too
