### ISSUE TITLE
[9.0] Product images missing in demodata

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#8789]
Installed Odoo 9 enterprise.
Created a database with demodata.
Installed the ecommerce module.
The products in the shops do not have images.

Maybe this error in the logs can have something to do with it:
k
2015-09-30 09:24:53,561 32029 INFO bringsvor9demo2 werkzeug: 109.189.223.147 - - [30/Sep/2015 09:24:53] "GET /shop/page/4 HTTP/1.1" 200 -
2015-09-30 09:24:53,894 32029 ERROR bringsvor9demo2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 149, in execute
    write(data)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 113, in write
    code, msg = status.split(None, 1)
ValueError: need more than 1 value to unpack

But then again maybe the reason is that I selected the eCommerce module directly, without having any other apps installed first.

**Comment by antonylesuisse** [comment]
upgrade werkzeug

**Comment by bringsvor** [comment]
Amazing, it works! Thanks!
