### ISSUE TITLE
[BUG] website_sale: error singleton with method _get_combination_info()

### ISSUE THREAD

**Issue by ypn** [odoo/odoo#88068]
Impacted versions: 14.0 - Community / Enterprise

Steps to reproduce: Using method **_get_combination_info()**  in model **product.template** of module **website_sale**  with param **pricelist** is `False or empty.`

Current behavior:
ValueError: Expected `singleton: res.currency()` because ensure_one() in method `res_currency.compare_amounts()`

Expected behavior:
In case pricelist is not have value, need use another default (eg: product_template) for warranty `compare_amounts()` working.

Video/Screenshot link (optional): Error log:
```

Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
    odoo_module_version_info = dependency._get_combination_info_variant(add_qty, pricelist, parent_combination)
  File "/opt/odoo/14.0/addons/sale/models/product_product.py", line 57, in _get_combination_info_variant
    return self.product_tmpl_id._get_combination_info(self.product_template_attribute_value_ids, self.id, add_qty, pricelist, parent_combination)
  File "/opt/odoo/14.0/addons/website_sale_stock/models/product_template.py", line 20, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/opt/odoo/14.0/addons/website_sale/models/product.py", line 308, in _get_combination_info
    has_discounted_price = pricelist.currency_id.compare_amounts(list_price, price) == 1
  File "/opt/odoo/14.0/odoo/addons/base/models/res_currency.py", line 156, in compare_amounts
    self.ensure_one()
  File "/opt/odoo/14.0/odoo/models.py", line 5011, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()
```

Support ticket number submitted via odoo.com/help (optional):

**Comment by ypn** [comment]
@tde-banana-odoo please take some minutes for this issue. Thank you!

**Comment by tde-banana-odoo** [comment]
@Feyensv @tivisse

**Comment by Feyensv** [comment]
Could you please give more details on how you managed to trigger this traceback (and reproduce it on runbot ideally) ?

The line you are specifying `has_discounted_price = ...` is only reached if a website is given in the context, and in this case, the pricelist is always specified, which means there is currency available.

**Comment by ypn** [comment]
@Feyensv, Thanks for your reply! I couldn't simulate this traceback, that why I open the issue instead of a PR to fix. But use a variable and not check its value available can make potential error.
