### ISSUE TITLE
Incorrect api decorator on method _quants_merge in stock

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#8822]
The method `_quants_merge` in the `stock` module is decorated using `api.cr_uid_ids_context`. However, the method only uses `cr`, `uid` and `context`: https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L554

Trying to call the function from new style code, e.g:
```
self._quants_merge(solved_quant_ids, solving_quant)
```
gives a traceback: 

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/aisopuro/repos/<my_own_file.py>", line 208, in my_function
    self.quant_ids.merge_stock_quants()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/aisopuro/repos/my_own_file.py", line 83, in merge_stock_quants
    self.env['stock.quant']._quants_merge(quant2merge, quant)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
TypeError: _quants_merge() got multiple values for keyword argument 'context'
```

The function should be callable from new-style code.

**Comment by aisopuro** [comment]
I would speculate that the reason it has worked so far is because it seems to only be called from a single old-style source: https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L604

**Comment by rco-odoo** [comment]
@aisopuro your call does not follow the API convention.  You should call it like this:

    solved_quants = self.browse(solved_quant_ids)
    solved_quants._quants_merge(solving_quant)

The `ids` part in the old API must be the ids of the recordset used in the new API.
