### ISSUE TITLE
after install module, can not use Odoo 9 any more

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#8832]
I report issue for overlapping image and content https://github.com/odoo/odoo/issues/8824

I installed lessc and reboot the system. 

Now my screen look like.

![1 after_creating_database](https://cloud.githubusercontent.com/assets/14229503/10223323/17a62fc0-6876-11e5-8ae2-7c041524473b.png)

When I installed module the issue remains.

![2_install_module](https://cloud.githubusercontent.com/assets/14229503/10223341/2bdb98d6-6876-11e5-95b5-131c7a0dae5e.png)

Below image for a inbox messaging.

![3_inbox_messages](https://cloud.githubusercontent.com/assets/14229503/10223372/4a63ed94-6876-11e5-9629-df722ba1fad1.png)

Below is server traceback 

2015-10-01 14:27:59,858 3143 ERROR odoo9_testing werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 149, in execute
    write(data)
  File "/usr/share/pyshared/werkzeug/serving.py", line 113, in write
    code, msg = status.split(None, 1)
ValueError: need more than 1 value to unpack
2015-10-01 14:27:59,863 3143 ERROR odoo9_testing werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 149, in execute
    write(data)
  File "/usr/share/pyshared/werkzeug/serving.py", line 113, in write
    code, msg = status.split(None, 1)
ValueError: need more than 1 value to unpack

May you please guide me?

**Comment by antonylesuisse** [comment]
Please upgrade werkzeug. At least 0.9
