### ISSUE TITLE
[9.0] Crash QWeb + UnicodeDecode

### ISSUE THREAD

**Issue by antwal** [odoo/odoo#8846]
2015-10-01 21:07:12,938 24919 INFO ? openerp: database: odoo9@default:default
2015-10-01 21:07:13,165 24919 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-10-01 21:07:16,813 24919 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2015-10-01 21:07:17,539 24919 INFO ? openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2015-10-01 21:07:17,819 24919 INFO ? openerp.http: HTTP Configuring static files
2015-10-01 21:07:17,855 24919 INFO odoo9 openerp.modules.loading: loading 1 modules...
2015-10-01 21:07:17,874 24919 INFO odoo9 openerp.modules.loading: 1 modules loaded in 0.02s, 0 queries
2015-10-01 21:07:17,890 24919 INFO odoo9 openerp.modules.loading: loading 14 modules...
2015-10-01 21:07:17,929 24919 INFO odoo9 openerp.modules.loading: 14 modules loaded in 0.04s, 0 queries
2015-10-01 21:07:18,313 24919 INFO odoo9 openerp.modules.loading: Modules loaded.
2015-10-01 21:07:18,315 24919 INFO odoo9 openerp.addons.base.ir.ir_http: Generating routing map
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/opt/odoo/9.0/openerp/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/opt/odoo/9.0/openerp/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 191626: ordinal not in range(128)
Logged from file ir_qweb.py, line 1369
2015-10-01 21:07:21,054 24919 INFO odoo9 werkzeug: 127.0.0.1 - - [01/Oct/2015 21:07:21] "GET /web/ HTTP/1.1" 500 -
2015-10-01 21:07:21,113 24919 ERROR odoo9 werkzeug: Error on request:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/9.0/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/opt/odoo/9.0/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/9.0/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/9.0/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/9.0/openerp/http.py", line 1390, in __call__
    return self.app(environ, start_wrapped)
  File "/Library/Python/2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/9.0/openerp/http.py", line 1580, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/9.0/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/9.0/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/9.0/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/9.0/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/9.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/9.0/openerp/http.py", line 311, in checked_call
    result.flatten()
  File "/opt/odoo/9.0/openerp/http.py", line 1367, in flatten
    self.response.append(self.render())
  File "/opt/odoo/9.0/openerp/http.py", line 1360, in render
    context=request.context)
  File "/opt/odoo/9.0/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/9.0/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/9.0/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/9.0/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 255, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 449, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 490, in render_tag_set
    qwebcontext[template_attributes["set"]] = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 326, in render_element
    raise_qweb_exception(message="Could not render element %r" % element.tag, node=element, template=template)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 482, in render_tag_call_assets
    return bundle.to_html(css=css, js=js, debug=bool(qwebcontext.get('debug')), async=async)
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 1185, in to_html
    for attachment in self.css():
  File "/opt/odoo/9.0/openerp/addons/base/ir/ir_qweb.py", line 1279, in css
    css += self.css_message(msg)
QWebException: 'ascii' codec can't decode byte 0xef in position 209528: ordinal not in range(128)

**Comment by antonylesuisse** [comment]
Please read https://github.com/odoo/odoo/wiki/Contributing
