### ISSUE TITLE
[9.0] crash when displaying a partner

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#8848]
There is an issue with partner AsusTek / Arthur Gomez. 

* connect to runbot
* Go to sales customers
* in the search box, remove "customers" and type "Gomez" (this does not happen with all partners)
* Click on the kanban card 

you'll get the following stack trace:

    Traceback (most recent call last):
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 599, in _handle_exception
        return super(JsonRequest, self)._handle_exception(exception)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 636, in dispatch
        result = self._call_function(**self.params)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 315, in _call_function
        return checked_call(self.db, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/service/model.py", line 113, in wrapper
        return f(dbname, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 308, in checked_call
        result = self.endpoint(*a, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 887, in __call__
        return self.method(*args, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/http.py", line 465, in response_wrap
        response = f(*args, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/web/controllers/main.py", line 971, in call_kw
        return self._call_kw(model, method, args, kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/web/controllers/main.py", line 963, in _call_kw
        return checked_call(request.db, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/service/model.py", line 113, in wrapper
        return f(dbname, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/web/controllers/main.py", line 962, in checked_call
        return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3168, in read
        result = BaseModel.read(records, fields, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3203, in read
        self._read_from_database(stored, inherited)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3383, in _read_from_database
        res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/osv/fields.py", line 613, in get
        result[att.res_id] = att.datas
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/fields.py", line 805, in __get__
        self.determine_value(record)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/fields.py", line 903, in determine_value
        record._prefetch_field(self)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3262, in _prefetch_field
        result = records.read([f.name for f in fs], load='_classic_write')
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 538, in new_api
        result = method(self._model, cr, uid, self.ids, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/base/ir/ir_attachment.py", line 420, in read
        return super(ir_attachment, self).read(cr, uid, ids, fields_to_read, context=context, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3168, in read
        result = BaseModel.read(records, fields, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3203, in read
        self._read_from_database(stored, inherited)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/models.py", line 3383, in _read_from_database
        res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/osv/fields.py", line 1488, in get
        result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/base/ir/ir_attachment.py", line 188, in _data_get
        result[attach.id] = self._file_read(cr, uid, attach.store_fname, bin_size)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/openerp/addons/base/ir/ir_attachment.py", line 149, in _file_read
        r = os.path.getsize(full_path)
      File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 2] No such file or directory:
      '/home/odoo/runbot/extra/runbot/static/build/105287-9-0-bc90b5/datadir/filestore/105287-9-0-bc90b5-all/01/01ffc93194ea57412f56165615bb72c97264a9d7'

A variant of this exact bug was reported in #8756, and then marked as fixed but
the issue described in there is still reproduceable.

**Comment by rco-odoo** [comment]
@gurneyalex I cannot reproduce the issue. It probably has been fixed since.
You are welcome to reopen this issue if you still experience this bug.
