### ISSUE TITLE
[9.0] Bank/Cash Statement Error on another Currency

### ISSUE THREAD

**Issue by raditv** [odoo/odoo#8884]
When I changed the company address to another country, it will automatically change the currency, for example I'm using Indonesian currency IDR as default currency. when create new transaction or bank statement, it will ask to reconcile, then after I click reconcile button there's an exception

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 636, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 971, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 963, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 962, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_currency.py", line 262, in get_format_currencies_js_function
    function = "if (arguments[1] === false || arguments[1] === undefined) {" + company_currency_format + " }" + function
UnboundLocalError: local variable 'company_currency_format' referenced before assignment

**Comment by raditv** [comment]
Fixed, By setting Company Currency to Active on Accounting Settings

**Comment by matheo** [comment]
This needs a better error handling but well, that's v7 code, so a warning message about the currency activation could be good instead get that exception :\
