### ISSUE TITLE
[8.0] sale: MissingError when using prototype inheritance on sale.order.line

### ISSUE THREAD

**Issue by naglis** [odoo/odoo#8921]
**MissingError when creating invoice from SO when prototype inheritance is used on sale.order.line**

Impacted versions:
- 8.0

Steps to reproduce:
- define a minimal module and use [prototype inheritance](https://www.odoo.com/documentation/8.0/reference/orm.html#inheritance-and-extension) to inherit `sale.order.line`, eg.:

``` python
class SaleOrderLineFoo(models.Model):
    _name = 'sale.order.line.foo'
    _inherit = 'sale.order.line'
```

Note: assume `sale` is in `depends` and everything else is correct.
- create a new sale order with at least one line (content is not important)
- click _Confirm Sale_ on the SO
- click _Create Invoice_ &rarr; _Create Invoice_

Current behavior:
- raises `MissingError: One of the documents you are trying to access has been deleted, please try again after refreshing.` [[traceback](https://gist.github.com/naglis/8cf008e21ea5742b5c05)]
- invoice is not created

Expected behavior:
- invoice is created

While debugging I've found that this happens because recomputation on [`invoice`](https://github.com/odoo/odoo/blob/8.0/addons/sale/sale.py#L916) field on `sale.order.line` triggers recomputation on 'sale.order.line.foo', too (see traceback).

As a workaround, I've redefined the `invoiced` field as a dummy computed field on 'sale.order.line.foo', as I'm not really using it. However, I don't think this is expected behavior.

**Comment by dexwiller** [comment]
Hi i ve got the same problem when i prototype inherit sale.order.

my class is excatly like yours.

class SaleOrderFoo(models.Model):
         _name = 'custom_module.foo' 
         _inherit='sale.order'

My problem related to field pricelist_id, which is calculated on every submit.

the problem is in  sale.py in sale module.

def _amount_all(self, cr, uid, ids, field_name, arg, context=None):
        cur_obj = self.pool.get('res.currency')
        res = {}
        for order in self.browse(cr, uid, ids, context=context):
            res[order.id] = {
                'amount_untaxed': 0.0,
                'amount_tax': 0.0,
                'amount_total': 0.0,
            }
            val = val1 = 0.0
            cur = order.pricelist_id.currency_id
            for line in order.order_line:
                val1 += line.price_subtotal
                val += self._amount_line_tax(cr, uid, line, context=context)
            res[order.id]['amount_tax'] = cur_obj.round(cr, uid, cur, val)
            res[order.id]['amount_untaxed'] = cur_obj.round(cr, uid, cur, val1)
            res[order.id]['amount_total'] = res[order.id]['amount_untaxed'] + res[order.id]['amount_tax']
        return res


when "cur = order.pricelist_id.currency_id" line proccessed, it gives an exception, missing error.

pricelist_id is returning None, I ve tried to define it in my custom class, cos of pricelist_id is many2one field, this time it gives me an error , tuple object has no attribute currency_id.


Any suggestions?

**Comment by arn64** [comment]
I have the same issue, prototyping the model "product.product", can create the prototype but, when I try to create a product, got the MissingError.
Server log:
`Traceback (most recent call last):
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/media/alberto/sdd_storage/Work/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/stock/product.py", line 502, in write
    return super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/product/product.py", line 778, in write
    self.create_variant_ids(cr, uid, ids, context=context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/product/product.py", line 731, in create_variant_ids
    id = product_obj.create(cr, uid, values, context=ctx)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/dev_modules/rent_car/nubea/nubearentcar/models/product.py", line 131, in create
    res = super(ChargeExtraProductProduct, self).create(vals)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/product/product.py", line 1204, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/models.py", line 4104, in create
    record = self.browse(self._create(old_vals))
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/models.py", line 4316, in _create
    cr, user, ids, fields2, context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/models.py", line 4454, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/media/alberto/sdd_storage/Work/odoo/openerp/osv/fields.py", line 1532, in _related_read
    value = value[field][:1]
  File "/media/alberto/sdd_storage/Work/odoo/openerp/models.py", line 5657, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/media/alberto/sdd_storage/Work/odoo/openerp/fields.py", line 841, in __get__
    return record._cache[self]
  File "/media/alberto/sdd_storage/Work/odoo/openerp/models.py", line 6057, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/media/alberto/sdd_storage/Work/odoo/openerp/fields.py", line 56, in get
    raise self.exception
MissingError: ('MissingError', u'Uno de los documentos al que est\xe1 intentado acceder ha sido eliminado. Int\xe9ntelo por favor de nuevo tras actualizar.')`

**Comment by Yenthe666** [comment]
Hi @naglis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
