### ISSUE TITLE
[9.0] WSGI: ValueError: no space following status code

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#8924]
I am getting the following error in my log, as i am still struggling getting odoo9 installed (see my other posted issue) perhaps this is related to it.

```
[Tue Oct 06 13:50:40.583113 2015] [wsgi:error] [pid 28932:tid 139983237306112] [remote 127.0.0.1:92]
mod_wsgi (pid=28932): Exception occurred processing WSGI script '/home/josesapelli/webapps/odoo/odoo/openerp-wsgi.py'.
 Traceback (most recent call last):
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 184, in application
     return application_unproxied(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 170, in application_unproxied
     result = handler(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1416, in __call__
     return self.dispatch(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1390, in __call__
     return self.app(environ, start_wrapped)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
     return self.app(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1586, in dispatch
     return response(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1207, in __call__
     start_response(status, headers)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1389, in start_wrapped
     start_response(status, new_headers)
 ValueError: no space following status code
```

**Comment by odony** [comment]
Could you try with the following patch: 41cb8dd7ce38 ?

**Comment by aduijs** [comment]
Cheers Olivier!
This little piece of code worked!
thanks in a million!

2015-10-22 3:53 GMT-05:00 Olivier Dony <notifications@github.com>:

**Comment by odony** [comment]
Thanks @aduijs for reporting it, that was a real bug indeed, it's just that most web servers and WSGI containers were more lenient with the HTTP specs than yours. Glad this is solved for you.

**Comment by aduijs** [comment]
@odony  you may close https://github.com/odoo/odoo/issues/9029 as well, as i suspected they were related. and the code solved the mysterious image problem
