### ISSUE TITLE
[15.0] Issue with account module installation with demo data

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#89524]
### Impacted versions:

15.0 (using the code from 20 April 2022)

### Steps to reproduce:

1. Create a database with language **Japanese**, country **Japan** and **demo data** (make sure to meet ALL the conditions).

![image](https://user-images.githubusercontent.com/7766939/164873971-d8fac197-cdd5-4122-8322-6791e5a45abf.png)

2. Install account module.

### Current behavior:

Module installation completes with following error, and without the Japanese CoA (l10n_jp).

> 検証エラー
> 操作を完了できません:別のモデルでは、レコードを削除する必要があります。可能であれば、代わりにアーカイブしてください。
> モデル: 不明 (不明), 制約: account_edi_format_account_journal_rel_account_journal_id_fkey

In English:

> Validation Error
> The operation cannot be completed: another model requires the record being deleted. If possible, archive it instead.
> Model: Unknown (Unknown), Constraint: account_edi_format_account_journal_rel_account_journal_id_fkey

Traceback:
```
2022-04-23 02:53:20,039 30 WARNING test2 odoo.addons.account.models.account_journal: Cannot use '顧客請求書-JP Company' as email alias, fallback to 'INV'
2022-04-23 02:53:20,046 30 WARNING test2 odoo.modules.loading: Module l10n_jp demo data failed to install, installed without demo data
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/opt/odoo/odoo/tools/convert.py", line 333, in _tag_function
    _eval_xml(self, rec, env)
  File "/opt/odoo/odoo/tools/convert.py", line 204, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/models/chart_template.py", line 198, in try_loading
    template.with_context(default_company_id=company.id)._load(15.0, 15.0, company)
  File "/opt/odoo/addons/account/models/chart_template.py", line 283, in _load
    acc_template_ref, taxes_ref = self._install_template(company, code_digits=self.code_digits)
  File "/opt/odoo/addons/account/models/chart_template.py", line 568, in _install_template
    tmp1, tmp2 = self.with_context(lang=company.partner_id.lang)._load_template(company, code_digits=code_digits, account_ref=acc_ref, taxes_ref=taxes_ref)
  File "/opt/odoo/addons/account/models/chart_template.py", line 620, in _load_template
    self.generate_journals(account_ref, company)
  File "/opt/odoo/addons/account/models/chart_template.py", line 463, in generate_journals
    journal = JournalObj.create(vals_journal)
  File "<decorator-gen-180>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 391, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/addons/account/models/account_journal.py", line 661, in create
    journal = super(AccountJournal, self.with_context(mail_create_nolog=True)).create(vals)
  File "<decorator-gen-130>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 265, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 4103, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/odoo/fields.py", line 1275, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/addons/account/models/account_journal.py", line 330, in _inverse_type
    record._update_mail_alias()
  File "/opt/odoo/addons/account/models/account_journal.py", line 536, in _update_mail_alias
    self.alias_id = self.env['mail.alias'].sudo().create(alias_values)
  File "<decorator-gen-128>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/mail/models/mail_alias.py", line 121, in create
    sanitized_names = self._clean_and_check_unique(alias_names)
  File "/opt/odoo/addons/mail/models/mail_alias.py", line 195, in _clean_and_check_unique
    raise UserError(
odoo.exceptions.UserError: The e-mail alias inv is already used by the 顧客請求書 仕訳帳. Choose another alias or change it on the other document.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/loading.py", line 86, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package)
  File "/opt/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /opt/odoo/addons/l10n_jp/demo/demo_company.xml:30, somewhere inside
<function model="account.chart.template" name="try_loading">
        <value eval="[ref('l10n_jp.l10n_jp1')]"/>
        <value model="res.company" eval="obj().env.ref('l10n_jp.demo_company_jp')"/>
    </function>
2022-04-23 02:53:20,076 30 INFO test2 odoo.addons.base.models.ir_translation: module l10n_jp: no translation for language ja_JP
2022-04-23 02:53:20,104 30 ERROR test2 odoo.sql_db: bad query: INSERT INTO account_edi_format_account_journal_rel (account_journal_id, account_edi_format_id) VALUES (8, 1) ON CONFLICT DO NOTHING
ERROR: insert or update on table "account_edi_format_account_journal_rel" violates foreign key constraint "account_edi_format_account_journal_rel_account_journal_id_fkey"
DETAIL:  Key (account_journal_id)=(8) is not present in table "account_journal".
```

I suspect that this commit https://github.com/odoo/odoo/commit/96a75b82475e369e79a4fde500992d667d0cae55 has introduced the issue.

### Expected behavior:

No error and modules are installed with data as expected.

**Comment by yostashiro** [comment]
https://github.com/odoo/odoo/blob/540dc692495928fedb297d5b0f2a31ddfd590976/addons/account/models/account_journal.py#L467-L475

I think this block should be supplemented with the conflict case - add a trailing number or something in case the suggested alias is already taken.

**Comment by yostashiro** [comment]
OPW: 2831638

**Comment by yostashiro** [comment]
https://github.com/odoo/odoo/pull/90429

Closing the issue for now since the PR has been merged.
