### ISSUE TITLE
[9.0] Bug when installing marketing campaign

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8976]
Hi Odoo,

I found a bug when I try to install marketing campaign on enterprise version.

http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:4257
Traceback:
TypeError: Cannot read property 'id' of undefined
    at OdooClass.Class.extend.on_action (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:4257:918)
    at OdooClass.<anonymous> (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:4257:632)
    at OdooClass.Class.extend.trigger (http://120.24.63.65:8099/web/content/249-90e3939/web.assets_common.js:2616:180)
    at OdooClass._.extend.trigger (http://120.24.63.65:8099/web/content/249-90e3939/web.assets_common.js:2618:669)
    at OdooClass.Widget.extend.do_action (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:3112:10)
    at OdooClass.Widget.extend.do_action (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:3172:878)
    at OdooClass.Widget.extend.on_hashchange (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:3172:1681)
    at new_handler (http://120.24.63.65:8099/web/content/339-9e2aa0d/web.assets_backend.js:2935:339)
    at jQuery.event.dispatch (http://120.24.63.65:8099/web/content/249-90e3939/web.assets_common.js:740:451)
    at elemData.handle (http://120.24.63.65:8099/web/content/249-90e3939/web.assets_common.js:713:173)

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report.
I've just tried this on the latest Odoo 9.0 and it has been fixed in the meanwhile. Please update your Odoo and try again.

Regards,
Yenthe
