### ISSUE TITLE
account_facturx: printing error

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#89816]
After this patch, it's not possible to print invoices:

https://github.com/odoo/odoo/commit/95f4794ea8dbd415f190ad722bf3aef15f0895cd#diff-697b9fb50b687bf2e100a8ade3de5651e130445e9991e34fd16bbfc61e98d3f9R91-R94

Impacted versions: 13.0

_Steps to reproduce:_

On a runbot, go to an invoice and try to print it

_Current behavior:_

It crashes:

Odoo Server Error
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5128, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/addons/web/controllers/main.py", line 2049, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/data/build/odoo/odoo/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1987, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/data/build/odoo/addons/account/models/ir_actions_report.py", line 50, in render_qweb_pdf
    return super().render_qweb_pdf(res_ids=res_ids, data=data)
  File "/data/build/odoo/odoo/addons/base/models/ir_actions_report.py", line 793, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/data/build/odoo/addons/account_facturx/models/ir_actions_report.py", line 21, in _post_pdf
    xml_content = invoice._export_as_facturx_xml()
  File "/data/build/odoo/addons/account_facturx/models/account_move.py", line 94, in _export_as_facturx_xml
    gross_price_subtotal = line.currency_id.round(line.price_subtotal / (1 - (line.discount / 100.0)))
  File "/data/build/odoo/odoo/addons/base/models/res_currency.py", line 133, in round
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5131, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

_Expected behavior:_

The invoice is printed :smile:

**Comment by pedrobaeza** [comment]
@vin-odoo can you please check?

**Comment by vin-odoo** [comment]
Nice catch, bad backport. I should have used the always_set_currency_id in 13. Will fix it right away.

**Comment by chienandalu** [comment]
> Nice catch, bad backport. I should have used the always_set_currency_id in 13. Will fix it right away. Thank you

You can check https://github.com/odoo/odoo/pull/89821/files
