### ISSUE TITLE
[9.0] Project Forescast Bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9002]
Hi Odoo,

I tried project forescast, and when I tried to create a new one, with project and task,
it has an error message:

Traceback (most recent call last):
  File "/opt/odoo90/odoo/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo90/odoo/openerp/http.py", line 636, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo90/odoo/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo90/odoo/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo90/odoo/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo90/enterprise/web/controllers/main.py", line 965, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo90/enterprise/web/controllers/main.py", line 957, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo90/enterprise/web/controllers/main.py", line 956, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/api.py", line 318, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/models.py", line 4114, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo90/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/api.py", line 454, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/models.py", line 4324, in _create
    recs.recompute()
  File "/opt/odoo90/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/models.py", line 5781, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/odoo90/odoo/openerp/models.py", line 5781, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/opt/odoo90/odoo/openerp/models.py", line 5668, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo90/odoo/openerp/fields.py", line 805, in __get__
    self.determine_value(record)
  File "/opt/odoo90/odoo/openerp/fields.py", line 887, in determine_value
    self.compute_value(recs)
  File "/opt/odoo90/odoo/openerp/fields.py", line 867, in compute_value
    self._compute_value(records)
  File "/opt/odoo90/odoo/openerp/fields.py", line 857, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo90/odoo/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo90/odoo/openerp/api.py", line 389, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo90/enterprise/project_forecast/models/models.py", line 89, in _compute_effective_hours
    if self.task_id and self.env['project.config.settings'].search([]).module_project_timesheet:
  File "/opt/odoo90/odoo/openerp/fields.py", line 795, in __get__
    record.ensure_one()
  File "/opt/odoo90/odoo/openerp/models.py", line 5358, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: project.config.settings(1, 2)

if I just define the project all is fine.
Thank You.

**Comment by DanielBaudry** [comment]
Hi,

I got the same error in my development environment this week.

Did anyone solve this issue already ?
I would rather update the module with the 'official code' than implementing my own fix.

Thank you for any feedbacks,

**Comment by sle-odoo** [comment]
Hi,
I can't reproduce this bug. When i try to create a forecast from a project, everything is working fine (project dashboard, settings, allow forecast). Could you be more precise about the procedure?

Regards

**Comment by DanielBaudry** [comment]
Hi,
The error is occuring when we try to select a task during the forecast creation. Even if the task belongs to the selected project, the error is raised.

Regards,

**Comment by sle-odoo** [comment]
Are you up to date? Can you reproduce this issue in the latest runbot?
I must be missing something

**Comment by dsu-odoo** [comment]
Hello @sle-odoo Please see this video how to reproduce it, https://drive.google.com/file/d/0Bx4JWs1efCreQnRLQWYzdXlTZUU/view?usp=sharing

**Comment by sle-odoo** [comment]
fixed at rev https://github.com/odoo/enterprise/commit/789e3c547201a22a3527f671077ed4b9fab0a3ff
