### ISSUE TITLE
[15] some chromium tests failing for web module

### ISSUE THREAD

**Issue by amh-mw** [odoo/odoo#90048]
### Impacted versions:
15.0

### Steps to reproduce:
Dockerfile
```
FROM odoo:15
USER root

# Install chromium testing requirements
RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium && \
    rm -rf /var/lib/apt/lists/*

# Install python testing requirements
RUN pip3 install websocket-client

USER odoo
```

docker-compose.yaml
```
version: '2'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  test:
    build: .
    command:
      - odoo
      - --database=test
      - --init=web
      - --log-level=warn
      - --max-cron-threads=0
      - --stop-after-init
      - --test-enable
      - --test-tags=web
    depends_on:
      - db
```

`docker-compose run test`

### Current behavior:
```
2022-04-28 14:37:23,011 1 ERROR test odoo.addons.web.tests.test_js: FAIL: WebSuite.test_js
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/tests/test_js.py", line 15, in test_js
    self.browser_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800)
  File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1606, in browser_js
    self.fail('%s\n%s' % (message, error))
AssertionError: Some js test failed
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""932-10-10" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-10-10T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""1932-10-10" is parsed as expected. [legacy]", actual: "1932-10-10T00:00:00.000Z", expected: "2000-10-10T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""09990101" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-01-01T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""19993012" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-01-01T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""19990101" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-01-01T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""19990130" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-01-01T00:00:00.000Z"]
QUnit test failed: utils > dates utils compatibility with legacy > parseDateTime (with legacy options.isUTC = true) [message: ""19991230" is parsed as expected. [legacy]", actual: "undefined", expected: "2000-01-01T00:00:00.000Z"]
```

### Expected behavior:
Tests pass.

**Comment by amh-mw** [comment]
I'm happy to chase this one down, but my initial investigation has only resulted in confusion. It looks like this test is attempting to preserve weird legacy date conversion behaviors. My initial reaction is simply to rip it out. Check out some of these test cases.

https://github.com/odoo/odoo/blob/15.0/addons/web/static/tests/core/l10n/dates_tests.js#L760-L777
```
["932-10-10", [undefined, "2000-10-10T00:00:00.000Z"]], // weird behaviour in legacy
["1932-10-10", ["1932-10-10T00:00:00.000Z", "2000-10-10T00:00:00.000Z"]], // weird behaviour in legacy
["09990101", [undefined, "2000-01-01T00:00:00.000Z"]], // weird behaviour in legacy
["19993012", [undefined, "2000-01-01T00:00:00.000Z"]], // weird behaviour in legacy
["19990101", ["1999-01-01T00:00:00.000Z", "2000-01-01T00:00:00.000Z"]], // weird behaviour in legacy
["19990130", ["1999-01-30T00:00:00.000Z", "2000-01-01T00:00:00.000Z"]], // weird behaviour in legacy
["19991230", ["1999-12-30T00:00:00.000Z", "2000-01-01T00:00:00.000Z"]], // weird behaviour in legacy
["2016-01-03 09:24:15.123Z", ["2016-01-03T09:24:15.123Z", undefined]], // weird behaviour in legacy
["2016-01-03T09:24:15.123Z", ["2016-01-03T09:24:15.123Z", undefined]], // weird behaviour in legacy
```

"932-10-10" should parse into date "2000-10-10T00:00:00.000Z"? What? 🤒

**Comment by amh-mw** [comment]
I think #92061 is going to fix this. I will retest after the next update of the odoo:15 docker container image.

**Comment by amh-mw** [comment]
LGTM

**Comment by pparidans** [comment]
Glad it fixes it for you @amh-mw 👍
