### ISSUE TITLE
KeyError in Odoo 8

### ISSUE THREAD

**Issue by agstyo** [odoo/odoo#9015]
I am get message error in my odoo =
please give me solution for my problem
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/agstyo/odoo/odoo/addons/web/controllers/main.py", line 1251, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/addons/base/ir/ir_actions.py", line 325, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/models.py", line 3143, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/models.py", line 3178, in read
    self._read_from_database(stored, inherited)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/models.py", line 3357, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/agstyo/odoo/odoo/openerp/osv/fields.py", line 1467, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/agstyo/odoo/odoo/openerp/addons/base/ir/ir_actions.py", line 265, in _search_view
    field_get = self.pool[act.res_model].fields_view_get(cr, uid,
  File "/home/agstyo/odoo/odoo/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'wc.backend'
```

**Comment by mart-e** [comment]
Hello,

this `wc.backend` is not a standard Odoo model so it is most likely due to a custom module that you have installed (WooCommerce ?)
Check with your custom modules but if you can reproduce with odoo standard code, please let us know the different steps.
Regards
