### ISSUE TITLE
[9.0] images are not displayed. Unable to change image as well

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#9029]
In a freshly installed Odoo 9 (https://github.com/odoo/odoo) contact and product images wont display. I am unable to change them too, generating an notification "image can not be displayed"

In another similar case i found was a solution to upgrade werkzeug

the werkzeug was already up to date.

pip install --upgrade werkzeug
Requirement already up-to-date: werkzeug in ./lib/python2.7
below is an isolated part of the log

```
 mod_wsgi (pid=1998): Exception occurred processing WSGI script '/home/josesapelli/webapps/odoo/odoo/openerp-wsgi.py'.
 Traceback (most recent call last):
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 170, in application_unproxied
     result = handler(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1416, in __call__
     return self.dispatch(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1390, in __call__
     return self.app(environ, start_wrapped)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
     return self.app(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1586, in dispatch
     return response(environ, start_response)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1207, in __call__
     start_response(status, headers)
   File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1389, in start_wrapped
     start_response(status, new_headers)
 ValueError: no space following status code
```
anyone got some ideas?

**Comment by aduijs** [comment]
updated coment since it affects more images then just contacts, products as well

**Comment by aduijs** [comment]
Was solved with patch https://github.com/odoo/odoo/commit/41cb8dd7ce38fa19a2c7ebca74116f775636f6c5

see: https://github.com/odoo/odoo/issues/8924
