### ISSUE TITLE
Odoo Dashboard access error: Uncaught Promise > NameError: name 'allowed_company_ids' is not defined 

### ISSUE THREAD

**Issue by Clement-Odrd** [odoo/odoo#90496]
Impacted versions:  Odoo 15.0+e 

Steps to reproduce: I added few graphs and tables to the dashboard from sales, inventory and manufacturing module analysis.
On my odoo I only manage 1 company.

Current behavior: When I click on the dahsboard icon, I can't access the dashboard and the error message is :
"UncaughtPromiseError
Uncaught Promise > NameError: name 'allowed_company_ids' is not defined
Error: NameError: name 'allowed_company_ids' is not defined
    at PY_ensurepy (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:2926:65)
    at Object.py.evaluate (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3043:8)
    at Object.py.evaluate (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3051:88)
    at Object.py.evaluate (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3053:194)
    at Object.py.eval (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3057:284)
    at https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3851:110
    at iterator (https://mynameenvironment/web/assets/977-a081411/web.assets_common.min.js:153:183)
    at Function.<anonymous> (https://mynameenvironment/web/assets/977-a081411/web.assets_common.min.js:156:8)
    at _.<computed> [as reduce] (https://mynameenvironment/web/assets/977-a081411/web.assets_common.min.js:208:526)
    at eval_contexts (https://mynameenvironment/web/assets/978-d799dfd/web.assets_backend.min.js:3849:136)"

Expected behavior:

Access the dashboard module

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 2842924

**Comment by Clement-Odrd** [comment]
Apparently some issues composed dashboard can

**Comment by Auto-Matt** [comment]
jupi 

![image](https://user-images.githubusercontent.com/89580764/172619336-9acb3bce-f95f-401e-b2dd-c4cff05deecc.png)

**Comment by pumppi** [comment]
I can confirm this issue. 

Looks like py.js is crashing for trying to resolve "allowed_company_ids" in context, where there is no allowed_company_ids. Did little bit debugging with developer tools, but should be debugged with real sources. This case was on odoo.sh.
