### ISSUE TITLE
[14.0][portal] TypeError when opening chatter on Portal site if subtype_id is False

### ISSUE THREAD

**Issue by dariodelzozzo** [odoo/odoo#90630]
Impacted versions: 
14.0, 15.0

Steps to reproduce:
In debug mode -> Got to Settings -> Technical -> Messages
Filter records with custom Filter where subtype is not set.
![image](https://user-images.githubusercontent.com/42646546/166935293-dc279293-c802-417b-be92-c73533c8723a.png)

Open in the Portal site one of the object related to the messages with subtype_id = False and you will receive the error

Or just go on Runbot -> Enterprise 14.0 or 15.0 ad Open as Admin in Portal Side the sale.order with id=2 that has some messages in the chatter with subtype_id = False

The error is related to this line of code:
https://github.com/odoo/odoo/blob/14.0/addons/portal/models/mail_message.py#L22
Because `subtype_id` is present in vals and is `False` so `False[0] `raise the error.

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'bool' object is not subscriptable
```

Current behavior:
If a Internal or Portal user open a Portal resource with Chatter and inside there are some messages with subtype_id = False a TypeError is raised

Expected behavior:
If a Internal or Portal user open a Portal resource with Chatter and inside there are some messages with subtype_id = False no errors are raised because the field is optional.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/42646546/166934653-c932d06b-1fe9-458a-afc1-832aeb3babf3.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by albertoprocesscontrol** [comment]
The same happens in the customer portal preview smart button from the sale order, if some of the sale order messages have the subtype_id field empty.

**Comment by dariodelzozzo** [comment]
> The same happens in the customer portal preview smart button from the sale order, if some of the sale order messages have the subtype_id field empty.

Yes this error appears on every Portal Chatter that contains messages with subtype_id
