### ISSUE TITLE
error create payment odoo 15

### ISSUE THREAD

**Issue by medosobh** [odoo/odoo#90835]
Impacted versions:

Steps to reproduce:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 5351, in _update_cache
    field_values = [(fields[name], value) for name, value in values.items()]
  File "/odoo/odoo-server/odoo/models.py", line 5351, in <listcomp>
    field_values = [(fields[name], value) for name, value in values.items()]
KeyError: 'effective_date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1348, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 6421, in onchange
    record = self.new(initial_values, origin=self)
  File "/odoo/odoo-server/odoo/models.py", line 5711, in new
    record._update_cache(values, validate=False)
  File "/odoo/odoo-server/odoo/models.py", line 5353, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'effective_date' on model 'account.payment'

Current behavior: error not complete

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @medosobh feel free to re-open if you can provide steps to reproduce.
