### ISSUE TITLE
Exception during JSON request handling

### ISSUE THREAD

**Issue by akram1** [odoo/odoo#9094]
This is a new database and the latest odoo9 build as of today. I got this error when creating the new database. Creation process went fine but the error keeps showing in the console. I am using Ubuntu 14.04 64bit and PG 9.4.

2015-10-15 18:35:37,819 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:35:37,837 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:37] "GET / HTTP/1.1" 200 -
2015-10-15 18:35:37,846 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:35:37,854 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:35:37,878 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:37] "POST /calendar/notify HTTP/1.1" 200 -
2015-10-15 18:35:37,891 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:35:37,893 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:37] "POST /longpolling/poll HTTP/1.1" 200 -
2015-10-15 18:35:37,884 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:37] "POST /longpolling/poll HTTP/1.1" 200 -
2015-10-15 18:35:37,906 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:37] "POST /calendar/notify HTTP/1.1" 200 -
2015-10-15 18:35:38,199 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:38] "GET /web HTTP/1.1" 303 -
2015-10-15 18:35:40,283 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/login HTTP/1.1" 200 -
2015-10-15 18:35:40,499 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 200 -
2015-10-15 18:35:40,500 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 200 -
2015-10-15 18:35:40,509 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/static/src/css/full.css HTTP/1.1" 200 -
2015-10-15 18:35:40,512 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 200 -
2015-10-15 18:35:40,616 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:40] "GET /web/binary/company_logo HTTP/1.1" 200 -
2015-10-15 18:35:49,535 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:49] "GET /web/database/manager HTTP/1.1" 200 -
2015-10-15 18:35:49,959 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:49] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 200 -
2015-10-15 18:35:49,959 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:49] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 200 -
2015-10-15 18:35:49,960 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:49] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 200 -
2015-10-15 18:35:50,084 31871 INFO ? werkzeug: 127.0.0.1 - - [15/Oct/2015 18:35:50] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/1.1" 304 -
2015-10-15 18:36:02,505 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:36:02,514 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:36:02] "POST /longpolling/poll HTTP/1.1" 200 -
2015-10-15 18:36:02,982 31871 INFO odoo9 openerp.addons.base.ir.ir_autovacuum: GC'd 0 user log entries
2015-10-15 18:36:29,504 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:36:29,516 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:36:29] "POST /longpolling/poll HTTP/1.1" 200 -
2015-10-15 18:36:36,123 31871 INFO None openerp.service.db: Create database `9-1`.
2015-10-15 18:36:46,490 31871 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-15 18:36:46,495 31871 INFO odoo9 werkzeug: 127.0.0.1 - - [15/Oct/2015 18:36:46] "POST /longpolling/poll HTTP/1.1" 200 -
2015-10-15 18:36:50,461 31871 INFO 9-1 openerp.modules.loading: loading 1 modules...
2015-10-15 18:36:50,799 31871 INFO 9-1 openerp.modules.module: module base: creating or updating database tables
2015-10-15 18:36:58,510 31871 INFO 9-1 openerp.models: Computing parent left and right for table ir_ui_menu...
2015-10-15 18:37:28,917 31871 INFO 9-1 openerp.models: Computing parent left and right for table res_partner_category...
2015-10-15 18:37:43,800 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'report_file'
2015-10-15 18:37:43,803 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'crud_model_name'
2015-10-15 18:37:43,805 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'wkf_model_name'
2015-10-15 18:37:43,807 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'global'
2015-10-15 18:37:43,809 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'menus_by_module'
2015-10-15 18:37:45,313 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'views_by_module'
2015-10-15 18:37:45,837 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'reports_by_module'
2015-10-15 18:37:46,410 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'display_name'
2015-10-15 18:37:46,434 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'commercial_partner_id'
2015-10-15 18:37:46,441 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'logo_web'
2015-10-15 18:37:46,458 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'email'
2015-10-15 18:37:46,460 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'phone'
2015-10-15 18:37:46,461 31871 INFO 9-1 openerp.models: storing computed values of fields.function 'share'
2015-10-15 18:37:46,483 31871 INFO 9-1 openerp.models: Storing computed values of res.partner.bank fields sanitized_acc_number
2015-10-15 18:37:46,498 31871 INFO 9-1 openerp.modules.loading: loading base/base_data.xml
2015-10-15 18:37:50,721 31871 INFO 9-1 openerp.modules.loading: loading base/res/res_currency_data.xml
2015-10-15 18:37:54,324 31871 INFO 9-1 openerp.modules.loading: loading base/res/res_country_data.xml

after creating the new database. It is still there

2015-10-15 18:44:28,509 31871 ERROR 9-1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/media/akram/Data/projects/servers/Odoo/runtime/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by radoslavgigov** [comment]
EXACTLY the same problem after removing v8 and install v9!!!

**Comment by kkoci** [comment]
Same here, but really I dunno wy is this happening, all the sudden, any help? =(

**Comment by jweste** [comment]
did you solve this please?

**Comment by moylop260** [comment]
I have the same issue with v9

**Comment by kkoci** [comment]
In my case I think I've just updated my odoo.git repo, from branch 9.0, can't remember now

**Comment by dfang** [comment]
same here

**Comment by marekmatej** [comment]
nearly the same problem here. after upgrading the previously working odoo 9.0c. Have no cluea how to solve this and my web is down for several ours :(

**Comment by pedrobaeza** [comment]
This is not happening anymore deploying correctly. As this is a generic error, some of the "same problem here" can be due to other reasons, but all of them will be probably on the deployment, not on Odoo itself.

**Comment by paolodina** [comment]
if you say so, happy ending then. close because "probably" it's generic.
