### ISSUE TITLE
 Unable to use TensorFlow in Odoo module

### ISSUE THREAD

**Issue by ErpMstar** [odoo/odoo#91425]
Impacted versions: Checked in ver 13 and 15

Steps to reproduce: I am getting this issue just by writing the import statement

`from tensorflow.keras.preprocessing import image`

Current behavior: Unable to import. In a single python file it works perfectly. Even in python interpreter console it is imported successfully. But when I try to integrate that script in a odoo module it gives strang error and crashes the odoo server. 

`Odoo Server Error

Traceback (most recent call last):
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 624, in _handle_exception
   return super(JsonRequest, self)._handle_exception(exception)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 310, in _handle_exception
   raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/tools/pycompat.py", line 14, in reraise
   raise value
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 669, in dispatch
   result = self._call_function(**self.params)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 350, in _call_function
   return checked_call(self.db, *args, **kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/service/model.py", line 94, in wrapper
   return f(dbname, *args, **kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 339, in checked_call
   result = self.endpoint(*a, **kw)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 915, in __call__
   return self.method(*args, **kw)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/http.py", line 515, in response_wrap
   response = f(*args, **kw)
 File "/home/dev/Odoo13_NEW/odoo-13.0/addons/web/controllers/main.py", line 1343, in call_button
   action = self._call_kw(model, method, args, kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/addons/web/controllers/main.py", line 1331, in _call_kw
   return call_kw(request.env[model], method, args, kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/api.py", line 387, in call_kw
   result = _call_kw_multi(method, model, args, kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/api.py", line 374, in _call_kw_multi
   result = method(recs, *args, **kwargs)
 File "", line 2, in button_immediate_install
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
   return method(self, *args, **kwargs)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/addons/base/models/ir_module.py", line 464, in button_immediate_install
   return self._button_immediate_function(type(self).button_install)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/addons/base/models/ir_module.py", line 574, in _button_immediate_function
   modules.registry.Registry.new(self._cr.dbname, update_module=True)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/modules/registry.py", line 86, in new
   odoo.modules.load_modules(registry._db, force_demo, status, update_module)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/modules/loading.py", line 426, in load_modules
   processed_modules += load_marked_modules(cr, graph,
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/modules/loading.py", line 313, in load_marked_modules
   loaded, processed = load_module_graph(
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/modules/loading.py", line 182, in load_module_graph
   load_openerp_module(package.name)
 File "/home/dev/Odoo13_NEW/odoo-13.0/odoo/modules/module.py", line 404, in load_openerp_module
   __import__('odoo.addons.' + module_name)
 File "/home/dev/Odoo13_NEW/odoo-13.0/custom_modules_2022_13/my_modules/e_may/cancer_detection-master/__init__.py", line 4, in 
   from . import models
 File "/home/dev/Odoo13_NEW/odoo-13.0/custom_modules_2022_13/my_modules/e_may/cancer_detection-master/models/__init__.py", line 3, in 
   from . import models
 File "/home/dev/Odoo13_NEW/odoo-13.0/custom_modules_2022_13/my_modules/e_may/cancer_detection-master/models/models.py", line 14, in 
   from tensorflow.keras.preprocessing import image
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in 
   from tensorflow.python.tools import module_util as _module_util
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 84, in 
   from tensorflow.python import keras
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/keras/__init__.py", line 27, in 
   from tensorflow.python.keras import models
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 27, in 
   from tensorflow.python.keras.engine import sequential
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 27, in 
   from tensorflow.python.keras.engine import training
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 49, in 
   from tensorflow.python.profiler import traceme
 File "/home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/profiler/traceme.py", line 28, in 
   from tensorflow.python.profiler.internal import _pywrap_traceme
ImportError: /home/dev/Odoo13_NEW/odoo-13.0/venv_3.8/lib/python3.8/site-packages/tensorflow/python/profiler/internal/_pywrap_traceme.so: failed to map segment from shared object`

Also showing MemoryError and RuntimeError: can't start new thread
 in the logs

**Comment by ErpMstar** [comment]
**Is there any Odoo limitations?**

**Comment by Xavier-Do** [comment]
> **Is there any Odoo limitations?**

It is maybe linked to the memory limit. You can tweak it using the command like, you can check the `odoo-bin --help` for that.
