### ISSUE TITLE
[9.0] Bug in Ecommerce, if the address delivery is changed.

### ISSUE THREAD

**Issue by krocket** [odoo/odoo#9146]
Impacted version [9.0] [Master]

Steps to reproduce

Set up an e-Commerce store
create an order and change address delivery

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 239, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 705, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 824, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 408, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/controllers/main.py", line 643, in confirm_order
    self.checkout_form_save(values["checkout"])
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/controllers/main.py", line 604, in checkout_form_save
    order_obj.onchange_partner_shipping_id(cr, SUPERUSER_ID, [order.id], context=context)
TypeError: onchange_partner_shipping_id() takes exactly 1 argument (5 given)

**Comment by explanar** [comment]
i can confirm.

In between we also got the situation that a "public user" without different delivery address gets an 
```500 Internal Server error``` 
with above ```Template Reset - selected templates will be reset. Type 'yes' in the box below if you want to confirm```.

Does anybody know workaround?

**Comment by krocket** [comment]
Temporarily : yes, I corrected it like this.  
Add a line in module  : addons/sale/sale.py

  @api.one    <----- Add line 164
  @api.onchange('partner_shipping_id')
    def onchange_partner_shipping_id(self):

**Comment by simongoffin** [comment]
Hello,
Using @api.one is deprecated as explained in the link:
https://github.com/odoo/odoo/blob/8.0/openerp/api.py#L378

**Comment by krocket** [comment]
@simongoffin : Thank you for the info and especially for update :)
