### ISSUE TITLE
[8.0] The Connection Pool Is Full

### ISSUE THREAD

**Issue by Dayssam** [odoo/odoo#9204]
Hi Odoo users,

I got this error below when i use odoo in a VPS with 50 connection simultaneously

My server configuration:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               1797.917
BogoMIPS:              3595.83
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-7

H/W path    Device  Class      Description
==========================================
                    system     Bochs ()
/0                  bus        Motherboard
/0/0                memory     96KiB BIOS
/0/401              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/402              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/403              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/404              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/405              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/406              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/407              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/408              processor  Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
/0/1000             memory     16GiB System Memory
/0/1000/0           memory     16GiB DIMM RAM
/0/100              bridge     440FX - 82441FX PMC [Natoma]
/0/100/1            bridge     82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1.1          storage    82371SB PIIX3 IDE [Natoma/Triton II]
/0/100/1.2          bus        82371SB PIIX3 USB [Natoma/Triton II]
/0/100/1.3          bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/2            display    GD 5446
/0/100/3    eth0    network    Virtio network device
/0/100/4    eth1    network    Virtio network device
/0/100/5            storage    Virtio block device
/0/100/6            generic    Virtio memory balloon

Any advice ,???

How to configure odoo to support this number of users ?????

The error : 

2015-10-09 12:17:39,174 5432 ERROR dejeuner werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 478, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, context=request.context)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/odoo/odoo-server/openerp/http.py", line 247, in cr
    self._cr = self.registry.cursor()
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 272, in cursor
    return self._db.cursor()
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 575, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 181, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 464, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 523, in borrow
    raise PoolError('The Connection Pool Is Full')
PoolError: The Connection Pool Is Full
2015-10-09 12:17:39,395 5432 ERROR dejeuner werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo-server/openerp/http.py", line 1437, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 478, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, context=request.context)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/odoo/odoo-server/openerp/http.py", line 247, in cr
    self._cr = self.registry.cursor()
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 272, in cursor
    return self._db.cursor()
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 575, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 181, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 464, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 523, in borrow
    raise PoolError('The Connection Pool Is Full')
PoolError: The Connection Pool Is Full

**Comment by chand3040** [comment]
Hi @Dayssam ,
Odoo works great with workers. It can handle many requests when it starts working with workers.
Set the number of workers and test it for appropriate scenario with the number of requests you want.
It will work out of box.
Happy Odooing.

**Comment by sle-odoo** [comment]
Yeah this is a deployment issue. You probably have to tweak the ``` --db-maxconn ``` argument.

Regards

**Comment by raj15feb** [comment]
Hello,
I have also facing from same error. I set db_maxconn=1000 in openerp-server.conf file and max_connections = 1000 in Postgresql.conf file, but there exists the same error. Can anyone help me?

Best Regards.

**Comment by sylnsr** [comment]
Keep in mind that each PG connection uses about 10MB of RAM so 1,000 connection is going to cost you 10GB of RAM.  You should use pgbouncer instead. See https://www.citusdata.com/blog/2017/05/10/scaling-connections-in-postgres/
