### ISSUE TITLE
Uncaught Error: QWeb2 - template['KanbanView.group_header']: Runtime Error: TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by heliarmandorojas** [odoo/odoo#9205]
odoo for windows version 8.0

buenas noches, 
al realizar la busqueda de proveedores del modulo de compras
usando el filtro personas con el group by comercial.

se produce el error adjunto:

Uncaught Error: QWeb2 - template['KanbanView.group_header']: Runtime Error: TypeError: Cannot read property 'get' of null

**Comment by Yenthe666** [comment]
Hi @heliarmandorojas,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by pa95657** [comment]
Traceback:
Error: QWeb2 - template['kanban-box']: Runtime Error: TypeError: Cannot read property 'value' of undefined
    at Object.exception (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3689:7)
    at Engine.eval (eval at _render (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3731:73), <anonymous>:57:29)
    at Engine._render (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3730:296)
    at Engine.render (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3730:151)
    at Engine._render (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3734:57)
    at Engine.render (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:3730:151)
    at Class._render (http://localhost:8089/web/content/24408-c12f0f9/web.assets_backend.js:1521:118)
    at http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:802:681
    at fire (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8089/web/content/23530-b2078fe/web.assets_common.js:797:467)

I am getting this error while inheriting the kanban view

**Comment by calkikhunt** [comment]
Have you find any solution i'm getting this error in odoo 15
