### ISSUE TITLE
[8.0][API] TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#9213]
This, in my use case, hidden error (anyway destroys the whole purpose of the request) came up in the log and on call of an on change with the use of the old api...so here an issue about mixing the two apis seems likely. 

Actually, it is triggered, in my use case, by `self.write(cr, uid, ids, {'date_order': date_order})` within an old api onchange function where it was still possible to write the record directly before like this.

``` python
openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/deploy/odoo-project/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/deploy/odoo-project/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/deploy/odoo-project/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/addons/mail/mail_thread.py", line 185, in read_followers_data
    for follower in self.pool.get('res.partner').browse(cr, uid, follower_ids, context=context):
  File "/home/odoo/deploy/odoo-project/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/deploy/odoo-project/openerp/models.py", line 5262, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/home/odoo/deploy/odoo-project/openerp/models.py", line 5255, in _browse
    env.prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'
```

There are other issues (https://github.com/odoo/odoo/issues/6821 https://github.com/odoo/odoo/issues/6051 https://github.com/odoo/odoo/issues/2037) having the exact same error in different places / from different directions and my assumption is that it is a regression due to the duality of old and new API in the on change mechanism. Maybe it could be easily fixed or at least explained?

@rco-odoo @beledouxdenis 
Can you please fix this as even in v9 there are still plenty of old api core modules around?

OPW-652868

**Comment by beledouxdenis** [comment]
Hello Wolfgang, 

You are not supposed to write on a record in the context of onchange. This would mean that the changes would not be discarded if the user discard his changes.

Regards,

**Comment by wtaferner** [comment]
Hi Denis,
I know that it is like that in the new API, but it was possible and it was used in the old API...

I used this matter of fact to lock a certain field value for other users with the same object...as a smooth concurrency handling work around ;-)

**Comment by beledouxdenis** [comment]
Then, as a workaround, you can temporary cancel the `in_onchange` environment, with something like:
```
env.all.mode = False
self.write...
env.all.mode = 'onchange'
```

**Comment by wtaferner** [comment]
Hmm, jup, this would be a possible solution for the new API, right? And Guewen even suggested today on the mailing list something like ```record.write(record._convert_to_write(record._cache))``` to write the whole cache inside the a onchange environment in the new API...

But I am talking about the old API onchange. Was the environment variable always available (even in the old API) or how do I retrieve it in the old API model?

**Comment by wtaferner** [comment]
Ok, I was curious and was digging deeper and the source of the stacktrace is https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L183 where a double nested list is for follower_ids is handled (I did not try to find out where this is messed up). 
But, If I fix this temporarily, it actually works but does not fix other issues whereas another related field (currency_id in sale.order) is not computed correctly too...which does make it impossible to save afterwards.

So, my conclusion, nothing to fix here b/c it is all messed up due to the new onchange mechanism and for sure not worth it ;-)

About the workaround you have suggested...I would be interested if you had only the new API in mind or think that it is possible for the old API somehow too?
