### ISSUE TITLE
[9.0] Error on upgrading from 8.0 (models.py:448)

### ISSUE THREAD

**Issue by f-ewald** [odoo/odoo#9235]
Hi *,
I have an error while upgrading odoo from 8.0 to 9.0. 

I updated the files via git and ran `./openerp-server -d testDB -u all`.

While doing this, the `models.py` tries to update all the filed and ran into the following problem:

2015-10-26 01:54:57,747 5930 CRITICAL testDB openerp.service.server: Failed to initialize database `testDB`.
Traceback (most recent call last):
  File "/opt/odoo/openerp/service/server.py", line 885, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 279, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/odoo/openerp/modules/loading.py", line 137, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/odoo/openerp/modules/module.py", line 293, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 2445, in _auto_init
    self._field_create(cr, context=context)
  File "/opt/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 437, in _field_create
    cr.execute(query, vals)
  File "/opt/odoo/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "index" of relation "ir_model_fields" does not exist
LINE 1: ...s (serialization_field_id,model_id,translate,name,index,requ...

It seems that the field is not existing in the odoo 8.0 and needs to exist in odoo 9.0. Is there an update routine which creates the necessary fields or what is the way to go here?

Regards,
F

**Comment by bistaray** [comment]
Upgrading from MAJOR versions of Odoo is not supported within the product.  It requires one of three options:

1. Support from Odoo (via https://upgrade.odoo.com/database/upload - requires a paid Enterprise Contract)
2. Support from the Community (via https://github.com/OCA/OpenUpgrade ).  Untested, unknown level of effort.
3. ETL (extract, transform, load) via CSV or XML or SQL (very hard and time consuming)

**Comment by sle-odoo** [comment]
Closing as @bistaray said everything.

Regards
