### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by LuisPeggo** [odoo/odoo#92469]
Impacted versions: 15.0

Steps to reproduce:

1. git clone from site

2. pip3 install -r requirements.txt

3. ./odoo-bin

Then:

```

Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/home/odoo/odoo/odoo/__init__.py", line 113, in <module>
    from . import modules
  File "/home/odoo/odoo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/odoo/odoo/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/home/odoo/odoo/odoo/tools/__init__.py", line 8, in <module>
    from . import pdf
  File "/home/odoo/odoo/odoo/tools/pdf.py", line 12, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

```

Current behavior: setup error

Expected behavior: successful install

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by manishkumarbohra** [comment]
Hello @LuisPeggo 

The requirement text file already defines the python dependency for this. 

Pillow==5.4.1 ; python_version <= '3.7' and sys_platform != 'win32'
Pillow==6.1.0 ; python_version <= '3.7' and sys_platform == 'win32'
Pillow==8.1.1 ; python_version > '3.7'

Kindly, try this one.
