### ISSUE TITLE
UnboundLocalError: 

### ISSUE THREAD

**Issue by agstyo** [odoo/odoo#9255]
Odoo Server Error
Traceback (most recent call last):
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/agstyo/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/agstyo/odoo/odoo/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/agstyo/odoo/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/addons/woocommerceerpconnect/model/backend.py", line 276, in update_product_stock_qty
    template_id = woo_products.recompute_woo_qty()
  File "/home/agstyo/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/agstyo/odoo/odoo/addons/woocommerceerpconnect/model/product_combination.py", line 126, in recompute_woo_qty
    return product.main_template_id
UnboundLocalError: local variable 'product' referenced before assignment

Hello , I 'm trying to make export data from Odoo 8 to WooCommerce , but I undergo constraints like the above , please give me a solution

**Comment by sle-odoo** [comment]
Hi,
It is the Odoo bug tracker and your issue is in the ```woocommerceerpconnect/model/product_combination.py```which is not part of the standard Odoo addons, so it's not the right place for this bug report.

Regards
