### ISSUE TITLE
Incompatibility with latest version of PyPDF2

### ISSUE THREAD

**Issue by Kontrolix** [odoo/odoo#92595]
Impacted versions: 12.0

Steps to reproduce: install odoo with latest version of PyPDF2 (Version 2.0.0, 2022-06-01)

Current behavior: 

```
Traceback (most recent call last):
  File "/usr/bin/odoo", line 5, in <module>
    import odoo
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 97, in <module>
    PyPDF2.filters.decompress = _decompress
AttributeError: module 'PyPDF2' has no attribute 'filters'
```

Expected behavior:

To not have this error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Kontrolix** [comment]
Maybe it's not so relevant, since PyPDF2 version is fixed to 1.26.0.

**Comment by MartinThoma** [comment]
As a side-note: I would recommend to move to `pypdf>=3.1.0`.

`PyPDF2==3.0.0` and `pypdf==3.1.0` are essentially the same, just the name of the package changed.

I'm the maintainer of `pypdf` and `PyPDF2`. As the capitalization / the number frequently lead to confusion, I decided to move the project to `pypdf`. Only `pypdf` will receive updates.

I have no clue about the Debian packages.

**Comment by bgermann** [comment]
Also Debian is going to remove PyPDF2. The odoo package will be autoremoved with that happening, probably in a month.
