### ISSUE TITLE
latest pull:   ImportError: cannot import name html_translate

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#9271]
Hi,
I just performed a pull and the result was the following error.
The import is in the test of the base module, and removing it temporary fixes odoo. (was crashing with a 500 because of the import error)

    mod_wsgi (pid=18843): Exception occurred processing WSGI script '/home/josesapelli/webapps/odoo/odoo/openerp-wsgi.py'.
    Traceback (most recent call last):
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 1565, in dispatch
    ir_http = request.registry['ir.http']
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/http.py", line 354, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/registry.py", line 354, in get
    update_module)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/loading.py", line 279, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
    File "/home/josesapelli/webapps/odoo/lib/python2.7/site-packages/odoo-9.0-py2.7.egg/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
    File "/home/josesapelli/webapps/odoo/odoo/openerp/addons/base/__init__.py", line 9, in <module>
    import tests
    File "/home/josesapelli/webapps/odoo/odoo/openerp/addons/base/tests/__init__.py", line 23, in <module>
    import test_translate
    File "/home/josesapelli/webapps/odoo/odoo/openerp/addons/base/tests/test_translate.py", line 5, in <module>
    from openerp.tools.translate import quote, unquote, xml_translate, html_translate
    ImportError: cannot import name html_translate

**Comment by Yenthe666** [comment]
Hi @aduijs,

Thanks a lot for your report. This issue should be fixed in the mean time.
If you update your Odoo codebase and database again the problem will be resolved.

Regards,
Yenthe
