### ISSUE TITLE
odoo 9 Enterprise bug

### ISSUE THREAD

**Issue by pgu42** [odoo/odoo#9272]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/openerp/openerp-server/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/openerp/openerp-server/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/openerp/openerp-server/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/openerp/openerp-server/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
  File "/openerp/openerp-server/openerp/http.py", line 1390, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/openerp/openerp-server/openerp/http.py", line 1580, in dispatch
    result = ir_http._dispatch()
  File "/openerp/openerp-server/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/openerp/openerp-server/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/openerp/openerp-server/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/openerp/openerp-server/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/openerp/openerp-server/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/openerp/openerp-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/openerp/openerp-server/openerp/http.py", line 311, in checked_call
    result.flatten()
  File "/openerp/openerp-server/openerp/http.py", line 1367, in flatten
    self.response.append(self.render())
  File "/openerp/openerp-server/openerp/http.py", line 1360, in render
    context=request.context)
  File "/openerp/openerp-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/openerp-server/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/openerp/openerp-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_ui_view.py", line 1065, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/openerp/openerp-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 458, in render_tag_call
    res = self.render(cr, uid, template, d)
  File "/openerp/openerp-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(element, qwebcontext, generated_attributes=qwebcontext.pop('generated_attributes', ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 296, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 319, in render_element
    generated_attributes= name == "t" and generated_attributes or ''))
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 387, in render_tag_foreach
    enum = self.eval_object(expr, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 197, in eval_object
    return self.eval(expr, qwebcontext)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 191, in eval
    return qwebcontext.safe_eval(expr)
  File "/openerp/openerp-server/openerp/addons/base/ir/ir_qweb.py", line 104, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/openerp/openerp-server/openerp/tools/safe_eval.py", line 298, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>

QWebException: "'NoneType' object has no attribute '__getitem__'" while evaluating
"menu_data['children']"
```

**Comment by mart-e** [comment]
? Please check [reporting issue guidelines](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues)

**Comment by sle-odoo** [comment]
looking at the traceback, it typically happens when you want to use a database created with the community edition on the entreprise edition without upgrading the web module

**Comment by pgu42** [comment]
Thank you for your reply. 
But how do they upgrade the web module ? 
What i've done is : 
- Install the Enterprise edition 
- Add the path of the Enterprise edition to the addons_path as below 
======================================== 
addons_path=/openerp/odoo-enterprise,/openerp/openerp-server/addons,/openerp/custom/addons 
======================================== 
- delete the "web" directory from the community addons directory (/openerp/openerp-server/addons) 
- restart odoo 

And i still have the same error 

Prosper Guena Nitcheu 

Port.: (33)6 12 91 17 90 | Fixe : (33)9 53 06 38 29 
linkedin.com/pub/prosper-guena-nitcheu/11/459/618 
pgnitcheu@cpg-consulting.com 
www.cpg-consulting.com | www.cpg-campus.com 


De: "Simon Lejeune" <notifications@github.com> 
À: "odoo/odoo" <odoo@noreply.github.com> 
Cc: "Prosper Guena Nitcheu" <pgnitcheu@cpg-consulting.com> 
Envoyé: Mercredi 28 Octobre 2015 14:37:51 
Objet: Re: [odoo] odoo 9 Enterprise bug (#9272) 



looking at the traceback, it typically happens when you want to use a database created with the community edition on the entreprise edition without upgrading the web module

**Comment by ilmir-k** [comment]
@pgu42 I suppose the issue is not actual for you, but anyway I resolved it by using 
 `./odoo.py --config=/path/to/config-file -u web`
