### ISSUE TITLE
[8.0][base_import] TypeError when trying to import CSV file

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9326]
Steps to reproduce:

1. Go to any list view.
2. Press *Import*.
3. Select any CSV file from your system.
4. You get this error:

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/extra-addons/core-addons/base_import/models.py", line 263, in parse_preview
    'preview': record.file[:ERROR_PREVIEW_BYTES]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This was not happening the last time I tried... Any help?

**Comment by Yajo** [comment]
Sorry, forget it. It was some failure between Firefox in Linux and Samba. Uploading a file from there got empty contents and thus made this fail. Copying file to local drive before uploading fixes that.
