### ISSUE TITLE
[14.0]TypeError: _notify_get_groups() got an unexpected keyword argument 'msg_vals'

### ISSUE THREAD

**Issue by filwu8** [odoo/odoo#93375]
Impacted versions:  Odoo version 14.0-20220607 

Steps to reproduce: I'm in the helpdesk change stage, it‘s error when i set email template。 when i set empty for email template ，it's seems to be working fine

Current behavior: error

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 355, in checked_call
    self._cr.precommit.run()
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1154, in run
    func()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 553, in _finalize_tracking
    record._message_track_post_template(changes)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 587, in _message_track_post_template
    self._fallback_lang().message_post_with_template(template.id, **post_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mass_mailing/models/mail_thread.py", line 37, in message_post_with_template
    return super(MailThread, no_massmail).message_post_with_template(template_id, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1989, in message_post_with_template
    return composer.send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/mail_compose_message.py", line 20, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/mail_compose_message.py", line 13, in send_mail
    return super(MailComposeMessage, self).send_mail(auto_commit=auto_commit)
  File "/usr/lib/python3/dist-packages/odoo/addons/coupon/models/mail_compose_message.py", line 15, in send_mail
    return super().send_mail(**kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 264, in send_mail
    ActiveModel.browse(res_id).message_post(**post_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1915, in message_post
    self._notify_thread(new_message, values, **notif_kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sms/models/mail_thread.py", line 238, in _notify_thread
    recipients_data = super(MailThread, self)._notify_thread(message, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2164, in _notify_thread
    self._notify_record_by_email(message, rdata, msg_vals=msg_vals, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2232, in _notify_record_by_email
    recipients_groups_data = self._notify_classify_recipients(partners_data, model_name, msg_vals=msg_vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2624, in _notify_classify_recipients
    groups = self._notify_get_groups(msg_vals=local_msg_vals)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _notify_get_groups() got an unexpected keyword argument 'msg_vals'

hot to fix it?

**Comment by filwu8** [comment]
fixed

helpdesk_ticket.py

835-840

    def _notify_get_groups(self, msg_vals=None):
        """ Handle helpdesk users and managers recipients that can assign
        tickets directly from notification emails. Also give access button
        to portal and portal customers. If they are notified they should
        probably have access to the document. """
        groups = super(HelpdeskTicket, self)._notify_get_groups(msg_vals=msg_vals)

**Comment by filwu8** [comment]
We should support ourselves by our own labor.
