### ISSUE TITLE
[15] TypeError: this.wysiwyg.cleanForSave is not a function

### ISSUE THREAD

**Issue by hardissimo** [odoo/odoo#93675]
Impacted versions: 15

Steps to reproduce: try to save a sale order or other model like customer

Current behavior: can't save and error pop up, after error, all actions are blocked until you reload webpage

UncaughtPromiseError > TypeError
Promesa desconocida > this.wysiwyg.cleanForSave is not a function
TypeError: this.wysiwyg.cleanForSave is not a function
    at Class.commitChanges (https://domain.tld/web/assets/643-13e066e/web.assets_backend.min.js:9681:54)
    at prototype.<computed> (https://domain.tld/web/assets/642-5e0fae1/web.assets_common.min.js:4725:488)
    at Class.commitChanges (https://domain.tld/web/assets/643-13e066e/web.assets_backend.min.js:9674:13)
    at Class.commitChanges (https://domain.tld/web/assets/642-5e0fae1/web.assets_common.min.js:4728:371)
    at https://domain.tld/web/assets/643-13e066e/web.assets_backend.min.js:4761:250
    at _.map._.collect (https://domain.tld/web/assets/642-5e0fae1/web.assets_common.min.js:154:270)
    at Class.commitChanges (https://domain.tld/web/assets/643-13e066e/web.assets_backend.min.js:4761:184)
    at https://domain.tld/web/assets/643-13e066e/web.assets_backend.min.js:4492:668

Expected behavior: save modal without error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by a0c** [comment]
@hardissimo Any solution to this? I've no idea what could have lead to this... I have updated Odoo v15 to the latest commit - and now I cannot create/edit any records, I'm getting the same error. When I create a new DB with the exact same list of modules installed, it works fine. Could there be some caching issue? I'm running Odoo in Docker.

**Comment by a0c** [comment]
@hardissimo Odoo seems to lack a JS/CSS rebuild facility on minor versions update.
A solution is very simple: just delete all JS/CSS/JS.MAP files from Attachments to force Odoo to regenerate them on next access:
```sql
DELETE FROM ir_attachment WHERE mimetype in ('text/css','application/octet-stream','application/javascript');
```
For me it deleted and recreated the following files:
```
/web/assets/2458-4f7ef1d/web.assets_common.min.css
/web/assets/2460-4f7ef1d/web.assets_common.min.js
/web/assets/2462-f18f3d4/web.assets_backend_prod_only.min.js
/web/assets/2463-1314ece/1/web_editor.assets_wysiwyg.min.css
/web/assets/2464-1314ece/1/web_editor.assets_wysiwyg.min.js
/web/assets/2467-1314ece/web_editor.assets_wysiwyg.min.css
/web/assets/2468-4f7ef1d/1/web.assets_common.min.css
/web/assets/2469-22be5c1/1/web.assets_frontend.min.css
/web/assets/2470-796b097/1/web.assets_common_minimal.min.js
/web/assets/2471-e6d4a91/1/web.assets_frontend_minimal.min.js
/web/assets/2472-da34e1c/1/web.assets_common_lazy.min.js
/web/assets/2473-bd4dfd3/1/web.assets_frontend_lazy.min.js
/web/assets/2474-6cda41e/web.assets_backend.min.css
/web/assets/2475-6cda41e/web.assets_backend.min.js
```

Enjoy :tada: :tada: :tada: :+1:

**Comment by jwaes** [comment]
Well this 'workaround' sometimes does delete stuff that is not recreated:

```
Could not get content for /website/static/src/scss/options/user_values.custom.web.assets_common.scss defined in bundle 'web.assets_common'.
Could not get content for /website/static/src/scss/options/colors/user_theme_color_palette.custom.web.assets_common.scss defined in bundle 'web.assets_common'.
```

**Comment by 99rgosse** [comment]
I could overcome this issue with the "Regenerate the assets" :

1.     Enable developer mode
2.     Open the debug menu from the toolbar
3.     Select Regenerate Asset Bundles
(https://holdenrehg.com/blog/2019-03-09_odoo-images-and-attachments-explain-regenerate-assets)
