### ISSUE TITLE
[9.0]  Debugging /my/home results in TypeError

### ISSUE THREAD

**Issue by fuzzy-id** [odoo/odoo#9392]
When using the `website_portal` addon one is not able to debug the route `/my/home`, i.e. start Odoo passing it the `--dev` option, then visit `http://localhost:8069/my/home?debug`, one gets the following stacktrace:

```
2015-11-03 16:10:57,711 3582 INFO odoo90 werkzeug: 127.0.0.1 - - [03/Nov/2015 16:10:57] "GET /my/home?debug HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vince/src/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/vince/src/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/vince/src/odoo/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
  File "/home/vince/src/odoo/openerp/http.py", line 1390, in __call__
    return self.app(environ, start_wrapped)
  File "/nix/store/d5hcgssadf71ni9gx15wlcdv5z3kb4ib-python2.7-Werkzeug-0.9.6/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/vince/src/odoo/openerp/http.py", line 1580, in dispatch
    result = ir_http._dispatch()
  File "/home/vince/src/odoo/addons/website/models/ir_http.py", line 190, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/home/vince/src/odoo/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/vince/src/odoo/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/home/vince/src/odoo/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/vince/src/odoo/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/home/vince/src/odoo/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/home/vince/src/odoo/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/vince/src/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/vince/src/odoo/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/vince/src/odoo/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/home/vince/src/odoo/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
TypeError: account() got an unexpected keyword argument 'debug'

```

**Comment by fuzzy-id** [comment]
Easily fixable via
```
diff --git a/addons/website_portal/controllers/main.py b/addons/website_portal/controllers/main.py
index a11adac..be1500d 100644
--- a/addons/website_portal/controllers/main.py
+++ b/addons/website_portal/controllers/main.py
@@ -7,7 +7,7 @@ from openerp.tools.translate import _
 
 class website_account(http.Controller):
     @http.route(['/my', '/my/home'], type='http', auth="public", website=True)
-    def account(self):
+    def account(self, **kw):
         partner = request.env.user.partner_id
 
         # get customer sales rep

```

**Comment by rdeodoo** [comment]
Already fixed
