### ISSUE TITLE
[9.0] Failed to 'Validate' Vendor Refund Bill

### ISSUE THREAD

**Issue by zenntrix** [odoo/odoo#9397]
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 546, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 583, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 828, in __call__
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 412, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 984, in exec_workflow
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 1136, in exec_workflow
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 904, in proxy_method
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\http.py", line 115, in dispatch_rpc
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 37, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 189, in exec_workflow
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 183, in exec_workflow_cr
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\service\model.py", line 165, in execute_cr
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 223, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\models.py", line 3575, in signal_workflow
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow__init__.py", line 67, in trg_validate
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\service.py", line 73, in validate
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\instance.py", line 57, in validate
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 102, in process
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 230, in _split_test
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 239, in _join_test
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 77, in create
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 98, in process
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 144, in _execute
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 295, in wkf_expr_execute
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\workflow\workitem.py", line 273, in wkf_expr_eval_expr
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\tools\safe_eval.py", line 298, in safe_eval
  File "", line 1, in <module>
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 221, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\account_asset\account_asset_invoice.py", line 15, in action_move_create
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 221, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\account\models\account_invoice.py", line 749, in action_move_create
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 221, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\account_asset\account_asset.py", line 514, in post
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 221, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\account\models\account_move.py", line 129, in post
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\api.py", line 221, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_sequence.py", line 251, in next_by_id
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_sequence.py", line 237, in _next
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_sequence.py", line 187, in _next_do
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\ir\ir_sequence.py", line 61, in _update_nogap
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\sql_db.py", line 139, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server.\openerp\sql_db.py", line 215, in execute
ValueError: "operator does not exist: integer = boolean
LINE 1: SELECT number_next FROM ir_sequence WHERE id=False FOR UPDAT...
                                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
" while evaluating
u'action_move_create()'

**Comment by rgeromegnace** [comment]
I have the same problem.
Is anybody has a solution?

Regards

**Comment by vincentius** [comment]
+1, Same problem here.

**Comment by vincentius** [comment]
Got it, I had to add a Refund Entry Sequence.

**Comment by Rakoun** [comment]
Yes it seems a good solution but not work for me. I duplicate a previous refund entry sequence that existed for another company and it does not work.
How do you specify that your new sequence is for refund entry?

Regards,

**Comment by sle-odoo** [comment]
Hi,
This issue is not reproducible anymore. Also, maybe it is related to the postgres version? Are you still facing this issue when validating a vendor bill?

Regards
