### ISSUE TITLE
Failure to export to XLSL/CSV in v15.0

### ISSUE THREAD

**Issue by dieg0-a** [odoo/odoo#94110]
Impacted versions: v15 (at least from 05/13/22 to 06/20/22 nightly releases)

Steps to reproduce: Try to export product data, so far trying to export other data also results in an error

Current behavior: The frontend displays the following error message:
```
TypeError: invalid parameter format
    at Object.parse (http://localhost:8069/web/assets/99-c254acb/web.assets_common.min.js:4547:45)
    at XMLHttpRequest.xhr.onload (http://localhost:8069/web/assets/99-c254acb/web.assets_common.min.js:4678:241)
```
Expected behavior: File save dialog should pop up

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Observations: Based on my research a string containing (product.template) is passed to contentDisposition.parse() and that results in PARAM_REGEXP not matching up to the end of the string, instead it stops as soon as it finds a "(", which results in an exception as per:

[addons/web/static/src/legacy/js/libs/content-disposition.js]
```
if (index !== -1 && index !== string.length) {
--
215 | throw new TypeError('invalid parameter format')
```

Removing this check works around the problem but the resulting file name appears to be missing something at the end, ie:
Product template_.xlsx

It doesn't look like the backend is catching any errors as there are no error or warning messages in the server log.

**Comment by mschulz-asphericon** [comment]
We had the same issue right now on an on-premise server. We have found that the problem was caused by a wrong version of the python module "Werkzeug", which was too new. The problem of the error message above was that the filename was not created correctly, in a way, that the brackets were not escaped.
