### ISSUE TITLE
[8.0] Server Error 528 when i go to setup/technical/mail/message !

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#9438]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/addons/web/controllers/main.py", line 912, in do_search_read
    length = Model.search_count(domain, request.context)
  File "/opt/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 1623, in search_count
    res = self.search(cr, user, args, context=context, count=True)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1771, in search
    return super(mail_message, self).search(cr, uid, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 1645, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/website_mail/models/mail_message.py", line 73, in _search
    context=context, count=count, access_rights_uid=access_rights_uid)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/portal/mail_message.py", line 45, in _search
    context=context, count=count, access_rights_uid=access_rights_uid)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_message.py", line 653, in _search
    allowed_ids = self._find_allowed_doc_ids(cr, uid, model_ids, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_message.py", line 605, in _find_allowed_doc_ids
    allowed_ids |= self._find_allowed_model_wise(cr, uid, doc_model, doc_dict, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1778, in _find_allowed_model_wise
    for virtual_id in self.pool[doc_model].get_recurrent_ids(cr, uid, doc_dict.keys(), [], order=order, context=context):
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1192, in get_recurrent_ids
    rdates = self.get_recurrent_date_by_event(cr, uid, ev, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 716, in get_recurrent_date_by_event
    ids_depending = self.search(cr, uid, [('recurrent_id', '=', event.id), '|', ('active', '=', False), ('active', '=', True)], context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1514, in search
    res = self.get_recurrent_ids(cr, uid, res, args, order=order, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1188, in get_recurrent_ids
    if not ev.recurrency or not ev.rrule:
  File "/opt/odoo/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/opt/odoo/openerp/fields.py", line 912, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3241, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/addons/calendar/calendar.py", line 1693, in read
    res = real_data[real_id].copy()
KeyError: 528

**Comment by malatestay** [comment]
A clarification about the reported error, when I use admin I do not have that mistake!
I continue to look for if someone has an idea ...
Thank you
Yves

**Comment by challs** [comment]
Hello @malatestay 

I might have the same issue, but it is not clear from your message what was happening.

I don't think there is enough information in the traceback alone for the developers to be able to understand the problem enough to find a fix.

* What did you do to get the error?
* What error message did you get? Ideally, what log messages were written to the log?

**Comment by malatestay** [comment]
Hello @challs 

From memory, I think the problem was the sync between google calendar and Odoo. Especially when there were repetitive events.

In our context, the user had a calendar in Outlook that it synchronized with Google Calendar, which was itself synchronized with Odoo.

The synchronization between Outlook and Google calendar tool does not correctly filled the agenda and it was not visible in Google Calendar but Odoo missing information (start date) was crashing the calandar Odoo.

To correct you had to manually edit the data in the DB.
The tool has now been corrected and the problem is fixed.

**Comment by Yenthe666** [comment]
Hi @malatestay,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
