### ISSUE TITLE
[9.0] server error after pull commit ed11d79

### ISSUE THREAD

**Issue by eneldoserrata** [odoo/odoo#9439]
@KangOl commit #ed11d79

Odoo Server Error
Traceback (most recent call last):
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 636, in dispatch
    result = self._call_function(**self.params)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/Users/eneldoserrata/PycharmProjects/marcos/odoo/odoo9/addons/web_settings_dashboard/controllers/main.py", line 43, in web_settings_dashboard_data
    'pending_count': counts[False],
KeyError: False

**Comment by eneldoserrata** [comment]
nice fast commit :)
