### ISSUE TITLE
 Installing odoo 12 on ubuntu LTS 22.04

### ISSUE THREAD

**Issue by bibalani** [odoo/odoo#94619]
when I am going to run odoo using `./odoo-bin -c /etc/odoo-server.conf`

I encounter with following error:

```
Traceback (most recent call last):
  File "/home/morteza/nak_project/odoo/odoo-server/./odoo-bin", line 5, in 
    import odoo
  File "/home/morteza/nak_project/odoo/odoo-server/odoo/__init__.py", line 73, in 
    import babel
  File "/home/morteza/nak_project/odoo/env/lib/python3.10/site-packages/babel/__init__.py", line 20, in 
    from babel.core import UnknownLocaleError, Locale, default_locale, \
  File "/home/morteza/nak_project/odoo/env/lib/python3.10/site-packages/babel/core.py", line 14, in 
    from babel import localedata
  File "/home/morteza/nak_project/odoo/env/lib/python3.10/site-packages/babel/localedata.py", line 17, in 
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
I have already installed babel-2.3.4 version

**Comment by dungnm8** [comment]
I same error. I install python 3.6.x or python 3.7.x fix fix issues
