### ISSUE TITLE
[9.0]Impossible to use french language

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#9474]
**French translation causes odoo crash**

Impacted versions:

 - 9.0

Steps to reproduce:

 1. create a new database in english
 2. install successfully some module
 3. Import french language
 4. Change the language of the admin user

Current behavior:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1416, in __call__
    return self.dispatch(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1390, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 1580, in dispatch
    result = ir_http._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/web/controllers/main.py", line 535, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, request.debug, context=request.context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in load_menus
    
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_menu.py", line 264, in load_menus
    menu_root_ids = self.get_user_roots(cr, uid, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_menu.py", line 239, in get_user_roots
    return self.search(cr, uid, menu_domain, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_menu.py", line 91, in search
    result = self._filter_visible_menus(cr, uid, ids, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_menu.py", line 72, in _filter_visible_menus
    visible_ids = self._visible_menu_ids(request.debug if request else False)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 230, in wrapper
    return new_api(self, *args, **kwargs)
  File "<string>", line 2, in _visible_menu_ids
    
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_ui_menu.py", line 54, in _visible_menu_ids
    if not fname or not menu.action[fname] or \
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/models.py", line 5679, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/fields.py", line 905, in determine_value
    record._prefetch_field(self)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 230, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/models.py", line 3273, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 230, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/addons/base/ir/ir_actions.py", line 373, in read
    res['help'] = self.pool[model].get_empty_list_help(cr, uid, res.get('help', ""), context=ctx)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/openerp/api.py", line 327, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo_9/addons/mail/models/mail_thread.py", line 357, in get_empty_list_help
    'dyn_help': _("Click here to add new %s") % document_name,
ValueError: unsupported format character ' ' (0x20) at index 30
```

Expected behavior:

 - No problem

**Comment by mart-e** [comment]
Hello,

Sorry but I can not reproduce your issue. Could you please give more details:
- which modules did you install?
- which menu have you opened?
- which revision of the code?

Thanks

**Comment by jeebee2013** [comment]
I've the same problem (bitnami VM)
no needs to install some module to reproduce the error
> load french translation
> change admin language
Error 500

**Comment by weevil83** [comment]
Same problem here, but when loading pt_BR translation.

I tryed the following steps 2 times each (OVH VPS) and the error persists.

1. Fresh install of CentOS 7.
2. Fresh install of Odoo 9.
3. Created database named "test" selecting language Portuguese (BR) / Português (BR).
4. Logged out.
5. Error 500.

1. Fresh install of CentOS 7.
2. Fresh install of Odoo 9.
3. Created database named "test".
4. Settings Menu > Load a Translation.
5. Successfully installed Portuguese (BR) / Português (BR).
6. Logged out.
7. Error 500.

Even when trying to select databases "http://IP:8069/web/database/selector", when I click on "test" database I get a 500 error.

Other databases where I did not load any language pack are working fine.

Any clues there? Thanks.

**Comment by mart-e** [comment]
Sorry guys but I will need more details than that. A 500 error has error logs on the server side, please share them.
Also the translations changes quite a lot so you need to test it on the latest 9.0 version or at least tell me the exact git revision you are usingg . You can try on the [runbot](http://runbot.odoo.com/runbot) where you can check the latest build of each version.

@weevil83 please let's keep one bug per issue reported. We have recently fixed a few translation issues with `pt_BR` (and I just fetched the translation at 463044a). Please let me know if you can reproduce with the latest.

**Comment by touilleMan** [comment]
I've the same trouble
commit 345809b9936da7664a881fa03679ff882bfb76f5 is fixing this

For those who have the trouble under

**Comment by mart-e** [comment]
Thanks for update @touilleMan 
I am closing this issue but let me know (with details) in case you still have this issue

**Comment by flotho** [comment]
Hi, with the latest rpm, I have a problem in the inventory planner. 
I won't update translations because of a https://github.com/odoo/odoo/issues/9480
