### ISSUE TITLE
Tracking functionality bugged for monetary fields

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [odoo/odoo#94962]
Impacted versions: 15

Steps to reproduce:

This is a bug in the mail module, found in addons/mail/models/models.py, line 57

Current behavior:

The problem code is the following:
`tracking['currency_id'] = getattr(self, col_info.get('currency_field', ''), self.company_id.currency_id).id`

This line of code assumes that the record for which tracking is enabled (self) has a field called company_id, which might not necessarily be the case. If this field doesn't exist, changes in a monetary field that has `tracking=True` result in the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 355, in checked_call
    self._cr.flush()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 109, in flush
    self.precommit.run()
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1137, in run
    func()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 543, in _finalize_tracking
    tracking = records.with_context(context).message_track(fnames, initial_values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 604, in message_track
    tracking[record.id] = record._mail_track(tracked_fields, initial_values[record.id])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/models.py", line 58, in _mail_track
    tracking['currency_id'] = getattr(self, col_info.get('currency_field', ''), self.company_id.currency_id).id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'contract' object has no attribute 'company_id'
```

Furthermore, it seems that the tracking function is also called multiple times for fields that are a dependency on *another* model's computed field, but with `self` set to the other model's record. 
Explaining more clearly: if I'm tracking `model_A.field_A`, and another `model_B` has a computed `field_B` with `@api.depends("model_A.field_A")`, the tracking function is called twice for `field_A` when this field changes, BUT on the second time, `type(self) = <class 'odoo.api.model_B'>`.
This forces model_B to also have the company_id field which also doesn't make sense.

Expected behavior:

I expect to be able to track monetary fields without having to associate a company with the record in question, as this doesn't make conceptual sense in this case.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/51457048/176684419-8c7e1db8-34de-41ff-8887-fda3698ac953.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
@tde-banana-odoo ?

**Comment by tde-banana-odoo** [comment]
https://github.com/odoo/odoo/pull/94831 ?

**Comment by FredericoCoelhoNunes** [comment]
Didn't notice that one! Seems like it was created not too long ago either. Thanks @tde-banana-odoo
