### ISSUE TITLE
JS error when Saving user data

### ISSUE THREAD

**Issue by vankhoafgc** [odoo/odoo#95194]
Impacted versions: Odoo 15 enterprise edition

Steps to reproduce: Create a new user or edit the existing user

Current behavior: Throw a JS error
```
UncaughtPromiseError > SyntaxError
Uncaught Promise > Failed to execute 'querySelectorAll' on 'Element': '"]' is not a valid selector.
```

Expected behavior: Should be saved successfully

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/50700543/177127130-d107d784-c38c-4635-b49d-c332e91bed27.png)
![image](https://user-images.githubusercontent.com/50700543/177127625-1878eb8b-b474-487c-8345-f244909f63f8.png)

Full log:
```
SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '"]' is not a valid selector.
    at classToStyle (http://localhost:8069/web/assets/debug/web.assets_backend.js:135954:32) (/web_editor/static/src/js/backend/convert_inline.js:312)
    at toInline (http://localhost:8069/web/assets/debug/web.assets_backend.js:136080:5) (/web_editor/static/src/js/backend/convert_inline.js:438)
    at Class._toInline (http://localhost:8069/web/assets/debug/web.assets_backend.js:136772:9) (/web_editor/static/src/js/backend/convert_inline.js:1130)
    at Class.commitChanges (http://localhost:8069/web/assets/debug/web.assets_backend.js:136747:18) (/web_editor/static/src/js/backend/convert_inline.js:1105)
    at Class.commitChanges (http://localhost:8069/web/assets/debug/web.assets_common.js:61384:38) (/web/static/src/legacy/js/core/class.js:124)
    at http://localhost:8069/web/assets/debug/web.assets_backend.js:69693:27 (/web/static/src/legacy/js/views/basic/basic_renderer.js:138)
    at _.map._.collect (http://localhost:8069/web/assets/debug/web.assets_common.js:2119:24) (/web/static/lib/underscore/underscore.js:164)
    at Class.commitChanges (http://localhost:8069/web/assets/debug/web.assets_backend.js:69692:22) (/web/static/src/legacy/js/views/basic/basic_renderer.js:137)
    at http://localhost:8069/web/assets/debug/web.assets_backend.js:63457:38 (/web/static/src/legacy/js/views/basic/basic_controller.js:214)
```

**Comment by Etren** [comment]
I also encountered this problem when I run odoo in docker, how can I fix it?
