### ISSUE TITLE
Error when create new mail template

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#9537]
**Error when create new mail template**

Impacted versions:

 - 9.0

Steps to reproduce:

 1. create a new mail template (Mass Mailing / Configuration / Mail template) or change "Applies To" of an existing one.

Current behavior:

 - Get the following error message :

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 636, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/addons/web/controllers/main.py", line 971, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/addons/web/controllers/main.py", line 963, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/api.py", line 232, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/models.py", line 5990, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/runbot/extra/runbot/static/build/112414-9-0-1db144/openerp/models.py", line 5896, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
TypeError: onchange_model_id() takes exactly 1 argument (5 given)
```

Expected behavior:

 - No error message !

**Comment by nle-odoo** [comment]
Hello,

It should be solved with https://github.com/odoo/odoo/commit/daca0d3 which need an update of the mass_mailing module, or a manual update of the `ir.ui.view` with id `email_template_form_minimal`.

Thanks.
