### ISSUE TITLE
hr_employee_benefit Module Bug when compute benefit button clicked

### ISSUE THREAD

**Issue by newmanx** [odoo/odoo#9541]
There seems to be a bug with hr_employee_benefit module, After adding the benefit categories and rate, when we click on Benefit compute button under payslips, its returning this error:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1137, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_employee_benefit/models/hr_payslip.py", line 78, in button_compute_benefits
    payslip.compute_benefits(payslip)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 378, in function_proxy
    return attr(self._cr, self._uid, [self._id], *args, **kwargs)
TypeError: compute_benefits() got multiple values for keyword argument 'context'

**Comment by newmanx** [comment]
Issue solved here:

https://github.com/OCA/hr/issues/191
