### ISSUE TITLE
requirements.txt wrong version requirement for gevent on jammy

### ISSUE THREAD

**Issue by PeteKraft** [odoo/odoo#95618]
I just tried a clean odoo install on Ubuntu Jammy (22.04)
The install of the requirements.txt would fail on the package requirement of gevent (21.8.0) according to requirements.txt
A wrong version of cffi backend would cause the install to fail.

I edited my requirements to install gevent version 21.12 instead and all went fine, so perhaps the requirements.txt needs changing ?

**Comment by gdgellatly** [comment]
Odoo doesn't target Jammy. Generally latest stable release of Debian or Ubuntu prior to version release. 

See https://www.odoo.com/documentation/15.0/administration/install/install.html - so if you want to install on a non target release, then yes you may need to adjust for that.

**Comment by PeteKraft** [comment]
If you look inside requirements.txt, you'll see that it explicitly specifies versions for Jammy. All I'm saying is that there is an error for the gevent version requirement, for Jammy...

I'm only sharing what I found. I'm sure someone will find this helpfull...

**Comment by kquiroz** [comment]
I have also found this issue. Trying to install requirements.txt on Jammy gives me this error.
```
Collecting gevent==21.8.0
  Using cached gevent-21.8.0.tar.gz (6.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 481, in <module>
        File "<string>", line 348, in run_setup
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
          ffi = FFI()
        File "/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.15.1, located in '/tmp/pip-build-env-n4fy0_a5/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
It has made some people say that [Odoo 15 is incompatible with Python 3.10](https://stackoverflow.com/a/73693506), which is the default installation on Jammy.

**Comment by yuriko-aya** [comment]
It's also happen on odoo 16.0
changing gevent to 21.12 fix this
