### ISSUE TITLE
Odoo15 Shutdown Error

### ISSUE THREAD

**Issue by tolgahankilic** [odoo/odoo#96146]
Impacted versions:15

Steps to reproduce: When closing with CTRL + C in Visual Studio Code

Current behavior: Shutdown Error

Expected behavior: Shutdown without error

Video/Screenshot link (optional):

**When I run the service and shut it down after a while without doing anything, I get the following error:**

```
2022-07-16 18:14:10,056 28962 INFO new_db odoo.modules.registry: Registry loaded in 1.359s 
^C2022-07-16 18:14:10,897 28962 INFO new_db odoo.service.server: Initiating shutdown 
2022-07-16 18:14:10,897 28962 INFO new_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2022-07-16 18:14:11,127 28962 INFO new_db odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
Exception in thread odoo.service.cron.cron0:
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/service/server.py", line 445, in cron_thread
```

**When I stop the service after adding or deleting data to the database, I get an error like the one below.**

```
2022-07-16 18:02:26,000 27815 INFO new_db werkzeug: 127.0.0.1 - - [16/Jul/2022 18:02:26] "POST /web/dataset/call_kw/hospital.patient/web_read_group HTTP/1.1" 200 - 2 0.000 0.003
^C2022-07-16 18:02:27,494 27815 INFO new_db odoo.service.server: Initiating shutdown 
2022-07-16 18:02:27,495 27815 INFO new_db odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2022-07-16 18:02:27,498 27815 INFO new_db odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 8 connections  
Exception in thread odoo.service.cron.cron0:
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/service/server.py", line 445, in cron_thread
    pg_conn.poll()
psycopg2.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/odoo15/odoo/odoo/service/server.py", line 473, in target
    self.cron_thread(i)
  File "/opt/odoo15/odoo/odoo/service/server.py", line 431, in cron_thread
    with conn.cursor() as cr:
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 162, in __exit__
    self.close()
  File "<decorator-gen-4>", line 2, in close
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 379, in close
    return self._close(False)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 405, in _close
    self.rollback()
  File "<decorator-gen-8>", line 2, in rollback
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 484, in rollback
    result = self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
2022-07-16 18:02:27,500 27815 ERROR ? odoo.addons.bus.models.bus: Bus.loop error, sleep and retry 
Traceback (most recent call last):
  File "/opt/odoo15/odoo/addons/bus/models/bus.py", line 177, in loop
    conn.poll()
psycopg2.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/addons/bus/models/bus.py", line 200, in run
    self.loop()
  File "/opt/odoo15/odoo/addons/bus/models/bus.py", line 169, in loop
    with odoo.sql_db.db_connect('postgres').cursor() as cr:
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 162, in __exit__
    self.close()
  File "<decorator-gen-4>", line 2, in close
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 379, in close
    return self._close(False)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 405, in _close
    self.rollback()
  File "<decorator-gen-8>", line 2, in rollback
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 484, in rollback
    result = self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
Exception in thread odoo.service.cron.cron1:
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/service/server.py", line 445, in cron_thread
    pg_conn.poll()
psycopg2.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/odoo15/odoo/odoo/service/server.py", line 473, in target
    self.cron_thread(i)
  File "/opt/odoo15/odoo/odoo/service/server.py", line 431, in cron_thread
    with conn.cursor() as cr:
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 162, in __exit__
    self.close()
  File "<decorator-gen-4>", line 2, in close
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 379, in close
    return self._close(False)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 405, in _close
    self.rollback()
  File "<decorator-gen-8>", line 2, in rollback
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/sql_db.py", line 484, in rollback
    result = self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
2022-07-16 18:02:27,514 27815 INFO new_db werkzeug: 127.0.0.1 - - [16/Jul/2022 18:02:27] "POST /longpolling/poll HTTP/1.1" 200 - 13 0.018 8.418
```

**There is no problem in adding or deleting data in the database, I just couldn't understand the reason for this error.**

**Comment by hamsukydev** [comment]
have you please resolved this issues

**Comment by tolgahankilic** [comment]
> have you please resolved this issues

Unfortunately, I could not solve the problem
