### ISSUE TITLE
[14.0][MRP] Bug with duplicated MO

### ISSUE THREAD

**Issue by fa-odoo** [odoo/odoo#96184]
Impacted versions: 14.0

Steps to reproduce:

- create a MO (WH/MO/00006) of 2units with a product tracked by lot
- validate the Mo  (WH/MO/00006) then change the produced quantity to 4units
- mark the MO  (WH/MO/00006) as done
- Duplicate the  (WH/MO/00006) and validate the new Mo  (WH/MO/00007)
- change the produced quantity to 3 then mark it as done (WH/MO/00007)

Current behavior:
an error occurs
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/data/build/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/data/build/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/data/build/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/data/build/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/data/build/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/data/build/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/mrp/wizard/mrp_production_backorder.py", line 40, in action_backorder
    return self.mrp_production_ids.with_context(ctx, skip_backorder=True, mo_ids_to_backorder=mo_ids_to_backorder).button_mark_done()
  File "/data/build/enterprise/quality_mrp/models/mrp_production.py", line 51, in button_mark_done
    return super(MrpProduction, self).button_mark_done()
  File "/data/build/odoo/addons/mrp_account/models/mrp_production.py", line 79, in button_mark_done
    res = super(MrpProduction, self).button_mark_done()
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 1544, in button_mark_done
    productions_to_backorder._post_inventory(cancel_backorder=False)
  File "/data/build/odoo/addons/mrp/models/mrp_production.py", line 1419, in _post_inventory
    if not finish_moves.quantity_done:
  File "/data/build/odoo/odoo/fields.py", line 965, in __get__
    record.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5014, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: stock.move(114, 115)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by techgrrow** [comment]
Hi, did you find a way to solve this issue?

**Comment by ahmed3baid** [comment]
Issue is that the original MO would have two finished moves lines and they got copied to the duplicate MO on mrp/models/mrp_production.py in copy_data.

`default['move_finished_ids'] = [(0, 0, move.copy_data()[0]) for move in move_finished_ids]`

Possible Solutions:
- Stop copying finished products and trigger _onchange_move_finished_product after copy.
- Refactor copied finished lines to one line.

**Comment by techgrrow** [comment]
Thanks for the fixes suggestions, it was indeed a problem with copying the MO.
