### ISSUE TITLE
Cache miss crashes the website (500)

### ISSUE THREAD

**Issue by Mulugruntz** [odoo/odoo#96503]
# Impacted versions:
Odoo 15

# Steps to reproduce:

1. Create an article with tons of variants.
2. Go to the shop to display the product.
3. After a few seconds, abord the request.
4. Try again to display the product.
5. It shows Error 500 (on the whole website, even admin).

In the event that you cannot reproduce...

A cache miss should never make a request fail.

Maybe a fix would be on this line :
https://github.com/odoo/odoo/blob/c725c3fbb29eff49eff3794aff9d407175599e63/odoo/fields.py#L1107

```python
                    except (AccessError, MissingError, CacheMiss):
```

Unless it was supposed to be caught earlier.

Please note that I only checked the code for 5 minutes and I've never looked at Odoo's codebase before, so I might be wrong.

# Current behavior:

Website is crashed (constant 500).

# Expected behavior:

Website does not crash.

# Video/Screenshot link (optional):

## Traceback

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 594
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(594,).list_price'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_2057>", line 8, in template_2057
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py", line 9, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py", line 17, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py", line 171, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/mnt/extra-addons/variant_price_system/models/product_template.py", line 84, in _get_combination_info
    list_price = product.price_compute('list_price')[product.id]
  File "/mnt/extra-addons/variant_price_system/models/product_product.py", line 30, in price_compute
    prices[product.id] = product[price_type] or 0.0
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5885, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1252, in compute_value
    fields = records.pool.field_computed[self]
KeyError: product.product.list_price
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 811, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 352, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1255, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1975, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 433, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1983, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 289, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 811, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 352, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1255, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1975, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 433, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1983, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 289, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
odoo.addons.base.models.qweb.QWebException: product.product.list_price
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 594
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(594,).list_price'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_2057>", line 8, in template_2057
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py", line 9, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py", line 17, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py", line 171, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/mnt/extra-addons/variant_price_system/models/product_template.py", line 84, in _get_combination_info
    list_price = product.price_compute('list_price')[product.id]
  File "/mnt/extra-addons/variant_price_system/models/product_product.py", line 30, in price_compute
    prices[product.id] = product[price_type] or 0.0
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5885, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1252, in compute_value
    fields = records.pool.field_computed[self]
KeyError: product.product.list_price
Error when render the template
KeyError: product.product.list_price
Template: 2057
Path: /t/t[2]
Node: <t t-set="combination_info" t-value="product._get_combination_info(combination, add_qty=add_qty or 1, pricelist=pricelist)"/>
```

</details>

![image](https://user-images.githubusercontent.com/13810199/180281969-e3581792-1e52-4f63-a24b-784f12511045.png)

# Support ticket number submitted via odoo.com/help (optional):

**Comment by Mulugruntz** [comment]
To be noted that every page of the server are now down.

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.company(1,).vat'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1725>", line 8, in template_1725
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py", line 9, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py", line 17, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py", line 186, in _get_combination_info
    fpos = self.env['account.fiscal.position'].sudo().get_fiscal_position(partner.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/partner.py", line 225, in get_fiscal_position
    if company.vat and partner.vat:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1252, in compute_value
    fields = records.pool.field_computed[self]
KeyError: res.company.vat
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 811, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 352, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1255, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1975, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 433, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1983, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 289, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 221, in render_template
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1730>", line 608, in template_1730
  File "<template_1730>", line 530, in t_call_content
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 811, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 352, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1255, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in render
    return env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1975, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 433, in _render
    return super(View, self)._render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1983, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 289, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 221, in render_template
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1730>", line 608, in template_1730
  File "<template_1730>", line 530, in t_call_content
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
odoo.addons.base.models.qweb.QWebException: res.company.vat
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.company(1,).vat'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1725>", line 8, in template_1725
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py", line 9, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py", line 17, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py", line 186, in _get_combination_info
    fpos = self.env['account.fiscal.position'].sudo().get_fiscal_position(partner.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/partner.py", line 225, in get_fiscal_position
    if company.vat and partner.vat:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1252, in compute_value
    fields = records.pool.field_computed[self]
KeyError: res.company.vat
Error when render the template
KeyError: res.company.vat
Template: website_sale.products_item
Path: /t/t[2]
Node: <t t-set="combination_info" t-value="product._get_combination_info(only_template=True, add_qty=add_qty or 1, pricelist=pricelist)"/>
```

</details>


And static images are still being served (`website.com/web/image/product.template/28/image_256/<name>?unique=8b1cc5e` -> it works)
