### ISSUE TITLE
website_sale_stock_wishlist gives Server Error but HTTP 200

### ISSUE THREAD

**Issue by Mulugruntz** [odoo/odoo#96504]
This contains 2 bugs in one ticket, because the error message reveals something more.

Impacted versions:
Odoo 15.0

Steps to reproduce:
Not sure, I went on a product with variants (front office), and selected different values for its variants.
I checked the requests with developer tools (Chrome) and found out this:

### Request Headers
<details>

```
POST /sale/get_combination_info_website HTTP/1.1
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 186
Content-Type: application/json
Cookie: ---
Host: xxx
Origin: xxx
Referer: xxx/shop/prefa-lettre-chiffre-nombre-mot-13
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36
X-Requested-With: XMLHttpRequest
```

</details>

### Response Headers

<details>

```
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 4085
Set-Cookie: session_id=xxx; Expires=Wed, 19-Oct-2022 18:39:06 GMT; Max-Age=7776000; HttpOnly; Path=/
Server: Werkzeug/1.0.1 Python/3.9.2
Date: Thu, 21 Jul 2022 18:39:06 GMT
```

</details>

### Response Body

<details>

```
{
    "jsonrpc": "2.0",
    "id": 307570838,
    "error": {
        "code": 200,
        "message": "Odoo Server Error",
        "data": {
            "name": "builtins.TypeError",
            "debug": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py\", line 237, in _dispatch\n    result = request.dispatch()\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 688, in dispatch\n    result = self._call_function(**self.params)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 360, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 94, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 349, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 917, in __call__\n    return self.method(*args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 536, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/controllers/variant.py\", line 13, in get_combination_info_website\n    return super().get_combination_info_website(product_template_id, product_id, combination, add_qty, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 536, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/controllers/variant.py\", line 13, in get_combination_info_website\n    return super(WebsiteSaleStockVariantController, self).get_combination_info_website(product_template_id, product_id, combination, add_qty, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 536, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/variant.py\", line 16, in get_combination_info_website\n    combination = self.get_combination_info(product_template_id, product_id, combination, add_qty, request.website.get_current_pricelist(), **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 536, in response_wrap\n    response = f(*args, **kw)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/sale/controllers/variant.py\", line 17, in get_combination_info\n    res = product_template._get_combination_info(combination, int(product_id or 0), int(add_qty or 1), pricelist)\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py\", line 9, in _get_combination_info\n    combination_info = super(ProductTemplate, self)._get_combination_info(\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py\", line 17, in _get_combination_info\n    combination_info = super(ProductTemplate, self)._get_combination_info(\n  File \"/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py\", line 171, in _get_combination_info\n    combination_info = super(ProductTemplate, self)._get_combination_info(\n  File \"/mnt/extra-addons/variant_price_system/models/product_template.py\", line 99, in _get_combination_info\n    combination_name = combination._get_combination_name()\n  File \"/usr/lib/python3/dist-packages/odoo/addons/product/models/product_attribute.py\", line 562, in _get_combination_name\n    return \", \".join([ptav.name for ptav in ptavs])\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 644, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 302, in _handle_exception\n    raise exception.with_traceback(None) from new_cause\nTypeError: sequence item 2: expected str instance, bool found\n",
            "message": "sequence item 2: expected str instance, bool found",
            "arguments": [
                "sequence item 2: expected str instance, bool found"
            ],
            "context": {}
        }
    }
}
```

Cleaned up traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/controllers/variant.py", line 13, in get_combination_info_website
    return super().get_combination_info_website(product_template_id, product_id, combination, add_qty, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/controllers/variant.py", line 13, in get_combination_info_website
    return super(WebsiteSaleStockVariantController, self).get_combination_info_website(product_template_id, product_id, combination, add_qty, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/variant.py", line 16, in get_combination_info_website
    combination = self.get_combination_info(product_template_id, product_id, combination, add_qty, request.website.get_current_pricelist(), **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/controllers/variant.py", line 17, in get_combination_info
    res = product_template._get_combination_info(combination, int(product_id or 0), int(add_qty or 1), pricelist)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock_wishlist/models/product_template.py", line 9, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/product_template.py", line 17, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/product_template.py", line 171, in _get_combination_info
    combination_info = super(ProductTemplate, self)._get_combination_info(
  File "/mnt/extra-addons/variant_price_system/models/product_template.py", line 99, in _get_combination_info
    combination_name = combination._get_combination_name()
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_attribute.py", line 562, in _get_combination_name
    return ", ".join([ptav.name for ptav in ptavs])
    Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
    TypeError: sequence item 2: expected str instance, bool found
```

</details>

Current behavior:

* Bug 1:
    * `HTTP/1.0 200 OK`
    * `"error": {"code": 200, "message": "Odoo Server Error", ...}`
* Bug 2:
    * `ProductTemplateAttributeValue.name` is supposed to be a `str`, but it seems that one of them contains a `bool`.
    * https://github.com/odoo/odoo/blob/6df87657db1da6212ca439354a83b52f355fdace/addons/product/models/product_attribute.py#L434
    * The end of the traceback: https://github.com/odoo/odoo/blob/6df87657db1da6212ca439354a83b52f355fdace/addons/product/models/product_attribute.py#L559-L563

Expected behavior:

* Bug 1: Either a 200 with a correct data. Or a 500 with a Server Error.
* Bug 2: Correct types.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by monty241** [comment]
Possibly related to #183636
