### ISSUE TITLE
[7.0][hr_wage_increment]: Error when "Individual" Wage Adjustment is clicked 

### ISSUE THREAD

**Issue by newmanx** [odoo/odoo#9677]
I am running openerp 7.0 latest, installed wage_increment along with its dependencies, but when i click on wage adjustment >> Individual, i get below error:

And this are from the /var/log/openerp/openerp-server.log

2015-11-19 16:35:02,425 961 ERROR finaltest openerp.sql_db: Programming error: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
, in query SELECT hr_employee."contract_id",hr_employee."resource_id",hr_employee.id FROM "hr_employee" WHERE hr_employee.id IN %s ORDER BY name_related
2015-11-19 16:35:02,426 961 ERROR finaltest openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
defaults[f] = self._defaultsf
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 185, in _get_effective_date
contract_id = self._get_contract_id(cr, uid, context=context)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 172, in _get_contract_id
data = self._get_contract_data(cr, uid, ['id'], context)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 160, in _get_contract_data
cr, uid, employee_id, ['contract_id'], context=context)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
result = self._read_flat(cr, user, select, fields, context, load)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
cr.execute(query, [tuple(sub_ids)] + rule_params)
File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
return f(self, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

2015-11-19 16:35:02,426 961 ERROR finaltest openerp.netsvc: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
result = ExportService.getService(service_name).dispatch(method, params)
File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
res = fn(db, uid, params)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
return self.execute(db, uid, obj, method, *args, *kw or {})
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
defaults[f] = self._defaultsf
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 185, in _get_effective_date
contract_id = self._get_contract_id(cr, uid, context=context)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 172, in _get_contract_id
data = self._get_contract_data(cr, uid, ['id'], context)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 160, in _get_contract_data
cr, uid, employee_id, ['contract_id'], context=context)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
result = self._read_flat(cr, user, select, fields, context, load)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
cr.execute(query, [tuple(sub_ids)] + rule_params)
File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
return f(self, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by antonylesuisse** [comment]
wage_increment is an external app.
