### ISSUE TITLE
JSONDecodeError on google Calendar Synch

### ISSUE THREAD

**Issue by gorjuce** [odoo/odoo#9682]
Hi,
I cannot synch my calendar with Google Calendar with my Odoo 8 instance. It's well configured but each time I click on the synch button I get:

Traceback (most recent call last):
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 605, in synchronize_events
    res = self.update_events(cr, user_to_sync, lastSync, context)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 879, in update_events
    error = simplejson.loads(e.read())
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JKE-be** [comment]
Hello, could you try to change YOUR line 879 from google_calendar.py with 
    error_key = simplejson.loads(str(e) or [])
(maybe google is returning an empty response and not a json)

Ps, seems like your code is not uptodate... because it is not the same line that in last version: https://github.com/odoo/odoo/blob/8.0/addons/google_calendar/google_calendar.py#L879
vs
https://github.com/odoo/odoo/blob/8.0/addons/google_calendar/google_calendar.py#L718

If it doesn't work with this change, could you print the e to know what google is returning.

Hard to debug it, if we can not reproduce the bug... And without your calendar we cannot understand what google is returning and why ...

Let us know what's append with this change... !

**Comment by gorjuce** [comment]
Hello,
thanks for reactivity.
I've updated the code and unfortunately it's seems the bug is deported to another point as described in the traceback.

Traceback (most recent call last):
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return gc_obj.synchronize_events(request.cr, request.uid, [], context=kw.get('local_context'))
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 577, in synchronize_events
    st, current_google, ask_time = self.get_calendar_primary_id(cr, user_to_sync, context=context)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 292, in get_calendar_primary_id
    'access_token': self.get_token(cr, uid, context)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 920, in get_token
    self.do_refresh_token(cr, uid, context=context)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_calendar/google_calendar.py", line 932, in do_refresh_token
    all_token = gs_pool._refresh_google_token_json(cr, uid, current_user.google_calendar_rtoken, self.STR_SERVICE, context=context)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/mfianalytics/mfianalytics/parts/odoo/addons/google_account/google_account.py", line 126, in _refresh_google_token_json
    error_key = simplejson.loads(e.read()).get("error", "nc")
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-i686.egg/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-i686.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/srv/openerp/eggs/simplejson-3.5.3-py2.7-linux-i686.egg/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JKE-be** [comment]
Can you print this var "e" before the simplejson.load, because it's very strange...
Can you reproduce the bug with a new calendar ? i will be interested to investigate it on my computer... that will be more easy :)

**Comment by gorjuce** [comment]
Yep I'll give you the "e" on tomorrow morning. It would be great if you reproduce cause I did not on runbot. The strange fact is my odoo code is up to date and I have no custom modules which can affect the result.

**Comment by gorjuce** [comment]
I've found the problem.
The parameter  "web.base.url" was not the correct url.
Updating this parameter with the right url fixe the issue.
Thanks for your help.

**Comment by JKE-be** [comment]
Nice !
Thank You for the feed-back !

I try asap to catch the exception to have a more explicit error !

Jeremy Kersten (JKE)

**Comment by gorjuce** [comment]
Welcome Jeremy,
I get a 410 code now each time I synch (I did not have this behavior when I fixed the issue)
Strange ...
