### ISSUE TITLE
[9.0] There are some problem in my E-commerce modules about performance,cron job,transaction

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9683]
Impacted versions:
- 9.0

I has developed E-commerce modules beas on Odoo one year,integrate into Amazon Wish EMS ALiexpress API.
There are some bug i has reported or not.
Now,I deploy my odoo on aliyun cloud server.(16cores 32GB 10MB)
That's Performance is disillusionary。
1. The Cron Job Lock
   There are many cron job of shop for listing,order,sqs,bidding... sync
   ![qq 20151123154555](https://cloud.githubusercontent.com/assets/11750796/11331820/9f535a6c-91fa-11e5-8a7a-51c8842bc3fc.png)
   Every Time I upgrade modules,The job locks transaction
   I must restart my odoo,kill all cron job thread
   My solution is :
   ir_cron.py 
   def _acquire_job
   cr.execute("SELECT id FROM ir_module_module WHERE state='to upgrade'")
           if cr.fetchone():
               _logger.info('The modules is to upgrade')
               return 
   Some jobs execute continually 
2. Performance
   my cloud server is 32G 16cores 10M
   openerp-server.conf
   [options]
   addons_path =./eking,./bobi
   admin_passwd = admin
   db_host = localhost
   db_maxconn = 400
   db_password = odoo
   db_port = 5432
   db_user = odoo
   limit_memory_hard = 5368709120
   limit_memory_soft = 4294967296
   limit_request = 10240
   limit_time_cpu = 86400
   limit_time_real = 86400
   log_level = info
   max_cron_threads = 8
   production = off
   proxy_mode = False
   redis_ip = localhost
   redis_port = 6379
   workers = 8

DB is only 30MB,but dbscan is hundreds thousand every seconds.There are only 20 users.
product_template is only 2000 items,but when i browse them on kanban,that cost usually at least 5sec to load the 40 items.
1.  Transaction rollback error

2015-11-23 07:35:48,579 11753 INFO odoo9 openerp.sql_db: bad query: UPDATE "eking_plisting" SET "asin"=NULL,"uri"='d856e4ba5c0e6c6be9d367c61e1f5d31.jpg',"write_uid"=12,"write_date"=(now() at time zone 'UTC') WHERE id IN (886)
2015-11-23 07:35:48,580 11753 INFO odoo9 openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4769 sec...
2015-11-23 07:35:49,060 11753 INFO odoo9 openerp.sql_db: bad query: UPDATE "eking_plisting" SET "asin"=NULL,"uri"='d856e4ba5c0e6c6be9d367c61e1f5d31.jpg',"write_uid"=12,"write_date"=(now() at time zone 'UTC') WHERE id IN (886)
2015-11-23 07:35:49,060 11753 ERROR odoo9 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo9/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo9/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo9/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo9/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/odoo9/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo9/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo9/openerp/addons/web/controllers/main.py", line 965, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo9/openerp/addons/web/controllers/main.py", line 957, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/odoo9/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo9/openerp/addons/web/controllers/main.py", line 956, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo9/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo9/eking/eking_product/models/product.py", line 1652, in write
    res = super(eking_plisting, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo9/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo9/openerp/addons/mail/models/mail_thread.py", line 276, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo9/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo9/openerp/models.py", line 3817, in write
    self._write(old_vals)
  File "/opt/odoo9/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo9/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo9/openerp/models.py", line 3929, in _write
    cr.execute(query, params + (sub_ids,))
  File "/opt/odoo9/openerp/sql_db.py", line 139, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo9/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
InternalError: 错误:  当前事务被终止, 事务块结束之前的查询被忽略

If update or select db frequently,I can't avoid there are some job to use same table data at same time.

I think odoo's erp function and support is very powerful. Now i can't find why so slow.Maybe my configuration is worry

I develop them just for myself, I use it to access the ecommerce platform 

My English is very poor.
I can contribute my code  ,if you can help me to solve there problems.
Thanks.

**Comment by JKE-be** [comment]
I cannot reproduce ! 
If you can reproduce it on v8, v9 or v10, please open a new ticket.

**Comment by galch99** [comment]
may this parameter was wrong max_cron_threads = 8 
workers have 8 worker+1 cron
