### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by gertcuykens** [odoo/odoo#97283]
I know the latest versions I am using isn't supported but I just hope you are aware of it and hopefully addressed in 16.0, thanks

Impacted versions: 15.0 

Steps to reproduce:
OSX 12.5
Postgres 14.4
Python 3.10.5
psycopg2  2.9.3
Stop odoo with keyboard interupt

Current behavior:

```log
2022-08-01 23:47:04,362 91610 INFO odoo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
Exception in thread odoo.service.cron.cron1:
Exception in thread odoo.service.cron.cron0:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/gert/odoo/odoo/service/server.py", line 443, in cron_thread
2022-08-01 23:47:04,666 91610 INFO odoo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
  File "/Users/gert/odoo/odoo/service/server.py", line 443, in cron_thread
    select.select([pg_conn], [], [], SLEEP_INTERVAL + number)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    select.select([pg_conn], [], [], SLEEP_INTERVAL + number)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

(odoo-venv) ~/Desktop/odoo-venv master % 
```

Expected behavior:

Clean exit

**Comment by 8191** [comment]
Still exists in lastest 17
