### ISSUE TITLE
[9.0] **Can not validate a Repair Order - ProgrammingError: can't adapt type 'account.tax'**

### ISSUE THREAD

**Issue by pgu42** [odoo/odoo#9730]
**Can not validate a Repair Order when 'To Bill' is checked**

Impacted versions:
- 9.0

Steps to reproduce:
1. Install "Repair" module
2. Create a Repair order and select a customer
3. On 'Operation' tab select 'add' on 'Operation Type', select a product and check 'To bill'
4. validate the Repair order

Current behavior: Odoo Server Error (ProgrammingError: can't adapt type 'account.tax')

Traceback (most recent call last):
  File "/openerp/openerp-server/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/openerp/openerp-server/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/openerp/openerp-server/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/openerp/openerp-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/openerp/openerp-server/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/openerp/openerp-server/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/openerp/openerp-server/addons/web/controllers/main.py", line 971, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/openerp/openerp-server/addons/web/controllers/main.py", line 963, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 327, in old_api
    result = method(recs, _args, *_kwargs)
  File "/openerp/openerp-server/addons/mail/models/mail_thread.py", line 230, in create
    thread = super(MailThread, self).create(values)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4125, in create
    record = self.browse(self._create(old_vals))
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4331, in _create
    cr, user, ids, fields2, context)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4469, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/openerp/openerp-server/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/openerp/openerp-server/addons/mrp_repair/mrp_repair.py", line 55, in _amount_tax
    tax_calculate = tax_obj.compute_all(cr, uid, line.tax_id, line.price_unit, cur, line.product_uom_qty, line.product_id.id, repair.partner_id.id)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/addons/account/models/account.py", line 676, in compute_all
    return recs.compute_all(price_unit, currency, quantity, product, partner)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/addons/account/models/account.py", line 612, in compute_all
    company_id = self[0].company_id
  File "/openerp/openerp-server/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/openerp/openerp-server/openerp/fields.py", line 905, in determine_value
    record._prefetch_field(self)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3273, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3203, in read
    self._read_from_database(stored, inherited)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3341, in _read_from_database
    cr.execute(query_str, params)
  File "/openerp/openerp-server/openerp/sql_db.py", line 139, in wrapper
    return f(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'account.tax'

Expected behavior:
- Repair order validated

**Comment by flotho** [comment]
Hi,

I have exactly the same issue.
Personnaly, without VAT, no problems
Additionally, I tried many things to patch this and to override the mrp.repair without success.

**Comment by flotho** [comment]
Additionnaly there is a problem in the code. The line price_subtotal is supposed to be VAT excluded but that's the VAT included that is used. So in the repair order it doesn't give the correct amounts.

regards

**Comment by bluestingray** [comment]
I'm getting the same issue with my tests.

**Comment by ges7** [comment]
Same issue here.

**Comment by Yenthe666** [comment]
Hi all,

I've just tried to reproduce this on the latest Odoo V9 and it seems to work fine out of the box. I was able to go through all steps of a repair order:
![image](https://user-images.githubusercontent.com/6352350/36200568-6cb6ff8c-117d-11e8-9f6d-89cea955dafe.png)
If you still face this issue then please update your Odoo source code and try again.

Regards,
Yenthe
