### ISSUE TITLE
[9.0] simplejson not included in dependencies

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#9734]
Commit: 6fd7fc9643932e238ba9211405053c5cb3a387e3

After installing a fresh instance of odoo, using pip install -r requirements.txt doesn't install simplejson, then odoo server crashes after when trying to load:
```
2015-11-25 10:05:12,202 24204 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/Users/aristobulo/eezee-it/projects/MQX/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/Users/aristobulo/eezee-it/projects/MQX/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/http.py", line 1415, in __call__
    self.load_addons()
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/http.py", line 1436, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/odoo/community/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/mqx/addons-community/eezee-it/community_edi/__init__.py", line 23, in <module>
    import edi_system
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/mqx/addons-community/eezee-it/community_edi/edi_system.py", line 2, in <module>
    from edi_serializer import serializer
  File "/Users/aristobulo/eezee-it/projects/MQX/parts/mqx/addons-community/eezee-it/community_edi/edi_serializer.py", line 8, in <module>
    import simplejson
ImportError: No module named simplejson
```

Simplejson is not present in requirements.txt file.

**Comment by xmo-odoo** [comment]
`simplejson` was removed in 9.0 at the community's behest (by #6940), since 9.0 (and 8.0 IIRC) depend on Python 2.7 which has a suitable stdlib `json` package.
