### ISSUE TITLE
[9.0] ERROR openerp.addons.website.models.ir_http: 500 Internal Server Error: after logout from odoo

### ISSUE THREAD

**Issue by Dilip97242** [odoo/odoo#9755]
hi

i am using odoo v9 comm. in ubuntu 14.04 installation is perfectly done after all works

but when i install eCommerce module of odoo and after when i log out from odoo it show following error
<pre>
2015-11-26 09:42:28,524 31671 INFO testenrp werkzeug: 127.0.0.1 - - [26/Nov/2015 09:42:28] "GET /web/session/logout?redirect=/ HTTP/1.1" 303 -
2015-11-26 09:42:28,684 31671 ERROR testenrp openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/dilip/workspace/90_enterprise/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 737, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/dilip/workspace/90_enterprise/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 768, in dispatch
    r = self._call_function(**self.params)
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dilip/workspace/90_enterprise/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "/home/dilip/workspace/90_enterprise/openerp/http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website/controllers/main.py", line 44, in index
    return request.registry['ir.http'].reroute(first_menu.url)
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website/models/ir_http.py", line 209, in reroute
    return self._dispatch()
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website/models/ir_http.py", line 175, in _dispatch
    key = self.get_page_key()
  File "/home/dilip/workspace/90_enterprise/openerp/addons/website/models/ir_http.py", line 94, in get_page_key
    return (self._name, "cache", request.uid, request.lang, request.httprequest.full_path)
AttributeError: 'Request' object has no attribute 'full_path'</pre>

it does only when i install ecommerce module otherwise it redirect to login page so how can i solve this.

**Comment by antonylesuisse** [comment]
I think it's a werkzeug issue, you should upgrade werkzeug.

**Comment by antonylesuisse** [comment]
@xmo-odoo Which version is required ?

**Comment by xmo-odoo** [comment]
@antonylesuisse 0.9 (we pin 0.9.6)

**Comment by Dilip97242** [comment]
My installed Werkzeug version,
<pre>Werkzeug (0.8.3)</pre>

and my ubuntu version details,
<pre>
$ uname -a
Linux dilip-Lenovo-G585 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 athlon i686 GNU/Linux</pre>

Thanks

**Comment by antonylesuisse** [comment]
You should upgrade to .9 or above. Try "pip install werkzeug"
