### ISSUE TITLE
Changing a user-defined standard value with umlauts results in an error message 

### ISSUE THREAD

**Issue by jholze** [odoo/odoo#978]
Changing or creating user-defined standard value with umlauts results in an error message. (copied issues from launchpad https://bugs.launchpad.net/openobject-addons/+bug/1306541 ) 

Impacted Versions:
- 7.0 and above
## Steps to reproduce.
1. Go to settings => Technical => Actions => User-defined defaults
2. Try to create new user-defined standard or change in comment field.
3. write german umlaute (ä, ö, ü) or any special character like 'Á' gives error following traceback.

please confirm it and give high priority as its blocking points.
### Traceback:

Server Traceback (most recent call last):
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/addons/audittrail/audittrail.py", line 524, in execute_cr
    return fct_src(cr, uid, model, method, _args, *_kw)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/orm.py", line 4546, in create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/fields.py", line 1159, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/addons/base/ir/ir_values.py", line 125, in _value_pickle
    self.write(cursor, user, id, {name[:-9]: value}, context=ctx)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/osv/orm.py", line 4226, in write
    'where id IN %s', upd1 + [sub_ids])
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/odoo/runbot/static/openerp-dev-7-0-30742/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
DataError: invalid byte sequence for encoding "UTF8": 0xc1 0x0a

**Comment by Yenthe666** [comment]
Hi @jholze ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
