### ISSUE TITLE
[14.0] mrp is causing js error in stock picking

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#97814]
Impacted versions:[14.0]

Steps to reproduce:
Define picking operations type 
type: incoming
use_existing_lots: true
Create new picking for this type
push button to assing lots on any stock_move with trazable product
try to assing an existing lot on move_line

Current behavior:
js traceback (It does not happen if show_operations in picking type is set as true. Selecting lots directly on lines without using the button goes right
Traza:
**Error: KeyError: 'raw_material_production_id'**
    at F.__getitem__ (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:354:161)
    at F.__getattr__ (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:355:69)
    at F.__getattribute__ (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:147:38)
    at py.PY_getAttr (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:111:176)
    at py.evaluate (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:217:11)
    at py.evaluate (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:215:194)
    at py.eval (http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:219:284)
    at http://51.255.69.39:8869/web/content/35914-95cfc77/web.assets_backend.js:362:110
    at iterator (http://51.255.69.39:8869/web/content/35897-0c41bf8/web.assets_common.js:110:183)
    at Function.<anonymous> (http://51.255.69.39:8869/web/content/35897-0c41bf8/web.assets_common.js:113:8)

Expected behavior:
Not to obtain any error but to be able to select an existing lot

CLUES TO SOLVE THE BUG:
https://github.com/odoo/odoo/blob/14.0/addons/mrp/views/stock_move_views.xml#L50

 'active_mo_id': parent.raw_material_production_id, --> active_mo_id is only informed if stock_move_line comes from an MO. Otherwise is null, so we think this is causing the error. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/186591/183666392-099670cf-9f5e-4649-9f45-47e41382459f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by mde-spring** [comment]
Same things in v15

The field raw_material_production_id is missing in the view stock.view_stock_move_operations.
By this way (from inventory, display detailed ope), the view mrp.view_stock_move_operations_raw seems not to be loaded (due to primary mode ?). 

My workaround is to inherit view_stock_move_operations for adding the field.

My odoo help ticket: 2952239

**Comment by mde-spring** [comment]
Seems corrected with issue #97071
