### ISSUE TITLE
[9.0][INCOMMING MAIL]Odoo can't root alias that point to alias

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#9795]
I create a catchall email "catchall@mydomain.com"
I create two alias that point to catchall@mydomain.com:
- "alias1@mydomain.com"
- "alias2@mydomain.com"

The aim of this two alias is to create opportunity for two sale team "team1" and "team2".
I then create a alias "allsaleteam@mydomain.com". My aim here is that all mail send to this alias create a apportunity in the two sale teams. So in my provider admin dashboard I create alias "allsaleteam@mydomain.com" that point to "alias1@mydomain.com" and "alias2@mydomain.com".

Sending mail to "alias1@mydomain.com" and "alias2@mydomain.com" works like a charm.
But when I send a email to alias "allsaleteam@mydomain.com" I got the following error:

2015-11-27 20:53:07,023 6115 INFO db_MYDB openerp.addons.fetchmail.fetchmail: Failed to process mail from imap server PROVIDER.
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/fetchmail/fetchmail.py", line 194, in fetch_mail
    context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 342, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 1175, in message_process
    routes = self.message_route(msg_txt, msg, model, thread_id, custom_values)
  File "/opt/odoo/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 1065, in message_route
    update_author=True, assert_model=True)
  File "/opt/odoo/odoo/openerp/api.py", line 236, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 816, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-11-27 20:53:07,028 6115 INFO MYDB openerp.addons.fetchmail.fetchmail: Fetched 2 email(s) on imap server MYPROVIDER; 0 succeeded, 2 failed.

**Comment by pedrobaeza** [comment]
This is because there's no default action configured on incoming mail server, like create a lead. Closing as no real bug.
