### ISSUE TITLE
[9.0e] UPS Shipping will crash when product weight is zero,

### ISSUE THREAD

**Issue by spadae22** [odoo/odoo#9801]
Hi,
Product weight needs to be greater than zero. Actually UPS has a min weight for certain packages so you could let UPS API return the default since they do change it. I would make it so if the product is 'stockable' do not allow zero weight when creating the product. Here is the traceback:
```
Traceback (most recent call last):
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 600, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 637, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 888, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-9.0e-20151128/openerp/http.py", line 466, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/web/controllers/main.py", line 993, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/web/controllers/main.py", line 985, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/mail/models/mail_thread.py", line 276, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/models.py", line 3819, in write
    self._write(old_vals)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 562, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/models.py", line 4079, in _write
    recs.recompute()
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/models.py", line 5823, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/home/odoo/odoo-9.0e-20151128/openerp/models.py", line 5823, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/home/odoo/odoo-9.0e-20151128/openerp/models.py", line 5710, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 889, in determine_value
    self.compute_value(recs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 869, in compute_value
    self._compute_value(records)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 859, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/delivery/models/sale_order.py", line 25, in _compute_delivery_price
    order.delivery_price = order.carrier_id.with_context(order_id=order.id).price
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 914, in determine_value
    self.compute_value(recs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 869, in compute_value
    self._compute_value(records)
  File "/home/odoo/odoo-9.0e-20151128/openerp/fields.py", line 859, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-9.0e-20151128/openerp/api.py", line 413, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/delivery/models/delivery_carrier.py", line 78, in get_price
    self.price = self.get_shipping_price_from_so(order)[0]
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/delivery/models/delivery_carrier.py", line 111, in get_shipping_price_from_so
    return getattr(self, '%s_get_shipping_price_from_so' % self.delivery_type)(orders)
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/delivery_ups/models/delivery_ups.py", line 62, in ups_get_shipping_price_from_so
    packages.append(Package(self, total_weight))
  File "/home/odoo/odoo-9.0e-20151128/openerp/addons/delivery_ups/models/ups_request.py", line 101, in __init__
    assert weight > 0
AssertionError

```

**Comment by rim-odoo** [comment]
The crash has been removed at https://github.com/odoo/enterprise/commit/7ecef3c57ab7a60a4bcf5a32ed98ed46010a42a8 (it will be forwardported in 9.0 soon).
We are working to add min weight support to a future version.
Thanks.
