### ISSUE TITLE
group by many2many field (projects, My tasks)

### ISSUE THREAD

**Issue by otahmasebi** [odoo/odoo#98127]
Impacted versions:15.0

Steps to reproduce: in the project module, create a project with some tasks, go to it's tasks view and group them by `Personal Stage` , Or go to `My Tasks`. 

Current behavior:
you will get this error:
```Traceback (most recent call last):
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/otahmasebi/PycharmProjects/odoo/addons/web/controllers/main.py", line 1305, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/otahmasebi/PycharmProjects/odoo/addons/web/controllers/main.py", line 1324, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/home/otahmasebi/PycharmProjects/odoo/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/models.py", line 5033, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/models.py", line 1811, in search
    return res if count else self.browse(res)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/models.py", line 5165, in browse
    if not ids:
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/osv/query.py", line 215, in __bool__
    return bool(self._result)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/osv/query.py", line 208, in _result
    self._cr.execute(query_str, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/otahmasebi/PycharmProjects/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "Inbox"
LINE 5: ...task__personal_stage_type_ids"."stage_id" IN (15, 'Inbox')
                                                             ^ ```

**Comment by otahmasebi** [comment]
I fixed it temporarily with this patch, I believe the problem is somewhere else.

```
--- addons/web/models/models.py	2022-08-13 20:13:26.356552481 +0430
+++ models.py	2022-08-13 20:12:05.640003980 +0430
@@ -59,6 +59,10 @@
             'length': number of records matching the domain (result of a call to 'search_count')
         }
         """
+        for filter in domain:
+            if isinstance(filter, list):
+                if filter[1] == "=" and isinstance(filter[2], list):
+                    filter[2] = filter[2][0]
         records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
         if not records:
             return {

```
