### ISSUE TITLE
Account_online_synchronization: Invalid field 'currency_code' 

### ISSUE THREAD

**Issue by belisac** [odoo/odoo#98210]
Impacted versions:
14.0
Steps to reproduce:
From Accounting >> Configuration >> Online Synchronization >> Fetch accounts
After put bank's credentials, the bank shows a message  that its OK (see 1.) ) and then Odoo shows the trackback (see 2.)  
Current behavior:
Odoo presents the trace back referring to the currency_code (see details at the end), 

Expected behavior:
Finish the Fetch account and see the wizard where it shows the accounts and I can choose a dairy  

Video/Screenshot link (optional):

1.) https://drive.google.com/file/d/1D4r3Ghi5i8lCcX8OApWhYQxAZTiixpT6/view?usp=sharing

2.) https://drive.google.com/file/d/1QjkooA_8wEElD8mlEhCoyda8dP06-OvQ/view?usp=sharing 

Support ticket number submitted via odoo.com/help (optional):
 Error en sincronización de Banco Sabadell (#2.942.816)

 The  issue maybe could be related with this change: https://github.com/odoo/enterprise/pull/29871

Thanks in advance for your attention

Regards,

Belisa

TRACEBACK

Error:

Odoo Server Error

 

Traceback (most recent call last):

  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch

    result = request.dispatch()

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 685, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 361, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 349, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 914, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 533, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1394, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1386, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 399, in call_kw

    result = _call_kw_multi(method, model, args, kwargs)

  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 386, in _call_kw_multi

    result = method(recs, *args, **kwargs)

  File "/opt/odoo/auto/addons/account_online_synchronization/models/account_online.py", line 404, in success

    return method()

  File "/opt/odoo/auto/addons/account_online_synchronization/models/account_online.py", line 426, in _success_link

    new_accounts = self._fetch_accounts()

  File "/opt/odoo/auto/addons/account_online_synchronization/models/account_online.py", line 358, in _fetch_accounts

    new_accounts = self.env['account.online.account'].create(accounts.values())

  File "<decorator-gen-64>", line 2, in create

  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi

    return create(self, arg)

  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create

    recs = super().create(vals_list)

  File "<decorator-gen-13>", line 2, in create

  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi

    return create(self, arg)

  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3833, in create

    raise ValueError("Invalid field %r on model %r" % (key, self._name))

Exception

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 641, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception

    raise exception.with_traceback(None) from new_cause

ValueError: Invalid field 'currency_code' on model 'account.online.account'

**Comment by vin-odoo** [comment]
Hello, to fix this issue you need to make sure that the account_online_sychronisation module is up to date.
Sorry for the inconvenience, have a great day.

**Comment by belisac** [comment]
Thank you @vin-odoo for your answer, I already did that, in fact I updated account_online_sychronization  and account , and I have the same traceback, what else can I do? 

Thanks in advance,

**Comment by sascha-seyfert** [comment]
We have exactly the same problem.

**Comment by csnauwaert** [comment]
Hello, @belisac @sascha-seyfert 
The problem is now solved. You don't have to do anything, just retry and it should work.

Best regards

**Comment by belisac** [comment]
Thanks @csnauwaert for your replay and solution,
I'll be checking with the Client and it doesn't go, I'll let you know

Regards!
