### ISSUE TITLE
[9.0][Project] date/time field value out of range: "2015-13-01"

### ISSUE THREAD

**Issue by hip-odoo** [odoo/odoo#9826]
Installing "Project" module gives following error on runbot:

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 600, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 637, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 888, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/http.py", line 466, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/web/controllers/main.py", line 982, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/web/controllers/main.py", line 970, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/base/ir/ir_model.py", line 1107, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/project/project.py", line 647, in create
    task_id = super(task, self).create(cr, uid, vals, context=create_context)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/mail/models/mail_thread.py", line 230, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/api.py", line 478, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/models.py", line 4270, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ParseError: "date/time field value out of range: "2015-13-01"
LINE 1: ... 'normal', 1, 'You can set a deadline on a task', '2015-13-0...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
" while parsing /home/odoo/runbot/extra/runbot/static/build/116444-9-0-fb2a54/openerp/addons/project/project_data.xml:293, near
```<record id="project_task_data_11" model="project.task">
            <field name="user_id" ref="base.user_root"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_data"/>
            <field name="name">You can set a deadline on a task</field>
            <field name="stage_id" ref="project_stage_data_1"/>
            <field name="date_deadline" eval="'2015-%s-01' %(datetime.now().month+1)"/>
        </record>```

**Comment by msh-odoo** [comment]
@hip-odoo This will be fixed in #9828 , you can close it
