### ISSUE TITLE
Error when run 'Check Action Rules' action from Scheduled Actions

### ISSUE THREAD

**Issue by fka-odoo** [odoo/odoo#9860]
9.0:

Steps to Reproduce:
1) Install hr_contract module.
2) Configured automation action of hr_contract from Automated Actions.
3) Create one contract which is near to expired or already expired
4) Now run the 'Check Action Rules' action from scheduled action to automatic triggered the automation action and getting following traceback in backend:
Video: https://www.dropbox.com/s/1bmxyjw2imgm5b8/tip.ogv?dl=0

_check
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/116626-8312-6c82b1/openerp/addons/base_action_rule/base_action_rule.py", line 445, in _check
    self._process(cr, uid, action, [record.id], context=context)
  File "/home/odoo/runbot/extra/runbot/static/build/116626-8312-6c82b1/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116626-8312-6c82b1/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/116626-8312-6c82b1/openerp/addons/base_action_rule/base_action_rule.py", line 180, in _process
    action_done = self._context['__action_done']
KeyError: '__action_done'

**Comment by osvalr** [comment]
I confirm this is happening

**Comment by osvalr** [comment]
This also applies in 10.0

**Comment by pedrobaeza** [comment]
Is this still happening? Please specify all the steps and data you input.

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
