### ISSUE TITLE
[delivery] no return statement for method delivery_set() on sale.order model

### ISSUE THREAD

**Issue by n1b0r** [odoo/odoo#987]
There is no return statement in the method delivery_set() on the sale.order model bring by the delivery module.

I used to have an xmlrpc script that force delivery method for sale orders, but since there is no more return statement, it returns None which is not compatible with xmlrpc :

> xmlrpclib.Fault: <Fault cannot marshal None unless allow_none is enabled

***Impacted versions:***

 - odoo branch 8.0

***Steps to reproduce:***

 1. Create a new order and set its carrier
 2. Call the delivery_set() method throught xmlrpc

***Current behavior:***

```python
 Traceback (most recent call last):
  File "testrpc_sale_order_delivery_set.py", line 11, in <module>
    ret = sock.execute(dbname, uid, pwd, 'sale.order', 'delivery_set', [order_id])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault cannot marshal None unless allow_none is enabled: 'Traceback (most recent call last):\n  File "/home/ubuntu/odoo/odoo/openerp/service/wsgi_server.py", line 76, in xmlrpc_return\n    response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 1085, in dumps\n    data = m.dumps(params)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 632, in dumps\n    dump(v, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump\n    f(self, value, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 658, in dump_nil\n    raise TypeError, "cannot marshal None unless allow_none is enabled"\nTypeError: cannot marshal None unless allow_none is enabled\n'>
```

***Expected behavior:***

```python
return True
```

**Comment by rim-odoo** [comment]
Pull requests in `master` version are welcome

**Comment by rim-odoo** [comment]
Fixed in master version at https://github.com/odoo/odoo/commit/dc043cf1bb4602fb298fca8b8d17765e3a6b93ff
