### ISSUE TITLE
[15.0] UncaughtPromiseError > TypeError Uncaught Promise > Cannot read properties of null (reading 'parentElement')

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#99268]
Impacted versions: 15.0ce

Steps to reproduce:
- In the list view -> right click Chrome tab -> duplicate
![image](https://user-images.githubusercontent.com/7898318/187580550-d161a15b-a713-46dc-99d9-804a36539a88.png)

Current behavior:
- Sometime the new tab does not  work well and have this error

`TypeError: Cannot read properties of null (reading 'parentElement')
    at Dropdown.onDropdownStateChanged (https://***.vn/web/assets/debug/web.assets_backend.js:3702:29) (/web/static/src/core/dropdown/dropdown.js:219)
    at EventBus.trigger (https://***.vn/web/assets/debug/web.assets_common.js:8715:30) (/web/static/lib/owl/owl.js:58)
    at AppsMenu.changeStateAndNotify (https://*****.vn/web/assets/debug/web.assets_backend.js:3631:22) (/web/static/src/core/dropdown/dropdown.js:148)
    at AppsMenu.close (https://*****.vn/web/assets/debug/web.assets_backend.js:3640:21) (/web/static/src/core/dropdown/dropdown.js:157)
    at AppsMenu.<anonymous> (https://*****.vn/web/assets/debug/web.assets_backend.js:137573:68) (/muk_web_theme/static/src/webclient/appsmenu/appsmenu.js:44)
    at EventBus.trigger (https://*****.vn/web/assets/debug/web.assets_common.js:8715:30) (/web/static/lib/owl/owl.js:58)
    at ControllerComponent.mounted (https://*****.vn/web/assets/debug/web.assets_backend.js:24509:25) (/web/static/src/webclient/actions/action_service.js:655)
    at ControllerComponent.__callMounted (https://*****.vn/web/assets/debug/web.assets_common.js:13052:18) (/web/static/lib/owl/owl.js:4395)
    at Fiber.complete (https://*****.vn/web/assets/debug/web.assets_common.js:12426:35) (/web/static/lib/owl/owl.js:3769)
    at https://*****.vn/web/assets/debug/web.assets_common.js:12154:40 (/web/static/lib/owl/owl.js:3497)`

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7898318/187580002-7eb29c5b-8314-4311-9c53-42da1e42681a.png)

Support ticket number submitted via odoo.com/help (optional):
N/A

**Comment by quyetvk** [comment]
Same issue!
