### ISSUE TITLE
Error al intentar crear un conduce en el módulo Flota - ValueError: Invalid field 'product_lot_id' on model 'stock.picking'

### ISSUE THREAD

**Issue by aperez-octagono** [odoo/odoo#99446]
Impacted versions:
14.0
------------------------------------->
Code:
        for tires in self.tires_set_ids:
            if not tires.product_id:
                raise ValidationError('Debe agregar por lo menos un neumatico!')
            # if not tires.stock_move_line_id:
            picking_vals = {
                'picking_type_id': picking_type_id.id,
                'product_id': tires.product_id,
                'product_lot_id': tires.product_lot_id,
                'location_id': picking_type_id.default_location_src_id.id,
                'location_dest_id': picking_type_id.default_location_dest_id.id,
                'move_type': 'direct',
            }
            picking_id = self.env['stock.picking'].create(picking_vals)
------------------------------------->
Error:
Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\web\controllers\main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\web\controllers\main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\users\cpere\desktop\odoo14\odoo14e\equiport\equiport_custom\models\fleet_vehicle.py", line 310, in button_validate
    self.action_stock_move()
  File "c:\users\cpere\desktop\odoo14\odoo14e\equiport\equiport_custom\models\fleet_vehicle.py", line 340, in action_stock_move
    picking_id = self.env['stock.picking'].create(picking_vals)
  File "<decorator-gen-222>", line 2, in create
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 326, in _model_create_single
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\stock\models\stock_picking.py", line 675, in create
    res = super(Picking, self).create(vals)
  File "<decorator-gen-135>", line 2, in create
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\mail\models\mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\addons\base\models\ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\models.py", line 3833, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0e.20220614\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'product_lot_id' on model 'stock.picking'

**Comment by niyasraphy** [comment]
traceback seems to have custom codes and most probably issue with custom modules, 
can you reproduce the same in odoo runbot ?
