### ISSUE TITLE
Error installing Project management

### ISSUE THREAD

**Issue by mschou** [odoo/odoo#9952]
When installing in december, Project management fails because of incorrect date in project_data.xml
Trying to import date 2015-13-01

ParseError: "date/time field value out of range: "2015-13-01"
LINE 1: ... 'normal', 1, 'You can set a deadline on a task', '2015-13-0...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
" while parsing /opt/odoo/odoo-server/addons/project/project_data.xml:293, near
<record id="project_task_data_11" model="project.task">
            <field name="user_id" ref="base.user_root"/>
            <field name="priority">0</field>
            <field name="project_id" ref="project.project_project_data"/>
            <field name="name">You can set a deadline on a task</field>
            <field name="stage_id" ref="project_stage_data_1"/>
            <field name="date_deadline" eval="'2015-%s-01' %(datetime.now().month+1)"/>
        </record>

**Comment by msh-odoo** [comment]
@mschou Fixed at [https://github.com/odoo/odoo/commit/0ee11f23f15ab11851baf3ca00d9c3a5947fe294] would you please try with updated code

**Comment by omer414** [comment]
@msh-odoo i am also having a similar issue on my enterprise edition. I started an issue #9831, which was closed later saying the issue has been solved. Now after pulling all the latest changes and restarting the server, i get this error. Can you point me where i might be going wrong. 

```
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 600, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 637, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 888, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 466, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/enterprise-addons/web/controllers/main.py", line 1238, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/opt/odoo/openerp/http.py", line 993, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_actions.py", line 370, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3191, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3226, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3417, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/openerp/addons/base/ir/ir_actions.py", line 312, in _search_view
    'search', context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 133, in fields_view_get
    res = super(module, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=False)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1566, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 878, in postprocess_and_fields
    fields = Model.fields_get(cr, user, None, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3137, in fields_get
    description = field.get_description(recs.env)
  File "/opt/odoo/openerp/fields.py", line 634, in get_description
    value = value(env)
  File "/opt/odoo/openerp/fields.py", line 664, in _description_string
    field_string = env['ir.translation'].get_field_string(model_name)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "<string>", line 2, in get_field_string
  File "/opt/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_translation.py", line 485, in get_field_string
    return {field.name: field.field_description for field in fields}
  File "/opt/odoo/openerp/addons/base/ir/ir_translation.py", line 485, in <dictcomp>
    return {field.name: field.field_description for field in fields}
  File "/opt/odoo/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/opt/odoo/openerp/fields.py", line 905, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3296, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3226, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3364, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_model_fields.store does not exist
LINE 1: ...ction","ir_model_fields"."relation" as "relation","ir_model_...
                                                             ^
```

**Comment by msh-odoo** [comment]
@omer414 you should check commit [https://github.com/odoo/odoo/commit/3f059d5edf9705af680914fcfd5b7a7472d33edb]

**Comment by JayVora-SerpentCS** [comment]
Should be closed, doesn't happen after the fix https://github.com/odoo/odoo/commit/0ee11f23f15ab11851baf3ca00d9c3a5947fe294
