### ISSUE TITLE
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#99809]
**Impacted versions:**

15

**Steps to reproduce:**

Using windows 10 as host machine.
Odoo 15 running on wsl2 debian sid.
Postgres runing on docker.
Downloaded odoo from github installed python requirements from txt file

**Current behavior:**

on startup:
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Issue is fixed if i downgrade cryptography  to 2.8

**Expected behavior:**

No problems

**Comment by Brawcks** [comment]
Updated pyopenssl to 22.0.0 to fix the issue

In standard requirements.txt : 

```text
pyopenssl==19.0.0 # BEFORE
pyopenssl==22.0.0 # AFTER
```

**Comment by pedrobaeza** [comment]
Related: #99829

**Comment by falahputra** [comment]
> Updated pyopenssl to 22.0.0 to fix the issue
> 
> In standard requirements.txt :
> 
> ```
> pyopenssl==19.0.0 # BEFORE
> pyopenssl==22.0.0 # AFTER
> ```

Thanks. Its work for me

**Comment by MiquelRForgeFlow** [comment]
This issue can be closed :)

**Comment by Samadeva** [comment]
Dear Yenthe,

First of all: thank you very much for your script, but using the recommendations in this page, I am still facing the same error.

I have installed odoo16 on Ubuntu 20.04 using Yenthe install-script at https://github.com/Yenthe666/InstallScript

The result of the launch command : ./odoo-bin -c /etc/sysb-server.conf
is:

    2022-11-11 15:09:01,324 23800 INFO ? odoo: addons paths: ['/odoo/odoo-server/odoo/addons', '/odoo/.local/share/Odoo/addons/16.0', '/odoo/enterprise/addons', '/odoo/odoo-server/addons']
    2022-11-11 15:09:01,324 23800 INFO ? odoo: database: default@default:default
    2022-11-11 15:09:01,799 23800 INFO ? odoo.addons.base.models.ir_actions_report: A package may be missing to print Data Matrix barcodes: pylibdmtx or libdmtx.
    2022-11-11 15:09:01,811 23800 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /bin/wkhtmltopdf
    2022-11-11 15:09:02,311 23800 CRITICAL ? odoo.modules.module: Could not load module web
    2022-11-11 15:09:02,311 23800 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
    2022-11-11 15:09:02,311 23800 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
    The `web` module is provided by the addons found in the `openerp-web` project.
    Maybe you forgot to add those addons in your addons_path configuration.
    Traceback (most recent call last):
      File "/odoo/odoo-server/odoo/service/server.py", line 1239, in load_server_wide_modules
        odoo.modules.module.load_openerp_module(m)
      File "/odoo/odoo-server/odoo/modules/module.py", line 432, in load_openerp_module
        __import__('odoo.addons.' + module_name)
      File "/odoo/odoo-server/addons/web/__init__.py", line 4, in <module>
        from . import controllers
      File "/odoo/odoo-server/addons/web/controllers/__init__.py", line 5, in <module>
        from . import database
      File "/odoo/odoo-server/addons/web/controllers/database.py", line 24, in <module>
        from odoo.addons.base.models.ir_qweb import render as qweb_render
      File "/odoo/odoo-server/odoo/addons/base/__init__.py", line 5, in <module>
        from . import models
      File "/odoo/odoo-server/odoo/addons/base/models/__init__.py", line 21, in <module>
        from . import ir_mail_server
      File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
        from OpenSSL import crypto as SSLCrypto
      File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
        class X509StoreFlags(object):
      File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
    2022-11-11 15:09:02,319 23800 CRITICAL ? odoo.modules.module: Couldn't load module base
    2022-11-11 15:09:02,319 23800 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
    2022-11-11 15:09:02,319 23800 ERROR ? odoo.service.server: Failed to load server-wide module `base`.

Using these recommendations: https://github.com/odoo/odoo/issues/99809, I have already tried to change the requirements file (pyopenssl==22.0.0 and cryptography==37.0.2):

    root@localhost:/sysb/sysb-server# sudo pip install -r /odoo/odoo-server/requirements.txt

Output:

    Installing collected packages: cryptography, pyopenssl
      Attempting uninstall: cryptography
        Found existing installation: cryptography 38.0.3
        Uninstalling cryptography-38.0.3:
          Successfully uninstalled cryptography-38.0.3
      Attempting uninstall: pyopenssl
        Found existing installation: pyOpenSSL 22.1.0
        Uninstalling pyOpenSSL-22.1.0:
          Successfully uninstalled pyOpenSSL-22.1.0
    Successfully installed cryptography-37.0.2 pyopenssl-20.0.1

But after re-launching odoo, the error still remains. Any idea please ?

**Comment by Samadeva** [comment]
I have eventually managed to find the compatible versions using the ones in odoo15's requirements.txt file:

    cryptography==2.6.1
    pyopenssl==19.0.0

And then re-install the requirements file on my server:

sudo pip install -r /sysb/sysb-server/requirements.txt

**Comment by Yenthe666** [comment]
Yes, it is an open issue depending on the Odoo version (it is an issue in their requirements.txt file actually)

**Comment by pleirb** [comment]
> cryptography==2.6.1
> pyopenssl==19.0.0



> 



> Or pin cryptography to:
> 
> ```
> cryptography<38
> ```
> 
> As, this is the lib introducing the breaking change with PyOpenSSL. Related: [pyca/pyopenssl#1114](https://github.com/pyca/pyopenssl/issues/1114)


Thank you so much! It worked for me! I got this error when installing pysftp and putting cryptography<38 fixed it. I am using doodba to run odoo 15

**Comment by colinstu12** [comment]
If this helps anyone else: running into a similar snag, urllib3 needed to be at 2.0.5, it was on 1.26.5 before and nothing seemed to be pointing this out.
