### ISSUE TITLE
html.Field copy errors v9

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#9996]
Enter some content in an html field. Copy/paste then proceed to delete with backspace.

Odoo v9, Version 9.saas~7e (Enterprise Edition), Windows 10
Chrome Version 47.0.2526.80 m
Firefox 42.0

Reportedly problem is not present on OSX
Chrome Version 47.0.2526.80 (64-bit)
Safary 9
OSX 10.11.1

firefox has error on paste:
```
TypeError: parent is null

http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6510
Traceback:
dom</wrap@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6510:224
range</WrappedRange/this.wrapBodyInlineWithPara@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6585:201
range</WrappedRange/this.insertNode@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6586:66
range</WrappedRange/this.pasteHTML/<@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6587:271
range</WrappedRange/this.pasteHTML@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6587:219
Editor/this.pasteHTML@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6650:1895
EventHandler/this.invoke@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6810:1499
Clipboard/pasteByHook@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6678:343
Clipboard/this.attach/</<@http://127.0.0.1:8069/web/content/304-ce4bd14/web.assets_backend.js:6677:533
```

Chrome on backspace:
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:843
Traceback:
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at getStyles (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:843:295)
    at curCSS (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:843:429)
    at Function.jQuery.extend.css (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:889:25)
    at http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:897:63
    at jQuery.access (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:704:51)
    at jQuery.fn.extend.css (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:895:153)
    at String.<anonymous> (http://127.0.0.1:8069/web/content/252-b57286e/web.assets_backend.js:5405:312)
    at Function.jQuery.extend.each (http://127.0.0.1:8069/web/content/249-813d132/web.assets_common.js:473:767)
    at jQueryCSS (http://127.0.0.1:8069/web/content/252-b57286e/web.assets_backend.js:5405:240)

```

**Comment by hackerwins** [comment]
If you find something wrong with summernote, please let me know.
https://github.com/summernote/summernote/issues

**Comment by InfernalLV** [comment]
I opened an issue on summernote repo as well detailing the reason for the chrome error
https://github.com/summernote/summernote/issues/1491 

The error occurs when in summernote/src/js/editing/Style.js $obj.css fails because $obj nodeType is comment.

`$obj == [ <!--StartFragment-->]`
```
    var jQueryCSS = function ($obj, propertyNames) {

      if (agent.jqueryVersion < 1.9) {
        var result = {};
        $.each(propertyNames, function (idx, propertyName) {
          result[propertyName] = $obj.css(propertyName);
        });
        return result;
      }
      return $obj.css.call($obj, propertyNames);
    };
```

**Comment by InfernalLV** [comment]
odoo\addons\web_editor\static\src\js\summernote.js
1369: summernote.pluginEvents.backspace = function...

```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
http://127.0.0.1:8069/web_editor/static/src/js/summernote.js:1502
Traceback:
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at $.summernote.pluginEvents.backspace (http://127.0.0.1:8069/web_editor/static/src/js/summernote.js:1502:118)
    at HTMLDivElement.<anonymous> (http://127.0.0.1:8069/web_editor/static/lib/summernote/src/js/EventHandler.js:382:13)
    at HTMLDivElement.jQuery.event.dispatch (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLDivElement.elemData.handle (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:4309:63)
```

**Comment by InfernalLV** [comment]
I made the offending methods return null in case their dealing with comment nodes.

@Gorash is there a timeframe for when this issue might be fixed? Or where would be the propper place to make summernote make not call the jQueryCSS function?

Since I can't reproduce the problem on summernotes website I'd assume the problem is to be found somewhere static/src/js.

summernote/src/js/editing/Style.js
```
    var jQueryCSS = function ($obj, propertyNames) {

        // console.log($obj)
        if ($obj.get(0).nodeType == 8) return null;
```

static\src\js\summernote.js
```
1369: summernote.pluginEvents.backspace = function...
...
...
    else if ((temp = dom.ancestorHavePreviousSibling(target)) && (temp2 = dom.hasContentBefore(temp)) && dom.isContentEditable(temp2)) {

        if (temp.nodeType == 8 || temp2.nodeType == 8) return null;*
       
        dom.removeSpace(temp2.parentNode, temp2, 0, temp, 0); // clean before jump for not select invisible space between 2 tag
        temp2 = dom.lastChild(temp2);
```

**Comment by Gorash** [comment]
Summernote only used for few part of the API, however their API changes all the time.
Functions that modify the dom are reimplemented because the behavior was different from a browser to another (and it takes a coherent dom for editing the site and for xpath without span automatically introduce)
I look for the bug but I have not locally.

**Comment by InfernalLV** [comment]
Heres a video demonstrating the bug on odoo.com 
http://youtu.be/1YB5OEU1HjI

**Comment by InfernalLV** [comment]
@Gorash did you manage to reproduce the error?

**Comment by Gorash** [comment]
I'have fixed some bugs bug I can't reproduce this bug. I'm installing a virtual machine with windows to try.

**Comment by InfernalLV** [comment]
Well if you need more specific informationor or if i can help in any other way feel free to ask. Managed to reproduce this over three different machines so far.

**Comment by Gorash** [comment]
I reproduce the bug with chrome 47 on windows. I create a branch and the bug is fixed but I'll testing for other cases. (new version of chrome add comment in the dom and some errors appear. I clean the dom because the editor is used for the website, email, mass_mailing... with xpath, css...)

**Comment by InfernalLV** [comment]
Try Firefox 42.0 on Windows
Just copy/paste and you should get a
TypeError: parent is null

You can see the full traceback in the 1st post

**Comment by Gorash** [comment]
Summernote have a different default comportment for paste content with firefox, I'll remove the condition and clean the dom. For ie, it's the default summernote feature.

**Comment by InfernalLV** [comment]
So I checked the branch Chrome seems to work fine. Though I got another one in FireFox.

1) Backspace to the beginning of some content
2) Hold for a while after all content is deleted
3) Error on keyup

Sometimes after the error I can't focus the field.

```

TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.

http://lido.its1.lv/web/static/lib/jquery/jquery.js:6118
Traceback:
getStyles@http://lido.its1.lv/web/static/lib/jquery/jquery.js:6118:24
curCSS@http://lido.its1.lv/web/static/lib/jquery/jquery.js:6125:1
.css@http://lido.its1.lv/web/static/lib/jquery/jquery.js:6718:31
.css/<@http://lido.its1.lv/web/static/lib/jquery/jquery.js:6867:33
jQuery.access@http://lido.its1.lv/web/static/lib/jquery/jquery.js:4153:34
.css@http://lido.its1.lv/web/static/lib/jquery/jquery.js:6849:1
Style/jQueryCSS/<@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/editing/Style.js:31:34
.each@http://lido.its1.lv/web/static/lib/jquery/jquery.js:383:49
Style/jQueryCSS@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/editing/Style.js:30:9
Style/this.fromNode@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/editing/Style.js:46:23
Style/this.current@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/editing/Style.js:125:23
Editor/this.currentStyle@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/module/Editor.js:127:52
eventHandler.modules.editor.currentStyle@http://lido.its1.lv/web_editor/static/src/js/summernote.js:1904:21
EventHandler/hToolbarAndPopoverUpdate/<@http://lido.its1.lv/web_editor/static/lib/summernote/src/js/EventHandler.js:214:25
```

Thanks for the work so far!

**Comment by Gorash** [comment]
Thanks for your feed back
I have merge a fix https://github.com/odoo/odoo/commit/50057c08aaf7817157962f44ecad5a69061fad99
