### ISSUE TITLE
[9.0] KeyError: sale.order.line.company_id

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9999]
Impacted versions:
- 9.0

Steps to reproduce:
1. get order data from amazon mws api
2. create sale order
- create vals

``` javascript
{
    'message_follower_ids': [
        [0, 0, {
            'res_model': 'sale.order',
            'subtype_ids': [(6, 0, [1])],
            'res_id': 4594,
            'partner_id': 3
        }]
    ],
    'latest_ship_date': u '2015-12-11T07:59:59Z',
    'order_line': [
        [0, 0, {
            'clisting_id': 18280,
            'fee': 0,
            'name': u "Men's Pockets Elastic Adjustable Drawstring Casual Pants",
            'product_uom': 1,
            'order_id': 4594,
            'price_unit': 14.99,
            'product_uom_qty': 1,
            'e_item_code': u '43866850826082',
            'product_id': 11401
        }]
    ],
    'picking_policy': u 'one',
    'team_id': 2,
    'shop_id': 2,
    'date_order': u '2015-12-10T03:21:27Z',
    'partner_id': 8131,
    'shipping_server_level': u 'Standard',
    'user_id': 1,
    'order_type': u 'StandardOrder',
    'company_id': 1,
    'state': 'draft',
    'latest_delivery_date': u '2016-01-22T07:59:59Z',
    'pricelist_id': 2,
    'project_id': 1,
    'e_id': u '111-0385535-8077063',
    'payment_term_id': 1,
    'partner_invoice_id': 8131,
    'fulfillment_channel': u 'MFN',
    'name': u '111-0385535-8077063',
    'partner_shipping_id': 8131,
    'payment_type': u 'Other'
}
```

Current behavior:

``` python
 - Traceback (most recent call last):
  File "/opt/odoo9/eking/eking_amazon/models/amazon.py", line 1022, in _download_orders
    order_obj.create(cr, uid, order_vals, context=context)
  File "/opt/odoo9/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo9/openerp/api.py", line 342, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo9/openerp/addons/sale/sale.py", line 222, in create
    result = super(SaleOrder, self).create(vals)
  File "/opt/odoo9/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/openerp/addons/mail/models/mail_thread.py", line 230, in create
    thread = super(MailThread, self).create(values)
  File "/opt/odoo9/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo9/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/openerp/api.py", line 478, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo9/openerp/models.py", line 4342, in _create
    recs.recompute()
  File "/opt/odoo9/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo9/openerp/models.py", line 5818, in recompute
    fs = self.env[field.model_name]._field_computed[field]
KeyError: sale.order.line.company_id
```

company_id is compute field, I don't know how to reproduct this problem or why happen
I don't change any sale.order or sale.order.line,just add some data field,and store data from amazon mws

**Comment by mart-e** [comment]
Hello,

It seems that your error comes from the module `eking_amazon` which is not standard.
Please check with the developer who made it or give us a way to reproduce the issue in standard.
Regards
